canonical/snapd

daemon/api_snaps.go
daemon/api_snaps_test.go
daemon/export_test.go
overlord/assertstate/assertstate.go
overlord/assertstate/assertstate_test.go
overlord/snapstate/snapstate.go

Update validation set assertions only when updating all snaps (i.e. snap names are not specified with `snap refresh` command). This is needed because if only specific snaps are requested, then refreshing all validation set assertions could result in a "broken" state where newer assertions required newer revisions of some snaps (but they were excluded from refresh).

o/assertstate, api: update validation set assertions only when updating all snaps

---

overlord/snapstate/backend_test.go
overlord/snapstate/booted_test.go
overlord/snapstate/export_test.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_prereq_test.go
overlord/snapstate/refreshhints.go
overlord/snapstate/refreshhints_test.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go

Updates a default provider when installing a snap if it's already installed but missing a required content attribute.

o/snapstate: update default provider if missing required content

---

.github/workflows/test.yaml
spread.yaml

As there are many images in ubuntu-os-cloud-devel project we need to
update the image to avoid pagination issue of spread
This change will fix issue trying to allocate image:
2021-09-22 19:58:26 Cannot allocate google:ubuntu-21.10-64: cannot find
any Google image matching "ubuntu-os-cloud-devel/ubuntu-2110" on project
"ubuntu-os-cloud-devel"
As the new impish image includes by default cgroups v2, I am removing the old image with groups v2 added manually. 
The image will be updated daily

tests: use our own image for ubuntu impish

---

.github/workflows/test.yaml

The idea is to start with a clean workspace in the self-hosted runner
The previous job could be left the workspace in a bad state as it is
happening when it adds a submodule.

tests: cleanup the job workspace as first step of the actions workflow

---

spread.yaml
tests/main/lxd-mount-units/task.yaml

Use core20 as base snap for focal system
The test is failing on focal with this error:
+ lxd.lxc exec ubuntu -- find /var/run/systemd/generator/ -name
container.conf
+ MATCH '/var/run/systemd/generator/snap-core18.*mount.d/container.conf'
/var/run/systemd/generator/snap-snapd-12883.mount.d/container.conf
/var/run/systemd/generator/snap-core20-1081.mount.d/container.conf
/var/run/systemd/generator/snap-lxd-21545.mount.d/container.conf

tests: fix lxd-mount-units test which is based on core20 in ubuntu focal system

---

tests/core/netplan/task.yaml

Skip i386 because core20 is not available for pc-i386 architecture
This is failing on beta validation:
+ snap install --dangerous netplan-snap-20.snap
error: cannot perform the following tasks:
- Ensure prerequisites for "netplan-snap" are available (cannot install
snap base "core20": no snap revision available as specified)

tests: fix netplan test on i386 architecture

---

cmd/libsnap-confine-private/cgroup-support-test.c

Clang 13.0 generates this warning:
```
libsnap-confine-private/cgroup-support-test.c:282:15: error: variable 'p' set but not used [-Werror,-Wunused-but-set-variable]
char *p SC_CLEANUP(sc_cleanup_string) = NULL;
^
1 error generated.
```

cmd/libsnap-confine-private: fix set but unused variable in the unit tests

---

cmd/snap-confine/snap-confine.apparmor.in

On some architectures, such as aarch64, we've seen the ld.so interpreter to be
named like lib-linux-aarch64.so.1. However, snap-confine's AppArmor profile
prevents that path from being loaded, thus breaking execution of snaps. The
following denial was observed on affected systems:
audit: type=1400 audit(1632477434.031:8902): apparmor="DENIED" operation="file_mmap"
namespace="root//lxd-happy-impish_<var-snap-lxd-common-lxd>"
profile="/snap/snapd/12886/usr/lib/snapd/snap-confine"
name="/usr/lib/aarch64-linux-gnu/ld-linux-aarch64.so.1"
pid=1101743 comm="snap-confine" requested_mask="m" denied_mask="m"
fsuid=1000000 ouid=1000000
Fixes: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1944004

cmd/snap-confine: update s-c apparmor profile to allow versioned ld.so

---

tests/main/security-device-cgroups/task.yaml

When both variants of the test run on the same host where the TAGS are sticky
due to systemd 247+, then any TAGS added due to the first variant will break the
assumptions of the second variant. Make sure that we check proper
TAGS/CURRENT_TAGS when verifying assumptions.

tests/main/security-device-cgroups: fix when both variants run on the same host

---

interfaces/apparmor/template.go

This does not leak any information since an app could always try to send dbus
messages and see what fails to perform the same inspection, but this helps
eliminate some messages when using i.e. dbus-run-session legitimately for some
applications.
See also the thread on https://forum.snapcraft.io/t/how-to-use-dbus-run-session-on-ubuntu-core/7077/3

interfaces/apparmor/template.go: allow inspection of dbus mediation level

---

interfaces/builtin/dsp.go

This is needed as per a recent customer ticket, see SF ticket #00319598 for
more details.

interfaces/dsp: add a usb rule to the ambarella flavor

---

tests/main/system-usernames-microk8s/task.yaml

This test is failing on uc20 for beta validation because the execution
is done even when TRUST_TEST_KEYS is false

tests: skip system-usernames-microk8s when TRUST_TEST_KEYS is false

---

gadget/install/install.go
gadget/install/params.go
overlord/devicestate/devicemgr.go
overlord/devicestate/devicestate_install_mode_test.go
overlord/devicestate/export_test.go
overlord/devicestate/handlers_install.go
secboot/encrypt.go
tests/lib/uc20-create-partitions/main.go

This branch uses a new `EncryptionType` in `DeviceManager.checkEncryption()` and `DeviceManager.checkFDEFeatures()`. 
This prepares for the "device-setup" feature that will not use cryptsetup but instead uses a device specific hook to configure crypto hardware.

devicestate: use EncryptionType

---

tests/nested/manual/core20-cloud-init-maas-signed-seed-data/task.yaml

The test tests/nested/manual/core20-cloud-init-maas-signed-seed-data is
failing trying to create the extra-snaps directory which is being
created while the test is prepared.
+ mkdir
/home/gopath/src/github.com/snapcore/snapd/tests/nested/manual/core20-cloud-init-maas-signed-seed-data/extra-snaps
mkdir: cannot create directory
‘/home/gopath/src/github.com/snapcore/snapd/tests/nested/manual/core20-cloud-init-maas-signed-seed-data/extra-snaps’:
File exists

tests: fix error trying to create the extra-snaps dir which already exists

---

overlord/ifacestate/export_test.go
overlord/ifacestate/ifacestate.go
overlord/ifacestate/ifacestate_test.go
overlord/snapstate/autorefresh_gating_test.go
tests/main/disconnect-undo/task.yaml

Ignore hook failures when doing auto-disconnect so they don't prevent a snap from being removed.
https://bugs.launchpad.net/snapd/+bug/1845880

o/ifacestate: don't fail remove if disconnect hook fails

---

interfaces/seccomp/template.go

Recent combinations of Go 1.17, glibc 2.34 and Linux 5.14 ended up triggering
pthread_create() code paths that try to use clone3() syscall when executing
snap-exec. Since snap-exec runs under the seccomp profile of the application,
make sure that clone3 is allowed in the default template. Also, applications may
trigger this code path themselves anyway.
The strace output when this fails looks like this:
```
mprotect(0x7f4ad3ea2000, 8388608, PROT_READ|PROT_WRITE) = 0
rt_sigprocmask(SIG_BLOCK, ~[], ~[KILL STOP RTMIN RT_1], 8) = 0
syscall_435(0x7ffc466b4c60, 0x58, 0x58b300, 0x8, 0x7f4ad46a1640, 0x7ffc466b4d4f) = -1 (errno 1)
rt_sigprocmask(SIG_SETMASK, ~[KILL STOP RTMIN RT_1], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
write(2, "runtime/cgo: ", 13runtime/cgo: )           = 13 …
```

interfaces/seccomp: add clone3 to default template

---

tests/main/degraded/task.yaml

Some mount units failing which are installed in the prebuilt image

tests: reset some mount units failing on ubuntu impish

---

osutil/disks/disks.go
osutil/disks/disks_linux.go
osutil/disks/disks_linux_test.go
osutil/disks/mockdisk.go
osutil/disks/mockdisk_test.go

These methods have been desired for a while and we finally need them to do some
operations for multi-volume gadget asset updates, so here they are.
This also refactors some things internally to make this easier/more foolproof.
Also add some basic support into MockDiskMapping for these methods as we will
need that too from other packages during tests.

osutil/disks: add Disk.KernelDevice{Node,Path} methods

---

overlord/snapstate/handlers.go
overlord/snapstate/snapstate_install_test.go

This PR prevents an install from hanging when its prerequisite has a duplicate install in the same change that fails. The following situation would trigger the bug: 
* `snap install A B` (where A depends on B)
* B's independent (i.e., not as a prerequisite) install fails
* A's installation starts and installs B as a prerequisite
* B's install checks for conflicts and fails, because the conflict checking code looks for a task affecting B that belongs to a change with tasks to be done (the previous install of B meets the criteria)
* The conflict error causes the prerequisite task to be retried after a timeout which causes the install be stuck in this loop, since the conflict is never "fixed"
One caveat: the check just skips without returning an error so A's install will proceed even though …

o/snapstate: prevent install hang if prereq install fails

---

osutil/disks/disks.go
osutil/disks/disks_linux.go
osutil/disks/disks_linux_test.go
osutil/disks/mockdisk.go
osutil/disks/mockdisk_test.go

Based on top of https://github.com/snapcore/snapd/pull/10856.
This was also a long standing TODO to more fully represent a partition on a
disk, so here this is too.
We also refactor the FindMatchingPartitionUUIDWith{Fs,Part}Label methods to use
a more generic searching function which returns the full Partition not just the
PartitionUUID. The more generic methods will be added to the Disk interface
shortly (in a future PR that is).

osutil/disks: add Partition struct and Disks.Partitions()

---

spread.yaml

This is possible due to the new change merged in spread to select the cpu to execute the tests.
Available options are:
Intel Xeon E5 (Sandy Bridge): "Intel Sandy Bridge" -> 2011
Intel Xeon E5 v2 (Ivy Bridge): "Intel Ivy Bridge" -> 2012
Intel Xeon E5 v3 (Haswell): "Intel Haswell" -> 2013
Intel Xeon E5 v4 (Broadwell): "Intel Broadwell" -> 2014
Intel Xeon (Skylake): "Intel Skylake" -> 2015
Intel Xeon (Cascade Lake): "Intel Cascade Lake" -> 2019

tests: use the latest cpu family for nested tests execution

---

desktop/notification/export_test.go
desktop/notification/fdo.go
desktop/notification/fdo_test.go
desktop/notification/gtk.go
desktop/notification/gtk_test.go
desktop/notification/manager.go
desktop/notification/manager_test.go
desktop/notification/notificationtest/gtk.go
desktop/notification/notify.go
usersession/agent/rest_api.go

Implement a simple gtk-based notification api backend and provie simple NotificationManager interface for both the new gtk backend and existing fdo implementation, as outlined by @jhenstridge here: https://forum.snapcraft.io/t/a-desktop-notifications-client-api-for-snapd/25063 ; based on old prototype from James (thank you!). 
A couple of high level remarks:
- one of the main ideas of the new approach is to use snap-name based notification ids that are internally remapped by fdoBackend to and from the IDs used by fdo notifications; gtk notifications are stateless on the client side so this is much simpler. This will let us avoid duplicate notifications about same snap.
- the existing fdo backend implements functions to cover aspects of the fdo that we are not aiming to use atm, so they …

desktop: implement gtk notification backend and provide minimal notification api

---

osutil/disks/disks.go
osutil/disks/disks_linux_test.go
osutil/disks/mockdisk.go
osutil/disks/mockdisk_test.go

These methods were already implemented for *disk, so expose them as part of the
interface so they can be directly tested.
Also, temporarily implement these methods for the MockDiskMapping using the
existing mappings that are provided with a TODO to switch over the
implementation to searching the static list when that static list is provided
by the test callers that need to mock this.
Finally notate in the doc-comments of
FindMatchingPartitionUUIDWith{Fs,Part}Label that these methods will be taken
out to pasture soon.

osutil/disks: add Disk.FindMatchingPartitionWith{Fs,Part}Label

---

cmd/snap/cmd_help_test.go
cmd/snap/cmd_run.go

Snap run help message does not indicate how to run a snap application. Improve
it by adding placeholders for snap.app and its arguments.
Fixes: https://bugs.launchpad.net/snapd/+bug/1944393

cmd/snap: improve snap run help message

---

osutil/disks/disks.go
osutil/disks/disks_darwin.go
osutil/disks/disks_linux.go
osutil/disks/disks_linux_test.go

RootMountPointsForPartition will be used from multi-volume gadget asset updates
where we need to identify the mount point for an arbitrary partition returned
by Disk.Partitions().
Based on top of https://github.com/snapcore/snapd/pull/10857, main commit to review is 5ccb29f6e9369cfaaab6cd1365e583cf56e838f4

osutil/disks: add RootMountPointsForPartition

---

osutil/disks/disks.go
osutil/disks/disks_darwin.go
osutil/disks/disks_linux.go
osutil/disks/disks_linux_test.go

Rename `RootMountPointsForPartition` -> `MountPointsForPartitionRoot` as suggested by @mardy, and expand it to support filtering by mount options since we will need to ensure we are only using rw mounts when actually performing gadget asset updates.
Also address some comments in https://github.com/snapcore/snapd/pull/10862 and https://github.com/snapcore/snapd/pull/10857.
Adding skip spread since nothing is using MountPointsForPartitionRoot right now so there is little regression risk here.

osutil/disks: support filtering by mount opts in MountPointsForPartitionRoot

---

overlord/snapstate/handlers.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_update_test.go

Use device context when installing or updating prerequisite snaps.

o/snapstate: use device ctx in prerequisite install/update

---

boot/debug.go
cmd/snap/cmd_debug_bootvars_test.go
overlord/devicestate/remodel.go
overlord/devicestate/remodel_test.go
overlord/managers_test.go
tests/nested/manual/core20-remodel/task.yaml

When the remodel is successful, update the bootloader environment with a new
recovery capable system.

overlord/devicestate: record recovery capable system on a successful remodel

---

interfaces/builtin/modem_manager.go
interfaces/builtin/modem_manager_test.go

Allow access to PCIe modems by using the modem-manager interfaces.

interfaces/modem-manager: add access to PCIe modems

---

daemon/api_sideload_n_try.go
daemon/api_sideload_n_try_test.go
daemon/api_snaps.go
daemon/api_snaps_test.go
overlord/devicestate/devicestate_bootconfig_test.go
overlord/devicestate/devicestate_gadget_test.go
overlord/devicestate/handlers_bootconfig.go
overlord/devicestate/handlers_gadget.go
overlord/ifacestate/ifacestate_test.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_link_test.go
overlord/snapstate/snapstate.go

This is https://github.com/snapcore/snapd/pull/10871/files for 2.52 
* daemon: introduce system-restart-immediate flag in the snaps APIs
this gets reflected on the Change
* overlord: make Changes respect system-restart-immediate
have all system restart requests that don't use Now already
use snapstate.RestartSystem which consults system-restrat-immediate
on the Change as set by daemon

many: support an API flag system-restart-immediate to make snap ops proceed immediately with system restarts (2.52)

---

cmd/snap-bootstrap/cmd_initramfs_mounts.go
cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
cmd/snap-bootstrap/export_test.go

The current snap-bootstrap has a race when mounting the seed
partition in `mountNonDataPartitionMatchingKernelDisk` on EFI
systems.
The code determines the partUUID of the disk that booted the
kernel by reading the EFI LoaderDevicePartUUID variable. However
there is no guarantee that this partition is available when
snap-bootstrap runs, the kernel may still enumerate the HW.
This can be observed on a fast NUC when booting from a USB
stick.
Note that the `the-tool.serice` already has a
"After=systemd-udev-settle.service" set but that is still
racy because any `udev settle` (or `udev trigger --settle`)
is racy, the only option is to poll for the part uuid to
appear.
This is a minimal commit to avoid too much churn in code. Let me
know if it's too hacky to avoid a bigger diff.
Thanks to …

snap-bootstrap: wait in `mountNonDataPartitionMatchingKernelDisk`

---

overlord/managers_test.go

When building on LP, the mock snap files generated with mksquashfs end up having
the same sha3-348 digest, despite forcing a 1s delay between consecutive snap
builds, what should have affected the internal file timestamps. As a workaround,
use a different content of mock files, such that the files must yield a
different digest.

overlord: fix generated snap-revision assertions in remodel unit tests

---

tests/main/interfaces-many-core-provided/task.yaml
tests/main/interfaces-many-snap-provided/task.yaml

The test was only limited to a list of specific Ubuntu version. The list was
never updated since 20.04 release, which proves that listing specific is not
very useful.

tests/main/interfaces-many: run both variants on all possible Ubuntu systems

---

tests/main/cgroup-devices-v1/task.yaml
tests/main/cgroup-freezer/task.yaml

Ubuntu 21.10 boots with unified hierarchy by default. Those tests cannot be
successfully executed on such systems.

tests/main: disable cgroup-devices-v1 and freezer tests on 21.10

---

overlord/snapstate/snapstate_update_test.go

Adds a test for the case where a version of snapd without the "update outdated prerequisite" code creates a "prerequisites" task but a new version executes it.

o/snapstate: test prereq update if started by old version

---

overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_update_test.go
overlord/snapstate/storehelpers.go

Support --ignore-validation flag when requesting refresh to a specific revision and it doesn't match the revision required by validation set.
Followup to #10760

o/snapstate: support ignore-validation flag when updating to a specific snap revision

---

tests/main/auto-refresh-gating-from-snap/task.yaml
tests/main/auto-refresh-gating-from-snap/test-snap-refresh-control-iface/meta/snap.yaml
tests/main/auto-refresh-gating-from-snap/test-snap-refresh-control-iface/proceed

Check that snap that doesn't have gate-auto-refresh hook can call `snapctl refresh --proceed`, and that it returns "no snaps are held by..." error.

tests: check that a snap that doesn't have gate-auto-refresh hook can call --proceed

---

spread.yaml
tests/lib/prepare.sh

Support setting experimental snapd features via EXPERIMENTAL_FEATURES environment variable, affecting all spread tests.
The idea is to use this with nightly test suite to run it with and without experimental.gate-auto-refresh-hook feature, e.g.
`EXPERIMENTAL_FEATURES=gate-auto-refresh-hook spread -debug google:ubuntu-core-18-64:tests/main/`

tests: support running all spread tests with experimental features

---

.github/workflows/test.yaml
run-checks

We are running the unit tests several times under different build flags, but every iteration destroys the data collected during the previous one. This PR wants to test whether combining the coverage results would have any benefit.
Edit: it turns out there's no benefit at all in the overall coverage numbers :-(, but these test runs are effectively covering different parts of the codebase, so I think we should still consider all of them:
|Build tag|# of tested files|Extra files
--- | --- | ---
| - |   900| - |
|faultinject|   900| osutil/faultinject.go |
|nosecboot|   897| cmd/snap-bootstrap/cmd_initramfs_mounts_nosecboot.go, gadget/install/install_dummy.go, secboot/encrypt_dummy.go, secboot/secboot_dummy.go |
|withbootassetstesting|   902|bootloader/assets/assetstesting.go, …

tests: merge coverage results

---

cmd/snap-confine/snap-confine.apparmor.in

Observed on an Impish s390x machine:
root@test-i:~# ls -lah /usr/lib/ld64.so.1
lrwxrwxrwx 1 root root 25 Sep  2 21:26 /usr/lib/ld64.so.1 -> s390x-linux-gnu/ld64.so.1
Which comes from the new libc6, and is different from what we expected on
previous releases, see for example Hirsute:
root@testing-h:~# ls -lah /usr/lib/ld64.so.1
lrwxrwxrwx 1 root root 26 Mar 31  2021 /usr/lib/ld64.so.1 -> s390x-linux-gnu/ld-2.33.so
The latter matched the existing rule, while the former does not. The new rule
allows both.
Also note that ppc64le had the same transition with the same filepaths, so this PR
will unbreak impish on that platform as well as s390x.

cmd/snap-confine/snap-confine.apparmor.in: update ld rule for s390x impish

---

daemon/ucrednet.go
tests/main/snapd-sigterm/task.yaml

For some reason, the old code was causing snapd to hang when asked to
terminate if there were still some clients connected: the connection
would not move to the "idle" state.
This was found while investigating LP#1946656, and as a matter of facts
it fixes it. While debugging, an inspection of snapd threads while in
hanging state revealed that one thread was stuck in
daemon.(*ucrednetConn).Read
and it was verified that removing the Accept function completely would
resolve the issue (though also considerably changing snapd behaviour).
This changeset also appears to fix the issue, while not changing snapd
behaviour.
The problem with the old code does not lie in duplicating the file
descriptor (which is done by calling UnixConn.File()), but rather in the
apparently innocuous call to …

daemon: use the syscall connection to get the socket credentials

---

daemon/api_validate.go
daemon/api_validate_test.go
daemon/export_api_validate_test.go
tests/main/snap-validate-basic/task.yaml

Allow enabling enforcing mode for a validation set with `snap validate --enforce ...`.
The existing spread test is only updated not to fail. Actual enforcing will be spread-tested separately once all the bits land.

daemon: allow enabling enforce mode

---

bootloader/export_test.go
cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
osutil/disks/mockdisk.go
osutil/disks/mockdisk_test.go
secboot/secboot_sb_test.go

This will be necessary for more complicated test cases in the gadget package,
so time to rip this band-aid and get rid of the old methods.
I did consider having the new member "Structure" exist alongside the existing map
fields, but it made the implementation clunky and difficult to read, so I opted instead
to just rip the band-aid off and totally remove these methods instead.

osutil/disks, many: switch to defining Partitions directly for MockDiskMapping

---

interfaces/builtin/hardware_observe.go

This is needed for a customer request, see ticket 00320804 for full details.

interfaces/builtin/hardware-observer: add /proc/bus/input/devices too

---

tests/main/snapd-sigterm/task.yaml

Since we don't stop the socket (stopping it could always make the test
pass, even if the code regresses and the bug reappears), systemd might
restart the snapd service. Make the check a bit more robust, as it was
seen that on some machine this test fails and the unit is found to be in
the "activating" state already.

tests/snapd-sigterm: be more robust against service restart

---

overlord/hookstate/ctlcmd/refresh.go
overlord/hookstate/ctlcmd/refresh_test.go
overlord/hookstate/hooks.go
overlord/hookstate/hooks_test.go
overlord/snapstate/autorefresh_gating.go
overlord/snapstate/autorefresh_gating_test.go
overlord/snapstate/snapstate_remove_test.go
overlord/snapstate/snapstate_update_test.go
tests/main/auto-refresh-gating/task.yaml

Print remaining hold time after `snapctl --hold`; this time is the minimum value of hold times of all snaps held by the gating snap that calls snapctl command. In the future this may get extended to allow snaps to ask for 1 extra hour.
The output is go-formatted duration with the idea of maybe adding a flag (e.g. --print-seconds) to request hold time in seconds.

o/snapstate, hookstate: print remaining hold time on snapctl --hold

---

interfaces/builtin/u2f_devices.go
interfaces/builtin/u2f_devices_test.go

This patch adds the Nitrokey 3 to the list of U2F devices that is used to generate the UDEV rules.

interfaces/u2f-devices: add Nitrokey 3

---

tests/lib/pkgdb.sh

Strace provided by strace-static is too old and segfaults on Sid.

tests/lib/pkgdb: install strace on Debian 11 and Sid

---

HACKING.md

HACKING.md: 
Push up the minimum Go version to 1.13 and assume Go
module support. Update the instructions to work on the current version
of snapd and Go. Any person checking out an older version will get the
older version of HACKING.md, which will provide matching instructions.
Add instructions for cross-compiling.
Signed-off-by: Fred Lotter <fred.lotter@canonical.com>

docs: update HACKING.md instructions for snapd 2.52 and later

---

build-aux/snap/snapcraft.yaml

Currently snapd snap can only be built correctly, when the ./debian symlink points to packaging that matches the current build-base (at the moment that is ubuntu-16.04). Thus to allow building classic .deb and snapd snap on any ubuntu release in a row, the snapcraft.yaml must ensure that correct debian packaging is used during part built time.
With this change:
$ ./generate-packaging-dir
$ dpkg-buildpackage -b
$ snapcraft --use-provider lxd
can be performed on any ubuntu release, and result in creating correct .deb for the host release and create a correct universal snap.
CC: @bboozzoo @anonymouse64 @alexmurray

build-aux: ensure that debian packaging matches build-base

---

osutil/disks/blockdev.go
osutil/disks/disks.go
osutil/disks/disks_linux.go
osutil/disks/disks_linux_test.go
osutil/disks/mockdisk.go

Split off the LastUsableByte function into two methods, SizeInBytes and 
UsableSectorsEnd. The SizeInBytes function returns the most basic, commonly
understood size of a disk, including all regions, even those that are not 
usable by user partitions, etc.
The UsableSectorsEnd method however now essentially returns the last sector of
the disk that cannot be used, such that a partition which is specified as 
occupying [start, end) at the end of the disk can be calculated easily with
this method. 
This also refactors some of the tests to be more clear what they are testing
and test related methods in the same test.

osutil/disks: re-org methods for end of usable region, size information

---

tests/main/interfaces-udisks2/task.yaml

This test keeps failing when it tires to mount /dev/loop200. Maybe
we run out of loop devices?

tests: disable flaky "interfaces-udisks2" on ubuntu-18.04-32

---

tests/main/lxd/task.yaml

The nested lxd test is currently failing on 21.04 and 21.10 when
it tries to install snapd inside the inner LXD. This very much
looks like an LXD bug and it's reported as
https://github.com/lxc/lxd/issues/9447
This commit comments out the nested testing to ensure we can
land PRs again.

tests: disable nested lxd snapd testing

---

cmd/snap/cmd_disconnect.go
cmd/snap/cmd_disconnect_test.go
cmd/snap/complete.go
cmd/snap/interfaces_common.go
cmd/snap/interfaces_common_test.go
tests/main/snap-disconnect/task.yaml

snap disconnect's parsing would output an error message "invalid
value: (want snap:name or snap)" even though invoking it with just
the snap resulted in an error with a conflicting message.
This commit fixes the parsing for snap disconnect so it's done in a
single place and returns a single error message.
https://bugs.launchpad.net/snapd/+bug/1943987

cmd/snap: improve snap disconnect arg parsing and err msg

---

tests/main/preseed-lxd/task.yaml

There were some failures in spread because /dev/nbd0p1 does not
appear. To ensure it's not a timing bug incrase the time from 5s
to 30s.

tests: give nbd0 more time to show up in preseed-lxd

---

overlord/snapstate/handlers.go

When debugging the test failure in LP:1949506 I ran into the issue
that the test fails with:
```
2021-10-27T14:53:31.6448594Z Oct 27 14:53:29 oct271439-116856 snapd[9755]: snapmgr.go:303: cannot read snap info of snap "disabled-svcs-kept" at revision x4: cannot find installed snap "disabled-svcs-kept" at revision x4: missing file /snap/disabled-svcs-kept/x4/meta/snap.yaml
```
but there is no indication that the mount failed. Yet the mount
for "x4" is not available and the exiting debug message yield not
enough data to see what happend. The mount task was there but it
is unclear if maybe some error handling in there is wrong or if
it was mounted to the wrong place etc. Hence this new debug line.

snapstate: add debug message where a snap is mounted

---

cmd/snap-confine/udev-support.c
tests/main/security-dev-input-event-denied/task.yaml

This is https://github.com/snapcore/snapd/pull/10968 for 2.53

 cmd/snap-confine: lazy set up of device cgroup, only when devices were assigned (2.53)

---

tests/lib/preseed.sh
tests/main/preseed-lxd/task.yaml

The nbd0 mount for the preseed test sometimes does not show
up, see LP:#1949513
```
...
2021-11-01T15:38:19.3281867Z + modprobe nbd
2021-11-01T15:38:19.3282497Z ++ command -v qemu-nbd
2021-11-01T15:38:19.3284212Z + systemd-run --system --service-type=forking --unit=qemu-nbd-preseed.service /usr/bin/qemu-nbd --fork -c /dev/nbd0 /home/gopath/src/github.com/snapcore/snapd/tests/main/preseed-reset/cloudimg.img
2021-11-01T15:38:19.3285956Z Running as unit: qemu-nbd-preseed.service
2021-11-01T15:38:19.3286886Z + retry -n 15 --wait 1 test -e /dev/nbd0p1
2021-11-01T15:38:19.3287721Z retry: command test -e /dev/nbd0p1 failed with code 1
2021-11-01T15:38:19.3288730Z retry: next attempt in 1.0 second(s) (attempt 1 of 15)
2021-11-01T15:38:19.3289674Z retry: command test -e /dev/nbd0p1 failed with …
```

tests: increase timeout/add debug around nbd0 mounting

---

tests/main/interfaces-udisks2/task.yaml

The test fails regularly with:
```
2021-11-02T20:35:10.3649857Z ++ losetup -j /home/gopath/src/github.com/snapcore/snapd/tests/main/interfaces-udisks2/dev0-fake0
2021-11-02T20:35:10.3652953Z + device=/dev/loop200
2021-11-02T20:35:10.3656188Z + retry -n 3 --wait 1 sh -c 'test-snapd-udisks2.udisksctl mount -b "/dev/loop200" -t ext4 | MATCH '\''Mounted /dev/'\'''
2021-11-02T20:35:10.3658850Z Error looking up object for device /dev/loop200
2021-11-02T20:35:10.3660405Z grep error: pattern not found, got:
2021-11-02T20:35:10.3661382Z
2021-11-02T20:35:10.3662638Z Error looking up object for device /dev/loop200
2021-11-02T20:35:10.3664163Z grep error: pattern not found, got:
2021-11-02T20:35:10.3665133Z
2021-11-02T20:35:10.3666746Z Error looking up object for device /dev/loop200 …
```

tests: give interfaces-udisks2 more time for the loop device to appear

---

spread.yaml

Rigt now we only show `journalctl -e` in the main spread suite.
However during debugging of LP:#1949511 it turned out that this
is not ideal because there was a failure like:
```
2021-11-02T10:53:19.0115499Z ##[error]2021-11-02 10:53:19 Error executing google:ubuntu-core-18-64:tests/core/snapd-refresh-vs-services-reboots (nov021031-469292) :
2021-11-02T10:53:19.0144305Z -----
2021-11-02T10:53:19.0145250Z + os.query is-pc-amd64
2021-11-02T10:53:19.0146770Z + '[' 0 = 0 ']'
2021-11-02T10:53:19.0148966Z + snap pack test-snapd-svc-flip-flop --filename=app.snap
2021-11-02T10:53:19.0150087Z built: app.snap
2021-11-02T10:53:19.0151186Z + snap install --dangerous app.snap
2021-11-02T10:53:19.0152138Z error: cannot perform the following tasks:
2021-11-02T10:53:19.0160635Z - Start snap …
```

spread.yaml: show `journalctl -e` for all suites on debug

---

overlord/hookstate/ctlcmd/fde_setup_test.go
overlord/hookstate/ctlcmd/is_connected_test.go
overlord/hookstate/ctlcmd/refresh.go
overlord/hookstate/ctlcmd/refresh_test.go

Print cohort key with `snapctl refresh --pending` as long as snap-refresh-control interface is connected.

o/hookstate: print cohort with snapctl refresh --pending

---

tests/lib/preseed.sh
tests/main/preseed-lxd/task.yaml

The pressed-* tests are flaky (see LP: 1949513). To get more
insights, add more debug to see why the device does not show up.

tests: add more debug around qemu-nbd

---

sandbox/cgroup/freezer.go
sandbox/cgroup/freezer_test.go

When freezing and thawing cgroups related to a snap, the code would incorrectly
try to operate on cgroups related to mounts, socket, slices if they had the
snap.<name>.<app> prefix.

sandbox/cgroup: freeze and thaw cgroups related to services and scopes only

---

tests/lib/tools/snapd-state

There was a failure in the snapd tests:
```
...
2021-11-02T16:55:11.8447301Z ++ /home/gopath/src/github.com/snapcore/snapd/tests/lib/tools/snapd-state wait-for-autorefresh 19
2021-11-02T16:55:11.8449962Z /home/gopath/src/github.com/snapcore/snapd/tests/lib/tools/snapd-state: line 92: [: : integer expression expected
...
```
and then a subsequent failure. Looking at snapd-state it seems like
the above failure will happen if _wait_autorefresh() times out. In
this case CHANGE_ID is never set and the line:
```
if [ "$LAST_CHANGE_ID" -eq "$CHANGE_ID" ]; then
```
errors because CHANGE_ID is never initialized and empty.
This commit initializes it which prevents this error.

tests: initialize CHANGE_ID in _wait_autorefresh

---

tests/core/netplan/task.yaml

The netplan test is a bit flaky (see LP:1949708 for details). To
get a better understanding what is going this commit adds a
--debug to netplan apply to see what it is about to do and also
a `netplan get` before the apply so that even if netplan apply
cuts the network connections early we still see what is going on.

tests: add `--debug` to netplan apply

---

overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go

This shares code between verify*Tasks, also switches them to take into account the snap type directly to reflect what doInstall is expected to do.

o/snapstate: test relink remodel helpers do a proper subset of doInstall and rework the verify*Tasks helpers

---

overlord/snapstate/autorefresh_gating_test.go
overlord/snapstate/refreshhints.go
overlord/snapstate/refreshhints_test.go
overlord/snapstate/snapstate_remove_test.go

Do not prune refresh-candidates if gate-auto-refresh-hook feature is not enabled. This makes it symmetrical with auto-refresh logic which only overwrites refresh-candidates state entry if that feature is enabled.  This is a workaround for a case where snapd from edge was used and  created the entry using "old" array format; the format was later 
changed to a  map, but if in the meantime the feature got disabled, the new format  would never be written to the state by auto-refresh, so pruning code  would always fail trying to unmarshal refresh-candidates in the old format.
Related: https://forum.snapcraft.io/t/cannot-r-emove-snap-json-cannot-unmarshal-array-into-go-value-of-type-map-string-snapstate-refreshcandidate/27276

o/snapstate: do not prune refresh-candidates if gate-auto-refresh-hook feature is not enabled

---

HACKING.md

HACKING.md: Suggest to the user to use Ubuntu 18.04 LTS or later for Snapd development.
Signed-off-by: Fred Lotter <fred.lotter@canonical.com>

docs: add run-checks dependency install instruction

---

overlord/devicestate/devicestate_test.go
timeutil/synchronized.go

The new timeutilIs.NTPSynchronized is not correctly dealing with systems without dbus (like the sbuild environment). So two fixes here to make it more robust.

timeutil,deviceutil: fix unit tests on systems without dbus or without ntp-sync

---

desktop/notification/fdo.go
desktop/notification/gtk.go
desktop/notification/manager.go
usersession/agent/rest_api.go
usersession/agent/session_agent.go
usersession/agent/session_agent_test.go

Observe notifications and handle notification closing and idle duration - usersession agent needs to stay alive till we have any notifications that need to be monitored for close signal. This is only needed for fdo backend which needs to update its internal mappings. The notification manager instance is now created on agent startup and kept around for its lifetime.
Also fixes reading from the channel which would sometimes panic with segmentation violation, depending on the timing (whether ObserveNotifications loop breaks due to ctx.Done() or final channel receive.
This is followup to the recently landed notifications PR and implementation of the plan outlined here: https://forum.snapcraft.io/t/a-desktop-notifications-client-api-for-snapd/25063

desktop, usersession: observe notifications

---

overlord/state/taskrunner_test.go

Add a unit test for taskrunner that uses a task sequence similar to that will
happen during a paralle kernel & base refresh.

overlord/state: add a unit test for a kernel+base refresh like sequence

---

data/selinux/snappy.te

Snapd needs to poke the org.freedesktop.timedate1 service to find out whether
NTP was synchronized. That DBus API is provide by systemd-timesyncd (most
systems) or timedatex (CentOS mostly). The SELinux policy does not currently
allow talking to either service, so upon startup snapd will enter a deadlock
after getting blocked in the timeutil.IsNTPSynchronized() waiting for dbus
messages, while this is called in a code path that acquired state.Lock(), thus
blocking all Ensure() calls and interaction through the snapd socket.
Extend the SELinux policy to allow dbus communication to either timedate1
provider service.

data/selinux: update the policy to allow snapd to talk to org.freedesktop.timedate1

---

cmd/snap-seccomp/syscalls/syscalls.go
tests/main/snap-seccomp-syscalls/task.yaml

Update the list of syscalls, to match the latest libseccomp commit:
seccomp/libseccomp@abad8a8

cmd/snap-seccomp/syscalls: update syscalls to match libseccomp abad8a8f4

---

tests/main/auto-refresh/task.yaml
tests/main/snapd-state/task.yaml

The auto-refresh test is now flaky because not all images are
ntp synced in GCE. See https://bugs.launchpad.net/snapd/+bug/1949886
This commit adds some debug for this.

tests: add ntp related debug around "auto-refresh" test

---

interfaces/builtin/network_manager_observe.go

Dart applications use the ObjectManager.GetManagedObjects() DBus interface
method to query properties from NetworkManager so update this interface to
provide access to that, plus ensure they can also receive the
PropertiesChanged signal from NetworkManager objects as well.
https://forum.snapcraft.io/t/request-auto-connect-network-manager-for-cybear-jinni-app-again/26520

interfaces/network-manager-observe: Update for libnm / dart clients

---

.github/workflows/test.yaml
tests/lib/tools/log-parser

These improvements include:
. new setup objects used to include the lines that come before the spread log starts
. save the spread log in the test workflow
. avoid parting string in log
. exit with error when the spread has not the expected format

tests: some improvements for the spread log parser

---

tests/lib/prepare.sh

There are a bunch of failures with the memory limits in e.g.
https://github.com/snapcore/snapd/pull/11014
To avoid blocking landings this commit partially reverts
memory limits.

tests: (partially) revert the memory limits PR#r10241

---

overlord/snapstate/flags.go
overlord/snapstate/handlers.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate_remove_test.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go

Maintain revision -> RevertStatus map in snapstate to mark revisions that shouldn't be blocked by Revert on future refreshes. Revert() function accepts RevertStatus in Flags to support this behavior. RevertStatus is an enum for future expansion (there is already one other case planned related to kernel reverts).
Revisions are pruned from SnapState.RevertStatus map when a snap revision is discarded, or doLinkSnap updates to that revision.

o/snapstate: maintain a RevertStatus map in SnapState

---

gadget/update.go
gadget/update_test.go
overlord/devicestate/devicestate_gadget_test.go
overlord/devicestate/devicestate_remodel_test.go
overlord/devicestate/export_test.go
overlord/devicestate/handlers_gadget.go

This will be needed in order to implement multi-volume updates, currently it is
ignored though.
Since there is no behavior change for different models currently, no additional
tests are added, but when the behavior is different we will add test cases with
different models.

gadget, many: add model param to Update()

---

osutil/disks/disks_darwin.go
osutil/disks/disks_linux.go
osutil/disks/disks_linux_test.go
osutil/disks/mockdisk.go
osutil/disks/mockdisk_test.go

This will be used when we have /dev/sda1 for example and want to get a Disk of
/dev/sda. Eventually this should be usable too when we need to track back from
a mapper device as well, but for now this is left out to be simpler and quicker
to mock and use in tests.
This also in effect removes the currently entirely unused and unclear use-case
around getting a Disk() for a non-physical mapper volume device node, where the
backing device of the mapper device is not a physical disk. These cases 
probably exist in real life on systems, but we do not need to concern ourselves
with them for now and it is becoming ever more clear that the disks package is
about real physical disks at the end of the day, so supporting these 
non-physical disks is out of scope of these functions.
Originally, based …

osutil/disks: add DiskFromPartitionDeviceNode 

---

.github/workflows/test.yaml

It seems that some recent github runs did not fail although no tests were run.
The only reasonable explanation being either broken action, or missing pipefail
that hid spread's non-0 exit status.

github: enable pipefail when running spread

---

interfaces/apparmor/template.go

Such as the core20 and newer base snaps for example.
Thanks to @xnox for finding this issue.
Not really sure if this needs security review, on the off chance it does though I added the tag hopefully it is quick enough to review :-)

interfaces/apparmor/template.go: allow udevadm from merged usr systems

---

tests/main/snap-advise-command/task.yaml

When the store is overloaded it will sent 403 from the
```
https://api.snapcraft.io/api/v1/snaps/names?confinement=strict%2Cclassic
```
endpoint. This causes our `snap-advise-command` test to fail but
we really should handle this gracefully instead.

tests: skip `snap advise-command` test if the store is overloaded

---

overlord/snapstate/snapstate_install_test.go

Removes a few repeated assertions in the install tests.

o/snapstate: remove repeated test assertions

---

interfaces/builtin/timezone_control.go

Using a snap with the timezone-control interface connected does not allow the ListTimezones DBus call, so the app can not determine what time-zones are supported by the host system:
```
$ snap run --shell geoip-lookup.geoip
$ timedatectl list-timezones
Failed to request list of time zones: Access denied
$ dbus-send --system --dest=org.freedesktop.timedate1 --type=method_call --print-reply /org/freedesktop/timedate1 org.freedesktop.timedate1.ListTimezones
Error org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.46" (uid=1000 pid=11034 comm="dbus-send --system --dest=org.freedesktop.timedate" label="snap.geoip-lookup.geoip (enforce)") interface="org.freedesktop.timedate1" …
```

interfaces: timezone-control, add permission for ListTimezones DBus call

---

overlord/snapstate/handlers.go
overlord/snapstate/handlers_copy_test.go

If the "copy-snap-data" task fails to read the snap data, an error is
logged but is not causing the task to fail. See for example these logs
(from `journald -xe`, occurring on [LP#1949089](https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1949089)):
```
Nov 12 06:08:50 nov120556-302222 systemd[1]: Reloading.
Nov 12 06:08:50 nov120556-302222 systemd[1]: Unmounting Mount unit for disabled-svcs-kept, revision x2...
-- Subject: Unit snap-disabled\x2dsvcs\x2dkept-x2.mount has begun shutting down
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit snap-disabled\x2dsvcs\x2dkept-x2.mount has begun shutting down.
Nov 12 06:08:50 nov120556-302222 systemd-udevd[663]: Network interface NamePolicy= disabled on kernel command line, ignoring.
Nov 12 06:08:50 nov120556-302222 …
```

o/snapstate/handlers: propagate read errors on "copy-snap-data"

---

interfaces/builtin/time_control.go
interfaces/builtin/time_control_test.go

Allow `/dev/pps[0-9]*` access for time-control interface
Signed-off-by: Ondrej Kubik <ondrej.kubik@canonical.com>

interfaces/builtin/time-control: allow pps access

---

cmd/libsnap-confine-private/device-cgroup-support.c
tests/main/security-device-cgroups-strict-enforced/task.yaml

With device cgroup v1, when reusing the cgroup (i.e. opening with
SC_DEVICE_CGROUP_FROM_EXISTING flag), we should not deny all devices, as this
will negatively affect the processes that are in the group.
This code path was executed by snap-device-helper, so it is possible that when
processing of real events from device changes the group could have become
broken.

cmd/libsnap-confine-private: do not deny all devices when reusing the device cgroup

---

gadget/gadget.go
gadget/gadget_test.go

This will also be helpful in identifying which disk is which when it comes time
to finally do that.
Needs Samuele review just to confirm the field names here.

gadget: include size + sector-size in DiskVolumeDeviceTraits

---

interfaces/builtin/block_devices.go

To allow blkid to visit block_devices attributes via low level probing, so that
we can get information like partition table type or PART_ENTRY_UUID
which could be useful for script based snap without parsing
/run/udev/data/b{major}:{minor}.

interfaces/builtin/block_devices: allow blkid to print block device attributes

---

overlord/snapstate/handlers.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_update_test.go

The undoLinkSnap handlers puts the candidate revision back in its
previous position, if the install fails. However, the install may
fail after the discard-snap tasks run which means that the old
candidate index may be outdated which could result in the wrong
Sequence being remade or even a panic. This change accounts for the
number of discarded revisions when undoing the install.

o/snapstate: account for deleted revs when undoing install

---

tests/main/lxd/task.yaml

The `lxd` test is currently failing in 21.10 with:
```
...
2021-11-11T07:41:21.3458885Z + lxd.lxc exec my-nesting-ubuntu -- snap set system experimental.refresh-app-awareness=false
2021-11-11T07:41:21.3460916Z + echo 'Ensure we can use snapd inside lxd'
2021-11-11T07:41:21.3461565Z Ensure we can use snapd inside lxd
2021-11-11T07:41:21.3488625Z + lxd.lxc exec my-ubuntu snap install test-snapd-sh
2021-11-11T07:41:21.3489599Z error: cannot perform the following tasks:
2021-11-11T07:41:21.3491133Z - Setup snap "core" (11993) security profiles (cannot run udev triggers: exit status 1
2021-11-11T07:41:21.3491824Z udev output:
2021-11-11T07:41:21.3492889Z LNXSYSTM:00: Failed to write 'change' to '/sys/devices/LNXSYSTM:00/uevent': Permission denied
...
```
until this is fixed we need to disable …

tests: the `lxd` test is failing right now on 21.10

---

build-aux/snap/snapcraft.yaml

NOTE! this Pull request is for master-riscv64 branch
1) Use newer golang snap on riscv64
2) Set source location to the master branch
3) Set build-base core20
4) Replace fontconfig builds with bin/true symlinks (ideally snapd on riscv64 should stop calling those)

build-aux: fork snapcraft.yaml for riscv64

---

gadget/install/export_secboot_test.go
gadget/install/install.go
gadget/install/install_test.go

This is to better support being able to mock things via the MockDevice... family of functions.
Eventually more of the gadget functions like gadget.ParentDiskFromMountSource can be 
eliminated too, but for now just this little tidbit which should be small and bite sized to review.

gadget/install: use disks functions to implement deviceFromRole, also rename

---

tests/main/interfaces-time-control/task.yaml

NTP syncronization is not done after the date is changed using the date
command. The issue happens even when the syncronization is manually forced.
The error displayed in the journal is the following:
synchronized.go:72: DEBUG: NTPSynchronized state returned by timedate1:
false
In order to reproduce the error and check the fix, run:
spread-debug -order -single-worker -debug
google:ubuntu-20.04-64:tests/main/interfaces-time-control
google:ubuntu-20.04-64:tests/main/snapd-stat

tests: skip the test-snapd-timedate-control-consumer.date to avoid NTP sync error

---

daemon/api_validate.go
daemon/api_validate_test.go
daemon/export_api_validate_test.go
overlord/assertstate/assertstate.go
overlord/assertstate/assertstate_test.go
overlord/assertstate/export_test.go
overlord/assertstate/validation_set_tracking.go
overlord/assertstate/validation_set_tracking_test.go

Move functions that set enforcing/monitoring from api to assertstate. Save current validation sets to the history on enforce/monitor/forget.
The affected api tests became more lightweight since most of the logic was already tested by assertstate tests.

o/assertstate, api: move enforcing/monitoring from api to assertstate, save history

---

tests/main/auto-refresh-gating/task.yaml

auto-refresh-gating spread test occasionally fails (https://bugs.launchpad.net/snapd/+bug/1950994); add more debug to help understand why.

tests: print extra debug on auto-refresh-gating test failure

---

packaging/ubuntu-16.04/snapd.postrm

We do not want to risk failing the whole script (and therefore leaving
the user's system in a dirty state) if removing the snap directories
fails.
This has happened in real life (see the bug report linked below) and,
although the mechanisms to reproduce the issue are not clear, this fixes
the symptoms.
Fixes: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1950634

packaging: make postrm script robust against `rm` failures

---

README.md

Update README to point at https://bugs.launchpad.net/snapd/+filebug (not snappy project).

README.md: point at bugs.launchpad.net/snapd instead of snappy project

---

tests/main/security-device-cgroups-strict-enforced/task.yaml

Extend the comments describing what happens in the test.

tests/main/security-device-cgroups-strict-enforced: extend the comments

---

gadget/gadget.go
gadget/gadget_test.go

This should also be there to verify that disks are the same.

gadget/gadget.go: include disk schema in the disk device volume traits too

---

spread.yaml

This is because images create with ubuntu-image 2.0 are displaying "No
space left on device" error

tests: use ubuntu-image 1.11 from stable channel 

---

data/env/Makefile
data/env/snapd.fish.in
packaging/fedora/snapd.spec
packaging/opensuse/snapd.spec

Profile profile setup for fish shell, which does not load /etc/profile.d.
Fixes: https://bugs.launchpad.net/snapd/+bug/1951145

data/env: provide profile setup for fish shell

---

spread.yaml

This change contains 2 things:
1. exit in case no debug each is required, and move out the code from
the if
2. Keep as the last step the line to show which tests were executed before.
This is needed to send to mongo db that info that will help to recognize
which test is making fail other tests

tests: reorganize the debug-each on the spread.yaml

---

tests/core/snapd-refresh-vs-services-reboots/task.yaml
tests/main/services-disabled-kept-happy/task.yaml
tests/main/snap-disconnect/task.yaml

This reverts commit 4aa662960544c1a5ddd33ab05ba4a087919c6a38.
Once https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1949089 is fixed we can re-enable this.

tests: Revert "tests: disable flaky uc18 tests until systemd is fixed"

---

gadget/export_test.go
gadget/gadget_test.go
gadget/gadgettest/gadgettest.go
gadget/install/partition.go
gadget/install/partition_test.go
gadget/layout.go
gadget/ondisk.go
gadget/ondisk_test.go
gadget/update.go
tests/main/uc20-create-partitions-reinstall/task.yaml
tests/main/uc20-create-partitions/task.yaml

This enables us to write much simpler tests for complicated disk setups, which
will be critical for supporting multiple volume update situations, as otherwise
we would be left writing extremely complicated sfdisk and lsblk mock commands
which is no fun.
This also refactors the calculation of the size of partitions to use the more
natural and specific field "UsableSectorsEnd" which makes the code more 
readable and clear about what is going on without using the Size field, which
isn't quite what we want for the partition size calculation of expanded 
partitions.
Also delete the short-lived MockLsblkCommand in the gadgettest package, its
utility is no more.
Based on top of:

gadget: replace ondisk implementation with disks package, refactor part calcs

---

interfaces/builtin/dsp.go
interfaces/builtin/dsp_test.go

There are two commits that just update ambarella flavor to add proc files to support their new features, and meanwhile rectify some permissions of proc files.

interfaces/builtin/dsp: update proc files for ambarella flavor

---

interfaces/builtin/mpris.go

Allow apps connected to mpris slot (e.g. of spotify snap) to monitor PropertiesChanged signal of /org/mpris/MediaPlayer2.
This should address the request from the forum: https://forum.snapcraft.io/t/mpris-interface-snap-unable-to-receive-propertieschanged-events/26869
I've verified this signal with a custom-built snap that includes dbus-monitor & spotify snap.

interfaces: allow receiving PropertiesChanged on the mpris plug

---

tests/main/snap-disconnect/task.yaml

The test pass in google backend, it was created 5 years ago and the
system ubuntu-core-16-64 was skipped.

tests: run snap-disconnect on uc16

---

overlord/servicestate/servicestate_test.go
systemd/systemd.go
systemd/systemd_test.go

systemd/systemd.go: provides systemctl Status() support for socket,
mount, service and timer units.
Target units in systemd provides a logical grouping of dependencies
associated with a high level capability (such as hibernate, sleep, reboot
and ctrl-alt-del). In order to manage these capabilities on a platform, 
we need the ability to perform unit operations on systemd targets using 
the existing systemctl interface in snapd.
The end goal is to allow snapd to control the platform behaviour by
exposing configuration items for some of these capabilities, such as
allowing ctrl-alt-del behaviour to be changed.
snap set system system.ctrl-alt-del="none"
Most systemctl functionality is generic in snapd and will already work
with systemd target units. The Status() function parsing the systemctl …

systemd: add support for .target units

---

daemon/api.go
daemon/api_base_test.go
daemon/api_sideload_n_try.go
daemon/api_sideload_n_try_test.go
daemon/api_snaps.go
daemon/api_test.go
daemon/export_test.go

The multipart stdlib writes formdata file parts (above a limit) to
/tmp and that could exceed the available space on devices using tmpfs.
The files would then be copied from /tmp to /var/lib/snapd/snaps.
This change adds a custom form reader that reads non-file parts into
memory and writes file parts directly to /var/lib/snapd/snaps.
Note: This also effectively reduces the memory limit because the library added
10MB to user passed limit. Since this change doesn't try to keep the file parts
in memory, I think the 1MB limit for non-file parts is more than enough. 
https://bugs.launchpad.net/snapd/+bug/1950190

daemon: write formdata file parts to snaps dir

---

tests/main/snapd-reexec-snapd-snap/task.yaml

The test has had a recent failure
(https://github.com/snapcore/snapd/runs/4287754619), which does not seem
easy to reproduce. Add a few debugging info, in case it happens again.
Please let me know if you have ideas of more debugging info to print.

tests/main/snapd-reexec-snapd-snap: improve debugging

---

cmd/libsnap-confine-private/device-cgroup-support.c
tests/main/security-device-cgroups-helper/task.yaml
tests/main/security-device-cgroups-helper/test-strict-cgroup-helper/bin/sh
tests/main/security-device-cgroups-helper/test-strict-cgroup-helper/meta/snap.yaml

Split attaching the BPF filtering program to own cgroup, such that the process
of setting up the map, loading device acecsses is not mixed with locking down
own cgroup. This makes the cgroup v2 setup even closer to v1, and fixes
snap-device-helper which tried to verify own cgroup during initialization what
prevented it from properly responding to device events.

cmd/libsnap-confine-private: fix snap-device-helper device allow list modification on cgroup v2

---

cmd/snap/cmd_run_test.go
osutil/strace/export_test.go
osutil/strace/strace.go

Some syscalls do not exist on some arches, and for some of these
non-existent syscalls strace doesn't have a mapping either. Meaning
the default syscall filter needs per-arch adjustments. This should
enable strace in snap run on arm and riscv64.

osutil/strace: try to enable strace on more arches

---

overlord/snapstate/snapstate.go

The disk space checks were repeated throughout the various install
and refresh functions (and more are being added soon), so this
change refactors them to a single function.

o/snapstate: refactor disk space checks

---

HACKING.md

Also document how to workaround a bug in snapcraft which prevents using the
very useful remote-build feature with the snapd snap.

HACKING.md: document building the snapd snap and splicing it into the core snap

---

overlord/devicestate/handlers_systems.go
overlord/managers_test.go

When remodeling, it is possible that the new model will use a snap of the same
name, but from a different track/channel which may in fact carry different
content. Thus when creating a recovery system, make sure to use the 'new' snap
if it is part of the download tasks, rather than first checking the local ones.

o/devicestate: during remodel first check pending download tasks for snaps

---

interfaces/builtin/browser_support.go

Like chromium and Chrome, Edge also requires namespaced access to /dev/shm
and likely access to /run/user as well.

interfaces/browser-support: Update rules for Edge

---

.github/workflows/test.yaml

We need to use pipefail, otherwise the piping to tee will mean that the exit
code is always 0 and thus never actually fails the GitHub Action even when the
spread tests fail.

.github/workflows/test.yaml: restore failing of spread tests on errors (nested)

---

interfaces/builtin/log_observe.go

To access kernel messages from snap, we need log_observe interface to
permit /dev/kmsg as read-only.

interface/builtin/log_observe: allow to access /dev/kmsg

---

interfaces/builtin/network_setup_control.go
tests/core/netplan/task.yaml

Execution of the netplan generator in `/usr/lib/netplan/generate` is prohibited in strictly confined snaps, therefore the `io.netplan.Netplan.Generate()` DBus API was implemented on the neptlan side (https://github.com/canonical/netplan/pull/208).
This new DBus API proxies the call to `netplan generate` and calls it in an unconfined way on the (trusted) system/base side instead.
[LP: #1926442](https://pad.lv/1926442)

network-setup-control: add netplan generate D-Bus rules (LP: #1926442)

---

packaging/debian-sid/control
packaging/ubuntu-16.04/control
packaging/ubuntu-16.04/rules
spread.yaml
tests/lib/pkgdb.sh
tests/main/lxd-mount-units/task.yaml
tests/main/lxd-snapfuse/task.yaml
tests/main/lxd-try/task.yaml

On a cgroup v2 system, we rely on being able to set up a systemd scope for the
snap applications. This is done by communicating with a proper systemd instance
over a dbus bus, which for user session is the session bus.
This only came up when one of the intermediate dependencies of ubuntu-server,
had their dependencies updated and no longer requires session bus and we
observed that it was impossible to launch snap applications that required device
access on Ubuntu 21.10.
Related to:
- https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1951491
- https://forum.snapcraft.io/t/cannot-launch-snap-applications-with-cgroup-v2/27700
cc @slyon

packaging/ubuntu, packaging/debian: depend on dbus-session-bus provider

---

overlord/snapstate/check_snap.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/storehelpers.go
snap/snaptest/snaptest.go

Add a function to install many local snaps. Uses the doUpdate helper
to take advantage of the single restart when installing base and
kernel snaps.
The relevant commits are the last two, the branch is based on https://github.com/snapcore/snapd/pull/11103

o/snapstate: add InstallPathMany

---

HACKING.md

Update the snapcraft remote-build instructions since now snapcraft on the
latest channel supports building remotely properly, but has a different
regression around the symlink farm we have in one of our tests.

HACKING.md: adjust again for building the snapd snap

---

overlord/configstate/configcore/handlers.go
overlord/configstate/configcore/hostname.go
overlord/configstate/configcore/hostname_test.go
tests/core/snap-set-core-config/task.yaml
tests/nested/manual/core-early-config/defaults.yaml
tests/nested/manual/core-early-config/task.yaml

The strict hostname validation rules in combination with the
fact that we now use the external configuration is broken.
If the hostname can be set externally via the hostnamectl
command we cannot have a validaton that is stricter then what
hostnamectl is doing.
This PR changes two things:
1. Only validate the hostname if it's set to in FSOnly apply mode,
i.e. when no hostnamectl call is issued [1].
2. Directly pass the hostname to hostnamectl and let it handle invalid
names. It has a concept of "static" and "pretty" hostname and will
apply even invalid hostnames as "pretty" hostnames. However it will
simplify/filter the pretty hostname so that it becomes a valid static
hostname. Because of this our logic to detect if the hostname has
changed needs to be tweaked to talk to hostnamectl …

configcore: relax validation rules for hostname

---

asserts/asserts.go
asserts/ifacedecls.go
asserts/ifacedecls_test.go
asserts/snap_asserts.go
asserts/snap_asserts_test.go

change the behavior of an alt attribute matcher when matching against
a list of values to match the alternatives to each element and not
overall
this is the approach used by all other matchers against a list of
values
the old behavior was unused and as the new tests show the new behavior
is quite productive. if really needed expressing for different
variants of a list can still be done by expressing variants for one
full level up
to avoid uses of this confusing old snapd, make sure format: 5 is used
to mark snap-declarations that use alt attribute matchers going
forward

asserts: change behavior of alternative attribute matcher

---

daemon/api_model.go
daemon/api_model_test.go
daemon/export_api_model_test.go
tests/main/generic-unregister/task.yaml

this is done by posting {"action":"forget"} to /v2/model/serial
a flag no-registration-until-reboot is also supported

daemon,tests: support forgetting device serial via API

---

tests/core/kernel-and-base-single-reboot/task.yaml
tests/lib/fakestore/refresh/refresh.go

Verify the single reboot feature. Sadly I was not able to make the test work correctly for core20 as the pc-kernel snap is repacked when preparing the UC20 system. Nonetheless, I'll keep on trying to have it work on uc20 too.

tests: verify that simultaneous refresh of kernel and base triggers a single reboot only

---

usersession/client/client.go
usersession/client/client_test.go

Provide a way for usersession client to send messages only to a subset of clients (based on user IDs).

usersession/client: provide a way for client to send messages to a subset of users

---

data/env/snapd.fish.in

Based on comments in https://github.com/snapcore/snapd/pull/11071 the way to add
$SNAP_MOUNT_DIR/bin to fish PATH can be simplified.
Thanks to @Karrq for the suggestion.

data/env: improve fish shell env setup

---

packaging/arch/PKGBUILD
packaging/debian-sid/changelog
packaging/fedora/snapd.spec
packaging/opensuse/snapd.changes
packaging/opensuse/snapd.spec
packaging/ubuntu-14.04/changelog
packaging/ubuntu-16.04/changelog

2.53.3 will go down in history as the short lived but nonetheless 4th straight "failed" snapd release, so here's hoping 2.53.4 is the one :crossed_fingers:

packaging: merge 2.53.4 (and also 2.53.3) changelogs back to master

---

overlord/snapstate/snapstate.go

Backport of https://github.com/snapcore/snapd/pull/11103, as a prerequisite to the backport of https://github.com/snapcore/snapd/pull/11109

o/snapstate: refactor disk space checks (2.53)

---

daemon/api.go
daemon/api_snaps.go
daemon/api_snaps_test.go
daemon/export_api_snaps_test.go
overlord/assertstate/assertstate.go
overlord/assertstate/validation_set_tracking.go
overlord/assertstate/validation_set_tracking_test.go
overlord/snapstate/export_test.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_rerefresh_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_update_test.go

When refresh/auto-refresh fails for some snaps, reconsider validation sets and restore them to the previous tracking state as well as revert some or all of the affected snaps to bring the system back to the state where validation-sets enforcing is satisfied. The critical logic is in maybeRestoreValidationSetsAndRevertSnaps function.
The following is considered:
- if after refresh failure validation sets as happy, then obviously there is nothing to do (this means that snaps that succeeded to refresh didn't affect the validation sets, e.g. revisions didn't matter or they are not required at all).
- otherwise validation sets tracking is restored using the topmost v-s history entry and:
- snaps that are at wrong revisions per the restored validation sets get reverted to the previous …

o/snapstate, assertsate: validation sets/undo on partial failure

---

tests/main/generic-unregister/task.yaml

add a variant that re-registration happens if not blocked until the
next reboot
addresses https://github.com/snapcore/snapd/pull/11135#discussion_r760562110

tests/main/generic-unregister: test re-registration if not blocked

---

tests/main/security-device-cgroups-helper/task.yaml

The test was reported to be flaky in https://bugs.launchpad.net/snapd/+bug/1952813. Try to collect more information on the system state when the test fails.

tests/main/security-device-cgroups-helper: collect some debug info when the test fails

---

tests/main/security-udev-input-subsystem/task.yaml

Drop information from udev database about devices used in the test

tests/main/security-udev-input-subsystem: drop info from udev

---

cmd/snap/last.go

While looking at our code I noticed that we are a bit inconsistent
in our changeIDMixin about where we accept the "short" form for
a change and where we don't. E.g. for the change type `install-snap`
we support the short form `install` but for others like `revert-snap`
we do not.
This commit unifies this some more and fixes a bug in our testsuite
along the way where we use `snap watch --last=revert?` which does
not work today.

snap: add support for `snap watch --last={revert,enable,disable,switch}`

---

overlord/snapshotstate/backend/export_test.go
overlord/snapshotstate/backend/helpers.go
overlord/snapstate/backend.go
overlord/snapstate/backend/copydata.go
overlord/snapstate/backend/copydata_test.go
overlord/snapstate/backend/export_test.go
overlord/snapstate/backend_test.go
overlord/snapstate/handlers.go
snap/helpers.go

This is the first PR of a series that will implement the hidden snap folder migration (the draft PR with all of migration code is https://github.com/snapcore/snapd/pull/10956). This PR adds functions to the backend to hide and undo the hiding of snap data. It also changes ClearTrashedData to look for data to clear in both hidden and exposed dirs. The final version of these functions will be slightly different because SnapDirOptions will have to have two flags, one to signal intent to migrate and another to signal that is has happened. When reviewing UndoHideSnapData bear in mind that it'll be used not only when disabling the feature but also as part of the error recovery behavior [when undoing](https://github.com/MiguelPires/snapd/blob/5dd673998556cc791bea4930679ada7f9f5e51f2/overlord/snap …

o/snapstate: add hide/expose snap data to backend

---

tests/core/fsck-on-boot/task.yaml

This is to avoid the issue "target is busy umount" trying to umount
/var/lib/snapd/seed on uc20
This error is just reproduced on beta validation.
2021-12-06 17:16:12 Error executing
external:ubuntu-core-20-64:tests/core/fsck-on-boot
(external:ubuntu-core-20-64) :
+ os.query is-core16
+ os.query is-core18
+ os.query is-core20
+ LABEL=ubuntu-seed
+ case "$SPREAD_REBOOT" in
+ echo 'We can corrupt the boot partition'
We can corrupt the boot partition
+ unmount_vfat
+ os.query is-core16
+ os.query is-core18
+ os.query is-core20
+ mountpoint /run/mnt/snapd
+ umount /run/mnt/snapd
+ umount /var/lib/snapd/seed
umount: /var/lib/snapd/seed: target is busy.

tests: retry umounting /var/lib/snapd/seed on uc20 on fsck-on-boot test

---

tests/core/remodel-base/task.yaml

As TRUST_TEST_KEYS is false, the restore is not being executed and the
model is not restored making the reset helper fail.

tests: avoid checking TRUST_TEST_KEYS on restore on remodel-base test

---

systemd/emulation.go

Provide more details with `notImplementedError` error to make it easier to understand what goes wrong.

systemd: provide more detailed errors for unimplemented method in emulation mode

---

tests/lib/pkgdb.sh
tests/lib/tools/tests.invariant

Use dbus-user-session to provide the session but, and drop dbus-x11 which
requires $DISPLAY and actual X to be running.

tests/lib/pkgdb: install dbus-user-session during prepare, drop dbus-x11

---

overlord/managers_test.go
overlord/snapstate/backend_test.go
overlord/snapstate/booted.go
overlord/snapstate/handlers.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go
overlord/state/taskrunner_test.go
tests/core/kernel-and-base-single-reboot-failover/task.yaml
tests/core/kernel-and-base-single-reboot/task.yaml
tests/lib/fakestore/cmd/fakestore/cmd_make_refreshable.go
tests/lib/fakestore/cmd/fakestore/main.go
tests/lib/fakestore/refresh/refresh.go

Backport of #11030 and dependencies #11019, #11007, bits from #10943
Marked as blocked as I need the spread tests from ~~#11126~~ and the failover one from #11138

overlord, o/snapstate, many: backport single reboot (2.53)

---

data/selinux/snappy.te

The kernel-module-load interface may trigger accesses to /etc/modprobe.d as seen
in the following denials:
```
type=AVC msg=audit(120721 16:27:22.859:25079) : avc: denied { getattr } for
pid=97494 comm=snapd path=/etc/modprobe.d dev="sda5" ino=13371
scontext=system_u:system_r:snappy_t:s0
tcontext=system_u:object_r:modules_conf_t:s0 tclass=dir permissive=1
type=AVC msg=audit(120721 16:27:22.859:25080) : avc: denied { read } for
pid=97494 comm=snapd name=modprobe.d dev="sda5" ino=13371
scontext=system_u:system_r:snappy_t:s0
tcontext=system_u:object_r:modules_conf_t:s0 tclass=dir permissive=1
type=AVC msg=audit(120721 16:27:22.859:25081) : avc: denied { open } for
pid=97494 comm=snapd path=/etc/modprobe.d dev="sda5" ino=13371
scontext=system_u:system_r:snappy_t:s0 …
```

data/selinux: allow snapd to access /etc/modprobe.d

---

tests/lib/pkgdb.sh
tests/lib/tools/tests.invariant

This is https://github.com/snapcore/snapd/pull/11152 for 2.53

tests/lib/pkgdb: install dbus-user-session during prepare, drop dbus-x11 (2.53)

---

cmd/.clangd

Add is expected to be a list of options not a single element as per the
example in https://clangd.llvm.org/config.html#add

cmd: Fixup .clangd to use correct syntax

---

overlord/snapstate/snapstate_install_test.go

InstallPathMany() unit tests fail when running on a host that does not support
classic confinement (Arch, Fedora). Make sure that proper mocking is in place.

o/snapstate: mock system with classic confinement support

---

cmd/snap/cmd_list.go
cmd/snap/cmd_list_test.go
cmd/snap/cmd_warnings_test.go

When producing the output of `snap list`, snaps that are broken (i.e. not
mounted) are printed without their version. This can be confusing when the
output is further processes by shell tools such as sed/awk/cut. Tweak the code
to always include a placeholder, even if the version is empty.

cmd/snap: print a placeholder for version of broken snaps

---

tests/main/security-device-cgroups-helper/task.yaml

Collect more info from a failing test.

tests/main/security-device-cgroups-helper: more debugs

---

overlord/devicestate/devicemgr.go
timeutil/synchronized.go

The current code in timeutil can produce excessive logging that spams the journal, if no NTP sync is happening each Ensure() call will trigger a log message that no NTP sync happend. The logger also does not belong into something generic like timeutil.
Instead it the devicemgr code will log (once) when it can*t get an NTP sync within the timeout.

devicestate,timeutil: improve logging of NTP sync

---

cmd/snap-bootstrap/cmd_initramfs_mounts.go
cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
cmd/snap-bootstrap/initramfs_systemd_mount.go
cmd/snap-bootstrap/initramfs_systemd_mount_test.go
tests/core/basic20/task.yaml

While squashfs is always read-only, when mount creates the required
loop device, it does not know that squashfs is a read-only
filesystem. This causes the loop devices for snaps mounted in the
initramfs to be be writable. Since the snaps are stored on
`/run/mnt/data`, it means the `/run/mnt/data` cannot be remounted
read-only.
There is a mount cycle now in Ubuntu Core where `/run/mnt/data` cannot
be unmounted because it contains the snap for the Core snap which is
mounted as root. After switching to the shutdown ramfs, then systemd
tries again to umount the remaining file systems as well as the root
file system. At this point, it still cannot umount `/run/mnt/data`, so
`systemd-shutdown` tries to remount read-only. But since the loop
device for the Core snap that cannot be unmounted is …

snap-bootstrap: Mount snaps read only

---

overlord/snapstate/handlers.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/storehelpers.go
overlord/snapstate/storehelpers_test.go
snap/info.go

The disk space checks were obtaining the size of the snaps' prerequisites and 
base via a call to the store. However, an InstallPathMany should allow the
user to install without calls to the store, if all requirements are
available locally. This change makes it so that, if the required bases and
prereqs are included in the install, those are used for the disk check instead
of gotten through the store. Note that for Install/UpdateMany with
prerequisites the already downloaded prereqs are also used, instead of
redownloaded.

o/snapstate: check disk space w/o store if possible

---

overlord/managers_test.go

Verify the post-change bootloader environment state in kernel and base states
for both happy and failover scenarios.
Related to: https://bugs.launchpad.net/snappy/+bug/1931873

overlord: extend kernel/base success and failover with bootenv checks

---

tests/core/failover/task.yaml

tests/core/failover: enable the test on core18

---

cmd/snap-device-helper/snap-device-helper-test.c
cmd/snap-device-helper/snap-device-helper.c
tests/main/security-device-cgroups-helper/task.yaml

The old shell-based snap-device-helper would identify the devices based on
pattern matching the device path. Specifically any device matching */block/*
or */nvme/nvme*/nvme*n* patterns was considered a block device, while all other
devices were consider to be char devices.
Bring back the old behavior, but only in a fallback path of the remove action.
Since when devices are removed, it is possible that the symlinks are already
gone by the time we inspect entries in /sys/devices/. However, we would still
like to remove the device from the cgroup.

cmd/snap-device-helper: bring back the device type identification behavior, but for remove action fallback only

---

.github/workflows/test.yaml
spread.yaml

As openSUSE Leap 15.2 reach its end of life on Dec. 31, 2021

tests: moving to manual opensuse 15.2

---

interfaces/builtin/opengl.go

Allow reading boot_vga attribute
(e.g. /sys/devices/pci0000:00/0000:00:01.0/boot_vga ) of the graphics
cards in /sys/devices, as is done by libpciaccess library by default.

interfaces/builtin/opengl.go: add boot_vga sys/devices file

---

build-aux/snap/snapcraft.yaml
debian
generate-packaging-dir
packaging/ubuntu-14.04/source
tests/lib/snaps/store/test-snapd-daemon-user/src/setregid32.c

When merging https://github.com/snapcore/snapd/pull/10957 we accidentally introduced a change that made the git tree dirty during the build. This lead to version numbers like "2.54-dirty" instead of the expected 2.54. Unfortunately this means we need a 2.54.1 with this fix to ensure we have a sane version number.
This PR adds two commits, one that detects and errors for dirty git trees and one that fixes the issue introduced in #10957.

build-aux: detect/fix dirty git revisions while snapcraft building

---

tests/lib/prepare.sh
tests/nested/manual/core20-initramfs-time-moves-forward/task.yaml

have a "test" directory for that
also stop creating an unused user-data directory in ubuntu-seed in UC20
Address https://github.com/snapcore/snapd/pull/10051#discussion_r602103141 as well

tests: tidy up the top-level of ubuntu-seed during tests

---

c-vendor/vendor.sh

During tests local instance of snapd is populated to VM
without `.git` folders. In case squashfuse is already
populated within the local instance, the `vendor.sh` script
fails to checkout a certain commit.
The checkout now checks first that `.git` exists, otherwise
is assumes that populated squashfuse is correct.
Signed-off-by: Arseniy Aharonov <arseniy@aharonov.icu>

tests: fixed an issue with retrieval of the squashfuse repo

---

cmd/snap-device-helper/snap-device-helper-test.c

Thanks to @setharnold for spotting this.

cmd/snap-device-helper: fix variable name typo in the unit tests

---

packaging/opensuse/snapd.spec

Yes. I have signed it.
I have updated the openSUSE spec file because of failed builds.
s390x requires apparmor-parser as a BuildRequires. Error message:
AppArmor status: apparmor_parser not found
Additionally, there is following message: at the end of the build log (for all) architectures:
[  578s] snapd-2.54.1-5.1.x86_64.rpm: directories not owned by a package:
[  578s]  - /usr/share/fish
That is the reason for adding the datadir for fish the same as it exists for zsh.

packaging: Update openSUSE spec file with apparmor-parser and datadir for fish

---

interfaces/builtin/mount_control.go
interfaces/builtin/mount_control_test.go
tests/lib/snaps/test-snapd-mount-control/meta/snap.yaml
tests/main/interfaces-mount-control/task.yaml

The source device for "tmpfs" must be "none": update the code to allow
the "what" attribute to be set to this value, and add a few checks to
ensure that the same value cannot be used with other filesystem types.

i/b/mount-control: support creating tmpfs mounts

---

gadget/gadget.go
gadget/gadget_test.go

The current code did not check if a gadget.yaml contains empty
volume sections. This leads to crashes for gadget.yaml like:
```
volumes:
lun-0:
```
This commits ensures that empty sections do not crash the code.

gadget: do not crash if gadget.yaml has an empty Volumes section

---

data/selinux/snappy.te

When running in a Xen guest, systemd-detect-virt when invoked by snapd may
trigger the following denial:
```
type=PROCTITLE msg=audit(1640771959.147:236972): proctitle="systemd-detect-virt"
type=AVC msg=audit(1640771959.147:236972): avc:  denied  { search } for pid=21113
comm="systemd-detect-" name="xen" dev="proc"
ino=4026532003
scontext=system_u:system_r:snappy_t:s0
tcontext=system_u:object_r:proc_xen_t:s0
tclass=dir permissive=1
```
See https://forum.snapcraft.io/t/snapd-unavailable-red-hat-enterprise-linux/28004/15
for details.

data/selinux: allow poking /proc/xen

---

tests/core/remodel-kernel/task.yaml

Save/restore the tracking channel of the kernel in the test to
fix a failure when this test runs on e.g. external devices that
have models where the tracking channel of the kernel does not
match the "$KERNEL_CHANNEL" we use when we build the images on
our own.

tests: fix remodel-kernel test when running on external devices

---

tests/core/failover/task.yaml

The boot-state tool is not very useful right now, as neither core18 nor core20
ship with grub_editenv or fw_printenv. Fix the test to use snap debug boot-vars
instead.

tests/core/failover: replace boot-state with snap debug boot-vars

---

tests/lib/tools/tests.invariant
tests/main/try/task.yaml

Tests should generally not leave broken snaps lying around, if there are broken
snaps left, then they should be cleaned up by the test itself to avoid failing
this invariant.
I expect the initial opening of this to reveal some lurking dragons so opening as
a draft to see what happens and what tests need to be cleaned up.

tests/lib/tools/tests.invariant: add invariant for detecting broken snaps

---

.github/workflows/test.yaml
build-aux/snap/snapcraft.yaml

Followup to https://github.com/snapcore/snapd/pull/11188.
We don't want to fail dirty builds since this means that no local builds of the
snapd snap can be performed unless all changes are committed, which is
unfortunate and adds unnecessary steps for snapd developers during development.
Instead when we detect that a build is dirty, include the information inside a
file that is put into the snap that can be inspected later on. This will make
it easy to spot what changed during the build of a dirty snap if for some
reason we ever have those sneak by into the released channels of the published
snap.
Also use build-packages for build dependencies instead of manual apt install
commands.
Also make the GitHub Actions step to build the snapd snap fail when it produces a snap
with a dirty git …

build-aux/snap/snapcraft.yaml: use build-packages, don't fail dirty builds

---

tests/nested/manual/core20-to-core22/task.yaml

Wait for device to obtain a serial number before the test executes a remodel.
Fixes: https://bugs.launchpad.net/snapd/+bug/1956361

tests/nested/manual/core20-to-core22: wait for device to be initialized before starting a remodel

---

tests/lib/tools/tests.invariant

Now that broken snaps have "-" as their version number, we can make the awk
expression here simpler.
Followup to https://github.com/snapcore/snapd/pull/11163

tests/lib/tools/tests.invariant: simplify check

---

.github/workflows/test.yaml
bootloader/assets/grub_cfg_asset.go
bootloader/assets/grub_recovery_cfg_asset.go
packaging/ubuntu-16.04/rules

The Copyright year for the generated bootloader asset files was out of date since the
year is now 2022, so building the snapd deb/snap resulted in this being changed.
The old_seccomp.go file is only needed for trusty, build tags already exclude this file 
from being built, so it's unnecessary to do this for xenial et al.
This should produce clean snapd versions again in the info/version.go files.
Also add to the GitHub Actions snap build a check that the info file has a clean version.

packaging, bloader, github: restore cleanliness of snapd info file; check in GA workflow

---

tests/main/interfaces-kernel-module-load/task.yaml

The `interfaces-kernel-module-load` test currently has no restore
section which means that if the test fails for some reason the
subsequent cleanup on core systems will fail because:
```
2021-12-24T11:45:04.0436279Z + snap remove --purge core
2021-12-24T11:45:04.0437140Z error: cannot remove "core": snap "core" is not removable: snap is being used
2021-12-24T11:45:04.0438421Z        by snap test-snapd-kernel-module-load.
```
This commit adds the missing restore.

tests: ensure that test-snapd-kernel-module-load is removed

---

tests/main/interfaces-kernel-module-load/task.yaml

The tests on the pi fail with `<kill-timeout reached>`. The
deeper reason needs investigation but right now it breaks the
testing because this also fails in restore with stops the full
test run.

tests: exclude interfaces-kernel-module load on arm

---

gadget/install/partition.go
gadget/install/partition_test.go

We previously added code to wait for udev to settle when removing partitions,
but we need the same thing when creating partitions too, otherwise we may fail
in the ensureNodesExist implementation.
Example failure of the tests/main/uc20-create-partitions-reinstall spread test
that happened once out of ~15 runs for me:
```
+ uc20-create-partitions ./gadget-dir ''
panic: cannot create the partitions: partition not available: Failed to open the device '/dev/loop1p3': No such file or directory
goroutine 1 [running]:
main.main()
/home/gopath/src/github.com/snapcore/snapd/tests/lib/uc20-create-partitions/main.go:81 +0x665
-----
```
But by the time the debug section runs:
```
+ udevadm info --query property /dev/loop1p3
DEVPATH=/devices/virtual/block/loop1/loop1p3
DEVNAME=/dev/loop1p3 …
```

gadget/install/partition.go: wait for udev settle when creating partitions too

---

daemon/api_base_test.go
dirs/dirs.go
overlord/devicestate/firstboot_test.go
overlord/export_test.go
overlord/overlord.go
overlord/overlord_test.go
overlord/snapstate/handlers.go
wrappers/core18.go
wrappers/core18_test.go

There can be situations where there exist two snapd processes in the
system: that's the case when one of them is invoked as a subprocess by
the snap-failure systemd unit (which runs cmd/snap-failure/cmd_snap.go),
which we refer to as the "ephimeral snapd", and the other one is the
new, repaired snapd which is started by the ephimeral one. When this
happens, we do not want both of these processes to operate on the
snapstate at the same time; therefore, create a file-based lock to make
the accesses mutually exclusive.
A file-based lock will cause the second process to block and wait until
the lock is released (which can happen either as a result of an explicit
release operation, or at the termination of the process holding it). The
process starting snapd therefore needs to invoke the …

overlord: fix issue with concurrent execution of two snapd processes

---

tests/lib/pkgdb.sh
tests/lib/prepare-restore.sh

This PR fixes some issues that I ran into when testing inside my own 14.04 qemu:
* distro_install_package will silently ignore errors when used in an `if` context
* the `dbus-user-session` package is not available on 14.04
* networkd cannot be restarted on 14.04
* the whole logic around trying to restart systemd-networkd is only for a very specific version upgrade during the 20.10 development cycle and is no longer needed.

tests: fix testing in trusty qemu

---

tests/main/microk8s-smoke/task.yaml

There is no microk8s snap available for 32 bit systems like i386
or armhf. So this test must be skipped.

tests: do not run k8s smoke test on 32 bit systems

---

tests/main/interfaces-fwupd-classic/task.yaml

The test has been seen failing here:
https://github.com/snapcore/snapd/runs/4759182513?check_suite_focus=true
Relevant log lines:
+ MATCH 'variant +string "[0-9.]+(-[0-9a-g-]+)?"'
+ test-snapd-fwupd.get-version
method return time=1641807098.785012 sender=:1.137 -> destination=:1.136 serial=311 reply_serial=2
variant       string "debian/1.7.1-1-2-geeedfc7c"
Since not all versions of debian are affected by this, and that there's
the possibility that the version prefix might appear and disappear
according to the versioning policy followed by the Debian fwupd
maintainer, let's accept a `debian/` prefix but do not require it.

tests: fix fwupd interface test in debian sid

---

cmd/snap-confine/snap-confine.rst
cmd/snap/cmd_help.go
cmd/snap/cmd_snap_op.go

Add mention of how to find channels in `snap {install|refresh|switch} --help` output. Update snap manpage to include links to online docs. While at it, update the link for filing bugs in s-c manpage.
Related to https://bugs.launchpad.net/snapd/+bug/1956832

cmd/snap, cmd/snap-confine: extend manpage, update links

---

data/env/snapd.fish.in

Tell fish to treat XDG_DATA_DIRS as a column separated list and not space separated (default).
Otherwise, get corrupted list with mixed separators:
`XDG_DATA_DIRS=/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop /var/lib/snapd/desktop /var/lib/snapd/desktop`

data/env: treat XDG_DATA_DIRS like PATH for fish

---

client/snap_op.go
client/snap_op_test.go
cmd/snap/cmd_snap_op.go
cmd/snap/cmd_snap_op_test.go
tests/main/install-sideload/task.yaml

Adds `cmd` support for installing multiple local snaps.

cmd: support installing multiple local snaps

---

tests/main/interfaces-kernel-module-load/task.yaml
tests/main/interfaces-kernel-module-load/test-snapd-kernel-module-load/meta/snap.yaml

Find another pair of modules which we can use on all tested devices.
The problem with the previous modules was that on the PI the pcspkr module was missing, and the parport_pc was causing a (recoverable) kernel crash.

tests: re-enable kernel-module-load tests on arm

---

cmd/snap/cmd_quota.go

As requested by Alberto a long time ago: https://github.com/snapcore/snapd/pull/10333#discussion_r644519259

cmd/snap/quota: fix typo in the help message

---

spread.yaml

The qemu systems had a duplicated debian-sid entry and no entries
for debian-10 and debian-11. This commit fixes this.

spread.yaml: add debian-{10,11}, drop debian-9

---

HACKING.md

We need this from the tests that use DBusTest.SetUpSuite() as they depend on
dbus-daemon and dbus-launch.
cc @kubiko

HACKING.md: add dbus-x11 to packages needed to run unit tests

---

tests/main/interfaces-bluez/task.yaml

This test is currently failing on 32-bit Ubuntu 18.04:
https://github.com/snapcore/snapd/runs/4759182899?check_suite_focus=true
The error occurs because the bluez snap is currently not available in
the stable channel (this would deserve an investigation of its own), but
we don't want this to cause our tests to fail.
The resulting code is rather verbose. I wonder if we really need to check for the standard output, if `snap install` quits with a 0 exit status?

tests: workaround missing bluez snap

---

cmd/snap/cmd_debug_disks.go
daemon/api_debug.go

Simple utility for getting the OnDiskVolume's for all disks on a device for debugging purposes. It's not super clean and contains lots of `null` since we don't have any json tags defined, but IMHO for a debug thing like this we don't need it.
Example output:
```json
[
{
"Structure": [
{
"VolumeName": "",
"Name": "BIOS Boot",
"Label": "",
"Offset": null,
"OffsetWrite": null,
"Type": "21686148-6449-6E6F-744E-656564454649",
"Role": "",
"ID": "b2e891ee-b971-4a2b-b874-694bbf9b821a",
"Filesystem": "",
"Content": null,
"Update": {
"Edition": 0,
"Preserve": null
},
"StartOffset": 1048576,
"AbsoluteOffsetWrite": null,
"Index": 1,
"LaidOutContent": null,
"ResolvedContent": null,
"Node": "/dev/sda1",
"Size": 1048576
},
{
"VolumeName": "",
"Name": "EFI System",
"Label": "system-boot",
"Offset": null, …
```

cmd/snap, daemon: add debug command for getting OnDiskVolume dump

---

tests/lib/prepare-restore.sh

With new versions of Go (1.16+) go get will not build and install binaries into
$GOPATH/bin, but rather only get the package and update go.mod. One has to use
go install to get the desired effect.
This should fakestore tests on openSUSE

tests/lib/prepare-restore: use go install rather than go get

---

tests/main/parallel-install-basic/task.yaml

We saw some test failures running this test on UC16 external
devices. It turns out the failures are a side-effect of the
way `tests.session exec` works on UC16. Here the `/snap/bin`
directory is not in `PATH`.
The other places that use `tests.session exec` workaround this
by prepending `snap run`. This commit does the same for
the `parallel-install-basic` test (thanks to Maciej for the
suggestion).

tests: fix parallel-install-basic on external UC16 devices

---

spread.yaml
tests/core/create-user/task.yaml

The `create-user` test was failing on the testflinger external
pi3 devices. The reason is that the test only looked at
`$MANAGED_DEVICE` which is set in spread.yaml just based on
if the device is external or not. However not all external
devices are already managed (the testflinger pi3 is not).
So this commit fixes this by simply checking directly for
`snap managed` instead.
In addition the MANAGED_DEVICE (which is now no longer used)
is removed.

tests: fix `tests/core/create-user` on testflinger pi3

---

cmd/snap/cmd_snap_op.go
cmd/snap/cmd_snap_op_test.go

This PR removes a validation check for `snap install` since go-flags's validation already covers it. Apparently, if the positional struct contains a slice, the slice field must also have a required tag. I had a look at the other commands and did some testing to see if this happened anywhere else but didn't see other examples of this quirk.

cmd/snap: rm unnecessary validation

---

tests/main/snap-info/check.py

Update the test script to work correctly with latest releases of PyYAML, which
now require the Loader to be passed for non-safe load() functions, like so:
```
+ python3 check.py
Traceback (most recent call last):
File "check.py", line 70, in <module>
res = list(yaml.load_all(sys.stdin))
TypeError: load_all() missing 1 required positional argument: 'Loader'
```

tests/main/snap-info: use yaml.safe_load rather than yaml.load

---

cmd/snap/cmd_run.go
cmd/snap/cmd_run_test.go
tests/main/cgroup-tracking/task.yaml

Normally apps declared to be services are started by systemd, and thus end up in
a service specific cgroup. However, it is possible for a user to invoke `snap
run foo.bar` (where foo.bar is a service) and thus run it themselves. In such
scenario, the service will be in the user's cgroup (typically the session
scope). On a cgroup v2 system, should the service then get access to devices,
and attempt to modify device filtering on the cgroup could break the session,
thus snap-confine stops and dies before modifying the cgroup. This was not a
problem with cgroup v1 as the device controller was separate and used a disjoint
hierarchy which could be modified freely.
Attempt to remedy this, by establishing a tracking cgroup also when an app being
a service is not in a systemd created group, in …

cmd/snap: setup tracking cgroup when invoking a service directly as a user

---

interfaces/builtin/desktop_legacy.go

In at-spi 2.40, the socket location for the accessibility bus was changed from an abstract namespace socket to a regular unix socket, with the aim of making it easier to sandbox: without the help of a kernel MAC system like AppArmor, you've really only got a choice between allowing access to all abstract sockets or denying access to all sockets. In contrast, access to regular unix sockets can be controlled via mount namespace manipulation or file permissions.
Unfortunately that release changed to using a randomised socket name under `/tmp`, which could not reasonably be supported with snapd's private /tmp. That issue has been fixed upstream in at-spi, presumably to be included in 2.44:
https://gitlab.gnome.org/GNOME/at-spi2-core/-/issues/43
Now the socket will be named something matching …

interfaces: allow access to new at-spi socket location in desktop-legacy

---

spread-shellcheck

Recent PyYAML made CSafeLoader a default, so for compatibility with older
version which still required CSafeLoader, use safe_load() explicitly which does
the right thing.

spread-shellcheck: use safe_load rather than load with a loder

---

gadget/export_test.go
gadget/gadget_test.go
gadget/update.go

I recently realized that there was another corner case to handle here, where ubuntu-image would create a system-data role partition on the disk at image build time when it was not specified in the gadet.yaml. This needs to be taken care of before we can merge https://github.com/snapcore/snapd/pull/11084 for consistency's sake, so I have prepared some fixes here which are based on top of this PR:
Additionally, as requested I broke out one particular change to a separate PR here:
You can also see how the helpers are used in https://github.com/snapcore/snapd/pull/11084, which now depends on this specific PR.
The main summary of changes:
- introduce OnDiskStructure.DiskIndex + LaidOutStructure.YamlIndex to fix ambiguity, issue with OnDiskStructure.Index vs LaidOutStructure.Index (as they mean …

gadget: misc helper fixes for implicit system-data role handling

---

gadget/gadget_test.go
gadget/update.go

The values in the error message here were reversed from the actual message.
Also only include the snippet about not being creatable at install if we are 
not using strict opts (since those opts are not set during installation) for an
even cleaner message where it does happen.

gadget: fix typo with filesystem message

---

tests/nested/manual/minimal-smoke/task.yaml

This needs more investigation, but for now to get test coverage again, bump it
to 512M.
See also https://bugs.launchpad.net/snapd/+bug/1954545

tests/nested/manual/minimal-smoke: bump mem to 512 for unencrypted case too

---

interfaces/builtin/mount_control.go
interfaces/builtin/mount_control_test.go
overlord/hookstate/ctlcmd/mount.go
overlord/hookstate/ctlcmd/mount_test.go
overlord/hookstate/ctlcmd/umount.go
overlord/hookstate/ctlcmd/umount_test.go
tests/lib/snaps/test-snapd-mount-control/meta/snap.yaml
tests/main/interfaces-mount-control/task.yaml

This adds support for persistent mounts, via a `snapctl` subcommand.

mount-control: step 3

---

go.sum

The effect of running go mod tidy
Everything should be good, but let's make sure that nested tests don't fail unexpectedly

go.mod: tidy up

---

interfaces/builtin/xilinx_dma.go
interfaces/builtin/xilinx_dma_test.go
interfaces/policy/basedeclaration_test.go
tests/lib/snaps/test-snapd-policy-app-consumer/meta/snap.yaml

Needed for a customer enablement project.
Should be a fairly self-explanatory hardware access interface. The hardware in question is a Xilinx FPGA PCIe card. This interface is for use on the device that is hosting the PCIe card, and allows it access to the character device streams provided by the driver (from https://github.com/Xilinx/dma_ip_drivers)

i/builtin/xilinx-dma: add interface for Xilinx DMA driver

---

store/store_action_test.go

```
FAIL: store_action_test.go:3191: storeActionSuite.TestSnapActionTimeout
store_action_test.go:3227:
c.Assert(err, ErrorMatches, `.*/v2/snaps/refresh"?: (net/http: request canceled|context deadline exceeded) \(Client.Timeout exceeded while awaiting headers\).*`)
... error string = "Post \"http://127.0.0.1:38011/v2/snaps/refresh\": context deadline exceeded"
... regex string = ".*/v2/snaps/refresh\"?: (net/http: request canceled|context deadline exceeded) \\(Client.Timeout exceeded while awaiting headers\\).*"
```
https://github.com/snapcore/snapd/runs/4838818272?check_suite_focus=true

store: fix flaky test

---

daemon/access.go
overlord/hookstate/ctlcmd/is_connected.go
overlord/hookstate/ctlcmd/mount.go
overlord/ifacestate/ifacemgr.go
overlord/ifacestate/ifacestate_test.go

There are a couple of places where a ConnectionState is checked for hotplug gone and undesired flag (upcoming #10864 is another one), so I though of reducing it by a tiny bit by adding `Active()` convenience method.
My initial idea was to have a helper for iterating over conns with a lambda for the actual logic (because this is the pattern for those places), but there is no good way of doing this without making it more complex, so it's not a win.
I'll update this PR after #10864 lands.

o/ifacestate: add convenience Active() method to ConnectionState struct

---

cmd/snap/cmd_run.go
cmd/snap/cmd_run_test.go
cmd/snap/cmd_userd.go
cmd/snap/cmd_userd_test.go
cmd/snap/export_test.go

This PR adjusts the /cmd code to the migration changes. It's based on https://github.com/snapcore/snapd/pull/11169 so the only relevant commits are the last two. The first commit changes the autostart code to look for autostart files in ~/.snap/data as well as ~/snap and the second commit changes the get snap options to check the sequence file to see if the snap dir has been migrated. I'm marking this as blocked because #11169 needs to merge first but it'd be good to get a head start by getting some reviews on this as well.

cmd/snap: adjust /cmd to migration changes 

---

.github/workflows/test.yaml
check-commit-email.py
run-checks

Adapted from script from Michael to prevent commits that have non-unicode (or
otherwise invalid) emails set in the commit message from being merged, as this
will break the LP git import.
I am including a broken example commit message to demonstrate that the unit 
tests fail here. Folks can force push away this commit message to land this PR
when desired.

run-checks, check-commit-email.py: check commit email addresses for validity

---

check-commit-email.py

The check fails with a source tarball, like the one used during spread tests.
```
Error: 2022-01-21 07:44:44 Error executing google:ubuntu-20.04-64:tests/unit/go (jan210735-282406) :
-----
...
Obtaining c-dependencies
HEAD is now at 74f4fe8 Merge pull request #63 from vasi/vasi-win-ci
Checking docs
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
File "./check-commit-email.py", line 42, in <module>
commitrange = get_commit_range()
File "./check-commit-email.py", line 22, in get_commit_range
lines = subprocess.check_output(
File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "/usr/lib/python3.8/subprocess.py", line 516, in run
raise …
```

check-commit-email: do not fail when current dir is not under git

---

osutil/user.go

When the `sssd` package is installed on a Ubuntu system the
`TestUserMaybeSudoUser` test will fail because then `user.Lookup`
returns a generic error
```
user: lookup username guy: no such file or directory
```
because in the go layer the getpw{uid,nam}_r() returned ENOENT.
This is already reported upstream as
https://github.com/golang/go/issues/40334
This commit works around this upstream issue by checking for
ENOENT on the error from user.Lookup(). It's not nice but the
best I could come up to to handle this case. On my 21.10 system
sssd is installed as part of `ubuntu-desktop-minimal`.

osutils: deal with ENOENT in UserMaybeSudoUser()

---

spread-shellcheck

Add caching of check results. The cache uses stamps that are based on test
content, while the stamps tree is stored under ~/.cache/spread-shellcheck.
On my 8-core ryzen 1700 with NVMe, wall clock time went down from 1m09s to
0.37s (user time 469s -> 0.27s, 1730x speedup).

spread-shellcheck: add a caching layer

---

packaging/ubuntu-16.04/tests/integrationtests
tests/lib/tools/not
tests/lib/tools/os.query
tests/lib/tools/retry
tests/lib/tools/tests.backup
tests/lib/tools/tests.cleanup
tests/lib/tools/tests.pkgs
tests/lib/tools/tests.pkgs.apt.sh
tests/lib/tools/tests.pkgs.dnf-yum.sh
tests/lib/tools/tests.pkgs.pacman.sh
tests/lib/tools/tests.pkgs.zypper.sh

The autopkgtest spread setup did not include the new external test
tools. This caused misleading errors during autopkgtest runs.
Also changes the placeholder tools to throw errors if they are
called to make clear what is happening.
This was tested with:
```
$ autopkgtest -s -U   -- qemu ~/VM/ubuntu-20.04-64.img
```
but I'm looking into how to also test it from spread to ensure
we do not run into this again. If feasible I will push a separate
PR on top of this one.

packaging,tests: fix running autopkgtest

---

tests/lib/reset.sh
tests/main/hidden-snap-dir/task.yaml

Test that the experimental "hidden snap folder" migrates the snap user data and sets the right environment variables after a refresh.

tests: spread test snap dir migration

---

spread.yaml
tests/lib/prepare.sh
tests/lib/reset.sh
tests/lib/state.sh
tests/lib/tools/tests.invariant

The reset_all_snaps code will get confused if the state contains
disabled snaps. The reason is that importing `reset.sh` will remove
all disabled snaps first. Then the `reset_all_snaps` will call
`restore_snapd_state` which will restore the state and the snaps
but the mount unit of the removed snaps are not re-started so
the snap appears to be broken.
This happens on e.g. the external testflinger devices when the
device starts with a stable core20, then refreshes to a core20
from beta. In that configuration the `tests.invariant` test will
detect a broken core20 revision because of the above behavior.
There are various ways to fix this, the easiest is to just start
with a snapd state that contains no disabled snaps on core systems.
The second commit also adds more debug code around the …

tests: fix running tests.invariant on testflinger systems

---

cmd/snapd-apparmor/snapd-apparmor

This was supposed to be a variable initialization, but likely local got dropped
in the process of making this script POSIX shell compliant. and as a result it
ended up being a program invocation.

cmd/snapd-apparmor: fix bad variable initialization

---

osutil/mkfs/mkfs.go

ubuntu-image is a classic confined snap, and therefore has access to system files such as /usr/lib/. This has been causing problems with the existing fakeroot call, as the fakeroot binary was being called from within the snap, but loading libfakeroot from the host system.
While this is caused by fakeroot hard coding path values, fakeroot does provide a --lib flag to allow the user to specify another location to look for libfakeroot. The change in this PR uses an environment variable to look for the location of libfakeroot. That environment variable will be set in ubuntu-image, and then the correct libfakeroot can be loaded when ubuntu-image calls osutil/mkfs
I used the approach of an environment variable as it seemed like the minimal code change that would get the job done. If the snapd …

osutil/mkfs: Expose option for --lib flag in fakeroot call

---

client/quota.go
client/quota_test.go
cmd/snap/cmd_quota.go
cmd/snap/cmd_quota_test.go
daemon/api_quotas.go
daemon/api_quotas_test.go
daemon/export_api_quotas_test.go
overlord/configstate/configcore/vitality_test.go
overlord/managers_test.go
overlord/servicestate/internal/quotas.go
overlord/servicestate/internal/quotas_test.go
overlord/servicestate/quota_control.go
overlord/servicestate/quota_control_test.go
overlord/servicestate/quota_handlers.go
overlord/servicestate/quota_handlers_test.go
overlord/servicestate/resources/quotas.go
overlord/servicestate/servicestate_test.go
overlord/servicestate/servicestatetest/quotas.go
overlord/snapstate/backend/link_test.go
snap/quota/quota.go
snap/quota/quota_test.go
snap/quota/resources.go
snap/quota/resources_test.go
wrappers/services_test.go

The is the first PR of two for the CPU Quota support for snaps. The PR is about refactoring a part of the current group quota implementation that currently supports the memory limit quota. This quota value is in most cases passed around as a parameter, the goal of this PR is to seperate this value out in a struct and then pass that around as well. This PR seperates the validation logic of quotas as well, and adds some helper functions to handle quotas.
Keep in mind that new quota values will be added in the next PR, and that many changes here will change again. 
overlord/servicestate has it's own type that keeps quota values in resources/quotas.go, I have been very unsure of the namings used in this case, and whether 'resources' was the correct name for that folder, if anyone has better …

overlord: small refactoring of group quota implementation in preparation of multiple quota values

---

mkversion.sh

It is possible that when the mkversion is called, the snapd source tree isn't a
git repository, but rather an extracted source tarball.
To make matters worse, the distro packaging files can be kept in a git source
tree. Then during the build from source tarballs within that source tree
mkversion will incorrectly interpret the output of `git describe` which actually
describes the state of the distro packaging repository.

mkversion: check that snapd is a git source tree before guessing the version

---

gadget/install/install.go
gadget/install/partition.go
gadget/install/partition_test.go

This rescan file does not seem to properly work in either the GCE cloud VM's we
use for spread testing, nor on ordinary QEMU VM's with IDE storage devices, so
we only want to do it for the very specific device that absolutely needs it
(because executing partx will break kernel data structures for the disks and
this kernel bug will not be fixed for various reasons).
So instead only execute the rescan trick if the gadget instructs us to by
placing a file named "force-partition-table-reload-via-device-rescan" in
the meta directory of the gadget.
If we try to use this rescan trick on GCE VM's for example, we see this on the
serial console:
```
Jan 09 14:53:09 ubuntu snapd[1347]: partition.go:295: partition rescan file /sys/devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:1/0:0:1:0/block …
```

gadget/install/partition.go: use device rescan trick only when gadget says to

---

.github/workflows/test.yaml
bootloader/lkenv/lkenv_test.go
logger/logger_test.go
osutil/buildid_test.go
overlord/snapshotstate/backend/backend_test.go
overlord/state/taskrunner_test.go
testutil/base.go

Minor changes ensuring unset SNAPD_DEBG to avoid test failures when run with SNAPD_DEBUG=1

many: unit test fix when SNAPD_DEBUG=1 is set

---

tests/lib/pkgdb.sh

This package was initially added in #10949 to all debian distros in
order to fix the interfaces-timeserver-control test, but was recently
reverted in 958ee4bd7bfd46309e8ca79fdf8d72b66de9a0b2 as the package was
not present in debian-10.
So let's try to add it only to debian sid and debian 11.

tests: add back systemd-timesyncd to newer debian distros

---

tests/main/hidden-snap-dir/task.yaml

The hidden-snap-dir spread test is flaky on CentOS (sorry). I'll work on debugging it in the morning but for now this should prevent it from blocking anyone.

tests: skip migration test on centOS

---

tests/lib/pkgdb.sh

We now have a new HTTPS-capable domain for public PPAs, namely
ppa.launchpadcontent.net.  Adjust a test to accept that.

tests: Handle PPAs being served from ppa.launchpadcontent.net

---

daemon/api_snaps.go
daemon/api_snaps_test.go
daemon/api_themes.go
daemon/api_themes_test.go
daemon/export_test.go
overlord/hookstate/ctlcmd/services_test.go
overlord/managers_test.go
overlord/snapstate/dbus_test.go
overlord/snapstate/flags.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go

Add Transaction to snapstate.Flags, which will be used to indicate
when we want to transactionally install/update a set of snaps. Add
also Flags as argument to InstallMany() so said flag can be used
there.

many: add Transactional to snapstate.Flags

---

tests/main/snaps-state/task.yaml

Skip validation of repacking when the sru validation is being executed, in this scenario the deb package used comes from the sru and repack is not done
To reproduce the issue, run: 
SPREAD_MODIFY_CORE_SNAP_FOR_REEXEC=0 SPREAD_TRUST_TEST_KEYS=false SPREAD_SNAP_REEXEC=0 SPREAD_CORE_CHANNEL=stable SPREAD_SRU_VALIDATION=1 spread -debug google-sru:ubuntu-20.04-64:tests/main/snaps-state

tests: fix snaps-state test for sru validation

---

systemd/systemd_test.go

The test that checked whether systemd wrapper uses a lock only tested
Systemd.DaemonReload, while there was a clear intention to check
Systemd.DaemonReexec too.

systemd: actually test the function passed as a parameter

---

snap/quota/resources_test.go

There were some missing test cases for the Resources.Validate logic. This adds test cases that verify that Validate and ValidateChange can actually give some positive feedback as well as negative.

snap/quota: add positive tests for the quota.Resources logic

---

tests/regression/lp-1871652/task.yaml

The test assumes that snapd is built from source but it doesn't happen for sru validation and the test fails because of that.
To check the test, run:
SPREAD_MODIFY_CORE_SNAP_FOR_REEXEC=0 SPREAD_TRUST_TEST_KEYS=false SPREAD_SNAP_REEXEC=0 SPREAD_CORE_CHANNEL=stable SPREAD_SRU_VALIDATION=1 spread -debug google-sru:ubuntu-18.04-64:tests/regression/lp-1871652

tests: skip version check on lp-1871652 for sru validation

---

spread.yaml

This is replacing systems ubuntu-21.04-64 recently removed

tests: use system ubuntu-21.10-64 in nested tests

---

cmd/snap-update-ns/system.go
cmd/snap-update-ns/system_test.go

Some of the file modes used in the `AddModeHint` calls were decimal integer constants, when they were clearly intended to be octal. The unit tests passed because they also used a decimal constant.
I couldn't see any spread test checking these permissions. As I remember it, the sequence of events for this to matter are:
1. Install a snap with an `x11` plug and another with an `x11` slot. Connect the plug to the slot.
2. Start a command from the plug-side snap before anything from the server has run.
3. The slot snap's private `/tmp` and `/tmp/X11-unix` directories should have been created with appropriate file permissions by the plug snap's run of snap-update-ns.
This is just the minimal change to fix this problem.  But if we're using Go >= 1.13 everywhere, it might be worth switching …

cmd/snap-update-ns: convert some unexpected decimal file mode constants to octal.

---

tests/lib/pkgdb.sh

On autopkgtest based ubuntu-20.04 the ca-certificates package is
not installed by default. This will lead to spread failures when
the prepare code tries to checkout code and cannot validate the
https certs. Therefore this commit ensures the package is
installed.

tests: ensure the ca-certificates package is installed

---

asserts/constraint.go
asserts/constraint_test.go
asserts/export_test.go
asserts/ifacedecls.go

Generalization is along:
* start preparing for different usages to have different sets of $OP() operators allowed
* have usage context specif word instead of "attribute" mainly in errors

asserts: start generalizing attrMatcher

---

client/snap_op.go
client/snap_op_test.go
cmd/snap/cmd_snap_op.go
cmd/snap/cmd_snap_op_test.go
daemon/api_sideload_n_try.go
daemon/api_sideload_n_try_test.go
daemon/api_snaps.go
daemon/api_snaps_test.go

Add transactional flag to snapd API. This is a continuation of https://github.com/snapcore/snapd/pull/11271, and it is the second of a series of three (see https://github.com/snapcore/snapd/pull/11255 for the original PR).

many: add transactional flag to snapd API

---

tests/main/snap-userd-reexec/task.yaml

The idea of this change is to run this test in all the systems that support reexec.

tests: enable snap-userd-reexec on ubuntu and debian

---

interfaces/builtin/opengl.go
interfaces/builtin/opengl_test.go

$ udevadm info --query property /dev/mali0
DEVPATH=/devices/platform/soc/13040000.mali/misc/mali0
DEVNAME=/dev/mali0
DEVMODE=0666
MAJOR=10
MINOR=60
SUBSYSTEM=misc
USEC_INITIALIZED=5223664
TAGS=:snap_ubuntu-frame_ubuntu-frame:snap_mir-test-tools_qt-test:snap_mir-test-tools_sdl2-test:snap_mir-test-tools_smoke-test:snap_mir-test-tools_hook_configure:snap_ubuntu-frame_daemon:snap_mir-test-tools_gtk3-test:snap_mir-test-tools_performance-test:
dma_buf_test_exportor is a necessary kernel module since ARM Mali r32p0
It's the buffer allocator and can export a DMA buffer.
/dev/dma_buf_te is generated by dma_buf_test_exportor
$ udevadm info --query property /dev/dma_buf_te
DEVPATH=/devices/virtual/misc/dma_buf_te
DEVNAME=/dev/dma_buf_te
MAJOR=10
MINOR=58
SUBSYSTEM=misc
USEC_INITIALIZED=4964986 …

interfaces/opengl: add support for ARM Mali

---

overlord/snapstate/export_test.go
overlord/snapstate/handlers.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_update_test.go

Write state and sequence file after undoing the migration, if
these exist. This must be done after the undo procedure because
only then do we know what the migration's final state is. Also,
take care to re-write what was written during the change (e.g., if
the sequence file was written but not the state, re-write only the
sequence file with the undone migration status).
Add comments explaining why state is written where it is.
Add new tests and improve test robustness.

o/snapstate: re-write state after undo migration

---

cmd/snap-repair/cmd_show_test.go

Use repair.NewCmdShow in the test to avoid appending to internal slice; this follows existing tests in the suite and fixes failures when running the test with -count N.

tests: fix repair test failure when run in a loop

---

interfaces/builtin/modem_manager.go

In modem-manager 1.16 some additional files are accessed in sysfs to
detect the modem type.

i/builtin: allow modem-manager interface to access some files in sysfs

---

asserts/asserts.go
asserts/asserts_test.go
asserts/authority_delegation.go
asserts/authority_delegation_test.go
asserts/constraint.go
asserts/export_test.go
asserts/header_checks.go
asserts/snap_asserts_test.go

authority-delegation allows and constraints delegating signing authority from one account to another.
TODO in later PRs:
* support "since" and optional "until" in assertion constraints
* support authority-delegation during signature checking and assertion validation
* implement $WITHIN(n1,n2) constraint
* support device scope constraint in assertion constraint, take them into account on assertion retrieval as well 
based on #11309 and #11308

asserts: start implementing authority-delegation

---

gadget/device.go
gadget/device_linux.go
gadget/gadget_test.go
gadget/gadgettest/examples.go
gadget/gadgettest/gadgettest.go
gadget/update_test.go
osutil/disks/disks_darwin.go

Add an examples.go file with basic examples of the structures we expect to see
and use in many gadget tests that have to do with MockDiskMapping, etc.
Also move some things around so that Err* variables from device_linux.go are
also available on darwin too, since we need to start importing bits of this
package from the snap command soon as well.
Broken out from https://github.com/snapcore/snapd/pull/11220 to make that PR easier to 
review - this is all just test-only changes.

gadget, gadgettest: reimplement tests to use new gadgettest examples.go file

---

cmd/snap/cmd_run.go
cmd/snap/cmd_run_test.go

Add a --debug flag to snap run, which is equal to setting SNAPD_DEBUG=1 in the
environment, but will hopefully be more discoverable for users trying to poke at
things.

cmd/snap: add --debug to snap run

---

overlord/servicestate/quota_control.go
overlord/servicestate/quota_control_test.go
overlord/servicestate/quota_handlers.go
overlord/servicestate/quota_handlers_test.go
snap/quota/quota.go
snap/quota/quota_test.go
tests/main/snap-quota/task.yaml

This PR disallows the mixing of snaps and quota subgroups in quota groups. The reason this is neccessary is because of the new quotas that we are implementing. Journal quotas and storage quotas do not support such nesting, and in this case it doesn't make sense for us to allow either. So it's better if we just allow groups to either contain subgroups only, or snaps only.

overlord/servicestate: disallow mixing snaps and subgroups.

---

data/selinux/snappy.te
spread.yaml
tests/main/degraded/task.yaml
tests/main/interfaces-packagekit-control/task.yaml

CentOS 8 has hit EOL and is now delivered as CentOS 8 Stream offering.
See: https://www.centos.org/centos-stream/

spread: switch to CentOS 8 Stream image

---

cmd/libsnap-confine-private/snap-test.c
cmd/libsnap-confine-private/snap.c
tests/main/interfaces-hooks-plug-with-number/task.yaml
tests/main/interfaces-hooks-plug-with-number/test-snap/meta/hooks/connect-plug-consumer0
tests/main/interfaces-hooks-plug-with-number/test-snap/meta/hooks/prepare-plug-consumer0
tests/main/interfaces-hooks-plug-with-number/test-snap/meta/snap.yaml

Allow numbers in hook names (except for the first character) when checking hook security tag in snap-confine to allow interface hooks for such plugs/slots; this matches the `validHook` regex (see `snap/naming/validate.go`) used by snapd.
Hooks for plugs/slots names that end with numbers otherwise cause an error if snapctl is used:
```connect-plug-station0": error: error running snapctl: interface attributes can only be read during the execution of interface hooks```
The error arises because snap-confine doesn't consider passed security context as hook's, and overrides SNAP_COOKIE env var with the one for the snap, replacing the cookie value passed by snap run for the hook execution. As a consequence snapctl considers to be running with an ephemeral context (not from the hook), so cannot …

snap-confine: allow numbers in hook security tag

---

dirs/dirs.go
overlord/servicestate/export_test.go
overlord/servicestate/quota_control.go
overlord/servicestate/quota_control_test.go
overlord/servicestate/quotas.go

This reverts commit d5eb40d189275403b12f2f4464192196fe691463.
PR #11003 unfortunately introduced a regression on systems where the memory
cgroup was disabled because now servicestate.AllQuotas would return an error,
but we need to be able to access at least the quota group information in the
state in order to compute what options to generate services with in a few
places:
* in the ensure loop of the servicestate manager (runs all the time)
* in link-snap tasks (for snap installs/refreshes)
* in config tasks (for specifically the vitality-rank config setting)
* in discard-snap tasks (for snap removes)
So when the memory cgroup is disabled, all of the above things fail, including
catastrophically not being able to update the snapd snap (since snap refreshes
are now also broken), meaning …

o/servicestate: revert #11003 checking for memory cgroup being disabled

---

gadget/install/content.go
gadget/install/content_test.go
gadget/install/install.go

This was never used, since by design, we only create partitions with
filesystems in install mode (and specifically only ubuntu-save, ubuntu-data,
and ubuntu-boot).
Also remove the gadgetRoot parameter since it is not used.
Removing support for this isn't really necessary, but it's unused code that we
likely do not ever have a plan for using.

gadget/install: rm unused support for writing non-filesystem structures

---

gadget/install/partition.go
gadget/install/partition_test.go

This is not strictly necessary, but resolves an issue wherein we previously
were mounting all partitions during install mode at the same location of
<contentMountpoint>/0 in writeFilesystemContent(). This is because we were 
using ds.Index as the directory to use for each partition, but now that we
switched to using YamlIndex and DiskIndex, the mount code in 
writeFilesystemContent() was adapted to use DiskIndex which made sense at the 
time because the structure it is operating on is an OnDiskStructure. This 
didn't cause any obvious issues since we unmount things before mounting again
so even though we would be mounting on the same directory different partitions, 
nothing was broken.
The alternative to this change is to revert to effectively using the YamlIndex
instead as the final …

gadget/install/partition.go: include DiskIndex in synthesized OnDiskStructure

---

gadget/install/content.go
gadget/install/content_test.go
gadget/install/export_test.go

Also because we know we will never create partitions/structures other than 
those with filesystems in UC20 install mode, error if the provided 
OnDiskStructure does not have a filesystem.

gadget/install: add unit tests for makeFilesystem, allow mocking mkfs.Make()

---

cmd/snap/cmd_auto_import.go
cmd/snap/cmd_auto_import_test.go
cmd/snap/export_test.go
osutil/mountinfo.go
osutil/mountinfo_linux.go

Eliminate the custom mount table parsing here in lieu of the existing and
arguably better tested parsing in LoadMountInfo.
Also fix a test-only bug where we were not properly skipping the UC20+ specific
mount dir of /writable/system-data/var/lib/snapd/seed. The code as written only
worked when dirs.GlobalRootDir was the empty string, if that was any other dir
like in tests, then it wouldn't match and we would consider it. However the
unit test for this specific case, TestAutoImportUC20CandidatesIgnoresSystemPartitions
had inadvertently copied the erroneous mount line which did not have a "-" to
delineate between the optional flags for the mount entry and the rest of the
mount fields which was used in another test, so it was silently skipped with
the custom implementation that was here …

cmd/snap/auto-import: use osutil.LoadMountInfo impl instead

---

osutil/cp_linux_test.go
snapd.code-workspace

Added support for MS VSCODE in a form of a workspace file
(snapd.code-workspace) configured to develop snapd using this IDE,
including recommendations for the set of useful extensions.
The IDE will suggest installing these extensions when the workspace
file is opened first time.
- The test `TestDoCpErr` has been adjusted to have a workaround
for the issue of debugger (used by VSCode Go extension) that
incorrectly allows writing to STDIN.
Signed-off-by: Arseniy Aharonov <arseniy.aharonov@canonical.com>

vscode: added integrated support for MS VSCODE

---

tests/nested/manual/remodel-cross-store/task.yaml
tests/nested/manual/remodel-simple/task.yaml

Wait for serial before querying for it and proceeding with remodel.

tests/nested/manual/remodel-cross-store,remodel-simple: wait for serial

---

gadget/gadgettest/examples.go
gadget/gadgettest/gadgettest.go
gadget/install/install_test.go
gadget/install/partition.go

Based on top of all of these PRs:
Ideally we would have written these a long time ago and avoided some bugs we did not catch, but there's no time like the present to fix it. 
This is a test only change after all the pre-reqs have landed, hence the skip spread label.

gadget/install: add unit tests for install.Run()

---

tests/main/snap-system-key/task.yaml

We start and stop snapd a lot during this test, so if it runs fast enough, it
can hit the start limit which looks in the logs like this:
```
Feb 03 18:01:47 feb031721-896841 systemd[1]: Starting Socket activation for snappy daemon.
Feb 03 18:01:47 feb031721-896841 systemd[1]: Listening on Socket activation for snappy daemon.
Feb 03 18:01:47 feb031721-896841 systemd[1]: Starting Snap Daemon...
Feb 03 18:01:47 feb031721-896841 systemd[1]: snapd.socket: Start request repeated too quickly.
Feb 03 18:01:47 feb031721-896841 systemd[1]: snapd.socket: Failed with result 'start-limit-hit'.
Feb 03 18:01:47 feb031721-896841 systemd[1]: Failed to listen on Socket activation for snappy daemon.
Feb 03 18:01:47 feb031721-896841 systemd[1]: Dependency failed for Snap Daemon.
Feb 03 18:01:47 …
```

tests/main/snap-system-key: reset-failed snapd and snapd.socket

---

cmd/snap/cmd_debug_gadget_disk_mapping.go
daemon/api_debug.go
gadget/gadget.go
gadget/gadget_test.go

This PR is somewhat large mainly just because of the test cases which have a 
lot of large objects included in them for mocking purposes, etc.
This is a more generalized version of DiskTraitsFromDeviceAndValidate which
takes multiple laid out volumes and attempts to do the actual task of locating
what devices volumes may exist on using FindDeviceForStructure.
With this, multiple test cases and example outputs are provided to test the
logic here for different situations in the gadgettest package and some existing
tests are re-written to use these common setups.
Finally, add a multi-volume equivalent of LayoutFromYaml to accommodate these
tests in gadgettest with LayoutMultiVolumeFromYaml.
Also add a debug command to call this function for easy debugging of multi-volume
gadget asset updates …

gadget/gadget.go: add AllDiskVolumeDeviceTraits

---

gadget/gadget_test.go

This type got moved to gadgettest in one of the prior PRs, but the checks for
the PR where this specific test was introduced had it's checks run before that
PR was merged so it was green and thus mergable and didn't show this error.
Thanks to Maciej for finding this out so quickly.

gadget/gadget_test.go: fix variable type

---

interfaces/seccomp/template.go

glibc 2.35 calls rseq() for all threads so allow this by default

interfaces/seccomp: Add rseq to base seccomp template

---

cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
cmd/snap-bootstrap/initramfs_systemd_mount.go
cmd/snap-bootstrap/initramfs_systemd_mount_test.go

To be able to survive switch root, mounts need to be "wanted" directly
or indirectly by `initrd-switch-root.target`. `initrd-fs.target` is
the proper target and enough. Specifying other targets is superfluous.
The mounts do not need to be "required". "Requires" has a stricter
semantic and potentially makes systems less robust. It is recommended
by documentation that we use "Wants" where "Requires" is not needed.
`initrd.target` and `local-fs.target` are not part
`initrd-switch-root.target` and are normally taken down during the
switch of root.
Default dependencies are not useful in non ephemeral mounts.
Specifically `Before=local-fs.target`. The dependency we need is
`Before=initrd-fs.target`.

snap-bootstrap: Cleanup dependencies in systemd mounts

---

overlord/snapstate/autorefresh.go
overlord/snapstate/autorefresh_test.go

Reduce maxInhibition for refresh app awereness by 1 second as sharp 14 days leads to a slightly strange notification when refreshes are retried quickly and the app is still running: at first the notification says we have 14 days left, and a moment later it switches to 13 days.

o/snapstate: reduce maxInhibition for raa by 1s to avoid confusing notification

---

cmd/snap-confine/mount-support-nvidia.c
cmd/snap-confine/mount-support.c

Adding the `static` keyword before initializations of const variables
ensures that such initialization will happen at compile-time. As it can
be seen from this assembly snippet (extracted from the
sc_populate_mount_ns() function), before this change the array of
`sc_mount` structures was computed at run-time:
```as
.LC62:
.string "/home"
.LC63:
.string "/root"
.LC64:
.string "/proc"
[...]
leaq    .LC62(%rip), %rax
movq    %rax, 128(%rsp)
leaq    .LC63(%rip), %rax
movq    %rax, 160(%rsp)
leaq    .LC64(%rip), %rax
movq    %rax, 192(%rsp)
```
whereas, declaring these variables as `static` causes them to be dumped
into the read-only data section, and loaded with a single operation:
```as
.LC115:
.string "/home"
.LC116:
.string "/root"
.LC117:
.string "/proc"
[...]
mounts.3:
.quad   .LC113 …
```

cmd/snap-confine: build const data structures at compile-time

---

HACKING.md

Fixes an incorrect link in the HACKING.md document.

docs: fix incorrect link

---

.github/workflows/test.yaml
asserts/fetcher.go
cmd/snap-update-ns/utils.go
cmd/snap/cmd_auto_import.go
dbusutil/netplantest/netplantest.go
desktop/notification/fdo_test.go
desktop/notification/gtk_test.go
desktop/notification/manager_test.go
osutil/faultinject_dummy_test.go
overlord/configstate/configcore/netplan.go
overlord/configstate/configcore/netplan_test.go
spdx/licenses.go
store/store.go
strutil/shlex/shlex.go

Fixes some issues flagged by golangci-lint:
* Groups 3rd party imports
* Removes some unused vars
* Moves var only used in tests into test pkg
* Add 'nolint' to ignore warning on unused iotas (wasn't sure if those were left intentionally, for instance for readability purposes)
Also allow golangci to fail the build so we can catch these nits before they're merged.

many: fix issues flagged by golangci and configure it to fail build

---

overlord/configstate/configcore/vitality_test.go
overlord/managers_test.go
overlord/servicestate/quota_control.go
overlord/servicestate/quota_handlers_test.go
tests/core/mem-cgroup-disabled/task.yaml

Add a managers level unit test which should be duplicated when we add back the memory cgroup enable check to also run when the memory cgroup is disabled.
Also add a spread test which runs with the memory cgroup disabled so we have a full end-to-end test of the situation.

tests: add regression tests for disabled memory cgroup operation

---

tests/lib/nested.sh

This error only affects the classic images. This is the error I see in
logs
-y "linux-modules-extra-$(uname -r)"'
Warning: Permanently added '[localhost]:8022' (ECDSA) to the list of
known hosts.
WARNING: apt does not have a stable CLI interface. Use with caution in
scripts.
Reading package lists...
Building dependency tree...
Reading state information...
linux-modules-extra-5.13.0-27-generic is already the newest version
(5.13.0-27.29).
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up linux-image-5.13.0-27-generic (5.13.0-27.29) ...
Processing triggers for linux-image-5.13.0-27-generic (5.13.0-27.29) ...
/etc/kernel/postinst.d/initramfs-tools:
update-initramfs: …

tests: increase nested disk size on classic images

---

tests/core/remodel-base/task.yaml
tests/core/remodel-gadget/task.yaml
tests/core/remodel/task.yaml

In case snapd is asserted, then we need to reboot after changing the model. 
These tests are failing when running beta validation because the tests don't detect that the sevice is going to reboot.

tests: reboot test running remodel

---

data/env/snapd.fish.in

Make the fish env setup script compatible with old versions of fish 3.0.x which
was released back in 2019, but is still shipped by recent releases of distros
eg. Ubuntu 21.10.
While doing so, make sure that helper variables used in the script stay local.
Since only newer versions of fish (3.1+) are aware of XDG_DATA_DIRS make sure
that it's exported.
Fixes:
https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1958022
https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1957948
https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1960492

data/env: fix fish env for all versions of fish, unexport local vars, export XDG_DATA_DIRS

---

cmd/snap/cmd_run.go
cmd/snap/cmd_run_test.go
overlord/snapstate/backend/copydata.go
overlord/snapstate/backend/copydata_test.go
tests/main/hidden-snap-dir/task.yaml

I noticed that some checks in the migration spread test could be a bit stricter. Making those changes actually made the test fail so this PR addresses the root causes and improves the tests (unit and spread). The first commit fixes an issue where even after migration, the `~/snap` dir was being created due to a hardcoded value. The second commit attempts to remove `~/.snap` (if empty) after removing `~/.snap/data`.

many: fix leftover empty snap dirs

---

asserts/account_key.go
asserts/account_key_test.go
asserts/asserts.go
asserts/authority_delegation.go
asserts/authority_delegation_test.go
asserts/database.go
asserts/database_test.go
asserts/export_test.go
asserts/snap_asserts_test.go
cmd/snap-repair/runner.go

this adds support for since-until in assertion constraints and needed checks during assertion/signature validation.
Currently prohibit delegation for repairs.
TODO in later PRs:
* first-class formatting/encoding support for signatory-id
* retrieve authority-delegation as needed when fetching account-keys for assertions
* support device scope constraint in assertion constraint, take them into account on assertion retrieval as well
* implement $WITHIN(n1,n2) constraint

asserts,cmd/snap-repair: support delegation when validating signatures

---

asserts/header_checks.go

this was flagged by deadcode/unused.
there is no obvious future use case for this anymore so I'm removing it
but this will not always be clear cut with header_checks.go functions
which is a growing helper library

asserts: remove unused function, fix for linter

---

asserts/asserts.go
asserts/asserts_test.go
asserts/database_test.go

asserts: first-class support for formatting/encoding signatory-id

---

spread.yaml
tests/lib/nested.sh
tests/lib/prepare-restore.sh
tests/lib/tools/journal-state

The idea of this change is to prepare and restore the nested tests as we do for the main suite.
Also by doing that we can access the journal logs instead of checking the systems service status.
This change also includes a fix for the assertion disk when the image is reused.

tests: prepare and restore nested tests

---

asserts/constraint.go
asserts/constraint_test.go
asserts/export_test.go
asserts/ifacedecls.go
asserts/ifacedecls_test.go
interfaces/policy/helpers.go

this moves DeviceScopeConstraint to constraint.go and adds a Check method in preparation for reuse of DeviceScopeConstraint for assertion constraints from authority-delegation.

asserts,interfaces/policy: move and prepare DeviceScopeConstraint for reuse

---

tests/main/hidden-snap-dir/task.yaml

Skip the hidden snap dir test on openSUSE, since the 'snap remove'
issue was observed there as well. Also, update the comment about
the flakiness and link to LP report.

tests: skip ~/.snap migration test on openSUSE

---

overlord/snapstate/snapstate_config_defaults_test.go
overlord/snapstate/snapstate_test.go

Unclear why this name was ever used, but it makes certain future tests I have
confusing to write since the "core" snap ends up having it's mount dir as
"/snap/corecore/..."

o/snapstate: rename "corecore" -> "core"

---

tests/main/security-udev-input-subsystem/task.yaml

Permission denied could also be returned instead of 'Operation not permitted'.

tests: fix security-udev-input-subsystem test

---

gadget/export_test.go
gadget/gadget.go
gadget/gadget_test.go
gadget/gadgettest/examples.go
gadget/update.go
gadget/update_test.go

Followup to https://github.com/snapcore/snapd/pull/11354, also introduces some stuff to gadgettest, which we use in https://github.com/snapcore/snapd/pull/11374.

gadget: refactor StructureEncryption to have a concrete type instead of map

---

overlord/devicestate/devicestate_bootconfig_test.go
overlord/devicestate/devicestate_cloudinit_test.go
overlord/devicestate/devicestate_gadget_test.go
overlord/devicestate/devicestate_install_mode_test.go
overlord/devicestate/devicestate_remodel_test.go
overlord/devicestate/devicestate_serial_test.go
overlord/devicestate/devicestate_systems_test.go
overlord/devicestate/devicestate_test.go
overlord/devicestate/firstboot_preseed_test.go
overlord/devicestate/handlers_test.go
overlord/devicestate/systems_test.go

- pass "classic" flag to deviceMgrBaseSuite to allow creating device manager with mocked classic/core upfront. This doesn't prevent tests from overriding MockOnClassic later in the test but is important in case DeviceManager needs to know if it's on classic early in its init (important for core20/preseeding tests).
- drop TestPreseedHappy which was pointless/misleading as it was actually run against core; TestPreseedOnClassicHappy covers real case.
- renamed test suites from preseed* to preseeding*
- some minor cleanups and sanity checks for classic.

o/devicestate: preseeding test cleanup

---

overlord/devicestate/firstboot_preseed_test.go

This is not used anymore and is failing the github actions. See https://github.com/snapcore/snapd/actions/runs/1860045472

o/devicestate/firstboot_preseed_test.go: remove deadcode

---

overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate_test.go

This commit changes the the message:
```
Remove vulnerable "core" snap
```
to
```
Remove inactive vulnerable "core" snap rev 1
```
so that it's a bit clearer what exactly is happening and a bit
less scary.

snapstate: make "remove vulnerable version" message more friendly

---

boot/boot.go
boot/boot_robustness_test.go
boot/boot_test.go
boot/bootstate16.go
boot/bootstate20.go
boot/boottest/device.go
boot/export_test.go
boot/flags.go
boot/model.go
boot/model_test.go
boot/systems.go
boot/systems_test.go
overlord/snapstate/backend.go
overlord/snapstate/backend/link.go
overlord/snapstate/backend/link_test.go
overlord/snapstate/backend/setup.go
overlord/snapstate/backend_test.go
overlord/snapstate/devicectx.go
overlord/snapstate/policy.go
overlord/snapstate/policy/base.go
overlord/snapstate/policy/gadget.go
overlord/snapstate/policy/kernel.go
overlord/snapstate/policy/os.go
overlord/snapstate/policy/policy.go
overlord/snapstate/policy/snapd.go
snap/device.go

This is a purely mechanical change because it touches so many files, the real
interesting parts we need that prompted this will be followups.

many: move boot.Device to snap.Device

---

spread.yaml

This was missing to help pass the smoke test suite for core22. This removes another workaround I had in place

spread.yaml: add core22 version of rsync to skip

---

tests/main/snap-run-devmode-classic/task.yaml

The current "snap-run-devmode-classic" test is hardcoding a
version number in the restore step of the test. This breaks
the test after 2.54.3 was released.

tests: fix "undo purging" step in snap-run-devmode-classic

---

daemon/api_debug.go
gadget/export_test.go
gadget/gadget.go
gadget/update.go
gadget/update_test.go

This is used during a multi-volume asset update routine where we have the 
traits for a volume which is to be updated and the LaidOutVolume for it, and we
want to find a real disks.Disk{} for it.
Also make the debug endpoint slightly smarter so it works on UC16/UC18 devices too.

gadget: add searchForVolumeWithTraits + tests

---

interfaces/builtin/cpu_control.go
interfaces/builtin/power_control.go

See the init_post_boot.sh[1] script for a summary of these accesses. There are
other accesses we are still evaluating where to provide them, they likely
belong in either custom-devices or in system-files for specific devices
however.
See also salesforce ticket 00320679.
[1] https://source.codeaurora.org/quic/le/snap/yaml/tree/sa8155p-gadget/postboot/init_post_boot.sh?h=UC.UM.1.0.r1-00600-sa8155.0

interfaces/{cpu,power}-control: add more accesses for commercial device tuning

---

gadget/export_test.go
gadget/update.go
gadget/update_test.go

For devices that don't have a disk-mapping.json, we need this method to
construct the traits for the system-boot containing volume only to allow
gadget asset updates to be performed on specifically that volume only.
The naive check to see if the device has encryption or not may be too 
naive, not sure...

gadget/update.go: add buildNewVolumeToDeviceMapping for existing devices

---

tests/main/snap-run-devmode-classic/task.yaml

This is needed because the snapcraft snap is removed for the snapd_first
variant, but we still ought to clean up the project tree from snapcraft
artifacts otherwise they can mess up other tests.

tests/main/snap-run-devmode-classic: reinstall snapcraft to clean up

---

data/env/snapd.fish.in
tests/lib/pkgdb.sh
tests/main/user-session-env/task.yaml

Tweak snapd.fish to be compatible with even older releases of fish, going back to 2.7, which was shipped with Ubuntu 18.04.

data/env: more workarounds for even older fish shells, provide reasonable defaults

---

data/env/snapd.fish.in
tests/lib/pkgdb.sh
tests/main/user-session-env/task.yaml

with merge fixes
Tweak snapd.fish to be compatible with even older releases of fish, going back to 2.7, which was shipped with Ubuntu 18.04.
* data/env: make fish setup compatible with fish 2.7
Make the environment setup script compatible with fish 2.7 which was shipped
with Ubuntu 18.04.
Thanks to @faho for the review.
Signed-off-by: Maciej Borzecki <maciej.zenon.borzecki@canonical.com>
* tests/main/user-session-env: verify env in fish shell
Signed-off-by: Maciej Borzecki <maciej.zenon.borzecki@canonical.com>
* tests/main/user-session-env: tweak comments
Signed-off-by: Maciej Borzecki <maciej.zenon.borzecki@canonical.com>
* data/env: provide reasonable default if XDG_DATA_DIRS is unset in fish shell
Fixes: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1960702
Signed-off-by: Maciej …

data/env: more workarounds for even older fish shells, provide reasonable defaults (2.54)

---

tests/main/interfaces-network-manager/task.yaml

Install network-manager from different channels depending on system
under test. Due to tight integration with UC, each UC version requires
a different NM snap.

t/m/interfaces-network-manager: use different channel depending on system

---

overlord/snapstate/backend/link.go
systemd/emulation.go
wrappers/core18.go
wrappers/core18_test.go

Do not call reload-daemon or restart services on core when preseeding, use EumulationMode. The unit test is based on the existing test for non-preseeding case.
There is a TODO about user services which will currently call `systemctl enable --global --user` .. without `--root`; this needs changes to EmulationMode which I'd like to address separately. I didn't see any issues when testing the prototype without it, but it probably needs to be handled via emulation mode for completeness and consistence with the rest.

wrappers: do not reload the deamon or restart snapd services when preseeding on core

---

dirs/dirs.go
osutil/cp.go
overlord/snapstate/backend.go
overlord/snapstate/backend/copydata.go
overlord/snapstate/backend/copydata_test.go
overlord/snapstate/backend/export_test.go
overlord/snapstate/backend_test.go
snap/info.go

Adds backend functions related to ~/Snap initialization and removal.

o/snapstate: add ~/Snap init related to backend

---

tests/main/snap-confine-tmp-mount/task.yaml

This test has been seeing failing once when executing snap-confine
with stdout and stderr being redirected into separate files, but
understanding the reason of the failure is nearly impossible without
these files being printed into the logs.

tests: add debugging to snap-confine-tmp-mount

---

cmd/snap-preseed/main_test.go
image/export_test.go
image/image_linux.go
image/image_test.go
osutil/mkfs/mkfs.go
seed/seed.go
seed/seed20.go
seed/validate.go

There are two changes here that are needed for ubuntu-image to support the --snap flag for classic image builds.
seed/seed.go: This change adds the NumSnaps and Iter functions to the seed interface. This is needed because there is a specific use case that requires ubuntu-image to parse seed.yaml and iterate through the snaps to create a list of the snaps and their channels. There is already a TODO for this task.
image/image_linux.go: This change is necessary to use image.Prepare on a prebuilt rootfs for which there is no model assertion. In this case the GenericClassicModel from sysdb is used

seed,image: changes necessary for ubuntu-image to support preseeding extra snaps in classic images

---

overlord/snapstate/export_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_test.go

The validation of refresh.retain value is too lax and allows a string to be passed, e.g.
```
$ sudo snap set system refresh.retain=\"2\"
$ sudo snap get system refresh.retain
2
$ sudo snap get -d system refresh.retain
{
"refresh.retain": "2"
}
```
Same thing is of course possible when using our REST API.
(using -d flag reveals it's stored as string; note that `snap set system refresh.retain=\"aaa\"' will fail, so we are good on that front).
This causes an issue in snapstate where refresh.retain value is read; unexpected type is silently ignored and we revert to the default retain value (2 or 3 depending on classic/core).
The PR fixes this by expecting either a json.Number or string. 
This fixes LP: #1947724

o/snapstate: deal with potentially invalid type of refresh.retain value due to lax validation

---

cmd/snap-mgmt/snap-mgmt.sh.in
packaging/debian-sid/snapd.postrm
packaging/ubuntu-14.04/snapd.postrm
packaging/ubuntu-16.04/snapd.postrm

Since we have possibly removed systemd unit files, a daemon-reload is in order.

cmd/snap-mgmt, packaging: trigger daemon reload after purging unit files

---

spread.yaml

This is because all the tests that use lxd are failing with the
following/similar error
+ VERSION_ID=20.04
+ lxd.lxc launch --quiet ubuntu:20.04 my-ubuntu
Error: Failed to run: /snap/lxd/current/bin/lxd forkstart my-ubuntu
/var/snap/lxd/common/lxd/containers
/var/snap/lxd/common/lxd/logs/my-ubuntu/lxc.conf:
Try `lxc info --show-log local:my-ubuntu` for more info
-----
I'll create another change to revert this to edge.

tests: get lxd snap from candidate channel

---

boot/assets_test.go
boot/makebootable_test.go
boot/seal_test.go
overlord/managers_test.go

Couple of fixes for running unit tests on arches other than amd64.
See the failures of snapd builds on LP for amhf, arm64, s390s, ppc64el,  eg: https://launchpadlibrarian.net/588462410/buildlog_ubuntu-jammy-arm64.snapd_2.54.3-0~202203011107~ubuntu22.04.1_BUILDING.txt.gz

overlord, boot: fix unit tests on arches other than amd64

---

interfaces/builtin/kernel_module_load.go
interfaces/builtin/mount_control.go
interfaces/builtin/shared_memory.go
interfaces/connection.go
interfaces/connection_test.go
interfaces/export_test.go
metautil/export_test.go
metautil/type_conversions.go
metautil/type_conversions_test.go
snap/export_test.go
snap/info.go
snap/info_test.go

Same commits as in https://github.com/snapcore/snapd/pull/11248 (the only conflict was on the polkit interface test, which is absent in the release branch).

many: backport attrer interface changes to 2.54

---

osutil/export_test.go
overlord/export_test.go
testutil/base.go
testutil/mocking_test.go

testutil: add generic mocking helpers
Two generic mocking helpers have been added:
- `testutil.MockAny()` - allows mocking of any mutable object with a compliant substitute,
it also return a restore function that shall be called to restore the original value
- `testutil.(*BaseTest).MockAny()` - allows mocking of any mutable object with a compliant substitute,
unlike the API above, this one takes care of restoring the original value on its own

testutil: add generic mocking helpers

---

boot/makebootable_test.go

One last fix for tests failing on non amd64:
```
FAIL: makebootable_test.go:791: makeBootable20Suite.TestMakeRunnableSystem20RunModeSealKeyErr
makebootable_test.go:893:
c.Assert(err, IsNil)
... value *errors.errorString = &errors.errorString{s:"cannot copy trusted asset to cache: read /tmp/check-855608922/49/run/mnt/ubuntu-seed: is a directory"} ("cannot copy trusted asset to cache: read /tmp/check-855608922/49/run/mnt/ubuntu-seed: is a directory")
```
google:ubuntu-18.04-32:tests/unit/go is passing now

boot: mock amd64 arch for mabootable 20 suite

---

data/selinux/snappy.te

Which can happen when there is a system key mismatch. Caught in the wild on
Fedora.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2057103

data/selinux: allow the snap command to run systemctl

---

packaging/ubuntu-16.04/rules

The machines running the tests are not currently fast enough to reliably pass
or be trusted, so for now just disable the tests. We will re-enable them when
we have time to adjust the tests for real or when we have better hardware that
can actually complete tests in a reasonable amount of time.

packaging/ubuntu-16.04/rules: don't run unit tests on riscv64

---

interfaces/builtin/cpu_control.go

This is needed for some kernels with the mentioned patch where individual
monitoring of CPU's can be achieved by these files.
See also ticket 00329266 and LP bug 1962447

interfaces/cpu-control: add extra idleruntime data/reset files to cpu-control

---

interfaces/builtin/network_control.go

Currently the only place these rules are exposed is in the network-manager
slot, which is only intended to be slotted by network-manager itself, but there
are valid use cases to be able to call these D-Bus endpoints for a snap
managing the network that is not network-manager too, so add them here.
Fixes: https://bugs.launchpad.net/snapd/+bug/1962501

interfaces/network-control: add D-Bus rules for resolved too

---

osutil/disks/disks_linux.go
osutil/disks/disks_linux_test.go

Some particular devices seem to have a hard time around being able to do lots
of requests to the udev database, where getting udev properties for the gadget
asset update task will work and then getting udev properties for the specific
bootloader disk devices will fail because some properties are missing, but
waiting for them like we do here resolves this issue and ensures that all
properties are available when we query them here.

osutil/disks: trigger udev on the partition device node

---

interfaces/apparmor/backend.go
interfaces/apparmor/backend_test.go
interfaces/ifacetest/backendtest.go

These unit tests were missing from the CVE branch, so proposing them now
instead.
Also fix a typo which we didn't have time to properly address while preparing
the branch in private.

interfaces/apparmor: add missing unit tests for special devmode rules/behavior

---

tests/main/mount-ns/task.yaml

This is created after installing qemu-tools, and apparently is not
needed.

tests/main/mount-ns: unmount /run/qemu

---

overlord/snapstate/flags.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_prereq_test.go
overlord/snapstate/snapstate_install_test.go

Make sure that the transactional flag is enforced when having
transactional updates with prerequirement snaps.

o/snapstate: implement transactional lanes for prereqs

---

tests/main/user-session-env/task.yaml

It was observed that the bash profiles on Tumbleweed do not contain
/usr/local/share in XDG_DATA_DIRS. The system seems to provide a non empty
default value, hence the defaults our profile provides are not applied.

tests/main/user-session-env: special case bash profile on Tumbleweed

---

interfaces/builtin/account_control.go
tests/main/interfaces-account-control/account-control-consumer-core20/bin/chpasswd
tests/main/interfaces-account-control/account-control-consumer-core20/bin/deluser
tests/main/interfaces-account-control/account-control-consumer-core20/bin/useradd
tests/main/interfaces-account-control/account-control-consumer-core20/meta/snap.yaml
tests/main/interfaces-account-control/task.yaml

Useradd can reach out to pam_tally2 to reset the login counter, in which case it
gets blocked by AppArmor with:
apparmor="DENIED" operation="exec" profile="snap.test.test"
name="/usr/sbin/pam_tally2" pid=5056 comm="useradd" requested_mask="x"
denied_mask="x" fsuid=0 ouid=0
Fixes: https://bugs.launchpad.net/snapd/+bug/1958640
See https://github.com/shadow-maint/shadow/blob/1882c66bda31e50367d41b36fea41cd04fa19c73/src/useradd.c#L2678 for reference

interfaces/builtin/account-control: allow to execute pam_tally2

---

interfaces/builtin/browser_support.go

This is needed for Firefox to set realtime priority on its AudioIPC child
processes (https://bugzilla.mozilla.org/show_bug.cgi?id=1755684).

interfaces/browser-support: allow RealtimeKit's MakeThreadRealtimeWithPID

---

tests/main/snapd-sigterm/task.yaml

The maximun time allowed to stop snapd on arm devices needs to be higher
than 5 seconds because those devices are slower than the google vms
Those are some time examples that I got from a dragonboard. Other
devices are showing similar times.
ubuntu@localhost:~$ date +"%T.%3N" && sudo systemctl stop snapd.service
&& ./retry -n 100 --wait 0.1 --quiet sh -c 'systemctl is-active
snapd.service | grep -Eq "inactive"' && date +"%T.%3N"
12:30:08.833
Warning: Stopping snapd.service, but it can still be activated by:
snapd.socket
12:30:17.368
ubuntu@localhost:~$ date +"%T.%3N" && sudo systemctl start snapd.service
&& ./retry -n 100 --wait 0.1 --quiet sh -c 'systemctl is-active
snapd.service | grep -Eq "^active"' && date +"%T.%3N"
12:40:44.515
12:40:45.614
ubuntu@localhost:~$ date +"%T.%3N" && sudo …

tests: increase the times in snapd-sigterm for arm devices

---

tests/main/interfaces-cups-control/task.yaml

The last update for cups package produced failures for the cups related
tests. The research showed that the problem is with the cups deb
package.
To ensure snapd is not responsible of the error, I created a new debian
sid image with not snapd installed and run:
dmesg command is showing some denials as well:
[   13.532910] audit: type=1400 audit(1646305531.156:14):
apparmor="DENIED" operation="capable" profile="/usr/sbin/cupsd" pid=470
comm="cupsd" capability=12  capname="net_admin"
I tried the same in debian-11 and it works well

tests: skip interfaces-cups-control from debian-sid

---

spread.yaml
tests/main/boot-state/task.yaml
tests/main/os.paths/task.yaml
tests/main/os.query/task.yaml
tests/main/snapd-state/task.yaml
tests/main/snaps-state/task.yaml

The idea is to avoid spending time validating testing tools on other
backends such as external.
Those tests are making longer the edge/beta validations for example.

tests: validate tests tools just on google and qemu backends

---

overlord/state/task.go
overlord/state/task_test.go
overlord/state/taskrunner_test.go

Make the transition from AbortStatus to DoneStatus a noop in task's SetStatus. This is to avoid the race where if the tasks are in same change and lane but run concurrently (i.e. they are not chained) and one of them fails, taskrunner would abort the other that's currently in Doing, and if the aborted task explicitly sets own status to DoneStatus, it wouldn't get undone.
The sequence of events is as follows:
- handler of task A gets started in a go routine, its state is "Doing". State is not locked by taskrunner when it enters the "do" handler of the task.
- at the same time another independent task B in same change fails with an error. With that, taskrunner aborts all tasks in the lane - this includes task A.
- taskrunner sets task A status to "Abort" (this would lead to transition to …

o/state: fix undo with independent tasks in same change and lane

---

interfaces/apparmor/template.go

In jammy, the full path for the dynamic linker has changed to
/usr/lib/{arch}-linux-gnu/ld-linux-{arch}.so.{1,2}
change that so things like ldd can work confined.

i/a/template.go: add ld path for jammy

---

interfaces/apparmor/template.go

The base apparmor template already includes the various VarLink sockets but
is missing the one from systemd-machined. Support was recently added
upstream in https://gitlab.com/apparmor/apparmor/-/merge_requests/861 so
this change ensures we keep the base template up to date in this regard
too.

interfaces/apparmor: Update base template for systemd-machined

---

build-aux/snap/snapcraft.yaml

Commands `mksquashfs`, `unsquashfs`, `fc-cache-v{6,7}` all load
`libz.so.1` from host. If it disappears or the ABI changes, they will
fail. So zlib needs to be packed in the snap.
To verify that a binary has all their dependencies, one can run in the root of the snap, for example:
```
LD_TRACE_LOADED_OBJECTS=1 ./lib64/ld-linux-x86-64.so.2 --library-path "${PWD}/lib/x86_64-linux-gnu:${PWD}/usr/lib/x86_64-linux-gnu" ./usr/bin/mksquashfs
```

snap: Add missing zlib

---

overlord/devicestate/devicestate_install_mode_test.go

A tiny change to split a mock helper which bundles creating a gadget and setting
it up in the state, with creating a model.

o/devicestate: split mocks to separate calls for creating a model and a gadget

---

interfaces/builtin/opengl.go

/proc/sys/dev/i915/perf_stream_paranoid is used to allow toggling Intel
Graphics metrics collection to non-root users. The firefox snap (at
least) reads this during startup (but doesn't try to write to it) which
causes log noise but otherwise seems to work ok. Since the contents are
a simple integer value, there is nothing sensitive in the file, so allow
snaps that plug opengl to read the file.
References:
- https://github.com/intel/pti-gpu#prerequisites

interface/opengl: allow read on /proc/sys/dev/i915/perf_stream_paranoid

---

cmd/snap/cmd_run.go
cmd/snap/cmd_run_test.go
snap/snapenv/snapenv.go
snap/snapenv/snapenv_test.go
tests/main/hidden-snap-dir/task.yaml

~This is based on https://github.com/snapcore/snapd/pull/11431 so only commits from fd486e65a8 (including) matter.~ fd486e65a8 sets environment variables related to the core22 migration. b95356d27e refactors and updates the spread tests

cmd: set core22 migration related env vars and update spread test

---

cmd/snap-preseed/export_test.go
cmd/snap-preseed/main.go
cmd/snap-preseed/preseed_classic_test.go
cmd/snap-preseed/preseed_linux.go
cmd/snap-preseed/preseed_uc20_test.go

Support for `--core20` flag with snap-preseed command. Initialize required mountpoints and run snapd inside a chroot to initialize preseeding. Contrary to the classic case, here I use `chroot` command to run this in a subprocess, so that mountpoints can be cleaned up properly.
TODO: this will get moved to a different package to be callable from prepare-image code. I'll do this in a dedicated followup PR.

cmd/snap-preseed: support for core20 preseeding

---

asserts/account.go
asserts/account_key.go
asserts/asserts.go
asserts/model.go
asserts/repair.go
asserts/snap_asserts.go
asserts/system_user.go
bootloader/grub.go
bootloader/uboot.go
daemon/api_base_test.go
gadget/install/encrypt.go
overlord/devicestate/devicectx.go
snap/info.go

This commit replaces the use of "sanity" with more inclusive
naming. When `// sanity` is used to check if an interface is
implemented the comment `expected interface is implemented`
is used.

many: replace use of "sanity" for interface implementation checks

---

.github/workflows/macos-quick.yaml

In order to move to a more inclusive naming we need to replace
the word "sanity" with something more inclusive like "quick".
This commit does that for the (user visible) workflow output.

github: replace "sanity check" with "quick check" in workflow

---

overlord/managers_test.go

While investigating a problem reported by a customer, we've observed that their
refresh sequence also includes additional snaps. Extend the managers level tests
to include a snap that is not a kernel nor a base.

overlord: extend single reboot test to include a non-base, non-kernel snap

---

dirs/dirs.go

This is unused, and we do not have any "meta" dir under
"/var/lib/snapd/" since Snappy was removed in 2016 with commit
82c1b27bfe8b076bb9a2faaa430688e71705092a.

dirs: remove unused SnapMetaDir variable

---

tests/main/hidden-snap-dir/task.yaml

This fix is to prevent that thes snap.yaml file of the test-snapd-tools
is modified to make it "base: core22" because in the following tests
where we do "snap try test-snapd-tools", it fails with the error:
- Ensure prerequisites for "test-snapd-tools" are available (cannot
install snap base "core22": no snap revision available as specified)

tests: fix test to avoid editing the test-snapd-tools snap.yaml file

---

daemon/api_quotas_test.go
overlord/configstate/configcore/vitality_test.go
overlord/managers_test.go
overlord/servicestate/internal/quotas_test.go
overlord/servicestate/quota_control_test.go
overlord/servicestate/quota_handlers.go
overlord/servicestate/quota_handlers_test.go
overlord/servicestate/servicestate_test.go
overlord/snapstate/backend/link_test.go
snap/quota/export_test.go
snap/quota/quota.go
snap/quota/quota_test.go
snap/quota/resources.go
snap/quota/resources_builder.go
snap/quota/resources_test.go
strutil/strutil.go
strutil/strutil_test.go
wrappers/services.go
wrappers/services_test.go

This is the third PR implementing cpu quotas, but it is the first of three incoming PRs. The purpose of this new PR series is to split up the primary PR which is too large #11252.
The PR has the following changes:
snap/quota: implement the new quotas
snap/quota: implement use of builder pattern for the quota.Resources
overlord:      correct tests after switching to builder pattern
daemon:      correct test after switching to builder pattern
wrappers:    implement the underlying functionality to write the new quotas to systemd slice file

snap: add new cpu quotas 

---

interfaces/seccomp/template.go

close_range was added to kernel 5.9. For snap-seccomp to actually use
this information, libseccomp 2.5.2 or later is needed.

i/seccomp/template.go: add close_range to the allowed syscalls

---

spread.yaml

This also fixes the error in test lxd-postrm-purge

tests: use lxd from edge to avoid issues not fixed on candidate yet

---

snap/quota/export_test.go
snap/quota/quota.go
snap/quota/quota_test.go

This is another followup PR from https://github.com/snapcore/snapd/pull/11410 that handles additional cases in the quota tree validation code. There was unfortunately a bug in how groups were validated if we were changing parent quotas when sub-quotas were in effect.

snap/quota: fix bug in quota group tree validation code

---

overlord/snapstate/backend_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go

At present, the user-daemons feature flag in snapd is disabled by default. However, we'd like to be able to make the snapd-desktop-integration snap (which relies on the feature) installable anyway. This PR disables the feature flag check if the snap ID matches the that of snapd-desktop-integration (as shown by running `snap info snapd-desktop-integration`).
I had originally considered also including a check for the snap name to help test unpublished versions of the snap (where there will be no snap ID), but determined that would be unnecessary: we can just enable the feature flag for that testing.

o/snapstate: allow installing the snapd-desktop-integration snap even if the user-daemons feature is otherwise disabled

---

cmd/snap/cmd_find_test.go
cmd/snap/cmd_info_test.go
cmd/snap/cmd_known_test.go
cmd/snap/cmd_routine_portal_info_test.go
cmd/snap/cmd_run_test.go

Go vet in 1.18 is more picky about fmt.*rintln and additional newlines at the
end of output, thus producing errors like:
```
./cmd_info_test.go:1197:4: fmt.Fprintln arg list ends with redundant newline
./cmd_info_test.go:1201:4: fmt.Fprintln arg list ends with redundant newline
./cmd_routine_portal_info_test.go:101:4: fmt.Fprintln arg list ends with redundant newline
./cmd_routine_portal_info_test.go:161:4: fmt.Fprintln arg list ends with redundant newline
./cmd_run_test.go:1755:5: fmt.Fprintln arg list ends with redundant newline
```
See https://github.com/golang/go/issues/49350 and https://go.dev/doc/go1.18#vet
Although I believe we should not be hitting this case, still it does not make
sense to output so many newlines, so it's worth fixing.

cmd/snap: make 1.18 vet happy

---

interfaces/builtin/network_control.go
interfaces/builtin/network_manager.go

Allow more calls to systemd-resolved dBus interface from the
interfaces that can control network resources. These new calls are
being used now by NetworkManager in jammy. Also, point to more
up-to-date documentation for the interface.

i/b/network_{control,manager}.go: add more access to resolved

---

interfaces/builtin/modem_manager.go

org.freedesktop.DBus.ObjectManager is now used in libmm-glib, so it
gets called by clients accessing the ModemManager daemon. Add access for it.

i/b/modem-manager: provide access to ObjectManager

---

cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
cmd/snap-bootstrap/initramfs_systemd_mount.go
cmd/snap-bootstrap/initramfs_systemd_mount_test.go

In a previous change, we removed a lot of useless dependencies in
mounts generated by `snap-bootstrap initramfs-mounts`. But because of
some cleanup was done also on core22, we get an issue with a missing
dependency from `local-fs.target`. Mounts get unmounted in the main
boot of core22 (not core20) because they are not part of any active
target.

snap-bootstrap: Partially revert simplifications of mount dependencies

---

overlord/state/change.go
overlord/state/change_test.go

A helper for aborting all lanes that aren't ready in a given change. An unready
lane is one that carries tasks which have not reached a final status yet.

overlord/state: add helper for aborting unready lanes

---

boot/seal.go
kernel/fde/device_unlock.go
kernel/fde/fde.go
kernel/fde/fde_test.go
kernel/fde/reveal_key.go

We need to specify the PartitionName for ICE decryption since it is currently
based on partition name as well as the mapper device provided in Device.
Also allow mocking the actual call to runFDEDeviceUnlockCommand from other 
packages without all the complexity of creating hook scripts and such, and add
some more debug logging.
All originally from @mvo5 in other branches.

kernel/fde: add PartitionName to various structs 

---

cmd/snap-update-ns/change_test.go

Hopefully this works better as the previous branch still fails in LP.
This was confirmed to work in a test PPA, see https://launchpad.net/~anonymouse67/+archive/ubuntu/snapd-test-ppa/+build/23489436
Still not really sure what happened where /opt/foo-runtime was getting created but oh well this works.

cmd/snap-update-ns: actually use entirely non-existent dirs

---

interfaces/builtin/kubernetes_support.go

These are the same rules found in the greengrass-support interface.

i/b/kubernetes_support: add access to Java certificates

---

cmd/snap-update-ns/change_test.go
packaging/arch/PKGBUILD
packaging/debian-sid/changelog
packaging/fedora/snapd.spec
packaging/opensuse/snapd.changes
packaging/opensuse/snapd.spec
packaging/ubuntu-14.04/changelog
packaging/ubuntu-16.04/changelog

Unfortunately this PR has a few extra things in it beyond just the packaging changes, but luckily it's just these 2 PR's:
As well as the changelog stuff for 2.55.2 and 2.55.1. 
Before reviewing this, please also go back and review the changelog in https://github.com/snapcore/snapd/pull/11550 which is the very large changelog between 2.54.4 and 2.55.

release: sync 2.55 back with master

---

tests/lib/nested.sh

This is to avoid issues like we see sometimes from google-nested:ubuntu-18.04-64:tests/nested/manual/devmode-snaps-can-run-other-snaps:
```
+ snapcraftctl pull
[Errno 13] Permission denied: '/root/project/tests/nested/core/hotplug/core18.snap'
Traceback (most recent call last):
File "/snap/snapcraft/6512/lib/python3.6/site-packages/snapcraft/file_utils.py", line 105, in link_or_copy
link(source, destination, follow_symlinks=follow_symlinks)
File "/snap/snapcraft/6512/lib/python3.6/site-packages/snapcraft/file_utils.py", line 139, in link
os.link(source_path, destination, follow_symlinks=False)
OSError: [Errno 18] Invalid cross-device link: '/root/project/tests/nested/core/hotplug/core18.snap' -> '/root/parts/snapd-deb/src/tests/nested/core/hotplug/core18.snap'
```

tests/lib/nested.sh: rm core18 snap after download

---

spread.yaml
tests/main/lxd-postrm-purge/prep-snapd-in-lxd.sh
tests/main/lxd/prep-snapd-in-lxd.sh

This workaround is to avoid error (function not implemented) in lxd when
it is being removed.

tests: workaround lxd issue lp:10079 (function not implemented) on prep-snapd-in-lxd

---

debug-tools/snap-debug-info.sh

This is the first iteration of the debug script for debugging customer issues,
with a collection of easily gathered and commonly requested information that is
helpful in debugging issues on Ubuntu Core.
Eventually this will become a snap command and a REST API endpoint, but for now
a script will have to do.

debug-tools/snap-debug-info.sh: add debug script

---

snap/quota/resources_test.go

We did not really check that when `Resource.Change()` got called
we also call `Validate()` on the new resulting `Resource`.
This commit adds these missing tests for the various resource types.

quota: add some more unit tests around Resource.Change()

---

sandbox/cgroup/cgroup.go
sandbox/cgroup/cgroup_test.go

During the review of #11534 it was noticed that the exiting error
message if the cgroup version cannot be detected is not very helpful:
```
cannot determine filesystem type: no such file or directory
```
instead the error should give useful context that it tried to
detect the cgroup version.
This commit fixes this and moves to:
```
cannot determine cgroup version: no such file or directory
```

sandbox: improve error message from `ProbeCgroupVersion()`

---

tests/nested/core/core20-fault-inject/task.yaml
tests/nested/manual/core20-remodel/task.yaml
tests/nested/manual/core20-to-core22/task.yaml

Update some tests to use the new tool and also the new variables to skip kernel/gadget/base repack

tests: adapt nested tests to use tests.nested tool

---

asserts/ifacedecls.go
asserts/ifacedecls_test.go
interfaces/policy/helpers.go
interfaces/policy/policy.go
interfaces/policy/policy_test.go

The use case for this is that we have now the unsupported situation of
an interface that is superprivileged but still wants to have special
system snap slots.
Because it needs to cover also the --dangerous case the
base-declaration slot side slot-snap-type constraint cannot express
this, it needs to allow both core and app. To restrict this as needed
we then allow to use slot-snap-id which can list the well-known system
snap ids.
Notice that this kind of constraint makes sense only in the
base-declaration.  In a snap-declaration the snap-id is fixed and
implied. We also do not want to put interface rules in the actual
snap-declarations of the system snaps.
Although there's no clear use case, as the system snaps don't have
plugs, we support also plug side allow-installation plug-snap-id …

asserts,interfaces/policy: slot-snap-id allow-installation constraints

---

cmd/snap/cmd_debug_state.go
cmd/snap/cmd_debug_state_test.go

The `snap debug state` sorts changes by their change ID, but in a
lexicographical order, hence changes with IDs 1, 2, 10 will be sorted as 1, 10,
2, producing a slightly confusing debug output. Eg.:
```
ID   Status  Spawn               Ready               Label               Summary
1    Done    today at 09:17 UTC  today at 09:18 UTC  seed                Initialize system state
10   Done    today at 09:18 UTC  today at 09:18 UTC  service-control     Running service command for snap "xxx"
11   Done    today at 09:18 UTC  today at 09:18 UTC  configure-snap      Change configuration of "xxx" snap
12   Done    today at 09:18 UTC  today at 09:18 UTC  auto-refresh        Auto-refresh 4 snaps
13   Done    today at 09:18 UTC  today at 09:18 UTC  service-control     Running service command for …
```

cmd/snap/debug: sort changes by their spawn times

---

tests/core/failover/task.yaml

The idea is to remove the $BUILD_DIR always when it is created.
With kernel snap and TRUST_TEST_KEYS = False it was being created but
not deleted making fail the restore invariant checks.
This produces that the whole test suite fails.

tests: fix restore of the BUILD_DIR in failover test on uc18

---

interfaces/builtin/network_manager.go

It turns out that separating the peer targets by commas is an AND,
while here we want an OR, so we need to split the rule.

i/b/network-manager: split rule with more than one peers

---

tests/lib/nested.sh

We currently use `swtpm-mvo` for testing. However this snap is
owned by an individual (me) and it's not clear from the name
that the main purpose of the snap is to test snapd.
So this commit moves to the new `test-snapd-swtpm` snap that
is team maintained in `github.com/snapcore/test-snapd-swtpm`
and has a more suitable name.
Thanks to Ian for the rename of the snap and for modernizing it.

tests: switch to "test-snapd-swtpm"

---

snap/quota/export_test.go
snap/quota/resources_test.go

This test ensures that `Resource.clone()` is really a copy of the
existing resource with all fields copied.
It checks this by creating a `Resource` struct using `reflect` and
then initializes each field with the right type. Then clone() is
called and in the resulting struct it is checked that:
a) all fields are non-nil (i.e. that the clone() did not forgot
to copy a field. This should protect us from adding fields in
the future and forgetting to add them to "clone".
b) all pointers in the fields are different from the original
`Resource`. This ensures we actually create a deep copy
(at least on the first level) and not just assign the pointer
to the same struct in the clone.

quota: add test for `Resource.clone()`

---

spread.yaml

Snapd tests are failing to create a new core image using ubuntu-image
snap from edge channel (rev 275)
This is the error that we see in the logs. The same code works well when
we use ubuntu-image from candidate channel (rev 253)
Bug created: https://bugs.launchpad.net/ubuntu-image/+bug/1966475

tests: moving ubuntu-image to candidate to fix uc16 tests

---

overlord/servicestate/export_test.go
overlord/servicestate/quota_control.go
overlord/servicestate/quota_control_test.go
snap/quota/export_test.go
snap/quota/quota_test.go
snap/quota/resources.go
snap/quota/resources_test.go

This commit adds a check that cpu-set resources can only be set
on systems with cgroup v2.
This is a followup for https://github.com/snapcore/snapd/pull/11534#discussion_r834116997 - the cgroup v2 check was only done client side but must be done on the backend. 
Setting to draft as I'm not 100% sure this is the right place, the `servicestate/quota_control.go` would also be an option but it does not have a natural place to validate a detail like this (AFAICT). Plus we already have systemd handling there so cgroup detection seems not too out of place.

quota: detect/error if cpu-set is used with cgroup v1

---

cmd/snap/cmd_info.go
cmd/snap/cmd_info_test.go
cmd/snap/export_test.go
strutil/strutil.go
strutil/strutil_test.go

Will need this function other places for the model command in snapctl, and it being in cmd/snap was hard to reuse. I hope this looks fine!

strutil: move wrapGeneric function to strutil as WordWrap

---

tests/lib/prepare-restore.sh
tests/main/uc20-create-partitions-encrypt/task.yaml
tests/main/uc20-create-partitions-reinstall/task.yaml
tests/main/uc20-create-partitions/task.yaml

Which fails on 22.04:
```
Run the snap-bootstrap tool
+ go get ../../lib/uc20-create-partitions
+ uc20-create-partitions --encrypt ./gadget-dir '' /dev/loop1
/bin/bash: line 113: uc20-create-partitions: command not found
-----
```

tests/main/uc20-create-partitions: update the test for new Go versions

---

tests/main/interfaces-cups-control/task.yaml

The test is failing in a very similar way to the debian-sid error, but now in all the ubuntu versions. 
The idea is to set as manual until the error is researched a bit more.
The test-snapd-cups-control-consumer was already regenerated, but the
error is not gone.
Error:
+ test-snapd-cups-control-consumer.lpr
/var/snap/test-snapd-cups-control-consumer/current/test_file.txt
+ MATCH 'scheduler not responding'
/snap/test-snapd-cups-control-consumer/17/usr/bin/lpr: Error - No
default destination.

tests: set as manual the interfaces-cups-control test

---

.github/workflows/test.yaml

1.40 seems to be complaining about weird things in latest stable Go job. Let's
see if this one is better.

github/workflows: update golangci-lint version

---

store/store_action.go
store/store_action_test.go

There was a bug where validation-sets were set on actions when
refreshing, but when actual snap actions were transformed into JSON
request the validation-sets field would only get carried over for
"install".
The test didn't catch that because it was "artificially" setting validation-sets key on context data (wouldn't happen in real code - `refreshCandidates` sets v-sets on action struct) and was expecting it on context data as well in the mockServer check.

store: set validation-sets on actions when refreshing

---

gadget/install/encrypt.go
gadget/install/encrypt_test.go
gadget/install/export_secboot_test.go
gadget/install/install.go
kernel/fde/fde.go
kernel/fde/fde_test.go

* Allow running the device-setup hook from install mode in gadget/install package when ICE is used (it never will be in this branch, that is a followup)
* Add some helpers and constants to the kernel/fde package
Originally all from @mvo5

gadget/install, kernel: more ICE helpers/support

---

debug-tools/gce-serial-output-continuously-append.sh

When debugging GCE spread runs where the VM fails to boot properly, you need to
look at the serial console, however doing so with the gcloud command line tool
is a bit finnicky.
This is a bash script which essentially will collect and follow all of the
output on the serial console from a GCE instance.
Hope this helps :wave:

[RFC] debug-tools: add script to help debugging GCE instances which fail to boot

---

snap/info.go
snap/info_test.go
snap/validate_test.go
tests/lib/snaps/test-snapd-service/bin/start-stop-mode
tests/lib/snaps/test-snapd-service/meta/snap.yaml
tests/main/services-stop-mode/task.yaml
wrappers/services_gen_test.go
wrappers/services_test.go

The robotics team needs SIGINT as a stop mode for their ROS snap.
This commit enables `stop-mode: sigint` and `stop-mode: sigint-all`.

snap,wrappers: add `sigint{,-all}` to supported stop-modes

---

bootloader/piboot.go
bootloader/piboot_test.go

Add support for armhf. The difference is that in this case the
pi-kernel snap stores the device trees in a different directory.

bootloader/piboot: add support for armhf

---

cmd/snap/cmd_debug_state.go
cmd/snap/cmd_info.go
cmd/snap/cmd_model.go
strutil/strutil.go
strutil/strutil_test.go

Moved to strutil as its needed for snapctl model as well, also added unit tests for its none exists. I know there might be some overlap between the tests in WordWrapPadded and WordWrap, but because of the modifications happening to the text before it's handed to WordWrap, it makes sense to make sure we test the same width/padding patterns. It actually revealed a flaw with the width check in WordWrap, which is now done differently, as it did not catch all cases before.
Can this skip spread test?

cmd/snap,strutil: move lineWrap to WordWrapPadded

---

tests/core/gadget-config-defaults/gadget-rsyslog.yaml
tests/core/gadget-config-defaults/gadget-ssh-common.yaml
tests/core/gadget-config-defaults/gadget-ssh-oneline.yaml
tests/core/gadget-config-defaults/task.yaml

Extend gadget-config-defaults test with refresh.retain to ensure we handle integers correctly.

tests: extend gadget-config-defaults test with refresh.retain

---

cmd/snap-exec/export_test.go
cmd/snap-exec/main.go
cmd/snap-exec/main_test.go
tests/main/interfaces-cups-control/task.yaml

The cups interface needs a way to set the environment variable
`CUPS_SERVER` if the `cups` interface is connected. However we
have no mechanism for setting environment vars based on interface
connections currently. To workaround this, the cups work added
a workaround in `snap-exec` that tried to detect if `cups` is
connected and when it is set the environment. Unfortunately the
code in there was too simplistic because it just checked if
the directory `/var/cups` exists. However ths dir now always
exists because it's needed as the mount point.
This commit fixes the detection by checking if `/var/cups` is
a bind mount. This is checked by looking at the `stat()` data
and the `dev_t` field in there. If they differ it means the
bind mount exists and the only thing that creates this bind
mount …

snap-exec: fix detection if `cups` interface is connected

---

packaging/ubuntu-16.04/tests/integrationtests

The behaviour of "go get" changes in 1.18 meaning spread does not get
installed to the expected location (or indeed, at all).

packaging: install Go snap from 1.17 channel in the integration tests

---

tests/main/nfs-support/task.yaml

We have quite a few failures like when the nfs `/home` cannot
be unmounted because it's busy.
This commit adds a debug section to get to the bottom of this.

tests: add debug output what keeps `/home` busy

---

sandbox/cgroup/export_test.go
sandbox/cgroup/memory.go
sandbox/cgroup/memory_test.go
snap/quota/resources.go
tests/core/mem-cgroup-disabled/task.yaml

This commit ensures that quotas can only be created/updated if
the memory cgroup is available. Without having the memory cgroup
the snapd memory quota system will not work.

sandbox,quota: ensure cgroup is available when creating mem quotas

---

tests/main/snap-quota-groups/task.yaml

In newer systemd, empty slices can use up to 12KB because of cached memory, and this messed up the memory quota spread test that expects either 0 or 4KB.

tests/main/snap-quota-groups: fix spread test

---

overlord/snapstate/backend.go
overlord/snapstate/backend/copydata.go
overlord/snapstate/backend/copydata_test.go
overlord/snapstate/backend_test.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_test.go
overlord/snapstate/snapstate_update_test.go

This PR is based on the catch-all revert PR https://github.com/snapcore/snapd/pull/11497 so the only relevant commit is d97faecea80cdb5735db3bafd4563c2e3732c44b (and any that may be added later). This makes the initialization of ~/Snap return undo information so that if the operation has to be undone, we know what was created in the current change and what was done in a previous migration. This is relevant because a migration can happen after a previous migration was reverted and, if that fails, we don't want to remove things that were already there (since that would break revert's promise).

o/snapstate: account for repeat migration in ~/Snap undo

---

spread.yaml
tests/lib/image.sh
tests/lib/nested.sh
tests/lib/prepare.sh

While building PRs to snapd, we would normally build u-i using the current snapd
checkout, but that may be unfavorable, as the PR under test may introduce
incompatible changes, thus breaking ubuntu-image. Add an option to build u-i
using the snapd tree it specifies in its go.mod file.

tests: allow ubuntu-image to be built with a compatible snapd tree

---

image/image_test.go
image/preseed/preseed_linux.go
image/preseed/preseed_test.go
overlord/devicestate/firstboot.go
seed/seed.go
seed/seed16.go
seed/seed16_test.go
seed/seed20.go
seed/seed20_test.go
seed/seedtest/seedtest.go
seed/validate.go
spread.yaml
tests/lib/image.sh
tests/lib/nested.sh
tests/lib/prepare.sh

as "install" mode should usually not need much more than the
essential snaps this should require a bit less work when seeding it

seed,many: allow to limit LoadMeta to snaps of a precise mode

---

.golangci.yml
cmd/snap-preseed/preseed_classic_test.go
overlord/snapstate/snapstate_update_test.go

Golangci is currently failing due to some unused code and a gci (https://github.com/daixiang0/gci/issues/54) issue.

many: fix failing golangci checks

---

tests/main/lxd-no-fuse/task.yaml

Now fuse is a snapd dependency so the test needs to check that snaps can be installed when fuse is not installed in lxd.

tests: update the lxd-no-fuse test

---

asserts/membackstore.go
asserts/membackstore_test.go

As this one is in-process there are not backward compatibility concerns.

asserts: extend optional primary keys support to the in-memory backend

---

overlord/managers_test.go

The current code will mock the `amd64` architecutre when running
the manager tests but it does not mock the `grub.cfg:static-cmdline`
or the `grub-recovery.cfg:static-cmdline`. This is needed because
the `bootloader/asserts` package registers the cmdline via `init()`
so this happens before the architecture is mocked in the
`manager_test.go` code. Hence the manager tests will fail when
inspecting the commandline on non amd64/i386 machines.
This commit makes the mocking explicit. An alternative approach
would be to move the snippet registration out of `init()` and
run it on first boot but that has it's own problems so I went
with this approach.
To test this needs to be run either on an arm system or one
needs to edit `assets/grub.cfg` and remove the arches there.

overlord: add missing grub.cfg assets mocks in manager_tests.go

---

interfaces/builtin/u2f_devices.go

Add device ID 1209:BEEE for newly released SoloKeys Solo V2, see
https://github.com/solokeys/solo2-cli/blob/09a4f8edbd43f5b4ffe7e715e05143b9fc815535/README.md
This is needed for my new security key to work with snap-packaged Firefox.

interfaces/u2f-devices: add Solo V2

---

interfaces/builtin/kernel_module_load.go
interfaces/builtin/kernel_module_load_test.go

A kernel module might need to load a file from the filesystem, and we
might have cases where this file is shipped with the snap itself;
therefore, support using $SNAP_COMMON in the kernel module options.

i/b/kernel_module_load: expand $SNAP_COMMON in module options

---

tests/main/interfaces-many-core-provided/task.yaml
tests/main/interfaces-many-snap-provided/task.yaml

We skip the test in trusty butcause it fails with the following error
since was added private /dev/shm support to shared-memory interface
shared-memory plug with "private: true" cannot be connected if
"/dev/shm" is a symlink)

tests: skip the test interfaces-many-snap-provided in trusty

---

client/snap_op.go
client/snap_op_test.go
cmd/snap/cmd_snap_op.go
cmd/snap/cmd_snap_op_test.go
daemon/api_snaps.go
daemon/api_snaps_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_update_test.go

Support --ignore-running flag when refreshing multiple snaps.

many: support --ignore-running with refresh many

---

boot/makebootable_test.go
boot/seal_test.go
bootloader/assets/grub_test.go
bootloader/grub_test.go

This is the same fix as commit 17fbdc7c, but in other tests.
The current code will mock the `amd64` architecture when running some
tests but it does not mock the `grub.cfg:static-cmdline` or the
`grub-recovery.cfg:static-cmdline`. This is needed because the
`bootloader/asserts` package registers the cmdline via `init()` so
this happens before the architecture is mocked in the testing
code. Hence the tests will fail when inspecting the command line on
non amd64/i386 machines.
This commit makes the mocking explicit. An alternative approach would
be to move the snippet registration out of `init()` and run it on
first boot but that has it's own problems so this other approach was
followed.

boot,bootloader: add missing grub.cfg assets mocks in some tests

---

bootloader/export_test.go
bootloader/piboot.go
bootloader/piboot_test.go

Check EEPROM version for RPi4 to make sure that tryboot is
supported. If the EEPROM need updating, return an error when
installing the kernel.

b/piboot.go: check EEPROM version for RPi4

---

packaging/ubuntu-16.04/control

This is a followup for https://github.com/snapcore/snapd/pull/11600.
Instead of a hard dependency on fuse3/fuse it's enough to have
a recommends because fuse is not strictly needed to run snapd.
It is just needed inside lxd.

packaging/ubuntu-16.04/control: recommend `fuse3 | fuse`

---

tests/nested/manual/core20-early-config/task.yaml

This test is failing in uc20 master branch
It fails when doing:
snap set system system.network.netplan.network.bridges.br54.dhcp4=true
with error:
Could not set hostname: Permission denied

tests: disable netplan-cfg test

---

interfaces/builtin/cpu_control.go

With the original rules, the paths in "/sys/devices/system/cpu/cpuX" are
not writable. AppArmor shows error messages, for instance:
```
audit: type=1400 audit(1649300989.268:103): apparmor="DENIED" operation="open" profile="snap.my-snap.init" name="/sys/devices/system/cpu/cpu4/core_ctl/min_cpus" pid=4702 comm="bash" requested_mask="wc" denied_mask="wc" fsuid=0 ouid=0
```
According to the AppArmor Core Policy Reference[1], the globbing syntax
is not correct.
> `*` - match zero or more characters at the directory level. When looking at the path as a string this will match every character except /
So, the following rule mean the CPU ID should be from cpu00* to cpu99*
```
/sys/devices/system/cpu/cpu[0-9][0-9]*/core_ctl/min_cpus rw
```
This patch change the path to be from cpu0* to cpu9*.
[1] …

interfaces/cpu-control: fix apparmor rules of paths with CPU ID

---

data/selinux/snappy.te

As some layouts may place things on top of paths under /var/snap.

data/selinux: allow snap-update-ns to mount on top of /var/snap inside the mount ns

---

interfaces/builtin/system_packages_doc.go
interfaces/builtin/system_packages_doc_test.go
tests/main/interfaces-system-packages-doc/task.yaml

Extend the AppArmor profile snippets for this interface by adding entries that
allow creating a writable mimic over /usr/share and further down.

interfaces/builtin: update apparmor profile to allow creating mimic over /usr/share

---

interfaces/builtin/network_control.go

This is needed for a customer device, see ticket #00318125.
Please hold off on merging until we can get confirmation that this works and is 
sufficient for the customer (hence the blocked label)
But reviews are welcome here.

interfaces/builtin/network-control: also allow for mstp and bchat devices too

---

packaging/ubuntu-16.04/tests/integrationtests

The most recent change in `go get` with go1.18 did not longer
install binaries. However we used this feature in our autopkgtest
script. As a workaround there was a commit to build spread with
go 1.17 to workaround this change.
This commit moves us back to latest go and instead of `go get`
we now use `go install`.
I tested this manually via
```
$ autopkgtest -U snapd_2.54.2.dsc -- qemu ubuntu-20.04-64.img
```
and it works as expected.

packaging: use latest go to build spread

---

interfaces/builtin/hardware_observe.go

Add read access for various device info required by hwinfo utility not covered by existing policy
We are using the hwinfo utility on our Ubuntu Core devices, and to ensure functionality and reduce audit logs it would be great to get this extra policy added.
https://github.com/openSUSE/hwinfo

interfaces/hardware_observe: add read access for various devices

---

cmd/snap/cmd_debug_state.go
cmd/snap/cmd_debug_state_test.go

Add a new flag to snap debug state that helps investigate if a given state
contains task dependency cycles.
On a particularly problematic dump it looks like this:
```
Detected task dependency cycle involving tasks:
Lanes  ID   Status  Spawn                      Ready       Kind                   Summary                                                                      After              Before
2      341  Do      27 days ago, at 09:22 CET  0001-01-01  prerequisites          Ensure prerequisites for "pc-kernel" are available                           [322,323,324,...]  [342,359,360]
2      342  Do      27 days ago, at 09:22 CET  0001-01-01  download-snap          Download snap "pc-kernel" (932) from channel "20/stable"                     [341,322,323,...]  [343,359,360]
2      343  Do …
```

cmd/snap: add check switch for snap debug state

---

overlord/snapstate/autorefresh_test.go
overlord/snapstate/handlers_link_test.go
overlord/snapstate/refresh.go
overlord/snapstate/refresh_test.go
overlord/snapstate/snapstate_install_test.go
tests/main/refresh-app-awareness/task.yaml

Print pids of running processes when BusySnapError is encountered with refresh-app-awareness.

o/snapstate: print pids of running processes on BusySnapError

---

interfaces/builtin/system_observe.go

OpenSearch Snap needs to access /proc/sys/vm/max_map_count and this
has a good fit with the system-observe interface.
For better context, please look at this [link](https://forum.snapcraft.io/t/manual-review-for-opensearch-auto-connect-request-for-mount-observe-and-system-files/29475)

interfaces: add max_map_count to system-observe

---

.github/workflows/naming.yml

The `woke-action` does not have the `reporter` option and running it
generates a warning:
Unexpected input(s) 'reporter', valid inputs are ['github-token', 'woke-args', 'fail-on-error', 'workdir', 'woke-version']

.github: use reviewdog action from woke tool

---

.github/workflows/test.yaml

See
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
for details.
> If you build the group name with a property that is only defined for specific
> events, you can use a fallback value. For example, github.head_ref is only
> defined on pull_request events. If your workflow responds to other events in
> addition to pull_request events, you will need to provide a fallback to avoid
> a syntax error. The following concurrency group cancels in-progress jobs or
> runs on pull_request events only; if github.head_ref is undefined, the
> concurrency group will fallback to the run ID, which is guaranteed to be both
> unique and defined for the run.

github: cancel workflows when pushing to pull request branches

---

debug-tools/snap-debug-info.sh

We start receiving support questions regarding validation sets; let's print some useful data in snap-debug-info script.

snap-debug-info: print validation sets and validation set assertions

---

tests/lib/pkgdb.sh

This dependency is needed to avoid this error.
Currently the error is not happening anymore because the dependency was
manually installed in jammy but it will break again on next image update
Error:
+ tests.device-cgroup test-strict-cgroup-helper.sh dump
WARNING: bpftool not found for kernel 5.15.0-1003
You may need to install the following packages for this specific
kernel:
linux-tools-5.15.0-1003-gcp
linux-cloud-tools-5.15.0-1003-gcp
You may also want to install one of the following packages to keep up
to date:
linux-tools-gcp
linux-cloud-tools-gcp

tests: install linux-tools-gcp on jammy to avoid bpftool dependency error

---

interfaces/builtin/content.go

I guess that skipping spread is fine for this one.

i/b/content: use slot.Lookup() as suggested by TODO comment

---

tests/nested/manual/core20-early-config/task.yaml

The checks cannot execute successfully due to
https://bugs.launchpad.net/ubuntu/+source/netplan.io/+bug/1967084

tests/nested/manual/core20-early-config: disable netplan checks

---

interfaces/builtin/custom_device.go
interfaces/builtin/custom_device_test.go

The udev rules being generated did not include an actual action. We must
use spec.TagDevice in order to actually tag the device.

i/b/custom_device: fix generation of udev rules

---

HACKING.md

The current stable version can do remote builds just fine.

HACKING: update info for snapcraft remote build

---

interfaces/apparmor/backend.go

We are actually using the loadProfiles() call: the code changed with
commit 826e4dc623617cdbecb8989baa557f80a6d761aa but the comment was left
over.

i/apparmor: remove leftover comment

---

cmd/libsnap-confine-private/apparmor-support.c

The call to secure_getenv() can overwrite the `errno` variable because
it internally invokes getauxval(), which could set `errno` to `ENOENT`.
This was discovered examining an error log containing these lines:
run-hook: Error
ERROR run hook "configure":
-----
cannot change profile for the next exec call: No such file or directory
snap-update-ns failed with code 1
-----

libsnap-confine-private: show proper error when aa_change_onexec() fails

---

overlord/snapstate/export_test.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_link_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_test.go

Exclude snapd and core snap from refresh-app-awareness run inhibit checks (followup to #11566)

o/snapstate: exclude TypeSnapd and TypeOS snaps from refresh-app-awareness

---

overlord/snapstate/snapstate_test.go

Two PRs for refresh-app-awareness landed at the same time, one of them enabled r-a-a by default adding expected run-inhibit-snap-for-unlink backend op to `TestSnapdRefreshTasks` test , the other PR however excluded snapd from r-a-a runinhibit logic but since the PRs were independent, this exploded only in master.

o/snapstate: fix TestSnapdRefreshTasks test after two r-a-a PRs

---

image/preseed/preseed_test.go
seed/seed.go
seed/seed16.go
seed/seed20.go
seed/seed20_test.go

This adds Seed.SetParallelism to control this.
Concretely ATM it is only implemented for UC 20+ seeds.

seed: support parallelism when loading/verifying snap metadata

---

tests/main/hidden-snap-dir/task.yaml

This tests how the migration interacts with the revert and refresh
commands. It also checks that the XDG directories are migrated to the
correct locations after the migration.

tests: test migration w/ revert, refresh and XDG dir creation

---

tests/nested/core/interfaces-custom-devices/task.yaml

After adding the proper tagging, the spread test has to be updated as
well, as the regular expression needs to take the TAG assignment into
account.

tests/nested: fix custom-device test

---

tests/main/interfaces-location-control/task.yaml

The new invariant check https://github.com/snapcore/snapd/pull/11693 revealed one more test that has a problem similar to op-remove-retry test (already fixed that one).
This should unblock 11693.

tests: fix interfaces-location-control tests leaking provider.py process

---

overlord/snapstate/backend/copydata.go
overlord/snapstate/backend/copydata_test.go
tests/main/hidden-snap-dir/task.yaml

'snap remove' wasn't removing the snap's user dir under ~/snap or 
~/.snap/data. This caused migrations to fail if a previous migration
occurred before since there was already data in its place. This PR 
fixes that issue and updates the spread test to cover it.

o/snapstate: migration overwrites existing snap dir

---

kernel/fde/cmd_helper.go
systemd/emulation.go
systemd/systemd.go
systemd/systemd_test.go

This commit adds a new `systemd.Run()` function that implements
a wrapper around `systemd-run`. This will be used to spawn
commands that use the `--keyring-mode=inherit` when interacting
with the kernel keyring.

systemd: add systemd.Run() wrapper for systemd-run

---

osutil/cp.go
osutil/cp_test.go
osutil/io.go
osutil/io_test.go

Allow setting desired modification time on AtomicFile and preserve mtime in AtomicWriteFileCopy.

osutil: allow setting desired mtime on the AtomicFile, preserve mtime on copy

---

asserts/snapasserts/snapasserts.go
image/image_test.go
image/preseed/preseed.go
image/preseed/preseed_test.go
overlord/devicestate/firstboot.go
seed/helpers.go
seed/seed.go
seed/seed16.go
seed/seed16_test.go
seed/seed20.go
seed/seed20_test.go
seed/seedtest/seedtest.go
seed/validate.go
spread.yaml

This allows to perform dedicated handling for seed snaps (like copying
them already) together with digest computation.
SnapHandler is slightly complex because of unasserted vs asserted
snaps and the differences how UC16/18 vs 20+ seeds are processed.
Before there was always caching of essential snaps across
LoadEssentialMeta* and LoadMeta, this is turned off if handlers are
provided, OTOH specific caching can be done by handler logic if it makes sense.

many: let provide a SnapHandler to Seed.Load*Meta*

---

boot/assets.go
boot/assets_test.go
boot/export_test.go
boot/makebootable_test.go
boot/seal.go
boot/seal_test.go
daemon/api_system_recovery_keys.go
daemon/api_system_recovery_keys_test.go
gadget/install/encrypt.go
gadget/install/encrypt_test.go
gadget/install/export_secboot_test.go
gadget/install/install.go
gadget/install/install_test.go
gadget/install/params.go
overlord/devicestate/devicestate_install_mode_test.go
overlord/devicestate/devicestate_test.go
overlord/hookstate/ctlcmd/fde_setup_test.go
packaging/debian-sid/rules
secboot/encrypt.go
secboot/encrypt_sb.go
secboot/encrypt_sb_test.go
secboot/keys/export_test.go
secboot/keys/keys.go
secboot/keys/keys_dummy.go
secboot/keys/keys_sb.go
secboot/keys/keys_test.go
secboot/secboot.go
secboot/secboot_sb_test.go
tests/lib/uc20-create-partitions/main.go

As part of the factory-reset work and introducing keymgr in https://github.com/snapcore/snapd/pull/11715 we're moving key types to a separate package secboot/keys.

secboot/keys: introduce a package for secboot key types, use the package throughout the code base

---

interfaces/builtin/custom_device_test.go

Not all hosts use /usr/lib/snapd as libexecdir, some use /usr/libexec/snapd.
Unit tests need to either mock the os-release, or just use the applicable value.

interfaces/builtin/custom-device: fix unit tests on hosts with different libexecdir

---

interfaces/builtin/shared_memory.go

this is the default and some tooling is confused by it being mentioned explicitly

interfaces/builtin: shared-memory drop plugs allow-installation: true

---

tests/lib/tools/boot-state

This fixes smoke-tests on raspberry pi's 3+4 when using piboot.
I don't know if this is the right file to check against, but it seems to be the only one present other than the snap itself

tests/lib/tools: add piboot to boot_path()

---

seed/helpers.go
seed/seed.go
seed/seed16.go
seed/seed16_test.go
seed/seed20.go
seed/seed20_test.go

this should allow to reduce Container.Install work if SnapHandler already copied the snap.

seed: let SnapHandler provided a different final path for snaps

---

overlord/devicestate/devicestate_install_mode_test.go

Turns out we did not mock os-release for install mode tests, and some of the
recently added tests fail on systems which use /var/lib/snapd/snap like so:
```
FAIL: devicestate_install_mode_test.go:606: deviceMgrInstallModeSuite.TestMaybeApplyPreseededData
devicestate_install_mode_test.go:659:
c.Check(osutil.FileExists(filepath.Join(writableDir, dirs.GlobalRootDir, "/snap/essential-snap/1")), Equals, true)
... obtained bool = false
... expected bool = true
devicestate_install_mode_test.go:661:
c.Check(osutil.FileExists(filepath.Join(writableDir, dirs.GlobalRootDir, "/snap/mode-snap/3")), Equals, true)
... obtained bool = false
... expected bool = true
devicestate_install_mode_test.go:663:
c.Check(osutil.FileExists(filepath.Join(writableDir, dirs.GlobalRootDir, …
```

o/devicestate: fix install tests on systems with /var/lib/snapd/snap

---

asserts/account.go
cmd/snap/cmd_find_test.go
cmd/snap/cmd_info_test.go
cmd/snap/cmd_model_test.go
cmd/snap/color.go
cmd/snap/color_test.go
tests/core/basic20/task.yaml
tests/main/listing/task.yaml

This commit adds support for the new account `starred` validation
value. It displays a unicode star "✪" when possible, otherwise
a ascii "*". Note that this also means that validated developers
get a "**" appended now. While this is an incompatible change
it is what was agreeded in the star developers spec because it
is the most natural way to present these values in ascii.
An example for the output is:
```
$ snap info josm
name:      josm
summary:   Editor for OpenStreetMap
publisher: Michael Vogt (mvo✪)
...
```

snap: implement "star" developers

---

interfaces/builtin/steam_support.go
interfaces/builtin/steam_support_test.go
interfaces/policy/basedeclaration_test.go
interfaces/seccomp/template.go
tests/lib/snaps/test-snapd-policy-app-consumer/meta/snap.yaml

This interface is intended to provide some additional permissions needed by the [steam snap](https://snapcraft.io/steam).
At present, this is primarily AppArmor and seccomp rules to allow Steam to launch [pressure-vessel containers](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/tree/master/pressure-vessel), which it uses to provide a consistent runtime environment to some games (at the moment mainly Windows games it runs under Proton/Wine). PV is based on Bubblewrap, as used by Flatpak and various other process sandboxes on GNOME systems.
Related to getting Steam games to run, I've added the [futex_waitv syscall](https://www.kernel.org/doc/html/latest/userspace-api/futex2.html) to the base template. Although the Ubuntu kernels don't yet support this syscall, we want to let …

interfaces: add a steam-support interface

---

overlord/assertstate/assertstate.go
overlord/assertstate/assertstate_test.go
overlord/assertstate/validation_set_tracking.go
overlord/assertstate/validation_set_tracking_test.go
overlord/hookstate/ctlcmd/services_test.go
overlord/snapshotstate/snapshotstate_test.go
overlord/snapstate/autorefresh_gating_test.go
overlord/snapstate/autorefresh_test.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_download_test.go
overlord/snapstate/handlers_prereq_test.go
overlord/snapstate/handlers_rerefresh_test.go
overlord/snapstate/refreshhints_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_remove_test.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go
overlord/snapstate/storehelpers.go
tests/main/snap-validate-enforce/task.yaml

Fix handling of validation set tracking update in enforcing mode when pinning/un-pinning or pinning to another sequence number, including a lower one. Make sure Current points to the latest sequence available in such cases.
Fixes https://bugs.launchpad.net/snapd/+bug/1969216

o/assertstate: fix handling of validation set tracking update in enforcing mode

---

overlord/devicestate/devicestate_install_mode_test.go
overlord/devicestate/handlers_install.go

Use snap handler to copy and calculate digest in one go in `maybeApplyPreseededData`. Use real uc20 seed in the test.

o/devicestate: use snap handler for copying and checksuming preseeded snaps

---

boot/boot.go
boot/boot_test.go
boot/bootstate20.go
boot/flags.go
boot/flags_test.go
boot/makebootable.go
boot/makebootable_test.go
boot/systems.go
bootloader/lk.go
bootloader/uboot.go
cmd/snap/cmd_debug_bootvars.go
gadget/install/install.go
gadget/install/install_test.go
image/image_linux.go
image/image_test.go
overlord/devicestate/devicestate.go
overlord/devicestate/devicestate_remodel_test.go
overlord/devicestate/systems.go
overlord/devicestate/systems_test.go
seed/seedwriter/writer.go

Use UC20+ instead of UC20.
Code comments and test-only strings are not touched here, for clarity they should be changed too, but it's a larger set and can wait.

many: use UC20+/pre-UC20 in user messages as needed

---

.github/workflows/test.yaml
run-checks
tests/unit/go/task.yaml

A change in golang.org/x/sys broke build of misspell and ienffassign
on go 1.13.

.github: skip misspell and ineffassign on go 1.13

---

tests/main/snap-mgmt/task.yaml

This change is to make sure the environent is ok and snapd is
functional.
The change is to make this test work similar to what we do in
postrm-purge.
Whith out this change, when other tests like auto-refresh-gating are
executed after, snapd fails when it is restarted. See the error:
Apr 29 17:40:43 apr291718-620032 systemd[1]: snapd.service: Succeeded.
Apr 29 17:40:43 apr291718-620032 systemd[1]: Stopped Snap Daemon.
Apr 29 17:40:43 apr291718-620032 systemd[1]: Starting Snap Daemon...
Apr 29 17:40:43 apr291718-620032 systemd[1]: Dependency failed for Snap
Daemon.
Apr 29 17:40:43 apr291718-620032 systemd[1]: snapd.service: Job
snapd.service/start failed with result 'dependency'.
Apr 29 17:40:43 apr291718-620032 systemd[1]: snapd.service: Triggering
OnFailure= dependencies.
To reproduce the …

tests: install snapd while restoring in snap-mgmt

---

cmd/snap-update-ns/main.go
cmd/snap-update-ns/system.go
cmd/snap-update-ns/system_test.go
cmd/snap-update-ns/utils.go
cmd/snap-update-ns/utils_test.go
tests/main/interfaces-shared-memory-private/task.yaml

This PR is intended to fix [security bug 1969777](https://bugs.launchpad.net/snapd/+bug/1969777), namely that the private /dev/shm directory created by the shared-memory interface is not created with the correct permissions. It was intended to be world writable with the sticky bit, but would often be created without the sticky bit, or even with `0755` permissions.
This was caused by two bugs in snap-update-ns:
1. the `MkDir` and `MkFile` utility functions would mask out any file permission bits not matching `0777` when creating directories and files respectively.
2. When invoked by snapd to update an existing mount namespace, snap-update-ns would inherit snapd's umask. This prevents it from creating files/directories that are group or world writable.
For (1), I've removed the `.Perm()` …

cmd/snap-update-ns: correctly set sticky bit on created directories where applicable

---

tests/lib/pkgdb.sh

The tests are failing to repack the kernel snap with the error
cpio: premature end of archive
This happens because the lz4 dependency is not installed in the system
Error:
+ cd repacked-kernel
+
unpackeddir=/home/gopath/src/github.com/snapcore/snapd/tests/main/abort/repacked-kernel
++ grep -Po 'config-\K.*'
++ ls config-5.15.0-27-generic
+ kver=5.15.0-27-generic
+ objcopy -j .initrd -O binary kernel.efi initrd
+ unmkinitramfs initrd unpacked-initrd
cpio: premature end of archive

tests: add lz4 dependency for jammy to avoid issues repacking kernel

---

interfaces/apparmor/template.go

Numfmt is a tool for formatting numbers. It should be allowed by the base
template.
Fixes: https://bugs.launchpad.net/bugs/1971074

interfaces/apparmor: allow executing /usr/bin/numfmt in the base template

---

snap/quota/resources.go
snap/quota/resources_builder.go
snap/quota/resources_test.go

To clarify intentions and also better support the maximum resolution for the 'Period' member. This was a small oversight. 
Systemd (and us) support a resolution down to microseconds, and thus I have decided to store the Period as microseconds. My original intent was to have this member be a time.Duration, however this type does not support json marshalling, and I really wanted to avoid writing my own custom type with custom marshalling code for that.
Thanks to @mardy for catching this!
**UPDATE:**
Changed to a time.Duration as it seems it works just fine when marshalling a time.Duration through json, that was my mistake - I had misunderstood reports about this, and should have tested how it worked before jumping to conclusions.

snap/quota: change the journal quota period to be a time.Duration

---

tests/core/mem-cgroup-disabled/task.yaml

The idea is to skip the tests for external backends by using the backends
field. By doing that the test is not executed at all on any external
device.

tests: skip external backend in mem-cgroup-disabled test

---

tests/main/user-session-env/task.yaml

Since a few days both openSUSE tumbleweed and 15.3 seem to behave as
expected, and the tweaks we had for them in the tests are not needed
anymore.

tests/main/user-session-env: remove openSUSE-specific tweaks

---

tests/regression/mount-order-regression/task.yaml

This is needed because gnome-3-38-2004 snap is not available for i386
and in beta validation it is also used the systems ubuntu-core-16-32 and
ubuntu-core-18-32

tests: skip mount-order-regression test on ubuntu-core for i386

---

image/preseed/preseed_linux.go
image/preseed/preseed_uc20_test.go

Unmounting of base snap was attempted before unmounting of paths mounted by handle-writable-paths, this resulted in a umount error (since mountpoint was busy) reported to stdout (umount errors are only logged, they are not fatal here);
this resulted in `/tmp/preseed-*` not getting cleaned up.
Also added a few missing newlines in messages printed to stdout.

image/preseed: umount the base snap last after writable paths

---

osutil/disks/disks_darwin.go
osutil/disks/disks_linux.go
osutil/disks/disks_linux_test.go

Helper for getting the partition UUID of a mount point source, which then can be
used to build /dev/disk/by-partuuid/<dev> path.

osutil/disks: helper for obtaining the UUID of a partition which is a mount point source

---

go.mod
go.sum
tests/unit/go/task.yaml

See https://github.com/seccomp/libseccomp-golang/pull/85 for details. Also fixes
https://github.com/seccomp/libseccomp-golang/issues/89.
Fixes: https://bugs.launchpad.net/bugs/1972119
This is a list of changes in libseccomp-golang: https://github.com/seccomp/libseccomp-golang/compare/9da99da69b1b425f6e8ebb86fa61a656b84c6dcd...f57e1d55ea18cbace22a9eefbd5e83417a2c1ace

deps: bump libseccomp to include build fixes, run unit tests using CC=clang

---

secboot/keymgr/keymgr_luks2.go
secboot/keymgr/keymgr_luks2_test.go

Add another helper to remove a recovery key, but authorize the operation with an existing key. The use case is removal of a recovery key from ubuntu-save in a run mode system, where the ubuntu-save key isn't in the kernel keyring, but rather is readily available on disk.

secboot/keymgr: remove recovery key, authorize with existing key

---

overlord/snapshotstate/snapshotstate.go
overlord/snapshotstate/snapshotstate_test.go

Make 'snap save' check if the snaps are installed before running the
tasks, so the returned error has the expected 'kind' and message format.
Signed-off-by: Miguel Pires <miguel.pires@canonical.com>

o/snapshotstate: check installed snaps before running 'save' tasks

---

.github/workflows/test.yaml

By default when a github actions job is re-executed, just the failed tests are executed. 
If the pr has a label called "Run all", then all the tests are going to be executed in case the job failed previously.
Once this pr is merged, the "Run failed" label will be removed

tests: run failed tests by default

---

overlord/snapstate/handlers.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go
tests/main/hidden-snap-dir/task.yaml

During the roadmap sprint in Copenhagen we had a discussion about
the behavior of the ~/Snap folder migration. Unfortunately there
seems to have been some misunderstandings in the previous plan
and during the discussion it became apparent that is considered
to risky to migrate all the snaps with `base: core22`.
Instead we will most likely create an experimental option to
opt-in into the ~/Snap folder for selected snaps to get feedback
and gather data what snaps behave well and which are problematic.
Based on these results we will then decide if:
a) we do the migration at a future point automatically for all snaps
b) if allow snaps to opt-in into the migration via a flag in snap.yaml
c) migrate with core24
This is an initial commit to remove the current automatic migration
for core22 based …

snapstate: do not auto-migrate to ~/Snap for core22 just yet

---

overlord/snapstate/handlers.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go
tests/main/hidden-snap-dir/task.yaml

This is https://github.com/snapcore/snapd/pull/11763 for 2.55 - sadly the test change did not apply cleanly from the cherry-pick

snapstate: do not auto-migrate to ~/Snap for core22 just yet (2.55)

---

interfaces/builtin/block_devices.go
interfaces/builtin/block_devices_test.go

This is needed for microceph as ceph-osd requires locking the block
device it's using. As that's a pretty common pattern for software
writing to block devices, it's reasonable to just extend the existing
interface to allow it.
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

interfaces: Allow locking in block-devices

---

overlord/snapshotstate/backend/backend.go
overlord/snapshotstate/backend/backend_test.go
overlord/snapshotstate/backend/export_test.go
overlord/snapshotstate/backend/helpers.go
overlord/snapshotstate/backend/reader.go
snap/info.go

The addToZip function was highly coupled with the snap directory structure which
made it hard to add things to the snapshot. This refactor separates pre-condition
checks, logic coupled to the snap directory structure and the actual writing
logic. This should make it easier to add ~/Snap while also being simpler overall.
Also refactors the reading logic a bit.

o/snapshotstate: refactor snapshot read/write logic

---

cmd/snap/cmd_find.go
cmd/snap/cmd_find_test.go
tests/main/searching/task.yaml

Thus trying to mimic what apt search does. Thus, one does not have to run:
```
snap find "hello world"
```
to narrow down the results, but can run:
```
snap find hello world
```
Fixes: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1972910

cmd/snap: join search terms passed in the command line

---

interfaces/builtin/posix_mq.go
interfaces/builtin/posix_mq_test.go

This is a small followup for PR#11590 - it makes the code in
getPath() a bit more linear and adds some more tests for (uncommon)
error conditions. A small typo in `validatePath()` was found and
fixed this way too.

interfaces: tweak getPath() slightly and add some more tests

---

secboot/keymgr/keymgr_luks2.go
secboot/keymgr/keymgr_luks2_test.go

Extend secboot/keymgr tests to cover a scenario in which cryptsetup fails with some arbitrary error. Add a helper to identify keyslot full errors. Unfortunately there's no smarter way to introspect the errors coming out from snapcore/secboot cryptsetup
wrappers our code is based on. Unfortunately there's no reasonable way to identify particular error coming from cryptsetup either, even though the manpage lists different error exit statuses, trying to use an occupied error falls under 'parameters' and has the status 1 which is shared with other errors.

secboot/keymgr: extend unit tests, add helper for identify keyslot used error

---

overlord/snapstate/handlers.go

Master is failing because of deadcode introduced in https://github.com/snapcore/snapd/pull/11763. This PR comments out this function so that the checks pass. I'm working on another PR to do a more extensive removal of unnecessary code based on what can be reworked for the new approach and what will most likely not be used.

o/snapstate: remove deadcode breaking static checks

---

snap/quota/quota.go
snap/quota/quota_test.go

The second PR in the journal quota support series; add the neccessary support for journal quotas in snap/quota/quota.go

snap/quota: add values for journal quotas (journal quota 2/n)

---

interfaces/builtin/mount_control.go
interfaces/builtin/mount_control_test.go
tests/lib/snaps/test-snapd-mount-control/meta/snap.yaml

AppArmor is very strict when it comes to specifying the target of a
mount rule: when the mount refers to a directory, the target *must* end
with a "/", or AppArmor will block the operation. We did not catch this
in our tests because we have always been ending our "where" attributes
with a "**", that also matches slashes.
So, we update the rule to allow for an optional "/" at the end of the
mount target specification; note that our regular expression for the
validation of the mount target attribute is written in such a way that
an ending slash is not allowed. For the time being this seems proper,
because we don't want to expose this subtlety to the developer.

i/b/mount_control: add an optional "/" to the mount target rule

---

interfaces/builtin/opengl.go
interfaces/builtin/opengl_test.go

This adds the appropriate AppArmor and UDEV rules and accompanying tests for using the GPU on NXP i.MX platforms that use the Vivante GPU driver.

interfaces: opengl: add rules for NXP i.MX GPU drivers

---

interfaces/builtin/hardware_observe.go

Allow read access to the thermal sysfs from the hardware-observe
interface. See Documentation/driver-api/thermal/sysfs-api.rst in the
kernel for reference.

i/b/hardware-observe.go: add access to the thermal sysfs

---

interfaces/builtin/network_manager.go

The network-manager interface does not currently provide the AppArmor rules for configuring bridges, resulting in the following denial (among others):
```
= AppArmor =
Time: Apr 27 10:57:12
Log: apparmor="DENIED" operation="open" profile="snap.network-manager.networkmanager" name="/sys/devices/virtual/net/br0/bridge/vlan_filtering" pid=2863 comm="NetworkManager" requested_mask="w" denied_mask="w" fsuid=0 ouid=0
File: /sys/devices/virtual/net/br0/bridge/vlan_filtering (write)
Suggestions:
* adjust program to not access '/sys/devices/virtual/net/br0/bridge/vlan_filtering'
* adjust program to not access '/sys/devices/virtual/net/br[0-9]*/bridge/vlan_filtering'
```
This can be reproduced by creating a bridge interface using `nmcli` from the `network-manager` snap:
```
$ sudo nmcli con add …
```

interfaces: network-manager: add AppArmor rule for configuring bridges

---

interfaces/builtin/dm_crypt.go
interfaces/builtin/dm_crypt_test.go

I created a snap that tries to use `cryptsetup` utility and installed it in `dev-mode`. According to the logs; it requires access to the  `/run/cryptosetup/` directory and also creates file(s) inside.
```
= AppArmor =
Time: May 11 11:55:03
Log: apparmor="ALLOWED" operation="open" profile="snap.test-content-slot.slot-exec" name="/run/cryptsetup/" pid=720119 comm="cryptsetup" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
File: /run/cryptsetup/ (read)
Suggestions:
* adjust program to use $SNAP_DATA
* adjust program to use /run/shm/snap.$SNAP_NAME.*
* adjust program to use /run/snap.$SNAP_NAME.*
* adjust snap to use snap layouts (https://forum.snapcraft.io/t/snap-layouts/7207)
= AppArmor =
Time: May 11 11:55:03
Log: apparmor="ALLOWED" operation="mknod" …
```

interfaces: allow access to the file locking for cryptosetup in the dm-crypt interface

---

interfaces/builtin/opengl.go

On RISC-V (or at least the SiFive Unmatched) the PCI devices show up under the platform subtree:
```plain
/sys/devices/platform/soc/e00000000.pcie/pci0000:00/0000:00:00.0/
├── 0000:00:00.0:pcie001
├── 0000:00:00.0:pcie002
├── 0000:00:00.0:pcie010
├── 0000:01:00.0
├── aer_dev_correctable
├── aer_dev_fatal
├── aer_dev_nonfatal
├── aer_rootport_total_err_cor
├── aer_rootport_total_err_fatal
├── aer_rootport_total_err_nonfatal
├── ari_enabled
├── broken_parity_status
├── class
├── config
├── consistent_dma_mask_bits
├── current_link_speed
├── current_link_width
├── device
├── devspec
├── dma_mask_bits
├── driver -> ../../../../../../bus/pci/drivers/pcieport
├── driver_override
├── enable
├── irq
├── link
├── local_cpulist
├── local_cpus
├── max_link_speed
├── max_link_width
├── modalias
├── …
```

interfaces: fix opengl interface on RISC-V

---

cmd/snap/cmd_model.go

This is the followup PR for https://github.com/snapcore/snapd/pull/11612. This replaces the existing printing logic in 'snap model' with the code added in 11612.

cmd/snap: replace existing code for 'snap model' to use shared code in clientutil (2/3)

---

tests/main/auto-refresh-gating/task.yaml

The test auto-refresh-gating is failing sporadically while snapd.socket is restarted with error 'start-limit-hit'.
The solution is to reset-failed before the snapd.socket is restarted.
To reproduce the issue run: 
-> spread-debug -debug -order -workers 1  google:centos-8-64:tests/main/snap-quota google:centos-8-64:tests/main/auto-refresh-gating
This is the issue:
● snapd.socket - Socket activation for snappy daemon
Loaded: loaded (/usr/lib/systemd/system/snapd.socket; enabled; vendor
preset: disabled)
Active: failed (Result: start-limit-hit) since Mon 2022-05-16
16:23:46 UTC; 11min ago
Listen: /run/snapd.socket (Stream)
/run/snapd-snap.socket (Stream)
May 16 16:23:46 may161603-595563 systemd[1]: Starting Socket activation
for snappy daemon.
May 16 16:23:46 may161603-595563 systemd[1]: …

tests: fix auto-refresh-gating test forcing reset-failed before restart

---

interfaces/apparmor/backend.go
interfaces/apparmor/spec.go
interfaces/apparmor/spec_test.go
interfaces/backend.go
interfaces/mount/backend.go
interfaces/mount/spec.go
interfaces/mount/spec_test.go
overlord/ifacestate/ifacestate_test.go

In preparation of adding support for journal namespace bind mount, we need to be able to add additional mount entries based on the current state of the snap (/whether the snap is in a quota group with a journal quota for instance), to mimic what systemd does during setup.
This is a followup PR based on my first attempt at adding this support, and with some guidance from Samuele, see https://github.com/snapcore/snapd/pull/11672.

interfaces,overlord: add support for adding extra mount layouts

---

cmd/snap-bootstrap/cmd_recovery_chooser_trigger.go
cmd/snap-bootstrap/cmd_recovery_chooser_trigger_test.go
cmd/snap-bootstrap/export_test.go
cmd/snap-bootstrap/triggerwatch/evdev.go
cmd/snap-bootstrap/triggerwatch/export_test.go
cmd/snap-bootstrap/triggerwatch/triggerwatch.go
cmd/snap-bootstrap/triggerwatch/triggerwatch_test.go
data/systemd/snapd.recovery-chooser-trigger.service.in

Keyboard drivers and the drivers for the bus they are plugged into are
not necessarily initialized by the time udev has settled cold plug
events. That means we have to read events for new input devices and
read those keyboards.
Also because the daemon is started in initramfs and needs to write
into the file system, it needs to chroot when switch root happens.
There are 2 things to decide in this PR:
- What should be the proper way to notify the switch root. This PR uses SIGUSR1. But we could use an RPC for example using dbus. That way we could pass the path too the new root for example.
- Now we always wait 10s before starting snapd. Before, it would not wait if no keyboard was found. Should we have a second timeout, like if after 3s no keyboard was found, we cancel.
- `osutil/udev` has …

cmd/snap-bootstrap: Listen to keyboard added after start and handle switch root

---

interfaces/builtin/removable_media.go
interfaces/builtin/removable_media_test.go

This PR is intended to help address https://github.com/canonical/steam-snap/issues/9 in the Steam snap. Steam allows the user to change the location where it stores games it downloads. While we are not trying to support arbitrary locations with the snap, one common case is to place the library on a volume mounted in `/media`. We almost support this by plugging the `removable-media` interface. Unfortunately, the AppArmor restrictions of that interface do not include execute permission.
This PR adds map and execute permissions for files under `/mnt/` and `/media/*/` to address this. As per @alexmurray's comment, it isn't worth making this configurable since a snap can already execute files found in these locations by first copying them to `$SNAP_USER_DATA`.

interfaces: allow map and execute permissions for files on removable media

---

cmd/snap/cmd_routine_portal_info.go
cmd/snap/cmd_routine_portal_info_test.go

Expose the application common ID in portal info, so that it can
be used to manage the application via Freedesktop Appplication API.

portal-info: Add CommonID Field

---

interfaces/udev/udev.go
interfaces/udev/udev_test.go

The old code would run unnecessary `udevadm trigger` commands in a
couple of situations:
1. If a subsystem other than "input" was specified, the trigger for it
would be run twice: once because of the unconditional call to
`udevadm --subsystem-nomatch=input`, and once because of the call to
`udevadm --subsystem-match=<subsystem>`.
2. If both "input" and "input/keys" are part of the subsystem list,
there's no need to run a trigger specific to the keys: running the
trigger for the whole "input" subsystem is enough.
Note that I do not understand the "FIXME" comment. I see that the history of this code is in https://github.com/snapcore/snapd/pull/5250, but it's not clear to me why we cannot update the subsystem list on interface removal. If you know the reason, please let me know -- maybe that …

interfaces/udev: refactor handling of udevadm triggers for input

---

cmd/snap-fde-keymgr/main.go
cmd/snap-fde-keymgr/main_test.go

Make the action of add-recovery-key idempotent, at least to the extent that's
practical.

cmd/snap-fde-keymgr: best effort idempotency of add-recovery-key

---

build-aux/snap/snapcraft.yaml

This will ensure that the "stable" build for riscv64 happens from the right branch.
Note that this is against "beta-riscv64" not **master**.
The build for riscv64 for beta/stable happens in https://launchpad.net/~snappy-dev/+snap/snapd-beta-riscv64

snapcraft.yaml: bump stable branch to release/2.56

---

testutil/errorischecker.go
testutil/errorischecker_test.go

This PR adds a new test checker that will be used to replaced error equality checks in tests for their `ErrorIs` equivalent. The idea is that some of the usages of `ErrNoState` don't have all the relevant information and some should even have entirely different error messages. Before we can replace `ErrNoState` where it's returned, we want to change the places that consume it to use `errors.Is` so that we can then change the return sites gradually. Ticket with context: https://warthogs.atlassian.net/browse/SNAPDENG-120
The next PR will replace the equals checker with this one, in the appropriate test checks, as well as occurrences of `!=` and `==` with the `errors.Is(...)` equivalent.

testutil: add ErrorIs test checker

---

wrappers/services.go

The function was quite long and complex, and I need to add the journal config files that need to written as well, so I wanted to split out the different things it did to make it easier to read/maintain

wrappers: refactor EnsureSnapServices

---

tests/main/upgrade-from-release/task.yaml

This commit adds a spread test that ensures that the first version
of a ubuntu release can be upgraded to the latest version of snapd.

tests: add spread test to test upgrade from release snapd to current

---

interfaces/builtin/modem_manager.go
interfaces/builtin/modem_manager_test.go

Classic systems provide their own ModemManager along with it's own DBus
policy - if we also generate DBus policy for ModemManager when a snap plugs
this interface, this will likely conflict with the DBus policy from the
classic system itself and cause unexpected results. As such, only generate
DBus policy for ModemManager when a snap plugs this interface on
non-classic systems (ie. Ubuntu Core etc).
See
https://forum.snapcraft.io/t/dbus-access-denied-while-using-modem-manager-plug-in-snap/29037/12
for background and discussion.
-------

interfaces/modem-manager: Don't generate DBus plug policy

---

interfaces/builtin/serial_port.go
interfaces/builtin/serial_port_test.go

Add support for USB gadget serial devices.
ttyGSX: drivers/usb/gadget/legacy/g_serial.c
Document: https://www.kernel.org/doc/Documentation/usb/gadget_serial.txt
I also changed the variable IDs, so it would be easier to add new serial devices.

interfaces/serial-port: add ttyGS to serial port allow list

---

.github/workflows/riscv64-builds.yml

Use github actions workflow to trigger daily riscv64 snapd edge
builds.

.github: Trigger daily riscv64 snapd edge builds

---

cmd/snap/cmd_changes.go
cmd/snap/cmd_snap_op.go
cmd/snap/cmd_snap_op_test.go
cmd/snap/error.go
cmd/snap/main.go

Snap always returned a 0 exit code when an operation failed due to the
snap not existing. This changes the default handling of that error to
return a non-zero exit code, except for 'snap remove' (since the result
is achieved).
LP bug: https://bugs.launchpad.net/snapd/+bug/1968609
Signed-off-by: Miguel Pires <miguel.pires@canonical.com>

cmd/snap: exit w/ non-zero code on missing snap

---

interfaces/builtin/shared_memory.go
interfaces/builtin/shared_memory_test.go

Allow snaps to mmap and link files under their own shared-memory
paths. Fixes LP: #1974464.
-------

interfaces/shared-memory: Update AppArmor permissions for mmap+link

---

systemd/systemd.go
systemd/systemd_test.go
usersession/agent/export_test.go
usersession/agent/rest_api.go
usersession/agent/rest_api_test.go
wrappers/services.go
wrappers/services_test.go

This patch relates to:
https://github.com/snapcore/snapd/pull/11340
In the process of improving the systemd stop code to better track
the progress of stopping units, we also removed the snapd concept
of a timeout period in order to exclusively rely on
'systemctl stop' to return an error after its internal stop
escalation process failed.
We therefore no longer can produce a 'Timeout' error.
This patch removes code in the code base that used to deal
with this 'Timeout' condition.
The idea behind this patch is that we trust 'systemctl stop'
to tell us if it failed to stop a unit within its configured
timeout, and if it fails, there is nothing more we can do but
to return an error.
Signed-off-by: Fred Lotter <fred.lotter@canonical.com>

systemd: remove the systemctl stop timeout handling

---

tests/core/netplan-cfg/task.yaml

This fixes parts of LP #1967084 by not enabling dhcp4 on the bridge
interface in the netplan-cfg test. The reason is that the bridge
will never be connected to a network so with the previous dhcp4=true
setting the interface will always be in the "configuring" state.

tests: set `br54.dhcp4=false` in the netplan-cfg test

---

tests/lib/nested.sh

From logs when preparing nested suite on 16.04:
```
+ '[' -n '' ']'
1855
/home/gopath/src/github.com/snapcore/snapd/tests/lib/nested.sh: line 809: UBUNTU_IMAGE_PRESEED_ARGS[@]: unbound variable
```

tests/lib/nested: fix unbound variable

---

spread.yaml
tests/lib/nested.sh

The relevant fixes for ubuntu-image are in their tree
https://github.com/canonical/ubuntu-image/commit/a5da68af0c46fad0575505ac44e4c2f14a707313
we can build it from master again.
Based on top of #11820 so that the nested tests on core 16 run.

spread: switch back to building ubuntu-image from source

---

interfaces/builtin/accounts_service.go

Looking at the history of this interface, it doesn't seem that the idea
was that of supporting Ubuntu OnlineAccounts as well; it seems more
likely that the `/com/ubuntu/...` is a copy&paste error, since it's the
only line referring to UOA in the whole interface.
Since GLib D-Bus client library by default introspects the objects when
a proxy is created, let's correct these lines (instead of just removing
them).
The most conservative step would be that of adding this rule with the
`deny` prefix, since having the rule with the wrong path was essentially
leading to the same result (aside from the suppressed warning), but that
would not buy us anything in terms of security or privacy: the
`Introspect` method only describes the D-Bus API of the object, and even
if a client was trying to abuse …

i/b/accounts_service: fix path of introspectable objects

---

cmd/snap-confine/mount-support-nvidia.c
cmd/snap-confine/mount-support.h

Here are a few cleanups, prompted by the new PR about a WSL2 mount-support module (https://github.com/snapcore/snapd/pull/11785).
There are just 4 small commits, but reviewing them as a whole can be a bit messy. I recommend have a look at each commit one by one to see the individual changes and the rationale.

cmd/snap-confine: mount support cleanups

---

interfaces/builtin/README.md

At the moment, this document explains the format of the base
declaration, and should help interface developers to write the various
`allow-*` and `deny-*` rules about installation, connection and
auto-connection.
This is heavily based on our internal "Brand store" documentation.

interfaces/builtin: add README file

---

cmd/snap/cmd_quota.go

Add help strings for `snap set-quota` options. Note, the whole quotas feature is
still considered experimental, hence the commands are hidden and go-flags only
prints out the top level description of the command, without the options in --help.
Related to: https://bugs.launchpad.net/snapd/+bug/1945362
Note this doesn't address the bug fully, we'd either have to make quota-groups an exported feature, or do not hide the commands (and thus consider quota-groups no longer experimental?).

cmd/snap: add help strings for set-quota options

---

tests/main/lxd/task.yaml

We can't launch the inner ubuntu lxd container in google cloud images
See https://github.com/lxc/lxd/issues/10492
See https://bugs.launchpad.net/cloud-images/+bug/1976552
I'll create a new change to revert this

tests: avoid launching lxd inside lxd on cloud images

---

tests/main/nfs-support/task.yaml

The umount command is often failing because the "test" user's
`dbus-daemon` process is still keeping the /home/test directory busy.
systemd-logind will automatically close the session after the test user
has logged out (which happens at the end of the `su` command), but it
allows for a 10 seconds grace period, which we cannot afford to waste.
Therefore, in addition to adding a retry loop to the umount operation,
we also explicitly kill all of the "test" user's processes.

tests/main/nfs-support: be robust against umount failures

---

overlord/snapstate/refresh.go
overlord/snapstate/refresh_test.go
tests/main/services-refresh-mode/task.yaml
tests/main/services-snapctl/task.yaml
tests/main/services-stop-mode-sigkill/task.yaml
tests/main/services-stop-mode/task.yaml

Exclude services from refresh-app-awareness check. So far we would ignore services with "endure" mode only, but there was an issue also with services which use stop-mode:sigterm and leave running child processes during refresh (microk8s). The agreed solution is to exclude services altogether - the assumption is that services generally know what they are doing and since snapd stops them during refresh (except for endure), they do the right thing.
Fixes: https://bugs.launchpad.net/snapd/+bug/1975714

o/snapstate: exclude services from refresh app awareness hard running check

---

interfaces/builtin/browser_support.go

Read-write access is needed to edit Jupyter notebooks. 
https://bugs.launchpad.net/ubuntu/+source/jupyter-notebook/+bug/1959417

interfaces/browser-support: allow editing of Jupyter notebooks in browsers

---

dirs/dirs.go
wrappers/services.go
wrappers/services_test.go

This adds the neccesary code to write journald config files for quota groups with journal quotas.

wrappers: write journald config files for quota groups with journal quotas (3/n)

---

interfaces/builtin/cups_control.go
interfaces/builtin/cups_control_test.go

While testing the CUPS snap, @tillkamppeter noticed that some D-Bus broadcast signals were being blocked by AppArmor.
On closer inspection, the rules related to the `org.cups.cupsd.Notifier` D-Bus interface all had a restriction like `peer=(name=org.freedesktop.DBus,label=...)`. This seemed weird to me, as that name is reserved for dbus-daemon, and these messages are not being sent to or received from the bus. Removing the `name=` restriction allowed the messages to be delivered.
I asked @alexmurray for his opinion, and he couldn't think of a reason the name conditional was included here either, so I've submitted this PR to remove it.
In this case, there isn't a different D-Bus name that could be used in the rule. The messages are sent by a short lived notifier plugin process: …

interfaces/builtin: remove the name=org.freedesktop.DBus restriction in cups-control AppArmor rules

---

cmd/snap/cmd_quota.go
cmd/snap/cmd_quota_test.go
cmd/snap/export_test.go

This is some more cleanup before adding journal quota options as it started to get crowded with parameters.

cmd/snap: cleanup and make the code a bit easier to read/maintain for quota options

---

cmd/snap-fde-keymgr/export_test.go
cmd/snap-fde-keymgr/main.go
cmd/snap-fde-keymgr/main_test.go
secboot/keymgr/export_test.go
secboot/keymgr/keymgr_luks2.go
secboot/keymgr/keymgr_luks2_test.go
tests/main/uc20-create-partitions-encrypt/task.yaml
tests/main/uc20-create-partitions/task.yaml

Make encryption key change a 2 step process. First the new encryption key is staged (i.e. added in a temporary slot), after that, the encryption key is transitioned to become the main one. The first part of the process normally happens during factory reset, while the second in a post-reset run system.

secboot/keymgr, cmd/snap-fde-keymgr: two step encryption key change

---

dirs/dirs.go
overlord/ifacestate/export_test.go
overlord/ifacestate/handlers.go
overlord/ifacestate/handlers_test.go
overlord/ifacestate/helpers.go

When a snap is in a quota group with a journal quota set, we need to add a bind mount from /etc/systemd/journal.<ns> to /etc/systemd/journal to simulate whatever systemd does to support journal namespaces. This code adds this redirect.

overlord/ifacestate: add journal bind-mount snap layout when snap is in a journal quota group (4/n)

---

interfaces/builtin/network_control.go
tests/main/interfaces-network-control/network-control-consumer/meta/snap.yaml
tests/main/interfaces-network-control/task.yaml

Update network-control interface with permissions required by resolvectl: read/query permissions for dbus objects required by resolvectl and permission to execute resolvectl command itself. This was requested by one of the customers.
Fixes https://bugs.launchpad.net/snappy/+bug/1976305

interfaces: update network-control interface with permissions required by resolvectl

---

gadget/gadgettest/examples.go
gadget/update.go
gadget/update_test.go

When testing if a gadget defines implicitly the system data
partition (which can happen for UC16 and UC18), we were checking the
type of the on-disk partition to determine if it was the system data
partition. However, we were testing only if it matched the GPT UUID
partition type, and we were not considering the MBR disk case, which
uses different numbers. Fixes LP:#1978127.

gadget: check also mbr type when testing for implicit data partition

---

gadget/install/install.go
gadget/install/install_test.go
osutil/disks/disks_darwin.go
osutil/disks/disks_linux.go

This is https://github.com/snapcore/snapd/pull/11857 backported to 2.56. Quite a bit of the install.go file changed so a careful look from @bboozzoo is appreciated. 
I tested this locally by cherry-picking https://github.com/snapcore/snapd/pull/11862 [1] to 2.56 and running:
```
$ spread -v qemu-nested:ubuntu-22.04-64:tests/nested/manual/core20-4k-sector-size
...
2022-06-13 13:19:44 Preparing qemu-nested:ubuntu-22.04-64:tests/nested/manual/ (qemu-nested:ubuntu-22.04-64)...
2022-06-13 13:21:13 Preparing qemu-nested:ubuntu-22.04-64:tests/nested/manual/core20-4k-sector-size (qemu-nested:ubuntu-22.04-64)...
2022-06-13 13:31:08 Executing qemu-nested:ubuntu-22.04-64:tests/nested/manual/core20-4k-sector-size (qemu-nested:ubuntu-22.04-64) (1/1)...
2022-06-13 13:31:35 Restoring …
```

gadget/install: do not assume dm device has same block size as disk (2.56)

---

boot/boot.go
boot/export_test.go
boot/seal.go
boot/seal_test.go

A helper in boot that completes the factory reset by rotating the sealed key file and PCR handles.
Contains a small helper from #11870

boot: post factory reset cleanup

---

tests/core/uboot-unpacked-assets/task.yaml

Simple fix to make the test work on devices using uc22

tests: add suport fof uc22 in test uboot-unpacked-assets

---

boot/makebootable_test.go
boot/seal.go
boot/seal_test.go

It is possible that a factory reset attempt is interrupted by a reboot after
sealing the keys, which means that the PCR handles may already have been used
and have TPM resources allocated to them. In such case, we should attempt to
release the handles before sealing for factory reset again.

boot: release the new PCR handles when sealing for factory reset

---

wrappers/services.go
wrappers/services_test.go

Another issue found by my journal spread tests, was that I was writing the LogNamespace= setting to the wrong unit file.

wrappers: fix LogNamespace being written to the wrong file

---

cmd/snap-update-ns/system.go
cmd/snap-update-ns/system_test.go
cmd/snap-update-ns/trespassing_test.go
snap/validate_test.go

This allows the bind mount of /run/systemd/journal.<namespace> to /run/systemd/journal which is required to enable log namespaces.

cmd/snap-update-ns: add /run/systemd to unrestricted paths

---

overlord/assertstate/validation_set_tracking.go
overlord/assertstate/validation_set_tracking_test.go
overlord/hookstate/ctlcmd/services_test.go
overlord/snapshotstate/snapshotstate_test.go
overlord/snapstate/autorefresh_gating_test.go
overlord/snapstate/autorefresh_test.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_download_test.go
overlord/snapstate/handlers_prereq_test.go
overlord/snapstate/handlers_rerefresh_test.go
overlord/snapstate/refreshhints_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_remove_test.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go
overlord/snapstate/storehelpers.go

Support multiple extra-validation sets in EnforcedValidationSets helper. This is needed to support new scenarios related to a list of sets.

o/assertstate: support multiple extra validation sets in EnforcedValidationSets

---

snap/squashfs/squashfs.go
snap/squashfs/squashfs_test.go

The current code in Snap.Unpack() will report a very generic:
` exit status 1` error if `unsquashfs` fails. This commit changes
the code to first look at any unsquashfs errors reported on stderr
and only if none of these are found it will report a (slightly less)
generic error.
This should help diagnose a bug in the pi-kernel refresh where
the Snap.Unpack() of the kernel assets fails.

squashfs: improve error reporting when `unsquashfs` fails

---

asserts/snapasserts/validation_sets.go
asserts/snapasserts/validation_sets_test.go
overlord/assertstate/assertstate_test.go
tests/main/snap-validate-enforce/task.yaml

Store required snap revision (if set in the assertion) for missing snaps in CheckInstalledSnaps as they will be needed when installing snaps to satisfy requested validation sets. This wasn't needed before because we were only reporting an error about missing snaps on `snap validate enforce ...`

asserts: store required revisions for missing snaps in CheckInstalledSnaps

---

cmd/snapd-apparmor/main.go
cmd/snapd-apparmor/main_test.go

This is a small followup for PR#11129 that tests the "main()"
function a bit more.

snapd-apparmor: add more integration-ish tests

---

tests/lib/pkgdb.sh

In opensuse leap 13 I see the following error generated
WARNING: There is 1 new warning. See 'snap warnings'.
and then after run snap warning:
last-occurrence:  today at 14:01 UTC
warning: |
the snapd.apparmor service is disabled; snap applications will likely
not start.
Run "systemctl enable --now snapd.apparmor" to correct this.
This change is fixing 2 tests:
tests/main/snap-info
tests/main/bad-interfaces-warn

tests: enable snapd.apparmor service in all the opensuse systems

---

features/features.go
features/features_test.go
overlord/snapstate/backend.go
overlord/snapstate/backend/copydata.go
overlord/snapstate/backend/copydata_test.go
overlord/snapstate/backend_test.go
overlord/snapstate/handlers.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_test.go

This adds an experimental feature and snapstate support for migrating a snap's home to ~/Snap. This will be used for a debug command to experimentally migrate snaps' homes.

o/snapstate: support migrating snap home as change

---

packaging/arch/PKGBUILD

The snapd-apparmor rewrite branch landed, but Arch packaging was not updated.

packaging/arch: install snapd-apparmor

---

overlord/devicestate/devicemgr.go
overlord/devicestate/devicestate_install_mode_test.go
overlord/devicestate/devicestate_test.go
overlord/devicestate/export_test.go
overlord/devicestate/handlers_install.go
tests/nested/core/core20-factory-reset/task.yaml

Hopefully the last patches for factory reset. The branch adds support for post-factory-reset ensure step, where we verify the fallback key, rotate the encryption keys and drop the marker.

o/devicestate: post factory reset ensure, spread test update

---

cmd/snapd-apparmor/main_test.go

Distros that do not support reexec have an additional line logged in the output,
such that the overall log looks like this:
... value string = "" +
...     "2022/06/22 14:56:34.246323 tool_linux.go:68: DEBUG: re-exec not supported on distro \"arch\" yet\n" +
...     "2022/06/22 14:56:34.250114 main.go:132: Loading profiles [/tmp/check-228349711/6/var/lib/snapd/apparmor/profiles/foo]\n"
Fix the unit test such that it runs correctly everywhere.

cmd/snapd-apparmor: fix unit tests on distros which do not support reexec

---

overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_update_test.go
overlord/snapstate/storehelpers.go

Support requesting validation sets via RevisionOptions and handle them in `installInfo` and `updateToRevisionInfo` store helpers. This is to allow enforcing new validation sets and install/refresh required snaps to satisfy their constraints.

o/snapstate: support passing validation sets to storehelpers via RevisionOptions

---

client/client.go
client/client_test.go
cmd/snap/cmd_debug_migrate.go
cmd/snap/cmd_debug_migrate_test.go
cmd/snap/cmd_snap_op_test.go
daemon/api_debug.go
daemon/api_debug_migrate.go
daemon/api_debug_test.go
daemon/export_test.go

Adds a "migrate-home" action to the /v2/debug endpoint and a corresponding debug command. Based on https://github.com/snapcore/snapd/pull/11858

many: add migrate-home debug command

---

image/preseed/export_test.go
image/preseed/preseed_linux.go
image/preseed/preseed_uc20_test.go

When preseeding fails with an exec-format error this is most likely
because the image is build from a system that has a different
architecture than the target architecture. Here installing the
`qemu-user-static` package is enough to preseed.
This commit adds a slightly more helpful error message in this
situation.

preseed: suggest to install "qemu-user-static"

---

daemon/api.go
daemon/api_snaps.go
daemon/api_snaps_test.go
daemon/api_validate.go
daemon/export_test.go
overlord/assertstate/assertstate.go
overlord/snapstate/snapstate.go

Implement api handler for refresh with validation sets (i.e. for `snap validate --enforce --refresh ...`). 
The two critical functions (`snapstate.EnforceSnaps` and `assertstate.TryEnforceValidationSets`) are stubs in this PR - they are drafted in #11899

daemon: implement api handler for refresh with enforced validation sets

---

build-aux/snap/snapcraft.yaml

At present, the build recipes used to build the official snapd snaps (e.g. https://launchpad.net/~snappy-dev/+snap/snapd-master)  use a PPA to pull in updated versions of some packages in the build. However, the snap built as an artifact of the CI process does not.
Among other things, this means it will be built against an older libseccomp (at present, 2.5.3 is in the PPA, while 2.5.1. is in the base archive), making the snap built by CI less useful for testing.
This PR makes use of [the `package-repositories' section](https://snapcraft.io/docs/package-repositories) to specify the PPA dependency directly in the `snapcraft.yaml` file, so that the snap is built more similarly to official releases.

build-aux/snap: build against the snappy-dev/image PPA

---

cmd/snap/cmd_debug_state_test.go

TestDebugCheckForCycles was failing locally with something like (I truncated the output for brevity): 
```
FAIL: cmd_debug_state_test.go:273: SnapSuite.TestDebugCheckForCycles
... String difference:
...     [2]: "1,2    11   Done    0000-12-31  0000-12-31  foo   Foo task  []     [13]" != "1,2    11   Done    0001-01-01  0001-01-01  foo   Foo task  []     [13]"
...     [3]: "1      12   Do      0000-12-31  0000-12-31  bar   Bar task  []     [13]" != "1      12   Do      0001-01-01  0001-01-01  bar   Bar task  []     [13]"
...     [4]: "2      13   Do      0000-12-31  0000-12-31  bar   Bar task  []     [11,12]" != "2      13   Do      0001-01-01  0001-01-01  bar   Bar task  []     [11,12]"
```
When we print human friendly times, we use the local timezone. In this test, the spawn and ready …

cmd/snap: fix test failing due to timezone differences

---

interfaces/apparmor/template.go

Currently the path in apparmor allows writes to the journal socket/stdout, which resides in `/run/systemd/journal`, which is fine for the default journal. However when journal namespaces are used, a new folder will be created for each namespace. Their paths will look like `/run/systemd/journal.{namespace}`
To support journal namespaces, this change is needed

interfaces/apparmor: add missing apparmor rules for journal namespaces

---

overlord/servicestate/export_test.go
overlord/servicestate/quota_control_test.go
overlord/servicestate/quota_handlers.go
overlord/servicestate/quota_handlers_test.go
overlord/servicestate/servicemgr.go

It was a missing step to get journal quotas to work. The code that adds the redirect in the .fstab for the services is not triggered when putting a snap into or out of a quota group. 
This code now triggers a "setup-profiles" for each snap that is affected by quota changes.

overlord/servicestate: refresh security profiles when services are affected by quotas

---

tests/nested/manual/core20-to-core22/task.yaml

This test is affected by this issue: https://bugs.launchpad.net/snapd/+bug/1979197
A new PR with the revert for this change is going to be created after this one.

tests: disable core20-to-core22 nested test

---

interfaces/builtin/system_observe.go

Adds memory stats to the system observe interface.

interfaces: add memory stats to system_observe

---

cmd/snap-repair/runner_test.go

Using a `Matches` checker will cause the Check() function to print the
string being compared. This can give us some hints on where is the
request coming from (sometimes this test randomly fails on CI).

test: print User-Agent on failed checks

---

tests/main/snap-validate-enforce/task.yaml

This change is to fix in opensuse tumbleweed the error:
+ snap install hello-world
+ MATCH 'error: cannot install "hello-world": cannot install snap
"hello-world" due to'
error: cannot install "hello-world": cannot install snap
"hello-world" due to enforcing rules of validation set
16/xSfWKGdLoQBoQx88vIM1MpbFNMq53t1f/testenforce1/1

tests: fix snap-validate-enforce in opensuse-tumbleweed

---

packaging/fedora/snapd.spec

As go toolset in centos 7 has been updated to 1.17.7-1, we need to
update the spec to reflect that.
This fixes all the boringcripto errors like this:
+ test-snapd-classic-confinement
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]
runtime stack:
runtime.throw({0x723818, 0x0})
/usr/lib/golang/src/runtime/panic.go:1198 +0x71
fp=0x7fff7eebb240 sp=0x7fff7eebb210 pc=0x435211
runtime.sigpanic()
/usr/lib/golang/src/runtime/signal_unix.go:719 +0x396
fp=0x7fff7eebb290 sp=0x7fff7eebb240 pc=0x44a996
goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x5e8250, 0xc00009f6c0)
/usr/lib/golang/src/runtime/cgocall.go:156 +0x5c fp=0xc00009f698
sp=0xc00009f660 pc=0x40551c …

tests: fix boringcripto errors in centos7

---

tests/main/snap-network-errors/task.yaml

The test is failing in uc 16 with error:
+ systemd-resolve --flush-caches
systemd-resolve: unrecognized option '--flush-caches'
Also the test is simplified to support all the systems

tests: fix snap-network-erros on uc16

---

tests/main/upgrade-from-release/task.yaml

When the "upgrade-from-release" tests runs on 16.04 we know
exactly what version to expect (2.48.3) because 16.04 is in ESM
mode and the archive will never change unless one enables ESM.
So force installing this version to ensure that even if some
test or something enables the ppa:snappy-dev/image PPA we always
get the right version.
We should probably also write an invariant test that ensures that
the sources.list does not change between runs but that would be
a followup.

tests: force version 2.48.3 on xenial ESM

---

data/completion/bash/complete.sh
dirs/dirs.go
image/preseed/preseed_classic_test.go
image/preseed/reset.go
overlord/snapstate/backend/aliases.go
overlord/snapstate/backend/aliases_test.go
snap/info.go
tests/completion/indirect/task.exp
tests/completion/indirect/task.yaml
tests/completion/lib.exp0
tests/completion/snippets/task.yaml
tests/core/bash-completion/task.yaml
tests/core/bash-completion/test-completion.py
tests/core/bash-completion/test-rc
tests/lib/prepare.sh
wrappers/binaries.go
wrappers/binaries_test.go

Snapd installs bash completion files from snaps in
`/usr/share/bash-completion/completions` which in some distributions
is a read-only filesystem.
Instead of installing them in `/usr` we can install them within
`/var/lib/snapd` which should always be writable.
To enable that path in bash completions we only need to add the path
to `XDG_DATA_DIRS`.
An alternative could be to install the file in
`/etc/bash_completion.d`.
~~DRAFT: This is incomplete as we need to migrate symlinks in
`/usr/share/bash-completion/completions` to `/var/lib/snapd`~~
Migration of the path was added.

many: install bash completion files in writable directory

---

client/quota.go
client/quota_test.go
cmd/snap/cmd_quota.go
cmd/snap/cmd_quota_test.go
cmd/snap/export_test.go
daemon/api_quotas.go
daemon/api_quotas_test.go
daemon/export_test.go
overlord/ifacestate/handlers.go
snap/quota/quota.go
snap/quota/quota_test.go
wrappers/services.go

This PR adds the frontend for journal quota options, and enables the usage of journal quotas. Spread tests will come in the last and final PR.

client,cmd/snap: add journal quota frontend (5/n)

---

tests/main/apt-hooks/task.yaml

When the store releases core or snapd it will disable the `names`
endpoint and return 403. Example:
```
Jul 08 10:06:01 autopkgtest snapd[46568]: retry.go:61: DEBUG: The retry loop for https://api.snapcraft.io/api/v1/snaps/names?confinement=strict%2Cclassic finished after 1 retries, elapsed time=91.88602ms, status: cannot decode new commands catalog: got unexpected HTTP status code 403 via GET to "https://api.snapcraft.io/api/v1/snaps/names?confinement=strict%2Cclassic"
```
Detect this and skip the test if that happens.
Note that we already support skipping the test if we get 429 but
the store seems to have changed behavior here.

tests: detect 403 in apt-hooks and skip test in this case

---

interfaces/apparmor/template.go

which.debianutils is the binary really invoked when which is run on
core22 bases. Make sure it can be run by default.

i/apparmor: allow calling which.debianutils

---

boot/boot.go
boot/boot_robustness_test.go
boot/boot_test.go
boot/bootstate16.go
boot/bootstate20.go
boot/bootstate20_bloader_kernel_state.go
boot/kernel_os.go
boot/kernel_os_test.go
overlord/managers_test.go
overlord/snapstate/backend/link.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_link_test.go
tests/lib/nested.sh
tests/lib/prepare.sh
tests/nested/core/base-revert-after-boot/task.yaml
tests/nested/core/kernel-revert-after-boot/task.yaml

Some times LinkSnap is called in an undo task when we want to revert
to a previous snap revision. Introduce a flag to make LinkSnap and
boot code aware of when this happen, as some of the logic for snap
installations should not be applied when doing a revert. Specifically,
avoid the "try" logic that applies to kernels and bases: we are
reverting to a known snap that is expected to work, and making the
current snap the fallback provokes failures as we are removing it (and
also probably we are removing it because it has failed).

many: introduce IsUndo flag in LinkContext

---

asserts/database.go
asserts/database_test.go
asserts/export_test.go

Adds a bit more context to the key expiry error.

asserts: add more context to key expiry error

---

interfaces/builtin/display_control.go

Once a developer would like to change the brigness of the display, they get the following AppArmor denials. This PR aims to fix that.
```
apparmor="DENIED" operation="open" profile="snap.my-app.awesome-ui" name="/sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-eDP-1/intel_backlight/brightness" pid=1859 comm="bash" requested_mask="wc" denied_mask="wc" fsuid=0 ouid=0 
```

interfaces/display-control: allow changing brightness value

---

dirs/dirs.go

The code using this variable got removed in 2016 with commit
c30beb38799df9a34c237dca4b1f036eae7a1a0a.

dirs: remove unused SnapAppArmorAdditionalDir

---

tests/main/interfaces-kernel-module-load/task.yaml

The test fails because a module is not found:
modprobe[28208]: FATAL: Module bfq not found.
Given how hard it is to find kernel modules available on all distros,
just drop Centos7.

tests: exclude centos-7 from kernel-module-load test

---

overlord/devicestate/handlers_install.go

There is a use-case for fixupWritableDefaultDirs() to include
the dirs:
```
- /etc/systemd/network
```
to support rename to predicable network names. Eventually this
is something that snapd/netplan will support but to unblock
users this workaround is needed.

devicestate: add more path to `fixupWritableDefaultDirs()`

---

interfaces/apparmor/backend.go
interfaces/apparmor/backend_test.go
interfaces/apparmor/template.go

As a part of the support for per-snap directories on the ubuntu-save partition, we need to allow snaps to access their own folder with read/write permissions. The ubuntu-save partition is mounted at /var/lib/snapd/save.

interfaces/apparmor: add permissions for per-snap directory on ubuntu-save partition

---

packaging/arch/PKGBUILD
packaging/debian-sid/changelog
packaging/fedora/snapd.spec
packaging/opensuse/snapd.changes
packaging/opensuse/snapd.spec
packaging/ubuntu-14.04/changelog
packaging/ubuntu-16.04/changelog

This is the 2.56.3 point release. This should be the last 2.56 release and I would like to release 2.57 to beta as soon as this hits candidate.
Note that this does not include https://github.com/snapcore/snapd/pull/11935 (and it's prerequisites) because there are various cherry pick conflicts and I felt it's probably ok to have this in 2.57 (given that it's coming very soon and this is an issue that is already present for some time).

release: version 2.56.3

---

tests/main/preseed-core20/task.yaml

The idea is to revert the change to use --apparmor-features-dir.
In the other hand the --apparmor-features-dir option seems to be not
working well, so it should be tested as well.
In the logs I see the dire created is var/cache/apparmor/a938305e.0/ but it should be var/cache/apparmor/b678de58.0/ instead because we are using a predefined apparmor-features-dir.

tests: make more robust the files check in preseed-core20 test

---

tests/main/fake-netplan-apply/task.yaml

This test requires a small tweak to the fake `netplan-snap` that
is build during the test.

tests: update fake-netplan-apply test for 22.04

---

tests/main/interfaces-opengl-nvidia/task.yaml

On 22.04+ the /sys/module/apparmor path is used for the userspace
apparmor communication. However the interfaces-opengl-nvidia test
creates a tmpfs on top of /sys/modules to simulate a nvidia
driver.
This commit changes to an overlayfs when possible to simulate
the nvidia driver.

tests: use overlayfs for interfaces-opengl-nvidia test

---

interfaces/builtin/hardware_observe.go

Hi,
The hardware-observe interface already defines the following AppArmor rule `/sys/{block,bus,class,devices,firmware}/{,**} r,`. Therefore, explicit definition of further access requests for specific sysfs paths are not needed and creates confusion. Therefore, this PR aims to remove all unnecessary explicit sysfs paths.
Thanks

interfaces/hardware-observe: clean up reading access to sysfs

---

tests/lib/tools/tests.invariant

Add invariant check for leftover snap.*.scope in /sys/fs/cgroup (meaning a leftover snap process running after the test).
(suggested in the review of #11566)

tests: add invariant check for leftover cgroup scopes

---

tests/nested/manual/core-early-config/task.yaml

The kernel is automatically handled by the nesting code so it's
actually harmful if the tests specifies it as it leads to the
kernel being specified twice on the commandline which breaks
ubuntu-image:
```
2022-07-14T23:58:23.7590500Z + /home/gopath/bin/ubuntu-image snap --image-size 10G /home/gopath/src/github.com/snapcore/snapd/tests/lib/assertions/nested-18-amd64.model --channel edge '' --output-dir /tmp/work-dir/images --snap /tmp/work-dir/assets/snapd-from-deb.snap --snap new-kernel.snap --snap /home/gopath/src/github.com/snapcore/snapd/tests/nested/manual/core-early-config/new-core18.snap --snap /home/gopath/src/github.com/snapcore/snapd/tests/nested/manual/core-early-config/extra-snaps/pc_104.snap --snap /home/gopath/src/github.com/snapcore/snapd/tests/nested/manual/core-early-config …
```

nested: fix core-early-config nested test

---

asserts/asserts.go
asserts/snap_asserts.go
overlord/snapstate/backend_test.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_update_test.go
snap/info.go
snap/info_snap_yaml.go
snap/info_snap_yaml_test.go
snap/info_test.go
snap/naming/validate.go
snap/naming/validate_test.go
snap/validate.go
snap/validate_test.go
store/details_v2.go
store/details_v2_test.go

This adds metadata and snap.Info support including validation for provenance.
Make sure we extract it from store results and make it available as SnapSetup.ExpectedProvenance for installation task for the from-the-store cases.

many: expose and support provenance from snap.yaml metadata

---

daemon/api_apps.go
overlord/servicestate/servicestate.go
overlord/servicestate/servicestate_test.go

These are followup changes to the remaining review comments in https://github.com/snapcore/snapd/pull/11960
Including rename of function, and return an error if one of the AppInfo's received is not a service. (The current usage already makes sure to only provide services)

daemon,overlord/servicestate: followup changes from PR #11960 to snap logs

---

tests/lib/prepare.sh

The
```
google-nested:ubuntu-18.04-64:tests/nested/manual/devmode-snaps-can-run-other-snaps
```
test is currently failing with:
```
...
2022-07-20T10:57:51.7437272Z + snap run snapcraft snap --output snapd-from-branch.snap
...
2022-07-20T10:57:51.8182845Z Pulling snapd-deb
2022-07-20T10:57:51.8182927Z + snapcraftctl pull
2022-07-20T10:57:51.8183224Z [Errno 13] Permission denied: '/root/project/tests/nested/core/hotplug/pc-kernel.snap'
2022-07-20T10:57:51.8183334Z Traceback (most recent call last):
2022-07-20T10:57:51.8183669Z   File "/snap/snapcraft/6512/lib/python3.6/site-packages/snapcraft/file_utils.py", line 105, in link_or_copy
2022-07-20T10:57:51.8183821Z     link(source, destination, follow_symlinks=follow_symlinks)
2022-07-20T10:57:51.8184139Z   File …
```

tests: remove leaking `pc-kernel.snap` in `repack_kernel_snap`

---

tests/nested/manual/connections/task.yaml

This test failed in spread with:
```
2022-07-20T15:05:25.9201971Z ##[error]2022-07-20 15:05:25 Error executing google-nested:ubuntu-20.04-64:tests/nested/manual/connections (jul201353-281932) :
...
2022-07-20T15:41:06.8471005Z + tests.nested exec 'snap connections'
2022-07-20T15:41:06.8471500Z + MATCH 'serial-port  *connections:serial-1  *pc:serial-1'
2022-07-20T15:41:06.8472066Z Warning: Permanently added '[localhost]:8022' (ECDSA) to the list of known hosts.
2022-07-20T15:41:06.8472463Z grep error: pattern not found, got:
2022-07-20T15:41:06.8472863Z -----
```
This is obscure, no output from the nested snap connections but
also no error. This commit adds a bit of debug info around this.

tests: add `debug:` section to `tests/nested/manual/connections`

---

tests/main/refresh-mode-ignore-running/task.yaml

Adds some comments to the new refresh-app-awareness test for `refresh-mode: ignore-running` and makes some of its checks a bit more strict.

tests: improve 'ignore-running' spread test

---

sandbox/cgroup/scanning.go
sandbox/cgroup/scanning_test.go
tests/main/lxd/task.yaml

Refresh app awareness has a bug (https://bugs.launchpad.net/snapd/+bug/1978834) where a refresh of a host's snap is prevented by the same snap running in a LXC container. This happens because we look for matching snaps under any directory in `/sys/fs/cgroup`. This PR fixes the cgroup tracking by skipping over systemd slices associated with containers (in particular, LXC and Docker, I didn't find an exhaustive list).

sandbox/cgroup: ignore container slices when tracking snaps

---

tests/nested/core/save-data/task.yaml

The output of `lsblk` apparently changed between 20.04 and 22.04.
But fortuantely because we are only interested in the LABEL in
this test the way it's run can be simplified a bit.
This also includes a drive-by simplification for another use of `grep` in the test.

tests: fix nested save-data test on 22.04

---

asserts/snapasserts/snapasserts.go
asserts/snapasserts/snapasserts_test.go
image/helpers.go
image/image_test.go
overlord/assertstate/assertmgr.go
overlord/assertstate/assertstate_test.go
seed/seed20.go
seed/seed20_test.go
seed/seedtest/seedtest.go
tests/lib/fakestore/refresh/refresh.go

snap revision fetching and cross-checking should take provenance into
account and also verify device scope constraints for revision
authority delegation
provenance is taken as a hint from the store, but then matching
assertions must be found and then provenance is double checked
a failure of the latter check is likely a sign of a bug or
error as an attacker that can submit or forge/sign a blob could
as well do one with the expected provenance
provenance goals are tracing and avoiding the risk of polluting
the snap-revision namespace
this leaves alone the DeriveSideInfo* functions, mainly used for
asserted local installs, this means they might fail to find a
snap-revision sometimes, they will be updated in a different branch.
This is based on #11969  and is an alternative approach to …

many: device and provenance revision authority cross checks

---

tests/nested/manual/core20-new-snapd-does-not-break-old-initrd/task.yaml

The nested `core20-new-snapd-does-not-break-old-initrd` installs
an old snapd and then refreshes to the new snapd and assume this
only causes a snapd restart. This assumption is incorrect, an
update like this can trigger a reboot if managed assets like
`grub.cfg` or the static commandline change. In this case a
full system reboot is performed.
This commit changes the code to deal with that by simply waiting
for the `snap install new-snapd.snap` to complete via `snap watch`
even if it take a reboot.

tests: fix `core20-new-snapd-does-not-break-old-initrd` test

---

asserts/snapasserts/snapasserts.go
asserts/snapasserts/snapasserts_test.go
daemon/api_sideload_n_try_test.go
overlord/devicestate/systems_test.go
seed/seedwriter/helpers.go

snapasserts.DeriveSideInfo* cannot deal with snap-revisions with the
same hash but different provenance in the local system assertion
database, this should be an acceptable limitation for a while
the seedwriter code now assumes that the input can be trusted, this is
reasonable
systems.go uses already installed snaps, so it's fine but probably
would still be good to address the TODO in it for efficiency/clarity
as the code in seedwriter DeriveSideInfo is even more clunky now for
this use case, we should be able to find an applicable snap-revisions
by other means

many: support non-default provenance snap-revisions in DeriveSideInfo*

---

tests/lib/prepare-restore.sh
tests/main/microk8s-smoke/task.yaml

The `tests/main/snap-run` test started to fail recently with:
```
2022-07-15T09:44:48.5703039Z [ 3998.633647] audit: type=1400 audit(1657878283.165:55207): apparmor="DENIED" operation="sendmsg" profile="snap.microk8s.daemon-containerd" pid=207855 comm="calico-node" family="netlink" sock_type="raw" protocol=0 requested_mask="send" denied_mask="send"
```
The most likely reason is that the `tests/main/microk8s-smoke` test
started to produce DENIALS. To ensure we catch this early this
commit adds a check for "DENIED" messages.
Maybe we should even create an invariant test for new DENIALS?

tests: ensure that microk8s does not produce DENIED messages

---

interfaces/builtin/desktop.go
interfaces/builtin/unity7.go

All the rules touched in this commit are about D-Bus signals. We want
the D-Bus daemon to forward them to any listening processes, so it's not
correct to limit them to the D-Bus daemon only.
Opening as a draft as I'm not sure this is correct. The fact that all D-Bus signals have this specification makes me thing that maybe this is intentional and that the rule might be like this because of some internal logic to the D-Bus AppArmor module of how signals are being treated.
Incidentally, I wonder if having the `label=unconfined` label is correct -- don't we want these signals to potentially reach any listening process, including confined snap applications?
@alexmurray, @jhenstridge: waiting for your feedback, on whether this is needed/correct at all.

i/b/desktop,unity7: remove name= specification on D-Bus signals

---

interfaces/builtin/posix_mq.go
interfaces/builtin/posix_mq_test.go

Posix message queue paths can now either be specified as a single string or an array of strings. This allows consolidating many slots with different paths and identical permissions into a single slot.
E.g.:
```
slots:
test-string:
interface: posix-mq
path: /test-default
test-path-array:
interface: posix-mq
path:
- /test-array-1
- /test-array-2
- /test-array-3
```

interfaces: posix-mq: allow specifying message queue paths as an array

---

tests/main/interfaces-network-control/task.yaml

The test fails to install network-control-consumer with the error:
Ensure prerequisites for "network-control-consumer" are available
(cannot install snap base "core20": no snap revision available as
specified)

tests: skip interfaces-network-control on i386

---

interfaces/builtin/opengl.go
interfaces/builtin/steam_support.go

This adds a few additional permissions to the steam-support interface. In particular:
* grant execute access to everything in `/usr/bin` and `/usr/sbin`. Inside the pressure-vessel container, `/usr` is provided by the Steam Runtime, and any of the binaries found there could be used by the sandboxed game. We are not yet trying to transition to a sub-profile for the PV sandbox yet (not really sure how achievable that'd even be), so this also grants exec access to those paths in the base snap before entering the sandbox.
* PV tries to bind mount the individual Nvidia driver files into the sandbox, so we let it do that too. It's possible more is needed after this though.

interfaces/builtin: add more permissions for steam-support

---

tests/main/lxd/task.yaml

The commented out checks are invalid and can be permanently removed,
as per the discussion in https://github.com/lxc/lxd/issues/9447.

tests: remove commented code from lxd test

---

spread.yaml
tests/lib/image.sh
tests/lib/prepare.sh

The binary is built using snapd master branch and it is uploaded to gce daily
Last binary was built on https://github.com/snapcore/spread-cron/runs/7529001261?check_suite_focus=true
The script used to build the 
https://github.com/snapcore/spread-cron/blob/master/branches/build-ubuntu-image-withtestkeys/target/tasks/build-ubuntu-image/task.yaml

tests: get the ubuntu-image binary built with test keys

---

features/features.go
features/features_test.go
overlord/hookstate/hooks_test.go
overlord/snapstate/handlers_link_test.go
overlord/snapstate/snapstate_test.go
tests/main/cgroup-tracking/task.yaml
tests/main/lxd/task.yaml
tests/main/refresh-app-awareness/task.yaml
tests/main/refresh/task.yaml

This reverts commit db339ccd371811225555afb1690ef8a0fecf379f.
The desktop team is very nervous about disabling
refresh-app-awareness, especially this close to the release of
22.04.1. The worry is that unknown bugs during a refresh may
cause firefox to crash. Given the really good progress we had
with the startup performance and other improvements this would
be very unfortunate. Fwiw, there are no refresh bugs known right
now but the risk is there. The desktop team feels that the
shortcoming in the UX are a better tradeoff than to risk crashes.
We fixed the known issues around refresh-app-awareness:
https://bugs.launchpad.net/snapd/+bug/1975714
https://bugs.launchpad.net/snapd/+bug/1978834
https://github.com/snapcore/snapd/pull/11834
https://github.com/snapcore/snapd/pull/11976 …

many: revert "features: disable refresh-app-awarness by default again"

---

tests/core/kernel-and-base-single-reboot-failover/task.yaml
tests/core/kernel-and-base-single-reboot/task.yaml
tests/main/lxd-mount-units/task.yaml
tests/main/lxd-snapfuse/task.yaml
tests/main/lxd-try/task.yaml

In a few places we call `systemctl is-system-running` and expect
either `running` or `degraded` to be returned.
But it can all return `starting`. If we want to wait for the system to
have finished starting, the documentation says we need to use
`--wait`.

tests: Fix calls to systemctl is-system-running

---

tests/main/microk8s-smoke/task.yaml

Recently the test started to fail:
microk8s.daemon-apiserver-kicker[27599]: error: error running snapctl: unknown service: "microk8s.daemon-apiserver"
snapd[25465]: daemon.go:217: DEBUG: pid=23473;uid=0;socket=/run/snapd-snap.socket; POST /v2/snapctl 6.431534ms 200
microk8s.daemon-kubelite[27652]: E0804 10:29:54.367901   27652 kubelet.go:2349] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Let's temporarily disable it, while we investigate the failure.
The PR to revert this is https://github.com/snapcore/snapd/pull/12015

tests: disable microk8s test on 16.04

---

systemd/systemd.go
systemd/systemd_test.go

When booting in OEM configuration mode, the systemd target is set to
`oem-config.target` instead of the usual `multi-user.target`; if our
mount units require solely the multi-user target, which is not reached
during OEM configuration mode, they won't be started.
So, let's add `default.target` to our mount units: this target is a
symbolic link to the system default target, which is usually
`multi-user.target` for a desktop session.
Most likely, there's no need to keep `multi-user.target` in the
`WantedBy` line, but since this is a hotfix, let's take a defensive
approach and keep it until we have the time to verify that removing it
does not cause any regression.
Fixes LP:#1983528

systemd: add `WantedBy=default.target` to snap mount units

---

tests/lib/prepare.sh

We should take the modules from pc-kernel rather than initramfs

tests: fix pc-kernel repacking

---

cmd/libsnap-confine-private/string-utils-test.c

This should fix error on Ubuntu 22.10 for ppc64el (see https://launchpad.net/ubuntu/+source/snapd/2.57+22.10)
```
gcc -DHAVE_CONFIG_H -I.   -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wno-missing-field-initializers -Wno-unused-parameter -Werror  -I/usr/include/glib-2.0 -I/usr/lib/powerpc64le-linux-gnu/glib-2.0/include -D_ENABLE_FAULT_INJECTION -g -O3 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -MT libsnap-confine-private/libsnap_confine_private_unit_tests-string-utils-test.o -MD -MP -MF libsnap-confine-private/.deps/libsnap_confine_private_unit_tests-string-utils-test.Tpo -c -o libsnap-confine-private/libsnap_confine_private_unit_tests-str …
```

snap-confine: disable -Werror=array-bounds in __overflow tests

---

interfaces/builtin/posix_mq.go
metautil/type_conversions.go
metautil/type_conversions_test.go

The existng error handling getPath() when checking if the path
is a list or a string. Instead add a new error type when a value
cannot be set from an attribute and only check for that.
Followup from:
https://github.com/snapcore/snapd/pull/11928#discussion_r928677524
Set as draft as there are questions about naming/location and if it is needed at all :)
Build on top of https://github.com/snapcore/snapd/pull/11928

interfaces,metautil: make error handling in getPaths() more  targeted

---

interfaces/builtin/mount_control.go
interfaces/builtin/mount_control_test.go

Instead of hardcoding a list of allowed FS types, create a list of the
disallowed ones based on the previous review feedback from security,
which got captured in a comment. Continue using the old list of allowed
FS types as the list of FS types to be used in case the plug declaration
does not explicitly mention a FS types.
The reason for this change is that some customers are using their own
custom filesystem; since this interface is super-privileged anyway, and
any plug must be approved by the Snap Store reviewers, it doesn't seem
that this change should pose a security risk.

i/b/mount-control: allow custom filesystem types

---

tests/main/interfaces-udisks2/task.yaml

In centos9 also is reproduced the same error than in arch linux
Object /org/freedesktop/UDisks2/block_devices/loop200 is not a mountable
filesystem.

tests: skip interfaces-ufisks2 on centos-9

---

spread.yaml
tests/lib/nested.sh
tests/nested/manual/core20-remodel/task.yaml
tests/nested/manual/remodel-cross-store/task.yaml
tests/nested/manual/remodel-simple/task.yaml

The idea is to simplify the code used to create images by creating
functions to prepare the snaps used to build the source images for the
nested tests.
This initial change includes snapd and kernel preparation.

tests: unify the way the snapd/core and kernel are repacked in nested helper

---

tests/core/kernel-and-base-single-reboot-failover/task.yaml
tests/core/kernel-and-base-single-reboot/task.yaml

`systemctctl is-system-running` does not support `--wait` in
bionic. So we need to call it several times instead.

tests: Work-around non-functional --wait on systemctl

---

interfaces/builtin/system_observe.go

This PR adds three paths to the `system-observe` interface to allow read-only access to the kernel build config.
x-ref: https://forum.snapcraft.io/t/new-interface-proposal-kernel-config/31253

interfaces: add kconfig paths to system-observe

---

overlord/snapstate/autorefresh.go
overlord/snapstate/export_test.go
overlord/snapstate/refreshhints.go
overlord/snapstate/snapstate_test.go

This PR refactors the logic in `autorefresh.go` that reads the refresh schedule and checks if can be managed. The logic was split around several functions in a (IMO) confusing way. Essentially, this function checks if the refresh config value is "managed" and, if it is, checks if there's a snap to manage. If not, then the refresh schedule value is parsed and the schedule is returned.

o/snapstate: refactor managed refresh schedule logic

---

tests/lib/nested.sh

This change is done to simplify how images are created and split the
functions prepare_gadget and prepare_base
extra_fundamentals is not used anymore as all the snaps are stored
in  extra-snaps dir and added to the command line using the same
mechanism

tests: implement prepare_gadget and prepare_base and unify all the version

---

testutil/errorischecker.go

As suggested by staticcheck.io

testutil: remove unneeded `fmt.Sprintf`

---

strutil/export_test.go
strutil/version.go
strutil/version_test.go

The current code in strutil.VersionCompare() is not fully
compatible with what a debian version allows. Specifically
the version number of `libgcc-s1` in 22.04 is valid
(`12-20220319-1ubuntu1`) but it's rejected right now.
The debian policy [1] says:
```
The upstream_version may contain only alphanumerics[14] and the
characters . + - : (full stop, plus, hyphen, colon) and should
start with a digit. If there is no debian_revision then hyphens
are not allowed; if there is no epoch then colons are not allowed.
```
and python-apt/apt/dpkg are all happy with the version. Given that
we generally follow the debian policy for this we should fix this.
Thanks to Gustavo for pointing this out.
As a drive-by I also include a commit that un-exports "strutil.VersionIsValid()"
that is not used in our …

strutil: fix VersionCompare() to allow multiple `-` in the version

---

asserts/asserts_test.go
asserts/database_test.go
asserts/fsbackstore_test.go
asserts/membackstore_test.go

The staticcheck.io complained that in some places in the
assert tests values are assigned but not used. This commit
fixes this by checking the values. Alternatives we could
of course just use `_, err := ...` instead of `a, err := ...`
but checking seems slightly more sensible to me.

asserts: add some missing `c.Check()` in the asserts test

---

daemon/api_apps_test.go
daemon/api_asserts_test.go
daemon/api_general_test.go
daemon/api_model_test.go
usersession/agent/rest_api_test.go

The `rec.HeaderMap` is deprecated since go1.11 and the
`rec.Header()` method should be used instead. This commit
does this switch.
Found by https://staticcheck.io/ which was suggested by Fred,
thanks for this.

daemon,usersession: switch from HeaderMap to Header in tests

---

spread.yaml

Now 22.04 is included for sru validation

tests: remove ubuntu 21.10 from sru validation

---

cmd/snap/cmd_download.go
cmd/snap/inhibit.go
cmd/snap/wait.go
image/image_linux.go
image/preseed/preseed.go
progress/export_test.go
progress/progress.go
progress/progress_test.go
store/tooling/tooling.go

making progress bars should take a stdout io.Writer
ToolingStore should carry an overridable stdout
make sure in image, preseed and cmd/snap code the overridable
top-level Stdout is passed along to make progress bars

many: progress bars should use the overridable stdouts

---

bootloader/lkenv/lkenv.go
systemd/systemd.go

Fix all the `don't use Yoda conditions (ST1017)` warnings found by staticcheck.io.
(see https://staticcheck.io/docs/checks#ST1017 for details).

bootloader,systemd: fix `don't use Yoda conditions (ST1017)`

---

cmd/snapd-apparmor/main_test.go
overlord/configstate/config/transaction_test.go
overlord/managers_test.go
overlord/state/taskrunner_test.go
sandbox/seccomp/compiler_test.go
tests/lib/fakedevicesvc/main.go

This fixes all issues of `unnecessary use of fmt.Sprintf (S1039)` as flagged by staticheck.io.

many: fix unnecessary use of fmt.Sprintf (S1039)

---

go.mod
go.sum
spread.yaml

The repo for maze.io/x/crypto is no longer accessible directly
(The Google cache date is May 2022).
If GOPROXY is enabled, the repo can still be indirectly located
through the proxy cache.
It is sometimes useful to have the proxy disabled (GOPROXY=direct)
as any upstream repository changes can take time to propagate to
the proxy (https://github.com/golang/go/issues/42449).
The crypto packages are currently needed in the secboot codebase
TPM package (https://github.com/snapcore/secboot). The secboot
repository is not currently a go module (no go.mod/go.sum) and is
built as part of the snapd build process.
Update the snapd module dependencies to redirect the old URL to
point to the exact same version on the Canonical hosted version of
the repository.
Tested with Go v1.13 and v1.18 running …

go.mod: replace maze.io/x/crypto with local repo

---

boot/boottest/device.go
boot/boottest/device_test.go
boot/boottest/model.go
overlord/devicestate/devicectx.go
overlord/devicestate/devicectx_test.go
overlord/devicestate/export_test.go
overlord/snapstate/snapstatetest/devicectx.go
snap/device.go

Is{Core,Classic}Boot() will be used to find if we are in a Ubuntu Core
device and if we are in a classic with modes (there is a modeenv file)
device respectively. That is determined by the information found in
the model assertion.

many: add Is{Core,Classic}Boot() to DeviceContext

---

data/selinux/snappy.te

This fixes an error occurring in our spread tests on Centos:
2022-08-17T12:52:45.7861235Z type=AVC msg=audit(08/17/22 12:52:06.099:6583) : avc:  denied  { open } for  pid=71804 comm=snap path=/etc/pki/tls/openssl.cnf dev="sda2" ino=33578739 scontext=system_u:system_r:snappy_cli_t:s0 tcontext=system_u:object_r:cert_t:s0 tclass=file permissive=1
2022-08-17T12:52:45.7898682Z type=AVC msg=audit(08/17/22 12:52:06.099:6583) : avc:  denied  { read } for  pid=71804 comm=snap name=openssl.cnf dev="sda2" ino=33578739 scontext=system_u:system_r:snappy_cli_t:s0 tcontext=system_u:object_r:cert_t:s0 tclass=file permissive=1
2022-08-17T12:52:45.7899442Z type=AVC msg=audit(08/17/22 12:52:06.099:6583) : avc:  denied  { search } for  pid=71804 comm=snap name=pki dev="sda2" ino=50341665 …

data/selinux: allow snaps to read certificates

---

daemon/api_download_test.go
snap/info.go
store/details.go
store/details_v2_test.go
store/download_test.go
store/store.go
store/store_download.go
store/store_download_test.go

v2 store APIs never provided them
v1 has for a long time returned the same value for both kind of URLs

snap,store: drop support/consideration for anonymous download urls

---

sandbox/apparmor/profile_test.go

This is already present in apparmor_test.go, and having it here too
causes the tests in this package to be executed twice.
Thanks @pedronis for the heads up!

sandbox/apparmor: remove duplicate hook into testing package

---

overlord/devicestate/devicectx_test.go

Which was happening because of duplicated wiring to go's testing
framework.

o/devicestate: do not run tests in this folder twice

---

overlord/devicestate/devicestate_install_mode_test.go
overlord/devicestate/handlers_install.go

The current code in DeviceManager.checkEncryption() will not return
an error if getting the KernelInfo fails. It was done this way
because historically we did not mock enough in many places in the
tests.
Now the tests need only a small update to do the proper checking
and error handling here. This commits adds the missing mocks and
updates the code.

devicestate: return an error in checkEncryption() if KernelInfo fails

---

packaging/debian-sid/tests/integrationtests
packaging/ubuntu-16.04/tests/integrationtests

In Debian and Ubuntu, sshd.service is an alias for ssh.service and always has
been.  Reload the service by its proper name in our test suite.
This is necessary because ssh is switching to socket activation in later
Ubuntu releases, which means the ssh.service is no longer enabled (in favor
of ssh.socket) and therefore the sshd.service alias is not registered.

packaging/*/tests/integrationtests: reload ssh.service, not sshd.service

---

store/auth.go
store/auth_u1.go
store/store.go
store/tooling/auth.go
store/tooling/export_test.go
store/tooling/tooling.go
store/tooling/tooling_test.go

including the simple credentials cases
this also starts supporting UBUNTU_STORE_AUTH taking diretcly the auth data instead of a filename.
to achieve this, we:
* reorg ToolingStore auth code
* fully allow for implicit user cred authorizing in store
* have the ToolingStore use and pass an Authorizer

store/tooling: support using snapcraft v7+ base64-encoded auth data

---

spread.yaml

This is because preseed-lxd tests is failing with the following error:
Error: write /var/lib/lxd/images/lxd_build_999208398/lxd_post_675612885:
no space left on device

tests: add extra space to ubuntu bionic

---

tests/nested/manual/cloud-init-never-used-not-vuln/task.yaml
tests/nested/manual/cloud-init-nocloud-not-vuln/task.yaml
tests/nested/manual/core-early-config/task.yaml
tests/nested/manual/core-seeding-devmode/task.yaml
tests/nested/manual/core20-4k-sector-size/task.yaml
tests/nested/manual/core20-boot-config-update/task.yaml
tests/nested/manual/core20-cloud-init-maas-signed-seed-data/task.yaml
tests/nested/manual/core20-custom-kernel-commandline/task.yaml
tests/nested/manual/core20-early-config/task.yaml
tests/nested/manual/core20-gadget-cloud-conf/task.yaml
tests/nested/manual/core20-grade-signed-above-testkeys-boot/task.yaml
tests/nested/manual/core20-grade-signed-cloud-init-testkeys/task.yaml
tests/nested/manual/core20-initramfs-time-moves-forward/task.yaml
tests/nested/manual/core20-install-device-file-install-via-hook-hack/task.yaml
tests/nested/manual/core20-install-mode-shutdown-via-hook/task.yaml
tests/nested/manual/core20-new-snapd-does-not-break-old-initrd/task.yaml
tests/nested/manual/core20-preseed/task.yaml
tests/nested/manual/core20-remodel/task.yaml
tests/nested/manual/core20-save/task.yaml
tests/nested/manual/core20-to-core22/task.yaml
tests/nested/manual/devmode-snap-seeded-dangerous/task.yaml
tests/nested/manual/gadget-connections/task.yaml
tests/nested/manual/remodel-cross-store/task.yaml
tests/nested/manual/remodel-simple/task.yaml
tests/nested/manual/snapd-refresh-from-old/task.yaml
tests/nested/manual/snapd-removes-vulnerable-snap-confine-revs/task.yaml
tests/nested/manual/uc20-fde-hooks-v1/task.yaml
tests/nested/manual/uc20-fde-hooks/task.yaml
tests/nested/manual/uc20-storage-safety/task.yaml

As now the image name is calculated automatically based on the test name
and variant for manual nested tests, it is not required anymore to setup
that in the test environment.
This was causing problems in some tests, i.e. the core20-4k-sector-size
test was setting just 1 NESTED_IMAGE_ID but it had 2 variants, so when
both variants were executed in the same host, both variants were using
the same image and the second execution was failing because of that.

tests: remove NESTED_IMAGE_ID from nested manual tests

---

overlord/ifacestate/handlers.go
overlord/ifacestate/helpers.go
overlord/ifacestate/ifacestate.go
overlord/ifacestate/ifacestate_test.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_link_test.go
overlord/snapstate/snapmgr.go
tests/nested/core/connected-after-reboot-revert/task.yaml

use this new tracking information in snapsWithSecurityProfiles
the main reason to do this is to avoid code using the result of
snapsWithSecurityProfiles to end up considering snaps being refreshed,
in particular when the refresh is being undone, to be gone and remove
connections to them
the tracking code tries to be simple and is based on the relatively
recent SnapLinkParticipant mechanism:
* we track also in situations where the snap will go away soon
* in undo situations we track the revision that ultimately we undo to
even if on disk there are still the new profiles, this is correct
anyway as the snap is inactive and that's the final state either way
the tracking is irrelevant and cleared when the snap becomes active again
to cover the new logic I had to increase the realism of some …

overlord: track security profiles for non-active snaps

---

daemon/api_base_test.go
daemon/api_find_test.go
daemon/api_general_test.go
daemon/api_snaps_test.go
daemon/api_test.go
daemon/api_users.go
daemon/api_users_test.go
daemon/daemon_test.go
overlord/auth/auth.go
overlord/auth/auth_test.go
overlord/snapstate/handlers_link_test.go
overlord/snapstate/snapstate_test.go
overlord/storecontext/context_test.go

In preperation for adding a new parameter (expiration date) to the user state in auth, I am moving arguments for auth.NewUser into a struct to avoid having to many parameters.

multiple: move arguments for auth.NewUser into a struct (auto-removal 1/n)

---

tests/main/uc20-create-partitions/task.yaml

The debug section breaks when the loop.txt file doesn't exist.

tests: fix debug section for test uc20-create-partitions

---

boot/bootstate20.go
boot/flags.go
boot/flags_test.go
boot/initramfs.go
boot/initramfs_test.go
cmd/snap-bootstrap/cmd_initramfs_mounts.go
cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
cmd/snap-bootstrap/main.go

If the model reveals that this is a classic system:
- Do not mount ubuntu-seed
- Do not mount base snap
- Do not mount snapd snap on first boot, we'll use initially the one
in the deb
This also needs changes in the initramfs to mount /sysroot differently
depending on whether this is UC or classic, and to avoid starting
populate-writable for the latter.

cmd/snap-bootstrap: changes to be able to boot classic rootfs

---

daemon/api_quotas.go
daemon/api_quotas_test.go
snap/quota/quota.go
snap/quota/quota_test.go
snap/quota/resources_builder.go
snap/quota/resources_test.go
wrappers/services.go
wrappers/services_test.go

One of my leftovers from the cpu-quota implementation. We should use CPUSet instead of AllowedCPUs internally so it matches our quota option, only when writing it to systemd will we use AllowedCPUs

multiple: clear up naming convention for cpu-set quota

---

mkversion.sh
overlord/devicestate/firstboot_test.go
overlord/managers_test.go
overlord/snapstate/snapstate_test.go

Re-exec support for snapd-apparmor was implemented in #11129.

many: Set SNAPD_APPARMOR_REEXEC=1

---

data/preseed.json

When collecting preseeded data, include also snapd/mounts.
This directory contains layout info and is essential to have a correct layout functionality on presseded system.

data: include snapd/mounts in preseeded blob

---

overlord/servicestate/quota_handlers.go
overlord/servicestate/quota_handlers_test.go
snap/quota/resources.go

Missing case when removing a quota group with a limit set.

overlord/servicestate: disallow removal of quota group with any limits set

---

data/systemd/Makefile

I've been hit by this working on abranch where I was adding my own
service. Thanks @mvo5 for the time-saver hint!

data/systemd/Makefile: add comment warning about "snapd." prefix

---

interfaces/builtin/system_observe.go

Some programs might want to show security label information. For
instance, netstat when using --context or --program options.

i/b/system-observe: allow reading processes security label

---

build-aux/snap/snapcraft.yaml

We need to move our riscv beta build to 2.57 as well

build-aux: move snapcraft branch to 2.57

---

client/snap_op.go
client/snap_op_test.go
cmd/snap/cmd_snap_op.go
cmd/snap/cmd_snap_op_test.go
daemon/api_sideload_n_try.go
daemon/api_sideload_n_try_test.go
daemon/api_snaps.go
daemon/api_snaps_test.go
tests/main/snap-quota-install/task.yaml

The second PR for the '--quota-group' option on snap install. This effectively invalidates the original PR https://github.com/snapcore/snapd/pull/11940 and is a followup to https://github.com/snapcore/snapd/pull/12066 which is also contained here.
This PR contains the frontend changes required to support the option, including a spread test.

overlord: frontend for --quota-group support (2/2)

---

client/systems.go
client/systems_test.go
daemon/api_systems.go
daemon/api_systems_test.go
daemon/export_api_systems_test.go

This commit implements the `client.SystemDetails()` call that will
return the data from the `/systems/<label>/` get endpoint.

client: add API for GET /systems/<label>
