canonical/snapd

tests/main/interfaces-udisks2/task.yaml

This is because the error "Object
/org/freedesktop/UDisks2/block_devices/loop200 is not a mountable
filesystem." is being reproduces also in fedora 35 and 36
In the meantime, I am trying to fix the error so it is possible to run this test in centos, arch and fedora again.

tests: skip interfaces-udisks2 in fedora

---

tests/main/microk8s-smoke/task.yaml

Revert #12014 once the failure has been fixed.

tests: reenable microk8s test on 16.04

---

spread.yaml

This new image is stored in canonical spread project, including latest dependencies.
It is required to use this image instead of the previous one in the ubuntu-os-cloud-devel project due to the spread pagination issue

tests: use the new ubuntu kinetic image

---

image/preseed/preseed_linux.go
image/preseed/preseed_uc20_test.go

Clean left behind tmp dir for snapd mount.
This is directory where snapd snap is mounted when running preseeding.

image: clean snapd mount after preseeding

---

spread.yaml
tests/lib/pkgdb.sh
tests/lib/prepare-restore.sh
tests/main/cgroup-devices-v2/task.yaml
tests/main/debug-sandbox/task.yaml
tests/main/system-usernames-illegal/task.yaml
tests/main/system-usernames-install-twice/task.yaml
tests/main/system-usernames-missing-user/task.yaml
tests/main/system-usernames/task.yaml

This change is to remove test code for systems which are not supported anymore.

tests: remove code for old systems not supported anymore

---

tests/lib/snaps/test-snapd-journal-quota/meta/snap.yaml
tests/main/snap-quota-install/task.yaml
tests/main/snap-quota-journal/task.yaml

**snap-quota-install**
On some versions of systemd, just creating a cgroup implies usage of memory.
**snap-quota-journal**
The test checks to quickly after doing quota changes for the services to be active again, let it retry 3 times to allow for services to come online, and also make sure the restart condition for the test journal snap is set to 'always', as if systemd restarts the journal namespace while the snap is writing to the namespace, then the service will be killed with a SIGPIPE. This is a valid exit condition for systemd, and thus the service will not be restarted as `on-failure` is the default behaviour.

tests/main/snap-quota-{install/journal}: fix unstable spread tests

---

client/systems.go
client/systems_test.go
daemon/api_systems.go
daemon/api_systems_test.go

This implements a stub `"action": "install"` for `POST /systems/<label>` and also adds the corresponding client interface code.

daemon: implement stub `"action": "install"`

---

daemon/api_quotas.go
snap/quota/quota.go
snap/quota/quota_test.go
wrappers/services.go

Clear up naming convention for threads, use threads internally and task when interacting with systemd

multiple: clear up naming convention for thread quota

---

tests/lib/image.sh

This is to make preseed tests work in kinetic

tests: add kinetic images to the gce bucket for preseed test

---

snap/quota/quota.go
snap/quota/resources.go
snap/quota/resources_test.go
wrappers/services.go
wrappers/services_test.go

Allow using 0 values for the journal rate to override the system default values, which are not set to unlimited.

snap/quota,wrappers: allow using 0 values for the journal rate limit

---

asserts/snapasserts/snapasserts.go
asserts/snapasserts/validation_sets.go
asserts/snapasserts/validation_sets_test.go
daemon/api_snaps.go
daemon/api_snaps_test.go
daemon/api_themes.go
daemon/api_themes_test.go
daemon/export_test.go
overlord/hookstate/ctlcmd/services_test.go
overlord/managers_test.go
overlord/snapstate/dbus_test.go
overlord/snapstate/export_test.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_rerefresh_test.go
overlord/snapstate/refreshhints.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go
overlord/snapstate/storehelpers.go

Adds support for passing specific revisions in *Many operations. This is necessary to implement 'snap validate --refresh --enforce' because, since we want meet constraints of some validation sets, we need to be able to specify the revisions that match those assertions.

o/snapstate: support specific revisions in UpdateMany/InstallMany

---

usersession/agent/rest_api.go

PendingSnapRefreshInfo is alreade defined in the client.go file, so there is no need to duplicate the definition.

usersession: Remove duplicated struct

---

client/systems.go
client/systems_test.go

This commit prepares the `InstallSystemOptions` to be ready for real use inside the installer API. This requires two things:
**1. Create client.InstallVolume{,Struct}**
The new struct is similar to `gadget.Volume{,Struct}` but tailored towards the installer use-case. The `client.VolumeStructure` contains an extra `Device` and `UnencryptedDevice` field that is filled in from the installer.
**2. Fix type mismatch in `client.InstallSystemOptions.OnVolumes`**
The volume information in snapd is usually encoded as: `map[string]*gadget.Volume`. However due to an oversight in the client code (and because it was not used yet) a small mistake made it into the code and it got encoded as:
`map[string][]gadget.Volume` there.

client: prepare InstallSystemOptions for real use

---

client/systems.go

Small PR to clarify what the install steps in `client.InstallSystemOptions` actually do.

client: clarify what InstallStep{SetupStorageEncryption,Finish} do

---

tests/main/interfaces-udisks2/task.yaml

The idea is to use udisksctl loop-setup instead of losetup tool.
This change is making the test work in ubuntu kinetic, arch linux, fedora and centos.

tests: fix non mountable filesystem error in interfaces-udisks2

---

client/systems.go
client/systems_test.go
daemon/api_systems.go
daemon/api_systems_test.go
daemon/export_api_systems_test.go
overlord/devicestate/devicemgr.go
overlord/devicestate/devicestate_systems_test.go
overlord/devicestate/export_test.go

This commit implements the API response for `/system/<label>` to
include the `storage-encryption` details for the current device.

daemon: return `storage-encryption` in /systems/<label> reply

---

tests/lib/image.sh

This change fixes the system names used by the preseed tests.

tests: fix preseed tests for arm systems

---

sandbox/cgroup/cgroup.go
sandbox/cgroup/cgroup_test.go
sandbox/cgroup/process_test.go
tests/main/cgroup-devices-v2/task.yaml

The cgroup V1 hierarchy behaves similarly to the V2 one when it is
unmounted: the hierarchy will be visible on the filesystem while there
is at least one process using it, but it will not appear as mounted in
/proc/mounts. Even more importantly, when systemd creates a transient
scope in such a situation, the cgroup V2 will be correctly reported in
`/proc/<self>/cgroup`, whereas the V1 group will be
1:name=systemd:/
(that is, the cgroup path is incorrect). In such cases, depending on the
order in which the entries appear in the `/proc/<self>/cgroup` file, snapd
could incorrectly think that the process has been placed in the `/`
cgroup path.
To fix the above, we consider the V1 hierarchy only if the V2 one has
not been mounted: when the V2 hierarchy is mounted, we know that this is
what …

sandbox/cgroup: don't check V1 cgroup if V2 is active

---

client/systems.go
client/systems_test.go
daemon/api_systems.go
daemon/api_systems_test.go
daemon/export_api_systems_test.go
gadget/gadget.go
gadget/gadget_test.go
overlord/devicestate/devicemgr.go
overlord/devicestate/devicestate.go
overlord/devicestate/devicestate_install_mode_test.go
overlord/devicestate/handlers_install.go

This commit adds code in the snapd daemon so that the installer
API calls `devicestate.InstallFinish()` and
`devicestate.InstallSetupStorageEncryption()` when the
`/systems/<label>` POST endpoint is called.
The devicestate part will create a change that sets up the
respective action and wires the tasks into the device managers
task handlers. The tasks itself are stubs and just return an
error for now. A followup will be used to write them up.
A bit of a question if devicestate should take `client.InstallVolume`
directly or if this needs to be moved or wrapped (we do use
`client` in `overlord` for some specific things already so not
a red flag it seems).

many: stub devicestate.Install{Finish,SetupStorageEncryption}()

---

tests/core/persistent-journal-namespace/task.yaml
wrappers/services.go
wrappers/services_test.go

As described in the journal doc the default value for 'Storage=' varies. 
For the default namespace, 'Storage' is set to 'auto', but for all other namespaces, 'Storage' defaults to 'persistent', which unfortunately then ignores the 'journal.persistent' setting in snapd. The solution is to explicitly set 'Storage' to 'auto' for namespaces created through snap.

wrappers: journal namespaces did not honor journal.persistent

---

daemon/api_systems.go
daemon/api_systems_test.go

This commit adds the missing `ensureStateSoon()` when the POST /systems/<label> is called. With that the generated change will actually start to be processed immediately.
Thanks to Alfonso for noticing.

daemon: add `ensureStateSoon()` when calling systems POST api

---

asserts/snapasserts/validation_sets.go
asserts/snapasserts/validation_sets_test.go
overlord/snapstate/autorefresh_gating_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_update_test.go
overlord/snapstate/storehelpers.go
store/store_action.go
store/store_action_test.go

Use a typed ValidationSetKey in the `store` package instead of a `[][]string`, to help prevent incorrectly formatted keys from being passed in. To the same end, also renames the field from ValidationSet to ValidationSetKey. The second commit renames the ValidationSets in the `snapstate` package to ValidationSetKeys, to make it a bit clearer.

store: use typed valset keys in store package

---

overlord/snapstate/flags.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_update_test.go

Support running multiple InstallMany, UpdateMany, InstallPathMany and
Update operations in the same lane such that one operation failing
causes the others to be rolled back. The InstallMany and UpdateMany
ops will be used transactionally to resolve validation set enforcement
conflicts. The new flag is forbidden in Install and InstallPath since
we don't need those right now.

o/snapstate: support running multiple ops transactionally

---

snapdenv/useragent.go
snapdenv/useragent_test.go

Adds wsl as an extra piece of information to the user agent string.
Snapd is not officially supported but there are workarounds to use it, this identifier would help detecting it when that is the case.
~Will stay as draft until https://github.com/snapcore/snapd/pull/12135 is merged or rejected. The linked PR changes the way to mock the WSL instance check. Once that is done, a check can be added to the unit tests so as to check that the string is indeed only added on (mocked) wsl.~
Nevermind, I found a way simpler to test this.

snapdenv: added wsl to userAgent

---

image/preseed/preseed_linux.go

When I execute the command `/usr/lib/snapd/snap-preseed /MY_ROOT_DIR`, it will produce the message `ubuntu classic preseedingstarting to preseed root`, I expect there should be a new line after `preseeding`

image/preseed: add missing new line

---

interfaces/builtin/login_session_control.go
interfaces/builtin/login_session_control_test.go

These new D-Bus interfaces allow the snaps to additionally control login sessions. This includes the ability to terminate or kill login sessions. These new interfaces were obtained from https://www.freedesktop.org/software/systemd/man/org.freedesktop.login1.html.
The unit tests have also been extended to add a check to ensure that the D-Bus rules are correctly included in the AppArmor snippet.

interfaces: login-session-control: add further D-Bus interfaces

---

tests/main/snap-env/task.yaml

This is to avoid this error
2022-09-19 16:50:09 Error debugging
external:ubuntu-core-22-arm-64:tests/main/snap-env:parallel (external:ubuntu-core-22-arm-64) :
+ cat './*-vars.txt' cat: './*-vars.txt': No such file or directory

tests: fix snap-env test on debug section when no var files were created

---

overlord/devicestate/devicestate_test.go
overlord/hookstate/hookstate_test.go
overlord/overlord.go
overlord/overlord_test.go
overlord/restart/restart.go
overlord/restart/restart_test.go
overlord/servicestate/servicemgr_test.go
overlord/snapstate/booted_test.go
overlord/snapstate/handlers_link_test.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go
overlord/standby/standby_test.go

later this will allow to add a StartUp method to handle held tasks waiting for a reboot

overlord: start turning restart into a full state manager

---

spread.yaml

This change is to fix the error caused by unbound SPREAD_PATH trying to start the debug session
2022-09-19 09:45:58 Starting shell to debug...
/tmp/tmp.bCYtcFnJLJ: line 92: SPREAD_PATH: unbound variable
This is only reproduced when the SPREAD_PATH is used in the suite environment.

tests: fix unbound SPREAD_PATH variable on nested debug session

---

tests/main/quota-groups-systemd-accounting/task.yaml
tests/main/snap-quota-memory/task.yaml
tests/main/snap-quota/task.yaml

Quotas have failed with the follwing error in arm devices for beta validation.
+ snap set-quota group-one --memory=100MB go-example-webserver error: cannot create quota group: cannot create quota group "group-one": cannot
use memory quota: memory cgroup is disabled on this system
We need to skip those tests until the memory cgroup is enabled on the systems

tests: disable quota tests on arm devices using ubuntu core

---

boot/flags.go
boot/flags_test.go

We do this to allow the usage of `snapctl system-mode` during factory-reset as a pre-requisite to running the install-device hook during factory-reset. The second PR will run the install-device hook and includes a spread test verifying that it is possible to run `snapctl system-mode`.
PR for this https://github.com/snapcore/snapd/pull/12154

boot: add factory-reset cases for boot-flags

---

boot/flags_test.go
boot/initramfs_test.go
boot/makebootable_test.go
boot/seal_test.go
cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
gadget/device/encrypt_test.go
gadget/install/install_test.go
overlord/devicestate/devicestate_install_mode_test.go
overlord/devicestate/devicestate_recovery_keys_test.go
overlord/devicestate/devicestate_test.go
sysconfig/cloudinit_test.go
sysconfig/gadget_defaults_test.go

This PR changes the tests to use the string
`/run/mnt/ubuntu-data/system-data` instead of using
`boot.InstallHostWritableDir`. There are two reasons for
this:
a) The tests are more explicit this way
b) A followup will change this string to a function and
the tests should still validate that the string value
has not changed
This change is auto-generated via:
```
$ git grep -l boot.InstallHostWritableDir | grep _test.go | xargs sed -i 's#boot.InstallHostWritableDir#filepath.Join(dirs.GlobalRootDir, "/run/mnt/ubuntu-data/system-data")#'
```
The same for:
- boot.InitramfsHostWritableDir
- boot.InitramfsWritableDir
- boot.InstallHostFDEDataDir
This diff is a bit repetitive and annoying but it makes the followup easier to review and validate as that changes the way these dirs are generated. …

many: refactor tests to use explicit strings instead of boot.Install{Initramfs,Host}{Writable,FDEData}Dir

---

boot/bootstate20.go
boot/cmdline.go
boot/cmdline_test.go
boot/flags.go
boot/flags_test.go
boot/initramfs.go
boot/initramfs_test.go
cmd/snap-bootstrap/cmd_initramfs_mounts.go
cmd/snap-bootstrap/cmd_initramfs_mounts_nosecboot.go
cmd/snap-bootstrap/cmd_initramfs_mounts_secboot.go
cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
cmd/snap-bootstrap/export_test.go
cmd/snap-bootstrap/initramfs_systemd_mount.go
cmd/snap-bootstrap/initramfs_systemd_mount_test.go
cmd/snap-bootstrap/main.go
secboot/export_sb_test.go
secboot/secboot.go
secboot/secboot_sb_test.go
secboot/secboot_tpm.go

This is https://github.com/snapcore/snapd/pull/12046 cherry picked for 2.57. 
Note that it also includes https://github.com/snapcore/snapd/commit/a3a2c22af3936987fcf08a07d9a69551a6bb74ea to avoid merge conflicts (which is slightly unfortunate as it makes the diff bigger).

cmd/snap-bootstrap: changes to be able to boot classic rootfs (2.57)

---

tests/core/snap-set-core-config/task.yaml
tests/core/system-settings/task.yaml
tests/lib/tools/suite/tests.session-support/task.yaml

This change includes 2 fixes:
The first is to update the timezone used by tests, Europe/Berlin is broken: readlink -f /etc/localtime -> /usr/share/zoneinfo/Arctic/Longyearbyen 
The other timezones are ok
The second, Ubuntu Core 18 supports user sessions now, so the tests.session-support test is updated accordingly

tests: fix issues related to dbus session and localtime in uc18

---

gadget/gadget.go
gadget/gadgettest/gadgettest.go
gadget/install/export_test.go
gadget/install/install.go
gadget/install/partition.go
gadget/install/partition_test.go
gadget/layout.go
gadget/layout_test.go
gadget/update.go
gadget/update_test.go
gadget/validate.go
image/helpers.go

This commit refactors the gadget code a bit to make the helpers more suitable for use from an installer.
To see how this is used check https://github.com/snapcore/snapd/pull/12176

gadget: refactor to allow usage from the installer

---

boot/boot_test.go
boot/flags.go
boot/flags_test.go
boot/initramfs20dirs.go
boot/initramfs_test.go
boot/makebootable.go
boot/makebootable_test.go
boot/seal.go
cmd/snap-bootstrap/cmd_initramfs_mounts.go
cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
cmd/snap-bootstrap/export_test.go
cmd/snap-bootstrap/initramfs_mounts_state.go
gadget/install/install.go
overlord/devicestate/devicemgr.go
overlord/devicestate/devicestate_recovery_keys_test.go
overlord/devicestate/devicestate_serial_test.go
overlord/devicestate/devicestate_test.go
overlord/devicestate/handlers_install.go

The location of these directories depends on the model.
E.g. `InstallHostWritableDir` is
- on classic: `/run/mnt/ubuntu-data`
- on core: `/run/mnt/ubuntu-data/system-data`
So these dirs need to take a minimal model interface instead
of being strings.

many: make {Install,Initramfs}{{,Host},Writable}Dir a  function

---

tests/main/cgroup-tracking-failure/task.yaml

This seems to happen very rarely:
+ . /home/gopath/src/github.com/snapcore/snapd/tests/lib/systems.sh
+ echo 'run a snap app as a root user, without session bus'
+ find /run/user/0
+ case "$SPREAD_SYSTEM" in
+ systemctl --user stop dbus.socket dbus.service
Failed to connect to bus: No such file or directory
It's not clear how we get there, but in any case since the test needs the D-Bus user session to be tore down, there's no harm in ignoring errors occurring while stopping it.
Internal issue: SNAPDENG-2396

tests/main/cgroup-tracking-failure: fix rare failure in Xenial and Bionic

---

overlord/snapstate/policy.go
overlord/snapstate/snapstate.go
tests/nested/manual/fde-on-classic/gadget.yaml
tests/nested/manual/fde-on-classic/mk-image.sh
tests/nested/manual/fde-on-classic/replace-image-files.sh
tests/nested/manual/fde-on-classic/task.yaml

this is a follow up to #12174, see the comments there.
The prepare-image and snap pack issues are probably the most important TODOs. They merit dedicated attention. This PR just tries to leave trace in the code of the comments in the original PR.

many: add todos discussed in the review in tests/nested/manual/fde-on-classic, snapstate cleanups

---

cmd/snapd-apparmor/export_test.go
cmd/snapd-apparmor/main.go
cmd/snapd-apparmor/main_test.go
release/export_test.go
release/release.go
release/release_test.go

This PR fixes three problems:
- `isWSL`had two separate implementations. One in *snapd-apparmor* and one in *release*. The former has been removed.
- `release.isWSL` works by detecting `Microsoft` in the kernel name. This only works on WSL1. A more robust solution has been implemented.
- `snapd_apparmor.IsContainer` depends on systemd's detection of WSL, which is not 100% robust. The previous solution has been used here as well.
Users are free to specify the kernel they run, so the kernel name can really take any value. This makes kernel-name-based WSL2 detection mechanisms insufficient. For WSL1 the kernel is always Microsoft's.
Current method of detecting if snapd is running on WSL only works for WSL1, but will return false in most instances of WSL2. It checks that the kernel version …

release, snapd-apparmor: fixed outdated WSL detection

---

overlord/devicestate/devicestate_install_mode_test.go

Fix a compilation error in `overlord/devicestate/devicestate_install_mode_test.go` that's currently breaking `master`.

o/devicestate: fix non-compiling test

---

kernel/fde/cmd_helper.go
kernel/fde/fde_test.go

We hit an issue in initrd where the basic.target had an implicit dependency on the snap-intiramfs-mounts unit. Part of snap-initramfs-mounts is to use `systemd-run` to run `fde-reveal-key`, without this `snap-initramfs-mounts` cannot complete. So this situation lead to a deadlock and an unbootable system.
While this is getting fixed in initrd the fde-reveal-key code should also be more robust and not hang like this. So this commits adds `--property=DefaultDependencies=no` which will avoid that fde-reveal-key needs basic.target to run.
This should fix the failure in the core22 `fde-reveal-test`  test.

fde: run fde-reveal-key with `DefaultDependencies=no`

---

interfaces/builtin/system_observe.go

This PR is based on the conversation [here](https://forum.snapcraft.io/t/auto-connect-request-for-opensearch-snap/31746/6) 
It adds read access to `/proc/cgroups` and `/proc/sys/vm/swappiness` to the `system_observe` interface

interfaces: add read access to /proc/cgroups and /proc/sys/vm/swappiness to system-observe

---

overlord/devicestate/firstboot_preseed_test.go
overlord/devicestate/firstboot_test.go
overlord/ifacestate/handlers.go

This is to fix what has been reported in here https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1990884.
It seems, during pre-seed when installing snaps that has connect hooks, we end up in a cylic loop. This is due to the conflict detection waiting for connect's and setup-profiles to finish, but we can end up in a state where the connect and setup-profiles wait for "mark-preseeding" task to finish, which in turn is waiting for the "auto-connect" task of the snap with the connect hooks. So we end up having this infinite loop where pre-seeding gets stuck. 
The fix here is to not report a conflict *as long as they are part of the same wait chain*.

overlord/ifacestate: fix conflict detection of auto-connection

---

overlord/devicestate/handlers_gadget.go
overlord/snapstate/handlers.go

The ineffassign checker got smarter and detected two ineffective assignments in our existing code. This breaks CI and this PR fixes this.

{device,snap}state: fix ineffectual assignments

---

data/selinux/snappy.te

Commit 5545f79af96cd1625d0958283c6e481e0090181a introduced a check for WSL that causes our spread tests (in particular, selinux-clean) to fail on Fedora and CentOS.
Add the rules from `audit2allow -a` to the SELinux rules, to suppress those warnings.

data/selinux: allow snapd to detect WSL

---

asserts/model.go
asserts/model_test.go
boot/boottest/device.go
gadget/validate.go
overlord/devicestate/devicectx.go
overlord/devicestate/devicemgr.go
overlord/devicestate/firstboot20_test.go
overlord/managers_test.go
overlord/snapstate/snapstatetest/devicectx.go

redefine IsCoreBoot as the model having a kernel
there are at least tests that show we can seed such systems
the changes ind devicemgr.go prompted fixes for some remodel tests that were
confusingly running wiht OnClassic true though they were using Core models

many: support extended classic models that omit kernel/gadget

---

overlord/state/change.go
overlord/state/state.go
overlord/state/state_test.go
overlord/state/taskrunner.go
overlord/state/taskrunner_test.go

these are overlord/state changes in preparation to support holding changes until a reboot has occurred instead of automatic rebooting for the kernels/gadgets in classic. 
the first commit here is tweaked code from #12102
next PR will have the changes in overlord/restart itself

o/state: Hold pseudo-error for explicit holding, concept of pending changes in prune logic

---

boot/makebootable.go
boot/makebootable_test.go
overlord/devicestate/devicemgr.go
overlord/devicestate/devicestate_install_mode_test.go
overlord/devicestate/handlers_install.go
tests/lib/fakeinstaller/mk-classic-rootfs.sh
tests/lib/nested.sh
tests/nested/manual/fakeinstaller/task.yaml

Further adjustments and cleanups to ensure that the full `fakeinstaller` nested test that can boot into the generated image.

devicestate,boot,tests: make `fakeinstaller` test work

---

boot/makebootable.go
boot/makebootable_test.go
boot/seal.go
overlord/devicestate/handlers_install.go
tests/nested/manual/fakeinstaller/task.yaml

MakeRunnableSystem implicitly assumes that the run system is a clone
of the current system, usually a UC20 ephemeral mode system
introduce MakeRunnableStandaloneSystem that does not make this assumption
and use it for the finish step of the install API
in theory we could change MakeRunnableSystem itself not to make the assumption
but it changes a bit its properties so it is something to maybe consider for
later

boot,o/devicestate: introduce and use MakeRunnableStandaloneSystem

---

seed/seed20_test.go

Never, ever, use real random data in tests!
Using random bytes was causing the test to randomly fail with a different error:
parsing assertion headers: header is not utf8

seed: fix seed test to use a pseudo-random byte sequence

---

client/snap_op.go
client/snap_op_test.go
cmd/snap/cmd_validate.go
cmd/snap/cmd_validate_test.go
tests/main/snap-refresh-enforce/refresh-enforce-set.yaml
tests/main/snap-refresh-enforce/task.yaml

* 67ea0ac10f20d0c8fe9087cc42e59b31763d8055 adds CLI support for a `snap validate --refresh --enforce` command
* 5dfbde21e2c4f1953d27dc714e4d5589effbda9c adds a spread test providing integration test coverage of validation set constraint auto-resolution

cmd/snap: validation set refresh-enforce CLI support + spread test

---

asserts/header_checks.go
asserts/model.go
asserts/model_test.go
overlord/devicestate/devicestate_test.go
overlord/devicestate/firstboot.go
overlord/devicestate/firstboot20_test.go
seed/seed20.go

They are implicitly supported and allowed with dangerous models on classic.
For non-dangerous classic models the model needs to opt-in for each by setting "classic: true" in the snap entry in the "snaps" stanza.

many: support classic snaps in the context of classic and extended models

---

client/quota.go
client/quota_test.go
cmd/snap/cmd_quota.go
cmd/snap/cmd_quota_test.go
daemon/api_quotas.go
daemon/api_quotas_test.go
tests/main/snap-quota-journal/task.yaml

It seems I had missed the communication between client and daemon with my fix for allowing zero values for the journal rate-limit. This adds the missing link :-)

cmd/snap,daemon: allow zero values from client to daemon for journal rate-limit

---

overlord/snapstate/autorefresh_gating.go
overlord/snapstate/autorefresh_gating_test.go
overlord/snapstate/export_test.go

while refreshes should forget the holds by other snaps on the refreshed snap, this should not be the case for holds set up by the user/system

o/snapstate: fix snaps-hold pruning/reset in the presence of system holding

---

tests/lib/pkgdb.sh

This should normally not be needed, but unfortunately it's necessary to workaround a test failure in Tumbleweed, where the version of the fwupd service has gone out of sync with the client library:
systemd[1]: Starting Firmware update daemon...
fwupd[16167]: Failed to load engine: libfwupd version 1.7.9 does not match daemon 1.7.10
systemd[1]: fwupd.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: fwupd.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Firmware update daemon.
dbus-daemon[574]: [system] Failed to activate service 'org.freedesktop.fwupd': timed out (service_start_timeout=25000ms)
Fixes: SNAPDENG-3009

tests: add libfwupd and libfwupdplugin5 to openSUSE dependencies

---

build-aux/snap/snapcraft.yaml

There is no libgcc1 package anymore on 20.04 and later. To get the needed `libgcc_s.so.1` library the package `libgcc-s1` is needed instead (the riscv snap is build with build-base: core20).
This should fix running `snap pack` on risc-v.

snapcraft: update libgcc1->libgcc-s1

---

tests/lib/fakeinstaller/main.go

When the fakeinstaller installs a system it will copy the selected seed on the target system. However for some pre-generated images there is a seed directory already on the target. In this case the fakeinstaller needs to remove it and make sure that the seed selected for install gets put into that place.
This fixes installing when using the casper.squashfs

tests: ensure that fakeinstaller put the seed into the right place

---

cmd/libsnap-confine-private/device-cgroup-support.c

On Debian and other distros the chmod operation on /sys/fs/bpf/snap/ fails with ENOTSUP. This means that the directory is left with the original 0000 permissions.
Since the functionality is not affected and the permissions are more restrictive than the ones we are attempting to set, let's not consider this an error case, but just continue.
This fixes frequent spread failures (SNAPDENG-2205).

cmd/libsnap-confine-private: do not panic on chmod failure

---

interfaces/builtin/steam_support.go

Added additional mounts allowed in the steam-support interface, necessary for proton support.  Fixes https://github.com/canonical/steam-snap/issues/6

interfaces: steam-support allow additional mounts

---

overlord/devicestate/devicemgr.go
overlord/devicestate/devicestate_test.go
overlord/devicestate/export_test.go
overlord/devicestate/firstboot.go
overlord/devicestate/firstboot20_test.go
overlord/devicestate/firstboot_test.go
overlord/devicestate/handlers_install.go
overlord/devicestate/handlers_test.go

to do this consistently we need to know the device model even earlier during first boot, this is a bit complicated
the double caching logic for the system/device seed on first boot is not pretty and quite baroque, to avoid this we probably should turn more things into proper DeviceManager methods
we have been reluctant to do that to keep mocking of some first boot logic straightforward but the messiness elsewhere doesn't justify insisting on that
it's too big of a change for this PR though, also because of the test churn, but we should do this in a follow-up soon

o/devicestate: support mounting ubuntu-save also on classic with modes

---

overlord/hookstate/ctlcmd/refresh.go
overlord/hookstate/ctlcmd/refresh_test.go
overlord/hookstate/hooks.go
overlord/hookstate/hooks_test.go
overlord/snapstate/autorefresh_gating.go
overlord/snapstate/autorefresh_gating_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_remove_test.go
overlord/snapstate/snapstate_update_test.go

levels are ordered and higher levels imply lower ones
there are two levels for now:
* HoldAutoRefresh that affects auto-refresh operations
* HoldGeneral that affects general refresh operations (no specific snap
mentioned) and implies HoldAutoRefresh

overlord: introduce hold levels in the snapstate.Hold* APIs

---

tests/nested/manual/minimal-smoke/task.yaml

I noticed that our minimal smoke spread test is failing right now with:
```
BdsDxe: loading Boot0002 "UEFI Misc Device" from PciRoot(0x0)/Pci(0x5,0x0)
BdsDxe: starting Boot0002 "UEFI Misc Device" from PciRoot(0x0)/Pci(0x5,0x0)
EFI stub: ERROR: Failed to allocate usable memory for kernel.
efi_relocate_kernel() failed!
efi_main() failed!
```
which indicates that our kernels are too big for 384MB. This should probably be escalated to the kernel team too.
As a drive-by change it also adds a run for UC22.

tests: add minimal-smoke test for UC22 and increase minimal RAM

---

overlord/snapstate/backend.go
overlord/snapstate/backend/copydata.go
overlord/snapstate/backend/copydata_test.go
overlord/snapstate/backend_test.go
overlord/snapstate/handlers.go

the options are more central to function than the Meter, the Meter goes as last except for timings
I noticed this while working on #12258

o/snapstate: drive-by: cleanup *CopySnapData signatures for consistency

---

interfaces/builtin/desktop_launch.go

Icons may be in subdirectories of /var/lib/snapd/desktop/icons/ if they are using icon themes, e.g. hicolor/apps/scalable/icon.svg.

interfaces: allow access to icon subdirectories

---

cmd/snap-seccomp/main.go
interfaces/seccomp/template.go

This is the first step to allow applications to open AF_XDP sockets. This change is limited to SecComp and is not enough to deliver the XDP functionality. Two more obstables remain:
1) AppArmor: profiles need to have the rule `network xdp,`
2) Capabilities: the net_raw capability is needed to use XDP
This change basically just registers the XDP protocol as allowed in the BPF profile of a snap.
From: https://bugs.launchpad.net/bugs/1990827
I could add the missing bit to this branch, too, if we know which interface should provide access to this protocol.

seccomp: allow opening XDP sockets

---

interfaces/builtin/microceph.go
interfaces/builtin/microceph_test.go
interfaces/policy/basedeclaration_test.go
tests/lib/snaps/test-snapd-policy-app-consumer/meta/snap.yaml
tests/main/interfaces-many-snap-provided/test-snapd-policy-app-provider-classic/meta/snap.yaml
tests/main/interfaces-many-snap-provided/test-snapd-policy-app-provider-core/meta/snap.yaml

This interface makes it possible to control MicroCeph.
It will be used by another snap, MicroCloud to bring up MicroCeph and LXD clusters automatically.
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

interfaces: add microceph interface

---

tests/nested/manual/fde-on-classic/mk-image.sh

Small PR to port the `mk-image.sh` script used in the `fde-on-classic` test to use `snap prepare-image --classic`.

tests: use `snap prepare-image` in fde-on-classic mk-image.sh

---

cmd/snaplock/runinhibit/inhibit.go

The function IsLocked() manually builds the path of the hint file, instead of rely on the hintFile() function to get it, as all the other functions do.
This patch fixes this.

inhibit: use hintFile()

---

tests/lib/nested.sh

Move to the test-snapd-swtpm snap in the nested tests.

tests: use test-snapd-swtpm instead of swtpm-mvo snap in nested helper

---

tests/lib/fakeinstaller/main.go
tests/nested/manual/fakeinstaller/task.yaml

Snapd will currently not deal with disks that have no partition table and error. To workaround this limitation the installer will now create the partition table.

tests: create partition table in fakeinstaller

---

tests/lib/fakeinstaller/mk-classic-rootfs.sh

When the fakeinstaller unsquashes a filesystem it may contain snap data already. This commit removes the most important elements of that.
The "-f" is a drive-by change which is also needed because "$DST" does exist already.

tests: remove squashfs leftovers in fakeinstaller

---

packaging/ubuntu-16.04/tests/integrationtests

The autopkgtests fail on kinetic right now because sshd switched from /etc/ssh/sshd_config to /etc/ssh/sshd_config.d which means spread setup on these systems breaks.

autopkgtests: fix running autopkgtest on kinetic

---

tests/main/lxd-mount-units/task.yaml

This fix change the core snap depending on the system and installs snapd and the core snap in ubuntu kinetic. The image used for ubuntu kinetic does not contain snapd.

tests: fix lxd-mount-units in ubuntu kinetic

---

cmd/snap/main.go
cmd/snapd-apparmor/main.go
cmd/snapd-apparmor/main_test.go
release/export_test.go
release/release.go
release/release_test.go
syscheck/wsl.go
syscheck/wsl_test.go

On Sept 21st, Microsoft anounced systemd support for WSL 2 ([see anouncement](https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/)), and Ubuntu-Preview already ships with systemd enabled by default.
Snap now works on WSL 2. Hence some of the current system checks in snapd have to be updated in response.
This PR fixes:
- [#1991823](https://bugs.launchpad.net/snapd/+bug/1991823) WSL detection is now incorrect / inappropriate
- [#1991826](https://bugs.launchpad.net/snapd/+bug/1991826) snapd is intentionally broken under WSL and shouldn't be

release, snapd-apparmor, syscheck: distinguish WSL1 and WSL2

---

interfaces/builtin/steam_support.go

Added mount for root pivot `/run/media` directory for Steam. Fixes https://github.com/canonical/steam-snap/issues/59.
Added mount for root pivot `/etc/nvidia` directory for Steam. Fixes https://github.com/canonical/steam-snap/issues/6.

interfaces: steam-support allow pivot /run/media and /etc/nvidia mount

---

packaging/arch/PKGBUILD
packaging/debian-sid/changelog
packaging/fedora/snapd.spec
packaging/opensuse/snapd.changes
packaging/opensuse/snapd.spec
packaging/ubuntu-14.04/changelog
packaging/ubuntu-16.04/changelog

This merged the `release/2.57` branch back into master to get the updated changelogs.

packaging: merge changelog for 2.57.5

---

asserts/asserts.go
asserts/asserts_test.go
asserts/header_checks.go
asserts/system_user.go
asserts/system_user_test.go

This PR adds a new member 'user-presence' which can (for now atleast) be set to 'until-expiration', which means that the user will be auto-removed once the assertion is longer valid.

asserts: add keyword 'user-presence' keyword in system-user assertion (auto-removal 3/n)

---

interfaces/builtin/kvm.go
interfaces/builtin/kvm_test.go

This allows consuming applications to determine with AMD-SEV is supported by the hypervisor.

kvm: allow read of AMD-SEV parameters

---

cmd/snap-seccomp/main.go

Thanks @alexmurray for spotting this!

cmd/snap-seccomp: fix typo in AF_XDP value

---

daemon/api_users.go
daemon/api_users_test.go
daemon/export_api_users_test.go
overlord/devicestate/users.go
overlord/devicestate/users_test.go

The final functionality for automatic user removal. This binds together the expiration provided in the assertion/REST with the expiration date in user state. The final PR will be a spread test that verifies this is correctly working E2E (most likely a manual test as it will be slow due to timings).
I split up the REST api functionality and the devicestate changes in each their commit so it's easier to review

o/devicestate,daemon: use the expiration date from the assertion in user-state and REST api (user-removal 4/n)

---

interfaces/builtin/system_observe.go

org.freedesktop.DBus.ListNames is already allowed, and this is a related method.

interface: Allow access to org.freedesktop.DBus.ListActivatableNames via system-observe interface

---

client/clientutil/snapinfo.go
client/clientutil/snapinfo_test.go
client/packages.go
client/packages_test.go
cmd/snap/cmd_info.go
cmd/snap/cmd_info_test.go
cmd/snap/export_test.go
daemon/api_snaps_test.go
image/image_test.go
overlord/snapstate/aux_store_info.go
overlord/snapstate/aux_store_info_test.go
overlord/snapstate/refreshhints.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_test.go
seed/internal/auxinfo20.go
seed/seed16.go
seed/seed16_test.go
seed/seed20.go
seed/seed20_test.go
seed/seedwriter/seed16.go
seed/seedwriter/seed20.go
seed/seedwriter/writer_test.go
snap/info.go
snap/info_test.go
snap/validate.go
store/details.go
store/details_v2.go
store/details_v2_test.go
store/store_test.go

to be backward compatible both in terms of what happens on a snapd revert or
dealing with data saved by an old snapd we still need to operate on the
fields/storage locations previously used for contact and website

many: expand fully handling links mapping in all components, in the API and in snap info

---

client/snap_op.go
client/snap_op_test.go
cmd/snap/cmd_snap_op.go
cmd/snap/cmd_snap_op_test.go
daemon/api.go
daemon/api_snaps.go
daemon/api_snaps_test.go
daemon/export_test.go
tests/main/snap-refresh-hold/task.yaml

* 40ee105a662eabcabd28994da4c2a76e8bfdc8b8 adds support for hold and unholding refreshes to the snapd REST API
* bde49218f74ffc7d54e18a206aab0961ebd2a0e7 adds support for the `snap refresh --hold/--unhold` commands to the `snap` tool
* 13ebf7d9a58627ff5ac031cb1bc45a5ffb2853b5 adds a spread test to integration test this feature

many: support refresh hold/unhold to API and CLI

---

cmd/snap/cmd_snap_op.go
cmd/snap/cmd_snap_op_test.go

This PR corrects the output of `snap refresh --hold` which was returning from "Auto-refresh of all snaps held until forever" instead of "... held forever". Thanks @degville for noticing and suggesting a better alternative. Requesting @pedronis' review in case you prefer to keep "forever" for consistency.

cmd/snap: improve refresh hold's output

---

client/validate.go

We noticed some copy/paste comments in client/validate.go in ValidationSetResult. This commit removes them as they are misleading.

client: remove misleading comments in ValidateApplyOptions

---

tests/main/degraded/task.yaml

There usually are three failed transient units with the "run-*" name, which behave like this:
● run-r0b8a16d6cda843a490480bf722d1dbce.service - /usr/bin/systemctl start man-db-cache-update
Loaded: loaded (/run/systemd/transient/run-r0b8a16d6cda843a490480bf722d1dbce.service; transient)
Transient: yes
Active: failed (Result: exit-code) since Wed 2022-11-02 12:43:51 UTC; 1min 48s ago
Main PID: 1793 (code=exited, status=1/FAILURE)
Nov 02 12:33:24 nov021231-806690 systemd[1]: Started /usr/bin/systemctl start man-db-cache-update.
Nov 02 12:43:51 nov021231-806690 systemctl[1793]: Warning! D-Bus connection terminated.
Nov 02 12:43:51 nov021231-806690 systemctl[1793]: Failed to wait for response: Connection reset by peer

tests/main/degraded: ignore man-db update failures in CentOS

---

cmd/snap-mgmt/snap-mgmt.sh.in
data/systemd/Makefile
data/systemd/snapd.mounts-pre.target
data/systemd/snapd.mounts.target
data/systemd/snapd.service.in
image/preseed/preseed_classic_test.go
image/preseed/reset.go
packaging/fedora/snapd.spec
packaging/opensuse/snapd.spec
packaging/ubuntu-14.04/snapd.postrm
packaging/ubuntu-16.04/snapd.postrm
systemd/emulation.go
systemd/systemd.go
systemd/systemd_test.go
tests/core/config-defaults-once/task.yaml
tests/core/core-to-snapd-failover16/task.yaml
tests/core/gadget-config-defaults-vitality/task.yaml
tests/core/gadget-config-defaults/task.yaml
tests/core/snapd-failover/task.yaml
tests/core/snapd16/task.yaml
tests/lib/core-config.sh
tests/lib/state.sh
tests/main/basic-target-socket-activation/task.yaml
tests/main/postrm-purge/task.yaml
tests/main/preseed-core20/task.yaml
tests/main/preseed/task.yaml
tests/main/snap-mgmt/task.yaml
wrappers/core18.go

This refactors mount units and  contains an alternative for [LP1983528](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1983528)
This contains 3 commits:
`snapd.mounts-pre.target` will be before any mount unit, `snapd.mounts.target`.  Now we can schedule before or after mounts without needing to modify the mount units.
We also install those mounts to `snapd.mounts.target` so that we can make snapd.service for example, "want" all mounts.
On OSTree systems with `/snap` being a symlink to `/var/lib/snapd/snap`, because `/var` is a bind mount with shared propagation, mounting in `/var/lib/snapd/snap` would create double mounts.  `ostree-remount.service` fixes propagation on `/var`. So if we want to mount in `/var` we need to mount after `ostree-remount.service`.
Otherwise double mounts …

many: create snapd.mounts targets to schedule mount units

---

sandbox/apparmor/apparmor_test.go

The current `apparmorSuite.SetUpTest` has confusing behavior when there is a host file `/etc/apparmor.d/tunables/home.d/snapd`. In this case the tests fail with:
```
PANIC: apparmor_test.go:49: apparmorSuite.SetUpTest
... Panic: BaseTest cleanup handlers were not consumed before a new test start, missing BaseTest.TearDownTest call? (PC=0x437966)
/usr/lib/go-1.18/src/runtime/panic.go:838
in gopanic
/home/egon/devel/go/src/github.com/snapcore/snapd/testutil/base.go:38
in BaseTest.SetUpTest
apparmor_test.go:50
in apparmorSuite.SetUpTest
/usr/lib/go-1.18/src/reflect/value.go:339
in Value.Call
/usr/lib/go-1.18/src/runtime/asm_amd64.s:1571
in goexit
```
This is because not all tests set the `dirs.GlobalRootDir` but the cleanup handlers try to remove the file
`filepath.Join(dirs.GlobalRootDir, …

sandbox: fix `apparmorSuite.SetUpTest`  when home.d/snap file exists

---

testutil/containschecker.go
testutil/containschecker_test.go

Only top-level containers were matched in an unsorted way and maps were compared with reflect.DeepEqual. Now map values are also "unsorted matched" so values like `map[string][]string` can be compared regardless of order even with nesting. Note that containers nested in slices or arrays are still compared in the normal way.

testutil: compare unsorted containers nested in maps

---

cmd/snap/cmd_recovery.go
cmd/snap/cmd_recovery_test.go

The current client code has a check for `release.OnClassic` when running: `snap recovery --show-keys`. This check is silly because 
a) if anything it needs to be on the daemon side
b) now with classic+modes systems it's no longer valid
Hence this commit removes the check entirely. The error on a classic system without encryption is still sensible:
```
$ snap recovery --show-keys
error: system does not use disk encryption
```

client: remove classic check for `snap recovery --show-keys`

---

tests/lib/fakeinstaller/main.go

Previously we were using the filesystem label, so this was not working
unless partition and filesystem labels were coincident.

tests/fakeinstaller: really use part label to find partitions

---

overlord/state/change.go
overlord/state/change_test.go
overlord/state/task.go
overlord/state/task_test.go
overlord/state/taskrunner.go
overlord/state/taskrunner_test.go

we considered abusing HoldStatus to mark tasks waiting fro some user/external action but there are two issues with that:
* HoldStatus is a ready status which is a bit confusing
* aborting something in HoldStatus does nothing but something in WaitStatus is actually done and should be aborted
treat WaitStatus mostly as DoneStatus except is not a ready status
turn the marker error state.Hold to state.Wait

o/state: introduce WaitStatus

---

tests/lib/snaps/store/test-snapd-libvirt-consumer/vm/ping-unikernel.xml
tests/main/interfaces-libvirt/task.yaml

The test is failing with a non critical AppArmor error message, but the real failure is due to QEMU command-line parsing:
error: internal error: qemu unexpectedly closed the monitor:
2022-10-03T11:56:15.932697Z qemu-system-x86_64:
-device {"driver":"virtio-balloon-pci","id":"balloon0","bus":"pci.0","addr":"0x2"}:
PCI: slot 2 function 0 not available for virtio-balloon-pci, in use by virtio-net-pci,id=(null)
This happens because something in libvirt (or maybe QEMU itself) adds an implicit PCI device on address 0x2 -- the log line pasted above shows what device is being added. This bug has also been noticed by other projects, see comment 45 on https://bugzilla.redhat.com/show_bug.cgi?id=2034160
The workaround we use is to specify a virtio-net-pci device on another PCI address, in order to …

tests: tweak the libvirt interface test to work on 22.10

---

release/export_test.go
release/release.go
release/release_test.go

The bug report is quite thorough:
---
This was the report that made me investigate:
https://github.com/ubuntu/WSL/issues/299#issuecomment-1294232561
The issue is that snapd correctly identifies that it is running on WSL, but cannot detect it is running on WSL2 so it falls back to thinking it is running on WSL1. The issue happens here:
https://github.com/snapcore/snapd/blob/3c05e535e5cff4b64e4427e38494795fbbfd5122/release/release.go#L140-L245
In particular, this happens because WSL2 is detected by finding when the root filesystem is of type ext, but on LXC it is btrfs.
Once snapd thinks it is running on WSL1, it refuses to perform any action:
```
Interacting with snapd is not yet supported on Windows Subsystem for Linux 1.
This command has been left available for documentation purposes …
```

release: Fix WSL detection in LXD (LP1995083)

---

boot/initramfs20dirs.go
gadget/gadget.go
gadget/gadget_test.go
gadget/gadgettest/examples.go
gadget/install/install.go
gadget/validate.go
gadget/validate_test.go
overlord/devicestate/handlers_install.go
tests/lib/fakeinstaller/main.go
tests/nested/manual/fakeinstaller/task.yaml
tests/nested/manual/fde-on-classic/gadget.yaml

The system-seed-null partition role will be used when there is a boot partition which bootloader runs before the bootloader/kernel in the boot partition. The difference with system-seed is that for this one there are no system seeds available, although eventually it could happen that those are added.

many: add system-seed-null partition role

---

overlord/devicestate/devicestate_bootconfig_test.go
overlord/restart/restart.go
overlord/restart/restart_test.go
overlord/snapstate/handlers_link_test.go
overlord/snapstate/snapstate.go
tests/nested/manual/fde-on-classic/mk-image.sh
tests/nested/manual/fde-on-classic/task.yaml

Trigger the `update-notifier` reboot required helper to inform the users about pending reboots on classic systems.

restart,snapstate: implement reboot-required notifications on classic

---

daemon/api_validate.go
daemon/api_validate_test.go
overlord/assertstate/assertstate.go
overlord/assertstate/assertstate_test.go
overlord/assertstate/validation_set_tracking.go
overlord/assertstate/validation_set_tracking_test.go
tests/main/snap-validate-enforce/task.yaml

Some places were setting ValidationSetTracking's Current to the currently active sequence and others were setting it to the latest, if an older sequence was pinned (see: https://github.com/snapcore/snapd/pull/11707). This was reflected in the output of `snap validate`; even when a previous sequence was pinned, the output always showed the latest one. The first commit of this PR changes this so Current is always equal to PinnedAt, when Pinned != 0 (i.e., there is a pinned assertion). The second commit introduces a Sequence() method that checks the PinnedAt before returning the Current sequence number, to be even more robust.

many: ensure Current in val set tracking matches PinnedAt (if != 0)

---

README.md

In the "Project Status" table, the "Build Status" was showing a broken image icon and a link to snapd's actions page (showing all branches). This commit adds a Github Actions badge showing if the tests are passing on master and changes the link to the master branch's actions page.

README.md: add Github Actions badge and fix link

---

interfaces/builtin/wayland.go
interfaces/builtin/wayland_test.go

This PR grants snaps with a Wayland slot access to the shm file created by Firefox.
Part of the Wayland protocol involves the client creating a wl_shm_pool to pass data to the server. The `wl_shm_create_pool()` has the client provide a file descriptor that will be mapped locally and sent to the server over the Wayland socket (via SCM_RIGHTS). That means that the server needs to have AppArmor access to whatever the file descriptor points to.
For GTK and Qt apps, no special permissions are needed because they use memfd_create() to create the shm pool: as there is no file name, it doesn't trigger any AppArmor file rules. Unfortunately, Firefox's Wayland code uses a file system backed fd:
https://searchfox.org/mozilla-central/source/widget/gtk/WaylandBuffer.cpp#48-65
Without this change, we …

interfaces: allow wayland slot snaps to access shm files created by Firefox

---

.github/labeler.yml
.github/workflows/labeler.yaml

Add the rule to manage the "Needs Documentation" label when a file is modified in 
. cmd/snap/
. cdaemon
. overlord/hookstate/ctlcmd 
. overlord/configstate/configcore

docs: new labeler rules for "Needs Documentation" label

---

.github/labeler.yml
.github/workflows/labeler.yaml
.github/workflows/test.yaml

the any: [] just works when all: [] is used, otherwise weeeee need to use a list that means the same than any.
I tested that in the snapd-testing-tools project
Then "sync-labels" by default is false, it means that when a file is removed from the pr, the label is not removed. But if we manually remove the label, then when the workflow is executed again, la label will be applied again following the rules defined.

ci: update labeler configuration

---

tests/main/snap-refresh-hold/task.yaml

The `snap-refresh-hold` spread test was flaky. I couldn't reproduce but looking at the logs it seems like the auto-refresh just didn't complete in time. This seems plausible since it only had 10 seconds to complete whereas the `snapd-state wait-for-snap-autorefresh` utility waits up to 2 minutes. This PR makes a couple of racy conditions more robust and also adds some debug info in case this happens again.

tests: make snap-refresh-hold more robust against race conditions

---

sandbox/apparmor/apparmor.go
sandbox/apparmor/apparmor_test.go
tests/main/snapd-snap/task.yaml

This commit disables the apparmor vendoring that got enabled in https://github.com/snapcore/snapd/pull/12087
The rational is:
1. it breaks some spread tests related to snapd reverts
2. it break the fde-on-classic install
3. customers are affected
Once this has landed I will open a new PR that reverts this disable and there we can iterate on the fix for the spread tests that fail.

apparmor: disable vendoring again

---

cmd/snap-confine/selinux-support.c

GCC 12.2.1 with the default build flags in Rawhide is more picky than usual, and fails with this:
```
snap-confine/selinux-support.c:85:29: error: initialization discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
85 |         char *new_ctx_str = context_str(ctx);
|                             ^~~~~~~~~~~
cc1: all warnings being treated as errors
```
Can this be cherry picked to 2.57? cc @mvo5

cmd/snap-confine: do not discard const qualifier, FTBFS on Rawhide fix

---

aspects/aspects.go
aspects/aspects_test.go

Adds support for placeholders in the aspect's names (in the `{foo}` format) that can then be used to fill in the path.

aspects: support placeholders in aspect names

---

overlord/devicestate/devicemgr.go
overlord/devicestate/devicestate_recovery_keys_test.go

We do not have the "system-data" subfolder on classic.

o/devicestate: fix paths for retrieving recovery key on classic

---

image/image_linux.go
image/image_test.go
overlord/configstate/configcore/homedirs.go

Some customizations (cloud init configuration seeding, disabling of console conf) were not happening for UC16/18 if there were also defaults in the gadget. This fixes an early return that was the
cause (LP: #1997494).

image: make sure file customizations happen also when we have defaults

---

cmd/snap/cmd_snap_op.go
cmd/snap/cmd_snap_op_test.go

The user can place an indefinite refresh hold which is internally represented as a maximum duration hold (in order to be compatible with the previous `snap set` mechanism). To check active holds the user can run `snap refresh --time` which currently returns a very distant time like `hold: 2315-03-07` for indefinite holds. This PR changes this so that indefinite/very long holds are displayed consistently as "forever" in the output of `snap refresh --time`.

cmd/snap: display refresh holds over 100y as forever

---

overlord/devicestate/devicestate_bootconfig_test.go
overlord/devicestate/devicestate_gadget_test.go
overlord/restart/restart.go
overlord/restart/restart_test.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_link_test.go

move the "requested system restart" logging to overlord/restart

overlord: avoid logging Requested system restart on classic with modes

---

build-aux/snap/snapcraft.yaml

The "snapcraft remote-build" is broken because, for some reason, the "build-aux" folder is removed and their contents moved up when the data is uploaded.
This patch fixes it.

snapcraft: fix remote build

---

gadget/install/install.go

This fixes an mounting issue during factory-reset where we tried to mount ubuntu-data as "crypto_LUKS" instead of "ext4", and now also uses the correct mount point.

gadget/install: use laidOut volume info instead of onDisk when mounting partitions during factory reset

---

interfaces/builtin/network_manager.go

Add permissions to the network-manager interface so it allows owning the dbus names required by NM's OpenVPN plugin.

interfaces/network-manager: add permission for OpenVPN

---

tests/lib/tools/suite/tests.session-support/task.yaml

The test has recently started failing because the command prints "ok". I'm not sure what happened, maybe something was backported there.

tests: update test now that core18 supports sessions

---

tests/main/lxd/task.yaml

The `if` condition checks the `https_proxy` variable, but then `http_proxy` is used instead, and it might be undefined.

tests: fix an unbound variable in LXD test

---

overlord/devicestate/firstboot20_test.go
seed/seedtest/seedtest.go
seed/seedwriter/seed16.go
seed/seedwriter/seed20.go
seed/seedwriter/writer.go
seed/seedwriter/writer_test.go

This avoids failing only later at seeding time.

seed/seedwriter,o/devicestate: classic snaps w/o flag and model grade higher than signed fail

---

spread.yaml

Ubuntu core executions are taking 20 extra minutes to finish. This is caused because even when ubuntu core runs less number of tests, the system setup takes so long compared with the regular ubuntu cloud image.
$ spread -list google:ubuntu-core-20-64: | wc -l
442
$ spread -list google:ubuntu-20.04-64: | wc -l
596
$ spread -list google:ubuntu-core-22-64: | wc -l
421
$ spread -list google:ubuntu-22.04-64: | wc -l
596

tests: add more workers for ubuntu core 20/22

---

cmd/snap/cmd_snap_op.go
cmd/snap/cmd_snap_op_test.go

The first commit forbids refresh holds that are negative or too short (< 1s). The second commit changes a few things in the command's output and help messages. It's a bit of a drive-by fix but they were pointed out by people outside snapd so I wanted the fix in 2.58 to avoid confusing more people.

cmd/snap: error on negative or very short holds 

---

.github/workflows/test.yaml

The problem with -abend is that spread discards the worker in case of failure, and it is not allocating a new one. This produces that the executions are delayed when there are tests that fail becuase the number of workers used is being decreased when tests fail.

tests: avoid running spread -abend in the github workflow

---

aspects/aspects.go
aspects/aspects_test.go

Validate names and paths to ensure they're correctly formed (no empty parts, invalid characters, etc) and that placeholders in names are present in paths and vice-versa (such that paths can always be filled if a name was matched).

aspects: validate aspect names and paths

---

cmd/snap-confine/mount-support-test.c
cmd/snap-confine/mount-support.c
cmd/snap-confine/snap-confine.apparmor.in
cmd/snap-update-ns/system.go
cmd/snap-update-ns/system_test.go
data/Makefile
data/systemd-tmpfiles/Makefile
data/systemd-tmpfiles/snapd.conf
interfaces/builtin/x11.go
interfaces/builtin/x11_test.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate_test.go
packaging/arch/PKGBUILD
packaging/debian-sid/changelog
packaging/fedora/snapd.spec
packaging/opensuse/snapd.changes
packaging/opensuse/snapd.spec
packaging/ubuntu-14.04/changelog
packaging/ubuntu-16.04/changelog
tests/lib/reset.sh
tests/main/cgroup-tracking/task.yaml
tests/main/install-refresh-remove-hooks/task.yaml
tests/main/interfaces-x11-unix-socket/task.yaml
tests/main/security-private-tmp/task.yaml
tests/main/snap-confine-drops-sys-admin/task.yaml
tests/main/snap-confine-tmp-mount/task.yaml
tests/main/snap-confine-undesired-mode-group/task.yaml

This merges the CVE-2022-3328 fixes from the release/2.57 branch back into master.

many: merge fixes from 2.57.6

---

bootloader/grub.go
bootloader/grub_test.go
overlord/devicestate/devicestate_install_api_test.go

The ubuntu-18.04-32 tests are currently failing because the TestInstallFinishEncryptionHappy cannot find trusted boot assets for grub on non {amd,arm}64 platforms. The error is extremely indirect because the code in the bootloader just returns an empty struct. Hence in addition to fixing the test the code is now also more robust when asking for non-existing boot assets in grub.go.

bootloader,devicestate: fix failing TestInstallFinishEncryptionHappy on i386

---

daemon/api_quotas.go
daemon/api_quotas_test.go
overlord/configstate/configcore/vitality_test.go
overlord/ifacestate/handlers_test.go
overlord/managers_test.go
overlord/servicestate/export_test.go
overlord/servicestate/internal/quotas.go
overlord/servicestate/internal/quotas_test.go
overlord/servicestate/quota_control.go
overlord/servicestate/quota_control_test.go
overlord/servicestate/quota_handlers.go
overlord/servicestate/quota_handlers_test.go
overlord/servicestate/servicestatetest/quotas.go
snap/quota/quota.go
snap/quota/quota_test.go
tests/main/snap-quota/task.yaml

This is the first PR in the per-service quota series. I'm sorry for the size of this PR, it's a bit bigger than I wanted it to be, I have tried to encapsulate changes in commits to make reviewing easier, but I believe most of the changes are unit test changes.
This adds support for per-service quota groups. There are some limitations that have been changed, and new ones introduced. The most important is that this PR changes the current limitation of not being able to mix snaps and sub-groups, which is now allowed to some extent.
If you mix snaps and sub-groups, you are not allowed to further put snaps into the sub-groups, only services as we do not allow nesting of snaps and sub-groups.
Instead you must only put services into sub-groups of groups that contain snaps.
Neither do we allow …

many: change the quota backend to support per-service quotas (1/4)

---

tests/main/mount-ns/google.ubuntu-16.04-64/PER-SNAP-16.expected.txt
tests/main/mount-ns/google.ubuntu-16.04-64/PER-SNAP-18.expected.txt
tests/main/mount-ns/google.ubuntu-16.04-64/PER-USER-16.expected.txt
tests/main/mount-ns/google.ubuntu-16.04-64/PER-USER-18.expected.txt
tests/main/mount-ns/google.ubuntu-18.04-64/PER-SNAP-16.expected.txt
tests/main/mount-ns/google.ubuntu-18.04-64/PER-SNAP-18.expected.txt
tests/main/mount-ns/google.ubuntu-18.04-64/PER-USER-16.expected.txt
tests/main/mount-ns/google.ubuntu-18.04-64/PER-USER-18.expected.txt

With commit a9812c467597159dd7fdbbb2da16b41c1a002962 we changed the location of the private tmp directory in snaps. Update the mount-ns test accordingly.
Note that the test is currently executed for Ubuntu 18.04 only. We should probably extend it to newer distros and decide what to do with 16.04.

tests: update mount-ns test for new tmpdir handling

---

tests/main/snapd-apparmor/task.yaml

This line of the test would be succeeding even if no additional output was emitted by snapd-apparmor, if th expected line was already present in the logs (maybe written at boot time or by some other test).
Use the `journal-state` program to read the logs, since it uses a cursor to limit the search to the logs emitted during the current test execution.
It also comes with a retry mechanism that can help to make the test more robust.

tests/main/snapd-apparmor: make log parsing more robust

---

tests/lib/nested.sh
tests/nested/manual/uc-update-assets-secure-add-sbat/task.yaml
tests/nested/manual/uc-update-assets-secure/generate_vendor_cert_section.py
tests/nested/manual/uc-update-assets-secure/task.yaml
tests/nested/manual/uc-update-command-line-secure/task.yaml

* Update the command line
* Update vendor key in shim
* Update shim from non-sbat to sbat
Also a previous commit fixes re-signing of boot files.

tests: add 3 tests that update boot assets in gadget on secure boot

---

overlord/devicestate/devicestate_install_api_test.go

The `testInstallFinishStep` test will fail on non-amd64 systems right now because it also matches the generated kernel commandline. This is however architecture depedant and generated in a way that is not easily mockable (right now) because it runs as part of the `init()` in `bootloader/assets/grub.go`.
So instead of using the exact match this commit will just check that the common commandline (`snapd_recovery_mode=run`) is generated and leave the exact match to the unit tests of the `assets` pkg.
This will fix the FTBFS we see in the PPAs right now.

devicestate: fix unit test failure on non-amd64 systems

---

overlord/configstate/configcore/vitality.go
overlord/ifacestate/handlers.go
overlord/ifacestate/handlers_test.go
overlord/ifacestate/helpers.go
overlord/servicestate/quota_handlers.go
overlord/servicestate/servicemgr.go
overlord/servicestate/servicestate.go
overlord/servicestate/servicestate_test.go
overlord/snapstate/handlers.go

This is in preparation for extending the usage of SnapServiceOptions where we need more info from snap.Info.

overlord/*: make SnapServiceOptions take snap.Info instead of the instanceName

---

gadget/gadget.go
gadget/gadget_test.go

Gadget validation depends only on gadget content, so it is not necessary to use LaidOutStructure for that. Simplify to using VolumeStructure.

gadget: do not use LaidOutStructure in gadget validation

---

packaging/fedora/snapd.spec
packaging/opensuse/snapd.spec

Changes:
. Update the date in the changelog to the correct format. 
. Use the correct TMPFILESDIR var in the Makefile
This is needed to fix systems where libexec is /usr/libexec instead of /usr/lib

tests: fix date and makefile for systemd-tmpfiles in snapd.spec

---

.github/workflows/test.yaml

The Go snap's stable channel was updated to 1.19.4, and golangci-lint 1.45.2 now produces failures like:
```
Running [/home/runner/golangci-lint-1.45.2-linux-amd64/golangci-lint run --out-format=github-actions --new-from-rev=master --path-prefix=] in [/home/runner/work/snapd/snapd/src/github.com/snapcore/snapd] ...
panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt
goroutine 1 [running]:
github.com/go-critic/go-critic/checkers.init.22()
github.com/go-critic/go-critic@v0.6.2/checkers/embedded_rules.go:46 +0x4b4
Error: golangci-lint exit with code 2
```
[v1.48.0](https://github.com/golangci/golangci-lint/releases/tag/v1.48.0) is the first with Go 1.19 support, but we may as well move to the latest version if we're changing at all.

ci: update golangci-lint to v1.50.1 in order to support Go 1.19

---

.github/workflows/macos-quick.yaml
.github/workflows/naming.yml
.github/workflows/test.yaml

At the moment, CI runs spit out a large number of warnings like:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/upload-artifact@v2
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-sta …
```

ci: update various Github actions to Node 16.x versions

---

overlord/servicestate/quota_control_test.go
overlord/servicestate/quota_handlers.go
overlord/servicestate/quota_handlers_test.go
snap/quota/quota.go
snap/quota/quota_test.go

The function `GroupForService` is also needed by https://github.com/snapcore/snapd/pull/12395

o/servicestate,snap/quota: check against adding the same service twice in quota groups

---

.github/workflows/test.yaml
build-aux/snap/snapcraft.yaml

Limit the number of processes created by make by using the value returned by nproc, so it adapts to the device it is running on.

build-aux,.github/workflows: limit make processes with nproc

---

overlord/servicestate/quota_control.go
overlord/servicestate/quota_control_test.go
overlord/servicestate/quota_handlers.go
overlord/servicestate/quota_handlers_test.go
snap/quota/quota.go
snap/quota/quota_test.go

Now that we support sub-groups for individual services with their own quotas, we need to impose some strict limitations in regards to journal quotas. Since mounts are generated per snap, it means we can't support multiple journal namespaces per snap. So we introduce a limitation in form of not allowing journal quotas on service sub-groups. They instead inherit the journal quota from their parent group (which contains the snap).

o/servicestate: disallow mixing journal quotas and services

---

overlord/snapshotstate/backend/backend.go
overlord/snapshotstate/backend/backend_test.go
tests/main/snapshot-basic/task.yaml

Snapshots require administrator privileges to be imported and hence are assumed to be trusted. However, let's try and be as helpful as possible and validate that they are self-contained on import (ie. there are no files within the snapshot that point outside of the parent directory) and report an error in that case.
Thanks: Sam Sanoop <sams@snyk.io>

o/snapshotstate: check snapshots are self-contained on import

---

gadget/gadget.go
gadget/gadget_test.go
gadget/gadgettest/gadgettest.go
gadget/layout.go
gadget/layout_test.go
gadget/update.go
gadget/update_test.go
gadget/validate.go
image/helpers.go
tests/lib/muinstaller/go.mod
tests/lib/muinstaller/main.go

LayoutConstraints was used only for the NonMBRStartOffset, which was actually always the same value unless used by ubuntu-image. It is possible to override this offset by setting explicitly offsets in gadget.yaml, so we do not need it to be configurable.
When used from ubuntu-image it was being set to zero, but anyway u-i calculates explicitly all offsets and inserts them in VolumeStructure, so this change should not be an issue for it.

gadget,image: remove LayoutConstraints struct

---

cmd/snap/cmd_prepare_image.go
cmd/snap/cmd_prepare_image_test.go
image/image_linux.go
image/image_test.go
image/manifest.go
image/options.go
tests/main/prepare-image-reproducible/task.yaml

This enables the generation of the seed.manifest and introduces (thanks to @pedronis) a new option for snapd prepare-image to control the generation.

image: generate seed.manifest

---

boot/boot_test.go
boot/bootstate20.go
boot/bootstate20_bloader_kernel_state.go
tests/nested/manual/fde-on-classic/task.yaml

When we were aborting a kernel installation before a reboot happened, a proper clean-up of left-overs was not happening. To fix that, make sure that current kernels in modeenv is always set appropriately and also make sure that the try-kernel.efi symbolic link used by the grub bootloader is removed.

boot: remove leftovers on kernel installation abort

---

HACKING.md

Fix a typo in the HACKING.md document

HACKING.md: fix typo in debug env var

---

httputil/logger.go
httputil/logger_test.go
logger/logger.go
logger/logger_test.go

Previously, for anything to be logged SNAPD_DEBUG had to be set to a true value (1, true, etc) even if SNAPD_DEBUG_HTTP was already set. In practice, this meant that we couldn't get HTTP logs w/o getting all other logging. This changes that so we can log only HTTP traffic by setting SNAPD_DEBUG_HTTP.

logger: allow logging HTTP traffic w/o logging everything

---

tests/lib/muinstaller/go.mod

As the PR that changed the API has already been merged.

tests/lib/muinstaller: build from master again

---

spread.yaml

After a set of nested tests is executed, the images saved in the disk use space that is required to create new images.
The test tests/nested/manual/muinstaller-real is failing because of not enough space in the disk. This is the error:
2022-12-12T13:07:17.7233318Z
'/tmp/work-dir/images/ubuntu-core-22-custom-muinstaller-real_encrypted.img' -> '/tmp/work-dir/images/ubuntu-core-current.img'
2022-12-12T13:07:17.7233828Z cp: error writing
'/tmp/work-dir/images/ubuntu-core-current.img': No space left on device 2022-12-12T13:07:17.7234006Z -----
2022-12-12T13:07:17.7234125Z .
2022-12-12T13:07:18.1915543Z 2022-12-12 13:07:18 Debug output for google-nested:ubuntu-22.04-64:tests/nested/manual/muinstaller-real:encrypted (dec121149-734952) :

tests: add more disk space to ubuntu-22.04 for nested tests

---

client/packages.go
cmd/snap/cmd_info.go
cmd/snap/cmd_info_test.go
daemon/snap.go

This refactors some things around the API:
* The first commit removes some unnecessary logic around error handling in a helper (see commit description for more information)
* The second commit avoids always serializing empty `time.Time` values in JSON responses by using `*time.Time` with the `omitempty` tag

daemon: improvements to REST API helper and JSON responses

---

tests/lib/tools/suite/tests.session-support/task.yaml

This test fails because the user session behaves different in ubuntu 18.04 than in uc18.
The test suite tests/lib/tools/suite is no preparing ubuntu core as the main suite does, so then a test in the main suite is executed before the tests.session-support, then the system under test is uc18, but if for example we execute teh test tests/lib/tools/suite/tests.session-support alone, then the system under test is ubuntu-18.04 because the prepare helper is not executed and the uc18 system is not built.
So to fix that, when the system under test matches "$SPREAD_SYSTEM" = ubuntu-core-18-*, but the actual system is '^ID=ubuntu$', in the case the test is not executed because it is the same than the test we do when "$SPREAD_SYSTEM" = ubuntu-18.04

tests: fix the tests.session-support test

---

.shellcheckrc
tests/core/basic20plus/task.yaml
tests/core/kernel-ver/task.yaml
tests/lib/tools/boot-state
tests/main/fake-netplan-apply/task.yaml
tests/main/snap-run-symlink-error/task.yaml
tests/main/snapd-snap/task.yaml

`master` is currently not building due to the new shellcheck warnings that v0.9.0 brought about. This PR fixes that in 3 commits:
* f8b035be15707f0e476abdca1b4a1c3b1785f4d7 fixes a test that was a bit broken and not always testing what is was supposed to
* 3c068cd7fcf0210076e0e8d7830e6ed3103e63b4 adds some double quoting to prevent string splitting
* 59ec8a39df0777b79b087dae20f1e1dad243a98e disables all unreachable code warnings because file-wide disables doesn't work in spread tests (see commit message for more detail)

tests: fix shellcheck warnings on unreachable code and var quoting

---

cmd/snap/notes.go
cmd/snap/notes_test.go
daemon/api_snaps_test.go
daemon/snap.go

This PR adds a 'held' tag to the notes in the `snap list`. Per the spec, the tag is only displayed if the hold is placed by the user (not a gating snap) to a specific set of snaps (not an all-snaps hold). It also doesn't display if the hold returned from the API has expired. 
This is based on the refactors in https://github.com/snapcore/snapd/pull/12436 so only 2c85cb40fa08ca1257c675e18281875be170a3a4 applies to this PR.

cmd/snap,daemon: add 'held' to notes in 'snap list'

---

overlord/configstate/configcore/corecfg_test.go
overlord/configstate/configcore/handlers.go
overlord/configstate/configcore/services.go
overlord/configstate/configcore/services_test.go
systemd/emulation.go
tests/lib/nested.sh
tests/nested/manual/core20-early-config/defaults.yaml
tests/nested/manual/core20-early-config/task.yaml

This new config option allows setting the addresses that the ssh
daemon listens to.
Note that this option is only available on UC20+ systems because
to work during first boot it needs to write a default configuration
into the `/etc/ssh/sshd_config.d` directory. This directory is
only available in UC20+ versions of ssh.

configcore: add option to set `service.ssh.listen-address`

---

httputil/client_test.go
httputil/retry.go
overlord/devicestate/devicestate_serial_test.go
overlord/devicestate/handlers_serial.go

When the serial assertion cannot be acquired because the certificate
of the remote system is expired or not yet valid then the most
likely reason for this is that the system clock is off. This case
is now treated in the same way as no network errors, i.e. snapd
will retry to acquire the serial and will not go into the backoff
mode. This helps with the issue that on systems without a RTC
when the device comes up and the NTP sync is slow the serial
is (re)tried 3 times and then it goes into a very long backoff
(as defined in DeviceManager.ensureOperationalShouldBackoff()).

devicestate: retry serial acquire on time based certificate  errors

---

boot/bootstate20.go
boot/initramfs_test.go
cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
tests/nested/core/bad-try-kernel-no-reboot/task.yaml

In case a bad try kernel was in the disk (i.e. by just a simple
dangling symlink try-kernel.efi), we entered a boot loop. Avoid that.

boot: avoid reboot loop if there is a bad try kernel

---

interfaces/builtin/shared_memory.go
interfaces/policy/basedeclaration_test.go
interfaces/policy/policy.go
interfaces/policy/policy_test.go

mostly purely for consistency the InstallCandidateMinimalCheck so far took into account both the the allow-installation and deny-installation constraints but only for their snap types and on-classic constraints
so far nothing in the base-declaration was using deny-installation though
switch to ignore deny-installation in the minimal check, this let us express super-privileged app-provided slots even in cases where there can also be system slots while supporting installation via --dangerous as app gets listed in the allow-installation side

interfaces: simplify the InstallCandidateMinimalCheck to help expressivity

---

overlord/devicestate/devicemgr.go
overlord/devicestate/devicestate_test.go
overlord/devicestate/export_test.go
overlord/devicestate/firstboot.go
overlord/devicestate/firstboot20_test.go
overlord/devicestate/firstboot_preseed_test.go
overlord/devicestate/firstboot_test.go
overlord/devicestate/handlers_test.go

also importAssertionsFromSeed
adjust the tests
the reason for this change is to be able to unify the early seed loading double caching that now exists both in loadDeviceSeed and earlyLoadDeviceSeed

o/devicestate: turn populateFromSeed into a DeviceManager method

---

tests/lib/pkgdb.sh

The package libfwupdplugin5 is not available anymore for opensuse tumbleweed.
'libfwupdplugin5' not found in package names. Trying capabilities. No provider of 'libfwupdplugin5' found.

tests: update dependencies to fix opensuse tumbleweed update process

---

snap/quota/quota.go
snap/quota/quota_test.go
wrappers/services.go
wrappers/services_gen_test.go
wrappers/services_test.go

This support was missing for the per-service quotas. Since we no longer allow specifying journal quotas for service sub-groups, they should instead inherit their parent journal quota (if set). This adds this missing code.

snap/quota,wrappers: support inheritting journal quota for service sub-groups

---

daemon/api_base_test.go
daemon/daemon_test.go
overlord/devicestate/devicemgr.go
overlord/devicestate/devicestatetest/state.go
overlord/devicestate/export_test.go
overlord/devicestate/firstboot.go
overlord/devicestate/firstboot20_test.go
overlord/devicestate/firstboot_preseed_test.go
overlord/devicestate/firstboot_test.go
overlord/devicestate/handlers_test.go
overlord/managers_test.go
overlord/overlord_test.go

Remove the current double caching both in the state cache and on DeviceManager, keep the latter only and for the happy case.
Start simplifying the arguments to populateFromSeedImpl as well now that is a method on DeviceManager.
See the single commits as well.

many: simplify loading and caching of the device seed in devicestate

---

interfaces/builtin/dm_crypt.go

When running `cryptsetup luksFormat` cryptsetup attempts to open /run but fails due to a missing apparmor rule
Fixes: https://bugs.launchpad.net/snapd/+bug/1999683
Signed-off-by: Peter Sabaini <peter.sabaini@canonical.com>

interfaces: add read access to /run for cryptsetup for dm-crypt

---

interfaces/builtin/block_devices.go
interfaces/builtin/raw_volume.go

Ubuntu Core ships mkfs.ext4 and mkfs.vfat utilities as part of the rootfs. Some developers/customers reported that they are not able to leverage existing e2fsprogs and dosfstools but need to `stage-package` them as part of their snap. This PR provides access to `mkfs.ext4` and `mkfs.vfat` once `block-devices` or `raw-volume` is connected.

interfaces: expand block-devices and raw-volume to support mkfs tools

---

tests/nested/manual/core20-early-config/defaults.yaml
tests/nested/manual/core20-early-config/task.yaml

As the previous value was too high and systemd complained.

tests/core20-early-config: change watchdog timeout

---

tests/main/lxd-mount-units/task.yaml
tests/main/lxd-no-fuse/task.yaml
tests/main/lxd-postrm-purge/task.yaml
tests/main/lxd-services-smoke/task.yaml
tests/main/lxd-try/task.yaml
tests/main/lxd/task.yaml

There is no community image published for lunar yet.
When the image is published the tests are going to be updated to include lunar
Also some comments are fixed and not used code is removed
There is a following pr created #12458 to re-enable the lxd tests once the images are published

tests: skip lxd tests in ubuntu lunar

---

client/client.go
client/client_test.go
cmd/snap/cmd_snap_op.go
httputil/client.go
httputil/logger.go
logger/logger.go

Add a SNAP_CLIENT_DEBUG_HTTP bitfield environment variable that allows logging requests, responses and bodies that the client receives from the REST API. Bodies are never logged in local installs because, since they contain packaged snaps, their size would make the log unreadable.

many: support logging HTTP requests in the client

---

.github/workflows/test.yaml
build-aux/snap/snapcraft.yaml

We had the issue that builds got reported as dirty. This got fixed in #12463
This was a bit harder to debug than needed, this commit helps to find the
reason more quickly by running the dirty detection after the
`dpkg-buildpackage` run and by fixing a bug in the extraction code in
the GH action that prevented showing the actual diff.

mkversion: show diff when the version is dirty

---

bootloader/assets/genasset/main.go

The copyright of the auto-generated grub_{recovery,}_cfg_assets.go
file is generated from the current date. This leads to a dirty build
when the year changes. This commit hardcodes the copyright year
to 2022.
Once there is a better go build system (or we use something like
meson) we can re-introduce this because then the generated files
will be no longer in git.

bootloader: use fixed copyright year

---

overlord/devicestate/devicemgr.go
overlord/devicestate/devicestate_test.go
overlord/devicestate/export_test.go
overlord/devicestate/firstboot.go
overlord/devicestate/firstboot20_test.go
overlord/devicestate/firstboot_preseed_test.go
overlord/devicestate/firstboot_test.go
overlord/devicestate/handlers_test.go

this also means not passing this information into populateFromSeedImpl and
importAssertionsFromSeed anymore but taking it from DeviceManager

o/devicestate: find out seed label and mode only once

---

client/quota.go
client/quota_test.go
cmd/snap/cmd_quota.go
cmd/snap/cmd_quota_test.go
cmd/snap/complete.go
daemon/api_quotas.go
daemon/api_quotas_test.go
tests/main/snap-quota-services/task.yaml

This is the last PR in the series, and contains the neccessary front-end changes for per-service quota to work. This also includes the spread tests.
This PR needs https://github.com/snapcore/snapd/pull/12316 and https://github.com/snapcore/snapd/pull/12395 to land first.

client,cmd/snap: add frontend support for per-service quotas (3/3)

---

osutil/inotify/LICENSE
osutil/inotify/PATENTS
osutil/inotify/README.md
osutil/inotify/inotify.go
osutil/inotify/inotify_linux.go
osutil/inotify/inotify_linux_test.go
osutil/inotify/inotify_others.go
sandbox/cgroup/export_test.go
sandbox/cgroup/monitor.go
sandbox/cgroup/monitor_test.go
sandbox/cgroup/scanning.go
sandbox/cgroup/scanning_test.go

cgroup: Add Snap/Cgroup monitoring capabilities (alternative MR)
This is an alternative MR for adding a Snap/Cgroup monitor that allows other parts of the code to wait until all the instances of a Snap have ended and it can be safely refreshed. It is the first step for a bigger MR that will allow to automagically refresh a snap after the system has notified the user that there is a refresh available and that they must close it.

many: implementation file monitoring for snap cgroups

---

bootloader/assets/genasset/main_test.go

`master` is failing due to a broken unit test. https://github.com/snapcore/snapd/pull/12469 changed the copyright in the generated asset to used a fixed year while the unit test was still using the current year.

bootloader: fix test w/ auto-generated copyright year

---

image/image_linux.go

Hi, 
IMO, I think it would be helpful to show the revision of snaps when building Ubuntu Core image, most of the time I need to spend quite some time(depends on the download speed, it might take more than 10 mins to download kernel snap) to fetch at least 4 snaps for building image, so if somehow I made a mistake and downloading the snap with incorrect revision, I can notice that in a relative early stage and save some time since I need to build image over and over again
thanks in advance!

image: show snap revision when fetching

---

strutil/version.go

strutil/version.go:104:2: should use 'return !matchEpoch(a)' instead of 'if matchEpoch(a) { return false }; return true' (S1008)

strutil: go staticcheck (S1008) code simplification

---

overlord/configstate/configcore/users.go

o/configstate/configcore: users.go makes sense only with !nomanagers

---

tests/main/interfaces-many-core-provided/task.yaml

As the test interfaces-many-core-provided is continuously failing with test kill timeout, the idea is to reduce the number of connections tested to speed up the test. 
This is needed because Debian 10 has bad performance disconnecting interfaces.

tests: reduce the number of conections testsed in debian 10

---

overlord/snapstate/autorefresh.go
overlord/snapstate/autorefresh_test.go
overlord/snapstate/handlers.go
overlord/snapstate/refresh.go
overlord/snapstate/refresh_test.go
overlord/snapstate/snapstate.go

Per the refresh app awareness UX improvement spec, don't trigger a notification stating that a refresh is pending due to a running snap if the refresh was triggered by the user. It's unnecessary since the error message will already carry the same information. We'll still trigger the notification when auto-refreshes are blocked by a running snap.

o/snapstate: don't notify of pending refresh if it's manual

---

cmd/snap-update-ns/change.go
cmd/snap-update-ns/change_test.go
tests/main/layout-remove/task.yaml
tests/main/layout-remove/test-layout-v1/bin/test
tests/main/layout-remove/test-layout-v1/meta/snap.yaml
tests/main/layout-remove/test-layout-v2/bin/test
tests/main/layout-remove/test-layout-v2/meta/snap.yaml

In some cases we were keeping mounts from removed layouts, because we
were not identifying properly the mounts that we wanted to keep, as we
used mountpoint as key for the reuse map used in neededChanges, while
there are corner cases when we mount more that once on a given
mountpoint. This can happen when, say, we have a layout for /dir/sd1
and another one for /dir/sd2/sd3, being the case that /dir/sd1 and
/dir/sd2/sd3 do not exist (but their parent dirs do exist) - /dir/sd2
will be one of the bind mounted directories of the tmpfs that is
created in /dir to have a layout on /dir/sd1, while at the same time a
tmpfs will be mounted in /dir/sd2 so we can have a layout in
/dir/sd2/sd3. So /dir/sd2 is used twice with different filesystem
types (none and tmpfs).
To prevent this, use as key in …

cmd/snap-update-ns: prevent keeping unneeded mountpoints

---

wrappers/services.go

Observed in other PRs that a test was failing due to varying order of generated service units.
We were already sorting the services, just not using the sorted list.
EDIT: Thanks to @MiguelPires, The relevant test is `servicesTestSuite.TestEnsureSnapServicesWithSnapServices`

wrappers: use sorted services for consistent test output

---

tests/main/lxd/task.yaml

snap.mount is not generated by snapd-generator if / is shared.

tests/main/lxd: fix a check

---

secboot/secboot_sb_test.go
snap/errors.go
snap/errors_test.go
snap/snapfile/snapfile.go
snap/snapfile/snapfile_test.go

When a NotSnapError is returned right now there is no context provided what went wrong. This makes debugging issues difficult when the user just reports:
```
2022-11-23T14:47:57Z ERROR "/var/lib/snapd/snaps/.local-install-130452292" is not a snap or snapdir
```
This commit creates a constructor `snap.NewNotSnapErrorWithContext()` that provides some context like:
```
cannot process snap or snapdir: open non-existing-file: no such file or directory
cannot process snap or snapdir: directory "empty-dir" is empty
cannot process snap or snapdir: directory "invalid-dir" is invalid
cannot process snap or snapdir: file "not-snap" is invalid header [110 111 116 45 97 45 115 110 97 112])
```

snap: provide more error context in `NotSnapError`

---

interfaces/builtin/desktop_launch.go

Many snaps put their icons inside the snap metadata directory (e.g. gnome-calculator). If you have a confined launcher app (e.g. a shell in a core desktop) it cannot access these icons unless they are moved to a public location like `/var/lib/snapd/desktop/icons/`. This change allows a snap with the desktop_launch plug to access metadata for all snaps, and so the icons show without modifying the snap.
This change is based on the fact that a snap using the desktop_launch is already aware of all the snaps installed on the system, so accessing the metadata is a reasonable thing to do. The metadata is not expected to contain anything considered a security issue for the consuming snap to know.

interfaces: Allow desktop_launch interface to access all snap metadata

---

tests/nested/manual/core20-early-config/task.yaml

This reverts commit ccc1cde1ee422f7944ccbb57483feb517438ab03.
Once netplan is fixed we can undo https://github.com/snapcore/snapd/pull/12376

tests: revert disable netplan part of core20-early-config on 22.04-64 

---

interfaces/builtin/modem_manager.go

NETLINK_ROUTE netlink sockets are being used since modem-manager 1.18 for some modems.

interfaces/modem-manager: add permissions for NETLINK_ROUTE

---

tests/main/lxd-mount-units/task.yaml
tests/main/lxd/task.yaml

snap.mount is not generated by snapd-generator if / is shared.
Like #12492

tests/main/lxd-mount-units: fix a check

---

overlord/snapstate/handlers.go
overlord/snapstate/handlers_prereq_test.go

During seeding, UpdateWithDeviceContext will fail with a conflict error describing that it is too early to update snaps, as we have not been seeded. Handle this and log that it was not possible, but do not return an error as this will break seeding, also do not return a state.Retry in this case as this will result in an infinite loop which will halt seeding.
This is related to https://github.com/canonical/workshops/issues/32

o/snapstate: do not infinitely retry when an update fails during seeding

---

go.mod
go.sum
overlord/devicestate/devicemgr.go
overlord/devicestate/devicestate_install_api_test.go
overlord/devicestate/devicestate_install_mode_test.go
overlord/devicestate/devicestate_systems_test.go
overlord/devicestate/export_test.go
overlord/devicestate/handlers_install.go
secboot/export_sb_test.go
secboot/secboot_dummy.go
secboot/secboot_sb_test.go
secboot/secboot_tpm.go
tests/nested/manual/muinstaller-real/task.yaml

This commit fixes the issue that the detection of TPM key sealing does not take into account if the system is already has the lockout auth attribute set. If this is the case an install will not be successful but currently this is detected very late.

secboot: detect lockout mode in CheckTPMKeySealingSupported

---

spread.yaml

This is needed to keep updated the sru systems

tests: add ubuntu kinetic to google-sru backend

---

overlord/snapstate/autorefresh.go
overlord/snapstate/autorefresh_test.go
overlord/snapstate/export_test.go
overlord/snapstate/refresh.go
overlord/snapstate/refresh_test.go

Remove the soft and hard check functions which have grown into the same check (`app.IsService() || app.RefreshMode == "ignore-running"`). Since these were being passed into a function which was itself called in a lambda passed into different locking functions, this also simplifies the logic surround the refresh checks.

o/snapstate: remove duplicated refresh checks

---

cmd/snap-confine/mount-support.c

fdopendir() takes ownership of the underlying file descriptor (rootfs_fd) so we should not declare rootfs_fd with SC_CLEANUP(sc_cleanup_close) otherwise it will be potentially close()'d twice.
As detected by scan.coverity.com -
https://scan7.scan.coverity.com/reports.htm#v42873/p15001/fileInstanceId=133708012&defectInstanceId=18701665&mergedDefectId=1532043

snap-confine: avoid possible double close() in sc_replicate_base_rootfs

---

daemon/api_apps_test.go
daemon/daemon_test.go
overlord/configstate/configcore/services.go
overlord/hookstate/ctlcmd/mount.go
overlord/hookstate/ctlcmd/mount_test.go
overlord/managers_test.go
overlord/servicestate/servicemgr_test.go
overlord/snapstate/backend/mountunit.go
overlord/snapstate/backend/mountunit_test.go
overlord/snapstate/backend/setup_test.go
overlord/snapstate/handlers_prereq_test.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go
systemd/emulation.go
systemd/systemd.go
systemd/systemd_test.go
tests/core/snapd-failover/task.yaml
tests/core/snapd16/task.yaml
tests/main/snapd-update-services/task.yaml
wrappers/core18.go
wrappers/services.go

When updating service files for the snaps, this also verifies the mount unit of the snap is updated. This however does not update mounts generated from `snapctl mount`.
Note that there is a lot or renaming. So to ease the review I have split it in commit with separate concerns.

servicemgr: update mount files

---

spread.yaml
tests/lib/prepare.sh
tests/lib/snaps/test-snapd-sh-core24/bin/sh
tests/lib/snaps/test-snapd-sh-core24/meta/snap.yaml

This is needed by core-base CI.

spread: add external:ubuntu-core-24-64

---

interfaces/builtin/fwupd.go
interfaces/builtin/fwupd_test.go
interfaces/builtin/polkit.go

This is what is needed to run `get-devices` fwupd on an Intel NUC.
Note for review, this has been tested with fwupd/fwupd#5062

i/b/fwupd: add more permissions

---

tests/main/snap-quota-install/task.yaml

The following error is displayed when the test is executed
snap set-quota group-one --memory=400MB
error: cannot create quota group: cannot create quota group "group-one": cannot
use memory quota: memory cgroup is disabled on this system

tests: skip snap-quota-install in arm core systems

---

cmd/snap/cmd_run_test.go

**Problem:**
When running `run-checks --unit` with snap `snapd-desktop-integration` installed in devmode, the unit test `RunSuite. TestDesktopIntegrationNoDBus` fails. This is because there is no mocking and a DBus message is successfully send which is not expected.
**Solution:**
Added DBus mocking.

cmd/snap: improved robustness of unit test TestDesktopIntegrationNoDBus

---

cmd/snap/cmd_run_test.go
cmd/snap/export_test.go
cmd/snap/inhibit.go

**Problem:**
When running `run-checks --unit` with snap `snapd-desktop-integration installed` in `devmode`, the unit tests `TestWaitWhileInhibitedGraphicalSessionFlow`, `TestWaitWhileInhibitedGraphicalSessionFlowError`, `TestWaitWhileInhibitedGraphicalSessionFlowErrorOnFinish` fails and or timeout.
The underlying issue in all three test is that the target function `graphicalSessionFlow` does not get called due to the presence of DBus and `snapd-desktop-integration` affecting the return values from function `tryNotifyRefreshViaSnapDesktopIntegrationFlow` in an unexpected way. Also, when inhibit state is not unlocked with a mock, `tryNotifyRefreshViaSnapDesktopIntegrationFlow` is stuck in `waitInhibitUnlock` loop until timeout (the case with test …

cmd/snap: improved robustness of unit tests TestWaitWhileInhibitedGraphicalSession*

---

tests/lib/muinstaller/main.go

The muinstaller imports from gadget/install code that has the `//go:build !nosecboot` build tag. However the muinstaller itself does not have this build tag which means that when building under Debian the build will fail because we set `nosecboot` there.
Tested by running:
```
$ spread -debug -v google:debian-sid-64:tests/nightly/sbuild
2023-01-26 10:42:28 Allocating google:debian-sid-64...
...
2023-01-26 11:17:59 Restoring google:debian-sid-64:tests/nightly/sbuild:normal (jan260942-675130)...
2023-01-26 11:18:23 Restoring google:debian-sid-64:tests/nightly/ (jan260942-675130)...
2023-01-26 11:18:32 Restoring google:debian-sid-64 (jan260942-675130)...
2023-01-26 11:18:32 Discarding google:debian-sid-64 (jan260942-675130)...
2023-01-26 11:21:11 Restoring …
```

tests: add `go:build !nosecboot` to avoid sbuild failure

---

cmd/snap/cmd_help.go
cmd/snap/cmd_quota.go
daemon/api_quotas_test.go
features/features.go
features/features_test.go
overlord/configstate/configcore/vitality_test.go
overlord/ifacestate/handlers_test.go
overlord/managers_test.go
overlord/servicestate/quota_control.go
overlord/servicestate/quota_control_test.go
overlord/servicestate/quota_handlers_test.go
tests/core/mem-cgroup-disabled/task.yaml
tests/main/postrm-purge/task.yaml
tests/main/quota-groups-systemd-accounting/task.yaml
tests/main/snap-mgmt/task.yaml
tests/main/snap-quota-cpu/task.yaml
tests/main/snap-quota-install/task.yaml
tests/main/snap-quota-memory/task.yaml
tests/main/snap-quota-thread/task.yaml
tests/main/snap-quota/task.yaml

Also repurpose quota-groups experimental feature instead of introducing a new feature flag.
This is a different approach that I think would be better, and also avoids introducing a new feature flag. This PR superseeds https://github.com/snapcore/snapd/pull/11991

many: move memory,cpu and thread quota out of experimental

---

overlord/snapstate/booted.go
overlord/snapstate/booted_test.go
tests/nested/manual/fde-on-classic/task.yaml

The existing `UpdateBootRevisions()` does not take into account that not all systems use the base as a boot participant. On a classic+modes system only the kernel is relevant. This PR updates this code to skip non-boot participants when checking if there were rollbacks across reboots.

snapstate: fix update boot revisions for classic+modes devices

---

overlord/configstate/configcore/homedirs.go
overlord/configstate/configcore/homedirs_test.go
tests/main/snapd-homedirs/task.yaml

Only invoke apparmor parser and reload profiles if apparmor is actually supported on the host, otherwise homedirs will act as a no-op to not break configure-hooks. Also only update apparmor rules if the homedirs actually change.
This is related to LP2002835.

o/configstate/configcore: do not invoke apparmor_parser when unsupported

---

overlord/configstate/configcore/homedirs_test.go

This lack of apparmor mocking made the launchpad builder fail. => https://launchpadlibrarian.net/649167600/buildlog_ubuntu-trusty-amd64.snapd_2.58.2~14.04+git4377.4e4abef0d~ubuntu14.04.1_BUILDING.txt.gz
My earlier PR touching the homedir code introduced this, as we now do an apparmor check, and if no apparmor is present, then homedir option acts as a no-op, and this messed up some of the unit tests when run on a host where no apparmor is supported.
Verified failing on Fedora 37 host, and they pass with this PR.

o/configstate/configcore: missing apparmor mocking for non-aa hosts

---

store/store.go
store/store_action.go
store/store_action_fetch_assertions_test.go
store/store_asserts.go
store/store_asserts_test.go

introduce Config.AssertionMaxFormats and Store.SetAssertionMaxFormats
the latter follows the pattern established by Store.SetCacheDownloads

store: provide ways to override the assertion max formats sent as supported

---

boot/makebootable.go
boot/makebootable_test.go

This is a followup for the PR#12532. Right now the system does put the `base` into the modeenv on `classic+modes` system. But here there is no need to keep track of the base as it is not used for booting, the deb based classic system is used for that.

boot: do not include `base=` in modeenv for classic+modes installs

---

interfaces/builtin/bluez.go

The bluetooth stack implements a way to circumvent the bluez socket and instead communicate over DBus to share a file descriptor between two different process IDs. This apparmor rule allows such file descriptor exchanging to be allowed.
Signed-off-by: Dilyn Corner <dilyn.corner@canonical.com>
Rule was created by Tony Espy after some discussions with John Johansen. 
Essentially, there are some useful rust bindings provided by bluer, a crate providing official rust bindings for bluez. It implements two methods which have the value-add of decreasing latency when interacting with devices connected over BLE. What this amounts to is directly passing a particular file descriptor from one process to another. The added rules should be scoped narrowly enough such that one would have the minimum …

interfaces: bluez: allow file descriptors to be shared via dbus

---

gadget/gadget.go
gadget/gadget_test.go

Hi, 
I think it would be better if we can check the offset does not overlap with GPT partition table when building gadget snap, here are some testing result if I try to set the offset that overlap with the GPT partition table, the image built by using ubuntu-image will be un-usable
If I understand correctly, the GPT partition table start at sector 2, and will have length 16384 bytes, so if the offset defined in gadget.yaml is less than 17408, then it will overlap the GPT partition table
Here is the gadget.yaml that will overlap with GPT partition, the offset is 17407
```sh
$ cat gadget/prime/meta/gadget.yaml 
device-tree-origin: kernel
device-tree: XXXXX.dtb
volumes:
test:
schema: gpt
bootloader: u-boot
structure:
- name: firmware
offset: 17407
size: 64M
type: …
```

gadget: return error if offset is less than 17408 bytes in gpt schema

---

interfaces/builtin/network_manager.go

Some kernels/network-manager versions produce read instead of trace denials, see LP: #1980119. For reference, see [1].
[1] https://gitlab.com/apparmor/apparmor/-/wikis/TechnicalDoc_Proc_and_ptrace#apparmor-3-with-ptrace-rules

interfaces/network-manager: do not show ptrace read denials

---

boot/boot.go
boot/boot_test.go

This commit fixes a a bug in master that will prevent `MarkBootSuccessful` from working. The issue is that on classic+modes the modeenv no longer contains a `base=` field but the MarkBootSuccessful code will fail if it is missing. This results in a system that never marks the boot as successful on classic+modes.
Setting to critical as master and release/2.58 are broken right now for classic+modes (neither is is stable so that is okay)

boot: on classic+modes `MarkBootSuccessfull` does not need a base

---

boot/boot.go
boot/boot_test.go

This commit fixes a a bug in master that will prevent `MarkBootSuccessful` from working. The issue is that on classic+modes the modeenv no longer contains a `base=` field but the MarkBootSuccessful code will fail if it is missing. This results in a system that never marks the boot as successful on classic+modes.
This is https://github.com/snapcore/snapd/pull/12549 for 2.58

boot: on classic+modes `MarkBootSuccessfull` does not need a base (2.58)

---

store/cache.go
store/cache_test.go
store/store_download.go
store/store_download_test.go

If a snap was already in the target path, the cache would try to link the cached file to that path, fail and return an os.ErrExist. Since the store code was interpreting any error from the cache as a cache miss, it would re-download it. In practice this didn't happen often because when installing/refreshing a snap the file is eventually deleted from that location so subsequent downloads wouldn't hit the issue unless the install/refresh is aborted. However, when we start pre-downloading snaps we would start hitting this in every delayed auto-refresh (that's how I noticed it).

store: fix cache miss when snap was already in download path

---

httputil/retry.go

The error is wrapped in Go1.20 so we need to unwrap first.
Fix https://bugs.launchpad.net/snapd/+bug/2006676

httputil: fix checking x509 certification error on Go1.20

---

interfaces/builtin/modem_manager.go

This is needed for NETLINK_ROUTE sockets, which started to be used by ModemManager 1.18.

interfaces/modem-manager: add net_admin capability

---

image/image_linux.go
overlord/devicestate/systems.go
seed/seedtest/seedtest.go
seed/seedwriter/seed16.go
seed/seedwriter/seed20.go
seed/seedwriter/writer.go
seed/seedwriter/writer_test.go

this will allow to try to make appropriate choices about the assertion formats that are compatible with the snapd code in the created seed/image
the implementation is a bit more complex than waiting till complete Downloaded for this, to try to preserve failing as early as possible

many: delay fetching assertions until snapd-carrying snaps are known

---

daemon/api_debug.go
gadget/device_darwin.go
gadget/device_linux.go
gadget/device_test.go
gadget/gadget.go
gadget/gadget_test.go
gadget/gadgettest/gadgettest.go
gadget/install/content.go
gadget/install/encrypt.go
gadget/install/encrypt_test.go
gadget/install/export_test.go
gadget/install/install.go
gadget/install/install_test.go
gadget/install/partition.go
gadget/install/partition_test.go
gadget/layout.go
gadget/layout_test.go
gadget/ondisk.go
gadget/raw.go
gadget/raw_test.go
gadget/update.go
gadget/update_test.go
overlord/devicestate/handlers_install.go
tests/lib/muinstaller/go.mod
tests/lib/muinstaller/main.go
tests/nested/manual/muinstaller-real/task.yaml

Include OnDiskStructure in LaidOutStructure so we really have all the
needed information to create partitions and content in
LaidOutStructure. Also, remove the now unneeded
onDiskAndLaidoutStructure.

gadget: include OnDiskStructure in LaidOutStructure

---

snap/info.go
snap/info_test.go
snapdtool/info_file.go
snapdtool/info_file_test.go

this will be useful to determine supported assertion max formats for snapd/core and kernel snaps that are used to build an image
to do this we split out snapdtool.ParseInfoFile

snap,snapdtool: introduce SnapdAssertionMaxFormatsFromSnapFile

---

.shellcheckrc
tests/lib/pkgdb.sh
tests/lib/prepare.sh

Shellcheck v0.9.0 added [SC2317](https://github.com/koalaman/shellcheck/commit/642ad8612597b28af4026bde289985583fddb69d) to detect unreachable code.
This caused shellcheck failures that is already addressed with [this approach](https://github.com/ernestl/snapd/commit/1d417aa3d0ed4a105162840412ef57d49dd97951).
This proposal is an alternative approach to avoid global disable of the unreachable code check:
1. Excluding the error at specific places as required for placeholder scripts that need to exit with failure if not populated (tests/lib/pkgdb.sh)
2. Avoiding the error by disabling unused code in if statement (tests/lib/prepare.sh)

.shellcheckrc, tests/lib: fix unreachable code warnings without global disable

---

overlord/managers_test.go
overlord/snapstate/autorefresh.go
overlord/snapstate/autorefresh_gating_test.go
overlord/snapstate/autorefresh_test.go
overlord/snapstate/conflict.go
overlord/snapstate/export_test.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_rerefresh_test.go
overlord/snapstate/progress.go
overlord/snapstate/refresh.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go

If an auto-refresh is totally or partially prevented due to some snaps being open, create pre-download tasks so that, when the user is asked to close the snap, it's ready to be auto-refreshed as quickly as possible. If the inhibition window has passed, pre-downloads aren't created and instead the user is notified that the refresh is proceeding despite the open snap. The next PR will add the actual pre-download logic as well as the related logic w.r.t waiting for snaps to close, concurrent downloads, continuing delayed auto-refreshes, etc.

o/snapstate: mk pre-download tasks if running snap blocks autorefresh

---

interfaces/builtin/fwupd.go

fwupd is going to use its own EFI directory to be able to handle multiple distros from the snap. For that it will need to copy Ubuntu's signed shim. And to not pollute the distro's directory, it will use its own. So we should just give it permission to put any file there.
See https://github.com/fwupd/fwupd/pull/5508

i/b/fwupd: allow writing in EFI's fwupd directory

---

overlord/snapstate/conflict.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_test.go

Add helper function that checks if there are active tasks that will affect the kernel command line, and use it in corresponding handlers.

o/snapstate: check for kernel cmdline update conflicts

---

image/image_linux.go
image/image_test.go
image/preseed/preseed_uc20_test.go
store/tooling/tooling.go
store/tooling/tooling_test.go

this fetches assertions using the right assertion max formats based
on what is supported by the snapd from the system snap going into the image
a later PR will do as best effort to take the kernel into account as well for UC20+

image,store: ensure to fetch assertions appropriate for the snapd in the image

---

wrappers/services_test.go

Remove unreachable code in the shell scripts used in the wrappers tests since it causes shellcheck to error.

wrappers: remove unreachable test code

---

interfaces/builtin/mount_control.go
interfaces/builtin/mount_control_test.go

The `functionfs` `what` rules are too strict. With functionfs pretty much anything can be in the `what` line so best to not bother, especially since functionfs requires a explicit mention in the plug declaration.

interfaces: relax rules for mount-control `what` for functionfs

---

interfaces/builtin/screen_inhibit_control.go

This is required for firefox
https://bugzilla.mozilla.org/show_bug.cgi?id=1785799

interfaces/screen-inhibit-control: Add support for xfce-power-manager

---

gadget/gadget.go
gadget/gadget_test.go
gadget/kcmdline.go
gadget/kcmdline_test.go
osutil/kcmdline.go
osutil/kcmdline_test.go

Add support for gadget's kernel-cmdline stanza, only for the allow list for the moment.

gadget,osutil: add support for gadget's kernel-cmdline stanza

---

boot/makebootable_test.go
bootloader/export_test.go
bootloader/piboot.go
bootloader/uboot.go
bootloader/uboot_test.go
bootloader/ubootenv/env.go
bootloader/ubootenv/env_test.go

First commit adapts ubootenv code to successfully read both formats of environments (uboot details [here](https://github.com/u-boot/u-boot/blob/7b84c973b96775576dcff228d865e8570be26c82/include/env_internal.h#L58) and [here](https://github.com/u-boot/u-boot/blob/7b84c973b96775576dcff228d865e8570be26c82/include/env_internal.h#L80)). The only really interesting thing here is that when `Open`ing an existing env file, it autodetects the format, and the caller only needs to specify the format when creating a new environment from scratch using `Create`.
For uboot, `Create` is only really called in one place (outside of unit tests and piboot), which is when creating the recovery boot.sel file (run mode boot.sel comes directly from gadget). This proposal reads that boot.sel file that is in the …

bootloader: handle uboot with SYS_REDUNDAND_ENVIRONMENT=n

---

overlord/configstate/configcore/kernel.go
overlord/configstate/configcore/kernel_test.go
overlord/configstate/configcore/runwithstate.go

Add options that will allow appending new arguments to the kernel command line. These are:
- system.kernel.cmdline-append, valid for any model grade
- system.kernel.dangerous-cmdline-append, valid only for dangerous models

overlord: add kernel command line options

---

tests/lib/fakestore/cmd/fakestore/cmd_make_refreshable.go
tests/lib/fakestore/refresh/refresh.go
tests/nested/manual/muinstaller-real/task.yaml

To ensure the kernel/gadget refresh works correctly for the encrypted cases this commit adds a new test that creates a new gadget and kernel snap and refreshes those.
The test will also check that the reboot will not happen automatically.

tests: test kernel/gadget refresh as part of muinstaller-real for both encrypted/unencrypted use-cases

---

image/image_linux.go
image/image_test.go

I have seperated out some of the steps done by SetupSeed in preparation to add support for validation sets. This is *only* cleanup by seperating out some of the code, no functionality have been added or removed. All unit tests still pass, so I feel safe that behaviour is identical.
If anyone wants to suggest any changes or any documentation for the changes please do.

image: cleanup setupSeed before adding support for validation sets

---

cmd/snaplock/runinhibit/inhibit.go
overlord/managers_test.go
overlord/snapstate/autorefresh.go
overlord/snapstate/autorefresh_test.go
overlord/snapstate/backend_test.go
overlord/snapstate/export_test.go
overlord/snapstate/handlers.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate_update_test.go
sandbox/cgroup/monitor.go

Handle a pre-download task by downloading the snap (so it's in the cache for the subsequent auto-refresh for that snap) and perform a soft check to see if the snap is still running. If it is, notify the user to close the snap and monitor for its closure. Once the snap closes, trigger an auto-refresh change and clear the monitoring state. If the soft check doesn't fail (the snap isn't running), the auto-refresh is triggered directly.

o/snapstate: pre-download and monitor snap for auto-refresh

---

overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_update_test.go

When deciding whether to create a new pre-download task or not, don't consider "Done" pre-download tasks since we can't know whether the auto-refresh they trigger has finished. If we don't create a new pre-download change because of a "Done" task and the auto-refresh it triggers completed before the current one was inhibited, we would miss a valid pre-download scenario. On the other hand, if we schedule an unnecessary pre-download change, the worst case scenario is that the snap is already in the cache and the auto-refresh is a no-op.

o/snapstate: create pre-dl task even if one is in DoneStatus

---

tests/lib/prepare.sh

When we get mount for the core snap, in arch linux the mount entry matches with 2 lines.
/var/lib/snapd/snaps/core_14940.snap on /var/lib/snapd/snap/core/14940 type squashfs (ro,nodev,relatime,errors=continue)
/var/lib/snapd/snaps/core_14940.snap on /var/lib/snapd/snap/core/14940 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide,x-gvfs-hide)
The change is done to get one of them, otherwise it fails like this:
+ unsquashfs -no-progress '/var/lib/snapd/snaps/core_14940.snap /var/lib/snapd/snaps/core_14940.snap'
Could not open /var/lib/snapd/snaps/core_14940.snap /var/lib/snapd/snaps/core_14940.snap, because No such file or directory
Also for some reason (possibly a bug) in arch linux, the dbus interface for systemd is not returning the JobRemoved dbus signal, even when it is …

tests: fix prepare task for arch linux

---

cmd/libsnap-confine-private/cleanup-funcs-test.c
cmd/libsnap-confine-private/cleanup-funcs.c
cmd/libsnap-confine-private/cleanup-funcs.h

Deep cleanup of string arrays. Utility function needed for PR https://github.com/snapcore/snapd/pull/12288.

cmd/libsnap-confine-private: add sc_cleanup_deep_strv

---

dirs/dirs.go
snap/sysparams/export_test.go
snap/sysparams/sysparams.go
snap/sysparams/sysparams_test.go

Sysparams package split out from the original PR https://github.com/snapcore/snapd/pull/12288. This is a small package that manages the system-params file under /var/lib/snapd/system-params, and is used to carry configuration data for homedirs to snap-confine.

snap/sysparams: introduce system-params file for managing homedirs

---

cmd/snap/cmd_help.go
cmd/snap/cmd_validate.go
tests/main/snap-validate-basic/task.yaml

Expose the `snap validate` command in the help info

cmd/snap: expose validate command

---

spread.yaml

This is to avoid some errors like this one:
Write on output file failed because No space left on device

tests: add extra space to the arch linux image

---

interfaces/builtin/microovn.go
interfaces/builtin/microovn_test.go
interfaces/policy/basedeclaration_test.go
tests/lib/snaps/test-snapd-policy-app-consumer/meta/snap.yaml
tests/main/interfaces-many-snap-provided/test-snapd-policy-app-provider-classic/meta/snap.yaml
tests/main/interfaces-many-snap-provided/test-snapd-policy-app-provider-core/meta/snap.yaml

This interface makes it possible to control MicroOVN.
It will be used by another snap, MicroCloud to bring up MicroOVN and LXD clusters automatically.

interfaces: add microovn interface

---

daemon/api_debug.go
gadget/install/encrypt.go
gadget/install/encrypt_test.go
gadget/install/export_secboot_test.go
gadget/install/install.go
gadget/install/install_test.go
gadget/update.go
go.mod
go.sum
overlord/devicestate/devicemgr.go
overlord/devicestate/devicestate_install_mode_test.go
overlord/devicestate/handlers_install.go
secboot/encrypt.go
secboot/encrypt_sb.go
secboot/encrypt_sb_test.go
tests/lib/fde-setup-hook/fde-setup.go
tests/nested/manual/uc20-fde-hooks-ice/task.yaml

This is a continuation of the work from Ondra based on input from Samuele.
Followup for https://github.com/snapcore/snapd/pull/12553
Added "skip-spread" until https://github.com/snapcore/secboot/pull/221/files gets merged

gadget: add inline crypto engine support using the device hook

---

secboot/encrypt_sb_test.go

I accidentally merged https://github.com/snapcore/snapd/pull/12589 before fixing the unit test. My bad, this fixes master.

secboot: fix unittest after updating an error message

---

tests/core/gadget-config-defaults-vitality/task.yaml
tests/core/gadget-config-defaults/task.yaml

Path for the mount unit name  was not properly escaped.

tests/core/gadget-config-defaults: fix cleanup

---

overlord/snapstate/handlers.go
overlord/snapstate/snapstate_update_test.go

The deletion of the empty "monitored-snaps" was wrong since it assigned nil to a variable with a map type and passed that into Cache(). This variable isn't equal to nil due to its type so Cache() would store it instead of deleting the state entry.

o/snapstate: fix deletion of monitored snaps map

---

interfaces/apparmor/template.go

See https://forum.snapcraft.io/t/interface-for-reading-proc-pid-cpuset/33886 for discussion but basically this is unprivileged information that is consistent with other similar pieces of information already exposed in the base template.

interfaces/apparmor: add read of /proc/PID/cpuset to base template

---

interfaces/builtin/fwupd.go

See https://github.com/fwupd/fwupd/blob/e69ffa1b713b7e21177bae7483cbbff1596a6284/plugins/uefi-capsule/fu-uefi-cod-device.c#L177

i/b/fwupd: allow to write to some EFI path for some capsules

---

cmd/snap/cmd_snap_op_test.go
cmd/snap/wait.go

This is a tiny patch to make the UX on classic+modes systems more user friendly. Right now when running e.g.
`snap refresh pc-kernel` there is no indication that a system reboot is required to continue, the only visible output is that a re-refresh is attempted.
To fix this properly a bigger change is required and various attempts in PR#12417 are all having problems. However as a very minimal improvement this commit shows log messages from tasks in `Wait` state without changing anything else.
This means that the UX is more like:
```
$ snap refresh pc-kernel
2023-02-24T11:2315Z INFO Task set to wait until a manual system restart allows to continue
Handling re-refresh of "pc-kernel" as needed
```
while not ideal UX it feels like a worthwhile improvement until we find the time to fix this …

snap: show log information from Wait tasks in the CLI

---

overlord/devicestate/devicestate_serial_test.go
overlord/devicestate/devicestatetest/devicesvc.go
overlord/devicestate/firstboot_test.go
overlord/devicestate/handlers_serial.go
overlord/managers_test.go

This PR fixes the issue that getting the serial fails in confusing ways when a custom SSL certificate is needed to connect
to get the serial. The error message in this case is:
```
handlers_serial.go:659: Proxy store does not support custom serial vault; ignoring the proxy
```
which is not at all true.
The root cause for the bug is that the used http client does
set `ExtraSSLCerts`. However there are more issues with the
code, e.g. that `newEnoughProxy` does not return an error but
instead just debug lots it and does nothing less.
The initial commit is a minimal fix, then a unit test change to ensure the MockDeviceService uses https with custom certificates and then a refactor of `newEnoughProxy` to ensure that errors are properly surfaced.
One open question is if `httputil.NewHTTPClient` …

devicestate: fix serial acquire when custom SSL certificates are needed

---

interfaces/builtin/polkit.go
interfaces/builtin/udisks2.go
interfaces/builtin/udisks2_test.go
interfaces/policy/basedeclaration_test.go
osutil/resolve_path.go
osutil/resolve_path_test.go

Here are 4 commits fixing udisks2 to work with newer version on udisks2 snap. And also on non UC distributions. And using polkit when available.
* allow installation of daemon on classic
* allow users to connect to daemon
* add missing AppArmor permissions
* add attribute to load udev rules
Also a commit fixing polkit. udisksd does send calls to methods with the name of the sender, but directly with the address of polkit. So filtering the peer label does not work and does  not let udiskd talk to polkit.
Tested to work with https://github.com/valentindavid/snap-udisks2

i/b/udisks2: multiple fixes

---

interfaces/builtin/desktop_legacy.go

The ibus input method communicates via a private D-Bus message bus implemented with glib's D-Bus implementation. With glib >= 2.75.0, this switched from an abstract namespace unix socket to a regular unix socket. This commit grants access to the regular unix socket path.
More details can be found in [Launchpad bug #2008279](https://launchpad.net/bugs/2008279). The problem is triggered by the glib currently in lunar-proposed, so I think this is a candidate to cherry-pick into the snapd that ships with Ubuntu 23.04.

interfaces: grant access to new ibus socket location in desktop-legacy

---

interfaces/builtin/hardware_observe.go

Each serial driver can leave its own file specifying harware information in /proc/tty/driver/, in the same format as "serial" driver, so we should allow reading any of them. Example of files created there are usbserial, max310x or IMX-uart.

interfaces/hardware-observe: allow readin /proc/tty/driver/*

---

overlord/snapstate/handlers.go
overlord/snapstate/snapstate_update_test.go

Stop monitoring and clear the related state if the user runs a `snap refresh --ignore-running` without stopping the snap.

o/snapstate: stop monitoring if refresh happens

---

overlord/configstate/configcore/handlers.go
overlord/configstate/configcore/kernel_test.go
overlord/configstate/configcore/runwithstate.go
tests/nested/manual/fde-on-classic/task.yaml

used on a system with modes. Use it for the kernel command line
options.

o/configcore: add flag that will determine if a system option can be

---

tests/main/snapd-reexec-prompt/task.yaml

Include ubuntu-core-16-arm-64 in the excluded systems, this is failing as it fails in amd64
This test is failing in beta validation on arm devices

tests: skip snapd-reexec-prompt on arm devices as it is excluded in amd64

---

.github/workflows/test.yaml
.golangci.yml
asserts/fetcher.go
cmd/snap-update-ns/utils.go
spdx/licenses.go
store/store.go
strutil/shlex/shlex.go

It seems the 'deadcode' linter is marked deprecated, and is replaced by unused (we already have that). This caused our static checks to fail
`The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.`

golang: remove deadcode linter and bump version

---

interfaces/builtin/account_control.go

pam uses /var/log/lastlog for successful log attempts, and /var/log/tallylog for failures.

interfaces/account-control: grant access to files needed by pam

---

asserts/header_checks.go
asserts/model.go
asserts/model_test.go

Add `validation-sets` support to the model assertion.

asserts: support validation-sets in model assertion

---

overlord/snapstate/autorefresh.go
overlord/snapstate/autorefresh_test.go

The current code will crash in doInstall() after
softCheckNothingRunningForRefresh() because the returned error if not the nil type but instead it's generated via:
```go
busyErr := &timedBusySnapError{}
...
busyErr = nil
return busyErr
```
when the application is running.
This leads to a confusing crash because the line:
```go
if err := softCheckNothingRunningForRefresh(st, snapst, snapsup, info); err != nil {
```
will execute as if `err != nil` but when accessing `err` it will crash because the err is a nil error interface type so it's like accessing the a nil pointer.
This is similar to https://github.com/snapcore/snapd/pull/12614
Fwiw, the full crash backtrace is:
```
Mär 14 10:09:37 top snapd[64660]: panic: runtime error: invalid memory address or nil pointer dereference
Mär 14 …
```

snapstate: fix crash in doInstall() when doing the soft checks

---

interfaces/builtin/docker_support.go
tests/regression/lp-2011485/task.yaml
tests/regression/lp-2011485/test-snapd-docker-support-core22-app/bin/test-snapd-docker-support
tests/regression/lp-2011485/test-snapd-docker-support-core22-app/meta/snap.yaml

Allow access to apparmor.d/abi/ files, as referenced by apparmor/parser.conf on base:core20+ to allow apparmor_parser to continue to work as used by docker.
LP: #2011485

interfaces: allow docker-support access to apparmor.d/abi/

---

interfaces/builtin/upower_observe.go
interfaces/builtin/upower_observe_test.go
interfaces/policy/basedeclaration_test.go

This change is similar to one done for [polkit](https://github.com/snapcore/snapd/pull/12071).
We want to be able to use the upower-observe interface on Ubuntu Core Desktop, so need an implicit system slot to be present there. This PR takes the approach of providing an implicit slot if the executable /usr/libexec/upowerd exists. This should be true for Core Desktop, and false for regular Core.
Note that there used to be a upower snap, but this was [deprecated](https://forum.snapcraft.io/t/upower-snap-deprecation/14772).

interfaces: make upower-observe implicit on core if /usr/libexec/upowerd exists

---

gadget/kcmdline_test.go
osutil/kcmdline.go
osutil/kcmdline_test.go
tests/nested/manual/fde-on-classic/task.yaml

The current code in kcmdline.go:parseArgumen() will "stanardize" parameters that have "-" to "_". While this is fine for kernel parameters it's breaking use-cases where the kernel commandline is used to transmit information to user-space. One example is the "dhc-dev-mode" option that is used by some systems.
It also means that the allow rules in the gadget must be explicit, i.e. "foo_bar" and "foo-bar" but I think that is reaonable.

osutil: do not change "-" and "_" in kcmdline parseArgument()

---

image/image_test.go
image/preseed/preseed_uc20_test.go
store/tooling/tooling.go
store/tooling/tooling_test.go

Needed as as part of introducing support for validation-sets in seedwriter. This exposes `SeqFormingAssertion` in ToolingStore to retrieve sequence forming assertions, and we then introduce `AssertionSequenceFormingFetcher` to use this.

image,store: introduce AssertionSequenceFormingFetcher in ToolingStore

---

image/image_linux.go
image/image_test.go

The text would come out with additional brackets like this:
`Fetching snapd ({18596})`
but should look like
`Fetching snapd (18596)`

image: fix odd output of 'Fetching ...' text

---

testutil/errorischecker_test.go
testutil/interfacenilchecker.go
testutil/interfacenilchecker_test.go

Add an IsStrictNil checker that ensures that both a variable's type and value are nil. This is useful to prevent returned errors with non-nil types from being compared to a nil value with a nil type (since the compiler can't tell that the other variable is not nil typed), resulting in the check failing.

testutil: add checker for nil typed and valued vars

---

interfaces/builtin/mount_control.go
interfaces/builtin/mount_control_test.go

These changes builds on [PR-12559](https://github.com/snapcore/snapd/pull/12559) to enable using functionfs with the mount-control interface.
Currently a mount-control functionfs use case requires functionfs to be used with options such as:
```what: diag
where: /dev/ffs-diag
type: [functionfs]
options: [uid=2000, gid=2000, rmode=0550, fmode=0660, no_disconnect=1]
```
results in error message `... mount-control option unrecognized or forbidden: "uid=2000"`
This change allows the use of all functionfs specific options when the filesystem type is functionfs only.

interfaces/builtin: allow mount-control functionfs specific options

---

image/image_test.go
seed/seedwriter/seed16.go
seed/seedwriter/seed20.go
seed/seedwriter/writer.go
seed/seedwriter/writer_test.go

with not extended classic models never seeing a system snap or seeing snapd outside the model would not trigger assertion fetching

image,seed/seedwriter: fix corner cases of asserts fetching not triggered

---

snap/validate.go
snap/validate_test.go

On a usrmerge'd system, /lib is a symlink to /usr/lib and /var/run is a symlink to /run - ensure these are also tested for when validating a snap layout.
Noticed in https://forum.snapcraft.io/t/snap-layouts/7207/50

snap: tighten up layout path checking for usrmerge'd systems

---

CONTRIBUTING.md
HACKING.md

- integrated @mardy's contribution improvements (with thanks to @mardy)
- renamed tags to labels to avoid confusion with git tags
- to keep the technical focus in HACKING.md, moved the contributing parts to the pre-existing CONTRIBUTING.md
- typo pass

docs: updates to CONTRIBUTING.md and HACKING.md

---

interfaces/builtin/steam_support.go
interfaces/builtin/steam_support_test.go
run-checks

This allows the Steam snap to add the `udev` rules from the `steam-devices` apt package. We're currently at an impasse on potentially allowing broader changes to the `udev` ecosystem in `snapd` so this works as a good enough fix for our current purposes.
The issue is that currently for a lot of controllers to work (in Steam), users need to `apt install steam-devices`, which, if installing recommends is enabled (as it is for most people) will also install the `deb` version of Steam. This bypasses this and installs the `udev` rules along with the snap on the connection of the `steam-support` plug. The addition is structured such that if `steam-devices` changes it's easy to copy+paste the new file (at least until/unless the game controller rules end up in `systemd` which will likely happen …

steam-support: add udev rules from steam-devices

---

asserts/fetcher.go
asserts/fetcher_test.go
image/image_linux.go
image/preseed/preseed.go
overlord/devicestate/systems.go
seed/seedtest/seedtest.go
seed/seedwriter/fetcher.go
seed/seedwriter/fetcher_test.go
seed/seedwriter/helpers.go
seed/seedwriter/writer.go
seed/seedwriter/writer_test.go

As a part of supporting sequence forming assertions during seeding, I'd like to take the opportunity to do some cleanup around how we fetch assertions during seeding. Instead of how weaved the RefAssertsFetcher was in/out of the seedwriter, I've isolated how it's used, so it's strictly provided as a parameter to writer.Start, and otherwise controlled by the caller.
I've also taken the liberty of renaming it and moving it to it's own file, to encourage us to use it more in terms of isolating logic related to how we fetch assertions.

image,seed: refactor RefAssertsFetcher

---

cmd/snap-bootstrap/main.go
logger/export_test.go
logger/logger.go
logger/logger_test.go
osutil/kcmdline.go
osutil/kcmdline_test.go

Avoid printing anything from snap-bootstrap if "quiet" is present in the kernel command line. This prevents flickering that might happen otherwise in the splash screen.

many: enforce quiet boot when requested

---

tests/nested/manual/minimal-smoke/task.yaml

This change is part of bigger drive to complete Spread Test UC20 Todos.

tests/nested/manual/minimal-smoke: remove todo for minimum requirements

---

data/selinux/snappy.te

This is required by upower-observe interface.
Some tests are failing in centos and fedora after the upowerObserveInterface was update in this way.
func (iface *upowerObserveInterface) StaticInfo() interfaces.StaticInfo {
...
ImplicitOnCore:
osutil.IsExecutable("/usr/libexec/upowerd"),
...
}
This is to avoid this denial:
type=SYSCALL msg=audit(1679948376.046:1319): arch=c000003e syscall=262 success=yes exit=0 a0=ffffffffffffff9c a1=c0001e47b0 a2=c0001246b8 a3=0 items=0 ppid=1 pid=40320 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="snapd" exe="/usr/libexec/snapd/snapd" subj=system_u:system_r:snappy_t:s0 key=(null)
type=AVC msg=audit(1679948376.046:1319): avc:  denied  { getattr } for pid=40320 comm="snapd" path="/usr/libexec/upowerd" …

tests: update selinux policy to allow snapd to read upowerd binary

---

tests/main/special-home-can-run-classic-snaps/task.yaml

This is needed to fix the invalid signatures error:
W: GPG error: https://pkg.jenkins.io/debian-stable binary/ Release: The following signatures were invalid: EXPKEYSIG FCEF32E745F2C3D5 Jenkins Project <jenkinsci-board@googlegroups.com>
E: The repository 'http://pkg.jenkins.io/debian-stable binary/ Release' is not signed.

tests: fix the invalid signatures error in special-home-can-run-classic-snaps

---

asserts/model.go
asserts/model_test.go
seed/seedwriter/writer.go
seed/seedwriter/writer_test.go

This PR handles the changes needed to seedwriter in order to fetch and verify validation-sets when building the image seed.
How validation-set assertions are included are left up to the current implementation for each seed. (i.e core16/18 vs core20+). This means on seeds for 16/18 the validation-set assertions are written directly to the assertions folder like all other assertions are done today, which required no modifications to how its done today, and like-wise for the core20+ seed, it follows the current implementation of being written to the `model-etc` file like other non-model and non-snap assertions today.
The changes to actually use this in image_linux.go will come in a separate PR as that implies additional testing. I'm trying to keep changes to a minimum in each PR, but still …

asserts,seed/seedwriter: support for validation sets in seedwriter

---

tests/lib/prepare-restore.sh
tests/lib/prepare.sh
tests/main/snap-confine-from-core/task.yaml

Avoid calling this function on every prepare because it is taking several seconds and it is delaying the whole test execution by more than 1 hour.
Currently, the tests are taking more than 2 hours instead of 70 minutes.
prepare_memory_limit_override is saving a configuration in /etc/systemd/system/snapd.service.d/. This directory is being restored during the prepare-each, so the change is to save the desired config before the snapd state is saved, so we make sure the config is applied for every test.
Also, reexec configuration is just updated when there is a change in SNAP_REEXEC var. By doing that, snapd is not needed to be restarted on every prepare-each.

tests: call prepare_memory_limit_override before the snapd state is saved

---

tests/lib/fakestore/store/store.go
tests/lib/fakestore/store/store_test.go
tests/lib/gendeveloper1/main.go

This adds support for fetching sequence forming assertions, and teaches fakestore how to return these.

tests/lib: support for sequence forming assertions in fakestore code

---

overlord/snapstate/autorefresh.go
overlord/snapstate/autorefresh_test.go
overlord/snapstate/handlers.go
overlord/snapstate/snapstate_update_test.go
tests/main/auto-refresh-pre-download/task.yaml

Include the names of the snaps being pre-downloaded in the summary of the pre-download change (e.g.,`Pre-download "foo" for auto-refresh`)

o/snapstate: include snap names in pre-dl change summary

---

data/systemd-user/Makefile
data/systemd-user/snapd.aa-prompt-ui.service.in
packaging/ubuntu-16.04/snapd.links

The current snapd.aa-prompt-ui.service user service is dbus activated. However this does not work with the latest prompt design.

data: fix snapd.aa-prompt-ui.service to actually get started

---

tests/main/retry-network/task.yaml

Set dev lo up just before ipv6 test is executed. This is making fail the test in ubuntu lunar when ipv4 is tested.
In ubuntu lunar we get "connection refused" instead of "network is unreachable" in ipv4.

tests: fix retry-network test in ubuntu lunar

---

overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go

`go test -race` flagged a race condition between two tests' TearDown() functions and the notification code that runs in a goroutine. This can only happen in tests where we mock the root dir, so it's not a problem in production code. This simply mocks the notification function so notification code can't race with the restoring of the root dir.

o/snapstate: fix test race condition

---

go.mod
go.sum
run-checks

nakedret was updated to require go version 1.18. This PR changes our static checks script so we use version 1.0.1 of nakedret which doesn't have this incompatibility.

run-checks: use nakedret@1.0.1 compatible w/ go1.13

---

overlord/snapstate/autorefresh.go
overlord/snapstate/export_test.go
overlord/snapstate/handlers.go
overlord/snapstate/snapstate_update_test.go
tests/main/auto-refresh-pre-download/task.yaml

Persist some monitoring-related information and use them to create new monitoring goroutines when snapd starts. This logic ensures that the pre-download/continue auto-refresh UX flow survives restarts. This is important because if snapd is part of the auto-refresh, it will trigger a restart once it refreshes which would then wipe the monitoring state.

o/snapstate: make monitoring survive across restarts

---

build-aux/snap/snapcraft.yaml
tests/lib/prepare-restore.sh

Currently riscv64 builds are failing, because dpkg-buildpackage attempts signing. Use the historic `-uc -us` (unsigned changes, unsigned sources) options that are available in xenial and up, to prevent attempts to sign with mvo's gpg key inside launchpad snap builds.

build-aux: Use dpkg-buildpackage options to not attempt signing anything

---

spread.yaml
tests/main/preseed/task.yaml

This is needed because the lxd snap had changed the base snap
Also, the ubuntu-image snap channel is updated to stable. With candidate snap the following error is happening:
[15948](https://github.com/snapcore/snapd/actions/runs/4682589568/jobs/8309300825?pr=12725#step:8:15949)/snap/ubuntu-image/460/bin/ubuntu-image:
/lib/x86\_64-linux-gnu/libc.so.6: version \`GLIBC\_2.32' not found
(required by /snap/ubuntu-image/460/bin/ubuntu-image)

tests: update lxd base snap for ubuntu gt 22.04 in preseed test

---

build-aux/snap/snapcraft.yaml
tests/lib/prepare-restore.sh

NB! target branch is beta-riscv64.
Currently riscv64 builds are failing, because dpkg-buildpackage attempts signing. Use the historic `-uc -us` (unsigned changes, unsigned sources) options that are available in xenial and up, to prevent attempts to sign with mvo's gpg key inside launchpad snap builds.
(cherry picked from commit 2204c2fd8e78443041de6e39ee935077d49af055)
(cherry pick packaging fix that unbreaks riscv64 builds into the beta-riscv64 branch to build 2.59 release)

[beta-riscv64] build-aux: Use dpkg-buildpackage options to not attempt signing anything

---

tests/main/lxd-mount-units/task.yaml

Same issue fixed in preseed test now needs to be fixed in lxd-mount-units test

tests: fix lxd-mount-units test in ubuntu-22.10

---

tests/lib/reset.sh
tests/main/snap-confine-tmp-mount/task.yaml

The reboot can be avoided in the test snap-confine-tmp-mount. 
Also the reboot was causing the test auto-refresh-gating-from-snap to fail because the refresh was being delayed about 5 minutes.
+ echo 'Trigger auto-refresh of test-snapd-refresh-control-provider but hold it via test-snapd-refresh-control'\''s hook'
Trigger auto-refresh of test-snapd-refresh-control-provider but hold it via test-snapd-refresh-control's hook
+ /home/gopath/src/github.com/snapcore/snapd/tests/lib/tools/snapd-state force-autorefresh
+ systemctl start snapd.service snapd.socket ++
/home/gopath/src/github.com/snapcore/snapd/tests/lib/tools/snapd-state wait-for-autorefresh 1
+ LAST_REFRESH_CHANGE_ID='snapd-state: expected a new auto-refresh change with id greater than 1, but it didn'\''t happen'
these are the …

tests: avoid reboot in snap-confine-tmp-mount test

---

overlord/servicestate/quota_handlers.go
overlord/servicestate/service_control.go
overlord/servicestate/service_control_test.go
overlord/servicestate/servicestate.go
tests/main/services-restart/task.yaml
tests/main/services-snapctl/task.yaml
wrappers/services.go
wrappers/services_test.go

Due to a previous change we were not restarting any non-running unit, but actually that should happen only if the unit is also disabled. Otherwise, stopping and the restarting will not work. Fixes LP#2012630. For reference, see [1], which looks like it might have been misinterpreted.
[1] https://forum.snapcraft.io/t/command-line-interface-to-manipulate-services/262/46

wrappers,tests: restart always enabled units

---

seed/seedwriter/writer.go
seed/seedwriter/writer_test.go

This is part 4 of the seedwriter functionality for using and producing the validation-set information in manifests.

seed/seedwriter: extend seedwriter to use validation-set info from manifest (4/4)

---

tests/lib/prepare.sh

This was introduced #12625 but since has been lost. Latest pc gadget fails test without this, because scopes are actually running around restart of snapd and `tests.invariant` identifies valid scopes as invalid.
This is blocking snapcore/core-base.

tests: reapply work-around when hooks running at restart

---

spread.yaml

This is the error that I see in uc16 and also when using the snap in ubuntu classic:
UC16
UBUNTU_IMAGE=/snap/bin/ubuntu-image
/snap/bin/ubuntu-image snap -w /home/image /home/image/pc.model --channel edge --snap
/home/image/core_16-2.59.1+git4490.46cba5af0_amd64.snap --output-dir /home/image
/snap/ubuntu-image/460/bin/ubuntu-image:
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /snap/ubuntu-image/460/bin/ubuntu-image) 
/snap/ubuntu-image/460/bin/ubuntu-image:
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /snap/ubuntu-image/460/bin/ubuntu-image)
Focal
ubuntu-image snap --validation=enforce --image-size 8G  --snap snapd=beta -c stable -O output/pc-amd64-22-stable- 
snapd_beta ./models/pc-amd64-22.model …

tests: update the ubuntu-image snap channel to avoid issue in uc16

---

overlord/configstate/configmgr.go
overlord/configstate/configstate.go
overlord/configstate/configstate_test.go
overlord/configstate/export_test.go
overlord/configstate/handler_test.go
overlord/configstate/hooks.go
overlord/hookstate/ctlcmd/services_test.go
overlord/managers_test.go
overlord/snapstate/check_snap.go
overlord/snapstate/check_snap_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_try_test.go
snap/hooktypes.go

Spec: https://docs.google.com/document/d/1QDlVmTCtRAe0SxyvMZ97NlcosEtf1-MCmGcsRixDbek
Two parts:
(1) Implementation and unit tests: https://github.com/snapcore/snapd/pull/12701   <- this is part 1
(2) Spread test: https://github.com/snapcore/snapd/pull/12747
**snap/hooktypes.go:**
- Added support for default-configure hook type
**overlord/configstate/configmgr.go:**
- Register the new default configuration handler
**overlord/configstate/configstate.go:**
- Added `DefaultConfigure` that provides the task set for the default configure hook. It is significantly simplified compared to the configure hook due to simpler mandate to configure snap with gadget defaults on first install for non-core snaps. 
**overlord/configstate/hooks.go**:
- Created new type `defaultConfigureHandler` with …

many: add default-configure hook

---

overlord/assertstate/assertstate.go
overlord/assertstate/assertstate_test.go
overlord/devicestate/firstboot.go
overlord/devicestate/firstboot20_test.go
overlord/devicestate/firstboot_test.go
overlord/snapstate/export_test.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/storehelpers.go
seed/seedtest/seedtest.go

This is the final functionality for reproducible images. This adds the neccessary handling of automatically setting up tracking of included validation-sets in the seed.

o/devicestate: track included validation-sets in seed on first boot 

---

tests/lib/tools/tests.session
tests/main/cgroup-tracking-failure/task.yaml

This is to avoid abandoned user sessions in systemd v253

tests: make sure there is not neither stopping nor abandoned user sessions

---

tests/main/services-watchdog/task.yaml
tests/main/services-watchdog/test-snapd-service-watchdog/meta/snap.yaml

It happens that in some rpi devices the 2s timeout is not enough and the service is failing like this:
snap.test-snapd-service-watchdog.direct-watchdog-ok.service × snap.test-snapd-service-watchdog.direct-watchdog-ok.service - Service for snap application test-snapd-service-watchdog.direct-watchdog-ok Loaded: loaded
(/etc/systemd/system/snap.test-snapd-service-watchdog.direct-watchdog-ok.service; enabled; vendor preset: enabled)
Active: failed (Result: watchdog) since Tue 2023-04-25 17:23:14 UTC; 2min 14s ago
Process: 6221 ExecStart=/usr/bin/snap run
test-snapd-service-watchdog.direct-watchdog-ok (code=killed, signal=ABRT)
Main PID: 6221 (code=killed, signal=ABRT)
CPU: 1.549s
Apr 25 17:23:12 ubuntu systemd[1]: Started Service for snap application …

tests: increate the watchdog-timeout to 5 seconds to avoid failed service

---

tests/main/auto-refresh-pre-download/task.yaml

I've seen some test failures of `tests/main/auto-refresh-pre-download` on the notification checks. I suspect it's a timing issue because there's a race condition between the notification and the task finishing (since the notification happens on a different thread). So this PR adds some retrying.
```
+ MATCH 'string "Pending update of "test-snapd-sh" snap"'
signal time=1682252401.117375 sender=org.freedesktop.DBus -> destination=:1.1 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
string ":1.1"
signal time=1682252401.117438 sender=org.freedesktop.DBus -> destination=:1.1 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
string ":1.1"
```

tests: retry the notification matching in racy check

---

image/image_linux.go
image/image_test.go
store/tooling/tooling.go

Fix how validation-sets and required revision was set for snaps that were controlled by validation-sets. Mirror how it's done for the snap validate --refresh. I missed in the first iteration that it needed to be done on a per-snap basis, and I also missed that the required revision for the snap should also be sent.
This was discovered while creating the spread test.

image, store/tooling: correct how validation-sets were sent to store

---

overlord/configstate/configcore/early_test.go

The correct name for the system config setting is "service", not "services".

early_test.go: correct typo, "services.ssh..." -> "service.ssh..."

---

seed/seedwriter/writer.go
seed/seedwriter/writer_test.go

Mark validation-sets seeded when producing the seed manifest. After adding manifest checks to the spread test I discovered this was missing from one of my earlier closed PRs

seed/seedwriter: produce validation-sets in the manifest

---

overlord/servicestate/quota_handlers.go
overlord/servicestate/service_control.go
overlord/servicestate/service_control_test.go
overlord/servicestate/servicestate.go
tests/main/services-restart/task.yaml
tests/main/services-snapctl/task.yaml
wrappers/services.go
wrappers/services_test.go

Due to a previous decision [1] we were not restarting any non-running
unit, this commit changes that back so non-running units are not
restarted only if the unit is also disabled. This way, stopping and
restarting works more similarly to how it is usually expected. Fixes
LP#2012630.
Merged in master by https://github.com/snapcore/snapd/pull/12670
[1] https://forum.snapcraft.io/t/command-line-interface-to-manipulate-services/262/46

overlord,wrappers: restart always enabled units

---

gadget/gadget.go
gadget/gadget_test.go

Warn instead of returning error if a structure overlaps with the GPT header. The previous check was introduced by [1], but unfortunately there are legacy gadgets that rely on the old behavior.
[1] https://github.com/snapcore/snapd/pull/12454/files

gadget: warn instead of returning error if overlapping with GPT header

---

overlord/snapstate/snapstate_update_test.go

The first commit fixes a race condition that I think (I couldn't reproduce) was causing a test to be flaky. The second commit simplifies a check in a few tests.

o/snapstate: fix race condition in test

---

interfaces/builtin/physical_memory_observe.go
interfaces/builtin/physical_memory_observe_test.go

I left this pretty permissive (`@{PROC}/@{pids}/pagemap` vs `owner @{PROC}/@{pid}/pagemap`) as I think that potentially fits more within the spirit of being able to observe all physical memory, but am happy to narrow it if that is seen as more appropriate.
John Johansen also noted that if we wanted to narrow it to "physical memory per process" as opposed to "all physical memory", we could probably use `ptrace r peer=snap...` or something.

i/b/physical_memory_observe: allow reading virt-phys page mappings

---

tests/lib/pkgdb.sh

Install dependencies to make sure veritysetup is installed in debian. Currently the unit tests are failing with the following error:
cmd_pack_test.go:148:
c.Assert(err, check.IsNil)
... value *xerrors.wrapError = cannot pack
"/tmp/check-7666987206516866937/651": exec: "veritysetup": executable file not found in $PATH ("cannot pack
\"/tmp/check-7666987206516866937/651\": exec: \"veritysetup\": executable file not found in $PATH")

tests: add dependency needed in debian to run the sbuild tests

---

cmd/snap/cmd_pack_test.go
snap/integrity/dmverity/export_test.go
snap/integrity/dmverity/veritysetup.go
snap/integrity/dmverity/veritysetup_test.go
snap/integrity/integrity_test.go
snap/pack/pack_test.go
tests/main/snap-pack-integrity/task.yaml

This PR introduces the following things:
- The veritysetup calls were not always mocked in our unit test, and this unfortunately causes a lot of instability in our spread tests, with some platforms failing on the veritysetup calls.
- Adds a spread test instead to verify that `veritysetup` works as expected
- Implements a workaround for older `veritysetup` installations, veritysetup fails on short files (or files that don't already exists, see https://gitlab.com/cryptsetup/cryptsetup/-/commit/dc852a100f8e640dfdf4f6aeb86e129100653673)

many: implement workaround for veritysetup usage on older distros

---

tests/lib/prepare.sh
tests/lib/tools/tests.invariant

This is required for core-base CI to pass. Also removes the previous work-around that did not fully work.
Tested in https://github.com/snapcore/core-base/pull/118

tests.invariant: wait for system scopes to finish

---

snap/revision.go

Pebble code review picked up unnecessary conversion.

snap: import revision tweak from pebble

---

interfaces/apparmor/backend.go
interfaces/apparmor/backend_test.go
overlord/snapstate/backend/apparmor.go

Rewrite the code in RemoveAllSnapAppArmorProfiles() to be more readable and to
allow to surface more errors, plus add a comment to clarify the backend test and
update a copyright date. Original review was given in:
https://github.com/snapcore/snapd/pull/12543#pullrequestreview-1394183004

interfaces/apparmor: address feedback from @mvo5 in #12543

---

asserts/header_checks.go
asserts/snap_asserts.go
asserts/snap_asserts_test.go

This depends on https://github.com/snapcore/snapd/pull/12460.
New commits start at https://github.com/snapcore/snapd/pull/12686/commits/adfba3b26ed0e3154a3f6604bb1849de70489a1c

[1/X] Integrity data for snaps: assertion changes

---

HACKING.md

Launching a locally compiled `snap userd --agent` command requires to disable first its dbus activation service.
This MR adds some notes to the HACKING.md file explaining this.

HACKING: add notes about launching user agent

---

data/selinux/snappy.te

selinux-clean was still failing on CentOS and Fedora

data/selinux: more AVC denials that needs to be handled

---

spread.yaml

Use the same number of workers than the other ubuntu systems.

tests: use 8 workers for ubuntu lunar

---

tests/lib/nested.sh

This was causing these tests to fail:
google-nested:ubuntu-22.04-64:tests/nested/manual/core20-install-mode-shutdown-via-hook
google-nested:ubuntu-22.04-64:tests/nested/manual/core20-install-mode-shutdown-via-hook

tests/lib/nested.sh: fix unbound variable access error

---

cmd/snap-bootstrap/cmd_initramfs_mounts.go
cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
cmd/snap-bootstrap/export_test.go

Make sure that we retry when looking for a label on non-UEFI systems. This is needed until we start to wait on udev to finish to detect disks.

cmd/snap-bootstrap: retry when looking for label on non-UEFI systems

---

run-checks

In the past HACKING.md instructed developers to setup GOPATH explicitly.
This was removed some time ago:
github.com/snapcore/snapd/commit/5b9864a203e9ea26d743436a424699ec07a52ac7
The run-checks script will not work on a clean developer machine, even if someone follows the HACKING.md instructions.
The problem is that run-checks does not support Go's default GOPATH
For example:
/home/foo> go env GOPATH
/home/foo/go
However, the internal GOPATH still respects externally set variables:
/home/foo> GOPATH="/home/foo/go:/home/foo/go2" go env GOPATH /home/foo/go:/home/foo/go2
The run-checks script supported falling back to a hardcoded GOPATH location, based on assumptions of where automated tests check out the repository.
For example:
The github actions repo location:
${{ github.workspace …

run-checks: allow default GOPATH for local checks

---

overlord/restart/restart.go
overlord/restart/restart_test.go
overlord/state/change.go
overlord/state/change_test.go
overlord/state/task.go
overlord/state/task_test.go
overlord/state/taskrunner.go
overlord/state/taskrunner_test.go

This allows tasks to go into WaitStatus with a custom result state. It also disallows SetStatus(WaitStatus).
This PR is needed as a part of the overall functionality to support single-reboot for gadget/kernel/base updates. The solution depends on being able to control which status the tasks are restored to post-reboot, as tasks no longer only reboot upon being 'Done', but rather also can be considered 'Do', 'Undo' or 'Undone' based on how they are. Mostly the 'Do' comes from the check-rerefresh task.

overlord/state: introduce a new SetToWait() method on Tasks

---

daemon/api_validate.go
daemon/api_validate_test.go
overlord/assertstate/assertstate.go
overlord/assertstate/assertstate_test.go
overlord/assertstate/validation_set_tracking.go
overlord/assertstate/validation_set_tracking_test.go

During spread testing I found these constraints missing when manipulating validation-sets post seeding.
- Do not allow forgetting validation-sets that have the mode `enforce` set in the model assertion
- When enforcing validation-sets, take any sequence constraint set by the model assertion into account.
- Improve/fix some existing error messages.

o/assertstate: take the model assertion into account when manipulating validation-sets

---

cmd/snap-mgmt/snap-mgmt.sh.in
tests/main/postrm-purge/task.yaml

This is to avoid snapd.apparmor.service snapd.mounts.target snapd.mounts-pre.target are listed after snapd is purged in arch linux.

tests: make sure there are not any snapd service listed after removing snapd

---

cmd/snap/cmd_download.go
cmd/snap/cmd_snap_op.go

the access to revisions limitations have been dropped in the store

cmd/snap: have help reflect the relaxing of --revision rules

---

tests/main/snap-quota-services/task.yaml

As with the other quota tests, we need to disable snap-quota-services too for external devices.
This is the error in the test
+ snap set-quota test-top --memory=400MB test-snapd-stressd error: cannot create quota group: cannot create quota group "test-top": cannot
use memory quota: memory cgroup is disabled on this system

tests: skip snap-quota-services in external devices

---

tests/main/canonical-livepatch/task.yaml
tests/main/docker-smoke/task.yaml
tests/regression/lp-1910456/task.yaml

Docker is failing frequently in ubuntu 14.04.
trusty is not supported any more for snapd, just livepacth is supported.

tests: remove docker tests in ubuntu trusty and update livepatch

---

interfaces/builtin/steam_support.go

Expanding on the conversation in https://github.com/snapcore/snapd/pull/12794 and https://github.com/canonical/steam-snap/issues/227, this PR allows Steam access to everything in `/usr` to better facilitate Steam changes in the future

steam_support: allow /usr access

---

tests/main/microk8s-smoke/task.yaml

The test fails with timeouts caused for lack of resources on those instances/vms.
The idea is to run this test in google backend where the machines have 4GB of RAM and 2 cores.

tests: skip microk8s-smoke test in external devices

---

.github/workflows/test.yaml

The codecov reporting was broken for a while and after some slightly painful debugging in PR#12834 it turns out that the use of `covertool merge` seems to break codecov. Using this is not needed as codecov can merge reports natively.
This commit removes the use of `covertool merge` and instead just send the various generated coverage reports to codecov.

github: remove use of `covertool merge` to fix codecov reporting

---

interfaces/builtin/custom_device.go
interfaces/builtin/custom_device_test.go

The KERNEL value in udev rules must be the basename of the device path. For devices for which there is not a matching kernel value specified in the custom-device `udev-tagging` section, a default udev kernel rule is generated.  Previously, https://github.com/snapcore/snapd/pull/12734 (and prior) generated these default rules by using the complete device path relative to `/dev/`.  However, for device paths which are in subdirectories of `/dev/`, this means that the kernel values were not basenames, which violates the udev spec.
This commit changes this behavior to instead generate udev kernel rules using the basename of each specified device.
Since ambiguity would arise if multiple devices had the same basename, this change introduces a check to ensure that all the specified devices have …

interfaces/builtin: fix custom-device default udev kernel rules

---

randutil/crypto.go
randutil/crypto_test.go
randutil/export_test.go
sandbox/cgroup/export_test.go
sandbox/cgroup/tracking.go
sandbox/cgroup/tracking_test.go
secboot/export_sb_test.go
secboot/secboot_sb.go
secboot/secboot_sb_test.go

This patchset includes the following changes:
- Make randutil.RandomKernelUUID() return an error instead of throwing a panic.
- Add unit tests for RandomKernelUUID()
- Modify snapd cgroup code to accommodate RandomKernelUUID() error return.
- Modify snapd secboot code to emulate panic behaviour with new RandomKernelUUID().

randutil: latest RandomKernelUUID() changes from x-go

---

interfaces/builtin/mount_control.go
interfaces/builtin/mount_control_test.go

This change alphabetizes the supported kernel mount options, as well as moves `zfs` after `xfs` in the list of default filesystems.
Filesystem-specific mount options are not alphabetized, and are instead left in the order they are defined in their documentation or source code in order to ease visual verification of their correctness.

interfaces/builtin: alphabetized kernel mount options

---

cmd/snap-seccomp-blacklist/snap-seccomp-blacklist.c
cmd/snap-seccomp/export_test.go
cmd/snap-seccomp/main.go
cmd/snap-seccomp/main_test.go
interfaces/seccomp/template.go
tests/main/security-seccomp/task.yaml
tests/main/snap-seccomp-blocks-tty-injection/task.yaml
tests/main/snap-seccomp-blocks-tty-injection/test-tioclinux.c
tests/main/snap-seccomp-blocks-tty-injection/test-tiocsti.c

Update snap-seccomp to support explicitly denying certain syscall argument combinations via a new `~` prefix - and use this to block the use of `ioctl` with `TIOCLINUX` - to fix snapd CVE-2023-1523 (similar to flatpak CVE-2023-28100 https://github.com/flatpak/flatpak/security/advisories/GHSA-7qpw-3vjv-xrqp)

many: introduce seccomp denylist to block ioctl with TIOCLINUX to fix CVE-2023-1523

---

cmd/snap-seccomp-blacklist/snap-seccomp-blacklist.c
cmd/snap-seccomp/export_test.go
cmd/snap-seccomp/main.go
cmd/snap-seccomp/main_test.go
interfaces/seccomp/template.go
tests/main/security-seccomp/task.yaml
tests/main/snap-seccomp-blocks-tty-injection/task.yaml
tests/main/snap-seccomp-blocks-tty-injection/test-tioclinux.c
tests/main/snap-seccomp-blocks-tty-injection/test-tiocsti.c

Backport of https://github.com/snapcore/snapd/pull/12849 to 2.59

many: introduce seccomp denylist to block ioctl with TIOCLINUX to fix CVE-2023-1523 (2.59)

---

cmd/snap-seccomp/main.go
interfaces/seccomp/template.go

For fixing https://bugs.launchpad.net/snapd/+bug/1998980 implement the suggested fix of allowing kcmp in the base template.

interfaces/seccomp/template: adding kcmp to allow Mesa usecases

---

interfaces/builtin/bluez.go

This allows bind for org.bluez.obex.* which is necessary for the agents that are created as well as the send for the org.bluez.AgentManager1 interface.

interfaces: add support for Bluez OBEX agent D-Bus API to bluez interface

---

cmd/snap-confine/snap-confine.apparmor.in

There is a bugfix to make the mount rules more strict/explicit in apparmor 3.0.10, seehttps://gitlab.com/apparmor/apparmor/-/wikis/Release_Notes_3.0.10 - this affects snapd as it's current profile relies on the implicit behavior. With this commit the missing mount rule is added explicitly. 
--- old description ----
After a fresh boot with the lunar proposed kernel 6.2.0-23.23 with the snapd from `edge/prompting` revision 19342 and 19399 (and the apparmor userspace build from https://gitlab.com/jjohansen/apparmor.git and the "prompt" branch). I cannot produce this with the snapd from "edge" that vendors a slightly older version of apparmor userspace.
I got an error starting snaps:
```
$ firefox
cannot perform operation: mount -t tmpfs /tmp/snap.rootfs_9ftEd8: Permission denied
$ sudo …
```

snap-confine: add `tmpfs` mount rule to apparmor profile

---

.github/workflows/test.yaml

It looks like the format check in the static tests got broken when
we moved to go 1.18. It was most likely missed because the code
does not check for `1.13` but uses a regexp `1\.13`.
This commit fixes this and also simplifies the code around this
so that on the next move to a newer go-version we have an easier
time finding the version.

github: fix/simplify `go fmt` check

---

cmd/snap/cmd_known.go
cmd/snap/cmd_sign.go
cmd/snap/cmd_sign_test.go

This introduces a `--chain` flag, which causes 'snap sign' to append the corresponding account-key and account assertions to the signed output of the command. This is often critical for creating working system-user assertions, especially for use in air-gapped or offline situations.
Over the years, Field has created a couple of tools that do this, specifically [make-system-user](https://github.com/canonical/make-system-user) (which reinvents the wheel a bit) and @kubiko's `sign-system-user-assertion` script (which just wraps `snap sign` and `snap known`) but for UX, packaging/distribution, and maintainability reasons, I think the `snap sign` command is really the right place for the logic.
The name "chain" is my rough suggestion, but if others have thoughts on naming, I'd appreciate …

cmd/snap: add '--chain' flag for sign command

---

interfaces/builtin/audio_playback.go
interfaces/builtin/pulseaudio.go

Currently, any application that connects to the audio-playback or the pulseaudio interfaces, have write permissions to the pulse/ folder. This means that a snapped malicious application would be able to delete the socket and put its own, being able to read the audio of any other snapped application.
This patch removes those permissions.

interfaces/audio: remove write permissions in pulse folder

---

timeutil/schedule_test.go

TestParseSchedule() has always failed for me - unless I set TZ=UTC before running go test, since one of the tested time intervals encompasses a daylight savings time transition here in my local timezone and so the result is different in this case. Consequently, since this test always fails, building the snapd deb or snap also fails for me locally. Fix this by forcing golang to use the UTC timezone when running these tests, regardless of how they were invoked.

timeutil: fix tests to run in non-UTC timezones

---

interfaces/builtin/mount_control.go

Added zfs mount options to the list of supported fs-specific mount options included in the mount-control interface.

interfaces/builtin: added zfs mount options to mount-control

---

spread.yaml

It looks like aparmor and arch are not in a happy place right now, the various logs (e.g. https://github.com/snapcore/snapd/actions/runs/5179085285/jobs/9345943979?pr=12694 and https://github.com/snapcore/snapd/actions/runs/5178270014 and /jobs/9345790086?pr=12842 and https://github.com/snapcore/snapd/actions/runs/5178273702/jobs/9345887057 show failures.
Some failure output is apparmor related, e.g.
```
...
error: cannot perform the following tasks:
2023-06-06T07:28:34.1885484Z - Connect test-snapd-with-configure-nc:network-control to core:network-control (cannot setup profiles for snap "test-snapd-with-configure-nc": cannot load apparmor profiles: exit status 1
2023-06-06T07:28:34.1886088Z apparmor_parser output:
2023-06-06T07:28:34.1886430Z Encoding of mount rule failed …
```

spread: add apparmor version as part of the debug output

---

interfaces/builtin/u2f_devices.go

Instead of adding it as a new device I added it under the existing entry for STMicroelectronics based devices which use the same VendorID for STM

interfaces: add flipper zero to u2f devices under existing STMicro based products

---

bootloader/lkenv/lkenv_test.go
timeutil/schedule_test.go

Removes a naked return that the latest version of golangci complains about. Also adds an assertion and a `testutil.Backup` as a follow-up to a PR that I merged too early.

many: minor test cleanups 

---

interfaces/builtin/network_control.go

It looks like some changes in apparmor 3.1.4 cause issues with the existing network-control rules. It appears the rules are stricter now.
Thie commit updates the rules to match the new behavior, see also https://bugs.launchpad.net/apparmor/+bug/2023025

interfaces: fix `network-control` rule for apparmor 3.1.4

---

tests/main/hidden-snap-dir/task.yaml

Shellcheck complains about unreachable code in the hidden-snap-dir test when running the static checks. This code is related to the ~/Snap directory work which is currently on hold. If/when we decide to pick it up again, we can just revert this.

tests: remove unused code in hidden snap dir test

---

aspects/aspects.go
aspects/aspects_test.go
daemon/api.go
daemon/api_aspects.go
daemon/api_aspects_test.go
daemon/export_test.go
overlord/aspectstate/aspectstate.go
overlord/aspectstate/aspectstate_test.go
snap/revision.go
strutil/strutil.go
tests/main/aspects/task.yaml

Adds a `/v2/aspects` endpoint to the REST API with set, get and unset capabilities. Also adds a spread test (which will probably be re-written at some point, once more of the aspects work has been done).

daemon: add aspects endpoint to REST API

---

sandbox/cgroup/monitor_test.go
sandbox/cgroup/scanning.go
sandbox/cgroup/scanning_test.go
sandbox/cgroup/tracking.go
sandbox/cgroup/tracking_test.go
tests/main/cgroup-tracking/task.yaml

The current naming pattern for transient scope units does not yield a natural way to create systemd drop-in configurations that apply to all instances of a snap, regardless of the UUID. For example, systemd drop-in configurations for a unit named foo-bar-baz.scope could be made by placing .conf snippets in any of the following directories:
/etc/systemd/user/foo-bar-baz.scope.d/
/etc/systemd/user/foo-bar-.scope.d/
/etc/systemd/user/foo-.scope.d/
In other words, successively truncating the unit name after '-' yields valid drop-in directory names. This feature is specifc to '-', and in particular does not work with '.'.
It is desirable to have the ability to write drop-in configurations that apply, for example, to all instances of firefox. To allow this functionality, modify the pattern used …

sandbox/cgroup: change scope unit pattern to snap.<pkg>.<app>-<uuid>.scope

---

overlord/devicestate/devicestate_serial_test.go
overlord/devicestate/devicestatetest/devicesvc.go
overlord/devicestate/handlers_serial.go

When a `proxy.store` is used together with a `device-service.url` snapd will try to acquire the serial assertion via the proxy store.
If there was any error from the proxy store snapd would historically just ignore the proxy store and use the `device-service.url` directly.
However this behavior is not neccessarily correct as the proxy may just be down or configured incorrectly. So this was changed [1] but existing customers depend on the old behavior.
For a real fix we need a way to express that a proxy store should be used in general but that it should not be used for the `device-service.url`. This is not possible to express right now and needs design.
So as a short term fix this commit restores the old behavior.
[1] https://github.com/snapcore/snapd/pull/12593/files#diff-def3111c6efb6681 …

devicestate: do not use the proxy for device-service on proxy errors

---

daemon/api_systems_test.go
gadget/device_test.go
gadget/gadget.go
gadget/gadget_test.go
gadget/gadgettest/gadgettest.go
gadget/install/partition_test.go
gadget/layout_test.go
gadget/mountedfilesystem_test.go
gadget/raw_test.go
gadget/update_test.go
overlord/devicestate/devicestate_remodel_test.go

With this pointer we can access to "partial" options from the Volume, with information that we need to check if the structure needs a filesystem or if it has a partially defined size.
Additionally, rename willHaveFilesystem() to HasFilesystem() and use it everywhere, as in the end they mean the same: the structure definition in the gadget expects a filesystem to be there.

many: add pointer to volume in gadget.VolumeStructure.

---

tests/main/snap-advise-command/task.yaml

On some slow external devices the test fails to restart snapd on restore
As the test fails during restore, it means the whole execution fails forcing re-execution.
The idea is to run this for classic and uc16 in google.

tests: skip snap-advice-command test on exernal backend

---

interfaces/builtin/account_control.go

This MR adds support for adding, removing and modifying the users. It is required for Core Desktop, to allow to add, remove and manage users from gnome-control-center.

account_control: allow local user account management

---

tests/lib/prepare.sh

This is required because currently ubuntu-image is failing to build the ubuntu core image with the following error:
runtime: goroutine stack exceeds 1000000000-byte limit
runtime: sp=0xc0204963b0 stack=[0xc020496000, 0xc040496000]
fatal error: stack overflow
A following pr with a revert will be created

tests: install ubuntu image snap to build uc18 and uc2*

---

interfaces/builtin/network_manager_observe.go

This fixes a typo in the `network_manager_observe` interface: `NetworkManger` -> `NetworkManager`.

interfaces: fix typo in network_manager_observe

---

interfaces/builtin/pcscd.go
interfaces/builtin/pcscd_test.go
tests/lib/snaps/test-snapd-policy-app-consumer/meta/snap.yaml

To access smart cards under a snapped program ([bug 1843392][1]), we need to allow it to communicate with the reader drivers via the pcscd socket.
This has already been discussed with the security team as the comment #1 in the linked bug report describes.
To create this interface I simply copied jack1.go and changed the appropriate parts.
[1]: https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1843392

interfaces: add pcscd interface

---

interfaces/builtin/block_devices.go

Allowing loopback devices in the block-devices interface would be convenient for testing and proof-of-concept setups for users of snaps that consume block devices such as MicroCeph
Use case 1: allow a snap to utilize a preconfigured loopback bdev, for
instance allow MicroCeph to use a loopback device as an OSD for
testing or other non-performance critical work
Use case 2: allow a snap to create a loopback device automatically;
e.g. for the above scenario MicroCeph could automatically set up a
loop bdev for use as an OSD

interfaces: allow loopback as a block-device

---

tests/main/auto-refresh-pre-download/task.yaml

Increase a retry in a function used to determined whether a new change has been created. Since it's used after a snapd restart (when forcing an auto-refresh), the timeout wasn't enough to ensure that snapd had started, auto-refreshed and triggered the pre-download flow. This is meant to address the recent flakiness in this test.

tests: increase retry in pre-download test

---

cmd/snap/cmd_aliases.go
cmd/snap/cmd_aliases_test.go

Remove section mentioning 'snap alias --reset' from aliases cmd which is now out of date as it was removed by commit e2d7e0ebd8d.

cmd/snap/cmd_aliases: update stale aliases cmd help text

---

overlord/hookstate/ctlcmd/refresh_test.go
overlord/hookstate/hooks_test.go
overlord/snapstate/autorefresh.go
overlord/snapstate/backend_test.go
overlord/snapstate/refreshhints.go
overlord/snapstate/refreshhints_test.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go

this is useful to be aware of it when looking at changes, for example to make conflict decisions
refreshCandidate.Version is absorbed by SnapSetup.Version, the code in o/hookstate/ctlcmd/refresh.go does not change

overlord: carry the target snap version in SnapSetup.Version

---

tests/main/store-state/task.yaml

This is because the following error: "cannot work with the staging store without a testing build with compiled-in staging keys"

tests: skip store-state test on external backend

---

tests/nested/manual/core20-new-snapd-does-not-break-old-initrd/task.yaml

The test needs to use an old pc snap as the new one is making fail the boot process (error: bad shim signature) as the shim was updated to revoke old stuff because of security.

tests: fix the core20-new-snapd-does-not-break-old-initrd test

---

go.mod
go.sum

This updates the github.com/snapcore/secboot uc22 branch to contain https://github.com/snapcore/secboot/pull/257 which will speed up the I/O performence for full disk encrypted NXP i.MX7D armhf devices significantly.

go.mod: update secboot to latest uc22 branch

---

cmd/snapd-apparmor/main_test.go
sandbox/apparmor/profile.go
sandbox/apparmor/profile_test.go
tests/regression/lp-1848567/task.yaml

We recently ran into a real world profile bug where the option `-O no-expr-simplify` causes a 10x increase in apparmor_parser runtime and memory usage [1] that breaks existing customers.
The decision to use `-O no-expr-simplify` was taken in 2014 [2] and the profiles back then where simpler. This commit will make some profile generation slower but it will avoid going into the exponential memory usage  when compiled with `apparmor_parser -O no-expr-simplify`.
[1] https://bugs.launchpad.net/snapd/+bug/2025030
[2] https://bugs.launchpad.net/ubuntu-rtm/+source/apparmor/+bug/1383858

many: stop using `-O no-expr-simplify` in apparmor_parser

---

aspects/aspects.go
aspects/aspects_test.go
aspects/transaction.go
aspects/transaction_test.go
daemon/api.go
daemon/api_aspects.go
daemon/api_aspects_test.go
daemon/export_test.go
overlord/aspectstate/aspectstate.go
overlord/aspectstate/aspectstate_test.go

Add a Transaction object that can be used to perform multiple get/set on a databag atomically. Transactions implement the DataBag interface so they can be used with the Aspects transparently.

aspects: add transactions to aspects

---

dirs/dirs.go
interfaces/apparmor/backend.go
interfaces/apparmor/backend_test.go
interfaces/apparmor/template.go
sandbox/apparmor/apparmor.go
sandbox/apparmor/apparmor_test.go
sandbox/apparmor/export_test.go
sandbox/apparmor/profile.go
sandbox/apparmor/profile_test.go
tests/main/snapd-snap/task.yaml

Then when using the internal vendored AppArmor, use a different location for SnapConfineAppArmorDir so that we don't interfere with the system installed AppArmor.
In Ubuntu, the snapd deb includes an AppArmor profile for /usr/lib/snapd/snap-confine that includes any profile snippets from the hard-coded directory of /var/lib/snapd/apparmor/snap-confine. When we use the snapd snap with the vendored AppArmor, this may contain newer features and so would create snippets under /var/lib/snapd/apparmor/snap-confine that then may not be supported by the system installed AppArmor. When the system installed apparmor.service would run on boot, it would try and load the snap-confine AppArmor profile shipped in the snapd deb, which would then try and include these snippets generated by the newer …

many: move SnapConfineAppArmorDir from dirs to sandbox/apparmor

---

overlord/snapstate/conflict.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_update_test.go

As a pre-requisite for https://github.com/snapcore/snapd/pull/12718, to avoid any incompatibilities between snapd versions, especially in the task system (i.e the WaitStatus changes), we want to avoid any changes in-flight while updating/reverting snapd, and vice versa.

snapstate: block snapd refresh/revert from occuring while other snap changes happen and vice-versa

---

gadget/layout.go
gadget/update.go
gadget/update_test.go

by EnsureVolumeCompatibility (when creating disk traits), as
LaidoutStructure.OnDiskStructure is not valid until we have the real
disk data (especially when we have a range of sizes/offsets).

gadget/update: set parts in laid out data from the ones matched

---

interfaces/apparmor/template.go
sandbox/apparmor/apparmor.go
sandbox/apparmor/apparmor_test.go
sandbox/apparmor/export_test.go
tests/core/basic18/task.yaml
tests/core/basic20plus/task.yaml
tests/main/snapd-snap/task.yaml

Don't enable the vendored apparmor if the system installed apparmor will try and load policy that would be generated by the vendored apparmor and hence may conflict with that by using newer features not supported by the system installed apparmor (LP: 2024637)

sandbox/apparmor: don't let vendored apparmor conflict with system

---

data/preseed.json

Generated preseed.targ.z should contain content of the
`/etc/modprobe.d` and `/etc/modules-load.d`
Those directories can be populated as a result of the auto-connecting of `kernel-module-load` interface

data: update content of the preseeded blob

---

gadget/install/content.go
gadget/install/content_test.go
gadget/install/install.go

The existing code in writeFilesystemContent() will error when the filesystem cannot be unmounted. However in practise this is problematic as the live-system can keep the mount point busy: https://bugs.launchpad.net/snapd/+bug/2025402
As a pragmatic solution this commit unmounts the filesystem with the `--lazy` option if a normal unmount does not work.
This is what live-editor is doing:
https://github.com/mwhudson/livefs-editor/pull/26
Alternatively we could do a bunch of retries and wait for the process that keep the filesystem busy to go away.

install: lazy unmount() in writeFilesystemContent() if needed

---

interfaces/ifacetest/backendtest.go
interfaces/mount/backend_test.go

This is also helpful as baseline to add unit tests in #12541

interfaces: add some tests for the mount backend ns update case

---

interfaces/mount/backend_test.go

i/mount: use testutil.DeepUnsortedMatches instead of explicit sorting

---

overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_test.go

Split out of https://github.com/snapcore/snapd/pull/12928. We need to save the refresh-candidates in the non-gated autorefresh enabled path, as preparation to the new way of doing refreshes after pre-downloads (see the draft PR for more information).

o/snapstate: save refresh-candidates on auto-refresh

---

overlord/assertstate/assertstate_test.go
overlord/assertstate/bulk.go
overlord/snapstate/autorefresh_test.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_download_test.go
overlord/snapstate/snapstate.go
store/download_test.go
store/store_action.go
store/store_action_test.go
store/store_download.go
store/store_download_test.go

The store option that controls whether requests carry the "Scheduled" header will soon be on only for non-continued auto-refreshes. This renames the field to avoid a mismatch between its name and when it's set. Split out of https://github.com/snapcore/snapd/pull/12928 to make the final PR smaller and less noisy.

many: rename store opt from IsAutoRefresh to Scheduled

---

interfaces/builtin/system_observe.go

Hello - this PR is a proposal to patch the `system_observe` interface to allow read access to `@{PROC}/*/{,task/*/}schedstat` which is a file needed by OpenSearch's performance analyzer. 
For context - [forum discussion](https://forum.snapcraft.io/t/interface-auto-connect-request-for-opensearch-snap/34772/13)
Do you think it makes sense to add it to `system-observe`?

i/builtin: add read access to /proc/task/schedstat in system-observe

---

interfaces/builtin/shutdown.go

Core Desktop needs access to the Inhibit member to be able to reboot or shutdown the system from a Gnome Shell session.
This patch fixes this.

interfaces/shutdown: fix reboot and shutdown in core desktop

---

secboot/luks2/cryptsetup.go
secboot/luks2/cryptsetup_test.go
secboot/luks2/export_test.go
secboot/luks2/fifo.go

I looked a bit at the spread failure on 23.04 for tests/main/uc20-create-partitions-encrypt and it turns out the error is real:
```
...
+ systemd-run --pipe --wait --collect -p KeyringMode=inherit -- /usr/lib/snapd/snap-fde-keymgr add-recovery-key --key-file /home/gopath/src/github.com/snapcore/snapd/tests/main/uc20-create-partitions-encrypt/recovery-key --devices /dev/loop1p5 --authorizations file:/home/gopath/src/github.com/snapcore/snapd/tests/main/uc20-create-partitions-encrypt/unsealed-key --devices /dev/loop1p4 --authorizations file:/home/gopath/src/github.com/snapcore/snapd/tests/main/uc20-create-partitions-encrypt/save-key
Running as unit: run-u58.service
error: cannot add recovery key to LUKS device using authorization key: cannot add key: cryptsetup failed with: 
-----
Key slot …
```

luks2: add missing unit tests, fix hang when cryptsetup fails

---

cmd/snap-bootstrap/cmd_initramfs_mounts.go
cmd/snap-bootstrap/cmd_initramfs_mounts_test.go

We got asked to print the version information of snap-bootstrap during the boot to help the enablement/field team to know if they are using the right version of snap-bootstrap.
This is a small commit that archives this. It uses the logger so quiet boot will also be honored.

snap-bootstrap: print version information at startup

---

tests/main/uc20-create-partitions-encrypt/task.yaml

This skip is required because the test is getting stuck
/usr/lib/snapd/snap-fde-keymgr add-recovery-key --key-file /home/gopath/src/github.com/snapcore/snapd/tests/main/uc20-create-partitions-encrypt/recovery-key --devices /dev/loop1p5 --authorizations
file:/home/gopath/src/github.com/snapcore/snapd/tests/main/uc20-create-partitions-encrypt/unsealed-key --devices /dev/loop1p4 --authorizations
file:/home/gopath/src/github.com/snapcore/snapd/tests/main/uc20-create-partitions-encrypt/save-key
Getting stuck in keymgr_luks3.go
if err := luks2.AddKey(dev, currKey, recoveryKey[:], &options); err != nil {
return fmt.Errorf("cannot add key: %v", err)
}
dev: /dev/loop1p5
currKey: [147 82 161 187 119 61 54 50 164 67 214 97 112 65 122 24 186 176 1 239 110 94 3 108 52 204 252 215 105 68 53 245] …

tests: skip uc20-create-partitions-encrypt in ubuntu-23.*

---

.github/workflows/cla-check.yaml

Make the CLA check action ignore launchpad translations.

.github: ignore launchpad translations commit in CLA check

---

.github/workflows/cla-check.yaml

I messed up the name in the exempted bots. I'm not sure why this wasn't caught when I pushed a test commit to the original PR

.github: fix exempted bot name

---

spread.yaml
tests/bin/tests.env
tests/lib/prepare.sh
tests/lib/state.sh
tests/lib/tools/suite/tests.env/task.yaml
tests/lib/tools/tests.env
tests/main/abort/task.yaml

The new tool is used to know in spread tests the initial value for the vars and be able to repeat not needed steps
With this change, an environment file with the values for SNAPD_NO_MEMORY_LIMIT and SNAPD_REEXEC is written at the beginning of the tests execution and then updated (and snapd restarted) just when the test changes the value through its environment section. This is done to speed up the prepare-each phase of the tests (a lot of snapd restarts are avoided).
Also the memory limit is re-introduced with 150M instead of the previous 100M which caused issues in tests

tests: speed up the prepare phase through a new tool to manage initial snapd env

---

interfaces/builtin/network_control.go

This commit reverts the commenting out of the rule:
```
mount options=(rw, rslave) /,
```
This was broken in apparmor 3.1.4 but got fixed in 3.1.6.

interface: partly revert network-control apparmor change (ee7e554)

---

advisor/backend_test.go

Tiny PR to see how codecov works now that the integration with GH should be back.
This should improve the test coverage of the advisor package as the backend rollback code had no unit tests before.

advisor: add a small unittest

---

overlord/state/change.go
overlord/state/state.go
overlord/state/state_test.go
overlord/state/task.go

This PR adds support for subscribing to task and change status events. It's extrapolated from this PR https://github.com/snapcore/snapd/pull/12898 and aims to replace this PR https://github.com/snapcore/snapd/pull/12720

o/state: support for task+change status events

---

interfaces/apparmor/spec.go
interfaces/builtin/i2c.go
interfaces/builtin/iio.go
interfaces/builtin/spi.go

This commit is a followup for the comments in the review for PR#12918 [1]. As snapd is no longer using `no-expr-simplify` all reference in the code got updated.
The `AddParametricSnippet()` that was originally introduced to avoid exponential memory growth with the parser is still useful and needed because the measurements in PR#12943 show that multiple lines with overlaping patterns will slow down the apparmor_parser when running with default `expr-simplify`.
The comments are updated accordingly in this commit.
[1] https://github.com/snapcore/snapd/pull/12918#pullrequestreview-1499831667

interfaces: update comments about `no-expr-simplify`

---

tests/main/security-seccomp/task.yaml

The test is failing sporadically in uc18. The error seems to be related to the apparmor_parser which is generating incorrect definitions. This error seems to be caused because of cached profiles.

tests: fix security-seccomp test by skip using the apparmor parser with cache

---

gadget/install/content.go
gadget/install/content_test.go
gadget/install/install.go

In the review of PR#12939 extracting a common helper for unmounting was suggested. This commit extracts a new `unmountWithFallbackToLazy` helper that first tries to do a normal unmount and then falls back to `syscall.MNT_DETACH` which is the same as `umount --lazy`. It will ensure the mountpoint will be released in the kernel once there are no longer any processes keeping it busy.
Followup for https://github.com/snapcore/snapd/pull/12939#discussion_r1251886974

install: extract unmount helper function

---

build-aux/snap/patches/apparmor/parser-replace-dynamic_cast-with-is_type-method.patch
build-aux/snap/snapcraft.yaml

The added apparmor patch `parser: replace dynamic_cast with is_type method` will speed up profile generation by 30%.
This is already part of apparmor upstream 4.x
Just for context, with Ondras test case:
```
3.0.8+perf: -j2 -O expr-simplify
User time (seconds): 102.52
Elapsed (wall clock) time (h:mm:ss or m:ss): 0:54.54
Maximum resident set size (kbytes): 18064
3.0.7: -j2 -O expr-simplify
User time (seconds): 215.94
Elapsed (wall clock) time (h:mm:ss or m:ss): 1:52.10
Maximum resident set size (kbytes): 17984
3.0.7: -j2 -O no-expr-simplify
User time (seconds): 148.56
Elapsed (wall clock) time (h:mm:ss or m:ss): 1:19.65
Maximum resident set size (kbytes): 33192
```
So we more than half the original runtime and a 50% improvement compared to -O no-expr-simplify. This should make …

snapcraft.yaml: pull in apparmor optimization patches from Alfonso

---

tests/main/snap-run/task.yaml

The current strace-static edge channel is unhappy so let's switch to `--beta` until this is fixed.

tests: make `strace-static` channel point to beta

---

tests/regression/mount-order-regression/task.yaml

Unfortunately it happens that we hit the memory limit while setting up security profiles for the snap. Set no memory limit for this test

t/regression/mount-order-regression: set no mem limit

---

daemon/errors.go
daemon/errors_test.go

Fixes: https://bugs.launchpad.net/snapd/+bug/2024858
Internal Server Error response was returned when only one of many snaps is not found. The problem was passing all snap names (including successful ones) to [errToResponse](https://github.com/snapcore/snapd/blob/b0c8a48341dd29e82f16f5220bd766f7d1d9b88a/daemon/errors.go#L292) instead of the unknown snap only.
**How to reproduce:**
In the following example only "spamandeggs" is not found, 404 status code is expected, 500 is returned instead:
```
curl -sS --unix-socket /run/snapd.socket http://localhost/v2/snaps -X POST \
-d '{"action": "install", "snaps": ["spamandeggs", "hello"]}' -H "Content-Type: application/json" \
| jq
```
```
{
"type": "error",
"status-code": 500,
"status": "Internal Server Error",
"result": {
"message": …
```

daemon: fix /v2/snaps "Internal Server Error" error when installing unknown snaps

---

boot/bootstate20.go

This commit removes an error check that is unnecessary. No new error is created here and err is already checked 4 lines above.

boot: fix redundant error check in markSuccessful()

---

image/preseed/preseed.go

There is no need to check `sd.EssentialSnaps()` as it does not return an error.

preseed: remove unneeded error check after sd.EssentialSnaps()

---

overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_update_test.go
tests/main/parallel-install-auto-aliases/task.yaml

Implicitly set `--unaliased` flag for parallel installs to avoid alias conflicts with the main snap.
Some potential improvement points:
- Extracting parallel install detection into a function to make it more explicit instead of doing `InstanceKey != ""` implicitly
- Adding a unit test for installing many snaps at once with parallel installs included
They seemed a bit out of scope for this PR, if they seem sensible, maybe they can be implemented in their own PRs?

o/snapstate: implicitly set --unaliased flag for parallel installs

---

daemon/api_aliases.go

There is a check for `err != nil` two lines above and no new err assignment in the loop.

daemon: remove unreachable code

---

tests/main/upgrade-from-release/task.yaml

make the test work for ubuntu lunar

tests: fix upgrade-from-release for ubuntu mantic and fix it for lunar

---

interfaces/builtin/network_setup_control.go

Update permissions to allow using new netplan dbus API calls. See https://netplan.readthedocs.io/en/stable/netplan-dbus/ for details.

interfaces/network-setup-control: update netplan dbus API

---

seed/validate.go
seed/validate_test.go

The variable `first` is never changed so the `else` part is never taken. This commit just removes the unused code.

seed: fix ValidateError output

---

osutil/io.go

The AtomicRename() code was assigning {old,new}Dir only inside the `if !snapdUnsafeIO{}` block which means that the `{old,new}Dir.Sync()` calls never happend.

osutil: fix broken {old,new}Dir.Sync() in AtomicRename()

---

cmd/snap/cmd_debug_timings.go
cmd/snap/cmd_debug_timings_test.go

The undo part of the debug timings had an incorrect `if` statement and missed a test. This commit fixes this.

snap: fix incorrect undo debug timings

---

osutil/disks/disks_linux_test.go
osutil/disks/mockdisk.go

The loop is about `KernelDeviceNode` but the code checks for `KernelDevicePath`. This looks like a copy/paste error from the previous looe` but the code checks
for `KernelDevicePath`. This is a copy/paste error from the previous loop. Includes a unit test.

disks: fix copy/paste error in mockdisks.go

---

overlord/assertstate/assertstate.go

The code checks that `as` is of type `asserts.ValidationSet`. Hower when it is not the (nil) value of the failed type assertion is used in the error. So if this ever is hit it would causes a crash.

assertstate: fix nil access in checkConflictsAndPresence

---

daemon/api_model.go
daemon/api_model_test.go

A remodel with an assertion that is not a model assertion will currently crash the daemon. This commit fixes this and adds a test.

daemon: fix crash when a non-model assertion is sent /v2/model

---

overlord/snapstate/autorefresh.go
overlord/snapstate/autorefresh_gating_test.go
overlord/snapstate/autorefresh_test.go
overlord/snapstate/backend_test.go
overlord/snapstate/flags.go
overlord/snapstate/handlers.go
overlord/snapstate/refreshhints.go
overlord/snapstate/refreshhints_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go

This addresses the [issue of Firefox auto-refreshes not being continued](https://bugs.launchpad.net/snapd/+bug/2019158) after the user stops the snap. The root cause is that the second auto-refresh doesn't always get a consistent response from the store. That is, the first auto-refresh might get a new revision but, if it's inhibited by a running snap, the next auto-refresh might not. This only happens for Firefox (to my knowledge) because the store only throttles Firefox, to reduce the load on its servers. This PR uses the refresh hints written during the auto-refresh (added [here](https://github.com/snapcore/snapd/pull/12946)) to continue the auto-refresh without relying on the store to return the same information.

o/snapstate: use refresh hints to continue auto-refresh after monitoring

---

interfaces/builtin/kvm.go

Everywhere else we check/return err if spec.AddModule() fails so this looks like an oversight.

interfaces: fix missing error return in kvm

---

client/snapshot.go
client/snapshot_test.go

The code was checking generating a `specificErr` but then checked `if err != nil {` (and not check for specificErr) and also lacked a unit test.
When adding the code test it became clear that the other issue there is that the response body was never read so r.err() would always return nil.
This commit fixes both issues.

client: fix specificErr handling in SnapshotExport()

---

overlord/configstate/configcore/netplan.go
overlord/configstate/configcore/netplan_test.go
tests/core/netplan-cfg/task.yaml
tests/nested/manual/core20-early-config/defaults.yaml
tests/nested/manual/core20-early-config/task.yaml

If using other files we might keep the default configuration from the
base, thing that we do not really want. Fixes LP: #2025737.

overlord,tests: use always 00-snapd-config.yaml to store netplan config

---

aspects/aspects.go
aspects/aspects_test.go
aspects/transaction_test.go
daemon/api_aspects.go
daemon/api_aspects_test.go
overlord/aspectstate/aspectstate.go
overlord/aspectstate/aspectstate_test.go
tests/main/aspects/task.yaml

Merge the FieldNotFound and AspectNotFound errors so the user-facing error messages returned by the API are consistent in wording and in the information they provide. Incomplete errors returned by `aspects/` are filled with additional information in `aspectstate/`.

aspects: merge and improve not found errors

---

cmd/snap/cmd_pack.go

as the dm-verity support work and how we ship the hashtrees is still in flux

cmd/snap: hide append-integrity-data

---

cmd/snap-confine/snap-confine.c

The readlink() call does not add a terminating \0. Because orig_cwd is not initialized this can lead to silent corruption (as was observed in PR#13014.

snap-confine: fix missing \0 after readlink

---

tests/nested/manual/core20-auto-remove-user/task.yaml

The "sudo timedatectl set-ntp false" command some times fails with message:
Failed to set ntp: Connection timed out
Apparently because it takes a bit of time to start org.freedesktop.timedate1 and then stop systemd-timedated, as trying again fixes the issue. Do some retries to prevent random failures of this spread test.

tests/core20-auto-remove-user: do retries for set-ntp

---

interfaces/builtin/steam_support.go

allow rw, rbind to /etc/localtime necessary for proton on Core Desktop

interfaces/steam-support: allow rw, rbind to /etc/localtime

---

arch/endian.go
arch/endian_test.go

The go and Debian/Ubuntu architecture names are extremly close and there was a typo in one of them (i386->386). In addition to fixing the typo this commit also includes a list of known architectures from the go source directly to ensure this change is correct.
There is no exported list of available architectures so it had to be copied. There is `go tool dist list` which will list all supported combinations of os/arch but the downside of using this is that when architecture support gets dropped in the future the test would start failing for no good reason.

arch: fix incorrect architecture name in `arch.Endian()`

---

boot/boot_test.go
boot/cmdline.go
boot/cmdline_test.go
boot/initramfs.go
boot/initramfs_test.go
bootloader/export_test.go
bootloader/grub.go
bootloader/lk.go
cmd/snap-bootstrap/cmd_initramfs_mounts.go
cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
cmd/snap/main_test.go
gadget/gadget.go
gadget/gadget_test.go
gadget/kcmdline.go
logger/logger.go
logger/logger_test.go
osutil/kcmdline.go
osutil/kcmdline/kcmdline.go
osutil/kcmdline/kcmdline_test.go
osutil/kcmdline_test.go
overlord/configstate/configcore/corecfg_test.go
overlord/managers_test.go

The matching code is now with the pattern type rather than where we interpret the pattern.  Also glob characters can be now used where we do not expect a pattern.
Also, add command line to string conversion and fix quotation when a space is in a parameter part of the argument.

osutil/kcmdline.go: create separate pattern type for cmdline

---

gadget/kcmdline.go

After refactors in b27425ab99c47cf8fc1b3bb8b0df96d143ea6fa3, the `kargKey` and `kernelArgsSet` types are now unused. This was caught by the `golangci-lint` workflow, but not previously by `./run-checks [--static]`.
The compiler usually catches unused variables, but I guess unused types are not caught in the same way?
I'm going to investigate adding `golangci-lint` to the static checks of `./run-checks` as well, so linting commits without a PR can be more easily caught in the future.

gadget: remove unused private types after refactor

---

interfaces/builtin/audio_playback.go
interfaces/builtin/audio_playback_test.go
interfaces/builtin/audio_record.go
interfaces/builtin/pulseaudio.go
interfaces/builtin/pulseaudio_test.go

This PR ports UDENG-418 to upstream. It enables audio and screen sharing in core Desktop. To do so, it allows access to pulse sockets provided by an app and it allows access to the pipewire socket from snapped applications that implement the _audio_playback_ slot, and allows to have pipewire running inside a snap container. To avoid security issues, it only allows to access the sockets located at the folder belonging to the snap that owns the slot.
With this patch, audio works fine in Core Desktop, and also screen sharing.

interfaces/audio: allow to provide pipewire/pulse slots from a containerized pipewire/desktop

---

tests/main/microk8s-smoke/task.yaml

Observed in spread tests failing due to microk8s security profile causing snapd to run out of memory and getting killed.
Example run: https://github.com/snapcore/snapd/actions/runs/5737693862/job/15553535179?pr=12922

tests/main/microk8s-smoke: set no memory limit

---

tests/core/snapd16/task.yaml

The umount could fail sporadically with the following error
+ umount /snap/snapd/x2 umount: /snap/snapd/x2: not mounted
The idea is to retry 3 times to make sure the umount is done

tests: fix snapd16 test

---

overlord/configstate/configcore/netplan.go
overlord/configstate/configcore/netplan_test.go
tests/core/netplan-cfg/task.yaml
tests/nested/manual/core20-early-config/defaults.yaml
tests/nested/manual/core20-early-config/task.yaml

This is PR https://github.com/snapcore/snapd/pull/12961 backported to 2.60

overlord,tests: use always 00-snapd-config.yaml to store netplan config (2.60)

---

c-vendor/vendor.sh

Hi! I've noticed that there is activity again in the [squashfuse repo](https://github.com/vasi/squashfuse) and that they just released [version 0.2.0](https://github.com/vasi/squashfuse/releases/tag/0.2.0) which, among bug fixes, adds multithreading support to squashfuse_ll.
This is not yet activated by default, [but will be in the next version](https://github.com/vasi/squashfuse/pull/100), but can be activated on a subsequent PR, as it should help with [performance of snaps running](https://github.com/nextcloud-snap/nextcloud-snap/issues/2453#issuecomment-1637381734) [inside of containers](https://github.com/apptainer/apptainer/issues/665#issuecomment-1249783592).

packaging: update squashfuse to 0.2.0

---

interfaces/builtin/steam_support.go

As per the discussion [in the Snapcraft forum](https://forum.snapcraft.io/t/autoconnect-request-steam-network-control/34267/7), this PR adds `unshare CLONE_NEWNS` to the steam_support builtin interface.
This change is essentially exactly @alexmurray's [suggestion](https://forum.snapcraft.io/t/autoconnect-request-steam-network-control/34267/8).

steam_support: add unshare CLONE_NEWNS to steam_support interface

---

bootloader/bootloader.go
overlord/restart/export_test.go
overlord/restart/restart.go
overlord/restart/restart_parameters.go
overlord/restart/restart_parameters_test.go
overlord/restart/restart_test.go

Implement a RestartContext system that keeps track of tasks that needs to restart and why for a change. This PR is the first part of https://github.com/snapcore/snapd/pull/12913 and contains most of the new logic. It does not integrate this code into the current system, that is postponed for when https://github.com/snapcore/snapd/pull/12921 lands as well.

o/restart: add first part of the new restart logic

---

daemon/daemon.go
daemon/daemon_test.go
daemon/export_test.go
tests/core/gadget-kernel-refs-update-pc/task.yaml
tests/core/mem-cgroup-disabled/task.yaml
tests/core/remodel-gadget/task.yaml
tests/core/snapd-maintenance-msg/task.yaml

Do not close snapdListener before the rebootNoticeWait, as the comment correctly says we want to give a notice period to polling clients to allow them to get informed of the pending reboot. Extend this also to be true for daemon restarts.
This fixes polling clients through the snapd API not getting notified of pending reboots, as the listener was closed immediately when rebooting.

daemon: move the closing of snapdListener til after the rebootNoticeWait period

---

cmd/snap/cmd_snap_op.go
cmd/snap/cmd_snap_op_test.go
tests/main/parallel-install-auto-aliases/task.yaml

I noticed that when passing `--prefer` when installing multiple snaps works and `--prefer` is ignored silently, this is because it is not being passed in the [client](https://github.com/snapcore/snapd/blob/d9e4ab8c5eeafda96bdf01df9e38dce0b684ec54/client/snap_op.go#L262) unlike for single [snap ops](https://github.com/snapcore/snapd/blob/d9e4ab8c5eeafda96bdf01df9e38dce0b684ec54/client/snap_op.go#L228).
This PR prevents `snap install --prefer snap1 snap2`, which was ignored silently before.

cmd/snap: prevent passing --prefer in multi-snap installs

---

asserts/account_key.go
asserts/account_key_test.go
asserts/asserts.go
asserts/asserts_test.go
asserts/database.go
asserts/database_test.go
asserts/export_test.go

and take them into account when verifying assertion signatures

asserts: add support for account-key constraints

---

tests/main/uc20-create-partitions/task.yaml

Make sure the correct pc snap is downloaded on mantic

tests: fix uc20-create-partitions test on ubuntu mantic

---

httputil/client_test.go
store/auth.go
store/export_test.go
store/store.go
store/store_download.go
store/store_download_test.go

LP bug: https://bugs.launchpad.net/snapd/+bug/2027993
I removed `Authorization` and `X-Device-Authorization` headers only, should we remove any other identifying headers?

store: remove auth headers from being sent in CDN redirects

---

c-vendor/vendor.sh

https://github.com/snapcore/snapd/pull/13022 updated the commit that squashfuse is pinned to. However, the vendor.sh script was failing because the reference wasn't in the repo unless you updated it manually. This makes the script check if the pinned commit is local and updates the repo if it isn't.
If someone who hasn't updated their squashfuse dependency could test this, I'd appreciate it.

c-vendor: update squashfuse repo if pinned commit is new

---

gadget/update.go
gadget/update_test.go
tests/nested/manual/remodel-offline/task.yaml

Don't care anymore if there is a change in offset-write, as that does
not imply that the partitions layout is incompatible. Also, allow
changes in the partition type as long as there is an intersection in
the list of supported types. This will make easier UC20 to UC 22
updates for images using pc gadget.

gadget: relax gadget update checks

---

gadget/update.go

Function is not used anymore causing static checks to fail on master.

snapd/gadgets: remove unused isSameRelativeOffset function

---

tests/main/snapd-reexec-prompt/task.yaml

This test needs to be skipped in i386 as well.

tests: skip snapd-reexec-prompt on uc16 i386 as well

---

cmd/Makefile.am
cmd/snap-confine/mount-support.c

The tiobe software quality checker flaged this and while it's a bit debatable it adds some clarity around the booleans in the `sc_mount` struct so I think it's overall worth it.

snap-confine: build with `-Wmissing-field-initializers`

---

interfaces/builtin/desktop.go

References:
https://github.com/fcitx/fcitx/blob/master/src/frontend/ipcportal/ipcportal.h#L27 https://github.com/fcitx/fcitx5/blob/master/src/frontend/dbusfrontend/dbusfrontend.cpp#L484

i/b/desktop: allow access to fcitx portal which is supported by both fcitx/fcitx5

---

cmd/Makefile.am
cmd/configure.ac

This will unbreak master, looks like older gcc versions are buggy. Not fully working yet

cmd: detect if -Wno-missing-field-initializers is needed

---

overlord/hookstate/ctlcmd/mount.go
overlord/hookstate/ctlcmd/mount_test.go

In combination with broken dev-mapper devices in UC20, it makes `snapctl mount` hang and then timeout.

o/h/ctlcmd/mount.go: remove a useless start

---

gadget/ondisk.go

The previous commit 85812c58a74d8efaef4734a8f0e28bacedfb6f77 introduced a testutil import in non-test code. This broke MacOS quick checks. Thanks @mvo5 for finding the bug and offering a solution!

gadget: remove testutil import in non-test code

---

data/selinux/snappy.te

After pr #13019 the selinux-clean test started failing after removing the snap test-snapd-service.
type=AVC msg=audit(08/21/23 14:42:23.030:1354) : avc:  denied  { search } for  pid=38749 comm=snap name=x1 dev="sda5" ino=196452 scontext=system_u:system_r:snappy_cli_t:s0
tcontext=system_u:object_r:snappy_var_t:s0 tclass=dir permissive=1 ----
type=AVC msg=audit(08/21/23 14:42:23.030:1355) : avc:  denied  { getattr } for  pid=38749 comm=snap path=/var/snap/test-snapd-service/x1 dev="sda5" ino=196452 scontext=system_u:system_r:snappy_cli_t:s0 tcontext=system_u:object_r:snappy_var_t:s0 tclass=dir permissive=1 ----
type=AVC msg=audit(08/21/23 14:42:38.846:1412) : avc:  denied  { search } for  pid=39200 comm=snap name=x1 dev="sda5" ino=196452 scontext=system_u:system_r:snappy_cli_t:s0 …

tests: fix selinux-clean denials after removing snap

---

osutil/syncdir.go
osutil/syncdir_test.go
systemd/systemd_test.go

This is part of the preparation for using `Ensure*` functions instead of `Add*` functions in `backend.LinkSnap` and `backend.UnlinkSnap`.
This is needed when replacing snap binaries as they are symlinks to `/usr/bin/snap`.
For more context: #13066
**Note: by adding support for symlinks to `EnsureFileSate` the other `Ensure*` functions also grow the feature.**

osutil: add support for symlinks to EnsureFileState

---

tests/main/system-usernames/task.yaml

Followup for https://github.com/snapcore/snapd/pull/13052 that updates the `system-usernames` test to also test for the new _daemon_ user. Only the last commit is relevant.

tests: modify system-usernames test to also test _daemon_ 

---

tests/main/uc20-create-partitions/task.yaml

This was never used and then removed in
snapcore/pc-gadget@a6d5e0dabca77663f6a32eb3b089b244ea428978

tests/main/uc20-create-partitions: do not check for shim on boot partition

---

tests/main/cgroup-tracking-failure/task.yaml

Ubuntu mantic is using systemd 253 so tests.session is not using busctl anymore to execute commands

tests: fix cgroup-tracking-failure test on ubuntu mantic

---

interfaces/apparmor/backend.go
interfaces/apparmor/backend_test.go
interfaces/apparmor/template.go
tests/main/snapd-homedirs-vendored/task.yaml
tests/main/snapd-homedirs-vendored/test-snapd-sh/bin/sh
tests/main/snapd-homedirs-vendored/test-snapd-sh/meta/snap.yaml

The release of snapd 2.60.2 surfaced a bug in the new vendored apparmor integration code. For users with customized /home dirs there is a regression that prevents snaps from working. This is reported in https://forum.snapcraft.io/t/upgrade-snapd-from-2-59-5-to-2-60-2-gives-apparmor-denied-on-app-launch-for-every-app/36492 and also in various LP bugreports.
The issue is that the vendored apparmor does not seem to use the system /etc because of the "--base" keyword we use in the apparmor_parser code. This branch fixes this by ensuring that at least /etc/apparmor.d/tunabables/home.d is included.
More work is needed to include the other tunables, I suspect the easiest fix for this is to add a new option to apparmor_parser to have a commandline option for a tunables search path but this …

i/apparmor: support for home.d tunables from /etc/

---

interfaces/builtin/shared_memory.go
interfaces/builtin/shared_memory_test.go

The isPrivate() method assumes that a plug has been sanitised by BeforePreparePlug and panics if there's no "private" attribute. There's been a customer report of this happening and even though it's unclear how the attribute is missing/wrong, we should handle it as gracefully as we can instead of panicking.

i/b/shared-memory: handle "private" plug attribute in shared-memory interface correctly

---

NEWS.md
packaging/arch/PKGBUILD
packaging/debian-sid/changelog
packaging/fedora/snapd.spec
packaging/opensuse/snapd.changes
packaging/opensuse/snapd.spec
packaging/ubuntu-14.04/changelog
packaging/ubuntu-16.04/changelog

Merge the changelog of 2.60.3 back into master. 
This needs to be merged via a merge-commit.

release: 2.60.3 (#13124)

---

cmd/Makefile.am
cmd/configure.ac
packaging/debian-sid/control
packaging/fedora/snapd.spec
packaging/opensuse/snapd.spec
packaging/ubuntu-14.04/control
packaging/ubuntu-16.04/control
tests/lib/pkgdb.sh

This is a cleanup of `cmd/configure.ac`.
* Cache results from running compiler.
* Use `AX_APPEND_COMPILE_FLAGS` to make sure warning flags exist
* Wrap test code in `AC_LANG_SOURCE`/`AC_LANG_PROGRAM` and simplify test code.

cmd/configure.ac: rework

---

overlord/snapstate/backend_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go

We (the Ubuntu Desktop team) would like to ship the firmware-updater snap by default in the next release. It makes use of the `daemon-scope: user` feature, which is currently locked behind an experimental feature flag.
I'd like to either get the feature flag turned on by default, or request another exception to allow this snap to bypass the feature flag like snapd-desktop-integration does. This PR implements the second option, but I'd be willing to withdraw it in preference to the first option if that's on the table.
Here is some information about the snap in question:
1. It is published by the "canonical" account.
2. It's source code can be found at https://github.com/canonical/firmware-updater
4. It installs two user services:
* firmware-notifier: runs in a timer, periodically polls …

overlord: allow the firmware-updater snap to install user daemons

---

gadget/install/install_test.go

The `TestMatchDisksToGadgetVolumes` is using insufficient mocking and therefor the test will fail on any system that has a /dev/vda2 device (like our ppc64el sbuild environment).
This commit fixes this by splitting the test into three tests that check different aspects of the `MatchDisksToGadgetVolumes()`.
With that the "not-found" base can be tested easily by ensuring that a device that is no longer supported by the kernel is used (/dev/xda which got deleted in v3.9 [0]. There is now a little bit more duplication but it seems an acceptable trade-off.
[0] https://docs.kernel.org/admin-guide/devices.html

gadget: fix TestMatchDisksToGadgetVolumes on systems with /dev/vda2

---

cmd/snapd-generator/main.c

Systemd now runs generators in a sandbox. That means `/proc/self/mountinfo` does not represent correctly the mounts of the system.
Also in this PR
No "enable" will happen for generated mounts. `snap.mount` is started because of implicit dependency from snap mounts.

cmd/snapd-generator: read mountinfo for pid 1

---

cmd/snap/cmd_quota_test.go
overlord/devicestate/firstboot20_test.go
overlord/install/install_test.go
overlord/snapstate/snapstate_test.go

While looking into 2.60.3 for fedora (we are two version behind right now) I ran the unit tests on a pristine fedora 38 system and noticed that we have a bunch of failures, mostly easy enough to fix. This PR contains the "easy" ones (i.e. differenes lke that on fedora/RH/some-others /snap is there /var/lib/snapd/snaps).
What is missing is:
* a PR to include  `glibc-static.i686 glibc-devel.i686 fakeroot python3-yamlordereddictloader` as BuildRequires
* a PR that deals with -xatts/-no-xattrs during the tests. when test snaps are build during the unit tests they cannot be unpacked to to selinux xattrs that get included when running snap pack

many: fix running unit tests on fedora

---

tests/main/interfaces-mount-control/task.yaml

The test was expecting audit logs to go to kmsg. But this is a buggy behavior from the kernel. It seems to have been fixed. Now auditd needs to be used.

tests/main/interfaces-mount-control: use auditd to match apparmor errors

---

aspects/schema.go
aspects/schema_test.go

Adds support for parsing and validating maps with "schema", "required", "keys" and "values" constraints. Also adds support for simple strings (without any of the constraints defined in the spec) because it simplifies testing of the maps (and, in the case of "keys", it's even required because they must be string-based). 
The spike that this was split from is https://github.com/snapcore/snapd/pull/13059. This PR is nearly as large as the draft even though the scope is much smaller (no ints, no string constraints, no user-defined types) because of all the tests. They're not verbose but they're many. The code's spec is SD133.

aspects: parse and validate maps and simple strings

---

asserts/account_key.go
asserts/account_key_test.go
asserts/signtool/sign.go
asserts/signtool/sign_test.go
cmd/snap/cmd_keys_test.go
cmd/snap/cmd_sign.go
cmd/snap/cmd_sign_test.go

this is done by passing the account-key if it could be retrieved
to signtool that has added support for cross-checking

cmd/snap,asserts,a/signtool: optional cross-checking with the account-key when signing

---

overlord/snapstate/snapstate_update_test.go

The polling loop would end with an unlocked state lock, in the case where the monitoring wasn't cleared in 5 seconds. This ensures that the test won't panic if it fails. It also increases the timeout to 10 seconds in case the failure was due to an overloaded test machine.

o/snapstate: fix test panic when monitoring isn't cleared

---

interfaces/builtin/u2f_devices.go
interfaces/builtin/u2f_devices_test.go

This PR adds support for the Swissbit iShield Key series which supports FIDO2 (U2F/CTAP).
dmesg output:
```
[ 2300.560476] usb 1-1: USB disconnect, device number 22
[ 2301.471451] usb 1-1: new full-speed USB device number 23 using xhci_hcd
[ 2301.629671] usb 1-1: New USB device found, idVendor=1370, idProduct=0911, bcdDevice= 0.01
[ 2301.629699] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 2301.629706] usb 1-1: Product: iShield Key Pro
[ 2301.629712] usb 1-1: Manufacturer: Swissbit
```
Reference: https://www.swissbit.com/en/products/ishield-key

interfaces/u2f-devices: add Swissbit iShield Key

---

tests/nested/manual/fde-on-classic/task.yaml

The EFI boot loader is for the ESP, not the boot partition. This was removed in pc-gadget recently.

t/n/m/fde-on-classic: do not check for default EFI boot loader (shim)

---

overlord/restart/restart.go
overlord/restart/restart_test.go

This is an alternative solution to https://github.com/snapcore/snapd/pull/13090, and implements the reverse logic, instead of marking which tasks are allowed to defer their restart, we instead mark which tasks **must** complete a reboot before the change can continue.
We support marking tasks both ways, both for the Do path and Undo path.

o/restart: support for restart boundaries

---

tests/nested/core/connected-after-reboot-revert/task.yaml

Here are the expected reboot causes:
* Make current revision for snap "core" unavailable
* Make snap "core" (unset) available to the system
* Make current revision for snap "pc-kernel" unavailable
* Make snap "pc-kernel" (unset) available to the system

t/n/c/connected-after-reboot-revert: expect one more reboot on UC16

---

asserts/model.go
asserts/model_test.go
asserts/preseed.go
asserts/preseed_test.go
seed/seed20.go
seed/seed20_test.go

Allow preseed authority delegation in the model assertion, and check that either the brand or a delegated authority has signed a preseed assertion when importing.

asserts,seed: preseed authority delegation

---

overlord/devicestate/remodel.go
overlord/devicestate/remodel_test.go

Resealing can take more than a minute since it must hash a lot of files that it might need to unpack from snaps. It also needs to interact with the TPM and parse the event log, which might be slow. If we keep the lock, then snapd will not respond for a long time.
This fixes failures for `tests/nested/manual/core20-remodel`

o/d/remodel.go: release lock when resealing

---

tests/main/system-usernames-missing-user/task.yaml

This test failed with:
```
2023-09-05T12:51:25.0650751Z + echo 'Then the snap cannot be installed'
2023-09-05T12:51:25.0651128Z Then the snap cannot be installed
2023-09-05T12:51:25.0651591Z + MATCH 'cannot add user/group "snap_daemon": group exists and user does not'
2023-09-05T12:51:25.0652024Z + snap install --edge test-snapd-daemon-user
2023-09-05T12:51:25.0652503Z grep error: pattern not found, got:
2023-09-05T12:51:25.0653135Z error: cannot install "test-snapd-daemon-user": cannot ensure users for snap
2023-09-05T12:51:25.0653797Z        "test-snapd-daemon-user" required system username "snap_daemon": cannot
2023-09-05T12:51:25.0654381Z        add user/group "snap_daemon": group exists and user does not
```
This is because of the line breaks that are added in the error and that …

tests: fix system-usernames-missing-user multiline MATCH

---

snap/implicit.go
snap/info.go
snap/info_test.go
snap/pack/pack.go
snap/pack/pack_test.go
snap/validate.go
snap/validate_test.go

Additional to [PR-12701](https://github.com/snapcore/snapd/pull/12701), to address [this comment](https://github.com/snapcore/snapd/pull/12701#discussion_r1172686765). 
As a temporary measure [checkConfigureHooks](https://github.com/snapcore/snapd/blob/master/overlord/snapstate/check_snap.go#L569) was added which extends [checkSnap](https://github.com/snapcore/snapd/blob/master/overlord/snapstate/check_snap.go#L242) that is called from [doMountSnap](https://github.com/snapcore/snapd/blob/master/overlord/snapstate/handlers.go#L1182)
The requirement is to have a similar check in place in:
- snap.Validate (with this in place, arguably the temporary measure can fall away)
- snap pack loadAndValidate
This PR proposes to achieve this by:
1. Export `addImplicitHooksFromContainer` and use in …

snap, snap/pack: add pack validation for default-configure hook

---

tests/lib/tools/report-mongodb

The the mongodb is configured with authentication, so this change is intended to support this.

tests: support mongodb authentication in the report-mongodb tool

---

sandbox/apparmor/notify/ioctl.go
sandbox/apparmor/notify/ioctl_test.go

The `IoctlRequestBuffer` is currently a struct with a single `[]byte`. This means it might equally be just an alias type with the needed methods.
A minimal draft mostly to get early feedback, this feels cleaner to me but maybe it's just personal. Once we agree about this direction we can trivially also remove `func (b IoctlRequestBuffer) Bytes() []byte` and Len() (if we want).

apparmor: simplify IoctlRequestBuffer

---

tests/main/snapd-homedirs-vendored/task.yaml

This fix is needed because the system is not remaining in the original state after the test is executed. For example if the test classic-prepare-image is executed after that one it fails with the following error
+ echo 'Wait for seeding to be done' Wait for seeding to be done
+ snap wait system seed.loaded -----
run this command line to reproduce the error: 
> spread-debug -debug -order -workers 1 google:ubuntu-22.04-64:tests/main/snapd-homedirs-vendored google:ubuntu-22.04-64:tests/main/classic-prepare-image

tests: fix how snapd is restored in snapd-homedirs-vendored

---

seed/seed20_test.go

otherwise validity checks might fail

seed: preseed timestamp should be after my-signer key registration

---

interfaces/builtin/block_devices.go

update the comment to match current reality

i/builtin/block-devices: loop* is actually included now

---

interfaces/builtin/custom_device.go
interfaces/builtin/custom_device_test.go

Previously, the handling of udev tagging rules was modified to allow device paths in subdirectories of `/dev/`.  As part of this work, checks were put in place to ensure that all KERNEL values, including default rules, must be basenames of a device path.
That work can be found in two previous commits:
- b1df21de4719da0644ce7528d9bc9cd46dbf99c1
- 12ca6af3a000b30552abb33377724379faf4aab8
The former allows either full paths (stripped of leading `/dev/`) or basenames, while the latter switches this requirement so that all values must be basenames.  The commit message of the latter indicates that KERNEL values which are not basenames violate the udev spec -- this is incorrect.
For some devices, the udev KERNEL value must be the full path of the device, stripped of leading `/dev/`, while for …

interfaces/builtin: fix custom-device udev KERNEL values

---

asserts/model_test.go

This adds a test to make sure that models that delegate authority for serial assertion signing can't be specified with a wildcard ("*"), and instead must be specified as an explicit list of authority ID's.
This was originally brought up [here](https://github.com/snapcore/snapd/pull/13034#discussion_r1309785329), but it seemed more appropriate to open a separate PR.

asserts/model: test serial-authority field with wildcard

---

aspects/schema.go
aspects/schema_test.go

Adds support for "pattern" and "choices" constraints in string schemas which constrain values to regular expressions or sets of alternatives, respectively.

aspects: support constraints in string schemas

---

tests/main/services-socket-activation/task.yaml
wrappers/services.go
wrappers/services_test.go

This PR fixes the current `snap start` and `snap start --enable` behaviour which today do exactly the same thing for services that are activated by other units. With this PR these commands now behave as you would expect.
`snap start` now starts the activation units, but does not enable them on startup
`snap start --enable` now starts the activation units, and enables them for startup.
For some history:
- Original PR that preserved this behaviour: https://github.com/snapcore/snapd/pull/11314
- The commit https://github.com/snapcore/snapd/pull/11314/commits/d275bda87153e4418a0eee496ffe6adc89c3fc69

wrappers: enable activated services only if flag is set

---

overlord/snapstate/autorefresh.go
overlord/snapstate/handlers.go

Use the snap name instead of a SnapSetup to make it clear that the monitoring process is not revision specific (since we use only the name to get the latest refresh candidate) and it doesn't need to be updated if a new revision is pre-downloaded.

o/snapstate: pass name instead of SnapSetup in pre-dl funcs

---

store/details_v2.go
store/details_v2_test.go

then applies any store only/store override data
this should help make any pre-download checks/validations work correctly

store: use as much from snap-yaml as possible if available

---

wrappers/core18.go
wrappers/core18_test.go

The snapd.session-agent.service unit written out on Core devices includes a line like:
ExecStart=/snap/snapd/NNNN/usr/bin/snap userd --agent
Running user session systemd instances will cache the unit, and should that snapd revision be removed, the unit can no longer be started. This can then break future operations that rely on the session agent.
To fix this, we ask all available session agents to do a deamon-reload after the new versions of the units have been written out. The exec path in the cached version of the unit should work for this call, since the old snapd revision is still available while upgrading to the new one.

wrappers: tell user systemd instances to reload after updating snapd's user units

---

gadget/gadget.go

ubuntu-image needs to serialize/deserialize gadget.Info. Recursion in the data structure causes infinite recursion in serialization.

gadget: add a way to reset recursive data structure

---

tests/main/docker-smoke/task.yaml

A reboot is needed to make sure the networking is properly configured after removing the docker snap.
Interface docker0 is not removed when docker is uninstalled, this problem is reproduced with docker snap and deb packages.
Rules added in iptables also are not working properly after docker is removed. A reboot is recommended.
This is an example of the problem: https://paste.ubuntu.com/p/dTDy22T2xJ/

tests: fix docker-smoke test

---

overlord/state/state.go
overlord/state/state_test.go

This PR separates a bugfix from the single-reboot PR (https://github.com/snapcore/snapd/pull/13044).
It adds a couple of missing initializers for an empty state, and a unit test to cover this doesn't happen in the future.

o/state: add missing initializers and a unit test to cover this

---

interfaces/builtin/utils.go

This is a patch we've been shipping in the Core Desktop snapd branch for a while, but had not previously upstreamed.
On Core Desktop, the upower-observe interface is available as an implicit slot. We want to make the same kind of implicit vs. app snap distinction in AppArmor rules as we would on classic systems. Allowing the implicitSystem*Slot() helpers to return true on Core systems achieves this.

interfaces: remove release.OnClassic check in implicitSystem*Slot() helpers

---

overlord/snapstate/backend/link.go
snap/info.go
snap/info_test.go
wrappers/binaries.go
wrappers/binaries_test.go
wrappers/desktop.go
wrappers/desktop_test.go
wrappers/icons.go
wrappers/icons_test.go

This is part of the preparation for using Ensure* functions instead of Add* functions in backend.LinkSnap and backend.UnlinkSnap.
For more context: https://github.com/snapcore/snapd/pull/13066

wrappers: use `Ensure` in snap linking operations for snap binaries/icons/desktop files

---

cmd/snap-device-helper/snap-device-helper-test.c
cmd/snap-device-helper/snap-device-helper.c
tests/main/security-device-cgroups-helper/task.yaml

At some point the kernel added two events "bind" and "unbind" for uevent.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=1455cf8dbfd0
Those actions were hidden by udev. But they seemed to have been added now. They were not handle by snap-device-helper. Instead it would generate an error.
Here we ignore `unbind`, since `remove` should take care of cleaning up. And it should happen after.
We treat `bind` like `change` (which is like `add`).

cmd/snap-device-helper: handle bind and unbind commands

---

cmd/Makefile.am

Some target were not having warnings, for instance snap-generator, because they did not have explicit CFLAGS, and AM_CFLAGS did not contain CHECK_CFLAGS.
~~Draft for now as it might conflict with #13112~~

cmd/Makefile.am: add warning to all CFLAGS

---

overlord/configstate/configcore/corecfg_test.go
overlord/configstate/configcore/vitality_test.go
overlord/managers_test.go
overlord/servicestate/servicemgr_test.go
overlord/snapstate/backend/link.go
tests/main/snap-service-install-mode/svc.v1/meta/snap.yaml
tests/main/snap-service-install-mode/task.yaml
wrappers/services.go
wrappers/services_test.go

This PR contains fixes for the following:
- When refreshing snaps, disabled services that were activated were re-enabled.
- When installing/refreshing snaps that have 'install-mode: disabled' for an activated service, we were enabling the service activation units.
This is accomplished by refactoring the logic that extracts service status. Before it was using `systemctl is-enabled`, which is insufficient for detecting the proper status of an activated service. Running this command on a service that is actived reports `static`. 
Now we use common logic for these cases, that retrieve the status of both the primary service and any activation units, and from this derives whether an activated service is enabled or not.

wrappers: dont enable service activation units for services with install-mode 'disable'

---

daemon/api_base_test.go

Race that was detected:
```
phelps@ubuntu ~/r/s/daemon> go test -race .                                                                                                                             
==================                                                                                                                                                      
WARNING: DATA RACE                                                                                                                                                      
Read at 0x00000234f880 by goroutine 433:                                                                                                                                
github.com/snapcore/snapd/bootloader.Find() …
```

daemon: make tests pass with race detector

---

boot/assets.go
boot/assets_test.go
boot/boot.go
boot/boot_test.go
boot/bootstate20.go
boot/cmdline.go
boot/export_test.go
boot/flags.go
boot/kernel_os.go
boot/makebootable.go
boot/model.go
boot/model_test.go
boot/seal.go
boot/seal_test.go
boot/systems.go
overlord/devicestate/devicestate_remodel_test.go
overlord/devicestate/handlers.go
overlord/devicestate/handlers_gadget.go
overlord/devicestate/remodel.go
overlord/devicestate/remodel_test.go
overlord/state/state.go
overlord/state/state_test.go

this should allow to release the global state lock while doing resealing/sealing proper as those are slow operations in fact

boot,o/devicestate: protect with a mutex modifying modeeenv and sealing/releasing

---

usersession/agent/session_agent.go

On Ubuntu 16.04, ssh sessions may not have a D-Bus session bus, resulting in the `bus` field of the session agent being nil.  If this is the case, calling `s.bus.Close()` results in a nil pointer exception. This commit adds a check of `s.bus` (like those found elsewhere in session_agent.go) before calling `s.bus.Close()` during a session shutdown.
Thanks to @andrewphelpsj for discovering and discussing this bug.

usersession/agent: only close session bus if non-nil

---

aspects/aspects.go
aspects/schema.go
aspects/schema_test.go

Adds support for user-defined types that can be based on any of the other built-in types and referred to in the schema definition with a '$' prefix.

aspects: support user-defined types in schemas

---

interfaces/builtin/fwupd.go

This access is needed by linux-display plugin.
Upstream PR: https://github.com/fwupd/fwupd/pull/6195

i/b/fwupd.go: allow access to drm devices

---

tests/core/snapd-failover/task.yaml

This is to avoid in uc16
umount: /snap/snapd/x1: target is busy
This is needed a retry to wait a but until /snap/snapd/x1 can be umounted

tests: fix snapd-failover test

---

snap/snapfile/snapfile.go
snap/snapfile/snapfile_test.go

There was a recent salesforce case where a invalid snap was downloaded but because the error from the snapfile only contains the "bytes" representation it was not clear right away that the header was actually a json error like: `{"err...`.
This commit tweaks the error so that more context (15 bytes) are displayed and they are also displayed as quoted string not only as bytes.

snapfile: show more context when a snap file header cannot be read

---

boot/bootstate20.go

Running `gofmt` (v1.20.4) makes some formatting changes to a comment.

boot: fix comment formatting

---

overlord/servicestate/servicemgr_test.go

The build was failing on master because golangci was picking up this unused struct and methods. I still have to look into why this wasn't picked up by golangci before merging but this should fix the build.

o/servicestate: remove unused test struct

---

overlord/devicestate/devicestate.go
overlord/devicestate/devicestate_bootconfig_test.go
overlord/devicestate/devicestate_gadget_test.go
overlord/devicestate/devicestate_remodel_test.go
overlord/devicestate/devicestate_systems_test.go
overlord/devicestate/devicestate_test.go
overlord/devicestate/firstboot_preseed_test.go
overlord/managers_test.go
overlord/restart/restart.go
overlord/restart/restart_test.go
overlord/snapstate/export_test.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_link_test.go
overlord/snapstate/handlers_rerefresh_test.go
overlord/snapstate/reboot.go
overlord/snapstate/reboot_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_update_test.go
tests/core/kernel-and-base-single-reboot-failover/task.yaml
tests/core/kernel-and-base-single-reboot/task.yaml
tests/core/system-snap-refresh/task.yaml

The PR switches to the new restart logic and changes a few neccessary things now that the semantics around restarting for changes is different. The whole process around restarting for tasks/changes is now more streamlined, and any deviances from the regular restarting must now explicitly be marked when creating a change. 
Currently two tasks are using deferred restarts ("update-gadget-assets" + "update-gadget-cmdline" for gadget/kernel snaps), to avoid incurring extra reboots during kernel/gadget installs, as they were implicitly allowed to be deferred before. 
Sadly a few changes were neccessary to the spread tests, as some reboots were actually skipped because it was allowed, even though they had been requested. The new restart code also provides full symmetry for do/undo paths, which …

many: switch to new restart logic

---

osutil/epoll/epoll.go
osutil/epoll/epoll_test.go

For users of `osutil/epoll` (namely the AppArmor Prompting listener in #13148 ), we want to ensure that calls to `Wait()` and `WaitTimeout()` return immediately when the epoll instance on which they are called is closed. This PR adds that functionality.

osutil/epoll: make `e.Wait{,Timeout}()` return immediately when `e.Close()` is called

---

snap/integrity/integrity_test.go
snap/pack/pack_test.go
snap/squashfs/export_test.go
snap/squashfs/squashfs.go
snap/squashfs/squashfs_test.go

Some kernel versions will log messages such as
```
[13026.677193] Dev loop12: unable to read RDB block 8
[13026.678051] loop12: unable to read partition table
[13026.678093] loop12: partition table beyond EOD, truncated
```
when creating a loopback device for squashfs files that are smaller than 16KB. To eliminate this log noise, we can enforce a minimum snap size of 16KB. This should only impact really small snaps, such as the `bare` snap.
Note that `losetup` prints a warning when creating a loopback device for truncated snaps:
```
losetup: bare_5.snap: Warning: file does not fit into a 512-byte sector; the end of the file will be ignored.
```
See https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1979633 for more relevant details.

snap/squashfs: enforce a minimum snap size to eliminate some kernel log noise

---

gadget/gadget.go
gadget/gadget_test.go
gadget/install/install.go
gadget/install/partition.go
gadget/layout.go
gadget/update.go
osutil/mkfs/mkfs.go
osutil/mkfs/mkfs_test.go

Add support to FAT16 by adding it as a valid filesystem in the gadget.yaml `filesystem` label. An alternative would be a fat specific field `fat-bits`, as in the end both FAT16 and FAT32 are seen as vfat type by Linux.
This change will require a recompilation of `ubuntu-image` and also new `snap-bootstrap` in pc-kernel for all pieces to work.

gadget,osutil: add support for fat16 partitions

---

asserts/ifacedecls.go
asserts/ifacedecls_test.go
interfaces/builtin/upower_observe.go
interfaces/policy/basedeclaration_test.go
interfaces/policy/helpers.go
interfaces/policy/policy_test.go

let connect/auto-connect only to an upower-observe implicit slot by default,
this will require changes to review-tools to detect that for an app slot
dedicated rules in snap-declaration are needed
to allow for this, first introduce new rule syntax in the form of slot-snap-type slot-side connection constraints

interfaces: upower-observe base policy considers whether the slot is implicit

---

interfaces/policy/basedeclaration_test.go

qualcomm-ipc-router was using snap-slot-type on the slot-side in allow-connection before it was enabled, that's why this started breaking on master

i/policy: fix TestConnection* for qualcomm-ipc-router

---

overlord/devicestate/devicestate.go

This change eliminates some code-nesting and makes things a bit more readable, in my opinion. I can close this though, if no one agrees!
The only change to the actual logic that I made was eliminating the check to see if the `*state.TaskSet` returned from `remodelVar.UpdateWithDeviceContext` is `nil`, since none of the code paths that I see in that method can result in a `nil` task set when `err == nil`.

o/devicestate: refactor remodelEssentialSnapTasks for readability

---

packaging/debian-sid/patches/0007-i18n-use-dummy-localizations-to-avoid-dependencies.patch

The change from using `ioutil.WriteFile` to `os.WriteFile` broke this patch file. This was breaking the spread tests on `debian-sid`.
Output from `debian-sid-64` spread tests:
```
patching file i18n/i18n_test.go
Hunk #1 FAILED at 20.
1 out of 1 hunk FAILED
```

packaging: fix i18n patch for debian-sid

---

data/selinux/snappy.te

Update the selinux policy to fix the denial which is shown in centos 7
type=AVC msg=audit(09/26/23 12:44:11.492:315) : avc:  denied  { rename } for  pid=28207 comm=snapd name=lxd.lxc.yLBQbN9J4LrW~ dev="sda2" ino=17679133 scontext=system_u:system_r:snappy_t:s0 tcontext=system_u:object_r:usr_t:s0 tclass=lnk_file permissive=1

tests: fix selinux-lxd in centos-7

---

interfaces/builtin/account_control.go
interfaces/builtin/locale_control.go

This PR adds support for the org.freedesktop.locale1 DBus interface. It is required for Ubuntu Core Desktop and for the installer.
Fix git checkout -b UDENG-1110-add-locale-1-dbus-interface-support-in-snapd

locale_control: add locale1 dbus support

---

aspects/schema.go
aspects/schema_test.go

Force required keys to be present in the schema as well. This constraint is the reason why a type "any" is necessary, since the writer may want to express that a key is expected regardless of type.

aspects: required keys must have schema entry

---

aspects/schema.go
aspects/schema_test.go

Adds support for integers in aspect schemas. Integer type definitions can be further constrained with `min`, `max` and `choices` constraints.

aspects: support integers in aspect schemas

---

overlord/snapstate/autorefresh.go
overlord/snapstate/autorefresh_test.go
overlord/snapstate/catalogrefresh.go
overlord/snapstate/catalogrefresh_test.go
overlord/snapstate/refreshhints.go
overlord/snapstate/refreshhints_test.go

`store.access` is used to control our access to the store. If this is set to `offline`, we can short-circuit the auto-refreshing of snaps so aren't even attempted.

o/snapstate: use store.access disable auto refresh

---

interfaces/builtin/network_status.go

This is a patch we've been using in the Core Desktop snapd tree for a while but had forgotten to upstream.
The `network-status` interface is used as a marker interface by `xdg-desktop-portal` to decide whether to provide access network connectivity portal API. We are using `xdg-desktop-portal` on Core Desktop, so needed to make this implicit slot available on core too.
We currently have one spread test for the interface in `tests/main/interfaces-network-status-classic`, but it is hard to get this running with any of the `ubuntu-core-*` backends since none of them currently include xdg-desktop-portal.

interfaces: make network-status implicit on core - it is required for using the network portal

---

aspects/schema_test.go

This was failing to compile on 32-bit architectures because the untyped constants were implicitly converted to an int which they overflowed. Explicitly converting the constant to int64 fixes the issue.

aspects: convert untyped constant before calling Sprintf

---

overlord/devicestate/devicestate.go
overlord/devicestate/devicestate_remodel_test.go

When attempting a remodel to a model that includes a snap that has its presence set to `optional`, then you will encounter a panic if that optional snap is not already present on the system. This change fixes that panic. I will have a follow-up PR that makes the logic inside of this for-loop a bit simpler, hopefully reducing the likelihood of something like this in the future.

o/devicestate: fix panic when attempting remodel to model with an snap that has an optional presence

---

tests/nested/manual/install-min-size/task.yaml

`snap install` may cause reboot before the command ends, which causes a deconnection. ssh returns 255 when a error happens, so we detect the deconnection that way.

tests/nested/manual/install-min-size: make it more stable

---

tests/main/prepare-image-reproducible/task.yaml

pc-kernel is not avaiblable for i386 architecture, so the tests needs to be skipped
This is what we get in the debug session for the test in i386
> snap info pc-kernel
error: no snap found for "pc-kernel"

tests: fix prepare-image-reproducible test

---

overlord/snapstate/reboot.go
overlord/snapstate/reboot_test.go

While doing the next step for single-reboot feature, I ran into the issue that `core` base was being marked for restart-boundaries, even when not being the boot base. This happened because the `core` snap shows up in `mappedTss` whenever its being present (unlike other bases, that only show up in `mappedTss` if they're the boot-base), so we must be a bit more careful to make sure that it's *actually* the boot-base, and not just there for other reasons.

o/snapstate: avoid incurring an extra reboot boundary for core snap when not boot-base

---

cmd/snap-bootstrap/initramfs_systemd_mount.go
cmd/snap-failure/cmd_snapd.go
daemon/api_general.go
errtracker/errtracker.go
osutil/disks/blockdev.go
osutil/disks/disks_linux.go
osutil/exec.go
osutil/exec_test.go
osutil/group.go
osutil/outputerr.go
osutil/outputerr_test.go
overlord/configstate/configcore/hostname.go
overlord/devicestate/devicestate_test.go
overlord/servicestate/servicemgr.go
snap/integrity/dmverity/veritysetup.go
snap/squashfs/squashfs.go
sysconfig/cloudinit.go
systemd/systemd.go
systemd/systemd_test.go
tests/lib/muinstaller/main.go
usersession/userd/launcher.go
usersession/userd/settings.go
wrappers/services_test.go

Some invocations to external programs used exec.CombinedOutput, that
combines stdout and strerr into a single byte array. This can be an
issue if this output is parsed, as many programs print debug output or
warnings to stderr and that data is unexpected by the parsers. This
patch changes to using osutil.RunSplitOutput or osutil.RunCmd (that
return separately stdout and stderr) when we need to parse stdout, and
also in some other cases when printing separately both streams could
be helpful. Fixes LP #1885597.

many: replace exec.CombinedOutput when output is parsed

---

interfaces/builtin/u2f_devices_test.go

5238d0581c9ed5ca3b0fdd80c63ac02628326ded broke the test by adding a new device. This should fix it.

i/builtin: fix u2f tests that was broken by adding new device

---

gadget/gadget.go

Cleaning the function added in https://github.com/snapcore/snapd/pull/13173. We no longer use it since we ubuntu-image moved to JSON encoding.

gadget: clean now useless ResetEnclosingVolumeInStructs function

---

cmd/snap-confine/mount-support-nvidia.c

Upcoming versions of the NVIDIA driver will include a new component:
https://forums.developer.nvidia.com/t/new-driver-component-libnvidia-gpucomp/267060
Update the list of NVIDIA driver libraries so that it can be included in the runtime environment along with the others.

cmd/snap-confine: add libnvidia-gpucomp to the list of nvidia driver library globs

---

tests/nested/manual/fde-on-classic/task.yaml
tests/nested/manual/muinstaller-real/task.yaml

Some of the reboot messages for the tasks changed with the restart code changes. Update them to make the tests pass.

tests/nested/manual: correct some reboot messages after reboot code changes

---

interfaces/builtin/gpio_control.go

A followup from #12816. This change will allow access to devices that are in any number of sub-directories in `/sys/devices/platform`. Unsure if this is the change we want, might be too liberal.
Example of paths that do not match the current pattern:
```
/sys/devices/platform/INT3452:00/gpiochip/gpio/gpio123
/sys/devices/platform/soc@0/soc@0:bus@30000000/30200000.gpio/gpiochip0/gpio/gpio123
```

i/builtin: update gpio profile to match pattern that contains multiple subdirectories under /sys/devices/platform

---

overlord/devicestate/devicestate_bootconfig_test.go
overlord/devicestate/devicestate_gadget_test.go
overlord/managers_test.go
overlord/restart/restart.go
overlord/restart/restart_test.go
overlord/snapstate/handlers_link_test.go
tests/nested/manual/snapd-refresh-from-old/task.yaml

When an older snapd is refreshed, together with an essential snap, then snapd would refresh to the new snapd, containing the new restart logic. The new restart logic relied on restart-boundaries to inform us when a change needs to restart before continuing, but the pre-this change does not have those. So we default to all restarts being restart-boundaries, when a change has no restart boundaries. 
This PR fixes the upgrade path from a old snapd to newer snapd where the restart logic is present. This was discovered by the nested test (and valentin!) tests/nested/core/core-snap-refresh-on-core, however the test wont be fixed before this lands in edge.

overlord/restart: support upgrade path from older snapd to newer with new restart logic

---

cmd/snap-repair/export_test.go
cmd/snap-repair/runner.go
cmd/snap-repair/runner_test.go

The handler for the `store.access` configurable writes a file to `/var/lib/snapd/repair.json`. Example:
```shell
ubuntu@core22:/var/lib/snapd$ cat repair.json | jq .
{
"store-offline": true
}
```
This PR modifies `snap-repair` to parse this file and disable store access if `store-offline` is set to true. If the file is not present or unparseable for some reason, then the store will be assumed to be online.
Example of running `snap-repair` when the store is offline:
```shell
ubuntu@core22:~$ sudo ./snap-repair run
error: snap store is marked offline
```

cmd/snap-repair: make snap-repair respect store.offline configurable

---

tests/nested/manual/core20-boot-config-update/task.yaml

In some cases the reboot was happening while running "snap watch", it makes more sense to run this after the reboot to ensure that the change has finished.

tests/core20-boot-config-update: wait for the reboot before the watch

---

interfaces/builtin/microstack_support.go

microstack requires read access to ``@{PROC}/*/{,task/*/}sched`` and ``@{PROC}/*/{,task/*/}schedstat`` to allow virsh to read cpu statistics of the instances.
Without this rule, ``openstack-hypervisor.virsh domstats <id>`` does not print cpu statistics, to be specific ``vcpu.<id>.time``, ``vcpu.<id>.wait``.
Apparmor deny rule in dmesg:
```
[98847.604617] audit: type=1400 audit(1693470840.357:1499):  apparmor="DENIED" operation="open" profile="snap.openstack-hypervisor.libvirtd" name="/proc/2014588/task/2014595/sched" pid=3668724 comm="rpc-libvirtd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```
This rule is also required by ceilometer service running on the openstack-hypervisor snap which queries libvirt for the cpu/memory/disk statistics of the instances running on hypervisor [1]. …

interfaces/microstack-support: read access to /proc/task/sched{,stat}

---

interfaces/builtin/microceph.go

Allow more types of block devices to be added as an OSD (bcache, indiv. partitions)
Allow access to the rbd sysfs controls for managing rbd-backed block devices (cf.
https://docs.kernel.org/admin-guide/abi-testing.html#abi-file-testing-sysfs-bus-rbd)

i/b/microceph: allow more access for microceph-support

---

secboot/luks2/luks2.go

Removes an unused variable that is breaking the build on master.

secboot/luks2: remove unused variable

---

overlord/snapstate/handlers_link_test.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate_test.go

The local cleanup test was failing on some systems due timing issues. I had to remove a check in another test because it started failing due to the new call to the mocked function. It was a somewhat roundabout way to check that LastRefreshTime was set by the link-snap task so I think there's not much loss in removing it

o/snapstate: fix flaky local install cleanup test

---

overlord/devicestate/devicestate_gadget_test.go
overlord/devicestate/handlers_gadget.go
overlord/managers_test.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_link_test.go

Something I had missed is that `link-snap` for gadget will not request a restart (i.e RestartRequired is hardcoded to false in bootstate20.go), which makes a change that contains a gadget not do any immediate restarts during the change. Instead gadget changes will restart when the change completes (goes into done), which is different from the previous logic.
Currently we set boundaries on `link-snap`, but not the gadget tasks `update-gadget-assets` or `update-gadget-cmdline`, which are the tasks that request reboots during a gadget update. But we don't want to set boundaries on those either as we don't want to end in a sitautation where we do 2 reboots, and we cannot know before-hand whether one of these (or both) will request a reboot.
Instead we make the tasks set a variable on the …

overlord: make link-snap request a reboot for gadget updates if any update to assets was made

---

wrappers/desktop.go

These are new additions in versions 1.4 and 1.5 of the [Desktop Entry Specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html) respectively, so are new since April 2020. Both are boolean keys, and seem safe to pass through from their description.
I filed this in response to this post in a thread on the forum:
https://forum.snapcraft.io/t/snaps-dont-detect-nvidia-driver-in-wayland/35065/14?u=jamesh

wrappers: allow PrefersNonDefaultGPU and SingleMainWindow keys in desktop files

---

tests/core/core-dump/core-dump-snap/bin/crash.sh
tests/core/core-dump/core-dump-snap/meta/snap.yaml
tests/core/core-dump/task.yaml

As reference, see https://forum.snapcraft.io/t/core-dumps-in-snapd/920

tests/core-dump: check that core dumps can be generated on UC

---

tests/nested/core/connected-after-reboot-revert/task.yaml
tests/nested/core/kernel-revert-after-boot/task.yaml

Modify installed kernel instead of downloading it, this will speed up the tests. Also, we cannot use pc-kernel from the edge channel anymore as it is not signed now with Canonical keys.

tests/connected-after-reboot-revert: modify installed kernel

---

aspects/schema.go
aspects/schema_test.go

Adds support for the "number" type in aspect schemas, with constraints to restrict its max, min and allowed values. I used generics to implement a generic validation of the number and int types. I'm not sure if we've used generics before since the codebase predates them but AFAIK we've also never explicitly decided against them. Since this package is new and self-contained, I didn't see a reason not to here.

aspects: support "number" type in aspect schemas

---

boot/boot.go
boot/boot_test.go
boot/cmdline.go
boot/cmdline_test.go
boot/makebootable.go
boot/makebootable_test.go
bootloader/bootloader.go
bootloader/bootloadertest/bootloadertest.go
bootloader/grub.go
overlord/devicestate/devicestate_bootconfig_test.go
overlord/devicestate/devicestate_gadget_test.go
overlord/devicestate/systems_test.go
overlord/managers_test.go

We know what are the default the default command line so that we can compute measurement, so there is not much reason to use `snapd_extra_cmdline_args`. Always using `snapd_full_cmdline_args` will allow us to filter part of the default command line.
There is a potential bug when filtering all arguments, `grub.cfg` will just revert to the all the default. We will need to fix it when we introduce the filtering.
See #12987 for full feature branch

boot: only use variable snapd_full_cmdline_args

---

spread.yaml

Channel for kernel cannot be edge as that one is not signed with Canonical keys anymore.

spread.yaml: set default kernel channel to beta

---

aspects/schema.go
aspects/schema_test.go

The null value will be used to delete entries so it's not a valid value for any type (even the actual "any" type).

aspects: reject null values for all types 

---

overlord/devicestate/devicestate.go
overlord/devicestate/devicestate_remodel_test.go
overlord/managers_test.go

Changes to snapd in a new model assertion (which can be only changes
in tracked channel at the moment) where not being applied, make sure
this does not happen anymore. Fixes LP#2035186.

o/devicestate: consider snapd snap when remodeling

---

interfaces/builtin/polkit_agent.go
interfaces/builtin/polkit_agent_test.go

New versions of polkit, such as the one in Ubuntu 23.10 move the polkit-agent-helper-1 executable from `/usr/libexec` to `/usr/lib/polkit-1`. The change can be seen in this file listing from the package:
https://packages.ubuntu.com/mantic/amd64/polkitd/filelist
This PR updates the polkit-agent interface to match the new path.

interfaces: update polkit-agent interface to handle new location of polkit-agent-helper-1

---

wrappers/core18.go
wrappers/export_test.go
wrappers/internal/export_test.go
wrappers/internal/journal_conf_gen.go
wrappers/internal/service_slice_gen.go
wrappers/internal/service_socket_gen.go
wrappers/internal/service_socket_gen_test.go
wrappers/internal/service_status.go
wrappers/internal/service_timer_gen.go
wrappers/internal/service_timer_gen_test.go
wrappers/internal/service_unit_gen.go
wrappers/internal/service_unit_gen_test.go
wrappers/services.go

Split out internal functionality in the wrappers package for services into an 'internal' package. Nothing functionality/test wise is changed, this also makes it easy to see what's tested and what's not tested.

wrappers: restructure service code, and split into an internal package

---

image/image_test.go
seed/seedwriter/seed16.go
seed/seedwriter/seed20.go
seed/seedwriter/writer.go
seed/seedwriter/writer_test.go

this is a preparatory step to fix the image building side of the issue of not supporting when a default-provider content is fulfilled by an alternative snap
this also drops some tests and behavior related to core16, as it's not pursued anymore and it was getting in the way here

seed/seedwriter,image: prereq check strategy change to use snap.ValidateBasesAndProviders

---

tests/main/interfaces-content/task.yaml

The interfaces-content tests was failing because installing the test-snapd-content-plug snap was pulling in the core snap which couldn't be validated. The root cause was that the download core revision (16203) is the same as the revision downloaded and modified during the prepare stage so it triggered a cache hit. The installation would then try to find an assertion based on the snap's digest which doesn't exist because it was modified. Clearing the cache fixes the problem.

tests: fix interfaces-content test by clearing snap cache

---

interfaces/builtin/microceph.go

This reverts commit 29878c72f782f44f9ca4aacd6971c7c70258d128.
the permissions are support permission for the service, not for the client side, so they were wrongly placed

revert i/b/microceph: allow more access for microceph-support (#13150)

---

spread.yaml
tests/lib/prepare.sh

pc-kernel was being downloaded twixe in some cases. Prevent that, also this was provoking failures in arm64 spread tests as no kernel was published for latest track for that arch.

tests: avoid downloading twice pc-kernel

---

snapdtool/tool_linux.go
snapdtool/tool_test.go

The current version of `InternalToolPath()` does not actually checks in all cases if the binary is actually there. Historically this was not a problem but with recent snapd releases we have the internal tool `apparmor_parser` that is only available in the `snapd` snap but not in the `core` snap. This means that on systems that have the snapd deb and only core `InternalToolPath` may return `/snap/core/123/usr/lib/snapd/apparmor_parser` even if this tool in not available inside the core snap.
This commit fixes this by checking if the actual executable is available.

snapdtool: check for binary existence in InternalToolPath()

---

tests/core/snapd-maintenance-msg/task.yaml

Refresh core20 snap using --amend as now it is not installed from the store with assertions.

tests: fix snapd-maintenance-msg

---

data/selinux/snappy.te

The selinux-clean test started failing in fedora and centos recently.
It is caused by a change in the polkit_agent interface where now the polkit-agent-helper-1 is located here
/usr/lib{exec,/polkit-1}/polkit-agent-helper-1
The change has been introduced in:
https://github.com/snapcore/snapd/pull/13261
The denial produced is the following:
type=AVC msg=audit(1698154354.527:12577): avc:  denied  { getattr } for pid=82525 comm="snapd" path="/usr/lib/polkit-1/polkit-agent-helper-1" dev="sda5" ino=109823 scontext=system_u:system_r:snappy_t:s0 tcontext=system_u:object_r:policykit_auth_exec_t:s0 tclass=file permissive=1

tests: fix selinux policy to support change in polkit_agent interface

---

tests/main/layout-change/task.yaml

Currently it is failing on armhf and also in ubuntu-core-16-32 (beta validation)

tests: skip layout-change test in all arm devices

---

daemon/api_sideload_n_try.go
daemon/api_sideload_n_try_test.go
daemon/export_test.go
overlord/devicestate/devicestate.go
overlord/devicestate/devicestate_remodel_test.go
overlord/devicestate/devicestate_test.go
overlord/devicestate/export_test.go
overlord/devicestate/firstboot.go
overlord/devicestate/handlers_test.go
overlord/hookstate/ctlcmd/services_test.go
overlord/managers_test.go
overlord/snapstate/autorefresh.go
overlord/snapstate/autorefresh_gating_test.go
overlord/snapstate/autorefresh_test.go
overlord/snapstate/export_test.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_prereq_test.go
overlord/snapstate/refreshhints.go
overlord/snapstate/refreshhints_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go
overlord/snapstate/storehelpers.go
overlord/snapstate/storehelpers_test.go
snap/info.go
snap/info_test.go
snap/validate.go
snap/validate_test.go

The idea is to gain more control over how snapstate functions to plan snap operations track prerequisites.  So that later we can have an implementation of snapstate.PrereqTracker that supports properly self-contained sets of snaps and can deal with alternative providers for content more in the same way as we do during normal operations. This implementation could then be used first for seeding and then also for remodel, instead of the current code that requires the default-providers to be installed and otherwise errors. The snapstate functions that are getting a PrereqTracker argument added are the one we use in those contexts.

many: introduce snapstate.PrereqTracker interface and snap.SimplePrereqTracker

---

tests/core/system-snap-refresh/task.yaml
tests/lib/tools/snaps-state
tests/main/snaps-state/task.yaml

Simplify the system-snap-refresh test and validate the base snap during restore is the same revision than the initial one (no need to remove).
Also it is included a new function to determine the revision of a snap and the test is updated accordingly.

tests: fix system-snap-refresh in uc20

---

gadget/update.go
gadget/update_test.go

Make sure that kernel/gadget updates on UC16/18 do not fail even in the case that the gadget volumes do not match the installed disk. This fixes a regression in behavior due to DiskTraitsFromDeviceAndValidate now checking compatibility with the disk, which was happening in a later stage in the past.

gadget: prevent failures when updating kernel/gadget on UC16/18

---

boot/boot.go
boot/boot_test.go

`ubuntu-core-20-64:tests/core/system-snap-refresh` fails because of this.

boot: lock the modeenv while reading revisions

---

overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_update_test.go

If we were remodeling to a different snapd track and that track contained an older snapd version than the current track, snapd reported incorrectly a conflict with a remodel change. Prevent that by passing to the conflict checker the change we are running.

o/snapstate: check properly conflicts when refreshing snapd

---

overlord/snapstate/autorefresh_gating_test.go
overlord/snapstate/export_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_test.go
tests/core/kernel-and-base-single-reboot/task.yaml

@niemeyer remarked that the message was a bit  mysterious and that listing all snaps for auto-refresh got very noisy
we still need to address the mechanics of how the task is run but that needs support from overlord/state and is a bigger change

o/snapstate: try to make the check-rerefresh summary cleaner/clearer

---

overlord/managers_test.go
overlord/snapstate/backend_test.go
overlord/snapstate/export_test.go
overlord/snapstate/handlers.go
overlord/snapstate/reboot.go
overlord/snapstate/reboot_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go
tests/core/kernel-base-gadget-failover/task.yaml

Move the snap dependency logic out of doUpdates, and move it into explicit functions that coordinate snap changes. This also gets rid of the behavior that `rearrangeBaseKernelForSingleReboot` introduces, which carefully rearranges task-sets to overlap correctly to support a single-reboot.
Instead the snap-dependency logic has been made much more visible, and is manually arranged instead of done in a loop. The new dependency logic also supports the single-reboot functionality, but by splitting task-sets into two parts (i.e pre-boot and post-boot), instead of rearranging individual tasks.

o/snapstate: add explicit snap dependency logic for doUpdates

---

cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
overlord/overlord_test.go
overlord/state/copy_test.go
overlord/state/export_test.go
overlord/state/notices.go
overlord/state/notices_test.go
overlord/state/state.go
overlord/state/state_test.go

The addition of Notices in snapd is based on Pebble Notices, for which the spec can be found at [JU048](https://docs.google.com/document/d/16PJ85fefalQd7JbWSxkRWn0Ye-Hs8S1yE99eW7pk8fA).
This PR adds notices to the snapd state, and exposes them primarily through `state.Notice`, `state.Notices`, and `state.WaitNotices`. The former allows looking up a particular notice by ID, and the latter two return existing notices which match the given optional filter. Notably, `state.WaitNotices` can be used to long-poll for new notices as they occur.
The corresponding PR in Pebble is: https://github.com/canonical/pebble/pull/295

o/state: implement core support for notices

---

aspects/schema.go
aspects/schema_test.go

Adds support for arrays in aspect schemas. Since this is the only type that must have a map definition with a "values" constraint, I added a new method to the parser interface to distinguish between types that have to have constraints.

aspects: support array type in aspect schemas

---

overlord/devicestate/devicestate.go
overlord/devicestate/devicestate_remodel_test.go

~~#13230 should be merged first before reviewing this.~~ done!
The loop that is responsible for updating/installing snaps that are in the new model is pretty complicated and difficult to trace through. This PR hopefully simplifies the logic a bit, while maintaining the current functionality.

o/devicestate: refactor remodelTasks for readability

---

tests/main/snap-run/task.yaml

Support a new error message displayed when executable is not found.

tests: fix snap-run test on arch-linux and tumbleweed

---

interfaces/builtin/media_control.go
interfaces/builtin/media_control_test.go

libcamera requires file locking on `/dev/media[0-9]*`. AppArmor denies locking currently, resulting in a _"Pipeline handler in use"_ error. Adding a `k` permission will solve this issue for AppArmor.

interfaces/media-control: also allow 'k' (lock)

---

cmd/snap/cmd_pack.go
cmd/snap/cmd_pack_test.go
overlord/snapstate/check_snap.go
snap/component.go
snap/component_test.go
snap/container.go
snap/container_test.go
snap/export_test.go
snap/naming/componentref.go
snap/naming/componentref_test.go
snap/pack/pack.go
snap/pack/pack_test.go
snap/snaptest/snaptest.go
snap/snaptest/snaptest_test.go
snap/validate.go
snap/validate_test.go

With this change we will be able to pack directories containing file `meta/component.yaml` with `snap pack <dir>`.

cmd,snap: add support to pack snap components

---

tests/nested/manual/core20-to-core22/task.yaml

The command has a typo which is fixed

tests: fix core20-to-core22 test

---

overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go
overlord/snapstate/storehelpers.go

This wrapper addresses the case were the store doesn't return refresh candidates for snaps with already existing `refresh-candidates` that are being monitored due to throttling.
A second request is sent for eligible snaps that might have been throttled with the `RevisionOptions.Scheduled` option turned off.
This PR should unblock #13215.

o/snapstate: wrap `refreshCandidates` to mitigate store throttling

---

client/login.go
tests/main/nfs-support/task.yaml

the group is not relevant for this even under NFS, otoh
trying to switch it fails under running with sg
this makes sg lxd -c "snap..." work again
also test the fixes for access to auth.json under NFS more in general

client,tests: do not try to change the gid when reading/removing auth.json

---

image/image_test.go
overlord/devicestate/firstboot.go
overlord/devicestate/firstboot_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_update_test.go
seed/seedwriter/writer.go
seed/seedwriter/writer_test.go
seed/validate.go
seed/validate_test.go
snap/validate.go
snap/validate_test.go

also in snap.ValidateBasesAndProviders
these now can produce warnings, OTOH the relaxed checks allow to build/seed an
image even if a content requirement is fulfilled by an alternative provider
notice that with the relaxed checks seeding might fail or the system not work
if the right auto-connections or connections are not in-place
snaps used as default-providers usually have been taken care of already but it
might be up to the user to ask to set that up for alternative ones

many: introduce and use snap.SelfContainedSetPrereqTracker

---

.github/workflows/test.yaml
tests/lib/nested.sh

This change adds a dependency between the labeler and the tests workflows. 
Then after the labeler is executed, the nested test job requests the labels added to the PR and based on that request it is determined if the nested tests have to be executed.
The collect step needs to be included in the same job (to be able to retrieve the output) and it is executed by using the gh client tool.

tests: stablish a dependency between test and labeler workflows

---

release-tools/changelog.py

The changelog.py script was failing on some older systems because BeautifulSoup could return a  different type: `AttributeError: 'NavigableString' object has no attribute 'text'`
Related PR https://github.com/snapcore/snapd/pull/13202

release-tools: fix handling of NEWS.md items

---

tests/lib/prepare.sh
tests/lib/reset.sh

Save preinstalled snaps when tests are executed in external systems 
The preinstalled snaps shouldn't be removed during tests clean up 
This is needed just for external devices because those could be using custom images with pre-installed snaps which cannot be removed, such as the network-manager.

tests: avoid removing preinstalled snaps in external devices

---

run-checks
tests/main/ack/task.yaml
tests/main/alias/task.yaml
tests/main/api-get-systems-label/task.yaml
tests/main/appstream-id/task.yaml
tests/main/apt-hooks/task.yaml
tests/main/aspects/task.yaml
tests/main/auth-errors/task.yaml

Add details to tests. This is part of the documentation plan.
Also it fixes issue in tests check when there are more than 1 test to validate.
Without this fix, the run-checks is failing when a PR changes more than 1 test.

tests: fix tests checks and add missing details in spread tests - part 1

---

tests/lib/snaps/store/test-snapd-load-generator/load-generator
tests/lib/snaps/store/test-snapd-load-generator/snapcraft.yaml

This snap can be used to generate cpu load to simulate different scenarios. Also allows to define the time for the load and the extra memory to use.
It is possible to generate load in a specific core but also in all the cores available in the system.

tests: adding new load generator snap

---

packaging/debian-sid/snapd.install

In debian sid, the system-generators are being created in usr/lib/systemd/system-generators instead of lib
This is needed to avoid this error building snapd:
dh_install: warning: Cannot find (any matches for) "lib/systemd/system-generators" (tried in ., debian/tmp)
dh_install: warning: snapd missing files: lib/systemd/system-generators
dh_install: error: missing files, aborting
make[1]: *** [debian/rules:265: override_dh_install-arch] Error 25

packaging: move directory for snapd-generator in debian sid

---

asserts/snapasserts/validation_sets.go
asserts/snapasserts/validation_sets_test.go
overlord/assertstate/assertstate.go
overlord/assertstate/assertstate_test.go

These functions/methods will be used in a later PR that takes into account validation sets during a remodel.
Usage of the new functionality is in this PR here: #13243

a/snapasserts, o/assertstate: add functions to help during remodel

---

overlord/snapstate/export_test.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go
overlord/snapstate/storehelpers.go

This commit fixes a regression caused by (#13259).
`refreshCandidates` wrapper was trying to check for updates for existing refresh candidates that were monitored even when not being passed in `names`. This caused snapd to crash when trying to access the `SnapState` for those updates later.
Thanks @pedronis for finding this and suggesting the fix.

o/snapstate: only use names passed to refreshCandidates

---

tests/core/basic20plus/task.yaml

This test is failing because uc22 on rpi is not using grub, it uses piboot instead. 
The test is failing to find the kernel.efi

tests: fix basic20plus test for uc22 on rpi

---

overlord/snapstate/handlers.go
overlord/snapstate/handlers_rerefresh_test.go
overlord/snapstate/snapstate_update_test.go

Discoved during the refactoring of the snap-dependency logic, where we saw that `refreshedSnaps` would not correctly return the list of snaps that were refreshed when the snaps share a single lane. This was the intended behaviour, as evident from the unit tests that specifically covered this scenario. So this is simply a change in behaviour to support snaps that are transactional.

overlord/snapstate: support snaps on same lane in refreshedSnaps

---

overlord/snapstate/snapstate_test.go

the snapstate unit tests otherwise can fail if run inside for example a lxd container

o/snapstate: make tests work consistently also in containers

---

aspects/aspects.go
aspects/aspects_test.go
overlord/aspectstate/aspecttest/mock_aspect.go

The terminology used in the aspect-bundle assertion and the spec has changed so this just replaces name with request and path with storage.

many: replace name w/ request and path w/ storage

---

cmd/snapd-generator/main.c
overlord/snapstate/snapstate_test.go

Systemd now runs generators in a sandbox. That means `/proc/self/mountinfo` does not represent correctly the mounts of the system.

cmd/snapd-generator: read mountinfo for pid 1  (2.60)

---

spread.yaml
tests/lib/nested.sh
tests/lib/tools/tests.nested
tests/nested/manual/minimal-smoke/task.yaml
tests/nested/perf/interfaces-core-provided/task.yaml
tests/perf/interfaces-core-provided/task.yaml

This is the initial change to support performance tests.
These new tests have to be able to run either in nested vms and in external devices.
The idea is to run nightly and on demand on nested vms and also as part of regular runs on specific devices.
The initial test is about connecting and disconnecting interfaces, covering a specific percentage of those and also test how the system behaves when all are connected together.

tests: add new performance and load test suite

---

overlord/snapstate/backend.go
overlord/snapstate/backend/mountunit.go
overlord/snapstate/backend/mountunit_test.go
overlord/snapstate/backend_test.go
overlord/snapstate/handlers.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate_test.go
snap/info.go
snap/info_test.go

and implement for snap.Info type. This interface will be used when
possible to make easier to reuse code for components where possible.

snap: create ContainerPlaceInfo interface

---

tests/nested/manual/core20-to-core22/task.yaml

Tests should pass once lp:1979197 is fixed

tests: revert the skip for change in nested test core20-to-core22

---

.github/workflows/test.yaml

Master is failing with some new typecheck failure in very old code but it's not reproducible locally. Let's try to bump up the version. Related https://github.com/snapcore/snapd/pull/13419 and https://github.com/snapcore/snapd/pull/13421

.github: update golangci-lint version to v1.55.2

---

boot/assets_test.go
boot/boot_test.go
boot/modeenv_test.go

Follow-up to https://github.com/snapcore/snapd/pull/13419. The original error message was a bit lacking so I missed that there were other similar errors. This adds types to the remaining missing slices. There's quite a few usages of `BootAssetsMap` and while some have types, others don't. I used this: 
```
grep --no-messages --no-group-separator -R -n -A 3 BootAssetsMap{ . | awk 'NR%4{printf "%s ",$0;next;}1' | grep -v "\[\]string"
``` 
to find usages of `BootAssetMap` that don't use types in the map values. It could miss things if any usage put the map values inline and there happened to be an unrelated `[]string` below it but a quick grep shows that's never the case.
Unfortunately, I haven't been able to reproduce the golangci failures locally, even with the same version run in the same …

boot: fix more slices missing types

---

aspects/aspects.go
aspects/aspects_test.go
daemon/api_aspects_test.go
daemon/export_test.go
overlord/aspectstate/aspectstate.go
overlord/aspectstate/aspectstate_test.go
tests/main/aspects/task.yaml

Get() can match requests to prefixes of the "request" field specified in the aspect's rules. When it does, the result is returned in a namespace equivalent to the unmatched sub-keys. Conceptually, the specified "request" is a namespace that the user's request cuts through during the operation. If there is more than one match for a request, the results are merged when possible (e.g., maps are merged and scalar can replace other scalars in leafs).

aspects: Get() matches request on prefixes and returns results in a merged namespace

---

interfaces/builtin/qualcomm_ipc_router_test.go

Ensure the required AppArmor parser feature is mocked during tests otherwise they may inadvertently fail.

interfaces/qualcomm_ipc_router: mock required features in test

---

interfaces/builtin/fwupd.go

On aarch64 devices supporting it, capsule update on disk will be used. This require access to the ESP's EFI/UpdateCapsule.
Fixes fwupd/fwupd#6256

i/b/fwupd.go: Allow write access to COD capsule update directory

---

interfaces/builtin/fwupd.go

Added in upstream: fwupd/fwupd#6236

i/b/fwupd.go: add access sysfs attributes needed by amdgpu

---

interfaces/builtin/fwupd.go

i/b/fwupd.go: give access to IPMI devices

---

overlord/devicestate/devicestate.go
overlord/devicestate/devicestate_remodel_test.go

We should not support remodeling from UC18+ to UC16. This change explicitly prevents that from happening.

o/devicestate: make sure we do not remodel to UC16 from UC18+

---

interfaces/builtin/desktop.go

This PR combines a few changes that we have been using on the Core Desktop images for a while. This includes:
1. Allow snaps with a desktop slot to talk to xdg-desktop-portal. This avoids the need for a self-connected desktop plug on the snap to allow e.g. opening links from apps bundled in the ubuntu-desktop-session snap.
2. Allow access to GDM's `OpenReauthenticationChannel` API and the associated private bus address. This is used by gnome-shell to authenticate the user on its lock screen. To work with newer GNOME versions, we depend on [GDM !226](https://gitlab.gnome.org/GNOME/gdm/-/merge_requests/226) to use a socket location outside of `/tmp` (which can't work with a snap-style private tmp directory).
3. Allow communication with colord on the D-Bus system bus. The shell uses this to …

interfaces: update desktop interface AppArmor permanent slot rules

---

cmd/snap-update-ns/change.go
cmd/snap-update-ns/change_test.go
cmd/snap-update-ns/export_test.go
cmd/snap-update-ns/update_test.go

`snap-update-ns` was dropping some synthetic mounts due to failure to match desired mounts that depend on them.
This mismatching was due to setting `x-snapd.needed-by` to whatever path that needed it (source or target) and not the mount entry id (`XSnapdEntryID()` which defaults to target if not set) which is later on is used in `NeededChanges()` to compute which synthetic mounts need to be kept.
https://github.com/snapcore/snapd/blob/38a74ecb3f8907e3808ff973f119ae396c53cbfd/cmd/snap-update-ns/change.go#L570-L574
https://github.com/snapcore/snapd/blob/38a74ecb3f8907e3808ff973f119ae396c53cbfd/cmd/snap-update-ns/change.go#L612-L616
Partially fixes: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/2043993
Mount ordering/logic needs a more in-depth refactor, this is just a bug fix in the …

cmd/snap-update-ns: set sythentic mounts `x-snapd.needed-by` to entry id instead of path

---

cmd/libsnap-confine-private/tool.c
cmd/snap-confine/snap-confine.c

Modify snap-confine to pass environment variables `$SNAP_UID` and `$SNAP_REAL_HOME` when a non-root user runs a non-classic snap application.
`$SNAP_REAL_HOME` is passed to `snap-update-ns` to enable expanding the new `ensure-dir` mount entries used for the personal-files interface that reference `$HOME`.  It is proposed that `$SNAP_UID` is also passed to `snap-update-ns` to allow for a basic sanity check to ensure that `$SNAP_REAL_HOME` belongs to the correct uid.
Call path:
`snap-confine.c | main() -> enter_non_classic_execution_environment() -> snap-confine/mount-support.c | sc_setup_user_mounts() -> libsnap-confine-private/tool.c | sc_call_snap_update_ns_as_user()`
This PR is `part 1` of a larger feature to automatically create missing personal-files interface parent directories. …

cmd/libsnap-confine-private: pass env real-home to snap-update-ns

---

tests/main/interfaces-personal-files/task.yaml
tests/main/interfaces-personal-files/test-snapd-sh/meta/snap.yaml

Spread testing to cover the personal-files missing directory creation solution consisting of [pull/13244](https://github.com/snapcore/snapd/pull/13244), [pull/13260](https://github.com/snapcore/snapd/pull/13260) and [pull/13342](https://github.com/snapcore/snapd/pull/13342).
The PRs have been broken up to simplify review. Only the tests part of this PR is relevant to this review, the remainder of commits are to provide the changes of the implementation PRs while they are not merged.
**This should be merged last after the 3 part implementation, so that the delta consist of the spread test changes only.**

tests: extend interfaces-personal-files for missing directory creation

---

NEWS.md
usersession/agent/export_test.go
usersession/agent/response.go
usersession/agent/rest_api.go
usersession/agent/rest_api_test.go
usersession/client/client.go
usersession/client/client_test.go

This is the next part of adding remaining user-services support in the wrappers package. This PR adds support for restarting and querying of service status. 
Next parts:
Supporting restart/querying user daemons in wrappers: https://github.com/snapcore/snapd/pull/13337
Support for scopes/user-selection in daemon API: https://github.com/snapcore/snapd/pull/13338
Support for querying user daemons in servicestate: https://github.com/snapcore/snapd/pull/13380
Support for --user/--users/--system in cli: https://github.com/snapcore/snapd/pull/13367 + https://github.com/snapcore/snapd/pull/13368 + https://github.com/snapcore/snapd/pull/13381

usersession: implement restart controls and status querying for user services

---

aspects/aspects.go
aspects/aspects_test.go
aspects/transaction.go
aspects/transaction_test.go
daemon/api_aspects.go
daemon/api_aspects_test.go
daemon/export_test.go
overlord/aspectstate/aspectstate.go
overlord/aspectstate/aspectstate_test.go

A Get() with a request that matches a rule without filling some of its placeholders gets the results from all possible placeholder values. The namespace in which the result in inserted takes these values into account instead of the unmatched placeholder.

aspects: unmatched placeholder returns all values

---

tests/main/snap-run/task.yaml

fix the test following the same pattern than other systems

tests: fix snap-run test work on ubuntu 24.04

---

overlord/snapstate/export_test.go
overlord/snapstate/handlers.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_remove_test.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go

This PR aims to clean up snap downloads that are not used anymore.
Clean up is run once for all snaps on startup, and run per-snap during pre-downloads.
relevant lp bug: https://bugs.launchpad.net/snapd/+bug/2033268 and https://bugs.launchpad.net/snapd/+bug/2043860

overlord/snapstate: remove unused snap downloads

---

interfaces/builtin/uio.go
interfaces/builtin/uio_test.go

The customer has a specific network component chip for industrial automation whose driver provides a way to configure the device via sysfs. 
```
May 04 15:48:33 mydevice audit[754]: AVC apparmor="DENIED" operation="open" profile="snap.my-snap.control" name="/sys/devices/pci0000:00/0000:00:01.1/0000:02:00.0/0000:03:00.0/config" pid=754 comm="my-snap" requested_mask="w" denied_mask="w" fsuid=0 ouid=0
May 04 15:48:33 mydevice kernel: audit: type=1400 audit(1683229713.151:85): apparmor="DENIED" operation="open" profile="snap.my-snap.control" name="/sys/devices/pci0000:00/0000:00:01.1/0000:02:00.0/0000:03:00.0/config" pid=754 comm="my-snap" requested_mask="w" denied_mask="w" fsuid=0 ouid=0
```
This PR expands the AppArmor profile to allow developers/customers to configure industrial I/O cards …

i/b/uio: allow configuring UIO drivers from userspace app/libraries

---

gadget/update.go
gadget/update_test.go

Boot assets must be updated in the reverse order of boot chain.  This is because new shim binary may not contain the certificate for older grub binaries, or even may revoke them. But new grub binaries may have several signatures.
Binaries from seed are loaded before binaries from boot. So the boot partition should be updated before the seed partition.

gadget/update.go: make sure to update boot before seed

---

.github/workflows/test.yaml

The idea of this change is to reduce the number of github runners needed to run the spread tests of a PR.
The systems in a group will be executed together in the same spread run, so in this case the number of runners needed to executed the whole change is reduced from 29 to 21
This approach could be also used to group in a different way the systems.
It is important to consider that required and non required systems don't have to be part of the same group.

tests: group the systems used in the github workflow

---

cmd/snapd-apparmor/main.go
cmd/snapd-apparmor/main_test.go

Add support to snapd-apparmor to properly support running under incus to fix https://bugs.launchpad.net/snapd/+bug/2042512

cmd/snapd-apparmor: add support for incus (LP: #2042512)

---

asserts/snapasserts/validation_sets.go
asserts/snapasserts/validation_sets_test.go

This method checks to see if a validation set has any rules pertaining to a snap. This method will be used during the creation of recovery systems to ensure that, if a validation set is used during the creation, that all snaps are constrained by the validation set.

a/snapasserts: add ValidationSets.SnapConstrained method

---

aspects/aspects.go
aspects/aspects_test.go
daemon/api_aspects.go
daemon/api_aspects_test.go

Per the spec, we should allow writes to match several entries with the same request but different paths so the storage can change while supporting old and new paths. The matching should also work on prefixes so we may write to paths nested in other matching paths and therefore have to take care to write to them in order of parentage to prevent overwriting more nested values.

aspects: set can write to multiple paths

---

spread.yaml
tests/perf/parallel-installs/task.yaml

This is required because gh is not available for arm64 devices

tests: update the snap used to install in parallel-installs perf test

---

sandbox/apparmor/notify/listener/export_test.go
sandbox/apparmor/notify/listener/listener.go
sandbox/apparmor/notify/listener/listener_test.go
sandbox/apparmor/notify/message.go
sandbox/apparmor/notify/message_test.go

This PR backports the listener package from the [WIP prompting branch](https://github.com/olivercalder/snapd/tree/prompting). The listener listens for and responds to access request messages from apparmor.

prompting: add listener package

---

boot/systems.go
boot/systems_test.go

This function will be used during the removal (and the undoing of creating) of a recovery system. It is the inverse of `MarkRecoveryCapableSystem`.

boot: add UnmarkRecoveryCapableSystem function for undoing creation of a recovery system

---

asserts/model.go
asserts/model_test.go
overlord/devicestate/devicestate.go

This method is a small helper that will be used during the creation of recovery systems. It also simplifies another case during remodeling a little bit.

asserts: add Model.AllSnaps method

---

aspects/aspects.go
aspects/aspects_test.go
daemon/api_aspects.go
daemon/api_aspects_test.go
overlord/aspectstate/aspectstate.go
overlord/aspectstate/aspectstate_test.go
tests/main/aspects/task.yaml

Instead of matching a request to rules and failing if those rules support the requested operation, ignore rules that don't and get/set those that do. If no rule matches the request string and the required access type, return the usual "no matching (read|write) rule".
Depends on https://github.com/snapcore/snapd/pull/13446, first relevant commit is 7919c287e8caea575395563fa4066193ad1e24f4

aspects: consider access when matching rules

---

daemon/api_base_test.go
daemon/api_sideload_n_try_test.go
daemon/api_snap_file_test.go
overlord/ifacestate/ifacestate_test.go
overlord/snapstate/booted_test.go
overlord/snapstate/component_install_test.go
overlord/snapstate/component_test.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_prereq_test.go
overlord/snapstate/sequence/sequence.go
overlord/snapstate/sequence/sequence_test.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go
overlord/snapstate/snapstatetest/snapstate.go

This will allow accessing the sequence in the state without using snapstate.

many: move snapstate.Sequence to its own package

---

sandbox/apparmor/notify/listener/export_test.go
sandbox/apparmor/notify/listener/listener_test.go

Thanks @ZeyadYasser for spotting the failure on https://github.com/snapcore/snapd/actions/runs/7486097781/job/20376253469?pr=13469

s/apparmor/notify/listener: fix concurrency test on slow single-core machines

---

cmd/snaplock/runinhibit/inhibit.go
cmd/snaplock/runinhibit/inhibit_test.go

This fixes a nil dereference bug that was introduced in https://github.com/snapcore/snapd/pull/13435. Nothing is  breaking because no part of snapd is using WaitWhileInhibited yet.

cmd/snaplock/runinhibit: fix nil dereference in WaitWhileInhibited

---

daemon/api_notices.go
daemon/api_notices_test.go
overlord/state/notices.go
overlord/state/notices_test.go

Add per-user notices. This is a backport of the following PR from pebble: https://github.com/canonical/pebble/pull/323

o/state,daemon: add per-user notices

---

overlord/devicestate/devicestate_serial_test.go
overlord/devicestate/handlers_serial.go

This fixes a panic that was reported when requesting a serial when `device-service.access=offline` is set.

o/devicestate: fix panic when requesting a serial when device-service.access=offline

---

overlord/hookstate/ctlcmd/mount.go
overlord/hookstate/ctlcmd/mount_test.go
overlord/snapstate/backend/mountunit.go
overlord/snapstate/backend/mountunit_test.go
overlord/snapstate/snapmgr.go
systemd/emulation.go
systemd/systemd.go
systemd/systemd_test.go

Remove SnapName from systemd.MountUnitOptions, as it was not used anymore (instead, the mount unit description already has the container name). Remove it from the EnsureMountUnitFile method as well.

overlord/systemd: remove unused variable from MountUnitOptions

---

daemon/api_base_test.go
daemon/api_sideload_n_try_test.go
daemon/api_snap_file_test.go
overlord/ifacestate/ifacestate_test.go
overlord/snapstate/booted_test.go
overlord/snapstate/component.go
overlord/snapstate/component_install_test.go
overlord/snapstate/component_test.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_components.go
overlord/snapstate/handlers_components_link_test.go
overlord/snapstate/handlers_components_mount_test.go
overlord/snapstate/handlers_components_prepare_test.go
overlord/snapstate/handlers_prereq_test.go
overlord/snapstate/sequence/sequence.go
overlord/snapstate/sequence/sequence_test.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go
overlord/snapstate/snapstatetest/snapstate.go

Storing the component type in the state is necessary so kernel-modules
type can be properly handled by the initramfs.

o/snapstate: add component type to sequence points and ComponentSetup

---

snap/component_test.go

Arch does not use /snap as the snap mount dir. Use the appropriate values from dirs to fix that.

snap: fix unit test on Arch

---

interfaces/builtin/desktop_test.go

Make sure that when checking Ubuntu Core scenario, the release info is mocked to indicate Ubuntu.
Fixes a unit test failure on Arch:
```
maciek@galeon:snapd/interfaces/builtin (git)-[bboozzoo/fix-component-location-test] go test
FAIL: desktop_test.go:160: DesktopInterfaceSuite.TestMountSpec
desktop_test.go:173:
c.Check(spec.MountEntries(), HasLen, 3)
... obtained []osutil.MountEntry = []osutil.MountEntry{osutil.MountEntry{Name:"/var/lib/snapd/hostfs/tmp/check-3094481031/3/usr/share/fonts", Dir:"/usr/share/fonts", Type:"", Options:[]string{"bind", "ro"}, DumpFrequency:0, CheckPassNumber:0}, osutil.MountEntry{Name:"/var/lib/snapd/hostfs/tmp/check-3094481031/3/usr/local/share/fonts", Dir:"/usr/local/share/fonts", Type:"", …
```

interfaces/builtin: fix distro mocking in font dirs mount spec test

---

features/features.go
features/features_test.go

This experimental feature flag is added to allow for quick testing and development of refresh-app-awareness UX improvements until it gets into a stable state.
This work should accelerate integrating and testing existing work since it will be hiding behind this feature flag and not be disruptive.
This change was suggested here https://github.com/snapcore/snapd/pull/13374#pullrequestreview-1772730702, thanks @pedronis!
for context: https://github.com/snapcore/snapd/pull/13066

features: add new feature (refresh-snap-awareness-ux)

---

HACKING.md

Add information about how to run C tests in the snap-confine section of HACKING.md

documentation: add a reference to make check target in HACKING.md

---

tests/main/postrm-purge/task.yaml

It is possible that snap services may have refused to stop or failed when purging the snapd package data, in which case such services will appear in the output like so:
snap.test-snapd-dbus-provider.system-provider.service not-found failed failed snap.test-snapd-dbus-provider.system-provider.service
Since we do not reset such service in order to allow the user to inspect their state, the test needs to account for this.

tests/main/postrm-purge: account for snap services which may have failed

---

tests/main/postrm-purge/task.yaml

If a unit not from snapd depends on a snapd units (e.g. with After=), the unit will still be listed. We have to check only "loaded" units to make sure no unit remains.

tests/main/postrm-purge: make check units more robust
