tests/regression/lp-1910456/task.yaml

https://github.com/snapcore/snapd/commit/d0023970be05279255028cbacb556b050890735b seems to have introduced a regression on Arch where we have the AppArmor userspace and kernel support, but apparently the profiles generated are not accepted by 3.1.6 parser currently present in Arch.

tests/regression/lp-1910456: temporarily disable the test on Arch

---

interfaces/builtin/u2f_devices.go
interfaces/builtin/u2f_devices_test.go

Added RSA DS100 authenticator to the whitelist. RSA Security is the vendor and the authenticator is certified by the FIDO Alliance (certificate no. FIDO20020230501001).

i/builtin: Added RSA DS100 authenticator

---

packaging/fedora/snapd.spec

This is a sync from Fedora, it was released as a part of: https://bodhi.fedoraproject.org/updates/FEDORA-2024-9699b795ca

packaging: require xdelta on Fedora and EPEL9

---

overlord/snapshotstate/backend/backend_test.go

Tweak the checks in snapshot export test to assert conditions which are required for the test to proceed.
The following failure was observed in a CI run:
```
backend_test.go:1339:
c.Assert(err, check.IsNil)
... value *errors.errorString = &errors.errorString{s:"cannot write data for 12_hello-snap_v1.33_42.zip: read /tmp/check-3525045165/10/var/lib/snapd/snapshots/12_hello-snap_v1.33_42.zip: file already closed"} ("cannot write data for 12_hello-snap_v1.33_42.zip: read /tmp/check-3525045165/10/var/lib/snapd/snapshots/12_hello-snap_v1.33_42.zip: file already closed")
```
So far I have been unable to identify the root cause so we're fishing for possible issues.

overlord/snapshotstate: tweak test checks

---

interfaces/apparmor/backend.go
interfaces/apparmor/backend_test.go
tests/regression/lp-1910456/task.yaml

https://github.com/snapcore/snapd/commit/d0023970be05279255028cbacb556b050890735b
added support for unconfined profile mode, however it is possible that in
certain scenarios snapd would produce a profile which contains both unconfined
and complain. This is rejected by the parser, as profile mode are exclusive.
I've looked at both the kernel bits in https://elixir.bootlin.com/linux/v6.7/source/security/apparmor/policy_unpack.c#L903 and apparmor parser bits in https://gitlab.com/apparmor/apparmor/-/blob/master/parser/profile.h?ref_type=heads#L60-85 and the code suggests that the profile modes enforce, complain, kill, unconfined and user (prompt), default_allow are indeed exclusive.

intefaces/apparmor: do not combine unconfined and complain profile flags

---

tests/main/interfaces-process-control/task.yaml

We are sending a SIGTERM to the test process, and so its handling and test process termination is asynchronous and there is no guarantee the test process exits immediately. Retry the check a couple of times to account for this.
The problem was often seen to happen on openSUSE:
```
Error: 2024-01-17 21:36:40 Error executing google:opensuse-tumbleweed-64:tests/main/interfaces-process-control (jan172104-345478) : -----
+ echo 'The interface is disconnected by default' The interface is disconnected by default
+ snap interfaces -i process-control
+ MATCH -- '- +process-control-consumer:process-control'
'snap interfaces' is deprecated; use 'snap connections'.
+ echo 'When the plug is connected' When the plug is connected
+ snap connect process-control-consumer:process-control
+ echo 'Then the …
```

tests/main/interfaces-process-control: retry check for process being terminated

---

overlord/devicestate/devicestate.go
overlord/devicestate/devicestate_remodel_test.go

* fail early if remodeling to an old model revision, as it cannot be added to the db
* allow offline update remodels without serial

o/devicestate: remodel policy/checks changes

---

aspects/schema.go
aspects/schema_test.go

Check that map keys (in the schema and input data) follow the expected format. We already check this for path elements specified as keys in a Set() but weren't doing the same with the actual value.

aspects: check map key format in parsing and validation

---

systemd/systemd.go
systemd/systemd_test.go

We define specific mount unit templates for kernel-modules components,
as we need to mount them before any service that loads kernel modules.
These units are of two types:
1. Units to mount the kernel-modules component containers.
2. Units that mount bits of these containers under
/usr/lib/{modules,firmware}.

systemd: add mount unit templates for kernel-modules

---

interfaces/builtin/network_control.go

LP: #2047798
we have similar permissions for /etc/resolvconf

i/builtin: allow to lock /run/netns with network-control

---

wrappers/export_test.go
wrappers/internal/export_test.go
wrappers/internal/service_status.go
wrappers/internal/service_status_test.go
wrappers/services.go
wrappers/services_test.go

Second PR that builds on top of https://github.com/snapcore/snapd/pull/13336. It implements support for querying status of user daemons using the existing `service_status.go`, and then implements restart of user-daemons on top of this.
This PR also adds the concept of `Scope` and `Users` to options for Start/Stop/RestartServices, which is used to control which services should be affected by these operations, it defaults to the current behaviour.
Next parts:
Support for scopes/user-selection in daemon API: https://github.com/snapcore/snapd/pull/13338
Support for querying user daemons in servicestate: https://github.com/snapcore/snapd/pull/13380
Support for --user/--users/--system in cli: https://github.com/snapcore/snapd/pull/13367 + https://github.com/snapcore/snapd/pull/13368 + …

wrappers: support for restarting user-daemons

---

overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_update_test.go

This was causing one of the nested spread tests to fail for my PR to swap remodeling over to use the prereq tracker.

o/snapstate: call Add on prereq tracker in the case that update is only a channel switch

---

interfaces/builtin/fwupd.go
interfaces/builtin/fwupd_test.go

Also:
interfaces/builtin/fwupd.go: allow locking for ipmi device nodes

interfaces/builtin/fwupd.go: tag missing devices

---

overlord/snapstate/policy.go
overlord/snapstate/policy/canremove_test.go
overlord/snapstate/policy/errors.go
overlord/snapstate/policy/export_test.go
overlord/snapstate/policy/os.go
overlord/snapstate/snapstate_test.go
tests/main/remove-core/task.yaml

This addresses this bug: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/2039113?comments=all
Since classic systems do not have a base set in the model, this code was assuming that we were on a UC16 system that required the "core" snap. Adding the `dev.IsCoreBoot()` check allows classic (non-hybrid) systems to remove "core", if it isn't required by other snaps.

o/s/policy: allow "core" snap to be removed on classic systems

---

aspects/schema.go
aspects/schema_test.go

Add support for defining a JSON list of alternative types (can be simple types or map-like types with constraints) that a schema should allow at that location.

aspects: support alternative types in schemas

---

aspects/aspects.go
aspects/aspects_test.go
client/aspects.go
client/aspects_test.go
client/client_test.go
cmd/snap/cmd_get.go
cmd/snap/cmd_get_test.go
cmd/snap/cmd_set.go
cmd/snap/cmd_set_test.go
daemon/api_aspects.go
daemon/api_aspects_test.go
overlord/aspectstate/aspectstate.go
overlord/aspectstate/aspectstate_test.go

Adds a CLI for getting and setting data through aspects. Doesn't include support for "unset". The first commit is a refactor that changes where the result of a get is namespaced just to make it easier to combine results at the API (it's mostly test changes).

many: add CLI support for getting and setting aspects

---

c-vendor/vendor.sh

Hi,
Now that snapd 2.61 has been branched, it's time to update squashfuse again, which will enable multithreading support by default.
Multithreading has already been tested somewhere else: https://github.com/apptainer/apptainer/issues/665#issuecomment-1249783592
Check https://github.com/snapcore/snapd/pull/13022 for more context.

packaging: update squashfuse to 0.5.0

---

features/features_test.go

Add count checks to mandatory tests in `features_test.go` to ensure we test new feature flags. https://github.com/snapcore/snapd/pull/13516#discussion_r1464829626

features: add count checks to ensure features are tested

---

tests/core/snapd-maintenance-msg/task.yaml

The core20 refresh was failing with a message that `core20` is local and unknown to the store because it's installed from a locally built revision. While trying to figure out what triggered this, I noticed the same fix was committed and then reverted at some point but I'll have to ask Sergio why once he's back. I think it's still worth merging this now to unblock PRs.

tests: fix snapd-maintenance-msg spread test

---

cmd/snap/cmd_run.go
cmd/snap/cmd_run_test.go

Recent versions of sudo (1.9.14+) changed the terminal flags when switching to the child process which broke the output of some commands which had their output piped. This was addressed in the upstream in
https://www.sudo.ws/repos/sudo/rev/faa06b1e8913 which added detection of whether a stdout is on a pipe, and thus preserved the terminal flags. In our case, when running a command under strace, we expect strace logs on stderr hence fd 2 is a pipe which isn't picked up by sudo auto detection, thus terminal flags are not being preserved and the output is garbled like so:
```
[pid 838721] execve("/snap/hello-world/29/bin/echo", ["/snap/"...], ["DBUS_S"..., "DEBUGI"..., "DISPLA"..., "EDITOR"..., "HG=/us"..., "HOME=/"..., "INVOCA"..., "JOURNA"..., "KWIN_T"..., "LANG=e"..., "LC_MES"..., …
```

cmd/snap: proxy stdout when running app under strace

---

daemon/api_model.go
daemon/api_model_test.go
daemon/export_api_model_test.go
overlord/devicestate/devicestate.go
overlord/devicestate/devicestate_remodel_test.go
overlord/devicestate/handlers_remodel.go
overlord/managers_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstatetest/snapstate.go
snap/errors.go
snap/errors_test.go

This flag will enable offline remodeling, even when all snaps required for the remodel are not provided locally. The remodel will fall back to using already installed snaps in situations that it can. This includes simple channel switches, and when the required revision of a snap is already installed. If a snap is required for the remodel, and the snap is neither provided locally or already installed, then the remodel will fail.

o/devicestate, overlord, daemon: add flag to devicestate.Remodel to force an offline remodel

---

osutil/cp.go
seed/seed.go
seed/seed20.go
seed/seed20_test.go

This PR adds a `Copier` interface that seeds can implement to copy themselves to a given seed partition. Additionally, an implementation for seed20 is done here. This will be used as a part of installing seeds during UC installation via the snapd API.

seed: implement Copier for seed20

---

sandbox/cgroup/export_test.go
sandbox/cgroup/monitor.go
sandbox/cgroup/monitor_test.go

This is an bunch of fixes and refactors for the cgroup monitoring code. The main issue addressed is with tracked path removal. We have previously added references to the leaf paths internally, but the actual watch was established using the parent path, for which the reference was never updated. As a result if all leaf paths were gone, we did not clean up the watch on the parent path.
While at it, change the structure internally to use a hash map in the group to watch to simplify bookkeeping.
Next, added support for the context and a way to cleanup and close the watcher in a reasonable manner. 
A bunch of improvements to the tests, so that we are no longer guessing and sleeping hoping to observe the right events. Instead provide an observer which the tests can hook to and inspect the state …

sandbox/cgroup: refactor and cleanup, fix path tracking and watch removal

---

cmd/snap/cmd_get.go
cmd/snap/cmd_set.go
cmd/snap/cmd_set_test.go
cmd/snap/cmd_unset.go
cmd/snap/cmd_unset_test.go

Add support for unsetting aspects in the `snap set` command.

cmd/snap: add CLI support for unsetting aspects

---

gadget/update_test.go

Add a unit test which checks the update with default policy and with a volume structure without any prior edition.
A question came up in the forum https://forum.snapcraft.io/t/updating-config-txt-for-device-tree-overlays-in-gadget-snap/33793/11?u=mborzecki1 and while double checking I noticed that we did not have an explicit unit test for this.

gadget: add unit test for default policy and no previous edition

---

sandbox/apparmor/notify/listener/listener_test.go

These should have been uint16 types, rather than uint32. This was causing failures on architectures that use big endian byte ordering

s/a/n/listener: correct size of Class and Op in msgNotificationFile to match fields in msgNotificationOpKernel

---

client/model.go
client/model_test.go
cmd/snap/cmd_remodel.go
cmd/snap/cmd_remodel_test.go
daemon/api_model.go
daemon/api_model_test.go
tests/nested/manual/remodel-offline/task.yaml

These changes expose the changes made in #13494 in the snapd API and CLI. An `--offline` flag is introduced to the CLI, and an `offline` boolean field is added to the snapd JSON API.

client, cmd/snap, daemon: api level changes for introducing offline flag to remodel

---

interfaces/builtin/polkit.go
interfaces/builtin/polkit_test.go

Discovered during fix of the polkit interface issue which we are trying to fix for core22 and core24 bases. The polkit daemon resides in different places in core22 base and core24 base.
The many-core interface tests will fail for core22 and core24 (core22 already failing) as snapd tries to write policy files into a read-only path in /usr/share/polkit-1/actions.

i/builtin/polkit: support different polkitd path on core24

---

overlord/snapstate/backend/link.go
overlord/snapstate/backend/link_test.go
overlord/snapstate/backend_test.go
overlord/snapstate/handlers.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go

This PR acts as the glue for all previous building blocks. It allows skipping binaries removal during refresh for the refresh-app-awareness UX flow.
- `LinkContext.SkipBinaries` is added to allow `unlink-current-snap` task to skip removing the snap's binaries when RAA is enabled when snap run is inhibited
For context: https://github.com/snapcore/snapd/pull/13066

many: skip binaries removal during refresh for RAA UX flow

---

overlord/snapstate/handlers.go
overlord/snapstate/handlers_aliasesv2_test.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go

This PR is a building block towards refresh app awareness UX improvements. It allows skipping aliases removal during refresh for the refresh-app-awareness UX flow. This is similar to what is done to binaries https://github.com/snapcore/snapd/pull/13374 but for aliases.
For context: https://github.com/snapcore/snapd/pull/13066

o/snapstate: skip aliases removal during refresh for RAA UX flow

---

cmd/snap/cmd_run.go
cmd/snap/cmd_run_test.go
cmd/snap/export_test.go
cmd/snap/inhibit.go
cmd/snaplock/runinhibit/export_test.go
cmd/snaplock/runinhibit/inhibit.go
cmd/snaplock/runinhibit/inhibit_test.go

This work extracts inhibition notification flows into separate structs to avoid entanglement with current inhibition waiting logic.
This PR is a building block for https://github.com/snapcore/snapd/pull/13411 in an attempt to split it into smaller chunks.
This will be later used in "snap run" to make it aware of inhibited snaps.

cmd/snap/inhibit.go: refactor inhibit notification flows

---

overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go

`Test*SkipBinaries` unit tests were failing due to #13449 because aliases removal is also skipped when
`refresh-app-awareness-ux` flag is enabled which affect `Test*SkipBinaries` unit tests backend operations list because it also depends on `refresh-app-awareness-ux` flag being enabled.
This was not caught in the PRs #13449 and #13374 themselves because they were tested against master and not with each other.

o/snapstate: fix `Test*SkipBinaries` unit tests

---

aspects/aspects.go
aspects/aspects_test.go
aspects/schema.go
aspects/schema_test.go
aspects/transaction_test.go

Add a TypeAtPath function to the schema interface that returns the schema types that can be stored at that path. Then use that for a pre-write check that compares the allowed types at the storage paths of matching rules. If the paths require different types, fail early. TypeAtPath could also be used in the future to validate that the aspect-bundle assertion and its schema make sense (i.e., no writable path defines constraint that can't be met).

aspects: pre-check writes for schema mismatches

---

kernel/export_test.go
kernel/kernel_drivers.go
kernel/kernel_drivers_test.go

Add ancillary methods:
- KernelVersionFromPlaceInfo, to find the kernel version ("uname -r") for a mounted snap.
- BuildKernelDriversTree, to build a tree from a mounted snap that can be bind-mounted to /usr/lib/{modules,firmware}.
These methods are needed to support kernel-modules components.

kernel: add ancillary methods

---

overlord/snapstate/snapstate_install_test.go

The test-only type behindYourBackStore method SnapAction assigned to coreInstallRequested through a non-pointer method, making the assignment ineffectual as soon as the method returns, as the code operates on a copy of the caller.

o/snapstate: fix assignment through non-pointer method

---

cmd/snap-bootstrap/cmd_initramfs_mounts.go
cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
tests/nested/manual/uc20-install-in-initrd/task.yaml

Single boot install appears to work, without modifications, for systems that do and don't have a FDE setup hook, and for systems that do and don't support secure boot.

c/snap-bootstrap: lift requirement of fde-setup hook for single-boot install

---

interfaces/builtin/steam_support.go

This allows for reading of `/sys/module/nvidia/version` and `/etc/debian_chroot` for the Steam Snap.
In order to properly determine the NVIDIA driver version, Steam needs to be able to read `/sys/module/nvidia/version`. This is a requirement for https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/merge_requests/652. This also would allow us to simplify the [Steam Snap NVIDIA dialog](https://github.com/canonical/steam-snap/blob/main/src/nvidia32) by making the driver version easier to obtain.
`/etc/debian_chroot` is needed to be able to determine container versions from inside Steam [Pressure Vessel](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/tree/main/pressure-vessel) containers, which makes debugging easier.
Additional context: …

steam_support: allow reading of nvidia version and debian_chroot

---

tests/main/aspects/task.yaml

Update the aspects spread test to use the new snap get/set interface instead of using the API directly.

tests: use snap get/set CLI in aspects test

---

packaging/fedora/snapd.spec
tests/lib/prepare-restore.sh

Sync downstream packaging from Fedora/EPEL and Amazon Linux.
Our AL2023 images come with xdelta installed from EPEL, but xdelta isn't available in Amazon's own repositories, so drop it to ensure vanilla Amazon Linux 2023 experience.

packaging/fedora, tests/lib/p-r: sync from downstream, drop xdelta on Amazon Linux 2023

---

overlord/servicestate/quota_control_test.go
overlord/snapstate/aliasesv2.go
overlord/snapstate/backend/link_test.go
overlord/snapstate/backend/locking_test.go
overlord/snapstate/conflict.go
overlord/snapstate/handlers.go
overlord/snapstate/progress_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go

Random collection of typos from today and yesterday, as I was browsing through snapstate. Bulk of changes are in comments but a few affect non-test methods or tested messages.

o/snapstate: assorted typos

---

interfaces/builtin/u2f_devices.go

My Idem Key with nfc and usb-c has the ProductIDPattern given in PR. I assume the ID Pattern 3201 is the pattern of the usb-a Version.
lsusb output is
```
Bus 001 Device 010: ID 32a3:3203 GoTrust Idem Key 1C
```
Please add.

interfaces/builtin: Add ProductIDPattern of GoTrust Idem Key with NFC and usb-c

---

osutil/export_test.go
osutil/user.go
osutil/user_test.go

`adduser` is perl based tool. Moving to `useradd` removes this dependency.
To maintain backwards compatibility as much as possible, prefer use of `adduser` if available and only then defer to `useradd`.
Older versions of `useradd` do not support `--badnames` option, so it is not safe to default to `useradd`.
This strategy will not affect UC22-, but will allow to have UC24+ without `adduser`, and therefore remove Perl dependency there.

osutil: move to useradd from adduser

---

data/systemd/snapd.apparmor.service.in

In case of re-execution, snapd snap has to be mounted. apparmor.service has a dependency to local-fs.target which is enough in theory. But in case this dependency dispappears, it is better to have an explicit dependency to snapd.mount.target in the unit.

snapd.apparmor.service: add explicit dependency to snapd.mounts.target

---

data/selinux/snappy.te

I had not updated the selinux profile to include the new polkitd path. So this is needed to fix the AVC denial
```
Error: 2024-02-07 06:48:20 Error executing google:fedora-38-64:tests/main/selinux-classic-confinement (feb070555-725780) : 
-----
+ snap install --dangerous --classic test-snapd-classic-service-hooks_1.0_all.snap
test-snapd-classic-service-hooks 1.0 installed
+ ausearch -i --checkpoint stamp --start checkpoint -m AVC
+ MATCH 'no matches'
----
type=AVC msg=audit(02/07/24 06:48:18.930:22938) : avc:  denied  { getattr } for  pid=113984 comm=snap path=/usr/lib/polkit-1/polkitd dev="sda5" ino=113733 scontext=system_u:system_r:snappy_cli_t:s0 tcontext=system_u:object_r:policykit_exec_t:s0 tclass=file permissive=1
-----
```

data/selinux: add missing polkitd permission for snappy_t/snappy_cli_t

---

interfaces/apparmor/template.go

Rebuilding snap-update-ns with Go 1.22.0 triggers a new denial with the process trying to read /proc/self/maps.
The denial shows up as:
```
audit: type=1400 audit(1707404561.548:1563): apparmor="DENIED"
operation="open" class="file"
profile="snap-update-ns.test-snapd-sh-core22"
name="/proc/2993630/maps" pid=2993630 comm="5"
requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```
Inspecting with strace, the attempt to open /proc/self/maps happens just a handful of syscalls after execing into snap-update-ns.

interfaces/apparmor: update apparmor template of s-u-n for changes in Go

---

aspects/aspects.go
aspects/aspects_test.go
asserts/aspect_bundle_test.go
overlord/aspectstate/aspecttest/mock_aspect.go

This PR makes each aspect a map with a mandatory list of rules under the "rules" key instead of just a list of rules. This allows us to add new fields later (like the "summary", which will come after). The 2nd commit adds some new test cases to improve coverage that was missing after the changes to prepare for the schema. The 3rd commit makes the terminology more consistent so we only use "rules" when referring to them and not "access patterns" as we sometimes did.

aspects: make aspect a map with a list of rules

---

.github/workflows/cla-check.yaml

Enable running the action in the context of the base repository, see: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target so that write permissions are set and comments can be posted to the PR.
Also see https://github.com/canonical/has-signed-canonical-cla?tab=readme-ov-file#has-signed-canonical-cla

github/workflows/cla-check: enable comments by running in the context of the base repository

---

.github/workflows/test.yaml
spread.yaml

This is needed to avoid quota issues
Until google define if we can move our compute quota to 1000, this is a workaround to avoid quota issues.

tests: split google backend in 2 zones

---

data/systemd/snapd.seeded.service.in

snapd.service should not need to be started from snapd.seed.service to start. Only snapd.socket needs to be started.

data/systemd: make snapd.seed wait for snapd.socket only

---

overlord/managers_test.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_link_test.go

It has been observed that if during unlink systemd returns an error (customers has observed that daemon-reload timed-out during unlink), and "unlink-current-snap" fails, then systemd services are not correctly restored. This implements some error handling for this specific case.

overlord: restore services if the unlink fails

---

interfaces/builtin/u2f_devices.go
interfaces/builtin/u2f_devices_test.go

Adding  Kensington VeriMark Guard Fingerprint Key to be used by Firefox, tested on Ubuntu 22.04

interfaces/builtin: Add Kensington VeriMark Guard Fingerprint Key

---

snap/naming/core_version.go
snap/naming/core_version_test.go

This is essential to enable preseeding for core desktop, as preseeding is gated based on the base snap version.

snap:  parse correctly base snap version for core desktop

---

.github/workflows/test.yaml
spread.yaml
tests/lib/pkgdb.sh
tests/lib/prepare-restore.sh
tests/main/completion/task.yaml
tests/main/interfaces-polkit/task.yaml

To be as close to the vanilla images as possible we no longer have a preinstalled xdelta in the Amazon Linux 2023 images. As such using xdelta to pack the project content will fail.

spread, github: disable xdelta for Amazon Linux 2023

---

cmd/snap-confine/mount-support-nvidia.c

This lib is needed for onnxruntime with CUDA support to work (nvidia-cudnn 8.9.2.26~cuda12+1).

cmd/snap-confine: add libcudnn.so to list of NVIDIA libraries

---

cmd/snapd-generator/main.c

Create mount units for /lib/{modules,firmware} that are run before kernel modules get loaded. The directories mounted have been built on kernel/components installation in
/var/lib/snapd/kernel/<snap_name>/<revision>. This is done only for UC or hybrid systems, which must have a snap kernel installed.
To find out which kernel snap is currently active, the snap file backing /run/mnt/kernel is found and the snap name and revision is extracted from it.

cmd/snapd-generator: create mount points for kernel drivers tree

---

dirs/dirs.go
interfaces/builtin/opengl.go
interfaces/builtin/opengl_test.go
tests/main/interfaces-opengl-nvidia/task.yaml

This allows access to `/usr/share/nvidia` in the `opengl` plug. Nvidia apparently requests this be available in containers as per discussion in #12794

opengl: add /usr/share/nvidia

---

tests/nested/manual/remodel-offline/task.yaml

Wait for the kernel change to be fully done before proceeding, otherwise we can have a race condition and remodel will fail with message:
error: cannot do offline remodel: cannot remodel device: snap "pc-kernel" has "refresh-snap" change in progress

tests/nested/manual/remodel-offline: wait for kernel refresh change

---

daemon/api_sideload_n_try.go
daemon/api_sideload_n_try_test.go
daemon/api_snaps.go
daemon/api_snaps_test.go

This information is needed to allow api clients to associate single-snap changes with the relevant snap as mentioned in [RAA-UX spec](https://docs.google.com/document/d/1HJQWKzgaB3yPKwRUqlxYhgyaKG5IcJe8eZOT4YY1CI8/edit#heading=h.c40tauj2e3fo).
This field is already present in multi-snap changes.
NOTE: I am bit hesitant between `snap-names` and `snap-name`. It seems that the `snap-name` convention is used for side-loading a single snap or trying a single snap, everywhere else `snap-names` is used. I am open to suggestions and discussions.

daemon: add `snap-names` data field to single-snap changes

---

cmd/snap-recovery-chooser/main.go
cmd/snap-recovery-chooser/main_test.go

Add support for running console-conf from a snap.

cmd/snap-recovery-chooser: support console-conf from a snap

---

overlord/devicestate/devicestate.go
overlord/devicestate/devicestate_remodel_test.go
overlord/managers_test.go
overlord/snapstate/snapstatetest/snapstate.go
tests/nested/manual/remodel-offline/task.yaml

This PR enables offline remodeling to look back at recently installed revisions of snaps, and will use one of those if any fulfill the revision requirements of the remodel.

o/devicestate: check for previously installed revisions when falling back to installed snaps during offline remodel

---

.github/workflows/test.yaml

We suspect that the current definition of workflow triggers, will trigger a a
full tests workflow on master whenever 'Pull Request Labeler' completes
successfully. The labeler workflow remains in place and will still run on each
PR.

github: temporarily disable pull request labeler trigger for main workflow

---

data/preseed.json
overlord/devicestate/devicestate_remodel_test.go
overlord/devicestate/handlers.go
overlord/managers_test.go
overlord/snapstate/backend.go
overlord/snapstate/backend/setup.go
overlord/snapstate/backend/setup_test.go
overlord/snapstate/backend_test.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_setup_kernel_test.go
overlord/snapstate/policy.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_test.go
snap/types.go
systemd/emulation.go
systemd/systemd_test.go
tests/main/preseed-core20/task.yaml

On kernel snap installation, a drivers tree is now created so it can
be mounted on early boot stages. This is needed to support
kernel-modules components.

many: add handlers and backend methods to {set,clean}-up kernel snaps

---

overlord/snapstate/backend_test.go
overlord/snapstate/conflict.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go

This pull request contains a number of patches that should be dropped, followed by a currently-failing test that reproduces the scenario from https://warthogs.atlassian.net/browse/SNAPDENG-13768
As debugged by Ernest and Samuele earlier, the debug output of the test shows (in messages prefixed with `@@@`) that a conflict is detected and then subsequently ignored.
This branch serves as a playground for fixing the problem.

overlord: fix prerequisite base snap silently not being installed due to conflict

---

packaging/ubuntu-16.04/rules
packaging/ubuntu-16.04/snapd.install.in

On a usr-merge system, systemd there is no `/lib/systemd`, it is all in `/usr/lib/systemd`.

packaging/ubuntu-16.04: install systemd files in correct place on 24.04

---

interfaces/builtin/upower_observe.go

Refresh is commonly used by applications like steam and others to get accurate
power usage information. Whilst calling this has a side-effect of causing the
daemon to refresh its data from the power source, this seems pretty innocuous
and so should just be added to the existing upower-observe interface rather than
creating a new interface such as upower-control or similar just to allow this
one method.

interface/upower-observe: allow to Refresh statistics for devices

---

interfaces/builtin/export_test.go
interfaces/builtin/polkit.go
interfaces/builtin/polkit_test.go
osutil/mountprofile_darwin.go

This should fix the interface tests that were failing due to polkit interface.
We check the mountpoints to ensure that the policy-path (/usr/share/polkit-1/actions) is indeed mounted in a read-write filesystems. On core-desktop this path is read-write, but on core systems this path is read-only.

i/b: dont have polkit interface being implicit on core read-only filesystems

---

asserts/system_user.go

Followup for one of the comments made by @pedronis in https://github.com/snapcore/snapd/pull/13236.
Since '+' is not allowed by adduser anyway (even with --force-badnames), there is no reason for us to allow it in our regexes. So we drop '+' from the regex here as well.

asserts: update username regex allowed by system-user assertion

---

overlord/snapstate/autorefresh.go
overlord/snapstate/autorefresh_test.go

It is possible that refresh.hold has been set to "forever" even before snapd ran for the first time.
Reference: https://bugs.launchpad.net/bugs/2051917

o/snapstate/autorefresh: do not expect a valid time string in refresh.hold

---

tests/main/interfaces-custom-device-app-slot/task.yaml

Install core snap to avoid installing it using the fake store
Fake store produces a problem when snapd tries to install core snap in uc18+
error: 
taskrunner.go:299: [change 9 "Ensure prerequisites for \"device-app\" are available" task] failed: cannot install snap base "core": unexpectedly empty response from the server (try again later)

tests: fix iterfaces-custom-device-app-slot test by installing core snap maually

---

interfaces/builtin/mount_observe.go

Fix for https://bugs.launchpad.net/snapd/+bug/2053271.
Processes are observed to read the info from /proc/thread-self/mountinfo instead, which resolves to /proc/$pid/task/$task/mountinfo, 
(example, taken from LP bug: https://github.com/moby/sys/blob/mountinfo/v0.7.1/mountinfo/mountinfo_linux.go#L139-L174)
I've taken the liberty to add both /mounts and /mountinfo as that seems in line with the interface.

i/builtin: add alternative mounts/mountinfo for mount-observe

---

client/clientutil/snapinfo_test.go
client/packages.go
client/packages_test.go
daemon/api_snaps.go
daemon/api_snaps_test.go
daemon/snap.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate_test.go

This field is needed to allow api clients to know the time remaining until a refresh is forced for a running snap in the next auto-refresh as mentioned in [RAA-UX spec SD167](https://docs.google.com/document/d/1HJQWKzgaB3yPKwRUqlxYhgyaKG5IcJe8eZOT4YY1CI8/edit#heading=h.c40tauj2e3fo).

many: add `refresh-inhibit-proceed-time` field to snaps api

---

interfaces/builtin/libvirt.go

virt-viewer requires read/write access to /run/libvirt/libvirt-sock-ro  to work properly. This PR adds the required rule to libvirt interface.

interfaces/builtin/libvirt: add /run/libvirt/libvirt-sock-ro

---

overlord/snapstate/snapstate.go

To more precisely explain the roles of link-snap and auto-connect for essential snaps, and why modifications around those must be a bit more cautious.

o/snapstate: add some docs around link-snap and auto-connect.

---

packaging/fedora/snapd.spec

As of the date of this commit, the policy on RHEL 9 contains the relevant bits to enable rules for bpf.

packaging/fedora: enable bpf selinux SELinux policy for RHEL9

---

interfaces/builtin/ros_opt_data.go
interfaces/builtin/ros_opt_data_test.go
interfaces/policy/basedeclaration_test.go
tests/lib/snaps/test-snapd-policy-app-consumer/meta/snap.yaml
tests/main/interfaces-ros-opt-data/task.yaml
tests/main/interfaces-ros-opt-data/test-snapd-sh/bin/sh
tests/main/interfaces-ros-opt-data/test-snapd-sh/meta/snap.yaml

This PR adds a new "ros" interface that allows snaps to access the host "/opt/ros" paths. This allows ros snaps to access to shared configuration and similar data.

interfaces: new "ros" host file system support

---

systemd/systemdtest/systemdtest.go
wrappers/services_test.go

Fix the test to not use a mocked systemctl command so that we can get more reliable execution even when running in a slow environment. The issue is that parts of the 'stop' chain run in a goroutine, so the order of `systemctl show` and `systemctl stop` calls isn't guaranteed. No top of this, since this can run in parallel now, the code would need to use `testutilg.MockLockedCommand` to prevent corruption of the call log.
Fixes the following issue seen in unit tests or OBS builds:
```
FAIL: services_test.go:3371: servicesTestSuite.TestStartServicesStopsServicesIncludingActivation
using shellcheck: "/usr/bin/shellcheck"
services_test.go:3433:
c.Check(r.Calls(), DeepEquals, [][]string{
// Enable phase for the service …
```

wrappers: fix unreliable tests to not use mocked systemctl command

---

interfaces/builtin/ros_opt_data_test.go

After merging https://github.com/snapcore/snapd/pull/13281 the unit tests seems to fail due to a conflict between that and https://github.com/snapcore/snapd/pull/13574 (since the former was not rebased after 13574 landed)

i/builtin: fix newly introduced unit tests after change to Specifications

---

tests/main/i18n/task.yaml

this is to avoid panic caused by error in the translations.

tests: skip my lang in i18n spread test

---

overlord/managers_test.go
overlord/snapstate/export_test.go
overlord/snapstate/refreshhints.go
overlord/snapstate/refreshhints_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_update_test.go

Fix handling of refresh-candidates, such that a re-refresh handler does not blindly overwrite its contents and thus discarding all the information about snaps being monitored for the purpose of RAA.

o/snapstate: fix RAA refresh triggering when app gets closed

---

daemon/api_apps.go
daemon/api_apps_test.go
daemon/api_base_test.go
daemon/export_api_apps_test.go
daemon/export_test.go
overlord/hookstate/ctlcmd/export_test.go
overlord/hookstate/ctlcmd/helpers.go
overlord/hookstate/ctlcmd/services_test.go
overlord/servicestate/service_control.go
overlord/servicestate/service_control_test.go
overlord/servicestate/servicestate.go
overlord/servicestate/servicestate_test.go
wrappers/services.go

Implements support for scopes and users in the API for service control.
Next parts:
Support for querying user daemons in servicestate: https://github.com/snapcore/snapd/pull/13380
Support for --user/--users/--system in cli: https://github.com/snapcore/snapd/pull/13367 + https://github.com/snapcore/snapd/pull/13368 + https://github.com/snapcore/snapd/pull/13381

daemon,o/servicestate: support for scopes and users in API for services

---

interfaces/builtin/desktop.go
interfaces/policy/basedeclaration_test.go

originally desktop was simply allow auto-connect, making the change to not auto-connect on UC is not that relevant because ultimately there will need to be a snap providing it and that snap will set policy if allowed from its snap-declaration
instead let auto-connection only happen with an implicit slot

interfaces: we actually expect snaps to auto-connect to desktop

---

overlord/managers_test.go

Fix a race in refresh monitoring tests, where the snap-app-presence monitoring code could call EnsureBefore(0) before the overlord Loop() was fully running.

overlord: fix race in refresh monitoring tests

---

interfaces/apparmor/template.go

This PR adds read access to /etc/default/keyboard to apparmor tempplate per suggestion of @alexmurray in https://forum.snapcraft.io/t/auto-connect-and-alias-request-for-uncomplicated-vm-tools/39029

interfaces/apparmor/template: add read access to /etc/default/keyboard

---

overlord/assertstate/validation_set_tracking.go
overlord/assertstate/validation_set_tracking_test.go
overlord/devicestate/devicestate.go
overlord/devicestate/devicestate_systems_test.go

I forgot to consider the current model's validation sets in the first PR. This change makes creating a recovery system respect the validation sets in the current model. The main effect of this change is that you cannot create recovery systems with validation sets that conflict with the validation sets of the current model.

o/devicestate: consider the current model's validation sets when creating a recovery system

---

daemon/api_apps.go
daemon/api_apps_test.go

As a part of the user-daemons support for services:
I want to allow polkit for the /v2/apps endpoint to allow non-root users to access the service API by interacting with polkit. This also enabled me to test non-root functionality in spread by using polkit policies. (See usage here: https://github.com/snapcore/snapd/pull/13368/files#diff-2521ae83c7dfc63ca503b0ea7c20fbf3ae285aaabfa8168355f15aa1f6ac4d53)
This of course may have other implications, and I want to get feedback on enabling polkit access to /v2/apps for "io.snapcraft.snapd.manage" scope.

daemon: allow polkit "io.snapcraft.snapd.manage" for /v2/apps endpoint

---

interfaces/builtin/polkit.go
interfaces/builtin/polkit_test.go

I was taking the address of the local variable in the for-loop, causing the mnt entry to point to the last inserted entry every time. This caused unstable results when running it live.

i/builtin: fix issue with for loop variable reference

---

daemon/api_notices.go
daemon/api_notices_test.go

Per discussions with @niemeyer, @pedronis, and @benhoyt, we have decided to rename the `select=all` query parameter for notices. The word "select" should be used when selecting a particular subset of items from a complete set, but in the case of notices, it was being used to extend the original set of notices to include those from all other users.
It has been proposed to rename `select=all` to `users=all`, and since `select=all` and `user-id=1234` were mutually exclusive, it makes sense that a client may choose to use *either* `user-id=1234` or `users=all`, as these are more clearly related.
These changes will need to be backported to pebble, and when doing so, it is important to also change the command-line argument `--select=all` to be `--users=all`, and check for any other uses of the …

daemon: replace notices "select" param with "users"

---

aspects/aspects.go
aspects/aspects_test.go
aspects/schema.go
aspects/schema_test.go
cmd/snap/cmd_get_test.go
daemon/api_aspects.go
daemon/api_aspects_test.go
daemon/export_test.go
overlord/aspectstate/aspectstate.go
overlord/aspectstate/aspectstate_test.go

Matches an empty request with the entire aspects i.e., all of the aspect's read rules. The first commit is a small fix to the schema mismatch check for "any" schema to permit longer paths (since "any" can also be a container type).

aspects: empty Get request returns entire aspect

---

aspects/aspects.go
aspects/aspects_test.go
overlord/aspectstate/aspectstate_test.go
overlord/assertstate/assertstate_test.go

Previously the path type mismatch check was done on Set, this PR moves the check to the aspect creation so this is done as early as possible. This check ensures that the assertion doesn't declare requests that can't be satisfied by some data type, per the schema. In the future, we'll have to include request prefixes in this check (since we can get/set those as well) considering that path prefixes are implicitly Map/Array types. However, since we requests still don't support index placeholders it makes sense to do this later.

aspects: check path type mismatch when creating aspect

---

overlord/snapstate/snapstate_test.go
overlord/state/change.go
overlord/state/change_test.go
overlord/state/state.go

This PR adds trigger points to the `change-update` notice based on the [JU048](https://docs.google.com/document/d/16PJ85fefalQd7JbWSxkRWn0Ye-Hs8S1yE99eW7pk8fA/edit) spec.
- `NewChange` trigger point is to address the `change spawned` case.
- `notifyStatusChange` is for all other status changes.
~~**Note:** Change status alternates rapidly between `Do` and `Doing` statuses because it gets computed based on an aggregation of its tasks' statuses which might cause the listener to hit the `/v2/changes` a lot hence putting pressure on snapd, no?~~
~~There are no test currently, I will add unit and spread tests as soon we align on the notice trigger points.~~

o/state: record change-update notices on change status updates

---

cmd/libsnap-confine-private/infofile-test.c
cmd/libsnap-confine-private/infofile.c
cmd/libsnap-confine-private/infofile.h

Add support for comments spanning the whole line.

cmd/libsnap-confine-private/infofile: support for comments

---

overlord/devicestate/devicestate.go
overlord/devicestate/devicestate_systems_test.go

Snaps that are optional in the model should only be a part of the recovery system if they are required by one of the validation sets, or if they are already installed on the system.

o/devicestate: skip optional snaps in model when creating recovery system

---

interfaces/udev/backend.go
interfaces/udev/backend_test.go

Add device-cgroup-v2 sandbox feature flag which was forgotten when we landed cgroup v2 device filtering support.

interfaces/backend: update sandbox features to account for cgroup v2 device filtering

---

overlord/configstate/configcore/picfg.go

Replacement for external PR: https://github.com/snapcore/snapd/pull/12455/commits.

overlord/configstate/configcore: add support rpi config sdtv_mode option

---

client/clientutil/snapinfo_test.go
client/packages.go
client/packages_test.go
daemon/api_apps.go
daemon/api_snaps.go
daemon/api_snaps_test.go
daemon/snap.go
overlord/snapstate/autorefresh.go
overlord/snapstate/handlers.go
overlord/snapstate/refreshhints.go

This select query allows only showing snaps whose refresh is inhibited which is needed by refresh-app-awareness ux clients as mentioned in the [RAA-UX spec SD167](https://docs.google.com/document/d/1HJQWKzgaB3yPKwRUqlxYhgyaKG5IcJe8eZOT4YY1CI8/edit#heading=h.c40tauj2e3fo).

daemon: add "refresh-inhibited" select query to /v2/snaps

---

overlord/snapstate/component_install_test.go
snap/component.go
snap/hooktypes.go
snap/info.go
snap/info_snap_yaml.go
snap/info_snap_yaml_test.go
snap/types.go
snap/validate.go
snap/validate_test.go

Adds fields to types in `snap` package pertaining to component hooks.

snap: add hooks to snap component types

---

interfaces/builtin/steam_support.go
interfaces/builtin/steam_support_test.go

This is a commit we've had in the Core Desktop snapd tree for a while that had not been proposed upstream.
We would like to be able to run the Steam snap on Core Desktop. We've got everything else working, so providing an implicit `steam-support` slot on core was the last piece of the puzzle. Everything else is similar enough not to be a problem.
Currently there are no Spread tests for steam-support, so there's nothing obvious to update on that side.

interfaces: make steam-support implicit on core

---

.github/workflows/test.yaml

Mention clang-format and indent 2.2.13+ in the error message.

github: mention C source code formatting tools we expect

---

interfaces/builtin/network_setup_control.go
interfaces/builtin/network_setup_observe.go

Starting from systemd 254, busctl will attempt to bind the socket to a known path to facilitate debugging. The change was introduced in https://github.com/systemd/systemd/commit/a0cb33581630a54c89d088d36eb3bf6cf7459cd7 and the path is composed of `@<hex-encoded-u64>/bus/<command>/<description>`.
Actual denial:
```
Feb 29 08:22:04 localhost kernel: audit: type=1400 audit(1709194924.547:213):
apparmor="DENIED" operation="bind" class="net" profile="snap.console-conf.console-conf"
pid=4504 comm="busctl" family="unix" sock_type="stream" protocol=0
requested_mask="bind" denied_mask="bind" addr="@f46ecfc1c63ae80f/bus/busctl/busctl"
```

interfaces/builtin/network_setup_control: allow busctl to bind

---

overlord/snapstate/handlers.go
overlord/snapstate/snapstate_update_test.go

This change records a notice when a snap refresh is forced due to inhibition timeout as mentioned in the [RAA-UX spec SD167](https://docs.google.com/document/d/1HJQWKzgaB3yPKwRUqlxYhgyaKG5IcJe8eZOT4YY1CI8/edit#heading=h.c40tauj2e3fo).

o/snapstate: record `change-update` notice on forced refresh

---

tests/lib/assertions/test-snapd-core22-required-vset.assert

This fixes test failure in release 2.61 branch

tests/lib/assertions: add missing assertion that was preventing nested/manual/remodel-offline from running

---

daemon/api_notices_test.go
overlord/snapstate/aliasesv2_test.go
overlord/snapstate/autorefresh.go
overlord/snapstate/autorefresh_gating_test.go
overlord/snapstate/autorefresh_test.go
overlord/snapstate/export_test.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_remove_test.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_try_test.go
overlord/snapstate/snapstate_update_test.go
overlord/state/notices.go
overlord/state/notices_test.go

This PR adds `refresh-inhibit` notice which is needed for RAA UX flow as mentioned in [RAA-UX spec SD167](https://docs.google.com/document/d/1HJQWKzgaB3yPKwRUqlxYhgyaKG5IcJe8eZOT4YY1CI8/edit#heading=h.c40tauj2e3fo).
Once https://github.com/snapcore/snapd/pull/13576 is merged, more complex state-based decisions can be made, like only sending when the list of inhibited snaps changes.
This commit https://github.com/snapcore/snapd/commit/1e6dec8ec6e77e84be453d85c9e05dbc308965d7 can be split into a different PR if needed.

many: add `refresh-inhibit` notice

---

build-aux/snap/snapcraft.yaml

It seems that squashfs-tools is pulling in libzstd1 from the host when executing snap pack, and that causes an mismatch with libc that is bundled in snapd. So bundle in libzstd to avoid using the host library.
```
Pack command: ['snap', 'pack', '--filename', 'core24_20240229_riscv64.snap', '--compression', 'xz', PosixPath('/home/ubuntu/core-base/prime'), PosixPath('/home/ubuntu/core-base')]    
2024-02-29 11:30:35.888 Command '['snap', 'pack', '--filename', 'core24_20240229_riscv64.snap', '--compression', 'xz', PosixPath('/home/ubuntu/core-base/prime'), PosixPath('/home/ubuntu/core-base')]' returned non-zero exit status 20.                                                                              
2024-02-29 11:30:35.891 Detailed information: error: cannot pack …
```

build-aux: add libzstd to snapd snap for snap pack

---

aspects/aspects.go
aspects/aspects_test.go
aspects/schema.go
aspects/schema_test.go

This addresses some feedback we got while demoing this by renaming the user-defined types to aliases. I've also changed this in the spec.

aspects: rename user-defined types to aliases

---

overlord/devicestate/handlers.go

Remove an unused method that is making golangci fail on master.

o/devicestate: remove unused method

---

cmd/snap-confine/snap-confine.c
cmd/snap-confine/udev-support.c
cmd/snap-confine/udev-support.h
tests/main/security-device-cgroups-required-or-optional/task.yaml

When no devices are tagged for the given snap, snap-confine will not put the current process under a device cgroup. This may lead to the snap having access to more devices than allowed by its connected interfaces. Example case when this happens is input devices, where AppArmor is not expressive enough and selective access is implemented using a device cgroup. On top of this, abusing system-files may accidentally allow a process to access a given device without additional mediation through device cgroup.
Moving forward we will set up device access mediation through cgroups for snaps always, unless the snap is using one of the well-known bases where the old behavior will be preserved for the sake of staying backwards compatible. Right now, snaps using bases:
- core, core16, core18, core20, …

cmd/snap-confine: always set up the device cgroup unless using one of the old bases

---

cmd/snap-confine/mount-support.c
tests/regression/exploding-namespace/task.yaml

The combination of snap set system homedirs=/var/lib/ and a snap that causes a mimic to be created over /var/lib is sufficient to leak over to the initial mount namespace.
Fixes: https://warthogs.atlassian.net/browse/SNAPDENG-17066

cmd/snap-confine: fix exploding homedirs bug

---

overlord/snapstate/backend.go
overlord/snapstate/backend/snapdata.go
overlord/snapstate/backend/snapdata_test.go
overlord/snapstate/backend_test.go
overlord/snapstate/handlers.go
snap/info.go
snap/info_test.go
tests/main/snapd-homedirs/task.yaml

`RemoveSnapDataDir` is leaving behind empty snap home data directories after the snap is removed (leaving a broken symlink behind).
Fixes: https://bugs.launchpad.net/snapd/+bug/2009617
This PR is a follow-up to https://github.com/snapcore/snapd/pull/13145.
This is an older PR https://github.com/snapcore/snapd/pull/13083 attempting the same thing, linking it here because the discussions are relevant.

many: remove snap data home directories

---

interfaces/builtin/steam_support.go

This PR changes every `pressure-vessel` parent to `*` (previously just `run`).
This fixes https://github.com/canonical/steam-snap/issues/356 in the Steam snap, where users were encountering the error: `bwrap: Can't mount tmpfs on /newroot/var/pressure-vessel/ldso: Permission denied` when running any Proton game, which represents a huge portion of games.
I included every pressure-vessel path (not just the tmpfs one noted in the issue) since pressure-vessel is likely to change at any point, as noted by @smcv here: https://github.com/canonical/steam-snap/issues/356#issuecomment-1893784766. In that comment, Simon recommended something more general and less restrictive (`/newroot/**/`), but for the time being I've opted for a more restrictive approach here.
Security permitting, we could …

steam_support: generalize pressure-vessel root paths

---

tests/core/basic20plus/task.yaml
tests/lib/prepare-restore.sh
tests/lib/prepare.sh
tests/lib/uc20-recovery.sh

Add changes to the spread tests to support edge and beta validation using testflinger backend
This works even not having the testflinger backend merged in spread.

tests: support testflinger

---

spread.yaml
tests/lib/nested.sh
tests/perf/install-many-snaps/task.yaml

This test installs as many snaps as desired and then checks the snapd status and main functions
The idea of this test is also to use all the disk space and see how snap works under this scenario

tests: new perf test install-many-snaps

---

packaging/debian-sid/control
packaging/debian-sid/snapd.dirs
packaging/debian-sid/snapd.install
packaging/debian-sid/snapd.links
packaging/debian-sid/snapd.maintscript
packaging/debian-sid/tests/control
packaging/ubuntu-14.04/control
packaging/ubuntu-14.04/snapd.dirs
packaging/ubuntu-14.04/snapd.install
packaging/ubuntu-14.04/tests/control
packaging/ubuntu-16.04/control
packaging/ubuntu-16.04/snapd.dirs
packaging/ubuntu-16.04/snapd.links
packaging/ubuntu-16.04/snapd.maintscript
packaging/ubuntu-16.04/tests/control

This is the go fmt equivalent of debian control files.

packaging: wrap-and-sort Debian and Ubuntu packaging

---

.github/workflows/test.yaml
NEWS.md
packaging/arch/PKGBUILD
packaging/debian-sid/changelog
packaging/fedora/snapd.spec
packaging/opensuse/snapd.changes
packaging/opensuse/snapd.spec
packaging/ubuntu-14.04/changelog
packaging/ubuntu-16.04/changelog
packaging/ubuntu-16.04/rules
packaging/ubuntu-16.04/snapd.install.in
spread.yaml
tests/lib/image.sh
tests/lib/pkgdb.sh
tests/main/cgroup-devices-v1/task.yaml
tests/main/cgroup-freezer/task.yaml
tests/main/cgroup-tracking-failure/task.yaml
tests/main/lxd-mount-units/task.yaml
tests/main/lxd-postrm-purge/task.yaml
tests/main/lxd-try/task.yaml
tests/main/lxd/task.yaml
tests/main/snapd-homedirs-vendored/task.yaml
tests/main/upgrade-from-release/task.yaml

This release is a followup on 2.61.2 which [failed to build for noble](https://launchpad.net/~snappy-dev/+archive/ubuntu/image/+packages?field.name_filter=snapd&field.status_filter=published&field.series_filter=noble).
It was agreed to be a deb only release.
Cherry-picked the noble build fix and enabling of tests for 24.04:
- [packaging/ubuntu-16.04: install systemd files in correct place on 24.04](https://github.com/snapcore/snapd/pull/13597)
- [tests: add spread tests support for ubuntu-24.04](https://github.com/snapcore/snapd/pull/13426)
Labelled all cherry-picked PRs and generated changelogs with:
DEBEMAIL="Ernest Lotter <ernest.lotter@canonical.com>" release-tools/changelog.py 2.61.3 2039017 NEWS.md
NEWS.md and changelogs was updated in the final commit: [release: …

release: 2.61.3

---

overlord/managers_test.go
overlord/snapstate/backend/setup_test.go
overlord/snapstate/snapstate_test.go
systemd/emulation.go
systemd/systemd.go
systemd/systemd_test.go

We were doing a reload-or-restart, but we actually need a restart if a mount unit is modified, as reload is relevant only to ask services to reload their (internal) configuration. This was hitting us when updating a component, as they get mounted in the same place as the previous component revision (for a given owner snap revision), and therefore we are rewriting a mount unit that does not change its name. The old component was still showing in that location.

overlord,systemd: restart mount units when changed

---

interfaces/builtin/system_packages_doc.go
interfaces/builtin/system_packages_doc_test.go
tests/regression/lp-2044335/task.yaml

The bare snap has few mount points, making the use of mimics, a workaround for creating mount points on an otherwise read-only squashfs, using a tmpfs and a farm of directories and files for bind-mounting, is required. In the particular case of system-packages-doc plug on a snap using the bare base snap, we need to create and re-create /usr.
The snap-update-ns program which is responsible for the bulk of mount manipulation, is invoked in one of two very different scenarios.  Most often, it is invoked from the "snap run" -> "snap-confine" -> "snap-update-ns", just before the "snap-exec" hop. In this scenario it is confined with a special, per-snap apparmor profile. This profile has so far had insufficient permissions to perform this manipulation. A user may work around the problem by …

i/builtin: system-packages-doc bare snap workaround

---

NEWS.md
client/systems.go
daemon/api_model.go
daemon/api_sideload_n_try.go
daemon/api_systems.go
daemon/api_systems_test.go
daemon/export_api_systems_test.go
overlord/assertstate/assertstate.go
overlord/assertstate/assertstate_test.go
overlord/devicestate/devicestate.go
overlord/devicestate/devicestate_systems_test.go
overlord/snapstate/snapstate_test.go
spread.yaml
tests/lib/assertions/test-snapd-recovery-system-pc-20.json
tests/lib/assertions/test-snapd-recovery-system-pc-20.model
tests/lib/assertions/test-snapd-recovery-system-pc-22.json
tests/lib/assertions/test-snapd-recovery-system-pc-22.model
tests/lib/assertions/test-snapd-recovery-system-pinned.assert
tests/lib/nested.sh
tests/nested/manual/recovery-system-offline/task.yaml
tests/nested/manual/recovery-system-reboot/task.yaml
tests/nested/manual/recovery-system/task.yaml

This PR updates the `/v2/systems/{label}` route for handling new actions, "create" and "remove".

many: add API routes for creating/removing recovery systems

---

interfaces/builtin/steam_support.go

Based on https://github.com/canonical/steam-snap/issues/359, [Pressure Vessel](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/tree/main/pressure-vessel?ref_type=heads) would like access to the same data that Steam itself has access to from within the Snap environment. Namely being the `/snap/` directory and `hostfs` directories. These are the same directories that are already available to Steam itself, so allowing them to be mounted into Pressure Vessel shouldn't increase attack surface as far as I'm aware.
I've tested these changes in my own app armor profile alongside the modified build of Pressure Vessel provided in https://github.com/canonical/steam-snap/issues/359 and I successfully can access the files required for https://github.com/canonical/steam-snap/issues/359.
For …

steam_support: Allow mounting of hostfs and snap for Pressure Vessel

---

.github/workflows/static-analysis.yaml

The are switching to the default configuration for the snapd project.
This is to avoid exception raised in prs.

tests: update the configuration used to display the static analysis info

---

packaging/debian-sid/rules

The effort to allow Debian to build without bolt support, have been insufficient, as we have discovered that parts of dh_golang do not support go build tags.
As an alternative that is brutal but works, remove the single offending file that causes 'go list -f ...' to enumerate github.com/snapcore/bolt due to missing -tags nobolt argument that debhelper does not provide.

packaging: fix debian builds broken by github.com/snapcore/bolt

---

tests/regression/lp-2044335/task.yaml

In certain cases, the kernel packaging may not contain the directory /usr/share/linux-image-$(uname -r). Since we do not precisely care about kernel packaging or special kernel packages for the cloud, isolate the test from this factor by automatically creating the directory if required.

tests: isolate lp-2044335 regression test kernel packaging

---

features/features.go
features/features_test.go

This is a stub version of #13670 , since checking AppArmor kernel and parser support for prompting and passing that information into AppArmor profile regeneration are non-trivial, and not particularly essential in the initial introduction of this feature, while the rest of prompting is not yet merged.
This PR is useful because #13681 exposes the list of supported and/or enabled features on `/v2/system-info`, and we want this feature to be included in that list and marked as unsupported, requiring a newer snapd release.
Whichever of this PR or #13681 get merged second should be responsible for adding a callback to the `featureSupportedCallbacks` which returns false, thus marking this feature as unsupported.

features: add experimental.apparmor-prompting feature stub

---

daemon/api.go
daemon/api_snap_conf.go
daemon/api_snap_conf_test.go
data/polkit/io.snapcraft.snapd.policy

For prompting, non-root clients need to be able to query and set the `system experimental.apparmor-prompting` option. Previously, there was no good way to do so without a workaround in the client to make a query as root, but using polkit is much preferred. This PR enables polkit authentication on the `/v2/snaps/{snap}/conf` endpoint.
Relevant discussion: https://forum.snapcraft.io/t/get-on-authenticated-endpoints-fail-despite-x-allow-interaction/39067

daemon: allow polkit authentication for `/v2/snaps/{snap}/conf`

---

boot/assets.go
boot/assets_test.go
boot/boot_test.go
boot/export_test.go
boot/model_test.go
boot/seal.go
boot/seal_test.go
boot/systems_test.go
bootloader/bootloader.go
bootloader/bootloadertest/bootloadertest.go
bootloader/grub.go
bootloader/grub_test.go
overlord/devicestate/devicestate_gadget_test.go
overlord/devicestate/devicestate_install_mode_test.go
overlord/devicestate/systems_test.go
overlord/install/install_test.go
tests/lib/nested.sh
tests/nested/manual/uc-grub-boot-chains/modify-gadget.py
tests/nested/manual/uc-grub-boot-chains/task.yaml

We need to resolve the boot chains another place based on the trusted assets we encountered to be installed. At this point it could be any chain. We will need to discover later what the correct chain is.
Also make TrustedAssets return an unsorted data structure to make sure we do not use the order like the comments claimed.

boot/grub.go: add new bootchain

---

NEWS.md
client/apps.go
client/apps_test.go
cmd/snap/cmd_services.go
cmd/snap/cmd_services_test.go
daemon/api_apps_test.go
overlord/servicestate/servicestate.go
overlord/servicestate/servicestate_test.go
tests/main/services-user/task.yaml
tests/main/services-user/test-snapd-user-service/bin/start
tests/main/services-user/test-snapd-user-service/meta/snap.yaml

Introduces the new switches `--user` to select user services for the current user, `--system` to select system services and `--users` to select user services for all users for the following operations:
`snap start`, `snap stop` and `snap restart`

client,cmd/snap: introduce --user, --system and --users switches for snap service operations

---

asserts/aspect_bundle.go
asserts/aspect_bundle_test.go
asserts/asserts.go
asserts/asserts_test.go
overlord/aspectstate/aspectstate_test.go
overlord/assertstate/assertstate_test.go
tests/lib/assertions/developer1-network-aspect-bundle.json
tests/lib/assertions/developer1-network.aspect-bundle
tests/lib/gendeveloper1/main.go

Move the aspect schema from a "storage" stanza to the assertion body. Also format parse and re-encode the JSON with two spaces for indentation and map ordered map keys. This should make the schema uniform and easy to read while still using a format that can be emulated by other tools. `jq -S` indents with 2 spaces and sorts maps by key, python's `json.dump` can be configured to do the same and Go's `json.MarshalIndent` sorts by default. For posterity, `jq` can also be used to escape newlines and quotes into a string that can be used in snap sign's expected input: `echo '{"storage":{"schema":{"foo":{"values":"any"}}}}' | jq -S | jq -sR`

asserts: move aspect schema to assertion body

---

release-tools/test/test_flake8.py

flake8 is broken on 24.04, this outright fails:
```
$ flake8 --ignore=E501 release-tools
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/flake8/plugins/finder.py", line 296, in _load_plugin
obj = plugin.entry_point.load()
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
module = import_module(match.group('module'))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line …
```

release-tools: skip flake8 on 24.04

---

tests/main/snap-quota-memory/task.yaml

snap.go-example-webserver.webserver.service is using about 540K and it is not killed (with 660K quota)

tests: fix snap-quota-memory in fedora systems

---

overlord/snapstate/backend/mountunit.go
overlord/snapstate/backend/mountunit_test.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate_test.go
systemd/emulation.go
systemd/systemd.go
systemd/systemd_test.go
tests/main/snapd-update-services/task.yaml

Do not restart the mount units when starting snapd even if the file
itself has been modified. This is to prevent systemd stopping services
when the mount unit gets restarted, as there are required dependencies
in the mount path for services defined in snaps.

overlord,systemd: do not restart mount units on snapd start

---

overlord/devicestate/devicestate_remodel_test.go
overlord/managers_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go

Create the kernel setup tasks that create the drivers tree only if a version of snapd-generator that creates mount units for this tree is installed in the system. This will happen if this is a UC24+ system or a hybrid system with snapd debian package version 2.62 or more modern.

overlord: create the drivers tree only if it will be mounted

---

tests/main/preseed-reset/task.yaml
tests/main/preseed/task.yaml

There is no longer any seeded snaps in base or minimal cloud images See:
. https://bugs.launchpad.net/ubuntu/+source/ubuntu-meta/+bug/2051346
. https://bugs.launchpad.net/ubuntu/+source/ubuntu-meta/+bug/2051572

tests: skip preseed tests in ubuntu noble

---

tests/main/snap-system-env/task.yaml

`/bin` and `/sbin` are not in the PATH generated by systemd in noble (systemd version is 255). I'm not sure if the change comes from another generator but it's likely related to the merging of /bin, /sbin, etc. In any case, the test is still valid and snapd's environment generator still works as expected. If anyone has some insight to share, please feel free to comment

tests: update the snap-system-env test for noble

---

NEWS.md
client/client.go
client/client_test.go
daemon/api_general.go
daemon/api_general_test.go
features/features.go
features/features_test.go

Adds `features.All()` to return a map from feature flag names to a struct indicating whether that feature is supported and/or enabled. A callback functions may be defined for a feature flag which returns `true` if that feature flag is supported by the system, otherwise `false`.
Features which are set to a value other than `true` or `false` are not included in the map, as these are not feature flags.
If no callback function is defined for a given feature flag, it is assumed that that feature flag is supported. Currently, callbacks are defined for `QuotaGroups` (check that systemd version >= 230) and `UserDaemons` (check that user units are supported).
Features may be enabled but not supported. In this case, the feature flag has been set to true, but the underlying feature is not supported …

client,daemon,features: expose feature flags supported/enabled info

---

interfaces/builtin/u2f_devices.go

I have a real device - [JaCarta U2F token (usb)](https://www.aladdin-rd.ru/catalog/jacarta_u2f/) - and can confirm, that it has the following characteristics:
idVendor=24dc, idProduct=0501

i/builtin: adds new JaCarta U2F usb token product id

---

tests/lib/prepare.sh
tests/lib/reflash.sh
tests/lib/uc16-reflash.sh

Originally, to reflash from Classic to Ubuntu Core, we rebooted with a grub entry that would use specific `root=` and `init=` script to reflash the disk.
We do not need a full reboot most of the time and we can just instead prepare an initramfs to switch when shutting down. Systemd will switch to `/run/initramfs` and run `/shutdown` in there.
However, on 16.04, systemd is unmounting mounts which makes this not as easy. So instead there we still reboot to grub, but instead of using `init=` and mount the root disk, we provide an initrd which can do the flashing, simplifying the method we have been using.

tests/lib/prepare.sh: reflash during shutdown

---

tests/main/interfaces-network-control/task.yaml

Fix the ARP manipulation checks and use the `ip` tool which is universally available.

tests/main/interfaces-network-control: fix tests for ARP manipulation

---

interfaces/builtin/serial_port.go
interfaces/builtin/serial_port_test.go

This commit is for the serial port of NXP Layerscape SoC
The prefix of the device name can be found [here](https://elixir.bootlin.com/linux/latest/source/drivers/tty/serial/fsl_lpuart.c#L245)

interfaces/builtin: add serial devices (ttyLPX) to allowed list

---

overlord/devicestate/handlers.go
tests/main/preseed-core20/task.yaml

Do not attempt to unmount early kernel mount point if one wasn't created during
preseeding. Normally, we conditionally add a setup-kernel-snap, which sets up
the mount where we have more device context information, but for the teardown in
mark-preseeded, it should be enough to just check if the mount was indeed
created.

o/devicestate: do not try to unmount early kernel mount if there isn't one

---

client/clientutil/service_scope.go
client/clientutil/service_scope_test.go
cmd/snap/cmd_services.go
overlord/hookstate/ctlcmd/restart.go
overlord/hookstate/ctlcmd/service_scope.go
overlord/hookstate/ctlcmd/services_test.go
overlord/hookstate/ctlcmd/start.go
overlord/hookstate/ctlcmd/stop.go

This is the snapctl version of https://github.com/snapcore/snapd/pull/13368 and based on top of it to reuse some of the code from that PR.

o/hookstate/ctlcmd: introduce --user, --system and --users switches for snap service operations

---

interfaces/builtin/microceph_support.go
interfaces/builtin/microceph_support_test.go
interfaces/policy/basedeclaration_test.go
tests/lib/snaps/test-snapd-policy-app-consumer/meta/snap.yaml

Add separate microceph-support interface in order to allow more types of block devices to be added as an OSD (bcache, indiv. partitions, device mapper)
Also allow access to the rbd sysfs controls for managing rbd-backed block devices (cf. https://docs.kernel.org/admin-guide/abi-testing.html#abi-file-testing-sysfs-bus-rbd)

i/b/microceph-support: add microceph-support interface

---

gadget/install/partition.go
gadget/install/partition_test.go
gadget/update_test.go

When building the list of partitions to create on auto-installation,
we were not properly calculating the end of a partition if that
partition existed on the disk and it had a size
range ([min-size,size]) defined in the gadget. Take this possibility
into account by properly matching on disk partitions to those in the
gadget and using the size on disk for existing partitions.

gadget/install: consider real partition size when creating partitions

---

tests/main/snapd-snap-transition/task.yaml

`snapd-snap-transition` fails infrequently due to retry timeout, This small PR increases the number of retries from 20 to 30 to increase the test robustness.

tests/main/snapd-snap-transition: increase retries for test robustness

---

interfaces/builtin/block_devices.go

ZFS is a versatile tool in managing block storage. Allowing ZFS vols as block-devices would enable additional scenarios for snaps (like MicroCeph) that need to deal with block storage. Specifically for MicroCeph it could be useful for testing and development scenarios where OSD block devices are expected without requiring actual physical disks.
Adding the /dev/zfs ioctrl device would enable snaps to automatically manage these volumes.

interfaces/builtin: allow ZFS vols as a block-device

---

boot/assets.go
boot/bootchain.go
boot/bootchain_test.go
boot/seal.go
boot/seal_test.go

This reverts #13402.
`tests/nested/manual/uc-update-assets-secure-add-sbat` shows some failures from time to time. It is possible in some context, the wrong hashes are pruned when resealing.

boot: revert bb7d327a36d8fd923126052c32792e1293c1d243

---

spread.yaml

LXD from [v5.21 adds "LTS"](https://docs.google.com/document/d/1UZqKQjbfE9ZTJyOmJCtZHwYgo1E2jlirsyDDB5tIWLM/edit#heading=h.fgvrz5f63wo) after version number for LTS versions when calling `lxd --version` which breaks snapcraft due to a snapcraft bug discussed [here](https://chat.canonical.com/canonical/pl/jkqk5b98hfrhzrrdptfodp4uew) 
The error: https://paste.ubuntu.com/p/2vwwkkw5Ty/
Where the error happens: https://github.com/snapcore/snapd/blob/master/tests/nested/manual/muinstaller-core/task.yaml#L99-L104
This fix proposal is to use latest/stable instead for all our testing. This impacts:
```
regression/lp-1871652/task.yaml:    lxc exec bionic -- snap install lxd --channel="$LXD_SNAP_CHANNEL"
main/lxd/task.yaml:    lxd.lxc exec my-nesting-ubuntu -- snap install lxd …
```

spread.yaml: make lxd-state install latest/stable instead of latest/candidate

---

tests/lib/core-config.sh

This function, when used in combination with clean_snapd_lib, tried to to make it appear as if the "x1" revision of "pc" was never installed. However, subsequent tests would fail if they removed what appeared to be their last revision of "pc", since that results in an attempt to remove the assumedly empty `/root/snap/pc`, which still contained `/root/snap/pc/x1`.

tests: remove root user data for pc snap in restore_pc_snap

---

tests/core/kernel-base-gadget-single-reboot-failover/task.yaml

fakestore that was setup in this test was leaking into other tests causing frequent failures.
This test was caught using this debug PR (#13717).

tests/core/kernel-base-gadget-single-reboot-failover: teardown fakestore on restore

---

cmd/snapd-apparmor/main_test.go
sandbox/apparmor/apparmor.go
sandbox/apparmor/profile_test.go

When using apparmor_parser from the host, pin the supported policy to ABI 4.0 or 3.0 if one is present on the host.
This is a twist on https://github.com/snapcore/snapd/pull/13715 as suggested by @alexmurray 
Interestingly, and unexpectedly, this ALSO works, even though we started to pin to 3.0 to avoid an apparent bug in 4.0. Go figure?
CC @alexmurray and @Meulengracht for awareness.

sandbox/apparmor: use host abi 4.0 or 3.0 if present

---

tests/lib/prepare-restore.sh

The spread-images is missing a cleanup step after an upgrade which would run auto-removal of obsolete packages. Work around this by removing any outstanding packages that would normally be dropped. This should prevent any package manipulation code in the tests from raising false positives in package cleanup checks running in restore-each.

tests: remove packages marked for auto-removal before running any tests

---

spread.yaml
tests/lib/tools/setup_nested_hybrid_system.sh
tests/nested/manual/devmode-snaps-can-run-other-snaps/task.yaml
tests/nested/manual/muinstaller-core/task.yaml

Use latest (edge) versions of snapcraft and lxd to avoid bugs and ensure compatibility. The LXD bug causes this issue in a few tests: https://paste.ubuntu.com/p/y3RGD2hjb5/, and the snapcraft bug cannot deal with the new LXD version naming that may include "LTS".
lxd bug: https://github.com/canonical/lxd-pkg-snap/pull/379
snapcraft bug: https://chat.canonical.com/canonical/pl/6w13o16npbffup3obepqiig3tr

tests: use snapcraft and lxd with latest fixes where possible

---

tests/main/cgroup-devices-v2/task.yaml
tests/main/microk8s-smoke/task.yaml

The test was observed to be unstable on certain systems. Try to collect more debug info.
Edit: Turns out it's microk8s leaving processes behind and interfering with tests that follow. I've pushed another patch which stops all microk8s processes and any pods we may have started during the test. I was able to successfully run the spread tests such that microk8s runs first, followed by cgroup-devices-v2

tests/main/cgroup-devices-v2, tests/main/microk8s-smoke: collect debus, stop all microk8s processes

---

gadget/gadget.go
gadget/gadget_test.go

Before unmarshalling storage traits json, check the size of the file, if file is zero size, assume traits do not exist.
This is a safe fallback, as no-existent storage traits is a valid usecase.
This addresses a problem which has occurred on the devices in the field which has been live repartitioned and at the same time those devices were provisioned with snapd version before device traits introduction. This resulted in the creation of zero-sized `disk-mapping.json` as there was non to start with.

gadget: if storage traits is zero sized file, assume traits do not exist

---

tests/nested/manual/recovery-system-reboot/task.yaml

In the case of an auto-refresh, the system would reboot. This resulted in some cryptic failures. Make sure to wait for an auto-refresh to happen before removing the recovery system, and make sure to wait for the system to reboot once the auto-refresh has finished.

tests: fix recovery-system-reboot install test that was being interrupted by a system reboot

---

tests/main/services-user/task.yaml

The polkit policy file was being left behind, and thus broke `tests/main/auth-error` test if that later on the same host.

tests/main/services-user: remove polkit policy file

---

tests/main/lxd-no-fuse/task.yaml

After 20.04, fuse3 is what replaced fuse in main so make sure both are removed.

tests/main/lxd-no-fuse: remove fuse and fuse3

---

daemon/api_snaps_test.go

This fixes the following tests failing for UK timezone:
- `TestSnapManyInfosReturnsRefreshInhibitProceedTime`
- `TestSnapInfoReturnsRefreshInhibitProceedTime`

daemon: fix local time comparison in tests

---

sandbox/apparmor/apparmor.go

Due to issues with incorrect behavior to mediate:
stat /dev/mqueue
For applications governed by the profile that allows it via
mqueue,
We cannot yet use apparmor 4, even if one is supported on the host. This does
impact userns mediation but it is better to have the old mediation and not
break snaps, than to have some new mediation in some cases and some unexpected
mediation in other cases.
Once the mqueue, issue is identified and we have updated bundled apparmor to a
stable release of apparmor 4, this patch can be reverted.

sandbox/apparmor: detect but ignore apparmor 4

---

NEWS.md
gadget/gadget.go
gadget/gadget_test.go
packaging/arch/PKGBUILD
packaging/debian-sid/changelog
packaging/fedora/snapd.spec
packaging/opensuse/snapd.changes
packaging/opensuse/snapd.spec
packaging/ubuntu-14.04/changelog
packaging/ubuntu-16.04/changelog
sandbox/apparmor/apparmor.go
tests/nested/manual/recovery-system-reboot/task.yaml

This release targets Ubuntu 24.04 BETA freeze.
Cherry picked single last minute additions:
- [Fix gadget zero-sized disk mapping caused by not ignoring zero sized storage traits](https://github.com/snapcore/snapd/pull/13719)
- [Fix recovery-system-reboot install test that was being interrupted by a system reboot](https://github.com/snapcore/snapd/pull/13736)
- [sandbox/apparmor: detect but ignore apparmor 4](https://github.com/snapcore/snapd/pull/13740)
DEBEMAIL="Ernest Lotter ernest.lotter@canonical.com" release-tools/changelog.py 2.62 2058277 NEWS.md
NEWS.md and changelogs was updated in the final commit: [release: 2.62](https://github.com/snapcore/snapd/pull/13731/commits/3fa0c816c422138af01c662b7d7a6e6a5f782298)

release: 2.62

---

boot/assets_test.go
boot/bootchain.go
boot/bootchain_test.go
boot/export_test.go

This is needed to re-merge #13402.
Hashes for boot assets are in a list that is already predictable: if there is only one hash, then the asset is not modified; if there are 2 hashes, then the first one is the old asset, and the second is the new asset.
There is no need to re-sort the hashes. And we lose the semantic if we do. We want to keep that semantic so we can prune impossible boot chains.

boot: do not sort list of hashes for boot assets

---

interfaces/builtin/desktop.go
interfaces/builtin/desktop_legacy.go
interfaces/builtin/unity7.go

apparmor in Ubuntu 24.04 LTS introduces an AppArmor profile for KDEs plasmashell
called "plasmashell". As such, the various DBus objects are now implemented
by a process that has the apparmor label "plasmashell" instead of
"unconfined" (since previously it did not have an AppArmor profile).
Extend the DBus rules for these objects to include this new
peer label to allow snaps to send notifications as before.
Fixes LP: #2056696

interfaces/desktop: allow DBus access to plasmashell

---

cmd/Makefile.am

Since snapd carries go.mod there is no point in trying to fiddle with GOPATH and simply let the Go toolchain figure things out.

cmd: update Go binaries targets

---

interfaces/builtin/docker_support.go

Allow docker to do anything with posix message queues. This may be refined later on with more fine-grained permission. This is likely coming out of apparmor 4.0 upgrade.

i/builtin: allow docker-support to use mqueue

---

spread.yaml

Add ubuntu-24.04-64 to the qemu spread backend so that spread tests for noble can be run locally with qemu.

spread.yaml: add ubuntu-24.04-64 to qemu spread backend

---

tests/lib/pkgdb.sh

The ppa check has to be done before the ppa is removed, otherwise it fails.

tests: fix checks done when snapd is install from ppa

---

cmd/libsnap-confine-private/cgroup-support-test.c
cmd/libsnap-confine-private/classic-test.c
cmd/libsnap-confine-private/snap-test.c
cmd/libsnap-confine-private/snap.c
cmd/snap-confine/mount-support.c

Address coverity scan results. None of the issues was classified as more than medium and none was particularly interesting.
https://scan7.scan.coverity.com/#/project-view/49681/15001

cmd/snap-confine, cmd/libsnap-confine-private: address coverity-scan results

---

interfaces/builtin/docker_support.go

Reverts snapcore/snapd#13738
Adding `mqueue` to docker-support interface results in spread test failure on focal, jammy, mantic and noble. `mqueue` has been available on apparmor_parser v3.0 already, and it seems apparmor 3.0 bug. The apparmor team was notified of this issue.
Proposing to revert allowing mqueue (all permissions) for the docker-support interface until the bug is fixed, to prevent issues as experienced in the docker smoke test.
`docker run hello-world`
`docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "mqueue" to rootfs at "/dev/mqueue": change mount propagation through procfd: resolving path inside …

i/builtin: revert allow docker-support to use mqueue

---

snap/container.go

This was introduced by b66fee81606a1c05f965a876ccbaf44174194063 (many: container validation improvements) but somehow flew under our radar in CI?

snap: format container.go

---

overlord/servicestate/servicestate.go
overlord/servicestate/servicestate_test.go
usersession/client/client.go
wrappers/internal/service_status.go

First of two PRs that implements support for user services in `snap services` command.

o/servicestate: support for user services

---

daemon/access.go
daemon/access_test.go
daemon/api_accessories.go
daemon/api_accessories_test.go
daemon/api_general.go
daemon/api_general_test.go
daemon/api_notices.go
daemon/api_notices_test.go
daemon/api_snaps.go
daemon/api_snaps_test.go
daemon/api_themes.go
daemon/api_themes_test.go
daemon/export_access_test.go
daemon/export_api_notices_test.go
daemon/ucrednet.go
daemon/ucrednet_test.go

For the some endpoints, including `/v2/notices`, we need to allow multiple interfaces to grant snaps access via `interfaceOpenAccess` or `interfaceAuthenticatedAccess`. Thus, the `Interface string` field in these structs should be replaced with `Interfaces []string`.
Accordingly, the optional `iface=` field in `RemoteAddr` should also support multiple interfaces. To do so, the relevant functions in `daemon/ucrednet.go` now support values of the form `iface=foo&bar&baz;`, which are added/parsed as `"foo"`, `"bar"`, and `"baz"`. That is, `ucrednetGetWithInterface(remoteAddr)` now returns `ifaces []string` instead of `iface string`, in case `remoteAddr` has an `iface=` value with multiple `'&'`-separated interfaces.
Importantly, `ucrednetAttachInterface` is now idempotent. Regardless of the …

daemon: support multiple interfaces in `RemoteAddr` and `interface{Open,Authenticated}Access`

---

overlord/state/taskrunner.go
overlord/state/taskrunner_test.go

This is a backport of the following PR from pebble: https://github.com/canonical/pebble/pull/391
In short, this changes the format of task failed log messages from this:
```
2024-03-21T06:37:37.224Z [pebble] [change 32 "Start service \"svc1\"" task] failed: cannot start service: exited quickly with code 1
```
to this
```
2024-03-21T06:43:09.559Z [pebble] Change 33 task (Start service "svc1") failed: cannot start service: exited quickly with code 1
```
This increases readability and consistency with pebble.
CC @benhoyt

o/state: adjust format of task failed log message

---

usersession/agent/rest_api.go
usersession/agent/rest_api_test.go
usersession/client/client.go
usersession/client/client_test.go
wrappers/services.go
wrappers/services_test.go

This PR simplifies reload-or-restart into just restart with `reload` parameter as well
This adds support for:
- enable+disabledServices to StartServices
- disable to StopServices
- reload to RestartServices and then remove "restart-or-reload"
This is not being used yet as I plan to do some cleanup and refactoring around the usession client / rest-api. This simply introduces new parameters, but nothing uses them yet.
I plan to cleanup and refactor how we return errors first.

usersession/client: add missing parameters (enable, disable, reload, disabled-services)

---

tests/main/preseed-lxd/task.yaml

The test stars a privileged LXD container which most likely replaced the AppArmor profiles on the host. Attempt to reload the host profiles in restore.

tests/main/preseed-lxd: restore apparmor profiles on the host

---

daemon/access.go
daemon/access_test.go

This PR cherry-picks commit 7870fb3ec40009a24fb6cbdfdc02e94e037e0278 which was lost while rebasing PR #13673.
The commit improves tests to ensure that `CheckAccess` correctly attaches all connected interfaces to the `remoteAddr`.

o/i/a/common: test that CheckAccess attaches all interface to remoteAddr

---

boot/assets.go
boot/bootchain.go
boot/bootchain_test.go
boot/seal.go
boot/seal_test.go

We are supposed to update on disk from the back of the boot chain to the beginning. That means and old shim should not be expected to install a new grub.
We can reduce the list of possible boot chains we give to secboot. When we will switch to secboot master, secboot will fail if it sees boot chains that cannot work. So we should make sure not to pass them.
There is still a bug where we update the seed partition before boot partition. But here we assume the bug is fixed.
This was previously merged in #13402, but reverted by #13713. Then waiting for #13720 to be reintroduced.

boot: prune some bootchains that should not happen

---

osutil/nfs_linux.go
osutil/nfs_linux_test.go

NFS and CIFS share the same shortcoming, that on kernels older than 6.8 (but I could be wrong on the version number), accessing files there causes apparmor to require network permissions even though the process performing the access is entirely unaware of the fact that network file system is in use.
Snapd contained a work-around for this behavior, with specific detection logic looking for NFS file system mounted or declared at a specific place. Extend the logic to handle NFS and CIFS equally, to give better support to SAMBA or Windows Server-based home directories.
Follows on https://github.com/snapcore/snapd/pull/13758

osutil: extend nfs-based home to support cifs

---

interfaces/builtin/posix_mq.go
interfaces/builtin/posix_mq_test.go

Added posix_mq missing mqueue time64 syscalls to seccomp allow list.
This is now aligned with docker-support seccomp.

interfaces/builtin: add missing time64 mqueue syscalls to posix_mq interface

---

interfaces/builtin/password_manager_service.go

https://launchpad.net/bugs/2058840: KDE 6 comes with Kwalletd6, so the profile needs updating.

interfaces/builtin: allow kwalletd version 6

---

store/store_download_test.go

Skip download speed monitoring unit tests if SNAPD_SKIP_SLOW_TESTS is set. The test is based on getting the timings right and so it becomes generally unreliable when running in super slow environment, such as a build VM in OBS, thus failing like so:
```
[ 2317s] ----------------------------------------------------------------------
[ 2317s] FAIL: store_download_test.go:886: storeDownloadSuite.TestTransferSpeedMonitoringWriterHappy
[ 2317s]
[ 2317s] store_download_test.go:903:
[ 2317s]     c.Check(store.Cancelled(ctx), Equals, false)
[ 2317s] ... obtained bool = true
[ 2317s] ... expected bool = false
[ 2317s]
[ 2317s] store_download_test.go:904:
[ 2317s]     c.Check(w.Err(), IsNil)
[ 2317s] ... value *store.transferSpeedError = &store.transferSpeedError{Speed:0} ("download too slow: 0.00 …
```

store: conditionally skip download monitoring unit tests

---

cmd/snap/cmd_snap_op_test.go

Since we closed the server immediately, the port was being re-used by another test. This caused this test to send its HTTP request to another test that wasn't expecting it.

c/snap: do not close test server until test is over

---

desktop/notification/notificationtest/fdo.go

Use sever mutex to protect access to err field. Running `go test -race` fails with the following error:
```
Read at 0x00c0003b72f8 by goroutine 468:
github.com/snapcore/snapd/desktop/notification/notificationtest.fdoApi.Notify()
/home/maciek/work/canonical/snapd/desktop/notification/notificationtest/fdo.go:149 +0x9c
runtime.call128()
/usr/lib/go/src/runtime/asm_amd64.s:773 +0x57
/usr/lib/go/src/reflect/value.go:380 +0xb5
github.com/godbus/dbus.exportedMethod.Call()
/home/maciek/work/canonical/snapd/vendor/github.com/godbus/dbus/default_handler.go:128 +0x219
github.com/godbus/dbus.(*exportedMethod).Call()
<autogenerated>:1 +0x84
github.com/godbus/dbus.(*Conn).handleCall()
/home/maciek/work/canonical/snapd/vendor/github.com/godbus/db …
```

desktop/notification/notificationtest: fix data race

---

desktop/notification/notificationtest/fdo.go

The test code takes the server lock for the whole duration of CloseNotification, what causes a deadlock due to a call to Close()

desktop/notification/notificationtest: fix deadlock in CloseNotification

---

.github/workflows/test.yaml

The idea is to have in this new job the checks needed to validate specific aspects when the branch is not master (just for release/**).
The first check requested is to validate the daily ubuntu system is the same than in master, this is needed to make sure that we can compile snapd and run tests on the latest ubuntu when we branch a new version

tests: add static checks for snapd branches 

---

client/notices.go
client/notices_test.go

This is a backport from pebble: https://github.com/canonical/pebble/pull/297 to allow sending notices from snap command.
This is a building block for https://github.com/snapcore/snapd/pull/13770 to allow snap run to record `snap-run-inhibit` commands.

client: add support to send notices

---

cmd/snap/cmd_run.go
cmd/snap/cmd_run_test.go
cmd/snap/export_test.go
cmd/snap/inhibit.go
cmd/snap/inhibit_test.go
snap/info.go
snap/info_test.go
tests/main/snap-run-symlink-error/task.yaml

This PR is a rebase of https://github.com/snapcore/snapd/pull/13411 on top of master + minor test refactoring. A lot changed on master and a direct rebase would have been very messy, I thought it would be better to keep the discussions there intact with the changes history and created a new PR.
`snap run` was failing due to missing `current` revision symlink when `snap run` is inhibited because due to refresh.
This PR fixes that by directly checking the old revision stored in the inhibition hint file and properly waits until the snap is no longer inhibited from running.
A retry might be needed if the snap was never inhibited before (inhibition hint file doesn't exist) and the refresh was started/completed in the tiny window between starting `snap run` and the transient cgroup being …

cmd/snap: use updated "current" revision after snap refresh run inhibition

---

tests/main/high-user-handling/task.yaml

Apparently some test user processes may still be running when we try to remove it.
```
2024-04-09 12:47:47 Restoring google-central:fedora-38-64:tests/main/high-user-handling (apr091230-325924)... Error: 2024-04-09 12:47:47 Error restoring google-central:fedora-38-64:tests/main/high-user-handling (apr091230-325924) : -----
+ tests.session -u hightest restore umount: /run/user/4294967294/gvfs: no mount point specified. umount: /run/user/4294967294/doc: no mount point specified.
+ userdel -r hightest userdel: user hightest is currently used by process 39295 -----
.
```

tests/main/high-user-handling: force kill test user's session

---

cmd/libsnap-confine-private/apparmor-support.c
cmd/libsnap-confine-private/apparmor-support.h

The apparmor profile can use 'kill' enforcement mode, in which case the process execution an action it has no permissions for will be sent SIGKILL. We need to account for this mode explicitly, otherwise s-c will complain about running with elevated permissions and exit with an error, which makes not sense since the process is still properly confined.

cmd/libsnap-confine-private: account for 'kill' apparmor profile mode

---

daemon/access.go
daemon/api_notices.go
daemon/api_notices_test.go
daemon/export_test.go
overlord/state/notices.go
overlord/state/notices_test.go

This PR adds the `snap-run-inhibit` notice which is need for the "snap-run during refresh UX" flow described in [SD167](https://docs.google.com/document/d/1HJQWKzgaB3yPKwRUqlxYhgyaKG5IcJe8eZOT4YY1CI8/edit#heading=h.v228s8hnqd53).
This is mostly a port of `custom` notices implementation from pebble https://github.com/canonical/pebble/pull/296 adapted for the `snap-run-inhibit` notice.
This PR is a building block for https://github.com/snapcore/snapd/pull/13770.

o/state,daemon: add snap-run-inhibit notice

---

aspects/aspects.go
aspects/aspects_test.go
aspects/schema.go
aspects/schema_test.go

Ensure that that value we are setting has keys that match the required format (similar to snap names). The map schema check enforces this constraint but we should always ensure it and not just when there's a schema for it.

aspects: validate map keys in Set value

---

data/systemd/snapd.service.in

Allow all service's control group processes to send notifications via sd_notify. This is necesssary to prevent log flooding with systemd warnings like:
Apr 05 14:36:55 qemuname systemd[1]: snapd.service: Got notification message from PID 1002, but reception only permitted for main PID 917
These warnings are happening due to a change in systemd 254 that makes all systemd programs (systemctl, udevadm, systemd-detect-virt, etc.) send EXIT_STATUS notifications when exiting.
Fixes LP#2060310.

data/systemd: allow notifications for all snapd subprocesses

---

NEWS.md
interfaces/builtin/system_observe.go
tests/main/interfaces-system-observe/task.yaml
tests/main/interfaces-system-observe/testsnap/meta/snap.yaml

Allow listing systemd units and querying their properties. This enables service
plugging system-observe to obtain more information about the state of the
system. Specifically, this enables Prometheus' systemd_exporter to work.

 interfaces/builtin/system_observe: allow listing systemd units and their properties

---

overlord/snapstate/autorefresh.go
overlord/snapstate/autorefresh_test.go
overlord/snapstate/snapstate_update_test.go
overlord/state/export_test.go
overlord/state/state_test.go
overlord/state/warning.go
overlord/state/warning_test.go

This PR allows using warnings as a fallback instead of the [current desktop notifications fallback](https://github.com/snapcore/snapd/blob/199386c78cd88be1a74a942fc7bd59437f736a18/overlord/snapstate/autorefresh.go#L743-L754) when no snap exists with the marker `snap-refresh-observe` interface (i.e. `snapd-desktop-integration` snap).
[SD167 - Refresh App Awareness Desktop UX Flow](https://docs.google.com/document/d/1HJQWKzgaB3yPKwRUqlxYhgyaKG5IcJe8eZOT4YY1CI8/edit)
This alternative fallback flow is hidden behind the experimental `refresh-app-awareness-ux` flag to avoid disrupting the current user experience until `snapd-desktop-integration` is compatible with the new flow.
This PR is split into two main parts:
1. Extending the warnings API
- [o/state: allow specifying options when creating …

o/state, o/snapstate: use warnings as fallback for RAA desktop notifications

---

NEWS.md
client/apps.go
client/apps_test.go
cmd/snap/cmd_services.go
cmd/snap/cmd_services_test.go
daemon/api_apps.go
daemon/api_apps_test.go
daemon/api_base_test.go
daemon/export_test.go
overlord/servicestate/servicestate.go
tests/main/services-user/task.yaml

Implements support for user services in `snap services`
For a root user, `snap services` behaviour will not change. It will show the global enable status of user services. It will be possible to see the status of user-services with the new `--user` switch.
For a non-root user, `snap services` will now default to show the status of user services for the current user.
Introduces a new flag for non-root users. `--global` which is equivelent to the behaviour we have today (and the behaviour for root-users). `snap services --global`
Introduces a new flag for root users. `--user` which is equivilent to the default behavior of non-root users.

daemon,cmd/snap: support for user services in snap services

---

snapdtool/tool_test.go

Distros like openSUSE Tumbleweed or Fedora use /usr/libexec/snapd. Update the test to account for the correct path.

snapdtool: fix unit tests when running on distro using /usr/libexec/snapd

---

aspects/aspects.go
aspects/aspects_test.go

This makes the behaviour of aspects when unsetting or setting maps with nil leaves more consistent with options. It also changes the behaviour of removing to not remove empty maps and removes nulls from values, which is also consistent with options.

aspects: make unset and set behaviour consistent with options

---

aspects/aspects.go
aspects/aspects_test.go
aspects/export_test.go

Limit how many nested levels a value set to an aspect can have. This is necessary because we recurse to traverse objects and it takes much less memory to create an object than it takes to traverse it. Here are my back-of-the-envelope calculations, please let me know if anything is off: the default limit on the http request body is 10Mb, since a nested level in the JSON object takes just 6 bytes {"a": ...} the API would accept JSON with more than 1.7 million levels and recursing into them would (at a 2Kb min stack size) take 3.5Gb. Limiting the recursion levels to 4096 keeps the stack size in the low MBs.

aspects: limit Set value's nestedness

---

interfaces/builtin/kubernetes_support.go

When running cilium under microk8s, the following denial is observed:
apparmor="DENIED" operation="create" class="net"
profile="snap.microk8s.daemon-containerd" pid=20550 comm="tc" family="alg"
sock_type="seqpacket" protocol=0 requested_mask="create" denied_mask="create"
which is triggered when cilium attempts to set up network package classifier through tc.

interfaces/bultin/kubernetes_support: allow SOCK_SEQPACKET

---

client/clientutil/service_scope.go
cmd/snap/cmd_services.go
overlord/hookstate/ctlcmd/ctlcmd.go
overlord/hookstate/ctlcmd/export_test.go
overlord/hookstate/ctlcmd/services.go
overlord/hookstate/ctlcmd/services_test.go

Introduce matching functionality for "snapctl services" as in "snap services" by this PR https://github.com/snapcore/snapd/pull/13381.
"Snapctl services" is one of the few commands that can run without being root user, which means we cannot make any assumptions around the user running the command, introducing the same decision logic around how to deal with the caller.

many: add support for user daemons in "snapctl services"

---

overlord/snapstate/backend.go
overlord/snapstate/backend/link.go
overlord/snapstate/backend/link_test.go
overlord/snapstate/backend/setup_test.go
overlord/snapstate/backend_test.go
overlord/snapstate/component_test.go
overlord/snapstate/handlers_components.go
overlord/snapstate/handlers_components_link_test.go
overlord/snapstate/sequence/sequence.go
overlord/snapstate/sequence/sequence_test.go
overlord/snapstate/snapmgr.go
snap/component.go
snap/component_test.go
tests/main/component/task.yaml

Use symlinks to point to the currently active component for a given snap revision, instead of mounting new component revisions always in the same mountpoint. This makes updates of components more atomic and will simplify parts of the code.
The symlinks will take the form
/snap/<snap_name>/components/<snap_revision>/<comp_name>
while the components will be mounted on
/snap/<snap_name>/components/mnt/<comp_name>/<comp_revision>

many: use symlinks for active component

---

.github/workflows/nightly.yaml

This change introduces a new github actions workflow to run the analisys tool (Tiobe tics server)
The workflow has been tested in my forked project. The only step that is failing is the last one because the integration with tics server has to be done from snapd main project (not from the fork).
The data produced is going to be displayed in https://canonical.tiobe.com/tiobeweb/TICS/TqiDashboard.html#axes=Project(snapd),Sub()&metric=tqi
Next step is to integrate the analysis as part of the pr pipeline, including a quality gate.

tests: run tiobe tics tool in a nightly workflow

---

cmd/snap/cmd_run.go
cmd/snap/cmd_run_test.go
cmd/snap/export_test.go
cmd/snap/inhibit.go
cmd/snap/inhibit_test.go
tests/main/snap-run-inhibition-flow/api-client/bin/api-client.py
tests/main/snap-run-inhibition-flow/api-client/meta/snap.yaml
tests/main/snap-run-inhibition-flow/task.yaml

This PR builds on https://github.com/snapcore/snapd/pull/13791 (~~and should be rebased after https://github.com/snapcore/snapd/pull/13791 gets merged~~ already rebased) to enable the "snap-run during refresh UX" flow described in [SD167](https://docs.google.com/document/d/1HJQWKzgaB3yPKwRUqlxYhgyaKG5IcJe8eZOT4YY1CI8/edit#heading=h.v228s8hnqd53).
This simply allows `snap run` to issue (per-user) `snap-run-inhibit` notices when it is inhibited for refresh. This notice can later be consumed by something like `snapd-desktop-integration` snap replacing the old flow of directly calling `snapd-desktop-integration` on dbus.
As fallback if no snap exists with the marker `snap-refresh-observe`  interface https://github.com/snapcore/snapd/pull/13619, a normal notification is sent using the user …

cmd/snap: record snap-run-inhibit notice

---

daemon/api_notices_test.go

Snap mount location is hardcoded, but os-release is not mocked, so host paths are assumed.
Failed like so:
```
FAIL: api_notices_test.go:947: noticesSuite.TestAddNoticesSnapCmdReexecCore
api_notices_test.go:948:
s.testAddNoticesSnapCmd(c, "/snap/core/12/usr/bin/snap", false)
api_base_test.go:648:
c.Assert(rsp.Type, check.Equals, daemon.ResponseTypeSync, check.Commentf("expected sync resp: %#v, result: %+v", rsp, rsp.Result))
... obtained daemon.ResponseType = "error"
... expected daemon.ResponseType = "sync"
... expected sync resp: &daemon.respJSON{Type:"error", Status:403, StatusText:"", Result:(*daemon.errorResult)(0xc0007911d0), Change:"", Sources:[]string(nil), SuggestedCurrency:"", WarningTimestamp:<nil>, …
```

daemon: fix notices API tests on non Ubuntu

---

cmd/snap-bootstrap/cmd_initramfs_mounts.go

When using single boot install mode, it is wrongly assumed that preseed capable system is always preseeded.
Improve conditions so attempt to apply pressed data is only made if `preseed.tgz` is present.

cmd: snap-bootstrap: fix unpreseeded single boot install

---

overlord/snapstate/backend/setup_test.go

The tests seem to call real depmod which fails when building on LP:
```
FAIL: setup_test.go:770: setupSuite.TestRemoveKernelModulesComponentsFails
setup_test.go:786:
s.testSetupKernelModulesComponents(c, firstInstalled, nil, ksnap, kernRev, "")
setup_test.go:709:
c.Assert(err, IsNil)
... value *exec.Error = &exec.Error{Name:"depmod", Err:(*errors.errorString)(0x4000118380)} ("exec: \"depmod\": executable file not found in $PATH")
FAIL: setup_test.go:656: setupSuite.TestSetupAndRemoveKernelModulesComponents
setup_test.go:662:
// Set-up and then remove
s.testSetupKernelModulesComponents(c, toInstall, nil, ksnap, kernRev, "")
setup_test.go:709: …
```

overlord/snapstate/backend: mock depmod

---

.github/workflows/nightly.yaml

Before running TiCS, It is required to install staticcheck, which is the Go analyser we use for compiler warnings.
Also it is updated the logs path to be uploaded as an artifact

tests: add missing dependency to nightly workflow

---

tests/nested/core/core20-kernel-failover/task.yaml

link. As sealing is taking longer than in the past because we have more branches now due to https://github.com/snapcore/secboot/commit/f3ad7c92552a7e2a99d8b1e292bc238628945cb1.

tests/core20-kernel-failover: increase timeout waiting for try-kernel

---

tests/main/fake-netplan-apply/task.yaml

The test was meant to fail in a clear way on unsupported releases but due to an unintentional refactor, it was just running on the wrong base.

tests: fix fake-netplan-apply test

---

tests/nested/core/core20-kernel-failover/task.yaml

The one from edge will always fail if we have FDE, make sure that there are no false negatives because of that.

tests/core20-kernel-failover: use kernel from beta channel

---

.github/workflows/nightly.yaml

To run the statick tools it is required the latest go version.

tests: update go version used in nightly workflow

---

cmd/snap-confine/seccomp-support.c

PR #13443 made coverity to report a new issue because of tainted input (hdr.len_deny_filter) being used in `sc_must_read_filter_from_file`. Whilst it is a false positive in our scenario (hdr.len_deny_filter is already checked in `sc_must_read_and_validate_header_from_file` ), I think it may be worth to make this check explicit in `sc_must_read_filter_from_file` even if it is duplicated.

seccomp-support: check filter length value before reading

---

build-aux/snap/snapcraft.yaml

Ship the current version of snap-debug-info.sh script inside the snapd snapd, so that folks no longer need to download it from snapd github repository.

build-aux/snap: ship snap-debug-info.sh script

---

daemon/api_sideload_n_try.go
overlord/snapstate/backend/backend.go
overlord/snapstate/backend/backend_test.go
overlord/snapstate/backend/setup.go
overlord/snapstate/component.go
overlord/snapstate/component_install_test.go
overlord/snapstate/component_test.go
overlord/snapstate/export_test.go
overlord/snapstate/handlers_components.go
overlord/snapstate/handlers_components_mount_test.go
overlord/snapstate/snapmgr.go
snap/component.go
snap/component_test.go
snap/info.go
snap/info_test.go
snap/pack/pack.go
snap/snaptest/snaptest.go

This PR expands the component hook information to snap.ComponentInfo. The hook data structures are derived from both the component directory itself (getting implicit hooks) and a `snap.Info`, which allows us to access explicit hooks and plugs that might be applied to the hooks.
Based on https://github.com/snapcore/snapd/pull/13763, first relevant commit is da5afbce327b0f65f3672c50b854f6bc86e98794.

daemon, o/snapstate, snap: add hooks to snap.ComponentInfo

---

overlord/snapstate/backend/setup.go
overlord/snapstate/snapmgr.go

We do not need early mounts for the kernel in UC16/18, and causes problems with systemd on UC16.

o/snapstate: use StartBeforeDriversLoad only for systems with modes

---

overlord/snapstate/backend/link.go
overlord/snapstate/backend/link_test.go
overlord/snapstate/backend/setup.go
overlord/snapstate/backend/setup_test.go
overlord/snapstate/backend_test.go
overlord/snapstate/component.go
overlord/snapstate/component_install_test.go
overlord/snapstate/export_test.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_components.go
overlord/snapstate/handlers_components_discard_test.go
overlord/snapstate/handlers_components_link_test.go
overlord/snapstate/handlers_components_mount_test.go
overlord/snapstate/handlers_components_test.go
overlord/snapstate/handlers_setup_kernel_test.go
overlord/snapstate/snapmgr.go
tests/main/component/task.yaml

Only one can be installed in the system at the same time.

o/snapstate,tests: discard previous component on a component refresh

---

interfaces/apparmor/template.go

Ever since snapd 2.62 was released, snap-update-ns requires opening the home directory of the user for some validation and sanity checking. This is now affected by a bug in base policy regarding ecryptfs. Add the similar workaround we have in other templates.
Fixes: https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/2062330
Fixes: https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/2062173

i/apparmor: fix snap-update-ns with ecrypfs home

---

interfaces/apparmor/template.go

I've noticed this denial in one of my test systems:
kwi 19 10:54:52 ubuntu-2204-cryptfs kernel: audit: type=1400
audit(1713516892.723:323): apparmor="DENIED" operation="open" class="file"
profile="snap-update-ns.chromium" name="/var/lib/snapd /" pid=8425 comm="5"
requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Given that snap-update-ns must access mount profiles and contains code to safely traverse a path without any symbolic links, I think the extra permissions is acceptable.
I did not audit the code to pinpoint the exact cause.

i/apparmor: allow snap-update-ns to traverse to /var/lib/snapd

---

cmd/libsnap-confine-private/utils-test.c
cmd/libsnap-confine-private/utils.c
cmd/libsnap-confine-private/utils.h
cmd/snap-confine/snap-confine.apparmor.in
cmd/snap-confine/snap-confine.c

Do not attempt to set up a device access filtering through cgroups when we're executing inside a container. Especially, in the case of unprivileged containers, the whole set up may be impossible to execute completely, as running in a separate userns means snap-confine is not even able to mount the bpf filesystem and cannot execute bpf() syscalls.

cmd/snap-confine: skip device cgroup setup when running inside a container

---

overlord/snapstate/autorefresh.go
overlord/snapstate/backend.go
overlord/snapstate/backend/link.go
overlord/snapstate/backend_test.go
overlord/snapstate/handlers.go
overlord/snapstate/snapstate_test.go
usersession/client/client.go
wrappers/services.go
wrappers/services_test.go

Required step in order to support user-daemons in the refresh code.
This adds support for QueryDisabledServices to return information related to disabled user-daemons. This also changes the signature of StartServices to accept a structure `DisabledServices` that QueryDisabledServices returns

many: support user-daemons in QueryDisabledServices

---

data/selinux/snappy.te

Since 3cfa28a0fc snap-confine checks if the system is running in a container. It does so by reading /run/systemd/container. Extend the SELinux to allow basic search operations within /run/systemd. It is unlikely anyone runs snapd in a container where the SELinux is enabled on the host, so the actual file read permissions are likely not needed.

data/selinux: update policy to allow stat of /run/systemd/container

---

spread.yaml

This is required to run beta validation on uc24

tests: add ubuntu noble to the google-nested-dev backend

---

interfaces/builtin/opengl.go

The nvidia container toolkit needs to traverse the top level libs directory in order to discover the libraries and generate a CDI config.  This change enables reading the directory listing, without actually being able to read the files themselves which are not specifically allowed by pattern.
This enhancement enables the use of nvidia support in the docker snap on classic systems.
Ref: https://github.com/NVIDIA/nvidia-container-toolkit/issues/82#issuecomment-2047596685
Ref: https://github.com/NVIDIA/nvidia-container-toolkit/issues/82#issuecomment-2047716550
Ref: https://github.com/docker-snap/docker-snap/issues/127

interfaces/opengl: enable use of nvidia container toolkit CDI config generation

---

.github/workflows/test.yaml
run-checks

Running unit tests with various build variants does not need to block test execution.

github, run-checks: split unit tests variants, add variant with -race

---

tests/main/try-non-fatal/task.yaml
tests/main/try-snap-goes-away/task.yaml
tests/main/try-snap-is-optional/task.yaml
tests/main/try-twice-with-daemon/task.yaml
tests/main/try-with-hooks/task.yaml
tests/main/try/task.yaml
tests/main/uc20-create-partitions-encrypt/task.yaml
tests/main/uc20-create-partitions-reinstall/task.yaml
tests/main/uc20-create-partitions/task.yaml
tests/main/unhandled-task/task.yaml
tests/main/upgrade-from-2.15/task.yaml
tests/main/user-data-handling/task.yaml
tests/main/validate-container-failures/task.yaml
tests/main/validate-container-happy/task.yaml
tests/main/vitality/task.yaml
tests/main/whoami/task.yaml
tests/main/writable-areas/task.yaml
tests/main/xdg-open-portal/task.yaml
tests/main/xdg-open/task.yaml
tests/main/xdg-settings/task.yaml

This adds details to tests from try-* all the way down to the end of the main/ directory.

tests: add details to some of the tests in main suite

---

overlord/snapstate/backend_test.go

Fix a race when appending an operations during failure scenarios in fake backend's LinkSnap.
Reported by -race:
```
Read at 0x00c0004822c0 by goroutine 1597:
github.com/snapcore/snapd/overlord/snapstate_test.(*fakeSnappyBackend).appendOp()
/home/runner/work/snapd/snapd/src/github.com/snapcore/snapd/overlord/snapstate/backend_test.go:1506 +0x104
github.com/snapcore/snapd/overlord/snapstate_test.(*fakeSnappyBackend).ForeignTask()
/home/runner/work/snapd/snapd/src/github.com/snapcore/snapd/overlord/snapstate/backend_test.go:1416 +0x1c4
github.com/snapcore/snapd/overlord/snapstate_test.AddForeignTaskHandlers.func1()
/home/runner/work/snapd/snapd/src/github.com/snapcore/snapd/overlord/snapstate/snapstate_test.go:366 +0x118 …
```

o/snapstate: fix race in fake backend operations

---

wrappers/services_test.go

Fixes the unit test failure on master.

wrappers: use Getuid in unit test to match the SetupTest code

---

overlord/snapstate/backend_test.go

There are more of those.
```
Read at 0x00c000160580 by goroutine 24:
github.com/snapcore/snapd/overlord/snapstate_test.(*fakeSnappyBackend).appendOp()
/home/runner/work/snapd/snapd/src/github.com/snapcore/snapd/overlord/snapstate/backend_test.go:1506 +0x104
github.com/snapcore/snapd/overlord/snapstate_test.(*fakeSnappyBackend).UndoCopySnapData()
/home/runner/work/snapd/snapd/src/github.com/snapcore/snapd/overlord/snapstate/backend_test.go:1267 +0x11a
github.com/snapcore/snapd/overlord/snapstate.(*SnapManager).undoCopySnapData()
/home/runner/work/snapd/snapd/src/github.com/snapcore/snapd/overlord/snapstate/handlers.go:1843 +0x8f1
github.com/snapcore/snapd/overlord/snapstate.(*SnapManager).undoCopySnapData-fm()
<autogenerated>:1 +0x4d …
```

o/snapstate: fix more racy operations in fake backend

---

features/export_test.go
features/features.go
features/features_test.go
sandbox/apparmor/apparmor.go
sandbox/apparmor/apparmor_test.go

This PR splits off a portion of the work from #13670 related to AppArmor feature support for prompting.
Notably, this also adjusts the apparmor kernel and parser feature probing, since the `prompt` kernel feature support is marked as the `prompt` string occurring in `/sys/kernel/security/apparmor/features/policy/permstable32`.
This file, on my system, contains the following:
```
$ cat /sys/kernel/security/apparmor/features/policy/permstable32
allow deny subtree cond kill complain prompt audit quiet hide xindex tag label
```
If this should be extended to other features besides `prompt`, I'm happy to add those as well -- the current handling is specific to `prompt` but could be generalized.

features,s/apparmor: add checks for prompt support in apparmor parser and kernel

---

overlord/snapstate/backend/link_test.go
wrappers/core18.go
wrappers/core18_test.go

We have udev rules that run /usr/lib/snapd/snap-device-helper, so we need to make sure that the binary is available before udevd starts.
In some devices, this has led to errors in the journal like:
`(udev-worker)[xxx]: <dev>: Process '/usr/lib/snapd/snap-device-helper snap_console-<profile>' failed with exit code 1.`

wrappers: mount /usr/lib/snapd before udevd starts

---

.github/workflows/test.yaml
overlord/ifacestate/udevmonitor/udevmon_test.go
packaging/fedora/snapd.spec
snap/squashfs/squashfs_test.go

Add support for running unit tests on other systems, especially those where we run unit tests as part of the package build process, and ones where the snap mount dir isn't /snap, or libexecdir isn't /usr/lib/snapd.

github,many: add support for running unit tests on other systems

---

spread.yaml

This change has 2 improvements:
1. reduce the amount of debug output in nested tests, just show useful information about the nested vm
2. add identifier for the list of tests executed (this will make esasier to query for that list)

tests: improve the debug output for spread tests

---

testutil/timeouts.go
testutil/timeouts_test.go

One of the tests I added in [this PR](https://github.com/snapcore/snapd/pull/13852) has quite a few tasks so it was failing to settle when running with the go race detector. Testing it locally, the tests take 10x longer which is in line with what [the official docs state](https://go.dev/doc/articles/race_detector#:~:text=The%20cost%20of%20race%20detection%20varies%20by%20program%2C%20but%20for%20a%20typical%20program%2C%20memory%20usage%20may%20increase%20by%205%2D10x%20and%20execution%20time%20by%202%2D20x). This PR increases settle timeout when running the test suite with the go race detector on.

testutil: increase settle timeout when running -race

---

spread.yaml
tests/lib/tools/setup_nested_hybrid_system.sh
tests/nested/manual/devmode-snaps-can-run-other-snaps/task.yaml
tests/nested/manual/muinstaller-core/task.yaml

This is the revert of the change
https://github.com/snapcore/snapd/pull/13716

tests: use lxd snap from candidate in spread tests

---

store/export_test.go

The race detector is failing in a test access:
```
Read at 0x00c000202060 by goroutine 17:
github.com/snapcore/snapd/store.(*TransferSpeedMonitoringWriter).MeasuredWindowsCount()
/home/mute/go/src/github.com/snapcore/snapd/store/export_test.go:119 +0x3a5
github.com/snapcore/snapd/store_test.(*storeDownloadSuite).TestTransferSpeedMonitoringWriterHappy()
/home/mute/go/src/github.com/snapcore/snapd/store/store_download_test.go:910 +0x3d9
/usr/local/go1.20/src/runtime/asm_amd64.s:728 +0x48
/usr/local/go1.20/src/reflect/value.go:370 +0xc7
/home/mute/go/src/github.com/snapcore/snapd/vendor/gopkg.in/check.v1/check.go:775 +0xadd
gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1() …
```

store: fix race condition warning in test

---

tests/completion/indirect/task.yaml
tests/completion/simple/task.yaml
tests/completion/snippets/task.yaml

There are "three" completion tests that multiply with the large number of variatns present in the suite. The "simple" test is unsual and I don't fully understand how it works because it does not install the test-snapd-complexion snap at all. Instead it relies on running the completion script directly, without the snap complete/etelpmoc script pair working across the sandbox.

tests/completion: document the "three" completion tests

---

tests/main/snap-run-symlink/task.yaml

This is a different text for the details of a particular test than one proposed here https://github.com/snapcore/snapd/pull/13911 -- the test is entirely useless today and I wanted to capture that in the text.

tests/main: document snap-run-symlink

---

interfaces/builtin/all.go
interfaces/builtin/all_test.go
snap/component_test.go

Make sure to remove sanitized plugs from component hook plugs.

interfaces/builtin, snap: remove sanitized plugs from component hook plugs

---

tests/core/network-config/task.yaml
tests/core/persistent-journal-namespace/task.yaml
tests/core/persistent-journal/task.yaml
tests/core/reboot/task.yaml
tests/core/services/task.yaml
tests/core/snap-auto-import-asserts-spools/task.yaml
tests/core/snap-auto-import-asserts/task.yaml
tests/core/snap-auto-mount/task.yaml
tests/core/snap-core-fixup/task.yaml
tests/core/snapd-failover/task.yaml
tests/core/snapd-refresh-vs-services/task.yaml
tests/core/uboot-unpacked-assets/task.yaml
tests/core/uc20-recovery/task.yaml
tests/core/writablepaths/task.yaml
tests/core/xdg-open-on-core/task.yaml

This change include all the missing details for core suite

tests: add details for core tests suite

---

tests/core/snap-set-core-config/task.yaml

There is no /etc/timezone file anymore on UC24.

tests/core/snap-set-core-config: fix test for UC24

---

cmd/snap-mgmt/snap-mgmt.sh.in
data/systemd/snapd.apparmor.service.in
data/systemd/snapd.autoimport.service.in
data/systemd/snapd.failure.service.in
data/systemd/snapd.service.in
data/systemd/snapd.snap-repair.service.in
overlord/configstate/configcore/debug.go
overlord/configstate/configcore/debug_test.go
overlord/configstate/configcore/runwithstate.go
packaging/fedora/snapd.spec
packaging/opensuse/snapd.spec
systemd/emulation.go
systemd/systemd.go
tests/core/debug/task.yaml

- debug.snapd.log to enable debug traces for snapd service. This is
done by creating an environment file used by the snapd service.
- debug.systemd.log-level to be able to set systemd log level, by
adding a configuration file to /etc/systemd/system.conf.d/.

many: add ubuntu core debug options

---

overlord/snapstate/backend_test.go
overlord/snapstate/export_test.go
overlord/snapstate/handlers.go
overlord/snapstate/reboot.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_update_test.go
store/store_action.go

Refreshes that include essential snaps are organised in a way that allows us to reboot a single time. However, on classic systems with kernel/gadget snaps this means that apps must wait for a reboot which. To prevent apps from blocking until then, this change splits a refresh into two mostly independent tasksets. One with essential snaps which is still organised according to the single reboot and another with apps and their bases which can complete before the reboot. Some constraints on this are snapd which is always refreshed first and we an app may depend on the model base in which case it must wait for that. This doesn't include change an auto-refresh or a spread test yet, those will be added in future PRs.

o/snapstate: don't make apps wait for reboot on classic w/ kernel

---

overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_update_test.go

Make app and non-model bases install independently of essential snaps in path installs. See https://github.com/snapcore/snapd/pull/13852 for more.

o/snapstate: make apps not wait for reboots in path installs

---

tests/main/snap-sign/task.yaml
tests/main/snap-system-key/task.yaml
tests/main/snap-user-service-socket-activation/task.yaml
tests/main/snap-user-service-start-on-install/task.yaml
tests/main/snap-user-service-upgrade-failure/task.yaml
tests/main/snap-userd-desktop-app-autostart/task.yaml
tests/main/snap-userd-reexec/task.yaml

Affected tests:
- tests/main/snap-sign/task.yaml
- tests/main/snap-system-key/task.yaml
- tests/main/snap-user-service-socket-activation/task.yaml
- tests/main/snap-user-service-start-on-install/task.yaml
- tests/main/snap-user-service-upgrade-failure/task.yaml
- tests/main/snap-userd-desktop-app-autostart/task.yaml
- tests/main/snap-userd-reexec/task.yaml

tests/main: add missing test details

---

packaging/snapd.mk

Have the snapd packaging helper create /var/lib/snapd/environment. This fixes RPM build on openSUSE:
```
RPM build errors:
Directory not found: /usr/src/packages/BUILDROOT/snapd-1337.2.63-0.x86_64/var/lib/snapd/environment
```

packaging: make sure that /var/lib/snapd/environment exists

---

interfaces/apparmor/backend.go
interfaces/apparmor/backend_test.go
interfaces/apparmor/spec.go
interfaces/apparmor/spec_test.go
interfaces/dbus/backend.go
interfaces/dbus/backend_test.go
interfaces/ifacetest/backendtest.go
interfaces/kmod/backend.go
interfaces/naming.go
interfaces/naming_test.go
interfaces/seccomp/backend.go
interfaces/seccomp/backend_test.go
interfaces/snap_app_set.go
interfaces/snap_app_set_test.go
overlord/ifacestate/handlers.go
overlord/ifacestate/helpers.go
overlord/ifacestate/ifacestate_test.go
overlord/snapstate/component.go
overlord/snapstate/component_install_test.go
overlord/snapstate/component_test.go
overlord/snapstate/handlers_components.go
overlord/snapstate/handlers_components_test.go
overlord/snapstate/snapmgr.go
snap/component.go
snap/component_test.go
snap/info.go
snap/info_test.go
snap/snaptest/snaptest.go

This PR does some of the work for creating security profiles for component hooks. First relevant commit is 3a7d9f9349296f845ad2fa587b72498bc754fb5a, based on https://github.com/snapcore/snapd/pull/13837.

many: generate security profiles from component hooks

---

cmd/snap-seccomp/main.go

Snap-seccomp stopped building on Arch since glibc got updated which revealed a source code problem in our code with a missing _GNU_SOURCE define.

cmd/snap-seccomp: define GNU_SOURCE for fallocate

---

overlord/devicestate/devicestate_install_mode_test.go
overlord/ifacestate/ifacestate_test.go

Some unit tests fail unexpectedly on hosts where snapd has been installed through the package, but its services have not been enabled (or started).

o/devicestate, o/ifacestate: fix mocking in unit tests

---

check-pr-title.py

This will make CI happy for dependabot PRs which have descriptions like:
"build(deps): bump golang.org/x/net from 0.9.0 to 0.23.0 in /tests/lib/muinstaller"

check-pr-title.py: allow parenthesis before colon in PR titles

---

tests/main/snap-run/task.yaml

The snap-run test started failing on debian-sid because there was
a change to the message emitted when running strace with an
invalid option.
```
+ MATCH 'Can'\''t stat '\''invalid'\'': No such file or directory'
/usr/bin/strace: Cannot find executable 'invalid'
error: exit status 1
```

tests: fix snap run test for debian-sid

---

tests/lib/fakestore/store/store.go
tests/lib/fakestore/store/store_test.go

The unit tests hardcode the port number, which occasionally seems to be occupied by something else when running the whole test suite on GH (most likely tests from another package). Have the port number be selected by the kernel.

tests/lib/fakestore/store: do not hardcode port in fakestore unit tests

---

.github/workflows/static-analysis.yaml

With this change the prs will run static analysis

tests: run static analysis for prs in self-hosted runners

---

tests/main/download-timeout/task.yaml

The download-timeout test was taking over 10min to complete due to a couple of issues. The first one is that there was a typo in the environment variables that controlled the measurement window so the timeout was still the default of 5min (the test downloads twice). Setting it correctly cut the execution time for one of the downloads but not the other strangely. It turns out that the test was creating a override file that was sorted before the other existing override (systemd applies sorts override files). Fixing this and lowering the timeout to 15s cuts the running time from 10min to 30s. I wanted to add a log when the env var was set so we could check it in the test but this happens in an `init()` and I don't think the logger is set up by then.

tests: fix/optimise download-timeout spread test

---

packaging/debian-sid/control
spread.yaml

We need to be able to iterate and at present master is broken, requiring a force-merge that only few people can use. Let's agressively fix master so that we can iterate and make things better bit-by-bit.

packaging: add missing dependencies, disable centos-9

---

cmd/snap/cmd_snap_op_test.go

Similarly to the issue fixed in https://github.com/snapcore/snapd/pull/13783, the test was opening a socket just to get a valid port number and then immediately closing it. Unfortunately, the port was being reused by another test which then received the request from this test. Fixed by sending the request to port 0 which cannot be connected to.
```
2024-05-21T12:49:22.2057178Z FAIL: runner_test.go:1276: runnerSuite.TestNextVerifySelfSigned
2024-05-21T12:49:22.2070788Z 
2024-05-21T12:49:22.2072017Z runner_test.go:870:
2024-05-21T12:49:22.2072735Z     c.Check(ua, testutil.Contains, "snap-repair")
2024-05-21T12:49:22.2074096Z ... container string = "snapd/2.63+git168.g8ee86bf (series 16; classic) snap ubuntu/22.04 (amd64) linux/6.5.0-1021-azure"
2024-05-21T12:49:22.2075254Z ... elem string = …
```

cmd/snap: fix port usage after release

---

spread.yaml

This reverts commit f58de9076d8286b8a07faaccbd237f068805baf6.
Centos 9 is not blocking merges. I was confused by GitHub user interface.

spread.yaml: revert "spread.yaml: disable centos-9"

---

osutil/strace/strace.go
osutil/strace/strace_test.go
tests/core/snapd-failover/task.yaml
tests/main/snap-run/task.yaml

This moves us off the custom patch and onto an upstream feature we've heled develop. The feature is not released yet but the patch has been integrated into the strace-static snap.
https://github.com/dilyn-corner/strace-static-snap/pull/3
Jira: SNAPDENG-19870

osutil: switch to -u UID:GID for strace-static

---

.github/workflows/test.yaml
spread.yaml
tests/cross/go-build/task.yaml
tests/lib/image.sh
tests/lib/prepare.sh
tests/main/listing/task.yaml

The region us-east1 is shared among project. In order to avoid reaching the instances quota we are moving out to europe regions. The idea of moving to europe is because the CI is in the UK.
From now, we will have 5 regions for snapd (4 in europe and 1 in the USA for sru and nested)
In all cases I tried to keep regions balanced in terms of number of instances.
In a following pr I'll create a tool to check the current spread backend in order to make simpler checks in the tests.

tests: moving out google machines from us-east1-b

---

.github/workflows/static-analysis.yaml

This step is not required because the tool was already installed in the self-hosted runners. This is needed to avoid requesting the secret with the tics token.

tests: skip tics tool installation in self-hosted runners

---

cmd/snap-failure/cmd_snapd.go
cmd/snap-failure/cmd_snapd_test.go
cmd/snap-failure/main_test.go
snapdtool/export_test.go
snapdtool/tool_linux.go
snapdtool/tool_test.go

The snap-failure helper is used as a general failure handler for failures of the
snapd.service unit. Its purpose is to trigger a revert of snapd snap to the
previous revision whenever a failure occurs. The logic asserting whether a snapd
refresh was in progress is privy to the actual snapd binary, however any attempt
to execute snapd binary from the snapd snap makes no sense if the system does
not support running snapd directly from the snap in the first place.
Related issues: SNAPDENG-21263, SNAPDENG-21264
Based on top of #13996

cmd/snap-failure: do not attempt to run snapd on classic when reexec is disabled

---

tests/main/interfaces-process-control/task.yaml

Cleaning (killing) the spawned process was deferred to restore but spread waits for execute script to finish completely which causes the test to hang for the whole time of the process (sleep 5m).
If the test is successful we could speed up the process by popping the clean command.
This fix speeds up the test by 5 minutes.

tests: kill process in interface-process-control as early as possible

---

spread.yaml

This is required to avoid errors related to space in the sru instances

tests: add more storage for sru google instances

---

spread.yaml

I'll propose enabling Fedora 40 separately, as we need to have a special image prepared and uploaded to our Google repository.

spread.yaml: remove Fedora 38 (EOL)

---

snapdtool/tool_linux.go

Simplify the check for reexec being enabled in the system.

snapdtool: simplify check for reexec being enabled

---

interfaces/builtin/network_control.go

Add the `FlushCaches` method to the already existing rules that allow resolved management. The existing access is for safe members of the systemd-resolved D-Bus API, and FlushCache should also be a safe operation.
Some utilities that configure systemd resolved via D-Bus use flush caches as part of their setup flow.
One such use case is Tailscale, which this changes enables use of in a strictly confined snap. Discussed here: https://github.com/tailscale/tailscale/issues/267

interfaces/network-control: Allow systemd resolved cache flushing via D-Bus

---

packaging/fedora/snapd.spec

There's no need to use sed to remove -lseccomp, the code uses pkg-config to interrogate for the right build flags.
This was tested with mock (fedora build tool) for EPEL-{7,8,9} and FC-{39,40,41}.
For context see commit 536f30bebcbaca8b391919afbda8dd67b360d45d

packaging: remove stale workaround from snap-seccomp RHEL build

---

tests/regression/lp-2065077/task.yaml

We used to unmount the directory, but the unit left behind by snapctl mount could be re-activated and cause problems to other tests.

tests: remove leftover mounts made by snapctl mount

---

overlord/restart/restart.go
overlord/restart/restart_test.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_rerefresh_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_update_test.go

In hybrid systems where we do refreshes of apps before the reboot and essential snaps after, check if a re-refresh is necessary after the apps are done instead of waiting for all (and therefore a reboot). This is possible because currently essential snaps don't use epochs and don't require re-refreshes. If an app has a dependency that requires a reboot (like the model base), then the check-rerefresh task needs to wait for that refresh to complete. Since, if we're waiting for the reboot, there isn't much to gain in resolving the app's dependencies to only wait for those, the check-rerefresh preserves the old behavior in that case to keep things simple.

o/snapstate: in hybrid systems re-refresh before reboot if possible

---

.github/workflows/test.yaml

Modified test workflow to enable tests on security release PRs.
As part of work to put in place a new security release process that includes security release for core maintenance the following to branches is required within a new private snapd fork https://github.com/snapcore/snapd-security-release.
- core-snap-security-release/2.61: single branch based off release/2.61 (tag 2.61.3) for security maintenance for "core" snaps (counterpart for release/2.61 that will be merged back after disclosure)
- security-release/: branches for general security releases for snapd (counterparts for release/ that will be merged back after disclosure)
I propose we keep branch matching fairly exact provide certainty about which branches we expect to exist. This is arguable ok since we do not foresee this …

tests: run test workflow on security release PRs

---

HACKING.md
tests/lib/prepare-restore.sh

Update instructions on installing development dependencies. Include an example for Fedora.

HACKING, packaging: update dependencies and information on installing development dependencies

---

systemd/systemd.go
systemd/systemd_test.go

Some tests were failing on debian-sid because we weren't coping with systemd versions that contained a release candidate suffix. This deals with it simply by ignoring which should be enough given that we only compare them roughly to check if systemd is not too old.
```
error: cannot get logs: cannot get systemd version: cannot convert systemd
version to number: 256~rc3
```
Seen here: https://github.com/snapcore/snapd/actions/runs/9267748316/job/25501253602#step:8:14581

systemd: strip pre-release suffixes when comparing versions

---

cmd/snap-bootstrap/cmd_initramfs_mounts.go
cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
cmd/snap-bootstrap/export_test.go
dirs/dirs.go
gadget/install/content.go
gadget/install/content_test.go
gadget/install/export_test.go
gadget/install/install.go
gadget/install/install_dummy.go
gadget/install/install_test.go
kernel/kernel_drivers.go
kernel/kernel_drivers_test.go
overlord/devicestate/devicestate_install_api_test.go
overlord/devicestate/devicestate_install_mode_test.go
overlord/devicestate/export_test.go
overlord/devicestate/handlers_install.go
overlord/snapstate/backend/setup.go
overlord/snapstate/snapstate.go
snap/naming/componentref.go
snap/naming/componentref_test.go
tests/lib/nested.sh
tests/lib/uc20-create-partitions/main.go
tests/main/uc20-create-partitions-encrypt/task.yaml
tests/main/uc20-create-partitions-reinstall/task.yaml
tests/main/uc20-create-partitions/task.yaml
tests/nested/manual/kernel-modules-components/component.yaml
tests/nested/manual/kernel-modules-components/task.yaml

Build drivers tree on installation so kernel modules can be found on first boot after installation (otherwise the modules would be available too late, after initial installation of the kernel has happened while seeding).
Also, make sure that the tree is not re-created when seeding, and add a spread test for kernel-modules components.

many: build drivers tree on install

---

.github/workflows/test.yaml
check-pr-title.py
run-checks

This is needed to be able to check pr titles in forked projects.

tests: update check-pr-title script to use it in forked projects

---

build-aux/snap/snapcraft.yaml

craftctl seems a bit slow, so we should just call it once.

snapcraft.yaml: call craftctl less often

---

.github/workflows/test.yaml
check-pr-title.py
run-checks

The check-pr-title.py was created when we used travis (a long time ago).
Now, in github actions we can access to the pr title from ${{ github.event.pull_request.title }}
The idea of this change is to avoid checking in the github api and simplify the check-pr-title.py tool.
This also is required to be able to use this check in private projects where a unauthenticated api call is not allowed.
Also, I am removing from the actions workflow the pr number variables which are not used anymore.

tests: simplify the pr-title check

---

tests/nested/manual/muinstaller-real/task.yaml
tests/nested/manual/split-refresh/task.yaml

Check that on a hybrid system, refreshes of both essential snaps and
apps and non-model bases don't make the apps wait for a reboot. In
particular check that the refresh of the kernel, gadget and model base
wait for a reboot. Check that apps that depend on the model base also
wait for it to be refreshed and that apps that don't can completely
refresh before the reboot.
Based on https://github.com/snapcore/snapd/pull/13925

tests: test refresh mixing essential and apps in hybrid systems 

---

overlord/snapstate/backend_test.go
overlord/snapstate/snapstate_install_test.go

`Install` and `InstallMany` have subtle differences in how they handle the case where the store provides an empty response.
`Install` -> returns a `snapstate.ErrMissingExpectedResult`
`InstallMany` -> returns a `store.SnapActionError`
Add tests to define this behavior, and thus requiring #13949 to conform to this behavior.

o/snapstate: test for specific errors returned by Install and InstallMany

---

tests/core/watchdog/task.yaml
tests/lib/prepare-restore.sh
tests/lib/tools/tests.session
tests/main/cgroup-tracking/task.yaml
tests/main/security-device-cgroups-serial-port/task.yaml
tests/main/security-device-cgroups/task.yaml

Debian sid is using an rc version of systemd which tests.session and various other tests weren't dealing with. This change cuts the pre-release suffix from all of them although some were only used by distros in which this isn't a problem. This is more consistent and robust IMO.
`/home/gopath/src/github.com/snapcore/snapd/tests/bin/tests.session: line 252: [: 256~rc3: integer expression expected`

tests: deal with pre-release suffix in systemd versions

---

tests/main/cifs-home/task.yaml
tests/main/cifs-home/test-snapd-sh/bin/sh
tests/main/cifs-home/test-snapd-sh/meta/snap.yaml

This test is a simpler rendition of the existing nfs test (nfs-support). Here I have focused only on checking the per-user home directory mount, as that captures our expectation of how the feature is to be used in practice.

tests: add integration test for cifs /home

---

build-aux/snap/snapcraft.yaml

This is needed by Ubuntu Core to have completion to work. It should be tested by `ubuntu-core-22-64:tests/core/bash-completion`. But because we still repack older snaps, it does not get caught.

snapcraft.yaml: add missing etelpmoc.sh for shell completion

---

tests/main/auto-refresh-pre-download/task.yaml

Kill the running process if the auto-refresh-pre-download test fails unexpectedly, otherwise we'll hang until the kill-timeout. Added the "Skip spread" label because the change would only be tested if the test fails. I forced a failure manually to test it.

tests: kill pending process on failure

---

tests/nested/manual/recovery-system-reboot/task.yaml

Because we need /snap/snapd/current symlink for the snapd snap to work when seeded, we need to update the test to use an up to date base. We cannot use an old core22 snap with a new snapd snap.

tests/nested/manual/recovery-system-reboot: use updated core22 base

---

build-aux/snap/snapcraft.yaml

This is a work-around for [LP#1673247](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1673247), which in theory should not affect the snap. But for now, since the code and tests depend on that path we should use that name, and then fix the code later.

snapcraft.yaml: use expected path for snap-confine apparmor profile

---

usersession/agent/export_test.go
usersession/agent/rest_api.go
usersession/agent/rest_api_test.go

Currently, when a notification is shown to the user to inform they that there is an update for an open snap, the snap name is used, which can be misleading to the user.
This PR uses the application name from the .desktop file, taking into account the current locale of the user.

usersession: Use the app name from .desktop file in notifications

---

cmd/snap/cmd_run_test.go
cmd/snap/inhibit.go
cmd/snap/inhibit_test.go
tests/main/snap-run-symlink-error/task.yaml

Due to the hint lockfile race detection logic introduced [here](https://github.com/snapcore/snapd/pull/13747/files#diff-2040a7ab4147eafb94c9b58c40202df922bd298e0ec3d152e322cef32f051db5R76-R82), snap run always shows race detected error when running snaps that don’t exist which can be confusing.
```bash
zeyad@z16:~$ snap run this-snap-does-not-exist
error: race condition detected, snap-run can only retry once
```
Discussion: https://chat.canonical.com/canonical/pl/p8x478mpiibttpudhsqm8zdnco
This PR fixes this by differentiating between snap not existing and a missing current symlink due to ongoing refresh.
Fixes: https://bugs.launchpad.net/snapd/+bug/2067034

cmd/snap: improve error message on running a non-existing snap

---

daemon/api_general.go
daemon/api_general_test.go
daemon/export_api_general_test.go
overlord/snapstate/conflict.go
overlord/snapstate/conflict_test.go
overlord/snapstate/export_test.go

This PR is an iteration based on #13902 which allows `/v2/changes` API caller to associate each task with the relevant affected snaps which is useful in the case change progress tracking per snap when a change is associated with multiple snaps.
This exact use case is needed by snapd-desktop-integration.
Note: When this is merged, The [REST API docs](https://snapcraft.io/docs/snapd-api#heading--changes) need to be updated as well.

daemon: attach affected-snaps data to tasks

---

tests/lib/nested.sh
tests/lib/prepare-restore.sh

This change is needed to create the test user in uc24 with home directory.
This is needed to fix tests in uc24 (edge validation)

tests: create test user with useradd in uc24

---

packaging/snapd.mk

The Go toolchain only generates a Go build ID, but GNU build IDs are expected to present almost universally. Make sure to generate GNU build IDs for Go binaries like we do in Fedora packaging, so that rpmbuild is happy.

packaging/snapd.mk: generate GNU build ID for Go binaries

---

cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
overlord/overlord_test.go
overlord/state/copy_test.go
overlord/state/export_test.go
overlord/state/notices.go
overlord/state/notices_test.go
overlord/state/state.go

When a client wants to receive the notices using the /v2/notices interface, it usually will first receive all the old notifications, store the date and time of the last notification, and in the next calls use that date and time to get the next notices, and avoid getting the old notices over and over again.
Unfortunately, if, due to chance, two or more notifications have the same date and time, this scheme will fail, because after receiving the first one, the call will return it, and when the client asks for the next, it will filter from the date/time of the last notice sent, so the second notice with the same timestamp won't be sent. This can happen if the timer used for timestamps doesn't have enough granularity.
This patch fixes this by ensuring that no notice has the same date/time …

notices: ensure that two notices don't have the same lastDateTime

---

cmd/snapd/main.go
daemon/daemon.go
daemon/daemon_test.go
overlord/managers_test.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_test.go
overlord/stateengine.go
overlord/stateengine_test.go
tests/core/snapd-failover/task.yaml

When the snapd.service unit fails to be activated, an OnFailure handler will
execute snap-failure which in turn starts the snapd process from the previous
revision of the snap with SNAPD_REVERT_TO_REV set in its environment. It may
happen that the snapd unit fails at runtime without an associated change to the
snapd snap, however snap-failure is not able to detect such case, and so the
snapd process started in its context would continue to run. Avoid this by
extending the logic within snapd to check it if has been started by snap-failure
with the intention of handling a rollback, and so whether there is a change
related to snapd snap in the state. When the conditions have not been met, snapd
exits and snap-failure continues to restart the snapd service.
Related issues: SNAPDENG-21605 …

o/snapstate: handling of unexpected runtime restart

---

interfaces/builtin/power_control.go

[auto-cpufreq project](https://github.com/AdnanHodzic/auto-cpufreq) has had snap package for few years now, and with [release of 2.2.0](https://github.com/AdnanHodzic/auto-cpufreq/releases) which adds functionality to set battery charging thresholds, its snap package is in broken state since. 
Reason for this is because `hardware-observe` interface doesn't have ability to write to `/sys/class/power_supply/`. This was discussion and this PR was suggested as part of [Snapcraft forum: Request for kernel-module-control interface for auto-cpufreq](https://forum.snapcraft.io/t/request-for-kernel-module-control-interface-for-auto-cpufreq/38953) by @alexmurray 
Currently only 2 locations auto-cpufreq will need to write to are:
```
/sys/class/power_supply/BAT*/charge_start_threshold …
```

i/builtin/power-control: add paths for battery charging thresholds to power-control interface

---

snap/types.go
snap/types_test.go
store/details_v2.go
store/details_v2_test.go
store/store.go
store/store_action.go
store/store_action_test.go

This enables us to request resources for a snap during a call to `SnapAction`. We only add the "resources" to the request "fields" query param if one of the actions includes resources.

store: interface with the store to request snap resources

---

overlord/ifacestate/handlers.go
overlord/ifacestate/ifacestate_test.go
overlord/snapstate/handlers_components_test.go
overlord/snapstate/snapmgr.go

This corrects and tests the behavior of undoing a `setup-profiles` task that contains components. We change `setupProfilesForSnap` to be `setupProfilesForAppSet`, so we can pass in a `SnapAppSet` that doesn't contain the components being set up for the current task when undoing the task.

o/ifacestate: properly undo setup-profiles on component installation

---

tests/nested/manual/cmdline-option/cloud.conf
tests/nested/manual/core20-gadget-cloud-conf/cloud.conf
tests/nested/manual/core20-gadget-cloud-conf/task.yaml
tests/nested/manual/muinstaller-core/task.yaml

We are not actually using the NoCloud datasource, so just use None which is the one really used by cloud-init if not specified by external means.

tests/nested: use None as single datasource in the tests

---

tests/lib/nested.sh
tests/lib/prepare-restore.sh

The nested tests are failing bucause of this problem
--comment is not supported by all the adduser versions (Unknown option: comment)

tests: revert change to used --comment in adduser

---

.github/workflows/test.yaml

Modified the test workflow to enable running nested tests on the private snapd repo snapcore/snapd-security-release by specifying "Run nested" label.

.github/workflows: enable test workflow to retrieve pr labels for any repo

---

daemon/api_snaps.go
daemon/api_snaps_test.go
tests/main/interfaces-snap-refresh-observe/task.yaml

Access to /v2/snaps/{name} is required for snap-refresh-observe because it is needed to get the path for the XXXXX.desktop file, which is needed for the icon and the visible name.
It should not be a problem because /v2/snaps is already enabled.

api-snaps: add refresh-observe access to /v2/snaps/{name}

---

overlord/snapstate/agentnotify/agentnotify.go
overlord/snapstate/agentnotify/agentnotify_test.go
overlord/snapstate/agentnotify/export_test.go
overlord/snapstate/autorefresh.go
overlord/snapstate/snapstate.go

The new Refresh Awareness specification moves all the work of showing refresh progress and notifications into a specific snap. To detect when that snap is available or not, snapd checks if there is a snap with the snap-refresh-observe interface connected. In that case, it presumes that it will manage all the notifications, and won't send any by itself.
Unfortunately, only the "Pending refresh" notification checks this case, while the "Refresh complete" notification doesn't. This results in duplicated notifications.
This patch fixes this.

notify: Dont send refresh complete notification if snap refresh observe is connected

---

tests/main/snapd-snap/task.yaml

Not very useful to build snapd snap from 14.04 given it has to use lxd. The VMs for 14.04 are not enough. So let's disable the test.

tests/main/snapd-snap: stop testing building of snapd snap on 14.04

---

boot/export_sb_test.go
boot/export_test.go
boot/setefibootvars.go
boot/setefibootvars_sb.go
boot/setefibootvars_sb_test.go

go-efilib always queries for efivarfs on initialization, which is not needed for most use of snapd. We can remove import of go-efilib when nosecboot tag is used.
See https://github.com/canonical/go-efilib/blob/ac83d67997a21bdf37b7a697425d505649a862fa/vars_linux.go#L287
Also this simplify packaging on some distributions.

boot: do not import go-efilib on nosecboot

---

interfaces/builtin/desktop.go

These set of rules allow for color managed applications to communicate with colord, which will be able to tell such applications which ICC profile to load.
This solution in itself is not complete, as it would still require a plug definition for personal files of the following form:
plugs:
dot-local-share-icc:
interface: personal-files
read:
- $HOME/.local/share/icc

interfaces/desktop: allow DBus communication with colord

---

wrappers/services.go
wrappers/services_test.go

This properly proxies the enable request to the user-session agent, along with the disabled-services for user services (however not used yet, will be used by https://github.com/snapcore/snapd/pull/13905)

wrappers: proxy missing enable+disabledSvcs to service agent

---

tests/lib/prepare.sh

As when we to prepare the main suite we restart snapd service at least 4 times (5 when we don't do re-exec), in fast vms it is easy to reach the starts limit and make the tests fail.
The error in the logs is:
snapd.service: Start request repeated too quickly.
snapd.service: Failed with result 'start-limit-hit'.

tests: increase the StartLimitBurst default value to 10

---

.github/workflows/test.yaml

-no-debug-output indicates to spread that debug output is not included in the log
-logs is used to store the logs generated (similar as artifacts is used)
When the log is saved, the debug line shows something like:	
2024-06-05 15:58:09 Debug output for google:ubuntu-20.04-64:tests/tests.backup (jun051856-832773) : saved to file .logs/google_ubuntu-20.04-64_tests_tests.backup.debug.log

tests: use no-debug-output for spread

---

tests/lib/pkgdb.sh

To make opensuse tests work in openstack, it is needed to install rpm-build.

tests: add rpm-build as dependency for opensuse systems

---

wrappers/services.go
wrappers/services_test.go

Refactor StopServices to make it easier to account for disabling user-services.
Changes from this refactor
* Now has a more identical flow to StartService in terms of ordering of user and system services, except in reverse.
* Correctly proxies the `--disable` request to the user-session agent.

wrappers: refactor StopServices to account for sending --disable to the user-session agent

---

overlord/snapstate/backend_test.go
overlord/snapstate/export_test.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_link_test.go
overlord/snapstate/snapstate_update_test.go

`defer lock.Close()` was placed after error handling which could leave the snap lock held. This regression was introduced in https://github.com/snapcore/snapd/pull/13599.
It seems that the lock file is closed on change failure, which hid this bug and makes it very hard to test.
I tried writing a test to capture the regression but the lock gets unlocked when testing. I am guessing this could be because of the goroutine holding the FDs getting killed?

o/snapstate: fix snap lock leak

---

.github/workflows/test.yaml

The idea is putting together in the github actions workflow all the spread test executions and use the groups to differentiate the nested and non nested tests.
With this change, we can reduce the complexity of this file by removing duplicated parts.

tests: unification between spread and spread-nested in workflow/test.yaml

---

.github/workflows/test.yaml

The idea of this change in to run on ubuntu trusty just the following
tests:
. tests/smoke/
. tests/main/canonical-livepatch
. tests/main/canonical-livepatch-14.04
Once #14032 is merged, this will just contain the changes related to trusty tests
spread-arm is not used anymore, so it is removed from the execution workflow.

tests: reduce tests for trusty

---

gadget/install/content.go
gadget/install/kernel.go
packaging/debian-sid/rules

We use debhelpers when building on Sid, but dh_golang is very 'automatic' and does not work well if the repository is complicated or makes use of build tags. Because of this we tend to 'modify' the code imperatively at build time (such that there's no need to maintain a bunch of additional patches for pieces which change often).
The branch addresses the build problem observed on Sid:
```
src/github.com/snapcore/snapd/gadget/install/install_dummy.go:33:65: undefined: KernelSnapInfo
src/github.com/snapcore/snapd/gadget/install/install_dummy.go:37:74: undefined: KernelSnapInfo
src/github.com/snapcore/snapd/gadget/install/install_dummy.go:41:151: undefined: KernelSnapInfo
```

packaging/debian-sid: gadget/install: fix build on debian sid

---

overlord/snapstate/handlers.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go

Since the prerequisites code can deal with app that depend on the model base, we can remove the code that sets up explicit dependencies between them. This also enables the app refresh to finish faster because the prereq code will only wait for the base to link and not to fully refresh (which requires the gadget/kernel to refresh, reboot,etc). Also, since this means all non-essential snaps are guaranteed to finish before the reboot, the rerefresh check can also always run before the reboot and we can simplify some of the associated logic.
Also lowers the prerequisites timeout since this makes split refreshes rely on it and 30 seconds is high.

o/snapstate: refactor/optimise dependency setup in split refresh

---

wrappers/services.go
wrappers/services_test.go

I've seen this atleast once in salesforce tickets, and recently experienced it myself. This effectively blocks removal of some snaps in very specific cases.
For instance take the fwupd snap:
```
philip@fadekraft-xps:~/Work/snapd/wrappers$ snap remove fwupd
error: cannot perform the following tasks:
- Stop snap "fwupd" services (systemctl command [stop snap.fwupd.fwupd.service] failed with exit status 5: stderr:
Failed to stop snap.fwupd.fwupd.service: Unit snap.fwupd.fwupd.service not loaded.)
``` 
I have fwupd installed as both a deb and a snap, and this causes systemctl to always return an issue when manipulating the service units for the snaps, as the deb package one loads first and is actually running. The error that systemctl reports is that two units are conflicting for dbus …

wrappers: only fail when stopping a service if it actually is still running

---

daemon/api_base_test.go
interfaces/ifacetest/app_set.go
interfaces/ifacetest/backendtest.go
interfaces/repo.go
interfaces/repo_test.go
overlord/devicestate/devicestate_test.go
overlord/ifacestate/handlers.go
overlord/ifacestate/helpers.go
overlord/ifacestate/helpers_test.go
overlord/ifacestate/hotplug_test.go
overlord/ifacestate/ifacemgr.go
overlord/ifacestate/ifacestate_test.go
overlord/managers_test.go
overlord/snapstate/autorefresh_gating_test.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_update_test.go
snap/validate_test.go

This change will enable us to inject an app set into the interfaces.Connected(Plug|Slot) types, which will allow interfaces to correctly generate label expressions for connected plugs/slots.

many: replace interfaces.Repository.AddSnap with AddAppSet

---

gadget/install/content.go
gadget/install/content_test.go
gadget/install/export_test.go
gadget/install/kernel.go
kernel/kernel_drivers.go
kernel/kernel_drivers_test.go
overlord/devicestate/handlers_install.go
overlord/snapstate/backend/setup.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_test.go
tests/lib/muinstaller/mk-classic-rootfs.sh
tests/lib/prepare-restore.sh
tests/lib/tools/lxd-state
tests/lib/tools/setup_nested_hybrid_system.sh
tests/nested/manual/muinstaller-core/task.yaml
tests/nested/manual/muinstaller-real/task.yaml

In some cases (when using the snapd install API or when installing
from initramfs), the place where the kernel snap / components used for the
installation are mounted is different to the final location in the
installed system. This change considers this so the drivers tree is
generated with symlinks pointing to the final expected location.
Additionally, fix `muinstaller-{core,real}` tests for core24.

many: build drivers tree when current mount is not the target mount

---

overlord/configstate/configcore/kernel.go
overlord/configstate/configcore/kernel_test.go

A bug was reported here (https://bugs.launchpad.net/snapd/+bug/2068874) relating to a derefencing of a nil structure. The real issue is that this code was invoked from a classic system, and the code clearly expects a gadget to be present on the system.
If we inspect the task handler for the resulting task, it would have errored out anyway:
overlord/devicestate/handlers_gadget.go:366.
```
if devCtx.IsClassicBoot() {
return fmt.Errorf("internal error: cannot run update gadget kernel command line task on a classic system")
}
```

o/configstate/configcore: guard against classic systems for kernel commandline params

---

daemon/api_sideload_n_try_test.go
interfaces/snap_app_set_test.go
snap/component.go
snap/component_test.go
snap/pack/pack_test.go

Add a `Provenance` to `snap.ComponentInfo`. This allows `snap pack` to work with components that define a provenance in their `component.yaml` file.

 many: add Provenance field to ComponentInfo

---

interfaces/builtin/network_manager.go

Network-manager on core24 seems to be accessing the /sys/net/mptcp paths now to detect whether MPTCP sockets are available.
More specifically `/proc/sys/net/mptcp/enabled` is being denied by apparmor, but we should allow network-manager to handle all the variables under this path.
This PR is to enable support for that in network-manager.
Docs for MPTCP: https://docs.kernel.org/networking/mptcp-sysctl.html

i/b/network_manager: add mptcp paths as available for network-manager to support MPTCP sockets

---

overlord/configstate/configcore/refresh.go
overlord/configstate/configcore/refresh_test.go
overlord/snapstate/autorefresh.go
overlord/snapstate/autorefresh_test.go
overlord/snapstate/export_test.go
overlord/snapstate/handlers_link_test.go
overlord/snapstate/refresh_test.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go

This patch allows to configure the number of days refresh is inhibited, between 1 and the current 14 days.
This patch implements proposal SD165. The rationale behind this is that 14 days is a reasonable value for a server, but not for a desktop, where users are, usually, less experienced than sysadmins, and so it is a good idea to keep updated the snaps faster.
The proposal is available at https://docs.google.com/document/d/1ZdKwvu-WRyAKLahFD7Tq_gEAwdt38VBu4KU6w31TZjo/edit?usp=sharing

o/configstate,o/snapstate: configurable refresh inhibition days number

---

overlord/devicestate/devicemgr.go
overlord/devicestate/devicestate_users_test.go
overlord/devicestate/export_test.go
overlord/devicestate/users.go
overlord/devicestate/users_test.go

Currently, if you attempt to create a user using a serial-bound assertion before the serial is available, the request will simply fail. This commit makes it so that attempts to create a system-user with a serial-bound assertion fail, but a flag is set within the device manager's state. Once the serial assertion is acquired, any serial-bound users will be created by the device manager's Ensure() function.
This is a reprise of #12852 applying my own feedback there

o/devicestate: create pending users after receiving a serial

---

.github/workflows/test.yaml
tests/lib/external/snapd-testing-tools/.github/workflows/tests.yaml
tests/lib/external/snapd-testing-tools/CODE_OF_CONDUCT.md
tests/lib/external/snapd-testing-tools/remote/remote.pull
tests/lib/external/snapd-testing-tools/spread.yaml
tests/lib/external/snapd-testing-tools/tests/log-analyzer/data/aborted-and-failed-execute-and-restore.json
tests/lib/external/snapd-testing-tools/tests/log-analyzer/data/all-aborted.json
tests/lib/external/snapd-testing-tools/tests/log-analyzer/data/all-failed.json
tests/lib/external/snapd-testing-tools/tests/log-analyzer/data/all-success-failed-restore.json
tests/lib/external/snapd-testing-tools/tests/log-analyzer/data/all-success.json
tests/lib/external/snapd-testing-tools/tests/log-analyzer/data/failed-prepare-and-restore.json
tests/lib/external/snapd-testing-tools/tests/log-analyzer/data/failed-prepare-project.json
tests/lib/external/snapd-testing-tools/tests/log-analyzer/data/failed-prepare-suite.json
tests/lib/external/snapd-testing-tools/tests/log-analyzer/data/failed-prepare-task.json
tests/lib/external/snapd-testing-tools/tests/log-analyzer/data/with-aborted-and-failed-restore.json
tests/lib/external/snapd-testing-tools/tests/log-analyzer/data/with-failed-and-failed-restore-suite.json
tests/lib/external/snapd-testing-tools/tests/log-filter/task.yaml
tests/lib/external/snapd-testing-tools/tests/log-parser/task.yaml
tests/lib/external/snapd-testing-tools/tests/log-parser/with-all-results.log.spread
tests/lib/external/snapd-testing-tools/tests/os.query/task.yaml
tests/lib/external/snapd-testing-tools/tests/remote.retry/task.yaml
tests/lib/external/snapd-testing-tools/utils/log-analyzer
tests/lib/external/snapd-testing-tools/utils/log-filter
tests/lib/external/snapd-testing-tools/utils/log-parser
tests/lib/external/snapd-testing-tools/utils/log_helper.py

The log utilities from snapd-testing-tools have been updated
1. log-helper: has enums instead of constants
2. log-parser: does not offer --print-details functions anymore, and the complexity was reduced. Also many other minor improvements have been implemented. 
3. log-analyzer: minor changes
4. minor fix in remote.pull to make it work in ubuntu noble with nested tests

tests: new spread log utils

---

osutil/fips/fips.go
osutil/fips/fips_test.go

Add a package with a helper for testing whether FIPS mode is enabled.

osutil/fips: helper for testing whether FIPS mode is enabled

---

tests/smoke/install/task.yaml

We run these tests in core-initrd PRs and we would like snapd debug traces enabled in that case.

tests/smoke/install: allow DEBUG traces in stderr output

---

registry/registry.go
registry/registry_test.go
registry/schema_test.go

Restricts paths of views to not allow numbers as the first character.

registry: restrict path patterns

---

interfaces/builtin/raw_usb.go

The Thinkpad x13s exposes USB device busnum files at a slightly different path:
apparmor="DENIED" operation="open" class="file" profile="snap.android-platform-tools.adb"
name="/sys/devices/platform/soc@0/a6f8800.usb/a600000.usb/xhci-hcd.1.auto/usb1/1-1/busnum"
pid=78132 comm="libusb_event" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Accommodate for that by adjusting the path in the generated AppArmor profile.

interfaces: Fixup raw_usb AppArmor path for the Thinkpad x13s

---

cmd/snap-seccomp/main.go

Recent change to seccomp processing has introduced a regression from commit 182b8ae699e39bd3707cec80777f58e5baed34c6 "snap-seccomp, snap-confine, i/seccomp, tests: rework seccomp denylist * snap-{seccomp,confine}: rework seccomp denylist" where the deny processing of devmode snaps was incorrectly logging *all* system calls (not denying, just logging). Restore the correct default action on the deny filter to "allow", as the deny filter explicitly denies on matching system calls.
Jira: SNAPDENG-22672
Thanks-To: Canonical Certification Team

cmd/snap-seccomp: fix default action on deny filter in devmode

---

.github/workflows/test.yaml
build-aux/snap/snapcraft.yaml

The branch adds support for building a FIPS variant of the snapd snap for the purpose of simply exercising that code in the github CI. The relevant patches were extracted from #13978. Note that we do not currently run any tests with that snap, nor use it for any other purpose than just having the build run and have the built snap available for download as artifact.

snapcraft, github: build a FIPS variant of the snap in CI

---

cmd/Makefile.am
cmd/snap-confine/snap-confine-args-test.c
cmd/snap-confine/snap-confine-args.c
cmd/snap-confine/snap-confine-args.h
interfaces/apparmor/backend.go
interfaces/apparmor/template.go
interfaces/builtin/system_observe.go
interfaces/systemd/backend.go
packaging/arch/PKGBUILD
packaging/debian-sid/snapd.install
packaging/fedora/snapd.spec
packaging/snapd.mk
packaging/ubuntu-14.04/snapd.install
packaging/ubuntu-16.04/snapd.install.in
sandbox/apparmor/profile_test.go
spread.yaml

The ubuntu-core-launcher is the old name of snap-confine, back in the early days of snapd 2.x where snapd was still generating shell scripts for launching all snap applications. There was no such code anywhere for nearly a decade and keeping the special mode around is not necessary anymore.
There are several changes broken out as distinct patches:
- removal of special mode from snap-confine argument parser
- removal of automake logic to install a symlink ubuntu-core-launcher -> snap-confine
- removal of installation or removal of ubuntu-core-launcher symlink in distribution packaging
- edits of comments referencing ubuntu-core-launcher in sandbox and interfaces packages
- tweak to spread.yaml comment referencing ubuntu-core-launcher
There are some remaining references that depend on the …

cmd,sandbox,interfaces: remove support for ubuntu-core-launcher

---

overlord/snapstate/handlers.go
overlord/snapstate/handlers_prereq_test.go

This fixes `google-nested:ubuntu-20.04-64:tests/nested/manual/remodel-offline:local_snaps`, which was failing when trying to talk to the store to install a prereq. This also updates a unit test to help prevent this regression in the future.

o/snapstate: properly ignore prereqs during remodels

---

.github/workflows/nightly.yaml

pylint is missing from the environment. TiCS uses pylint for CS of python.

tests: install pylint in nightly tiobe tics run

---

cmd/Makefile.am
cmd/libsnap-confine-private/snap-dir-test.c
cmd/libsnap-confine-private/snap-dir.c
cmd/libsnap-confine-private/snap-dir.h
cmd/libsnap-confine-private/snap.h

Add a pair of functions to probe, memoize and return the value of snap mount directory. The premise is to look at /snap in the initial mount namespace and depending on its absence or presence and type, and if it is a symbolic link, link target, either pick /snap, /var/lib/snapd/snap or die.
Jira: SNAPDENG-22335
Spec: SD-179

cmd/libsnap-confine-private: add snap mount dir detection

---

client/clientutil/snapinfo_test.go
client/components.go
client/packages.go
daemon/api_sideload_n_try.go
daemon/api_sideload_n_try_test.go
daemon/api_snaps_test.go
daemon/snap.go
overlord/snapstate/backend/link.go
snap/component.go
snap/component_test.go

Send back components information on GET /v2/snaps and GET /v2/snaps/{name} requests.

many: send components information on GET /v2/snaps

---

tests/main/lxd-mount-units/task.yaml
tests/main/lxd-postrm-purge/task.yaml
tests/main/lxd-try/task.yaml
tests/main/lxd/task.yaml

Use ubuntu-daily remote for 24.10.

tests/main/lxd: use ubuntu-daily for 24.10

---

daemon/snap.go

Information about components of a snap is repacked from a map to a list. Since map iteration does not guarantee stability, we need to sort the list of components to keep the tests reliable.
Fixes the following failure:
```
FAIL: api_snaps_test.go:1611: snapsSuite.TestMapLocalFieldsWithComponents
api_snaps_test.go:1809:
c.Check(daemon.MapLocal(about, nil), check.DeepEquals, expected)
... obtained *client.Snap = &client.Snap{...}
... expected *client.Snap = &client.Snap{...}
... Difference:
...     Components[2].Name: "comp-4" != "comp-3"
...     Components[2].Summary: "" != "summary 3"
...     Components[2].Description: "" != "description 3"
...     Components[3].Name: "comp-3" != "comp-4"
...     Components[3].Summary: "summary 3" != ""
...     Components[3].Description: "description 3" …
```

daemon: ensure stability of components list in snap info

---

spread.yaml

The test-snapd-rsync-core24 snap cannot be removed during reset because it is listed as broken when the initial state is restored.
This is needed to fix uc24 tests which are failing to prepare.

tests: skip removing test-snapd-rsync-core24 during reset

---

spread.yaml

This is to avoid issue like:
error: cannot extract "*" to "/home/test/tmp/kernel": -----
Write on output file failed because No space left on device FATAL ERROR: writer: failed to write file
/home/test/tmp/kernel/modules/5.4.0-182-generic/kernel/nvidia-535srv/bits/nvidia/nv-kernel.o

tests: add extra storage to arch vms in google cloud

---

build-aux/snap/snapcraft.yaml

A set of improvements for building the snapd snap cherry picked from https://github.com/snapcore/snapd/pull/13978/files. First, drop the `requirefips` build tag, as FIPS compliance enforcement will be enabled at runtime. Next, since we already have a FIPS enabled core22 snap published, use that snap as a donor of the FIPS openssl libraries and modules.

snapcraft: improve FIPS snap build, pull FIPS libraries from core22

---

daemon/api_snaps_test.go

The test creates two symbolic links but reuses some information about them by passing the same variable. Use the proper variable to avoid being sensitive to symlink mtime differences on fast enough systems.

daemon: fix racy tests caused by copy-pasted variable

---

tests/main/security-setuid-root/task.yaml

The debug section was always broken, as they do not share environment variables with the other sections.
This should fix an error seen in the wild:
2024-06-19 13:05:09 Error debugging
google:ubuntu-20.04-64:tests/main/security-setuid-root (jun191226-580356) :
/bin/bash: line 92: SNAP_MOUNT_DIR: unbound variable

tests: set SNAP_MOUNT_DIR in debug section

---

registry/registry.go
registry/registry_test.go

When creating registries, constrain view names to a simpler pattern (like the storage path elements).

registry:  validate view names on registry creation

---

asserts/account_key_test.go
asserts/asserts.go
asserts/asserts_test.go
asserts/constraint.go
asserts/constraint_test.go
asserts/export_test.go
asserts/ifacedecls.go
asserts/ifacedecls_test.go
asserts/snap_asserts.go
asserts/snap_asserts_test.go
interfaces/policy/helpers.go
interfaces/policy/policy.go
interfaces/policy/policy_test.go

Allow plugs to specify the $PLUG_PUBLISHER_ID reference in attribute constraints such that interfaces can restrict auto-connection to when certain attributes match their publisher IDs.

asserts: allow $PLUG_PUBLISHER_ID in plug attribute constraints

---

overlord/snapstate/backend_test.go
overlord/snapstate/component.go
overlord/snapstate/handlers_components.go
overlord/snapstate/handlers_components_download_test.go
overlord/snapstate/snapmgr.go

Implement a task handler for downloading components from the store. Will be used in subsequent PRs for installing components and snaps from the store at the same time.

o/snapstate: implement download-component handler

---

overlord/snapstate/component.go
overlord/snapstate/component_install_test.go
overlord/snapstate/component_test.go
overlord/snapstate/handlers_components.go
overlord/snapstate/handlers_components_prepare_test.go
overlord/snapstate/sequence/sequence.go
overlord/snapstate/sequence/sequence_test.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate_test.go

* Look at all sequence points to assign a local revision. We want it to be unique across all sequence points, as otherwise we would be duplicating file names.
* Look at all the sequence to find out if we can remove a component container when we are replacing it, as it might be used still in a non-current sequence point to where we might want to revert eventually.

o/snapstate: assign properly local revisions and be more careful when removing components

---

cmd/snap/cmd_snap_op.go
cmd/snap/cmd_snap_op_test.go
daemon/api_sideload_n_try.go
daemon/api_sideload_n_try_test.go
tests/main/component/task.yaml

Changes to start send and processing components data on installation. With this we can show better messages on installation of a local component.

cmd,daemon: changes in api data to show components information

---

overlord/configstate/configcore/proxy.go
overlord/configstate/configcore/proxy_test.go

Proxy entries added to /etc/environment did not end with a newline, hence any entries appended later manually, would end up being concatenated and produce garbage.

o/configstate/configcore: include newlines in proxy entries added to /etc/environment

---

interfaces/builtin/network_manager.go

Additional apparmor denials have come to light for both `nmcli` and `NetworkManager` - this time related to gnutls configuration, which is fine.
Notes around the gnutls configuration file (since it does not actually exist on core systems):
`If the file doesn't exist, built-in defaults are used. To make configuration changes, the /etc/gnutls directory and the config file in it must be created manually, since they are not shipped in the Ubuntu packaging.`
```
[   88.294738] audit: type=1400 audit(1718264509.595:842): apparmor="DENIED" operation="open" class="file" profile="snap.network-manager.nmcli" name="/etc/gnutls/config" pid=4871 comm="nmcli" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[   88.842027] audit: type=1400 audit(1718264510.142:844): apparmor="DENIED" operation="open" …
```

i/b/network_manager: allow access to gnutls config for both plug and slot

---

tests/lib/spread/backend.openstack.yaml

This is needed for the nightly cron job where we run all the openstack systems

tests: increase the number of workers we use in openstack

---

overlord/hookstate/context.go
overlord/hookstate/context_test.go
overlord/hookstate/hookmgr.go
overlord/hookstate/hooks.go
overlord/hookstate/hookstate_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_test.go

This change largely updates the hookstate package to enable running component hooks. At a high level, we add fields to the HookSetup struct to convey that a hook comes from a component, and we handle those properly.

o/hookstate: changes to enable running component hooks from the HookManager 

---

spread.yaml

Add Ubuntu Pro systems as a separate group.
Related: SNAPDENG-23245, SNAPDENG-23246

spread: add Ubuntu Pro systems

---

tests/main/interfaces-snap-refresh-observe/task.yaml
tests/main/snap-run-inhibition-flow/task.yaml
tests/main/theme-install/task.yaml

Python will try to guess the IO encoding based on the terminal, but apparently not all terminals support UTF-8, thus causing errors like this:
```
$ PYTHONIOENCODING="ascii" api-client --socket /run/snapd-snap.socket /v2/snaps Traceback (most recent call last):
File "/snap/api-client/x1/bin/api-client.py", line 40, in <module>
sys.exit(main(sys.argv))
File "/snap/api-client/x1/bin/api-client.py", line 36, in main
print(body.decode('UTF-8'))
UnicodeEncodeError: 'ascii' codec can't encode character '\xa0' in position 3183: ordinal not in range(128)
```

tests/main: override Python's IO encoding guess

---

overlord/snapstate/backend_test.go
overlord/snapstate/component.go
overlord/snapstate/component_install_test.go
overlord/snapstate/handlers_components.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_remove_test.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go
overlord/snapstate/target.go
overlord/snapstate/target_test.go
store/store_action.go
store/store_action_test.go

This PR enables us to install components and a snap from the store at the same time. Note that installing components from the store for an already installed snap is not yet handled yet, as that interaction with the store is more complex, requiring the usage of both channel and revision.
First relevant commit is 97dad459a4e9410994c02942c795b882c3e52791, based on https://github.com/snapcore/snapd/pull/14070.

o/snapstate: install components from the store

---

cmd/snap-repair/main.go
cmd/snap/main.go
cmd/snapd/main.go
snapdtool/export_test.go
snapdtool/fips_linux.go
snapdtool/fips_linux_test.go
snapdtool/fips_other.go
snapdtool/tool_linux.go
snapdtool/tool_linux_test.go
snapdtool/tool_test.go

Switch to FIPS compliance mode when the system has booted with FIPS enabled. Specifically, set GOFIPS=1 to enforce FIPS mode at runtime, and set up environment such that the relevant openssl modules can be located.

snapdtool, cmd: switch to FIPS mode when needed

---

asserts/registry.go
interfaces/builtin/registry.go
interfaces/builtin/registry_test.go
interfaces/policy/basedeclaration_test.go
registry/registry.go
run-checks

Add a registry interface that snaps can use to access a particular registry view.

i/builtin: add registry interface

---

snapdtool/tool_linux.go
snapdtool/tool_test.go
tests/main/command-chain/command-chain/meta/snap.yaml
tests/main/command-chain/task.yaml
tests/main/install-sideload/task.yaml
tests/main/snap-run-hook/task.yaml
tests/main/writable-areas/task.yaml

Snapd normally stops trying to reexec when the current host distribution is not
in the list of supported ones. However, allow reexec to be attempt if
SNAP_REEXEC is explicitly set to a truthy value in the environment. This enables
testing of the reexec functionality on a wider range of distributions.
Based on #13370

snapdtool: explicit opt-in for reexec

---

interfaces/repo.go
overlord/configstate/configcore/refresh.go
overlord/devicestate/devicestate.go
overlord/managers_test.go
overlord/snapstate/autorefresh.go
overlord/snapstate/autorefresh_test.go
overlord/snapstate/refreshhints.go
overlord/snapstate/refreshhints_test.go
overlord/snapstate/snapstate_test.go

Drop the additional check to CanManageRefreshes() when the refresh schedule is
already set to 'managed'. This was originally a way to ensure that there is at
least one snap entitled to directly manage the refreshes or fall back to the
default auto-refresh schedule. However, the conditions in which the fallback
would be applied are incorrect and could lead to a situation when snapd would
trigger an auto-refresh even while a snap which is entitled to using a managed
refresh schedule is being refreshed (due to the snapd-control being temporarily
disconnected). On top of this, since the device was once switched to managed, it
clearly means that it was entitled to do so and it was intentional, hence we
should not accidentally break the expectations.
An attempt to fix this was introduced in …

o/snapstate: make a managed refresh schedule not require any additional checks

---

tests/lib/spread/backend.openstack.yaml

ubuntu arm-64 is removed because it fails to boot in nightly 
ubuntu jammy and noble are added to be executed in nighty run

tests: updated the backends list used for openstack

---

.github/workflows/test.yaml
spread.yaml

Use log-filter tool to generate a .filtered.log file which is sent to grafana.
Those filtered logs don't include the error and debug output, just the executed tests and the results.

tests: filter spread logs to be sent to grafana

---

.woke.yaml
cmd/Makefile.am
cmd/libsnap-confine-private/snap-dir-test.c
cmd/libsnap-confine-private/snap-dir.c
cmd/libsnap-confine-private/test-utils.c
cmd/libsnap-confine-private/test-utils.h
cmd/snap-confine/mount-support.c
cmd/snap-confine/ns-support.c
cmd/snap-confine/snap-confine-args-test.c
cmd/snap-confine/snap-confine-args.c
cmd/snap-confine/snap-confine-invocation-test.c
cmd/snap-confine/snap-confine-invocation.c
cmd/snap-confine/snap-confine.apparmor.in
cmd/snap-confine/snap-confine.c

This is based on https://github.com/snapcore/snapd/pull/14068 which contains the first patch in this series (snap-dir.[ch] and snap-dir-test.c). Please disregard that when reviewing.
Bulk of the changes are related to testing sc-invocation. I can break that out if it helps. The rest is fairly straigtforward replacement of `SNAP_MOUNT_DIR` with `sc_snap_mount_dir(NULL)` except when it was used as a compile time string concatenation (only in tests) where a sligthly more verbose construct is in use.
The apparmor profile has two changes: one to allow it to probe (stat,readlink) `/proc/1/root/snap`. This change is contained in the patch "cmd/snap-confine: probe SNAP_MOUNT_DIR on startup". The second change is to remove `@SNAP_MOUNT_DIR@` - sed text replacement - from snap-confie.apparmor.in …

cmd/snap-confine: switch to dynamic SNAP_MOUNT_DIR

---

cmd/snapd/main.go
daemon/api_aliases_test.go
daemon/api_cohort.go
daemon/api_download.go
daemon/api_notices.go
daemon/api_notices_test.go
daemon/api_sections.go
daemon/api_sideload_n_try.go
daemon/api_snaps.go
daemon/api_snaps_test.go
daemon/api_snapshots.go
daemon/api_snapshots_test.go
daemon/daemon.go
daemon/daemon_test.go
overlord/snapstate/snapstate.go

This is another take at #13961, but this time around the branch is attempting at a refactor of how the context is propagated and how it interacts with cancelation.
Related: SNAPDENG-22871

daemon, cmd/snapd: propagate context

---

tests/main/upgrade-from-release/task.yaml

update the test to include the proper snapd version and skip it in ubuntu  24.10

tests: fix upgrade-from-release test in ubuntu noble

---

interfaces/builtin/lxd_support.go
interfaces/builtin/lxd_support_test.go

Set controls-device-cgroup flag for lxd-support interface, thus allowing LXD to self manage the device cgroup and also be exempt from the mandatory device cgroup set up with core24 base.

interfaces/builtin/lxd-support: allow LXD to manage its own cgroup

---

tests/main/fake-netplan-apply/task.yaml

Add workaround for Ubuntu 24.10

tests/main/fake-netplan-apply: support for Ubuntu 24.10

---

interfaces/builtin/desktop_launch_test.go
interfaces/builtin/desktop_legacy.go
interfaces/builtin/unity7.go
interfaces/builtin/utils.go
interfaces/builtin/utils_test.go

The interface 'desktop-legacy' (and 'unity7') specifically denies read access to the .desktop files, which means that any extension that requires it (like gnome or kde) won't be able to read them.
Unfortunately, there are some specific cases where reading the .desktop files is mandatory, like when implementing the new Refresh Awareness specification. This specification requires to show the "visible name" of a snap, and its icon, and in order to have access to that, it is mandatory to be able to read the .desktop files.
The 'desktop-launch' interface does include read access to the .desktop files. Although it is a very privileged interface, it is not a problem because the snaps that implement the Refresh Awareness specification are too, so using it to gain access to the .desktop files …

interfaces: give priority to desktop-launch over desktop-legacy

---

.github/workflows/test.yaml

Currently all the changes sent to grafana are sent as main because the check in the testing workflow is done incorrectly

tests: fix change_id used for grafana

---

overlord/devicestate/firstboot.go
overlord/snapstate/component.go
overlord/snapstate/handlers_components.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/target.go
overlord/snapstate/target_test.go

This allows us to install snaps and components from files at the same time. Based on https://github.com/snapcore/snapd/pull/14092, first commit is 12afed26cc9e5e454233a7b838b0cbf26ad7dc54.

o/snapstate: install components and snaps from file

---

overlord/snapstate/handlers.go
overlord/snapstate/handlers_prereq_test.go

In https://github.com/snapcore/snapd/pull/14088 I broke `tests/nested/manual/hybrid-remodel` when attempting to fix a different bug. By moving the remodeling check, I accidentally omitted checking for remodeling when updating a prereq. This change makes sure that we check for remodeling when installing and updating prereqs.

o/snapstate: account for remodeling when installing prereqs as well as updating them

---

daemon/daemon.go

Data race was picked up in the tests:
```
Write at 0x00c00041a648 by goroutine 175:
github.com/snapcore/snapd/daemon.(*Daemon).HandleRestart()
/home/runner/work/snapd/snapd/src/github.com/snapcore/snapd/daemon/daemon.go:446 +0x198
github.com/snapcore/snapd/overlord/restart.(*RestartManager).handleRestart()
/home/runner/work/snapd/snapd/src/github.com/snapcore/snapd/overlord/restart/restart.go:242 +0x10e
github.com/snapcore/snapd/overlord/restart.Request()
/home/runner/work/snapd/snapd/src/github.com/snapcore/snapd/overlord/restart/restart.go:348 +0xd0
github.com/snapcore/snapd/overlord/standby.(*StandbyOpinions).Start.func1()
/home/runner/work/snapd/snapd/src/github.com/snapcore/snapd/overlord/standby/standby.go:102 +0xe4
Previous read at …
```

daemon: fix data race accessing requestedRestart

---

.github/workflows/test.yaml
build-aux/snap/snapcraft.yaml
spread.yaml
tests/lib/nested.sh
tests/lib/prepare.sh
tests/lib/tools/snaps-state
tests/lib/uc20-recovery.sh
tests/main/preseed-core20/task.yaml
tests/main/preseed-lxd/task.yaml
tests/main/preseed/task.yaml
tests/main/snap-seccomp/task.yaml
tests/main/snapd-without-core/task.yaml
tests/main/snaps-state/task.yaml
tests/nested/manual/cloud-init-never-used-not-vuln/task.yaml
tests/nested/manual/cloud-init-nocloud-not-vuln/task.yaml
tests/nested/manual/core20-boot-config-update/task.yaml
tests/nested/manual/core20-new-snapd-does-not-break-old-initrd/task.yaml
tests/nested/manual/preseed/task.yaml
tests/nested/manual/snapd-refresh-from-old/task.yaml
tests/nested/manual/snapd-removes-vulnerable-snap-confine-revs/task.yaml

Now we build also the test version of snapd snap in `snap-builds` workflow job. We copy this into the spread tests. And we use that snap, which we only instrument instead of copying the snapd deb build.
If the snap is not available, then we build it in spread. On CI, this happens on arm since the workflow does not build it. It will also happen when triggering test manually.

tests: properly build snapd snap

---

data/Makefile
data/polkit/Makefile
packaging/arch/PKGBUILD
packaging/debian-sid/snapd.install
packaging/fedora/snapd.spec
packaging/opensuse/snapd.spec
packaging/ubuntu-14.04/snapd.install
packaging/ubuntu-16.04/snapd.install.in

With the refactoring of the snapcraft packaging in #13370, the polkit policy file got dropped from the snap. Core Desktop depends on this for polkit authorisation to work correctly.
This PR installs the policy file via the makefile in `data/` rather than duplicating it in each distro packaging script.

data, packaging: install polkit policy files via data Makefile

---

interfaces/builtin/custom_device.go
interfaces/builtin/custom_device_test.go

`custom-device` gives [rw apparmor rule](https://github.com/snapcore/snapd/blob/master/interfaces/builtin/custom_device.go#L332) while `rwk` is needed for some device (i.e: /dev/AMA0, the serial port on PI 4).
The raw-usb interface access rights to [/dev/ttyUSB* with rwk](https://github.com/snapcore/snapd/blob/master/interfaces/builtin/raw_usb.go#L38).
This PR replace in the `custom-device` interface the permissions for write device from `rw` to `rwk`.

i/builtin: enable locking in apparmor custom-device for device write

---

interfaces/builtin/raw_usb.go

The Raspberry Pi 5 has a totally [reworked USB topology](https://www.raspberrypi.com/news/rp1-the-silicon-controlling-raspberry-pi-5-i-o-designed-here-at-raspberry-pi/#:~:text=USB%20topology%20for%20improved%20bandwidth). This also means the USB devices are available under a different path under `/sys/devices/platform`. 
A `tree` of `/sys/devices/platform/axi` is attached: 
[tree-sys.device.platform.axi.txt](https://github.com/user-attachments/files/16065757/tree-sys.device.platform.axi.txt)
This PR adds the two new paths for the Raspberry Pi 5 to the `raw-usb` interface.
Solves LP bug: https://bugs.launchpad.net/snapd/+bug/2071319

interfaces/builtin/raw-usb: add Raspberry Pi 5 raw-usb paths

---

client/client.go
cmd/snap/cmd_debug_api.go

Add a new `snap debug api` command which can be used to execute raw queries against snapd API. This is supposed to be a replacement for curl which is not part of the base snaps and thus, especially on core, needs to be installed separately using --devmode.
Trigger snap refresh:
```
$ echo '{"action": "refresh"}' | sudo SNAPD_DEBUG=1 snap debug api --pretty \
-X POST -H  'Content-Type=application/json' '/v2/snaps/toolbox'
2024/06/24 12:32:39.856855 logger.go:93: DEBUG: re-exec not supported on distro "arch" yet
2024/06/24 12:32:39.857264 logger.go:93: DEBUG: url: /v2/snaps/toolbox
2024/06/24 12:32:39.857275 logger.go:93: DEBUG: query: 
2024/06/24 12:32:39.857280 logger.go:93: DEBUG: headers: map[Content-Type:application/json]
{
"change": "2992",
"result": null,
"status": "Accepted", …
```

cmd/snap: add `debug api` command

---

overlord/hookstate/ctlcmd/helpers.go
overlord/hookstate/ctlcmd/services_test.go
overlord/hookstate/ctlcmd/start.go

This PR queues `snapctl` services' commands to be run after the `default-configure` similar to what is done for configure hook #4070. This is to avoid a problem where the service doesn't see a new value if it uses `snapctl get ...`, because it's still not committed by `default-configure` hook similar to what was described in [LP#2047949](https://bugs.launchpad.net/snapd/+bug/2047949) .
Fixes: https://bugs.launchpad.net/snapd/+bug/2047949

o/hookstate/ctlcmd: queue service commands if run from default-configure hook

---

overlord/hookstate/ctlcmd/get.go
overlord/hookstate/ctlcmd/get_test.go
overlord/hookstate/ctlcmd/is_connected_test.go
overlord/registrystate/registrystate.go
overlord/registrystate/registrystate_test.go
registry/registry.go
registry/registry_test.go
registry/transaction.go
registry/transaction_test.go

Adds registry support to `snapctl get` so snaps can access registry views, if they have a matching connected plug for the view and if the registry assertion can be found (locally, for now).

o/h/ctlcmd: support reading registry views in snapctl

---

tests/main/apt-hooks/task.yaml

The error message installing a package that cannot be located has changed.

tests: fix apt-hooks in ubuntu oracular

---

interfaces/builtin/cpu_control.go
interfaces/builtin/cpu_control_test.go

Some applications like real-time ones often need to control the CPU C-state. 
Which is a capability that makes sense to be added in cpu-control interface.
- add: AppArmor rule to access cpu_dma_latency device node.
- add: udev rule to allow access of cpu_dma_latency device node.
- add: unit test for udev rule
see: https://docs.kernel.org/power/pm_qos_interface.html#pm-qos-framework

interfaces/builtin/cpu-control: add CPU c-state switch capability

---

interfaces/builtin/display_control.go
interfaces/builtin/display_control_test.go

This PR allows developers to control brightness and backlight power of LVDS screen.

interfaces/display-control: allow changing lvds backlight brightness and power

---

interfaces/apparmor/spec.go
interfaces/apparmor/spec_test.go
interfaces/builtin/all_test.go
interfaces/builtin/desktop_launch.go
interfaces/builtin/desktop_legacy.go
interfaces/builtin/unity7.go
interfaces/builtin/utils.go
interfaces/builtin/utils_test.go
interfaces/connection.go

AppArmor rules that forbid access to a resource have more priority than rules that allow access to those same resources. This means that if an interface restricts access to an specific resource, it won't be possible to enable access to that same resource from another, more privileged, interface.
An example of this is reading the .desktop files of all the installed snaps in the system: the superprivileged interface 'desktop-launch' enables access to these files, so any snap that has a connected plug for this interface should be able to read them. Unfortunately, the 'desktop-legacy' interface explicitly denies access to these files, and since it is connected automatically if a snap uses the 'desktop' or the 'unity7' interfaces, this mean that no graphical application will be able to read …

i/apparmor: add snippets with priorities

---

cmd/snap/cmd_snap_op.go
cmd/snap/cmd_snap_op_test.go

Make sure that snap refresh/install does not crash if a change has no api data. This is not happening in usual interactions with the store, but it does in some cases when we use the fakestore, which is breaking some integration tests.
The error seen when this happens is:
```
2024-07-08T15:13:08.6779600Z goroutine 1 [running]:
2024-07-08T15:13:08.6780335Z main.main.func1()
2024-07-08T15:13:08.6781075Z /home/gopath/src/github.com/snapcore/snapd/cmd/snap/main.go:497 +0x54
2024-07-08T15:13:08.6781480Z panic({0x558477cadfe0?, 0x558478289ba0?})
2024-07-08T15:13:08.6782031Z /usr/lib/go-1.22/src/runtime/panic.go:770 +0x132
2024-07-08T15:13:08.6782516Z main.(*changedSnapsData).hasChanges(...)
2024-07-08T15:13:08.6783130Z /home/gopath/src/github.com/snapcore/snapd/cmd/snap/cmd_snap_op.go:387 …
```

cmd: make sure there are no crashes if no api data is returned

---

overlord/assertstate/assertmgr.go
overlord/devicestate/firstboot.go
overlord/ifacestate/handlers.go
overlord/ifacestate/helpers.go
overlord/ifacestate/ifacestate_test.go
overlord/snapstate/handlers_components.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate.go
overlord/snapstate/target.go
snap/component.go

We're using `TODO:COMPS` to make component-related TODOs harder to forget. This change updates already-existing TODOs I've written related to components. I also removed a few outdated TODOs that have been addressed.

many: update component-related TODOs to use TODO:COMPS

---

cmd/snap/cmd_prepare_image.go
cmd/snap/cmd_prepare_image_test.go
image/image_linux.go
image/image_test.go
image/options.go
overlord/devicestate/systems.go
seed/internal/options20.go
seed/internal/options20_test.go
seed/seedtest/sample.go
seed/seedtest/seedtest.go
seed/seedwriter/seed16.go
seed/seedwriter/seed20.go
seed/seedwriter/writer.go
seed/seedwriter/writer_test.go

This is a first PR that adds support for seeding components. The parts targeted by this PR are:
- Add support for components in options.yaml
- Add --comp option to snap prepare-image, for local component files of component names
- Copy local component files to seed
Interactions with the store are not in this PR.

many: support adding local components to seeds

---

interfaces/prompting/constraints.go
interfaces/prompting/constraints_test.go
sandbox/apparmor/notify/permission.go

It was previously believed that `AA_MAY_SETATTR` and `AA_MAY_GETATTR` would not appear in notification messages from the kernel. However, that is not the case, and we want to be able to handle these similar to other writes and reads, respectively. As such, add them to the permissions map for the home interface.
This should address a bug identified by @sminez and tracked as part of SNAPDENG-23750 and related to https://github.com/canonical/aa-prompting-test/pull/12 and https://github.com/canonical/aa-prompting-test/pull/15.

i/prompting/constraints: map get-attr and set-attr to read and write

---

spread.yaml
tests/lib/prepare.sh

This change fixes 2 errors when ubuntu core tests are executed on master branch.
2024-07-12T15:38:24.0440669Z FATAL ERROR: dir_scan: failed to make directory /tmp/core24-snap/bin.usr-is-merged, because File exists
and also
2024-07-12T15:22:48.6292243Z 2024-07-12 15:22:39.558 :: Write failed because No space left on device

tests: fix errors building ubuntu core

---

sandbox/apparmor/apparmor_test.go

An octal-looking 755 mode managed to land without upsetting tests. Add a leading zero to make the values octal.

sandbox/apparmor: fix file permissions used in tests

---

tests/nested/manual/core20-4k-sector-size/task.yaml

xxd is from vim. od from coreutils.

tests/nested/manual/core20-4k-sector-size: do not assume we have xxd

---

cmd/snap/cmd_version_linux.go
cmd/snap/cmd_version_test.go

Commit 1adae138ee8c489f959a29fc0ee349d697409bfb ("sanity: refuse to try to do things on WSL.") disabled snap version from attempting to talk to snapd whenever WSL was detected, as WSL 1 didn't support enough of the Linux features for snapd to meaningfully operate. Ever since WSL 2 was released, this is now significantly different, with almost all of the features working out of the box.
Adjust the condition to look for WSL 1 specifically and add missing tests checking both WSL 1 and WSL 2 behavior.
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-23939

cmd/snap: allow normal snap --version on WSL 2

---

interfaces/builtin/u2f_devices.go

Token2 is planning the launch of three new security keys, which will feature OpenPGP applets accessible via USB. These keys use a different set of PID (depending on transport combination) that need to be recognized by snapd

interfaces: add new u2f token2 security keys

---

tests/lib/state.sh

Subdirectories of this folder and mounted in /lib/{modules,firmware} and if we remove it we would end up unable to load kernel modules.

tests/lib: do not touch /var/lib/snapd/kernel when restoring state

---

interfaces/builtin/polkit.go

Existing logic was looking only at the first mount option but there is no guarantee that "rw" or "ro" shows up as the first option. Use OptBool to check for the right option reliably.

interfaces/builtin: fix polkit rw/ro check

---

tests/nested/manual/split-refresh/task.yaml

The split-refresh test needs to be adapted to UC24 changes, similar to the muinstaller tests (cf2ef86).

tests/nested: adapt split-refresh test to UC24 changes

---

image/image_linux.go
overlord/snapstate/backend_test.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/target.go
overlord/snapstate/target_test.go
store/store_action.go
store/tooling/tooling.go
store/tooling/tooling_test.go
tests/main/mix-revision-and-channel/task.yaml

This removes the code that silently removes channels from actions that are sent to the store when the action also contains a channel.
We do continue to remove the channel when an action either contains specific validation sets, or if the action's revision comes from an enforced validation set.

o/snapstate, tests: allow mixing revision and channel on snap install

---

.github/workflows/nightly.yaml

tests: remove "Uploading TICS logs" step from static check

---

overlord/snapstate/snapstate_test.go

golangci-lint is failing on master due to a test type that become unused in the recent snapstate refactor
https://github.com/snapcore/snapd/actions/runs/9987375764/job/27601677610

o/snapstate: remove unused test type

---

.github/workflows/test.yaml

This is a required step to move snapd project under canonical org.
In canonical org we have shared github action runners with no spread installed. So, by using this tag, we make sure we run on runners with spread installed.

tests: support running tests in github agents with spread-enabled tag

---

tests/lib/spread/backend.openstack.yaml

This helps to avoid using an image which has not been created for our
project

tests: update openstack image names

---

cmd/Makefile.am

When tests show a leak picked up by valgrind, report details of the leak to aid developers in fixing without having to reproduce again.

cmd: show leak details if valgrind is present

---

cmd/snapd-apparmor/main.go
cmd/snapd-apparmor/main_test.go

This fixes broken unit tests that don't work on WSL-2 environment due to incorrect assumption about the host environment and also change the non-test code to *disable* attempts to use apparmor on WSL-2.
The reason for this is articulated in 35e15ecdc27a0700108c4c77dbfb7a076b5f5c78 but mainly, because it just doesn't work unless you have a custom kernel and run only one distribution at a time.
Once AppArmor is enabled in the Microsoft distribution of the Linux kernel, and once stacking is enabled in the Microsoft WSL init process, then we can drop most of the special-casing for WSL and just treat WSL-2-with-apparmor-and-apparmor-stacking as a LXD container with internal policy. Before that time comes, this is a more sane approach.
We can consider a follow-up that adds an environment …

cmd/snapd-apparmor: disable on WSL-1 and 2, fix tests

---

interfaces/builtin/export_test.go
interfaces/builtin/polkit.go
interfaces/builtin/polkit_test.go

Polkit unit tests depend on the host /proc/self/mounts and two possible locations of polkitd executable. This is fragile and incorrect for unit tests. Recently we realized that the LoadMountProfile function has fails to parse real entries generated by the kernel, when the mount options field contains spaces.
Isolate polkit tests by mocking the locations read by interface methods and by overriding StaticInfo so that tests can replace the mount profile location to inspect. Separate testing of core-specific conditions to a dedicated test.
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-23799

interfaces/builtin: isolate polkit tests from the host

---

tests/lib/preseed.sh
tests/nested/manual/preseed/task.yaml

Create seed dir if non exists because in Ubuntu 24.04 there is no longer any seeded snaps in base or minimal cloud images.
- https://bugs.launchpad.net/ubuntu/+source/ubuntu-meta/+bug/2051346
- https://bugs.launchpad.net/ubuntu/+source/ubuntu-meta/+bug/2051572

tests: create empty seed dir for images without seed

---

interfaces/builtin/steam_support.go
interfaces/builtin/steam_support_test.go
sandbox/apparmor/apparmor.go
sandbox/apparmor/apparmor_test.go

This is implemented by @jrjohansen but I will garden tests and ensure it can land.
Technically the feature works as is today but can benefit from AppArmor 4.0.2 (unreleased). We will most likely want to add https://github.com/snapcore/snapd/pull/14167 to ensure that we can use apparmor from the host to the full extent and to create a new PR updating bundled apparmor (inside snapd snap) once a release is available upstream.
Replacement for: https://github.com/snapcore/snapd/pull/14211

interfaces: adjust steam to allow all apparmor permissions

---

sandbox/apparmor/apparmor.go
sandbox/apparmor/apparmor_test.go

The state of AppArmor 4 in Ubuntu 24.04 and 24.10 is now sufficient for
using in snapd. The recently-added version-aware feature check guarantee
that features such as mqueue are not used when the parser is not
sufficiently up-to-date.

sandbox/apparmor: do not skip ABI 4.0 from host parser

---

.woke.yaml
cmd/libsnap-confine-private/snap-test.c
cmd/libsnap-confine-private/snap.c
cmd/libsnap-confine-private/snap.h
cmd/libsnap-confine-private/string-utils-test.c
cmd/libsnap-confine-private/string-utils.c
cmd/libsnap-confine-private/string-utils.h
cmd/snap-confine/snap-confine-invocation-test.c
cmd/snap-confine/snap-confine-invocation.c
cmd/snap-confine/snap-confine-invocation.h
cmd/snap-confine/snap-confine.c
cmd/snap-device-helper/snap-device-helper-test.c
cmd/snap-device-helper/snap-device-helper.c
interfaces/ifacetest/app_set.go
interfaces/udev/spec.go
interfaces/udev/spec_test.go

This PR teaches `snap-confine` and `snap-device-helper` how to parse security tags that represent component hooks.
An example of a security tag from a component hook would be: `snap.name+comp.hook.install`
And one with an instance key: `snap.name_instance+comp.hook.install`
Something important to note is how these are encoded as udev tags. Currently, when converting a security tag to a udev tag, we replace all `.` characters in the tag with `_` characters because systemd limits udev tags to having only alphanumeric characters, with the addition of the characters `-` and `_`. Since security tags can now contain `+`
characters, those will be encoded as two consecutive `_` characters.
For example:
```
"snap.name+comp.hook.install" -> "snap_name__comp_hook_install" …
```

c/snap-confine, i/udev, i/ifacetest: update snap-confine and snap-device-helper to understand component hook security tags

---

run-spread

This new script builds snapd snap using snapcraft locally previous to run the spread tests. Then this snap is used to prepare the instances in the desired backend as it is done in the CI
When re run spread from localhost it could be very usefull to avoid long waits during prepare stage (while the snapd snap is built)

tests: new script used to build snapd and run tests from localhost

---

interfaces/builtin/steam_support.go
interfaces/builtin/steam_support_test.go
sandbox/apparmor/apparmor.go
sandbox/apparmor/apparmor_test.go

This is v2 of an attepmt to transition steam to a permissive allow-all apparmor profile. The earlier attempt https://github.com/snapcore/snapd/pull/14216 was reverted as it broke on some systems that lacked apparmor parser capable of emitting mqueue and userns mediation classes.
This v2 approach is largely the same except that the sandbox module now identifies io-uring as an apparmor feature and emits the pre-allow-all (largely for apparmor 3.x systems) profile based on a fixed snippet followed by three conditional snippets: one for mqueue, userns and io_uring.
Support for io_uring was merged in June 2023 but has only been released in the 4.x series. It may have been backported to some distributions hence the feature support test.

interfaces,sandbox: transition steam to permissive apparmor profile

---

tests/main/sudo-env/task.yaml

With update of sudo to 1.9.15.p5-2 in Arch, sudo's secure_path is enabled by default through:
https://gitlab.archlinux.org/archlinux/packaging/packages/sudo/-/commit/e5e504db273b7b0a3990da6a8acf9d515d654ec6
Account for this in the test and verify the workaround added to archwiki at https://wiki.archlinux.org/title/Snap#Sudo
Related: SNAPDENG-25371

tests/main/sudo-env: add Arch to distros using secure_path, verify workaround

---

.github/workflows/test.yaml
spread.yaml
tests/lib/prepare-restore.sh

We've been experiencing failures to prepare Debian systems caused by *.pyc files related to one of the log analyzers:
```
dpkg-source: error: cannot represent change to tests/lib/external/snapd-testing-tools/utils/__pycache__/log_helper.cpython-310.pyc: binary file contents changed
```
Since the files may be created at any time, and spread may be used interactively on a stateful host, use defense-in-depth approach by filtering out `*.pyc` files in both spread and tar, and by attempting not to write them when starting log analyzers from the host running spread.
A pair of drive-by `retry` simplifications is included.

tests,github,spread: fix debian prepare logic

---

spread.yaml

I see several preseed tests failing in master branch because no disk space.
This change adds more space for the failing systems.

tests: fix preseed tests

---

interfaces/builtin/export_test.go
interfaces/builtin/polkit.go
interfaces/builtin/polkit_test.go

We used to parse the mount table, which is fragile and complex. Instead we can
just use access(2) to ask the kernel for a simple yes-or-no answer.
Thanks to James Henstridge (@jhenstridge) for the suggestion.
This is stacked on top of https://github.com/snapcore/snapd/pull/14184 for convenience.

interfaces: simplify checks for polkit actions

---

daemon/api_find_test.go
overlord/snapstate/refreshhints.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_update_test.go
overlord/snapstate/storehelpers.go
overlord/snapstate/target.go
tests/main/refresh-all/task.yaml

This fixes a bug that was introduced in #14146. This is one of many ways to do this, so let me know if you think this should be done somehow else.
The source of the bug is the fact that our `updatePlan` just collects snaps to be refreshed, and `doUpdate` now makes the decision on if they should be updated or not. Since this decision moved later in the set of operations, all of the snaps ended up being returned by `snapstate.RefreshCandidates`.
Working on spread tests now, should be pushed shortly.

o/snapstate: only return snaps that are changing revisions during refresh from snapstate.RefreshCandidates

---

asserts/snap_asserts.go
asserts/validation_set.go
asserts/validation_set_test.go

This adds components to validation sets, with this schema:
```
type:         validation-set
authority-id: <authority account id>
series:       16
account-id:   <account-id>
name:         <validation set name>
revision:     <int>
sequence:     <int>
snaps:
- name:     <snap-name>
id:       <snap id>
presence: "required"|"optional"|"invalid" # optional
revision: <n> # the revision of the snap. optional
components:   # optional
<component-name-1>: "optional"|"required"|"invalid" # presence
<component-name-2>:
presence: "optional"|"required"|"invalid"           
revision: <n> # optional
```

asserts: extend validation-set assertions to understand components

---

interfaces/builtin/steam_support.go
interfaces/builtin/steam_support_test.go

To match similar changes to apparmor, steam-support will no longer restrict launched games with a seccomp profile. Steam still relies on an internal sandbox system, and the interaction of the two sandboxes has had ill effects historically, with broken features, degraded performance (real-time scheduling) or extensive logging.
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-24864

interfaces: switch steam to unrestricted seccomp profile

---

interfaces/prompting/prompting.go
interfaces/prompting/prompting_test.go
interfaces/prompting/requestprompts/export_test.go
interfaces/prompting/requestprompts/requestprompts.go
interfaces/prompting/requestprompts/requestprompts_test.go

This is part of ongoing work to support AppArmor Prompting. When a request is received from the listener, a prompt is created with information which is provided to the user so that they may decide whether to allow or deny the requested action. This package manages the prompt database and individual request prompts.
This task is tracked internally by SNAPDENG-8329

i/prompting/requestprompts: add package to manage outstanding request prompts

---

wrappers/services.go
wrappers/services_test.go

LP bug that triggered this fix: https://bugs.launchpad.net/snapd/+bug/2028141
The issue was that the restart code was not dealing correctly with activated services. Instead of restarting the activator units (i.e sockets, timers) for an activated service, it would just go ahead and restart the primary unit. This would start otherwise unwanted services that previously was not running (but reported enabled to the code as the activator units are enabled).
Cover this case in unit tests and correctly deal with activated services.

wrappers: correctly deal with activated services during service restart

---

cmd/snap/cmd_download.go
image/helpers.go
image/image_linux.go
image/image_test.go
overlord/devicestate/systems.go
overlord/snapstate/target.go
overlord/snapstate/target_test.go
seed/seedtest/seedtest.go
seed/seedwriter/seed20.go
seed/seedwriter/writer.go
seed/seedwriter/writer_test.go
tests/lib/assertions/pc24-with-comps-dangerous.json
tests/lib/assertions/pc24-with-comps-dangerous.model
tests/lib/assertions/pc24-with-comps-signed.json
tests/lib/assertions/pc24-with-comps-signed.model
tests/main/prepare-image-components/task.yaml

Support creating seeds with components and related assertions that are downloaded from the store.

many: add support for seeding components from the store

---

wrappers/services.go
wrappers/services_test.go

Cleans up the StartServices function, and improves how we start services that are affected by activated units, and also how we undo start of those.

wrappers: wrappers: cleanup and improve how we start/undo start services

---

boot/assets_test.go
boot/boot_test.go
boot/bootchain.go
boot/export_test.go
boot/model_test.go
boot/seal.go
boot/seal_test.go
boot/systems_test.go
overlord/fdestate/backend/reseal.go
overlord/fdestate/fdemgr.go
overlord/fdestate/fdemgr_test.go
overlord/managers_test.go

We also make the FDE state manager install the the backend function to be associated with the state.

many: move resealing backend from boot to fdestate's backend

---

daemon/api.go
daemon/api_snaps.go
daemon/api_snaps_test.go
daemon/export_test.go
overlord/snapstate/snapstate.go

This is needed in preparation for the new `snap remove --terminate` flag.
This PR introduces the `terminate` REST API flag which is passed through to remove operations and will be used later to kill running snap apps and services.
This PR is part 2 of implementing force removal of snaps according to [SD174 - Force removal of snaps](https://docs.google.com/document/d/1ikDI-vPJO6YYFHOyFJ5hfK5L5Gv8voMeY8HJvxNWujw/edit#bookmark=id.5l2budzsqbb) spec.
For context:
- Part 1: https://github.com/snapcore/snapd/pull/14126
- Part 3.1: https://github.com/snapcore/snapd/pull/14160
- Part 3.2: https://github.com/snapcore/snapd/pull/14189

daemon: add terminate flag to snap remove action

---

cmd/snap/cmd_run.go
cmd/snap/cmd_run_test.go
cmd/snap/export_test.go
cmd/snap/inhibit.go
cmd/snap/inhibit_test.go
cmd/snaplock/runinhibit/inhibit.go

This is needed in preparation for the new `snap remove` `--terminate` flag.
New snap app runs must be inhibited before we start killing the running apps to avoid having new runs in the window between killing currently running and unlinking the snap binaries.
This PR is part 1 of implementing force removal of snaps according to [SD174 - Force removal of snaps](https://docs.google.com/document/d/1ikDI-vPJO6YYFHOyFJ5hfK5L5Gv8voMeY8HJvxNWujw/edit#bookmark=id.loect9uz09x5) spec.
For context:
- Part 2: https://github.com/snapcore/snapd/pull/14144
- Part 3.1: https://github.com/snapcore/snapd/pull/14160
- Part 3.2: https://github.com/snapcore/snapd/pull/14189

cmd/snap: inhibit snap run during snap removal

---

snap/info.go
snap/info_test.go
snap/types.go
systemd/emulation.go
systemd/systemd.go
systemd/systemd_test.go
usersession/agent/export_test.go
usersession/agent/response.go
usersession/agent/rest_api.go
usersession/agent/rest_api_test.go
usersession/client/client.go
usersession/client/client_test.go

This is needed in preparation for the new `snap remove --terminate` flag.
This PR introduces a new `/v1/app-control` userd endpoint that currently only support killing snap apps. This endpoint will be invoked by snapd during removal of snaps when the `--terminate` flag is used.
Calling `client.AppsKill` would do the following for each user session:
- Find running snap apps transient scope units (matching pattern `snap.<snap-name>.*.scope`)
- Send SIGKILL signal to those running snap apps
Looking up snap's transient units and killing them is delegated to systemd by calling `systemctl`.
This PR is part 3.1 of implementing force removal of snaps according to [SD174 - Force removal of snaps](https://docs.google.com/document/d/1ikDI-vPJO6YYFHOyFJ5hfK5L5Gv8voMeY8HJvxNWujw/edit#bookmark=id.a0tjy4 …

many: support killing running snap apps 

---

client/snap_op.go
client/snap_op_test.go
cmd/snap/cmd_snap_op.go
cmd/snap/cmd_snap_op_test.go
tests/main/component-from-store/task.yaml
tests/main/component/task.yaml

Adding support and tests to remove components using `snap` command.

client,cmd: support removing components and snaps with components

---

store/store_action_test.go

There is no "install key". It is probably "instance key".

store/store_action_test.go: fix a typo in the name of a test

---

interfaces/builtin/registry.go
interfaces/builtin/registry_test.go

Roles are not intended to serve the purpose of access control (views can already do that). The role only controls which of the snaps' hooks are invoked when changing registry data. This commit makes the default role "observer" in which case snapd calls a hook when a view changes. The snap can optionally set role to manager to be called during the alteration of the view to be able to modify or veto the changes. This has been changed in the SD133 spec accordingly.

i/builtin: make registry role optional

---

.github/workflows/test.yaml
packaging/opensuse-15.6
spread.yaml
tests/main/cgroup-devices-v1/task.yaml
tests/main/cgroup-freezer/task.yaml
tests/main/interfaces-calendar-service/task.yaml
tests/main/interfaces-contacts-service/task.yaml

Run tests in opensuse leap 15.6

tests: add testing support for opensuse 15.6

---

cmd/libsnap-confine-private/cgroup-support.c
cmd/libsnap-confine-private/cgroup-support.h
cmd/libsnap-confine-private/privs-test.c
cmd/snap-confine/mount-support.c
cmd/snap-confine/ns-support.c
cmd/snap-update-ns/utils.go
tests/lib/prepare-restore.sh
tests/lib/ramdisk.sh
tests/main/base-migration/task.yaml
tests/main/cifs-home/task.yaml
tests/main/core-snap-not-test-test/task.yaml
tests/nested/manual/core20-auto-remove-user/task.yaml
tests/regression/lp-1815869/task.yaml
tests/unit/c-unit-tests-clang/task.yaml
tests/unit/c-unit-tests-gcc/task.yaml

The syntax with the dot is deprecated, and modern chown warns about it:
+ chown root.disk /dev/ram0
chown: warning: '.' should be ':': root.disk

tests: use chown USER:GROUP instead of USER.GROUP

---

overlord/snapstate/component.go
overlord/snapstate/component_remove_test.go
overlord/snapstate/handlers_components.go
overlord/snapstate/handlers_components_link_test.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_remove_test.go
overlord/snapstate/snapstate_update_test.go
tests/main/component/task.yaml

Remove components on snap removal by adding discard-component tasks.
No other task is actually needed as unlinking the snap also removes
components from the state and clean-up of kernel drivers tree is done
by a per-snap task.

o/snapstate: remove components on snap removal

---

tests/main/download-timeout/task.yaml

Update the test because in openstack ens3 interface is used and in google it is used ens4

tests: fix download-timeout test

---

tests/lib/spread/backend.openstack.yaml

This is needed to finish the full run before the instances are killed.

tests: add more workers to run ubuntu tests in openstack

---

tests/nested/manual/core20-install-mode-shutdown-via-hook/task.yaml
tests/nested/manual/uc-update-assets-secure/task.yaml

This test failes with the executables are moved to EFI/ubuntu instead of EFI/boot
Also fix core20-install-mode-shutdown-via-hook. I used the code we have in nested.sh to check "cloud-init status --wait"

tests: fix uc-update-assets-secure nested test in uc24

---

overlord/export_test.go
testutil/base.go
testutil/export_test.go
testutil/mocking_test.go

Add an explicit `Mock()` helper for mocking single objects. Extend unit tests for exiting `Backup*` code

testutil: provide a type safe helper for Mocking

---

spread.yaml

This is required to fix arm tests which are failing to boot because the error:
failed: cannot install system: gadget and system-boot device /dev/vda partition table not compatible: cannot find disk partition /dev/vda2 (starting at 2097152) in gadget: on disk size 8673820672 (8.08 GiB) is larger than gadget size 1258291200 (1.17 GiB)

tests: use ubuntu-image snap from beta channel

---

interfaces/builtin/gpio_control.go
tests/lib/snaps/store/test-snapd-gpio-control/bin/cmd
tests/lib/snaps/store/test-snapd-gpio-control/snapcraft.yaml
tests/lib/snaps/test-snapd-policy-app-consumer/meta/snap.yaml
tests/main/interfaces-gpio-control/task.yaml

Add supported for /dev/gpiochip* devices implementing the new GPIO character
device kernel APIs.
Related: SNAPDENG-25370

interfaces/builtin/gpio_control: add support for accessing gpiochip* devices

---

cmd/snap/cmd_run.go
sandbox/apparmor/apparmor.go
secboot/encrypt_sb_test.go
snapdtool/tool_linux.go
snapdtool/tool_test.go

Back in 2019 in https://github.com/snapcore/snapd/commit/216890f6352339d3e732c2fba1b2c7f74cd529ea I have introduced a change which allowed snapdtool.InternalToolPath() to fall back to use an executable from the same directory as currently executing process with the idea of facilitating the local development. However, this has proved to be problematic as it introduces ambiguity about the tool location. Specifically, when called in the context of /usr/bin/snap, a lookup an internal tool called apparmor_parser may return /usr/bin/apparmor_parser, which is obviously incorrect, as that path isn't an internal snapd tool. With https://github.com/snapcore/snapd/pull/13321 landing, the nfs-support tool broke on Arch. The test attempts to set up a known failure scenario, which now did not take …

snapdtool, sandbox/apparmor: fix apparmor_parser lookup

---

overlord/hookstate/ctlcmd/set.go
overlord/hookstate/ctlcmd/unset.go
overlord/hookstate/ctlcmd/unset_test.go

Adds support to `snapctl unset` for removing registry data.

o/h/ctlcmd: support unsetting registry data in snapctl

---

tests/main/mix-revision-and-channel/task.yaml

This was failing because arm didn't have revisions uploaded. This is fixed now, and this change will help with maintainability. Thanks, @sergiocazzolato!

tests: fix mix-revision-and-channel to use revisions independent of architecture

---

interfaces/apparmor/template.go

A customer reported an AppArmor denial related to the jdk trying to read /sys/fs/cgroup/.../memory.max. At least on [OpenJDK](https://github.com/openjdk/jdk/blob/156f0b4332bf076165898417cf6678d2fc32df5c/src/hotspot/os/linux/cgroupV2Subsystem_linux.cpp#L220) that seems plausible and like something we might reasonably allow by default. The internal SF case is attached to this ticket SNAPDENG-26289

interfaces: allow reading memory.max by default

---

overlord/state/notices.go
overlord/state/notices_test.go

Add the prompting-related notice types:
- `interfaces-requests-prompt`
- `interfaces-requests-rule-update`
These should be recorded when a request prompt or request rule is created, modified, or removed.
This is tracked internally by https://warthogs.atlassian.net/browse/SNAPDENG-26287 .

o/state: add notice types for request prompts and request rules

---

tests/lib/nested.sh
tests/nested/manual/uc-update-assets-secure/task.yaml

It can happen that an update of assets in seed partition is interupted and shim is old, but grub is new. That means that the new grub has to be signed with a vendor key from shim.
Secboot will refuse to reseal if we have a potential impossible boot chain. So we should not test that impossible case.

t/n/m/uc-update-assets-secure: sign new grub also with old key

---

build-aux/snap/snapcraft.yaml
cmd/snap-confine/mount-support-nvidia.c
interfaces/builtin/opengl.go

There are two small fixes related to driver bitrot and a somewhat shocking omission from our snapd snap build configuration. This was tested on Ubuntu 24.10 with RTX 2080 in an eGPU and the result was dramatically better support for using steam snap.
Co-Authored-With: Maciej Borzecki <maciej.borzecki@canonical.com>

cmd/snap-confine: improve compatibility with nvidia drivers

---

build-aux/snap/snapcraft.yaml

core-initrd for UC20 is missing the following fixes:
* https://github.com/snapcore/core-initrd/pull/64
* https://github.com/snapcore/core-initrd/pull/70
* https://github.com/snapcore/core-initrd/pull/97
Because of that, it still kills recovery-chooser-trigger from initrd, and expects it to re-run from snapd snap. Until those fixes are backported, we need to keep on building snap-bootstrap.
This is not needed by UC22+
Bug: https://bugs.launchpad.net/snapd/+bug/2075323

snapcraft.yaml: pack snap-bootstrap because of uc20

---

overlord/snapstate/component_install_test.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/target_test.go
snap/component_test.go
snap/info_snap_yaml.go
store/details_v2_test.go

With this change, "snap pack" and "snap install" will fail if the target snap defines kernel-modules components and it is not of type kernel.
Thanks to @andrewphelpsj for noticing.

snap: allow kernel-modules components only in kernel snaps

---

overlord/snapstate/backend/export_test.go
overlord/snapstate/backend/setup.go
overlord/snapstate/backend/setup_test.go

We were not using the right information to revert to the previous drivers tree in the case of a failure when adding kernel-modules components.

o/s/backend: restore properly when EnsureKernelDriversTree fails

---

boot/assets.go
boot/assets_test.go
boot/export_test.go
boot/makebootable.go
boot/makebootable_test.go
boot/seal.go
boot/seal_test.go
cmd/snap-bootstrap/cmd_initramfs_mounts.go
cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
gadget/install/export_test.go
gadget/install/install.go
gadget/install/install_dummy.go
gadget/install/install_test.go
gadget/install/params.go
overlord/devicestate/devicestate_install_api_test.go
overlord/devicestate/devicestate_install_mode_test.go
overlord/devicestate/handlers_install.go
overlord/install/install.go
overlord/install/install_test.go
secboot/bootstrap_container.go
secboot/secboot.go
secboot/secboot_hooks.go
secboot/secboot_sb_test.go
secboot/secboot_tpm.go
tests/lib/uc20-create-partitions/main.go

Because we will need to enroll multiple keys, we need to make the first key at volume creation an installation key that we remove in the end.  This commit does not implement it, but it does add the abstraction where to allow us to do it.

secboot: add installation key abstraction

---

tests/nested/manual/kernel-modules-components/task.yaml

Remove kernal-modules component now that it is possible to do so. Also, run with TPM as now the initramfs contains the needed change to support kernel-modules components.

tests/kernel-modules-components: remove component

---

interfaces/prompting/constraints.go
interfaces/prompting/constraints_test.go
interfaces/prompting/requestprompts/export_test.go
interfaces/prompting/requestprompts/requestprompts.go
interfaces/prompting/requestprompts/requestprompts_test.go
sandbox/apparmor/notify/listener/export_test.go
sandbox/apparmor/notify/listener/listener.go
sandbox/apparmor/notify/listener/listener_test.go

Include the AppArmor permissions allowed/denied by the user along with the allow/deny decision in the response sent back to the listener. This way, the listener can allow only the permissions which were explicitly granted by the user, rather than automatically granting all requested permissions.
One reason to do so is that if a request is received for several AppArmor permissions and at least one of those permissions has no mapping to an abstract permission for the interface in question, then those unknown permissions can be discarded. If the request is eventually allowed, then only the AppArmor permissions matching the abstract permissions which the user explicitly approved are allowed, and the unknown permissions are implicitly denied.
On the listener side, the listener receives two …

i/p/requestprompts,s/a/n/listener: include explicit permissions in replies

---

.github/workflows/test.yaml

tests: support running tests in github agents with spread-enabled

---

tests/nested/manual/uc-update-assets-secure-add-sbat/task.yaml

There is no point to test this case on uc24 or later, we already have an sbat, and it is unlikely any UC24 will boot without one.  Also it becomes difficult to build an old version on shim on newer GCC.

tests/nested/manual/uc-update-assets-secure-add-sbat: do not run for uc24+

---

overlord/snapstate/component.go
overlord/snapstate/component_install_test.go

We were discarding the component that was just installed (and also previously installed) when doing something like a `snap refresh --revision=n <snap>`, where `n` is the current revision, and no component revisions change.

o/snapstate: do not discard components if we are refreshing to the same revision already installed

---

overlord/snapstate/backend_test.go

Remove unused fields:
overlord/snapstate/backend_test.go:95:2: field `compsToInstall` is unused (unused)
compsToInstall, currentComps []*snap.ComponentSideInfo
^
overlord/snapstate/backend_test.go:96:2: field `compsToRemove` is unused (unused)
compsToRemove, finalComps    []*snap.ComponentSideInfo
^

overlord/snapstate: remove unused field in fake backend operations

---

daemon/api.go
daemon/api_aliases_test.go
daemon/api_sideload_n_try_test.go
daemon/api_snaps.go
daemon/api_snaps_test.go
daemon/export_test.go
overlord/snapstate/component.go
overlord/snapstate/component_install_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/storehelpers.go
overlord/snapstate/target.go
snap/errors.go
store/store_action.go
store/store_action_test.go
tests/main/component-from-store/task.yaml

This adds support for installing components for snaps that are already installed. Based on https://github.com/snapcore/snapd/pull/14241, for now.

o/snapstate, daemon: allow installing components for already installed snap

---

interfaces/snap_app_set.go
overlord/ifacestate/handlers.go
overlord/ifacestate/helpers.go
overlord/ifacestate/ifacestate.go
overlord/ifacestate/ifacestate_test.go
overlord/snapstate/component.go
overlord/snapstate/component_test.go
overlord/snapstate/snapmgr.go

This adds the set of being-setup-components to the PendingSecurity struct that we use to track security changes that have happened for inactive snap revisions.

o/snapstate, o/ifacestate: consider comps in pending security

---

interfaces/builtin/pcscd.go
interfaces/builtin/pcscd_test.go
interfaces/builtin/ros_opt_data.go
interfaces/builtin/ros_opt_data_test.go
interfaces/builtin/steam_support.go
interfaces/builtin/steam_support_test.go

Correct summaries that break uniformity to ensure that `snap interface --all` looks correct/uniform
Tweaks:
- pcscd: introduced newline that complicates parsing of output (overflows into the first column "name")
- ros: "Allows read-only" -> "allows ..."
- steam: "allow Steam" -> "allows Steam"
Part of https://warthogs.atlassian.net/browse/SNAPDENG-26156
Relates to https://github.com/canonical/snapd/pull/14273

interfaces/builtin: correct pscd, ros_opt_data and steam_support summaries

---

interfaces/builtin/network_control.go

Unsure on how we'd normally do tests for a change like this, it doesn't seem we have coverage of the functionality of this plug right now.

i/builtin: add access to wpa_supplicant's dbus api to the network-control plug

---

interfaces/prompting/dirs.go
interfaces/prompting/dirs_test.go
interfaces/prompting/internal/maxidmmap/maxidmmap.go
interfaces/prompting/internal/maxidmmap/maxidmmap_test.go
interfaces/prompting/patterns/patterns.go
interfaces/prompting/prompting.go
interfaces/prompting/prompting_test.go
interfaces/prompting/requestprompts/export_test.go
interfaces/prompting/requestprompts/requestprompts.go
interfaces/prompting/requestprompts/requestprompts_test.go
interfaces/prompting/requestrules/export_test.go
interfaces/prompting/requestrules/requestrules.go
interfaces/prompting/requestrules/requestrules_test.go

Add package for storing request rules. This is very much akin to the requestprompts package, which was added in #13981.
This also relates to https://github.com/olivercalder/snapd/pull/37, and some discussion of rule handling there is relevant here as well.
This work is tracked internally by https://warthogs.atlassian.net/browse/SNAPDENG-8328

i/prompting/requestrules: add package to manage prompting rules

---

features/features.go
features/features_test.go
interfaces/system_key_test.go
overlord/configstate/configcore/prompting.go
overlord/configstate/configcore/prompting_test.go
overlord/ifacestate/helpers.go
sandbox/apparmor/apparmor.go
sandbox/apparmor/apparmor_test.go
tests/main/apparmor-prompting-flag-restart/task.yaml
tests/main/interfaces-snap-interfaces-requests-control/task.yaml

When attempting to enable apparmor prompting experimental feature, first check whether it is supported by the system at all.
Related: SNAPDENG-22972
~~Note that this basically enables the prompting feature if both kernel and parser support it. Perhaps we should still gate this with an environment flag, eg SNAPD_APPARMOR_PROMPTING_ENABLE=1 ?~~

many: check for apparmor prompting support when enabling the experimental feature

---

overlord/configstate/configcore/prompting.go
overlord/configstate/configcore/prompting_test.go
tests/lib/snaps/test-snapd-prompt-handler/bin/start
tests/lib/snaps/test-snapd-prompt-handler/meta/snap.yaml
tests/main/apparmor-prompting-flag-restart/task.yaml
tests/main/interfaces-snap-interfaces-requests-control/api-client/bin/start
tests/main/interfaces-snap-interfaces-requests-control/api-client/meta/snap.yaml
tests/main/interfaces-snap-interfaces-requests-control/task.yaml

Based on #14340. This is a WIP branch, the tests aren't passing yet.

o/configstate/configcore: check whether prompts handler is present and connected

---

interfaces/apparmor/backend_test.go
interfaces/apparmor/template.go

Account for snap-exec coming from the snapd snap when starting a confined process with jailmode.
Cherry picked from #14294

interfaces/apparmor/template: account for snap-exec from snapd when in jailmode

---

overlord/configstate/configcore/export_test.go
overlord/configstate/configcore/prompting.go
overlord/configstate/configcore/prompting_test.go
tests/lib/snaps/test-snapd-prompt-handler/meta/snap.yaml
tests/main/interfaces-requests-activates-handlers/task.yaml

Attempt to enable and start prompting handlers whenever prompting is enabled.
Based on top of #14342 
Related: SNAPDENG-22972

o/configstate/configcore: enable and start prompting handlers

---

interfaces/builtin/home.go

Home readall is distinctly different from the usual home interface permissions, so don't prompt for these.

i/builtin: do not prompt for home non-owner read:all paths

---

.github/workflows/test.yaml

Bump version of golangci-lint to 1.60.1 for Go 1.23 compatibility fixes. See https://github.com/golangci/golangci-lint/issues/4837

github: bump golangci-lint version to 1.60.1

---

interfaces/prompting/constraints.go
interfaces/prompting/constraints_test.go
interfaces/prompting/requestprompts/export_test.go
interfaces/prompting/requestprompts/requestprompts.go
interfaces/prompting/requestprompts/requestprompts_test.go
overlord/ifacestate/apparmorprompting/export_test.go
overlord/ifacestate/apparmorprompting/prompting.go
overlord/ifacestate/apparmorprompting/prompting_test.go
overlord/ifacestate/export_test.go
overlord/ifacestate/handlers.go
overlord/ifacestate/helpers.go
overlord/ifacestate/ifacemgr.go
overlord/ifacestate/ifacestate_test.go
sandbox/apparmor/notify/listener/export_test.go
sandbox/apparmor/notify/listener/listener.go
sandbox/apparmor/notify/listener/listener_test.go

This PR is based on the current outstanding prompting PRs, which are aggregated under #14314. Only the last few commits are relevant to the PR, others will be removed as the preceding PRs are merged.
The code in this PR was originally based on the udevmonitor package. Much of this PR should be rewritten and simplified, as there's no reason for this manager to be governed by the `Connect`, `Run`, `Stop` methods and repeatedly restarted via `Ensure`.
-----
Add the `apparmorprompting` interface manager to start and manage interactions between the listener, prompts backend, and rules backend.
This package mediates interactions between the prompting API and these backends, and between the listener and these backends.
This PR is tracked internally by …

many: add apparmorprompting interface manager

---

asserts/snapasserts/snapasserts.go
asserts/snapasserts/snapasserts_test.go
image/image_linux.go
image/image_test.go
overlord/devicestate/systems.go
seed/seedtest/seedtest.go
seed/seedwriter/helpers.go
seed/seedwriter/writer.go
seed/seedwriter/writer_test.go

Consider asserted components when building a seed, so they can be specified as local files but considered asserted if matching assertions are found in the store.

many: consider asserted components when building a seed

---

image/preseed/preseed_test.go
overlord/devicestate/devicestate_install_mode_test.go
overlord/install/install.go
overlord/install/install_test.go
seed/helpers.go
seed/seed.go
seed/seed16.go
seed/seed16_test.go
seed/seed20.go
seed/seed20_test.go

We want to treat in the same way snaps and component containers when
reading a seed. Additionally, remove parameters from the interface
methods that were not used.

many: change seed.SnapHandler to a seed.ContainerHandler

---

interfaces/builtin/desktop.go

According to this [forum post](https://forum.snapcraft.io/t/kde-all-applications-personal-files-request/40885/9) by @ScarlettGatelyMoore, kde apps need to read the `.config/kdeglobals` file to properly select the correct theme. This PR fixes this for classic systems.

i/b/desktop: add support for kdeglobals

---

tests/main/snap-quota-thread/task.yaml

Fix the test to work as intended and have 10 second timeout waiting for threads to increase from 16 to 24. Currently it loops infinitely up to spread timeout.
For robustness, also implemented the same wait mechanism for ramping from zero to 16 threads, which currently seems to just hope for sufficient delays up the the point of checking.
Failure mode:
Note: I am investigating an issue, may result in more changes...

tests/main/snap-quota-thread: fix thread spawn wait counter

---

dirs/dirs.go
overlord/configstate/configcore/coredump.go
overlord/configstate/configcore/coredump_test.go
overlord/configstate/configcore/export_test.go
overlord/configstate/configcore/handlers.go
overlord/configstate/configcore/proxy.go
overlord/configstate/configcore/proxy_test.go
tests/core/coredump-options/task.yaml

Add system options
- system.coredump.enable, that enables or disables core dumps using systemd-coredump
- system.coredump.maxuse, that sets the MaxUse [1] parameter for core dumps
To have this fully working, https://github.com/snapcore/core-base/pull/227 need to land in core24. See UC025 for more details.
[1] https://man7.org/linux/man-pages/man5/coredump.conf.5.html

many: add coredump options

---

spread.yaml

In debian sid there is a retry (related to autopkgtests) command already installed, which is making our tests fail because it conflicts with our retry tool.
This change makes sure that in our tests, the testing tools are located before the preinstalled binaries by updating the PATH in the spread.yaml

tests: fix debian-sid tests

---

daemon/api_interfaces_test.go
interfaces/repo.go
interfaces/repo_test.go

Provide default doc URL for `snap interface` <name>.
This quick attempt to demonstrate one simple approach that does not require modifying all of the interfaces.
https://warthogs.atlassian.net/browse/SNAPDENG-26156
Related to: https://github.com/canonical/snapd/pull/14337
Follow-up PR will add nightly test check all URLs are reachable.

interfaces: added default doc url for all builtin interfaces

---

.github/workflows/test.yaml

This is needed to be able to see the filtered data in grafana. After this change is merged, the spread cron job to run master tests will be disable.

tests: run github actions workflow on master branch

---

.github/workflows/test.yaml

To be able to run spread tests in master branch when changes are pushed it is required to run the snap-builds job first (spread jobs depends on snap-builds).
This change complements https://github.com/canonical/snapd/pull/14341

tests: enable snap-builds for pushes to master

---

tests/main/snap-interface/snap-interface-network-core.yaml
tests/main/snap-interface/snap-interface-network-snapd.yaml

After changes in this [PR](https://github.com/canonical/snapd/pull/14273) the default doc URL is expected.

tests/main/snap-interface: added expected default doc url

---

interfaces/builtin/lxd_support.go

This reverts commit 4a0c15d0527f559ec617aac5b100a82d12f313d7.
The revert is required because this change produced the following issue when uninstalling snapcraft:
https://bugs.launchpad.net/snapd/+bug/2077101

revert: "interfaces/lxd-support: add support for allow all in AppArmr (#14251)"

---

tests/main/xdg-open/task.yaml

The xdg-open test is getting stuck during prepare stage in opensuse when running the following line:
`tests.session -u test exec sh -c 'cat > ~test/.local/share/applications/test-handler.desktop' << EOF`
In the machine I can see the process runuser process consuming 100% of the cpu. 
That code was changed by
`cat <<EOF > ~test/.local/share/applications/test-handler.desktop`
`chown test:test ~test/.local/share/applications/test-handler.desktop`

tests: fix xdg-open in opensuse

---

interfaces/builtin/lxd_support_test.go

Partially reverts https://github.com/canonical/snapd/pull/14376 to remove test TestAppArmorSpecAllowAll that is not required since revert https://github.com/canonical/snapd/pull/14381.

i/builtin: mock apparmor consistently for the tests

---

overlord/snapstate/check_snap.go
overlord/snapstate/component.go
overlord/snapstate/component_install_test.go
overlord/snapstate/handlers_components.go
overlord/snapstate/handlers_components_mount_test.go
overlord/snapstate/refreshhints_test.go
overlord/snapstate/target.go
overlord/snapstate/target_test.go

Based on https://github.com/canonical/snapd/pull/14347, since that changes how some of the code that calls earlyChecks looks.

o/snapstate: prevent mixed unasserted comps and snaps

---

cmd/snap-confine/mount-support-nvidia.c

Vulkan has a safety-critical (SC) variant for engineering and medical applications. The Nvidia driver version 560 contains an implementation that should be exposed to snap applications.

cmd/snap-confine: add libnvidia-vksc-core.so support

---

.github/workflows/test.yaml

This is needed to be able to count different runs in grafana. 
Also will be needed to identify the source run for a failure

tests: add run id to the file sent to grafana

---

interfaces/prompting/requestprompts/requestprompts.go
interfaces/prompting/requestprompts/requestprompts_test.go
overlord/ifacestate/apparmorprompting/export_test.go
overlord/ifacestate/apparmorprompting/prompting.go
overlord/ifacestate/apparmorprompting/prompting_test.go
sandbox/apparmor/notify/listener/export_test.go
sandbox/apparmor/notify/listener/listener.go
sandbox/apparmor/notify/listener/listener_test.go

When an application tries to carry out an operation and AppArmor mediates the operation via prompting, it sends to snapd a struct with an `Allow` and `Deny` field, among others. The `Allow field contains the bits for the permissions which the application already possessed, while the `Deny` field contains the bits for the permissions which the application currently lacks.
The listener and related code was originally written with the assumption that a permission could not occur in both the `Allow` and `Deny` fields in the same request, and more generally, that any permission which occurred in the `Allow` field should be granted regardless of the prompt decision. The thought process was that this field was permissions which were matched by allow rules and were not in need of mediation. …

many: fix behavior of deny rules created as a result of a prompt reply

---

tests/core/fsck-on-boot/task.yaml

Do a couple of retries when unmounting ubuntu-seed as sometimes the test fails with error:
umount: /run/mnt/ubuntu-seed: target is busy.

tests/fsck-on-boot: do some retries on umount

---

tests/main/snap-quota-thread/task.yaml

The way the spawner snap works is by being a bit abusive and just trying to spawn X threads every delay - now this seems to be mostly fine, but from testing it more it seems that once in a while the delay it takes from changing the cgroup thread allowance for currently running processes to the moment when the spawner actually get to spawn additional thread can take a while, causing the test to timeout.
Avoid this instability all together by restarting the service, causing the change to go into immediate effect.

t/m/snap-quota-thread: make the test more robust against delays

---

tests/nested/manual/broken-model/task.yaml

When using FDE with hooks or tpm, modifying the run model in the boot partition should result in disk that does not unlock. A recovery must be used in that case.

tests: verify that breaking the model results in a locked disk

---

daemon/api_aliases_test.go
daemon/api_snaps.go
daemon/api_snaps_test.go

This allows us to properly attach `snap-names` and `components` to a change when we're installing a snap and components at the same time.

daemon: refactor single snap actions so that we can know if they only changed components

---

cmd/snap-failure/cmd_snapd.go
cmd/snap-failure/cmd_snapd_test.go
cmd/snap-failure/export_test.go
cmd/snap-failure/main_test.go

When there is just one revision of snapd installed in the system, snap-failure
would always fall back to run snapd from core during recovery process if the
core snap is installed. However, on Ubuntu Core systems where the snapd snap is
present by default, such as UC18+, the fallback mechanism should only consider
calling binaries from the snapd snap. On classic, we still allow falling back to
the core snap binaries.
Related: SNAPDENG-22792

cmd/snap-failure: consider distro release info when choosing the fallback target

---

tests/main/interfaces-opengl-nvidia/task.yaml
tests/main/nvidia-files/task.yaml

New libapparmor, which is part of the vendored AppArmor stack, probes files under /sys/module/apparmor. Once we move to testing with snapd snap, this hierarchy needs to be preserved when mocking the contents of /sys/module/.

tests: fix mocking of /sys/module and recreate /sys/module/apparmor in nvidia files tests

---

cmd/snap-failure/cmd_snapd.go
cmd/snap-failure/cmd_snapd_test.go
tests/core/snapd-failover/task.yaml

Attempt to restart the snapd service once recovery is complete. This ensures
that we restore to the same state which was present before the failure.
Related: SNAPDENG-26661

 cmd/snap-failure: restart snapd.service after recovery

---

cmd/snap-failure/cmd_snapd_test.go

It looks like https://github.com/canonical/snapd/pull/14394 didn't contain these unit tests, so they weren't updated.

c/snap-failure: fix failing unit test that was missed when restarting snapd.service after recovery

---

kernel/kernel.go
kernel/kernel_drivers.go
kernel/kernel_drivers_test.go
kernel/kernel_test.go
overlord/snapstate/backend/setup.go
overlord/snapstate/backend/setup_test.go

Consider modules and firmware in $SNAP_DATA when creating the drivers tree. Drivers in that place can be created by hooks from kernel-modules components. The drivers are expected in $SNAP_DATA/{modules,firmware}.

o/snapstate,kernel: allow drivers in $SNAP_DATA

---

overlord/ifacestate/apparmorprompting/prompting.go
overlord/ifacestate/apparmorprompting/prompting_test.go
tests/main/apparmor-prompting-snapd-startup/task.yaml

During snapd startup, the state lock is held while the prompting-related backends are created. However, the backends may try to record notices if, e.g., some rules on disk have expired before they are read by load.
Similarly, during snapd shutdown, the state lock may be held while the interfaces requests manager is being stopped.
If recording a notice happens synchronously during such situations, it results in a deadlock on the state lock. Thus, the notices must be recorded asynchronously.
Note: this means that the order of notices is no longer guaranteed in the prompt and rule backends, but this is okay, since clients should always be prepared to consult the actual prompting endpoints as a single source of truth, and notice data is just a convenient shortcut if it is known that a prompt …

o/i/apparmorprompting: record notices in goroutines

---

overlord/registrystate/export_test.go
overlord/registrystate/registrystate.go
overlord/registrystate/registrystate_test.go
registry/registry.go
registry/registry_test.go

Introduce some helpers to compute a list of views and plugs for those views that may have observed change to some storage path. This will be needed once we introduce the <plug>-view-changed hooks.

registry: compute view/plugs affected by modified path

---

overlord/snapstate/handlers.go

Removes an unused slice, unsure what it was originally used for.

o/snapstate: remove unused slice that is only appended to

---

overlord/snapstate/handlers.go

Do not take the state lock when removing snap files, since it is not known how long the removal will take. We have observed a system in the field, where there were issues with I/O on the storage device and unlink() took significant time, this preventing snapd from functioning normally as the state lock was held.
Related: SNAPDENG-26617

o/snapstate: do not keep the state lock while removing snap files

---

build-aux/snap/snapcraft.yaml

On some architectures, like RISC-V, go decides to not use it. But this is required by some kernels.

snapcraft.yaml: force pie buildmode for go

---

interfaces/prompting/requestprompts/requestprompts.go
interfaces/prompting/requestprompts/requestprompts_test.go
overlord/ifacestate/ifacemgr.go
overlord/ifacestate/ifacestate_test.go
tests/main/apparmor-prompting-snapd-startup/task.yaml

If creation of the interfaces requests manager fails for some reason, we need to mark the manager's internal `useAppArmorPrompting` value to false so that calls to `AppArmorPromptingRunning()` will return false, and we don't try to access a nil-pointer manager backend.
Extend the apparmor-prompting-snapd-startup test to cover this scenario.
Further, we address one reason for this failure: lack of `/run/snapd/` during the interface manager startup. We should ensure that this directory exists as part of the requestprompts backend attempting to open the max prompt ID mmap.
This is tracked internally by https://warthogs.atlassian.net/browse/SNAPDENG-31381

o/ifacestate,tests: apparmor prompting not running if manager creation failed

---

NEWS.md
build-aux/snap/snapcraft.yaml
interfaces/prompting/requestprompts/requestprompts.go
interfaces/prompting/requestprompts/requestprompts_test.go
overlord/ifacestate/ifacemgr.go
overlord/ifacestate/ifacestate_test.go
packaging/arch/PKGBUILD
packaging/debian-sid/changelog
packaging/fedora/snapd.spec
packaging/opensuse/snapd.changes
packaging/opensuse/snapd.spec
packaging/ubuntu-14.04/changelog
packaging/ubuntu-16.04/changelog
tests/main/apparmor-prompting-snapd-startup/task.yaml

DEBEMAIL="Ernest Lotter [ernest.lotter@canonical.com](mailto:ernest.lotter@canonical.com)" release-tools/changelog.py 2.65.1 2077473 NEWS.md
- This was required to fix AppArmor prompting bug preventing release of 2.65. 
- Additionally build fix for snapd riscv64.
Release notes for 2.65 (that will not become an actual release) was replaced with 2.65.1 in order to show the full set of changes relative to the last actual released snapd (2.63).
Cherry-picked:
- https://github.com/canonical/snapd/pull/14421
- https://github.com/canonical/snapd/pull/14411
**Requires rebase-merge**

release: 2.65.1

---

.github/workflows/test.yaml
spread.yaml

We stopped releasing core and snapd snaps for i386 with version 2.60.4. As such 18.04 i386 is no longer supported
Cherry picked from #14294 
Related: SNAPDENG-20098

spread, github: drop 18.04 i386 variant

---

tests/lib/assertions/test-snapd-remodel-bases-24.json
tests/lib/assertions/test-snapd-remodel-bases-24.model
tests/lib/assertions/test-snapd-remodel-pc-rev1-24.json
tests/lib/assertions/test-snapd-remodel-pc-rev1-24.model
tests/nested/manual/remodel-min-size/task.yaml

To fix this test it was required to have the track 24 for snap test-snapd-remodel-pc-min-size, otherwise the remodel failed because it was trying to remodel this snap from base 24 to base 22.

tests: fix remodel-min-size test

---

image/image_linux.go
seed/seed.go
seed/seed20.go
seed/seed20_test.go
seed/seedtest/sample.go
seed/seedtest/seedtest.go
seed/seedwriter/seed20.go
seed/seedwriter/writer_test.go
store/tooling/tooling.go
store/tooling/tooling_test.go
tests/main/prepare-image-components/task.yaml

There were two related bugs here. First, we weren't writing anything to options.yaml when we added components to the seed that weren't in the model, but the snap was in the model.
On the other side of things, we weren't considering components from options.yaml when the snap itself was from the model.
There is the question of the currently failing `TestSeedSnapsWriteMetaCore20SignedLocalAssertedSnapsWithComps`, which looks like it is adding extra components to a seed that doesn't have them defined in the model. I think maybe this shouldn't be allowed?

seed: fix bugs pertaining to how components missing from the model are handled

---

cmd/snap/cmd_debug_execution.go
snapdtool/tool_other.go
tests/main/debug-execution/task.yaml

Add a debug command for investigating various execution aspects of snap related
commands.
Related: SNAPDENG-25499

cmd/snap: add debug command for investigating execution aspects of the snap toolchain

---

interfaces/builtin/cpu_control.go

Many real-time system need to tune IRQ affinity by accessing the related `/proc` file system files. 
Adding this to CPU-control avoids the need to create a new interface for IRQ's or either for real-time applications.

interfaces/builtin/cpu-control: Add IRQ affinity control to cpu_control

---

overlord/devicestate/devicestate_install_api_test.go
overlord/devicestate/handlers_install.go
seed/seed.go
seed/seed20.go
seed/seed20_test.go
seed/seedtest/sample.go
seed/seedwriter/writer.go
snap/snaptest/snaptest.go

Based on https://github.com/canonical/snapd/pull/14378 for now.

seed, o/devicestate: allow picking which optional snaps and components to copy when using seed.Copier

---

overlord/devicestate/devicestate_install_api_test.go
seed/seed.go
seed/seed20.go
seed/seed20_test.go

This will enable us to return the set of optional snaps and components that are available in a seed. Will be used from the /v2/systems API eventually.

seed: add ability to get optional snaps and components that are available from seeds

---

overlord/hookstate/hookmgr.go
overlord/hookstate/hookstate_test.go
overlord/hookstate/hooktest/handler.go

Adds a Preconditioner interface that a hook handler can implement in order to set preconditions for a hook to run. This differs from the Handler's Before method in that, if the Precondition exists and returns false, the hook is skipped without any errors being outputted.
This will be used by registry hook handlers to check that the relevant plug is still connected and the hook should run.

o/hookstate: allow hook handlers to set preconditions

---

overlord/snapstate/backend/link.go
overlord/snapstate/backend/link_test.go
overlord/snapstate/backend/setup.go
overlord/snapstate/backend_test.go
overlord/snapstate/handlers.go
overlord/snapstate/snapstate_remove_test.go
overlord/snapstate/snapstate_test.go

Fix a problem with parallel installs and handling of the shared snap directory, eg /snap/foo, for snap instances /snap/foo_bar. A bug was identified which was a race between a removal of the shared directory in the discard-snap handler of one instance, and creating of the same shared directory in setup-snap handler of another instances if both changes happened to be executing in parallel. The existing conflict resolution does not consider the instances of the same snap to be in conflict, since with exception of the shared snap directory and/or aliases, there should be no collision.
In detail, the shared directory was created in setup-snap handler, which runs before link-snap, and so before the instance-being-installed is effectively added to the state. At the same time, discard-snap …

o/snapstate: create shared snap directory during link-snap

---

spread.yaml

Update Ubuntu Pro image names to use the generic image family name. Fix the Ubuntu 22.04 Pro image name.

spread:  update ubuntu pro image names, fix 22.04 image

---

interfaces/builtin/u2f_devices.go
interfaces/builtin/u2f_devices_test.go

This adds support for OneSpan DIGIPASS FX series FIDO Devices.

interfaces: add onespan fx series fido u2f devices

---

interfaces/builtin/intel_qat.go
interfaces/builtin/intel_qat_test.go
tests/lib/snaps/test-snapd-policy-app-consumer/meta/snap.yaml

This adds an interface for Intel QuickAssist Technology (QAT) devices. There are at least a few snapped applications maintained by Canonical (MicroCeph, OpenSearch) that require this interface, and integration and benchmarking efforts with QAT are ongoing this cycle (for now, the snaps are being run in dev mode). 
In addition to the tests included in this PR, I have also tested with a [simple openssl snap](https://github.com/canonical/intel-quickassist-technology) on a server containing QAT devices.
I have also created a spec (`PE-PEK020`) that I would welcome your review on!

interfaces: add intel-qat interface

---

interfaces/builtin/pcscd.go
interfaces/builtin/pcscd_test.go

The Opensc-Pkcs11 module needs to read this configuration file. https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1967632/comments/74.
As Debian has a patch that changes /etc/opensc.conf->/etc/opensc/opensc.conf, I'm keeping the two paths in the proposal.

interfaces: allow pcscd to read opensc.conf.

---

tests/main/snap-quota-cpu/task.yaml

The test was failing because the cpu limits weren't getting updated. Restarting the snap service (thanks @Meulengracht) before checking the limits ensures they are properly updated.

tests: added snap restart to ensure cpu limits get respected

---

overlord/snapstate/snapstate_test.go
wrappers/desktop.go
wrappers/desktop_test.go

`{Ensure,Remove}SnapDesktopFiles` are updated to support desktop file IDs.
Snaps are allowed to have their desktop files copied without name mangling (snap name prefix) if the file name is listed under `desktop-file-ids` attribute in their `desktop` interface declartion.
This is needed to support desktop IDs detailed in [SD170](https://docs.google.com/document/d/1j4flP303OJKrSxSCjkeZkh-9COuahVmo_EK_ye09RxQ/edit#heading=h.v7nluroo4fyr) spec.

wrappers: update desktop helpers to support desktop IDs

---

HACKING.md

Describe use of run-spread and how integration tests need snapd snap now.

HACKING: update to mention run-spread

---

interfaces/builtin/modem_manager.go
interfaces/builtin/modem_manager_test.go

From Linux 5.14, the WWAN ports are using a different format. E.g:
* wwan0p1AT   -> wwan0at0
* wwan0p2MBIM -> wwan0mbim0
* wwan0p3AT   -> wwan0at1
See the following commits for the details:
[1] https://github.com/torvalds/linux/commit/392c26f7f133b9f09e5f58db1ce6ef4b3b4df49f
[2] https://github.com/torvalds/linux/commit/f458709ff40b0d992fec496952f79c7820dd3fde

interfaces/modem-manager: add new format of WWAN ports

---

tests/core/remodel-base/task.yaml

On 2024-08-29 a new revision of core18 was pushed latest/edge to the store, which caused the test to revert back to a revision different than in the seed which is older. In this scenario, the restore snippet would incorrectly identify no need to a reboot and so the test would break. Snapd when forced to reinitialize the system would issue reboot, since the installed core18 is different than one in the seed, but the test would not trigger a reboot through spread.

tests/core/remodel-base: fix the test when store base has different revision

---

tests/main/nfs-support/task.yaml

Disable the test on Sid where `sg` appears to be broken and thus was ultimately removed from the `login` package.
See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1078122

tests/main/nfs-support: disable the test on Debian Sid

---

build-aux/snap/snapcraft.yaml
snapdtool/fips.go

Introduce a build that which sets up a FIPS compliant TLS configuration.  Unfortunately Microsoft Go FIPS toolchain < 1.22 does not set up the relevant runtime configuration dynamically, see     https://github.com/microsoft/go/blob/66dd0ab88969dff30f3180c41a1a77f592090d68/eng/doc/fips/README.md#configuration-overview In fact none of them does, so we need to have a workaround that isn't too invasive. 
Note that this will only build if the crypto/tls/fipsonly package itself is enabled through relevant build tags.
Related: SNAPDENG-23793

snapdtool, snapcraft: enable FIPS compliant TLS configuration

---

interfaces/builtin/desktop_legacy.go

gcin should use socket for this

interfaces: grant access to gcin socket location in desktop-legacy

---

store/tooling/tooling.go
store/tooling/tooling_test.go

Results aren't returned from the store in the same order that we send them, so we shouldn't depend that behavior.

s/tooling: do not depend on order of snap action results when downloading components

---

cmd/Makefile.am
cmd/configure.ac
cmd/snap-mgmt/snap-mgmt-selinux.sh.in
cmd/snap-mgmt/snap-mgmt.sh.in
cmd/snap/cmd_snap_op.go
cmd/snapd-env-generator/main.c
cmd/snapd-generator/main.c

Given that most tools now detect the snap mount directory dynamically, picking either /var/lib/snapd/snap or /snap, depending on what is actually being used, it is the right time to rename the remaining option to the more appropriate name of static snap mount directory. The name differs because the value is baked into the files shipped with the distribution-specific packaging. This includes systemd units, environment generators and the management script.
We still need this value and it is not going away anytime soon, but it is not the only value and so I think that separating SNAP_MOUNT_DIR from STATIC_SNAP_MOUNT_DIR is well, apt.

cmd: rename SNAP_MOUNT_DIR to STATIC_SNAP_MOUNT_DIR

---

snap/info.go
snap/info_test.go
wrappers/desktop.go

Those helpers are extracted to be reused in a later PR when generating apparmor rules specific to desktop-file-ids.
Those helpers are needed by https://github.com/canonical/snapd/pull/14444.

many: extract desktop-ids helpers from wrappers package into snap package

---

interfaces/apparmor/template.go

When using `set-quota loggroup`, the journal only contains the log of service starting, but not the logs of run-time.
```
$ sudo journalctl -b --namespace snap-mmgroup
-- Logs begin at Wed 2024-09-04 06:29:18 UTC, end at Wed 2024-09-04 06:29:37 UTC. --
Sep 04 06:29:18 ubuntu systemd-journald[20109]: Journal started
Sep 04 06:29:18 ubuntu systemd-journald[20109]: Runtime Journal (/run/log/journal/1fd84e120be8440688196db3cca02d84.snap-mmgroup) is 7.6M, max 61.0M, 53.4M free.
Sep 04 06:29:18 ubuntu modem-manager.modemmanager[20108]: + export SNAP_APP_PATH=/snap/modem-manager/470
Sep 04 06:29:18 ubuntu modem-manager.modemmanager[20108]: + LOG_LEVEL=INFO
Sep 04 06:29:18 ubuntu modem-manager.modemmanager[20108]: + DEBUG=
Sep 04 06:29:18 ubuntu modem-manager.modemmanager[20108]: + [ -f …
```

i/apparmor/template:  allow writing to /run/systemd/journal/dev-log by default

---

daemon/api_systems.go
daemon/api_systems_test.go
daemon/export_api_systems_test.go
overlord/devicestate/devicemgr.go
overlord/devicestate/devicestate.go
overlord/devicestate/devicestate_install_api_test.go
overlord/devicestate/devicestate_install_mode_test.go
overlord/devicestate/devicestate_systems_test.go
overlord/devicestate/handlers_install.go
overlord/devicestate/systems.go
seed/seedtest/sample.go
tests/lib/muinstaller/go.mod
tests/lib/muinstaller/go.sum
tests/lib/muinstaller/main.go
tests/lib/muinstaller/snapcraft.yaml
tests/lib/tools/setup_nested_hybrid_system.sh
tests/nested/manual/muinstaller-core/comp1/meta/component.yaml
tests/nested/manual/muinstaller-core/snap-with-comps/meta/snap.yaml
tests/nested/manual/muinstaller-core/snap-with-comps/test
tests/nested/manual/muinstaller-core/task.yaml
tests/nested/manual/muinstaller/task.yaml
tests/nested/manual/split-refresh/task.yaml

This PR ties together work that enables users to pick which snaps and components to install from a set of available containers.

many: allow systems installed via installer API to pick optional snaps and components

---

daemon/api_snaps.go
daemon/api_snaps_test.go
tests/main/interfaces-snap-interfaces-requests-control/task.yaml

Previously on the prompting branch, `snap-interfaces-requests-control` granted access to `/v2/snaps/{name}` and a few other endpoints around snap metadata. When porting from the prompting branch to snapd master, I conservatively restricted the permissions granted by `snap-interfaces-requests-control` to the bare minimum. However, we still want to grant prompting clients access to information about the snap which triggered a request prompt.
CC @sminez
This task is tracked internally by https://warthogs.atlassian.net/browse/SNAPDENG-31760

daemon,tests: grant /v2/snaps/{name} via snap-interfaces-requests-control

---

c-vendor/vendor.sh

Bump suquashfuse to 0.5.2 to include fixe for 32bit build from https://github.com/vasi/squashfuse/commit/cb148fc1477ed676049b7891ebb6efc90b2c00ec which was first released in 0.5.1.

c-vendor: bump squashfuse to 0.5.2

---

dirs/dirs.go
gadget/install/content.go
gadget/install/content_test.go
systemd/emulation.go
systemd/systemd.go
systemd/systemd_test.go

We need to create a mount unit for the kernel snap as its content is
linked from the drivers tree. Otherwise the drivers tree is not
functional until the system is seeded.

gadget/install: create mount unit for the kernel on installation

---

NEWS.md
c-vendor/vendor.sh
packaging/arch/PKGBUILD
packaging/debian-sid/changelog
packaging/fedora/snapd.spec
packaging/opensuse/snapd.changes
packaging/opensuse/snapd.spec
packaging/ubuntu-14.04/changelog
packaging/ubuntu-16.04/changelog

DEBEMAIL="Ernest Lotter [ernest.lotter@canonical.com](mailto:ernest.lotter@canonical.com)" release-tools/changelog.py 2.65.2 2077473 NEWS.md
Cherry picked: https://github.com/canonical/snapd/pull/14474
This addresses a build error caused by new version of GCC used in oracular that escalates warning that previously existed to and error when building snapd squashfuse for armhf (32bit). See:
- https://launchpadlibrarian.net/747597684/buildlog_ubuntu-oracular-armhf.snapd_2.65.1+24.10_BUILDING.txt.gz
- https://gcc.gnu.org/gcc-14/porting_to.html | `Type checking on pointer types`
This change only affects snapd deb
**Requires rebase-merge**

release: 2.65.2

---

asserts/preseed.go
asserts/preseed_test.go

This is the first step in preseeding systems with components.
Example of components in preseed assertion:
```
type: preseed
snaps:
-
name: snap-one
id: snap-one-id
revision: 1
components:
-
name: comp1
revision: 2
-
name: snap-two
components:
-
name: comp2
```
If the snap has a revision, then the components must have revisions. If the snap doesn't have a revision, then the components cannot have revisions.

asserts: allow defining components in preseed assertions

---

seed/seed20.go
seed/seed20_test.go

This fixes `seed.Seed.ModeSnaps` to filter down the components to only the applicable ones for the given mode.
I also removed the `seed20.modes` member variable, since we only ever use it in this method and it seems pretty cheap to calculate. Let me know if there is a reason we took this approach and I can re-evaluate.

seed, s/seedwriter: properly filter out components in seed.Seed.ModeSnaps

---

overlord/snapstate/backend_test.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/target.go
tests/main/aux-info/task.yaml

This was dropped (by me) accidentally a while back when introducing components. This adds it back and adds some tests for it.

o/snapstate: make sure to put aux info from store on SnapSetup

---

data/preseed.json
image/preseed/preseed.go
image/preseed/preseed_linux.go
image/preseed/preseed_uc20_test.go

Now that preseed assertions can contain components, we should include them in the one created with a seed.

i/preseed, data: include components in preseed assertion during seed creation

---

spread.yaml
tests/main/nvidia-files/task.yaml

There's a now-known new bug in the packaging of nvidia drivers that is
tracked as https://bugs.launchpad.net/ubuntu/+source/nvidia-graphics-drivers-535-server/+bug/2080351
The result is that the libnvidia-egl-wayland1:i386 package is not
installable.
Adjust the test to allow expressing broken packaging.
--
Separately, I've talked to the maintainer and their preference is not to fix it as the -server packages are unlikely to be used for gaming. I will follow up with a refactor that only exercises 32bit versions on non-server packages.

tests: mark ubuntu-20.04/535-server as broken-packaging

---

.github/workflows/test.yaml

Github actions changed their upload action to not include hidden files and directories by default. To ensure the logs get uploaded, I removed the hidden directory for the logs.

tests: fix upload by changing from hidden directory

---

.github/workflows/test.yaml

I missed some other hidden folders. The coverage files are also in hidden folders, so I added the github directive to include those as well.

tests: fixed coverage upload

---

NEWS.md
overlord/snapstate/backend_test.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/target.go
packaging/arch/PKGBUILD
packaging/debian-sid/changelog
packaging/fedora/snapd.spec
packaging/opensuse/snapd.changes
packaging/opensuse/snapd.spec
packaging/ubuntu-14.04/changelog
packaging/ubuntu-16.04/changelog
tests/main/aux-info/task.yaml

DEBEMAIL="Ernest Lotter [ernest.lotter@canonical.com](mailto:ernest.lotter@canonical.com)" release-tools/changelog.py 2.65.3 2077473 NEWS.md
Cherry picked: https://github.com/canonical/snapd/pull/14482 (regression bug fix)
This change affects snapd debs and snap
**Requires rebase merge**

release: 2.65.3

---

features/features_test.go
overlord/configstate/configcore/prompting_test.go
sandbox/apparmor/apparmor.go
sandbox/apparmor/apparmor_test.go
sandbox/apparmor/export_test.go
tests/main/apparmor-prompting-flag-restart/task.yaml
tests/main/apparmor-prompting-snapd-startup/task.yaml
tests/main/interfaces-requests-activates-handlers/task.yaml
tests/main/interfaces-snap-interfaces-requests-control/task.yaml

This PR is based on #14294, only the final few commits are relevant to this PR. Should rebase this PR on master once that PR lands.
Prompting cannot be supported if the kernel notification socket does not exist. Thus, add a check for its presence to PromptingSupportedByFeatures.
However, this alone is not sufficient. The notification socket may be used for other purposes as well. When this becomes the case, a directory will be added at `/sys/kernel/security/apparmor/features/policy/notify`. If that directory exists, and it contains a file called `user`, which contains the list of prompting mediation classes, then prompting is supported on the system. If no file called `user` exists in that directory, but the directory itself exists, then we know prompting is not supported.
This work is …

s/apparmor: expand apparmor prompting support checks

---

interfaces/builtin/registry.go
interfaces/builtin/registry_test.go
overlord/hookstate/ctlcmd/get_test.go
overlord/registrystate/registrystate.go
overlord/registrystate/registrystate_test.go
snap/info_test.go

The manager role has been renamed to custodian to reflect that the snap is responsible for the registry data but any snap can modify it (assuming it plugs a view that allows it).

many: rename registry role s/manager/custodian

---

overlord/snapstate/component.go
overlord/snapstate/component_install_test.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_install_test.go
overlord/snapstate/snapstate_update_test.go
overlord/snapstate/target.go
overlord/snapstate/target_test.go

This enables us to update snaps with components from local snap and component files.

o/snapstate: allow updating snaps with components from local files

---

.github/workflows/test.yaml
build-aux/snap/snapcraft.yaml
mkversion.sh
packaging/ubuntu-16.04/rules
snapdtool/fips_linux.go
spread.yaml
tests/main/fips/task.yaml

Based on #14439. Add spread testing of FIPS snap variant.
Related: SNAPDENG-23245

tests: enable testing with snapd snap FIPS variant

---

.github/workflows/test.yaml
run-checks
tests/unit/go/task.yaml

This adds the use of golangci-lint snap both in run-checks.sh and in the CI. The change in the CI's serves to align a local  run-checks.sh run with a CI run. By using the same snap and ensuring it's always up to date in both cases, developers should know what the CI is going to tell them before triggering a runner.

run-checks: added golangci-lint to run-checks

---

tests/lib/prepare-restore.sh

I've ran across a test failure caused by attempt to use systemctl to reset the failed status of a service that was not loaded due to being masked.
+ systemctl reset-failed snapd.service snapd.socket snapd.failure.service
Failed to reset failed state of unit snapd.failure.service: Unit
snapd.failure.service not loaded.
Use systemctl status as a way to check if a service is known before attempting to reset it.

tests: conditionally reset-failed snapd.failure.service

---

build-aux/snap/snapcraft.yaml
release-tools/is-lp-fips-build.sh

Add support for building a FIPS variant of snapd snap in Launchpad using https://launchpad.net/~fips-cc-stig/fips-cc-stig/+snap/snapd-fips recipe.
Based on #14476 
Related: SNAPDENG-23124

snapcraft: support for FIPS build on LP

---

overlord/snapstate/backend_test.go
overlord/snapstate/check_snap.go
overlord/snapstate/check_snap_test.go
overlord/snapstate/export_test.go
overlord/snapstate/handlers.go
overlord/snapstate/snapstate.go

This PR does desktop-file-ids conflict detection as they should be unique across the system. The checks are very similar to the [conflict checks for dbus activation](https://github.com/canonical/snapd/blob/718ba573a216859435eeaa10e73dcbd36d9c016e/overlord/snapstate/dbus.go#L51).
This simply checks if any other snap uses any of desktop-file-ids of the snap being installed and refuses to refresh/install when a conflict is detected. This is mostly target to prevent conflicts with parallel installs.

o/snapstate: refuse to install snaps whose desktop-file-ids conflict with installed snaps

---

overlord/devicestate/handlers.go
overlord/devicestate/handlers_test.go
overlord/install/install.go
overlord/install/install_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_test.go
seed/seed20.go
seed/seed20_test.go
tests/lib/assertions/developer1-20-components-dangerous.json
tests/lib/assertions/developer1-20-components-dangerous.model
tests/nested/manual/core20-preseed/task.yaml

This should complete the changes to make preseeding work with components. `ubuntu-image` still needs to be updated (PR here: https://github.com/canonical/ubuntu-image/pull/243).

many: consume preseeded components when seeding system

---

tests/main/snap-remove-terminate/task.yaml

The flock check was testing that the service just created has held the flock immediately. In some cases the test service wasn't able to hold the lock fast enough.
Instead, check that a file is created by the service to confirm the snap is run by the service.
Sample test run where this happend: https://github.com/canonical/snapd/actions/runs/10846480097/job/30100068155

tests: increase flock check timeout in tests/main/snap-remove-terminate

---

tests/core/snapd-failover/task.yaml

Improve the test so that we wait for snapd.failure service to complete, otherwise it was possible for the test to proceed with execution while recovery was still in progress.

tests/core/snapd-failover: improve the test to wait for snapd.failure to be finished

---

desktop/desktopentry/desktopentry.go
desktop/desktopentry/desktopentry_test.go
overlord/snapstate/snapstate_test.go
snap/info.go
snap/info_test.go
tests/main/install-sideload/task.yaml
tests/main/parallel-install-desktop/task.yaml
wrappers/desktop.go
wrappers/desktop_test.go
wrappers/export_test.go

Now that `desktop-file-ids` are supported, the simple `$PREFIX_$APP.desktop` heuristic when looking up snap app's desktop file won't cut it.
Instead, Loop through `desktop-file-ids` desktop interface plug attribute in order to have deterministic output and return the first matching desktop file found if (the newly added) `X-SnapAppName` entry matches the app name and fallback to the simple heuristic if no matches are found.
This follows the [SD170 - Custom desktop file IDs for snaps](https://docs.google.com/document/d/1j4flP303OJKrSxSCjkeZkh-9COuahVmo_EK_ye09RxQ/edit?pli=1#heading=h.lifosn8k7vke) spec.

{snap,wrappers}: improve desktop file to snap app matching

---

asserts/validation_set.go
asserts/validation_set_test.go

We're going to require this for now, might be lifted later. I also added some more context to error messages while in here.

asserts: require components in validation sets to have revisions if their associated snap has one

---

interfaces/builtin/desktop.go

This allows two things:
* introspecting the properties on the portal interfaces
* being notified about setting changes

interfaces/desktop: Improve integration with xdg-desktop-portal

---

overlord/snapstate/backend_test.go
overlord/snapstate/component.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_update_test.go
overlord/snapstate/storehelpers.go

This change properly handles components when refreshing to a snap revision that has already been on the system.
When doing something like: `snap refresh --revision=n snapname`, where `n` has already been installed on the system, we were previously just switching back to the components that were installed with that revision. This is more of a revert than a refresh.
To properly handle this, we should consider which components are currently installed, and remove any that are not available for the revision `n`, and check with the store for the most up-to-date revisions of components.

o/snapstate: properly handle components when refreshing to revision that has been on the system before

---

overlord/hookstate/hooks.go
overlord/ifacestate/ifacestate_test.go
overlord/overlord.go
overlord/registrystate/export_test.go
overlord/registrystate/registrymgr.go
overlord/registrystate/registrymgr_test.go
overlord/registrystate/registrystate.go
overlord/registrystate/registrystate_test.go
overlord/registrystate/transaction.go
overlord/registrystate/transaction_test.go
snap/hooktypes.go

Adds registry hook handlers. The change-view-<plug> hook handler checks the transaction to see if the snap has rejected the changes (this will be done with a `snapctl fail <reason>` command) and outputs that information nicely if so. The save-view-<plug> hook handler attempts to roll back previous save-view hooks that have already run if the hook failed. It saves the error, schedules rollback tasks and then outputs the error once those are done. The <plug>-view-changed doesn't have any code to it.

o/registrystate: add registry hook handlers

---

.github/workflows/test.yaml
run-checks

For each pr we have too many warnings, mostly caused because we are not using the latest actions.

tests: update actions versions to avoid warnings in prs github summary

---

wrappers/core18.go
wrappers/desktop.go
wrappers/desktop_test.go
wrappers/export_test.go

Snapd desktop files on core are installed under `SnapDesktopFilesDir` and since they don't have the usual `X-SnapInstanceName` for other snaps errors were showing in the logs.
This PR just skips those files when looking up installed desktop files.
Sample log: https://github.com/canonical/spread-cron/actions/runs/10693759238/job/29688990832#step:4:2445

wrappers: skip snapd desktop files in {Ensure,Remove}SnapDesktopFiles

---

cmd/snap-update-ns/testdata/annotations-2.patch
cmd/snap-update-ns/testdata/annotations-4.patch
cmd/snap-update-ns/testdata/annotations-5.patch
cmd/snap-update-ns/testdata/annotations-6.patch
cmd/snap-update-ns/testdata/content-layout-2-after-disconnect.current.fstab
cmd/snap-update-ns/testdata/content-layout-4-initially-disconnected-then-connected.current.fstab
cmd/snap-update-ns/testdata/content-layout-4-initially-disconnected-then-connected.desired.fstab
cmd/snap-update-ns/testdata/content-layout-5-initially-connected-then-content-refreshed.current.fstab
cmd/snap-update-ns/testdata/content-layout-6-initially-connected-then-app-refreshed.current.fstab
cmd/snap-update-ns/update.go
cmd/snap-update-ns/update_test.go

This is stacked on top of https://github.com/canonical/snapd/pull/14491
We recently realized that the order of saved mount profile, after
performing mount namespace update, was subtly incorrect. The order was
seemingly swapped after each operation. In reality, the order reflected
the order of performed changes, including the special change type of
"keep", which means that an entry is kept intact.
Fix the problem by storing "kept" changes in the original order, which
is back-to-front compared to the order of changes computed by the
algorithm. At the same time, keep track of mount changes in the order of
their execution.
This probably fixes a hell lot of edge cases and weird behaviors that
went undiagnosed for many years. Interestingly a test case had a TODO
that hinted at the problem, but …

cmd/snap-update-ns: keep order of existing mount entries

---

asserts/validation_set.go
asserts/validation_set_test.go

This is a fix to a bug that was requiring that components have a revision, even if they are being marked as invalid.

asserts: do not require revision when setting component as invalid

---

interfaces/builtin/desktop_legacy.go
interfaces/builtin/desktop_legacy_test.go
interfaces/builtin/export_test.go
interfaces/builtin/unity7.go
interfaces/builtin/unity7_test.go
interfaces/builtin/utils.go
interfaces/builtin/utils_test.go
snap/info.go
snap/info_test.go
tests/lib/snaps/test-snapd-desktop-file-ids/bin/check-dirs
tests/lib/snaps/test-snapd-desktop-file-ids/bin/check-files
tests/lib/snaps/test-snapd-desktop-file-ids/meta/gui/bad. ,?**[]{}^\$#.desktop
tests/lib/snaps/test-snapd-desktop-file-ids/meta/gui/foo.desktop
tests/lib/snaps/test-snapd-desktop-file-ids/meta/gui/org.example.Foo.desktop
tests/lib/snaps/test-snapd-desktop-file-ids/meta/gui/org.example.desktop
tests/lib/snaps/test-snapd-desktop-file-ids/meta/snap.yaml
tests/main/desktop-file-ids/task.yaml
wrappers/desktop.go
wrappers/desktop_test.go

This PR adds support for `desktop-file-ids` for apparmor rules generated when the `desktop-legacy` and `unity7` interfaces are connected because they provide the ability for the snap to access it own desktop files.
This adds a bit of complexity due to the deny rules that needs to be generated to suppress warnings. `GenerateAAREExclusionPatterns` is used with care to generate the deny rules for multiple patterns.
Now, since the rules generated depend on the snap content itself, more aggressive validation and sanitization is required:
- Sanitized desktop file names during mangling so they can only contain `[A-Za-z0-9-_.]` so they can't contain special AARE characters
- Kept `desktop-file-ids` as is without sanitization because they should already be validated during install
- Added …

i/builtin: support desktop-file-ids in desktop files rule generation

---

overlord/hookstate/ctlcmd/fail.go
overlord/hookstate/ctlcmd/fail_test.go
overlord/registrystate/transaction.go
overlord/registrystate/transaction_test.go

Add a `snapctl fail <reason>` command to rejects changes in a registry transaction in `change-view-<plug>` hooks.

o/h/ctlcmd: add a snapctl fail command

---

check-commit-email.py

Commit d935048f4ee5f9a8cde640a760bf1fdb9409de7e by dependabot used an invalid email address 49699333+dependabot[bot]@users.noreply.github.com which trips the valid email checker.

check-email-commit: exception for dependabot

---

overlord/registrystate/export_test.go
overlord/registrystate/registrymgr.go
overlord/registrystate/registrymgr_test.go
overlord/registrystate/registrystate_test.go

Adds a RegistryManager which implements handlers for tasks related to
the committing of registry transactions. These do things like committing
the transaction internally, clean up state once that's done or on error,
etc. This doesn't include logic to deal with concurrent writers, that
will be added later once the registrystate side of this is added as
well.
~Depends on https://github.com/canonical/snapd/pull/14483 so only the last commit is relevant here~

o/registrystate: add registry tx task handlers and helpers

---

tests/main/bare-snapctl/task.yaml

The bare base snap has no libraries and no dynamic linker. Show that even in such environment it is possible to use the snapctl program.
This test also helps in testing upcoming changes to the snapd-specific dynamic linker, namely in the fact that snapd linker is not affecting snapctl.
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-32203

tests: show that snapctl can be used with bare base

---

interfaces/builtin/u2f_devices.go

Inspired by [pull/14429](https://github.com/canonical/snapd/pull/14429) that did not pass CLA check.
https://github.com/Yubico/libfido2/blob/main/udev/70-u2f.rules
`# TrustKey Solutions FIDO2 T120 by eWBM Co., Ltd.
KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="311f", ATTRS{idProduct}=="a6e9", TAG+="uaccess", GROUP="plugdev", MODE="0660"`

interfaces/builtin: add u2f trustkey t120 product id

---

cmd/snapd-apparmor/main.go
cmd/snapd-apparmor/main_test.go

Normally securityfs is mounted by systemd on startup. This is done on
non-container systems. People that experiment with WSL and apparmor using a
custom kernel would like to continue to use snapd this way, and to allow that
we need to make our checks tighter.
Earlier this code was refactored to do nothing on all WSL systems. With this
change the behavior on default WSL kernels (with WSL2) is exactly the same.
When non-default kernel is used, and when the user explicitly mounts securityfs
by hand, then snapd.apparmor.service will load the profiles into the kernel as
it does on typical systems.
There's a known issue where this is not using apparmor namespaces, so one
distribution container can load a profile that is visible and effective in
another, but this is outside of the scope of snapd …

cmd/snapd-apparmor: only skip WSL without securityfs

---

spread.yaml
tests/nested/core/core20-fault-inject-on-install/task.yaml
tests/nested/core/core20-fault-inject-on-refresh/task.yaml
tests/nested/manual/core20-fault-inject-on-install-component/component.yaml
tests/nested/manual/core20-fault-inject-on-install-component/task.yaml
tests/nested/manual/core20-fault-inject-on-remodel/task.yaml
tests/nested/manual/core20-fault-inject-on-update-config/cloud.conf
tests/nested/manual/core20-fault-inject-on-update-config/defaults.yaml
tests/nested/manual/core20-fault-inject-on-update-config/task.yaml

This change includes some scenarios that are missing to check fault injection.
In this case are included fault/reboot for:
- install snapd --dangerous
- remodel
- install kernel component
- update boot config

tests: adding extra scenarios for fault injection

---

.github/workflows/nightly.yaml

This is required to fix an issue that happens when Coverity tool is used with go snap.
Also update the version of the checkout action to avoid a warning

tests: install go version using the setup-go@v5 action

---

.github/workflows/nightly.yaml

This fix is required to make the nightly job well.

tests: minor fix for step used to setup go version

---

.github/workflows/nightly.yaml

Apparently the examples in go-setup action were not tested well.

tests: remove run from got setup

---

.github/workflows/nightly.yaml

Missing steps to make the nightly job work

tests: use matrix to define version and remove snap step

---

.github/workflows/nightly.yaml

This step fails as we are not installing the go snap anymore

tests: remove go snap refresh from nightly job

---

.github/workflows/nightly.yaml

This is needed because staticcheck requires 1.23
go: honnef.co/go/tools/cmd/staticcheck@latest (in honnef.co/go/tools@v0.5.1): go.mod:3: invalid go version '1.22.1': must match format 1.23

tests: udpate the go version used for nightly run

---

overlord/hookstate/hooks.go
overlord/snapstate/component.go
overlord/snapstate/component_remove_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_remove_test.go
overlord/snapstate/snapstate_test.go
tests/lib/snaps/test-snap-component-hooks/two-hooks/remove
tests/main/component-refresh-hooks/task.yaml

This change lets us run component remove hooks.

o/snapstate, o/hookstate: run component remove hooks

---

cmd/libsnap-confine-private/locking-test.c
cmd/libsnap-confine-private/locking.c
cmd/libsnap-confine-private/locking.h
cmd/snap-confine/snap-confine.c
overlord/snapstate/backend_test.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_link_test.go
sandbox/cgroup/export_test.go
sandbox/cgroup/freezer.go
sandbox/cgroup/kill.go
sandbox/cgroup/kill_test.go
tests/lib/snaps/fork-bomb/bin/bomb
tests/lib/snaps/fork-bomb/bin/sh
tests/lib/snaps/fork-bomb/meta/snap.yaml
tests/main/snap-remove-terminate/task.yaml

unify termination algorithm for v1/v2
- for each snap cgroup:
- while cgroup.procs is not empty:
- SIGKILL each pid in cgroup.procs
- for v2 only
- set pids.max to 0 to counter fork-bombs (this is an alternative to cgroup freezing which is not available on older kernels)
- for v1 only
- kill pids found in freezer cgroup created by snap-confine (this is relevant for systemd v237 (used in ubuntu 18.04) for non-root users where the transient scope cgroups are not created)
- freeze/thaw using freezer cgroup because we cannot guarantee having the pids controller on hybrid systems on the cgroup version we are using
**Note: Terminating classic snap apps is best effort and cannot be guaranteed because a snap app can use systemd-run to break out of the cgroups used for tracking snap pids.**
This …

sandbox/cgroup: improve cgroup-based process termination algorithm

---

interfaces/prompting/patterns/render.go
interfaces/prompting/patterns/render_internal_test.go
interfaces/prompting/requestrules/requestrules.go
interfaces/prompting/requestrules/requestrules_test.go

Add a specific unit for parsing and then rendering a pattern which produces many identical variants.

interfaces/prompting/patterns: add checks for duplicate pattern variants

---

cmd/snap/cmd_pack.go
cmd/snap/cmd_pack_test.go
snap/container.go
snap/container_test.go
snap/pack/pack.go
snap/pack/pack_test.go

This improves some inconsistencies in "snap pack --check-skeleton" error logs.
- Shows detailed logs only if SNAPD_DEBUG is set.
- Returns first error caught
It should be explored how to aggregate errors with consistency in mind as this is parsed by snapcraft.
For more context: https://warthogs.atlassian.net/browse/SNAPDENG-23795

many: make snap pack --check-skeleton error logs consistent

---

.github/workflows/test.yaml
osutil/group_test.go
osutil/strace/strace_test.go
osutil/user/getent.go
osutil/user/getent_test.go
osutil/user/user.go
osutil/user/user_from_snap.go

github: test snapdusergo tag

---

osutil/disks/disks_darwin.go
osutil/disks/disks_linux.go
osutil/disks/disks_linux_test.go
overlord/devicestate/devicestate_install_mode_test.go
overlord/devicestate/devicestate_test.go
overlord/devicestate/export_test.go
overlord/devicestate/handlers_install.go
secboot/encrypt_sb.go
secboot/encrypt_sb_test.go
secboot/secboot_sb.go
secboot/secboot_sb_test.go

`by-partuuid` does not make much sense because it uselessly assumes that it is a partition. Conceptually we should not care about it.  It also makes the resolution more complex as we need to fetch information about the device which we do not really need at this point.
It is more common to resolve by filesystem UUID than part UUID. For instance cryptsetup accepts path as `UUID=deadbeef-dead-dead-dead-deaddeafbeef`. But it does not accept this kind of syntax for partitions.
We will also need to register the old paths with something like https://github.com/snapcore/secboot/pull/331

secboot: use uuid of luks2 instead of partition

---

interfaces/builtin/time_control.go
tests/lib/snaps/test-snapd-timedate-control-consumer/bin/sh
tests/lib/snaps/test-snapd-timedate-control-consumer/meta/snap.yaml
tests/main/interfaces-time-control/task.yaml

We already allow access to the symlinks themselves, but we weren't allowing access to their destinations.

i/builtin: allow accessing real-time clock device nodes via symlinks

---

data/selinux/snappy.te

This comes up when snap-update-ns called from snapd attempts to mount on files labeled with var_t, such as /var/cache/swcatalog.
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-32055

data/selinux: allow mounting on var_t

---

overlord/snapstate/snapstate_update_test.go

I spent a while trying to reproduce this issue by running the spread test manually, but I wasn't able to catch it in the act. I'm pretty confident the failures we're seeing are because of a timeout that is too low, since the state of the tasks when settle times out has been different in the cases where we have seen a failure. This indicates to me that we're not getting stuck on something specific.
Regardless, if we have a real issue where something is getting completely blocked, this won't solve anything. However, if the issue is that our timeout is just too low, then hopefully this will make things better.

o/snapstate: bump timeout in test*ComponentsRunThrough variants

---

tests/main/interfaces-time-control/task.yaml

`/sys/class/rtc/rtc0/wakealarm` seems to only be present on the amd64 machines. This will make this test work on arm as well, but still tests the same functionality.

tests/main/interfaces-time-control: use "name" device node since it is also present on arm systems

---

interfaces/builtin/opengl.go
interfaces/builtin/opengl_test.go

Add support for cuda workloads on Tegra iGPU in opengl interface
When run on a Tegra iGPU, cuda workloads require 4 more device nodes
than what is currently included in the opengl interface.
Notably, three device nodes are related to the GPU. On an integrated GPU on
tegra platforms, those correspond to `/dev/nvgpu/igpu0/power`,
`/dev/nvgpu/igpu0/ctrl` and `/dev/nvgpu/igpu0/prof`.
Additionally, we need read-write access to `/dev/host1x-fence`, which is a
tegra specific dma barrier.
In addition to granting write access in the apparmor profiles, we also
need to tag these device nodes in the udev rules.
This pull request is related to a previous one that created a new interface for this functionality: https://github.com/canonical/snapd/pull/14188
The device nodes listed are the ones needed to …

interfaces/bulitin/opengl: add support for cuda workloads on Tegra iGPU in opengl interface

---

daemon/access.go
daemon/access_test.go
daemon/api.go
daemon/api_system_secureboot.go
daemon/api_system_secureboot_test.go
daemon/export_access_test.go
daemon/export_api_system_secureboot_test.go
overlord/fdestate/fdestate.go

Add a dedicated integration API endpoint for controlling/notifying of secure boot keys databases updates.
This is a draft PR with no unit tests, with the purpose of validating the API endpoint and the policy around it.
Related: SNAPDENG-32364 SNAPDENG-31856

daemon: secureboot updates API endpoint

---

cmd/snap/cmd_debug_api.go

Add an option to choose access through the dedicated snap socket. Useful for debugging when curl isn't around.

cmd/snap/debug-api: option to choose access through /run/snapd-snap.socket

---

daemon/api.go
daemon/api_registry.go
daemon/api_registry_test.go
daemon/export_test.go
overlord/hookstate/ctlcmd/export_test.go
overlord/hookstate/ctlcmd/get.go
overlord/hookstate/ctlcmd/get_test.go
overlord/hookstate/ctlcmd/set.go
overlord/hookstate/ctlcmd/set_test.go
overlord/hookstate/ctlcmd/unset_test.go
overlord/registrystate/registrystate.go
overlord/registrystate/registrystate_test.go
overlord/registrystate/transaction.go
overlord/registrystate/transaction_test.go

Support `snapctl get --pristine ...` which allows snaps to read the state of the view disregarding the pending changes in the current transaction. Includes a small refactor to the registrystate functions that was necessary.

o/registrystate: support snapctl get --pristine

---

gadget/gadget.go
gadget/gadget_test.go

This method is needed to determine the size of the disk image to create in ubuntu-image.

gadget: add a Size method to Volume

---

asserts/snapasserts/validation_sets.go
asserts/snapasserts/validation_sets_test.go
daemon/api_validate_test.go
overlord/assertstate/assertstate_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_test.go
seed/seedwriter/writer.go

This will enable us to track components alongside snaps with validation sets.

a/snapasserts: keep track of components in validation sets

---

build-aux/snap/snapcraft.yaml

Pin the Ubuntu Advantage Pro FIPS updates PPA during the build. The PPA should be enabled on the build host, typically LP.
Related: SNAPDENG-33324

snapcraft: pin Ubuntu Advantage Pro FIPS Updates PPA when building FIPS variant

---

tests/core/snapd-maintenance-msg/task.yaml
tests/core/uc20-recovery/task.yaml
tests/lib/uc20-recovery.sh
tests/main/api-get-systems-label/task.yaml
tests/main/apparmor-prompting-flag-restart/task.yaml
tests/main/appstream-id/task.yaml
tests/main/aux-info/task.yaml
tests/main/debug-pprof/task.yaml
tests/main/generic-unregister/task.yaml
tests/main/interfaces-snap-interfaces-requests-control/task.yaml
tests/main/snap-quota-memory/task.yaml
tests/main/snap-quota-thread/task.yaml
tests/main/snapctl/task.yaml
tests/main/snapshot-exclusions-dynamic/task.yaml
tests/nested/core/core20-basic/task.yaml
tests/nested/core/core20-tpm/task.yaml
tests/nested/manual/core20-create-recovery/task.yaml
tests/nested/manual/muinstaller-core/task.yaml
tests/nested/manual/muinstaller-real/task.yaml
tests/nested/manual/muinstaller/task.yaml
tests/nested/manual/recovery-system-offline/task.yaml
tests/nested/manual/recovery-system-reboot/task.yaml
tests/nested/manual/recovery-system/task.yaml
tests/nested/manual/split-refresh/task.yaml

Modifies spread tests to use, when possible, `snap debug api` instead of `curl`.

tests: replaced curl with snap debug api

---

tests/lib/snaps/test-snapd-desktop-file-ids/meta/gui/bad. ,?**[]{}^\$#.desktop
tests/main/desktop-file-ids/task.yaml

This test file name used to exercise desktop file name sanitization was causing trouble when packaging snapd go library.
This switches the test to generate the guilty test desktop file dynamically and removes the weird test file completely.

tests/lib: remove test file that breaks snapd go library

---

sandbox/apparmor/apparmor.go
sandbox/apparmor/apparmor_test.go

While testing prompting behavior on a new oracular VM with the new kernel, prompting was reported as not supported due to lack of kernel features. This was unexpected, since oracular should support prompting, and has in recent testing.
`snap debug api /v2/system-info` reported the following in kernel features:
```
...
"kernel:policy",
"kernel:policy:notify",
"kernel:policy:permstable32:allow",
...
```
So we have `kernel:policy:notify` but we're missing `kernel:policy:notify:user:file`. This is strange, since:
```
ubuntu@oracular:~$ cat /sys/kernel/security/apparmor/features/policy/notify/user 
file
```
The new apparmor/kernel for oracular now has the more robust checks for prompting support, given by the presence of `/sys/kernel/security/apparmor/features/policy/notify/user`, but this has …

s/apparmor: fix check for prompting support for kernels with policy/notify/user

---

.github/workflows/test.yaml
spread.yaml
tests/lib/prepare-restore.sh

Remove the variables SNAPD_PUBLISHED_VERSION and
BUILD_SNAPD_FROM_CURRENT from the spread.yaml file
Those vars are not used in practice anymore

tests: remove not needed variables in spread.yaml

---

overlord/hookstate/hookmgr.go
overlord/hookstate/hookstate_test.go
overlord/hookstate/hooktest/handler.go

This reverts commit 8ffadb5d5b3304b9ce5c4801cdac78e4b7b55c1a. Due to changes in the way registry hooks are organised/named we no longer need this.

o/hookstate: remove precondition interface

---

tests/lib/prepare-restore.sh

This is a missing fix for how snap pkg is built without BUILD_SNAPD_FROM_CURRENT variable

tests: fix how snapd is built from current

---

overlord/snapstate/component.go
overlord/snapstate/component_install_test.go

The snap-setup-task was not being added to the prepare kernel-modules task in the case of installing from the store, which made the installation to fail.

overlord: make sure to reference the snap-setup-task in kmod tasks

---

tests/lib/pkgdb.sh

In oracular the packages systemd-cryptsetup and systemd-dev are not included anymore in the base image which is used in google and openstack.
This change adds this package as a tests dependency to avoid the following error when building snapd deb package.
To reproduce the error, run:
SPREAD_SNAPD_DEB_FROM_REPO=false spread -debug -no-debug-output google:ubuntu-24.10-64:tests/main/abort
Error:
configure: error: Package requirements (udev) were not met:
Package 'udev', required by 'virtual:world', not found

tests: install missing dependency to fix oracular building

---

.github/workflows/nightly.yaml

We received this communication:
"We are facing some infrastructure limitations due to the ramp up on CI integrations and we would like you to reduce the TIOBE runs to a single weekly run temporarily until we have this sorted out."

tests: run once a week the nightly static checks

---

client/clientutil/snapinfo_test.go
client/packages.go
client/packages_test.go
daemon/api_snaps_test.go
daemon/snap.go
overlord/snapstate/autorefresh.go
overlord/snapstate/backend_test.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/snapstate_update_test.go
snap/info.go
tests/lib/fakestore/store/store.go
tests/lib/fakestore/store/store_test.go
tests/lib/tools/snapd-state
tests/lib/tools/store-state
tests/main/auto-refresh-backoff/check_auto_refresh_count.sh
tests/main/auto-refresh-backoff/task.yaml

This PR implements a system to delay refreshing (auto-refreshing) a snap to the same revision in face of past failures as detailed in [SD183 - Avoiding failed upgrade loops](https://docs.google.com/document/d/1YmpZSvIoEeKeOGw-OA77j_PgCx0c7awCeee_9xlKIvU/edit) spec.
Since adding changes to the refresh logic is critical, I wrote the spread test first and went with TDD for this work. I faced some limitations and bugs in the fakestore because it wasn't designed with repeated auto-refreshes in mind.
The PR is split into multiple parts but closely related so I thought it would be inefficient to split into multiple PRs and ask for reviews on each. Those parts are:
- Update/Fix `fakestore` to handle multiple auto-refreshes properly
- Make `snapd-state` commands (specifically `force-autorefresh`) …

many: add snap auto refresh backoff

---

overlord/devicestate/firstboot.go
overlord/devicestate/firstboot20_test.go
overlord/devicestate/firstboot_test.go
snap/info.go
snap/info_test.go
snap/types.go

We need to seed the boot base before the kernel so we can run the recently added kernel hooks on seeding. Otherwise, snap-confine is not able to find a usable base for the kernel.

overlord,snap: order boot base before kernel when seeding

---

secboot/secboot_hooks.go
secboot/secboot_sb.go
secboot/secboot_sb_test.go
secboot/secboot_tpm.go

This factors and simplifies the TPM and FDE Hook code together. This does not yet factor the key file base one.

secboot: factor code for encrypted disk activation

---

overlord/snapstate/storehelpers.go

golangci-lint is failing due an unused function.

o/snapstate: remove unused function

---

run-checks

Running golangci-lint with --new-from-rev will only run it against the diff which is not enough to determine if the change adds issues (e.g., if it removes the last call to a function). Another alternative would be to still run it with --new-from-rev but also --whole-files which would mitigate it but not completely eliminate the chance of this happening.
It's expected that the CI fails until https://github.com/canonical/snapd/pull/14624 is merged and this is triggered again

run-checks: run golangci-lint on all files

---

cmd/snap/cmd_components.go
cmd/snap/cmd_components_test.go
cmd/snap/cmd_help.go
cmd/snap/main.go
tests/main/component-from-store/task.yaml

Needs some spread tests, but this implements what we have in the components spec for the "snap components" subcommand.

c/snap: add components subcommand to enable listing available and installed components for snaps

---

boot/assets_test.go
boot/boot_test.go
boot/export_test.go
boot/model_test.go
boot/seal.go
boot/seal_test.go
boot/systems_test.go
osutil/disks/disks.go
osutil/disks/disks_linux.go
osutil/disks/disks_linux_test.go
overlord/fdestate/backend/reseal.go
overlord/fdestate/backend/reseal_test.go
overlord/fdestate/export_test.go
overlord/fdestate/fdemgr.go
overlord/fdestate/fdemgr_test.go
overlord/fdestate/fdestate.go
overlord/managers_test.go
secboot/secboot.go
secboot/secboot_dummy.go
secboot/secboot_sb.go
secboot/secboot_sb_test.go
secboot/secboot_tpm.go

Ensure() initializes the empty profiles, and reseal updates them.
This is on top of #14400

overlord/fdestate: keep FDE state up to date

---

tests/main/snap-run/task.yaml

This fixes a problem in which strace and one of its dependent libraries (libunwind-ptrace) have an ABI disagreement. Instead of expecting a non-empty stderr, this searches instead for a keyword.

tests: fix snap-run failure

---

overlord/hookstate/ctlcmd/fail.go
overlord/hookstate/ctlcmd/fail_test.go
overlord/hookstate/ctlcmd/get.go
overlord/hookstate/ctlcmd/get_test.go
overlord/hookstate/ctlcmd/set.go
overlord/hookstate/ctlcmd/unset.go
overlord/registrystate/registrystate_test.go

Hides the registry-related commands behind the feature flag.

o/h/ctlcmd: hide snapctl registry commands behind feature flag

---

tests/main/disk-space-awareness/task.yaml

It seems snap size has crept up over time, and now 150M is not sufficient to hold all the snaps and data needed for the `disk-space-awareness` test. This PR bumps the size to 200M and sets a variable, so the value can more easily be adjusted in the future.

tests: increase disk-space-awareness default size to 200M

---

overlord/registrystate/registrymgr.go
overlord/registrystate/registrymgr_test.go

Fixes the scheduling of rollback tasks to revert a save-view hook. This it based on https://github.com/canonical/snapd/pull/14544, so the only relevant commit is the last one 3546db76cda074b60d24c6a53b79d649588a5db7.

o/registrystate: fix rollback of failed save-view hooks

---

tests/main/snap-quota-cpu/task.yaml

Apparently, in some cases, the cpu usage can contain more than two decimal points as seen here in this failure: https://github.com/canonical/snapd/actions/runs/11165803126/job/31038865747. This fixes the issue by removing any decimal points.

tests: fix failure in snap-quota-cpu spread test

---

tests/main/document-interfaces-url/task.yaml

Currently the servers are returning http status code 500 randomly making the test fail. 
Also, sometimes the server is taking to long to send the response so a connection timeout is needed.
Finally, the test now shows the interfaces which are having issues at the end of the output, so it is easier to see which interface is causing issues.

tests: fix document-interfaces-url test

---

boot/seal.go
boot/seal_test.go

Provide a dedicated helper for obtaining the boot chains relevant for
resealing of disk encryption keys.
Cherry picks from https://github.com/canonical/snapd/pull/14615

boot: provide a helper for obtaining boot chains for resealing
