daemon/api_sideload_n_try_test.go, daemon/api_snaps_test.go, daemon/snap.go, overlord/snapstate/refreshhints_test.go, overlord/snapstate/snapstate_update_test.go, overlord/snapstate/target_test.go, seed/seedwriter/seed16.go, seed/seedwriter/seed20.go, seed/seedwriter/writer.go, seed/seedwriter/writer_test.go, snap/component.go, snap/component_test.go, snap/pack/pack.go, snap/pack/pack_test.go, snap/snapenv/snapenv.go, snap/snapenv/snapenv_test.go, store/tooling/tooling.go
If there is no version filed in the component metadata, use the snap version as component version too.
=> many: use snap version in components when unspecified in them

interfaces/prompting/requestrules/requestrules.go, interfaces/prompting/requestrules/requestrules_test.go, overlord/ifacestate/apparmorprompting/prompting_test.go
Allow several rules which render to the same variant to coexist in the tree without conflict, so long as the outcome of all those overlapping rules is identical.
This allows the client to reply with "allow read forever for /foo/bar" and then later say "allow read|write forever for /foo/bar" without the latter being treated as a rule conflict error. Clearly, the second rule is a superset of the first, and there's no intent-based reason that these two rules couldn't coexist, it was just an implementation detail that we previously only allowed a pattern variant to be associated with a single rule ID.
Now, each pattern variant in the tree for a particular snap, interface, and permission can be associated with a set of rule IDs. Any non-expired rules in that set must have the same outcome. Any …
=> i/p/requestrules,o/i/apparmorprompting: allow overlapping rules

interfaces/mount/backend.go
When snapd calls snap-update-ns and that operation fails, as a last resort the namespace is discarded. Show the error that is causing this so that it can be debugged better.
=> interfaces/mount: show error causing discard

overlord/snapstate/snapstate.go, overlord/snapstate/snapstate_update_test.go, overlord/snapstate/storehelpers.go, overlord/snapstate/target.go, overlord/snapstate/target_test.go
This will eventually enable something like a `snap refresh <snapname>+<compname>`, where `<compname>` is a new component that will be installed during the refresh.
=> o/snapstate: enable installing additional components during a refresh

tests/main/component-from-store/task.yaml
Restore was failing on `google-distro-1:fedora-39-64:tests/main/component-from-store`:
```
...
postinst purge failed
+ ls -lR /var/lib/snapd/snap/ /var/snap/
/var/lib/snapd/snap/:
total 4
drwxr-xr-x. 1 root root 20 Oct 21 18:48 test-snap-with-components_key
...
```
=> tests/main/component-from-store: fix restore now that another snap is installed during test

interfaces/apparmor/template.go
As discovered while running Slack on Debian, it seems required and sensible to allow read-access to /etc/debian_version in a similar manner to /etc/os-release.
Reference: https://forum.snapcraft.io/t/cant-start-slack-on-debian-bookworm/41630/2
=> interfaces: apparmor: Add read-access to debian_version to the template

secboot/secboot_sb.go, secboot/secboot_sb_test.go
Key datas may be in the tokens of the key slot. ActivateVolumeWithKeyData will read those. So in the case the key file does not exist, we should still try without keydata.
=> secboot: allow unlocking without key file

boot/boot_test.go, boot/bootchain_test.go, boot/boottest/fde.go, boot/export_test.go, boot/model_test.go, boot/seal.go, boot/seal_test.go, boot/systems_test.go
Based on #14625. Move some test helpers into boot/boottest so that they can be reused in unit tests of other packages. Allow mocking seed.ReadSystemEssential in boot package in unit tests.
Related: SNAPDENG-32509
=> boot, boottest: move helpers to boottest, allow mocking seed functions

cmd/snap-confine/mount-support.c
We mount the tmpfs which will be used as the rootfs of the mount namespace of the snap without any options. Since at the time were are running as root (user) but keep the original group of the calling user, this captures the gid of the user in the mount options.
Pass uid=0,gid=0 explicitly, so that it is not an issue.
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-33380
=> cmd/snap-confine: pass uid/gid to initial tmpfs

boot/modeenv.go, boot/modeenv_test.go, overlord/devicestate/devicemgr.go, overlord/devicestate/handlers.go, overlord/devicestate/handlers_install.go, overlord/devicestate/systems.go, overlord/fdestate/export_test.go, overlord/fdestate/fdemgr.go, overlord/fdestate/fdemgr_test.go, overlord/fdestate/fdestate.go, overlord/managers_test.go, overlord/overlord.go
Attempt to improve the behavior when one of data or save partitions isn't mounted, thus only even consider failures when we are in run mode. There is a FIXME which we will need to address at some point to degrade this in a nicer way. Handle preseeding, by simply skipping all initialization there.
Supersedes https://github.com/canonical/snapd/pull/14644
=> overlord/fdestate: improve error handling when one of partitions isn't mounted, handle preseeding

tests/core/snapd-refresh-vs-services-reboots/task.yaml, tests/core/snapd-refresh-vs-services/task.yaml
Tests snapd-refresh-vs-services-reboots and snapd-refresh-vs-services no longer work on core18 because the kernel on core18 uses snap-declaration assertion format 5. These tests use snapd version 2.29.2, which only supports format 4 of snap-declaration assertions.
=> tests: disable some tests that no longer work on core18

tests/lib/prepare.sh
StartLimitBurst and StartLimitIntervalSec should be placed in the unit section.
=> tests/lib/prepare: use correct section for snapd service overrides related to service restarts

daemon/api_registry_test.go, overlord/hookstate/ctlcmd/export_test.go, overlord/hookstate/ctlcmd/get.go, overlord/hookstate/ctlcmd/get_test.go, overlord/hookstate/ctlcmd/set.go, overlord/hookstate/ctlcmd/unset_test.go, overlord/registrystate/registrystate.go, overlord/registrystate/registrystate_test.go, registry/registry.go, registry/registry_test.go, tests/main/registries-cross-config/task.yaml, tests/main/registries/task.yaml
Refactor the not found errors as we now also have to use them in registrystate so the previous construction is not convenient. Also improves clarity and consistency in some of the errors messages. The second commit adds a GetView function to registrystate so it can be used in several places and removes some usages of Set from ctlcmd tests (so we can remove it in the next PR when we stop using it in the API). This became a bit of a ball of mud of refactorings but I'd like to do them before moving on to the next epics
=> many: refactor registry errors and add GetView function

cmd/snap-bootstrap/cmd_initramfs_mounts.go, cmd/snap-bootstrap/cmd_initramfs_mounts_test.go, cmd/snap-bootstrap/hybrid_users_import.go, cmd/snap-bootstrap/hybrid_users_import_internal_test.go, tests/lib/muinstaller/mk-classic-rootfs.sh, tests/nested/manual/muinstaller-real/extra-paths, tests/nested/manual/muinstaller-real/task.yaml
This PR changes snap-bootstrap so that we import users from the sudo and admin groups into the ephemeral system that is created when we boot into recovery mode.
=> c/snap-bootstrap: import users from hybrid system into recovery system

data/selinux/snappy.te
The upstream selinux-policy has dropped timedatex in https://github.com/fedora-selinux/selinux-policy/commit/2246d17b3c63df73e3359161a9c4e9c07d1cd523 Even when referencing type that no longer exists, our SELinux module builds fine, but then cannot be loaded at runtime:
```
maciek@localhost:~/snapd/data/selinux$ sudo semodule -i snappy.pp.bz2
Failed to resolve typeattributeset statement at /var/lib/selinux/targeted/tmp/modules/400/snappy/cil:223
Failed to resolve AST
semodule:  Failed!
```
And the offending line is:
```
maciek@localhost:~/snapd/data/selinux$ /usr/libexec/selinux/hll/pp snappy.pp | tail -n +223 | head -1
(typeattributeset cil_gen_require timedatex_t)
```
Fixes: https://bugs.launchpad.net/snapd/+bug/2085535
Have you signed the …
=> data/selinux: remove timedatex

.github/workflows/coverity-scan.yaml
Since the scan.coverity.com API throttles submissions, run weekly for now.
=> .github/workflows/coverity-scan.yaml: add github action for Coverity

cmd/snap-mgmt/snap-mgmt.sh.in, packaging/debian-sid/snapd.postrm, packaging/ubuntu-14.04/snapd.postrm, packaging/ubuntu-16.04/snapd.postrm, tests/main/component-from-store/task.yaml, tests/main/postrm-purge/task.yaml, tests/main/snap-mgmt/task.yaml
This script was failing when ran on systems that have components installed because it was attempting to remove files that were part of the mounted components. Unmounting them first should solve that.
=> c/snap-mgmt: unmount components before unmounting snaps

tests/main/nvidia-files/task.yaml
This variant is currently failing to `apt-get install` the needed packages.
=> tests/main/nvidia-files: set ubuntu-20.04-64/550-server to broken packaging in table of expectations

daemon/api.go, daemon/api_registry.go, daemon/api_registry_test.go, daemon/export_test.go, overlord/hookstate/ctlcmd/export_test.go, overlord/hookstate/ctlcmd/set.go, overlord/hookstate/ctlcmd/set_test.go, overlord/hookstate/ctlcmd/unset_test.go, overlord/registrystate/registrystate.go, overlord/registrystate/registrystate_test.go, overlord/state/state.go, overlord/state/state_test.go, tests/main/registries/task.yaml, tests/main/registries/test-custodian-snap/bin/sh, tests/main/registries/test-custodian-snap/meta/hooks/manage-wifi-view-changed, tests/main/registries/test-custodian-snap/meta/snap.yaml
29f4a008d5ccde85d5d68f658b11bb5fb9703506 allows TaskChanged handlers to signal that they should be removed after being called (this simplifies the removal of the handler since there's no need to track the ID, lock state, remove the handler, etc).
d2cccac161a264916f7222b90218dee5a8ba980b makes the API code (used in the `snap set --view` path) create a transaction and an associated change to commit it. It also removes the registrystate.Context in lieu of a simpler callback that is returned with the transaction to trigger the commit. That callback then returns the change ID or wait channel.
=> many: registry API creates transaction commit change

store/cache.go
Refactor the store cache manager cleanup to make it easier to follow and do not keep repeating the same operations multiple times.
=> store: refactor and improve store cache

snap/snapenv/snapenv_test.go, snapdtool/tool_test.go
If the environment running the unit tests has SNAP_REEXEC set, then these tests will fail. This fixes them to either not depend on the value or to properly validate that we're reading it.
=> s/snapenv, snapdtool: fix tests that depend on user's SNAP_REEXEC

boot/seal.go, boot/seal_test.go, overlord/fdestate/backend/export_test.go, overlord/fdestate/backend/reseal.go, overlord/fdestate/backend/reseal_test.go, secboot/export_sb_test.go, secboot/secboot_dummy.go, secboot/secboot_hooks.go, secboot/secboot_sb_test.go, tests/lib/fakestore/store/store.go, tests/lib/tools/store-state, tests/nested/manual/remodel-uc-to-next-version-fakestore/prepare-device, tests/nested/manual/remodel-uc-to-next-version-fakestore/repack-kernel.sh, tests/nested/manual/remodel-uc-to-next-version-fakestore/task.yaml
This also adds:
* tests/lib/fakestore: add support for tracking channels
* tests: add remodeling test using fakestore
=> overload/fdestate/backend: implement FDE hook resealing

interfaces/builtin/desktop.go, interfaces/builtin/shutdown.go, interfaces/builtin/system_observe.go, interfaces/builtin/upower_observe.go
This is extracting the commits from #13920 not related with the `systemd-user-control` interface as requested by @zyga.
It is mostly about
* adding a few missing members on already exposed interfaces
* exposing a few interfaces on core which were missing
* doing a couple of adjustments for KDE Plasma based sessions in the `desktop` interface
=> interfaces: Improving use of existing interfaces on core

interfaces/builtin/desktop.go
This allows applications to notify the session about job progression and implement the status notifier item protocol.
=> interfaces/desktop: Improve launch entry and systray integration with session

overlord/fdestate/backend/reseal.go, overlord/fdestate/backend/reseal_test.go, secboot/secboot.go, secboot/secboot_sb_test.go, secboot/secboot_tpm.go
A helper in fdestate backend to reseal with DBX update payload.
Cherry picked from #14615 
Related: SNAPDENG-32509 SNAPDENG-34135
=> secboot, o/fdestate/backend: reseal with DBX update payload

.github/workflows/test.yaml
Go formatting has been pretty stable after the 'breaking' changes introduced in 1.18. There is no clear reason to not simply use the latest/stable version, which is also most likely the version folks use for local development.
Cherry picked from https://github.com/canonical/snapd/pull/14676 
=> github: only check formatting when using latest/stable Go

asserts/snapasserts/snapasserts.go, asserts/snapasserts/snapasserts_test.go, image/helpers.go, image/image_test.go, overlord/assertstate/assertmgr.go, overlord/assertstate/assertstate_test.go, seed/seed20_test.go, seed/seedtest/seedtest.go
This adds some cross-checks that were missing for components. Testing this was a bit messy unfortunately.
=> many: complete various component cross-checks

cmd/snap-bootstrap/initramfs_systemd_mount.go, cmd/snap-bootstrap/initramfs_systemd_mount_test.go
First PR in preparation of tightening mount options for ubuntu core partitions.
This will allow setting those options on certain mounts (i.e ubuntu-save).
REF: SNAPDENG-34143
=> cmd/snap-bootstrap: support for noexec and nodev options

cmd/snap-bootstrap/cmd_initramfs_mounts.go, cmd/snap-bootstrap/cmd_initramfs_mounts_nosecboot.go, cmd/snap-bootstrap/cmd_initramfs_mounts_secboot.go, cmd/snap-bootstrap/cmd_initramfs_mounts_test.go, cmd/snap-bootstrap/export_test.go, secboot/export_sb_test.go, secboot/secboot_sb.go, secboot/secboot_sb_test.go, secboot/secboot_tpm.go
=> cmd/snap-bootstrap: unlock save partition with protector key

interfaces/builtin/opengl.go, interfaces/builtin/opengl_test.go
This is used to control AMD GPUs, especially when using the [ROCm](https://www.amd.com/en/products/software/rocm.html) software stack.
This is my first time contributing to snapd, so please let me know if I missed something :smile:
=> daemon: Add Kernel Fusion Driver access to opengl

tests/lib/pkgdb.sh, tests/main/snap-seccomp-syscalls/task.yaml
Migrate this test to noble as there is not new images for bionic anymore.
=> tests: migrate snap-seccomp-syscalls to noble

tests/lib/prepare-restore.sh
The service in Xenial randomly fails to create a socket on virbr0-nic.
The problem is fixed when the ntp service is restarted. The test tests/main/auto-refresh is fixed with this change.
The errror lines are:
ntpd: bind(23) AF_INET6 ... flags 0x11 failed: Cannot assign requested address
ntpd: unable to create socket on virbr0-nic
ntpd: kernel reports TIME_ERROR: 0x41: Clock Unsynchronized
=> tests: restart ntp in Xenial to prevent errors in auto-refresh

overlord/ifacestate/handlers.go, overlord/ifacestate/helpers.go, overlord/ifacestate/ifacestate_test.go, overlord/snapstate/export_test.go, overlord/snapstate/handlers_components.go, overlord/snapstate/snapmgr.go
In a scenario where two snaps with connected content plugs and slots were refreshed together, the first snap to be refreshed could get an AppArmor profile generated that used the previous revision (so revisioned paths like $SNAP_DATA and $SNAP_USER_DATA) would not be accessible. The issue is that we generate security profiles for connected snaps when generating the profile for the refreshed snap but don't take into account that the snap may have been refreshed in the same change (the new revision isn't reflected in state yet). So we'd generate an incorrect AppArmor profile with the previous revision. I couldn't add a spread test to tests/regression/ because it's not a deterministic failure.
=> o/ifacestate: fix generation of AppArmor profile w/ incorrect revision

interfaces/builtin/mpris.go
Similar to #13737. Amending this makes mpris work again in plasma.
=> i/b/mpris: add plasmashell as label

interfaces/builtin/common_files.go, interfaces/builtin/personal_files_test.go, interfaces/builtin/system_files_test.go
For the `common-files` interface and those which use `commonFilesInterface` (such as `system-files` and `personal-files`), these append a trailing `{,/,/**}` to the end of each path.
The `@` character is allowed in filepaths specified in these plugs, since filepaths like `/dev/foo@bar` may be required. However, if an `@` character occurs at the end of the filepath (e.g. `/foo/bar@`), then the resulting filepath in the rule is `/foo/bar@{,/,/**}`. AppArmor treats `@{FOO}` as a variable, so having `@{,/,/**}` in the final rule snippet is problematic.
This commit adds a check to `common_files.go` to ensure that filepaths do not have a trailing `@`.
This addresses https://github.com/canonical/snapd/pull/14651#issuecomment-2452778487
=> i/builtin: prohibit trailing '@' in common-files filepaths

cmd/snap/cmd_debug_api.go, cmd/snap/cmd_debug_seeding.go, cmd/snap/cmd_debug_validate_seed.go
After reviewing all debug commands, the all that are hidden also use `(internal)` in the help message, and the ones that aren't have reasonable help messages.
For clarity, the `snap debug seeding` and `snap debug validate-seed` are exposed since folks already use them in various contexts, so there is no point in keeping them hidden.
Related: [SNAPDENG-26743](https://warthogs.atlassian.net/browse/SNAPDENG-26743)
[SNAPDENG-26743]: https://warthogs.atlassian.net/browse/SNAPDENG-26743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> cmd/snap: expose debug validate-seed and debug seeding

cmd/snap/cmd_run.go, cmd/snap/cmd_run_test.go, cmd/snap/inhibit_test.go, cmd/snaplock/lock.go, cmd/snaplock/runinhibit/inhibit.go, cmd/snaplock/runinhibit/inhibit_test.go, overlord/hookstate/ctlcmd/refresh.go, overlord/hookstate/ctlcmd/refresh_test.go, overlord/hookstate/hooks.go, overlord/hookstate/hooks_test.go, overlord/snapstate/backend.go, overlord/snapstate/backend/link.go, overlord/snapstate/backend/link_test.go, overlord/snapstate/backend/locking.go, overlord/snapstate/backend/locking_test.go, overlord/snapstate/backend/setup.go, overlord/snapstate/backend/setup_test.go, overlord/snapstate/backend_test.go, overlord/snapstate/handlers.go, overlord/snapstate/handlers_link_test.go, overlord/snapstate/refresh.go, overlord/snapstate/refresh_test.go, tests/regression/lp-2084730/task.yaml
This avoids the deadlock scenario:
- snap run holds inhibition lock.
- snapd holds state lock (link-snap).
- snapd tries to hold inhibition lock but waits for snap run to release lock.
- snap run calls the REST API (i.e. for notices, connections) which tries to hold state lock.
- snap run is now waiting for snapd to release state lock (to send the notice) and snapd is waiting for snap run to release the inibition lock.
- we have a deadlock and snapd state is locked.
Unlocking snapd state using the new explicitly passed unlocker to runinhibit helpers avoids this deadlock.
Fixes: https://bugs.launchpad.net/snapd/+bug/2084730
This is an alternative approach to https://github.com/canonical/snapd/pull/14669
=> many: add state unlocker to runinhibit helpers

overlord/snapstate/backend.go, overlord/snapstate/backend/link.go, overlord/snapstate/backend/link_test.go, overlord/snapstate/backend_test.go, overlord/snapstate/handlers.go, overlord/snapstate/handlers_link_test.go, overlord/snapstate/snapstate_install_test.go, overlord/snapstate/snapstate_remove_test.go, overlord/snapstate/snapstate_test.go, overlord/snapstate/snapstate_update_test.go
Backend.LinkSnap prepares the system for a reboot, move that bit to a different backend method so we can use it from tasks different from link-snap, as we now plan to do reboots later that said task in some cases.
=> o/snapstate: move the reboot part of Backend.LinkSnap to a new method

gadget/gadget.go, gadget/gadget_emmc_test.go, gadget/validate.go, gadget/validate_test.go, overlord/install/install_test.go
This is the first PR of 3 (likely) in the road to emmc support.
The first PR (this one)
- Implement the neccessary syntax support for gadgets to specifiy eMMC hardware boot partitions and which images go there during gadget updates
Next PRs:
- Add support for volume-assignments (https://github.com/canonical/snapd/pull/14563)
- Add support for eMMC partitions during gadget updates
REF: SNAPDENG-32142
=> gadget: emmc syntax support

tests/lib/prepare.sh
It may happen that a prepare step of a 'core' suite fails, which
followed by successful restore, will lead spread to try and run another
suite on the same host (eg. tests/core/ fails, followed by attempt to
start tests/main/). Make sure that each time we run prepare and repack
things, a new temp directory is used, so that subsequent suite runs do
not conflict with each other.
=> tests/lib/prepare: create a temp directory when repacking snaps

.golangci.yml
Enable the depguard linter. We alredy have some rules for it, but forgot to enable the linter itself.
=> golangci: enable depguard

tests/lib/prepare.sh
We were just appending to the snap-bootstrap binary instead of replacing it. Fixes
google-nested:ubuntu-24.04-64:tests/nested/core/core20-kernel-failover:crash.
=> tests: properly inject kernel failure for UC24

cmd/snap-bootstrap/cmd_initramfs_mounts.go, cmd/snap-bootstrap/cmd_initramfs_mounts_test.go, tests/core/basic20plus/task.yaml
Tightens mount flags for ubuntu-save by setting nodev, nosuid and noexec
REF: SNAPDENG-34144
=> cmd/snap-bootstrap: add nodev, nosuid and noexec to ubuntu-save in run/factory-reset

tests/main/mounts-persist-refresh-content-snap/task.yaml, tests/main/mounts-persist-refresh-content-snap/test-snapd-desktop-layout-with-content/bin.sh, tests/main/mounts-persist-refresh-content-snap/test-snapd-desktop-layout-with-content/bin/crash-foo-font, tests/main/mounts-persist-refresh-content-snap/test-snapd-desktop-layout-with-content/bin/sh, tests/main/mounts-persist-refresh-content-snap/test-snapd-desktop-layout-with-content/meta/snap.yaml
There are three real bug fixes, broken out as separate patches:
- `meta/snap.yaml` is malformed
- `/usr/share/fonts/foo-font` directory was not cleaned up
- startup of `snap run --shell ... &` was racing with snap install
That last issue is the most serious, as the test checks what is going on to a process in a constructed mount namespace in face of updates but the race could have been lost and the invisible update may have masked a real bug in snapd.
=> tests: assorted fixes for mounts-persist-refresh-content-snap

interfaces/builtin/custom_device.go, interfaces/builtin/custom_device_test.go
Allow the `@` symbol to occur in filepaths for the custom-device interface. This is common in paths under `/sys/`, such as `/sys/devices/platform/soc@0/soc@0:bus@30000000/30350000.ocotp-ctrl/imx-ocotp0/nvmem`.
This work is tracked internally by https://warthogs.atlassian.net/browse/SNAPDENG-32542
=> i/builtin: allow @ in custom-device filepaths

tests/lib/spread/backend.openstack.yaml
We need to update the plan used in openstack in order to save disk space which is not needed for testing.
=> tests: use images with 20G disk in openstack

interfaces/builtin/screen_inhibit_control.go, interfaces/policy/basedeclaration_test.go
* Make it available on Ubuntu Core
* Receive notifications for inhibit changes, plugged application could change the inhibit status but had no way to be notified when it actually changes.
=> interface/screen_inhibit_control: Improve screen inhibit control for use on core

.golangci.yml, randutil/rand.go, run-checks, testtime/export_test.go, testtime/testtime.go, testtime/testtime_test.go, timeutil/timer.go, timeutil/timer_test.go
Introduce a `testtime` package with a `Timer` interface which can be used in place of `time.Timer` when we want direct control over timers in tests.
The `testtime.Timer` interface is fully compatible with `time.Timer`, except that the former has a `C()` method instead of instance variable, as interfaces cannot have instance variables. As such, `time.Timer` does not directly implement `testtime.Timer`, so we must define a minimal wrapper (`testtime.RealTimer`) which directly calls the functions/methods associated with `time.Timer`, and exposes the latter's `C` instance variable as `C()`.
The `testtime.TestTimer` struct simulates the behavior of `time.Timer`, except that control of the passage of time and the ability to fire the timer are provided directly to the user. This way, tests which …
=> testtime: add mockable timers for use in tests

.github/labeler.yml, .github/workflows/spread-tests.yaml, tests/lib/spread/rules/nested.yaml
Through this change we will run the tests suggested by the spread-filter tool following the rules located in tests/lib/spread/rules which defined for each system.
For nested tests, this ruleset will make sure that: . Always that the nested.sh lib or the assertions dir are updated, all the nested test are executed
. When an specific nested test is added/updated, then this is executed
. If the "Run Nested" label is added to the PR, all the nested tests will be executed as well.
. In master branch, all nested test are executed
. In other scenarios, nested tests are not executed.
Also, in master branch, all the tests are executed (the tests defined in the matrix for each system).
=> tests: udpate the github workflow to run tests suggested by spread-filter tool

tests/lib/tools/store-state, tests/main/interfaces-custom-device-app-slot/task.yaml, tests/main/store-state/snap/meta/snap.yaml.in, tests/main/store-state/task.yaml, tests/main/system-usernames-snap-scoped/snap/meta/snap.yaml.in, tests/main/system-usernames-snap-scoped/task.yaml
Use `set -e` in the store-state tool to catch errors. Fix failing tests. Update tests/main/store-state to use core22 instead of core for the test snap.
Cherry picked from #14686
=> tests/lib/tools/store-state: exit on errors, update relevant tests

.github/workflows/spread-tests.yaml
This change is needed to avoid error in the ci when spread doesn't find any test to run with the provided filter.
=> tests: no need to run spread when there are not tests matching the filter

interfaces/builtin/fwupd.go
Downstream issue: https://github.com/fwupd/fwupd/issues/8014
=> interfaces/builtin/fwupd.go: allow access to nvmem for thunderbolt plugin

interfaces/builtin/desktop_legacy.go
com.canonical.dbusmenu is used to define actions for app-indicators. The desktop-legacy interface already has rules to allow app-indicators, so it shold also allow com.canonical.dbusmenu.
Rules copied from the unity7 interface.
=> interfaces/desktop-legacy: allow DBus access to com.canonical.dbusmenu

tests/lib/nested.sh, tests/lib/tools/setup_nested_hybrid_system.sh, tests/lib/tools/tests.nested, tests/nested/manual/muinstaller-core/task.yaml, tests/nested/manual/muinstaller-real/task.yaml
When restarting a nested VM, we reset the EFI variables and the TPM. It was possible to keep the state of the TPM, but it makes little sense to keep the TPM but not the EFI variables. With the new secboot, both resetting EFI and resetting the TPM will potentially cause recovery key to be needed.
This fixes the case where an installer image would create a sbatlevel revocation, and get a different one after reset and boot with the gadget snap.
=> tests/lib/tools/tests.nested: change --tpm-no-restart to --keep-firmware-state

gadget/install/content.go, gadget/install/content_test.go, gadget/install/export_test.go, gadget/install/install.go
Prerequisite for changing mount flags during install mode for ubuntu-save
=> gadget/install: support for no{exec,dev,suid} mount flags

tests/main/services-socket-activation/task.yaml, wrappers/services.go, wrappers/services_test.go
Reported here: https://bugs.launchpad.net/snapd/+bug/2083961 it seems that we fail to restart services that have activation units when passing `--reload`.
When we do `snap restart` we actually do `systemctl stop ...` and then `systemctl start ...`. This works completely fine when doing this on activated service units, with their activation units, and thus we do not see an issue here.
When we do `snap restart --reload`, we directly call `systemctl reload-or-restart` on the service unit and its activation units, however this causes an error from systemd, for two different reasons:
* We cannot restart socket units while the main service is running (i.e main service must be stopped, which happens during normal restart path)
* Systemd does not support reloading of socket units (so --reload …
=> wrappers: do not reload activation units

spread.yaml, tests/lib/prepare-restore.sh, tests/lib/tools/simpleget
It is not viable to build gojq in some of the test environments (eg. beta validation), so use a prebuilt binary from github.
Since we do not always have a wget or curl available on the host, add a simplistic replacement which is only capable of fetching files.
**NOTE** this doesn't solve the case for armhf yet, we do not have prebuilt binaries available there.
Related: [SNAPDENG-34224](https://warthogs.atlassian.net/browse/SNAPDENG-34224)
[SNAPDENG-34224]: https://warthogs.atlassian.net/browse/SNAPDENG-34224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> spread, tests: use prebuilt gojq, add simple tool for fetching files

tests/nested/manual/snapd-removes-vulnerable-snap-confine-revs/task.yaml
SNAPDENG-34146
fixes snapd-removes-vulnerable-snap-confine-revs intermittent failure
=> tests: add wait for seeding to finish at the end of the prepare script

tests/main/nvidia-files/task.yaml
Split exceptions table per system, for easier visual inspection. Add new entries to cover 24.10.
One notable problem is the 560 driver is not really working, causing a segvfault on startup.
```
zyga@novigrad:~$ test-snapd-nvidia.64
+ shopt -s nullglob
+ export LD_LIBRARY_PATH=/snap/test-snapd-nvidia/2/usr/lib/x86_64-linux-gnu:/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void
+ LD_LIBRARY_PATH=/snap/test-snapd-nvidia/2/usr/lib/x86_64-linux-gnu:/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void ++ ls /var/lib/snapd/lib/gl/libEGL_nvidia.so.0 /var/lib/snapd/lib/gl/libEGL_nvidia.so.560.35.03 /var/lib/snapd/lib/gl/libGLESv1_CM_nvidia.so.1 /var/lib/snapd/lib/gl/libGLESv1_CM_nvidia.so.560.35.03 /var/lib/snapd/lib/gl/libGLESv2_nvidia.so.2 …
```
=> tests: extend nvidia-files to check 24.10

.github/workflows/test.yaml, tests/lib/pkgdb.sh
This is the first part of the migration to start using openstack to run spread tests in openstack located in PS6
=> tests: migrate centos-9 from google to openstack

.github/workflows/spread-tests.yaml
Updated the check needed to run nested tests in the ci based on the group name.
=> tests: fix execution of nested tests in ci workflow

.github/workflows/test.yaml, spread.yaml, tests/lib/pkgdb.sh, tests/main/cgroup-devices-v1/task.yaml, tests/main/cgroup-freezer/task.yaml, tests/main/cgroup-tracking-failure/task.yaml, tests/main/lxd-mount-units/task.yaml, tests/main/lxd-postrm-purge/task.yaml, tests/main/lxd-snapfuse/task.yaml, tests/main/lxd-try/task.yaml, tests/main/lxd/task.yaml, tests/main/upgrade-from-release/task.yaml
This branch adds support for ubuntu plucky. 
Also moves oracular to no-lts
Related: [SNAPDENG-34223](https://warthogs.atlassian.net/browse/SNAPDENG-34223)
[SNAPDENG-34223]: https://warthogs.atlassian.net/browse/SNAPDENG-34223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> tests: add support for ubuntu plucky

tests/lib/spread/backend.testflinger.beta.yaml, tests/lib/spread/backend.testflinger.edge.yaml
Replace the old images with the new ones in snapd project
=> tests: update images used for core24 snap validation

interfaces/builtin/network_control.go, interfaces/builtin/network_manager.go
Fixes: https://bugs.launchpad.net/snapd/+bug/2086203
=> interfaces/network_{control,manager}: add missing dbus link rules

interfaces/builtin/udisks2.go
Otherwise:
```
apparmor="DENIED" operation="dbus_method_call"  bus="system" path="/org/freedesktop/UDisks2" interface="org.freedesktop.DBus.Peer" member="Ping" mask="send" name="org.freedesktop.UDisks2" pid=4321 label="snap.<foo>.<bar>" peer_pid=1234 peer_label="unconfined"
```
=> interfaces/udisks2: allow `Ping`ing the UDisks2 service

interfaces/apparmor/template.go
This is used by auditd, and is generally safe to expose.
=> interfaces/default: allow owner read on `@{PROC}/@{pid}/sessionid`

interfaces/builtin/network_manager_observe.go
GetAllDevices and GetDeviceByIpIface dbus methods looks appropriate to be part of the network-manager-observe interface. See https://forum.snapcraft.io/t/mission-center-auto-connection-requests/43198/22
=> i/b/network_manager_observe: add getDevices methods

data/completion/bash/snap, data/completion/zsh/_snap, tests/main/completion/install.exp, tests/main/completion/task.yaml
Allow tab completion in bash and zsh when `snap install`ing a local `.comp` file
=> data/completion: add tab completion for local component files

interfaces/builtin/u2f_devices.go, interfaces/builtin/u2f_devices_test.go
This adds the Nitrokey Passkey FIDO2/U2F device to the `u2f_devices.go` list. I hope, this is the right way. I made it work in Firefox on my system by editing `/etc/udev/rules.d/70-snap.firefox.rules` manually.
You can verify the VendorId and ProductID here:
https://github.com/Nitrokey/nitrokey-udev-rules/blob/48482a54e4c101dcac4991af4b4f006e75800d84/41-nitrokey.rules#L23
(I haven't signed the license agreement, because it wouldn't let me without providing a "Canonical Project Manager or contact" – which I don't have...)
Edit: Nevermind. I have signed the agreement …
=> i/b/u2f_devices: add Nitrokey Passkey

gadget/install/install.go, gadget/install/install_test.go
This makes us mount ubuntu-save with no{dev,exec,suid} during install-mode as well
=> gadget/install: switch mount flags for ubuntu-save to no{dev,exec,suid}

interfaces/apparmor/template.go
With the `microcloud` snap, we need an editor and `vim.tiny` is conveniently shipped in the `coreXX` base snaps so let's make it possible to use it.
=> i/apparmor: allow using `vim.tiny` (available in base snaps)

daemon/api_snap_conf.go, daemon/api_snap_conf_test.go, overlord/configstate/config/export_test.go, overlord/configstate/config/transaction.go, overlord/configstate/configcore/experimental.go, tests/main/old-experimental-flags/task.yaml
There is window between moving an experimental flag out of experimental and possibly having a snapd revert to a version where the experimental flag was used.
To avoid breaking devices that depend on those flags, instead of removing them completely from state, let's hide them instead.
This PR will unblock https://github.com/canonical/snapd/pull/14117 and other attempts to move features out of experimental.
This PR replaces https://github.com/canonical/snapd/pull/14258.
=> daemon: hide old experimental flags

spread.yaml
This is needed to run the next set of sru validations
=> tests: add ubuntu oracular to google-sru backend

dirs/dirs.go, dirs/dirs_test.go, overlord/fdestate/fdemgr_test.go, overlord/fdestate/fdestate.go, overlord/managers_test.go
We used a path that is not a mount point on hybrid to discover the data disk. Instead we now use / for hybrid, and /writable on core.
=> overlord/fdestate/fdestate.go: fix path to data mount point on hybrid

tests/lib/nested.sh
Some tests like
`tests/nested/manual/core20-install-mode-shutdown-via-hook` source this script with `-u` set. So `NESTED_KEEP_FIRMWARE_STATE` which is potentially unbound has to be used as such.
=> tests/lib/nested.sh: allow unbound NESTED_KEEP_FIRMWARE_STATE

cmd/libsnap-confine-private/utils-test.c, cmd/libsnap-confine-private/utils.c, interfaces/system_key.go, tests/main/command-chain/task.yaml, tests/main/install-sideload/task.yaml, tests/main/snap-run-hook/task.yaml, tests/main/writable-areas/task.yaml
On arch, snap-confine's security tag will be prefixed with /var/lib/snapd. This change accounts for that, allowing us to use SNAP_REEXEC on arch systems.
Additionally, the fix in interfaces allows us to account for where snaps are installed on non-ubuntu systems.
=> c/libsnap-confine-private, interfaces: account for reexec on arch

overlord/ifacestate/export_test.go, overlord/ifacestate/handlers.go, overlord/snapstate/backend_test.go, overlord/snapstate/booted_test.go, overlord/snapstate/component_remove_test.go, overlord/snapstate/handlers.go, overlord/snapstate/handlers_components.go, overlord/snapstate/handlers_link_test.go, overlord/snapstate/snapstate.go, overlord/snapstate/snapstate_install_test.go, overlord/snapstate/snapstate_test.go, overlord/snapstate/snapstate_update_test.go, tests/nested/manual/kernel-modules-components/task.yaml
Delay reboot when we are installing/updating/removing kernel-modules
components jointly with a kernel refresh so it happens after the
refresh hooks have run. With this we ensure that the kernel modules
shipped in the component or built from the hooks is available at the
same time as the other modules after rebooting.
=> o/{ifacestate,snapstate}: delay reboot when we have kernel-modules

overlord/assertstate/assertmgr.go, overlord/assertstate/assertstate_test.go, overlord/snapstate/component.go, overlord/snapstate/component_install_test.go, overlord/snapstate/snapstate_install_test.go, overlord/snapstate/snapstate_test.go, overlord/snapstate/snapstate_update_test.go, overlord/snapstate/target_test.go
Since we might need to fetch new assertions when installing a component alongside an arbitrary snap revision, we should always run this task when installing a component from the store.
Even if the snap doesn't get downloaded from the store because it was installed alongside a previous snap revision, we still need to fetch the new assertions and make sure that it can be installed with the new snap revision.
=> o/snapstate, o/assertstate: always run validate-component when installing components from the store

overlord/snapstate/snapstate_install_test.go, overlord/snapstate/snapstate_update_test.go, run-checks
Due to the ordering of some merges, TestUpdateWithComponentsRunThroughShareComponents were both not compiling and incorrect. This fixes those issues.
=> o/snapstate: fix TestUpdateWithComponentsRunThroughShareComponents tests now that reboot changes are merged

tests/main/snap-userd-reexec/task.yaml, tests/main/snapd-reexec/task.yaml
Those tests are failing when we ran it for SRU validation, I used tests.exec to make sure prepare, execute and restore phases are properly skipped.
=> tests: fix reexec tests when SNAP_REEXEC=0

image/preseed/preseed_test.go, overlord/devicestate/devicestate_install_mode_test.go, overlord/install/install_test.go, seed/seed.go, seed/seed16.go, seed/seed16_test.go, seed/seed20.go, seed/seed20_test.go
The new method returns snap if applicable to mode, and returns only the components that can be used in said mode.
=> many: add method to seed to retrieve mode snap and components

overlord/configstate/configcore/corecfg_test.go, overlord/configstate/configcore/ctrlaltdel_test.go, overlord/configstate/configcore/services.go, overlord/configstate/configcore/services_test.go
On ubuntu 22.10+ sshd uses socket activation and that means we must reload SSH differently for the socket unit.
This should fix the nested test tests/nested/manual/core20-early-config
REF: SNAPDENG-34249
=> o/configstate/configcore: support SSH socket activation configurations

tests/main/cgroup-tracking-failure/task.yaml
Simple fix for test cgroup-tracking-failure
=> tests: fix cgroup-tracking-failure in ubuntu 25.04

overlord/fdestate/backend/reseal.go, overlord/fdestate/backend/reseal_test.go, overlord/fdestate/export_test.go, overlord/fdestate/fdemgr.go, overlord/fdestate/fdemgr_test.go, overlord/fdestate/fdestate.go
Instead of splitting completely FDE hook and TPM resealing, we split the calculation of role parameters, udpate the state, then do     the resealing based on that state.
This depends on https://github.com/canonical/snapd/pull/14305
=> overlord/fdestate/backend/reseal.go: factor FDE hook and TPM resealing

tests/lib/pkgdb.sh, tests/lib/prepare-restore.sh
Aamazon Linux 2023 uses versioned releases. Make sure we are always working with the latest release.
=> tests: upgrade Amazon Linux 2023 to the latest release during prepare

spread.yaml, tests/lib/nested.sh, tests/nested/core/core-revert/task.yaml, tests/nested/core/core20-fault-inject-on-install/task.yaml
Failures were noticed in snapd-update-services. It attempts to access the snapd.snap built during the prepare phase. If, before that test executes, another test triggers a reboot, the working directory gets removed and the test cannot find snapd.snap. This changes the working directory to `/var/tmp` to ensure the working files stick around.
=> tests: don't use tmp directory for prepare files

interfaces/prompting/patterns/patterns_test.go, interfaces/prompting/patterns/scan.go, interfaces/prompting/patterns/scan_internal_test.go
Since patterns like /foo/./bar don't match paths paths like /foo/bar, throw an error if the client tries to reply or create a rule with such a construction clearly in the pattern. That is, if the pattern contains `/./` or `/../`, or if it ends with `/.` or `/..`.
Notably, we do this on the raw pattern string, similarly to how we validate that the pattern begins with a `/`: we don't consider whether all alts in a leading group happen to start with `/`, we simply throw an error if the first character is not `/`.
In this case, we take a more lenient (but similarly lazy) approach: if there's a literal `/./` or `/../`, or trailing `/.` or `/..`, then an error is thrown. As long as there's something interrupting the `/` or end of the pattern string (e.g. a group), we consider that fine. For …
=> i/p/patterns: disallow /./ and /../ in path patterns

.github/workflows/test.yaml, tests/lib/spread/rules/fips.yaml
Use a separate rules file for matching the FIPS test suite tests.
Related: [SNAPDENG-34289](https://warthogs.atlassian.net/browse/SNAPDENG-34289)
[SNAPDENG-34289]: https://warthogs.atlassian.net/browse/SNAPDENG-34289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> github, tests: use separate spread rules for FIPS test suite

tests/lib/pkgdb.sh
Some tests like auto-refresh-backoff fail in xenial. The issue is related to the following problem:
kernel reports TIME_ERROR: 0x41: Clock Unsynchronized
Other ubuntu varions have chrony installed, so this changes ensures chrony is installed in xenial too.
=> tests: fix time synchronization issues is ubuntu xenial

tests/lib/pkgdb.sh
Fix  google:ubuntu-25.04-64:tests/unit/c-unit-tests-{clang,gcc} by installing package systemd-dev (provides /usr/share/pkgconfig/udev.pc) to resolve pkg-config dependency "udev".
**Failure looks like:**
___
checking for libapparmor... yes
checking for libudev... yes
checking for udev... no
configure: error: Package requirements (udev) were not met:
Package 'udev', required by 'virtual:world', not found
Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
Alternatively, you may set the environment variables UDEV_CFLAGS
and UDEV_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
___
=> tests: added dependency system-dev for ubuntu24.10+

tests/main/auto-refresh-backoff/task.yaml
Make sure that the tests generates a configure hook which is 'bad' in a proper way.
=> tests/main/auto-refresh-backoff: generate properly 'bad' configure hook

overlord/fdestate/export_test.go, overlord/fdestate/extop.go, overlord/fdestate/extop_test.go, overlord/fdestate/fdestate.go
Add a helper type for capturing externally running operations
Cherry picked from https://github.com/canonical/snapd/pull/14615
Related: [SNAPDENG-32509](https://warthogs.atlassian.net/browse/SNAPDENG-32509)
[SNAPDENG-32509]: https://warthogs.atlassian.net/browse/SNAPDENG-32509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> overlord/fdestate: add helper type for capturing externally running operations

tests/main/snapd-snap/task.yaml
This test is currently failing because we use the deb from the repository which is 2.66.1+2x.04 and the snap version is 2.66.1. This produces that the re-execution is not done and the check for re-exec fails.
Also I removed code for systems which are not supported anymore in that test.
=> tests: fix snapd-snap test 

asserts/snapasserts/validation_sets.go, asserts/snapasserts/validation_sets_test.go, daemon/api_snaps.go, daemon/api_snaps_test.go, daemon/export_test.go, overlord/devicestate/devicestate.go, overlord/hookstate/ctlcmd/export_test.go, overlord/hookstate/ctlcmd/helpers.go, overlord/hookstate/ctlcmd/snap_management_test.go, overlord/snapstate/component.go, overlord/snapstate/component_install_test.go, overlord/snapstate/handlers.go, overlord/snapstate/handlers_download_test.go, overlord/snapstate/snapstate.go, overlord/snapstate/snapstate_install_test.go, overlord/snapstate/snapstate_update_test.go, overlord/snapstate/storehelpers.go, overlord/snapstate/target.go
Using a `snapasserts.ValidationSets` rather than a slice of `snapasserts.ValidationSetKey` makes many operations more convenient.
This will help enable verifying that component revisions are correct inside of snapstate. Additionally, it alleviates the need of providing a revision in `snapstate.RevisionOpts` when installing with a specific set of validation sets.
=> many: make snapstate.RevisionOpts carry snapasserts.ValidationSets

timeutil/human.go
Stumbled upon this while looking for
This has been added in snapd back in the day here:
* https://github.com/canonical/snapd/pull/4775
Move conditionals to the correct case where they belong (e.g. >= -cutoffDays belongs to the "%d days ago", ...), and then just naturally move the non-special case of then.Format("2006-01-02") to the default case.
Looking at compiler explorer, it seems like Go (gc 1.21 on x86_64) can optimize out the old version's panic(), so it's just dead code in the source (as it should be): https://godbolt.org/z/fxqTzYfPv
---
Related proposed downstream Pebble patch: https://github.com/canonical/pebble/pull/455
=> fix(timeutil): remove unreachable panic() call

interfaces/apparmor/template.go
The Snapcraft documentation on [system usernames](https://snapcraft.io/docs/system-usernames#dropping-privileges) states that snap developers can use `setpriv` to drop privileges and run a snapped daemon as a non-root user, such as `_daemon_`.
Whilst `setpriv` is present in the core20/core22/core24 base snaps, it isn't possible to run the base snap's copy within the environment of a strictly confined snap. (The documentation doesn't refer to this particular issue, but it does suggest that developers add the `util-linux` package to the daemon snap.) This PR seeks to overcome this issue by adding `/usr/bin/setpriv` to the AppArmor template.
If there are any reasons against doing this - particularly if there is a better way to run a snapped daemon as a non-root user (or if there *will* be a …
=> interfaces/apparmor/template: add setpriv to the base template

tests/lib/nested.sh, tests/nested/manual/uc-update-assets-secure/task.yaml
Backport of https://github.com/canonical/snapd/pull/14252 from fde manager branch.
Plus a fix for uc24 to re-sign the fallback binary correctly.
=> t/n/m/uc-update-assets-secure: sign new grub also with old key [backport]

interfaces/builtin/locale_control.go
In Core Desktop, like in Classic, locale-control is required to be implicit. This complements the already merged PR https://github.com/snapcore/snapd/pull/13027
=> i/builtin: make locale-control interface implicit on Core Desktop

daemon/api_prompting.go, daemon/api_prompting_test.go, interfaces/prompting/requestprompts/export_test.go, interfaces/prompting/requestprompts/requestprompts.go, interfaces/prompting/requestprompts/requestprompts_test.go, overlord/ifacestate/apparmorprompting/prompting.go, overlord/ifacestate/apparmorprompting/prompting_test.go
This PR now depends on https://github.com/canonical/snapd/pull/14672, which introduces mockable timers used in tests.
When there has been no retrieval of prompt details for a given user after a particular duration, expire all outstanding prompts for that user, as this suggests that there is no prompt client running for that user.
If a user retrieves prompt details or interacts with prompts in some way, such as by retrieving all prompts, a prompt by ID, or attempting to reply to a prompt, bump the timeout to a much longer timeout, since this indicates that a prompt client is running for that user.
This is tracked internally by https://warthogs.atlassian.net/browse/SNAPDENG-28665
=> i/p/requestprompts: add timeout for prompts

overlord/snapstate/component.go, overlord/snapstate/component_install_test.go, overlord/snapstate/snapstate.go, overlord/snapstate/snapstate_install_test.go, overlord/snapstate/snapstate_update_test.go
This change makes it so when installing (or refreshing) a snap and its components, we do all the downloads back-to-back. This will help make the code changes needed for remodeling simpler.
Example of the tasks created when installing a snap and two components from the store:
```
task prerequisites (1), Ensure prerequisites for "test-snap" are available
waiting on:
task download-snap (2), Download snap "test-snap" (11) from channel "channel-for-components"
waiting on:
- prerequisites (1)
task validate-snap (13), Fetch and check assertions for snap "test-snap" (11)
waiting on:
- download-snap (2)
task download-component (3), Download component "kernel-modules-component" (1)
waiting on:
- validate-snap (13)
task validate-component (4), Fetch and check assertions for component …
```
=> o/snapstate: reorder tasks such that snap and component downloads now happen consecutively

cmd/snap-bootstrap/cmd_initramfs_mounts.go, cmd/snap-bootstrap/cmd_initramfs_mounts_cvm.go, cmd/snap-bootstrap/cmd_initramfs_mounts_cvm_test.go, cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
As requested in https://github.com/canonical/snapd/pull/14713#pullrequestreview-2473080901
=> c/snap-bootstrap: split CVM related functionality in separate files

.github/workflows/test.yaml, tests/lib/spread/backend.openstack.yaml, tests/main/interfaces-kernel-module-control/task.yaml, tests/unit/go/task.yaml
This change moves the non-required debian system to openstack
=> tests: move debian-12 and sid to openstack

.github/dependabot.yaml
When merged to master, dependabot will check for updates in go dependencies and github actions weekly. When it finds an out-of-date package, it will automatically open a pull request. Here's an example of the pull requests opened on my fork of snapd when I pushed this yaml file to master: https://github.com/maykathm/snapd/pulls
=> tests: added dependabot for updating dependencies

boot/makebootable.go, boot/makebootable_test.go, cmd/snap-bootstrap/cmd_initramfs_mounts.go, gadget/install/content.go, gadget/install/content_test.go, gadget/install/kernel.go, overlord/devicestate/devicemgr.go, overlord/devicestate/devicestate_install_api_test.go, overlord/devicestate/devicestate_install_mode_test.go, overlord/devicestate/handlers_install.go, seed/seedtest/sample.go, tests/lib/nested.sh, tests/lib/tools/build_kernel_with_comps.sh, tests/lib/tools/setup_nested_hybrid_system.sh, tests/nested/manual/build-with-kernel-modules-components/task.yaml, tests/nested/manual/kernel-modules-components/task.yaml, tests/nested/manual/muinstaller-real/task.yaml
Make sure that module shipped in kernel-modules components are available on first boot after auto-install. This does not consider yet installation using the snapd API.
=> many: make kernel-modules components available on first boot

spread.yaml
The jq snap should no longer be required after being replaced with gojq
=> tests: remove jq from PRE_CACHE_SNAPS to install

.github/dependabot.yaml
Have dependabot open only one PR for all github action updates.
=> tests: create one PR for all github action dependabot updates

cmd/snap-bootstrap/cmd_initramfs_mounts.go, cmd/snap-bootstrap/cmd_initramfs_mounts_cvm.go, cmd/snap-bootstrap/cmd_initramfs_mounts_test.go, gadget/install/install.go, gadget/install/install_test.go, tests/core/basic20plus/task.yaml
Make ubuntu-seed mounted as no-{suid,exec,dev} as those mount permissions are strictly not required after booting. Important to note in this PR that I've not touched mount flags for ubuntu-seed in the CVM case.
REF: SNAPDENG-34221
=> cmd/s-b,g/install: mount ubuntu-seed as no{suid,exec,dev}

.github/workflows/nightly-spread.yaml, .github/workflows/spread-tests.yaml, tests/lib/spread/rules/nightly.yaml
This PR migrates all cron jobs from [spread-cron](https://github.com/canonical/spread-cron) to snapd that run spread tests on snapd. It makes a minor change in the spread-test.yaml to allow for use of the master snap along with two required environment variables.
It also adds the possibility of executing with (in addition to manually specifying the systems) "ALL" systems or "NONE." To help not create confusion, it will no longer be possible to leave the systems input blank.
To ensure the commands will run correctly, [I ran a job in snapd-ci with cron disabled to check the executed spread commands](https://github.com/snapcore/snapd-ci/actions/runs/11852303165). To ensure the scheduling mechanism works correctly, I pushed the changes to the master branch of snapd-ci and saw the three …
=> tests: added nightly run from spread-cron

interfaces/builtin/checkbox_support.go, interfaces/builtin/checkbox_support_test.go, interfaces/policy/basedeclaration_test.go, tests/lib/snaps/test-snapd-policy-app-consumer/meta/snap.yaml
The checkbox-support interface is a privileged interface designed for the Canonical checkbox test and certification system. The system is able to run a wide collection of system tests and is thus allowed to execute any command mostly bypassing the sandbox.
The interface is allowed to run on both core and classic systems, so that certification can use the same snap across the entire range of devices.
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-34252
=> i/builtin: add the checkbox-support interface

tests/main/document-interfaces-url/task.yaml
A couple of improvements to the document-interfaces-url test:
* 59ed590b7ccca3f1151d4fa2f8f921a5fc84f796 adds a delay before retrying if we get a 429 (seen here: https://github.com/canonical/snapd/actions/runs/12232010759/job/34116725765?pr=14705). The server doesn't return a Retry-After so I just chose a fixed delay
* 21b600b544279c4163d4a4acf0831f65b075df63 changes the curl command to do a HEAD request instead of a GET to avoid downloading 100Kb of HTML each time
* b51c35e14fc48d3fe44b1f6c324ca9b59082ba17 removes some of the exclusions which we no longer need since the docs urls have been fixed in the mapping
=> tests: fixes and improvements to the document-interfaces-url test

.woke.yaml, interfaces/builtin/export_test.go, interfaces/builtin/mount_control.go, interfaces/builtin/mount_control_test.go, osutil/mount/libmount/libmount.go, osutil/mount/libmount/libmount_darwin.go, osutil/mount/libmount/libmount_linux.go, osutil/mount/libmount/libmount_linux_test.go
We need to recognize and validate libmount-style mount options, such as those that one can use with the mount(1) utility on command line for possible conflicts.  This is so that the apparmor parser, which does similar validation, does not fail "late" in the interface setup process, when given incorrect data by the mount-control interface.
This patch adds the skeleton of the validator, along with read-only and read-write mount options.
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-32984
NOTE: this is a draft, I need to hook it up to interfaces logic as well.
I have considered asking apparmor for this information but given that we cannot even discover the full set of known mount options and the interrogation is inefficient (compile and see if it gets ignored), I chose to just bake in …
=> osutil: add mount/libmount package with option validator

.github/workflows/spread-tests.yaml
Fixes issue where if a spread task excludes a system and that task is run by itself in the CI, then the `spread -list <backend>:<system-that-excludes-task>:<task>` command will error.
=> tests: ignore error in provider filter

tests/main/apparmor-prompting-integration-tests/task.yaml
disable memory limit for app armor integration tests since they regularly exceed the 200MB limit
=> tests: set no-memory-limit for app armor tests

overlord/assertstate/assertmgr.go, overlord/devicestate/devicestate.go, overlord/devicestate/devicestate_systems_test.go, overlord/devicestate/export_test.go, overlord/devicestate/systems.go, overlord/managers_test.go, overlord/snapstate/handlers.go, overlord/snapstate/handlers_components.go, overlord/snapstate/handlers_components_download_test.go, overlord/snapstate/snapmgr.go, overlord/snapstate/snapstate.go, overlord/snapstate/snapstate_test.go, overlord/snapstate/storehelpers.go, overlord/snapstate/target.go
This will enable us to download arbitrary components for the purpose of creating a recovery system. Follow-up PR will move where we download the blobs to from the global blob dir, to somewhere under `/var/cache/snapd`.
=> o/snapstate, overlord, o/devicestate: support downloading components in snapstate.Download

overlord/snapstate/component.go, overlord/snapstate/snapstate.go, overlord/snapstate/snapstate_test.go
This change allows us to install/update components when resolving a validation set.
=> o/snapstate: install/update component when resolving validation sets

overlord/ifacestate/ifacemgr.go, overlord/ifacestate/ifacestate_test.go
If an error occurs during interfaces requests manager initialization, record a warning containing the error and indicating that prompting will remain inactive until snapd is restarted.
Even when an error occurs, the `"apparmor-prompting"` feature flag is left enabled, as the user deliberately turned this flag on, and we don't want to change feature flags without user interaction.
This work is tracked internally by: https://warthogs.atlassian.net/browse/SNAPDENG-32064
=> o/ifacestate: record warning if prompting errors during startup

tests/main/command-chain/task.yaml, tests/main/install-errors/task.yaml, tests/main/install-sideload-epochs/task.yaml, tests/main/install-sideload/task.yaml, tests/main/snap-run-hook/task.yaml, tests/main/snapd-homedirs-vendored/task.yaml, tests/main/writable-areas/task.yaml
The test is not applicable when re-exec is not enabled. Also improved multiple copies of the same "No needed" message.
This issue was discovered while testing with as part of snapd deb validation for Bionic:
SPREAD_SNAPD_DEB_FROM_REPO=false SPREAD_MODIFY_CORE_SNAP_FOR_REEXEC=0 SPREAD_TRUST_TEST_KEYS=false SPREAD_SNAP_REEXEC=0 SPREAD_CORE_CHANNEL=stable spread -no-debug-output google:ubuntu-18.04-64:tests/main/snapd-homedirs-vendored.
It was confirmed relevant on master as well, if SPREAD_SNAP_REEXEC=0 as above.
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-34179
=> tests/main/snapd-homedirs-vendored: skip when reexec is disabled

seed/seedwriter/seed20.go, seed/seedwriter/writer_test.go
This tries to address the discussion that happened in #14071
=> seed/seedwriter: more precise error message when overriding channels with grade > dangerous

overlord/devicestate/firstboot20_test.go, overlord/devicestate/firstboot_test.go, overlord/ifacestate/handlers.go, overlord/snapstate/handlers.go, overlord/snapstate/handlers_link_test.go, overlord/snapstate/snapstate.go, tests/core/snapd-refresh-undo/task.yaml, wrappers/core18.go, wrappers/core18_test.go, wrappers/services_test.go
When doing a snapd upgrade (specifically from pre snapd-snap to snapd-snap) either as transactional or as a part of a validation-set/remodel refresh, and a snap fails to update after snapd has succesfully upgraded, it seems the 'undo' path of snapd ends up causing an issue with how we utilize internal tools from the snapd snap.
After 'link-snap' undo's for the snapd, we technically should not be running as the new snapd, and we do actually do a 'LinkSnap' operation in undo because a snapd snap must always be available, and the task does request a restart of snapd to switch to the older snapd. However, the task prior to 'link-snap', which is 'setup-profiles', does not wait for this restart request and instead continues to try to load apparmor_parser from the new snap. This fails.
Make undo …
=> overlord: wait for snapd restart after requesting by undo of 'link-snap'

spread.yaml, tests/main/listing/task.yaml
Correct and cleanup regex used to identify core & snapd `snap list` information.
This issue was discovered while testing with as part of snapd deb validation for Bionic:
`SPREAD_SNAPD_DEB_FROM_REPO=false SPREAD_MODIFY_CORE_SNAP_FOR_REEXEC=0 SPREAD_TRUST_TEST_KEYS=false SPREAD_SNAP_REEXEC=0 SPREAD_CORE_CHANNEL=stable spread -no-debug-output google:ubuntu-18.04-64:tests/main/listing`.
It was confirmed relevant on master as well, if `SPREAD_CORE_CHANNEL=stable` as above. It does not typically show up because `SPREAD_CORE_CHANNEL=edge` by default
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-34179
=> tests/main/listing: correct and clean up core and snapd version regex

tests/lib/prepare-restore.sh, tests/lib/prepare.sh
Occasionally, the mount order regression test would get the oom-killer called due to an imposed memory limit. That memory limit was incorrect applied due to the prepare_memory_limit_override not being called in the prepare-each.
=> tests: prepare memory limit before each test

daemon/api_prompting.go, daemon/api_prompting_test.go, interfaces/prompting/constraints.go, interfaces/prompting/constraints_test.go, interfaces/prompting/errors/errors.go, interfaces/prompting/errors/errors_test.go, interfaces/prompting/export_test.go, interfaces/prompting/prompting.go, interfaces/prompting/prompting_test.go, interfaces/prompting/requestprompts/requestprompts.go, interfaces/prompting/requestprompts/requestprompts_test.go, interfaces/prompting/requestrules/export_test.go, interfaces/prompting/requestrules/requestrules.go, interfaces/prompting/requestrules/requestrules_test.go, overlord/ifacestate/apparmorprompting/prompting.go, overlord/ifacestate/apparmorprompting/prompting_test.go, strutil/joinerrors.go, strutil/joinerrors_test.go, tests/main/apparmor-prompting-snapd-startup/task.yaml, tests/main/interfaces-snap-interfaces-requests-control/task.yaml
This PR is based on #14538, and is tracked internally by https://warthogs.atlassian.net/browse/SNAPDENG-32594. It addresses some of the problems discussed in that PR (such as https://github.com/canonical/snapd/pull/14538#issuecomment-2383774515), and more broadly in https://github.com/canonical/desktop-security-center/issues/74. CC @sminez @juanruitina.
Let rule content constraints have heterogeneous outcomes and lifespans for different permissions in the constraints. As such, convert the list of permissions to a map from permission to permission entry, where the entry holds the outcome, lifespan, and duration/expiration for that particular permission, where previous those were global to the containing rule, rule contents, or patch contents.
However, the existing concept of replying …
=> many: support mixed outcomes for permissions in prompting constraints

tests/lib/fakestore/store/store.go, tests/lib/fakestore/store/store_test.go, tests/lib/tools/store-state
Cherry-pick of eb2a9560e989335f9d5cb5b010b0b330886155e8 from https://github.com/canonical/snapd/pull/14305 in `fde-manager-features` branch.
=> tests/lib/fakestore: add support for tracking channels

tests/main/aux-info/task.yaml
The oom-killer gets somewhat regularly called during the snap-store setup. This disables the memory limit.
=> tests: disable memory limit for aux-info

interfaces/prompting/requestprompts/export_test.go, interfaces/prompting/requestprompts/requestprompts.go, interfaces/prompting/requestprompts/requestprompts_test.go, overlord/ifacestate/apparmorprompting/prompting.go, overlord/ifacestate/apparmorprompting/prompting_test.go
Rename `remainingPermissions` to `outstandingPermissions` and clarify their purpose and behavior in request prompts.
This work is tracked internally by https://warthogs.atlassian.net/browse/SNAPDENG-30515
=> many: rename `remainingPermissions` to `outstandingPermissions`

wrappers/desktop.go, wrappers/desktop_test.go
Logs were cryptic when snapd found malformed desktop files, this PR improves the logs and make them actually usable.
```
Nov 25 15:21:35 snapd[31935]: desktop.go:308: cannot read instance name: %!s(<nil>)
Nov 25 15:21:35 snapd[31935]: desktop.go:308: cannot read instance name: %!s(<nil>)
Nov 25 15:21:35 snapd[31935]: desktop.go:308: cannot read instance name: %!s(<nil>)
```
=> wrappers/desktop: add more context to logs for malformed desktop files

interfaces/builtin/cpu_control.go
* The contents available on `/sys/kernel/irq/<IRQnum>` are the same as those available on `/proc/interrupts` the difference is that on the `sysfs` directory they are present in a more machine-readable form.
On this directory, usually it's found:
- `actions`: Which is the string name of the IRQ, found on the last column of `/proc/interrupts`;
- `chip_name`: Found The first column right after the CPUs columns;
- `hwirq`: The IRQ number itself;
- `name`: A string that usually represents the `type` of IRQ;
- `per_cpu_count`: This is the data for all CPUs columns of `/proc/interrupts`;
- `type`: Differentiates between an IO-APIC-edge and IO-APIC-fasteoi interrupt handling modes. Found on the last but one column of `/proc/interrupts`;
- `wakeup`: Informs if the given IRQ is capable of waking …
=> interfaces/builtin/cpu-control: Add read access to /sys/kernel/irq/<IRQ>

daemon/api_sideload_n_try_test.go, snap/snaptest/snaptest.go, tests/lib/fakestore/cmd/fakestore/cmd_new_snap_decl.go, tests/lib/fakestore/cmd/fakestore/cmd_new_snap_resource_pair.go, tests/lib/fakestore/cmd/fakestore/cmd_new_snap_resource_revision.go, tests/lib/fakestore/cmd/fakestore/cmd_new_snap_rev.go, tests/lib/fakestore/refresh/snap_asserts.go, tests/lib/fakestore/store/store.go, tests/lib/fakestore/store/store_test.go, tests/lib/tools/store-state
This will let us test things with the fake store that use components.
=> t/l/f/store: make the fake store aware of components

interfaces/prompting/requestrules/export_test.go, interfaces/prompting/requestrules/requestrules.go, interfaces/prompting/requestrules/requestrules_test.go, overlord/ifacestate/apparmorprompting/prompting.go
This PR builds on #14865, only the final commit is relevant to this PR.
Move the logic which iterates through requested permissions into the requestrules package, instead of the o/i/apparmorprompting package. 
This work is tracked internally by https://warthogs.atlassian.net/browse/SNAPDENG-31370
=> i/p/requestrules,o/i/apparmorprompting: move request matching logic into requestrules

core-initrd/build-source-pkgs.sh, spread.yaml, tests/lib/core-initrd.sh, tests/lib/prepare.sh
Build and install the ubuntu-core-initramfs package from snapd repo
sources, and use it to build the initramfs on UC24+.
=> many: build and use ubuntu-core-initramfs package in spread tests

interfaces/seccomp/template.go
Add epoll_pwait2 in the base template. The syscall has been available since 5.11 (early 2021).
Reported in the forum: https://forum.snapcraft.io/t/epoll-works-on-core20-but-fails-on-core22/44347
Some context: https://kernelnewbies.org/Linux_5.11#Add_epoll_pwait2.282.29_syscall_for_higher_resolution_waits
=> interfaces/seccomp/template: allow epoll_pwait2 in the base template

tests/core/snapd-refresh-vs-services-reboots/task.yaml, tests/core/snapd-refresh-vs-services/task.yaml, tests/lib/tools/simpleget, tests/main/default-tracks/task.yaml, tests/nested/manual/cloud-init-never-used-not-vuln/task.yaml, tests/nested/manual/cloud-init-nocloud-not-vuln/task.yaml
Add support for setting request headers to simpleget and replace uses of test-snapd-curl with simpleget in an attempt to reduce the number of external dependencies installed by the tests.
Related: [SNAPDENG-34225](https://warthogs.atlassian.net/browse/SNAPDENG-34225)
[SNAPDENG-34225]: https://warthogs.atlassian.net/browse/SNAPDENG-34225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> tests, simpleget: replace use of test-snapd-curl with simpleget where possible, support request headers

tests/lib/prepare.sh
The error message talks about snapd snap.
=> tests: fix typo: snapd vs snap

osutil/group.go, osutil/group_test.go, osutil/user.go, osutil/user/export_test.go, osutil/user/getent.go, osutil/user/getent_test.go, osutil/user_test.go
It is possible that `snap run` may be called with a PATH set such that it does not include a directory containing getent. To workaround this, try to look up getent in a number of known locations on the host.
Fixes: https://bugs.launchpad.net/snapd/+bug/2090938
Ernest: this is the original scenario where the issue was first detected: https://github.com/canonical/operator-workflows/issues/496
=> osutil/user: look up getent executable in known host directories

tests/main/upgrade-from-release/task.yaml
Provide workaround for older snapd debs that fail to run `test-snapd-tools.echo hello` with re-exec disabled.
This issue was discovered while testing with as part of snapd deb validation for Bionic:
SPREAD_SNAPD_DEB_FROM_REPO=false SPREAD_MODIFY_CORE_SNAP_FOR_REEXEC=0 SPREAD_TRUST_TEST_KEYS=false SPREAD_SNAP_REEXEC=0 SPREAD_CORE_CHANNEL=stable spread -no-debug-output google:ubuntu-18.04-64:tests/main/proxy-no-core.
It was confirmed relevant on master as well, if SPREAD_SNAP_REEXEC=0 as above.
The specific snapd deb on Bionic to easily reproduce the failure:  2.32.5+18.04
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-34179
=> tests/main/upgrade-from-release: workaround for older snapd deb version

overlord/configstate/configcore/prompting.go, overlord/ifacestate/export_test.go, overlord/ifacestate/ifacemgr.go, overlord/ifacestate/ifacestate.go, overlord/ifacestate/ifacestate_test.go
During snapd startup, if the "apparmor-prompting" flag is enabled but there is no snap with an interfaces-requests-control connection and an app app declared as a "handler-service", then record a warning that prompts will be auto-denied until a prompting client is installed.
Such a situation could arise if the user uninstalled the prompting client snap without disabling the "apparmor-prompting" feature flag, or if they disconnected the plug for the interfaces-requests-control interface.
There is a check for the presence of a handler-service client when one attempts to enable the "apparmor-prompting" feature flag in the first place: when enabling the flag, if there is no handler-service app present, or it cannot be successfully started, then the flag is left disabled. Before this commit, …
=> o/c/configcore,o/ifacestate: check for presence of handler-service on startup

tests/lib/spread/rules/main.yaml
This maps anything under `tests/nested` to nothing. With this change, in future PRs, if the PR's only change is a nested test, the non-nested systems will not run any tests.
Here's the change to the main.yaml rule file in action:
```
$ python3 tests/lib/external/snapd-testing-tools/utils/spread-filter -r tests/lib/spread/rules/main.yaml -p google::ubuntu-24.04-64 -c tests/nested/manual/some-test/task.yaml
$
```
=> tests: change main rule so that changes in nested tests won't run main

asserts/account_key.go, asserts/asserts.go, asserts/confdb.go, asserts/confdb_test.go, asserts/database.go, asserts/database_test.go, overlord/devicestate/devicemgr.go, overlord/devicestate/devicestate_test.go
The process to update a `confdb-control` assertion (see SD172 & SD186) looks like this:
1. Call `/v2/confdbs` with an action like `delegate` or `revoke`
2. The assertion is updated as required
3. The assertion is signed with the device key
4. The new revision of the assertion is acknowledged
This PR adds a method to `devicestate.DeviceManager` that can be used to sign `confdb-control` assertions.
Its usage would (roughly) look like:
`daemon/api_confdbs`:
```go
func doDelegateOrRevoke(c *Command, r *http.Request, _ *auth.UserState) Response {
// request validation
[...]
// the existing assertion is updated
[...]
groups = existingAs.Groups()
revision = existingAs.Revision() + 1
// lock device state
state := c.d.overlord.State()
state.Lock()
defer state.Unlock()
// sign the assertion …
```
=> o/devicestate,asserts: sign confdb-control assertions with the device key

tests/lib/prepare-restore.sh
The auto-refresh tests and the degraded test were failing due to conflicts between chrony.service and ntp.service. The former happened because chrony sometimes failed to run and the latter because ntp.service conflicted with chrony and the unit would be marked as failed. Removing ntp and leaving chrony fixes both issues.
If merged this replaces https://github.com/canonical/snapd/pull/14888
Fixes:
```
- google:ubuntu-16.04-64:tests/main/auto-refresh-backoff
- google:ubuntu-16.04-64:tests/main/auto-refresh-gating-from-snap
- google:ubuntu-16.04-64:tests/main/auto-refresh-pre-download:close
- google:ubuntu-16.04-64:tests/main/auto-refresh-pre-download:close_mid_restart
- google:ubuntu-16.04-64:tests/main/auto-refresh-pre-download:ignore
- google:ubuntu-16.04-64:tests/main/auto-refresh-retry …
```
=> tests: remove NTP service on Xenial

.github/workflows/test.yaml, spread.yaml, tests/lib/spread/backend.openstack.yaml, tests/main/interfaces-calendar-service/task.yaml, tests/main/interfaces-contacts-service/task.yaml, tests/main/interfaces-packagekit-control/task.yaml
OpenSUSE 15.5 is EOL now. Let's drop it from the CI.
Related: [SNAPDENG-34181](https://warthogs.atlassian.net/browse/SNAPDENG-34181)
[SNAPDENG-34181]: https://warthogs.atlassian.net/browse/SNAPDENG-34181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> spread, tests: drop openSUSE 15.5 (EOL)

daemon/api.go, daemon/api_find.go, daemon/api_find_test.go, daemon/export_test.go, overlord/assertstate/assertstate.go, overlord/assertstate/assertstate_test.go
`snap refresh --list` didn't report snaps that would be refreshed with a `snap refresh` because it, unlike the actual refresh, didn't refresh the validation sets which could make new snap revisions available. This change fetches new validation sets (without tracking them) before checking for refreshable snaps
=> daemon: fetch validation sets before checking refresh candidates

tests/core/uboot-unpacked-assets/task.yaml, tests/core/update-snapd-symlink/task.yaml, tests/lib/spread/backend.testflinger.beta.yaml, tests/lib/spread/backend.testflinger.edge.yaml, tests/main/listing/task.yaml
This change fixes 3 tests for beta validation:
. update-snapd-symlink: in this test the snapd.failure.service remains a bit activating and needs a retry to make sure it becomes inactive. . listing: needs support for testflinger backend
. uboot-unpacked-assets: support that uc24 does not use uboot.
Also it adds support for rpi5 in edge and beta validation
=> tests: fix tests for beta validation

interfaces/apparmor/backend.go, interfaces/apparmor/backend_test.go, interfaces/apparmor/template.go, interfaces/backend.go, overlord/ifacestate/export_test.go, overlord/ifacestate/handlers.go, overlord/ifacestate/handlers_test.go, overlord/ifacestate/helpers.go, overlord/ifacestate/ifacestate_test.go
In UC24+ the kernel modules and firmware is accessed from symlinks in
/lib/{modules,firmware} that can point to different locations. Make
sure that the files can be read by any snap, as there are actions that
can trigger the automatic loading of modules or firmware from the
kernel. This is also needed so the kernel-modules-control can actually
work as expected.
=> interfaces,overlord: allow access to kernel snap in profiles

.github/workflows/spread-results-reporter.yaml, .github/workflows/spread-tests.yaml, .github/workflows/test.yaml
This adds a new workflow that runs every time the "Tests" workflow runs. It will read the spread.json files (if any) produced during the Tests workflow and collect that data into a single report that it will then comment on the PR. This had to be a separate workflow due to insufficient permissions for PRs from forked versions of the repo.
It is currently in operation on the snapcore/snapd-ci fork and [commented failures on the demo PR](https://github.com/snapcore/snapd-ci/pull/4). Note that it correctly updates an already existing comment instead of creating a new one.
[The workflow does not run when the causal "Tests" workflow run is not a PR](https://github.com/snapcore/snapd-ci/actions/runs/12068091933)
=> tests: create/update PR with failed spread tests

build-aux/snap/snapcraft.yaml
Patching with patchelf 0.14.3 available in 22.04 produces the result binaries get silently broken and break parsing with python-elfutils.
Inspectign a patched binary with readelf also shows a warning like so:
snapcraft-snapd-on-amd64-for-amd64-1579591 ../project# readelf -h snapd.orig
ELF Header:
Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
Class:                             ELF64
Data:                              2's complement, little endian
Version:                           1 (current)
OS/ABI:                            UNIX - System V
ABI Version:                       0
Type:                              DYN (Position-Independent Executable file)
Machine:                           Advanced Micro Devices X86-64
Version:                           0x1
Entry point address: …
=> snapcraft: build and use patchelf 0.18

overlord/devicestate/devicestate.go, overlord/devicestate/devicestate_remodel_test.go, overlord/devicestate/devicestate_systems_test.go, overlord/devicestate/export_test.go, overlord/devicestate/systems.go, overlord/devicestate/systems_test.go, tests/lib/assertions/test-snapd-component-recovery-system-pc-24.json, tests/lib/assertions/test-snapd-recovery-system-pinned.assert, tests/lib/nested.sh, tests/lib/prepare.sh, tests/lib/tools/build_kernel_with_comps.sh, tests/nested/manual/component-recovery-system/task.yaml, tests/nested/manual/recovery-system-offline/task.yaml, tests/nested/manual/recovery-system/task.yaml
This PR allows us to create recovery systems that contain components using the /v2/systems API.
=> many: support creating recovery systems with components from the store

daemon/api_model.go, daemon/api_model_test.go, daemon/api_sideload_n_try.go, daemon/api_sideload_n_try_test.go, daemon/export_api_model_test.go, overlord/devicestate/devicestate.go, overlord/devicestate/devicestate_remodel_test.go, overlord/devicestate/export_test.go, overlord/devicestate/firstboot.go, overlord/devicestate/handlers_remodel.go, overlord/devicestate/handlers_test.go, overlord/managers_test.go, overlord/snapstate/snapstate.go, overlord/snapstate/snapstate_install_test.go, overlord/snapstate/snapstate_update_test.go, overlord/snapstate/target.go, overlord/snapstate/target_test.go
The new snapstate API supports components, so we need to swap over to that before anything else.
This also includes a refactor to move where we make some of the decisions during remodeling. Specifically, we were duplicating a lot of the logic for what snap to install/update for essential and non-essential snaps. This will get worse when introducing components, so I think it makes sense to move things around a bit so that we can share some more code for the essential and non-essential snaps.
=> o/devicestate: refactor remodeling code to use new snapstate API

tests/main/apparmor-prompting-integration-tests/task.yaml
The prompting-client snap is not available for armhf.
=> tests: skip apparmor-prompting-integration-tests in armhf

.github/workflows/spread-results-reporter.yaml
The spread failures reporter was incorrectly not reporting all errors on PRs. This fixes that issue. 
Additionally:
- It adds the URL to the workflow run. 
- It now checks for the presence of the 'Skip spread' label; if that label is present, it will only report "Spread tests skipped." 
- Updated language of "No spread failures" to "No spread failures reported" to indicate simply a lack of spread failure logs rather than a successful run.
To demonstrate the above, I opened three PRs on the demo repo:
- [Spread run generates failure logs](https://github.com/snapcore/snapd-ci/pull/8)
- [Job fails before spread and spread doesn't run](https://github.com/snapcore/snapd-ci/pull/9)
- ['Skip spread' label added to PR](https://github.com/snapcore/snapd-ci/pull/10)
=> tests: fix missing spread failures in PR comments

overlord/snapstate/handlers.go, overlord/snapstate/handlers_link_test.go
Actually we skip the entire link code for snapd  as this has already been done in undoLinkSnap.
REF: SNAPDENG-34315
=> o/snapstate: do not restart again for snapd along the undo path inside undoUnlinkCurrentSnap

cmd/snap-bootstrap/cmd_initramfs_mounts_cvm.go, cmd/snap-bootstrap/cmd_initramfs_mounts_cvm_test.go, cmd/snap-bootstrap/export_test.go, cmd/snap-bootstrap/initramfs_systemd_mount.go, cmd/snap-bootstrap/initramfs_systemd_mount_test.go
This tidies up options to `doSystemdMountImpl` related to dm-verity or overlayfs.
=> c/snap-bootstrap: refactor systemd-mount dm-verity/overlayfs options API

.github/workflows/spread-tests.yaml, .github/workflows/test.yaml
Divides spread systems into fundamental and non-fundamental systems with the goal of running overall fewer tests. The fundamental set of systems are a representative group that hopefully will catch most problems without having to run spread across all systems. Once the tests pass across the fundamental systems, then the remaining systems will run. The systems required to pass for a PR merge remain unaltered.
=> tests: divide spread into fundamental/non-fundamental

interfaces/builtin/opengl.go
interfaces/opengl: Enable parsing of nvidia driver information files
Some nvidia hardware companion utilities required access to driver information in order to operate properly, for example nvidia-persistenced.  This enables read only access to those files.
Example file content:
`/proc/driver/nvidia/gpus/0000\:70\:00.0/information`
```
Model: 		 NVIDIA L4
IRQ:   		 16
GPU UUID: 	 GPU-3291dfa4-fcc4-0110-615b-c894a0d7c689
Video BIOS: 	 95.04.65.00.13
Bus Type: 	 PCIe
DMA Size: 	 47 bits
DMA Mask: 	 0x7fffffffffff
Bus Location: 	 0000:70:00.0
Device Minor: 	 0
GPU Excluded:	 No
```
`/proc/driver/nvidia/capabilities/mig/monitor`
```
DeviceFileMinor: 2
DeviceFileMode: 292
DeviceFileModify: 1
```
=> interfaces/builtin/opengl: enable parsing of nvidia driver information files

tests/main/snap-service-install-mode/task.yaml
There is another column with 'timer-activated' for the service. Ignore this part.
REF: SNAPDENG-34380
=> t/m/snap-service-install-mode: fix line being longer than expected

.github/workflows/spread-results-reporter.yaml
Some spread results have spaces in the name. This ensures the directories are correctly created and accessed.
=> tests: use quotation marks to support directories with spaces

interfaces/builtin/auditd_support.go, interfaces/builtin/auditd_support_test.go
The `auditd` program requires seccomp `setpriority` permission. This is mentioned under exit code 1 in the manpage: https://manpages.ubuntu.com/manpages/oracular/en/man8/auditd.8.html
This is a follow-up to the PR which added the auditd-support interface: #14811
This relates to ongoing work for the customer SF case 00399076.
=> i/builtin: make auditd-support grant seccomp setpriority

tests/nested/manual/remodel-uc-to-next-version-fakestore/prepare-device, tests/nested/manual/remodel-uc-to-next-version-fakestore/repack-kernel.sh, tests/nested/manual/remodel-uc-to-next-version-fakestore/task.yaml
This was merged in https://github.com/canonical/snapd/pull/14305
But it disappeared, probably during a rebase.
=> tests: add remodeling test using fakestore

overlord/managers_test.go, overlord/snapstate/snapstate.go
These were leftover edges from some earlier single-reboot code.
=> overlord: cleanup some old edges

data/Makefile, data/systemd/Makefile, packaging/arch/PKGBUILD, packaging/fedora/snapd.spec, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/rules, packaging/ubuntu-16.04/rules
When building from AUR it is surprisingly common to not perform the builds in chroots or allow one's PATH to leak into the build environment. Turns out, if one has shellcheck installed form a snap, it could be picked up by the build and then trip over the sandbox. However, this highlights a separate issue, where running `make -C data` invokes an implicit default target in `data/systemd` which then happens to run checks/tests. Those are normally reserved for (dist)check like targets and expected to be invoked explicitly. The branch introduces a separate `check` target in top level Makefile under `data` which subsequently invokes `check` for the sole directly having an implementation.
=> data, packaging: separate check and implicit build makefile targets

tests/nested/manual/core20-new-snapd-does-not-break-old-initrd/task.yaml
We should not test the case where we do the install with a new snapd with an old kernel. Some old kernels cannot be in a seed with a too new snapd. However we should still verify that installing a new snapd does not break an existing installation.
On FDE branch: https://github.com/canonical/snapd/pull/14957
=> t/n/m/core20-new-snapd-does-not-break-old-initrd: remove new-snapd/old-kernel case

overlord/snapstate/component.go, overlord/snapstate/component_install_test.go, overlord/snapstate/snapmgr.go, overlord/snapstate/snapstate.go, overlord/snapstate/snapstate_install_test.go, overlord/snapstate/snapstate_test.go, overlord/snapstate/snapstate_update_test.go, overlord/snapstate/snapstatetest/snapstate.go
This change adds a field to SnapSetup for tracking if a SnapSetup comes from a task set that only deals with components.
Additionally, this adds an edge that points to the snap setup task that is created by many of the functions in snapstate. Since a task set might contain many snap-setup tasks, but we really only want to find one (especially now that a snap-setup task needs to carry a `component-setup-tasks`), we use this edge to pick the one that will have all the fields needed to help with remodeling.
=> o/snapstate: add some metadata to help with component remodeling

secboot/encrypt_sb.go, secboot/encrypt_sb_test.go
There was a bug where the protector key file for the plainkey of the ubuntu-save partition was incorrectly used as the unlock key, the fix is to first check the unlock key from the keyring if it is not there, then probably the key file is for the unlock key and no plainkey is used.
=> secboot: look for unlock key in kernel keyring first

.github/workflows/fundamental-systems.json, .github/workflows/non-fundamental-systems.json, .github/workflows/test.yaml
With each push on the designated branches, all tests should run, even if fundamental systems do not pass. This fixes the issue by dividing the non-fundamental job into two: one for PRs and one for everything else. Note that github does not support conditional needs for jobs.
=> tests: have dependency on fundamental systems only for PRs

sandbox/apparmor/notify/export_test.go, sandbox/apparmor/notify/ioctl.go, sandbox/apparmor/notify/listener/export_test.go, sandbox/apparmor/notify/listener/listener.go, sandbox/apparmor/notify/listener/listener_test.go, sandbox/apparmor/notify/message.go, sandbox/apparmor/notify/message_test.go, sandbox/apparmor/notify/notify.go, sandbox/apparmor/notify/notify_test.go, sandbox/apparmor/notify/version.go, sandbox/apparmor/notify/version_test.go
Add versioning to the AppArmor notification protocol, do compatibility checks when registering a listener on the notify socket, and correctly validate incoming message versions against the listener version and set outgoing message versions correctly.
This work is tracked internally by https://warthogs.atlassian.net/browse/SNAPDENG-34337
=> s/a/notify: add proper version handling to the notification protocol

daemon/api_prompting_test.go, interfaces/prompting/constraints.go, interfaces/prompting/constraints_test.go, interfaces/prompting/errors/errors.go
Previously, both prompts and rules used lists of permissions, but now that rules use a map from permission to outcome and lifespan, language around permission lists is no longer accurate. Simply remove the "list" from the error name and error message, and it can continue to be used in both situations.
This is a drive-by fix while working on https://warthogs.atlassian.net/browse/SNAPDENG-31322
=> daemon,i/prompting: replace PermissionsListEmptyError with PermissionsEmptyError

cmd/snap/cmd_pack.go
Trivial fix for formatting problem introduced in #14869.
=> cmd/snap: fix formatting in packCmd struct

interfaces/prompting/constraints.go, interfaces/prompting/constraints_test.go
It's reasonable that one might wish to convert an empty list of abstract permissions to AppArmor permissions, such as when one is constructing an allowed permissions set where all permissions are denied.
It was incorrect to treat this as an error, and furthermore, the only current caller of `AbstractPermissionsToAppArmorPermissions` which actually uses the error value is in `requestprompts`, which logs a logger notice on an error. So we were getting false-positive errors in the journalctl log. This commit fixes that issue.
This addresses https://warthogs.atlassian.net/browse/SNAPDENG-31322
=> i/prompting: do not error when converting empty abstract perms to AA perms

tests/main/confdb-cross-config/task.yaml
This test sometimes fails due to snap-confine issues when running after a specific set of tests (see https://warthogs.atlassian.net/browse/SNAPDENG-34356). I haven't been able to debug it yet but it doesn't happen if run by itself, on another system or even with a different set of sets running before, so it's likely not a confdb issue. I'm disabling this for debian11 while I debug it further so it doesn't impact other work.
=> tests: skip confdb-cross-config on debian11

.github/workflows/spread-tests.yaml, confdb/schema_test.go, image/preseed/preseed_test.go, mkversion.sh, overlord/devicestate/firstboot_test.go, overlord/managers_test.go, overlord/snapstate/snapstate_test.go, strutil/version_test.go, tests/main/listing/task.yaml
The snap ecosystem enforces a length limit on snap versions and the version of snapd, especially non-tagged versions that include git hashes and the FIPS marker, are simply too long.
Abbreviate the longest variant of the version by three bytes by dropping the word "git". This in itself should not impact sorting as the plus byte following git is retained.
=> many: abbreviate version from git by three bytes

overlord/snapstate/snapstate.go, overlord/snapstate/snapstate_test.go
Sometimes during a remodel, we need to create link-snap tasks for snaps that are already installed, but not yet considered boot participants. These tasks were missing reboot boundaries, which caused the tasks to be marked as done before the reboot completed.
tests/nested/manual/remodel-offline exhibits this behavior, where core22 already is installed, but not the model's base snap. The link-snap task that was created during the remodel was being marked as done before the reboot that the task triggers completed.
With this change, the entire remodel change will not be marked as done until that the link-snap task triggers is completed.
=> o/snapstate: put MaybeReboot edges on link-snap in AddLinkNewBaseOrKernel and LinkNewBaseOrKernel

cmd/snapd-apparmor/main.go, interfaces/backends/backends.go, interfaces/backends/backends_test.go, systemd/detect.go, systemd/detect_test.go, tests/regression/lp-1867193/task.yaml
Devices are not namespace-aware in Linux, thus udev inside containers does not really do anything sensible and is set to not execute if /sys is not mounted as a writable file system.
This solves the issue where snapd is failing to install snaps in LXD, demanding workarounds like installing the snap twice, hoping that once-generated files are intact and not trigger a udev rule reload.
Fixes: https://bugs.launchpad.net/snapd/+bug/1712808
Fixes: https://bugs.launchpad.net/snapd/+bug/1865503
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-24757
=> interfaces: disable udev backend when inside a container

daemon/api_systems.go, daemon/api_systems_test.go, overlord/devicestate/devicestate.go, overlord/devicestate/devicestate_systems_test.go, overlord/devicestate/systems.go, tests/nested/manual/component-recovery-system-offline/task.yaml
This enables us to create recovery systems from local component files.
=> o/devicestate, daemon: support creating recovery systems with components in offline context

.github/workflows/non-fundamental-systems.json, .github/workflows/test.yaml
Moves nested tests outside of the fundamental/non-fundamental systems division to run parallel to fundamental systems
=> tests: move nested tests to its own job

snap/squashfs/squashfs.go, snap/squashfs/squashfs_test.go
Do not exclude xattrs when packing the snapd snap. The xattrs need to be preserved in order to support non-setuid snap-confine work.
Related: [SNAPDENG-34240](https://warthogs.atlassian.net/browse/SNAPDENG-34240)
[SNAPDENG-23251]: https://warthogs.atlassian.net/browse/SNAPDENG-23251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SNAPDENG-34240]: https://warthogs.atlassian.net/browse/SNAPDENG-34240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> snap/squashfs: do not exclude xattrs when packing snapd snap

.github/workflows/spread-tests.yaml
Add a "req" tag in the Grafana log name if the system is required. The addition serves to simplify and remove some potential for errors in the dashboard
=> tests: add tag in grafana log path to indicate if system is required

overlord/ifacestate/ifacestate_test.go
Not sure we had other tests that checked the ifacestate <-> interfaces package <-> interface definition interworkings on refresh.
=> o/ifacestate: add some multi-slot connected plug tests to anchor behavior

client/errors.go, daemon/api_prompting.go, daemon/api_prompting_test.go, interfaces/prompting/constraints.go, interfaces/prompting/constraints_test.go, interfaces/prompting/errors/errors.go
If applying a patch to a rule would result in that rule having no permissions, then return an error, including an error response from the snapd API.
This error warrants its own error kind because it is not an internal error or an invalid field error, it's a validation error when taking into account the state of the system, and it doesn't fit under any of the existing validation error kinds for prompting.
This work is tracked internally by https://warthogs.atlassian.net/browse/SNAPDENG-34373
=> client, daemon, i/prompting: return error if patch results in no permissions

cmd/libsnap-confine-private/locking-test.c
=> cmd/snap-confine: fix memory leak in unit test

tests/main/document-interfaces-url/task.yaml
Expected documentation https://snapcraft.io/docs/checkbox-support-interface does not exist. Exclude this from the test until 2025/03 to provide sufficient time to put it in place.
=> tests/main/document-interfaces-url: exclude missing checkbox-support

tests/core/snapd-refresh-undo/task.yaml
This happens on beta validation that /var/lib/snapd/snaps/snapd_x1.snap doesn't exist and there is a snapd snap with the beta revision instead of x1.
=> tests: fix snapd-refresh-undo test for beta validation

interfaces/builtin/fwupd.go
=> i/builtin: allow fwupd access to shim/fallback shim

tests/nested/manual/kernel-modules-components/task.yaml
The time spent sealing the key has increased, wait for more time for the try-kernel.efi link to appear.
=> tests/kernel-modules-components: wait more for the try-kernel.efi link

overlord/fdestate/fdemgr_test.go
Mock the architecture so that boot assets can be properly identified even when running unit tests on ARM64.
=> overlord/fdestate: mock amd64 architecture in unit tests

packaging/opensuse/0001-packaging-snapd.mk-drop-randomized-build-ID-generati.patch, packaging/opensuse/pie.patch, packaging/opensuse/snapd.spec
Sync changes from openSUSE packaging.
=> packaging/opensuse: sync with downstream packaging

cmd/snap-seccomp/export_test.go, cmd/snap-seccomp/main.go, cmd/snap-seccomp/main_test.go, tests/main/snap-seccomp/task.yaml
I was tinkering with the profiles in the context of https://github.com/canonical/snapd/pull/14138 and noticed there is no obvious way to dump the profiles written in the new format.
Add a command to dump the filter rules from a compiled profile to
separate files.
=> cmd/snap-seccomp: add 'dump' command

tests/nested/core/core20-fault-inject-on-refresh/task.yaml
Refresh from store get some kernel that have an old initrd that do not support FDE installation from new snapd.
=> tests/nested/core/core20-fault-inject-on-refresh: disable FDE

interfaces/builtin/docker_support_test.go, testutil/apparmor.go
On some distros which support AppArmor, the apparmor_parser binary is located under /usr/sbin, which also happens to not be included in a regular user's $PATH. The sandbox/apparmor package code is able to locate it directly by checking a number of default paths, however the test code simply assumes that it is available in $PATH. Instead of complicating things further, let's skip the offending unit test.
=> interfaces/builtin, testutil: skip unit test when apparmor_parser is not in PATH

interfaces/builtin/checkbox_support.go, interfaces/builtin/checkbox_support_test.go
Checkbox should have unrestricted access to all devices.
=> interfaces/builtin: make checkbox-support exempt from device access mediation

osutil/disks/disks_linux.go, osutil/disks/disks_linux_test.go
There is a bug in old UC20 kernels where udev does not retrieve data from cold plugged disks initialized in initrd.
It was fixed in:
* https://github.com/canonical/core-initrd/pull/58
* https://github.com/canonical/core-initrd/pull/203
=> osutils/disks: work-around old UC 20 bug where udev did not run on a device

tests/nested/core/core20-fault-inject-on-refresh/task.yaml
Because we do not count reboots correctly, if we did not see the second reboot, we should not fail.
=> t/n/c/core20-fault-inject-on-refresh: do not fail if 2 reboots are not detected

tests/lib/nested.sh, tests/lib/tools/mkimage-uc22, tests/main/mkimage-uc22/task.yaml, tests/nested/manual/install-volume-assignment/task.yaml
UEFI expects non volatile memory which `-bios` can not provide. So to have a behavior that every where what we expect, we should stop using `-bios`. Otherwise, we cannot test UEFI boot entries, sbat revocation, DBX update, etc.
=> tests: remove occurences of -bios parameters to qemu

cmd/snap-failure/cmd_snapd.go
Snapd needs `KeyringMode=shared`, but `snap-failure` runs it without. We either need to add access to the keyring or disable initialization of FDE state when re-seeding.
=> cmd/snap-failure: add fixme about running snapd with keyring access

overlord/devicestate/devicestate.go, overlord/devicestate/devicestate_remodel_test.go, overlord/devicestate/devicestate_systems_test.go, overlord/devicestate/export_test.go, overlord/snapstate/snapstate.go, overlord/snapstate/snapstate_test.go, tests/lib/assertions/test-snapd-component-remodel-initial-pc-24.json, tests/lib/assertions/test-snapd-component-remodel-new-pc-24.json, tests/nested/manual/remodel-with-components/task.yaml
This change enables us to do a remodel that includes components from the store. This is a little incomplete, as I discovered that I need to handle the case where we swap to an already installed kernel (leftover from a previous remodeling) that may have some components already installed. This is a small edge case, and will not change most of the PR.
Based on https://github.com/canonical/snapd/pull/14939 for now.
=> o/snapstate, o/devicestate: remodel with components from the store

interfaces/builtin/u2f_devices.go
This expands the list of OneSpan Product IDs.
OneSpan does not provide documentation that shows the VID/PID, so I cannot link to it.
=> interfaces: Add missing OneSpan Device Product IDs

osutil/chattr.go
Documentation for `unsafe.Pointer` explicitly mentions that uintptr cannot be stored in variable before implicit conversion back to Pointer during system call.
https://pkg.go.dev/unsafe#Pointer
> (4) Conversion of a Pointer to a uintptr when calling functions like [syscall.Syscall](https://pkg.go.dev/syscall#Syscall).
> 
> The Syscall functions in package syscall pass their uintptr arguments directly to the operating system, which then may, depending on the details of the call, reinterpret some of them as pointers. That is, the system call implementation is implicitly converting certain arguments back from uintptr to pointer.
>
> If a pointer argument must be converted to uintptr for use as an argument, that conversion must appear in the call expression itself:
> 
> …
=> osutil/chattr.go: avoid possible garbage collection of unsafe pointer

interfaces/apparmor/template.go
This is used by newer Mesa for GPU accounting.
=> i/default: allow owner read on @{PROC}/@{pid}/fdinfo/*

HACKING.md
I was running through a build using current documentation in HACKING.md for building snapd with snapcraft and it doesn't work in 24.04 (or 22.04). It also doesn't mention the lxd requirement, which leads to uncertainty about the build process when lxd asks many config questions and isn't mentioned in the build instructions. This documentation change:
- Adds --classic flag to snap install for snapcraft, as it is required
- Removes --channel option from snapcraft call as it no longer exists in 8.5.1
- Adds necessary and missing sudo to snap install
- Makes the lxd install and lxd init step explicit
=> docs: Fix snapcraft build instructions and explicitly install lxd

tests/nested/manual/recovery-system-reboot/task.yaml
This a temporary measure since pc-kernel in store does not have a fresh enough snap-bootstrap.
=> tests/nested/manual/recovery-system-reboot: disable disk encryption

tests/nested/manual/remodel-uc20-to-uc22/task.yaml
The encrypted case is more complex and is covered in tests/nested/manual/remodel-uc-to-next-version-fakestore
=> tests/nested/manual/remodel-uc20-to-uc22: remove encrypted case

cmd/snap/cmd_prepare_image.go, cmd/snap/cmd_prepare_image_test.go
Expose the `validation` parameter when preparing the image.
This seems to be forgotten to be exposed when `validation` support for image preparation was implemented.
=> cmd: snap: image: expose 'validation' parameter

spread.yaml
Fedora 39 has reached EOL in Nov 2024.
=> spread: drop Fedora 39

daemon/api_snaps_test.go, daemon/snap.go, overlord/snapstate/handlers.go, overlord/snapstate/snapstate_update_test.go
This fixes https://bugs.launchpad.net/snap-store-desktop/+bug/2089195. Snaps could be falsely marked as being monitored due to absent refresh-candidate entry which could have been pruned or overwritten.
This PR makes the removal more robust so it doesn't early exit when the corresponding refresh-candidate entry is missing. Also, as an extra measure I added a check for Zero proceed time on the API level.
=> o/snapstate: make monitoring removal more robust

overlord/devicestate/devicestate_install_api_test.go, overlord/devicestate/handlers_install.go, tests/lib/muinstaller/main.go, tests/lib/tools/setup_nested_hybrid_system.sh, tests/nested/manual/muinstaller-real/task.yaml
Hybrid systems might not have this mountpoint setup in the pre-existing rootfs. Here, this change makes it so when we install a hybrid system and copy the seed over, we also install and enable a mount unit that will bind mount `/run/mnt/ubuntu-seed` (which is mounted in the initramfs) to `/var/lib/snapd/seed`.
=> o/devicestate, tests: setup bind mount from /run/mnt/ubuntu-seed to /var/lib/snapd/seed on hybrid system install

tests/lib/assertions/test-snapd-recovery-system-reboot-pc-22.json, tests/lib/assertions/test-snapd-recovery-system-reboot-pc-22.model, tests/lib/assertions/test-snapd-recovery-system-reboot-pc-24.json, tests/lib/assertions/test-snapd-recovery-system-reboot-pc-24.model, tests/nested/manual/recovery-system-reboot/task.yaml
recovery-system-reboot:factory_reset creates a recovery system and does a factory reset using it, also using a validation-set assertion that pins some snaps, including pc-kernel 1869. That revision has a kernel signed with a Canonical key. However, when a refresh is triggered after the factory reset, the system refreshes to a pc-kernel from 24/edge as this is the channel specified in the model used in the test. This kernel is signed with a test key. This makes the refresh fail as Secure Boot is enabled. This seems to be random as the re-refresh some times does not refresh all the snaps pending.
This change moves the model assertion to use pc-kernel from 24/beta so we have a kernel with a good signature.
Fwiw, the original seed created by the test is fine because we override the model …
=> tests/assertions: fix recovery-system-reboot:factory_reset test

osutil/export_test.go, osutil/io.go, osutil/io_test.go
Add `AtomicLink`, akin to `AtomicSymlink`, but with hardlinks instead of symlinks.
This functionality is needed for #15003.
This work is tracked internally by https://warthogs.atlassian.net/browse/SNAPDENG-34470
=> osutil: add AtomicLink function to create atomic hardlinks

features/features.go, features/features_test.go
Due to limitations imposed by the kernel support, the `gpio-chardev` interface (not implemented yet) is considered experimental and needs `experimental.gpio-chardev-interface` setting to be enabled in snapd, either explicitly at runtime or through the defaults section in gadget.yaml.
=> features: add experimental gpio-chardev-interface flag

overlord/fdestate/dbx_test.go
The cleanliness status of a change was checked too early. The test were subsequently fixed to properly expect a status at a later moment, but the initial check was never removed.
=> overlord/fdestate: relax change cleanliness checks in dbx unit tests

overlord/snapstate/backend_test.go, overlord/snapstate/handlers.go, overlord/snapstate/snapstate_install_test.go, overlord/snapstate/snapstate_test.go, overlord/snapstate/target.go
This is a follow-up to f2c208e04808ce07e797c0c2ec4f8cefc7cd8232, which added the "store-url" field to snap auxinfo. However, the caller of keepAuxStoreInfo never actually set the `StoreURL` field, so the auxinfo stored to disk continued to be lacking it.
Other related commits are eee4a0e2f0c9fbcc8a6576385abbafb0a0a9cab6, which set up `cmd/snap` to look for store URL in the local snap's auxinfo, and 25ca26311f62ff4f39c4527029a52797eb43373f, which included store URL in the store request.
To see evidence of the store URL currently being missing from local snap info, see the following (assuming snapd and jq are installed):
```bash
snap debug api '/v2/find?name=snapd' | jq '.result.[0]' | grep '"store-url"'
snap debug api '/v2/snaps/snapd' | jq '.result' | grep '"store-url"'
cat …
```
=> o/snapstate: include store url in snap setup and auxinfo stored on disk

interfaces/backends/backends.go, interfaces/configfiles/backend.go, interfaces/configfiles/backend_test.go, interfaces/configfiles/export_test.go, interfaces/configfiles/spec.go, interfaces/configfiles/spec_test.go, interfaces/core.go, interfaces/ifacetest/testiface.go
The configfiles backend ensures the state of configuration files in the filesystem. Interfaces using it must provide a list of globs with the files that are under their control.
For the moment, only classic systems are supported (we write the configuration files in the rootfs). In the future, doing similar changes in the mount namespace of the application might be implemented.
=> interfaces: add configfiles backend

logger/logger.go, logger/logger_test.go
A dependency for both #15003 and now #15032, might as well break out this into its own PR.
=> logger: add function to mock logger with debug enabled

core-initrd/latest/factory/etc/os-release
Add a symlink /etc/os-release pointing to /etc/initrd-release to ensure that the environment can correcly be identified by snap-bootstrap and snapd.
This also completes the recommendation described in os-release(5) regarding execution in initrd/exitrd environments.
Cherry picked from #15030
=> core-initrd: symlink /etc/os-release to /etc/initrd-release

client/errors.go, client/systems.go, daemon/api_systems.go, daemon/api_systems_test.go, daemon/export_api_systems_test.go, gadget/device/encrypt.go, gadget/device/encrypt_test.go, overlord/devicestate/devicestate_install_mode_test.go, overlord/install/install.go, strutil/entropy.go, strutil/entropy_test.go
This PR adds entropy checks for passphrases and PINs used during installation ass specified in SD201 and FO197.
The underlying entropy check implementation itself is naive and is expected to improve. The passphrase/PIN quality checks are expected to be used by snapd before using passphrase/PIN and also by the installer through the new `check-passphrase` and `check-pin` system actions which are added to the `/v2/systems/<label>` endpoint to display to the user in real-time their passphrase/PIN strength.
The PR is split into 3 parts:
- Adding entropy calculation helper `strutil.Entropy()`
- Using entropy-based checks before accepting a passphrase/PIN in snapd during installation
- Extending the /v2/systems API with `check-passphrase` and `check-pin` actions to expose a single source of …
=> many: add passphrase and PINs quality checks system actions

boot/assets.go, boot/assets_test.go, boot/export_test.go, boot/makebootable.go, boot/makebootable_test.go, boot/seal.go, boot/seal_test.go, cmd/snap-bootstrap/cmd_initramfs_mounts.go, cmd/snap-bootstrap/cmd_initramfs_mounts_test.go, gadget/install/install.go, gadget/install/install_test.go, gadget/install/params.go, go.mod, go.sum, overlord/devicestate/devicestate_install_api_test.go, overlord/devicestate/export_test.go, overlord/devicestate/handlers_install.go, overlord/fdestate/backend/seal.go, overlord/fdestate/backend/seal_test.go, overlord/install/install.go, overlord/install/install_test.go, secboot/export_sb_test.go, secboot/secboot.go, secboot/secboot_hooks.go, secboot/secboot_sb_test.go, secboot/secboot_tpm.go
This PR is a re-implementation of https://github.com/canonical/snapd/pull/14918 with suggestion from @valentindavid https://github.com/canonical/snapd/pull/14918#pullrequestreview-2558738600 of not having volumes authentication options attached to the bootstrapped containers but rather passed along with the rest of other FDE params. A followup PR could be created to tidy up the passed FDE parameters (e.g. data/save bootstrap containers, primary key, volume auth options).
This PR implements passphrase authentication support during installation. Currently all volumes created during installation are passphrase encrypted, i.e. `ubuntu-data` and `ubuntu-save`.
Note: This is still not exposed through the API until target system (#14943) and entropy checks are added. This is done by not …
=> many: add passphrase authentication support v2

release/export_test.go, release/release.go, release/release_test.go
Add /etc/initrd-release documented in os-release(5) as an optional fallback, for cases when the initrd lacks required symlinks.
Cherry picked from #15030
=> release: add optional fallback to /etc/initrd-release

confdb/confdb.go, confdb/confdb_test.go, confdb/schema.go, confdb/schema_test.go, overlord/confdbstate/transaction_test.go
This adds support for marking parts of a databag as ephemeral, by allowing us to add a `"ephemeral": true` constraint to type definitions. It also adds an `Ephemeral() bool` function to expose this. In reality, I expect that the most natural implementation of the pruning will just recursively prune parts of the data based on the ephemeral field without using this function directly but I needed some way of testing the parsing without having to also implement the pruning in this commit. We also use Ephemeral() to forbid user-defined types from using ephemeral so, when we support that, we can remove it from the interface and move the functions to export_test just for white-box testing.
=> confdb: support marking paths in schemas as ephemeral

daemon/api_model.go, daemon/api_model_test.go, daemon/api_systems_test.go, daemon/export_api_model_test.go, overlord/devicestate/devicestate.go, overlord/devicestate/devicestate_remodel_test.go, overlord/devicestate/handlers_remodel.go, overlord/managers_test.go, tests/nested/manual/remodel-with-components-offline/task.yaml, tests/nested/manual/remodel-with-components/task.yaml
This change enables us to remodel in an offline context, while including components.
=> many: handle components during an offline remodel

cmd/snap/cmd_get.go, cmd/snap/cmd_get_test.go, cmd/snap/color.go, cmd/snap/main.go
The output of 'snap get' command changes depending on whether the
process is attached to a tty or not. However, instead of checking
whether stdout is attached to a tty, and thus produce a compact listing,
the code checked stdin. Thus redirecting the output did not produce a
desired change in the format.
Related: [SNAPDENG-34147](https://warthogs.atlassian.net/browse/SNAPDENG-34147)
[SNAPDENG-34147]: https://warthogs.atlassian.net/browse/SNAPDENG-34147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> cmd/snap: fix behavior of snap get with tty

strutil/version_test.go
Extend strutil.VersionCompare() unit test with more examples corresponding to actual package versions used in Ubuntu.
=> strutil: extend unit test to cover more realistic version examples

cmd/Makefile.am
Add a unit test support library which *-unit-tests binaries can link with instead of including specific source files from libsnap-confine-private.
=> cmd: build unit test support static library

cmd/Makefile.am, cmd/configure.ac, cmd/libsnap-confine-private/locking-test.c, cmd/libsnap-confine-private/snap-dir-test.c, cmd/libsnap-confine-private/snap-dir.c, cmd/libsnap-confine-private/snap.c, cmd/libsnap-confine-private/string-utils-test.c
I noticed that CHECK_CFLAGS is never substituted, so the flags, even though we collect them in configure.ac, are never passed down to Makefile.
Once I fixed that, a number of compilation errors in libsnap-confine-private turned up, which are all addressed in separate patches.
Note, this PR should be merged with rebase & merge.
=> cmd: libsnap-confine-private: enable checks in when building with unit-tests, fix errors

progress/progress.go, tests/main/progress/task.yaml
Look at stdout rather than stdin when trying to choose appropriate progress meter. The ensures that when snap is invoked under dpkg, it will emit progress regardless of stdin being closed/redirected. At the same time, do not produce a rich output when stdout is redirected.
Related: [SNAPDENG-34147](https://warthogs.atlassian.net/browse/SNAPDENG-34147)
Fixes: LP#1886414
[SNAPDENG-34147]: https://warthogs.atlassian.net/browse/SNAPDENG-34147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> progress: look at stdout rather than stdin when choosing a suitable meter

cmd/snap-bootstrap/cmd_initramfs_mounts.go, cmd/snap-bootstrap/cmd_initramfs_mounts_test.go, secboot/secboot.go, secboot/secboot_sb.go, secboot/secboot_sb_test.go
With the new FDE manager, FDE hooks keys will be authorized for specific boot modes. For now, the keys are authorized for all boot modes. But soon they will be only authorize specific run modes. Snap-bootstrap needs to set the boot mode to authorize the unsealing of those keys.
=> secboot,snap-bootstrap: set boot mode for FDE hooks

confdb/confdb.go, confdb/confdb_test.go, confdb/schema.go, confdb/schema_test.go, overlord/confdbstate/transaction_test.go
This introduces a PruneEphemeral function to schemas. It takes raw data and removes paths that the schema has marked as ephemeral.
=> confdb: support pruning ephemeral data

.github/workflows/test.yaml
Consistently use ubuntu-latest for all jobs. This also fixes use of debian dependencies cache, which collected on 20.04, but later jobs used either ubuntu-22.04 or ubuntu-latest.
=> github: test: use ubuntu-latest, fix caching

osutil/buildid.go, osutil/buildid_test.go, osutil/export_test.go
With Go 1.24, GNU build ID is added to binaries by default, unless -B none is added. Since osutil.ReadBuildID() attempts to read GNU build ID first, the test broke since it expected the Go build ID to be returned.
Related: [SNAPDENG-34507](https://warthogs.atlassian.net/browse/SNAPDENG-34507)
[SNAPDENG-34507]: https://warthogs.atlassian.net/browse/SNAPDENG-34507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> osutil: account for Go 1.24 when reading build ID in the tests

gadget/export_test.go, gadget/gadgettest/examples.go, gadget/gadgettest/gadgettest.go, gadget/ondisk.go, gadget/ondisk_test.go, gadget/raw.go, gadget/raw_test.go, gadget/update.go, gadget/update_test.go, tests/lib/nested.sh
Couple of final changes to support eMMC
* Teach RawStructureUpdater to handle eMMC schema before writing to the disk. Because of how we deal with updates (i.e as a list of abstract updates), it felt simpler to handle this in the RawStructureUpdater, as that is the code that deals with this. 
* Add a missing schema switch in the gadget update code.
* Select the correct sub-device when finding a device location for a volume structure.
REF: SNAPDENG-32503
=> gadget: emmc gadget update support

logger/logger.go, logger/logger_test.go, store/download_test.go, store/export_test.go, store/store.go, store/store_download.go, store/store_download_test.go
This PR is based on #14990 and #15050.
Store the etag for the snap icon (if etag exists) in the xattrs of the icon file on disk. When attempting to update an existing icon, first try to read the etag, and if it does exist, send it in the `If-None-Match` header of the HTTP request to the server.
If the current store icon has the same etag as the existing icon on disk (and the server behaves), the server should respond with 304 Not Modified, and not send the whole icon contents in the response body. The download icon function can then exit early, discarding its pending changes to the filesystem.
If the etag from the server differs from that on disk (or one of them lacks an etag), then the server should respond with a 200, and send the whole icon file contents. The icon download function …
=> store: record snap icon etag and use If-None-Match header

interfaces/builtin/u2f_devices.go, interfaces/builtin/u2f_devices_test.go
Adds Arculus AuthentiKey USB security key device that supports FIDO U2F, CTAP2.1, and PIV.
http://www.linux-usb.org/usb.ids has the 3752:0001 device id as well as https://ccid.apdu.fr/ccid/shouldwork.html#0x37520x0001
Tested webauthn.io register and authenticate with chromium-browser and firefox snaps under a snapcraft built local install and also did ./run-checks.
This is a redo of https://github.com/canonical/snapd/pull/15071 which will be closed.
=> interfaces/u2f: add Arculus AuthentiKey

tests/lib/spread/backend.openstack.yaml
The wait timeout is used to configure the time that spread waits until the instances is allocated with ACTIVE state (and ready to be used).
This is needed to deal with timeouts trying to allocate instances.
=> tests: wait more time until the openstack intance is with Active state

tests/lib/pkgdb.sh
As libfwupd2 is not available any more for tumbleweed, we need to install libfwupd3 instead.
This missing lib is breaking tests in tumbleweed currently
=> tests: update opensuse tumbleweed dependecies

cmd/Makefile.am
The target is no longer used anywhere.
=> cmd: drop unused check-syntax-c target

spread.yaml
Use anchor to pull in system definitions from google-nested to google-nested-dev.
=> spread: use the same system definitions in google-nested-dev as in google-nested

spread.yaml
Include the output of df so that we know how much space is left on disk.
=> spread: include disk space information when debugging nested suites

.github/actions/download-install-debian-deps/action.yaml, .github/workflows/test.yaml, .github/workflows/unit-tests.yaml
Split unit-tests to Go and C specific workflows.
=> github: unit-tests: split unit tests to code specific workflows

confdb/schema.go, confdb/schema_test.go
Allow alternatives to mix ephemeral and non-ephemeral types and process each type in order, taking the first matching alternative's ephemeral tag in consideration when pruning.
=> confdb: process alternative types in order

.github/workflows/spread-tests.yaml
We need to remove the 'set -x' because it is including in the output a huge list of tests when doing
spread_list="$($SPREAD -list $RUN_TESTS 2>&1 || true)"
=> tests: remove 'set -x' from "Run spread tests" step in Tests workflow

tests/nested/manual/hybrid-fde-dbx/task.yaml
Spread test for a hybrid system and a DBX update
Related: [SNAPDENG-34126](https://warthogs.atlassian.net/browse/SNAPDENG-34126)
[SNAPDENG-34126]: https://warthogs.atlassian.net/browse/SNAPDENG-34126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> tests/nested/manual/hybrid-fde-dbx: hybrid with DBX updates

.github/workflows/unit-tests.yaml, .woke.yaml, cmd/Makefile.am, cmd/configure.ac
The branch builds on #15045 and adds support for building with asan and ubsan. This is only useful for testing local installation or running unit tests, as otherwise we'd have to ship libasan/libubsan in the snapd snap to make it universally useful in all scenarios.
Note, some binaries which are linked statically, `snap-gdb*-shim` specifically, had to be skipped, since libasan relies on dlopen().
=> cmd: add support for building with address and undefined behavior sanitizers

cmd/snap-bootstrap/main.go, cmd/snapd/main.go, secboot/argon2_out_of_process.go, secboot/argon2_out_of_process_dummy.go, secboot/argon2_out_of_process_sb.go, secboot/argon2_out_of_process_sb_test.go, secboot/export_sb_test.go, secboot/secboot.go, secboot/secboot_sb_test.go, secboot/secboot_tpm.go
`MaybeRunArgon2OutOfProcessRequestHandler` is supposed to be called from the `main()` of binaries involved with sealing/unsealing of keys (i.e. `snapd` and `snap-bootstrap`).
This switches the binary to a special mode where it acts as an argon2 out-of-process helper command, and exits when its work is done.
For more context, check docs for [`sb.WaitForAndRunArgon2OutOfProcessRequest`](https://github.com/canonical/secboot/blob/30317622bbbc348db12d91659332ed66cd9da642/argon2_out_of_process_support.go#L453) and [`sb.NewOutOfProcessArgon2KDF` ](https://github.com/canonical/secboot/blob/30317622bbbc348db12d91659332ed66cd9da642/argon2_out_of_process_support.go#L1066)for details on how the flow works in secboot.
This PR also reverts workaround from https://github.com/canonical/snapd/pull/15058 …
=> cmd, secboot: add argon2 out-of-process kdf support

data/systemd/snapd.gpio-chardev-setup.target, packaging/arch/PKGBUILD, packaging/debian-sid/rules, packaging/fedora/snapd.spec, packaging/opensuse/snapd.spec
The `snapd.gpio-chardev-setup.target` will be used for synchronization of app services and virtual device setup during boot.
=> data/systemd: add gpio-chardev systemd ordering target

spread.yaml
We should be using metalink instead of putting more pressure on the main mirrors.
=> spread: stop disabling metalink for Fedora

tests/main/apparmor-batch-reload/task.yaml, tests/main/apparmor-prompting-flag-restart/task.yaml, tests/main/apparmor-prompting-integration-tests/task.yaml, tests/main/apparmor-prompting-snapd-startup/task.yaml, tests/main/interfaces-requests-activates-handlers/task.yaml, tests/main/interfaces-snap-interfaces-requests-control/task.yaml, tests/main/remote-home/task.yaml, tests/main/store-state/task.yaml
These fixes are needed to fix sru validation where the snap snap is not used and we use the snapd deb from proposed instead. 
The change include fixes for tests:
- tests/main/apparmor-batch-reload/task.yaml
- tests/main/apparmor-prompting-flag-restart/task.yaml
- tests/main/apparmor-prompting-integration-tests/task.yaml
- tests/main/apparmor-prompting-snapd-startup/task.yaml
- tests/main/interfaces-requests-activates-handlers/task.yaml
- tests/main/interfaces-snap-interfaces-requests-control/task.yaml
- tests/main/remote-home/task.yaml
- tests/main/store-state/task.yaml
=> tests: tests fixes for sru validation

cmd/snap-bootstrap/cmd_initramfs_mounts.go, cmd/snap-bootstrap/cmd_initramfs_mounts_test.go, cmd/snap-bootstrap/export_test.go, core-initrd/latest/factory/usr/lib/systemd/system/snap-initramfs-mounts.service
Previously we looked at the model and mounted base/rootfs directly if it was Ubuntu 24+. Now, we check instead an environment variable that is set if the initramfs is 24+.
This is done so now the kernels that contain the 24+ initramfs can be booted in older Ubuntu releases with older bases. This situation is not something we really support, as the systemd of the initramfs will not match the one in the system, but it is something that could happen while remodeling and it seems safer to allow this at least temporarily.
=> core-initrd,snap-bootstrap: look at env to mount directly to /sysroot

cmd/.clangd
Add -D_GNU_SOURCE so that clangd doesn't complain about O_PATH.
=> cmd/clangd: add _GNU_SOURCE

dirs/dirs.go, overlord/managers_test.go, overlord/snapstate/backend.go, overlord/snapstate/backend/aux_store_info.go, overlord/snapstate/backend/export_test.go, overlord/snapstate/backend/icon.go, overlord/snapstate/backend/icon_test.go, overlord/snapstate/backend/metadata.go, overlord/snapstate/backend/metadata_test.go, overlord/snapstate/backend_test.go, overlord/snapstate/handlers.go, overlord/snapstate/snapstate_install_test.go, store/store_download.go, store/store_download_test.go, store/storetest/storetest.go
This PR is based on #15051, and replaces #15003.
During the "download-snap" task, download the snap icon as well.
During "link-snap" and "unlink-snap", link/unlink the snap icon from the downloaded icons pool to the  installed icons directory. Do this by adding snap icon management helpers, and calling them from the store metadata helpers in the backend.
Lastly, discard the downloaded snap icon when the final revision of the snap is discarded from disk (and there are no other instances). We want to ensure that the snap icon remains in the pool during any situation when it's possible to install the snap without doing another "download-snap" task, such as via a revert.
This PR is tracked internally by https://warthogs.atlassian.net/browse/SNAPDENG-34436
=> o/snapstate: download, link, unlink, and discard snap icon in snapstate handlers

cmd/snap-confine/snap-confine.c
Fix type mismatch warnings due to incorrect debug() type specifier that's escalated to errors when build in LP. 
The mismatches that shows in noble, oracular and plucky happens because of armhf definition type changes in  sys/time.h
tv.sec:        `long int`     ->    `__int64_t`
tv.usec:      `long int`     ->    `__int64_t`
Example: https://launchpadlibrarian.net/777801433/buildlog_ubuntu-plucky-armhf.snapd_2.68+ubuntu25.04_BUILDING.txt.gz (look for `snap-confine/snap-confine.c: In function`)
Currently affects armhf (32 bit) on: [2.68 | 25.04](https://launchpad.net/~snappy-dev/+archive/ubuntu/image/+sourcepub/16993872/+listing-archive-extra), [2.68 | 24.10](https://launchpad.net/~snappy-dev/+archive/ubuntu/image/+sourcepub/16993850/+listing-archive-extra), [2.68 | …
=> cmd/snap-confine: fix type specifier type mismatches on armhf

gadget/gadgettest/examples.go, gadget/install/export_test.go, gadget/install/install.go, gadget/install/install_test.go, gadget/install/partition.go, gadget/install/partition_test.go
When performing a re-install, snapd uses "size" from the gadget when re-creating partitions that it just removed. However, in the case of using min-size there is a possibility that the deleted partition size was smaller but still compatible with the installed gadget. Use the size of the deleted partition, as we want to respect the already existing layout - otherewise we might destroy partitions that are not re-created in the re-install and that could appear after the partitions using min-size.
=> gadget: make reinstalls honor existing sizes of partitions

.github/workflows/snap-builds.yaml, build-aux/snap/snapcraft.yaml
This change was initiated by a conversation started by Iseoluwa Titiloye https://chat.canonical.com/canonical/pl/qpo9iy53z3fudkbdj4akdnteth
Related to: https://bugs.launchpad.net/snapcraft/+bug/2097440
=> snapcraft.yaml: fix missing primed packages in manifest

tests/nested/manual/muinstaller-real/task.yaml
We were hitting the 32 characters limit in the version because now the kernel uses very long strings as version, line
5.15.0-130.140.1+1+535.216.03.
=> tests/muinstaller-real: make fake kernel version shorter

tests/lib/spread/rules/nested.yaml
This will automatically trigger nested tests if certain key areas of the go code are changed, while excluding changes to go tests. The change will be helpful in cases where a developer makes a change and should have added the "Run nested" label but forgot to do so.
As an example, any changes inside the `kernel` directory will automatically trigger nested tests:
```
$ tests/lib/external/snapd-testing-tools/utils/spread-filter -r tests/lib/spread/rules/nested.yaml -p "google:ubuntu-24.04-64" -c kernel/fde/fde.go 
google:ubuntu-24.04-64:tests/nested/
```
while changes to a key directory but to a unit test will not:
```
$ tests/lib/external/snapd-testing-tools/utils/spread-filter -r tests/lib/spread/rules/nested.yaml -p "google:ubuntu-24.04-64" -c overlord/devicestate/systems_test.go 
$
```
=> tests: automatically run nested tests for certain go changes

cmd/libsnap-confine-private/tool.c, cmd/libsnap-confine-private/utils.h
We had a recurring pattern of switching the identity, then calling a tool, followed by restoring the old identity. Since the tool is called in a forked child process anyway, there is no clear win to switch the identity in the parent process, which then requires a followup restore operation. Move switching of identity to the child process, this simplifying the code path.
Cherry picked from https://github.com/canonical/snapd/pull/15094 where it allows the code to not need PR_SET_KEEPCAPS.
Related: [SNAPDENG-34419](https://warthogs.atlassian.net/browse/SNAPDENG-34419) …
=> cmd/libsnap-confine-private/tool: switch identity only after forking a child

NEWS.md, cmd/snap-confine/snap-confine.c, packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
This is a deb only dot release that fixes a type warning that gets escalated to error preventing armhf builds for newer releases. 
**VERIFICATION:** Current automated tests does not cover building for armhf or any other 32 bit system. Verified the fix by uploading on LP PPA: [LP builds to verify the fix](https://launchpad.net/~ernestl/+archive/ubuntu/snapd2/+build/30362382)
DEBEMAIL="Ernest Lotter [ernest.lotter@canonical.com](mailto:ernest.lotter@canonical.com)" release-tools/changelog.py 2.68.1 2098137 NEWS.md
Cherry picks:
- https://github.com/canonical/snapd/pull/15111
SRU Bug: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/2098137
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-34552
Requires rebase merge
=> Release: 2.68.1

.github/workflows/nested-systems.json, .github/workflows/nightly-spread.yaml, .github/workflows/spread-tests.yaml, .github/workflows/test.yaml
This change runs the tests using master branch nightly instead of after a change is pushed to master.
We do that in order to reduce the amount of instances used in google.
Also the nightly job was renamed to nightly-static-analysis which is a more representative name.
=> tests: run tests on master branch nightly

interfaces/builtin/opengl.go
This is a follow-up of #14685.
I am trying to create [a snap](https://github.com/pedro-avalos/rocminfo-snap) of [`rocminfo`](https://github.com/rocm/rocminfo), and I noticed that `rocminfo` is accessing the Kernel Fusion Driver via the `/sys/devices/virtual/kfd` path to retrieve the GPUs' properties. I've added the files that `rocminfo` was specifically accessing, but there are other subdirectories/files that are not included here.
These denials seem to also be blocking `rocm-validation-suite` from querying these properties when running some of its tests.
I also noticed that the Mir team is also [interested](https://github.com/canonical/graphics-test-tools/issues/18) in including `rocminfo` in their graphics-test-tools, so I'm sure they'd run into these issues eventually.
Let me know if …
=> interfaces: Add more kernel fusion driver files to opengl

cmd/libsnap-confine-private/tool.c, cmd/libsnap-confine-private/utils.c, cmd/libsnap-confine-private/utils.h, cmd/snap-confine/snap-confine.c
A followup to #15100, which adds a helper suggested by @alexmurray and updates all sites where change_uid/gid is used to pass bools.
=> cmd/libsnap-confine-private,snap-confine: helper for no-change identity, booleans with sc_identity

cmd/libsnap-confine-private/cgroup-support-test.c, cmd/libsnap-confine-private/classic.c, cmd/libsnap-confine-private/device-cgroup-support.c, cmd/libsnap-confine-private/snap-test.c, cmd/libsnap-confine-private/snap.c, cmd/libsnap-confine-private/utils-test.c, cmd/libsnap-confine-private/utils.c, cmd/libsnap-confine-private/utils.h, cmd/snap-confine/mount-support-nvidia.c, cmd/snap-device-helper/snap-device-helper-test.c, cmd/snap-discard-ns/snap-discard-ns.c, cmd/snapd-generator/main.c
Introduce a macro SC_ARRAY_SIZE derived from Linux' ARRAY_SIZE. See https://elixir.bootlin.com/linux/v6.13.3/source/include/linux/array_size.h#L11 for reference.
And yes, the static check actually raises an error when trying with non 'array' types. This is obtained after enabling the snippet in utils-test.c which should fail during compilation:
```
libsnap-confine-private/utils-test.c: In function ‘test_sc_array_size’:
libsnap-confine-private/utils.h:30:18: error: division ‘sizeof (char *) / sizeof (char)’ does not compute the number of array elements [-Werror=sizeof-pointer-div]
30 |     (sizeof(arr) / sizeof((arr)[0]) + ((int)sizeof(struct {                                                 \
|                  ^
/usr/include/glib-2.0/glib/gtestutils.h:54:61: note: in definition of macro …
```
=> cmd/libsnap-confine-private, cmd: introduce SC_ARRAY_SIZE macro and use where applicable

.github/workflows/snap-builds.yaml, .github/workflows/test.yaml
Changing to github hosted arm runners due to self-hosted arm runners giving problems that is blocking merging the release content. This can be reverted back once the self-hosted runners are back in action.
=> tests: switch to github-hosted arm runners

tests/lib/snaps/test-snapd-policy-app-consumer/meta/snap.yaml, tests/main/interfaces-posix-mq/task.yaml
The posix-mq interface was merged a while ago without any dedicated tests. Historically there were a number of issues around mediation of mqueue and having this sort of test provided earlier might have saved us some time later.
The test verifies runtime correctness of the read, write, create and delete permissions specific to the posix-mq interface, using the test-snapd-posix-mq snap. The snap has been issued with a snap declaration assertion to use the posix-mq interface slots, which are super-privileged. All slots grant access to the /test POSIX message queue, with the relevant permission, read, write, create or delete.
The tests is skipped on Ubuntu Core 18 and earlier, and equivalent, due to a bug (referenced). Technically the interface apparmor elements require apparmor_parser …
=> tests: add test for the posix-mq interface

overlord/fdestate/backend/export_test.go, overlord/fdestate/backend/reseal.go, overlord/fdestate/backend/reseal_test.go, overlord/fdestate/backend/seal.go, overlord/fdestate/backend/seal_test.go, secboot/export_sb_test.go, secboot/secboot.go, secboot/secboot_dummy.go, secboot/secboot_hooks.go, secboot/secboot_sb_test.go
2 commits:
* secboot,overlord/fdestate: seal with boot mode for FDE hooks
Set the authorized boot modes for FDE hook keys. For now the run+recover key allows "run" and "recover", while the recover key allows "recover" and "factory-reset".
* overlord/fdestate/backend: split profiles for data and save partitions
There should be 3 different keys for FDE hooks. The run+recover key should be allowed for boot modes "run" and "recover". While recover key on data disk should be allowed on "recover". And finally recovery  on save disk should be allowed in "recover" and "factory-reset". Here we split the profiles for "recover" for disks "data" and "save", so that we can set different authorized boot modes.
=> secboot,fdestate: use boot mode for FDE hooks

tests/main/snap-quota/task.yaml
Despite groups not being assigned to any snaps, there are quota groups related files created by system under /sys/fs/cgroup/. Make sure to remove all groups and check that no files are left behind.
Cherry picked from #15094
=> tests/main/snap-quota: explicitly remove all created groups during restore

daemon/api_snapctl.go, daemon/api_snapctl_test.go
If the snapd-snap socket receives a request with no context or invalid context and there is a stdin field, the service could crash. Fix this with a simple check.
=> daemon: the service could crash for some snapctl inputs

.github/workflows/nightly-spread.yaml
The spread jobs didn't have a dependency on the read-systems job, which caused those jobs to remain forever in a pending state for lack of data.
=> tests: fix nightly spread executions and add them to manual dispatch

interfaces/builtin/posix_mq.go, interfaces/builtin/posix_mq_test.go, sandbox/apparmor/apparmor.go, sandbox/apparmor/apparmor_test.go
All the patches have detailed descriptions but the main idea is make the interface more precise. The `type=posix` qualifier ensures that the rules talk about POSIX message queues and not sysv queues. The `getattr` and `setattr` changes codify ability to express those permissions and retain the former semantics of automatically providing them by default whenever the `read` or `write` permissions are used.
The penultimate patch in this series fixes a bug that incorrectly clobbered a global variable.
=> interfaces: fix a number of issues affecting posix-mq

tests/lib/muinstaller/mk-classic-rootfs.sh
https://cdimage.ubuntu.com/ubuntu-base/releases/24.04/release/ubuntu-base-24.04.1-base-amd64.tar.gz now gives 404, move to 24.04.2 release
=> tests/muinstaller: move to 24.04.2 release

cmd/snap/cmd_prepare_image.go, cmd/snap/cmd_prepare_image_test.go, image/image_linux.go, image/options.go, seed/seedwriter/writer.go, seed/seedwriter/writer_test.go, spread.yaml
Snapd 2.68 or later is not compatible in the same seed as snap-bootstrap 2.67 or before. We need to make it a bit more obvious to image builders by forbidding that combination.
=> image, seed: check snap-bootstrap compatibility for FDE

boot/bootstate20.go, boot/export_test.go, boot/makebootable.go, boot/seal.go, boot/seal_test.go
when we write a fresh modeenv and seal we are operating on the modeenv
of not the current system, so it was wrong to use the same mutext
this now mostly avoid overlapping operations of this kind, which shouldn't
happen, but is the most conservative change
we need to rethink the modeenv mutexes as naively releasing the
state lock while holding them can create deadlocks when we try
to reacquire the former
=> boot: have a separate mutex for the sections writing a fresh modeenv 

overlord/devicestate/devicestate_remodel_test.go, overlord/snapstate/snapstate.go, overlord/snapstate/snapstate_install_test.go, overlord/snapstate/snapstate_test.go, tests/lib/assertions/test-snapd-remodel-to-installed-kernel-24.json, tests/lib/assertions/test-snapd-remodel-to-installed-kernel-rev-1-24.json, tests/lib/assertions/test-snapd-remodel-to-installed-kernel-rev-2-24.json, tests/lib/assertions/test-snapd-remodel-to-installed-kernel-rev-3-24.json, tests/lib/tools/build_kernel_with_comps.sh, tests/nested/manual/remodel-to-installed-kernel/task.yaml
This fixes and tests the case where we remodel to a kernel snap that is already installed on the system, but is not the current kernel due to a previous remodel.
Note that this PR removes the existing "prepare-kernel-snap" task from the created tasks here, because the task is superfluous in this case. The kernel's drivers tree is already generated from the original installation of the kernel.
=> many: fix swapping back and forth between kernels with components during remodeling

go.mod, go.sum, secboot/secboot_hooks.go
Bump secboot to include a fix from
https://github.com/canonical/secboot/pull/384
=> secboot: bump secboot to rev e07f4ae48e98

tests/main/progress/task.yaml
We're trying to identify a failure in spread tests which is manifested
by the following output:
+ tr '\r' '\n'
+ socat 'system:snap install test-snapd-tools-core24,pty,raw,echo=0' -
2025/02/25 20:01:47 socat[182348] W exiting on signal 15
+ socat 'system:snap remove test-snapd-tools-core24,pty,raw,echo=0' -
+ tr '\r' '\n'
The culprit seems to be the default IO timeout which is set at 0.5s.
Bump the timeout to 30s, but keep debug logs on in case we need them.
=>  tests/main/progress: set IO timeout and collect verbose debug log from socat

.github/workflows/nightly-spread.yaml, .github/workflows/spread-tests.yaml
The nightly tests were missing the flag to use the snapd snap from master and the arm snap download was missing a check on that flag.
=> tests: fix using master snap flag on nightly

tests/main/prepare-image-classic/task.yaml
This warning was added to warn against snapd 2.68+ not being compatible with a kernel containing snapd prior to 2.68 which is useful in the context of FDE installations.
This was introduced by #15106.
=> tests: account for snapd/kernel incompatibilty warning in prepare-image

spread.yaml
Those are missing as compared to google backends.
=> spread: add ubuntu-{24.10,25.04}-64 to qemu

packaging/ubuntu-16.04/rules
Drop extra bracket.
During release 2.68.2, the LP deb build for plucky failed.
This was broken since commit commit 9f6a29a2d11d75d96de278288c444102decb3ec6, but became problematic after plucky started using make 4.4.
=> packaging/ubuntu-16.04: fix ifneq in debian/rules

dirs/dirs.go, interfaces/polkit/backend.go, interfaces/polkit/backend_test.go, interfaces/polkit/spec.go, interfaces/polkit/spec_test.go, polkit/validate/validate.go, polkit/validate/validate_test.go
This PR extends the polkit backend to allow adding custom rules supplied by a snap, actual use of the rules backend will be in a followup PR.
For reference please check SD198.
=> interfaces: extend polkit backend to support custom polkit rules

packaging/ubuntu-16.04/rules
Fix snapd deb build on plucky.
Build issue encountered during snapd deb build on plucky as per [build log](https://launchpadlibrarian.net/779864313/buildlog_ubuntu-plucky-amd64.snapd_2.68.2+ubuntu25.04.1_BUILDING.txt.gz):
Tested build for plucky: https://launchpad.net/~ernestl/+archive/ubuntu/snapd/+build/30388551
Borrowed fix for similar issue: https://salsa.debian.org/debian/snapd/-/commit/59b0652d7a34c6534616b249d2334c5654e22758
=> debian/rules: change permissions of /var/lib/snapd/void

spread.yaml
On 01-03-2025 Arch project has finally turned off the [community] repository mirrors. This ends a 2 year grace period period since the change was first announced. While we have a task to fix and update spread images, the patch adds a temporary workaround.
=> spread, arch: workaround for dropped community repository

tests/core/prepare-image-mismatch-snapd/task.yaml
=> tests/core: add test for the prepare-image switch and env variable

overlord/confdbstate/confdbmgr.go, overlord/confdbstate/confdbmgr_test.go, overlord/confdbstate/confdbstate.go, overlord/confdbstate/confdbstate_test.go, overlord/confdbstate/export_test.go, overlord/hookstate/ctlcmd/fail_test.go, snap/hooktypes.go
81070b99be08ae23ea5d9896d39a9e16ecc7b6e3 changes the key used to link tasks to the transaction carrying task
c3aca30ebc073e6495cc550f83f44a0f4d55df82 is a small refactor to prevent duplicating some code in the new helper
5490fc10db201a9237ec457b7a2b9eacc5791dab adds support for the query-view and load-view hooks as well as a helper that schedules tasks appropriately
=> o/confdbstate: add helper to schedule load confdb hook/tasks

sandbox/apparmor/apparmor.go, sandbox/apparmor/apparmor_test.go
Previously, only directories under /sys/kernel/security/apparmor/features were included in the probed kernel features list. However, boolean files are sometimes used to indicate support for particular features as well.
This commit extends the probed features to include the presence of files, as well as directories.
Though we are looking in a sysfs, /sys/kernel/security/apparmor/features is entirely managed by apparmorfs, so it should not be a problem to include files there in the kernel features (and by extension in the system key).
This is required by #15089 so that the version support checks can use `apparmor.KernelFeatures` to check for the presence of the protocol version boolean files, indicating kernel support for particular versions.
This work is tracked internally by …
=> s/apparmor: include files in apparmor kernel features

overlord/configstate/configcore/prompting_test.go, sandbox/apparmor/apparmor.go, sandbox/apparmor/apparmor_test.go, sandbox/apparmor/export_test.go, sandbox/apparmor/notify/listener/export_test.go, sandbox/apparmor/notify/listener/listener.go, sandbox/apparmor/notify/listener/listener_test.go, sandbox/apparmor/notify/notify.go, sandbox/apparmor/notify/notify_test.go, sandbox/apparmor/notify/version.go
Move the definition of the notify socket path from the notify package into the apparmor package. This means that the apparmor package no longer needs to import the notify package, so the notify package can import the apparmor package in the future without a circular import.
This is required for #15089 so that it can check the supported AppArmor kernel features by importing the `apparmor` package.
This work is tracked internally by https://warthogs.atlassian.net/browse/SNAPDENG-34598
=> many: move notify.SysPath to apparmor.NotifySocketPath

tests/core/snapd-refresh-undo/task.yaml, tests/main/aux-info/task.yaml, tests/main/snap-icons-fallback/task.yaml, tests/main/snap-quota-services/task.yaml
Using edge channel for test snaps and skipping arm devices doe quota-services test.
=> tests: fixes for errors found in snapd  2.68.2 validation

interfaces/prompting/constraints.go, interfaces/prompting/constraints_test.go, interfaces/prompting/requestprompts/requestprompts.go, interfaces/prompting/requestprompts/requestprompts_test.go, overlord/ifacestate/apparmorprompting/export_test.go, overlord/ifacestate/apparmorprompting/prompting.go, overlord/ifacestate/apparmorprompting/prompting_test.go, sandbox/apparmor/notify/listener/export_test.go, sandbox/apparmor/notify/listener/listener.go, sandbox/apparmor/notify/listener/listener_test.go, sandbox/apparmor/notify/permission.go
Rather than using `any` to store and pass around generic AppArmor permission masks (which are usually `notify.FilePermission`), instead create a dedicated interface with a `AsAppArmorOpMask` method which returns the corresponding `uint32` permission mask for the AppArmor `MsgNotificationOp`. This way, we can enforce that only appropriate types are passed into replies, and the reply code itself can use the be simplified by using the new method without requiring additional validation.
This work is tracked internally by https://warthogs.atlassian.net/browse/SNAPDENG-30466
=> many: create notify.AppArmorPermission interface

interfaces/builtin/network_control.go, tests/main/interfaces-network-control/task.yaml
Trying to delete a network namespace raises a denial:
audit: type=1400 audit(1741169474.109:5051): apparmor="DENIED"
operation="umount" class="mount"
profile="snap.network-control-consumer.cmd"
name="/run/netns/foo" pid=2490600 comm="ip"
Issue reported by customer.
=> interfaces/builtin/network_control: allow removing created network namespaces

cmd/snap-fde-keymgr/main.go, secboot/keymgr/export_test.go, secboot/keymgr/keymgr_luks2.go, secboot/keymgr/keymgr_luks2_test.go
When using snapd 2.68+ along with snap-boostrap <2.68, then the path in keyring is still using the old by-partuuid path, but the old keymgr tries to find it with the new path. So we need to look for the old path if we cannot find the new one.
SF00406468
=> secboot/keymgr: fallback to old keyring path for keys

spread.yaml
This reverts commit 513d788c376dfe7309a6bf6bcc2bfcc1787572c1.
The arch linux base images was updated here https://github.com/canonical/spread-images/pull/26
=> spread: Revert "spread: arch: workaround for dropped community repository (#15160)"

.github/workflows/fundamental-systems.json, .github/workflows/nested-systems.json, .github/workflows/nightly-spread.yaml, .github/workflows/non-fundamental-systems.json, .github/workflows/spread-tests.yaml, .github/workflows/test.yaml
Through this change it is possible to determine if the alternative backend has to be used for the a group in the ci
Alternative backends usage depends on the value stored in the file USE_ALTERNATIVE_BACKEND, where it is defined the backend to use when images are ready in both google and openstack.
The content for USE_ALTERNATIVE_BACKEND is:
opensuse: false,
debian-not-req: false,
centos: false,
ubuntu-jammy: false,
ubuntu-focal (fundamental): false,
ubuntu-noble (fundamental): false
In case we need to swith a group, we just need to change false by true
=> tests: add switch to move executions between google and openstack

.github/workflows/test.yaml
This removes the fundamental/non-fundamental dependency for PRs with the "cross-distro" label
=> tests: if PR has cross-distro label, run all systems in parallel

cmd/snap-bootstrap/cmd_initramfs_mounts.go, cmd/snap-bootstrap/cmd_initramfs_mounts_cvm.go, cmd/snap-bootstrap/cmd_initramfs_mounts_cvm_test.go
The sysroot.mount is now dynamically created by snap-bootstrap instead of being a static file in the initramfs, but that was being done only for UC/hybrid. Make sure that this happens also for CVMs.
=> cmd/snap-bootstrap: create sysroot.mount for CVMs

cmd/Makefile.am, cmd/snap-discard-ns/snap-discard-ns.c
Assert process capabilities, to ensure correctness when invoked from snap-confine.
Cherry picked from #15094. This is a preparatory step for having snap-discard-ns be invoked by a user with privileges carried by capabilities.
Related: [SNAPDENG-34419](https://warthogs.atlassian.net/browse/SNAPDENG-34419)
[SNAPDENG-34419]: https://warthogs.atlassian.net/browse/SNAPDENG-34419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> cmd/snap-discard-ns: assert process capabilities

packaging/opensuse/permissions, packaging/opensuse/permissions.easy, packaging/opensuse/permissions.easy.in, packaging/opensuse/permissions.in, packaging/opensuse/permissions.paranoid, packaging/opensuse/permissions.paranoid.in, packaging/opensuse/permissions.secure, packaging/opensuse/permissions.secure.in, packaging/opensuse/snapd.spec
The permissions file for snapd uses incorrect libexecdir location on
openSUSE Tumbleweed (/usr/lib/snapd instead of /usr/libexec/snapd).
Hence, permissions were never correctly applied through permctl and the
setuid on s-c only worked by accident as we were setting
%attr(4775,root,root).
=> packaging/opensuse: fix setting permissions through permctl

tests/lib/prepare-restore.sh
Modern sudo setups use /etc/sudoers.d/ for local configuration. Some even take it a step further and use /usr/etc/sudoers which includes /etc/sudo, but in this case the latter needs to be properly built so that it doesn't break the configuration. To make all setups happy, try to use /etc/sudoers.d where possible.
=> tests/lib/prepare-restore: use /etc/sudoers.d where possible

.github/workflows/nested-systems.json
Fix small typo that caused never running nested tests on ubuntu-22.04, instead running on 24.04 twice.
=> tests: fix not running nested-ubuntu-22.04

cmd/snap/cmd_debug_paths.go, cmd/snap/cmd_debug_paths_test.go, daemon/api_general_test.go, dirs/dirs.go, dirs/dirs_test.go, dirs/dirstest/mocks.go, dirs/export_test.go, overlord/devicestate/firstboot_test.go, overlord/managers_test.go, overlord/overlord_test.go, overlord/servicestate/servicemgr_test.go, overlord/snapstate/readme_test.go, overlord/snapstate/snapstate_install_test.go, overlord/snapstate/snapstate_test.go, snapdtool/cmdutil_test.go, syscheck/dirs.go, syscheck/dirs_test.go, syscheck/export_test.go, tests/main/core18-configure-hook/task.yaml, tests/main/mount-dir-detect-check/task.yaml, tests/main/snapd-snap-removal/task.yaml, wrappers/internal/service_unit_gen.go, wrappers/internal/service_unit_gen_test.go, wrappers/services_test.go
dirs: auto detect snap mount dir location on unknown distributions
Introduce automatic detection of snap mount directory, similarly to a
change introduced to snap-confine in
https://github.com/canonical/snapd/commit/0d60393deebbbd4972996639e6cf727745b4e2dc.
This enables proper support of mount dir on distributions which we have
no information on, but one of the expected mount locations is provided
by the packaging.
Related: [SNAPDENG-34258](https://warthogs.atlassian.net/browse/SNAPDENG-34258)
[SNAPDENG-34258]: https://warthogs.atlassian.net/browse/SNAPDENG-34258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> dirs, many: auto detect snap mount dirs

core-initrd/24.04/debian/changelog, core-initrd/24.10/debian/changelog, core-initrd/latest/debian/changelog
New packages had to be uploaded after mreging
https://github.com/canonical/snapd/pull/15168.
=> core-initrd: changelog update after CVM fix

tests/main/interfaces-system-dbus/task.yaml
Ensure that snaps are fully removed, such that their cgroups may be cleaned up.
=> tests/main/interfaces-system-dbus: ensure snaps are fully removed in restore

tests/lib/pkgdb.sh, tests/main/apparmor-prompting-integration-tests/task.yaml
The github CI images have lsof, but when running spread on qemu or elsewhere, it may not be installed. Ensure it is.
Additionally, drive-by cleanup some extraneous whitespace.
=> tests: ensure spread tests have lsof preinstalled

tests/main/interfaces-kernel-module-load/task.yaml, tests/main/interfaces-kernel-module-load/test-snapd-kernel-module-load/meta/snap.yaml
The 6.14.0-1002-gcp kernel in 25.04 cloud images does not ship the
vmac module anymore.
=> tests/interfaces-kernel-module-load: switch vmac to wp512 module

overlord/fdestate/backend/reseal.go, overlord/fdestate/backend/reseal_test.go, overlord/fdestate/dbx_test.go, overlord/fdestate/export_test.go, overlord/fdestate/fdemgr.go, overlord/fdestate/fdemgr_test.go, overlord/fdestate/fdestate.go, overlord/managers_test.go
Both the state and reseal needed to know where disk and keys were
located. This now always takes the run mode and the model to correctly
resolve the paths. The device paths are not compatible with the path
used in the keyring. And the disks are annotated with the same
container role names used in the FDE state.
=> overlord/fdestate: re-factor listing of the disks

client/packages.go
this PR just fixes a typo in the json tags,
from:
```
`json:"links,omitempy"`
```
to:
```
`json:"links,omitempty"`
```
=> client: fix typo in json tags

overlord/confdbstate/confdbmgr.go, overlord/confdbstate/confdbmgr_test.go, overlord/confdbstate/confdbstate.go, overlord/confdbstate/confdbstate_test.go, overlord/confdbstate/export_test.go, overlord/hookstate/ctlcmd/export_test.go, overlord/hookstate/ctlcmd/fail.go, overlord/hookstate/ctlcmd/get.go, overlord/hookstate/ctlcmd/get_test.go
Adds a GetTransactionForSnapctlGet helper that returns a Transaction for `snapctl get` to read a confdb. If there are hooks to run, it schedules the right tasks and tracks the transaction. This is meant only for snapctl, the API will use a different helper since the circumstances there differ quite a bit.
Also changes the tracking of the transaction to distinguish between read and write transactions, since there can be many concurrent read transaction but not write. A follow-up PR will use that to check for conflicts earlier in the read/write.
=> o/confdbstate: add helper for snapctl confdb load

interfaces/builtin/hostname_control.go
Since https://github.com/systemd/systemd/pull/27573 we need to allow binding on the client side of the dbus socket.
Also hostnamectl seems to need to read properties on /org/freedesktop/systemd1 which should be fine.
To reproduce the issue, try to call `hostnamectl` from a snap on Ubuntu Core 24.
=> interfaces/builtin/hostname_control.go: fix call to hostnamectl in core24

sandbox/apparmor/notify/export_test.go, sandbox/apparmor/notify/listener/listener_test.go, sandbox/apparmor/notify/message.go, sandbox/apparmor/notify/message_test.go, sandbox/apparmor/notify/strings.go, sandbox/apparmor/notify/version.go, sandbox/apparmor/notify/version_test.go
This PR is based on #15130 and #15131.
Implement version 5 of the apparmor notification protocol, as defined here: https://docs.google.com/document/d/1_WvEM9Qi2Je2Vwulzv5TzHwLJ8ld0W8gTNESZZd9VsY/edit?tab=t.0#heading=h.q2d8zdyargyy
This work is tracked internally by https://warthogs.atlassian.net/browse/SNAPDENG-32517
=> s/a/notify: implement protocol v5 with metadata tagging parser

secboot/secboot_hooks.go
This was done in 041e705792b06f44d7d87b004fed17ab34d89f1f #15049
=> secboot/secboot_hooks.go: remove an implemented TODO

sandbox/apparmor/apparmor.go, sandbox/apparmor/apparmor_test.go
Use host libexecdir as identified at runtime, rather than a hardcoded value which is only correct on systems using /usr/lib/snapd.
Related: [SNAPDENG-34646](https://warthogs.atlassian.net/browse/SNAPDENG-34646)
Cherry picked from: #15201 
[SNAPDENG-34646]: https://warthogs.atlassian.net/browse/SNAPDENG-34646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> sandbox/apparmor: use correct host libexec dir rather than a hardcoded one

tests/main/snap-user-service-socket-activation/task.yaml
AppArmor is undergoing a flurry of activity, with dozens of new confinement profiles for previously unconfined applications. In Ubuntu 25.04 and newer, the nc program is now sandboxed and the sandbox does not allow cap_dac_override. As such the test running as root, no longer has the ability to traverse /home/test or /run/user/12345/ which ordinarily lack the o+x permission.
=> tests: fix snap-user-service-socket-activation with confined nc

packaging/ubuntu-16.04/control, packaging/ubuntu-16.04/rules
Dix deb build failures for plucky caused by missing pkg-config dependency udev that looks for package providing udev.pc
- In Xenial, Bionic, Focal and Jammy udev.pc used to be provided by package udev (systemd-dev is not available)
- In Noble onward package systemd-dev was introduced and provided udev.pc while udev was still available but no longer providing udev.pc (see http://archive.ubuntu.com/ubuntu/pool/main/s/systemd/)
Approach:
Changed build dependency so that at the point where systemd-dev replaced udev with providing udev.pc, udev >= 255 (noble, oracular, plucky), we require systemd-dev. 
Tests:
- Plucky |  https://launchpad.net/~ernestl/+archive/ubuntu/snapd2/+sourcepub/17064219/+listing-archive-extra
- Oracular | https://launchpad.net/~ernestl/+archive/ubuntu/snapd2/+sourcepub/1 …
=> packaging/ubuntu-16.04: install systemd-dev if pkg-config udev not satisfied

interfaces/builtin/opengl.go
> apparmor="DENIED" operation="file_receive" class="net" profile="snap.graphics-test-tools.glxinfo" pid=2801 comm="Xorg" family="unix" sock_type="stream" protocol=0 requested="send receive" denied="send receive" addr=none peer_addr=none peer="Xorg"
Since oracular Xorg has a new AppArmor profile, in complain mode.
The snap's AppArmor profile is now blocking communication on an unnamed stream
socket, breaking GLX on NVIDIA only.
`addr=none, peer_addr=none` is a socket_pair.
`file_receive` indicates one end of the pair is being passed over SCM rights.
The reason there was no denial or message previously, is that unconfined does
object delegation of open descriptors.
Object delegation is not currently available to confined applications (WIP),
so a rule is needed.
Fixes LP#2088456.
=> interfaces/opengl: Fix GLX on NVIDIA when Xorg is confined by AppArmor

dirs/dirs.go, snapdtool/tool_linux.go, snapdtool/tool_test.go
Two patches needed for supporting reexec when the host uses /usr/libexec/snapd instead of /usr/lib/snapd. This happens on Fedora/Amazon Linux and Tumbleweed.
Related: [SNAPDENG-34646](https://warthogs.atlassian.net/browse/SNAPDENG-34646)
Cherry picked from: #15201 
[SNAPDENG-34646]: https://warthogs.atlassian.net/browse/SNAPDENG-34646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> dirs, snapdtool: support reexec when using /usr/libexec/snapd on the host

overlord/confdbstate/confdbmgr.go, overlord/confdbstate/confdbstate.go, overlord/confdbstate/confdbstate_test.go, snap/hooktypes.go, tests/main/confdb-cross-config/task.yaml, tests/main/confdb-cross-config/test-custodian-snap/meta/hooks/observe-view-manage-wifi, tests/main/confdb-cross-config/test-snap/meta/hooks/observe-view-setup-wifi, tests/main/confdb/task.yaml, tests/main/confdb/test-custodian-snap/meta/hooks/observe-view-manage-wifi
The `<plug>-view-changed` needs to be renamed to `observe-view-<plug>` in the context of the clustering sprint so it matches the `observe-cluster-*` hooks.
=> many: rename view-changed confdb hook to observe-view

tests/main/snap-ns-forward-compat/task.yaml
`snap-ns-forward-compat` is failing on 25.04 due to unshare's apparmor profile.
https://warthogs.atlassian.net/browse/SNAPDENG-34643
=> tests: set apparmor to complain mode for unshare profile in snap-ns-forward-compat test

spread.yaml, tests/lib/pkgdb.sh
Add openSUSE to set of systems on which we run cross distro with snapd
reexec test suite.
Depends on #15197 
Related: [SNAPDENG-34646](https://warthogs.atlassian.net/browse/SNAPDENG-34646)
[SNAPDENG-34646]: https://warthogs.atlassian.net/browse/SNAPDENG-34646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> spread: enable cross distro reexec test suite on openSUSE

client/confdb.go, client/confdb_test.go, cmd/snap/cmd_get.go, cmd/snap/cmd_get_test.go, cmd/snap/cmd_set.go, cmd/snap/cmd_set_test.go, cmd/snap/cmd_unset_test.go, cmd/snap/cmd_watch.go, cmd/snap/wait.go, confdb/confdb.go, confdb/confdb_test.go, daemon/api.go, daemon/api_confdb.go, daemon/api_confdb_test.go, daemon/export_test.go, overlord/confdbstate/confdbmgr.go, overlord/confdbstate/confdbstate.go, overlord/confdbstate/confdbstate_test.go, overlord/hookstate/ctlcmd/get_test.go, overlord/hookstate/ctlcmd/set.go, overlord/hookstate/ctlcmd/unset_test.go, tests/main/confdb/task.yaml
Load ephemeral confdb data when reading from the API (for snap get). This requires making the read side of the API async, since it might be necessary to run hooks. The result in then transmitted through the change to the client. In case there are no custodian hooks to run, no tasks are run and the result is just directly placed into a "done" change.
This change turned out to be larger than I thought due to the API changes. The changes to the API are relatively simple but they required basically a re-write of the tests which blew up the diff. I can split the changes, if needed
=> many: make API confdb reads load ephemeral data

overlord/devicestate/devicestate.go, overlord/devicestate/devicestate_remodel_test.go, overlord/snapstate/snapstate_update_test.go, overlord/snapstate/snapstatetest/snapstate.go, snap/snaptest/snaptest.go
This will enable us to remodel back to a snap revision that was already installed in the past (somewhere in the sequence), assuming that the snap has all of the components that are needed already installed as well.
=> o/devicestate: allow remodeling back to an old snap revision that includes components

.github/workflows/naming.yml, .github/workflows/spread-tests.yaml, .github/workflows/static-checks.yaml
This is proposed solution to avoid a security issue in change-files action used in snapd workflows raised in https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/
=> tests: use sha commit instead of version tag in changed-files

.github/workflows/naming.yml
Use commit sha instead og version tag for woke-action-reviewdog as those tags could be insecure.
This need to be addressed too after the security issue raised with the changed-files action.
=> tests: use sha commit instead of version tag in woke-action-reviewdog

tests/main/snap-user-service-socket-activation/task.yaml
The intent was to remove the x permission in the "other" group, not for everyone.
=> tests: fix overeager chmod -x in restore

tests/lib/tools/simpleget
Some logs are very hard to read because of the progress reported by the simpleget tool.
The idea of this change is to make it quiet by default but with a new option to display progress.
=> tests: make simpleget tool quiet by default

tests/main/prepare-image-classic/task.yaml
This reverts commit d086b44163dc3c93df8dec914481f6ca9e559617.
The `prepare-image-classic` test is failing, blocking other PRs from being merged. It only runs on jammy, which is required.
It seems the warning added by that commit is no longer occurring, likely because the kernel has been updated. Is this warning likely to be resolved permanently for this test, or do we expect it to recur later? If the latter, perhaps we need a more dynamic check.
=> tests: revert account for snapd/kernel incompatibilty warning in prepare-image

overlord/ifacestate/apparmorprompting/export_test.go, overlord/ifacestate/apparmorprompting/prompting.go, sandbox/apparmor/notify/ioctl.go, sandbox/apparmor/notify/listener/export_test.go, sandbox/apparmor/notify/listener/listener.go, sandbox/apparmor/notify/listener/listener_test.go, sandbox/apparmor/notify/message.go, sandbox/apparmor/notify/message_test.go
No more `tomb`, no more waiting goroutines, no more atomics.
The listener run loop is now synchronous, and a `once.Do` ensures that it only runs once, and thus the `reqs` channel is only closed once.
The `Reply` method on `Request` now directly encodes and sends the response to the kernel. As a result, the `Request` struct now contains the ID of the message from which it was derived, a pointer to the listener, and the permission mask which was already allowed by existing AppArmor rules.
A close channel is used to signal to the main loop that the listener has been closed.
A `Mutex` guards the notify file, the epoll instance, and the close channel, ensuring that the listener run loop and any replies cannot race, and that there are no races around checking whether the listener has been …
=> s/a/notify: simplify the listener

tests/main/aux-info/task.yaml, tests/main/interfaces-posix-mq/task.yaml
The change includes:
. use a different channel for snap-store snap  (to make sure it is available in all the architectures)
. skip arm devices too in interfaces-posix-mq for core-18 and core-20
. remove ubuntu-core-16 from interfaces-posix-mq as it is not supported anymore
=> tests: fixes in after beta validation 2.68.3

overlord/confdbstate/confdbstate.go, overlord/confdbstate/confdbstate_test.go, overlord/hookstate/ctlcmd/export_test.go, overlord/hookstate/ctlcmd/get.go, overlord/hookstate/ctlcmd/get_test.go, overlord/hookstate/ctlcmd/set.go, overlord/hookstate/ctlcmd/set_test.go, overlord/hookstate/ctlcmd/unset_test.go
Use the previously added helpers to load ephemeral data in `snapctl get`. Since we no longer use the general confdbstate.Get/Set functions that directly accessed the databags, these are also removed and any tests using them are changed to use the new way of accessing confdb.
=> o/h/ctlcmd: snapctl get loads ephemeral data

tests/main/interfaces-timeserver-control/task.yaml
It appears ntp is no longer available, which is causing the apt install to fail.
=> tests: remove ntp removal and install in tests/main/interfaces-timeserver-control

interfaces/builtin/audio_playback_test.go, interfaces/builtin/pipewire_test.go
Some AppArmor tests for Classic snaps where put inside the SecComp test function for Classic. This PR moves them into the right AppArmor test function.
=> tests: Move AppArmor checks outside SecComp test functions

.github/workflows/static-checks.yaml, .github/workflows/unit-tests-cross-distro.yaml, cmd/Makefile.am, packaging/arch/PKGBUILD, run-checks, tests/unit/go/task.yaml
Proposing changes to run-check with the goal of boosting verbosity around what is run/skipped and early warning when tool dependency is missing that will, perhaps unexpectedly, cause lower coverage.
**Overview:**
- format run-checks with shfmt
- add C format check based on clang-format
- install required packages that is now flagged as missing on fedora and opensuse
- remove independent step for similar check in static-checks.yaml (now covered by previous step "run checks --static")
- re-enabled build tree dirty check (TODO with conditions met)
- add tool dependency precheck, that will fail on missing dependency if not instructed otherwise
- ability to IGNORE_MISSING (default=0): override default behavior to error on missing dependency (for development)
- ability to AUTO_INSTALL …
=> run-checks, cmd: multiple run-check improvements

build-aux/snap/snapcraft.yaml
That saves 1MB on the snapd snap after compression.
=> snapcraft.yaml: build snap-bootstrap with nomanagers

cmd/configure.ac, packaging/debian-sid/control, packaging/fedora/snapd.spec, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/control, packaging/ubuntu-16.04/control
Drop explicilt check for udev pkg-config module. What we really ever need at this level is libudev.
Based on the discussion around #15210 
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-34666
=> cmd: drop explicit check for udev pkg-config module, update build dependencies

sandbox/apparmor/notify/ioctl.go, sandbox/apparmor/notify/ioctl_test.go, sandbox/apparmor/notify/listener/listener.go, sandbox/apparmor/notify/listener/listener_test.go
This is a follow-up to f04f00b2bb78b8f04f468b2a5765927d73136c9a (#15089) which fixes a place where the protocol version was erroneously left hard-coded.
=> s/a/notify: properly set protocol version in ioctl request buffer

tests/lib/assertions/developer1-network-ephemeral-confdb.json, tests/lib/assertions/network-ephemeral.confdb, tests/main/confdb-cross-config/eph-schema.json, tests/main/confdb-cross-config/loading-custodian/bin/sh, tests/main/confdb-cross-config/loading-custodian/meta/hooks/change-view-manage-wifi, tests/main/confdb-cross-config/loading-custodian/meta/hooks/load-view-manage-wifi, tests/main/confdb-cross-config/loading-custodian/meta/hooks/query-view-manage-wifi, tests/main/confdb-cross-config/loading-custodian/meta/hooks/save-view-manage-wifi, tests/main/confdb-cross-config/loading-custodian/meta/snap.yaml, tests/main/confdb-cross-config/task.yaml
Adds checks to the confdb-cross-config test to check that custodians can save and load ephemeral data.
~~Based on https://github.com/canonical/snapd/pull/15228 so only commit [3414c29](https://github.com/canonical/snapd/pull/15245/commits/3414c2940f587dc330b140daf98c05356c34ddc4) is relevant to this PR~~
=> tests: test ephemeral data loading

client/client_test.go
The test was failing due to a different timeout message thane expected. This relaxes the check a little bit to succeed on different timeout messages
```
client_test.go:684:
c.Assert(err, ErrorMatches, `.* timeout exceeded while waiting for response`)
... error string = "cannot communicate with server: Post \"http://127.0.0.1:34801\": dial tcp 127.0.0.1:34801: i/o timeout"
... regex string = ".* timeout exceeded while waiting for response"
```
=> client: relax timeout err check

cmd/snap-confine/snap-confine.c
The following error was observed when building for armhf:
```
snap-confine/snap-confine.c: In function ‘log_startup_stage’: snap-confine/snap-confine.c:280:60: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘__time64_t’ {aka ‘long long int’} [-Werror=format=]
280 |     debug("-- snap startup {\"stage\":\"%s\", \"time\":\"%lu.%06lu\"}", stage, tv.tv_sec, tv.tv_usec);
|                                                          ~~^                   ~~~~~~~~~
|                                                            |                     |
|                                                            long unsigned int     __time64_t {aka long long int}
|                                                          %llu …
```
=> cmd/snap-confine: workaround time_t size differences between architectures

snapdtool/tool_linux.go, snapdtool/tool_test.go
Snap re-execution looked confusing since it did not update `cmdline` in `/proc`. That means `ps`, `top`, `systemd-cgls` showed `/usr/lib/snapd/snapd` as running when the binary comes from the snap.
=> snapdtool: update command line when re-executing

cmd/snap-confine/snap-confine.apparmor.in
Add all known glibc HWCAPS subdirectories to the list of runtime library paths to fix application launch errors like the following:
```
/usr/lib/snapd/snap-confine: error while loading shared libraries: libc.so.6: failed to map segment from shared object
```
As with my 11th Generation Intel laptop, `libc.so.6` matches to:
```
$ ldd /snap/bin/mari0
linux-vdso.so.1 (0x00007fe51b817000)
libc.so.6 => /usr/lib/glibc-hwcaps/x86-64-v4/libc.so.6 (0x00007fe51a038000)
/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fe51b819000)
```
There are the following known glibc HWCAPS subdirectories:
- /usr/lib/glibc-hwcaps/x86-64-v2
- /usr/lib/glibc-hwcaps/x86-64-v3
- /usr/lib/glibc-hwcaps/x86-64-v4
- /usr/lib/glibc-hwcaps/power9
- /usr/lib/glibc-hwcaps/power10
- …
=> cmd/snap-confine: handle glibc HWCAPS subdirs

cmd/snap/cmd_run.go, interfaces/system_key.go, interfaces/system_key_test.go, overlord/ifacestate/helpers.go
Since we will need to transfer the system key from snap client to snapd, return generated system key when a mismatch is detected.
=> interfaces/system_key, many: return generated system key on mismatch

tests/lib/assertions/developer1-24-classic-dangerous.json, tests/lib/assertions/developer1-24-classic-dangerous.model, tests/lib/prepare.sh, tests/lib/tools/build_kernel_with_comps.sh, tests/nested/manual/core-factory-reset-new-secboot/task.yaml, tests/nested/manual/core20-fault-inject-on-install-component/task.yaml, tests/nested/manual/hybrid-fde-dbx/task.yaml, tests/nested/manual/muinstaller-core/task.yaml, tests/nested/manual/muinstaller/task.yaml, tests/nested/manual/split-refresh/task.yaml, tests/nested/manual/update-snapd-seed-and-factory-reset/task.yaml
That fixes some of the nested tests failures.
=> tests/lib/tools/build_kernel_with_comps.sh: fix failure when lib already exists

tests/main/document-interfaces-url/task.yaml
Fixed document-interfaces-url check issue that is now showing in tests [during testing](https://github.com/canonical/snapd/actions/runs/14208273236/job/39810952635?pr=15276) because of expired exclusion date. Also moved forward dates for others that will expire soon.
=> tests/main/document-interfaces-url: updated expiration dates and removed nomad-support

kernel/kernel_drivers.go, kernel/kernel_drivers_test.go, overlord/snapstate/snapstate_test.go
Models in in classic 24.04/24.10 are base core22 while should have been core24. We check the model base to know if we need a drivers tree or not. Special-case these models so the kernel can be safely refreshed, workarounding LP#2104933.
=> kernel: workaround for wrong model base in 24.04/24.10

asserts/confdb.go, asserts/confdb_test.go, daemon/api.go, daemon/api_confdb.go, daemon/api_confdb_test.go, daemon/export_test.go, overlord/devicestate/devicemgr.go, overlord/devicestate/devicestate_test.go
This PR adds the confdb-control API as specified in SD186.
I've removed the mandatory requirement for `groups` since it's possible to have a confdb-control assertion without any delegations. Previously, it would raise an error:
```console
$ sudo curl --unix-socket /run/snapd.socket -X POST \
-d '{"action": "delegate", "operator-id": "alice", "views": ["canonical/confdb/view", "canonical/another/view"], "authentications": ["operator-key"]}' \
"http://localhost/v2/confdb"
{"type":"sync","status-code":200,"status":"OK","result":null}
$ snap known confdb-control
type: confdb-control
brand-id: generic
model: generic-classic
serial: <serial>
groups:
-
authentications:
- operator-key
operators:
- alice
views:
- canonical/another/view
- canonical/confdb/view
sign-key-sha3-384: …
```
=> daemon,o/devicestate,asserts: add confdb-control api

packaging/ubuntu-16.04/control
`<` is not a valid operator and needs to be replaced with `<<`
Inspired by [LP#2106009](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/2106009), but does not solve the issue directly for 2.68.3 SRU review, so this PR should not be linked to the SF ticket.
Went back my [test build](https://launchpadlibrarian.net/782343129/buildlog_ubuntu-plucky-amd64.snapd_2.68.3+ubuntu25.04.2_BUILDING.txt.gz), and noticed a similar warning in build log as well: 
`dpkg-source: warning: relation < is deprecated: use << or <=`
IMPORTANT: Need to be cherry-picked for 2.68.4 and 2.69
=> debian/control: replace invalid operator

overlord/confdbstate/transaction.go, overlord/confdbstate/transaction_test.go, overlord/hookstate/ctlcmd/get.go, overlord/hookstate/ctlcmd/get_test.go
In order to make --pristine consistent with the features required for clustering, we need to rework into a --previous. This isn't semantically the same since --pristine ignored uncommitted changes but --previous ignores all of the transaction's changes (even committed) so the behaviour in `observe-view-<plug>` hooks will differ.
=> o/confdbstate: rework --pristine into --previous

overlord/ifacestate/helpers.go
Refactor regenerateAllSecurityProfiles() to collect and cache all security options.
Cherry-picked: #15254 
=> overlord/ifacestate/helpers: refactor regeneration of all security profiles

interfaces/system_key.go, interfaces/system_key_test.go
A helper implementing a policy for dealing with system key mismatch.
Cherry picked from: #15254 
=> interfaces/system_key: system key mismatch policy

cmd/snap/cmd_validate.go, cmd/snap/cmd_validate_test.go
Fix `snap validate <specific validation set>` output missing a newline.
Further considerations:
- Should we implement suggested exit with error when invalid?
- Why do we provide less information when inspecting specific validation set VS if there is only a single validation set?
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-34714?focusedCommentId=717454
=> cmd/snap: fix snap validate missing newline

cmd/snap/cmd_validate.go, cmd/snap/cmd_validate_test.go
Fix snap validate --refresh <specific validation set> outputs valid/invalid state instead of error
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-34714?focusedCommentId=717365
Builds on: https://github.com/canonical/snapd/pull/15288
=> cmd/snap: fix snap validate refresh without enforce

sandbox/apparmor/notify/message.go
This fixes a bug introduced in f04f00b2bb78b8f04f468b2a5765927d73136c9a from #15089.
That bug the potential to break `"lifespan": "single"` since the kernel would cache the response at the profile level.
=> s/a/notify: fix URESPONSE_NO_CACHE flag which should be 1

go.mod, go.sum, secboot/secboot_sb.go, secboot/secboot_tpm.go
See https://github.com/canonical/snapd/pull/15226 and https://github.com/canonical/secboot/pull/390
LP#2102456
~~IMPORTANT: This is dependent on https://github.com/canonical/snapd/pull/15226~~ Not really. Just not much point without it.
=> secboot: use new auth requestor without text/template

tests/main/remote-home/task.yaml
Update the test to run on 20.04, as it's still fully supported. While at it, install linux-modules (which carries cifs.ko/nfs.ko), and not linux-modules-extra and stop skipping the test.
=> tests/main/remote-home: enable 20.04, require linux-modules, no skipping

overlord/fdestate/backend/export_test.go, overlord/fdestate/backend/reseal.go, overlord/fdestate/backend/reseal_test.go, overlord/managers_test.go, secboot/secboot.go, secboot/secboot_dummy.go, secboot/secboot_hooks.go, secboot/secboot_sb.go, secboot/secboot_sb_test.go, secboot/secboot_tpm.go
We now stop reading primary key files for FDE hooks and TPM. And instead we get them in the keyring. We still try to read the file on reseal if the primary key was not found in the keyring.
=> secboot, overlord/fdestate/backend: use primary key from keyring

daemon/api_base_test.go, overlord/devicestate/firstboot20_test.go, overlord/devicestate/firstboot_test.go
=> daemon: fake fde state in tests to avoid warnings initializing it

tests/nested/manual/muinstaller-core/task.yaml, tests/nested/manual/muinstaller-real/task.yaml, tests/nested/manual/muinstaller/task.yaml, tests/nested/manual/passphrase-support-on-hybrid/task.yaml, tests/nested/manual/split-refresh/task.yaml
Most hybrid tests take a lot of extra space in the test folder, clean up things to avoid failures due to lack of space when doing full runs of the test suite.
=> tests/nested/manual: free some space in restore stanza

daemon/api.go, daemon/api_test.go, daemon/daemon.go
This is the first piece of avoiding taking state lock within `Command.ServeHTTP()`.
This work is tracked internally by https://warthogs.atlassian.net/browse/SNAPDENG-34635
=> daemon: avoid locking state until necessary in userFromRequest

cmd/snap-bootstrap/cmd_initramfs_mounts.go, cmd/snap-bootstrap/cmd_initramfs_mounts_classic_test.go, cmd/snap-bootstrap/cmd_initramfs_mounts_test.go, tests/lib/assertions/developer1-22-kernel-24-classic-dangerous.json, tests/nested/manual/muinstaller-oldbasenewkernel/task.yaml
In case we do not have a drivers tree on 24+, mount /lib/{modules,firmware} from the kernel snap as a fallback. This should not really happen and we do not support fully this scenario, but there are cases where this might be necessary, like if somebody uses a core22 model but install a 24+ kernel.
=> cmd/snap-bootstrap: mount /lib/{modules,firmware} from snap as fallback

tests/lib/prepare-restore.sh, tests/lib/prepare.sh, tests/lib/tools/tests.invariant
This change introduces 2 improvements while preparing each task:
1. Reduces the invariant check check_stray_dbus_daemon from 5 seconds to 1 (https://pastebin.canonical.com/p/mT5m6qqDwj/)
2. Moves the removal of lxd-installer to the suite preparation, which takes almost 2 seconds (https://pastebin.canonical.com/p/qfkT6hvcmp/)
=> tests: speed up the prepare-each phase

interfaces/apparmor/backend.go, interfaces/apparmor/backend_test.go, interfaces/backend.go, interfaces/ifacetest/backend.go
Add support for reinitialization in AppArmor security backend.
Cherry picked from #15254
=> interfaces/apparmor: make AppArmor backend reinitializable

.github/workflows/nightly-spread.yaml, .github/workflows/spread-tests.yaml
This change is needed to run nigthly jobs using the snapd deb build from the master branch but without re-exec. The idea is to test the snapd deb.
Also it is removed the spread-snapd-deb-from-repo because now we can pass it as spread-env
=> tests: update the nightly workflows to run with no-reexec

.github/workflows/state-locks.yaml
This workflow runs snapd tests and check there is not new state lock traces comparing with the baseline.
The workflow builds snapd with testkeys to allow state locks are generated, and the run the main and core test suites to obtain the locks generated (using a threshold of 1000 ms).
Once the artifacts are generated and retrieved, the lock files are compiled into a single log and the traces are compared against the baseline.
If new traces are found in the logs, the workflow will print the diff and fail.
State lock logs are always uploaded as an artifact.
=> tests: new workflow to check state locks against the baseline

.github/workflows/state-locks.yaml
Simple fix for state-locks workflow
=> tests: fix how state_locks_baseline.traces is downloaded in state-locks.yaml

sandbox/apparmor/notify/export_test.go, sandbox/apparmor/notify/ioctl.go, sandbox/apparmor/notify/ioctl_test.go, sandbox/apparmor/notify/message.go, sandbox/apparmor/notify/message_test.go, sandbox/apparmor/notify/notify.go, sandbox/apparmor/notify/strings.go
Avoid repeatedly calling `arch.Endian()` whenever data needs to be de/serialized. A computer's endianness can't change while snapd is running.
This is cherry-picked from #15237 to reduce the changes required there, since this mostly touches existing code.
=> s/a/notify: use variable for native byte order instead of rechecking

overlord/fdestate/dbx.go, overlord/fdestate/dbx_test.go, tests/nested/manual/core20-nofde-dbx/task.yaml
Make sure that dbx operations are a NOP when there are no FDE keys.
Fixes an issue reported for fwupd in
https://github.com/fwupd/fwupd/issues/8684
=> overlord/fdestate/dbx: do nothing for dbx when there are no encryption keys

overlord/ifacestate/handlers.go, overlord/ifacestate/helpers.go, overlord/ifacestate/ifacemgr.go, overlord/ifacestate/ifacestate.go, overlord/ifacestate/ifacestate_test.go
Handle reported system key mismatch by launching a change to
regenerate all security profiles if needed.
Add a handler for regenerating security profiles, which reinitializes the security backends and recomputes the profiles.
Cherry picked from #15254
=> o/ifacestate, interfaces: system key mismatch handling

interfaces/core.go, interfaces/ifacetest/testiface.go, interfaces/symlinks/backend.go, interfaces/symlinks/backend_test.go, interfaces/symlinks/spec.go, interfaces/symlinks/spec_test.go, testutil/filepresencechecker.go, testutil/filepresencechecker_test.go
The symlinks backend maintains symlinks in the rootfs that points inside $SNAP or $SNAP_DATA. It will be useful for interfaces that allow exporting files from a snap to a classic rootfs or, eventually, to the mount namespace of a snap.
=> interfaces: add symlinks backend

overlord/ifacestate/apparmorprompting/prompting.go, overlord/ifacestate/apparmorprompting/prompting_test.go
Don't set backends to `nil` when the manager closes. In doing so, we don't need to check for `nil` backends elsewhere, since the backends are never `nil`.
After acquiring the interfaces requests manager lock, check that the backend which is about to be accessed is not nil, which could be the case if the manager has been stopped.
This is cherry-picked from https://github.com/canonical/snapd/pull/15237 to reduce the changes required there, since this mostly touches existing code.
=> o/i/apparmorprompting: do not set backends to nil when closed

cmd/snap/cmd_prepare_image.go, cmd/snap/cmd_prepare_image_test.go, image/image_linux.go, image/image_test.go, image/options.go, seed/seedwriter/fetcher.go, seed/seedwriter/fetcher_test.go, seed/seedwriter/seed16.go, seed/seedwriter/seed20.go, seed/seedwriter/writer.go, seed/seedwriter/writer_test.go
image: added feature to inject proxy store assertions in build image
This PR adds the possibility of including extra assertions in the created image at build time.
The reason for this is avoiding workarounds such as stopping the build, including proxy store assertions and resuming the build.
The solution adds the necessary fields to `image.Options` and the necessary control flow so that assertions contained in files passed with the `--assert` option (and in the future in the calls from `ubuntu-image`) will be imported and saved to the seed.
For now, only store assertions are allowed as I couldn't see a way to have a truly polymorphic approach to decoding each kind of assertion, resulting in the code found [here](https://github.com/lorenzo-medici/snapd/blob/1d3f1ca8cadc282e1d529e9020aaa9c40 …
=> image: added feature to inject proxy store assertions in build image

tests/lib/tools/cleanup-state, tests/main/security-device-cgroups-required-or-optional/task.yaml, tests/smoke/install/task.yaml
`security-device-cgroups-required-or-optional` was failing due to leftover cgroup pinned map files. This adds removing those leftover files.
=> tests: add cleanup of cgroup pinned maps

cmd/snap-bootstrap/triggerwatch/export_test.go, cmd/snap-bootstrap/triggerwatch/triggerwatch.go, cmd/snap-bootstrap/triggerwatch/triggerwatch_test.go, timeutil/timer.go, timeutil/timer_test.go
Avoid blocking unit tests through time.Sleep() and use timeutil/testutil.MockTimer() to simulate passing time.
Fix mocking of timeAfter so that go test -count=n, with n>1 works. As drive by fixes, update the mocking to use testutil.Mock.
=> cmd/snap-bootstrap/triggerwatch: simulate passing time, better event sychronization

.github/workflows/test.yaml, build-aux/snap/snapcraft.yaml, cmd/snap-failure/main.go, cmd/snap-fde-keymgr/main.go, cmd/snap-recovery-chooser/main.go, cmd/snap-repair/main.go, cmd/snap/main.go, cmd/snapd-apparmor/main.go, cmd/snapd/main.go, logger/logger.go, logger/logger_test.go, logger/simple_logger.go, logger/structured_logger.go, logger/structured_logger_test.go, overlord/configstate/configcore/debug.go, overlord/configstate/configcore/debug_test.go, overlord/configstate/configcore/export_test.go, tests/lib/fakestore/cmd/fakestore/main.go, tests/lib/uc20-create-partitions/main.go
This adds a new trace method for logging as well as `slog`'s json logger for builds with the `structuredlogger` tag. The json logging will only be used if the `SNAPD_USE_JSON_LOGGING` environment variable is set. The trace logging will only happen when `SNAPD_TRACE` is activated and only when the `structuredlogger` build tag is present.
Note: `slog` uses log levels inside its higher-order logging functions to determine what actually gets logged (e.g. if the level is set a debug, then it logs debug, info, and error). Properly showing the correct source file in the log entry required directly creating a record, which bypasses the level-checking mechanism. Rather than include those checks, I opted to simplify and use the same method already present in the other logger.
=> github, build-aux, logger: add structured logger with build tag and new trace logger method

core-initrd/latest/bin/ubuntu-core-initramfs
Copy the initramfs manifest file to the same directory where the initramfs file is created, so it can be copied to the kernel snap and read without extracting the initramfs from the UKI. The name is this file is "manifest-initramfs.yaml".
=> core-initrd/ubuntu-core-initramfs: copy initramfs package to output folder

spread.yaml
This change is needed to avoid issues in spread selecting ubuntu images. 
Spread could get arm images instead of the x86 ones.
=> tests: add image names for ubuntu 2*

packaging/fedora/snapd.spec, spread.yaml
Enable Amazon Linux 2 as a target for cross distro reexec smoke suite.
Related: [SNAPDENG-34925](https://warthogs.atlassian.net/browse/SNAPDENG-34925)
[SNAPDENG-34925]: https://warthogs.atlassian.net/browse/SNAPDENG-34925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> spread: enable cross distro reexec suite on Amazon Linux 2

daemon/api_notices.go, daemon/daemon.go, daemon/daemon_test.go
We still want to wait for most requests when shutting down/restarting snapd except for notices which are long polling up to a timeout chosen by the clients.
Related: [SNAPDENG-34668](https://warthogs.atlassian.net/browse/SNAPDENG-34668) https://bugs.launchpad.net/snapd/+bug/2104066
[SNAPDENG-34668]: https://warthogs.atlassian.net/browse/SNAPDENG-34668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> daemon: only cancel notices requests on Stop/shutdown

daemon/api_general.go, daemon/daemon.go, overlord/ifacestate/ifacestate_test.go, overlord/state/state.go, overlord/state/state_test.go, overlord/state/warning.go, overlord/state/warning_test.go
Add a `RWMutex` to guard the state warnings map, and no longer require the state lock to be held just to read warnings.
This means that callers of `state.AllWarnings`, `state.PendingWarnings`, and `state.WarningsSummary` no longer need to hold the state lock .
Those callers include `daemon` and tests within `o/ifacestate`.
Some other callers still require state lock for other reasons, so these are left unchanged.
This work is tracked internally by https://warthogs.atlassian.net/browse/SNAPDENG-34635
=> daemon,o/state: don't require state lock just to get warnings

client/errors.go, daemon/api_base_test.go, daemon/api_general.go, daemon/api_general_test.go, daemon/errors.go
Add support for POST to /v2/system-info with system-key-mismatch
indication from the client.
Cherry picked from https://github.com/canonical/snapd/pull/15254
=> daemon: /v2/system-info system key mismatch support

interfaces/builtin/timeserver_control.go, interfaces/builtin/timeserver_control_test.go, tests/lib/snaps/test-snapd-timedate-control-consumer-core20/bin/date, tests/lib/snaps/test-snapd-timedate-control-consumer-core20/bin/hwclock, tests/lib/snaps/test-snapd-timedate-control-consumer-core20/bin/sh, tests/lib/snaps/test-snapd-timedate-control-consumer-core20/bin/timedatectl, tests/lib/snaps/test-snapd-timedate-control-consumer-core20/meta/snap.yaml, tests/lib/tools/snaps-state, tests/main/interfaces-timeserver-control/task.yaml
Extend timeserver-control interface to allow timedatectl timesync commands.
Requires:
- apparmor: ability to get all /org/freedesktop/timesync1 properties
- apparmor: ability to bind to @*/bus/timedatectl.rea/system unix sockets (timedatectl wraps timedatectl.real)
- seccomp: bind
Testing:
Modified existing `tests/main/interfaces-timeserver-control/task.yaml`, allowing the test for any system with systemd-timesyncd enabled, and checking to ensure we cover at least core20+.
Manually tested on classic systems as well, but adding it to spread is arguably not worth it, due to the need to replace chronyd which also requires a significant wait time for org.freedesktop.timedate1 CanNTP to become true, and also introduce conflicts with automatic package remove logic that does not seem to account …
=> interfaces/builtin: extend timeserver-control interface to allow timedatectl timesync commands

daemon/daemon.go, daemon/daemon_test.go, overlord/restart/restart.go, overlord/restart/restart_test.go
~~This PR is based on #15309~~
In places such as the daemon, we acquire state lock just to check whether a restart is pending. This increases state lock contention and slows down API replies.
Thus, make the restart value atomic, allowing it to be checked via a method on the `RestartManager` without needing to lock snapd state.
This is an adaptation of a similar change from pebble:
https://github.com/canonical/pebble/pull/451
Because many other places do not have a reference to an overlord from which they call `RestartManager()` to get access to the manager, we also preserve the existing `restart.Pending()` function, which differs from the change in pebble.
Snapd is still on go 1.18, so we cannot yet use `atomic.Int32` as pebble does. Instead, we use `atomic.{Load,Store,Swap}` on an …
=> daemon,o/restart: add method to check pending restart without state lock

overlord/hookstate/ctlcmd/mount.go, overlord/hookstate/ctlcmd/mount_test.go, systemd/systemd.go, systemd/systemd_test.go, tests/lib/nested.sh, tests/nested/core/remount-hotplug/mount-usb-drive/bin/mnt_check, tests/nested/core/remount-hotplug/mount-usb-drive/meta/snap.yaml, tests/nested/core/remount-hotplug/task.yaml
Run "systemtctl start" for mount units in case we have not modified them, with
the intention of making sure they are actually running. Fixes LP#2102189.
=> systemd,overlord: run systemtclt start if mount unit is unchanged

cmd/snap/cmd_run.go, cmd/snap/cmd_run_test.go, cmd/snap/export_test.go, cmd/snap/main.go, cmd/snap/wait.go, tests/main/remote-home/task.yaml
React to system key mismatch by pinging snapd for advice on how to
proceed and optionally wait for a pending security profiles regeneration
change.
Cherry picked from https://github.com/canonical/snapd/pull/15254
Exact same thing as https://github.com/canonical/snapd/pull/15332 but I had to reopen the PR.
=> cmd/snap, tests/main: react to system key mismatch 

asserts/asserts.go, asserts/confdb.go, confdb/confdb.go, confdb/confdb_test.go, confdb/schema.go, confdb/schema_test.go, overlord/confdbstate/transaction_test.go
Adds a NestedEphemeral() method to the schema types which should return true if the type or any of its nested types is ephemeral. It differs from Ephemeral() in that the latter is only true if the type itself was marked as ephemeral.
=> confdb: add NestedEphemeral to confdb schemas

.github/workflows/nested-systems.json
The rules cannot be used for nested arm because when the "Run Nested" label is added, then all the "tasks" are executed and the rules are not followed. 
So until nested tests are prepared to run on arm, the rules cannot be used.
=> tests: update nested tests executed for arm64

tests/nested/manual/kernel-modules-components/task.yaml
as otherwise we might get random failures due to installing while the a change for the same snap is in progress.
=> tests/kernel-modules-components: wait properly for snap installation

boot/initramfs.go
We are trying to get rid of /sbin in favor for /usr/sbin in core-initrd.
Also we should call directly systemctl which should always be in PATH.
=> boot/initrafms.go: use systemctl reboot instead of /sbin/reboot

interfaces/builtin/common.go, interfaces/builtin/docker_support.go, interfaces/builtin/docker_support_test.go, interfaces/builtin/gpio_chardev.go, interfaces/builtin/gpio_chardev_test.go, interfaces/builtin/greengrass_support.go, interfaces/builtin/greengrass_support_test.go, interfaces/builtin/kubernetes_support.go, interfaces/builtin/kubernetes_support_test.go, interfaces/builtin/lxd_support.go, interfaces/builtin/lxd_support_test.go, interfaces/builtin/microstack_support.go, interfaces/builtin/microstack_support_test.go, interfaces/builtin/nomad_support.go, interfaces/builtin/nomad_support_test.go, interfaces/core.go, interfaces/core_test.go, wrappers/internal/service_unit_gen.go, wrappers/internal/service_unit_gen_test.go, wrappers/services_test.go
This PR extends plug service snippets to allow specifying target section as originally it implicitly injected the snippets into the `[Serivce]` section. Using the new mechanism, it injects a Wants/After relation into consumer services that reference a plug of gpio-chardev so that they are ordered after gpio setup is completed.
=> interfaces: inject dependency into snap services that have a gpio-chardev plug

cmd/snap-update-ns/change_test.go, cmd/snap-update-ns/update_test.go
Some tests used "x-snapd.overname" option without making it clear this is an "rbind". Adjust them to add "rbind" to mount options so that upcoming logic does not need special-cases for test-only flaws.
=> cmd/snap-update-ns: overname entries are always rbind

spread.yaml
Enable reexec test suite on CentOS and Amazon Linux 2023
Related: [SNAPDENG-34263](https://warthogs.atlassian.net/browse/SNAPDENG-34263)
[SNAPDENG-34263]: https://warthogs.atlassian.net/browse/SNAPDENG-34263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> spread: enable reexec test suite on remaining distros

cmd/snap-update-ns/change_test.go
Some tests used "x-snapd.synthetic" option without making it clear this is an "rbind" (for directories), or a "tmpfs". Adjust them to add the appropriate option or type so that upcoming logic does not need special-cases for test-only flaws.
=> cmd/snap-update-ns: synthetic is always tmpfs, or bind or rbind

confdb/confdb.go, confdb/confdb_test.go, overlord/confdbstate/confdbstate.go, overlord/confdbstate/confdbstate_test.go, overlord/hookstate/ctlcmd/export_test.go, overlord/hookstate/ctlcmd/get.go, overlord/hookstate/ctlcmd/get_test.go
Make save-view/load-view hooks mandatory only if the operation might affect ephemeral data. If the path traverses or is a parent of a subpath with ephemeral data, then the save/load hooks must be defined. Based on https://github.com/canonical/snapd/pull/15349
=> many: make save/load hooks mandatory if affecting ephemeral

interfaces/prompting/prompting.go, interfaces/prompting/requestprompts/requestprompts.go, interfaces/prompting/requestprompts/requestprompts_test.go, overlord/ifacestate/apparmorprompting/prompting.go, overlord/ifacestate/apparmorprompting/prompting_test.go
The desktop client needs to know the request PID so that it can determine which window to attach the prompt dialog to.
The listener request already includes a `PID` field, so all we need to do is add a `PID` field to `requestprompts.Prompt` as well, and wire it up to be populated by the request PID.
A different PID should be enough to cause to otherwise identical prompts to be treated as distinct, so that the client can get a prompt for every separate process which happens to cause the same request within the same snap. This avoids a situation where a headless process causes a request, then a non-headless process in the same snap causes the same request, but the client doesn't get the second PID and so can't attach the prompt to the latter's window. In practice, situations like this …
=> many: include request PID in prompt

cmd/snap-update-ns/change_test.go
Many tests only provided the mount point, without clarifying the file system type or bind-mount options, relying on loose semantics of the current codebase. Adjust them to use "tmpfs" so that upcoming logic does not need special-cases for test-only flaws.
In some tests the type "tmpfs" disagrees with common sense device name "/dev/sda1", but this is harmless and snapd does not support mounting actual devices this way.
In the test TestNeededChangesMountOrder more creative filling-the-blanks was exercised to make the data valid.
Crucially no resulting Change has different order or action than before.
=> cmd/snap-update-ns: provide more realistic test data

sandbox/apparmor/notify/ioctl.go, sandbox/apparmor/notify/ioctl_test.go, sandbox/apparmor/notify/listener/listener_test.go, sandbox/apparmor/notify/message.go, sandbox/apparmor/notify/message_test.go
These changes are cherry-picked from #15237
In order to support snapd reclaiming outstanding notifications after it restarts, we need to register the listener ID with the kernel and re-register it after a restart. Then, we send a request to re-send outstanding messages.
This commit adds the ioctl register and resend commands and defines the structs used for those commands.
This work is tracked internally by https://warthogs.atlassian.net/browse/SNAPDENG-34637
=> s/a/notify: add structs/commands for v5 listener registration

cmd/snap/cmd_debug_lsm.go, sandbox/lsm/lsm.go, sandbox/lsm/lsm_darwin.go, sandbox/lsm/lsm_linux.go, sandbox/lsm/lsm_test.go, tests/main/lsm/task.yaml
Helpers and internal tool for introspecting LSM state.
24.04 VM:
```
root@u1:~# snap debug lsm
found 5 active LSMs
- ( 108) lockdown
- ( 100) capability
- ( 110) landlock
- ( 105) yama
- ( 104) apparmor
context entries: 1
current apparmor LSM context: unconfined
```
24.04 container and a nested container:
```
root@c1:~# snap debug lsm
found 5 active LSMs
- ( 108) lockdown
- ( 100) capability
- ( 110) landlock
- ( 105) yama
- ( 104) apparmor
context entries: 1
current apparmor LSM context: unconfined
root@c1:~# lxc exec -t nestedc1 /root/snap debug lsm
found 5 active LSMs
- ( 108) lockdown
- ( 100) capability
- ( 110) landlock
- ( 105) yama
- ( 104) apparmor
context entries: 1
current apparmor LSM context: lxd-nestedc1_</var/snap/lxd/common/lxd> (enforce)
```
Arch booted with with …
=> sandbox/lsm: helpers for introspecting LSM state

packaging/arch/PKGBUILD, tests/lib/prepare-restore.sh
The PKGBUILD file was originally based on one for snapd-git AUR package.
However, since then snapd-git became defunct, at the same time all of
the downstream packaging is done in the snapd AUR package.
The patch syncs the packaging so that it's almost identical, with a
small exception of the header and lack of patches.
With the PKGBUILD more in line with how 
the actual downstream packaging looks like, we can further  simplify
packing of source tarballs, i.e. reuse pack-source script and drop the
custom sed/awk processing.
Related: [SNAPDENG-34616](https://warthogs.atlassian.net/browse/SNAPDENG-34616)
[SNAPDENG-34616]: https://warthogs.atlassian.net/browse/SNAPDENG-34616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> packaging/arch, tests/lib/prepare-restore: simplify PKGBUILD, simplify building of Arch package in CI

cmd/snapd/main_test.go
Snapd is still running and can be logging while the test is checking logger buffer content.
Related race when running with SNAPD_DEBUG=1:
```
Read at 0x00c0003ef710 by goroutine 38:
bytes.(*Buffer).String()
/usr/lib/go/src/bytes/buffer.go:71 +0x8f4
github.com/snapcore/snapd/cmd/snapd_test.(*snapdSuite).TestSyscheckFailGoesIntoDegradedMode()
/home/maciek/work/canonical/snapd/cmd/snapd/main_test.go:110 +0x8d1
/usr/lib/go/src/runtime/asm_amd64.s:775 +0x42
/usr/lib/go/src/reflect/value.go:368 +0xb5
/home/maciek/work/canonical/snapd/vendor/gopkg.in/check.v1/check.go:775 +0x955
gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1() …
```
=> cmd/snapd: fix logger data race

interfaces/systemd/service.go, interfaces/systemd/service_test.go
Dependency options e.g. After,Before,Wants,WantedBy must go under the [Unit] section.
=> i/systemd: fix dependency options target section

overlord/configstate/configcore/services.go, overlord/configstate/configcore/services_test.go, tests/core/snap-set-core-config/task.yaml
Start/stop the ssh.socket unit instead of ssh.service when enabling/disabling the ssh service (service.ssh.disable service option), where the unit exists (that is, for UC24+). With this we prevent that on stop the socket unit tries to retrigger the service (which makes it fail by retries), and on start we do not start a sshd process that will be instead started by the socket unit when needed.
=> o/configstate/configcore: start/stop ssh.socket for 24+

cmd/snap-gpio-helper/cmd_export_test.go, cmd/snap-gpio-helper/cmd_unexport_test.go, cmd/snap-gpio-helper/export_test.go, cmd/snap-gpio-helper/main.go, sandbox/gpio/common.go, sandbox/gpio/export_test.go, sandbox/gpio/gpio_chardev.go, sandbox/gpio/gpio_chardev_test.go
Make sure the gpio-aggregator module is loaded because the systemd security backend comes before the kmod security backend, there is an edge case on first connection where the helper service could be started before the gpio-aggregator module is loaded.
Check backends' order is controlled through: https://github.com/canonical/snapd/blob/f05804bf6c76580311eda9b21d9b77acb626acc6/interfaces/backends/backends.go#L40
=> sandbox/gpio: load gpio-aggregator module if not loaded

interfaces/prompting/prompting.go, interfaces/prompting/prompting_test.go
Instead of implementing `json.{M,Unm}arshaler`, implement the `encoding.Text{M,Unm}arshaler` interface. `json.Marshal` uses the text (un)marshaler interface as a fallback when the json (un)marshaler interfaces are not implemented.
Importantly, when marshaling `IDType` to json as a key in a map, the implementation of the json interfaces is not sufficient for the ID to be properly marshaled in its string format; instead, the default `uint64` marshaling is used. This is because json keys must be strings, and the keys must be unique, so keys are marshalled to text first, then later marshalled as json. As a result, by implementing the `TextMarshaler` interface, the text representation of `IDType` is correct, and the json marshaling inherits it.
Additionally, the `MarshalText` method must be …
=> i/prompting: implement Text(Un)Marshaler for IDType

cmd/snap-bootstrap/cmd_initramfs_mounts.go, cmd/snap-bootstrap/cmd_initramfs_mounts_classic_test.go, cmd/snap-bootstrap/cmd_initramfs_mounts_factoryreset_test.go, cmd/snap-bootstrap/cmd_initramfs_mounts_install_test.go, cmd/snap-bootstrap/cmd_initramfs_mounts_installrun_test.go, cmd/snap-bootstrap/cmd_initramfs_mounts_recover_test.go, cmd/snap-bootstrap/cmd_initramfs_mounts_run_test.go, cmd/snap-bootstrap/cmd_initramfs_mounts_test.go, cmd/snap-bootstrap/initramfs_systemd_mount.go
On first boot we had to mount the snapd snap to /run/mnt/base. Avoid this duplicate mount by mounting directly to /snapd/snapd/<revision>, which will allow also some simplifications in the base script that runs on first boot.
=> cmd/snap-bootstrap: mount snapd snap directly to /snap

interfaces/backends/backends.go, interfaces/backends/backends_test.go
When running a preseeding change we want the udev backend to exist even if running on a container so the related configuration files can be generated. Fixes LP#2109843.
=> interfaces/backends: leave udev backend when preseeding

.github/workflows/unit-tests-cross-distro.yaml
We have observed valgrind 3.25 to cause a failure in unit tests:
not ok /cgroup/v2/own_path_full_die - GLib-FATAL-ERROR: g_test_trap_subprocess() failed: Failed to close file descriptor for child process (Invalid argument) Bail out!
==406847==
==406847== Process terminating with default action of signal 5 (SIGTRAP): dumping core
==406847==    at 0x493A9DB: UnknownInlinedFun (gmessages.c:434)
==406847==    by 0x493A9DB: g_logv (gmessages.c:1287)
==406847==    by 0x493AC53: g_log (gmessages.c:1329)
==406847==    by 0x49666EF: g_test_trap_subprocess_with_envp (gtestutils.c:4190)
==406847==    by 0x4005D99: _test_sc_cgroupv2_own_group_path_die_with_message (cgroup-support-test.c:290)
==406847==    by 0x4965376: UnknownInlinedFun (gtestutils.c:3115)
==406847==    by 0x4965376: …
=> github: workaround valgrind 3.25 and glib test suite

tests/utils/features/featextractor.py, tests/utils/features/state.py
There are some tests that are missing tasks/changes in their state.json:
- core/config-defaults-once
- core/custom-device-reg
- core/gadget-config-defaults-to-snaps
- core/gadget-config-defaults-vitality
- core/remodel
- main/disk-space-awareness
- main/generic-unregister
- main/snap-mgmt
- nested/manual/minimal-smoke
Rather than killing feature tagging, this change will add the string 'NOT FOUND' as the snap type.
=> tests: allow for not finding snap type in feature tagging

.github/workflows/weekly-state-locks.yaml
Even when the tests fail, the state locks reports have to be generated.
=> tests: make sure the state lock reports are always generated

overlord/ifacestate/apparmorprompting/export_test.go, overlord/ifacestate/apparmorprompting/prompting.go, overlord/ifacestate/apparmorprompting/prompting_test.go, sandbox/apparmor/notify/listener/export_test.go, sandbox/apparmor/notify/listener/listener.go, sandbox/apparmor/notify/listener/listener_test.go, sandbox/apparmor/notify/notify.go, sandbox/apparmor/notify/notify_test.go
~~This PR is based on #15178~~
TODO:
The spec for restarts support can be found here: https://docs.google.com/document/d/1ODuvREJXCuTBWFaoj_k_bHJuoVcnG5WSz850j2ks15Y
The current struct definitions from JJ here: https://pastebin.canonical.com/p/2qbKQ8NFWz/
This work is tracked internally by https://warthogs.atlassian.net/browse/SNAPDENG-34637
=> s/a/notify{,/listener}: register listener id and resend notifications

tests/main/interfaces-snap-interfaces-requests-control/task.yaml
This spread test now only runs on systems which support prompting, so there is need for the `EXPECTED_HTTP_CODE` variable.
Additionally, expand the test slightly to check that a snap can access a prompt by ID when it has the interface connected.
=> tests/main/interfaces-snap-interfaces-requests-control: simplify test

.github/workflows/spread-tests.yaml, .github/workflows/weekly-feature-tagging.yaml
For feature tagging, some spread tests should simply be skipped.
There are some tests that are not compatible with feature tagging like `core/persistent-journal`, `core/persistent-journal-namespace` and `nested/manual/snapd-refresh-from-old`. Some test suites make no sense with feature tagging like `tests/lib` or `tests/unit` and should be skipped. Also artifact retrieval doesn't work on Trusty, so might as well just skip it.
=> github: add the ability to skip spread tests

asserts/asserts.go, asserts/signtool/sign.go, asserts/signtool/sign_test.go
In order to keep assertions readable and consistent, we require the JSON in an assertion body (e.g., confdb-schema) to be indented with two spaces per level and have all object keys sorted.
This change makes the signtool reformat assertion bodies. This makes the UX of writing and signing an assertion (whether with snapcraft or snap sign) much better, since it can be difficult to get the format right "by hand".
=> asserts/signtool: format JSON in assertion bodies

overlord/snapstate/handlers.go, overlord/snapstate/handlers_prereq_test.go
This fixes a bug reported by @bugraaydogar:
Bug scenario:
* Installing a snap that updates a prereq (in our case, chromium requires a cups update):
* Creates another set of update tasks, including a `check-rerefresh` task for the prereq. Adds them all to the change for the snap installation.
* Snap being installed has a configure hook that creates tasks (chromium's configure hook has a `snapctl stop chromium.daemon`):
* Tasks created by the hook are added to the change that is installing the snap
* Tasks created by the hook wait on all other tasks in the change, including the `check-rerefresh` for the prereq
* `check-rerefresh` task explicitly panics if any tasks are waiting on it
=> o/snapstate: temporarily disable rerefresh on prereq updates

sandbox/apparmor/notify/notify.go, sandbox/apparmor/notify/notify_test.go
The kernel will return `ENOENT` on `APPARMOR_NOTIF_REGISTER` if the listener with the given ID does not exist, such as if the listener timed out. This PR adds handling for snapd to remove the saved listener ID and retry if it tries to register the listener with a saved ID and gets a `ENOENT` instead.
=> s/a/notify: add handling for kernel listener timeout and more logging

spread.yaml
Now spread will require endpoint, endpoint and location keys.
Those keys are configured using env vars already cnofigured in the selfhosted runners.
Tests are not executed as this pr need to be ready to be landed when the new spread binary is deployed in the selfhosted runners
=> tests: update how openstack backend is configured in the spread.yaml

cmd/snap-gpio-helper/main.go, cmd/snap-gpio-helper/main_test.go, features/features.go, features/features_test.go, interfaces/builtin/export_test.go, interfaces/builtin/gpio_chardev.go, interfaces/builtin/gpio_chardev_test.go, sandbox/gpio/export_test.go, sandbox/gpio/gpio_chardev.go, sandbox/gpio/gpio_chardev_test.go, tests/core/interfaces-gpio-chardev/task.yaml
GPIO chardev support is hidden in this PR until kernel configfs gpio-aggregator interface makes it to the 24.04 kernel AND the snap-gpio-helper is updated to use the new configfs interface.
In the meantime remove the feature flag and mark the gpio-chardev interface as unsupported to avoid snaps from using the workaround implementation that utilized the gpio-aggregator sysfs kernel interface so that it can be completely removed after configfs support lands without having to worry about backwards compatibility.
**NOTE: The flag landed in 2.68 BUT actual support (export/unexport commands https://github.com/canonical/snapd/pull/15212) will land in 2.70, so it is impossible to use the flag even in 2.69 in any meaningful way. It would still be good if we can land this into 2.69 and 2.68 in a …
=> many: remove the gpio-chardev-interface experimental flag

overlord/ifacestate/helpers.go, overlord/ifacestate/ifacemgr.go, overlord/ifacestate/ifacestate_test.go
The warning about snapd.apparmor not being enable should only be emitted when apparmor backend is present, which happens when snapd has detected a usable support for apparmor in the host system. A mere fact of having the service packaged in the system is not sufficient to show the warning to the user.
Related: [SNAPDENG-34259](https://warthogs.atlassian.net/browse/SNAPDENG-34259)
Cherry picked from: #15434 
[SNAPDENG-34259]: https://warthogs.atlassian.net/browse/SNAPDENG-34259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> overlord/ifacestate: emit snapd.apparmor warning only when using apparmor backend

cmd/snap-bootstrap/cmd_initramfs_mounts.go, cmd/snap-bootstrap/cmd_initramfs_mounts_install_test.go, cmd/snap-bootstrap/cmd_initramfs_mounts_test.go, tests/lib/assertions/developer1-22-components-dangerous.json, tests/lib/assertions/developer1-24-components-dangerous.json, tests/nested/manual/core20-preseed/task.yaml
This was causing bad values in the modeenv, with eventual failures after installation due to changes on the mount of sysroot.
=> cmd/snap-bootstrap: fix type of snapd used when retrieving base

tests/nested/manual/core20-new-snapd-does-not-break-old-initrd/task.yaml
Older kernel initramfs is actually not compatible with snapd 2.68. Use snaps from stable channels instead for the image, so what this tests is that updating to latest snapd and to the kernel in beta does not break things.
Also, enable this for 22 and 24.
=> tests/core20-new-snapd-does-not-break-old-initrd: do not used fixed kernel/gadget

data/selinux/snappy.fc, data/systemd/snapd.apparmor.service.in, packaging/fedora/snapd.spec
Fedora, CentOS and the likes do not use AppArmor natively, but when running when one of those distributions is running in a LXC container on an AppArmor enabled system, the apparmor state in /sys/kernel/security/apparmor is usually exposed inside the container. The native packages on those distributions are not apparmor-enabled, however after explicitly enabling reexec (via SNAP_REEXEC=1, ensuring the /snap symlink), one would now be running the apparmor-enabled binaries from the snapd snap which expect certain sandbox features to be present on an AppArmor capable host. Specifically, snap-confine from the snapd snap has strict checks that verify it is running under a dedicated AppArmor profile.
At this stage, one would usually be unable to progress further unless they can ensure that the …
=> packaging, data/systemd: enable snapd.apparmor on Fedora

.github/workflows/test.yaml, tests/lib/external/snapd-testing-tools/.github/workflows/tests.yaml
Changes required to fix these failures:
- required static and unit tests skipped due to cache-build-deps relying on retired ubuntu-20.04 runner
- cannot calculate ubuntu daily due to change on master workflow naming
This is only to enable previously skipped required static and unit tests, skipping spread tests.
=> .github/workflows: release/2.68 ci maintenance

seed/seedwriter/writer.go, seed/seedwriter/writer_test.go
in dangerous mode we allow overriding a required snap, which might end up needing a different base, allow providing for it via an optional snap
this addresses the issue mentioned in https://github.com/canonical/snapd/pull/12745
=> s/writer: allow providing a different base when overriding snap

systemd/systemd.go
The serviceNames function argument is read by the snippet invoking s.systemctl(), but it could also be modified in parallel by the polling goroutine which is started immediately before.
A data race was identified in tests:
```
Read at 0x00c000454888 by goroutine 360:
github.com/snapcore/snapd/systemd.(*systemd).Stop()
/home/runner/work/snapd/snapd/systemd/systemd.go:1145 +0x2a4
github.com/snapcore/snapd/systemd_test.(*SystemdTestSuite).TestStopMany()
/home/runner/work/snapd/snapd/systemd/systemd_test.go:422 +0xe7c
/snap/go/10672/src/runtime/asm_amd64.s:747 +0x42
/snap/go/10672/src/reflect/value.go:380 +0xb5 …
```
=> systemd: fix data race when stopping services

tests/lib/spread/backend.openstack.yaml, tests/main/confdb-cross-config/task.yaml, tests/main/confdb/task.yaml
Backport https://github.com/canonical/snapd/pull/15453 to branch release/2.68.
In this branch, openstack was not yet officially supported as a backport and relied on copying yaml snippet from `tests/lib/spread/backend.openstack.yaml` into `spread.yaml`. The only required change was to use the new key as per [this change in #15453](https://github.com/canonical/snapd/pull/15453/files#diff-e1e5ecb5e7fe7aa228c64f680564673541f91452212c3c6c23cbbd27bb78dcedR384). Also corrected configdb test restore as was also done in #15453.
This change does not require all spread tests to pass, only some openstack tests to prove the key modification works.
=> spread.yaml, tests/main: backport openstack fix #15453

interfaces/builtin/fwupd.go, interfaces/builtin/fwupd_test.go
With the modem-manager plugin enabled, fwupd may attempt to update firmware of devices controlled by modem-managed. For this, relevant device access is needed.
See https://github.com/fwupd/fwupd/pull/8689 for context.
=> interfaces/builtin/fwupd: add support for modem-manager plugin

tests/main/confdb-cross-config/task.yaml, tests/main/confdb/task.yaml
Follow up for backport https://github.com/canonical/snapd/pull/15472 to correct restore step that used confdb setting name that is different on master.
=> tests/main: correct confdb restore step setting name

interfaces/prompting/requestprompts/requestprompts.go, interfaces/prompting/requestprompts/requestprompts_test.go
If a message notification has expired in the kernel, than an attempt to reply to the corresponding request will result in ENOENT from the kernel.
Previously, any error when sending the reply would result in aborting the reply and surfacing the error to the caller.
This commit instead handles ENOENT differently, recording a debug log and otherwise carrying on without returning an error. That means that if a prompt reply receives an ENOENT for one of the listener requests associated with that prompt, the other requests will still be sent responses.
Additionally, if a reply returns ENOENT, then any rule which would be created as a result of the successful reply will still be created.
This work is tracked internally by https://warthogs.atlassian.net/browse/SNAPDENG-35041
=> i/p/requestprompts: handle expired notification when replying

cmd/snap-confine/snap-confine.c, tests/main/classic-confinement-perms/task.yaml
Skip dropping capabilities permitted set too early, if the original user
is already root. This preserves the original behavior we had before
introducing non-setuid support, where it was possible for the root user
to have its current working directory to be restored properly right
before we exec into the snap.
=> cmd/snap-confine: do not drop capabilities if the original user is already root

cmd/snap-seccomp/main.go, cmd/snap-seccomp/main_test.go, interfaces/seccomp/template.go, tests/main/snap-seccomp-blocks-pipe-notifications/task.yaml, tests/main/snap-seccomp-blocks-pipe-notifications/test.c
Linux 5.8 has added yet another method of obtaining events from the kernel. This time, in the form of a flag to the pipe2 system call. An LWN.net article [1] goes into all the details and is recommended reading.
Mozilla has similarly discovered this and patched it [2] in the Firefox sandbox.
The snap-seccomp entry uses O_EXCL as O_NOTIFICATION_PIPE as including the actual header <linux/watch_queue.h> causes type definition errors.
```
In file included from /usr/include/asm/fcntl.h:1,
from /usr/include/linux/fcntl.h:5,
from /usr/include/linux/watch_queue.h:6,
from cmd/snap-seccomp/main.go:209:
/usr/include/asm-generic/fcntl.h:157:1: error: redefinition of struct or union 'struct f_owner_ex'
157 | };
| ^
In file included from /usr/include/bits/fcntl.h:61,
from /usr/include/fcntl.h:35,
from …
```
=> interfaces,cmd: disallow O_NOTIFICATION_PIPE

interfaces/backends/backends.go, interfaces/backends/backends_test.go, interfaces/udev/backend.go, interfaces/udev/udev.go, interfaces/udev/udev_test.go
Apologies to everyone affected. The udev backend was recently disabled in containers, with the patch 75e6f1d02d9fb204ee27b6ef4a56133b41c7e84c This worked fixed issues with snapd-inside-lxd that launchpad team exercises heavily but also broke snapd used for pre-seeding by the CPC team. The follow up b504599b84a6228040f653e3062e79b757f8d3ebi fixed pre-seeding but accidentally re-enabled udev in containers, breaking launchpad again.
This patch fixes both behaviors. The snapd udev backend is unconditionally enabled. When EITHER pre-seed mode is on, or when a container is detected then udev commands are not invoked but the files for udev ARE written.
**Agreed that we really want/need this in 2.70.**
=> interfaces: fix udev in containers without breaking pre-seed

daemon/api_snapctl.go, tests/main/auto-refresh-gating/task.yaml, tests/main/services-snapctl/task.yaml, tests/main/snapctl-is-connected/task.yaml
It was pointed out that "error: error running snapctl" makes it look like snapctl itself had an error instead of an operation triggered by snapctl failing.
=> daemon: change snapctl error prefix

cmd/snap/cmd_debug_raa.go, daemon/api_debug.go, daemon/api_debug_raa.go, daemon/api_debug_test.go, daemon/export_api_debug_test.go, tests/main/snap-debug-raa/task.yaml
This command would be helpful in debugging unexpected behavior of refresh-app-awareness by inspecting the snapd persistent and cached state.
Sample API `/v2/debug?aspect=raa`:
```json
{
"result": {
"monitored-snaps": {
"firefox": {
"pids": {
"snap.firefox.firefox": [
92960,
93398,
93413,
93417,
93450,
93740,
93749,
93752,
93758,
96102,
96196,
115681,
115738,
115801
]
}
}
},
"refresh-candidates": {
"firefox": {
"channel": "latest/stable",
"monitored": true,
"revision": "6103",
"version": "138.0.1-1"
}
}
},
"status": "OK",
"status-code": 200,
"type": "sync"
}
```
Sample command output:
```bash
Monitored snaps:
Name     Security Tag          PID
firefox  snap.firefox.firefox  92960
firefox  snap.firefox.firefox  93398
firefox  snap.firefox.firefox  93413
firefox  snap.firefox.firefox  93417 …
```
=> many: add raa debug command

NEWS.md, interfaces/backends/backends.go, interfaces/backends/backends_test.go, interfaces/udev/backend.go, interfaces/udev/udev.go, interfaces/udev/udev_test.go, packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog, tests/main/nvidia-files/task.yaml
DEBEMAIL="Ernest Lotter <ernest.lotter@canonical.com>" release-tools/changelog.py 2.68.5 2098137 NEWS.md
The main purpose of this release is to create official release with the fix currently provided by the hotfix branch: stable/hotfix-preseeding-lp2109843.
The main fix that is the reason for this dot release, https://github.com/canonical/snapd/pull/15411, was merged to release/2.68 branch, so no need to cherry pick. In addition also, https://github.com/canonical/snapd/pull/15462, for needed ci maintenance.
Cherry-picks:
Functional:
- https://github.com/canonical/snapd/pull/15439
Testing:
- https://github.com/canonical/snapd/pull/15409
SRU Bug: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/2098137
**Requires rebase merge**
=> release: 2.68.5

spread.yaml
This is a no-change cleanup of `spread.yaml`.
I chose to split it out of another branch for readability.
=> spread: unify and clean up formatting

interfaces/builtin/udisks2.go
The chown capability is required in the udisks2 slot to allow the daemon to mount devices for non-root users. This is required for core desktop systems.
This patch implements it.
=> udisks2: Allow chown capability

core-initrd/latest/postinst.d/ubuntu-core-initramfs
Add the "panic=60" kernel cmdline option for Azure kernels in order to make them reboot after 60s upon a panic during boot. This will be relevant for implementing a fallback mechanism in nullboot, allowing rollbacks in the event of a faulty kernel upgrade. The 60s timeout is chosen to allow easier collection of console logs during troubleshooting.
=> core-initrd: make Azure kernels reboot upon panic

spread.yaml, tests/lib/prepare.sh
This change is only adding the backends in the spread.yaml and it is adding a new env var to define if snapd needs to use the proxy because it is required in ps7 and it is not in ps6.
Next change will move 1 system to PS7
=> tests: initial change to support the new ps7 environment

overlord/devicestate/handlers_install.go, tests/nested/manual/core20-early-config/defaults.yaml
Do not use m.seedLabel as it might not be set when the task runs if snapd restarts during seeding due to early-config (specifically the users.create.automatic) behavior. Instead rely on the modeEnv we load. The system is marked seeded before `Setup system for run mode` is run, so a well timed snapd restart will end up with empty `m.seed*` values
Adding some tracing of an install mode shows us that if snapd restarts during seeding, then `seedLabelAndMode()` might not have been called again, and thus `m.seedLabel` will be empty.
Tracing before snapd restarts:
```
May 27 12:10:37 localhost snapd[1092]: devicemgr.go:841: DEBUG: earlyDeviceContext()
May 27 12:10:37 localhost snapd[1092]: devicemgr.go:885: DEBUG: earlyLoadDeviceSeed()
May 27 12:10:37 localhost snapd[1092]: devicemgr.go:857: …
```
=> overlord/devicestate: fix a regression during seeding when using early-config

interfaces/builtin/system_packages_doc.go, tests/main/interfaces-system-packages-doc/task.yaml
LP: #1955325
With commit "8e8eb2ddce interfaces: grant access to /usr/local/share/doc", access was granted to /usr/local/share/doc. However, the mount target does not (or ceased to) exist in the base snap, so the snaps connecting this interface did not yet have access to that directory.
This can be observed in Firefox for example:
```
% snap connections firefox|grep doc
system-packages-doc     firefox:system-packages-doc      :system-packages-doc            -
% grep local/share/doc /run/snapd/ns/snap.firefox.fstab
```
Thanks to @jhenstridge for the valuable help with this.
=> system-packages-doc: Fix access to /usr/local/share/doc

mkversion.sh
Use ${parameter:=word} to assign a default value.
=> mkversion: fix DPKG_PARSECHANGELOG assignment

HACKING.md
The garden backend simplifies the extra work needed to run qemu locally. Rewrite the relevant section of the HACKING.md file to reflect that.
=> docs: update HACKING.md, remove references to local qemu

tests/lib/fakestore/store/store.go, tests/nested/manual/update-snapd-seed-and-factory-reset/task.yaml
"channel" is defined for a refresh action only if we change of channel. Otherwise we have to find the tracking channel in the
context.
=> fakestore: fix channels in refresh

core-initrd/latest/factory/usr/lib/systemd/system/snap-initramfs-mounts.service, overlord/install/install.go, secboot/bootstrap_container.go, secboot/bootstrap_container_sb.go, secboot/bootstrap_container_sb_test.go, secboot/encrypt_sb.go, secboot/export_sb_test.go, secboot/secboot.go, secboot/secboot_hooks.go, secboot/secboot_sb.go, secboot/secboot_tpm.go, tests/nested/manual/uc20-install-in-initrd/task.yaml
Because did not install in initrd did not install keys keyring, we have always been missing the unlock key on first boot that made enrolling recovery key impossible.
Here we also test for the primary key being available by forcing a reseal. We will then be able to remove the primary key safely from files during install.
=> many: store keys in keyring in install in initrd

tests/lib/prepare.sh
Ensure that snapd snap used in the tests is usable wrt. file capabilities on snap-confine.
=> tests/lib/prepare: ensure snapd snap is usable

run-spread
When running locally, the debug output is not as useful as it obscures the failure that just happened. Unlike what happens in CI, there is no post-processing or archiving of logs.
Detect tty connected to stdout and set SPREAD_DEBUG_EACH=0
=> spread: automatically disable debugging when running interactively

go.mod, go.sum
Update secboot to make available the [new RunChecksContext API](https://github.com/canonical/secboot/commit/7fb379721237726dd216fbc821e83ec17eccb178).
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-34453
=> secboot: update to rev 7fb379721237 (RunChecksContext API)

debug-tools/startup-timings, tests/lib/collect-artifacts.sh, tests/main/bad-meta-file-types/task.yaml, tests/main/cgroup-tracking-failure/task.yaml, tests/main/refresh-app-awareness-notify/task.yaml, tests/main/security-apparmor/task.yaml, tests/main/security-device-cgroups-strict-enforced/task.yaml, tests/main/snap-download/task.yaml, tests/main/snap-run-alias/task.yaml, tests/main/snap-run-symlink/task.yaml, tests/main/snap-run/task.yaml, tests/main/snapctl-is-connected-list/task.yaml, tests/main/snapctl-is-connected/task.yaml, tests/main/validate-container-failures/task.yaml, tests/regression/lp-1943853/task.yaml
Does the following:
- allows tests to also handle json logs
- changes startup timings reader to correctly parse json logs
- makes retrieving state.json optional
- for logs that get divided into separate entries in the journal, re-compiles them into one before writing journal.txt
=> debug-tools, tests: fix various errors when executing feature tagging

daemon/api_snaps.go, daemon/api_snaps_test.go, daemon/export_test.go, overlord/devicestate/devicestate.go, overlord/devicestate/devicestate_remodel_test.go, overlord/snapstate/snapstate.go, overlord/snapstate/snapstate_test.go
This fixes a bug reported by @bugraaydogar. We weren't properly handling the case where we switched to a channel without an actual refresh. I added a prereq tracker to `snapstate.Switch` so that it aligns better with the other exported function, and we can pass ours from the remodeling code in.
=> o/devicestate: add snap to prereq tracker when we switch channels without refresh during an offline remodel

interfaces/apparmor/template.go, interfaces/builtin/microstack_support.go
This exposes the maximum number of open file descriptors which does not seem particularly sensitive. While doing this, remove the duplicate entry from the microstack interface.
=> interfaces: allow reading /proc/sys/fs/nr_open

cmd/snap/main.go, systemd/export_test.go, systemd/journal.go, systemd/journal_test.go, usersession/autostart/autostart.go
Add support for unit name and namespaces in the systemd journal helper code. Move parameters into a struct instead.
Reflect what is done in https://github.com/systemd/systemd/blob/2e8a581b9cc1132743c2341fc334461096266ad4/src/core/exec-invoke.c and try to set the send buffer.
=> systemd: update code for creating a journal stream

overlord/stateengine.go, tests/utils/features/featextractor.py, tests/utils/features/features.py, tests/utils/features/test_featextractor.py, tests/utils/features/test_query_features.py
Previously, the ensure feature tagging grouped by a single ensure loop so a singular feature would look like:
```json
{
"manager": "SnapManager",
"functions": [
"ensureVulnerableSnapConfineVersionsRemovedOnClassic",
"ensureMountsUpdated",
"ensureDownloadsCleaned"
]
}
```
This change separates the loops so a singular ensure feature is the execution of a single function. The previous data will now be represented as:
```json
{
"manager":"SnapManager",
"function":"ensureVulnerableSnapConfineVersionsRemovedOnClassic"
},
{
"manager":"SnapManager",
"function":"ensureMountsUpdated"
}, 
{
"manager":"SnapManager",
"function":"ensureDownloadsCleaned"
}
```
Without a need to identify individual ensure loops, the top-level log entry is no longer necessary
=> overlord, tests: fix ensure feature tagging to no longer group by loop

cmd/Makefile.am, cmd/libsnap-confine-private/tools-dir.h, cmd/snap-confine/group-policy-test.c, cmd/snap-confine/group-policy.c, cmd/snap-confine/group-policy.h, cmd/snap-confine/snap-confine.c, tests/main/security-group-policy/task.yaml
Some distributions have opinions on who can run snaps and would prefer to have a way to limit execution of snaps only to members of a specific group.
The patch allows support for setting the group ownership of snap-confine as an indicator that only members of said group should be able to run snaps.
In theory the same can be limited by setting root:<group> ownership and then 0750 flags, or ACLs, but this only works for the local case. However, this is not enough to ensure a consistent policy if reexec is enabled. In such scenario /usr/bin/snap reexecs into /snap/snapd/current/usr/bin/snap and proceeds to call snap-confine from the snapd snap. The snapd snap is built as part of the upstream releases and is not aware of any local distro policies expressed through group ownership or ACLs, …
=> cmd/snap-confine: support for host policy for limiting users able to run snaps

.github/workflows/spread-tests.yaml
=> github: do not run spread when run_tests only contains whitespace

daemon/api_system_volumes.go, daemon/api_system_volumes_test.go, daemon/export_api_system_volumes_test.go, overlord/fdestate/export_test.go, overlord/fdestate/fdemgr.go, overlord/fdestate/fdemgr_test.go, secboot/keys/keys_dummy.go, secboot/keys/keys_sb.go, secboot/keys/keys_test.go, secboot/secboot_dummy.go, secboot/secboot_sb.go
This PR introduces a new (sync) action `check-recovery-key` that checks that the provided recovery key is matching one that was added during install or post-install.
Please note that the underlying secboot implementation is missing and currently this always returns 200 OK. The underlying secboot helper needs to be swapped when it lands.
For context, please check the SD201 spec.
=> many: add /v2/system-volumes action for checking recovery keys

daemon/api_icons.go, daemon/api_icons_test.go, daemon/api_snaps.go, daemon/api_snaps_test.go, tests/main/interfaces-desktop-launch/api-client/bin/api-client.py, tests/main/interfaces-desktop-launch/api-client/meta/snap.yaml, tests/main/interfaces-desktop-launch/task.yaml, tests/main/interfaces-snap-interfaces-requests-control/task.yaml, tests/main/interfaces-snap-refresh-observe/task.yaml
This adds interface access to `/v2/icons` for the `desktop-launch`, `snap-interfaces-requests-control`, and `snap-refresh-observe` interfaces. Additionally, this grants `desktop-launch` access to the `/v2/snaps/{name}` and `/v2/snaps` endpoints.
=> daemon, tests: add interface access to icons endpoint and grant desktop-launch access to /v2/snaps

.github/workflows/non-fundamental-systems.json, NEWS.md, interfaces/builtin/hostname_control.go, overlord/devicestate/handlers_install.go, packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog, tests/nested/manual/core20-early-config/defaults.yaml
DEBEMAIL="Ernest Lotter \<ernest.lotter@canonical.com\>" release-tools/changelog.py 2.68.5.lp2104254 2104254 NEWS.md
**Hotfix release content:**
- https://github.com/canonical/snapd/pull/15497 | [LP: #2104254](https://bugs.launchpad.net/stuttgart/+bug/2104254)
- https://github.com/canonical/snapd/pull/15196
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-35155
**These assumptions needs to be double checked during review:**
- Proposed version: 2.68.5.1  (initially suggested 2.68.5.lpxxxxx, but CI versioning exceeds snapcraft char limit)
- Using separate branch `hotfix/2.68.5` based off `release/2.68` to allow for iteration, but nothing will be merged back
- [Hotfix release spec](https://docs.google.com/document/d/1G4Hulmmd8fxvvlCWNUpcJGEPXnAvcpvBAUAvDfVRSEo/e …
=> hotfix release: 2.68.5.1

.github/workflows/weekly-feature-tagging.yaml, tests/utils/features/featcomposer.py, tests/utils/features/test_featcomposer.py
When passing an extremely long list of arguments, the script will fail with `Argument list too long`. This changes from passing the list via the command line to instead reading a file.
=> github, tests: have featcomposer.py failed-tests argument use a file instead of a list of failed tests

client/confdb.go, client/confdb_test.go, cmd/snap/cmd_get_test.go, daemon/api_confdb.go, daemon/api_confdb_test.go, overlord/confdbstate/confdbstate.go
Rename the confdb API's query parameter from fields to keys to match the options API.
=> daemon: rename the confdb URL query param

daemon/api_system_volumes.go, daemon/api_system_volumes_test.go, daemon/export_api_system_volumes_test.go, overlord/fdestate/fdemgr.go, overlord/fdestate/fdemgr_test.go, overlord/fdestate/fdestate.go, overlord/fdestate/fdestate_test.go, overlord/fdestate/handlers.go
This PR doesn't implement the actual recovery key replacement since the created tasks are currently no-op until they are carefully designed. This is needed to mock corresponding API to enable integration testing with the security center. Task implementation will be in a follow up PR.
This adds a new `replace-recovery-key` action to the system volumes api `POST /v2/system-volumes`. This action will use the recovery key generated in the `generate-recovery-key` action to replace the specified target key slots.
For context, please check the SD201 spec.
JIRA ticket: SNAPDENG-35122
=> many: add mock api for replacing recovery keys

.github/workflows/nightly-static-analysis.yaml
The TIOBE workflow is broken as clang-format is not a build dependency, but the run-checks tool still attempts to find it.
=> github/workflows/nightly-static-analysis: ignore missing tools in run-checks

asserts/preseed.go, asserts/preseed_test.go, image/image_test.go, image/preseed/preseed_uc20_test.go, overlord/devicestate/devicestate_systems_test.go, overlord/devicestate/export_test.go, overlord/devicestate/handlers_install.go, seed/seed20.go, seed/seed20_test.go, tests/nested/manual/build-with-kernel-modules-components/task.yaml
Make sure that when we read a seed, the local components get a x1 revision. Not doing this was causing strange behaviors on installation, like having extra components in /var/lib/snapd/snaps/ with revision "unset", and having those components mounted too.
A check is spread tests is added for this.
=> overlord/devicestate,tests: set revision of seed components to x1

.github/workflows/nightly-static-analysis.yaml
After the last Tics refresh it is required that all the goloang projects define the tics env car with
https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=GoProjects before executing the TICSQServer binary
=> tests: fix tics jobs with new TICS env var

packaging/pack-source
Exclude .git directory, not just its contents. This works around the problem, where go build notices the presence of .git directory and attempts to incorporate VCS information into the build, but since the directory is empty, the attempt fails. One can pass `-buildvcs=false` to disable this, but it needs to be included in the appropriate packaging files when consuming tarballs generated by pack-source.
Cherry picked from: #15564
=> packaging/pack-source: exclude .git directory

overlord/servicestate/export_test.go, overlord/servicestate/internal/export_test.go, overlord/servicestate/internal/quota_state.go, overlord/servicestate/internal/quota_state_test.go, overlord/servicestate/quota_control_test.go, overlord/servicestate/quota_handlers.go, overlord/servicestate/quota_handlers_test.go
Changes
- Move the returned items into a struct instead
- Use the same struct for updating
- Add the Group Name as a tracked value
- Add dedicated tests as well
=> overlord/servicestate: isolate quota-state update code

client/errors.go, confdb/confdb.go, confdb/confdb_test.go, daemon/api_confdb.go, daemon/api_confdb_test.go, overlord/confdbstate/confdbmgr.go, overlord/confdbstate/confdbstate.go, overlord/confdbstate/confdbstate_test.go
This makes the confdb API errors more consistent with the options API. Instead of a 404 for various "not found" errors, we return a 400 with an appropriate error kind. This uses the same error kind that options uses for the "no data" scenario and introduces a couple of others (view not found, no matching rule, etc).
~Based on https://github.com/canonical/snapd/pull/15559 because there's some overlap~
=> many: make confdb API errors consistent with options

boot/seal.go, boot/seal_test.go, overlord/fdestate/backend/reseal.go, overlord/fdestate/backend/reseal_test.go, overlord/fdestate/backend/seal_test.go, overlord/fdestate/dbx.go
For now ResealKeyForBootChainsParams only contained boot chain related parameters. But we will need to pass more. WithBootChains needs to be able to only give the boot chain parameters and other parameters can be provided by functions passed as parameters.
=> boot/seal.go: factor boot chain related parameters in its own type

.github/workflows/snap-builds.yaml, .github/workflows/spread-tests.yaml
Changes label checking from event data to API requests, which permits PR authors to modify PR labels without having to close and reopen the PR or push a new commit before that label applies
=> github: change label checking to use the Github API

interfaces/builtin/log_observe.go
Add dac_read_search to log-observe so telemetry agent snaps don't cause the log from being spammed with AppArmor messages. For context: https://bugs.launchpad.net/snapd/+bug/2098780
=> i/builtin: add cap dac_read_search to log-observe

client/system_volumes.go, daemon/api_debug.go, daemon/api_system_volumes.go, daemon/api_system_volumes_test.go, daemon/export_api_system_volumes_test.go, overlord/devicestate/export_test.go, overlord/devicestate/volumes.go, overlord/devicestate/volumes_test.go, overlord/fdestate/fdemgr.go, overlord/fdestate/fdemgr_test.go
This PR introduces the key slots enumeration API `GET /v2/system-volumes` as specified in the SD201 spec.
This builds on top of https://github.com/canonical/snapd/pull/15557 and must be rebased, for now the relevant commit for review is https://github.com/canonical/snapd/pull/15558/commits/77313dae5558554063951754a697b047ce25c60f.
JIRA ticket: SNAPDENG-35091
=> daemon: add /v2/system-volumes enumeration endpoint

go.mod, go.sum, tests/lib/nested.sh, tests/nested/manual/kernel-modules-components/task.yaml
Update secboot to make available the [non amd build fix](https://github.com/canonical/secboot/commit/3dd8877a2a1c8ce3b1ab8322521ea8f0c3729762) and [provide public 
API CheckPassphraseEntropy](https://github.com/canonical/secboot/commit/97bf6d7fa895ebab5e3e10d2a86ee58154c1e76a).
The fix was verified to solve the build issue [here](https://github.com/canonical/snapd/actions/runs/15756045938/job/44411598494?pr=15569): which in turn enables us to merge https://github.com/canonical/snapd/pull/15569, once it is rebased and the API is required to complete snapd entropy work.
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-34453
=> secboot: update to rev 97bf6d7fa895 (add public API CheckPassphraseEntropy)

cmd/libsnap-confine-private/utils.c
Glibc implements a fallback handling for fchmodat() which opens the desired file and applies chmod() [1]. Fix our sc_ensure_mkdirat() helper code to ensure consistent semantics, which ensures that the only errno we see on success is either 0 or EEXIST (which indicates that the desired path already exists).
1. https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/unix/sysv/linux/fchmodat.c;h=dd1fa5db86bde99fe3eb4804b06c5adf11914b94;hb=HEAD#l31
=> cmd/libsnap-confine-private/utils: workaround for glibc fchmodat() fallback

secboot/export_sb_test.go, secboot/preinstall.go, secboot/preinstall_nosb.go, secboot/preinstall_sb.go, secboot/preinstall_sb_test.go, systemd/detect.go, systemd/detect_test.go
Add snapd secboot preinstall check wrapper based on recently added [secboot RunChecksContext API](https://github.com/canonical/secboot/pull/387)
This PR aims to finalize part 1 of the [complete implementation](https://github.com/canonical/snapd/pull/15546).
Spec: [SD201 | Perform TPM/FDE pre-install checks](https://docs.google.com/document/d/1Mbj7Ut0tgW0PCz8VWdhvBN52kHTxYqkZZKQODB1NlLk/edit?tab=t.0#heading=h.jsatitiw8ll7)
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-34453
**IMPORTANT: Do not merge until after arm64 secboot issue is fixed.**
=> secboot: add preinstall check wrapper

secboot/export_sb_test.go, secboot/secboot_sb.go, secboot/secboot_sb_test.go
`CheckRecoveryKey` was a no-op mock, This PR updates `CheckRecoveryKey` the corresponding secboot helper now that the it has landed https://github.com/canonical/secboot/pull/422
=> secboot: use secboot.TestLUKS2ContainerKey helper in CheckRecoveryKey

tests/main/security-group-policy/task.yaml
Collect debug information on capabilities when the test fails.
=> tests/main/security-group-policy: collect debug information

cmd/snap/export_test.go, cmd/snap/main.go, cmd/snap/main_test.go
This changes the snap command logging to only log the command names (including any nested commands)
The logging then takes the following form with all optional and positional arguments ignored:
```json
{"msg":"command-execution","cmd":"watch"}
{"msg":"command-execution","cmd":"whoami"}
{"msg":"command-execution","cmd":"debug api"}
{"msg":"command-execution","cmd":"debug boot-vars"}
{"msg":"command-execution","cmd":"debug set-boot-vars"}
{"msg":"command-execution","cmd":"debug can-manage-refreshes"}
{"msg":"command-execution","cmd":"debug confinement"}
{"msg":"command-execution","cmd":"debug connectivity"}
{"msg":"command-execution","cmd":"debug disks"}
{"msg":"command-execution","cmd":"debug ensure-state-soon"}
{"msg":"command-execution","cmd":"debug execution apparmor"} …
```
=> cmd/snap: change cmd trace log to remove all positional and optional arguments

interfaces/builtin/posix_mq.go, interfaces/builtin/posix_mq_test.go, tests/main/interfaces-posix-mq/task.yaml
Allow stat() on /dev/mqueue, which is a legitimate use case for
programs trying to probe whether it is indeed a mqueue pseudo
filesystem.
Related: SNAPDENG-35208
[SNAPDENG-35208]: https://warthogs.atlassian.net/browse/SNAPDENG-35208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> interfaces/builtin/posix-mq: allow stat on /dev/mqueue

interfaces/apparmor/template.go
The systemd credentials [1] system can be used to provide configuration or secrets to any snap service. Allow snaps to read their own credentials.
[1] https://systemd.io/CREDENTIALS/
This fixed denials such as this one:
```
[21063.296829] audit: type=1400 audit(1745860372.867:5505): apparmor="DENIED" operation="open" class="file" namespace="root//lxd-juju-5cae6a-4_<var-snap-lxd-common-lxd>" profile="snap.vault.vaultd" name="/run/credentials/snap.vault.vaultd.service/vault_token" pid=1014667 comm="vaultd-start" requested_mask="r" denied_mask="r" fsuid=1000000 ouid=1000000
```
=> interfaces: allow reading snap-specific credentials

tests/main/security-group-policy/task.yaml
The no_reexec variant does not make any sense on Ubuntu, where snapd comes preinstalled. In such case, we would only attempt to exercise the feature using the native package, which may even be to old to to support it.
=> tests/main/security-group-policy: do not execute no_reexec variant on  Ubuntu, unless doing SRU

.github/workflows/data-nested-systems.json, .github/workflows/spread-tests.yaml, tests/lib/external/snapd-testing-tools/tests/spread-filter/task.yaml, tests/lib/external/snapd-testing-tools/tests/spread-filter/tests/nested/core/test1/task.yaml, tests/lib/external/snapd-testing-tools/tests/spread-filter/tests/nested/core/test2/task.yaml, tests/lib/external/snapd-testing-tools/utils/spread-filter
When determining tasks to run in the `spread-test.yaml`, if a rule is not specified, then it will automatically run all nested tests since `spread-filter` requires a rule to determine what tests to run. This caused the nested arm test to always run in all PRs without the 'Skip spread' label.
```bash
if [ -z "${{ github.event.number }}" ] || [ "$RUN_NESTED" = 'true' ] || [ -z "${{ inputs.rules }}" ] || [ -z "$changes_param" ]; then
for TASKS in ${{ inputs.tasks }}; do
TASKS_TO_RUN="$TASKS_TO_RUN $prefix:$TASKS"
done
else
NEW_TASKS="$(./tests/lib/external/snapd-testing-tools/utils/spread-filter -r ./tests/lib/spread/rules/${{ inputs.rules }}.yaml -p "$prefix" $changes_param)"
TASKS_TO_RUN="$NEW_TASKS"
fi
```
To ensure that only the paths indicated in tasks will run, this adds an additional …
=> github: add a ruleset to arm nested tests

tests/lib/tools/tests.session, tests/unit/go/task.yaml
The user session is not getting the SNAP_REEXEC env var, so this change pass that to the Environment used when systemd-run is called in tests.session
This fixes the remote-home test which fails when we test snapd from the ppa or from proposed.
=> tests: set SNAP_REEXEC env var in systemd-run when preparing the user session

cmd/snap/cmd_snap_op.go, cmd/snap/cmd_snap_op_test.go
This fixes a bug where only the last component, when using this kind of syntax, was installed.
=> c/snap: support ops on multiple components with syntax "snap <op> snap1+comp1 snap1+comp2"

.image-garden.mk
Switch to permissive mode for SELinux enabled Tumbleweed.
=> image-garden: switch selinux into permissive mode for Tumbleweed with SELinux

interfaces/builtin/microstack_support.go
Nova currently fails to attach SR-IOV VFs as the Libvirt service is blocked by Apparmor.
To address this, we'll update the `microstack_support` interface, exposing the following paths:
* `/sys/devices/pci*/**/driver_override`
* `/sys/bus/pci/drivers/**/unbind`
* `/sys/bus/pci/drivers_probe`
Logs:
```
2025-06-23T14:07:24Z -[1950]: Failed to add driver 'vfio-pci' to
driver_override interface of PCI device '0000:1b:10.6': Permission denied
[  +6.342381] audit: type=1400 audit(1750687644.519:1123): apparmor="DENIED"
operation="open" class="file" profile="snap.openstack-hypervisor.libvirtd"
name="/sys/devices/pci0000:17/0000:17:03.0/0000:1b:10.6/driver_override"
pid=1950 comm="rpc-libvirtd" requested_mask="w" denied_mask="w" fsuid=0 ouid=0
```
```
2025-06-24T11:39:57Z -[340147]: Failed to …
```
=>  i/builtin: update "microstack_support" interface to allow SR-IOV attachments

client/system_volumes.go, daemon/api_system_volumes.go, daemon/api_system_volumes_test.go, daemon/export_api_system_volumes_test.go, overlord/fdestate/fdestate.go
This PR adds a new `/v2/system-volumes` action `change-passphrase` that allows changing an existing passphrase protected key slot.
https://github.com/canonical/snapd/pull/15614 contains the actual implementation for changing a passphrase.
For context, please check SD201 spec.
=> daemon: add /v2/system-volumes action for changing passphrase

secboot/preinstall_sb.go, secboot/preinstall_sb_test.go
Workaround to avoid preinstall check error "...value added retailer supplied drivers where detected to be running". This [was reported](https://chat.canonical.com/canonical/pl/csxncd55wj83dqumo196d87isy) to happen when testing in qemu and virt-manager. In these cases it was caused by the presence for network card ROM.
This changes is based on [recommendation by Chris C](https://chat.canonical.com/canonical/pl/77s81wxcdjfodfh5cnc7iq4emy). It is a temporary measure, that will be replaced by secboot action to modify the configuration ina similar way with user visibility & consent.
=> secboot: permit value-added-retailer drivers

.github/workflows/spread-tests.yaml, tests/main/microk8s-smoke/task.yaml
Spread could be remain locked in the actions runner in case of a communication problem (still researching when)
This change makes sure there are not spread processes running in the actions runner before and after we run spread tests.
=> tests: make sure spread is killed in the tests workflow in case it is locked

data/selinux/snappy.te
Update the selinux policy to allow watching cgroups (for RAA), and talking to user session agents (user service mgmt and refresh).
Related: [SNAPDENG-34561](https://warthogs.atlassian.net/browse/SNAPDENG-34561)
Cherry picked from: #15635 
[SNAPDENG-34561]: https://warthogs.atlassian.net/browse/SNAPDENG-34561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> data/selinux: update policy, allow watching cgroups, allow connecting to user session

confdb/confdb.go, confdb/confdb_test.go, confdb/export_test.go, confdb/schema.go, confdb/schema_test.go
8e8416432f03c663945cfc5cd3bd2f34486fea13 extends the dotted path validation to prevent the same placeholder name to be used more than once in a request
3703dc0e04bd93263866d8e843291e6239f571e8 supports paths with list indexes, both literal and placeholders (foo[1], foo[{n}])
=> confdb: support list indexing paths in confdb-schema 

cmd/snap-bootstrap/blkid/blkid.go, cmd/snap-bootstrap/blkid/mock_blkid.go, cmd/snap-bootstrap/cmd_scan_disk.go, cmd/snap-bootstrap/cmd_scan_disk_test.go
See related issue on LP: https://bugs.launchpad.net/canonical-kernel-snaps/+bug/2114779
=> cmd/snap-bootstrap: allow non-gpt in fallback mode to support rpi

interfaces/builtin/cpu_control.go
- The current rules for procfs and sysfs are wrong:
```
/sys/kernel/irq/[0-9]*/* r,
/proc/irq/[0-9]+/smp_affinity rw,
/proc/irq/[0-9]+/smp_affinity_list rw,
```
According to the AppArmor Wiki documentation[1]:
> AppArmor uses a file globbing syntax similar to that used by the
bash shell. Globbing is not standard full regular expression syntax, but instead uses a few characters known as wild cards.
So: 
- `/sys/kernel/irq/[0-9]*/* r,` doesn't give us access to list the contents of `sys/kernel/irq`.
- `/proc/irq/[0-9]+/smp_affinity rw,` and `/proc/irq/[0-9]+/smp_affinity_list rw,` uses a `+` sign that isn't recognized by the AppArmor syntax.
[1]: https://gitlab.com/apparmor/apparmor/-/wikis/QuickProfileLanguage#file-globbing
=> interfaces/builtin/cpu-control: Fix rules for accessing IRQ sysfs and procfs directories 

.github/workflows/weekly-feature-tagging.yaml, tests/lib/collect-artifacts.sh
- Removes the end-of-line requirement for matching snapd-refresh-from-old, which was incorrect because that test has variants
- Allow for errors in retrieving logs in nested tests. When tests are skipped, they will not have a vm, which will cause the `remote.exec` command in the restore phase to fail.
=> github, tests: fix minor errors when running spread with feature tagging

daemon/api_system_volumes.go, daemon/api_system_volumes_test.go, overlord/fdestate/errors.go, overlord/fdestate/errors_test.go, overlord/fdestate/export_test.go, overlord/fdestate/fdemgr.go, overlord/fdestate/fdemgr_test.go, overlord/fdestate/fdestate.go, overlord/fdestate/fdestate_test.go, overlord/fdestate/handlers.go, overlord/fdestate/handlers_test.go, secboot/export_sb_test.go, secboot/secboot.go, secboot/secboot_sb.go, secboot/secboot_sb_test.go
This PR adds support for changing passphrase post installation given the old passphrase is provided. A follow up PR while build on top of this to allow changing passphrase through the API (i.e. /v2/system-volumes).
For context, please check SD201 spec.
=> many: support changing passphrases post installation

osutil/inotify/inotify.go, osutil/inotify/inotify_linux.go
A problem with RAA was identified when running on openSUSE Tumbleweed, the
the inotify file descriptor would return 0 sized reads for no particular
reason. Further debugging revealed that Read() was returning ErrClosed,
indicating that the file is already closed. The problem was tracked down
to storing a copy of os.File instead of a pointer *os.File inside the
inotify.Watcher{} structure. The issue was only observed when building
snapd with 1.25rc1. A minimal sample using osutil/inotify behaved in a
similar way.
A possible explanation of this behavior are the changes to the 'os'
package in
https://github.com/golang/go/commit/fdaac84480b02e600660d0ca7c15339138807107
adding 'cleanup' for os.File objects, attached directly to the object
itself. Further documentation on runtime.AddCleanup() …
=> osutil/inotify: store a pointer to os.File rather than a copy

.github/workflows/ci-labeler.yaml, .github/workflows/ci-test.yaml, .github/workflows/spread-tests.yaml
This automatically adds the 'Run only one system' label to all draft PRs. The label is then dynamically checked (along with 'Run nested') in `spread-tests.yaml` to permit its removal without requiring a close/reopen or a new commit push. All systems except for Noble (and nested systems if the "Run nested" is present) will be filtered out). To remove the filtering, after having removed the "Run only one system" label, one will have to either rerun all jobs or rerun the read-systems job (assuming the read-systems job has already run at least once). 
~The spread test job will automatically fail for all systems except for non-nested ubuntu-24.04-64 (also if the 'Run nested' label is present, then nested tests will also be exempt from automatic failure).~
~## Why automatic failure instead of …
=> github: run only one system for draft PRs

overlord/snapstate/snapstate.go, overlord/snapstate/snapstate_remove_test.go, tests/smoke/remove/task.yaml
Make the removal of last active snap revision be the same as if one
requested removal of all revisions.
Related: [SNAPDENG-35121](https://warthogs.atlassian.net/browse/SNAPDENG-35121)
Fixes: [LP#2112551](https://bugs.launchpad.net/snapd/+bug/2112551)
[SNAPDENG-35121]: https://warthogs.atlassian.net/browse/SNAPDENG-35121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> overlord/snapstate: make removal of last active revision of a snap equal to snap remove

.github/workflows/ci-test.yaml
Update branch spec in CI workflow to run tests on hotfix PRs (for example #15670)
=> github: run CI tests on hotfix branches

boot/assets.go, boot/assets_test.go, boot/bootstate20.go, boot/cmdline.go, boot/model.go, boot/model_test.go, boot/seal.go, boot/systems.go, overlord/fdestate/backend/reseal.go, overlord/fdestate/backend/reseal_test.go
Only when the model or try model is changed then we should reseal.
=> boot: do not reseal FDE hook keys every time

cmd/snap/cmd_get.go, cmd/snap/cmd_get_test.go, overlord/confdbstate/confdbmgr.go, overlord/confdbstate/confdbstate_test.go
This changes the structure and field names of the data carried in the change during a confdb read. The intent is to make this consistent with the structure described in signed message format (see spec SD187).
=> o/confdbstate: rename value/error fields in confdb response

cmd/snap/cmd_debug_features.go, cmd/snap/cmd_debug_features_test.go, daemon/api.go, daemon/api_debug.go, daemon/api_debug_features_test.go, daemon/export_api_debug_test.go
This adds a features aspect to the /v2/debug endpoint as well as the command `snap debug features`. It returns the complete list of features (task and change kinds, interface names, ensure functions, endpoints, and complete snap command names).
=> cmd, api: add debug features to get complete list of features

interfaces/builtin/usb_gadget.go, interfaces/builtin/usb_gadget_test.go, tests/lib/snaps/test-snapd-policy-app-consumer/meta/snap.yaml, tests/main/document-interfaces-url/task.yaml
Tested creating a device using usbg examples from their repo
```
philip@ubuntu:~/usbg$ sudo usbg.create
```
Tested listing it again from the snap
```
philip@ubuntu:~/usbg$ usbg.list
ID 1d6b:0104 'g1'
UDC                   1000480000.usb
bcdUSB                2.00
bDeviceClass          0x00
bDeviceSubClass       0x00
bDeviceProtocol       0x00
bMaxPacketSize0       64
idVendor              0x1d6b
idProduct             0x0104
bcdDevice             0.01
Language:     0x409
Manufacturer        Foo Inc.
Product             Bar Gadget
Serial Number       0123456789
Function, type: acm instance: usb0
port_num            0
Function, type: acm instance: usb1
port_num            1
Function, type: ecm instance: usb0
dev_addr            76:3c:97:5b:5f:1
host_addr           26:ab:7d:9e:8f:9e
ifname …
```
=> i/builtin: add usb-gadget interface

daemon/access.go, daemon/access_test.go, daemon/export_access_test.go
This PR adds the following:
- `byActionAccess` access checker decides which access checker to use based on the JSON `action` field `{"action": "<action>"}` to allow using different access checkers based on the target action.
-  This is intended to be used by the `/v2/system-volumes` endpoint but can also be used for similar action-based endpoints if needed.
- `interfaceRootAccess` access checker to allow root requests over `snapd-snap.socket` for snaps that have a connection of specific interface and are present on the plug side of that connection.
- add optional polkit support to root* access checkers
Example of how those new access checkers would be used:
```go
var systemVolumesCmd = &Command{
Path: "/v2/system-volumes",
GET:  getSystemVolumes,
POST: postSystemVolumesAction,
ReadAccess: …
```
=> daemon: add access checkers needed for /v2/system-volumes endpoint

confdb/confdb.go, confdb/confdb_test.go
Support paths with indexes (both literal and placeholder) in the Get() and support traversing JSON lists when reading data from databags.
=> confdb: support JSON lists when reading databag

tests/main/snap-session-agent-service-control/task.yaml, tests/main/snap-session-agent-socket-activation/task.yaml
The apparmor profile in 25.10 is currently blocking access to unix sockets that live anywhere outside of $HOME. Using the snap allows us to get around that.
=> tests: use test-snapd-curl snap since curl in 25.10 has a strict apparmor profile

overlord/confdbstate/confdbstate.go, overlord/confdbstate/confdbstate_test.go
Fix a small but misleading typo in an error message
=> o/confdbstate: fix incorrect error message

daemon/api.go, daemon/api_system_volumes.go, daemon/api_system_volumes_test.go, data/polkit/io.snapcraft.snapd.policy
Some actions under /v2/system-volumes need more relaxed access checks, otherwise a default (root or admin via polkit) access checker is used.
Relevant specs: [SD201](https://docs.google.com/document/d/1Mbj7Ut0tgW0PCz8VWdhvBN52kHTxYqkZZKQODB1NlLk/edit?tab=t.0), [FO167](https://docs.google.com/document/d/1qSWhO9EHXNdsz-6NtJljDKPkMEsWY7yYkayO5fmDeng/edit?tab=t.0), [FO197](https://docs.google.com/document/d/1es6k72MUv71wVi5oEZcZ4IMo4p13kA-4aVyOMWv4LTI/edit?tab=t.0)
JIRA: [SNAPDENG-35271](https://warthogs.atlassian.net/browse/SNAPDENG-35271)
[SNAPDENG-35271]: https://warthogs.atlassian.net/browse/SNAPDENG-35271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> daemon: set per-action access checkers for /v2/system-volumes

.github/workflows/weekly-feature-tagging.yaml, tests/utils/features/feattranslator.py, tests/utils/features/mongo_upload.py, tests/utils/features/test_feattranslator.py
~Assumes the changes in https://github.com/canonical/snapd/pull/15684 for the structure of the data from `snap debug features`~
This translates the output data into the same format as the feature tagging data and then uploads the results to mongo, together with the other feature tagging data.
=> github, tests: upload complete list of feature tagging data to mongo

tests/utils/features/query_features.py, tests/utils/features/test_query_features.py
This assumes feature coverage data is transformed from this PR https://github.com/canonical/snapd/pull/15687
We currently don't enrich feature coverage information from snapd with details of the applicable snap types. This PR correspondingly limits the feature matches to exclude snap types when checking whether a given feature is present in a system or not.
Example:
The output of feature tagging from spread tests for tasks looks something like:
```json
{
"kind": "connect",
"last_status": "Done",
"snap_types": ["app", "snapd"]
},
{
"kind": "connect",
"last_status": "Done",
"snap_types": ["app", "app"]
}
```
While the feature coverage data from snapd for the "connect" task would look like:
```json
{
"kind": "connect",
"last_status": "Done",
},
{
"kind": "connect",
"last_status": "Undone", …
```
=> tests: change all feature comparisons to use not-exact matches for tasks, changes, and interfaces

interfaces/builtin/u2f_devices.go
This adds our new device and fixes the entry for the old device. Apparently, it needs lowercase letters.
OneSpan does not produce public documentation with our VID/PID, so I cannot link to it.
=> interfaces/builtin: add OneSpan device and fix older device for u2f interface

overlord/managers_test.go
`JoinPath` is available from go 1.19 on
=> overlord: use path.Join instead of url JoinPath

cmd/snap/cmd_run.go, cmd/snap/cmd_run_test.go, interfaces/builtin/kerberos_tickets.go, interfaces/builtin/kerberos_tickets_test.go, tests/main/document-interfaces-url/task.yaml, tests/main/interfaces-kerberos-tickets/kerberos-tickets-consumer/bin/kerberos-tickets-consumer, tests/main/interfaces-kerberos-tickets/kerberos-tickets-consumer/meta/snap.yaml, tests/main/interfaces-kerberos-tickets/task.yaml
Expose Kerberos tickets in /tmp to snaps via the hostfs.
The snaps will need to connect the kerberos-ticket interface (slot also here provided) to actually be able to read the tickets.
[LP: #1849346](https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1849346)
[UDENG-7057](https://warthogs.atlassian.net/browse/UDENG-7057)
[UDENG-7057]: https://warthogs.atlassian.net/browse/UDENG-7057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> intefaces/builtin, cmd/snap: Kerberos tickets support

spread.yaml
These new environments can be used for development. In all cases we need to run tests from the VPN.
It is important that we have an env var OS_CREDENTIALS_STG_AMD64_PS7 and OS_CREDENTIALS_STG_ARM64_PS7 poiting to the credential files used to connect.
=> tests: new dev environments in ps7

go.mod, go.sum
This contains the fix needed for pre-OS verification events: https://github.com/canonical/secboot/pull/442
=> go.mod: update secboot

.woke.yaml, osutil/vfs/tests/bind-semantics/task.yaml
This test is simple in principle and answers the question: how do propagation settings of a bind mount source and bind mount destination affect the propagation settings of the new mount created by the bind operation.
=> osutil/vfs: add test for bind mount propagation sharing semantics

cmd/Makefile.am
Fix how snap-confine profile is installed when using 'make hack'. Install the appropriate profile for the target system. This avoids situation when on Arch or openSUSE, one could end up with 2 AppArmor profiles for snap-confine, one in usr.lib.snapd.snap-confine and another in usr.lib.snapd.snap-confine.real. This causes a situation in which a parallelized profile loading at boot time which would nondeterministically put one or the other profile in effect.
=> cmd: fix installation of snap-confine profile with 'make hack'

tests/lib/nested.sh
spread-plus does not work on 20.04 or earlier because it depends on glibc ABI that is not available there. So for
tests/nested/manual/minimal-smoke to work, we need to fallback on older builds of spread. Those are used only for external backend anyway.
=> tests/lib/nested.sh: download older spread on 20.04 and earlier

boot/export_test.go, boot/makebootable.go, boot/makebootable_test.go, boot/seal.go, boot/seal_test.go, cmd/snap-bootstrap/cmd_initramfs_mounts.go, overlord/devicestate/devicemgr.go, overlord/devicestate/devicestate_test.go, overlord/devicestate/export_test.go, overlord/devicestate/handlers_install.go, overlord/fdestate/backend/seal.go, overlord/fdestate/backend/seal_test.go, secboot/secboot_dummy.go, secboot/secboot_hooks.go, secboot/secboot_sb_test.go
This is a preliminary change split out from the main OPTEE branch. Will eventually be used to integrate OPTEE.
=> many: introduce KeyProtectorFactory abstraction to prepare for optee changes

overlord/notices/export_test.go, overlord/notices/notices.go, overlord/notices/notices_test.go, overlord/state/notices.go, overlord/state/notices_test.go
This PR is the `overlord/notices` changes from #15556.
Define a `NoticeManager` struct and a `NoticeBackend` interface. Particular backends which implement the `NoticeBackend` interface may be registered with a `NoticeManager` as providers of a particular notice type, along with a unique namespace which must occur as a prefix to the ID of any notice of that type produced by that backend.
A particular backend may be registered as a provider of more than one notice type, as long as the namespace prefix registered for that backend and type is unique. Similarly, multiple backends may be registered as providers of the same notice type, as long as each has a unique namespace prefix.
Snapd state is an implicit backend for any notice types which have no registered backends. Notices from state …
=> overlord/notices: add notice manager and notice backend interface

tests/main/debug-pprof/task.yaml
openSUSE has packaged go 1.25 release candidate and there are some issues with packaging that cause pprof to fail.
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-35300
=> tests: exclude debug-pprof test on openSUSE Tumblweed

.github/workflows/rerun.yaml
The condition on the rerun via workflow dispatch was incorrect. There is no `github.event.workflow_dispatch` object, but I verified that the `github.event_name` is `workflow_dispatch` when the workflow was called via dispatch
=> github: fix if condition for triggering a rerun via dispatch

packaging/snapd.mk
Pass tags when running unit tests.
=> packaging/snapd.mk: pass tags when running unit tests

interfaces/builtin/u2f_devices.go, interfaces/builtin/u2f_devices_test.go
Add The Kensington VeriMark DT Fingerprint to the u2f devices.
=> interfaces: add Kensington VeriMark DT Fingerprint Key to u2f devices

daemon/api_notices.go, overlord/overlord.go
~~This PR is based on #15673, only the final commit(s) are relevant.~~
Initialize a new `NoticeManager` after state is loaded from disk, and expose it under a new `NoticeManager()` method on the overlord.
Then, for the notices endpoints which query existing notices, switch from querying notices directly from state, and instead query via the overlord's notice manager.
The goal of this is that if there is an API request for notices which is satisfied by notice backends outside of state, then there is no need to acquire state lock in order to process that notices request, and the notice manager can instead only query the relevant notice backends.
This work is tracked internally by https://warthogs.atlassian.net/browse/SNAPDENG-35275
=> daemon,overlord: use notice manager and query from daemon

gadget/gadget.go, gadget/gadget_emmc_test.go, gadget/gadget_test.go, gadget/gadgettest/examples.go, gadget/install/partition.go, gadget/install/partition_test.go, gadget/layout.go, gadget/ondisk_test.go, gadget/update.go, gadget/update_test.go
Improve emmc handling from a disk-traits and compatibility perspective, this should fix the varying underlying disk schema when emmc is validated.
This should fix the following error during seeding
```
execution error: cannot gather disk traits for device /dev/mmcblk0 to use with volume emmc-boot: volume emmc-boot is not compatible with disk /dev/mmcblk0: disk partitioning schema "gpt" doesn't match gadget schema "emmc"
```
This PR also tackles an oversight in behaviour, which makes the feature more in line with the spec, we remove the requirement of `size` and add more explicit checking code.
=> gadget: improve (and fix) how we handle emmc volumes

tests/utils/features/dashboard.py, tests/utils/features/dashboard_callbacks.py, tests/utils/features/query_features.py, tests/utils/features/test_query_features.py
Changes:
- Change the `-` lookalike to an `_` in the feature exploration section. The lookalike's original purpose was to not allow the GUI to wrap systems names. However, the `-` lookalike in feature exploration made it difficult to search systems because it was not possible to search for system names that included a `-` (e.g. one could only search for `18` but not `core-18`). 
- Makes matching snap types optional (by adding a boolean switch) in feature coverage comparison between systems.
- Adds a modal popup to coverage diff and system coverage sections.
When a user clicks on a feature, a popup will open with the list of tests that contain that feature.
=> tests: add modal popups with test lists in feature tagging dashboard

.github/workflows/spread-tests.yaml
Spread errors during restore could mean unsuccessful artifact retrieval. When the workflow's goal is to retrieve artifacts and spread had errors during restore, this adds a check to go through all tests and make sure that all those without data are considered failed.
=> github: when retrieving artifacts, fail tests without successful artifact download

tests/lib/assertions/developer1-network-confdb.json, tests/lib/assertions/developer1-network.confdb, tests/main/confdb/task.yaml
Adds spread test coverage for lists and indexed path reads/set/unsets to an existing confdb test.
=> tests: add spread coverage for lists and indexed paths

osutil/vfs/export_test.go, osutil/vfs/mount.go, osutil/vfs/vfs.go
The change is perhaps tiny but helps greatly in upcoming operations. The main benefit is that the suffix of the mount is no longer interested as to where it is exactly attached. Recursive bind, pivot root and mount move operation all change that location. With the new design most of the operations will no longer need to touch the new `mount.attachedAt` value, but merely invalidate the mount point cache.
=> osutil/vfs: replace [mount.mountPoint] with [mount.attachedAt]

tests/main/interfaces-posix-mq/task.yaml
We were mislead to believe that the test works on the kernel present in Ubuntu 20.04 (focal) because up until recently the CI/CD stack used virtual machines allocated in GCE (Google Compute Engine). GCE kernels are somewhat more recent than their regular counterparts and happened to contain mqueue support that is present in later kernels.
It's probably something we should have noticed when we excluded Ubuntu Core 20 which had the same kernel as Ubuntu 20.04, but at the time the test just passed so why would we.
Interestingly the 5.4.0 kernel used on Ubuntu 20.04 doesn't even advertise the mqueue feature:
```
garden:ubuntu-20.04-64 .../tests/main/interfaces-posix-mq# uname -a
Linux ubuntu-20-04 5.4.0-216-generic #236-Ubuntu SMP Fri Apr 11 19:53:21 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux …
```
=> tests: disable the interfaces-posix-mq test on Ubuntu 20.04

tests/main/document-interfaces-url/task.yaml
Add a sleep when teh status code returned is 000, which means that a connection to the server could not be established.
The sleep helps to add extra time to avoid connections issues.
=> tests: fix document-inetrfaces-url test when connection fails

.woke.yaml, osutil/vfs/tests/propagation-to-shared-slave/expected.txt, osutil/vfs/tests/propagation-to-shared-slave/task.yaml, osutil/vfs/tests/propagation-to-shared-subdirectory/expected.txt, osutil/vfs/tests/propagation-to-shared-subdirectory/task.yaml, osutil/vfs/tests/root-dir-mount-point-optional-fields-and-source.awk
The sub-directory test shows how having a peer group member that sees a subtree of a file system may cause it to not observe some events and translate attachment of all events it does see.
The shared-slave test extends behavior to show secondary propagation (from shared to slave which
is separately shared and to its peers).
A new helper script that shows somewhat more information is used in those two tests.
=> osutil/vfs/tests: add more tests for propagation

tests/lib/muinstaller/mk-classic-rootfs.sh
http://cdimage.ubuntu.com/ubuntu-base/releases/24.04/release/ubuntu-base-24.04.2-base-amd64.tar.gz is not available anymore. Change to new .3 which is now available. This solves below  error as seen for e.g. tests/nested/manual/muinstaller-real.
```cannot create classic rootfs: 
stderr:
+ DST=/run/muinstaller-mnt/ubuntu-data
+ '[' '!' -d /run/muinstaller-mnt/ubuntu-data ']'
+ ROLE=
+ '[' -f /cdrom/casper/base.squashfs ']'
+ BASETAR=ubuntu-base.tar.gz
++ lsb_release -r -s
+ release=24.04
+ case "$release" in
+ pointrel=.2
+ wget -q -c http://cdimage.ubuntu.com/ubuntu-base/releases/24.04/release/ubuntu-base-24.04.2-base-amd64.tar.gz -O ubuntu-base.tar.gz
```
=> tests/lib/muinstaller: change 24.04 ubuntu base to .3

tests/utils/features/state.py
When the snap type is not found in the state.json, raise NotInStateError rather than RuntimeError
=> tests: raise NotInStateError when snap type not found

cmd/Makefile.am, cmd/snap-confine/snap-confine.c, cmd/snap-confine/snap-confine.caps, cmd/snap-confine/snap-confine.v2-only.caps, data/selinux/snappy.te, packaging/arch/snapd.install, packaging/debian-sid/snapd.install, packaging/debian-sid/snapd.postinst, packaging/fedora/snapd.spec, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/snapd.install, packaging/ubuntu-16.04/snapd.install.in, tests/main/lxd/task.yaml, tests/main/snap-confine-caps/task.yaml
Snap-confine contains cgroup-v1-specific behavior: the use of the freezer group
for both application tracking and consistency guarantee for snap-update-ns that
may be concurrently modify the mount namespace.
The switch to capability-based snap-confine missed the fact that moving
processes within a cgroup is governed by additional constraints that no
capabilities can remedy. The process making the move must either be a global
root (not in the process namespace) or the UID of the process being moved (here
snap-confine moves itself) must match the UID of the target cgroup hierarchy.
This is not true in LXD containers that use user namespaces.
The failure was introduced in snapd 2.70 but due to a faulty test, was not
detected until after the release.
The fix alters the freezer join logic to …
=> cmd/snap-confine: switch to root:root to operate v1 freezer

overlord/fdestate/fdemgr.go, overlord/fdestate/fdemgr_test.go, overlord/fdestate/fdestate.go, overlord/fdestate/fdestate_test.go, overlord/hookstate/ctlcmd/export_test.go, overlord/hookstate/ctlcmd/system_mode.go, overlord/hookstate/ctlcmd/system_mode_test.go, tests/nested/manual/muinstaller-core/task.yaml, tests/nested/manual/muinstaller-real/task.yaml
Extended snapctl system-mode to detect if system is encrypted.
The proposed method of detecting FDE is based on the presence of a primary key in the FDE state.
This method does not work for specific legacy scenarios:
- v1 TPM keys are in used because an old snapd was used during installation
- snap-bootstrap in the kernel is old and does not provide a primary key in the keyring
[See details](https://github.com/canonical/snapd/blob/master/overlord/fdestate/fdestate.go#L165).
Spec: [SD201 | Heading: Detect system storage encryption](https://docs.google.com/document/d/1Mbj7Ut0tgW0PCz8VWdhvBN52kHTxYqkZZKQODB1NlLk/edit?tab=t.0#heading=h.f54182akcjzb)
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-35246
=> o/fdestate, o/h/ctlcmd: extended snapctl system-mode to detect if system is encrypted

overlord/hookstate/ctlcmd/system_mode.go
Tiny fix for formatting on master.
=> o/hookstate/ctlcmd: fix formatting

client/change.go, client/change_test.go, cmd/snap/cmd_snap_op.go, cmd/snap/cmd_snap_op_test.go, tests/main/snapshot-basic/task.yaml
Add a note in the output when a snapshot of snap's data was created when
removing a snap.
Related: SNAPDENG-35165
Fixes: LP#2114704
=> client/snap: add a note when snap data snapshot was created during remove

packaging/fedora/snapd.spec
Drop fakeroot as build dependency.
=> packaging/fedora: drop fakeroot

overlord/confdbstate/confdbstate.go, overlord/hookstate/ctlcmd/get.go, overlord/hookstate/ctlcmd/get_test.go, overlord/hookstate/ctlcmd/set.go, tests/main/confdb/task.yaml
Add a check in snapctl that the confdb plug is actually connected. Also adds spread test coverage
=> o/h/ctlcmd: check confdb plug connection in snapctl

daemon/api_system_recovery_keys.go, overlord/install/install.go
25.10 is Questing not Plucky, renamed function accordingly.
=> o/install, daemon: rename CheckHybridPluckyRelease to CheckHybridQuestingRelease

osutil/vfs/tests/bind-semantics/task.yaml
I used the pattern where capital letters A and B are actual file system mounts and lower-case letters are directories that are bind mounted. I also expanded both the measured data and the data that is displayed for each measurement.
=> osutil/vfs/tests: expand bind-semantics test for better clarity and visibilty

.image-garden.mk
Add support for local overrides files, where one can redefine variables or targets.
=> image-garden: include optional local overrides file

tests/main/snap-user-service/task.yaml
Instead of checking against specific service count, just make sure the service we care about is there / not there with the correct enable/active statuses.
On core, there is the 'rsync' service present.
=> t/m/snap-user-service: varying number of services between core and classic

cluster/assemblestate/devices.go, cluster/assemblestate/devices_test.go
This data structure helps facilitate tracking device identities. It also tracks queries from device information from our peers. Additionally, it tracks when we should query our peers for device identities based on their knowledge.
=> c/assemblestate: add DeviceQueryTracker implementation

desktop/desktopentry/desktopentry_test.go, overlord/snapstate/snapstate_test.go, snap/info_test.go, tests/main/install-sideload/task.yaml, tests/main/parallel-install-desktop/task.yaml, usersession/userd/privileged_desktop_launcher_test.go, wrappers/desktop.go, wrappers/desktop_test.go
This is something that was only supported by Unity desktop and it was not particularly well designed either (as sandboxed apps might have been not properly matched), so after many years I think it's safe to drop it given that unity is not anymore used in any major distros for many years
At the same time for those that may be affected, I've updated BAMF to do some better matching in the snap case [1].
So we may consider to SRU it if many people will be affected, but I feel dropping this obsolete (and not clean) code is safe nowadays.
[1] https://git.launchpad.net/bamf/commit/?id=9183645dc5
=> snap: Drop legacy BAMF_DESKTOP_FILE_HINT in desktop files

secboot/secboot.go, secboot/secboot_dummy.go, secboot/secboot_sb.go, secboot/secboot_sb_test.go, secboot/secboot_tpm.go
This PR adds a secboot helper for adding new TPM protected keys, this is split from https://github.com/canonical/snapd/pull/15705.
=> secboot: add helper for adding new TPM protected keys

.github/workflows/ready-for-review-checker.yaml
This adds a workflow to trigger only when a PR moves from draft to ready to review. It checks if the "Run only one system" label is present. If it is, then it removes it and attempts to rerun the "read-systems" job. If it is unable to do so because the workflow is currently running, then it comments on the PR (overwriting spread results) that it was unable to automatically rerun the job.
=> github: add automatic label removal and relevant job rerun

.github/workflows/data-non-fundamental-systems.json, spread.yaml, tests/main/cloud-init/task.yaml, tests/main/docker-smoke/task.yaml, tests/main/interfaces-mount-control-cifs/task.yaml, tests/regression/lp-1910456/task.yaml
Move arm tests from google to openstack ps7
Migrating from ubuntu-22.04-arm-64 to ubuntu-24.04-arm-64 because kernel in jammy does not support the apparmor prompting features, so all those tests have to be skipped if tests are executed in jammy,
unit tests fixed in https://github.com/canonical/snapd/pull/15735
=> tests: run spread tests in ps7 arm environment

interfaces/kmod/spec.go
=> interfaces/kmod: fix comment to mention kmod rather than mount

interfaces/systemd/service.go, interfaces/systemd/service_test.go
`WantedBy` is not supported under `[Unit]` and was giving the following warning:
> Unknown key name 'WantedBy' in section 'Unit', ignoring
=> i/systemd: move WantedBy option to [Install] section

interfaces/builtin/u2f_devices.go
This PR adds Thetis FIDO2 BioFP+ Security Key, to the U2F allow list.
The security key is also known as ExcelSecu FIDO2 Security Key, which is shown by lsusb and can be seen in probes of two computers at https://linux-hardware.org/?id=usb:1ea8-fc26
Other relevant web pages:
- Thetis: https://thetis.io/products/fido2-fingerprint-key
- Excelsecu: https://www.excelsecu.com/productdetail/esecufido2secu.html
I have used a Thetis FIDO2 BioFP+ Security Key successfully with Firefox (141.0.3-1) and a modified /etc/udev/rules.d/70-snap.firefox.rules.
=> interfaces/builtin: add Thetis FIDO2 BioFP+ Security Key to U2F list

packaging/ubuntu-16.04/source/options
Ignore the contents of .image-garden.
=> packaging/ubuntu-16.04/source/options: ignore .image-garden content

spread.yaml
This is needed to setup the proxy properly in the machines used to run the upgrade test suite
=> tests: use the proper prepare/restore functions in the upgrade suite

tests/main/snap-user-service/task.yaml
On openSUSE/Fedora/Arch, the snapd.session-agent.socket is not enabled by default during package installation. Make sure those systems are skipped.
=> tests/main/snap-user-service: skip more systems

snap/info.go, snap/info_snap_yaml.go, snap/info_snap_yaml_test.go, snap/types.go, store/details_v2_test.go
Modifications:
- info.go Ln 384 - Added Grade field of type GradeType to Info structure
- types.go Ln 113 - Added GradeType (string)
- types.go Ln 117 - 118 - Added two default grade types, representing "devel" or "stable"
- info_snap_yaml.go Ln 50 - Added Grade field of type GradeType to snapYaml structure 
- info_snap_yaml.go Ln 255-260 - Added grade field validation, invalid field will throw error
- info_snap_yaml.go Ln 293-297 - If grade is empty set as "devel" for default
- info_snap_yaml.go Ln 312 - Added grade initialization in infoSkeletonFromSnapYaml()
- - info_snap_yaml_test.go Ln 2363 - 2398 - Added three tests for snap.yaml with "stable", "invalid", and "" as the three test cases.
=> snap: added 'Grade' field to  types.go, info.go, and info_snap_yaml.go

cmd/snap-bootstrap/cmd_initramfs_mounts.go, core-initrd/latest/factory/usr/lib/systemd/system/core-ensure-kernel-in-sysroot.service, core-initrd/latest/factory/usr/lib/systemd/system/initrd-core-system-defaults.service, core-initrd/latest/factory/usr/lib/systemd/system/initrd-core-tmpfiles-setup.service, core-initrd/latest/factory/usr/lib/systemd/system/initrd-parse-etc.service.wants/core-ensure-kernel-in-sysroot.service, core-initrd/latest/factory/usr/lib/systemd/system/initrd-root-fs.target.wants/initrd-core-system-defaults.service, core-initrd/latest/factory/usr/lib/systemd/system/initrd-root-fs.target.wants/initrd-core-tmpfiles-setup.service, core-initrd/latest/factory/usr/lib/systemd/system/populate-writable.service, core-initrd/latest/factory/usr/lib/systemd/system/sysroot-run-mnt-kernel.mount, core-initrd/latest/factory/usr/lib/systemd/system/sysroot-run.mount, core-initrd/latest/factory/usr/lib/systemd/system/sysroot-writable.mount
Rebase of https://github.com/canonical/core-initrd/pull/74 but keeping backward compatibility for now.
This goes along https://github.com/canonical/core-base/pull/25
=> core-initrd: do not use writable-paths when not available

interfaces/builtin/gpio_chardev.go, interfaces/builtin/gpio_chardev_test.go
`BeforeConnectPlug` under the `gpio-chardev` interface is called before the kmod backend loads the `gpio-aggregator` module so it will always be reported as not supported.
To fix it, now load the module if a snap that plugs `gpio-chardev` is detected without being connected.
=> i/builtin: fix gpio-aggregator module not being loaded in the right order

interfaces/builtin/unity7.go
This was missed in https://github.com/canonical/snapd/pull/14061
=> i/builtin: remove stale apparmor rules placeholder SNAP_DESKTOP_FILE_RULES

tests/main/mounts-persist-refresh-content-snap/task.yaml, tests/main/mounts-persist-refresh-content-snap/test-snapd-desktop-layout-with-content/bin/crash-foo-font
A few small improvements to the test I've been looking at for the past few days.
=> tests: small improvements to mounts persist refresh content

interfaces/builtin/all_test.go, interfaces/builtin/common.go, interfaces/builtin/gpio_chardev.go, interfaces/core.go, interfaces/ifacetest/testiface.go, interfaces/repo.go, interfaces/repo_test.go
This PR adds the ability for an interface to define a set of exclusive connected interfaces, this is needed when two interfaces cannot be connected at the same time e.g. `gpio-chardev` and `gpio`.
=> interfaces: support setting exclusive snap connections

tests/lib/prepare.sh
It seems detection of squashfs format is broken on some platforms and fails the spread tests. Forcing squashfs should help.
=> tests/lib/prepare.sh: Mount snap as squashfs

build-aux/snap/snapcraft.yaml
Bump the version of FIPS Go toolchain to 1.23, same version we use for other builds.
Related: [SNAPDENG-35096](https://warthogs.atlassian.net/browse/SNAPDENG-35096)
[SNAPDENG-35096]: https://warthogs.atlassian.net/browse/SNAPDENG-35096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> snapcraft: bump FIPS toolchain to 1.23

cmd/snap-gpio-helper/cmd_export.go, sandbox/gpio/common.go, sandbox/gpio/export_test.go, sandbox/gpio/gpio_chardev.go, sandbox/gpio/gpio_chardev_test.go, tests/core/interfaces-gpio-chardev/task.yaml
This PR re-enables the `gpio-chardev` interface now with the more robust `gpio-aggregator` configfs kernel interface.
Note: This PR builds on top of the fix from https://github.com/canonical/snapd/pull/15848 and should be rebased
For context, Check the SD201 spec.
=> many: support gpio-aggregator configfs kernel for gpio-chardev

boot/makebootable.go, boot/makebootable_test.go, overlord/configstate/configcore/kernel.go, overlord/configstate/configcore/kernel_test.go, tests/nested/manual/cmdline-option/defaults.yaml, tests/nested/manual/cmdline-option/task.yaml
Add kernel command line coming from defaults in gadget.yaml to the modeenv so
we seal against the correct arguments. Fixes LP#2120717.
Also, if not seeded, we do not want to create an update kernel command line change that
comes from the gadget defaults, as those have already been applied to the
current kernel command line on installation. This created an unexpected error
messages as a conflict was detected. Fixes LP#2120184.
Add checks for this in spread test.
=> boot: make sure that we seal properly with kernel command line defaults

tests/main/docker-smoke/task.yaml, tests/regression/lp-1910456/task.yaml
In Questing, the new curl profile prevents saving a file in the current directory in spread. This saves it to the home directory and moves it back to the testing directory to get around the profile's restrictions.
=> tests: have curl save tar to home directory in docker-smoke and lp-1910456

.github/workflows/data-nested-systems.json, .github/workflows/nightly-cross-build.yml, .github/workflows/nightly-spread.yaml
Run nightly executions in openstack instead of google
=> tests: move nightly executions to openstack

cmd/snap-bootstrap/blkid/mock_blkid.go, cmd/snap-bootstrap/cmd_scan_disk.go, cmd/snap-bootstrap/cmd_scan_disk_test.go
When installing from initramfs using a preseeded image on the rpi, two issues where observed in the logs.
One, udev can become retriggered during installation (when creating partitions), which causes retriggering scan-disk command.
Scan-disk then fails because LABEL is not available as the partition has not been formatted. Because this fails, udev then proceeds to remove the disk again, making the main snap-bootstrap process die.
The second issue is that loop devices created from snap mounts can make scan-disk crash as well, as no partitions are returned.
Fix has been manually verified on my Raspberry Pi 4 with a repacked initramfs and a preseeded image.
=> cmd/snap-bootstrap: robustness in terms of scanning disks

interfaces/builtin/xilinx_dma.go, interfaces/builtin/xilinx_dma_test.go
Support both qdma-pf and qdma-vf modes
When a queue is created and started, the driver will create a device entry (such as `/dev/qdma01000-MM-0`) dynamically for applications to use.
The configuration entries will be in the PCIe device entries of sysfs. For instance:
`/sys/devices/pci0000:00/0000:00:01.1/0000:01:00.0/qdma/`.
The hardware-observe interface may also be required for an application to gather hardware information before accessing the actual QDMA device.
=> i/b/xilinx-dma: support Multi Queue DMA (QDMA) IP

client/clientutil/snapinfo.go, client/clientutil/snapinfo_test.go, client/packages.go, cmd/snap/cmd_info.go, cmd/snap/cmd_info_test.go, snap/types.go, tests/lib/snaps/basic/meta/snap.yaml, tests/main/snap-info/task.yaml
- Client: Added Grade field to Snap struct, and modified clientutil  to properly convert from a Snap.Info to a client.Snap, modified tests accordingly.
- Cmd: Added code to print grade when printing snap info with --verbose flag, modified tests to check output of Snaps with "stable", "devel", and "", the three supported grades.
=> client, clientutil, cmd: Add Grade field to Client.Snap -SNAPDENG-34170

interfaces/builtin/hardware_observe.go
This PR is a continuation of this [previous one](https://github.com/canonical/snapd/pull/15844), and its aim is to reduce the error logs in node-exporter running as a strictly confined snap. 
More info: https://forum.snapcraft.io/t/should-some-snapd-interfaces-be-modified/48242/11?u=abuelodelanada
=> interfaces:  read access to ksm (Kernel Samepage Merging) added

interfaces/builtin/fwupd.go
Fixes: upstream issue: https://github.com/fwupd/fwupd/issues/9203
=> i/b/fwupd: allow access to intel cvs sysfs

overlord/fdestate/conflict.go, overlord/fdestate/export_test.go, overlord/fdestate/fdemgr.go, overlord/fdestate/fdestate.go, overlord/fdestate/fdestate_test.go, overlord/fdestate/handlers.go, overlord/fdestate/handlers_test.go, secboot/secboot.go
This helper is needed to currently implement root passphrase reset without providing the old passphrase but the implementation is generic enough that it can be used for more use cases like:
- Reset a passphrase/PIN without providing the old value
- Change key authentication mode, for example:
- Switch from passphrase to PIN authentication
- Switch from PIN to passphrase authentication
- Switch from no authentication to PIN or Passphrase authentication
- Switch from PIN or Passphrase authentication to no authentication
- Change key authentication options, i.e. KDF options
API spec proposal: [SD201](https://docs.google.com/document/d/1Mbj7Ut0tgW0PCz8VWdhvBN52kHTxYqkZZKQODB1NlLk/edit?tab=t.0#bookmark=id.8kjwg3jmkwny)
This PR is built on top of https://github.com/canonical/snapd/pull/15758 …
=> o/fdestate: support protected keys replacement

tests/core/interfaces-gpio-chardev/task.yaml
extend test to check gadget refresh disconnects gpio connections to make sure that what is recommended in the docs when migrating from gpio to gpio-chardev is tested.
https://snapcraft.io/docs/gpio-chardev-interface
> ### Migration from gpio to gpio-chardev
>
> Since gpio and gpio-chardev interfaces cannot be connected at the same time, all existing gpio interface connections must be disconnected first before connecting to gpio-chardev.
>
> This is only required if the gadget snap has both gpio and gpio-chardev slots declared since performing a gadget refresh to a revision that only declares gpio-chardev slots will automatically disconnect gpio connections due to missing slot.
>
> It is recommended to only have only one slot type on the gadget, either gpio or gpio-chardev.
=> tests/core/interfaces-gpio-chardev: extend test to check gadget refresh

interfaces/prompting/prompting.go, interfaces/prompting/requestprompts/requestprompts.go, interfaces/prompting/requestprompts/requestprompts_test.go, overlord/ifacestate/apparmorprompting/prompting.go, overlord/ifacestate/apparmorprompting/prompting_test.go, sandbox/apparmor/notify/listener/export_test.go, sandbox/apparmor/notify/listener/listener.go, sandbox/apparmor/notify/listener/listener_test.go
Include the cgroup path in prompts so that prompts related to different processes of the same application instance can be identified as belonging to that same instance.
This work is tracked internally by https://warthogs.atlassian.net/browse/SNAPDENG-35444
=> many: include request cgroup in prompt

store/download_test.go, store/export_test.go, store/store_action_test.go, store/store_download.go, store/store_download_test.go
Use the shared client setup helpers, thus ensuring we are using whatever http(s) proxy passed in the store's configuration.
While at it, extend the unit tests a bit so that the use of a configured proxy is also checked for snap downloads and action requests.
Related: [SNAPDENG-35461](https://warthogs.atlassian.net/browse/SNAPDENG-35461)
[SNAPDENG-35461]: https://warthogs.atlassian.net/browse/SNAPDENG-35461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> store: use http(s) proxy for icon downloads, improve unit tests

.github/workflows/nightly-spread.yaml, spread.yaml
This workflow is executed nightly and runs some tests which cannot be executed in openstack due to proxy/other restrictions.
Also in spread.yaml the google-distro-1 and google-distro-2 have been unified in google-distro backend, as it is not needed to have separated backends anymore.
=> tests: new nigthly workflow execution in google backend

cmd/snap/cmd_version.go, cmd/snap/cmd_version_linux.go, cmd/snap/cmd_version_test.go, tests/smoke/versioning/task.yaml
Include information on system architecture in output of snap version.
Related: [SNAPDENG-35305](https://warthogs.atlassian.net/browse/SNAPDENG-35305)
Fixes: [LP#2043406](https://bugs.launchpad.net/snapd/+bug/2043406)
[SNAPDENG-35305]: https://warthogs.atlassian.net/browse/SNAPDENG-35305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> cmd/snap: add system architecture to snap version output

tests/lib/nested.sh
Fix issue identified in https://github.com/canonical/snapd/actions/runs/17466738684/job/49690619454?pr=15921.
The issue relates to changes made in https://github.com/canonical/snapd/pull/15799.
openstack-ext-ps7:ubuntu-24.04-64:tests/nested/manual/recovery-system-reboot:recover failed with:
```
2025-09-05T13:38:32.1053457Z remote.wait-for: snap command ready
2025-09-05T13:38:32.1054198Z + tests.nested setup-vm
2025-09-05T13:38:32.1055229Z nameserver 10.151.11.5
2025-09-05T13:38:32.1055956Z nameserver 10.151.11.6
2025-09-05T13:38:32.1056262Z nameserver 10.151.11.7
2025-09-05T13:38:32.1057024Z HTTPS_PROXY=http://egress.ps7.internal:3128
2025-09-05T13:38:32.1057827Z https_proxy=http://egress.ps7.internal:3128
2025-09-05T13:38:32.1058263Z HTTP_PROXY=http://egress.ps7.internal:3128 …
```
=> tests/lib: setup-vm should also stop snapd.socket before changing proxy configuration

tests/main/apparmor-prompting-snapd-startup/task.yaml
Avoid using apt without -y
This prevents thie error:
Upgrading:
libattr1
Installing:
attr
Summary:
Upgrading: 1, Installing: 1, Removing: 0, Not Upgrading: 75
Download size: 35.7 kB
Space needed: 152 kB / 12.5 GB available
Continue? [Y/n] Abort.
=> tests: fix apparmor-prompting-snapd-startup by using tests.pkgs to install

overlord/ifacestate/apparmorprompting/export_test.go, overlord/ifacestate/apparmorprompting/noticebackend.go, overlord/ifacestate/apparmorprompting/noticebackend_test.go
This PR is based on #15932.
This is the second part of the notice backend implementation, split from #15768.
`BackendNotices` and `BackendWaitNotices` get real implementations here.
This work is tracked internally by https://warthogs.atlassian.net/browse/SNAPDENG-35196
=> o/i/apparmorprompting: implement methods to retrieve notices from backends

client/systems.go, daemon/api_systems.go, daemon/api_systems_test.go, daemon/export_api_systems_test.go, gadget/install/install.go, gadget/install/install_dummy.go, gadget/install/install_test.go, gadget/install/params.go, overlord/devicestate/devicemgr.go, overlord/devicestate/devicestate_install_api_test.go, overlord/devicestate/devicestate_install_mode_test.go, overlord/devicestate/devicestate_systems_test.go, overlord/devicestate/export_test.go, overlord/devicestate/handlers_install.go, overlord/install/install.go
Extend post /v2/system for error actions
This PR aim to complete part 2 based on [the complete POC](https://github.com/ernestl/snapd/pull/3)
The concept of caching encryption information existed at a daemon/api_systems.go level to avoid expensive preinstall check when only required to check if passphrase or pin is supported. This is now moved into devicestate, because the preinstall check context that is hidden in the encryption information structure also needs to be cached to enable follow-up preinstall checks with a specific action.
The preinstall check result needs to be stored in the save partition to configure optimum PCR configuration and enable resealing post install. The existing mechanism that transports encryption setup information between install steps …
=> many: extend post v2 system with error actions

client/system_volumes.go, daemon/api_system_volumes.go, daemon/api_system_volumes_test.go, daemon/export_api_system_volumes_test.go, gadget/device/encrypt.go, gadget/device/encrypt_test.go, overlord/fdestate/conflict.go, overlord/fdestate/conflict_test.go, overlord/fdestate/export_test.go, overlord/fdestate/fdemgr.go, overlord/fdestate/fdemgr_test.go, overlord/fdestate/fdestate.go, overlord/fdestate/fdestate_test.go, overlord/fdestate/handlers.go, overlord/fdestate/handlers_test.go, tests/nested/manual/passphrase-support-on-hybrid/task.yaml
This PR enables platform protected key replacement.
The new `/v2/system-volumes` action `replace-platform-key` action is needed to currently implement root passphrase reset without providing the old passphrase but the implementation is generic enough that it can be used for more use cases like:
- Reset a passphrase/PIN without providing the old value
- Change key authentication mode, for example:
- Switch from passphrase to PIN authentication
- Switch from PIN to passphrase authentication
- Switch from no authentication to PIN or Passphrase authentication
- Switch from PIN or Passphrase authentication to no authentication
- Change key authentication options, i.e. KDF options
API spec: [SD201](https://docs.google.com/document/d/1Mbj7Ut0tgW0PCz8VWdhvBN52kHTxYqkZZKQODB1NlLk/edit?tab=t.0#bookm …
=> many: add /v2/system-volumes action for replacing platform keys

tests/main/apparmor-prompting-snapd-startup/task.yaml
When running without reexecution, snapd built on systems which ship go 1.24+ (plucky and questing) obeys omitzero, and thus omits fields which were previously zero values. The snapd snap is built with go 1.23, for now. When this is bumped to 1.24+, this test will need to be updated again, making the lack of fields the default, and adding special cases for old systems when not reexecuting.
=> tests: account for omitzero in go 1.24+ for apparmor-prompting-snapd-startup

cmd/snap-update-ns/bootstrap.go, cmd/snap-update-ns/change.go, cmd/snap-update-ns/main.go, cmd/snap-update-ns/trespassing.go, interfaces/apparmor/template.go
When /run/snapd/ns/snap.$SNAP_NAME.log, for per-snap operations, or /run/snapd/ns/snap.$SNAP_NAME.user.$UID.log, for per-snap-and-user operations, file exists and can be written to, then configure it as a write-only (that is, without truncate) log.
This log captures all the operations performed by snap-confine and snap-update-ns, in relation to constructing and updating a persisted mount namespace of a given snap.
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-35498
=> cmd/snap-update-ns: add opt-in logging support

tests/main/document-interfaces-url/task.yaml
for the moment until they get stable.
=> tests/document-interfaces-url: do not document new GPU interfaces

tests/lib/tinyproxy/tinyproxy.py, tests/main/snap-network-errors/task.yaml
Extend tinyproxy to support blocking or stalling all requests. Update snap-network-errors to use that.
Related: [SNAPDENG-35419](https://warthogs.atlassian.net/browse/SNAPDENG-35419)
[SNAPDENG-35419]: https://warthogs.atlassian.net/browse/SNAPDENG-35419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> tests/main/snap-network-errors, tinyproxy: inject errors by using a custom proxy

spread.yaml, tests/main/sru-validation-check/task.yaml
Fix the test which fails with:
```
+ /usr/bin/env SNAPD_DEBUG=1 SNAP_REEXEC=1 snap list
/bin/bash: line 126: SNAPD_MOUNT_DIR: unbound variable
-----
```
and then with:
```
+ snap version
+ MATCH 'snap .+2.71\+24.04$'
snap    2.71+ubuntu24.04
snapd   2.71+ubuntu24.04
series  16
ubuntu  24.04
kernel  6.8.0-57-generic
```
=> tests/main/sru-validation-check, spread: fix test, add TODOs

tests/main/interfaces-libvirt/task.yaml
Explicitly specify libvirt connect URI. This seems to be required as driver auto detection ends up trying the session socket instead of the system one, even though the test theoretically keeps running as the test user.
Related: SNAPDENG-35497
=> tests/main/interfaces-libvirt: specify libvirt connect URI

daemon/api_general.go, daemon/api_general_test.go, tests/main/interfaces-ros-snapd-support/api-apps-client/bin/api-apps-client.py, tests/main/interfaces-ros-snapd-support/task.yaml
As discussed: https://forum.snapcraft.io/t/ros2-snapd-ros-snapd-support-and-snap-refresh-observe/47862/5
The `ros-snapd-support` interface should have its own access to `/v2/changes/{id}`
=> fix(ros-snapd-support): add access to /v2/changes/

cluster/assemblestate/assemblestate.go, cluster/assemblestate/assemblestate_internal_test.go, cluster/assemblestate/selector.go, cluster/assemblestate/selector_test.go
This will let us support a flag for setting an expected size on the command line, if we want that.
Based on https://github.com/canonical/snapd/pull/15829, only the top commit is relevant.
=> c/assemblestate: add concept of expected size

.github/workflows/ci-spread-times.yaml
SPREAD_USE_SNAPD_SNAP_URL and SPREAD_USE_PREBUILT_SNAPD_SNAP vars are set to be used by spread.
=> tests: use prebuilt snapd snap for testing times workflow

interfaces/compatibility/compatibility.go, interfaces/compatibility/compatibility_test.go, interfaces/compatibility/export_test.go, interfaces/compatibility/lex.go, interfaces/compatibility/lex_test.go, interfaces/compatibility/parse.go, interfaces/compatibility/parse_test.go
This implements a parser for compatibility expressions (SD211), which is a combination of compatibility labels with AND and OR operators, with the possibility of grouping expressions using parenthesis.
The lexer is loosely based on on go's text/template lexer. See https://www.youtube.com/watch?v=HxaD_trXwRE&t=2s for ideas behind this.
=> interfaces/compatibility: implement parser for compatibility expressions

overlord/confdbstate/confdbmgr.go, overlord/confdbstate/confdbstate.go, overlord/confdbstate/confdbstate_test.go, overlord/hookstate/ctlcmd/set.go, overlord/snapstate/autorefresh_gating_test.go, overlord/snapstate/conflict.go, overlord/snapstate/refresh.go, overlord/snapstate/refresh_test.go, overlord/snapstate/snapstate_test.go, tests/main/confdb/task.yaml, tests/main/confdb/waiting-custodian/bin/sh, tests/main/confdb/waiting-custodian/meta/hooks/load-view-wifi-setup, tests/main/confdb/waiting-custodian/meta/snap.yaml
Since conflict checks between other changes and confdb hooks are dealt with at the points where we unlink relevant snaps or run hooks, we can relax the conflict checks to let confdb accesses run concurrently with other changes.
=> o/snapstate: relax confdb change conflict checks

.github/workflows/ci-spread-times.yaml
These are new scenarios
1. spread -list
2. prepare/restore task avg times
=> tests: new scenarios for snapd test times

cmd/snap-seccomp/main_test.go
Apparently glibc attempts use some randomized values when setting up ptmalloc allocator. When the initial call to getrandom() fails, it will then proceed to call clock_gettime() in a loop, probably initializing the random seed from current time. When both system calls are blocked, the seccomp_syscall_runner appears to be stuck thus blocking the unit tests.
Fix that by allowing `getrandom()`.
=> cmd/snap-seccomp: fix unit tests running on questing with glibc 2.42

go.mod, go.sum
Update secboot to f8400226f49a to include FDE bug fix for Questing install image: https://github.com/canonical/secboot/pull/461
The commit is on the tip of secboot branch use-by-snapd-2.71 created in secboot PR: https://github.com/canonical/secboot/pull/463
=> secboot: update to f8400226f49a

NEWS.md, go.mod, go.sum, packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog, tests/lib/muinstaller/mk-classic-rootfs.sh
Follow-up of https://github.com/canonical/snapd/pull/15733 to update secboot revision f8400226f49a which with fix for possible panic when  secure boot is disabled: https://github.com/canonical/secboot/pull/461
DEBEMAIL="Ernest Lotter <[ernest.lotter@canonical.com](mailto:ernest.lotter@canonical.com)>" release-tools/changelog.py 2.71.1 2118396 NEWS.md
**Cherry-picks:**
- https://github.com/canonical/snapd/pull/16047
- https://github.com/canonical/snapd/pull/15794
This release is intended only to supersede deb release 2.71 only on Questing to fix this issue classic hybrid preinstall issue that was reported in  [LP: #2125439](https://bugs.launchpad.net/ubuntu-desktop-provision/+bug/2125439)
**Requires Rebase Merge**
=> release: 2.71.1

asserts/database.go
This will enable consumers of an `asserts.RODatabase` to perform more complex checks on sets of assertions, while still maintaining the immutability of the underlying database.
=> asserts: expose WithStackedBackstore in RODatabase

spread.yaml, tests/lib/prepare-restore.sh
This change allows to specify the ubuntu kernel version to be used for tests. This is an example to use this change.
Then this will be integrated with a new workflow which will be used to test snapd using the different supported kernels.
SPREAD_UPDATE_UBUNTU_^CRNEL_VERSION=6.2.0-32-generic spread -shell openstack-ps7:ubuntu-22.04-64:tests/main/abort
=> tests: define an ubuntu kernel version to use with spread tests

bootloader/lkenv/lkenv.go, cluster/assemblestate/assemblestate.go, cluster/assemblestate/intset/intset.go, cluster/assemblestate/selector.go, gadget/gadget_test.go, interfaces/prompting/requestprompts/requestprompts.go, interfaces/prompting/requestrules/requestrules.go, interfaces/prompting/requestrules/requestrules_test.go, osutil/exitcode.go, osutil/mount/libmount/libmount_linux.go, osutil/udev/netlink/rawsockstop.go, osutil/udev/netlink/rawsockstop_other.go, osutil/vfs/lists/iter.go, osutil/vfs/vfs.go, overlord/ifacestate/apparmorprompting/noticebackend.go, overlord/notices/notices.go, overlord/restart/restart.go, overlord/snapstate/snapstate_test.go, overlord/state/notices.go, run-checks, sandbox/apparmor/notify/notify.go, sandbox/apparmor/notify/strings.go, sandbox/cgroup/freezer.go, snap/container.go, store/tooling/tooling_test.go, strutil/joinerrors.go
Unsure if we want this, but it might make it easier to find these when we do update go. This is probably not comprehensive, just tried to grep around for things.
Some of these are actually fixable now, but I figured not good to mix in with this PR.
=> many: add TODO:GOVERSION to comments related to updating the go version

overlord/hookstate/context.go, overlord/hookstate/context_test.go, overlord/hookstate/ctlcmd/helpers.go, overlord/hookstate/ctlcmd/snap_management_test.go, overlord/snapstate/snapstate_test.go
This makes it so that we use the validation sets that are currently being enforced to create the tasks to install the components, rather than using the validation sets that are currently enforced (which would be out of date).
=> o/hookstate, o/snapstate: use in-flight validation sets when calling "snapctl install" from hook

.github/workflows/ci-test.yaml, tests/cross/go-build/task.yaml, tests/lib/prepare-restore.sh, tests/main/user-libnss/task.yaml, tests/unit/go/task.yaml
This removes the unnecessary pre-building packages for debian and non-core and non-nested ubuntu. In the ci-tests.yaml workflow, those systems use the deb from the archive and do not build snapd. Additionally, this moves around packaging steps to inside the packaging else branch.
=> tests, github: clean up packaging in tests

spread.yaml
This is a change requested by IS to increase the time spread waits until a server is ACTIVE.
Which that we will try al avoid errors like
cannot allocate new Openstack instance oct021646-321042 (2265e270-47c8-476f-a69a-ed16b9c54cdb): timeout waiting for 2265e270-47c8-476f-a69a-ed16b9c54cdb to provision, status: BUILD
=> tests: increase wait timeout to 10m for openstack backends

client/confdb.go, client/confdb_test.go, cmd/snap/cmd_set_test.go, cmd/snap/cmd_unset_test.go, daemon/api_confdb.go, daemon/api_confdb_test.go
Put the map of values to be written to confdb nested under "values". This helps with backwards compatibility if we need to add new fields to the PUT body. It's also more consistent with other parts of the API, namely on read and other related endpoints currently in spec stage.
=> daemon: wrap confdb write values under "values" key

.image-garden.mk
Selinux is interfering with tests.session so set it in permissive mode.
=> image-garden: set fedora to selinux permissive mode

tests/lib/systems.sh, tests/main/cgroup-tracking/task.yaml
In ubuntu questing the label of /sys/fs/cgroup is not cgroup2fs, see the output
stat -fc %T /sys/fs/cgroup
UNKNOWN (0x63677270)
So now we check the constant 0x63677270 to validate if it is cgroups v2
=> tests: fix cgroup tests in ubuntu questing

interfaces/apparmor/template.go
There is no reason to not allow these.
=> interfaces/apparmor: add free and pidof to the template

osutil/vfs/lists/export_test.go, osutil/vfs/lists/lists.go, osutil/vfs/lists/lists_test.go, osutil/vfs/vfs.go
At the cost of storing the pointer to `*T` within `Node[T]`, we can stop relying on
the unsafe package. The overall shape of `Node[T]` and `List[T]` is still very
close to the Linux kernel, but the chance of getting something catastrophically
wrong is smaller.
The signature of `List[T, O]` was changed to just `List[T]`, at the cost of making
`List.Append` and `List.Prepend` take an argument that ensures `Node.container` is
initialized. With the help of a new public function `ContainedNode` that
calls the `NodePointer` method on the helper associated type constrained by the
interface `NodePointerer`.
All the test and non-test code is adjusted to the new design.
=> osutil/vfs: trade memory for safety

.image-garden.mk, spread.yaml
Left-overs from recent development sessions:
- Support for Amazon Linux 2
- Persistent journal on all Ubuntu releases
- Removal of ESM entry from /etc/apt/sources.list.d
- Some stray white-space in spread.yaml
=> tests: tweaks to image-garden

tests/lib/prepare-restore.sh
Error when runing locally using snapd snap from master
```
++ go install ./tests/lib/fakestore/cmd/fakestore
go: inconsistent vendoring in
/home/gopath/src/github.com/snapcore/snapd:
github.com/canonical/go-efilib@v1.6.0: is explicitly required in
go.mod, but not marked as explicit in vendor/modules.txt
github.com/canonical/go-tpm2@v1.13.0: is explicitly required in
go.mod, but not marked as explicit in vendor/modules.txt
github.com/godbus/dbus/v5@v5.1.0: is explicitly required in
go.mod, but not marked as explicit in vendor/modules.txt
github.com/mattn/go-runewidth@v0.0.15: is explicitly required in
go.mod, but not marked as explicit in vendor/modules.txt
github.com/snapcore/secboot@v0.0.0-20250925122121-f8400226f49a:
is explicitly required in go.mod, but not marked as explicit in …
```
=> tests: fix missing go vendor to build fakestore
