canonical/snapd

cmd/snappy/cmd_update.go
po/snappy.pot

... because tiny branches are great.
Fixes trivial brought up in #48.

Address trivial from mvo's review on PR #48.

---

integration-tests/tests/autoupdate-msg_test.go

Also customized expected string for the different releases

Added snappy-autopilot stop to the teardown

---

testutil/checkers.go
testutil/checkers_test.go

- introduce testCheck/testInfo as in the upstream check.v1 package
- test failing conditions better
- improve error messages
- use more go-ish variable names

Improve testutil package based on code reviews

---

caps/capabilities.go
caps/capabilities_test.go

Just more functions and tests for capabilities.

Ongoing work on the capability APIs

---

partition/bootloader.go
partition/bootloader_public.go
pkg/file.go
pkg/types.go
snappy/common_test.go
snappy/kernel.go
snappy/snapp.go
snappy/snapp_snapfs_test.go

Handle the bootloader settings for os/kernel snaps. Also unpack the
kernel asssts to the bootdir.

Basic kernel/os handling

---

caps/capabilities.go
caps/capabilities_test.go
caps/misc.go
caps/misc_test.go
caps/repo.go
caps/repo_test.go
caps/types.go
caps/types_test.go

NOTE: this is based on #131  so please land that first.
This is just a few cleanups people were asking for. Nothing semantically should change here.

Re-factor tests for capabilities

---

README.md

We don't use LP anymore, update instructions.

Update contributor instructions

---

daemon/api.go
daemon/api_test.go
docs/rest.md

also: bumped api_compat; added json tags to licenseData, and added an integration-ish test for it all

Added license info to rest.md

---

integration-tests/main.go
integration-tests/testutils/autopkgtest/autopkgtest.go
integration-tests/testutils/autopkgtest/autopkgtest_test.go

As suggested by @niemeyer in a code review, I'm getting rid of the useless func.

Remove the NewAutopkgtest function.

---

integration-tests/tests/snapd_1_0_test.go

Check for a generic int instead of a concrete number

Relax the check of api_compat

---

testutil/checkers.go
testutil/checkers_test.go

Just more testing goodies. With more tests too. I need this for REST API tests that are in a separate branch.

Add testutil.DeepContains

---

integration-tests/main.go
integration-tests/testutils/autopkgtest/autopkgtest.go
integration-tests/testutils/autopkgtest/autopkgtest_test.go

As requested by @niemeyer and @sergiusens, s/Autopkgtest/AutoPkgTest.

Renamed Autopkgtest to AutoPkgTest.

---

run-checks
snappy/build_test.go
snappy/click_test.go
snappy/kernel.go
snappy/snapp_snapfs_test.go
snappy/systemimage.go
snappy/systemimage_test.go
systemd/systemd_test.go

Some tests lacked cleanup and leaked test files into the source
tree. This is fixed with this branch.

Fix unclean tests

---

docs/autoupdate.md

added missing hyphen to autoupdate config example

---

snappy/snapp.go

As discussed on the mailing list drop the concept of a global channel preference for now.

cherry pick #b30a8e0

---

classic/create.go
classic/create_test.go

Fix test failure in schroot environments

---

asserts/account_key.go
asserts/account_key_test.go
asserts/asserts.go
asserts/asserts_test.go
asserts/checkers.go
asserts/crypto.go
asserts/database.go
asserts/database_test.go
asserts/export_test.go
asserts/privkeys_for_test.go
asserts/snap_asserts.go
asserts/snap_asserts_test.go

* the other suites are private, change the asserts_test.go one too
* correct copyright range here: 2015

asserts: be consistent with suites and  copyright is 2015

---

classic/create_test.go

There was an armhf test failure caused by two errors:
- incorrect test data
- incorrect handling of unexpected URLs in the test server
This branch fixes both issues.

Fix test failure on armhf due to incorrect test data and error handling

---

debian/ubuntu-snappy-cli.install
debian/ubuntu-snappy.install
etc/profile.d/apps-bin-path.sh

This will allow binaries to be found by the system

Add etc/profile.d/apps-bin-path.sh and install in ubuntuc-snappy-cli

---

snappy/click_test.go
snappy/firstboot.go
snappy/firstboot_test.go
snappy/install_test.go
snappy/snapp.go

Cherry pickings are cherry picked.

15.04 activate oem on firstboot

---

asserts/database.go
asserts/snap_asserts_test.go

Fix typo: knownledge -> knowledge.

---

integration-tests/tests/purge_test.go

Added cli purge integration test

---

cmd/snappy/cmd_early_setup.go
debian/rules
debian/ubuntu-snappy.early-setup.service
snappy/install_test.go
snappy/snapp.go
snappy/snapp_test.go

backport of details-loop-for-update, plus early-setup command & associated debian/ files.

15.04 details loop for update

---

cmd/snappy/cmd_early_setup.go
coreconfig/config.go
coreconfig/config_test.go
debian/ubuntu-snappy.early-setup.service
snappy/click.go
snappy/click_test.go
snappy/firstboot.go
snappy/install_test.go
snappy/parts_test.go
snappy/purge.go
snappy/purge_test.go
snappy/service_test.go
snappy/snapp.go
snappy/snapp_test.go
systemd/systemd.go
systemd/systemd_test.go

Several miscelaneous fixes rolled into one. Sorry. Also no tests. Also needs refactoring of bool, bool to bitmap. And forwardporting to rolling. I already said sorry, what do you want of me.

fix all the things!

---

snappy/firstboot.go
snappy/firstboot_test.go

In the all-snap world we install a kernel/os/gadget but we do
not activate it. So we do this on first-boot now.

Enable kernel/os/gadget on first boot

---

asserts/asserts.go
asserts/snap_asserts.go
asserts/snap_asserts_test.go
asserts/toolbelt/main.go

new snap-build assertion carries what was the content of snap-declaration as it's on master atm

asserts: turn snap-declaration into snap-build

---

docs/rest.md

Removed in fb63c6e4cabde7fc9df6b8adc836900ef7324f50

`/1.0/icons/{icon}` endpoint is not available, update the docs

---

asserts/snap_asserts.go

Update & improve SnapBuild doc comments (based on reviews while adding SnapRevision).

Asserts snap build docs style

---

docs/rest.md

Mention `Content-Disposition` header for icons endpoint in docs

---

client/services.go
client/services_test.go

**WebDM** links to web UIs provided by active packages.
This PR facilitates this by providing the details of any services belonging to a specific package, including port information.

List the services belonging to an active package

---

client/packages.go
client/packages_test.go

Retrieve an individual `Package` from the `snapd` API

Get package details from snapd API

---

client/icons.go
client/packages.go
client/packages_test.go
client/services.go
client/services_test.go

Return by reference rather than by value

---

skills/core.go

This branch starts the work on the skills package. The existing change to repository API will that I was working on will simply land into the skills package. The caps package can be removed as this process completes.

Initial work on the skills package

---

asserts/account_key.go
asserts/account_key_test.go
asserts/asserts.go
asserts/asserts_test.go
asserts/checkers.go
asserts/crypto.go
asserts/database.go
asserts/database_test.go
asserts/export_test.go
asserts/fsbackstore.go
asserts/fsentryutils.go
asserts/fskeypairmgr.go
asserts/memkeypairmgr.go
asserts/memkeypairmgr_test.go
asserts/snap_asserts.go
asserts/snap_asserts_test.go
asserts/sysdb.go
asserts/sysdb_test.go
daemon/api.go
daemon/api_test.go
daemon/daemon.go

asserts,daemon: bump some copyright years for things that have been touched in the new year
Bump the copyright year/range for things that have been touched in 2016.

asserts,daemon: bump some copyright years for things that have been touched in the new year

---

integration-tests/tests/update_os_test.go
integration-tests/testutils/partition/bootloader.go
integration-tests/testutils/partition/bootloader_test.go

integration-tests: fix the bootloader path

---

partition/uboot.go
partition/uboot_test.go

Really remove the obsolete uEnv.txt checks.

partition: remove obsolete uEnv.txt

---

client/packages.go
client/packages_test.go

client: filter snaps by type

---

daemon/api.go
daemon/api_test.go
docs/rest.md
snappy/snap_remote_repo.go
snappy/snapp_test.go

Give snapd the ability to search by package name.

daemon, snappy: add find (aka search)

---

client/packages.go
client/packages_test.go

Corresponds with #371 but could potentially be landed beforehand.

client: filter snaps with a seach query

---

osutil/group_linux.go

Go vet is silly. Work around it.

osutil: make go vet happy again

---

daemon/api.go
daemon/api_test.go
daemon/daemon.go
skills/core.go
skills/repo.go
skills/repo_test.go
skills/testtype.go
skills/testtype_test.go

skills,daemon: add REST APIs for skills
This branch adds the complete REST API for working with skills. Refer to commits within for more information.

skills,daemon: add REST APIs for skills

---

integration-tests/tests/rollback_test.go

This branch re-enables the integration test for the rollback command. It first creates a fake update, installs it. Checks that the booted version is higher than the previous version and then rolls back and ensures that the version is now the same as the version it all started with.

integration-tests: reenable TestRollbackMustRebootToOtherVersion

---

client/client.go
client/client_test.go
client/packages.go
client/packages_test.go
client/snap_op.go
client/snap_op_test.go
daemon/api.go

Implemented them all. Made install be "Add" and update be "Refresh" as per what we'll be moving to soon internally.

client: implement doAsync, and all snap ops

---

client/skills_test.go

client: improve test data

---

cmd/snap/main_test.go

cmd/snap: add client test support methods

---

docs/rest.md

docs: add docs for skills API

---

asserts/asserts.go
classic/create.go
classic/run.go

The bind mounts need to be undone otherwise the all the stuff that
is bind mounted will get deleted (like the users home dir)

classic: if classic fails to get created, undo the bind mounts

---

skills/types/bool_file_test.go

skills: fix broken tests builds

---

arch/arch.go

Trivial branch that fixes a FTBFS on s390x. Will need an archive upload to verify the fix because there is no s390x PPA (afaik).

arch: fix build failure on s390x

---

integration-tests/main.go
integration-tests/testutils/common/common.go
integration-tests/testutils/config/config.go
integration-tests/testutils/config/config_test.go

Also define the default config file path as a constant in the config package

integration-tests: add fromBranch config field

---

helpers/helpers.go
helpers/helpers_test.go

omit vowels from MakeRandomString to avoid embedding words 

---

docs/meta.md
snappy/click.go
snappy/click_test.go
snappy/common_test.go
snappy/snap_yaml.go
snappy/snapp_test.go
systemd/systemd.go

This branch fixes the inconsistency of the snap.yaml parsing code in snappy with the spec.

snappy: bugfix for snap.yaml parsing to be more consistent with the spec

---

overlord/state/change.go
overlord/state/state_test.go
overlord/state/task.go
overlord/state/task_test.go

This introduces Status/SetStatus and Progress/SetProgress on Task and the Status type itself.

overlord/state: introduce Status/SetStatus and Progress/SetProgress on Task

---

overlord/state/change.go
overlord/state/change_test.go
overlord/state/state_test.go
overlord/state/task.go
overlord/state/task_test.go

This adds Status/SetStatus on Change.
It introduces DefaultStatus Status value as well to indicate the status before SetStatus gets called.

overlord/state: introduce Status/SetStatus on Change

---

docs/security.md

the launcher is not actually changing the directory, the wrapper script is doing this

[docs] fix inaccurate description of what the launcher is doing

---

daemon/api.go
daemon/api_test.go
daemon/daemon.go
daemon/response.go
docs/rest.md
notifications/hub.go
notifications/hub_test.go
notifications/subscriber.go
notifications/subscriber_test.go

Reworking of #530 but with random strings of alphanumeric characters for subscriber identifiers

daemon: snapd API events endpoint redux

---

snap/squashfs/squashfs.go

This is for the snap reviwers tools

snappy: add mksquashfs --no-xattrs parameter

---

snappy/hwaccess.go
snappy/hwaccess_test.go

This patch changes 'snappy hw-assign' to work with the new
per-application udev tags.  The change is simple, instead of writing one
rule per snap, we write one rule for each app of the snap mentioned on
command line.
Unit tests are affected (there was some missing setup needed for one of
the tests, which now matters since we want to see snap meta-data) as
well as some part of the implementation (we sort the rules so that
behavior and tests are deterministic) but nothing major.
There should be no user-visible differences on the outside. This is only
meant to keep hw-assign working before developer mode and interfaces
make it entirely obsolete.

snappy: fix hw-assign to work with per-app udev tags

---

overlord/overlord.go

overlord: fix typo

---

debian/ubuntu-snappy-cli.install
dirs/dirs.go
etc/X11/Xsession.d/65snappy

This branch makes desktop files work end-to-end in unity.

debian: tweak desktop file dir, ship Xsession.d snip for seamless integration

---

snappy/verify.go

snappy: fix leftover plug/slot variable swap

---

interfaces/builtin/bool_file.go
interfaces/builtin/bool_file_test.go

This patch changes the security of bool-file to align it with the
permanent vs connected snippet idea. The slot is now permanently able to
control GPIOs (to export/unexport them and to change direction).
The plug side remains the same, that is, plugs can access the GPIO value
or LED brightness, as before.
This also has a nice property of not requiring any restarts of the
service that has this slot when a plug is disconnected because the
plug-side security is not affected by connections. This doesn't matter
yet but will quite soon as interface code is being integrated with the
overlord.

interfaces/builtin: use permanent snippets in bool-file

---

overlord/state/change.go
overlord/state/change_test.go
overlord/state/task.go
overlord/state/task_test.go

Trivial helper branch for the StateManager branch.

overlord/state: Add State() methods to state.{Task,Change}

---

overlord/ifacestate/ifacemgr_test.go

overlord/ifacestate: make package testable

---

overlord/snapstate/export_test.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapmgr_test.go
overlord/state/taskrunner.go
po/snappy.pot

Still very basic and coarse grained

snapstate: initial install/remove support

---

overlord/ifacestate/ifacemgr.go
overlord/ifacestate/ifacemgr_test.go
overlord/overlord_test.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapmgr_test.go
overlord/state/change.go
overlord/state/change_test.go
overlord/state/state.go
overlord/state/task.go
overlord/state/task_test.go
overlord/state/taskrunner.go
overlord/state/taskrunner_test.go

overlord/state: preserve task order for presentation

---

interfaces/seccomp.go

interfaces/seccomp.go: update for recent ubuntu-core-security updates

interfaces: update for recent ubuntu-core-security updates

---

interfaces/builtin/all.go
interfaces/builtin/all_test.go
interfaces/builtin/firewall_control.go
interfaces/builtin/firewall_control_test.go
interfaces/builtin/home.go
interfaces/builtin/home_test.go
interfaces/builtin/locale_control.go
interfaces/builtin/locale_control_test.go

interface: add locale-control from ubuntu-core-security

---

store/snap_remote_repo.go
store/snap_remote_repo_test.go

This *should* fix [lp:1561669](https://bugs.launchpad.net/snappy/+bug/1561669). I need to look into the `find` side of that bug, but this'll fix the `install` aspect of it.

store: do not use anon url when authenticated

---

interfaces/builtin/all.go
interfaces/builtin/all_test.go
interfaces/builtin/firewall_control.go
interfaces/builtin/firewall_control_test.go
interfaces/builtin/home.go
interfaces/builtin/home_test.go
interfaces/builtin/locale_control.go
interfaces/builtin/locale_control_test.go
interfaces/builtin/log_observe.go
interfaces/builtin/log_observe_test.go
interfaces/builtin/mount_observe.go
interfaces/builtin/mount_observe_test.go
interfaces/builtin/network_control.go
interfaces/builtin/network_control_test.go
interfaces/builtin/network_observe.go
interfaces/builtin/network_observe_test.go
interfaces/builtin/snap_control.go
interfaces/builtin/snap_control_test.go

interfaces: add snap-control interface from ubuntu-core-security

interfaces: add snap-control interface from ubuntu-core-security

---

interfaces/builtin/all.go
interfaces/builtin/all_test.go
interfaces/builtin/firewall_control.go
interfaces/builtin/firewall_control_test.go
interfaces/builtin/home.go
interfaces/builtin/home_test.go
interfaces/builtin/locale_control.go
interfaces/builtin/locale_control_test.go
interfaces/builtin/log_observe.go
interfaces/builtin/log_observe_test.go
interfaces/builtin/mount_observe.go
interfaces/builtin/mount_observe_test.go
interfaces/builtin/network_control.go
interfaces/builtin/network_control_test.go
interfaces/builtin/network_observe.go
interfaces/builtin/network_observe_test.go
interfaces/builtin/snap_control.go
interfaces/builtin/snap_control_test.go
interfaces/builtin/system_observe.go
interfaces/builtin/system_observe_test.go

interfaces: add system-observe from ubuntu-core-security

interfaces: add system-observe from ubuntu-core-security

---

interfaces/builtin/all.go
interfaces/builtin/all_test.go
interfaces/builtin/firewall_control.go
interfaces/builtin/firewall_control_test.go
interfaces/builtin/home.go
interfaces/builtin/home_test.go
interfaces/builtin/locale_control.go
interfaces/builtin/locale_control_test.go
interfaces/builtin/log_observe.go
interfaces/builtin/log_observe_test.go
interfaces/builtin/mount_observe.go
interfaces/builtin/mount_observe_test.go
interfaces/builtin/network_control.go
interfaces/builtin/network_control_test.go
interfaces/builtin/network_observe.go
interfaces/builtin/network_observe_test.go
interfaces/builtin/snap_control.go
interfaces/builtin/snap_control_test.go
interfaces/builtin/system_observe.go
interfaces/builtin/system_observe_test.go
interfaces/builtin/timeserver_control.go
interfaces/builtin/timeserver_control_test.go

interfaces: add timeserver-control from ubuntu-core-security

interfaces: add timeserver-control from ubuntu-core-security

---

interfaces/builtin/all.go
interfaces/builtin/all_test.go
interfaces/builtin/firewall_control.go
interfaces/builtin/firewall_control_test.go
interfaces/builtin/home.go
interfaces/builtin/home_test.go
interfaces/builtin/locale_control.go
interfaces/builtin/locale_control_test.go
interfaces/builtin/log_observe.go
interfaces/builtin/log_observe_test.go
interfaces/builtin/mount_observe.go
interfaces/builtin/mount_observe_test.go
interfaces/builtin/network_control.go
interfaces/builtin/network_control_test.go
interfaces/builtin/network_observe.go
interfaces/builtin/network_observe_test.go
interfaces/builtin/snap_control.go
interfaces/builtin/snap_control_test.go
interfaces/builtin/system_observe.go
interfaces/builtin/system_observe_test.go
interfaces/builtin/timeserver_control.go
interfaces/builtin/timeserver_control_test.go
interfaces/builtin/timezone_control.go
interfaces/builtin/timezone_control_test.go

interfaces: add timezone-control from ubuntu-core-security

interfaces: add timezone-control from ubuntu-core-security

---

interfaces/builtin/all.go
interfaces/builtin/all_test.go
interfaces/builtin/firewall_control.go
interfaces/builtin/firewall_control_test.go
interfaces/builtin/home.go
interfaces/builtin/home_test.go
interfaces/builtin/locale_control.go
interfaces/builtin/locale_control_test.go
interfaces/builtin/log_observe.go
interfaces/builtin/log_observe_test.go
interfaces/builtin/mount_observe.go
interfaces/builtin/mount_observe_test.go
interfaces/builtin/network_control.go
interfaces/builtin/network_control_test.go
interfaces/builtin/network_observe.go
interfaces/builtin/network_observe_test.go
interfaces/builtin/snap_control.go
interfaces/builtin/snap_control_test.go
interfaces/builtin/system_observe.go
interfaces/builtin/system_observe_test.go
interfaces/builtin/timeserver_control.go
interfaces/builtin/timeserver_control_test.go
interfaces/builtin/timezone_control.go
interfaces/builtin/timezone_control_test.go
interfaces/builtin/unity7.go
interfaces/builtin/unity7_test.go

interfaces: add unity7 interface from ubuntu-core-security

interfaces: add unity7 interface from ubuntu-core-security

---

interfaces/builtin/all.go
interfaces/builtin/all_test.go
interfaces/builtin/firewall_control.go
interfaces/builtin/firewall_control_test.go
interfaces/builtin/home.go
interfaces/builtin/home_test.go
interfaces/builtin/locale_control.go
interfaces/builtin/locale_control_test.go
interfaces/builtin/log_observe.go
interfaces/builtin/log_observe_test.go
interfaces/builtin/mount_observe.go
interfaces/builtin/mount_observe_test.go
interfaces/builtin/network_control.go
interfaces/builtin/network_control_test.go
interfaces/builtin/network_observe.go
interfaces/builtin/network_observe_test.go
interfaces/builtin/snap_control.go
interfaces/builtin/snap_control_test.go
interfaces/builtin/system_observe.go
interfaces/builtin/system_observe_test.go
interfaces/builtin/timeserver_control.go
interfaces/builtin/timeserver_control_test.go
interfaces/builtin/timezone_control.go
interfaces/builtin/timezone_control_test.go
interfaces/builtin/unity7.go
interfaces/builtin/unity7_test.go
interfaces/builtin/x.go
interfaces/builtin/x_test.go

interfaces: add x from ubuntu-core-security

interfaces: add x from ubuntu-core-security

---

interfaces/apparmor/backend_test.go

interfaces/apparmor: s/mockCmd/parserCmd/g

---

store/snap_remote_repo.go
store/snap_remote_repo_test.go

Added helper to get MyApps base URL for API requests. Based on existing helpers for CPI and SSO.

Added myappsURL function to get MyApps API base URL.

---

integration-tests/tests/classic_dimension_test.go

https://bugs.launchpad.net/snappy/+bug/1563193

integration-tests: skip classicDimensionSuite tests due to LP: #1563193

---

overlord/snapstate/backend.go
overlord/snapstate/backend_test.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapmgr_test.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_test.go
po/snappy.pot
snappy/desktop_test.go
snappy/info_test.go
snappy/overlord.go
snappy/overlord_test.go
snappy/snap_yaml.go
snappy/snapdata.go
snappy/snapp_snapfs_test.go

Also integrates security handling.

overlord: add support for removal via smaller tasks

---

interfaces/repo.go
interfaces/repo_test.go

This patch adds a way to disconnect all connections to / from a given
snap. This is useful for performing snap upgrades where all connections
are severed before the snap is replaced.

interfaces: add DisconnectSnap

---

overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate.go

This should fix the issue that @zyga ran into.

snapstate: use TaskSnapSetup in doRemoveSnap{Security,Files,Data}

---

interfaces/seccomp/backend.go

interfaces/seccomp: fix build

---

client/login.go
client/login_test.go

Add login method for daemon REST login API.

client/login: add login method

---

client/packages.go
client/packages_test.go
cmd/snap/cmd_list.go
daemon/api_test.go
daemon/snap.go
docs/rest.md
integration-tests/tests/snap_op_test.go
po/snappy.pot

Dates, dates, every where,
And all the boards did shrink;

daemon, client, cmd/snap: add install_date to rest api, client, and snap list output

---

overlord/ifacestate/ifacemgr.go

overlord/ifacestate: some AddSnap errors are non-fatal

---

overlord/ifacestate/ifacemgr.go
overlord/ifacestate/ifacemgr_test.go

overlord/ifacestate: scan available snaps on initialization

---

overlord/ifacestate/ifacemgr_test.go
overlord/snapstate/export_test.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapmgr_test.go
overlord/snapstate/snapstate.go

This branch exposes ``SnapState``, ``GetSnapState`` and ``SetSnapState`` and uses them in the interfaces test so that everything works correctly.

overlord: fix broken tests

---

overlord/ifacestate/export_test.go
overlord/ifacestate/ifacemgr.go

overlord/ifacestate: allow tests to override security backends

---

overlord/ifacestate/export_test.go

overlord/ifacestate: drop duplicate package comment

---

daemon/api.go
daemon/api_test.go

Includes #912 so start there first

daemon: include progress in rest changes

---

overlord/ifacestate/export_test.go
overlord/ifacestate/ifacemgr_test.go

overlord/ifacestate: modularize and extend tests

---

store/snap_remote_repo.go
store/snap_remote_repo_test.go

store: cache suggested currency from the store

---

client/client.go
client/op.go
cmd/snap/cmd_login.go
daemon/api.go
daemon/api_test.go
daemon/response.go
integration-tests/tests/login_test.go
po/snappy.pot
store/errors.go

Updates to the snap login command to use the daemon login REST API.

cmd/snap,daemon,store: rework login command to use daemon login API

---

overlord/ifacestate/ifacemgr.go
overlord/ifacestate/ifacemgr_test.go

This branch ensures that connections are tracked in the state

overlord/ifacestate: track connections in the state

---

daemon/api.go
daemon/api_test.go
debian/tests/integrationtests
integration-tests/tests/snap_example_test.go
integration-tests/testutils/cli/cli.go

This branch ensures that we install ubuntu-core if it is missing. This helps gnome-software and the cloud images.

daemon: auto install ubuntu-core if missing

---

overlord/snapstate/backend_test.go
overlord/snapstate/snapmgr_test.go
snap/info.go
snap/info_test.go
store/details.go
store/snap_remote_repo.go
store/snap_remote_repo_test.go

what to do about states already out in the field?

overlord/snapstate,snap,store: track snap-id in side-info and therefore in state

---

client/change.go
client/change_test.go
daemon/api.go
daemon/api_test.go
overlord/state/task.go

daemon,client,overlord: progress current => done

---

interfaces/apparmor/backend.go
interfaces/apparmor/backend_test.go
interfaces/backend.go
interfaces/dbus/backend.go
interfaces/dbus/backend_test.go
interfaces/seccomp/backend.go
interfaces/seccomp/backend_test.go
interfaces/udev/backend.go
interfaces/udev/backend_test.go

interfaces: rename developerMode to devMode

---

client/asserts.go
client/change.go
client/client.go
client/interfaces.go
client/login.go
client/op.go
client/packages.go
client/packages_test.go
cmd/snap/cmd_find.go
cmd/snap/cmd_list.go
daemon/api.go
daemon/api_test.go
daemon/response.go
docs/rest.md

Depends on #929.
Review here: https://github.com/ubuntu-core/snappy/pull/934/commits/1bff8a34a87e7fd8275a318274b0076c4f4e7ab4

daemon,client,cmd: return snap list from /v2/snaps

---

daemon/api_test.go
daemon/snap.go
docs/rest.md

docs: update rest.md with price information

---

overlord/snapstate/snapmgr.go

overlord/snapstate: fix JSON name of SnapState.Candidate

---

snap/snapenv/snapenv.go
snappy/binaries.go
snappy/binaries_test.go
snappy/services.go
snappy/services_test.go
snappy/utils.go
systemd/systemd.go
systemd/systemd_test.go

snap/snapenv,snappy,systemd: expose SNAP_REVISION to app environment

---

daemon/api.go
daemon/api_test.go
overlord/snapstate/backend_test.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapmgr_test.go
overlord/snapstate/snapstate.go

Add authentication setup for downloads from the store. Similar work would be needed for updates.

daemon,overlord: setup authentication for store downloads

---

client/change.go
client/change_test.go
cmd/snap/cmd_changes.go
cmd/snap/cmd_list.go
daemon/api.go
daemon/api_test.go
overlord/state/change.go
po/snappy.pot

Also send spawn and ready time to the client for displaying.

daemon,client,overlord/state,cmd: add changes command

---

debian/snapd.dirs
debian/snapd.install
debian/snapd.service

debian: put snapd in /usr/lib/snapd/

---

snappy/snapp_snapfs_test.go
systemd/systemd.go
systemd/systemd_test.go

systemd: add multi-user.target

---

store/snap_remote_repo_test.go

Sorry, the previous branch got merged before I noticed the feedback. Here is a follow-up.

store: address review feedback from previous branch

---

overlord/ifacestate/ifacemgr_test.go

overlord/ifacestate: pass SnapSetup to test fixture helper

---

overlord/state/task.go
overlord/state/task_test.go

This is in preparation of fixing the issue of daemon sometimes creating changes in state too early.

overlord/state: introduce more convenience methods on TaskSets

---

debian/snapd.dirs

debian: remove unneeded /var/lib/snapd/apparmor/additional directory

---

etc/profile.d/apps-bin-path.sh

etc: trivial typo fix

---

debian/tests/integrationtests
integration-tests/data/snaps/network-consumer/bin/consumer
integration-tests/data/snaps/network-consumer/meta/snap.yaml
integration-tests/tests/interfaces_test.go
integration-tests/testutils/data/data.go

The tests exercise these aspects of the interface:
* autoconnect
* disconnect and reconnect
* disabled network access after disconnect

integration-tests: network interface

---

client/packages.go
client/packages_test.go

Frameworks are no more and we now have core

client: list correct snap types

---

overlord/snapstate/snapstate.go

I tried writing a unit test for this, but couldn't get it to fail. So here you go...

snapstate: load squashfs support

---

daemon/api.go
daemon/api_test.go
daemon/snap.go
docs/rest.md
store/details.go
store/errors.go
store/store.go
store/store_test.go

This does not change `/v2/snaps`, nor does it switch the client to use find. It just exposes find, and updates the docs, mostly for discussion.

daemon, store: use find

---

systemd/escape_test.go
systemd/export_test.go
systemd/systemd_test.go

systemd: isolate tests from main package

---

classic/create.go
classic/create_test.go
daemon/api.go
daemon/api_test.go
integration-tests/tests/snapd_2_0_test.go
release/export_test.go
release/release.go
release/release_test.go
snappy/snapp_test.go
store/store.go

integration test fix on top of #1131 by Gustavo

many: simplify release package and add OnClassic

---

cmd/snap/cmd_list.go
po/snappy.pot

Fix conflicts and apply reviews from @arges' #1154 to get it in.

cmd: make snap list with no snaps not special

---

daemon/snap.go

Applying review on @mvo5's #1163 to get it in.

daemon: make localSnapInfo return SnapState

---

integration-tests/tests/snap_install_test.go

Regression test for https://bugs.launchpad.net/snappy/+bug/1574829

integration-tests: add regression test for LP #1574829

---

interfaces/builtin/unity7.go

interfaces: allow access to new ibus abstract socket path (Closes LP#1580463)

interfaces: allow access to new ibus abstract socket path

---

client/packages.go
client/packages_test.go
cmd/snap/cmd_find.go
cmd/snap/cmd_list.go
cmd/snap/cmd_list_test.go
cmd/snap/cmd_snap_op_test.go
cmd/snap/notes.go
cmd/snap/notes_test.go
daemon/api_test.go
daemon/snap.go
integration-tests/tests/list_test.go
integration-tests/tests/snap_find_test.go
integration-tests/tests/snap_install_test.go
integration-tests/tests/snap_op_test.go
integration-tests/tests/tryapp_test.go

This builds on `local-devmode-in-daemon` (#1224) so [compare with that](https://github.com/chipaca/snappy/compare/local-devmode-in-daemon...chipaca:notes-in-list).

cmd: add "notes" column in list and find outputs; add developer to find output; move price in find output into notes

---

integration-tests/tests/snap_abort_test.go

This test is giving flaky results, this change removes it while we investigate the causes.

integration-tests: remove abortSuite.TestAbortWithValidIdInDoingStatus 

---

overlord/state/taskrunner.go
overlord/state/taskrunner_test.go

This add proper support for tasks that sets themselves on their own as done/undone to be fully transactional. Added test cases for this.

ovlerlord/state: actually support task setting themself as done/undone

---

boot/boottest/mockbootloader.go
boot/kernel_os_test.go
overlord/managers_test.go
overlord/snapstate/snapmgr_test.go
snap/snaptest/snaptest.go

This are going to be used also in the next PR.

many: add some shared testing helpers to snap/snaptest and to boot/boottest

---

integration-tests/tests/snap_interfaces_test.go

Added tests according to the recommendations from the Ubuntu Personal - Product Test team. A reference to the Test Case ID is included in each test comment.

integration-tests: add interfaces cli tests

---

cmd/cmd.go
cmd/snap/cmd_snap_op.go
cmd/snap/cmd_snap_op_test.go
cmd/snap/export_test.go
daemon/daemon.go
debian/snapd.service
overlord/overlord.go
overlord/overlord_test.go

Also tweaks to the service file and the make reexec print a debug line.

several: tie up overlord's restart handler into daemon; adjust snap to cope

---

integration-tests/tests/list_test.go
tests/basics/task.yaml
tests/listing/task.yaml

Ported listing integration tests to spread

tests, integration-tests: port listing tests to spread

---

cmd/snap/cmd_run_test.go

Trivial fix for a build failure on powerpc with go-6

snap: fix go-6 FTBFS

---

overlord/firstboot.go

Fix spread failure in the gccgo build.

add missing lock around chg.Status()

---

overlord/snapstate/link_snap_test.go
overlord/snapstate/snapmgr.go

This is really @mvo5's #1425. Picking it up just to reword the sentence.

snapstate: add logging after a successful doLinkSnap

---

tests/main/abort/task.yaml
tests/main/ack/task.yaml
tests/main/change-errors/task.yaml
tests/main/cmdline/task.yaml
tests/main/help/task.yaml
tests/main/install-errors/task.yaml
tests/main/install-sideload/task.yaml
tests/main/install-store/task.yaml
tests/main/interfaces-cli/task.yaml
tests/main/interfaces-home/task.yaml
tests/main/interfaces-log-observe/task.yaml
tests/main/interfaces-network-bind/task.yaml
tests/main/interfaces-network/task.yaml
tests/main/known/task.yaml
tests/main/listing/task.yaml
tests/main/op-install-failed-undone/task.yaml
tests/main/op-remove-retry/task.yaml
tests/main/op-remove/task.yaml
tests/main/refresh/task.yaml
tests/main/remove-errors/task.yaml
tests/main/revert-sideload/task.yaml
tests/main/revert/task.yaml
tests/main/searching/task.yaml
tests/main/security-profiles/task.yaml
tests/main/server-snap/task.yaml
tests/main/try-snap-goes-away/task.yaml
tests/main/try/task.yaml
tests/main/writable-areas/task.yaml

Also removed unneeded leftover `|| exit 1` guards.

tests: set yaml indentation to 4 spaces

---

daemon/api.go
daemon/api_test.go
daemon/daemon.go
daemon/daemon_test.go
overlord/auth/auth.go
overlord/auth/auth_test.go

also: overlord/auth: make user.Authenticator not explode on nil user

daemon: drop auther()

---

store/auth.go
store/auth_test.go

Introducing helper to get a discharge macaroon soft-refreshed. Given a discharge macaroon, the endpoint will return a new refreshed discharge (after verifying no password change or invalidation from the user, server-side).

store/auth: add helper for the macaroon refresh endpoint

---

release/release.go
release/release_test.go

release: work around elementary mistake

---

client/packages.go
client/packages_test.go
cmd/snap/cmd_find.go
daemon/api.go
daemon/api_test.go
overlord/snapstate/backend.go
overlord/snapstate/backend_test.go
store/errors.go
store/store.go
store/store_test.go

This builds on #1554 so [compare with that](https://github.com/chipaca/snappy/compare/find-search...find-private).

store, daemon, client, cmd/snap: implement `snap find --private`

---

overlord/snapstate/backend/mountunit.go

This branch fixes the autopkgtest failures in yakkety (at least it did in my local autopkgtest run).

snapstate: add daemon-reload to fix autopkgtest on yakkety

---

store/store.go

Introduces requestOptions handling store request parameters, instead of passing them as arguments to doRequest/newRequest

store: refactor newRequest/doRequest to take requestOptions

---

daemon/api.go
daemon/api_test.go
osutil/user.go
osutil/user_test.go

Picks up @mvo5's #1600 for trivial typo fixes.

many: various fixes around the `create-user` command

---

store/auth.go
store/auth_test.go

Add API returning a device nonce required to setup a device session.

store: add device nonce API support

---

overlord/auth/auth.go
overlord/auth/auth_test.go
store/store.go
store/store_test.go

Get device state and set device authentication header in store requests.

overlord,store: set store device authorization header

---

docs/rest.md

docs: fix references to refresh action

---

.gitignore

Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>

gitignore: add vim swap files

---

partition/bootloader.go
partition/bootloader_test.go

partition: fix cleaning of the boot variables on the second good boot

---

docs/rest.md

docs: private flag doesn't exist on /v2/find (it's select)

---

integration-tests/tests/create_user_test.go
osutil/export_test.go
osutil/osutil_test.go
osutil/user.go
osutil/user_test.go

This is applying the review on @mwhudson's #1651, and testing the feature.

osutil: change escaping for create-user's sudoers

---

interfaces/builtin/bluez_test.go
tests/main/interfaces-bluez/task.yaml

https://github.com/snapcore/snapd/pull/1676 fixed a problem which was a regression with the bluez. This PR adds tests to ensure this doesn't happen again.

interfaces: bluez: add a few more tests to verify interface connection works

---

README.md
run-checks
spread.yaml
tests/main/interfaces-cli/task.yaml
tests/main/interfaces-home/task.yaml
tests/main/interfaces-log-observe/task.yaml
tests/main/interfaces-network-bind/task.yaml
tests/main/interfaces-network/task.yaml
tests/main/refresh-all/task.yaml
tests/main/refresh-devmode/task.yaml
tests/main/refresh/task.yaml
tests/main/revert/task.yaml
tests/main/security-private-tmp/task.yaml
tests/main/try-snap-goes-away/task.yaml
tests/main/unity/task.yaml

Built on top of #1693 , will fail util the new spread binary is made available to travis.

tests: adapt to new spread version

---

tests/lib/fakestore/store/store.go
tests/lib/store.sh

keep some debugging help as well

tests: this seems to improve the situation regarding flaky stopping of fakestore

---

tests/lib/prepare.sh

Tiny cleanup from the previous code review in #1698

tests: spread all-snap test cleanup

---

docs/interfaces.md
interfaces/builtin/all.go
interfaces/builtin/all_test.go
interfaces/builtin/lxd_support.go
interfaces/builtin/lxd_support_test.go
snap/implicit.go
snap/implicit_test.go

This is just Jamies #1720 with the (trivial) review feedback applied.

interfaces: add lxd-support interface

---

interfaces/builtin/lxd_support_test.go
overlord/boot/firstboot_test.go

Trivial branch that fixes package building.

boot: add missing udevadm mock to fix FTBFS

---

cmd/snap/cmd_run.go

cmd/snap: use UserDataDir and UserCommonDataDir

---

asserts/asserts.go
asserts/asserts_test.go
asserts/headers.go

* text bodies
* no repeated headers

asserts: add some stricter checks around format

---

cmd/snap/cmd_snap_op.go

snap: use "up to date" instead of "up-to-date"

---

store/store.go
store/store_test.go

Set the initial device session if there is none set.

store: set initial device session

---

tests/lib/prepare.sh

tests: adjust test setup after ubuntu user removal

---

snap/implicit_test.go

fix incorrect number of implicit interfaces

---

interfaces/builtin/serial_port.go

Use the function in utils to build the udev snippets in serial-port interface

interfaces: serial-port use udevUsbDeviceSnippet

---

tests/lib/prepare.sh

Proposing to get test results.

tests/lib/prepare.sh: test that classic does not setting bootvars

---

daemon/api_test.go
overlord/hookstate/hookmgr.go

I keep forgetting about `MockCommand`.

hookstate,daemon: don't mock HookRunner, mock command.

---

snap/info.go
store/details.go
store/store.go
store/store_test.go

store,snap: initial support for delta downloads

---

cmd/snap/cmd_buy.go
daemon/api.go
overlord/snapstate/backend.go
store/errors.go
store/store.go
store/store_test.go

* This method will replace the PaymentMethods.
* CLI, snapd API changes will follow in subsequent PRs.
* TODOs added for the follow on changes.

store: add "ready to buy" method

---

tests/main/create-key/task.yaml

Details at http://paste.ubuntu.com/23217619/.

tests: disable broken create-key test

---

tests/main/regression-home-snap-root-owned/task.yaml

Strange stuff happend in https://github.com/snapcore/snapd/pull/1973

tests: ensure HOME is also set correctly

---

debian/control

This should make our PPA build work again.

debian: re-add golang-github-gosexy-gettext-dev 

---

daemon/api.go
daemon/api_test.go
docs/rest.md

As requested in https://github.com/snapcore/snapd/pull/1990#discussion_r80388206

daemon: add the actual ssh keys that got added to the create-user response

---

daemon/api.go
daemon/api_test.go
overlord/configstate/transaction.go
overlord/configstate/transaction_test.go
overlord/hookstate/ctlcmd/get_test.go
overlord/hookstate/ctlcmd/set.go
overlord/hookstate/ctlcmd/set_test.go

Also add a couple of helpers to deal with missing options.

overlord: fix and simplify configstate.Transaction

---

docs/hooks.md

Finish up LP: [#1596629](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1596629) by adding `configure` to the hooks document.

docs: add `configure` hook to hooks list.

---

docs/interfaces.md

Added timezone-control to interfaces.md - this addresses the comment to my earlier PR for time-control, I forgot to address the request from @jdstrand https://github.com/snapcore/snapd/pull/1832#issuecomment-250285130

doc: added timezone-control to interfaces doc

---

client/login.go
cmd/snap/cmd_login.go
daemon/api.go
daemon/api_test.go
overlord/auth/auth.go
overlord/auth/auth_test.go
overlord/snapstate/snapmgr_test.go

Adds Email field to UserState and refactors loginUser to set the right fields, keeping compatibility.

many: add email to UserState

---

overlord/auth/auth.go
overlord/auth/auth_test.go

Adds snapd macaroon verification for local user auth, keeping previous token-style check as fallback for backwards compatibility

overlord/auth: update CheckMacaroon to verify local snapd macaroons

---

client/client.go
client/client_test.go
client/login.go
client/login_test.go
cmd/snap/cmd_auto_import.go
cmd/snap/cmd_auto_import_test.go
daemon/api.go
daemon/api_test.go
overlord/auth/auth.go
overlord/auth/auth_test.go

This branch implements the last piece in the puzzle to allow taking ownership to a unowned device via e.g. a usb-stick.

client,daemon,overlord,cmd: add /v2/users and create-user on auto-import

---

store/store.go
store/store_test.go

Picks up @matiasb's #2089 to merge master, fixing tests.

store: do not set store auth for local users

---

daemon/api_test.go

This removes a lot of boilerplate code from the individual tests and consolidates it in the SetUpTest/TearDown test of the postCreateUserSuite.

daemon: add postCreateUserSuite test suite

---

snap/squashfs/squashfs.go

Builds on #2167 so [diff with that](https://github.com/chipaca/snappy/compare/do-not-remove-seed...chipaca:install-links-squashfs).

snap/squashfs: try to hard link instead of copying. Also, switch to osutil.CopyFile for cp invocation.

---

asserts/ifacedecls.go
asserts/ifacedecls_test.go
interfaces/policy/helpers.go
interfaces/policy/policy_test.go

asserts,interfaces/policy: implement on-classic plug/slot constraints

---

overlord/snapstate/snapmgr_test.go
overlord/snapstate/snapstate.go

make RevertToRevision not reset the snap state channel, and make Enable not drop the snap side info. All with tests that would fail without the fixes.
paired with Samuele, so he gives his +1 to this already.

overlord/snapstate: two bugs for one

---

docs/gadget.md

As requested in trello: https://trello.com/c/Swii8LIR

docs: less details about cloud.cfg

---

overlord/snapstate/export_test.go
overlord/snapstate/snapmgr_test.go
overlord/snapstate/snapstate.go
tests/main/enable-disable/task.yaml
tests/main/remove-errors/task.yaml

https://launchpad.net/bugs/1636894

snapstate: ensure gadget/core/kernel can not be disabled

---

overlord/snapstate/snapmgr.go

overlord/snapstate: fix missing argument to Noticef

---

overlord/overlord_test.go
overlord/snapstate/snapstate.go
overlord/state/change.go
overlord/state/change_test.go
overlord/state/state.go
overlord/state/state_test.go
overlord/state/task.go
tests/main/refresh-all-undo/task.yaml

Picks up @mvo5's #2244 and test lane marshaling.

overlord/state: marshaling tests for lanes

---

overlord/ifacestate/ifacemgr_test.go

overlord/ifacestate: add unit tests for undo of setup-snap-security

---

cmd/snap/cmd_buy_test.go

Same problem on powerpc as ppc64el

tests: /dev/ptmx also broken on powerpc

---

spread.yaml

Add quotes around snap mode check in spread.yaml.

spread tests: fix snap mode check

---

osutil/chattr.go
osutil/chattr_32.go
osutil/chattr_64.go
tests/main/chattr/task.yaml
tests/main/chattr/toggle.go

Adding chattr without actually using it, to check it actually works on all architectures as implemented.

osutil: add chattr funcs

---

store/store.go
store/store_test.go

Next in the "retry" PR series - Retry the call for snap details.

store: retry call for snap details

---

store/store.go
store/store_test.go

Retry Assertion calls on some server errors; this is the continuation of retry-store ops PR series.

store: retry assertion store call

---

store/store.go
store/store_test.go

Retry Buy request in the store.

store: retry buy request

---

daemon/api.go
daemon/api_test.go

This addresses the techdebt in https://trello.com/c/GfEXOVA1

daemon/api.go: add quotedNames() helper

---

progress/progress.go

Trivial techdebt cleanup, from https://trello.com/c/GfEXOVA1

progress: init pbar with correct total value

---

daemon/snap.go
overlord/assertstate/assertmgr.go
overlord/ifacestate/handlers.go
overlord/patch/patch1.go
overlord/patch/patch5.go
overlord/snapstate/snapmgr_test.go

Trivial rename mostly, simplified one test a little bit along the way.

many: some more missing snapState->snapst

---

cmd/snap/cmd_login.go
cmd/snap/cmd_login_test.go
tests/main/login/missing_email_error.exp

Addresses https://trello.com/c/V4pcInYj 
TestLoginAskEmail is slightly ugly, suggestions welcome!

snap: make `snap login` ask for email if not given as argument

---

cmd/snap/cmd_login_test.go

Fixes FTBFS on powerpc and ppc64el

tests: skip pty tests on ppc64el and powerpc

---

store/store.go

Retry not only on io.UnexpectedEOF but also on io.EOF.

store: retry on io.EOF

---

cmd/snap/cmd_list.go
cmd/snap/cmd_list_test.go

cmd/snap: document 'snap list --all'

---

daemon/api.go
daemon/api_test.go

daemon: ensure `snap try` installs core if it's missing

---

debian/rules

debian/rules: build with -buildoptions=pie

---

snap/validate.go
snap/validate_test.go

snap: support "daemon: notify" in snap.yaml

---

HACKING.md

docs: document SNAP_DEBUG_HTTP in HACKING.md

---

cmd/snap/main.go

snap: remove unused experimental command

---

cmd/snap/cmd_help_test.go
cmd/snap/main.go
debian/control

snap: Improve `snap --help` output as designed by Mark

---

store/store.go
store/store_test.go

Tweaked retry parameters for longer delays between retries. Added some logging.

store: retry tweaks and logging

---

daemon/api.go
store/store.go
tests/main/snap-info/check.py

also, unrelatedly: what does it say about me that I really enjoy the `<foo>-no-<bar>` construction when you're left wondering if I meant no or の?

daemon, store: let snap info find things in any channel

---

tests/main/ubuntu-core-upgrade-no-gc/task.yaml

tests: fix incorrect restore of the current symlink

---

snap/info.go
snap/info_snap_yaml.go
snap/info_snap_yaml_test.go
snap/validate.go
snap/validate_test.go

This adds support for parsing and exposing on snap.Info aliases lists on snap applications.

snap: support for parsing and exposing on snap.Info aliases

---

store/store.go

fix unhandled error from io.Copy() in download() for 2.18.1

---

tests/lib/prepare.sh

tests: check if snap-confine --version is unknown

---

cmd/snap/cmd_snap_op.go
cmd/snap/cmd_snap_op_test.go
tests/main/install-store/task.yaml

snap: tweak snap install output as designed by Mark

---

overlord/ifacestate/ifacemgr.go

overlord/ifacestate: remove stale comments

---

tests/lib/prepare.sh

tests: show --version when it matches unknown

---

tests/main/classic-confinement/task.yaml

Trivial branch that adds more testing to the classic confinement test.

tests: test classic confinement `snap list` and  `snap info` output

---

tests/main/snap-connect/task.yaml

tests: switch more tests to MATCH

---

cmd/Makefile.am

cmd: fix typo (thanks to jdstrand!)

---

interfaces/repo_test.go

interfaces: abbreviate ConnRef construction

---

cmd/snap/cmd_info.go
cmd/snap/cmd_info_test.go

snap: show price in `snap info`

---

.gitignore
cmd/Makefile.am
cmd/snap-alter-ns/snap-alter-ns.c
cmd/snap-alter-ns/snap-alter-ns.rst
debian/snap-confine.install

cmd: add stub implementation of snap-alter-ns

---

interfaces/core.go
interfaces/core_test.go
overlord/ifacestate/handlers.go
overlord/ifacestate/helpers.go

many: change interfaces.ParseID to return value

---

cmd/snap/cmd_snap_op.go

snap: be more helpful in the `snap install <already-installed>` error message

---

README.md

Provide a more interesting pitch for upstream developers using snaps. We cannot assume they'll first land on snapcraft.io, so let's do our best to sell them on the experience here so they're compelled to read the documentation on that site.

Provide a more interesting pitch for upstream developers using snaps

---

cmd/autogen.sh

I was working on my Fedora machine and I realized I never commited this small
change to autogen.sh so here it is.

cmd: fix autogen.sh on fedora

---

store/retry.go

Real world example:
https://travis-ci.org/snapcore/snapd/jobs/197585054#L2047

store: retry on 502 http response as well

---

overlord/devicestate/devicemgr.go
overlord/devicestate/devicemgr_test.go
overlord/devicestate/export_test.go

Also do a better effort extracting the server error message.

overlord/devicestate: backoff between retries if the server seems to have refused the serial-request

---

interfaces/mount/backend.go
interfaces/mount/backend_test.go

This patch changes the mount backend to generate the new per-snap
mount profile in additon to the exsting per-app profiles. Currently
snap-confine still relies on per-app profile but once this is changed
(soon) they can be removed.

interfaces/mount: generate per-snap mount profile

---

release/release.go

Add support for GaliumOS (based on ubuntu-16.04).

release: add galliumos support

---

cmd/snap/cmd_buy.go
cmd/snap/cmd_buy_test.go
store/store.go
store/store_test.go

- https://docs.google.com/document/d/1g6nWgl3bQARp8deSU3NAAJJAMS-PgpTFtglSQJjLFKM/edit#heading=h.has8x2jj0kie

cmd/snap, store: change error messages to reflect latest UX doc

---

tests/main/listing/task.yaml

This fixes the listing test for master.

tests: update listing test for latest core snap version update

---

errtracker/errtracker.go
errtracker/errtracker_test.go

errtracker: include kernel version in error reports

---

tests/lib/failover/inject_rclocalcrash.sh
tests/main/failover/task.yaml

Proposing again these changes, they work consistently fine executing on linode, I've added a debug section just in case.

tests: failover test for rc.local crash

---

overlord/snapstate/snapmgr.go
overlord/snapstate/snapmgr_test.go

More details for our error reports.

snapstate: include change kind/summary in error report

---

overlord/ifacestate/helpers.go

This should fix existing snaps failing with kernel 4.4.0-65.86 
I will look into how this can be converted to a task next.

ifacestate: re-generate apparmor in InterfaceManager.initialize()

---

interfaces/builtin/all.go
interfaces/builtin/all_test.go
interfaces/builtin/autopilot.go
interfaces/builtin/autopilot_test.go
interfaces/builtin/basedeclaration.go
interfaces/builtin/basedeclaration_test.go
snap/implicit.go

Allow applications to export their ui status over dbus

interfaces: interface to allow autopilot introspection

---

tests/main/docker/task.yaml

tests: remove workaround for docker again, snap-declaration is fixed now

---

cmd/snap-confine/mount-support.c

This patch removes some boilerplate code around all the mount calls by
replacing them with a call to sc_do_mount() that does automatic logging
and error checks.

cmd/snap-confine: use sc_do_mount everywhere

---

interfaces/builtin/dbus_test.go

interfaces/builtin: small refactor of dbus tests

---

interfaces/builtin/location_control.go

@jdstrand and @zyga would appreciate your feedback here.

[interfaces] Enable location.Service.Provider in dbus policy.

---

interfaces/backends/backends.go
spread.yaml

This reverts commit 5f929a7ef1828fd008f7ab6e92f18e5e539c5a8b as
suggested by Gustavo.

misc: revert "Log if the system goes into ForceDevMode"

---

interfaces/mount/backend.go
interfaces/mount/change.go
interfaces/mount/entry.go
interfaces/mount/spec.go

interfaces/mount: fix golint issues

---

tests/regression/lp-1644439/task.yaml

tests: fix incorrect shell expression

---

.travis.yml

Adds `quiet` option to travis' git config according to https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/git/clone.rb#L67

.travis.yml: add option to make raw log less noisy

---

interfaces/apparmor/backend_test.go

We are currently seeing build failures in https://launchpad.net/~snappy-dev/+archive/ubuntu/edge/+packages - this branch should fix those.

tests: ensure we mock force dev mode as well to fix FTBFS in sbuild

---

interfaces/mount/change.go
interfaces/mount/change_test.go

interfaces/mount: add Change.String for readable output

---

overlord/snapstate/backend.go
overlord/snapstate/backend/aliases.go
overlord/snapstate/backend/aliases_test.go
overlord/snapstate/backend_test.go

This was actually potential bugs in the waiting.

overlord/snapstate: make UpdateAliases idempotent, simplify the backend interface bits for aliases not used anymore (aliases v2)

---

client/client.go
cmd/snap/cmd_snap_op.go
cmd/snap/error.go
cmd/snap/main.go
daemon/api.go
daemon/response.go
overlord/snapstate/check_snap.go
overlord/snapstate/check_snap_test.go
overlord/snapstate/snapstate_test.go
tests/main/classic-confinement/task.yaml
tests/main/install-store/task.yaml

more a strawman than anything else at this stage

client,cmd/snap: first pass at client messaging around modes

---

tests/lib/prepare.sh

Applies debian's solution to improve entropy to ubuntu classic systems.

tests: improve entropy also for ubuntu

---

vendor/vendor.json

The change was obtained with 'govendor remove +unused'

vendor: remove unused packages

---

interfaces/seccomp/backend.go

interfaces/seccomp: document Backend.NewSpecification

---

daemon/api_test.go
daemon/daemon.go
daemon/daemon_test.go

Btw go1.8 has similar behavior built-in in Server.Shutdown.

daemon: teach the daemon to wait on active connections when shutting down

---

tests/completion/indirect/task.yaml
tests/unit/c-unit-tests/task.yaml
tests/unit/go/task.yaml

Shellcheck improvements for the scripts on tests/unit

tests: shellcheck improvements for unit tasks

---

tests/nested/core-revert/task.yaml
tests/nested/extra-snaps-assertions/task.yaml
tests/nested/image-build/task.yaml

Shellcheck improvements for the scripts on tests/nested

tests: shellcheck improvements for tests/nested tasks

---

cmd/snap-seccomp/main_test.go

The seccomp.GetSyscallFromNameByArch() may return negative numbers
with special meaning for libseccomp. Unfortunately there is no way
to resolve these syscalls to the "real" number using libseccomp.
So we need to resolve the impacted arch/syscall ourself.

snap-seccomp: fix snap-seccomp tests in artful

---

overlord/devicestate/firstboot_test.go
overlord/state/change.go
overlord/state/change_test.go

Because WaitFor builds a Kⁿ, make Abort not try to build a n! list.

overlord/state: Abort() only visits each task once

---

cmd/snap/notes.go
tests/main/listing/task.yaml

cmd/snap: include snap type in notes

---

overlord/configstate/config/transaction.go
overlord/hookstate/ctlcmd/get_test.go
tests/lib/snaps/snapctl-hooks/meta/hooks/configure
tests/main/snap-set/task.yaml

Fix for https://bugs.launchpad.net/snapd/+bug/1699768

snapd: fix for snapctl get panic on null config values.

---

tests/nightly/docker/task.yaml
tests/nightly/unity/task.yaml
tests/regression/lp-1595444/task.yaml
tests/regression/lp-1597839/task.yaml
tests/regression/lp-1597842/task.yaml
tests/regression/lp-1599891/task.yaml
tests/regression/lp-1607796/task.yaml
tests/regression/lp-1613845/task.yaml
tests/regression/lp-1615113/task.yaml
tests/regression/lp-1618683/task.yaml
tests/regression/lp-1630479/task.yaml
tests/regression/lp-1641885/task.yaml
tests/regression/lp-1644439/task.yaml
tests/regression/lp-1665004/task.yaml
tests/regression/lp-1667385/task.yaml
tests/regression/lp-1693042/task.yaml
tests/upgrade/basic/task.yaml

Shellcheck improvements for the scripts on tests/nightly tests/upgrade
and tests/regression

tests: shellcheck improvements for nightly upgrade and regressions tests

---

tests/lib/dirs.sh
tests/lib/mkpinentry.sh
tests/lib/names.sh
tests/lib/nested.sh
tests/lib/network.sh
tests/lib/os-release.16
tests/lib/pinentry-fake.sh
tests/lib/pkgdb.sh
tests/lib/prepare-project.sh
tests/lib/prepare.sh
tests/lib/reset.sh
tests/lib/store.sh

Shellcheck improvements over all the scripts on tests/lib dir

tests: shellcheck improvements for tests/lib scripts

---

daemon/api.go
interfaces/policy/basedeclaration_test.go
overlord/snapstate/snapstate.go
partition/grubenv/grubenv.go
strutil/strutil.go
strutil/strutil_test.go

also strutil.SortedListContains.

many: introduce and use strutil.ListContains

---

data/systemd/snapd.core-fixup.sh

As suggested by @chipaca in PR #3557

systemd: add explicit sync to snapd.core-fixup.sh

---

packaging/ubuntu-14.04/changelog
packaging/ubuntu-16.04/changelog

This will also give us proper edge builds again.

Merge release/2.26 back into master

---

cmd/cmd.go

Trivial docstring improvement.

cmd: fix mustUnsetenv docstring (thanks to Chipaca)

---

snap/snapenv/snapenv.go

snap/snapenv: document the use of CoreSnapMountDir for SNAP

---

interfaces/builtin/time_control.go

Simplify the time-control interface by using common Interface.

interfaces: convert time-control to common iface

---

interfaces/builtin/ppp.go

Simplify the ppp interface by using common Interface.

interfaces: convert ppp to common iface

---

interfaces/builtin/physical_memory_control.go

Simplify the physical_memory_control interface by using common Interface.

interfaces: convert physical_memory_control to common iface

---

interfaces/builtin/optical_drive_test.go

Update the interface testsuite by adding missing test for optical_drive interface

interfaces: add missing test for optical_drive interface.

---

interfaces/builtin/physical_memory_observe.go

Simplify the physical_memory_observe interface by using common Interface.

interfaces: convert physical_memory_observe to common iface

---

interfaces/builtin/opengl_test.go
interfaces/builtin/ppp_test.go

* Test security backend specs one by one(TestAppArmorSpec, TestKModSpec)
* Some tweaks for opengl_test

Improve the test for ppp interface.

---

interfaces/builtin/kvm.go
interfaces/builtin/kvm_test.go

interfaces: convert kvm to common iface

---

interfaces/builtin/joystick.go
interfaces/builtin/joystick_test.go

interfaces: convert joystick to common iface

---

interfaces/builtin/io_ports_control.go
interfaces/builtin/io_ports_control_test.go

interfaces: convert io_ports_control to common iface

---

interfaces/builtin/firewall_control_test.go
interfaces/builtin/network_control_test.go
interfaces/builtin/optical_drive_test.go
interfaces/builtin/physical_memory_control_test.go
interfaces/builtin/physical_memory_observe_test.go
interfaces/builtin/ppp_test.go
interfaces/builtin/raw_usb_test.go
interfaces/builtin/tpm_test.go

* improve test for raw-usb interface.
* improve test for tpm interface.
* improve test for network control interface.
* improve test for firewall control interface.
* nitpicking on TestAppArmorSpec for some interfaces for simplicity purposes.

interfaces: improve and tweak bunch of interfaces test cases.

---

interfaces/builtin/lxd.go
interfaces/builtin/lxd_test.go

interfaces: convert lxd to common iface

---

osutil/flock_test.go

Older versions of flock (like the version in 14.04) do not support
the --conflict-exit-code switch. Skip the test in those cases.
This fixes a build failure on trusty.

osutil: ensure TestLockUnlockWorks uses supported flock

---

overlord/auth/auth.go
overlord/auth/auth_test.go
overlord/devicestate/devicemgr.go
overlord/devicestate/devicestate_test.go
overlord/managers_test.go
store/auth.go
store/auth_test.go
store/store.go
store/store_test.go

follow up to #3712 as requested by @chipaca

overlord,store: no piles of return args for methods gathering device session request params

---

interfaces/builtin/camera_test.go

Update the interface testsuite by adding missing test for camera interface

interfaces: add missing test for camera interface.

---

interfaces/builtin/lxd_support.go
interfaces/builtin/lxd_support_test.go

interfaces: convert lxd_support to common iface

---

interfaces/builtin/alsa_test.go
interfaces/builtin/bluez_test.go
interfaces/builtin/fuse_support_test.go
interfaces/builtin/kernel_module_control_test.go
interfaces/builtin/raw_usb_test.go
interfaces/builtin/udisks2_test.go

* improve test for udisk2 interface.
* improve test for raw usb interface.
* improve test for kernel module control interface.
* improve test for bluez interface.
* improve test for fuse support interface.
* improve test for alsa interface.

interfaces: a bunch of interfaces test improvement

---

packaging/fedora/snapd.spec

Fedora Dist-Git carries changes that should be merged back into the snapd reference packaging files.
Signed-off-by: Neal Gompa <ngompa13@gmail.com>

packaging/fedora: Merge changes from Fedora Dist-Git

---

overlord/hookstate/hookmgr.go
overlord/hookstate/hookstate_test.go

Cherry-pick of https://github.com/snapcore/snapd/pull/3816 for 2.27.

hooks: do not error when hook handler is not registered (2.27)

---

vendor/vendor.json

vendor: fix artifact from manually editing vendor/vendor.json 

---

cmd/snap-seccomp/main_test.go

This fixes a FTBFS on arm64, e.g. https://launchpad.net/~snappy-dev/+archive/ubuntu/edge/+build/13314071

tests: deal with __PNR_chown on aarch64 to fix FTBFS on arm64

---

spread.yaml

Do this until other fires are under control.

spread.yaml: turn suse to manual given that it's breaking master

---

packaging/ubuntu-14.04/control
packaging/ubuntu-16.04/control

This should also go to master, *maybe* via https://github.com/snapcore/snapd/pull/3835 if @chipaca adds it there :)

debian: improve package description

---

daemon/api_test.go
overlord/managers_test.go

many: fix TestSetConfNumber missing an Unlock and other fragility improvements

---

daemon/api_test.go

Backport of https://github.com/snapcore/snapd/pull/3894 (unfortunately did not cherry-pick cleanly)

many: fix TestSetConfNumber missing an Unlock and other fragility improvements (2.28)

---

overlord/assertstate/assertstate_test.go
overlord/devicestate/devicestate_test.go
overlord/devicestate/firstboot_test.go
overlord/hookstate/hookstate_test.go
overlord/ifacestate/ifacestate_test.go
overlord/managers_test.go

overlord: use overlord.Mock in more tests, make sure we check the outcome of Settle

---

daemon/api_test.go
overlord/devicestate/devicestate_test.go
overlord/devicestate/firstboot_test.go
overlord/snapstate/snapmgr.go

daemon: reach for Overlord.Loop less thanks to overlord.Mock

---

asserts/asserts.go
asserts/asserts_test.go

asserts: add empty values check in HeadersFromPrimaryKey

---

interfaces/builtin/network.go

Add permissions to run netcat to network interface

interfaces/network: allow using netcat as client

---

asserts/repair.go
asserts/repair_test.go
cmd/snap-repair/runner.go
cmd/snap-repair/runner_test.go

asserts,cmd/snap-repair: represent RepairID internally as an int

---

snap/info_test.go

snap: correct typo in test name

---

tests/main/ubuntu-core-services/task.yaml

Minor change in the name what is making tests fail on dragonboard

tests: fix ubuntu core services 

---

interfaces/core.go
interfaces/repo.go

Just a baby step to introduce new Connection struct, it's meant to be used universally across snapd.

interfaces: add Connection type

---

cmd/snap-repair/runner_test.go

The tests are run as root under some test runners (like autopkgtest).
In this case os.Chmod(path, 0555) will not prevent writing to the
"path" because permissions are for lusers.
Skip these tests when run as root for now. We could make them work
with osutil.Chattr() but given that we test this already it is
probably not worth it.

cmd/snap-repair: fix tests when running as root

---

HACKING.md

Note to supply a testing snap-seccomp file when detected security error while testing snapd

Added note in HACKING file 

---

.travis.yml

This should unbreak travis tests.

tests: do not use http://canihazip.com/ which appears to be down

---

cmd/autogen.sh

cmd: add autogen case for solus

---

packaging/arch/PKGBUILD
packaging/ubuntu-14.04/rules
packaging/ubuntu-16.04/rules

Follow up from https://github.com/snapcore/snapd/pull/4011

packaging: update nvidia configure options

---

cmd/libsnap-confine-private/classic-test.c
cmd/libsnap-confine-private/string-utils-test.c

cmd/libsnap: enable two stranded tests

---

dirs/dirs.go
overlord/storestate/storestate.go
store/cache.go
store/cache_test.go
store/export_test.go
store/store.go
store/store_test.go

Implement the download cache as outlined in
https://forum.snapcraft.io/t/2374

store: add download caching

---

packaging/fedora/snapd.spec
packaging/opensuse-42.2/snapd.changes
packaging/opensuse-42.2/snapd.spec
packaging/ubuntu-14.04/changelog
packaging/ubuntu-16.04/changelog

Trivial update so that we get our edge builds with proper versioning back.

release: merge 2.29~rc1 changelog

---

po/am.po
po/bs.po
po/ca.po
po/cs.po
po/da.po
po/de.po
po/el.po
po/en_GB.po
po/es.po
po/fi.po
po/fr.po
po/hr.po
po/ia.po
po/id.po
po/it.po
po/ja.po
po/lt.po
po/ms.po
po/nb.po
po/oc.po
po/pt.po
po/pt_BR.po
po/ru.po
po/sv.po
po/tr.po
po/ug.po
po/zh_CN.po
tests/main/i18n/task.yaml

Fwiw, ths will fail currently because we actually crash for some locales - this will get fixed with #4050.

tests,po: sync translations from LP and add regression test for LP:1723974

---

tests/main/snapctl-services/task.yaml

Cherry pick the fix for the race in services test into 2.29

tests: cherry pick the fix for services test into 2.29

---

spread.yaml

The new Ubuntu 18.04 series has openend. We need to update our
tests for that.

spread: welcome bionic beaver

---

cmd/snap-update-ns/export_test.go

This patch expands the fault injection code to allow varying the result
programmatically. This can be used to return an error once and return no
error on 2nd and subsequent attempts, which matches "try, work around,
try again" test patterns.

cmd/snap-update-ns: allow fault injection to provide dynamic result

---

asserts/store_asserts.go
asserts/store_asserts_test.go
cmd/snap/cmd_known_test.go
overlord/assertstate/assertstate.go
overlord/assertstate/assertstate_test.go
overlord/auth/auth.go
overlord/auth/auth_test.go
overlord/devicestate/devicemgr.go
overlord/devicestate/devicestate.go
overlord/devicestate/devicestate_test.go
overlord/managers_test.go
store/store.go
store/store_test.go
tests/main/prepare-image-grub/task.yaml

many:  have a timestamp on store assertions

---

tests/lib/assertions/fake.store
tests/lib/store.sh
tests/main/set-proxy-store/task.yaml

tests:  add a spread test for proxy.store setting together with store assertion

---

overlord/state/change.go
overlord/state/change_test.go

Implemented a helper which returns all tasks from given lanes. This will be use in #4158.

state: add change.LaneTasks helper

---

cmd/snap-update-ns/change.go

cmd/snap-update-ns: tweak changePerform

---

HACKING.md

HACKING: fix path in snap install

---

daemon/api_test.go
interfaces/builtin/all.go
interfaces/builtin/all_test.go
snap/info.go
snap/info_snap_yaml.go
snap/info_test.go

many: reject bad plugs/slots 2.29

---

cmd/Makefile.am
cmd/snap-confine/snap-confine.c
packaging/fedora/snapd.spec
packaging/opensuse-42.2/snapd.spec
spread.yaml
tests/main/lxd/task.yaml

Port of https://github.com/snapcore/snapd/pull/4246 for 2.29

 snap-confine: fix snap-confine under lxd (2.29)

---

overlord/snapstate/backend_test.go
overlord/snapstate/snapstate_test.go
snap/info.go
store/store.go
store/store_test.go

Keep the data about payed snaps in the state just like we do with
private snaps.

snapstate,store: store if a snap is a paid snap in the sideinfo

---

overlord/snapstate/handlers.go
overlord/snapstate/handlers_link_test.go
overlord/snapstate/snapmgr.go

Trivial PR as a first step towards fixing LP https://bugs.launchpad.net/snapd/+bug/1733910

snapstate: store userID in snapstate

---

interfaces/builtin/netlink_connector.go
tests/lib/snaps/test-snapd-netlink-connector/bin/bind
tests/lib/snaps/test-snapd-netlink-connector/meta/snap.yaml
tests/main/interfaces-netlink-connector/task.yaml

Adding test for netlink-connector interface

---

packaging/opensuse-42.2/snapd.spec

Also fixes project prepare on openSUSE

packaging/opensuse-42.2: package and use snap-mgmt

---

cmd/snap-mgmt/snap-mgmt.sh.in

Fixing the issues from #4316 #4308

cmd/snap-mgmt: fixes

---

interfaces/builtin/alsa_test.go
interfaces/builtin/avahi_control_test.go
interfaces/builtin/avahi_observe_test.go
interfaces/builtin/bluez_test.go
interfaces/builtin/broadcom_asic_control_test.go
interfaces/builtin/camera_test.go
interfaces/builtin/firewall_control_test.go
interfaces/builtin/framebuffer_test.go
interfaces/builtin/fuse_support_test.go
interfaces/builtin/gpio_memory_control_test.go
interfaces/builtin/hardware_random_control_test.go
interfaces/builtin/hardware_random_observe_test.go
interfaces/builtin/io_ports_control_test.go
interfaces/builtin/joystick_test.go
interfaces/builtin/kernel_module_control_test.go
interfaces/builtin/kvm_test.go
interfaces/builtin/network_control_test.go
interfaces/builtin/opengl_test.go
interfaces/builtin/optical_drive_test.go
interfaces/builtin/physical_memory_control_test.go
interfaces/builtin/physical_memory_observe_test.go
interfaces/builtin/ppp_test.go
interfaces/builtin/raw_usb_test.go
interfaces/builtin/time_control_test.go
interfaces/builtin/tpm_test.go
interfaces/builtin/udisks2_test.go
interfaces/repo.go

Followup to #4303 - update FIXME comments with some more detail.

interfaces: update fixme comments

---

snap/info.go
snap/info_snap_yaml.go
snap/info_snap_yaml_test.go

This PR contains just the data types and snap YAML changes #4340. I've pulled the change out into a separate PR in hope of landing this faster.

snap: YAML and data structures for app before/after ordering

---

interfaces/builtin/gpg_keys.go
interfaces/builtin/gpg_keys_test.go
interfaces/builtin/gpg_public_keys.go
interfaces/builtin/gpg_public_keys_test.go
interfaces/builtin/ssh_keys.go
interfaces/builtin/ssh_keys_test.go
interfaces/builtin/ssh_public_keys.go
interfaces/builtin/ssh_public_keys_test.go
tests/lib/snaps/test-snapd-policy-app-consumer/meta/snap.yaml

PR https://github.com/snapcore/snapd/pull/4100 for 2.30

add ssh-keys, ssh-public-keys, gpg-keys and gpg-public keys interfaces for 2.30

---

interfaces/builtin/desktop.go
interfaces/builtin/unity7.go

PR https://github.com/snapcore/snapd/pull/4384 for 2.30.

interfaces/desktop,unity7: allow status/activate/lock of screensavers for 2.30

---

interfaces/builtin/system_observe.go
interfaces/builtin/system_observe_test.go

interfaces: add /proc/partitions to system-observe

---

daemon/api_test.go
overlord/auth/auth.go
overlord/auth/auth_test.go

overlord/auth,daemon: introduce an explicit auth.ErrInvalidUser

---

overlord/auth/auth.go
overlord/snapstate/autorefresh.go

overlord/snapstate: fix auto-refresh summary for 2 snaps

---

tests/lib/prepare-restore.sh

tests/lib/prepare-restore: disable rate limiting in journald

---

tests/main/catalog-update/task.yaml

This code has a missing $() and sleep.

tests: fix catalog-update wait loop

---

daemon/api_test.go
overlord/assertstate/assertmgr.go
overlord/assertstate/assertstate_test.go
overlord/cmdstate/cmdmgr.go
overlord/cmdstate/cmdstate_test.go
overlord/devicestate/devicemgr.go
overlord/devicestate/devicestate_test.go
overlord/hookstate/hookmgr.go
overlord/hookstate/hookstate_test.go
overlord/ifacestate/ifacemgr.go
overlord/ifacestate/ifacestate_test.go
overlord/overlord_test.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate_test.go
overlord/state/taskrunner.go
overlord/state/taskrunner_test.go
overlord/stateengine.go
overlord/stateengine_test.go

Added KnowTaskKinds helper to taskrunner and all managers, in preparation for implementing handling of unknown tasks.

taskrunner/many: KnownTaskKinds helper

---

asserts/signtool/sign.go
asserts/signtool/sign_test.go

This adds a way to specify complementary headers when using signtool.Sign so that it can be used for tools that compute/fill-in some headers to complete input.

asserts/signtool: support for building tools on top that fill-in/compute some headers

---

cmd/snap/cmd_find.go
tests/main/searching/task.yaml

This was reported in https://bugs.launchpad.net/snapd/+bug/1740605

snap: fix snap find " " output

---

cmd/snap-update-ns/export_test.go
cmd/snap-update-ns/utils.go

Just some preparatory work for upcoming tests / other cleanups.

cmd/snap-update-ns: improve mocking for tests

---

snap/gadget.go
snap/gadget_test.go

There is a bugreport that gadget.yaml parsing does not work for
snaps with multiple volumes. This PR fixes this and also adds
a multi volume gadget.yaml for (regression) testing.
It also fixes the incorrect parsing of "label" to "filesystem-label".

snap: fix gadget.yaml parsing for multi volume gadgets

---

spread.yaml

Checking if bumping dnf number of retries will be sufficient to get this going.

spread: trying to re-enable tests on Fedora

---

overlord/snapstate/snapstate_test.go

overlord/snapstate: fix gofmt -s -l

---

cmd/snap-update-ns/export_test.go
cmd/snap-update-ns/utils.go

This branch collects assorted test improvements from https://github.com/snapcore/snapd/pull/4452 in a much more approachable and reviewable package.

cmd/snap-update-ns: new test features

---

tests/lib/snaps/test-snapd-after-before-service/bin/start
tests/lib/snaps/test-snapd-after-before-service/meta/snap.yaml
tests/main/snap-service-after-before/task.yaml

tests/main/snap-service-after-before: add test for after/before service ordering

---

tests/lib/snaps.sh
tests/lib/snaps/test-snapd-hardware-random-control/bin/check
tests/lib/snaps/test-snapd-hardware-random-observe/bin/check
tests/lib/snaps/test-snapd-hardware-random-observe/meta/snap.yaml
tests/main/interfaces-hardware-observe/task.yaml
tests/main/interfaces-hardware-random-control/task.yaml
tests/main/interfaces-hardware-random-observe/task.yaml

It also includes some improvements for the test interfaces-hardware-
random-control.

New spread test for hardware-random-observe interface

---

data/dbus/io.snapcraft.Launcher.service.in
interfaces/dbus/backend.go

This should fix dbus activation on bionic
My testing indicates this fixes the issue with url opening in 18.04.

data/dbus: add AssumedAppArmorLabel=unconfined

---

tests/main/interfaces-netlink-connector/task.yaml

The connected pattern is fixed and checked after the connection is done.

tests: fix for test interface-netlink-connector

---

interfaces/builtin/netlink_audit.go
tests/lib/snaps/test-snapd-netlink-audit/bin/bind
tests/lib/snaps/test-snapd-netlink-audit/meta/snap.yaml
tests/main/interfaces-netlink-audit/task.yaml
tests/main/interfaces-netlink-connector/task.yaml

tests: new spread test for netlink-audit interface

---

interfaces/apparmor/template.go
interfaces/builtin/bluetooth_control.go
interfaces/builtin/desktop.go
interfaces/builtin/network_observe.go
interfaces/builtin/screen_inhibit_control.go
interfaces/builtin/unity7.go

https://github.com/snapcore/snapd/pull/4535 for 2.31.

interfaces: miscellaneous policy updates - 2.31

---

packaging/ubuntu-14.04/changelog
packaging/ubuntu-16.04/changelog

Merge the 2.31~rc1 changes back into master.

release: 2.31~rc1

---

spread.yaml

@mvo5 I didn't add the removals on that 2nd patch. I should get some sleep.

spread: remove more EOLed releases

---

data/systemd/Makefile

data/systemd: tweak comment

---

snap/validate.go

snap: apply some golint suggestions

---

interfaces/system_key.go
interfaces/system_key_test.go
release/apparmor.go
release/apparmor_test.go

release, interfaces: add new release.AppArmorFeatures helper

---

snap/squashfs/squashfs.go
snap/squashfs/squashfs_test.go

When unsquashfs fails to write files this is currently not reported
via the exit code. There is an upstream PR open about this:
https://github.com/plougher/squashfs-tools/pull/46
However this is not merged yet. While waiting for this a workaround
is to look for "failed" in the unsquashfs output. This string is
not translated (nothing in unsquashfs is) and it is used pretty
consistently for error reporting.
This would have detected the prepare-image error we had on arm64
where the tmpfs was too small and the kernel.img file was not unpacked.
This was not detected by us because unsquashfs returned no error.

snap: detect unsquashfs write failures

---

interfaces/builtin/avahi_observe.go

Signed-off-by: Ondrej Kubik <ondrej.kubik@canonical.com>

Fixing denial for when using avahi-observe slot

---

osutil/mountentry.go

osutil: add and update docstrings

---

systemd/systemd.go

systemd: update comment on SocketsTarget

---

cmd/snap/cmd_run.go

Followup on https://github.com/snapcore/snapd/pull/4491

snap: improve `snap run` comments/naming

---

tests/lib/pkgdb.sh

These packages are not used any more after PR
https://github.com/snapcore/snapd/pull/4354

tests: removing packages which are not needed anymore to generate random data

---

osutil/syncdir.go

This is a little refactor to make it really trivial to add FileState support to the FileEquals checker.

osutil: refactor EnsureFileState to separate out the comparator

---

vendor/vendor.json

vendor: resync formatting of vendor.json

---

cmd/snap-repair/cmd_run_test.go
cmd/snap-repair/main_test.go
cmd/snap-repair/runner.go
cmd/snap-repair/runner_test.go
httputil/useragent.go

cmd/snap-repair,httputil: set snap-repair User-Agent on requests

---

overlord/snapstate/handlers_prereq_test.go

Fixes the following test failure:
```
FAIL: handlers_prereq_test.go:155: prereqSuite.TestDoPrereqRetryWhenBaseInFlight
handlers_prereq_test.go:186:
// check that t is not done yet, it must wait for core
c.Check(t.Status(), Equals, state.DoingStatus)
... obtained state.Status = 4 ("Done")
... expected state.Status = 3 ("Doing")
OOPS: 351 passed, 1 FAILED
--- FAIL: TestSnapManager (6.13s)
FAIL
coverage: 86.7% of statements
exit status 1
FAIL	github.com/snapcore/snapd/overlord/snapstate	6.153s
```

overlord/snapstate: fix task iteration order in TestDoPrereqRetryWhenBaseInFlight

---

tests/main/layout/task.yaml

tests: add debug for layout test

---

snap/squashfs/squashfs.go
snap/squashfs/squashfs_test.go

in the hopes of this being helpful, and before moving on from it and
forgetting, I offer you a BuildDate function and method for squashfs
snaps.

snap/squashfs: add BuildDate

---

timeutil/export_test.go
timeutil/human.go
timeutil/human_test.go

(I'll be using this soon, if you'd rather see it in action before reviewing)

timeutil: timeutil.Human(t) gives a human-friendly string for t

---

client/client.go
cmd/snap/cmd_snap_op.go
cmd/snap/cmd_snap_op_test.go
daemon/api.go
overlord/configstate/configcore/refresh.go
overlord/configstate/configcore/refresh_test.go
overlord/devicestate/firstboot_test.go
overlord/devicestate/handlers.go
overlord/snapstate/autorefresh.go
overlord/snapstate/autorefresh_test.go
overlord/snapstate/export_test.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate_test.go
snap/info.go
snap/info_test.go
tests/lib/reset.sh
timeutil/schedule.go
timeutil/schedule_test.go

many: support holding refreshes by setting refresh.hold (2.32)

---

data/polkit/io.snapcraft.snapd.policy
po/its/polkit.its
update-pot

This mirrors the commits of [PR #4723](https://github.com/snapcore/snapd/pull/4723) which has been merged into snapcore:master.

data: translate polkit strings (2.32)

---

store/store.go
store/store_test.go

store: reorg auth refresh  (2.32)

---

cmd/snap-mgmt/snap-mgmt.sh.in
packaging/ubuntu-14.04/snapd.postrm
packaging/ubuntu-16.04/snapd.postrm
packaging/ubuntu-16.04/tests/integrationtests
tests/lib/names.sh
tests/lib/pkgdb.sh
tests/lib/prepare.sh
tests/lib/reset.sh
tests/lib/snaps/test-snapd-service/bin/reload

On my bionic system I saw a bunch of shellcheck errors. This PR fixes those.

many: fix shellcheck warnings in bionic

---

overlord/devicestate/devicemgr.go
overlord/devicestate/devicestate_test.go
overlord/devicestate/handlers.go

devicestate: add DeviceManager.Registered returning a channel closed when the device is known to be registered

---

client/client.go
cmd/snap/cmd_disconnect.go
daemon/api.go
daemon/api_test.go
daemon/response.go
tests/main/snap-disconnect/task.yaml

Cherry-pick of #4798 for 2.32.

snap: don't create empty Change with "Hold" state on disconnect (2.32)

---

interfaces/builtin/modem_manager.go

intrefaces/builtin: let MM change qmi device attributes

interfaces/builtin: let MM change qmi device attributes

---

update-pot

This will fix https://launchpad.net/bugs/1747272
(this is https://github.com/snapcore/snapd/pull/4885 for master)

po: specify charset in po/snappy.pot

---

daemon/daemon.go
daemon/daemon_test.go
polkit/authority.go

This fixes https://launchpad.net/bugs/1751327

polkit: Pass caller uid to PolicyKit authority

---

tests/lib/prepare.sh

tests: copy or sanity check core users using usernames

---

packaging/fedora/snapd.spec
packaging/ubuntu-14.04/changelog
packaging/ubuntu-16.04/changelog
spread.yaml
tests/lib/prepare.sh

tests: disentangle etc vs extrausers in core tests (2.32)

---

vendor/vendor.json

vendor: update gopkg.in/yaml.v2 to the latest version

---

timeutil/human.go
timeutil/human_test.go

timeutil: in Human, count days with fingers

---

cmd/snap-update-ns/utils.go

This patch cleans up unfortunate function argument name from "i" to
"segNum". All functions participating in the segmented path operations
are altered.

cmd/snap-update-ns: rename i to segNum

---

interfaces/builtin/content.go
interfaces/builtin/content_test.go

This is a 3.32 back port of #4932
* Content-interface: add AppArmor rule so slot can access shared directory using plug's namespace
* Add test
* Improve comment

interfaces/content: add rule so slot can access writable files at plug's mount point

---

overlord/ifacestate/export_test.go
overlord/ifacestate/handlers.go
overlord/ifacestate/ifacestate_test.go

Helper function that  introduced in one of the interface-hooks PRs (was interface hooks review by Samuele), proposing it separately now as it will help with auto-connect fix.

ifacestate: injectTasks helper.

---

interfaces/system_key.go
overlord/ifacestate/helpers.go
tests/main/snap-system-key/task.yaml

See https://bugs.launchpad.net/snappy/+bug/1760841

interfaces: make system-key more robust against invalid fstab entries

---

overlord/ifacestate/export_test.go
overlord/ifacestate/handlers.go
overlord/ifacestate/ifacestate_test.go

Inject auto-connect task for compatibility.
https://github.com/snapcore/snapd/pull/4981 and https://github.com/snapcore/snapd/pull/4974 for 2.32

ifacestate: inject autoconnect (#4981)

---

overlord/ifacestate/export_test.go
overlord/ifacestate/helpers.go
overlord/ifacestate/ifacestate_test.go

* add to the repo also snaps that are pending being activated but have a done setup-profiles
* double check that name on setup-profiles also matches

ifacestate: add to the repo also snaps that are pending being activated but have a done setup-profiles (2.32)

---

interfaces/apparmor/template.go
interfaces/builtin/firewall_control.go
interfaces/builtin/fuse_support.go
interfaces/builtin/process_control.go

https://github.com/snapcore/snapd/pull/5006 for 2.32.

interfaces: misc updates for default, firewall-control, fuse-support and process-control - 2.32

---

daemon/daemon.go
overlord/hookstate/hookmgr.go
overlord/hookstate/hookstate_test.go

Wait gracefully for running hooks when restarting and stop the hook manager before closing the snapctl socket.

 daemon,overlord/hookstate: stop/wait for running hooks before closing the snapctl socket (2.32)

---

cmd/snap/cmd_snap_op.go
daemon/api.go
daemon/api_test.go
overlord/hookstate/ctlcmd/services_test.go
overlord/managers_test.go
overlord/snapstate/autorefresh_test.go
overlord/snapstate/backend.go
overlord/snapstate/backend_test.go
overlord/snapstate/export_test.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_download_test.go
overlord/snapstate/handlers_prereq_test.go
overlord/snapstate/refreshhints_test.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_test.go
overlord/snapstate/storehelpers.go
store/details_v2.go
store/details_v2_test.go
store/errors.go
store/store.go
store/store_test.go
store/storetest/storetest.go
tests/lib/fakestore/store/store.go
tests/lib/fakestore/store/store_test.go

overlord/snapstate: introduce envvars to control the channels for bases and prereqs (2.32)

---

snap/info.go
snap/validate.go
wrappers/services.go
wrappers/services_gen_test.go

This addresses open review feedback points from #5043. This is a separate PR because the changes are cosmetic and it was important to get 5043 into edge.

snap,wrappers: address review feedback from #5043

---

spread.yaml

Experiment to see if the bionic test failures go away with this.

spread.yaml: move bionic image forward

---

spread.yaml

spread: bump delta reference to 2.32.5

---

snap/info.go
snap/validate.go
wrappers/services.go
wrappers/services_gen_test.go

snap,wrappers: address review feedback from #5043 (2.32)

---

store/store.go

store: getStructFields takes pointers now

---

testutil/lowlevel.go

testutil: document all fake syscall/os functions

---

testutil/lowlevel.go
testutil/lowlevel_test.go

This implementation mimics the existing OsLstat differing in just the
type of the returned information. This will allow us to fix an issue in
the writable mimic that requires using syscall.Lstat to read the mode
and, most importantly, ownership of the mimicked directory.

testutil: add test helper for SysLstat

---

overlord/cmdstate/cmdstate_test.go

cmdstate: add missing test for default timeout handling

---

spread.yaml

spread: add adt for ubuntu 18.10

---

HACKING.md

HACKING: fix typos

---

spread.yaml

This will also unbreak the cosmic autopkgtests.

spread.yaml: add cosmic (18.10) to autopkgtest/qemu

---

tests/completion/indirect/task.yaml
tests/completion/simple/task.yaml
tests/completion/snippets/task.yaml
tests/main/abort/task.yaml
tests/main/alias/task.yaml
tests/main/auto-aliases/task.yaml
tests/main/auto-refresh-private/task.yaml
tests/main/auto-refresh/task.yaml
tests/main/base-snaps/task.yaml
tests/main/canonical-livepatch/task.yaml
tests/main/catalog-update/task.yaml
tests/main/cgroup-freezer/task.yaml
tests/main/classic-confinement-not-supported/task.yaml
tests/main/classic-confinement/task.yaml
tests/main/classic-custom-device-reg/task.yaml
tests/main/classic-ubuntu-core-transition-auth/task.yaml
tests/main/classic-ubuntu-core-transition-two-cores/task.yaml
tests/main/classic-ubuntu-core-transition/task.yaml
tests/main/completion/task.yaml
tests/main/config-versions/task.yaml
tests/unit/spread-shellcheck/must

tests: shellchecks, part 1

---

data/systemd/snapd.core-fixup.sh
tests/main/snap-core-fixup/task.yaml

This addresses the review feedback from 5147 that was left to get the PR landed sooner.

core-fixup: address review feedback from #5147

---

boot/kernel_os.go
boot/kernel_os_test.go
partition/bootloader.go

This implements the suggested improvements from PR  #5145.

boot,partition: improve tests/docs around SetNextBoot()

---

snap/broken.go
snap/container.go
snap/info.go

I did a quick review over snap package doc comments. This is the result with some fixes and additions.

snap: some doc comments fixes and additions

---

cmd/snap-confine/mount-support.c
cmd/snap-confine/mount-support.h
cmd/snap-confine/snap-confine.c

cmd/snap-confine: applied make fmt

---

tests/main/econnreset/task.yaml
tests/main/lxd/task.yaml

tests: backport lxd force stop and econnreset fixes (2.33)

---

data/selinux/snappy.fc
data/selinux/snappy.te

Update the SELinux policy to resolve error messages on a Fedora 28 system.
I have signed the license agreement.

Update SELinux Policy

---

interfaces/builtin/dvb.go
interfaces/builtin/dvb_test.go
tests/lib/snaps/test-snapd-policy-app-consumer/meta/snap.yaml

This is a first draft of the dvb interface as discussed here: https://forum.snapcraft.io/t/new-interface-requirement-dvb/3497
Now all DVB device files are included!

interfaces: add the dvb interface

---

overlord/snapstate/backend_test.go

snapstate: stop using evolving SnapSpec internally, use an internal-only snapSpec instead

---

interfaces/builtin/joystick.go
interfaces/builtin/joystick_test.go
interfaces/builtin/mir.go
interfaces/builtin/mir_test.go
interfaces/builtin/wayland.go
interfaces/builtin/wayland_test.go
interfaces/builtin/x11.go
interfaces/builtin/x11_test.go
interfaces/udev/backend.go
interfaces/udev/backend_test.go
interfaces/udev/spec.go
interfaces/udev/udev.go
interfaces/udev/udev_test.go
tests/lib/snaps/test-snapd-event/bin/read-evdev-device
tests/lib/snaps/test-snapd-udev-input-subsystem/bin/read-evdev-kbd
tests/lib/snaps/test-snapd-udev-input-subsystem/meta/snap.yaml
tests/main/security-udev-input-subsystem/task.yaml

This is https://github.com/snapcore/snapd/pull/5250 for 2.33.

many: improve udev trigger on refresh experience (2.33)

---

tests/main/interfaces-timeserver-control/task.yaml

The output has changed between systemd in Ubuntu 16.04 and Ubuntu 18.04.

tests: update interfaces-timeserver-control to core18

---

snap/validate.go
snap/validate_test.go

Add helper for validating snap instance names

snap: helper for validating snap instance names

---

tests/main/security-dev-input-event-denied/task.yaml
tests/main/security-udev-input-subsystem/task.yaml

Tests failing on arm-64 with error:
https://paste.ubuntu.com/p/zCgygSznRp/

tests: fix tests when no keyboad input detected

---

dirs/dirs.go

dirs: fix antergos typo

---

tests/lib/pkgdb.sh
tests/main/interfaces-timeserver-control/task.yaml

This is https://github.com/snapcore/snapd/pull/5482 for 2.34

tests: fix arch tests (2.34)

---

overlord/snapstate/snapmgr.go

overlord/snapstate: improve PlugsOnly comment

---

client/client.go

client: add some existing error kinds that were not listed in client.go

---

daemon/api_test.go
overlord/assertstate/assertmgr.go
overlord/assertstate/assertstate_test.go
overlord/cmdstate/cmdmgr.go
overlord/cmdstate/cmdstate_test.go
overlord/configstate/configstate_test.go
overlord/devicestate/devicemgr.go
overlord/devicestate/devicestate_test.go
overlord/devicestate/firstboot_test.go
overlord/hookstate/hookmgr.go
overlord/hookstate/hookstate_test.go
overlord/ifacestate/export_test.go
overlord/ifacestate/ifacemgr.go
overlord/ifacestate/ifacestate_test.go
overlord/overlord.go
overlord/overlord_test.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate_test.go
overlord/stateengine.go
overlord/stateengine_test.go
overlord/unknowntask.go

many: finish sharing a single TaskRunner with all the the managers

---

packaging/ubuntu-16.04/changelog

Merge the 2.35~pre1 changelog back into master.

release: 2.35~pre1

---

packaging/ubuntu-16.04/changelog

Merge the 2.35~pre3 changes back into master.

release: 2.35~pre3

---

tests/lib/snaps/test-snapd-juju-client-observe/bin/sh
tests/lib/snaps/test-snapd-juju-client-observe/meta/snap.yaml
tests/main/interfaces-juju-client-observe/task.yaml

tests: new test for juju client observe interface

---

interfaces/seccomp/backend.go
interfaces/seccomp/backend_test.go
interfaces/seccomp/export_test.go
interfaces/seccomp/template.go

https://github.com/snapcore/snapd/pull/5601 for 2.35

seccomp: conditionally add socketcall() based on system and base - 2.35

---

interfaces/builtin/cpu_control.go
interfaces/builtin/cpu_control_test.go
tests/lib/snaps/test-snapd-policy-app-consumer/meta/snap.yaml

https://github.com/snapcore/snapd/pull/5657 for 2.35

interfaces: add cpu-control for setting CPU tunables (2.35)

---

tests/main/parallel-install-store/task.yaml

Basic spread test for checking that parallel installs from the store work.

tests: basic test for parallel installs from the store

---

interfaces/mount/backend.go
interfaces/mount/spec.go
interfaces/mount/spec_test.go

interfaces/mount: tweak naming of things

---

interfaces/apparmor/backend.go
interfaces/apparmor/spec.go
interfaces/apparmor/spec_test.go

interfaces/apparmor: tweak naming, rename to AddLayout()

---

cmd/cmd_linux.go
overlord/snapstate/autorefresh.go

Fix things caught by Go 1.11

---

tests/lib/snaps.sh
tests/main/parallel-install-desktop/task.yaml
tests/main/parallel-install-interfaces/task.yaml
tests/main/parallel-install-sideload/task.yaml

tests: introduce a helper for installing local snaps with --name

---

boot/kernel_os.go
cmd/snap-repair/export_test.go
cmd/snap-seccomp/main.go
cmd/snap/interfaces_common.go
cmd/snap/interfaces_common_test.go
cmd/snapctl/main_test.go
daemon/api.go
daemon/api_mock_test.go
i18n/xgettext-go/main_test.go
image/image.go
interfaces/builtin/common.go
interfaces/builtin/gpio.go
overlord/configstate/configcore/watchdog.go
overlord/ifacestate/ifacestate.go
partition/bootloader.go
tests/lib/fakestore/store/store.go
userd/settings.go

I ran deadcode (remyoudompheng/go-misc/deadcode) over our codebase
and removed all the low hanging fruits.

many: remove deadcode

---

testutil/lowlevel.go
testutil/lowlevel_test.go

One of the upcoming tests needs the `fstatfs`system call result to vary over time.
I didn't go all the way (YAGNI) and made all the system call recorders behave this way
because I have a better idea on how to make unit testing of complex system call cases
easier to write.

testutil: allow Fstatfs results to vary over time

---

tests/main/proxy/task.yaml
tests/main/proxy/tinyproxy.py

This ports the proxy test away from squid to a tinyproxy (thanks to @chipaca)

tests: port proxy test to use python tinyproxy

---

spread.yaml
tests/nightly/unity/task.yaml

Fix the nightly test suite which is currently failing

tests: update prepare/restore for nightly suite

---

tests/main/interfaces-network-setup-control/task.yaml

tests: cleanup copy/paste dup in interfaces-network-setup-control

---

tests/main/parallel-install-layout/task.yaml

tests: remove unneeded cleanup from layout tests

---

cmd/Makefile.am
cmd/snap-confine/snap-confine.c
cmd/snap-update-ns/bootstrap.c
cmd/snap-update-ns/bootstrap.h
cmd/snapd-env-generator/main.c

cmd: fix C formatting

---

asserts/ifacedecls.go
daemon/api_test.go
overlord/ifacestate/helpers.go
overlord/ifacestate/ifacestate.go
overlord/ifacestate/ifacestate_test.go
overlord/managers_test.go

overlord/ifacestate: make sure to pass in the Model assertion when enforcing policies

---

get-deps.sh
mkauthors.sh
packaging/arch/PKGBUILD
run-checks
tests/lib/files.sh
tests/lib/nested.sh
tests/lib/pkgdb.sh
tests/lib/prepare-restore.sh
tests/lib/reset.sh
tests/lib/snaps/basic-iface-hooks-consumer/meta/hooks/unprepare-plug-consumer
tests/lib/snaps/snap-hooks/meta/hooks/remove
tests/main/lxd/task.yaml

make run-checks --static pass again w/shellcheck installed

---

spread.yaml

Downloading repomd.xml times out.

spread: put openSUSE to manual

---

packaging/ubuntu-16.04/changelog

release: 2.36~pre1

---

spread.yaml

This reverts commit 116beb9558c725f1159f97529e2d8199d261446a.

Revert "spread: put openSUSE to manual"

---

wrappers/export_test.go
wrappers/services.go
wrappers/services_gen_test.go

wrappers: do not depend on network.taget in socket units, tweak generated units (2.35)

---

.travis.yml
run-checks
tests/lib/cla_check.py

This reorganises our travis tests so that a number of cheaper (in
time, money, and environmental impact) tests are run before running
the full integration suite.

[RFC] use stages to run "cheaper" tests first

---

image/image.go
image/image_test.go

image: fetch device store assertion if available

---

overlord/snapstate/snapstate.go

Export getFeatureFlagBool as it's going to be used also from ifacestate (for hotplug).

overlord/snapstate: export getFeatureFlagBool.

---

cmd/snap/cmd_pack_test.go
snap/info_test.go
snap/pack/pack.go
snap/validate.go
snap/validate_test.go

Overhaul error messages from snap validation in the hope of making them more useful by adding context.

snap: overhaul validation error messages

---

tests/main/interfaces-accounts-service/task.yaml

tests/main/interfaces-accounts-service: more debugging

---

osutil/user.go
osutil/user_test.go

Small drive-by PR while looking at the osutil  user creation code.

osutil: tweak handling of error adduser errors

---

tests/main/interfaces-accounts-service/task.yaml

tests: ensure that goa-daemon is off

---

overlord/snapshotstate/backend/backend_test.go

Tar was assumed to be located at /bin/tar, but the unit tests are run using user
provided PATH which may have :/bin appearing after :/usr/bin. On systems where
/bin is a symlink to /usr/bin, this would make tar be found at /usr/bin/tar and
the test would fail.

overlord/snapshotstate/backend: detect path to tar in unit tests

---

overlord/snapstate/snapstate_test.go

Mock classic snap support so that all unit test can are run everywhere

overlord/snapstate: run tests for classic snaps even on systems that don't support classic

---

client/client.go
cmd/snapd/main_test.go

Improve degraded mode unit test by using synchronization between the calls to
mocked sanity check and the test itself. This fixes the following failure
sometimes appearing on Travis:
```
FAIL: main_test.go:57: snapdSuite.TestSanityFailGoesIntoDegradedMode
main_test.go:84:
c.Check(sanityCheckWasRun >= 1, Equals, true)
... obtained bool = false
... expected bool = true
main_test.go:85:
c.Check(err, ErrorMatches, "system does not fully support snapd: foo failed")
... error string = "cannot communicate with server: Post http://localhost/v2/changes/123: dial unix /tmp/check-7403011171824342112/0/run/snapd.socket: connect: no such file or directory"
... regex string = "system does not fully support snapd: foo failed"
main_test.go:86:
c.Check(logbuf.String(), testutil.Contains, "system does not …
```

client, cmd/daemon: allow disabling keepalive, improve degraded mode unit tests

---

strutil/strutil_test.go

Followup from https://github.com/snapcore/snapd/pull/6053/files#r228819472

strutil: add extra test to CommaSeparatedList as suggested by mborzecki

---

tests/main/find-private/task.yaml
tests/main/install-refresh-private/task.yaml
tests/main/interfaces-broadcom-asic-control/task.yaml
tests/main/interfaces-joystick/task.yaml
tests/main/interfaces-raw-usb/task.yaml

Cherry pick of https://github.com/snapcore/snapd/pull/6043 to make 2.36 tests great^Wgreen again.

tests/main: fixes for the new shellcheck

---

cmd/snap-exec/main.go
snap/info.go
snap/info_test.go
tests/regression/lp-1800004/task.yaml

Port of https://github.com/snapcore/snapd/pull/6048 for 2.36.

 cmd/snap-exec: don't fail on some try mode snaps (2.36)

---

overlord/ifacestate/export_test.go
overlord/ifacestate/helpers.go
overlord/ifacestate/helpers_test.go

Helper function for finding connState entries matching given hotplug key and interface type.

ifacestate/helpers: findConnsForHotplugKey helper

---

overlord/snapstate/snapmgr.go

correct localInstallCleanup doc comment

---

cmd/autogen.sh

cmd: update autogen.sh for opensuse

---

interfaces/hotplug/spec.go
interfaces/ifacetest/testiface.go
overlord/ifacestate/hotplug.go
snap/info.go

many: some small doc comment fixes in recent hotplug code

---

tests/lib/systemd.sh

This was a suggestion from Pawel in #6153 - I like it a lot.

tests: add SPREAD_JOB to the description of systemd_create_and_start_unit

---

interfaces/builtin/avahi_observe.go

s/deamon/daemon/
Signed-off-by: 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>

interfaces/avahi_observe: Fix typo in comment

---

snap/epoch.go
snap/epoch_test.go

Without this, `{[0,0]}` would be considered a valid epoch. This puts
an end to that.

snap: epoch lists must contain no duplicate entries

---

mkversion.sh

mkversion: use "test -n" rather than "! test -z"

---

asserts/header_checks.go
cmd/snap/cmd_advise.go
cmd/snap/cmd_help.go
cmd/snap/cmd_userd.go
cmd/snapd/main.go
daemon/api.go
interfaces/apparmor/backend.go
osutil/udev/netlink/conn.go
overlord/patch/patch3.go
overlord/snapstate/snapmgr.go
run-checks
spdx/parser.go
tests/lib/fakedevicesvc/main.go
tests/lib/fakestore/cmd/fakestore/cmd_run.go
tests/lib/systemd-escape/main.go

Trying this again (maybe the continual test failures weren't this one's fault :-) ).

Staticcheck fixes

---

tests/lib/cla_check.py

cla_check should pass for members of canonical on LP

Members of canonical LP group should pass CLA check

---

spread.yaml
tests/lib/prepare-restore.sh
tests/lib/prepare.sh
tests/lib/reset.sh
tests/main/classic-custom-device-reg/task.yaml
tests/main/classic-firstboot/task.yaml

This reverts commit 19e5a1d7889de6d8cf9c86b57edeaffcae002a15, reversing
changes made to 6f7203b4eb1b176524c4cba9e3b9e3c2706846a1.

Revert "Merge pull request #6217 from sergiocazzolato/tests-reorg-prepare-restore"

---

snap/epoch.go
snap/epoch_test.go

This lets us check whether two epochs are the same.

snap: give Epoch an Equal method

---

release-tools/repack-debian-tarball.sh

Doing the release once in blue moon, one would appreciate the release
tools hand-holding one through the process.

release-tools: display self-help

---

osutil/mountprofile_linux.go
osutil/mountprofile_linux_test.go

This is used in some upcoming branches but I wanted to propose it separately to shrink
the delta needed for review.

osutil: add helper for loading fstab from string

---

cmd/snap/cmd_snap_op.go
cmd/snap/cmd_snap_op_test.go
cmd/snap/color.go
cmd/snap/main_test.go

See https://bugs.launchpad.net/snappy/+bug/1593157

Add check for snap binaries dir not being in path

---

cmd/snapd/main_test.go

Ensure the MockSanityCheck code runs at least *twice* to
avoid a race in the TestSanityFailGoesIntoDegradedMode test:
If we close the channel and this wakes up the "select"
in the test immediately and stops this go-routine, then the
check that the logbuf contains the error will fail.
By running this at least twice we know the error made
it to the log.

snapd: fix race in TestSanityFailGoesIntoDegradedMode test

---

spread.yaml

Add cosmic to the google-sru backend

tests: update systems for google sru backend

---

cmd/snap/cmd_run_test.go

Without this change the run tests were messing about with the actual
user's home.

cmd/snap: use a fake user for 'run' tests

---

interfaces/apparmor/template.go
interfaces/builtin/camera.go
interfaces/builtin/dbus.go
interfaces/builtin/home.go
interfaces/builtin/pulseaudio.go
interfaces/builtin/system_observe.go
interfaces/seccomp/template.go

https://github.com/snapcore/snapd/pull/6419 for 2.37

miscellaneous policy updates - 2.37

---

interfaces/builtin/block_devices.go
interfaces/builtin/block_devices_test.go
interfaces/policy/basedeclaration_test.go
tests/lib/snaps/test-snapd-policy-app-consumer/meta/snap.yaml

https://github.com/snapcore/snapd/pull/6427 for 2.37

interfaces: add block-devices interface - 2.37

---

interfaces/builtin/common.go
interfaces/builtin/common_test.go
interfaces/builtin/display_control.go
interfaces/builtin/display_control_test.go
tests/lib/snaps/test-snapd-policy-app-consumer/meta/snap.yaml

interfaces: add display-control interface
References:
https://forum.snapcraft.io/t/interface-to-change-display-brightness/8890

interfaces: add display-control interface

---

tests/lib/best_golang.py
tests/lib/prepare-restore.sh

This is https://github.com/snapcore/snapd/pull/6439 for 2.37

 tests: workaround missing go dependencies in debian-9

---

snap/channel.go
snap/channel_test.go

Improve channel spec parser to catch more invalid cases. Part of #6415

snap/channel: improve channel parsing

---

polkit/authority.go

polkit: cast pid to uint32 to keep polkit happy for now

---

tests/main/auto-refresh-private/task.yaml

 tests/main/auto-refresh-private: make sure to actually download with the expired macaroon

---

interfaces/apparmor/template.go

Allow signaling ourselves, to fix master.

interfaces/apparmor: allow sending and receiving signals from ourselves

---

overlord/snapstate/aliasesv2.go
overlord/snapstate/backend.go
overlord/snapstate/backend_test.go
overlord/snapstate/booted_test.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_download_test.go
overlord/snapstate/progress.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate.go

As I was reading about the snap manager I noticed a few typos and fixed
them. Here's the patch with all of them aggregated.

overlord: fix random typos

---

tests/regression/lp-1813365/helper
tests/regression/lp-1813365/logger
tests/regression/lp-1813365/task.yaml

tests: add regression test for LP: #1813365

---

tests/regression/lp-1813365/helper

tests: add attribution to helper script

---

spread.yaml

tests: enable opensuse tumbleweed on spread

---

cmd/snap/cmd_connectivity_check.go
cmd/snap/cmd_connectivity_check_test.go
daemon/api_debug.go
daemon/api_debug_test.go

With this, all non-hidden debug commands can run unauthorized.

cmd/snap, daemon: make the connectivity check use GET

---

interfaces/builtin/greengrass_support.go
interfaces/builtin/greengrass_support_test.go

Testing this interface with the snap is quite complicated, please reach out to me over IRC/email if you would like information on how to test the interface directly with the snap.

interfaces/greengrass_support: update accesses for GGC 1.8

---

overlord/configstate/configcore/picfg.go

Updated https://github.com/snapcore/core/pull/98

Add force_turbo to the list valid pi config keys

---

overlord/hookstate/ctlcmd/get_test.go
tests/lib/snaps/snapctl-hooks/meta/hooks/configure

Small tweaks/clarification as a followup to #6322 (thanks @mvo5!).

ctlcmd/tests: tests tweaks (followup to #6322)

---

client/connections.go
cmd/snap/cmd_connections.go
cmd/snap/cmd_connections_test.go
daemon/api_connections.go
daemon/api_connections_test.go
daemon/api_json.go
overlord/ifacestate/ifacemgr.go
overlord/ifacestate/ifacestate_test.go
tests/main/snap-connections/task.yaml

cmd/snap, client, daemon, ifacestate: show a leading attribute of a connection (2.38)

---

spread.yaml

spread: refresh metadata on openSUSE

---

testutil/exec.go
testutil/exec_test.go

When shellcheck is running from a snap it will get a private /tmp. Scripts are
generated in a workdir that is places under /tmp, but inside the host mount
namespace, thus the file will not be accessible by shellcheck.
Work around that by feeding the script to be checked through stdin.

testutil: make mocked command work with shellcheck from snaps

---

tests/lib/prepare.sh
tests/main/refresh-app-awareness/task.yaml

This branch contains four patches, three of them are fixes, the last one is just a refactor
for core systems. Please see the commit messages of the patches inline for details.

tests: fixes discovered debugging refresh-app-awareness

---

run-checks
tests/main/canonical-livepatch/task.yaml
tests/main/selinux-clean/task.yaml

We see a bunch of test failures in travis right now. This PR combines the open PRs that attempt to fix things into a single PR so that we actually get a green test.

tests: fix master

---

packaging/ubuntu-16.04/changelog

Merge packaging update back into master.

packaging: release 2.39~pre1

---

cmd/snap-confine/snap-confine.apparmor.in

Signed-off-by: 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
> Have you signed the [license agreement](https://www.ubuntu.com/legal/contributors) and read the [contribution guide](https://github.com/snapcore/snapd/blob/master/CONTRIBUTING.md)?
Yes, and I suppose for comment typo fixes spread test is not a requirement...?

cmd/snap-confine/snap-confine.apparmor: Fix typo

---

cmd/snap-confine/README.nvidia

Signed-off-by: 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
> Have you signed the [license agreement](https://www.ubuntu.com/legal/contributors) and read the [contribution guide](https://github.com/snapcore/snapd/blob/master/CONTRIBUTING.md)?
Yes.

cmd/snap-confine: Fix typo in README

---

cmd/snap-update-ns/export_test.go

cmd/snap-update-ns: formatting tweaks

---

overlord/configstate/configcore/corecfg.go
overlord/configstate/configcore/snapshots.go
overlord/configstate/configcore/snapshots_test.go
overlord/snapshotstate/snapshotmgr.go
overlord/snapshotstate/snapshotstate.go
overlord/snapshotstate/snapshotstate_test.go
overlord/snapstate/snapmgr.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_test.go
tests/main/snapshot-basic/task.yaml

This is https://github.com/snapcore/snapd/pull/6669/commits for 2.39.

overlord/corecfg: make expiration of automatic snapshots configurable (4/4) - 2.39

---

osutil/buildid_test.go

The TestReadBuildGo test creates a test go binary. This breaks
in ubuntu 14.04 and ubuntu 16.04 because go wants to create a
cache dir in $HOME. But sbuild sets the $HOME to a non-exiting
directory. As a workaround, set $HOME to a tmpdir created by
the test.
This fixes a bunch of build failures in our "edge" PPA:
https://launchpad.net/~snappy-dev/+archive/ubuntu/edge/

osutil: fix TestReadBuildGo test in sbuild

---

overlord/devicestate/devicestate.go
overlord/devicestate/devicestate_test.go

This also adjusts and simplifies the tests for this.

devicestate: use deviceCtx in checkGadgetOrKernel

---

cmd/snap-update-ns/update.go
cmd/snap-update-ns/user.go

cmd/snap-update-ns: add several TODO comments

---

snap/snaptest/snaptest.go
snap/snaptest/snaptest_test.go

Add a helper for mocking an installed snap with given contents.

snaptest: add helper for mocking snap with contents

---

cmd/snap-confine/mount-support.c
tests/regression/rhbz-1584461/task.yaml

Based on comments from @jdstrand in #6874

cmd/snap-confine, tests: tweak comments, reenable symlink check in RHBZ 1584461 regression

---

packaging/fedora/snapd.spec

Go toolchain will use external linking only under specfiic conditions, such as
enabling PIE buildmode, using code that depends on CGO or an GOARCH/GOOS
unsupported by the internal linker.
Make sure that Go binaries are always using the external linker. This ensures
that external flags defined by distro policy, or package (such as -static) are
actually used.
Fixes the problem with non-statically built snapctl in #6759 on CentOS. For that particular combination, the PIE buildmode is not enabled as libc was built without -fPIC. In this case, go tool link falls back to internal linker and -extldflags (including -static) are ignored. The resulting binary is dynamically linked.
Add checks to make sure that binaries we need statically built are such.
cc @Conan-Kudo

packaging/fedora: force external linker to ensure static linking and -extldflags use

---

spread.yaml

spread.yaml: bump delta ref to 2.39.1

---

overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_test.go

During the review of #6835 the question about the order of
the checks in canRemove for the active boot snaps was raised.
This PR improves snapsate.canRemove() so that it checks early
if the revision about to be removed is currently used for the
boot. Also adds some unit tests around this.
In practise its a bit of a corner case. A kernel/base used for
booting is usually active and we disallow removing of active
revisions anyway. The window is only when snapd refreshed
base/kernel but has not rebooted yet. But then it does not
accept commands right now until the reboot happend. But even
though we should be careful in canRemove().
It also includes a tiny "extraction" of model := ... in canRemove.

devicestate: disallow removal of snaps used in booting early

---

tests/regression/lp-1805485/task.yaml

Update the description. Based on #6980

tests/regression/lp-1805485: update test description

---

cmd/snap/cmd_advise_test.go

Followup for #6734 - add unit test for `--dump-db`.

cmd/snap: add unit test for "advise-snap --dump-db".

---

packaging/opensuse-15.1
packaging/opensuse-42.1
packaging/opensuse-42.2
packaging/opensuse-42.3
spread.yaml
tests/lib/prepare.sh
tests/regression/lp-1805485/task.yaml

spread: openSUSE 15.1 (2.39)

---

tests/main/appstream-id/task.yaml

The test fails often. Try to collect some information to find out what is going
on.

tests/main/appstream-id: collect debug info

---

spread.yaml

tests: update systems to be used for during sru validation

---

tests/main/snap-seccomp-syscalls/task.yaml

Add some info to explain what the test does and give hints on what needs to be
updated when it fails.

tests/main/snap-seccomp-syscalls: add description

---

cmd/libsnap-confine-private/error.h
cmd/libsnap-confine-private/mountinfo.c
cmd/libsnap-confine-private/snap.c
cmd/libsnap-confine-private/string-utils-test.c
cmd/snap-confine/snap-confine-args.c
cmd/snap-confine/snap-confine-args.h
cmd/snap-confine/snap-confine.c
cmd/snap-confine/snap-device-helper-test.c
cmd/snap-confine/user-support.c

cmd: make fmt

---

packaging/ubuntu-16.04/changelog

Merge 2.40~pre1 changelog back into master.

packaging: release 2.40~pre1

---

gadget/export_test.go
gadget/filesystemimage.go
gadget/filesystemimage_test.go

Add a helper for creating and populating filesystem images.

gadget: filesystem image writer

---

image/image.go
recovery/device.go
recovery/recovery.go
recovery/util.go

This should bring the initamfs-tools used in uc20 in sync with the snapd code.

uc20: merge Claudios LUKS creation branch

---

vendor/vendor.json

This should fix the build failure on arm64

vendor: update to latest version of fdeutil from chris (uc20)

---

cmd/snapd/main.go

We tweaked GOMAXPROCS but after testing we found no performance gains. Hence the revert.

cmd: revert PR#6933 (tweak of GOMAXPROCS)

---

tests/main/snap-run/task.yaml

A small drive-by as I was exploring test fixes.

tests: show stderr only if it exists

---

gadget/device_darwin.go
gadget/export_test.go
gadget/update.go
gadget/update_test.go

Hook up proper updater selection.

gadget: select the right updater for given structure

---

tests/snapd-state.md

tests: reformat and fix markdown in snapd-state.md

---

tests/main/refresh-with-epoch-bump/task.yaml

tests: fix typo "current"

---

spread.yaml

tests: respect SPREAD_DEBUG_EACH on the main suite

---

tests/main/sbuild/task.yaml

tests: set sbuild test as manual

---

packaging/fedora/snapd.spec

packaging/fedora: build on RHEL8 (2.40)

---

interfaces/builtin/docker_support.go
interfaces/builtin/kubernetes_support.go

https://github.com/snapcore/snapd/pull/7292 for 2.41

interfaces: k8s worker node updates - 2.41

---

arch/arch_test.go

I added some cases increasing coverage of arch package's tests.

tests: add new cases into arch_test

---

overlord/hookstate/ctlcmd/set_test.go

A few trivial cleanups of existing snapctl tests as a byproduct of #7287 (which I thoughtlessly carried over to new tests, thanks @mvo5 for pointing those out in the review of #7287) - the test can simply reuse mockContext from the test suite.

tests: trivial snapctl test cleanup

---

cmd/snap/cmd_snap_op.go
cmd/snap/error.go
daemon/api_test.go
image/image.go
overlord/snapstate/snapstate.go
snap/channel/channel.go
snap/channel/channel_test.go
snap/seed_yaml.go
snap/snaptest/snaptest.go
store/errors.go
store/store_test.go

This will allow to use it from asserts.

many: move channel parsing to snap/channel

---

asserts/batch.go
asserts/batch_test.go
asserts/export_test.go
daemon/api_asserts.go
overlord/assertstate/assertstate.go
overlord/assertstate/assertstate_test.go
overlord/assertstate/helpers.go

many:  merging asserts.Batch Precheck with CommitTo and other clarifications

---

tests/lib/desktop-portal.sh
tests/lib/pkgdb.sh
tests/lib/prepare-restore.sh
tests/lib/prepare.sh
tests/lib/state.sh
tests/lib/store.sh

tests: remove trailing spaces from shell scripts

---

tests/main/listing/task.yaml

This test is failing during beta validation.

tests: fix system version check on listing test for external backend

---

image/image_test.go
overlord/devicestate/firstboot_test.go
seed/helpers_test.go

image,o/devicestate,seed: oops, make sure to clear seedtest helpers

---

interfaces/builtin/kubernetes_support.go

https://github.com/snapcore/snapd/pull/7458 for 2.41

interfaces/kubernetes-support: allow systemd-run to ptrace read unconfined - 2.41

---

README.md

This pull requests add the Snap Store badge to README.md to help better raise awareness of Snapcraft and snaps.

README: Add Snap Store badge to README.md

---

usersession/userd/userd.go

The problem was reported by a user in the forum[1]. When attempting to open a
URL from the snap application, it fails on the first attempt. This happens when
userd is launched as a result of DBus request.
In the `snap run --shell`, the problem is logged like this:
```
[maciek@sloop maciek]$ xdg-open http://google.com
user-open error: Object does not implement the interface
[maciek@sloop maciek]$ xdg-open http://google.com
[maciek@sloop maciek]$
```
The actual reason is a a race between DBus, which has queued the call message,
and the interface becoming exported (and thus handled) at godbus level. When
there is no handler for given call at godbus level, it returns a generic error
message which is related back to the called. The problem is also reproducible
with a dbus-send call.
1. …

usersession/userd: make sure to export DBus interfaces before requesting a name

---

tests/main/listing/task.yaml

tests: listing test, make accepted snapd/core versions consistent

---

interfaces/builtin/docker_support.go
interfaces/builtin/kubernetes_support.go

https://github.com/snapcore/snapd/pull/7512 for 2.42

interfaces/docker-support,kubernetes-support: misc updates for strict k8s - 2.42

---

seed/seedwriter/helpers.go
seed/seedwriter/seed16.go
seed/seedwriter/writer.go
seed/seedwriter/writer_test.go

Setting/resolving channels will happen in the follow-ups.

seed/seedwriter: implement WriteMeta and tree16 corresponding code

---

asserts/model.go
asserts/model_test.go
seed/seedwriter/helpers.go
seed/seedwriter/seed16.go
seed/seedwriter/writer.go
seed/seedwriter/writer_test.go

seed/seedwriter: resolve channels using channel.Resolve* for snaps

---

overlord/snapstate/backend_test.go
overlord/snapstate/handlers.go
overlord/snapstate/handlers_prereq_test.go
overlord/snapstate/snapstate.go
tests/main/base-invalid-type/task.yaml

addresses:
https://forum.snapcraft.io/t/confusing-error-message-when-base-is-not-available/12447

overlord/snapstate: have more context in the errors about prerequisites

---

seed/seedwriter/helpers.go
seed/seedwriter/seed16.go
seed/seedwriter/writer.go
seed/seedwriter/writer_test.go
snap/info.go
snap/info_test.go

This also improves doc comments.

seed/seedwriter,snap: support local snaps

---

image/export_test.go
image/helpers.go
image/helpers_test.go
image/image.go
image/image_test.go
seed/seedwriter/seed16.go
seed/seedwriter/writer.go
seed/seedwriter/writer_test.go

For this introduce Writer.BootSnaps|UnassertedSnaps|Warnings.

image,seed/seedwriter: switch image to use seedwriter.Writer

---

.gitignore

While working on something related I made some update to .gitignore.

.gitignore: pair of trivial changes

---

boot/boot.go
boot/boot_test.go
dirs/dirs.go
image/helpers.go
image/helpers_test.go
image/image.go
image/image_test.go

boot,dirs,image: various refinements in the prepare-image code switched to seedwriter

---

vendor/vendor.json

Sync Chris Coulson's latest ubuntu-core-fde-utils master
Signed-off-by: Claudio Matsuoka <claudio.matsuoka@canonical.com>

vendor: update fde-utils to latest master

---

image/image_test.go
seed/internal/doc.go
seed/internal/seed_yaml.go
seed/internal/seed_yaml_test.go
seed/seed16.go
seed/seed16_test.go
seed/seedwriter/export_test.go
seed/seedwriter/seed16.go
seed/seedwriter/writer_test.go
seed/validate.go

This moves them to a newly introduced seed/internal internal package.

image,seed: hide Seed16/Snap16, use seed.Open in image_test.go

---

cmd/snap-recovery/partition/sfdisk.go
cmd/snap-recovery/partition/sfdisk_test.go

Passing what partitions are already in use in Create() is a bit odd because sfdisk already has the partition information for the system and can work out what is missing on its own.

snap-recovery: remove "usedPartitions" from sfdisk.Create()

---

interfaces/policy/helpers.go
interfaces/policy/policy.go

Also use Alt(ernating)Constraints in the name of functions taking []*XyzConstraints

interfaces/policy: expand cstrs/cstrs1 to altConstraints/constraints

---

seed/internal/auxinfo20.go
seed/internal/helpers.go
seed/seedwriter/seed16.go
seed/seedwriter/seed20.go

seed: share auxInfo20 and makeSystemSnap via internal

---

daemon/api.go
daemon/api_download.go
daemon/api_download_test.go
daemon/api_test.go

This is the last chunk of the first step down this channels path! huzzah.

daemon: parse and reject invalid channels in snap ops

---

spread.yaml

Simple typo fix to spread.yaml

spread: fix typo in spread suite

---

overlord/snapstate/handlers_prereq_test.go

Improve TestDoPrereqRetryWhenBaseInFlight test and (hopefully) fix occasional flakiness. The test could fail very sporadically (e.g. after 2 hours when run in a loop) with the prerequsites task in "Done" state instead of expected "Doing". It's relatively easy to make this test fail fast (e.g. after just a few iterations when run in a loop by modifying the wait times inside the test loop, e.g. from 1 ms to 1s).
This was caused by delicate time dependencies in the test. The main task status-probing loop probably assumed that every Ensure+Wait execution picked exactly one task at a time, but what I found by a bit of printf-debugging in the test and in the taskrunner code was that every iteration executed both tasks - most likely because there is no blocking (as _WaitFor_) dependency between …

tests: improve TestDoPrereqRetryWhenBaseInFlight to fix occasional flakiness

---

overlord/devicestate/firstboot.go
seed/validate.go
snap/validate.go
snap/validate_test.go

simplify a bit firstboot code with less local vars.

many: make ValidateBasesAndProviders signature simpler/canonical

---

seed/seed20_test.go

seed: fix confusing pre snapd dates in tests

---

osutil/mount/mount_linux.go
osutil/mount/mount_linux_test.go

This is slightly less performant due to the loop and variables, but is more readable and less susceptible to typos and the ilk that plague repetitive code.
For clarity, the difference in performance is:
```
benchmark                                    old ns/op     new ns/op     delta
BenchmarkUnmountFlagsToOptsAllMissing-32     2.90          6.20          +113.79%
BenchmarkUnmountFlagsToOptsMixed-32          48.1          60.6          +25.99%
BenchmarkUnmountFlagsToOptsAllPresent-32     262           285           +8.78%
BenchmarkMountFlagsToOptsAllMissing-32       9.89          9.20          -6.98%
BenchmarkMountFlagsToOptsAllPresent-32       406           474           +16.75%
BenchmarkMountFlagsToOptsMixed-32            66.2          67.0          +1.21%
benchmark …
```

osutil/mount: de-duplicate code to use a list

---

cmd/snap-bootstrap/cmd_initramfs_mounts.go

Mostly trying to use consistent naming with other parts of the system, and in the UC20 case minimize the ambiguity between seed as the seed partition/directory vs a single recover system.

cmd/snap-bootstrap: some small naming and code org tweaks

---

overlord/configstate/hooks.go
overlord/snapstate/snapstate.go
overlord/snapstate/snapstate_test.go
tests/main/ubuntu-core-config-defaults-once/gadget-defaults.yaml
tests/main/ubuntu-core-config-defaults-once/manip_seed.py
tests/main/ubuntu-core-config-defaults-once/task.yaml

This is https://github.com/snapcore/snapd/pull/7796 for 2.42

 overlord/snapstate: make sure configuration defaults are applied only once (2.42)

---

seed/seed20_test.go
seed/seedwriter/writer.go
seed/seedwriter/writer_test.go

seed: fix seed location of local but asserted snaps

---

seed/seed20.go
seed/seed20_test.go

seed: support ModeSnaps(mode) for mode != "run"

---

interfaces/builtin/login_session_control.go

wlroots-library from sway needs following dbus members

intrefaces: login-session-control - added missing dbus commands

---

cmd/snap-bootstrap/cmd_initramfs_mounts.go
cmd/snap-bootstrap/cmd_initramfs_mounts_test.go

Perform similar refactor in runMode, as was done in installMode and
mount all available mount points in combined step.
I think runMode was written, in-parallel with installMode refactor landing.

bootstrap: reduce runmode mounts from 5 to 2 steps.

---

cmd/snap-preseed/main.go

Update help strings of snap-preseed command, per discussion with Samuele and Graham.

cmd/snap-preseed: update help strings
