canonical/snapd

cmd/snap-bootstrap/cmd_initramfs_mounts.go
=> cmd/snap-bootstrap: xxx todos about kernel cross-checks

overlord/snapstate/booted_test.go, overlord/snapstate/snapstate.go
The snapstate.WaitRestart code will detect rollbacks accross
reboots for base/core/kernel. This does not make much sense
in ephemeral mode where we never reboot into something that
can cause rollbacks. Therefore this commit skips the rollback
detection in non-run modes (like recover, install).
=> snapstate: do not try to detect rollback in ephemeral modes

tests/lib/prepare.sh
This commit just shuffles the code that prepares the core writable
partition in the test setup around. It will make adding UC20
preparation (which cannot modify "writable") simpler.
=> test: extract code that modifies "writable" for test prep

overlord/snapstate/backend/link_test.go
Improve backend link tests with cases for snapd snap. Extra test case for snap
unlink to make sure that the regular backend code does not break snapd.
=> overlord/snapstate: improve snapd snap backend link unit tests

cmd/snap/cmd_known.go, cmd/snap/cmd_known_test.go
This commit changes the default in `snap known --remote` to a direct
store query again. It remove the ability to query remote assertions
via snapd for now. This is to be consistent with the `snap download`
command which also goes directly to the store. For 2.44 we will
switch snap download to download via the snapd daemon.
=> snap: default to "--direct" in `snap known` for 2.43

.travis.yml
Make travis run on forked branches.
=> travis-ci: add go import path

bootloader/bootloader.go, bootloader/lk.go, snap/info.go
These are some small changes I split out from a larger WIP branch I have to hopefully make that one easier to review.
=> many: misc tweaks

overlord/standby/standby_test.go
A deadlock was observed in the tests, and a timeout was eventually hit.
Relevant backtrace:
```
=== RUN   Test
SIGQUIT: quit
PC=0x45be81 m=0 sigcode=0
...
goroutine 5 [chan receive]:
github.com/snapcore/snapd/vendor/gopkg.in/check%2ev1.(*suiteRunner).runTest(0xc4200ac200, 0xc4200a3e30, 0xc4200c4960)
/<<BUILDDIR>>/snapd-2.43+git1625.7e2fbf5~ubuntu19.04.1/_build/src/github.com/snapcore/snapd/vendor/gopkg.in/check.v1/check.go:819 +0x55
github.com/snapcore/snapd/vendor/gopkg.in/check%2ev1.(*suiteRunner).run(0xc4200ac200, 0xc420024730)
/<<BUILDDIR>>/snapd-2.43+git1625.7e2fbf5~ubuntu19.04.1/_build/src/github.com/snapcore/snapd/vendor/gopkg.in/check.v1/check.go:624 +0xf2
github.com/snapcore/snapd/vendor/gopkg.in/check%2ev1.Run(0x5e8660, 0xc420024730, 0xc420066c00, 0x0) …
```
=> overlord/standby: fix possible deadlock in standby test

tests/main/interfaces-upower-observe/task.yaml, tests/main/interfaces-upower-observe/test-snapd-upower/bin/upowerd.sh, tests/main/interfaces-upower-observe/test-snapd-upower/snapcraft.yaml
Duplicate of https://github.com/snapcore/snapd/pull/8028 but for 2.43.
=> tests: use test-snapd-upower instead of upower

.travis.yml, run-checks, tests/unit/go/task.yaml, testutil/containschecker.go
=> tests, run-checks, many: fix nakedret issues (2.43)

osutil/io.go, osutil/io_test.go
As requested by @cmatsuoka in #8045
=> osutil/tests: check there are no leftover symlinks with AtomicSymlink

dirs/dirs.go
=> dirs: fixlet for XdgRuntimeDirGlob

asserts/asserts.go, asserts/export_test.go, asserts/ifacedecls.go, asserts/ifacedecls_test.go, asserts/snap_asserts.go, asserts/snap_asserts_test.go
This introduces format 4 for snap-declaration.
=> asserts: parse plug-names/slot-names constraints 

dirs/dirs.go
=> dirs: variable with distros using alternate snap mount

tests/lib/prepare.sh
Fix the FIXME. Picked from #8069
=> tests/lib/prepare: fix hardcoded loopback device names for UC images

interfaces/builtin/utils.go
This will be needed to backport UIO interface support.
=> interfaces/builtin: backport verifySlotPathAttribute (2.43)

tests/lib/prepare.sh
Followup on #8097 
Copy the initramfs skeleton provided by the ubuntu-core-initramfs package and
modify it locally, rather than tainting the distro's directories.
=> tests/lib/prepare: use a local copy of uc20 initramfs skeleton

spread.yaml
Those images have been created manually. Those are for testing.
=> tests: add new backend which includes images with tpm support

tests/lib/desktop-portal.sh, tests/lib/user.sh
A common set of snippets that set up the user session and do things as a user.
=> test/lib/user: add helper lib for doing things for and as a user

gadget/mountedfilesystem.go, gadget/mountedfilesystem_test.go
Even though the structure edition is bumped, the actual content of filesystem
structure may be unchanged. This can only be determined once we run the
`Backup()` phase of the update sequence. Should such scenario be identified,
return an error indicating that there is no update. The callers up the stack are
already prepared to handle such scenarios and trigger no reboot.
The mechanism is already part of the 'raw' structure updater (introduced in #8040), the patch
introduces it for the filesystem updater.
=> gadget: skip update when mounted filesystem content is identical

snap/helpers.go
=> snap: use the actual staging snap-id for snapd

spread.yaml
A new image has been created with the dependencies fixed
=> tests: adding amazon linux to google backend

overlord/devicestate/firstboot.go, overlord/devicestate/firstboot20_test.go, overlord/devicestate/handlers.go
Also make a drive-by tweak to a variable declaration in firstboot.
=> o/devicestate: unset recovery_system when done seeding

tests/main/install-store/task.yaml, tests/main/local-install-w-metadata/task.yaml
=> tests: updating checks to new test account for snapd-test snaps

interfaces/builtin/u2f_devices.go, interfaces/builtin/u2f_devices_test.go
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>
=> interfaces/u2f: Add Titan USB-C key

tests/main/xdg-open/task.yaml, usersession/userd/launcher.go, usersession/userd/launcher_test.go
Fixes: https://bugs.launchpad.net/snapd/+bug/1776873
=> usersession/userd: add "apt" to the white list of URL schemes handled by xdg-open

interfaces/apparmor/template.go, interfaces/builtin/browser_support.go, interfaces/builtin/mpris.go, interfaces/builtin/system_observe.go, interfaces/seccomp/template.go
https://github.com/snapcore/snapd/pull/8232 for 2.44
=> interfaces: miscellaneous policy updates - 2.44

cmd/snap-exec/main_test.go
It was noticed that snap-exec's handling of environment is incorrect.
Under certain circumstances the environment block contains more than one
entry for the given key (environment variable). In addition, though this
is not illustrated in this patch, the internal expansion code (built
into parts of snapd) uses only one of those values when expanding
environment variables ahead of forwarding their values to snap
applications.
This patch contains only the test case showing the problem.
=> cmd/snap-exec: add test case for LP:#1860369

interfaces/builtin/docker_support.go, interfaces/builtin/kubernetes_support.go
https://github.com/snapcore/snapd/pull/8231 for 2.44
=> interfaces/{docker,kubernetes}-support: updates for lastest k8s - 2.44

.travis.yml
=> travis: disable arm64 again

spread.yaml, tests/main/lxd/task.yaml, tests/main/postrm-purge/task.yaml, tests/main/snap-session-agent-socket-activation/task.yaml, tests/regression/lp-1805838/task.yaml
https://github.com/snapcore/snapd/pull/8256 for 2.44
=> tests: backport master test fixes

interfaces/builtin/udisks2.go
https://github.com/snapcore/snapd/pull/8262 for 2.44
=> interfaces/udisks2: also allow Introspection on /org/freedesktop/UDisks2/** - 2.44

interfaces/builtin/kubernetes_support.go, interfaces/builtin/kubernetes_support_test.go
k8s.io/apiserver/pkg/storage/etcd3/logger.go pulls in go-systemd via
go.etcd.io/etcd/clientv3 and several k8s services use
apiserver/pkg/storage. go-systemd connects to the journald socket using
the 'autobind' feature of bind(). While an argument could be made to add
this support to the default policy since we generally want all snaps to
be able to log to journald, due to LP: 1867216, we cannot use the
specific 'unix (bind) type=dgram addr=none' rule and must instead use a
less specific rule that allows bind() to arbitrary SOCK_DGRAM abstract
socket names (separate send and receive rules are still required for
communicating over the socket). For now, since the rule would allow
snaps to DoS each other and the system by allowing them to bind to
well-known socket names, omit this from …
=> interfaces/kubernetes-support: allow autobind to journald socket

interfaces/builtin/kubernetes_support.go, interfaces/builtin/kubernetes_support_test.go
https://github.com/snapcore/snapd/pull/8258 for 2.44
=> interfaces/kubernetes-support: allow autobind to journald socket - 2.44

interfaces/builtin/gpio.go, interfaces/builtin/gpio_test.go
Right now the gpio interface fails with an error if a gpio device
node is missing in /sys. This leads to a not upgradable snapd.
This commit changes the code to warn only instead of failing. In
the longer run we probably want to do something smarter here but
this will unblock.
Fixes: https://bugs.launchpad.net/snapd/+bug/1866424
=> interfaces: make gpio robust against not-existing gpios in /sys

client/systems.go, client/systems_test.go, daemon/api.go, daemon/api_recovery.go, overlord/devicestate/devicemgr.go
The branch implements the data structures and stubs for querying the systems via snapd API.
This is needed for the chooser.
=> client, daemon, overlord/devicestate: structures and stubs for systems API

snap/squashfs/squashfs.go
Thanks to Zyga and Maciej for the suggestions.
=> snap: tweak comment in Install() for overlayfs detection

.travis.yml, boot/makebootable.go
=> boot: apply Go 1.10 formatting

interfaces/builtin/greengrass_support.go
This is https://github.com/snapcore/snapd/pull/8302, but for 2.44
=> interfaces/greengrass-support: fix typo

snap/info.go
=> snap: run gofmt -s

cmd/snap-failure/cmd_snapd.go, cmd/snap-failure/cmd_snapd_test.go, cmd/snap-failure/export_test.go, tests/core/snapd-failover/task.yaml, tests/lib/bin/retry-tool
This is https://github.com/snapcore/snapd/pull/8314 for 2.44
=>  cmd/snap-failure,tests: try to make snap-failure more robust (2.44)

cmd/snap-failure/cmd_snapd.go, tests/lib/bin/retry-tool
=> many: improve comments, naming, a possible TODO

boot/cmdline.go, overlord/devicestate/devicectx.go, overlord/devicestate/devicemgr.go, overlord/devicestate/devicestate_install_mode_test.go, overlord/devicestate/devicestate_serial_test.go, overlord/devicestate/devicestate_test.go, overlord/devicestate/export_test.go, overlord/devicestate/remodel.go, overlord/devicestate/remodel_test.go, overlord/snapstate/devicectx.go, overlord/snapstate/devicectx_test.go, overlord/snapstate/snapstatetest/devicectx.go
=> boot,overlord: rename operating mode to system mode 

daemon/api_systems.go, daemon/api_systems_test.go
Make the endpoint accessible to root user only.
=> daemon: make POST /v2/systems/<label> root only

daemon/api.go, daemon/api_test.go, store/details_v2.go, store/store.go, store/store_test.go
Small tweaks suggested by @mvo5 in the comments to #8270.
=> store: search v2 tweaks

store/details_v2.go, store/errors.go, store/export_test.go, store/search_v2.go, store/store.go, store/store_test.go
=> store: support for search API v2

cmd/snap/cmd_debug_state.go, cmd/snap/cmd_debug_state_test.go
This commit allows to get the seeded status via the snap debug
command. This will be used in the snapd postinst to double
check if seeding worked to avoid an expensive seed check if
it's not needed.
=> snap: add `snap debug state --is-seeded` helper

interfaces/builtin/login_session_observe.go, interfaces/builtin/modem_manager.go, interfaces/builtin/network_manager.go
Some updates detected while working on NM based on 20.04 release.
=> interfaces: updates to login-session-observe, network-manager and modem-manager interfaces

interfaces/policy/policy_test.go
=> interfaces/policy: fix comment in recent new test

systemd/systemd.go
=> systemd: move the doc comments to the interface so they are visible

interfaces/apparmor/template.go, interfaces/builtin/appstream_metadata.go, interfaces/builtin/desktop.go, interfaces/builtin/firewall_control.go, interfaces/builtin/hostname_control.go, interfaces/builtin/kubernetes_support.go, interfaces/builtin/network.go, interfaces/builtin/network_bind.go, interfaces/builtin/network_control.go, interfaces/builtin/network_observe.go
https://github.com/snapcore/snapd/pull/8443 for 2.44
=> interfaces/many: miscellaneous policy updates xliv - 2.44

data/systemd/snapd.apparmor.service.in, packaging/ubuntu-16.04/rules, packaging/ubuntu-16.04/snapd.install, wrappers/services.go, wrappers/services_gen_test.go
=> many: fix loading apparmor profiles on Ubuntu 20.04 with ZFS (2.44)

bootloader/bootloader.go, bootloader/grub.go, bootloader/lkenv/lkenv.go, bootloader/uboot.go, cmd/snap-bootstrap/bootstrap/bootstrap.go, cmd/snap-bootstrap/partition/sfdisk.go, gadget/gadget.go
These are miscellaneous things from my hacks I worked on to get rpi4 support working...
=> bootloader, gadget, cmd/snap-bootstrap: misc cosmetic things

run-checks
=> run-checks: use consistent "Checking ..." style messages

httputil/retry_test.go
The detection of timeout coupled with context.DeadlineExceeded errors in
http.Client.do() is racy, and boils down to `time.Now().After(deadline)` where
deadline is based on the timeout setting of the client.
This has been partially fixed in 1.14 in
https://github.com/golang/go/commit/7fc2625ef16c9e271ca3016f761157ec082cc45a but
feels more reliable if returned via err when reading the response body.
Make the tests expect either the proper `Client.Timeout exceeded while awaiting
headers` or context deadline exceeded error.
=> httputil: fix client timeout retry tests

boot/bootstate20.go
Re-opening of https://github.com/snapcore/snapd/pull/8509 that hopefully is not contentious this time /me ducks
Don't track the status to commit in the bootloaderKernelState20 implementations, instead always use DefaultStatus for the markSuccessful implementation, and pass in the desired status in the setNextKernel implementation. This will reduce duplication in different bootloaderKernelState20 implementations.
The name markSuccessful on bootloaderKernelState20 kept confusing me with markSuccessful on bootstate, so making these separate is useful while coding if nothing else, but I will concede the full name is now repetitive.
Also move the big comment to where it's applicable, it won't be applicable in the new implementation of bootloaderKernelState20 I'll be adding soon for u-boot and …
=> boot/bootstate20: small changes to bootloaderKernelState20

interfaces/builtin/openvswitch.go, interfaces/builtin/openvswitch_test.go
=> interfaces/openvswitch: support use of ovs-appctl

cmd/snap/cmd_download.go, image/helpers.go, image/helpers_test.go, image/image.go, image/image_test.go, seed/seedwriter/seed16.go, seed/seedwriter/writer.go, seed/seedwriter/writer_test.go
=> image,seed/seedwriter: support redirect channel aka default tracks

image/helpers.go
=> image: improve/adjust DownloadSnap doc comment

cmd/snap-bootstrap/cmd_initramfs_mounts.go, cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
Some cleanups after #8513 landed.
=> cmd/snap-bootstrap: cleanups, naming tweaks

boot/initramfs20dirs.go, cmd/snap-bootstrap/cmd_initramfs_mounts.go, cmd/snap-bootstrap/cmd_initramfs_mounts_test.go, cmd/snap-bootstrap/export_test.go, cmd/snap-bootstrap/initramfs_mounts_state.go, dirs/dirs.go, overlord/devicestate/devicestate_install_mode_test.go, overlord/devicestate/handlers_install.go, tests/lib/nested.sh, vendor/vendor.json
=>  many: put the sealed keys in a directory on seed for tidiness

tests/lib/bin/session-tool, tests/main/user-session-env/task.yaml
This bundles and uses the rather trivial https://github.com/snapcore/snapd/pull/8587
=> tests: port user-session-env to session-tool

cmd/snap-bootstrap/bootstrap/bootstrap.go, cmd/snap-bootstrap/bootstrap/options.go, cmd/snap-bootstrap/cmd_initramfs_mounts.go, cmd/snap-bootstrap/cmd_initramfs_mounts_test.go, overlord/devicestate/devicestate_install_mode_test.go, overlord/devicestate/handlers_install.go
backport PR of #8619 to release/2.45.
=> o/devicestate,cmd/snap-bootstrap: seal to recover mode cmdline, unlock in recover mode initramfs

cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
=> c/snap-bootstrap: port mount state mocking to the new style on master (2.45)

usersession/agent/session_agent.go, wrappers/services_test.go
=> usersession/agent,wrappers: fix races between Shutdown and Serve

tests/lib/nested.sh
=> tests: new directory used to store the cloud images on gce

tests/lib/pkgdb.sh, tests/main/session-tool-support/task.yaml
Please check the two commit messages for details.
=> tests: test adjustments and fixes for recently published images

spread.yaml, tests/lib/pkgdb.sh
This is to make tests pass in next update of bionic
=> tests: add dbus-user-session to bionic and reorder package names

tests/lib/boot.sh
This is https://github.com/snapcore/snapd/pull/8611 for 2.45
=>  tests: not fail when boot dir cannot be determined (2.45)

vendor/vendor.json
This update contains a fix/workaround for broken TPMs on the NUC.
=> vendor: update to latest secboot

asserts/export_test.go, asserts/internal/grouping.go, asserts/internal/grouping_test.go, asserts/pool.go
This is the follow-up to https://github.com/snapcore/snapd/pull/8563#discussion_r422007231
=> asserts: make clearer that with label we mean a serialized label

tests/main/interfaces-location-control/task.yaml
The usual story, less magic hacks, less leaking processes, more reliable
tests. You know you love it. Just merge it!
=> tests: port interfaces-location-control to session-tool

spread.yaml, tests/lib/nested.sh
This is a change to make the nested tests pass in the different systems
supported.
=> tests: fix nested tests 

overlord/devicestate/systems.go
=> o/devicestate: typo fix

boot/makebootable.go, boot/makebootable_test.go, overlord/devicestate/firstboot20_test.go, overlord/snapstate/backend/setup.go, snap/container.go, snap/snapdir/snapdir.go, snap/snapdir/snapdir_test.go, snap/snapfile/snapfile_test.go, snap/squashfs/squashfs.go, snap/squashfs/squashfs_test.go, tests/core/basic20/task.yaml, tests/core/seed-base-symlinks/task.yaml
This is https://github.com/snapcore/snapd/pull/8711 for 2.45
=> snap/squashfs: also symlink snap Install with uc20 seed snap dir layout (2.45)

spread.yaml
Best enjoyed with "Hide whitespace changes" :smile: 
This was applied via the yaml-language-server from https://github.com/redhat-developer/yaml-language-server (used by the vscode-yaml VS code plugin).
=> spread.yaml: apply yaml formatter/linter

tests/lib/bin/session-tool, tests/lib/snaps/test-snapd-desktop/bin/sh, tests/lib/snaps/test-snapd-desktop/meta/snap.yaml, tests/main/mount-ns/google.ubuntu-18.04-64/HOST.expected.txt, tests/main/mount-ns/google.ubuntu-18.04-64/PER-SNAP-16.expected.txt, tests/main/mount-ns/google.ubuntu-18.04-64/PER-SNAP-18.expected.txt, tests/main/mount-ns/google.ubuntu-18.04-64/PER-SNAP-C7.expected.txt, tests/main/mount-ns/google.ubuntu-18.04-64/PER-USER-16.expected.txt, tests/main/mount-ns/google.ubuntu-18.04-64/PER-USER-18.expected.txt, tests/main/mount-ns/google.ubuntu-18.04-64/PER-USER-C7.expected.txt, tests/main/mount-ns/task.yaml, tests/main/selinux-clean/task.yaml
This cherry picks a bunch of commits from master with test fixes. This should make 2.45 greener.
=> tests: cherry-pick test fixes from master (2.45)

interfaces/builtin/fwupd.go, interfaces/builtin/fwupd_test.go
To enable fwupd client connecting to fwupd on core18 or later, we have to incoporate bind mount for /boot from host system, and rbind is used to make sure /boot/efi and /boot/grub can be writable to be accessible for fwupd.
Although this commit can work with uefi-fw-tools running and updating bios on UC18, I'm sure there are still something should be addressed and improved due to lack of background behind snapd, and please help to review commit for making it better. Very appreciated!
=> interfaces/fwupd: allow bind mount to /boot on core

bootloader/ubootenv/env.go, bootloader/ubootenv/env_test.go
=> bootloader/ubootenv: don't panic with an empty uboot env

osutil/chattr_64.go, osutil/sys/sysnum_32_linux.go
=> osutil: enable riscv64 build

interfaces/apparmor/template.go, interfaces/builtin/account_control.go, interfaces/builtin/audio_playback.go, interfaces/builtin/desktop.go, interfaces/builtin/fwupd_test.go, interfaces/builtin/gsettings.go, interfaces/builtin/kernel_module_control.go, interfaces/builtin/network.go, interfaces/builtin/network_bind.go, interfaces/builtin/pulseaudio.go, interfaces/builtin/unity7.go, interfaces/builtin/utils.go, usersession/userd/launcher.go
https://github.com/snapcore/snapd/pull/8792 for 2.45.
=> interfaces: miscellanious policy updates xlv - 2.45

arch/arch.go, arch/arch_test.go
Also sort arches alphabetically, and drop duplicate ppc64 test.
=> arch: add riscv64

tests/lib/prepare.sh
Thanks to @zyga for the recommendation.
As requested in https://github.com/snapcore/snapd/pull/8857#discussion_r440793503
=> tests/lib/prepare.sh: adjust comment about sgdisk

asserts/asserts.go, asserts/asserts_test.go, asserts/header_checks.go, asserts/snap_asserts.go, asserts/validation_set.go, asserts/validation_set_test.go
See the doc comment for asserts.ValidationSet.
=> asserts: introduce new assertion validation-set

osutil/disks/disks.go
We can eliminate the found var if we use d == nil and only assign to d when found.
We can also eliminate some of the nesting in the function to make it easier to follow the logic.
Thanks to @mvo5 for the patches!
As requested in https://github.com/snapcore/snapd/pull/8675#pullrequestreview-432994891
=> osutil/disks: refactor diskFromMountPointImpl a bit

gadget/mountedfilesystem.go, gadget/mountedfilesystem_test.go, gadget/update_test.go
The mounted filesystem update would perform a mount lookup for each of
Update/Backup/Rollback operations. This is excessive, we can limit the lookup to
happen just once. This also makes further handling of boot assets update easier
to integrate.
=> gadget: do only one mount point lookup in mounted fs updater

gadget/mountedfilesystem.go
=> gadget: fix typo in mounted filesystem updater

tests/lib/nested.sh, tests/lib/snaps.sh
Some tweaks/helpers to make the nested tests more flexible.
=> tests: improve nested tests flexibility

asserts/database.go, asserts/findwildcard.go, asserts/fsbackstore.go, asserts/header_checks.go, asserts/membackstore.go
=> asserts: small improvements and corrections for sequence-forming assertions' support

bootloader/bootloadertest/bootloadertest.go
=> bootloader/bootloadertest: fix comment typo

tests/main/xdg-open/task.yaml, usersession/userd/launcher.go
This is a split out from https://github.com/snapcore/snapd/pull/9013 which is a bit big as it is.
=> usersession/userd: do not modify XDG_DATA_DIRS when calling xdg-open

interfaces/apparmor/export_test.go, interfaces/apparmor/spec.go, interfaces/apparmor/spec_test.go, interfaces/builtin/i2c.go, interfaces/builtin/i2c_test.go, interfaces/builtin/iio.go, interfaces/builtin/iio_test.go, interfaces/builtin/spi.go, interfaces/builtin/spi_test.go
=> interfaces: optimize rules of multiple connected iio/i2c/spi plugs (2.45)

cmd/snap-preseed/main.go, cmd/snap-preseed/main_test.go, cmd/snap-preseed/reset.go, tests/main/preseed-reset/task.yaml
Cherry pick fixes from #9015 and #9018
=> cmd/snap-preseed: backport fixes (2.45)

tests/lib/nested.sh
=> tests: avoid exit when nested type var is not defined  (2.45)

sysconfig/cloudinit_test.go
These tests have been renamed to make more clear what use-cases in the real
codebase they are testing, i.e. disabling cloud-init for the ephemeral system
in install or run mode, or disabling/configuring cloud-init for the run mode
system while running in install mode.
This came about during review of a manual back-porting of patches from https://github.com/snapcore/snapd/pull/8533/files#diff-783da8f78a2576a41ab7cb0ca2c25e55 to release/2.45 at https://github.com/snapcore/snapd/pull/9052
=> sysconfig/cloudinit_test.go: add test for initramfs case, rm "/" from path

packaging/ubuntu-16.04/changelog
=> packaging: add placeholder changelog for 2.45.3.1

daemon/api_debug_seeding.go, daemon/api_debug_seeding_test.go
This, in conjunction with the associated change to `snap debug seeding` client will help in determining when to output "-" for a time / duration that can't be calculated because the start time is 0 and the end time is an actual time for example, where now we output unexpected things like seeding taking 292 years, instead we could just output `seed-completion: -`
=> daemon/api: use pointers to time.Time for debug seeding aspect

interfaces/system_key_test.go
add debugging as well for when it fails
=> interfaces: make the unmarshal test match more the comment

cmd/snap/cmd_help.go, cmd/snap/cmd_recovery.go, cmd/snap/cmd_recovery_test.go, tests/core/basic20/task.yaml
The new "snap recovery" command lists the available recovery
systems.
=> cmd: add new "snap recovery" command

packaging/ubuntu-16.04/changelog
Merge changelog back into master.
=> debian: release 2.46~pre2

sandbox/cgroup/cgroup.go, sandbox/cgroup/cgroup_test.go
Mounting cgroup2, even for a moment, is sticky. Consider this shell
program, running on 4.15 kernel and Ubuntu 16.04 user-space, which does
not mount this hierarchy by default:
cat /proc/self/cgroup | grep -F '0::' # no matches
mkdir /tmp/cg2
mount -t cgroup2 cgroup2 /tmp/cg2
umount /tmp/cg2
rmdir /tmp/cg2
cat /proc/self/cgroup | grep -F '0::' # does match
After mounting cgroup2 all processes gain additional entry for it, as
seen in /proc/PID/cgroup. Even after unmounting the file-system the
entry persists. This is expected behavior, all controllers remain in use
until the system is rebooted. User-space is expected to cross-verify if
the controller is mounted before using it.
This can happen when systemd mounts a cgroupv2 inside a container, such
as the act of booting Ubuntu 18.04 on a …
=> sandbox/cgroup: detect dangling v2 cgroup

interfaces/builtin/docker_support.go, interfaces/builtin/kubernetes_support.go
https://github.com/snapcore/snapd/pull/9139 for 2.46.
=> interfaces/many: miscellaneous updates for strict microk8s - 2.46

cmd/snap-bootstrap/cmd_initramfs_mounts.go, cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
Followup to #9010 and some suggestions there as well as making some of the things we want to do more explicit with TODOs here.
=> cmd/snap-bootstrap/initramfs-mounts: tweak names, add comments from previous PR

interfaces/builtin/kernel_crypto_api.go, interfaces/builtin/kernel_crypto_api_test.go, tests/lib/snaps/test-snapd-policy-app-consumer/meta/snap.yaml
https://github.com/snapcore/snapd/pull/9120 for 2.46.
=> interfaces: add kernel-crypto-api interface - 2.46

kernel/kernel_test.go, kernel/validate.go, kernel/validate_test.go, snap/pack/pack.go
This commit adds validation of the kernel.yaml and if the assets
are actually available.
Build on top of https://github.com/snapcore/snapd/pull/9150
=> kernel: add kernel.Validate()

boot/bootstate20.go, osutil/doc.go, osutil/sizer.go
=> osutil: add a package doc comment (via doc.go)

mkversion.sh
We want dirty to show up in the version number if the tree is in fact dirty when
we build. Currently, if the version is dirty on a tag, we would get something
like 2.46-dirty as version_from_git, which will not be the same as 2.46 from the
changelog, and then we produce a silly version number like:
2.46+git2.46.2.46
but with this we now produce:
2.46-dirty
And for commits that are not directly on a tag, and are dirty, we get
2.46+git83.g1671726-dirty
which also produces the desired effect of including dirty in the version.
=> mkversion.sh: simple hack to include dirty in version if the tree is dirty

secboot/secboot_tpm.go, secboot/secboot_tpm_test.go
If a load sequence includes a snap file, assume it's the kernel snap
and create a SnapFileEFIImage load event that reads kernel.efi from
the squashfs instead of a regular FileEFIImage load event.
Signed-off-by: Claudio Matsuoka <claudio.matsuoka@canonical.com>
=> secboot: read kernel efi image from snap file

overlord/devicestate/devicemgr.go, overlord/devicestate/devicestate_cloudinit_test.go, sysconfig/cloudinit.go, sysconfig/cloudinit_test.go
Cleanups from reviews on:
- https://github.com/snapcore/snapd/pull/9023
- https://github.com/snapcore/snapd/pull/9024
- https://github.com/snapcore/snapd/pull/9025
See individual commit messages for all details.
=> many: cloud-init cleanups from previous PR's

overlord/hookstate/ctlcmd/services_test.go, overlord/managers_test.go, overlord/snapstate/backend_test.go, overlord/snapstate/export_test.go, overlord/snapstate/snapstate.go, overlord/snapstate/snapstate_install_test.go, overlord/snapstate/snapstate_test.go, overlord/snapstate/snapstate_update_test.go, tests/go.mod
Use disk space check introduced with InstallMany.
=> o/snapstate: disk space check with InstallMany

boot/assets_test.go
Little tweaks to the unit tests.
=> boot: add unit test helpers

boot/cmdline.go, boot/kernel_os_test.go, boot/makebootable.go, bootloader/bootloader_test.go, bootloader/grub.go, bootloader/grub_test.go
=> boot,bootloader: clarifications after the changes to introduce bootloader.Options.Role

seed/seedwriter/writer_test.go
this is expected to work but was not covered by tests so far
=> seed/seedwriter: test local asserted snaps with UC20 grade signed

bootloader/bootloader.go
=> bootloader: tweak doc comments (thanks Samuele)

overlord/devicestate/devicestate_cloudinit_test.go
We renamed the "mockLogger" (which is really just a buffer) in
the devicestate_systems_test.go (commit fc6a314). However this
name is also used in devicestate_cloudinit_test.go. This commit
updates the name here too.
=> devicestate: rename "mockLogger" to "logbuf"

boot/bootchain.go, boot/bootchain_test.go, boot/export_test.go
Some prerequisites for resealing work.
=> boot: tweak boot chains to support a list of kernel command lines, keep track of model and kernel boot file

overlord/snapstate/export_test.go, overlord/snapstate/snapstate.go, overlord/snapstate/snapstate_update_test.go
Disk space check when refreshing multiple snaps.
=> o/snapstate: disk space check on UpdateMany

spread.yaml, tests/lib/nested.sh, tests/lib/prepare.sh
A bunch of patches that improve the logging in UC20 nested tests
=> test: improve logging in nested tests

tests/lib/nested.sh, tests/nested/core20/gadget-reseal/manip_gadget.py, tests/nested/core20/gadget-reseal/task.yaml
This adds a gadget reseal spread test on top of #9331
=> tests: add nested core20 gadget reseal test

boot/bootstate20.go, boot/seal.go
this is based on feedback on #9355
=> boot: adjust comments, naming, log success around reseal

tests/lib/cla_check.py
Use Python 3 by default. Apply little tweaks. Reformat with black.
=> tests/lib/cla_check: default to Python 3, tweaks, formatting

packaging/ubuntu-16.04/changelog
Merge the 2.47~pre1 beta changelog back into master.
=> release: 2.47~pre1

overlord/snapshotstate/backend/backend.go
Small tweak to the just landed #9371
=> o/snapshotstate: tweak comment regarding snapshot filename

tests/lib/nested.sh, tests/nested/classic/hotplug/task.yaml, tests/nested/core/hotplug/task.yaml
=> tests/nested: misc robustness fixes

tests/lib/prepare-restore.sh, tests/lib/snaps.sh
Couple of cleanups for the test suite.
=> tests/lib: move to new directory when restoring PWD, cleanup unpacked unpacked snap directories

tests/core/enable-disable-units-gpio/task.yaml, tests/core/iio/task.yaml, tests/core/reboot/task.yaml, tests/regression/lp-1595444/task.yaml, tests/regression/lp-1597839/task.yaml, tests/regression/lp-1597842/task.yaml, tests/regression/lp-1606277/task.yaml, tests/regression/lp-1607796/task.yaml, tests/regression/lp-1615113/task.yaml, tests/regression/lp-1618683/task.yaml, tests/regression/lp-1630479/task.yaml, tests/regression/lp-1644439/task.yaml, tests/regression/lp-1665004/task.yaml, tests/regression/lp-1704860/task.yaml, tests/regression/lp-1732555/task.yaml, tests/regression/lp-1797556/task.yaml, tests/regression/lp-1802581/task.yaml, tests/regression/lp-1803535/task.yaml, tests/regression/lp-1803542/task.yaml, tests/regression/lp-1805838/task.yaml, tests/regression/lp-1813963/task.yaml, tests/regression/lp-1815722/task.yaml, tests/regression/lp-1884849/task.yaml, tests/regression/lp-1886786/task.yaml
=> tests: move core and regression suites to snaps-state tool

client/snapshot.go, client/snapshot_test.go, cmd/snap/cmd_snapshot.go, cmd/snap/cmd_snapshot_test.go, daemon/api.go, daemon/api_snapshots.go, daemon/api_snapshots_test.go, daemon/export_api_snapshots_test.go, daemon/response.go, overlord/snapshotstate/snapshotstate.go
This is split out from https://github.com/snapcore/snapd/pull/9036 for easier review.
Credit for a lot of this code goes to James Jesudason (slimjim777)
=> many: scaffolding for snapshots import API 

cmd/snap-bootstrap/cmd_initramfs_mounts.go
As requested by @pedronis a long time ago...
See https://github.com/snapcore/snapd/pull/9049#discussion_r459559671
=> cmd/snap-bootstrap/initramfs-mounts: split off new helper for misc recover files

tests/main/snap-run-hook/task.yaml, tests/main/snap-run-symlink/task.yaml, tests/main/snap-run-userdata-current/task.yaml, tests/main/snap-run/task.yaml, tests/main/snap-service/task.yaml, tests/main/snap-services/task.yaml, tests/main/snap-set/task.yaml, tests/main/snap-unset/task.yaml, tests/main/snap-update-ns/task.yaml, tests/main/snap-user-service-restart-on-upgrade/task.yaml, tests/main/snap-user-service-socket-activation/task.yaml, tests/main/snap-user-service-start-on-install/task.yaml, tests/main/snap-user-service-upgrade-failure/task.yaml, tests/main/snap-user-service/task.yaml, tests/main/snap-userd-desktop-app-autostart/task.yaml, tests/main/snap-wait/task.yaml, tests/main/snapctl-from-snap/task.yaml, tests/main/special-home-can-run-classic-snaps/task.yaml, tests/main/stale-base-snap/task.yaml, tests/main/system-usernames/task.yaml, tests/main/systemd-service/task.yaml, tests/main/umask/task.yaml, tests/main/user-mounts/task.yaml, tests/main/xdg-open-compat/task.yaml, tests/main/xdg-open-portal/task.yaml, tests/main/xdg-open/task.yaml, tests/main/xdg-settings/task.yaml
Last part of the snaps-state tool migration
=> tests: migration of the main suite to snaps-state tool part 6

spread-shellcheck
Thanks to James for spotting my earlier mistake
=> spread-shellcheck: correctly attribute suite errors

overlord/snapstate/autorefresh.go, overlord/snapstate/autorefresh_test.go
This was pre-agreed with Samuele and Michael
=> overlord: increase refresh postpone limit to 14 days

tests/nightly/sbuild/task.yaml
Adding verbose and debug flags to sbuild
With this is easier to understand any sbuild error
Errors detected by adding those flags: https://paste.ubuntu.com/p/XBfFXKxXQF/
=> tests: more output for sbuild test

interfaces/builtin/ptp.go, interfaces/builtin/ptp_test.go, tests/lib/snaps/test-snapd-policy-app-consumer/meta/snap.yaml
The Precision Time Protocol interface allows the clock to be synced to sub-100 nanoseconds.
https://github.com/torvalds/linux/blob/master/Documentation/ABI/testing/sysfs-ptp
=> interfaces: PTP hardware clock interface

tests/lib/core-config.sh, tests/lib/nested.sh, tests/lib/prepare-restore.sh, tests/lib/prepare.sh, tests/lib/reset.sh, tests/lib/state.sh, tests/lib/tools/os.query
Part 1 of the systems.sh helper to os.query tool migration
=> tests: moving the lib section from systems.sh helper to os.query tool

cmd/snap/cmd_snapshot_test.go
Hardcoding the exact value will make the test fail in October and March when the
DST change occurs.
=> cmd/snap: do not hardcode snapshot age value

overlord/snapstate/autorefresh.go
There's no change in the logic, just in the flow and code comments.
=> overlord/snapstate: refactor ihibitRefresh

osutil/disks/mockdisk.go, osutil/disks/mockdisk_test.go
We should panic if we are passed a mapping that has the same mountpoint with
different options show up twice, as this is an inconsistent world-view, as one
mountpoint can only have one option set on it. The reason we have this option as
the input and not as a property of the disk itself is so that we can verify the
input, as whether or not to expect a decrypted device is a thing we need to
test, but it does have the unfortunate side effect where you can create
situations like this.
This would make the unit test proposed in #9528 panic
=> osutil/disks/mockdisk: panic if same mountpoint shows up again with diff opts

cmd/snap-bootstrap/cmd_initramfs_mounts.go, cmd/snap-bootstrap/cmd_initramfs_mounts_nosecboot.go, cmd/snap-bootstrap/cmd_initramfs_mounts_secboot.go, cmd/snap-bootstrap/export_test.go, secboot/encrypt_tpm.go, secboot/encrypt_tpm_test.go, secboot/export_test.go, secboot/secboot_tpm.go, secboot/secboot_tpm_test.go, vendor/vendor.json
A couple of patches split out from #9528
=> secboot: version bump, unlock volume with key

secboot/secboot_tpm.go
=> secboot: fix doc comment on helper for unlocking volume with key

spread.yaml
We need this for next sru validation
=> tests: update google sru backend to support groovy

tests/nested/core20/save/task.yaml
Add a test for checking that ubuntu-save is present and set up correctly.
=> tests/nested/core20/save: a test that verifies ubuntu-save is present and set up

overlord/devicestate/devicestate_test.go
Some tweaks suggested in #9565
=> o/devicestate: unit test tweaks

gadget/device_darwin.go, gadget/device_linux.go, gadget/device_test.go, gadget/export_test.go, gadget/gadget.go, gadget/gadget_test.go, gadget/install/content.go, gadget/install/content_test.go, gadget/install/install_test.go, gadget/internal/mkfs.go, gadget/layout.go, gadget/layout_test.go, gadget/ondisk.go, gadget/ondisk_test.go, gadget/quantity/size.go, gadget/quantity/size_test.go, gadget/raw.go, gadget/raw_test.go, gadget/update.go, gadget/update_test.go, overlord/devicestate/devicestate_remodel_test.go
An idea about capturing gadget related quantities into a single package not fearing circular imports.
=> gadget/quantity: introduce a new package that captures quantities 

gadget/quantity/size_test.go
Suggested in https://github.com/snapcore/snapd/pull/9582#discussion_r515703681
=> gadget/quantity: tweak test name

cmd/autogen.sh, dirs/dirs.go
Signed-off-by: Zac Medico <zmedico@gmail.com>
Hello! This is my first contribution, and I've signed the [contributor agreement](http://www.ubuntu.com/legal/contributors) just now.
=> dirs: add "gentoo" to altDirDistros

spread.yaml, tests/nested/manual/cloud-init-never-used-not-vuln/task.yaml, tests/nested/manual/cloud-init-nocloud-not-vuln/task.yaml, tests/nested/manual/core-early-config/task.yaml, tests/nested/manual/core20-early-config/task.yaml, tests/nested/manual/grade-signed-above-testkeys-boot/task.yaml, tests/nested/manual/grade-signed-cloud-init-testkeys/task.yaml, tests/nested/manual/minimal-smoke/task.yaml, tests/nested/manual/preseed/task.yaml, tests/nested/manual/refresh-revert-fundamentals/task.yaml, tests/nested/manual/snapd-refresh-from-old/task.yaml
This is the first step, then new commands will be migrated as well.
=> tests: using the nested-state tool in nested tests

boot/initramfs20dirs.go, boot/seal.go, boot/seal_test.go, cmd/snap-bootstrap/cmd_initramfs_mounts.go, cmd/snap-bootstrap/cmd_initramfs_mounts_test.go, cmd/snap-bootstrap/initramfs_mounts_state.go, gadget/install/install.go, overlord/devicestate/devicestate_install_mode_test.go, overlord/devicestate/handlers_install.go, secboot/secboot_tpm.go, secboot/secboot_tpm_test.go, tests/core/basic20/task.yaml, tests/nested/core20/gadget-reseal/task.yaml, tests/nested/core20/kernel-reseal/task.yaml
* Move sealed-key for ubuntu-data to ubuntu-boot
* Move model file to devicedir
* Rename keyring prefix
=> many: mv keys to ubuntu-boot, move model file, rename keyring prefix for secboot

gadget/gadget.go, gadget/validate.go, gadget/validate_test.go, overlord/devicestate/devicestate_gadget_test.go, overlord/devicestate/devicestate_install_mode_test.go, overlord/devicestate/handlers_install.go, snap/pack/pack.go
Run a gadget validation pass before we attempt install.
=> gadget, overlord/devicestate: validate that system supports encrypted data before install

overlord/devicestate/firstboot_preseed_test.go
Followup to #9607  with small test tweaks suggested by @anonymouse64
=> tests: minor test tweaks suggested in the review of 9607

cmd/snap-bootstrap/cmd_initramfs_mounts.go, packaging/ubuntu-16.04/changelog, secboot/secboot_tpm_test.go, tests/lib/nested.sh, tests/nested/core20/degraded/task.yaml
Version of https://github.com/snapcore/snapd/pull/9637 for the release/2.48 branch.
=>  cmd/snap-bootstrap, secboot, tests: misc cleanups, add spread test (2.48)

boot/makebootable.go, boot/makebootable_test.go, bootloader/androidboot.go, bootloader/bootloader.go, bootloader/bootloadertest/bootloadertest.go, bootloader/grub.go, bootloader/lk.go, bootloader/uboot.go, image/image_test.go
This is https://github.com/snapcore/snapd/pull/9643 for 2.48.
This is needed so that we can cherry-pick #9654
=> bootloader: use ForGadget when installing boot config (2.48)

daemon/api_base_test.go, daemon/api_general_test.go, daemon/api_users_test.go
we can use the Method from Request to know what to try
=> daemon: simplify test helpers Get|PostReq into Req

cmd/snap-repair/runner.go, store/store.go
=> cmd/snap-repair,store: increase initial retry time intervals, stalling TODOs

boot/makebootable.go, boot/makebootable_test.go, boot/seal.go, boot/seal_test.go, tests/nested/core20/tpm/task.yaml
Populate modeenv with kernel command line during installation.
=> boot: set kernel command line in modeenv during install 

seed/seed.go, seed/seedwriter/seed16.go, seed/seedwriter/seed20.go, seed/seedwriter/writer.go
solve also a XXX now that we know we won't write/need options.yaml for grade != dangerous.
=> seed: cleanup/drop some no longer valid TODOS, clarify some other points

tests/lib/tools/os.query, tests/main/os.query/task.yaml
Now the tool allows querying for other OSs
The help has been reorganized
The test is updated
=> tests: New queries for the os tools

overlord/hookstate/context.go, overlord/hookstate/hookmgr.go
This implements the feedback/ideas from https://github.com/snapcore/snapd/pull/9715#discussion_r533210795
=> hookstate: refactor around EphemeralRunHook

bootloader/bootloader.go, bootloader/bootloader_test.go
As requested by @pedronis in https://github.com/snapcore/snapd/pull/9695
=> bootloader: add check for prepare-image time and more tests validating options

gadget/export_test.go, gadget/gadget_test.go, gadget/install/export_test.go, gadget/install/partition.go, gadget/install/partition_test.go, gadget/ondisk.go, gadget/ondisk_test.go
it has no other users atm. this was discussed already a while ago.
=> gadget: move BuildPartitionList to install and make it unexported

cmd/snap/cmd_help_test.go
Skip --help output tests for older versions of
go-flags. Notably v1.4.0 from debian-sid will fail because
the formating is slightly different. Note that the check here
is not precise i.e. this is not the commit that added the change
that changed the help output but this change is easy to test for
with reflect and in practice this is fine.
Fwiw, I ran:
```
$ spread -debug   -v google:debian-sid-64:tests/nightly/sbuild
...
2021-01-04 16:11:35 Restoring google:debian-sid-64:tests/nightly/sbuild:normal (jan041449-154313)...
2021-01-04 16:11:38 Restoring google:debian-sid-64:tests/nightly/ (jan041449-154313)...
2021-01-04 16:11:59 Restoring google:debian-sid-64 (jan041449-154313)...
2021-01-04 16:12:00 Discarding google:debian-sid-64 (jan041449-154313)...
2021-01-04 16:12:18 Restoring …
```
=> snap: skip help output tests for go-flags v1.4.0

tests/lib/tools/cleanup-state, tests/lib/tools/fs-state, tests/lib/tools/journal-state, tests/lib/tools/lxd-state, tests/lib/tools/snapd.tool, tests/lib/tools/tests.cleanup, tests/lib/tools/tests.invariant, tests/lib/tools/tests.session, tests/lib/tools/to-one-line
This is the first part of the normalization done for test tools.
The idea is to keep as similar as possible all the test tools regarding implementation and usage.
=> tests: normalize test tools - part 1

gadget/gadget.go
Thanks to @bboozzoo for spotting this too
=> gadget/gadget.go: rename ubuntu-* to system-* in doc-comment

osutil/chdir_test.go, osutil/cp_linux_test.go, osutil/cp_test.go, osutil/exitcode_test.go, osutil/export_test.go, osutil/fshelpers_test.go, osutil/outputerr_test.go, osutil/stat_test.go
Also add some mocking functions in order to properly test things.
=> osutil/many: make all test pkgs osutil_test instead of "osutil"

bootloader/uboot.go, overlord/snapstate/check_snap_test.go, secboot/secboot_tpm.go, seed/seedwriter/writer.go
Some silly little things I have from various other random branches.
=> misc: little tweaks

snap/info.go
Thanks to @bboozzoo for the recommendation.
=> snap/info.go: add doc-comment for SortServices

gadget/layout.go
=> gadget: fix documentation/typos

HACKING.md
I had to run UC20 spread tests locally and had forgotten the tricks, so leave some info for folks who want to try this out (probably myself 3-6 months from now again)
=> HACKING.md: explain how to run UC20 spread tests with QEMU

overlord/backend.go
=> overlord: DEBUG PATCH: print some information about state.json

overlord/devicestate/firstboot20_test.go
this is double checking the early config mechanics end to end
=> o/devicestate: test that users.create.automatic is configured early

boot/modeenv.go
=> boot: fix typo, should be systems

spread.yaml, tests/lib/pkgdb.sh, tests/lib/prepare-restore.sh, tests/main/boot-state/task.yaml, tests/main/interfaces-opengl-nvidia/task.yaml, tests/main/snap-run/task.yaml, tests/smoke/sandbox/task.yaml
Move from regular SPREAD_SYSTEM check to os.query check
=> tests: use new commands of os.query tool on tests

gadget/update.go
Small followup from PR#9907, thanks to Maciej for the suggestion.
=> gadget: simplify filterUpdate (thanks to Maciej)

boot/systems_test.go
A little tweak to systems tests in the boot package.
=> boot: simplify systems test setup

boot/assets.go, boot/assets_test.go, boot/boot_test.go, boot/export_test.go, boot/makebootable.go, boot/modeenv.go, boot/modeenv_test.go, boot/seal_test.go, boot/systems_test.go
This is not the way. 
There is a simpler way that we will do instead.
=> boot: revert #10009

daemon/api_validate_test.go
Cleanup/simplify validation sets api tests a bit.
=> daemon: validation sets/api tests cleanup

interfaces/apparmor/backend.go, interfaces/apparmor/backend_test.go
Apply the cleanups suggested in the review of https://github.com/snapcore/snapd/pull/10081.
=> interfaces/apparmor: followup cleanups, comments and tweaks

interfaces/builtin/u2f_devices.go, interfaces/builtin/u2f_devices_test.go
Fixes: https://launchpad.net/bugs/1919268
=> interfaces/u2f-devices: add HyperFIDO Pro

features/features.go, features/features_test.go
Introduce refresh-control feature flag.
=> features: add gate-auto-refresh-hook feature flag

tests/lib/prepare-restore.sh
We have a bug where trying to purge the snapd debian package at the same time
that there is an on-going auto-refresh will cause snapd to die and then trigger
snap-failure to start, which re-writes some of the files that the debian
package maintainer scripts deleted, which thus causes the purge to fail because
after the maintainer scripts return, the /var/lib/snapd directory is not empty
and thus isn't removed by apt and the operation fails.
This code sidesteps that issue by cancelling all ongoing changes, then removing
all snaps, then purging snapd. These things should move into the debian
maintainer postrm scripts eventually since this is a real operation that could
happen in the real world, but for now to have more stable spread tests, do this
manually by ourselves.
Also add a bit more …
=> tests/lib/prepare-restore.sh: clean out snapd changes and snaps before purging

tests/main/help/task.yaml
The help test works in all the supported systems, let's test on them
=> tests: enable help test for all the systems

boot/boot.go, boot/boot_test.go, boot/cmdline.go
~~Stacked on top of #10140.~~ The relevant commit is https://github.com/snapcore/snapd/commit/0e4abc9f9b6e5dea27dbeddc711e1ab68cc8d0ee
Note that this branch does not include the actual consumer of the change proposed here, hence the 'skip spread' label.
=> boot: handle updating of components that contribute to kernel command line

wrappers/services.go
We need to use a very similar function in an upcoming function to ensure the
state of systemd slice units is updated, so we ought to break out the bulk of
the implementation handling the ensuring of the file state to a separate
function that can be reused.
=> wrappers/services.go: refactor helper lambda function to separate function

overlord/snapstate/snapstate.go
Drop unused argument of ensureInstallPreconditions function.
=> o/snapstate: remove unused DeviceCtx argument of ensureInstallPreconditions

daemon/daemon_test.go
=> daemon: test that requesting restart from (early) Ensure works

daemon/api_apps_test.go, daemon/api_base_test.go, overlord/configstate/configcore/vitality.go, overlord/configstate/configcore/vitality_test.go, overlord/managers_test.go, overlord/overlord.go, overlord/overlord_test.go, overlord/servicestate/servicemgr.go, overlord/servicestate/servicemgr_test.go, overlord/servicestate/servicestate.go, overlord/servicestate/servicestate_test.go, overlord/snapstate/backend/link.go, overlord/snapstate/backend/link_test.go, overlord/snapstate/backend_test.go, overlord/snapstate/booted_test.go, overlord/snapstate/handlers.go, overlord/snapstate/handlers_link_test.go, overlord/snapstate/snapstate_test.go, systemd/emulation.go, systemd/systemd.go, systemd/systemd_test.go, tests/regression/vitality-rank-uc18-required-snapd-snap/task.yaml, wrappers/core18.go, wrappers/services.go, wrappers/services_gen_test.go, wrappers/services_test.go
This is https://github.com/snapcore/snapd/pull/10163 for 2.50 - it includes https://github.com/snapcore/snapd/pull/10191
=> o/configstate/configcore/vitality: fix RequireMountedSnapdSnap bug (2.50)

client/quota.go, client/quota_test.go, cmd/snap/cmd_quota.go, cmd/snap/cmd_quota_test.go
Implementation of `snap remove-quota` command & client method (see last commit).
=> cmd/snap, client: snap remove-quota command

client/quota.go, client/quota_test.go, daemon/api_quotas.go, tests/main/snap-quota/task.yaml
Draft, do not review yet. Will be tweaked and fleshed out once the feature works.
=> tests: basic spread test for snap quota commands

seed/seedwriter/writer.go
=> seed/seedwriter: clarify in the diagram when SetInfo is called

overlord/devicestate/devicestate_test.go
Some of the helpers that were originally part of the deviceMgrSuite were moved
to deviceMgrBaseSuite. Move them closer to the definition of the suite
structure.
=> overlord/devicestate: move devicemgr base suite helpers closer to test suite struct

overlord/devicestate/systems.go, overlord/devicestate/systems_test.go
Followup to #10181. Tweak the comment about getInfo. Simplify formatting, expand
comments in tests.
=> overlord/devicestate: tweak comment about creating recovery systems, formatting tweaks

daemon/api_apps.go, daemon/api_connections.go, daemon/api_console_conf.go, daemon/api_download_test.go, daemon/api_general.go, daemon/api_model.go, daemon/api_quotas_test.go, daemon/api_snap_file_test.go, daemon/api_systems_test.go, daemon/api_validate_test.go, daemon/daemon.go
=> daemon: fix linter errors

tests/main/system-usernames-illegal/task.yaml, tests/main/system-usernames-install-twice/task.yaml, tests/main/system-usernames-missing-user/task.yaml, tests/main/system-usernames/task.yaml
=> tests: remove old fedora systems from tests

spread.yaml
Bump the reference version for generating deltas.
=> spread: bump delta reference version

.github/workflows/test.yaml, spread.yaml, tests/main/debug-sandbox/task.yaml, tests/main/degraded/task.yaml, tests/main/system-usernames-illegal/task.yaml, tests/main/system-usernames-install-twice/task.yaml, tests/main/system-usernames-missing-user/task.yaml, tests/main/system-usernames/task.yaml
New image created and support added to snapd test suite to test on debian 10
=> tests: adding support for debian 10 on gce

overlord/managers_test.go
Some tweaks to the unit tests.
=> overlord:  unit test tweaks, use well known snap IDs, setup snap declarations for most common snaps

spread.yaml
Make sure that unattended-upgrades is disabled on Debian.
=> spread: disable unattended-upgrades on debian

overlord/hookstate/ctlcmd/refresh.go, overlord/hookstate/ctlcmd/refresh_test.go
Print "pending" info on `snapctl refresh --pending`.
From the spec: pending is set to none if there are no pending refreshes for the snap itself. It is set to ready if there are, and to inhibited if there are but they are inhibited because some of the snap applications are running and "refresh app awareness" is enabled.
=> o/hookstate: print pending info (ready, inhibited or none)

cmd/snap/cmd_get_base_declaration.go, cmd/snap/cmd_get_base_declaration_test.go, daemon/api_debug.go, daemon/api_debug_test.go, daemon/api_model.go, daemon/api_model_test.go, tests/main/snap-debug-get-base-declaration/task.yaml
=> daemon: tighten access to a couple of POST endpoints that should be really be root-only

packaging/debian-sid/patches/0006-systemd-disable-snapfuse-system.patch
Update systemd patch to apply on latest master
=> packaging/debian-sid: update systemd patch

tests/main/snap-user-dir-perms-fixed/task.yaml
=> tests: fix snap-user-dir-perms-fixed vs format checks

usersession/userd/privileged_desktop_launcher_internal_test.go
Some systems use /var/lib/snapd, make sure that relevant unit tests are passing
there too.
=> usersession/userd: fix unit tests on systems using /var/lib/snapd

store/store_action.go
Fix typo in snapActionResult struct json tag.
=> store: fix typo in snapActionResult struct json tag

daemon/api_buy_unsupp.go, daemon/api_find.go, daemon/api_find_test.go, daemon/api_model.go, daemon/api_sections.go, daemon/api_snap_conf.go, daemon/api_snapctl.go, daemon/api_users.go, daemon/api_users_test.go, daemon/api_validate.go, daemon/response.go
=> daemon: use apiError for more of the code

interfaces/builtin/dsp.go
Thanks to @woodrow-shen for verifying the fix
=> interfaces/dsp: fix typo in udev rule

daemon/errors.go, daemon/errors_test.go, daemon/response.go, daemon/response_test.go
=> daemon: split out error response code from response*.go to errors*.go

tests/main/apparmor-batch-reload/task.yaml, tests/main/base-policy/task.yaml, tests/main/base-snaps/task.yaml, tests/main/ca-certs-for-snaps/task.yaml, tests/main/configure-hook-with-network-control/task.yaml, tests/main/disable-autoconnect/task.yaml, tests/main/install-errors/task.yaml, tests/main/interfaces-opengl-nvidia/task.yaml, tests/main/lxd-no-fuse/task.yaml, tests/main/lxd-postrm-purge/task.yaml, tests/main/lxd-snapfuse/task.yaml, tests/main/lxd/task.yaml, tests/main/searching/task.yaml, tests/main/selinux-lxd/task.yaml, tests/main/snap-seccomp/task.yaml, tests/regression/lp-1644439/task.yaml, tests/smoke/sandbox/task.yaml
Minor changes to clean up tests and remove old style
=> tests: first part of the cleanup

systemd/emulation.go, systemd/systemd.go, systemd/systemd_test.go
As suggested by Maciej, Michael and Samuele in snapcore/snapd#10354.
=> systemd: refactor property parsers for int values in CurrentTasksCount, etc.

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
Release 2.51.1 against the release/2.51 branch.
Once this is merged I will tag the release.
=> release: snapd 2.51.1

osutil/bootid_test.go, osutil/buildid_test.go, osutil/chdir_test.go, osutil/disks/labels_test.go, osutil/exitcode_test.go, osutil/fshelpers_test.go, osutil/io_test.go, osutil/outputerr_test.go, osutil/stat_test.go, strutil/map_test.go, strutil/quantity/example_test.go, testutil/lowlevel_test.go
=> osutil,strutil,testutil: fix imports order (according to gci)

interfaces/builtin/netlink_driver_test.go
As requested by Michael in https://github.com/snapcore/snapd/pull/10380#discussion_r651551919
=> interfaces/builtin/netlink_driver_test.go: add test snippet

interfaces/builtin/opengl.go, interfaces/builtin/opengl_test.go
interfaces/opengl: add support for Imagination PowerVR
=> interfaces/opengl: add support for Imagination PowerVR

daemon/api_quotas_test.go, overlord/configstate/configcore/vitality_test.go, overlord/managers_test.go, overlord/servicestate/quota_handlers.go, overlord/servicestate/servicestatetest/quotas.go
* Fix some of the tests in api_quotas_test which were not restoring mocked functions properly.
* Add servicestatetest.MockQuotaInState and use it in external package tests
* Also delete a completed TODO
=> o/svcstate/svcstatetest, daemon/api_quotas: fix some tests, add mock helper

cmd/libsnap-confine-private/cgroup-support.c
=> cmd/libsnap-confine-private/cgroup-support.c: Fix typo

tests/main/preseed/task.yaml
Images are using core20 on systems 20.10 and 21.04
=> tests: fix preseed test to used core20 snap on latest systems

asserts/crypto.go, asserts/extkeypairmgr.go, asserts/extkeypairmgr_test.go, asserts/gpgkeypairmgr.go, vendor/vendor.json
this supports using an external program with a simple interface to handle key management.
=> asserts: introduce ExternalKeypairManager

client/quota.go, client/quota_test.go, overlord/servicestate/quota_handlers.go, overlord/servicestate/quota_handlers_test.go
Some small adjustments as suggested by myself and others in the pre-req's which have now landed.
=> many/quotas: little adjustments

cmd/snap/cmd_quota.go
Thanks to Graham for the suggestions here.
=> cmd/snap/quotas: adjust help texts for quota commands

overlord/servicestate/quota_control.go, overlord/servicestate/quota_handlers.go
These cover comments on #10471
=> o/servicestate: TODO and fix preexisting typo

.github/workflows/test.yaml, cmd/snap-confine/spread-tests/main/test-seccomp-compat/task.yaml, spread.yaml, tests/lib/pkgdb.sh, tests/main/interfaces-fwupd-classic/task.yaml, tests/regression/lp-1644439/task.yaml
As bionic 32 bits is being tested, this change is to remove xenial 32 bits.
=> tests: remove xenial 32 bits

overlord/devicestate/devicestate.go, overlord/devicestate/devicestate_remodel_test.go
It is possible that a remodel can occur on the same day as the image is built,
in which case try to not fail and pick an alternative recovery system label.
=> overlord/devicestate: try to pick alternative recovery labels during remodel

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
Release 2.51.2 changelog to master
=> release: 2.51.2

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
Update changelog with the 2.51.3 changes.
=> release: 2.51.3

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
Merge back the changelog from 2.51.3 to master.
=> packaging: merge changelog from 2.51.3 back to master

gadget/gadget_test.go, gadget/validate.go, gadget/validate_test.go, overlord/devicestate/devicestate_install_mode_test.go
=> gadget: check for system-save with multi volumes if encrypting correctly

spread.yaml, tests/lib/nested.sh, tests/lib/pkgdb.sh, tests/lib/tools/os.query, tests/main/degraded/task.yaml, tests/main/lxd-mount-units/task.yaml, tests/main/lxd/task.yaml, tests/main/os.query/task.yaml, tests/main/security-dev-input-event-denied/task.yaml
New system added to spread test suite
Also included new dependencies needed
=> tests: adding Ubuntu 21.10 to spread test suite

interfaces/builtin/dbus.go, interfaces/builtin/gpio.go, interfaces/builtin/pwm.go
=> interfaces: s/specifc/specific/

.github/workflows/test.yaml
=> tests: fix cached-results condition in github actions workflow

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
Update changelog with the 2.51.4 changes.
=> release: 2.51.4

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
Update changelog with the 2.51.5 changes.
=> release: 2.51.5

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
Update changelog with the 2.51.6 changes.
=> release: 2.51.6

spread.yaml, tests/core/create-user-2/task.yaml
Removing xenial and adding hirsute, according to the supported systems
=> tests: update systems for sru validation

testutil/containschecker.go, testutil/containschecker_test.go
Adds a Checker to test that two containers have the same elements (duplicates must occur in the same number) but possibly in different orders.
=> testutil: add DeepUnsortedMatches Checker

spread.yaml
So that spread uploads are smaller
=> spread: bump delta ref to 2.52

.github/workflows/macos-sanity.yaml, .github/workflows/test.yaml, README.md, osutil/flock_test.go, run-checks, spread.yaml
Remove all the travis references in the project
=> tests: remove travis leftovers

systemd/systemd.go
Thanks @mvo for the suggestion! :-)
=> systemd: use text.template to generate mount unit

spread.yaml
This info could be useful in case of errors related to user sessions
=> tests: print user sessions info on debug-each

kernel/fde/fde_test.go
This test has been occasionally failing under spread:
```
FAIL: fde_test.go:492: fdeSuite.TestRevealErr
using shellcheck: ""
fde_test.go:508:
c.Assert(err, ErrorMatches, `(?s)cannot run fde-reveal-key "reveal":
-----
failed
service result: exit-code
-----`)
... error string = "cannot run fde-reveal-key \"reveal\": exit status 1"
... regex string = "" +
...     "(?s)cannot run fde-reveal-key \"reveal\": \n" +
...     "-----\n" +
...     "failed\n" +
...     "service result: exit-code\n" +
...     "-----"
OOPS: 9 passed, 5 skipped, 1 FAILED
```
While we couldn't yet reproduce it locally and find what exactly
triggers it, it makes sense to exclude systemd-run from the picture by
mocking it. We now simply check that it was invoked with the right
parameters and that its output is captured …
=> kernel/fde: mock systemd-run in unit test

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
Update changelog with the 2.52.1 changes.
=> release: 2.52.1

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
Update changelogs with the 2.53 changes.
=> release: 2.53

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
Update changelogs with the 2.53.1 changes.
=> release: 2.53.1

overlord/snapstate/snapstate_install_test.go, overlord/snapstate/snapstate_test.go
introduce snapmgrBaseTest instead
=> o/snapstate: avoid validationSetsSuite repeating snapmgrTestSuite

interfaces/builtin/dsp.go, interfaces/builtin/dsp_test.go
As per customer ticket 00321783.
=> interfaces/dsp: add more ambarella things

spread.yaml, tests/nested/manual/cloud-init-never-used-not-vuln/task.yaml, tests/nested/manual/core20-cloud-init-maas-signed-seed-data/task.yaml
See individual commits for details
=> tests: misc robustness changes

cmd/snap/cmd_run.go, cmd/snap/cmd_run_test.go
https://bugs.launchpad.net/snapd/+bug/1910298
follow-up of https://github.com/snapcore/snapd/pull/9897
=> cmd: create ~/snap dir with 0700 perms

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
Update changelogs with the 2.53.2 changes.
=> release: 2.53.2

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
Merge 2.53.2 changelog back to master
=> packaging: merge changelog for 2.53.2 back to master

build-aux/snap/snapcraft.yaml
Fun times with snapcraft.yaml!
=> snapcraft.yaml: fix advanced grammar & 20.04 packaging

packaging/fedora/snapd.spec, packaging/opensuse/snapd.spec
Update spec files with what we use in Fedora and openSUSE.
=> packaging: sync with downstream packaging in Fedora and openSUSE

asserts/database_test.go
First PR to fix an error from the "woke" checker [1].
[1] https://github.com/get-woke/woke
=> asserts: rename "white box" to "clear box" (woke checker)

tests/lib/tools/query-mondodb
This can be used to get information of test errors collection in snapd mongo db
Please suggest different ways to aggregate data
=> tests: new tool used to retrieve data from mongo db

daemon/api.go, daemon/api_base_test.go, daemon/api_sideload_n_try.go, daemon/api_sideload_n_try_test.go, daemon/api_snaps.go, daemon/api_test.go, daemon/export_test.go
Backport of https://github.com/snapcore/snapd/pull/11053
=> daemon: write formdata file parts to snaps dir (2.53)

overlord/devicestate/devicemgr.go, overlord/devicestate/devicestate_serial_test.go
This is https://github.com/snapcore/snapd/pull/10900 for 2.53
=> o/devicestate: introduce DeviceManager.Unregister (2.53)

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
Update changelogs with the 2.53.3 changes.
=> release: 2.53.3

tests/core/kernel-and-base-single-reboot-failover/task.yaml, tests/lib/fakestore/cmd/fakestore/cmd_make_refreshable.go, tests/lib/fakestore/cmd/fakestore/main.go, tests/lib/fakestore/refresh/refresh.go
Verify single reboot and failover
=> tests/core/kernel-and-base-single-reboot-failover, tests/lib/fakestore: verify failover scenario

overlord/snapstate/check_snap.go, overlord/snapstate/snapstate.go, overlord/snapstate/snapstate_install_test.go, overlord/snapstate/snapstate_test.go, overlord/snapstate/storehelpers.go, snap/snaptest/snaptest.go
Backport of https://github.com/snapcore/snapd/pull/11109. Depends on https://github.com/snapcore/snapd/pull/11140
=> o/snapstate: add InstallPathMany (2.53)

daemon/api.go, daemon/api_sideload_n_try.go, daemon/api_sideload_n_try_test.go, daemon/api_snaps.go, daemon/export_test.go
Add support for sideloading multiple local snaps.
=> daemon: add multiple snap sideload to API

daemon/api.go, daemon/api_sideload_n_try.go, daemon/api_sideload_n_try_test.go, daemon/api_snaps.go, daemon/export_test.go
Backport of #https://github.com/snapcore/snapd/pull/11134. The changes are the same.
=> daemon: add multiple snap sideload to API (2.53)

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
Release version 2.54 of snapd.
=> release: 2.54

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
Release version 2.54.1 of snapd.
=> release: 2.54.1

tests/main/microk8s-smoke/task.yaml
=> tests: do not test microk8s-smoke on arm

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
Update changelogs with the 2.54.2 changes.
=> release: 2.54.2

overlord/hookstate/ctlcmd/umount.go, overlord/hookstate/ctlcmd/umount_test.go
go-flags already does this check. Thanks Miguel for spotting it!
=> overlord/h/c/umount: remove handling of required parameter

tests/lib/assertions/test-snapd-remodel-pc-cross-store-18.json, tests/lib/assertions/test-snapd-remodel-pc-cross-store-18.model, tests/lib/assertions/test-snapd-remodel-pc-cross-store-20.json, tests/lib/assertions/test-snapd-remodel-pc-cross-store-20.model, tests/lib/snaps/test-snapd-remodel-pc-18/meta/hooks/prepare-device, tests/lib/snaps/test-snapd-remodel-pc-20/meta/hooks/prepare-device, tests/nested/manual/remodel-cross-store/task.yaml, tests/nested/manual/remodel-simple/task.yaml
Add a cross store remodel spread test. Based on #11122
=> tests: cross store remodel

gadget/update.go, gadget/update_test.go
Also add doc-comments.
As requested by Samuele in https://github.com/snapcore/snapd/pull/11220
=> gadget: rename DiskVolume...Opts to DiskVolume...Options

gadget/gadget_test.go, gadget/gadgettest/gadgettest.go, gadget/install/install.go, gadget/install/install_test.go, gadget/update_test.go, gadget/validate_test.go
Also small test enhancement for install.Run() which right now is basically entirely not unit tested. In a followup I will propose a unit test there but I already had this small bit ready so I figured why not throw it in with this PR.
=> gadget: mv modelCharateristics to gadgettest.ModelCharacteristics 

overlord/servicestate/service_control_test.go, tests/lib/snaps/test-snapd-service-many/bin/start, tests/lib/snaps/test-snapd-service-many/meta/snap.yaml, tests/main/services-stress/task.yaml, wrappers/services.go, wrappers/services_test.go
Some of the initial batched called split out from #10463. Still needs more work and tweaks for cases where we could call Enable/Disable fewer times
=> systemd: batched operations

tests/external-backend.md
=> tests: updated the documentation to run spread tests using external backend

packaging/fedora/snapd.spec
Sync with downstream changes from Fedora. Use proper rpm macro for selinux deps
=> packaging/fedora: sync with downstream, packaging improvements

HACKING.md
This commit contains cosmetic changes that are intended to clean up some of the legacy leftovers (e.g. reference to Go 1.6).
The major changes were made within the [HACKING.md](https://github.com/are-scenic/snapd/blob/cosmetic_cleanups/HACKING.md) document. 
Please review the changes! Any comment is greatly appreciated.
Thank you,
Arseniy
---
Following the request of @anonymouse64, this is the list of the tests that fail due to strict assumption on system locale:
- `cmd_list_test.go`:31: `SnapSuite.TestListHelp`
- `cmd_login_test.go`:70: `SnapSuite.TestLoginAskEmail`
- `cmd_reboot_test.go`:33: `SnapSuite.TestRebootHelp`
- `cmd_recovery_test.go`:32: `SnapSuite.TestRecoveryHelp`
- `cmd_snapshot_test.go`:79: `SnapSuite.TestSnapSnaphotsTest`
- `cmd_whoami_test.go`:31: …
=> docs: cosmetic cleanups

tests/core/mem-cgroup-disabled/task.yaml
As suggested by Sergio in https://github.com/snapcore/snapd/pull/11342#pullrequestreview-876021007
=> tests/core/mem-cgroup-disabled: minor fixups

cmd/libsnap-confine-private/string-utils.c
=> libsnap-confine-private: string functions simplification

data/env/snapd.fish.in
@faho pointed out in https://github.com/snapcore/snapd/pull/11416 this can be
done in a single set call
=> data/env: cosmetic tweak for fish

overlord/snapstate/snapstate_update_test.go
Test that multiple refreshes do garbage collection of old revisions when refresh.retain is lower than our default for core. This replicates the scenario from bug #1947724 (and works fine because the problem is elsewhere).
=> tests: add test to ensure consecutive refreshes do garbage colleciton of old revs

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
This commit contains the changelog for the 2.54 release.
=> release: 2.54.4 changelog

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
Merge the 2.54.4 changelog back into master
=> release: 2.54.4 changelog to master

daemon/api_systems_test.go, overlord/devicestate/devicemgr.go, overlord/devicestate/devicestate_systems_test.go
The first bits of factory reset support.
=> o/devicestate, daemon: introduce factory-reset mode, allow switching

.github/workflows/test.yaml, tests/lib/tools/report-mongodb
The idea is to have traceability to the original error log in the mondo db issues.
So then the URL can be included in the jira issue comments when a new system fails.
=> tests: Include the source github url as part of the mongo db issues

tests/lib/tools/report-mongodb
=> tests/lib/tools/report-mongodb: fix typo in help text

overlord/snapstate/snapstate.go, overlord/snapstate/snapstate_test.go, overlord/snapstate/snapstate_update_test.go
Add snapd as an explicit prerequisite for the base snaps. Add unit test for
that.
=> o/snapstate: make sure that snapd is a prerequisite for updating base snaps

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
Update changelogs with the 2.55 changes.
=> release: 2.55

cmd/snap-update-ns/change_test.go
On armhf and arm64 LP builders, /opt/runtime exists and is a symlink, so the
new code added in https://github.com/snapcore/snapd/pull/10676 would detect
this and thus generate a different mount operation order.
Using a name like foo-runtime should shield us from such issues going forward.
=> cmd/snap-update-ns/change_test.go: use non-exist name foo-runtime instead

interfaces/systemd/backend.go, interfaces/systemd/backend_test.go, overlord/configstate/configcore/services.go, overlord/configstate/configcore/services_test.go, overlord/configstate/configcore/vitality_test.go, overlord/managers_test.go, overlord/servicestate/service_control_test.go, systemd/emulation.go, systemd/systemd.go, systemd/systemd_test.go, wrappers/core18.go, wrappers/core18_test.go, wrappers/services.go, wrappers/services_test.go
Backport of https://github.com/snapcore/snapd/pull/11353 to 2.55
=> systemd: do not reload system when enabling/disabling services (2.55)

overlord/devicestate/devicemgr.go, overlord/devicestate/handlers_install.go
Some cleanups noticed during review of #11496
=> overlord/devicestate: install system cleanups

bootloader/lkenv/lkenv.go, cmd/snap-seccomp/main.go, cmd/snap-update-ns/change.go, cmd/snap/cmd_services.go, interfaces/builtin/dsp_test.go, snapdtool/export_test.go, snapdtool/tool_linux.go, snapdtool/tool_linux_test.go, snapdtool/tool_test.go, spread.yaml, tests/main/snapd-snap/task.yaml
In keeping with tradition, I have to assume that some part of 6f903940b5401f72ac7faf06249f65c41db04240 will become contentious so feel free to drop that patch, otherwise the rest of these should be easy to approve typos :smile:
=> many: small inconsequential tweaks

packaging/ubuntu-16.04/control
=> packaging/ubuntu-16.04/control: depend on fuse3 | fuse

gadget/gadgettest/examples.go, gadget/install/install.go, gadget/install/install_dummy.go, gadget/install/install_test.go, gadget/install/partition.go, overlord/devicestate/handlers_install.go
Split out from the WIP branch, rebased on top of #https://github.com/snapcore/snapd/pull/11496. The relevant commit is https://github.com/snapcore/snapd/commit/f04d651b0e54278621ba28915d9e2fa619c6eb2c
=> gadget/install: implement factory reset for unencrypted system

overlord/managers_test.go, overlord/state/change.go, overlord/state/change_test.go
Add a checker that can identify problems such as in #11520.
=> overlord/state: add a helper to detect cyclic dependencies between tasks in change

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
The changelog for release 2.55.3
=> release: version 2.55.3

snap/info_test.go, snap/snapshots.go
This is a follow-up on https://github.com/snapcore/snapd/pull/11517, implementing the changes suggested by Samuele.
=> snapshots: follow-up on exclusions PR

gadget/device_test.go
Now that multi volume gadget updates moved to using disks, the code is no longer
needed.
=> gadget: drop unused code in unit tests

spread.yaml, tests/lib/tools/tests.nested, tests/nested/core/core20-create-recovery/task.yaml, tests/nested/core/core20-degraded/task.yaml, tests/nested/core/core20-factory-reset/task.yaml, tests/nested/core/core20-fault-inject/task.yaml, tests/nested/core/core20-gadget-reseal/task.yaml, tests/nested/core/core20-kernel-failover/task.yaml, tests/nested/core/core20-kernel-reseal/task.yaml, tests/nested/core/core20-reinstall-partitions/task.yaml, tests/nested/core/coreconfig-services/task.yaml, tests/nested/core/interfaces-custom-devices/task.yaml, tests/nested/manual/core20-boot-config-update/task.yaml, tests/nested/manual/core20-custom-kernel-commandline/task.yaml, tests/nested/manual/core20-early-config/task.yaml, tests/nested/manual/core20-initramfs-time-moves-forward/task.yaml, tests/nested/manual/core20-install-mode-shutdown-via-hook/task.yaml, tests/nested/manual/devmode-snap-seeded-dangerous/task.yaml, tests/nested/manual/refresh-revert-fundamentals/task.yaml, tests/nested/manual/snapd-removes-vulnerable-snap-confine-revs/task.yaml, tests/nested/manual/uc20-fde-hooks-v1/task.yaml, tests/nested/manual/uc20-fde-hooks/task.yaml
This is the initial set of tests to include on nested executions
=> tests: initial set of tests to uc22 nested execution

overlord/snapstate/backend/snapdata.go, overlord/snapstate/backend/snapdata_test.go, tests/lib/snaps/snap-hooks/meta/hooks/remove, tests/main/hidden-snap-dir/task.yaml, tests/main/install-refresh-remove-hooks/task.yaml
This tests a fresh install of a core22 based snap followed by a remove and new install.
=> tests: test fresh install of core22-based snap

cmd/snap-fde-keymgr/main.go, secboot/keymgr/keymgr_luks2.go, secboot/keyring/keyring.go, secboot/luks2/cryptsetup.go, secboot/luks2/fifo.go, secboot/luks2/luks2.go
Some cleanups suggested by @mardy in #11715
=> cmd/snap-fde-keymgr, secboot: followup cleanups

.github/workflows/test.yaml, tests/nested/core/core20-basic/task.yaml, tests/nested/core/core22-basic/task.yaml
This change is to allow running just the failed tests for google-nested backend when the "Run failed" tag is set
=> tests: run failed tests on nested suite

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
The changelog for the 2.55.5 release
=> release: 2.55.5

osutil/disks/disks_darwin.go, osutil/disks/disks_linux.go, osutil/disks/disks_linux_test.go
=> osutil/disks: partition UUID lookup

secboot/encrypt_dummy.go, secboot/encrypt_sb.go, secboot/encrypt_sb_test.go
Add support for changing encryption key of an unlocked device
=> secboot: support for changing encryption keys via keymgr

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
Changelog for the 2.56 release.
=> release: 2.56

overlord/devicestate/devicemgr.go, overlord/devicestate/devicestate_recovery_keys_test.go, overlord/devicestate/export_test.go, secboot/encrypt.go, secboot/encrypt_dummy.go, secboot/encrypt_sb.go, secboot/encrypt_sb_test.go, tests/main/uc20-create-partitions-encrypt/task.yaml, tests/nested/core/core20-basic/task.yaml, tests/nested/core/core20-tpm/task.yaml, tests/nested/core/core22-basic/task.yaml
Optional recovery keys. Based on #11748, with cherry picks from #11757.
The tests that verify idempotency of adding a recovery key will fail until #11800 lands
=> many: optional recovery keys

systemd/sysctl.go, systemd/sysctl_test.go
From a comment by @mvo5 on a code review.
=> systemd: improve error handling for systemd-sysctl command

interfaces/builtin/browser_support.go, tests/main/interfaces-browser-support/task.yaml
=> tests/main/interfaces-browser-support: verify jupyter notebooks access

daemon/snap.go, overlord/assertstate/assertstate.go, overlord/assertstate/assertstate_test.go, overlord/hookstate/ctlcmd/ctlcmd.go, overlord/hookstate/ctlcmd/export_test.go, overlord/hookstate/ctlcmd/model.go, overlord/hookstate/ctlcmd/model_test.go
This is the third PR and followup to https://github.com/snapcore/snapd/pull/11778. This adds the new snapctl command. There was an older attempt at doing this by me which had received some PR comments, I have tried to address them within this PR, so fear not! Your previous review of this PR was not a waste and still appreciated!
=> overlord/hookstate/ctlcmd: add 'snapctl model' command (3/3)

secboot/encrypt_dummy.go, secboot/encrypt_sb.go, secboot/encrypt_sb_test.go
secboot level wrappers for keymgr operations
=> secboot: stage and transition encryption keys

tests/main/listing/task.yaml
This to make the test work on external backend
=> tests: add support for uc22 in listing test

dirs/dirs.go, overlord/ifacestate/handlers.go, overlord/ifacestate/handlers_test.go
I seem to have used /etc/ instead of /run/, which caused my journal spread tests to fail.
=> overlord/ifacestate: fix path for journal redirect

tests/main/debug-migrate-home/task.yaml
Adds a spread test for the `snap debug migrate-home` command.
=> tests: add spread test for migrate-home command

tests/nested/manual/connections/task.yaml
The change is to teardown the fake store
=> tests: fix nested/manual/connections test

boot/seal.go, cmd/snap-bootstrap/cmd_initramfs_mounts.go, gadget/device/encrypt.go, gadget/device/encrypt_test.go, gadget/update.go, overlord/devicestate/devicemgr.go, overlord/devicestate/handlers_install.go
Various helpers for getting location of things were spread out or doubled in the code base. This package aggregates them in one place.
=> gadget/device: introduce package which provides helpers for locations of things

overlord/servicestate/quota_handlers.go, overlord/servicestate/quota_handlers_test.go
This was missing and discovered while adding this case to a spread test. It's not that critical, but it still needs to be done. This can land after https://github.com/snapcore/snapd/pull/11815 and includes that PR.
=> overlord/servicestate: restart the relevant journald service when a journal quota group is modified

asserts/model.go, asserts/model_test.go
Allow models with classic field that can contain kernel and bases, and add distribution field to model for classic.
=> asserts: allow classic + snaps models and add distribution to model

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
Updating version numbers and changelogs.
=> release: 2.57.1

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
Merge the 2.57 changelog back into master.
=> release: merge 2.57 changelog

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
=> release: 2.57.2

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
=> release: snapd 2.57.3

overlord/devicestate/handlers_bootconfig.go, overlord/devicestate/handlers_gadget.go, overlord/devicestate/handlers_systems.go, overlord/snapstate/export_test.go, overlord/snapstate/handlers.go, overlord/snapstate/handlers_link_test.go, overlord/snapstate/snapstate.go
This change will allow holding tasks in certain error conditions.
=> overlord,daemon: allow returning errors when requesting a restart

gadget/install/install.go
Split the Run function that performs the installation in more manageable functions that can be more easily reused.
=> gadget/install: split Run in several functions

overlord/hookstate/hookmgr.go, overlord/ifacestate/ifacestate.go, overlord/servicestate/conflict.go, overlord/servicestate/servicemgr.go, overlord/snapshotstate/snapshotmgr.go, overlord/snapstate/conflict.go, overlord/snapstate/snapmgr.go, overlord/state/change.go, overlord/state/change_test.go, overlord/state/state.go, overlord/state/state_test.go
see each commit
the Has additions are both for completeness and for use in a future PR
=> many: rename AddAffected* to RegisterAffected*, add Change|State.Has, fix a comment

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
=> release: 2.57.4

daemon/api_base_test.go, daemon/api_find_test.go, daemon/api_general_test.go, daemon/api_snaps_test.go, daemon/api_test.go, daemon/api_users.go, daemon/api_users_test.go, daemon/daemon_test.go, overlord/auth/auth.go, overlord/auth/auth_test.go, overlord/devicestate/users.go, overlord/devicestate/users_test.go, overlord/snapstate/handlers_link_test.go, overlord/snapstate/snapstate_test.go, overlord/storecontext/context_test.go
=> o/auth: rename NewUserData to NewUserParams

aspects/aspects.go, aspects/aspects_test.go
Start of configuration aspects orthogonal to snaps.
Basic modeling of aspects and set/get via aspects of underlying configuration data.
=> aspects: initial code

client/quota.go, client/quota_test.go, cmd/snap/cmd_quota.go, cmd/snap/cmd_quota_test.go, daemon/api_quotas.go, daemon/api_quotas_test.go, overlord/devicestate/handlers_gadget.go, overlord/servicestate/quota_handlers.go, overlord/snapstate/handlers.go, snap/quota/quota.go, snap/quota/quota_test.go, tests/core/persistent-journal-namespace/task.yaml, wrappers/services.go, wrappers/services_test.go
This PR includes
https://github.com/snapcore/snapd/pull/12199
https://github.com/snapcore/snapd/pull/12241
They failed automatic merge because of a missing spread test in the 2.57 release branch. So any changes done to this spread test are excluded from this cherry-pick.
=> release: port PR 12199 and 12241

data/apt/20snapd.conf
Thanks for @ julian-klode  for suggesting this.
=> data: tweak apt integration config var

cmd/snap/cmd_snap_op.go, daemon/api_snaps.go
=> many: refresh --hold follow-up

image/image_linux.go, tests/main/prepare-image-classic/task.yaml
This PR addresses small naming/test improvement feedback from https://github.com/snapcore/snapd/pull/12146
See the individual commits for details.
=> image,tests: tweak naming and test for classic UC20+ image

boot/initramfs20dirs.go, gadget/gadget.go, gadget/gadget_test.go, gadget/gadgettest/examples.go, gadget/install/install.go, gadget/validate.go, gadget/validate_test.go, overlord/devicestate/handlers_install.go, tests/nested/manual/fakeinstaller/task.yaml, tests/nested/manual/fde-on-classic/gadget.yaml
Backport/cherry-picks of https://github.com/snapcore/snapd/pull/12287 for 2.58
=> many: backport add system-seed-null role for volume structures in gadget

daemon/api_quotas.go, daemon/api_quotas_test.go, daemon/export_api_quotas_test.go, overlord/managers_test.go, overlord/servicestate/quota_control.go, overlord/servicestate/quota_control_test.go, overlord/servicestate/quota_handlers_test.go
As a pre-requisite for https://github.com/snapcore/snapd/pull/12316, to simplify the changes done before adding additional parameters.
=> overlord,daemon: refactor parameters for CreateQuota into a structure, and rename QuotaGroupUpdate

daemon/api_validate.go, daemon/api_validate_test.go, overlord/assertstate/assertstate.go, overlord/assertstate/assertstate_test.go, overlord/assertstate/validation_set_tracking.go, overlord/assertstate/validation_set_tracking_test.go, tests/main/snap-validate-enforce/task.yaml
Backport of https://github.com/snapcore/snapd/pull/12311 for 2.58
=> many: ensure Current in val set tracking matches PinnedAt, if != 0 (2.58)

boot/boot.go, boot/boot_test.go, overlord/devicestate/devicestate.go, overlord/devicestate/devicestate_remodel_test.go, overlord/devicestate/firstboot.go, overlord/snapstate/backend/setup.go
=> many: cleanups and fixes for classic with modes

cmd/snap/cmd_snap_op.go, cmd/snap/cmd_snap_op_test.go
Backport of https://github.com/snapcore/snapd/pull/12368
=> cmd/snap: error on negative or very short holds (2.58)

cmd/snap-confine/mount-support-test.c, cmd/snap-confine/mount-support.c, cmd/snap-confine/snap-confine.apparmor.in, cmd/snap-update-ns/system.go, cmd/snap-update-ns/system_test.go, data/Makefile, data/systemd-tmpfiles/Makefile, data/systemd-tmpfiles/snapd.conf, interfaces/builtin/x11.go, interfaces/builtin/x11_test.go, overlord/snapstate/snapmgr.go, overlord/snapstate/snapstate_test.go, packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog, tests/lib/reset.sh, tests/main/cgroup-tracking/task.yaml, tests/main/install-refresh-remove-hooks/task.yaml, tests/main/interfaces-x11-unix-socket/task.yaml, tests/main/security-private-tmp/task.yaml, tests/main/snap-confine-drops-sys-admin/task.yaml, tests/main/snap-confine-tmp-mount/task.yaml, tests/main/snap-confine-undesired-mode-group/task.yaml
This merges the CVE-2022-3328 fixes from the release/2.57 branch into release/2.58.
=> many: merge fixes from 2.57.6 (2.58)

overlord/hookstate/ctlcmd/get.go, overlord/hookstate/ctlcmd/is_connected.go, overlord/hookstate/ctlcmd/set.go
based on discussion/suggestions here:
https://forum.snapcraft.io/t/snapctl-health-help-considered-lacklustre/16510/2
=> o/hookstate/ctlcmd: try to clean up/improve snapctl -h

overlord/devicestate/firstboot_test.go
While working on some network namespace environment, I have realized that one of the snapd unit tests was failing. Upon closer inspection it was evident that firstBoot16Suite.TestPopulateFromSeedWithConnectHook was not mocking the device registration server URL, and performing registration against the production snap store each time.
=> devicestate: mock registration server during test

client/packages.go, cmd/snap/cmd_info.go, cmd/snap/cmd_info_test.go, daemon/snap.go
Backport of https://github.com/snapcore/snapd/pull/12436
=> daemon: improvements to REST API helper and JSON responses (2.58)

.shellcheckrc, tests/core/basic20plus/task.yaml, tests/core/kernel-ver/task.yaml, tests/lib/tools/boot-state, tests/main/fake-netplan-apply/task.yaml, tests/main/snap-run-symlink-error/task.yaml
Backport of https://github.com/snapcore/snapd/pull/12438
=> tests: fix shellcheck warnings on unreachable code and var quoting (2.58)

overlord/devicestate/devicestate_install_mode_test.go, overlord/devicestate/handlers_install.go
Take 3 on https://github.com/snapcore/snapd/pull/12339
=> o/devicestate: run systemctl daemon-reload after install-device hook

cmd/snap/notes.go, cmd/snap/notes_test.go, daemon/api_snaps_test.go, daemon/snap.go
Backport of https://github.com/snapcore/snapd/pull/12437
=> cmd/snap,daemon: add 'held' to notes in 'snap list' (2.58)

packaging/opensuse/snapd.spec
Sync with downstream packaging in openSUSE
=> packaging/opensuse: sync with openSUSE packaging

packaging/fedora/snapd.spec
Sync with the downstream packaging in Fedora.
=> packaging/fedora: sync with downstream packaging

client/quota.go, client/quota_test.go, cmd/snap/cmd_quota.go
Followup to one of the comments of my earlier PRs.
=> client,cmd/snap: refactor options to EnsureQuota.

interfaces/builtin/upower_observe.go, interfaces/builtin/upower_observe_test.go
Snap: https://github.com/valentindavid/snap-upower.git
=> i/b/power_observe: Allow daemon on classic and update udev policy

CODING.md, HACKING.md, README.md, mdlint.py, run-checks, tests/manual-tests.md
This captures considerations and practices that we have evolved in the project and should be taken into account when code is reviewed for it.
=> HACKING.md,CODING.md: add a coding/review checklist for the project 

tests/nested/manual/fde-on-classic/gadget.yaml, tests/nested/manual/fde-on-classic/mk-image.sh
Fixup sizes, and add more comments.
=> tests/fde-on-classic: fix fde sizes

.github/workflows/test.yaml, go.mod, go.sum, overlord/devicestate/devicemgr.go, overlord/devicestate/devicestate_install_mode_test.go, overlord/devicestate/devicestate_systems_test.go, overlord/devicestate/export_test.go, overlord/devicestate/handlers_install.go, secboot/export_sb_test.go, secboot/secboot_dummy.go, secboot/secboot_sb_test.go, secboot/secboot_tpm.go
Backport of PR #12418 to release/2.58
=> secboot: detect lockout mode in CheckTPMKeySealingSupported (2.58)

tests/smoke/versioning/task.yaml
This is to find during validation the version is not dirty
=> tests: new smoke test to check the version is not dirty

interfaces/builtin/fwupd.go
Needed for upstream issue https://github.com/fwupd/fwupd/issues/5485
=> i/b/fwupd: allow reading host os-release

cmd/snap/cmd_run_test.go
Added more checks based on my interpretation of this comment:
https://github.com/snapcore/snapd/pull/12535#discussion_r1091983700
=> cmd/snap: enhance inhibit graphical flow unit tests

usersession/userd/launcher.go
=> usersession/userd: reminder about issues with XDG_DATA_DIRS modification

boot/boot.go, boot/boot_test.go, boot/cmdline.go, boot/cmdline_test.go, boot/makebootable.go, boot/makebootable_test.go, overlord/devicestate/handlers_bootconfig.go, overlord/devicestate/handlers_gadget.go, overlord/devicestate/systems.go, strutil/strutil.go, strutil/strutil_test.go
in functions used to update it.
=> boot: introduce parameter for optional kernel command line

tests/core/gadget-update-pc/generate.py, tests/core/gadget-update-pc/task.yaml
We do not need the BIOS boot partition in pc-gadget anymore.  But it might still be here without content for backward compliance.
=> tests: Allow dummy bios boot partition

gadget/kcmdline.go, gadget/kcmdline_test.go, overlord/configstate/configcore/kernel.go, overlord/configstate/configcore/kernel_test.go, overlord/devicestate/devicestate_bootconfig_test.go, overlord/devicestate/devicestate_gadget_test.go, overlord/devicestate/export_test.go, overlord/devicestate/handlers_bootconfig.go, overlord/devicestate/handlers_gadget.go, overlord/state/task.go, tests/lib/assertions/developer1-22-dangerous.json, tests/lib/assertions/developer1-22-dangerous.model, tests/nested/manual/cmdline-option/cloud.conf, tests/nested/manual/cmdline-option/defaults.yaml, tests/nested/manual/cmdline-option/prepare-device, tests/nested/manual/cmdline-option/task.yaml
Use the kernel command line options when building the kernel command
line.
=> many: read system options when handling kernel command line

NEWS.md
This NEWS.md will replace the auto-generated changelogs and we shoudl update it on the fly for any significant PR we land (and it can contain more context than this initial very terse version).
=> NEWS.md: new file and updated for 2.59

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
New 2.59 release, changelog generated from the NEWS.md which makes it much more readable.
=> release: 2.59

tests/lib/prepare.sh
Since a new prepare-device hook has been added to the pc gadget, this has been keeping core-base tests from succeeding. This is the work-around we need.
CI was run on https://github.com/snapcore/core-base/pull/107
=> tests: work-around hooks running at restart

daemon/api_systems_test.go, gadget/export_test.go, gadget/gadget.go, gadget/gadget_test.go, gadget/install/content_test.go, gadget/install/install.go, gadget/install/partition.go, gadget/install/partition_test.go, gadget/layout.go, gadget/layout_test.go, gadget/mountedfilesystem.go, gadget/raw.go, gadget/raw_test.go, gadget/update.go, gadget/update_test.go, overlord/devicestate/devicestate_remodel_test.go
Order structures in gadget according to offset as preparation for min-size and some minor refactoring.
=> many: order structures in gadget according to offset

daemon/api_systems.go, daemon/api_systems_test.go, daemon/export_api_systems_test.go, overlord/devicestate/devicemgr.go, overlord/devicestate/devicestate_install_api_test.go, overlord/devicestate/devicestate_install_mode_test.go, overlord/devicestate/devicestate_systems_test.go, overlord/devicestate/export_test.go, overlord/install/export_test.go, overlord/install/install.go, overlord/install/install_test.go
start separating there the logic to check for encryption support
=> o/install,o/devicestate: start a new package for UC20+ installation logic

aspects/aspects.go, aspects/aspects_test.go
Rename aspect "directory" to "bundle".
=> aspects: rename aspect directory to bundle

boot/assets.go, boot/assets_test.go, tests/nested/manual/muinstaller-real/task.yaml
This goes on top of https://github.com/snapcore/snapd/pull/12753
=> tests/muinstaller-real: test with UBUNTU-SEED fs label

interfaces/core.go
=> interfaces/core.go: comment corrections, no functional changes

gadget/update.go
Remove an unused function that is causing the golangci action to fail on master.
=> gadget: remove unused function

gadget/layout.go, gadget/layout_test.go
=> gadget: remove LaidOutVolume.Size

aspects/aspects.go
Remove an unused struct field.
=> aspects: remove unused field

NEWS.md, packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
Merge the changelog from 2.59.5 back into master.
=> release: 2.59.5

gadget/gadget.go, gadget/gadget_test.go
This  PR introduces the new "partial" field in gadget.yaml and considers it when validating the gadget information.
=> gadget: support validation of partial gadgets

gadget/install/install.go, gadget/install/install_test.go
We need to be consistant on what snap-bootstrap mounts as seed and where UC is installed. There are cases where multiple disks contain UC seed. snap-bootstrap may choose a disk based on kernel parameters.
=> gadget/install/install.go: obey seed mounted by initramfs

packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
Merge 2.60 changelog back into master.
Please use "Merge commit"
=> release: 2.60 (#12894)

tests/lib/prepare.sh
Abandon proposal to drop kernel modules on UC20.
The hypothesis was that the kernel modules loaded on the host at the time of preparation is sufficient and we can delete the other modules to make a smaller image and save time. The reality is far less ideal.
Modules additional to what the host have loaded is required for (1) interfaces and (2) to support other aspects of the host environment such as networking/virtualisation. Instrumented the spread test code to determine a definitive list of drivers loaded by the host at preparation time VS loaded for tests when they pass and calculated the difference. For UC20 the difference was around 40 drivers and for UC22 significantly less. See: SNAPDENG-5917
It was concluded that it was not worth the effort to try and calculate and maintain the …
=> tests/lib: removed proposal to drop kernel modules for uc20

.github/workflows/test.yaml, spread.yaml, tests/lib/image.sh, tests/main/download-timeout/task.yaml, tests/main/fake-netplan-apply/task.yaml, tests/main/lxd-mount-units/task.yaml, tests/main/lxd-postrm-purge/task.yaml, tests/main/lxd-try/task.yaml, tests/main/lxd/task.yaml, tests/main/uc20-create-partitions-encrypt/task.yaml, tests/main/uc20-create-partitions/task.yaml
Spread support for ubuntu mantic
=> tests: adding spread support for ubuntu mantic

gadget/install/install_test.go
The default cipher/keysize on armhf is different from the other platforms. This commit ensures this is taken into account in the `testEncryptPartitions()` test.
=> gadget: fix install test on armhf

NEWS.md, packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
Merge changelog back into master.
Note this should be merged via a "merge commit".
=> release: merge 2.60.1 changelogs back into master

gadget/install/install_test.go
There was no unit tests for [MountVolumes](https://github.com/snapcore/snapd/blob/85cdda5c732c6e6de04f522a5b076badb0c7b393/gadget/install/install.go#L566) before.
=> gadget/install/install_test: add unit tests for MountVolumes

.mailmap, osutil/epoll/epoll.go, osutil/epoll/epoll_test.go, osutil/epoll/export_test.go
Adds the epoll package in preparation for use in apparmor prompting.
=> prompting: add epoll package

tests/main/auto-refresh-pre-download/task.yaml, usersession/agent/rest_api.go, usersession/agent/rest_api_test.go
=> agentnotify: Update the text on refresh dialogs

aspects/transaction.go
Apply this suggestion https://github.com/snapcore/snapd/pull/12892#discussion_r1233953868 for an optimisation to the aspect transaction's Get operation. It caches a copy of the transaction's working databag so that a new one doesn't have to be created and all the deltas re-applied to answer new Get operations. It also keeps track of which deltas were applied to the bag, so that only new changes are applied in subsequent Gets.
=> aspects: optimise aspect transaction Get()

CODING.md, CONTRIBUTING.md
as we use rebase now to merge ideally all the commit from branches should follow the expected format
=> CODING.md,CONTRIBUTING.md: describe expected format of commit messages

tests/core/system-snap-refresh/task.yaml
=> tests/core/system-snap-refresh: fix test after restart logic changes

daemon/api_snaps.go, daemon/api_snaps_test.go, tests/main/install-remove-multi/task.yaml
For context: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/2030941
=> daemon: enable --purge on multi-snap remove

daemon/api_debug.go, gadget/export_test.go, gadget/gadget.go, gadget/gadget_test.go, gadget/gadgettest/gadgettest.go, gadget/install/encrypt.go, gadget/install/encrypt_test.go, gadget/install/export_test.go, gadget/install/install.go, gadget/install/install_dummy.go, gadget/install/install_test.go, gadget/install/partition.go, gadget/install/partition_test.go, gadget/layout.go, gadget/layout_test.go, gadget/ondisk.go, gadget/ondisk_test.go, gadget/partial.go, gadget/partial_test.go, gadget/update.go, overlord/devicestate/devicestate_install_api_test.go, overlord/devicestate/export_test.go, overlord/devicestate/handlers_install.go, tests/lib/muinstaller/go.mod, tests/lib/muinstaller/go.sum, tests/lib/muinstaller/main.go
Use laid out types only for writing content on installations and factory reset.
=> many: use laid out types only for writing content

gadget/install/partition_test.go
This fixes failing static static-checks.
Relevant PR: https://github.com/snapcore/snapd/pull/13019
=> gadget/install/partition_test: remove unused asOffsetPtr function

NEWS.md, packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
Merge changelog back into master.
Note this should be merged via a "merge commit".
=> release: 2.60.2 (#13063)

osutil/kcmdline/kcmdline.go, osutil/kcmdline/kcmdline_test.go
Needed for https://github.com/canonical/ubuntu-image/pull/136
=> osutil/kcmdline: provide marshalers for ArgumentPattern

sandbox/apparmor/notify/ioctl.go, sandbox/apparmor/notify/ioctl_test.go
The IoctlRequestBuffer is just a type alias for a []byte so the helpers to get the bytes or the len from it is so trivial it can be removed.
=> apparmor/notify: remove IoctlRequestBuffer.{Bytes,Len}()

NEWS.md, packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
=> release: 2.60.4

NEWS.md, packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
Merge the changelog back into the main branch. 
This should be merged via a "merge" commit.
=> release: 2.60.4 (#13200)

overlord/snapstate/snapstate.go
Taskset `ts` created at the top of `doInstall` is not required within that scope. It is always empty at the point where it is chained and added to taskset `installSet`, therefore superfluous.
This is part of the larger task to modify firstboot task order for pre/seeding. These changes are done separately to simplify review before more complicated changes in this file.
=> overlord/snapstate: simplify install taskset construction

tests/nested/manual/uc-update-assets-secure/task.yaml
This should only be in seed partition.
=> tests/nested/manual/uc-update-assets-secure: do not check for shim in boot

interfaces/builtin/README.md, interfaces/builtin/common.go, interfaces/core.go, interfaces/policy/basedeclaration.go
incorporate into it and update the patterns described in basedeclaration.go
have a few relevant doc comments point to it
=> interfaces: review and extend README.md

aspects/schema.go, aspects/schema_test.go
Adds support for an "any" type that accepts data from any other type (e.g., int, strings, etc) except for the null value. This can be used in maps as the value of keys that are expected to be present but without a particular type.
=> aspects: support 'any' type in aspect schemas

boot/makebootable.go, boot/makebootable_test.go, boot/seal.go, boot/seal_test.go, overlord/devicestate/handlers_install.go
Same as #13171 but after #13185 was merged.
=> boot: unlock snapd state when sealing keys

aspects/schema.go, aspects/schema_test.go
Adds support for booleans in aspect schemas.
=> aspects: support boolean type in aspect schemas

boot/boot.go, boot/boot_test.go, boot/cmdline.go, boot/cmdline_test.go, boot/makebootable.go, boot/seal.go, boot/seal_test.go, bootloader/bootloader.go, bootloader/grub.go, gadget/gadget.go, gadget/gadget_test.go, gadget/kcmdline_test.go, osutil/kcmdline/kcmdline.go, tests/nested/manual/cmdline-remove-append/task.yaml
=> gadget: add kernel command-line remove filter and append to gadget yaml

NEWS.md, packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
changelogs for [release 2.61.1](https://github.com/snapcore/snapd/pull/13366)
=> release: 2.61.1

tests/main/catalog-update/task.yaml, tests/main/cgroup-devices-v1/task.yaml, tests/main/cgroup-devices-v2/task.yaml, tests/main/change-errors/task.yaml, tests/main/chattr/task.yaml, tests/main/classic-confinement-not-supported/task.yaml, tests/main/classic-confinement/task.yaml, tests/main/classic-custom-device-reg/task.yaml, tests/main/cmdline/task.yaml, tests/main/docker-smoke/task.yaml, tests/main/interfaces-accounts-service/task.yaml, tests/main/interfaces-browser-support/task.yaml
This is needed to improve the spread tests documentation.
=> tests: add details to spread tests - part-3

aspects/schema.go, aspects/schema_test.go
Improve handling of array indexes in validation errors paths. Build error with typed parts so we can inspect them on creating the error message and handle indexes specially. e.g., instead of `foo.[1].bar`, do `foo[1].bar`.
=> aspects: improve array index handling in validation errors

aspects/schema.go, aspects/schema_test.go
Improve errors caused by unexpected types when validating against the schema.
=> aspects: improve errors caused by unexpected types

NEWS.md, overlord/snapstate/backend.go, overlord/snapstate/backend/backend_test.go, overlord/snapstate/backend/setup.go, overlord/snapstate/backend/setup_test.go, overlord/snapstate/backend_test.go, overlord/snapstate/component.go, overlord/snapstate/component_install_test.go, overlord/snapstate/component_test.go, overlord/snapstate/export_test.go, overlord/snapstate/handlers_components.go, overlord/snapstate/handlers_components_mount_test.go, overlord/snapstate/handlers_components_prepare_test.go, overlord/snapstate/snapmgr.go, snap/component.go, snap/component_test.go, snap/snaptest/snaptest.go
Add first needed handlers for components: mount/unmount/prepare.
=> many: add mount/unmount/prepare handlers for components

overlord/snapstate/component_install_test.go, overlord/snapstate/component_test.go, overlord/snapstate/handlers_components.go, overlord/snapstate/handlers_components_link_test.go, overlord/snapstate/snapmgr.go, overlord/snapstate/snapstate_test.go
=> o/snapstate: add handlers to link/unlink components

cmd/snaplock/runinhibit/export_test.go, cmd/snaplock/runinhibit/inhibit.go, cmd/snaplock/runinhibit/inhibit_test.go
This PR is a building block for https://github.com/snapcore/snapd/pull/13411 in an attempt to split it into smaller chuncks.
This helper will be later used in "snap run" to make it aware of inhibited snaps.
=> cmd/snaplock/runinhibit: add WaitWhileInhibited helper function

overlord/managers_test.go, overlord/snapstate/snapstate.go, overlord/snapstate/snapstate_test.go
This return parameter will be used during the creation of recovery systems. The prereq tracker could be used for the same purpose, but this might be a little more general purpose?
=> snapstate, overlord: add snap.Info to snapstate.Download return values

interfaces/builtin/u2f_devices.go
Add the new Google Titan v2 security key
```Bus 005 Device 006: ID 18d1:9470 Google Inc. Titan Security Key v2```
=> interfaces/builtin: add google titan v2 to u2f-devices interface

cmd/snap/cmd_snap_op.go, daemon/api.go, daemon/api_base_test.go, daemon/api_sideload_n_try.go, daemon/api_sideload_n_try_test.go, daemon/errors.go, daemon/errors_test.go, daemon/export_test.go, overlord/snapstate/component.go, overlord/snapstate/component_install_test.go, tests/main/component/comp1/meta/component.yaml, tests/main/component/snap-with-comps/meta/snap.yaml, tests/main/component/snap-with-comps/test, tests/main/component/task.yaml
Support sideloading components in snapd API and by snap command. Add spread test for this.
=> many: support sideloading components

sandbox/cgroup/tracking.go, sandbox/cgroup/tracking_test.go
`ConfirmSystemdAppTracking` can be used if the process is a member of an existing transient scope to avoid leaking cgroups in case of retries.
This PR is a building block for https://github.com/snapcore/snapd/pull/13411 in an attempt to split it into smaller chunks.
This will be later used in "snap run" to make it aware of inhibited snaps.
=> sandbox/cgroup: add tracking helper to confirm transient scopes

cmd/snap-confine/PORTING, daemon/daemon.go, interfaces/apparmor/backend.go, interfaces/apparmor/backend_test.go, overlord/snapstate/policy/base.go, overlord/snapstate/policy/canremove_test.go, overlord/snapstate/policy/errors.go, overlord/snapstate/policy/export_test.go, overlord/snapstate/policy/gadget.go, overlord/snapstate/policy/kernel.go, overlord/snapstate/policy/os.go, overlord/snapstate/policy/policy.go, overlord/snapstate/policy/snapd.go
Typos I've ran across while looking at the code last week.
=> many: assorted typos

snap/naming/wellknown.go
this is mainly used by the assertion model code
=> naming: add well-known core24 snap-id

asserts/aspect_bundle.go, asserts/aspect_bundle_test.go, asserts/asserts.go, asserts/asserts_test.go
this holds configuration aspects' defintions
=> asserts: define new aspect-bundle assertion

seed/seed20.go
I didn't catch this in the original PR
=> seed: change termilogy for the copy timings for consistency

client/model.go, client/model_test.go, cmd/snap/cmd_remodel.go, cmd/snap/cmd_remodel_test.go, daemon/api_model.go, daemon/api_model_test.go, daemon/export_api_model_test.go, overlord/devicestate/devicestate.go, overlord/devicestate/devicestate_remodel_test.go, overlord/devicestate/handlers_remodel.go, overlord/managers_test.go, overlord/snapstate/snapstate.go, overlord/snapstate/snapstatetest/snapstate.go, snap/errors.go, snap/errors_test.go, tests/nested/manual/remodel-offline/task.yaml
This PR backports #13494 and #13507. #13553 is a prerequisite for merging this PR.
=> o/devicestate, overlord, daemon: backport offline remodel

overlord/devicestate/devicemgr.go, overlord/devicestate/devicestate_install_api_test.go, overlord/devicestate/handlers_install.go, tests/lib/muinstaller/main.go, tests/nested/manual/muinstaller-core/task.yaml
Copy the seed on Ubuntu Core installations.
=> o/devicestate: copy seed on finish install API call, for UC

NEWS.md, packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
Changelogs for [release: 2.61.2](https://github.com/snapcore/snapd/pull/13607).
Please use “merge” to merge it.
=> release: 2.61.2

tests/lib/prepare.sh
This reverts commit 1bc83c65d8a2e03847a52dc132c6a605104daf2c.
=> revert: "tests: install ubuntu image snap to build uc18 and uc2* (#12891)"

kernel/kernel_drivers.go, kernel/kernel_drivers_test.go, osutil/rename.go, osutil/rename_darwin.go, osutil/rename_linux.go, osutil/rename_linux_test.go, overlord/snapstate/backend/setup.go
=> kernel,overlord: modify EnsureKernelDriversTree so it can handle

kernel/kernel_drivers.go, overlord/devicestate/handlers.go, overlord/snapstate/backend/setup.go
=> kernel,overlord: use function from kernel pkg to get kernel early

aspects/aspects.go, aspects/aspects_test.go
Adds support for "content" rules that can be used to extend the rules in which they're nested. This is intended to be syntactic sugar equivalent to help write nested rules without having to repeat the parent prefix. Using the content rule is equivalent to adding a new rule with the prefix of the parent's request and storage plus whatever is in the content rule's own request and storage. These rules can also have access modes that are different than the rules that contain them.
=> aspects: support content sub-rules

NEWS.md, packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
Changelogs for https://github.com/snapcore/snapd/pull/13671
Please use “merge” to merge it.
=> release: 2.61.3

cmd/snap/cmd_run_test.go, osutil/strace/strace.go, osutil/strace/strace_test.go, tests/main/snap-run/task.yaml
This is a re-base of https://github.com/snapcore/snapd/pull/13180
I didn't want to force-push to the original branch.
=> strace: add support for --uid/--gid using strace-static

tests/lib/nested.sh
Consider the case then the log is not growing but the ssh can be stablished. In that case the log checks should return.
=> tests: make more robust the nested log checks

interfaces/builtin/u2f_devices.go, interfaces/builtin/u2f_devices_test.go
=> interfaces/builtin: add TrustKey G310H

CODING.md, CONTRIBUTING.md
Add merge guideline to coding policy (Riga internal discussion action)
=> coding policy: cover merge types and preference

NEWS.md, gadget/gadget.go, gadget/gadget_test.go, packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog, sandbox/apparmor/apparmor.go, tests/nested/manual/recovery-system-reboot/task.yaml
This is a duplicate of https://github.com/snapcore/snapd/pull/13731 that was accidentally squash merged instead of rebase-merged.
=> release: 2.62

overlord/snapstate/handlers_components.go, overlord/snapstate/handlers_components_prepare_test.go
=> o/snapstate: make sure new local installation get always a new

spread.yaml, tests/lib/pkgdb.sh
Change how we install snapd from proposed since mantic. 
Also update the sru systems list
=> tests: update sru validation process

tests/lib/reset.sh
The reset code runs purge, but give how purge works, it may happen that there are unexpected snap units. Specifically, lxd tends to start snap.lxd.workaround.service unit directly through systemd-run, which is not known to snapd and thus will not be stopped during purge.
```
+ systemctl --plain --no-legend --full
+ grep -E 'snap\..*\.(service|timer|socket)'
snap.lxd.workaround.service                                                                  loaded active exited    /bin/true
+ echo 'found unexpected leftovers'
found unexpected leftovers
+ exit 1
```
=> tests/lib/reset: try to identify unexpected snap units still present after purge

tests/nested/manual/run-spread/task.yaml
Ths is needed to re-exec failed tests on beta validation
=> tests: fix run-spread test to allow running multiple tests on custom variant

timeutil/synchronized_test.go
Exported object is running in a separate goroutine, accesses to fields need to by synchronized.
```
Read at 0x00c000536430 by goroutine 36:
github.com/snapcore/snapd/timeutil_test.timedate1Api.Get()
/home/maciek/work/canonical/snapd/timeutil/synchronized_test.go:87 +0x126
runtime.call64()
/usr/lib/go/src/runtime/asm_amd64.s:772 +0x42
/usr/lib/go/src/reflect/value.go:380 +0xb5
github.com/godbus/dbus.exportedMethod.Call()
/home/maciek/work/canonical/snapd/vendor/github.com/godbus/dbus/default_handler.go:128 +0x219
github.com/godbus/dbus.(*exportedMethod).Call()
<autogenerated>:1 +0x84
github.com/godbus/dbus.(*Conn).handleCall()
/home/maciek/work/canonical/snapd/vendor/github.com/godbus/dbus/export.go:153 +0x591 …
```
=> timeutil: fix data race in unit tests

desktop/portal/document_test.go
go test -race found a data race accessing fields of a mock service running asynchronously in a goroutine and the test
```
Read at 0x00c00021a078 by goroutine 23:
github.com/snapcore/snapd/desktop/portal_test.(*documentPortalSuite).TestGetMountPointResponseError()
/home/maciek/work/canonical/snapd/desktop/portal/document_test.go:124 +0x531
/usr/lib/go/src/runtime/asm_amd64.s:770 +0x42
/usr/lib/go/src/reflect/value.go:380 +0xb5
/home/maciek/work/canonical/snapd/vendor/gopkg.in/check.v1/check.go:775 +0x9c5
gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1()
/home/maciek/work/canonical/snapd/vendor/gopkg.in/check.v1/check.go:669 +0xe9
Previous write at 0x00c00021a078 …
```
=> desktop/portal: fix data race in unit tests

cmd/snap-bootstrap/triggerwatch/triggerwatch_test.go
go test -race complains about data race, which isn't entirely accurate as the goroutine which may modify the data has exited by the time checks are done. However, should we want to enable -race as part of the test suite, this fixes a blocker.
```
Read at 0x00c0000123a8 by goroutine 16:
github.com/snapcore/snapd/cmd/snap-bootstrap/triggerwatch_test.(*triggerwatchSuite).TestNoDevsWaitKeyTimeout()
/home/maciek/work/canonical/snapd/cmd/snap-bootstrap/triggerwatch/triggerwatch_test.go:118 +0x3e5
/usr/lib/go/src/runtime/asm_amd64.s:770 +0x42
/usr/lib/go/src/reflect/value.go:380 +0xb5
/home/maciek/work/canonical/snapd/vendor/gopkg.in/check.v1/check.go:775 +0x9c5 …
```
=> cmd/snap-bootstrap/triggerwatch: fix data race in tests

overlord/snapshotstate/backend/backend.go
The `NewSnapshotExport` function sets the finalizer to call `Close()` on the newly-created `SnapshotExport` insteance. This behavior was introduced in commit 03135412a526ea26a84bf805f4a3d7c296515feb.
Calling `Close()` closes all of the snapshot file FDs. However, the `StreamTo()` function may be reading from one of the snapshot files after the last reference to the snapshot export instance. Thus, the finalizer might be called while that read is still occurring or about to happen, thus causing read errors because the FD is closed.
This caused the `TestExportTwice` test to fail intermittently, if the garbage collector happened to run at just the right moment.
This commit fixes the issue at hand by adding a `runtime.KeepAlive` on the snapshot export instance after all the reads of the …
=> o/snapshotstate/backend: delay finalizer call during StreamTo

tests/core/apt/task.yaml, tests/core/backlight/task.yaml, tests/core/bash-completion/task.yaml, tests/core/basic18/task.yaml, tests/core/classic-snap16/task.yaml, tests/core/compat/task.yaml, tests/core/config-defaults-once/task.yaml, tests/core/core-dump/task.yaml, tests/core/core-to-snapd-failover16/task.yaml, tests/core/create-user-2/task.yaml, tests/core/create-user/task.yaml, tests/core/custom-device-reg-extras/task.yaml, tests/core/custom-device-reg/task.yaml, tests/core/dbus-activation/task.yaml, tests/core/desktop-files/task.yaml, tests/core/device-reg/task.yaml, tests/core/fan/task.yaml, tests/core/gadget-config-defaults-to-snaps/task.yaml, tests/core/gadget-config-defaults-vitality/task.yaml, tests/core/gadget-kernel-refs-update-pc/task.yaml, tests/core/generic-device-reg/task.yaml, tests/core/grub-no-unpacked-assets/task.yaml
First part of test updates. The second part will complete all the tests in core suite
=> tests: adding details to tests in core suite - part 1

.github/workflows/nightly.yaml
The main fix in this change is the cobertura file path is updated
Also several shellcheck improvements are included
=> tests: improve nightly github workflow

seed/seed20.go
Make sure to stop the time span before returning job's outcome.
This was identified as a data race where the DeviceManager.ensureSeeded() would call seed20.LoadMeta(), which internally loads seed meta and launches load-meta jobs. When exuction goes back to in ensureSeeded(), the timings would be saved to state, which causes flattening of all time spans. Since load-meta jobs were running, and the code in seed20.doLoadMeta() only synchronized with results from outcomeCh, there was no guarantee that TimeSpan.Stop() ran before we exited the function.
Backtrace from go test -race:
``` …
```
=>  seed: stop span before returning job outcome 

dbusutil/netplantest/netplantest.go, overlord/configstate/configcore/netplan_test.go
go test -race identified a data race when accessing mock netplan service, where
the exported object is accessed from a godbus goroutine and the test.
Example:
```
Read at 0x00c0003d0040 by goroutine 259:
github.com/godbus/dbus.(*Conn).sendError()
/home/maciek/work/canonical/snapd/vendor/github.com/godbus/dbus/conn.go:482 +0x6cf
github.com/godbus/dbus.(*Conn).handleCall()
/home/maciek/work/canonical/snapd/vendor/github.com/godbus/dbus/export.go:155 +0x9dc
github.com/godbus/dbus.(*Conn).inWorker.gowrap1()
/home/maciek/work/canonical/snapd/vendor/github.com/godbus/dbus/conn.go:334 +0x44
Previous write at 0x00c0003d0040 by goroutine 252:
github.com/snapcore/snapd/desktop/notification_test.(*gtkSuite).TestSendNotificationError() …
```
=> o/configstate/configcore, dbusutil/netplantest: fix data races in unit tests

desktop/notification/notificationtest/gtk.go
Fix data races identified by go test -race caused by manipulation of fields of an exported dbus object.
```
Read at 0x00c0003f0fd0 by goroutine 191:
github.com/godbus/dbus.(*Conn).sendError()
/home/maciek/work/canonical/snapd/vendor/github.com/godbus/dbus/conn.go:482 +0x6cf
github.com/godbus/dbus.(*Conn).handleCall()
/home/maciek/work/canonical/snapd/vendor/github.com/godbus/dbus/export.go:155 +0x9dc
github.com/godbus/dbus.(*Conn).inWorker.gowrap1()
/home/maciek/work/canonical/snapd/vendor/github.com/godbus/dbus/conn.go:334 +0x44
Previous write at 0x00c0003f0fd0 by goroutine 182:
github.com/snapcore/snapd/desktop/notification_test.(*gtkSuite).TestCloseNotificationError()
/home/maciek/work/canonical/snapd/desktop/notification/gtk_test.go:108 +0x224 …
```
=> desktop/notification/notificationtest: fix data races in gtk mocks

tests/upgrade/basic/task.yaml, tests/upgrade/selinux-relabel/task.yaml
Just two to see how the process feels like and how to make it not hog up all the CI resources.
=> tests: add details to upgrade tests

usersession/agent/rest_api.go, usersession/agent/rest_api_test.go
Some more primitives in order to improve handling of user-services in Start/StopService code inside wrappers.
=> usersession/agent: implement support for enable and disable functionality in service code

tests/core/kernel-base-gadget-single-reboot/task.yaml, tests/core/mem-cgroup-disabled/task.yaml, tests/core/netplan-cfg/task.yaml, tests/core/remodel-gadget/task.yaml, tests/core/remodel-kernel/task.yaml, tests/core/remodel/task.yaml, tests/core/remove-user/task.yaml, tests/core/snap-set-core-config/task.yaml, tests/core/snapd-refresh-vs-services-reboots/task.yaml, tests/core/snapd-refresh/task.yaml, tests/core/snapd16/task.yaml, tests/core/swapfiles/task.yaml, tests/core/system-settings/task.yaml, tests/core/tmp/task.yaml, tests/core/upgrade/task.yaml, tests/core/watchdog/task.yaml
=> tests: add details to a new set of tests - part 9

image/preseed/preseed_classic_test.go, image/preseed/preseed_linux.go, image/preseed/preseed_uc20_test.go
Needed by https://github.com/snapcore/snapd/pull/13370
=> snap-preseed: set symlink before calling snapd

tests/lib/tools/snaps-state, tests/main/fakestore-install/task.yaml, tests/main/interfaces-system-dbus/task.yaml, tests/main/refresh-classic/task.yaml, tests/main/security-apparmor/task.yaml, tests/main/services-stop-mode-sigkill/task.yaml, tests/main/services-stop-mode/task.yaml, tests/main/snap-set-core-w-no-core/task.yaml, tests/main/snapd-without-core/task.yaml
Add details to some spread tests.
=> tests: add details to some tests

tests/main/refresh-delta-from-core/task.yaml, tests/main/refresh-delta/task.yaml, tests/main/refresh-hold/task.yaml, tests/main/refresh-many-transactional-undo/task.yaml, tests/main/refresh-mode-ignore-running/task.yaml, tests/main/regression-home-snap-root-owned/task.yaml, tests/main/remove-errors/task.yaml, tests/main/retry-network/task.yaml, tests/main/revert-devmode/task.yaml, tests/main/revert-sideload/task.yaml, tests/main/searching/task.yaml, tests/main/snap-refresh-enforce/task.yaml, tests/main/snap-refresh-hold/task.yaml
Document the behavior of some spread tests in the details field.
=> tests: add details to more spread tests

tests/main/deb-restart-behavior/task.yaml, tests/main/debs/task.yaml, tests/main/debug-migrate-home/task.yaml, tests/main/debug-paths/task.yaml, tests/main/debug-pprof/task.yaml, tests/main/debug-sandbox/task.yaml, tests/main/default-tracks/task.yaml, tests/main/degraded/task.yaml, tests/main/econnreset/task.yaml, tests/main/enable-disable/task.yaml, tests/main/exitcodes/task.yaml, tests/main/generic-classic-reg/task.yaml, tests/main/health/task.yaml, tests/main/proxy-no-core/task.yaml, tests/main/proxy/task.yaml, tests/main/snap-validate-basic/task.yaml, tests/main/snap-validate-enforce/task.yaml, tests/main/snap-validate-with-store/task.yaml, tests/main/snap-wait/task.yaml
New set of spread tests with details
=> tests: more details in spread tests - part 13

tests/cross/go-build/task.yaml, tests/lib/external/snapd-testing-tools/tests/log-parser/task.yaml, tests/lib/external/snapd-testing-tools/tests/log-parser/with-debug-output.log.spread, tests/lib/external/snapd-testing-tools/tests/log-parser/with-error-output.log.spread, tests/lib/external/snapd-testing-tools/tests/remote.exec/task.yaml, tests/lib/external/snapd-testing-tools/tests/remote.retry/task.yaml, tests/lib/external/snapd-testing-tools/tests/snaps.name/task.yaml, tests/lib/external/snapd-testing-tools/tests/spread-manager/checks/task2/task.yaml, tests/lib/external/snapd-testing-tools/utils/log-parser, tests/lib/tools/suite/tests.invariant/task.yaml, tests/main/auto-aliases/task.yaml, tests/main/prepare-image-grub-core18/task.yaml, tests/main/prepare-image-grub/task.yaml, tests/main/prepare-image-reproducible/task.yaml, tests/main/prepare-image-uboot-uc20/task.yaml, tests/main/prepare-image-uboot/task.yaml, tests/main/prepare-image-validation-sets/task.yaml, tests/main/security-private-tmp/task.yaml, tests/main/snap-session-agent-socket-activation/task.yaml, tests/main/snap-session-agent-unavailable-to-snaps/task.yaml
=> tests: more details in spread tests - part 14

tests/main/retryable-error/task.yaml, tests/main/server-snap/task.yaml, tests/main/services-after-before-install/task.yaml, tests/main/services-disable-install-hook/task.yaml, tests/main/snap-confine-from-core/task.yaml, tests/main/snap-switch/task.yaml, tests/main/snapshot-basic/task.yaml
This is the last set of test details
=> tests: test details part 15

packaging/fedora/snapd.spec, spread.yaml
Cherry picks https://github.com/snapcore/snapd/pull/13910 and a fix for fakeroot
=> packaging, spread: do not pull in fakeroot, enable EPEL on CentOS 9, tweak RPM spec

cmd/snap-exec/main.go, cmd/snap-failure/main.go, cmd/snap-recovery-chooser/main.go, cmd/snap-repair/main.go, cmd/snap-update-ns/main.go, cmd/snap/main.go, cmd/snapd-apparmor/main.go, cmd/snapd/main.go, logger/logger.go, logger/logger_test.go, overlord/configstate/configcore/debug.go, overlord/configstate/configcore/debug_test.go, overlord/configstate/configcore/export_test.go, overlord/snapshotstate/backend/backend_test.go, sandbox/cgroup/monitor_test.go, tests/lib/fakestore/cmd/fakestore/main.go, tests/lib/uc20-create-partitions/main.go, tests/main/retry-network/detect-retry.go
when the option is set.
This depends on https://github.com/snapcore/snapd/pull/13893
=> o/configstate: enable logging for current snapd instance

seed/validate.go
=> chore: slice loop replace

sysconfig/cloudinit.go, sysconfig/cloudinit_test.go
This builds on (and replaces) https://github.com/snapcore/snapd/pull/13289 contributed by @holmanb. Rebased, fix conflict, and trimmed comment to be similar to existing.
=> sysconfig/cloudinit: check if disabled via kernel cmdline

overlord/snapstate/handlers.go, overlord/snapstate/snapstate_update_test.go
In hybrid systems, a split refresh can have an app that pulls in the default provider along with other essential snaps (kernel, base, etc). If the default provider depends on the model base, we need to set up an explicit dependency between the two (since the base is used to run
hooks, it must be available before the default provider). The app with the plug can't wait to auto-connect the default provider since it will be refreshed after the reboot.
This is based on https://github.com/snapcore/snapd/pull/13955 so only 73bc9ac8ce9934a214eabaa97f46c8e0e5ed17e9 is relevant
=> o/snapstate: don't wait for def provider if it depends on base in split refresh

.github/workflows/test.yaml, spread.yaml
Start adding 24.10 as ubuntu-daily
=> spread, github: add Ubuntu 24.10

tests/nested/manual/muinstaller-core/task.yaml, tests/nested/manual/muinstaller/task.yaml
=> tests/muinstaller{,-core}: use variable for core version

sandbox/apparmor/apparmor_test.go
The test was particularly expensive as it was testing all the combination of known parser features, 2**N, with an entirely mocked parser written in shell.
Replace the test with a per-feature probe detector, a checker for all the recognized features and separate smaller tests for not having any parser and for using the internal parser.
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-21937
=> sandbox/apparmor: refactor parser feature test

overlord/configstate/configcore/vitality.go, overlord/servicestate/quota_handlers.go, overlord/servicestate/service_control.go, overlord/snapstate/backend/link.go, wrappers/services.go, wrappers/services_test.go
Performs a rename from Flags to Options in wrappers/services.go for Start/Stop/Restart
=> overlord,wrappers: rename Start/Restart/StopServicesFlags to Start/Restart/StopServiceOptions

spread.yaml
The uploads are marginally smaller.
=> spread: bump snapd tag used for reference when generating deltas

.github/workflows/test.yaml
=> github: fix unit tests on openSUSE

daemon/api.go, daemon/api_snaps.go, daemon/api_snaps_test.go, daemon/export_test.go, overlord/snapstate/component.go, overlord/snapstate/component_install_test.go, overlord/snapstate/component_remove_test.go, overlord/snapstate/handlers_components.go, overlord/snapstate/sequence/sequence.go, overlord/snapstate/sequence/sequence_test.go, overlord/snapstate/snapmgr.go, overlord/snapstate/snapstate.go, snap/errors.go, snap/errors_test.go
This PR add support to remove components:
* API changes
* Functions to create the tasks
The cli part is missing though.
=> many: add support to remove components

cmd/snap/cmd_download.go, image/image_linux.go, seed/seedtest/seedtest.go, store/store_action.go, store/store_action_test.go, store/tooling/tooling.go, store/tooling/tooling_test.go
This has been split out from https://github.com/snapcore/snapd/pull/14181.
=> many: add support for downloading components to store tooling

interfaces/builtin/steam_support.go, interfaces/builtin/steam_support_test.go, sandbox/apparmor/apparmor.go, sandbox/apparmor/apparmor_test.go
Reverts snapcore/snapd#14216 based on https://github.com/snapcore/snapd/pull/14216#pullrequestreview-2190444972
=> Revert "interfaces: adjust steam to allow all apparmor permissions"

interfaces/builtin/steam_support.go, interfaces/builtin/steam_support_test.go, sandbox/apparmor/apparmor.go, sandbox/apparmor/apparmor_test.go
Reverts snapcore/snapd#14221 which was merged by accident
=> Revert "interfaces,sandbox: transition steam to permissive apparmor profile"

tests/main/microk8s-smoke/task.yaml
This is a fix for the microk8s-smoke test in openstack environment
=> tests: fix microk8s-smoke test when the proxy is configured

strutil/version_test.go
Add a unit test with a sample of version compare taken from the spread tests.
=> strutil: add unit test with version compare sample from CI tests

.woke.yaml, build-aux/snap/local/apparmor/af_names.h, build-aux/snap/local/apparmor/apparmor-parser-fix-protocol-error-on-older-kernels-caused-by.patch, build-aux/snap/local/apparmor/parser-add-support-for-prompting.patch, build-aux/snap/snapcraft.yaml, cmd/configure.ac, run-checks
=> build-aux/snap: update vendored apparmor to latest 4.0.2 release

cmd/snap/cmd_snap_op.go, cmd/snap/cmd_snap_op_test.go, cmd/snap/export_test.go, overlord/hookstate/ctlcmd/export_test.go, overlord/hookstate/ctlcmd/helpers.go, overlord/hookstate/ctlcmd/install.go, overlord/hookstate/ctlcmd/remove.go, overlord/hookstate/ctlcmd/snap_management_test.go, overlord/snapstate/component.go, overlord/snapstate/component_remove_test.go, snap/info.go, snap/info_test.go, tests/lib/snaps/test-snap-components-snapctl/dump/one-hooks/install, tests/lib/snaps/test-snap-components-snapctl/dump/one-hooks/post-refresh, tests/lib/snaps/test-snap-components-snapctl/dump/test, tests/lib/snaps/test-snap-components-snapctl/dump/two-hooks/install, tests/lib/snaps/test-snap-components-snapctl/dump/two-hooks/post-refresh, tests/lib/snaps/test-snap-components-snapctl/snap/hooks/configure, tests/lib/snaps/test-snap-components-snapctl/snapcraft.yaml, tests/main/component-snapctl/task.yaml
Depends on https://github.com/snapcore/snapd/pull/14260
=> o/hookstate: add snapctl install and remove commands

boot/boot_test.go, bootloader/bootloadertest/bootloadertest.go
=> boot/boot_test.go: fix tests with multiple kernels

boot/bootchain.go, boot/export_test.go, boot/seal.go, boot/seal_test.go, overlord/fdestate/backend/reseal_test.go
Part 2 of https://github.com/canonical/snapd/pull/14282
=> overlord/fdestate/backend: add basic test for resealing

interfaces/builtin/lxd_support.go
Similarly to the recent changes to the steam-support interface in #14229, the
lxd-support interface also needs to support an essentially unconfined LXD by
giving it all the possible permissions. This was previously done through the use
of the unconfined AppArmor profile mode, along with the userns,
permission. However, due to issues with apparmor_parser not correctly generating
all the required permissions when using the unconfined profile mode, it is
better to instead follow the same pattern as is now done in steam-support and
make use of the allow all, AppArmor parser feature/syntax when available, or to
fallback to generating a profile which includes all the possible permissions
when this is not available (as well as retaining the unconfined profile mode).
Signed-off-by: Alex Murray …
=> interfaces/lxd-support: add support for allow all in AppArmor

osutil/mountentry_linux.go, osutil/mountentry_linux_test.go
The 9p file system bugs strike again!
This is a variation of 3d72b032669cab29fdf639bc32894ac258825fa4 (osutil: fix parsing super-block options with spaces) but for /proc/PID/mounts.
The problem is somewhat worse here, as unlike /proc/self/mountinfo, the mount profile parser is used to load both /etc/fstab as well as /proc/{,PID/}mounts. In the former case it is technically allowed to omit the last several fields (options and two numbers) but in the latter case they are always emitted.
The problem is somewhat unsolvable, as the format never expected to handle any fields with unescaped spaces. We pick a pragmatic approach that is certainly valid but not the only way to parse a mount entry.
In other news, in 2024 Linux still cannot handle text formats without running into Johnny Tables …
=> osutil: fix parsing /proc/PID/mounts with spaces

tests/main/snap-quota-thread/task.yaml
Use for to iterate instead of until with (( n++ )) which is making bash to fail.
=> tests: fix snap-quota-thread test

interfaces/builtin/lxd_support_test.go
also add a "allow all" test as there wasn't one afaict
=> i/builtin: mock apparmor consistently for the tests

daemon/api.go, daemon/api_prompting.go, daemon/api_prompting_test.go, daemon/export_api_prompting_test.go, interfaces/prompting/prompting.go, interfaces/prompting/requestprompts/requestprompts.go, interfaces/prompting/requestprompts/requestprompts_test.go, overlord/ifacestate/apparmorprompting/prompting.go, overlord/ifacestate/ifacemgr.go, overlord/ifacestate/ifacestate_test.go, tests/main/interfaces-snap-interfaces-requests-control/task.yaml
Add AppArmor Prompting API endpoints.
This task is tracked internally by https://warthogs.atlassian.net/browse/SNAPDENG-10090
=> daemon: add prompting api

NEWS.md, cmd/snap-failure/cmd_snapd.go, cmd/snap-failure/cmd_snapd_test.go, cmd/snap-failure/export_test.go, cmd/snap-failure/main_test.go, dirs/dirs.go, overlord/configstate/configcore/coredump.go, overlord/configstate/configcore/coredump_test.go, overlord/configstate/configcore/export_test.go, overlord/configstate/configcore/handlers.go, overlord/configstate/configcore/proxy.go, overlord/configstate/configcore/proxy_test.go, overlord/ifacestate/apparmorprompting/prompting.go, overlord/ifacestate/apparmorprompting/prompting_test.go, packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog, tests/core/coredump-options/task.yaml, tests/core/snapd-failover/task.yaml, tests/main/apparmor-prompting-snapd-startup/task.yaml, tests/main/interfaces-opengl-nvidia/task.yaml, tests/main/nvidia-files/task.yaml
DEBEMAIL="Ernest Lotter <ernest.lotter@canonical.com>" release-tools/changelog.py 2.65 2077473 NEWS.md
Cherry-picked:
- https://github.com/canonical/snapd/pull/14379
- https://github.com/canonical/snapd/pull/14394
- https://github.com/canonical/snapd/pull/14274
- https://github.com/canonical/snapd/pull/14398
- https://github.com/canonical/snapd/pull/14405
**Requires rebase-merge**
=> release: 2.65

boot/assets_test.go, boot/boot_test.go, boot/model_test.go, boot/systems_test.go
=> boot: mock ResealKeyForBootChains instead of ResealKeys

interfaces/core.go
=> interfaces: removed json tags from StaticInfo

run-spread, spread.yaml, tests/build-test-snapd-snap, tests/lib/prepare.sh, tests/lib/state.sh, tests/main/apparmor-batch-reload/task.yaml, tests/main/apparmor-prompting-flag-restart/task.yaml, tests/main/apparmor-prompting-snapd-startup/task.yaml, tests/main/cifs-home/task.yaml, tests/main/debug-execution/task.yaml, tests/main/exitcodes/task.yaml, tests/main/interfaces-many-core-provided/task.yaml, tests/main/interfaces-requests-activates-handlers/task.yaml, tests/main/interfaces-snap-interfaces-requests-control/task.yaml, tests/main/mount-ns/google.ubuntu-18.04-64/HOST.expected.txt, tests/main/mount-ns/google.ubuntu-18.04-64/PER-SNAP-16.expected.txt, tests/main/mount-ns/google.ubuntu-18.04-64/PER-SNAP-18.expected.txt, tests/main/mount-ns/google.ubuntu-18.04-64/PER-SNAP-C7.expected.txt, tests/main/mount-ns/google.ubuntu-18.04-64/PER-USER-16.expected.txt, tests/main/mount-ns/google.ubuntu-18.04-64/PER-USER-18.expected.txt, tests/main/mount-ns/google.ubuntu-18.04-64/PER-USER-C7.expected.txt, tests/main/nfs-support/task.yaml, tests/main/remove-core/task.yaml, tests/main/snap-seccomp-blocks-tty-injection/task.yaml, tests/main/snap-userd-reexec/task.yaml, tests/main/snapd-reexec-snapd-snap/task.yaml, tests/main/snapd-reexec/task.yaml, tests/main/snapd-slow-startup/task.yaml, tests/main/snapd-snap-transition/task.yaml
For classics systems install built snapd snap during suite preparation step.
https://warthogs.atlassian.net/browse/SNAPDENG-26744
=> tests, run-spread: install snapd snap during classic system prepare

tests/main/exitcodes/task.yaml, tests/main/interfaces-snap-interfaces-requests-control/task.yaml
=> tests: followup fixes after landing snapd snap

run-spread, tests/lib/prepare.sh
More followup tweaks after landing snapd snap.
=> run-spread, tests/lib/prepare: more followup tweaks

tests/main/document-interfaces-url/task.yaml
- Add doc exclusion for newly added interface: https://github.com/canonical/snapd/commit/0ae8759db855a2f0618254eee49f80a5e43e2f09
- Also adjusted dates for all exclusions push for quicker doc corrections
=> tests/main/document-interfaces-url: added exclusion for nomad-support interface

interfaces/builtin/custom_device.go, interfaces/builtin/custom_device_test.go
There is an implicit assumption that the `kernel` entry in `udev-tagging` snippet matches the device path listed in devices. While this is often true for most devices, there are some where the kernel device is exposed under a completely different path under /dev, specifically msr[0-9], are exposed at /dev/cpu/0-9/msr, rather than /dev/msr[0-9]. Hence the implicit rules made it impossible to describe a device in a way which would result in the right access rules.
The branch introduces a new attribute `device` in in the `udev-tagging` snippets which allows to establish a match between said snippet and an actual device listed in `devices` section.
Related: SNAPDENG-26290
=> interfaces/builtin/custom-device: allow to explicitly identify matching device in udev tagging block

boot/export_test.go, boot/makebootable_test.go, boot/seal.go, boot/seal_test.go, overlord/fdestate/backend/backend.go, overlord/fdestate/backend/backend_test.go, overlord/fdestate/backend/export_test.go, overlord/fdestate/backend/reseal.go, overlord/fdestate/backend/reseal_test.go, overlord/fdestate/backend/seal.go, overlord/fdestate/backend/seal_test.go
=> boot: split sealing tests and move some to fdestate's backend

overlord/snapstate/handlers.go, overlord/snapstate/handlers_link_test.go
This avoids a maliciously crafted snap from somehow causing the termination logic to fail (even though we should be able to handle most scenarios even fork-bombs with the existing implementation) and hence causing the snap to never be removed.
=> o/snapstate: make kill-snap-apps best effort

NEWS.md, interfaces/builtin/content.go, interfaces/policy/basedeclaration_test.go, overlord/snapstate/snapstate_update_test.go, overlord/snapstate/storehelpers.go, packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog, sandbox/apparmor/apparmor.go, sandbox/apparmor/apparmor_test.go, tests/lib/pkgdb.sh, tests/main/refresh-amend/task.yaml
DEBEMAIL="Ernest Lotter [ernest.lotter@canonical.com](mailto:ernest.lotter@canonical.com)" release-tools/changelog.py 2.66.1 2083490 NEWS.md
Cherry-picked:
- https://github.com/canonical/snapd/pull/14593
- https://github.com/canonical/snapd/pull/14589
- https://github.com/canonical/snapd/pull/14613 (test fix)
SRU bug: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/2083490
JIRA: https://warthogs.atlassian.net/browse/SNAPDENG-32812
**Requires rebase merge**
=> release: 2.66.1

overlord/fdestate/export_test.go, overlord/fdestate/fdemgr_test.go
Cherry picks of small unit tests improvements from DBX branch.
=> overlord/fdestate: improve unit tests

.github/workflows/cla-check.yaml
=> github: enable required checks on FDE branch

.github/workflows/test.yaml
=> github: verbose snapcraft build, drop duplicate snap build step

store/store_download.go, store/store_download_test.go
When a file is rebuilt from delta, make sure it is added to the snap
blobs cache, such that subsequent download will be able to correctly
observe the file.
Related: [SNAPDENG-32332](https://warthogs.atlassian.net/browse/SNAPDENG-32332)
Based on https://github.com/canonical/snapd/pull/14524
[SNAPDENG-32332]: https://warthogs.atlassian.net/browse/SNAPDENG-32332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> store: place downloaded file in cache after rebuilding from delta

overlord/fdestate/backend/reseal.go, overlord/fdestate/backend/reseal_test.go
As per specification, we should populate the pcr profile for "run" only mode in the state. This will be needed later to add keys only working for "run".
See https://github.com/canonical/snapd/pull/14516#discussion_r1801380240
=> overlord/fdestate/backend/reseal.go: save run only boot chain in state

overlord/fdestate/fdemgr.go, overlord/fdestate/fdemgr_test.go, overlord/fdestate/fdestate.go, overlord/managers_test.go, secboot/secboot_dummy.go, secboot/secboot_sb.go
=> overlord/fdestate/fdestate.go: use HashAlg type from secboot

daemon/api.go, daemon/api_base_test.go, daemon/api_model.go, daemon/api_sideload_n_try.go, daemon/api_sideload_n_try_test.go, daemon/api_systems.go, daemon/export_test.go, overlord/snapstate/snapstate.go, tests/main/component-local-installs/comp-four/meta/component.yaml, tests/main/component-local-installs/comp-one/meta/component.yaml, tests/main/component-local-installs/comp-three/meta/component.yaml, tests/main/component-local-installs/comp-two/meta/component.yaml, tests/main/component-local-installs/task.yaml, tests/main/component-local-installs/test-snap-one/meta/snap.yaml, tests/main/component-local-installs/test-snap-one/test, tests/main/component-local-installs/test-snap-two/meta/snap.yaml, tests/main/component-local-installs/test-snap-two/test
This change allows us to mix components and snaps when installing from local files on the command line.
=> many: allow installing snaps and components from local files on the cli

.github/workflows/snap-builds.yaml, .github/workflows/spread-tests.yaml, .github/workflows/test.yaml
https://warthogs.atlassian.net/browse/SNAPDENG-31561
=> tests: Added arm github runner to build snapd

tests/lib/spread/backend.openstack.yaml
This is needed previous to the migration to openstack
=> tests: add new systems to openstack backend

overlord/fdestate/fdemgr_test.go, overlord/snapstate/conflict.go
Assorted minor tweaks cherry picked from https://github.com/canonical/snapd/pull/14615
Related: [SNAPDENG-32509](https://warthogs.atlassian.net/browse/SNAPDENG-32509)
[SNAPDENG-32509]: https://warthogs.atlassian.net/browse/SNAPDENG-32509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> overlord/fdestate, overlord/snapstate: tweak unit tests, capture logs, formatting

.github/workflows/unit-tests.yaml
This adds the go channel to the unit test coverage upload
=> tests: corrected unit test coverage upload name to include go channel

.github/actions/combine-results/action.yaml, .github/workflows/test.yaml
Proposal to address this concern: https://github.com/canonical/snapd/pull/14794#discussion_r1870891355
Alternative to https://github.com/canonical/snapd/pull/14794
=> .github/{workflows,actions}: expect branch static check skipped on master

tests/lib/fakestore/store/store.go, tests/lib/fakestore/store/store_test.go
This change will help us test features that works with revisions that aren't just the latest, like validation sets.
=> t/l/f/store: make the fake store aware of snap revisions

CODING.md
from recent discussions with team members
=> CODING.md: some tips about refactorings

daemon/api_model.go, daemon/api_model_test.go, daemon/api_sideload_n_try.go, daemon/api_sideload_n_try_test.go, daemon/api_systems.go, daemon/export_test.go, tests/main/component-sideload/task.yaml
This one enables us to sideload snaps and components at the same time.
=> daemon, tests/main/component-sideload: support sideloading multiple snaps and components at the same time

interfaces/builtin/fwupd.go
Fixes: Upstream issue: https://github.com/fwupd/fwupd/issues/8227
=> i/b/fwupd: allow access to dell bios recovery

tests/lib/fakestore/store/store.go
This makes requests run faster and overcome the 10s timeout that snap client has.
=> tests/lib/fakestore: cache analyzing of snaps

tests/nested/manual/uc-update-assets-secure-add-sbat/task.yaml
This is a cherry-pick of #14877 from master
=> tests: remove check for bootx64.efi in boot in uc-update-assets-secure-add-sbat

overlord/fdestate/fdestate.go
Some old kernels do not store keys in the keyring at all. Unfortunately, we do need an FDE state so that we can reseal, as resealing needs to save/retrieve the policies in/from the state.
=> overlord/fdestate: make primary keys in keyring optional

cmd/snap-confine/snap-confine.c
When snap-confine is executing inside container it doesn't do anything with devices but the order of checks is such, that the function sc_get_device_cgroup_setup is called unconditionally. Since the recent change to snapd udev backend, that function will fail to load the snap.$SNAP_NAME.device file when executing inside a container.
Re-arrange the order so that container check happens earlier.
=> cmd/snap-confine: fix order of container checks

.github/workflows/spread-tests.yaml
Add condition that only uploads test results if a test failed on that system
=> tests: only upload spread.json if at least one test has failed

NEWS.md, osutil/buildid.go, osutil/buildid_test.go, osutil/export_test.go, packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog
DEBEMAIL="Ernest Lotter [ernest.lotter@canonical.com](mailto:ernest.lotter@canonical.com)" release-tools/changelog.py 2.68 2098137 NEWS.md
Cherry picks:
- https://github.com/canonical/snapd/pull/15072
SRU Bug: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/2098137
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-34481
Requires rebase merge
=> release: 2.68

.github/workflows/cla-check.yaml
=> github/cla-check: update canonical/has-signed-canonical-cla action to v2

tests/lib/nested.sh, tests/nested/manual/run-spread/task.yaml, tests/perf/nested/install-many-snaps-no-wait/task.yaml, tests/perf/nested/install-many-snaps/task.yaml, tests/perf/nested/interfaces-many/task.yaml, tests/perf/nested/parallel-installs/task.yaml
This is an improvement to simplify the test results analysis on edge and beta validation
=> tests: make test fail when nested spread fails

NEWS.md, cmd/snap-fde-keymgr/main.go, packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog, packaging/ubuntu-16.04/rules, secboot/keymgr/export_test.go, secboot/keymgr/keymgr_luks2.go, secboot/keymgr/keymgr_luks2_test.go, spread.yaml, tests/core/snapd-refresh-undo/task.yaml, tests/main/aux-info/task.yaml, tests/main/snap-quota-services/task.yaml, tests/nested/manual/core20-remodel/task.yaml
DEBEMAIL="Ernest Lotter [ernest.lotter@canonical.com](mailto:ernest.lotter@canonical.com)" release-tools/changelog.py 2.68.3 2098137 NEWS.md
Cherry-picks:
Functional:
- https://github.com/canonical/snapd/pull/15167
- https://github.com/canonical/snapd/pull/15165
- https://github.com/canonical/snapd/pull/15157
Tests:
- https://github.com/canonical/snapd/pull/15173
- https://github.com/canonical/snapd/pull/15160
- https://github.com/canonical/snapd/pull/15159
- https://github.com/canonical/snapd/pull/15154
SRU Bug: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/2098137
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-34641
Requires rebase merge
=> release: 2.68.3

SECURITY.md
Add SECURITY.md as per SSDLC security management requirements v1.1
Spec:  [SEC0026 | SSDLC - Vulnerability Response](https://docs.google.com/document/d/1RolsiWCWhM-sVmHFjLt-Mq5yKcgQJ8GLXssGJREjSL0/edit?usp=sharing)
- [Template](https://docs.google.com/document/d/1wAO9ejAYcTpG76xwR822RZCnxfTMkf_caODWUL7BldE/edit?pli=1&tab=t.0)
- [LXD reference ](https://github.com/canonical/lxd/blob/main/SECURITY.md)
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-34604
=> docs: add security how-to

tests/lib/tools/simpleget
Fix progress reporting which got broken during previous refactor.
=> tests/lib/tools/simpleget: fix progress reporting

interfaces/system_key.go, interfaces/system_key_test.go
Return the 'generated' system key even when mismatch function returns an error.
Cherry picked from #15254 
=> interfaces/system_key: return generated system key on mismatch errors

cmd/snap-bootstrap/initramfs_systemd_mount.go, systemd/systemd.go
This leads to size improvements for this binary.
Usage of go templates was introduced in 4b21b922c432fa468b48c008d5a09abc61b7f263 (thanks @valentindavid for pointing to the exact place) - removing its usage improves size in ~4MB.
However, since the mentioned change was commited, text templates have been introduced in more places, including another function in snap-bootstrap (changed in this PR), and it is also pulled from secboot:
https://github.com/canonical/secboot/blob/master/auth_requestor_systemd.go#L72
A quick check reveals that this PR + removing the calls to `NewSystemdAuthRequestor` in the secboot package makes the 4MB improvement appear again, so the change in secboot would be needed too.
=> cmd,systemd: remove usage of go templates in snap-bootstrap

.github/workflows/unit-tests-cross-distro.yaml
Update the container before installing anything.
=> github/workflows/unit-tests-cross-distro: update before installing any build dependencies

client/system_key.go, client/system_key_test.go
Helper for requesting advice from snapd when a system-key mismatch is detected.
Cherry picked from #15254 
=> client: system key mismatch helpers

boot/flags.go, boot/unlocked_state.go, boot/unlocked_state_test.go, cmd/snap-bootstrap/cmd_initramfs_mounts.go, cmd/snap-bootstrap/cmd_initramfs_mounts_recover_degraded_test.go
This is in preparation to use this format in more places.
=> cmd/snap-bootstrap: extract type definition of degraded.json

cmd/snap-bootstrap/triggerwatch/export_test.go, cmd/snap-bootstrap/triggerwatch/triggerwatch.go, cmd/snap-bootstrap/triggerwatch/triggerwatch_test.go
LP: https://bugs.launchpad.net/snapd/+bug/2106121
=> cmd/snap-bootstrap/triggerwatch: fix busy loop

.github/workflows/rerun.yaml, .github/workflows/snap-builds.yaml, .github/workflows/spread-tests.yaml, .github/workflows/state-locks.yaml, .github/workflows/static-checks.yaml, .github/workflows/unit-tests-cross-distro.yaml, .github/workflows/unit-tests.yaml
Add names to workflows and also fix missing dependency for job create-reports.
=> tests: new dependency for state locks worflow

NEWS.md, cmd/snap-bootstrap/triggerwatch/export_test.go, cmd/snap-bootstrap/triggerwatch/triggerwatch.go, cmd/snap-bootstrap/triggerwatch/triggerwatch_test.go, overlord/fdestate/dbx.go, overlord/fdestate/dbx_test.go, packaging/arch/PKGBUILD, packaging/debian-sid/changelog, packaging/fedora/snapd.spec, packaging/opensuse/snapd.changes, packaging/opensuse/snapd.spec, packaging/ubuntu-14.04/changelog, packaging/ubuntu-16.04/changelog, tests/nested/manual/core20-nofde-dbx/task.yaml
`DEBEMAIL="Ernest Lotter <ernest.lotter@canonical.com>" release-tools/changelog.py 2.69 2105854 NEWS.md`
Cherry-picks:
Functional:
- https://github.com/canonical/snapd/pull/15287
- https://github.com/canonical/snapd/pull/15326
SRU Bug: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/2105854
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-34653
Before merge, first merge in 2.68.4 changelog
Requires rebase merge
=> release: 2.69

build-aux/snap/snapcraft.yaml
Build with libselinux, use a static library.
Related: [SNAPDENG-34260](https://warthogs.atlassian.net/browse/SNAPDENG-34260)
[SNAPDENG-34260]: https://warthogs.atlassian.net/browse/SNAPDENG-34260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> snapcraft: build with libselinux

sandbox/apparmor/notify/listener/export_test.go, sandbox/apparmor/notify/listener/listener.go
@maykathm spotted a race condition test failure in a CI run: https://github.com/canonical/snapd/actions/runs/14495650799/job/40663317986#step:13:1100
I think this was due to the lack of locking when getting the socket FD, which could race with the file being closed. This shouldn't actually change the return value of `notifyFile.Fd()`, but it's a data race nonetheless.
For good measure (and to avoid the assumption that closing a file doesn't change the return value of `Fd()`), make a small adjustment to `handleRequests()` as well, so that the socket FD is known to be from before `Close()` was potentially called.
=> s/a/n/listener: avoid race between closing/reading socket FD

tests/nested/core/core20-basic/task.yaml
The model name is not "pc" anymore.
=> tests/core20-basic: fix for uc22+

spread.yaml
Related: [SNAPDENG-34261](https://warthogs.atlassian.net/browse/SNAPDENG-34261)
[SNAPDENG-34261]: https://warthogs.atlassian.net/browse/SNAPDENG-34261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> spread: enable reexec test suite on Fedora

overlord/snapstate/handlers.go, overlord/snapstate/handlers_prereq_test.go, overlord/snapstate/snapstate.go, overlord/snapstate/snapstate_test.go
A deadlock occurs when a validation set enforcement results in these actions:
* a snap to be refreshed (not installed for the first time)
* that snap's base to be installed for the first time (not refreshed)
For some reason, validation set enforcement is written to require updates before installs. There is a comment calling it out, but not quite sure why. Assuming that is there for a reason, doing things in this order fixes the issue:
* Install all bases
* Update everything
* Install everything else
Bases are the issue, not other prerequisites. We don't block on those.
Forum: https://forum.snapcraft.io/t/validation-set-refresh-deadlock/46618/5
SF: [00409558] Validation set refresh hangs
=> o/snapstate: make sure that bases do not wait on snaps when enforcing validation sets

.codecov.yml, codecov.yml
=> codecov: add codecov config

.codecov.yml, .github/workflows/ci-master-push.yaml, .github/workflows/ci-test.yaml
=> github: specify coverage directory, disable search

.github/actions/download-install-debian-deps/action.yaml, .github/workflows/unit-tests.yaml, cmd/Makefile.am, cmd/configure.ac, cmd/libsnap-confine-private/fault-injection.c
Simplified version of https://github.com/canonical/snapd/pull/15048.
Related: [SNAPDENG-34327](https://warthogs.atlassian.net/browse/SNAPDENG-34327)
[SNAPDENG-34327]: https://warthogs.atlassian.net/browse/SNAPDENG-34327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> github: collect C code coverage

tests/main/nvidia-files/task.yaml
=> tests/main/nvidia-files: fix some test cases as the repos have changed

tests/core/interfaces-gpio-chardev/mk-sim-chips.sh, tests/core/interfaces-gpio-chardev/rm-sim-chips.sh, tests/core/interfaces-gpio-chardev/task.yaml, tests/lib/snaps/store/test-snapd-gpio-chardev/bin/cmd, tests/lib/snaps/store/test-snapd-gpio-chardev/bin/service.sh, tests/lib/snaps/store/test-snapd-gpio-chardev/snapcraft.yaml
=> tests: add test for the gpio-chardev interface

spread.yaml
Also it is included the new environment for arm64.
Tests are not executed as the env vars are not deployed yet.
=> tests: add new env vars to support more openstack environments

overlord/confdbstate/confdbstate.go, overlord/confdbstate/confdbstate_test.go
If a change to load confdb data fails (for instance, because a hook failed) we need to remove it from the ongoing transaction state, as we already do for the confdb writes.
=> o/confdbstate: clear tx state on failed load

tests/main/interfaces-requests-activates-handlers/task.yaml, tests/main/layout-symlink-bind-revert/task.yaml
Add missing unset of experimental feature
=> tests: unset experimental user-daemons

tests/main/cgroup-tracking-failure/task.yaml, tests/main/component-refresh-and-revert/task.yaml
These are 2 test fixes required after beta validation. Those tests are currently failing in some arm devices.
=> tests: fix tests executed in arm devices

.github/workflows/data-fundamental-systems.json, .github/workflows/data-non-fundamental-systems.json, spread.yaml, tests/lib/prepare.sh, tests/main/lxd-mount-units/task.yaml, tests/main/lxd-postrm-purge/task.yaml, tests/main/lxd-snapfuse/task.yaml, tests/main/lxd-try/task.yaml, tests/main/lxd/task.yaml, tests/main/microk8s-smoke/task.yaml, tests/main/upgrade-from-release/task.yaml
=> github: move 25.04 to interim, add 25.10 daily

.github/labeler.yml
Update configuration to match what is expected for v5 according to the documentation at https://github.com/actions/labeler
=> github/labeler: fix configuration

overlord/fdestate/dbx_test.go
Fix races in DBX update unit tests which were caused by progressing too fast without waiting for a well known state to be reached first.
Related: [SNAPDENG-35124](https://warthogs.atlassian.net/browse/SNAPDENG-35124)
[SNAPDENG-35124]: https://warthogs.atlassian.net/browse/SNAPDENG-35124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> o/fdestate: fix races in DBX update unit tests

cmd/snap-confine/group-policy-test.c, cmd/snap-confine/group-policy.c
=> cmd/snap-confine: improve error handling in group policy

.image-garden.mk, spread.yaml
This doesn't really work yet but will allow us to start working on the policy package for openSUSE systems.
=> spread: add support for openSUSE Tumblweed with SELinux

tests/main/snap-run/task.yaml
=> tests: add journal output to head of stderr instead of end during feature tagging

tests/nested/manual/passphrase-support-on-hybrid/task.yaml
=> tests: extend passphrase-support-on-hybrid to test changing passphrases

tests/lib/assertions/developer1-network-ephemeral-confdb.json, tests/lib/assertions/network-ephemeral.confdb, tests/main/confdb-cross-config/eph-schema.json
This extends the confdb-cross-config spread test to cover aliases
=> tests: cover aliases in confdb spread test

overlord/managers_test.go
Rather than accidentally hitting example.com...
=> overlord: set up a test http server to serve snap icons

run-checks, tests/unit/go/task.yaml
=> tests/unit: set nooptee build tag for all arm unit tests

cmd/snap/cmd_help.go, cmd/snap/cmd_help_test.go
the last category contents was displayed instead
improve the tests so this would have been caught
=> c/snap: fix Development category in the short help

.github/workflows/data-fundamental-systems.json, spread.yaml, tests/lib/prepare.sh
Migrate:
ubuntu-20.04-64
ubuntu-24.04-64
ubuntu-core-20
ubuntu-core-24
=> tests: migrate ubuntu systems from google to openstack-ps7

.github/workflows/weekly-feature-tagging.yaml
The nested tests are actually core tests and should be considered as such for feature coverage results
=> github: merge the nested test results into the corresponding core results file during feature tagging

tests/nested/manual/build-with-kernel-modules-components/task.yaml, tests/nested/manual/core20-fault-inject-on-install-component/task.yaml, tests/nested/manual/core20-fault-inject-on-update-config/task.yaml, tests/nested/manual/hybrid-fde-dbx/task.yaml, tests/nested/manual/hybrid-fde-recovery-keys/task.yaml, tests/nested/manual/hybrid-remodel/task.yaml, tests/nested/manual/kernel-modules-components/task.yaml, tests/nested/manual/muinstaller-core/task.yaml, tests/nested/manual/muinstaller-oldbasenewkernel/task.yaml, tests/nested/manual/muinstaller-real/task.yaml, tests/nested/manual/muinstaller/task.yaml, tests/nested/manual/passphrase-support-on-hybrid/task.yaml, tests/nested/manual/split-refresh/task.yaml, tests/nested/manual/uc20-fde-hooks-ice/task.yaml, tests/nested/manual/uc20-fde-hooks-v1/task.yaml, tests/nested/manual/uc20-fde-hooks/task.yaml
Cleanup: remove unused env var NESTED_ENABLE_OVMF
See discussion: https://chat.canonical.com/canonical/pl/uf9akjkpf7rkiripzwpjuu4ccw
=> tests/nested/manual: removed unused env var NESTED_ENABLE_OVMF

cmd/snap/cmd_snap_op_test.go, cmd/snap/wait.go
When installing or refreshing snaps, and a snap pulls in additional
dependencies, the progress reporting gets stuck on 'Auto-connecting of
eligible slots and plugs'. The snap command is indeed waiting for
auto-connect task to complete since its status is still 'Doing', however
internally on the daemon side, the task is getting retried waiting for
prerequisites to finish installing/refreshing. As such, the actual
progress is somewhat invisible to the user and the installation refresh
command may appear stuck.
Attempt to resolve it by adding a simple heuristic to consider showing
the status of the last active task. When a snap install or refresh needs
to pull in additional dependencies, those tasks will be added at the end
and thus will show up in the progress report. In case of refresh, …
=> cmd/snap: improve progress reporting when installing and refreshing snaps

.github/workflows/data-non-fundamental-systems.json, tests/lib/pkgdb.sh, tests/lib/tools/mkimage-uc22, tests/main/interfaces-requests-activates-handlers/task.yaml
Migrating jammy which is missing as part of the migration process
=> tests: move ubuntu-jammy to openstack-ps7 backend

.github/workflows/data-non-fundamental-systems.json, spread.yaml, tests/lib/pkgdb.sh, tests/lib/prepare-restore.sh, tests/lib/prepare.sh, tests/main/cloud-init/task.yaml, tests/main/snap-quota-memory/task.yaml
This migration is the last part of the systems migration planned.
The images are created and ported to openstack now with ntp and proxy configuration to run in ps7.
=> tests: run amazon-linux and arch-linux in openstack

.github/workflows/unit-tests-cross-distro.yaml
Ignore missing tools and do not attempt auto installation.
=> github/workflows/unit-tests-cross-distro: do not auto install tools

.github/workflows/data-nested-systems.json, spread.yaml, tests/lib/muinstaller/mk-classic-rootfs.sh, tests/lib/nested.sh, tests/lib/network.sh, tests/lib/prepare.sh, tests/lib/tools/mkimage-uc22, tests/lib/tools/network-state, tests/lib/tools/tests.nested, tests/nested/manual/minimal-smoke/task.yaml, tests/nested/manual/recovery-system-reboot/task.yaml, tests/nested/manual/remodel-uc-to-next-version-fakestore/task.yaml, tests/nested/manual/seeding-failure/task.yaml, tests/nested/manual/snapd-refresh-from-old/task.yaml, tests/upgrade/sudoers-conffile-removal/task.yaml
Initial changes to run nested tests in openstack environment
The good news is that there is a good performance improvement running nested tests.
=> tests: run nested tests in openstack-ps7 environment

interfaces/prompting/requestrules/requestrules_test.go
This happens in Debian build infrastructure:
```
FAIL: requestrules_test.go:748: requestrulesSuite.TestReadOrAssignUserSessionID
requestrules_test.go:765:
c.Assert(err, IsNil)
... value syscall.Errno = 0x5f ("operation not supported")
```
Most likely the file system under /run is not a tmpfs or is restricted by a sandbox of some sort. Allow tests to detect this condition and skip certain parts.
=> interfaces/prompting: handle unsupported xattrs

cmd/snap/cmd_run.go
Classically confined snaps do not use a private /tmp directory, so they can already access Kerberos tickets without constraints.
Fixes: https://bugs.launchpad.net/snapd/+bug/2121238
=> cmd/snap: do not expose Kerberos tickets for classic snaps

tests/lib/prepare.sh
Retry LP operations that tend to fail often.
=> tests: be very persistent about using resources from LP

overlord/fdestate/backend/reseal.go, overlord/fdestate/backend/reseal_test.go, secboot/secboot.go, secboot/secboot_sb.go, secboot/secboot_sb_test.go
This does not depend on sealing method.
Draft until optee work has landed.
=> many: do not depend on sealing method when resealing

overlord/hookstate/ctlcmd/version_test.go
=> overlord/hookstate/ctlcmd: trivial unit test tweak

.image-garden.mk
=> image-garden: make sure apparmor is installed in openSUSE Tumbleweed images

tests/main/document-interfaces-url/task.yaml
Remove document-interfaces-url exclusions after having created the required documents.
Jira: https://warthogs.atlassian.net/browse/SNAPDENG-35673
=> test/main: remove document-interfaces-url exclusions

.github/workflows/nightly-spread.yaml
=> tests: fix jammy and noble nightly executions with kernels
