- tests/lib/nested.sh
- tests/lib/prepare.sh
Repack the core18 snap with tweaks that enable snapd logging to console.
> tests/lib/nested: enable snapd logging to console for core18

- spread.yaml
Groovy was released, update spread.yaml.
> spread: use the official image for Ubuntu 20.10, no longer an unstable system

- gadget/install/partition_test.go
- gadget/ondisk.go
- gadget/ondisk_test.go
sfdisk --json means dump disk in json format. --dump means dump disk
in sfdisk format. The two options have been made mutually exclusive in
2.35. It is best to be precise and specify only the format that is
expected.
This prevents installation of UC22.
> gadget: correct sfdisk arguments

- secboot/secboot_tpm.go
- secboot/secboot_tpm_test.go
With the run mode and previous implementation of recover mode using
UnlockVolumeUsingSealedKeyIfEncrypted, we would always know what the last call
was and thus when to pass lockKeysOnFinish = true, however with the new degraded
mode, we do not know which call will be the last one.
As such, we need to use a separate function to lock access to the sealed keys,
and call that from the recover mode in initramfs-mounts.
Broken out from https://github.com/snapcore/snapd/pull/9592
> secboot: add LockTPMSealedKeys() to lock access to keys independently

- cmd/snap-bootstrap/cmd_initramfs_mounts.go
- cmd/snap-bootstrap/cmd_initramfs_mounts_nosecboot.go
- cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
- cmd/snap-bootstrap/export_test.go
- secboot/secboot_tpm.go
- secboot/secboot_tpm_test.go
Refactor UnlockVolumeUsingSealedKeyIfEncrypted to always check the disk for
partitions first, then do the TPM connection. This is so that we always know
for sure (if we can know and FindMatchingPartitionUUID doesn't have a
catastrophic error) when we return from UnlockVolumeUsingSealedKeyIfEncrypted
that there is an encrypted device or not. This will make the degraded
recover implementation more robust as it means that even with TPM errors
for i.e. unlocking ubuntu-data-enc, we will still know that we should try
to unlock ubuntu-save.
Additionally, we will want to be able to call this function with different
sealed keys for ubuntu-data, either the main run object or the fallback
object, both of which will be in the encryption dir on ubuntu-seed. As such,
take in a specific key to use …
> secboot: refactor Unlock...IfEncrypted to take keyfile + check disks first

- cmd/snap-bootstrap/cmd_initramfs_mounts.go
- cmd/snap-bootstrap/cmd_initramfs_mounts_nosecboot.go
- cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
- cmd/snap-bootstrap/export_test.go
- secboot/secboot.go
- secboot/secboot_tpm.go
- secboot/secboot_tpm_test.go
Extend the secboot API to allow controlling whether activation with recovery key is enabled or disabled.
> secboot, cmd/snap-bootstrap: enable or disable activation with recovery key

- tests/core/custom-device-reg-extras/task.yaml
- tests/core/custom-device-reg/task.yaml
- tests/core/snap-set-core-config/task.yaml
- tests/lib/network.sh
- tests/main/classic-custom-device-reg/task.yaml
- tests/main/classic-prepare-image-no-core/task.yaml
- tests/main/interfaces-network-control/task.yaml
- tests/main/interfaces-network-observe/task.yaml
- tests/main/interfaces-network/task.yaml
- tests/main/try/task.yaml
This is a task to start replacing the system helper by systemd-run for non-persistent services.
> tests: using systemd-run instead of manually create a systemd unit - part 1

- cmd/snap-bootstrap/cmd_initramfs_mounts.go
- cmd/snap-bootstrap/cmd_initramfs_mounts_nosecboot.go
- cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
- cmd/snap-bootstrap/export_test.go
- secboot/secboot.go
- secboot/secboot_tpm.go
- secboot/secboot_tpm_test.go
We eventually will want to know how we unlocked a volume for implementing
degraded mode and providing some indication to the user as to what happened
automatically during boot.
As such, change UnlockUsingSealedKeyIfEncrypted to return an UnlockResult to be
inspected eventually from cmd_initramfs_mounts.go.
> secboot, many: return UnlockMethod from Unlock* methods for future usage

- interfaces/builtin/fwupd.go
In the previous work, since UC16, we relied on the classic way to use
the path under /EFI/ubuntu for FW update, and this made shimx64.efi
redundant when it was copied to /EFI/ubuntu as well, as /EFI/boot
already provided bootx64.efi which is shim itself. It should be
improved by aligning the ESP layout the gadget specified, and the
confined fwupd just needs to do the same things under /EFI/boot instead.
However, the original rules for /EFI/ubuntu are needed to be maintained
for backward compatibility.
> interfaces/fwupd: enforce the confined fwupd to align Ubuntu Core ESP layout

- overlord/devicestate/firstboot.go
- overlord/devicestate/firstboot_preseed_test.go
- overlord/devicestate/firstboot_test.go
- tests/nested/manual/preseed/task.yaml
At the moment, if more than one non-essential (i.e. regular app snap) snap is preseeded, only one is chained so that mark-seeded waits for it; tasks of other snaps are run after first boot when they should, but are not included in the wait chain of mark-seeded, so mark-seeded doesn't wait for them, and they may finish after seeding is marked "done".
To fix that, the chaining logic makes install-hook wait for all tasks of previous snaps.
> o/devistate: fix chaining of tasks related to regular snaps when preseeding

- interfaces/builtin/kvm_test.go
- interfaces/udev/spec.go
- interfaces/udev/spec_test.go
The snap-device-helper is located under $libexecdir which is /usr/lib/snapd on
some distros, but /usr/libexec/snapd on others (Fedora, recent openSUSE
Tumbleweed).
The commands triggered by rules are executed by udevd which runs in the same
mount ns as pid 1, which is the rootfs of a specific distribution.
> interfaces/udev: use distro specific path to snap-device-helper

- packaging/debian-sid/rules
In the debian-sid packaging we remove a bunch of files from
./secboot/ because dh-golang makes it hard to pass build-flags.
This commit adds the new encrypt_dummy.go so that debian-sid
builds again.
> packaging: keep secboot/encrypt_dummy.go in debian

- gadget/install/install.go
- gadget/install/partition_test.go
- gadget/ondisk.go
- gadget/ondisk_test.go
Add logs so that the console contains some information about the installation
progress.
```
snapd[1309]: handlers_install.go:160: create and deploy partitions
snapd[1309]: install.go:57: installing a new system
snapd[1309]: install.go:58:         gadget data from: /snap/pc/x1
snapd[1309]: install.go:60:         encryption: on
snapd[1309]: install.go:137: created new partition /dev/vda3 for structure #3 ("ubuntu-boot") (size 750 MiB) role system-boot
snapd[1309]: install.go:137: created new partition /dev/vda4 for structure #4 ("ubuntu-save") (size 16 MiB) role system-save
snapd[1309]: install.go:144: encrypting partition device /dev/vda4
snapd[1309]: install.go:160: encrypted device /dev/mapper/ubuntu-save
snapd[1309]: install.go:137: created new partition /dev/vda5 for structure #5 …
```
> gadget/install: add progress logging

- tests/main/lxd/task.yaml
It seems we forgot about enabling this test on 20.10 too.
> tests: enable main lxd test on 20.10

- tests/main/lxd/task.yaml
This commit enables the lxd test on all Ubuntu releases except for
14.04. It also simplifies the systems: string to ensure it is run
as soon as we open e.g. ubuntu-21.04 for spread testing.
> tests: enable lxd test on ubuntu-core-20 and 16.04-32

- spread.yaml
The ubuntu-20.10 spread tests currently run with 6 workers.
However 20.04 and 18.04 use 8 workers and looking at the
spread runtime it seems like 20.10 is currently delaying
runs. So this commit increases the number of workers on
20.10 to 8.
> spread.yaml: increase number of workers on 20.10

- cmd/snap-bootstrap/cmd_initramfs_mounts.go
- cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
- overlord/devicestate/devicestate_install_mode_test.go
- overlord/devicestate/handlers_install.go
this is to make sure that we don't use credentials from data to give access to a save from a different install
> cmd/snap-bootstrap,o/devicestate: use a secret to pair data and save

- vendor/vendor.json
This commit updates our vendored secboot reference to the latest
version that includes the KDF parameter update from PR#127.
> vendor: update to current secboot

- secboot/secboot_tpm.go
- secboot/secboot_tpm_test.go
BlockPCRProtectionPolicies inserts PCR events that signal the
transition from initramfs to runtime, in the same way that EV_SEPARATOR
events signal the transition from pre-OS (platform firmware) to
OS present. When the TPM is disabled, platform firmware will cap
PCRs 0-7 with a EV_SEPARATOR event. There is no reason for us not
to behave in a similar way.
> secboot: call BlockPCRProtectionPolicies even if the TPM is disabled

- spread.yaml
The idea is to make periodical checks to determine if the problem related to the kernel
is already fixed.
The executions are still failing when doing "govendor sync". 
I'll set a spread-cron wekly execution
> tests: set the opensuse tumbleweed system as manual in spread.yaml

- tests/lib/nested.sh
Using new function systemd_stop_and_remove_unit to stop nested-vm
service
> tests: fix nested tests

- cmd/snap-bootstrap/cmd_initramfs_mounts.go
- cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
- secboot/secboot.go
- secboot/secboot_tpm.go
- secboot/secboot_tpm_test.go
- tests/lib/nested.sh
BlockPCRProtectionPolicies is only called during run and recover modes.
This changes snap-bootstrap so that it is called in all boot modes using
a deferred function that is declared very early which ensures that it is
called on most early failures as well.
In addition to this, the same code path for calling it is now used on
all boot modes, which allows UnlockVolumeUsingSealedKeyIfEncrypted to
be significantly simplified.
> snap-bootstrap,secboot: call BlockPCRProtectionPolicies in all boot modes

- tests/lib/nested.sh
- tests/nested/manual/refresh-revert-fundamentals/task.yaml
Temporarily disable secure boot and TPM until we get a new kernel with new
snap-bootstrap.
> tests/nested/manual/refresh-revert-fundamentals: temporarily disable secure boot

- boot/seal.go
- boot/seal_test.go
- cmd/snap-bootstrap/cmd_initramfs_mounts.go
- dirs/dirs.go
This avoids the use of InstallHostFDESaveDir in initramfs at the cost
of some definitional messiness.
We have probably reached the limit of clarity that *Under functions
as they are can bring,
> boot,dirs,c/snap-bootstrap: avoid InstallHost* at the cost of some messiness

- cmd/snap-bootstrap/cmd_initramfs_mounts.go
- cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
- secboot/secboot.go
- secboot/secboot_tpm.go
- secboot/secboot_tpm_test.go
- tests/lib/nested.sh
Based on top of https://github.com/snapcore/snapd/pull/9626.
Now secboot.UnlockResult has two better named fields, FsDevice and PartDevice, where
the PartDevice is always the underlying block device, and FsDevice (if not
the empty string) is whatever device should be mounted to access the
filesystem.
Also update the handling of setting up state for degraded mode in recover
mode to use these variables in a simpler way.
Finally, simplify some logic in the state machine around ubuntu-save being
optional if it is unencrypted and add an additional consistency check that
if ubuntu-data was mounted unencrypted that ubuntu-save must be unencrypted
as well.
All this allows us to implement more correct state handling in the initramfs, where
we can better distinguish between the case of "found but …
> secboot,cmd/snap-bootstrap: fix degraded mode cases with better device handling

- cmd/snap-bootstrap/cmd_initramfs_mounts.go
- secboot/secboot_tpm_test.go
- tests/lib/nested.sh
- tests/nested/core20/degraded/task.yaml
This test currently just exercises the logic if we are missing the run object
key for ubuntu-data and ubuntu-save respectively, since we don't yet have a nice
way to test the other degraded mode cases.
> cmd/snap-bootstrap, secboot, tests: misc cleanups, add spread test

- interfaces/builtin/greengrass_support.go
- interfaces/builtin/greengrass_support_test.go
- interfaces/builtin/system_observe.go
This adds a new attribute to the greengrass-support interface, "flavor", which
indicates what mode of containerization the greengrassd daemon is meant to be
supporting with the plug. With no flavor attribute, or the "container" flavor,
then the old policy is available so as to not break old users of the snap, but
with a new "process" flavor, then a far less privileged version of the interface
is provided, which allows the greengrassd daemon to implement no
containerization and thus the lambdas that are run are not run with the
additional privilege afforded to the original implementation of the interface,
as that would allow lambdas to trivially escape the sandbox.
I have tested this change with a version of the greengrass snap that was provided to me by AWS, but my testing is minimal and …
> interfaces/greengrass-support: add additional "process" flavor for 1.11 update

- data/selinux/snappy.te
- sandbox/cgroup/tracking.go
- sandbox/cgroup/tracking_test.go
- tests/lib/snaps/test-snapd-xdg-settings/bin/xdg-settings-wrapper
- tests/lib/tools/tests.invariant
- tests/main/refresh/task.yaml
- tests/main/xdg-settings/task.yaml
This patch moves refresh app awareness closer to being enabled by
enabling application tracking unconditionally. This will improve our
understanding of the feature, specifically the interaction with systemd,
without actually acting on the new information yet.
In addition, this will allow us to map any pid to a snap name, improving
interaction with some portals.
> sandbox: track applications unconditionally

- tests/lib/nested.sh
The check to get the snap revisions was parsing the output of `snap info`
command, which may produce incorrect output when the looks like this:
```
channels:
latest/stable:    20       2020-05-07 (634) 63MB -
latest/candidate: 20       2020-05-07 (634) 63MB -
latest/beta:      20201027 2020-11-11 (875) 64MB -
latest/edge:      ↑
```
Instead of parsing text, use the store API directly to find out the revision of
a snap in a given channel.
> tests/lib/nested: poke the API to get the snap revisions

- interfaces/builtin/greengrass_support.go
- interfaces/builtin/greengrass_support_test.go
The flavor attribute names are now as follows:
- "legacy-container" is the full containerization also known as
"Greengrass container" in AWS's UI.
- "no-container" is the process-mode, no confinement mode, also known as "no
container" in AWS's UI.
> interfaces: fix greengrass attr naming

- spread.yaml
The grub bug has been fixed, everything should work fine with the 1500MB default.
> spread: UC20 no longer needs 2GB of mem

- snap/hooktypes.go
Even though this is trivial having this is useful when testing the full "fde-setup" branch. The reason is that snap-exec will read the hooks and discard hooks that are not valid. But snap-exec is taken from inside the core or snapd snap so right now to test the full fde-setup branch a bind mount of snap-exec is needed or a full rebuild of the core/snapd snap. With this PR a local snapd build is enough.
> snap: add new "fde-setup" hooktype

- asserts/model.go
- asserts/model_test.go
This commit implements the new "storage-safety" header for the
model assertion. This header controls the encryption handling
for the given model and grade. Valid values for the storage-safety
header are "encrypted|prefer-encrypted|prefer-unencrypted".
Note that the the combination of "model: secured" and 
"storage-safety: prefer-unencrypted" is an error.
In addition to the assertion change this will need work on the
devicemanager to honor the settings.
> asserts: implement "storage-safety" in uc20 model assertion

- boot/makebootable.go
- boot/makebootable_test.go
- image/image_test.go
This is the first step to doing away with the current default of
snapd_recovery_mode being unset implying "install". We need prepare-image (and
thus also ubuntu-image) to start writing "snapd_recovery_mode=install".
> boot/makebootable.go: set snapd_recovery_mode=install at image-build time

- tests/core/basic20/task.yaml
Skip some kernel and boot checks for arm devices
This is because kernel.efi file does not exist and the checks to validate we are using managed boot assets are checking the grub config.
> tests: fix basic20 test on arm devices

- osutil/udev/netlink/conn_test.go
- strutil/quantity/example_test.go
- strutil/shlex/shlex_test.go
This allows us to use -gocheck options for the whole codebase, for example to
run all tests in the codebase with the name matching "kernel" one can now do:
go test ./... -gocheck.f kernel
and that will only fail if the tests fail, whereas previously it would fail
because in these packages gocheck was not imported and as such -gocheck.f was
not recognized as an option and the help text for `go test` was printed off
instead of running any tests.
Eventually we may want to adapt the tests in these packages to use go-check too
so that these can also be filtered/run successfully with go test and gocheck
options.
> strutil/shlex,osutil/udev/netlink: minimally import go-check

- boot/makebootable.go
- boot/seal.go
- boot/seal_test.go
Add intial support for sealKeyToModeenv() to support running
a "fde-setup" hook instead of using the build-in secboot
implementation for key sealing.
This is broken out of the larger
https://github.com/mvo5/snappy/tree/fdehook-skeleton-2
branch to ensure we agree on naming and approach in this part.
> boot: add scaffolding for "fde-setup" hook support for sealing

- tests/core/fsck-on-boot/task.yaml
With the updated initrd /boot/efi is now bind mounted to ubuntu-seed,
see https://github.com/snapcore/core-initrd/pull/8. This needs to
be unmounted before we do the vfat partition manipulation.
> tests: unmount /boot/efi in fsck-on-boot test

- interfaces/builtin/raw_usb.go
This appears to be needed for the chromium snap to talk to a ttyACM0 device.
See [bug #1890365](https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1890365) for details.
> interfaces/raw_usb: allow read access to /proc/tty/drivers (LP: #1890365)

- tests/main/classic-prepare-image-no-core/task.yaml
- tests/main/classic-prepare-image/task.yaml
- tests/main/prepare-image-grub/task.yaml
Revert change which made this test to be executed on some non supported systems.
> tests: updated the systems to run prepare-image-grub test

- spread.yaml
Unattended upgrades may interfere with package installation in tests.
> spread: disable unattended-upgrades on ubuntu

- boot/makebootable.go
- boot/seal.go
- boot/seal_test.go
- overlord/devicestate/devicemgr.go
- overlord/devicestate/devicestate.go
- overlord/devicestate/devicestate_test.go
- overlord/devicestate/export_test.go
This commit adds support for setting boot.HasFDESetupHook and matching
tests.
> devicestate: implement boot.HasFDESetupHook

- vendor/vendor.json
The secboot repo had a accidental secboot.test binary commited
and we pulled it in via the vendor.json. This commit updates the
vendor.json to a version of secboot that does no longer include
this binary.
The version also implements a less strict AddEFISecureBootPolicyProfile.
> vendor: update secboot repo to avoid including secboot.test binary

- cmd/snap-bootstrap/cmd_initramfs_mounts.go
- overlord/devicestate/devicestate_install_mode_test.go
- overlord/devicestate/export_test.go
- overlord/devicestate/handlers_install.go
- tests/lib/assertions/developer1-20-storage-safety-prefer-unencrypted.json
- tests/lib/assertions/developer1-20-storage-safety-prefer-unencrypted.model
- tests/nested/manual/uc20-storage-safety/task.yaml
This commit adds support for the model storage-safety preferences.
So for models that set "prefer-unencrypted" the encryption will be
skipped currently. Note that this does not yet implement setting
a different preference via the install chooser menu. This should
also be supported eventually.
> devicestate: support "storage-safety" defaults during install

- cmd/snap/cmd_run.go
- cmd/snap/cmd_run_test.go
The kernel snap can have hooks, e.g. the fde-setup hook or a configure
hook. To support this we run the hooks with the boot base of the model.
> snap: use the boot-base for kernel hooks

- tests/core/snap-debug-bootvars/task.yaml
The test is failing on arm devices because the kernel and the core do not match.
> tests: Fix snap-debug-bootvars test to make it work on arm devices and core18

- bootloader/bootloader.go
- bootloader/bootloadertest/bootloadertest.go
- bootloader/grub.go
- bootloader/grub_test.go
Indicate when the bootloader boot config was updated. This allows the callers to
take a better decision as to whether an update or some other action is required.
> bootloader: indicate when boot config was updated

- packaging/arch/PKGBUILD
The 2.48 has been pushed to AUR. Sync PKGBUILDs to make the future updates
easier.
> packaging/arch: sync with AUR packaging

- daemon/api_base_test.go
- daemon/api_console_conf_test.go
- daemon/api_debug_pprof_test.go
- daemon/api_debug_seeding_test.go
- daemon/api_debug_test.go
- daemon/api_model_test.go
- daemon/api_systems_test.go
- daemon/api_test.go
- daemon/api_users_test.go
- daemon/daemon_test.go
- daemon/export_api_users_test.go
- daemon/export_test.go
This branch does 3 things mainly:
* moves apiBaseSuite to api_base_test.go, it starts making some of its fields exported because for a while it will need to be used both from daemon vs daemon_test residing tests,  in the process it also uses more AddCleanup and correct some issues with its usage (missing BaseTest.SetUpTest etc)
* it switches api_users_test.go to live in daemon_test, it also moves some store method faking to it
* it adds a new way to invoke handling logic that sits between pure HTTP invocation and needing to know/expose Commands, this is implemented in APIBaseSuite as GetReq and PostReq helpers
The two commits are probably easier to read on their own.
> daemon: start cleaning up api tests

- asserts/model.go
- asserts/model_test.go
- cmd/snap-bootstrap/cmd_initramfs_mounts.go
- overlord/devicestate/devicestate_install_mode_test.go
- overlord/devicestate/export_test.go
- overlord/devicestate/handlers_install.go
- tests/core/fsck-on-boot/task.yaml
- tests/lib/assertions/developer1-20-storage-safety-prefer-unencrypted.json
- tests/lib/assertions/developer1-20-storage-safety-prefer-unencrypted.model
- tests/nested/manual/uc20-storage-safety/task.yaml
This is a backport of the storage-safety PRs from:
https://github.com/snapcore/snapd/pull/9555
https://github.com/snapcore/snapd/pull/9656
to 2.48. This is needed to get clean cherry-picks for
https://github.com/snapcore/snapd/pull/9670
so that we can have "fde-setup" hook support in 2.48
> devicestate: support "storage-safety" defaults during install (2.48)

- boot/cmdline.go
- boot/cmdline_test.go
Add a helper that can generate a candidate kernel command line that would be
used when booting a recovery system.
> boot: add helper for generating candidate kernel lines for recovery system

- data/selinux/snappy.te
Some distros, eg. CentOS 7 do not have /tmp on tmpfs. Because of this, the
policy rules for tmpfs are not effective and the following denial can be
observed when disconnecting the x11 interface (which mounts /tmp/.X11-unix from
the host):
```
type=AVC msg=audit(1606220902.660:1383): avc:  denied  { rmdir } for
pid=28575 comm="snap-update-ns" name=".X11-unix" dev="sda2"
ino=17552915
scontext=system_u:system_r:snappy_mount_t:s0
tcontext=system_u:object_r:tmp_t:s0
tclass=dir permissive=1
```
We need to extend the policy to explicitly allow poking generic tmp_t files and
directories.
@Conan-Kudo can you take a look too?
> data/selinux: update the policy to allow operations on non-tmpfs /tmp

- cmd/snap-bootstrap/cmd_initramfs_mounts.go
given we measure models cross-checking them otherwise is not
a need on TPM systems, but is an open question how to ensure
we open and boot only under the expected models on non-TPM
systems
> cmd/snap-bootstrap: update model cross-check considerations

- overlord/hookstate/ctlcmd/fde_setup.go
- overlord/hookstate/ctlcmd/fde_setup_test.go
- overlord/hookstate/fdesetup.go
This commit implements support for running `fde-setup-{request,result}`
from hooks.
> hookstate: implement snapctl fde-setup-{request,result}

- daemon/api_base_test.go
- daemon/api_connections_test.go
- daemon/api_interfaces_test.go
- daemon/api_mock_test.go
- daemon/api_test.go
make it live in daemon_test, also do the same for api_connections.go
they both share the interfacesSuite
This is already quite large, a different PR will move the /v2/interfaces handlers themselves to api_interfaces.go
> daemon: split out /v2/interfaces tests to api_interfaces_test.go

- tests/main/uc20-create-partitions-encrypt/task.yaml
- tests/main/uc20-create-partitions-reinstall/task.yaml
- tests/main/uc20-create-partitions/task.yaml
The "pc" gadget contains the ubuntu-save partition now. This
shifts the partition tables and the create-partitions test
needs adjustment.
> tests: fix uc20-create-parition-* tests for updated gadget

- tests/lib/uc20-create-partitions/main.go
- tests/main/uc20-create-partitions-encrypt/task.yaml
- tests/main/uc20-create-partitions/task.yaml
A followup to #9706. Verify that ubuntu-save encryption keys are valid and can open the partitions. Replace `not MATCH` with `NOMATCH`
> tests/main/uc20-create-partitions: verify ubuntu-save encryption keys, tweak not MATCH

- update-pot
The update-pot script was not generating any plural message IDs because it was scanning for `i18n.DG()` calls instead of `i18n.NG()`.  This fixes that bug and adds an extra string to the `check_canaries` sanity check using a string from `timeutil/human.go`.
> update-pot: fix typo in plural keyword spec

- tests/lib/store.sh
When a unit fails, systemd may keep its status, resetting it allows to start the
unit again with a clean slate. Otherwise, subsequent attempts to create and
start the unit through systemd-run will fail.
> tests: reset fakestore unit status

- client/client.go
we increased the default client pkg timeout to deal with slow machines,
but /v2/system-info request timeout influences how long
snap version will take to come back if snapd is not running at all
reduce to 25 secs
ideally all the client methods should take context so that each
caller can set up a caller specific timeout if desired, that is much more
involved though
> client: reduce again the /v2/system-info timeout

- daemon/api_systems.go
- overlord/devicestate/devicemgr.go
- tests/nested/manual/core20-early-config/task.yaml
We should be able to trigger a reboot without specifying the system label, since
we can detect the current system label and use that for the specified mode.
This was not caught before because of how we test daemon command endpoints and
the fact that the router we use operates weirdly for paths like /v2/systems,
where we have separate commands for the version without any sub-path and the
version with a sub-path.
> o/devicestate,daemon: fix reboot system action to not require a system label

- seed/seedwriter/helpers.go
- seed/seedwriter/seed16.go
- seed/seedwriter/seed20.go
- seed/seedwriter/writer.go
- seed/seedwriter/writer_test.go
the code before wasn't taking into account the modes in which
the base or default content providers were available vs
the modes of the dependent snap, with the changes here
it now does
fixes LP: #1883970
> seed/seedwriter: consider modes when checking for deps availability

- overlord/hookstate/context.go
- overlord/hookstate/hookmgr.go
- overlord/hookstate/hookstate_test.go
This commit adds support to run hooks in an ephemeral mode. This
will be used by the fde-setup hook runner in PR#9705.
> hookstate: add new HookManager.EphemeralRunHook()

- cmd/snap/cmd_auto_import_test.go
> cmd/snap: suppress a case of spurious stdout logging from tests

- cmd/snap-bootstrap/cmd_initramfs_mounts.go
- cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
- osutil/disks/disks.go
- osutil/disks/disks_linux.go
- osutil/disks/disks_linux_test.go
- osutil/disks/mockdisk.go
- osutil/disks/mockdisk_test.go
- secboot/secboot_tpm.go
This is to accommodate a future FindMatching...WithPartLabel. Additionally, an
internal refactor to support storing additional properties for partitions when
we search a disk is implemented to allow for the additional future method.
The error type now is also more versatile to allow specifying what part failed,
searching for a partition by filesystem label or by partition label.
This PR is just the change to rename things to make the followup simpler to 
review, which I will open shortly...
> many: rename disks.FindMatching... to FindMatching...WithFsLabel and err type

- bootloader/androidboot.go
- bootloader/bootloader.go
- bootloader/grub.go
- bootloader/lk.go
- bootloader/uboot.go
This is not used anywhere anymore, so let's just drop it. If we need it again,
we can bring it back.
> bootloader: remove installableBootloader interface and methods

- overlord/snapshotstate/backend/backend.go
- overlord/snapshotstate/backend/backend_test.go
- overlord/snapshotstate/backend/export_test.go
The snaphsot backend cleanup code may run into multiple errors
that should be captured but where the code should not stop.
When returning those to the user the formating easily becomes
messed up. This commit adds code and tests to make sure this
works better.
Followup to PR #9526
> snapshotstate: improve handling of multiple errors

- osutil/disks/disks.go
- osutil/disks/disks_linux.go
- osutil/disks/disks_linux_test.go
- osutil/disks/mockdisk.go
- osutil/disks/mockdisk_test.go
This will enable searching for a partition with a given label on the provided
disk.
This is needed for the lk bootloader on UC20 work.
> osutil/disks: add FindMatchingPartitionUUIDWithPartLabel to Disk iface

- bootloader/export_test.go
- bootloader/lk.go
- bootloader/lk_test.go
- bootloader/lkenv/lkenv.go
- bootloader/lkenv/lkenv_test.go
To simplify existing code, use "" as the backup file to mean path+"bak".
Also add tests that when specifying a non-empty string as the backup file that
we don't use the legacy backup file handling logic.
This will resolve the issue we have in #9695 around passing in `/dev/disk/by-partuuid/1234` as the primary file and then getting `/dev/disk/by-partuuid/1234bak` as the backup file.
> bootloader/lkenv: specify backup file as arg to NewEnv(), use "" as path+"bak"

- gadget/gadget.go
- gadget/gadget_test.go
A customer with a gadget snap that has a "ubuntu-boot" label
in the wild is broken by this new validation in 2.48. This
commit fixes this.
> gadget: disable ubuntu-boot role validation check

- interfaces/builtin/log_observe.go
This is similar in purpose to allowing writes to /sys/kernel/printk_ratelimit.
This will allow i.e. snappy-debug to write `noquiet` to this file and thus show file accesses that were denied, even when a snap is in devmode. This is not quite as useful as my original proposal with [this other PR](https://github.com/snapcore/snapd/pull/8019), but it is more useful than the status quo since if a user runs snappy-debug as root, then tries to debug their devmode snap, they will at least see the denied accesses whereas today those accesses will not be seen.
This is supported since kernel version 2.X so this should be safe for snappy-debug to do on all systems which support snaps.
CC @jrjohansen who notified me of this :smile:
> interfaces/builtin/log_observe.go: allow controlling apparmor audit levels

- overlord/devicestate/devicestate_serial_test.go
- overlord/devicestate/handlers_serial.go
- tests/nested/core20/basic/task.yaml
this makes serial-authority cross-checks work for example
have a spread test as well
> o/devicestate: save model with serial in the device save db

- gadget/gadget.go
- gadget/gadget_test.go
- overlord/devicestate/devicestate_gadget_test.go
This comes with tests (that will need to evolve) and the minimal fix we applied over 2.48 to keep allowing hybrid 18->20 ready volumes setups.
> gadget,o/devicestate: hybrid 18->20 ready volume setups should be valid

- overlord/devicestate/devicestate_serial_test.go
- overlord/devicestate/handlers_serial.go
- tests/nested/core20/basic/task.yaml
this makes serial-authority cross-checks work for example
have a spread test as well
> o/devicestate: save model with serial in the device save db (2.48)

- tests/main/security-seccomp/task.yaml
If the test fails before the file "$SRC".orig is created, then the test fails during restore making the whole suite fail.
> tests: fix the scenario when the "$SRC".orig file does not exist

- tests/regression/lp-1899664/task.yaml
This happens when snapd is not rev x1 during beta validation
> tests: fix lp-1899664 test when snapd_x1 is not installed in the system

- secboot/export_test.go
- secboot/secboot_tpm.go
- secboot/secboot_tpm_test.go
This commit implements running fde-reveal-key and using the
output to unlock a disk that was previously sealed using the
fde-setup hook.
> secboot: use `fde-reveal-key` if available to unseal key

- cmd/snap-update-ns/sorting_test.go
A followup to #9751.
Add a simpler test case for checking the order of sorting with overname.
> cmd/snap-update-ns: add better unit test for overname sorting

- gadget/export_test.go
- gadget/gadget.go
- gadget/gadget_test.go
- gadget/validate.go
- gadget/validate_test.go
This is a first step on the journey to not do full validation where we might get stricter or change rules slightly intentionally or by mistake for already on-system gadgets.
The idea is to separate the more convention/rule based checks, from the ones that should always be valid (basic syntax and not overlapping) and then gain control over when the former are run.
Also add a test about hybrid setups in the context of the new started separation.
> gadget: start separating rule/convention validation from basic soundness 

- daemon/api_aliases_test.go
- daemon/api_apps_test.go
- daemon/api_base_d_test.go
- daemon/api_base_test.go
- daemon/api_buy_unsupp_test.go
- daemon/api_connections_test.go
- daemon/api_general_test.go
- daemon/api_interfaces_test.go
- daemon/api_model_test.go
- daemon/api_snap_conf_test.go
- daemon/api_snapctl_test.go
- daemon/api_system_recovery_keys_test.go
- daemon/api_systems_test.go
- daemon/api_users_test.go
- daemon/export_test.go
temporarely keep a version also in daemon in api_base_d_test.go, that will go away...
unexport all methods that are not interface implementations
sorry for the flip-flop about this
> daemon: actually move APIBaseSuite to daemon_test.apiBaseSuite

- bootloader/lk.go
- bootloader/lkenv/lkenv.go
* bootloader/{lk,lkenv}: adjust Debugf's to be more useful and specific 
* bootloader/lk.go: don't check backup file in Present() during prepare-image time
> bootloader/{lk,lkenv}: followups from #9695

- sandbox/seccomp/compiler.go
- sandbox/seccomp/compiler_test.go
Some distributions set up a preload of some optimized libraries that can trigger
ld.so to output errors to stderr. For example on Raspbian the output of
snap-seccomp version-info can look like this (with the error written to stderr);
```
ERROR: ld.so: object ‘#/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so’ from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
0528cb62afe0b3d7be81b1ea0b9e60361ec8fd80 2.4.3 9b218ef9a4e508dd8a7f848095cb8875d10a4bf28428ad81fdc3f8dac89108f7 bpf-actlog
```
Improve the code to collect version-info from stderr only, but still show stderr
if snap-seccomp version-info exits with non-0 status.
Originally reported in the forum: https://forum.snapcraft.io/t/snapd-has-failed/21462/3
Fixes: …
> sandbox/seccomp: use snap-seccomp's stdout for getting version info

- boot/export_test.go
- boot/seal.go
- boot/seal_test.go
- overlord/devicestate/devicemgr.go
- overlord/devicestate/devicestate_test.go
- overlord/devicestate/fde/fde.go
- overlord/hookstate/ctlcmd/fde_setup_test.go
This commit adds code so that sealKeyToModeenvUsingFdeSetupHook()
actually writes sealed keys to the expected places.
Preview at this point, needs more tests.
Build on top of https://github.com/snapcore/snapd/pull/9705 
(which needs to squash merged first and then this need to be re-based on top of master)
> boot: add sealKeyToModeenvUsingFdeSetupHook()

- gadget/gadget.go
- gadget/gadget_test.go
- gadget/install/content_test.go
- gadget/layout.go
- gadget/mountedfilesystem.go
- gadget/mountedfilesystem_test.go
- gadget/update_test.go
- gadget/validate.go
- overlord/devicestate/devicestate_remodel_test.go
Samuele asked for this in https://github.com/snapcore/snapd/pull/9149/files#r537628269 
The first commit renames gadget.VolumeContent.Source to "UnresolvedSource" and updates all the tests.
The second commit adds a "ResolvedSource()" accessor and updates the places that need resolved sources.
Note that this will all change further when the actual resolving is implemented. Right now a common pattern
is something like: 
```
srcPath := filepath.Join(f.contentDir, source)
```
but after the solve is done this is no longer needed, ResolvedSource() will have contentDir already set.
> gadget: prepare gadget kernel refs (0/N)

- testutil/dbustest.go
- testutil/dbustest_test.go
The standard session bus configuration searches for service activation files found in /usr/share/dbus-1/services, and may load other custom local configuration.  This could cause the test suite to spawn arbitrary services installed on the system.
By using a custom daemon configuration file, without this servicedir configuration, we ensure that tests using the fixture only see names provided by the test suite.
This is important when testing against well known services: if we want to test what happens when there is no notification daemon installed, we don't want the test's behaviour to depend on whether there is a service activation file for that name installed.
> testutil: make DBusTest use a custom bus configuration file

- tests/core/netplan/task.yaml
- tests/main/fake-netplan-apply/task.yaml
See the related issue for more context, but eventually we want to stop using
test-snapd-netplan-apply and use a much simpler snap that uses netplan from the
base snap instead but that requires changes to network-setup-control which may
take time to land into master.
This is meant temporarily until https://github.com/snapcore/snapd/pull/9784 gets full reviews and can re-enable the test
> tests/main/fake-netplan-apply: disable test on xenial for now

- boot/assets.go
- boot/export_test.go
- boot/seal.go
- boot/seal_test.go
This commit adds code so that resealKeyToModeenv() will read the
sealed-keys file and use either "tpm" or "fde-setup-hook" for
resealing. This also unbreaks master because this no longer
runs HasFDESetupHook during seeding.
> gadget: use "sealed-keys" to determine what method to use for reseal

- sysconfig/cloudinit.go
- sysconfig/cloudinit_test.go
- tests/main/cloud-init/task.yaml
- tests/nested/manual/cloud-init-nocloud-not-vuln/task.yaml
Without this key in the cloud-init restrict file, cloud-init on subsequent boots
will not know what instance-id to trust, as in multipass and other NoCloud
deployments the instance-id will only be available via the NoCloud CIDATA
filesystem label, but the snapd restriction file will not allow reading or
importing that filesystem label and so cloud-init will not know whether it is in
a new first boot like in the cloud where a "golden image" is booted with a given
cloud-init and then saved and rebooted with a new instance-id.
When cloud-init is unable to detect the instance-id of the current boot, it
assumes that it is booting a "golden image" and will search for new
configuration input and thus a new instance-id, but in the case of multipass,
where all cloud-init configuration is provided …
> sysconfig/cloudinit.go: add "manual_cache_clean: true" to cloud-init restrict file

- testutil/exec.go
our own test fixtures might have messed up with it, notably
some tests change DBUS_SESSION_BUS_ADDRESS for example
> testutil: use the original environment when calling shellcheck

- boot/assets.go
- boot/seal.go
- boot/seal_test.go
This is a small followup on #9783 to tweak/improve the error handling and tests.
> boot: tweak resealing with fde-setup hooks

- overlord/devicestate/devicemgr.go
- overlord/devicestate/devicestate_install_mode_test.go
- overlord/devicestate/export_test.go
- overlord/devicestate/handlers_install.go
Run the fde-setup hook with "op":"features" as part of the install
to ensure that we test that the hardware actually supports
encryption. Later this features operation may also alter the way
that the install happens.
> devicestate: implement checkFDEFeatures()

- overlord/devicestate/devicestate_install_mode_test.go
- overlord/devicestate/handlers_install.go
This is a followup for PR#9791 that logs errors from
checkEncryption to the logger during install.
> devicestate: log checkEncryption errors via logger.Noticef

- secboot/secboot_tpm.go
- secboot/secboot_tpm_test.go
- tests/nested/manual/uc20-fde-hooks/task.yaml
We can't have  nice things apparently, see https://github.com/snapcore/core-initrd/issues/13, i.e. we cannot run:
systemd-run --wait or --pipe in the initrd because there is no dbus there.
So this PR implements a workaround that uses polling to get the result and tmp files. Not nice but workable.
Alternatively we could simply run "fde-reveal-key" with exec.Command() but that would mean no basic seccomp and no max-runtime support and no isolation in a cgroup.
This is based on https://github.com/snapcore/snapd/pull/9769 and probably not fun to review until the other one has landed
> secboot: add workaround for snapcore/core-initrd issue #13

- tests/core/netplan/task.yaml
- tests/main/fake-netplan-apply/task.yaml
This is https://github.com/snapcore/snapd/pull/9785 for 2.48. Had to do an extra cherry pick so that it applies cleanly.
> tests: backport netplan workarounds from #9785 (2.48)

- secboot/export_test.go
- secboot/secboot_tpm.go
- secboot/secboot_tpm_test.go
This commit ensures that the loop that waits for fde-reveal-key
terminates even if systemd-run for some reason does not honor
the MaxRuntimeSec timeout.
> secboot: add extra paranoia when waiting for that fde-reveal-key

- daemon/api_base_test.go
- daemon/api_model_test.go
- daemon/api_sideload_n_try_test.go
- daemon/api_snap_conf_test.go
- daemon/api_snaps_test.go
- daemon/api_snapshots_test.go
- daemon/api_systems_test.go
- daemon/export_api_snapshots_test.go
Import tests use wrong endpoint path (which isn't relevant for the test because it calls api command directly but is confusing). This PR fixes the path and also updates the test to use apiBaseTest (and with this, the endpoint path actually needs to be correct).
> tests: use apiBaseSuite for snapshots tests, fix import endpoint path

- run-checks
The ineffassign utility has changed its argument syntax so that the static checks fail with:
```
-: no Go files in .../src/github.com/snapcore/snapd
ineffassign: error during loading
```
To check the current package and all sub-packages, we now need to pass `./...` as the argument (as outlined in https://github.com/gordonklaus/ineffassign/pull/51).
> run-checks: update to match new argument syntax of ineffassign

- tests/lib/snaps/test-snapd-sh/bin/cmd
- tests/lib/snaps/test-snapd-sh/meta/snap.yaml
- tests/main/cohorts/task.yaml
The `yq` tool changed its command line arguments and the test broke. Try not to
depend on external tools and use a simple Python snippet to extract the cohort key.
> tests/main/cohorts: replace yq with a Python snippet

- tests/lib/pkgdb.sh
The path to the tool is not correct and it is making fail the imports like:
snapd-master/tests/lib/pkgdb.sh: line 16: /root/spread/tasks/google/update-ubuntu-14.04-64/snapd-master/tests/lib/tools/tests.pkg.apt.sh: No such file or directory
snapd-master/tests/lib/pkgdb.sh: line 18: remap_one: command not found
> tests: fix library path used for tests.pkgs

- tests/main/snap-validate-basic/task.yaml
go-flags on Fedora 32/33 panics when showing --help of a hidden command. Git bisect indicates that breakage is due to this commit in go-flags https://github.com/jessevdk/go-flags/commit/71064e1638ea2c34ad561fd1ec92a23944673ff4 which got triggered by this commit https://github.com/snapcore/snapd/commit/85900470da735d61e7c520b27dfc82172a6af911 in the snapd tree.
> tests/main/snap-validate-basic: disable test on Fedora due to go-flags panics

- daemon/api.go
- daemon/api_sideload_n_try.go
- daemon/api_sideload_n_try_test.go
- daemon/api_snaps.go
- daemon/api_snapshots.go
- daemon/export_test.go
and api_sideload_n_try.go
for now this moves many snaps and sideload/try code
in the process create a separate sideloadOrTrySnap
and simplify the signature of trySnap
two renames as well:
snapsOp => snapManyOp
snapsActionFunc => snapManyActionFunc
> daemon: start moving implementation to api_snaps.go

- tests/lib/dirs.sh
- tests/lib/tools/tests.pkgs.apt.sh
This change updates some missing uses of the os.query tool to check the os
> tests: use os-query tool to check debian, trusty and tumbleweed

- tests/lib/tools/os.query
Include now aarch as part of the possibilities when checking if the current system is arm
> tests: update check to verify is the current system is arm

- packaging/debian-sid/snapd.postrm
- packaging/ubuntu-14.04/snapd.postrm
- packaging/ubuntu-16.04/snapd.postrm
- tests/main/lxd-postrm-purge/prep-snapd-in-lxd.sh
- tests/main/lxd-postrm-purge/task.yaml
When executing inside the containers, / is not mounted with shared propagation,
thus snap-confine bind mounts /snap to itself and sets the MS_SHARED propagation
flag accordingly.
During postrm purge, the final directly cleanup must be done after we have dealt
with the /snap mount.
Add a spread that to verify that purge inside LXD works correctly.
> packaging/deb, tests/main/lxd-postrm-purge: fix purge inside containers

- interfaces/builtin/opengl.go
- interfaces/builtin/opengl_test.go
To use the Raspberry Pi multimedia abstraction layer libraries (MMAL [1]) for hardware accelerated video decoding applications do additionally to the existing access to /dev/vchiq need also read/write access to the Contiguous Memory Allocator [2] through the /dev/vcsm-cma device node provided by the newer VideoCore drivers. 
In combination with the closed source GPU libraries from broadcom this allows fully accelerated Video playback on Raspberry Pi devices.
This pull requests adds the needed read/write permission to /dev/vcsm-cma to the opengl interface.
[1] http://www.jvcref.com/files/PI/documentation/html/index.html
[2] https://lwn.net/Articles/486301/
> interfaces/opengl: allow RPi MMAL video decoding

- cmd/libsnap-confine-private/cleanup-funcs-test.c
When running inside a docker/podman container, there usually is no /etc/fstab.
In such case the test_cleanup_endmntent() test fails as it tries to poke
/etc/fstab directly.
Fix the test so that it pokes a temporary file instead.
> cmd/libsnap-confine-private: make unit tests execute happily in a container

- cmd/libsnap-confine-private/cleanup-funcs-test.c
The version of glib we compile against on Ubuntu 14.04 Trusty Tahr does not
support "g_autofree", so just manually free at the end of the test to get spread
tests running again on 14.04.
The test failure was introduced via https://github.com/snapcore/snapd/pull/9818, and was not caught because "skip spread" was used, so we didn't see that it made 14.04 fail.
> cmd/libsnap-confine-private/cleanup-funcs-test.c: rm g_autofree usage

- interfaces/apparmor/spec.go
Fix confusing comments introduced via copy pasting from the mount backend.
> interfaces/apparmor: drive by comment fix

- tests/nightly/interfaces-openvswitch/task.yaml
The service openvswitch-switch.service cannot be started due to an error
on debian sid.
+ systemctl enable --now openvswitch-switch.service
Synchronizing state of openvswitch-switch.service with SysV service
script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable openvswitch-switch
Failed to start openvswitch-switch.service: Unit
openvswitch-nonetwork.service not found.
The test si still being executed on debian-9
> tests: skip interfaces-openvswitch spread test on debian sid

- interfaces/builtin/greengrass_support.go
- interfaces/builtin/greengrass_support_test.go
- interfaces/builtin/system_observe.go
- run-checks
- tests/lib/snaps/test-snapd-sh/bin/cmd
- tests/lib/snaps/test-snapd-sh/meta/snap.yaml
- tests/main/cohorts/task.yaml
This is https://github.com/snapcore/snapd/pull/9595 and https://github.com/snapcore/snapd/pull/9639, back-ported to 2.48.
This also includes https://github.com/snapcore/snapd/pull/9806 and https://github.com/snapcore/snapd/pull/9807 in order to get unit tests + spread tests to run.
> interfaces/greengrass-support: back-port interface changes to 2.48

- interfaces/builtin/docker_support.go
- interfaces/builtin/home.go
- interfaces/builtin/kernel_module_observe_test.go
- interfaces/builtin/mir_test.go
- interfaces/builtin/ptp_test.go
- interfaces/builtin/raw_volume_test.go
- interfaces/builtin/u2f_devices.go
- interfaces/builtin/upower_observe_test.go
golangci-lint was unhappy so I had a go at fixing some of those.
> interfaces/builtin: more drive by fixes, import ordering, removing dead code

- sandbox/cgroup/process_test.go
- tests/main/cgroup-devices/task.yaml
- tests/main/cgroup-freezer/task.yaml
- tests/main/security-device-cgroups/task.yaml
- tests/main/snap-device-helper-nvme/task.yaml
- tests/main/snapctl-is-connected/task.yaml
Since 21.12.2020 (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=943981)
Debian Sid is using a unified cgroup hierarchy (v2). Disable tests that fail on
such system. Fix sandbox/cgroup unit tests to apply proper mocking of v1 support.
> sandbox/cgroup, tess/main: fix unit tests on v2 system, disable broken tests on sid

- tests/main/snap-advise-command/task.yaml
snap-advise spread test fails a lot with "429 Too many requests". This workaround skips the rest of the test if 429 is encountered.
> tests: skip main part of snap-advise test if 429 error is encountered

- tests/main/apt-hooks/task.yaml
The same issue is faced on both tests: snap-advise-command and apt-hooks. 
The idea is to work around this when the store is misbehaving.
> tests: apply workaround done for snap-advise-command to apt-hooks test

- cmd/snap-repair/cmd_run_test.go
- cmd/snap-repair/runner.go
- cmd/snap-repair/runner_test.go
This information will be used in a follow-up when we actually filter repair assertions by their `bases` and `modes` settings in the headers.
> cmd/snap-repair: save base snap and mode in device info; other misc cleanups

- packaging/debian-sid/rules
- tests/nightly/sbuild/task.yaml
The clean of override_dh_install-indep was missing to remove
```
tmp/usr/bin/genasset
```
this is fixed now. The nightly sbuild test also needs to be
tweaked to *only* build the arch:all packages to reproduce
this bug.
I also removed --debug from sbuild as it's *really* verbose.
> packaging: fix arch-indep build on debian-sid

- osutil/udev/.travis.yml
- osutil/udev/go.mod
- osutil/udev/netlink/conn.go
- osutil/udev/netlink/conn_test.go
Update go-udev package with upstream; the project isn't very active and in fact there are just 3 commits since we imported it into osutil, but they just fixed https://github.com/pilebones/go-udev/issues/3 which is good too have.
Updated with:
```
git subtree pull --prefix=osutil/udev http://github.com/pilebones/go-udev master
```
> osutil: update go-udev package

- cmd/libsnap-confine-private/cgroup-support.c
> cgroup-support.c: fix link to CGROUP DELEGATION

- interfaces/builtin/desktop.go
- interfaces/builtin/desktop_legacy.go
- interfaces/builtin/unity7.go
This allows access to e.g. the "Inhibited" property in KDE Plasma 5.16+ that indicates
whether "Do not disturb" mode is enabled.
---
This is for example used by Telegram to turn off own notification popups and sounds when notifications are inhibited.
> interfaces/builtin: Allow DBus property access on org.freedesktop.Notifications

- tests/main/snap-network-errors/task.yaml
Centos 7 doesn't seem to have any local DNS caching, so just skip the part of
the test that flushes the cache.
> tests/main/snap-network-errors: skip flushing dns cache on centos-7

- overlord/snapshotstate/backend/backend.go
- overlord/snapshotstate/backend/backend_test.go
- overlord/snapshotstate/snapshotstate.go
- overlord/snapshotstate/snapshotstate_test.go
The detection and handling of duplicated snapshot and returning the id of the original snapshot has a subtle bug, it doesn't return affected snap names correctly. This wasn't noticed because unit test wasn't good enough, and on the outside (snapshotstate.go line 341) it looked like it did return snap names. This PR fixes this.
> o/snapshotstate: fix returning of snap names when duplicated snapshot is detected

- gadget/install/content.go
- gadget/install/install.go
- gadget/internal/mkfs.go
- gadget/internal/mkfs_test.go
If we are creating partitions that are small such as ubuntu-save, then we have
code to specify the block size, but on some devices where the sector size is
not the default of 512 (and is instead 4K for example), we need to adjust the
block size when creating the filesystem to something that is at least the same
as the sector size. This is confirmed looking at the source of e2fsprogs at
https://github.com/tytso/e2fsprogs/blob/master/misc/mke2fs.c#L2151-L2156.
As such, pass the sector size along to where we call mkfs, and adjust the
specified block size to be the same as the sector size if the sector size is
larger than 1K when creating ext4 partitions. Similar code will be needed for
vfat partitions eventually as well.
This branch will be useful and necessary regardless of the direction we …
> gadget: pass sector size in to mkfs family of functions, use to select block sz

- tests/lib/tools/tests.pkgs.dnf-yum.sh
New using freeglut instead of libXft. freeglut is not installed by
default and it is available in all the systems.
This change is to fix:
+ dnf install -y robotfindskitten
...
No match for argument: robotfindskitten
Error: Unable to find a match: robotfindskitten
> tests: update test pkg for fedora and centos

- cmd/snap-repair/export_test.go
- cmd/snap-repair/runner.go
- cmd/snap-repair/runner_test.go
Use the bases and modes settings in repair assertions to filter repair
assertions when snap-repair is running.
The logic for modes is such that when modes is not set, on UC20 devices,
the assertion only applies to run mode devices. If modes include "run",
non-UC20 devices will also be included. To filter just on UC20 or UC18
devices, the bases setting should be set in assertion.
A spread test using test keys, etc. will be a followup.
> cmd/snap-repair: filter repair assertions based on bases + modes

- gadget/gadget.go
- gadget/gadget_test.go
- gadget/install/export_test.go
- gadget/install/install.go
- gadget/install/install_test.go
- gadget/install/partition_test.go
Rename LaidOutVolumeFromGadget to LaidOutSystemVolumeFromGadget, since now the
function returns the specific volume with all the ubuntu roles on it.
Additionally, allow multiple volumes and choose the right one by searching for
the SystemSeed role/partition.
Also move the old implementation of LaidOutVolumeFromGadget to a test-only
helper in the gadget/install package, since there are many tests in the install
package which use this helper with invalid gadget.yaml's that don't contain any
ubuntu roles and porting all of those tests to also include ubuntu roles is a
bit of a fool's errand.
This will fully enable using multiple volumes with UC20, albeit with all the ubuntu-*
roles/partitions on the same volume.
> gadget: enable multi-volume uc20 gadgets in  LaidOutSystemVolumeFromGadget; rename too

- .github/workflows/test.yaml
- bootloader/assets/assets.go
- bootloader/assets/assets_test.go
- bootloader/assets/assetstesting.go
- bootloader/withbootassettesting.go
- bootloader/withbootassettesting_test.go
- packaging/ubuntu-16.04/rules
Add support for injecting bootloader assets and corresponding snippets in test
builds of snapd. The code is only picked up when building with
`withbootassetstesting `tag.
The snippets are injected only when a specific marker file is present in the
same directory as the snapd binary. This way it is possible to control when a
snapd snap update will trigger an update of boot config assets of the grub
bootloader.
> bootloader/assets: support injecting bootloader assets in testing builds of snapd

- spread.yaml
Centos 8 is taking more than 60 minutes to run, we need more workers as
we have for the other systems.
> tests: use 6 spread workers for centos8

- osutil/stat.go
- osutil/stat_test.go
This can be used like DirExists, to determine if a file exists and is
definitively a regular file and not a socket or a symlink, etc.
Broken out from https://github.com/snapcore/snapd/pull/8699 and added unit tests
> osutil/stat.go: add RegularFileExists

- .github/workflows/test.yaml
- run-checks
Collecting test coverage data has significant time cost, as we're rerunning the
same test suite twice. There is no need to do so on subsequent test runs. even
with changed build tags.
> github, run-checks: do not collect coverage data on subsequent test runs

- cmd/libsnap-confine-private/error.c
- cmd/libsnap-confine-private/string-utils.c
- tests/nightly/sbuild/task.yaml
The i386 sid sbuild fails because apparently some sbuild code
is calling functions that are not implemented so errno is set
during the tests when it is not expected. This leads to test
failures because the die() code will append errno status if
errno is set. This commit fixes this and makes the nightly
test also run on i386.
> cmd: make string/error code more robust against errno leaking

- cmd/snap-repair/runner.go
- cmd/snap-repair/runner_test.go
This can be used by repair assertions to detect what mode they are running in,
if they are meant to be used in multiple modes. Eventually we may need to
include more information here, but note that repair assertion scripts run
unconfined, so they could also parse degraded.json themselves in the meantime
for example.
> cmd/snap-repair/runner.go: add SNAP_SYSTEM_MODE to env of repair runner

- cmd/libsnap-confine-private/error.c
- cmd/libsnap-confine-private/string-utils.c
- tests/nightly/sbuild/task.yaml
The i386 sid sbuild fails because apparently some sbuild code
is calling functions that are not implemented so errno is set
during the tests when it is not expected. This leads to test
failures because the die() code will append errno status if
errno is set. This commit fixes this and makes the nightly
test also run on i386.
> cmd: make string/error code more robust against errno leaking (2.49)

- interfaces/builtin/browser_support.go
This is used by chromium to try and optimize some render threads, and there are 
already more dangerous system calls allowed in the browser-sandbox: true policy.
Additionally, on some user's machines this system call is called relentlessly by
Chromium and thus ends up spamming the logs.
Fixes: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1900679
> interfaces/browser-support: allow sched_setaffinity with browser-sandbox: true

- .github/workflows/test.yaml
The idea of this change is to test how long unit tests take in focal
compared with xenial. The test already done shows a very big diff.
Xenial times:
ok  	github.com/snapcore/snapd/cmd/snap	23.130s
ok  	github.com/snapcore/snapd/cmd/snap	23.151s
ok  	github.com/snapcore/snapd/cmd/snap	23.133s
ok  	github.com/snapcore/snapd/cmd/snap	23.188s
ok  	github.com/snapcore/snapd/cmd/snap	23.138s
Focal times:
ok  	github.com/snapcore/snapd/cmd/snap	3.636s
ok  	github.com/snapcore/snapd/cmd/snap	3.511s
ok  	github.com/snapcore/snapd/cmd/snap	3.528s
ok  	github.com/snapcore/snapd/cmd/snap	3.569s
ok  	github.com/snapcore/snapd/cmd/snap	3.520s
> tests: run unit tests in Focal instead of Xenial

- gadget/install/install.go
- gadget/install/install_dummy.go
- gadget/install/install_test.go
- gadget/update.go
- overlord/devicestate/devicestate_install_mode_test.go
- overlord/devicestate/export_test.go
- overlord/devicestate/handlers_install.go
- tests/lib/uc20-create-partitions/main.go
- tests/main/uc20-create-partitions-encrypt/task.yaml
- tests/main/uc20-create-partitions-reinstall/task.yaml
- tests/main/uc20-create-partitions/task.yaml
This commit adds kernelRoot to install.Run() so that kernel
references can be resolved during install. No further functionality
is changed this is the first trivial split out of #9780 to make
the review easier.
> gadget,overlord: pass kernelRoot to install.Run()

- tests/unit/go/task.yaml
Drop a number of TRAVIS_* flags that are no longer used. Skip coverage
collection, since it's not really useful now.
> tests/unit/go: drop unused environment variables, skip coverage

- spread.yaml
Looks like the tests may be leaking a dbus-daemon process. Try to confirm that
by including a parent process PID in the output.
> spread: use full format when listing processes

- cmd/snap/cmd_known_test.go
- overlord/managers_test.go
- store/store.go
- store/store_action_fetch_assertions_test.go
- store/store_asserts.go
- store/store_asserts_test.go
- tests/lib/fakestore/store/store.go
- tests/lib/fakestore/store/store_test.go
Switch to v2/assertions endpoint.
This has small regression potential (not just on our side, but also store - we weren't using this endpoint before).
> store: switch to v2/assertions api

- interfaces/builtin/fwupd.go
As talked to fwupd upstream about ubuntu core integration, there were
few PR and conclusions to ensure that fwupd wil move on the confined
snap. The fwupd upstream asked for supporting fwupd interface to allow
fw updates on any classic system.
Reference:
https://github.com/fwupd/fwupd/issues/2513
https://github.com/fwupd/fwupd/pull/2571
> interfaces/fwupd: allow any distros to access fw files via fwupd

- cmd/snap-preseed/main.go
- cmd/snap-preseed/main_test.go
Initialize SanitizePlugsSlots method, otherwise we panic on readInfo if gadget is present, e.g.
```
panic: SanitizePlugsSlots function not set
goroutine 1 [running]:
github.com/snapcore/snapd/snap.glob..func1(0xc4200b2000)
/build/snapd/parts/snapd-deb/build/_build/src/github.com/snapcore/snapd/snap/info.go:1133 +0x3b
github.com/snapcore/snapd/snap.infoFromSnapYaml(0xc42012e000, 0x14c, 0x34c, 0xc420127a68, 0x0, 0x0, 0x55571e6392b0)
/build/snapd/parts/snapd-deb/build/_build/src/github.com/snapcore/snapd/snap/info_snap_yaml.go:227 +0x8cb
github.com/snapcore/snapd/snap.infoFromSnapYamlWithSideInfo(0xc42012e000, 0x14c, 0x34c, 0xc4204b2100, 0xc420127a68, 0x34c, 0x0, 0x0)
/build/snapd/parts/snapd-deb/build/_build/src/github.com/snapcore/snapd/snap/info.go:1074 +0x4f …
```
> cmd/snap-preseed: initialize snap.SanitizePlugsSlots for gadget in seeds

- cmd/snap-preseed/main_test.go
- seed/seed.go
- seed/seed16.go
- seed/seed16_test.go
- seed/seed20.go
- seed/seed20_test.go
Consequently drop EssentialMetaLoaderSeed.
Use caching to avoid re-verifying the essential snaps many times.
> seed: add LoadEssentialMeta to seed16 and allow all of its implementations to be called multiple times

- snap/info.go
- snap/info_test.go
- tests/main/services-after-before/task.yaml
- tests/main/snap-service-install-mode/task.yaml
When a snap has daemons that use before/after, and a hook tries to specify
snapctl restart of a single daemon, then the code here is subtly wrong in that
it thinks that there is an ordering cycle because we couldn't dequeue the other
services since they don't exist in the list of services provided to
SortSnapServices. As such, we should only sort the services that actually exist
in the list we were provided, we will handle errors around unknown services that
don't exist at all in the snap elsewhere in the stack before we get here.
> snap/info.go: ignore unknown daemons in SortSnapServices

- tests/core/fsck-on-boot/task.yaml
This error is faced running beta validation
+ [[ ubuntu-core-20-64 == ubuntu-core-20-arm-* ]]
+ umount '/run/mnt/ubuntu-seed/systems/*/snaps/snapd_*.snap'
umount: /run/mnt/ubuntu-seed/systems/*/snaps/snapd_*.snap: no mount
point specified.
Also, the test now is using the os-query to determine is the system is
running on arm
> tests: fix umount for snapd snap on fsck-on-boot test

- boot/assets.go
- boot/assets_test.go
For consistency with command line handling, we should not try do anything with
boot assets we successfully booted with if the system is not in run mode.
> boot: do not observe successful boot assets if not in run mode

- data/env/snapd.sh.in
When PATH contain spaces, which is a really bad idea anyway, the export will
most likely set it to a value up to the first space. Use quoting to prevent
that.
Note, shellcheck does not complain about that, but try this:
```
sh-5.1$ export foo=foo bar baz
sh-5.1$ echo $foo
foo
sh-5.1$ export foo="foo bar baz"
sh-5.1$ echo $foo
foo bar baz
sh-5.1$
```
Supersedes #9682
> data/env/snapd: use quoting in case PATH contains spaces

- osutil/buildid_test.go
The TestReadBuildGo test started to fail recently inside an
hirsute build environment with:
```
FAIL: buildid_test.go:131: buildIDSuite.TestReadBuildGo
buildid_test.go:142:
c.Assert(string(output), Equals, "")
... obtained string = "" +
...     "# command-line-arguments\n" +
...     "loadinternal: cannot find runtime/cgo\n"
... expected string = ""
```
Failure reason is unknown but only reproducible inside the particular
a dpkg-buildpackage build on 21.04 (with dh-golang).
Not reproducible outside the dpkg-buildpackage when running tests
in a normal hirsute environment.
This is a first stop-gap to fix the FTBFS until the root cause is
found.
Test build: https://launchpad.net/~mvo/+archive/ubuntu/tmp/+build/20976408
> osutil: skip TestReadBuildGo inside sbuild

- overlord/devicestate/devicemgr.go
- overlord/devicestate/devicestate_bootconfig_test.go
- overlord/devicestate/handlers_bootconfig.go
- overlord/managers_test.go
- overlord/snapstate/snapstate.go
- overlord/snapstate/snapstate_install_test.go
- overlord/snapstate/snapstate_test.go
- tests/nested/core20/boot-config-update/task.yaml
This is the final branch for updating the run time boot config. It adds a new task that performs the actual update. There's a related spread test that injects a new boot config asset and runs through the update.
> overlord/devicestate: task for updating boot configs, spread test

- asserts/asserts.go
- asserts/asserts_test.go
Introduce AtSequence struct that will get passed to new Pool functions, and will be an input for store actions (via ToResolve()). This resembles AtRevision except it is tailored for sequence assertions where we have sequence key only and sequence number is optional (sequence key is a primary key minus sequence number).
> asserts: introduce AtSequence

- cmd/snap-bootstrap/cmd_initramfs_mounts.go
- cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
- cmd/snap-bootstrap/initramfs_mounts_state.go
The current modeenv that is written from the initramfs is incomplete to the
extent that it doesn't accurately reflect what base and model are booted on the
system so when things like snap-repair try to determine device information using
only the modeenv, they fail.
This adds as much information as can be trivially gained from the initramfs
about the device/system. The current kernel snaps, trusted boot assets and 
kernel command lines can probably also be determined at this point and included
in the modeenv as well, but it's unclear if that's the direction we want to go
with the modeenv we write here.
This will unblock us from enabling the recover portion off the snap-repair test in https://github.com/snapcore/snapd/pull/9884
I milestoned this for 2.49 so that we could get this picked up …
> cmd/snap-bootstrap/initramfs-mounts: write realistic modeenv for recover+install

- client/clientutil/snapinfo.go
- client/clientutil/snapinfo_test.go
- overlord/servicestate/servicestate.go
- overlord/servicestate/servicestate_test.go
- tests/main/snap-services/task.yaml
The primary purpose of this branch is to add a "dbus-activated" note to services in the output of `snap services`.  This involved a bit of extra work behind the scenes:
1. update ServiceDecorator in `overlord/servicestate` to add AppActivator entries for each bus name the service activates on.  I've set the Name field to the bus name and Type to "dbus".  I'm setting Enabled and Active to true, since we always install the D-Bus service activation files for the snap, and there is no real equivalent to systemd's "installed but not enabled" state.
2. update ClientAppInfoNotes in `client/clientutil` to convert the presence of a "dbus" activator to a "dbus-activated" note.
I've also updated ServiceDecorator to only try to decorate system daemons, since the current code will fail in the presence …
> overlord/servicestate: expose dbus activators of a service

- tests/lib/prepare.sh
This ensures that if you are running qemu locally with SPREAD_QEMU_GUI=1 you can
see the console output, it seems that things are busted right now trying to run
UC20 spread tests via QEMU locally, so this at least shows us that something is
segfaulting in reflash.sh since you can see the console.
> tests/lib/prepare.sh: add another console= to the reflash magic grub entry

- interfaces/builtin/desktop_test.go
Mock distribution which triggers a known behavior in the fontconfig cache
handling unit tests, so that the tests execute correctly on all supported
platforms.
> interfaces/builtin: mock distribution in fontconfig cache unit tests

- cmd/snap-bootstrap/cmd_initramfs_mounts.go
Fix typo in function name. Noticed when going through the initramfs code in snap-bootstrap.
> cmd/snap-bootstrap/initramfs-mounts: fix typo in func name

- tests/nested/core20/boot-config-update/task.yaml
The test requires some additional test features to be enabled when snapd is
built. For simplicity look at the TRUST_TEST_KEYS flag which is false when such
features are not present.
> tests/nested/core20/boot-config-update: skip when snapd was not built with test features

- tests/main/snap-services/task.yaml
- wrappers/services.go
- wrappers/services_gen_test.go
Breaking out from PR #9872, this PR removes the `[Install]` section of timer and dbus activated services.  While snapd never tried to enable these services, the presence of the section meant that systemd would report the units to be in the `disabled` state instead of `static`.
Removing the `[Install]` section also reduces the chance of unexpected behaviour should a user call `systemctl enable` on one of these units.
> wrappers: don't generate an [Install] section for timer or dbus activated services

- boot/boot_test.go
- boot/bootchain_test.go
- boot/seal_test.go
Use a common helper for mocking boot assets in cache. Cherry picked from recovery systems management branch.
> boot: use a common helper for mocking boot assets in cache

- packaging/fedora/snapd.spec
Update the reference RPM spec used in Fedora CI with actual downstream
packaging.
Ideally we should land it after #9925 lands.
> packaging/fedora: sync with downstream packaging in Fedora

- cmd/snap-confine/snap-confine.apparmor.in
On Yocto/Poky `/var/log` and `/var/tmp` are symlinks to `/var/volatile/log` and `/var/volatile/tmp` respectively. Which obviously means that snapd is not able to write to those directories.
We have been using this patch https://github.com/s-things/meta-snappy/blob/master/recipes-support/snapd/files/0001-poky-apparmor-fix.patch for 4 months without a problem. Without this, snaps don't really work.
> snap-confine.apparmor.in: support tmp and log dirs on Yocto/Poky

- cmd/snap-gdb-shim/snap-gdbserver-shim.c
- cmd/snap/cmd_run.go
- tests/main/snap-run-gdbserver/task.yaml
The `snap run --experimental-gdbserver` option is available
since a while and we got no negative feedback so far. Given
that it's also superior to the `snap run --gdb` option this
PR make it available with the *experimental* prefix.
The old `snap run --experimental-gdbserver` option is still
available for compatbility and can be removed after some
releases.
> snap: rename gdbserver option to `snap run --gdbserver`

- wrappers/services_test.go
The tests assumed that the system is using $(root)/snap, but os-release isn't
mocked in the tests, so that path becomes incorrect on hosts not using /snap.
> wrappers: use proper paths for mocked mount units in tests

- overlord/snapstate/check_snap.go
- overlord/snapstate/check_snap_test.go
This came up recently when we ended up doing a sub version release of snapd
2.48.2.1, and we wanted snaps to depend on this, but we couldn't make them do it
because the parsing regex gode gave up after 2.48.2. So make it fully support
any number of subversions in the hope that we never have to use this.
If folks think this will never become a problem, I call to the stand runC's release 
page: https://github.com/opencontainers/runc/releases . I hope and pray we never
get there, but who knows, it is better to have more support and never use it than 
need the support and not have it.
> o/snapstate/check_snap.go: add support for many subversions in assumes snapdX..

- interfaces/seccomp/template.go
This was recently introduced as an optimization to Go 1.15, and so apps that
start compiling may start to try and use it.
Note that Go 1.15 does currently fall back to using other methods if copy_file_range
returns EPERM so that apps that get denied usage of copy_file_range will fallback
to potentially slower implementations. (originally upon Go 1.15 release there
was not a fallback implementation and the app would just crash returning a non-nil
error up the stack).
See https://github.com/golang/go/issues/40893 and
https://go-review.googlesource.com/c/go/+/249257/ for more details on the Go
issue and the fallback implementation.
> interfaces/seccomp/template.go: allow copy_file_range

- asserts/database.go
- asserts/database_test.go
findAccountKey was alread checking this but
this is an additional defense and makes CheckSignature a more
robust standalone helper if used that way
> asserts: repeat the authority cross-check in CheckSignature as well

- gadget/gadget.go
- gadget/gadget_test.go
- gadget/layout.go
- gadget/layout_test.go
- gadget/mountedfilesystem_test.go
This commit improves the error messages and the error detection
for incorrect gadget assets content sources.
Followup for https://github.com/snapcore/snapd/pull/9875#discussion_r568176099
> gadget: improve error handling around resolving content sources

- packaging/snapd.mk
The snapd.mk is a packaging helper that is currently used by openSUSE only. Once
Go 1.16, which defaults to expecting modules, lands and becomes default in
Tumbleweed, snapd builds will fail. Make sure to disable the modules
functionality before that happens.
> packaging: disable Go modules in snapd.mk

- packaging/opensuse/snapd.spec
Sync with downstream packaging in openSUSE.
> packaging/opensuse: sync with openSUSE packaging

- overlord/configstate/configcore/handlers.go
- tests/lib/prepare.sh
Splitting the script into two parts allows us to execute the second part where
we totally obliterate the hard disk without having any dangling reference to
/dev/{s,v}da from /bin/sh, because we use busybox in /tmp. Sometimes we see
problems locally with this reflash.sh script segfaulting because probably some
part of it's memory is mapped to a file or something that got deleted.
Using busybox, a static executable, entirely located in RAM via tmpfs avoids
this.
> tests/lib/prepare.sh: split reflash.sh into two parts

- data/selinux/snappy.te
The SELinux reference policy has a new set of access vectors for watch*. The
support in core policy landed in
https://github.com/fedora-selinux/selinux-policy/pull/546 on 07.02.2021.
Snapd sets up /var/lib/snapd/dbus-1/services to be watched by the system dbus.
However, dbus trying to watch those directories triggers new watch permissions
to be checked. The snappy.te policy does not allow this access, thus on Rawhide
dbus fails like this:
```
systemd[1]: Starting D-Bus System Message Bus...
dbus-broker-launch[7728]: ERROR dirwatch_add @ ../src/util/dirwatch.c +122: Permission denied
dbus-broker-launch[7728]:       launcher_load_service_dir @ ../src/launch/launcher.c +763
dbus-broker-launch[7728]:       launcher_load_services @ ../src/launch/launcher.c +978
dbus-broker-launch[7728]: …
```
> data/selinux: allow system dbus to watch /var/lib/snapd/dbus-1

- .github/labeler.yml
Auto labeler seems to be removing the labels unexpectedly, see:
- https://github.com/snapcore/snapd/pull/9940#event-4345279407 label was added
manually when opening a PR and later removed by bot
- https://github.com/snapcore/snapd/pull/9943#event-4346822699 modified files
match the label, but labeler removed 'Run nested' label
> github: temporarily disable action labeler due to issues with labels being removed

- boot/boot.go
- boot/boot_test.go
- boot/bootstate20.go
- boot/makebootable.go
- boot/makebootable_test.go
- boot/modeenv.go
- boot/modeenv_test.go
- boot/systems.go
- tests/nested/core20/tpm/task.yaml
Introduce good_recover_systems into modeev. Provide basic compatibility handling.
> boot: introduce good recovery systems, provide compatibility handling

- tests/main/interfaces-broadcom-asic-control/task.yaml
This is because using external backend the test is failing like this:
+ for file in "$config" "$vendor" "$device" "$subsystem_vendor"
"$subsystem_device"
+ '[' -n
/sys/devices/pci0000:00/0000:00:1f.2/ata1/link1/ata_link/link1/device
']'
+ test-snapd-sh.with-broadcom-asic-control-plug -c 'cat
/sys/devices/pci0000:00/0000:00:1f.2/ata1/link1/ata_link/link1/device'
cat:
'/sys/devices/pci0000:00/0000:00:1f.2/ata1/link1/ata_link/link1/device':
Is a directory
> tests: find files before using cat command when checking broadcom-asic-control interface

- tests/core/uboot-unpacked-assets/task.yaml
The idea is to get the kernel.img from
/run/mnt/ubuntu-seed/systems/*/kernel/
This is to fix the following error when using external backend
2021-02-17 05:16:45 Error executing
external:ubuntu-core-20-arm-32:tests/core/uboot-unpacked-assets:kernelimg
(external:ubuntu-core-20-arm-32) :
os.query is-core20
find '/run/mnt/ubuntu-seed/systems/*/kernel/*-kernel_*.snap/' -name
'kernel.img*'
find: ‘/run/mnt/ubuntu-seed/systems/*/kernel/*-kernel_*.snap/’: No such
file or directory
output=
> tests: use new path to find kernel.img in uc20 for arm devices

- spread.yaml
Snapd does not support go modules yet, but some distros already started shipping
Go 1.16 which defaults to enabling the modules. Explicitly disable modules in
spread environment until snapd is ready.
Also, piggyback a spread ref bump.
> spread: disable Go modules support in environment 

- snap/info_snap_yaml_test.go
Go 1.16 has moved some bits from the os to the fs package, os.FileMode was among
those. The test used a hardcoded type name which no longer matches the returned
error message.
> snap: fix unit tests on Go 1.16

- interfaces/apparmor/backend.go
- interfaces/apparmor/backend_test.go
- interfaces/apparmor/export_test.go
Apparmor downgrade was automatically enabled when the running kernel
supported some, but not all of the features. Since the complete set was
never upstreamed, this effectively meant that users had less features
than they otherwise would have.
Since apparmor is still reported as "partial", nothing changes from the
point of view of not sending any misleading messages. For certain
classes of snap packages, this improves the effective confinement on
systems such as Debian or openSUSE Leap.
Perfect confinement is still way off, this doesn't change that.
> interfaces: remove apparmor downgrade feature

- overlord/snapshotstate/backend/backend.go
- overlord/snapshotstate/snapshotstate_test.go
When tar fails with a fatal error, include the last message it prints, as it
will likely contain the actual error.
Related to https://bugs.launchpad.net/stuttgart/+bug/1915781, where the root
cause of the problem was caused by the directory getting modified while tar was
processing it.
Supersedes #9941
> overlord/snapshotstate: include the last message printed by tar in the error

- tests/lib/pkgdb.sh
- tests/main/preseed-reset/task.yaml
- tests/main/preseed/task.yaml
This is a simple fix for preseed and dbus tests on 21.04
> tests: fix for preseed and dbus tests on 21.04

- tests/lib/reset.sh
- tests/regression/lp-1910456/task.yaml
This ensures that future tests that are run on the same system such as
tests/main/classic-confinement-not-supported do not fail since they expect the
/snap symlink to be absent by default.
Also cleanup some other things and address TODOs from when the test was written
for 2.48 since we have better os.query support on master now.
See for example https://pastebin.ubuntu.com/p/T3vT49KpFB/ where this failed.
Also make a script more verbose to aid future debugging like in https://pastebin.ubuntu.com/p/sMSy9FFRgy/ (although this specific failure is a bit of an orthogonal question if we should be saving /var/lib/snapd/save between test runs in UC20 spread, but the difficulty debugging remained).
> tests/regression/lp-1910456: cleanup the /snap symlink when done 

- tests/main/lxd-mount-units/task.yaml
- tests/main/lxd/task.yaml
Currently the lxd image for 21.04 is not published and when we use the
image for 20.10 then the snapd cannot be built because dependencies
constrains like:
The following packages have unmet dependencies:
snapd : Depends: libc6 (>= 2.33) but 2.32-0ubuntu3 is to be installed
E: Unable to correct problems, you have held broken packages.
> tests: disable lxd tests for 21.04 until the lxd images are published for the system

- interfaces/builtin/x11.go
This is PR is based on discussions in this forum thread:
https://forum.snapcraft.io/t/firefox-wouldnt-run-on-plasma-wayland/22779/5?u=jamesh
Similar to the way GNOME's Wayland session works, KDE Plasma writes out an Xauthority file for its Xwayland instance using a randomly named file, and then points clients at it via the `XAUTHORITY` environment variable.  It uses files named like `$XDG_RUNTIME_DIR/xauth_*`:
https://github.com/KDE/kwin/blob/553b6d39c69fccbb6854bb4a35a6bba889ad342d/src/xwl/xwayland.cpp#L102-L104
This PR adjusts the `x11` interface's AppArmor rules to allow reading files matching this pattern, similar to what we do for GNOME.
> interfaces: allow reading the Xauthority file KDE Plasma writes for Wayland sessions

- .github/labeler.yml
- .github/workflows/labeler.yaml
This was suggested in the upstream bug at https://github.com/actions/labeler/issues/104
Also apply the YAML linter that my editor applies to every YAML file :-)
> .github/workflows/labeler.yaml: try work-around to not sync labels

- interfaces/hotplug/deviceinfo_test.go
- interfaces/repo_test.go
- overlord/devicestate/devicestate_serial_test.go
For some reason all of a sudden these were flagged by the latest/stable go snap
in CI:
Checking for ineffective assignments
/home/runner/work/snapd/snapd/src/github.com/snapcore/snapd/interfaces/repo_test.go:2088:2: ineffectual assignment to conn
/home/runner/work/snapd/snapd/src/github.com/snapcore/snapd/interfaces/hotplug/deviceinfo_test.go:88:2: ineffectual assignment to di
/home/runner/work/snapd/snapd/src/github.com/snapcore/snapd/overlord/devicestate/devicestate_serial_test.go:664:2: ineffectual assignment to device
No idea why these all of a sudden starting failing, but see https://github.com/snapcore/snapd/runs/1983645493?check_suite_focus=true for an example failure
> many: fix new ineffassign warnings

- mkversion.sh
The logic around concatenating the version from dpkg changelog and git revision
seems to be incorrect on systems where dpkg-parsechangelog is not installed. For
instance, on Arch, the version would end up being: `+git1000.gb5e86eb`. With the
fix it is `2.49+git472.gb9c4e04220-dirty`.
> mkversion: check that version from changelog is set before overriding the output version

- interfaces/builtin/opengl.go
Add read access to sysfs bits from the Xilinx zocl DRM driver, which
are used to retrieve information about the hardware. See
https://github.com/Xilinx/XRT/tree/master/src/runtime_src/core/edge/drm.
> interfaces: opengl: add Xilinx zocl bits

- cmd/snap-bootstrap/triggerwatch/evdev.go
- cmd/snap-bootstrap/triggerwatch/triggerwatch.go
While debugging an issue of input devices, I found that these returns don't use correct errors.
This PR is used to fix them.
> cmd/snap-bootstrap/triggerwatch: fix returning wrong errors

- overlord/snapshotstate/backend/backend.go
- overlord/snapshotstate/snapshotstate_test.go
- strutil/matchcounter.go
- strutil/matchcounter_test.go
Keep some last lines of the tar output.
This is an improvement over #9953 as it correctly handles a case when more than N lines are present in tar output, and correctly keeps the last couple of line.
> ovelord/snapshotstate: keep a few of the last line tar prints before failing

- asserts/account_test.go
- asserts/database.go
- asserts/model_test.go
- asserts/snap_asserts_test.go
We occasionally get the following backtrace in the tests:
```
PANIC: api_users_test.go:762: userSuite.TestPostCreateUserFromAssertionNoModel
... Panic: cannot add test assertions: model assertion timestamp outside of signing key validity (key valid since "2021-02-23 11:10:41 +0000 UTC") (PC=0x45CF4A)
/snap/go/2117/src/runtime/panic.go:491
in gopanic
/home/runner/work/snapd/snapd/src/github.com/snapcore/snapd/overlord/assertstate/assertstatetest/add_many.go:38
in AddMany
api_users_test.go:776
in userSuite.TestPostCreateUserFromAssertionNoModel
/snap/go/2117/src/reflect/value.go:302
in Value.Call
/snap/go/2117/src/runtime/asm_amd64.s:2337
in goexit
OOPS: 439 passed, 1 skipped, 1 PANICKED
--- FAIL: Test (9.62s)
FAIL …
```
> asserts: include the assertion timestamp in error message when outside of signing key validity range

- daemon/api_console_conf_test.go
- daemon/api_debug_pprof_test.go
- daemon/api_debug_seeding_test.go
- daemon/api_debug_test.go
- daemon/export_api_debug_seeding_test.go
- daemon/export_api_debug_test.go
- daemon/export_test.go
still todo later: clean up what is left in api.go and api_test.go
there are other non api_ tests also still in daemon
> daemon: move the last api_foo_test.go to daemon_test

- daemon/api_users.go
- daemon/api_users_test.go
- overlord/configstate/configcore/runwithstate.go
- overlord/configstate/configcore/users.go
- overlord/configstate/configcore/users_test.go
the option if set to false disables automatic user creation on assertion
auto-import
it is processed early which means its setting available
before snapd starts serving users API requests
> daemon,o/c/configcore: introduce users.create.automatic

- asserts/pool.go
- asserts/pool_test.go
Use Fetcher in AddSequenceToUpdate. Fix addUnresolvedSeq not returning error. Also addresses some cleanups suggested by @anonymouse64 in #9930 
This replaces #9964 to have clean history.
> asserts: use Fetcher in AddSequenceToUpdate

- bootloader/lkenv/lkenv_test.go
- bootloader/lkenv/lkenv_v2.go
- include/lk/snappy_boot_v2.h
Add try_recovery_system and recovery_system_status to the boot variables tracked inside
little kernel bootloader's environment.
As suggested in https://github.com/snapcore/snapd/pull/9942#discussion_r583916600
> bootloader/lkenv: add recovery systems related variables

- cmd/snap/cmd_recovery.go
Fixes tab output error in 'snap recovery' (due to potential special character) by adding call to _fillerPublisher_ function.
Old output:
```
$ sudo snap recovery
Label     Brand                Model                      Notes
20201202  canonical✓  ubuntu-core-20-amd64-beta  current
```
New output:
```
$ sudo ./snap.new recovery
Label     Brand       Model                      Notes
20201202  canonical✓  ubuntu-core-20-amd64-beta  current
```
> cmd/recovery: small fix for `snap recovery` tab output

- packaging/ubuntu-16.04/rules
- tests/unit/go/task.yaml
We already set GO111MODULE=off in spread.yaml, but for some reason that's not
sufficient when building the deb in hirsute, which now has Go 1.16 and defaults
to using modules. So explicitly disable it for all the manual go commands we run
here.
This should at least get us running tests on hirsute again, though there are still some failing there AIUI.
> packaging/ubuntu-16.04/rules: turn modules off explicitly

- interfaces/builtin/wayland.go
- interfaces/builtin/x11.go
Xwayland was the expected user of these rules, however that was based on a
misunderstanding, since the compositor will instead be the one writing out Xauth
cookie before running XWayland.
These rules should instead be provided to the x11 slot implementation, such that
the Wayland compositor (such as mutter) would write this file would slot x11 and
then be provided write access to these files. 
However, we don't add those files yet since it's unclear what a real user like
gnome-shell will actually need to do, so instead just leave a TODO in the 
policy about adding such rules.
See discussion at https://github.com/snapcore/snapd/pull/9952#discussion_r580839553
> interfaces/wayland: rm Xwayland Xauth file access from wayland slot 

- osutil/export_test.go
- osutil/settime.go
- osutil/settime_32bit.go
- osutil/settime_64bit.go
- osutil/settime_test.go
We need to use syscall.Settimeofday to set the time of day from snap-bootstrap
in the initrd, but syscall.Timeval has architecture dependent definitions, on
32-bit systems it uses int32's, but on 64-bit systems it uses int64's, so we
have to split up the actual implementation between two files.
The unit testing here is a bit pointless, since we can't actually run the real syscall 
without being root or having CAP_SYS_TIME, so the unit test really just confirms
that our logic of changing time.Time{} into syscall.Timeval{} is correct.
> osutil: add SetTime() w/ 32-bit and 64-bit implementations

- packaging/debian-sid/snapd.maintscript
- packaging/ubuntu-14.04/snapd.maintscript
- packaging/ubuntu-16.04/snapd.maintscript
- tests/main/upgrade-sudoers-conffile-removal/task.yaml
- tests/upgrade/sudoers-conffile-removal/task.yaml
We dropped shipping /etc/sudoers.d/99-snapd.conf in PR#8885 but
did not clean up properly in the debian/* packaging. This is a
conffile in debian packaging terms so it needs special handling.
Fortunately the dpkg-maintscript-helper makes this easy(ish)
now with debian/<pkg>.maintscript
This fixes LP: #1915156
> packaging: drop 99-snapd.conf via dpkg-maintscript-helper

- tests/main/lxd/prep-snapd-in-lxd.sh
We _still_ continue to see errors like
```
+ apt update
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
E: Type 'xenial-security' is not known on line 50 in source list /etc/apt/sources.list
E: The list of sources could not be read.
```
executing this test, so rather than just be confused about what apt says is
wrong about the file, instead just dump that file before every apt operation, in
the hopes that it eventually fails again and we can see what the output was
right before the apt operation fails.
> tests/main/lxd/prep-snapd-in-lxd.sh: dump contents of sources.list

- overlord/snapshotstate/backend/backend.go
- overlord/snapshotstate/backend/backend_test.go
- tests/main/snapshot-basic/task.yaml
Create snapshots directory (in case it doesn't exist, which is a case on a virgin device) on import.
Fixes LP: #1917617
> o/snapshotstate: create snapshots directory on import

- tests/unit/go/task.yaml
This is a backport of PR#9979 to 2.49. The second commit did not cleanly cherry-pick so I included the relevant parts.
Pushing as a PR to get a full spread run to ensure there are no other test fixes missing for 2.49
> tests: turn modules off explicitly in spread go unti test (2.49)

- tests/core/netplan/task.yaml
- tests/lib/prepare.sh
This fixes running the netplan test on UC20 in spread and possibly may fix other subtle bugs in spread that we didn't notice.
This is now a pre-req for https://github.com/snapcore/snapd/pull/9784, so that we can actually test netplan on UC20.
> tests/lib/prepare.sh: use /etc/group and friends from the core20 snap 

- client/export_test.go
- client/snapctl.go
- client/snapctl_test.go
This is a followup for PR#9692 where it was suggested that the
new "snapctl" support for reading from stdin should have some
protection against reading too much data. See
https://github.com/snapcore/snapd/pull/9692#discussion_r530255566
This starts with a 4MB limit.
> client: protect against reading too much data from stdin

- boot/assets.go
- boot/assets_test.go
- boot/boot_test.go
- boot/export_test.go
- boot/makebootable.go
- boot/modeenv.go
- boot/modeenv_test.go
- boot/seal_test.go
- boot/systems_test.go
We need this to be exported to be able to serialize a trusted asset observer
across multiple tasks during UC20 install mode. The only state that is not
currently observable from filesystem state are the keys and the boot asset maps
for tracked assets here. The keys can easily be saved in state.json to
serialize, but the boot asset map needs to be exported to be able to serialize
it in the state.json across tasks.
This is the first of 4+ PR's which will enable adding an factory hook to be run 
during install mode.
> boot: export bootAssetsMap as AssetsMap

- spread.yaml
The idea is to avoid using any tool until the code is unpacked. The
os.query tool is being used but it fails and the systems are not
properly configured.
This is an example of the content of the bin directory included in path
before unpack the current.delta file
sergio@cachiomachine:~/workspace/snapcore/snapd$ spread -debug
google:fedora-32-64:tests/regression/rhbz-1708991
2021-03-08 22:19:29 Project content is packed for delivery (208.03KB).
2021-03-08 22:19:29 If killed, discard servers with: spread
-reuse-pid=477473 -discard
...
2021-03-08 22:20:18 Starting shell to debug...
google:fedora-32-64 ...# os.query is-fedora && echo pepe
bash: os.query: command not found
google:fedora-32-64 ...# echo $PATH
/home/gopath/bin:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin: …
> tests: revert os.query usage in spread.yaml

- boot/seal.go
- boot/seal_test.go
Tweak the inputs for resealing the keys. With introduction of a tried recovery
system tracked in the current recovery systems list, it was decided that only
the run key shall be resealed for those systems. The recovery keys, are resealed
for a list of known good recovery systems.
> boot: reseal the run key for all recovery systems, but recovery keys only for the good ones

- gadget/gadget_test.go
We used the `device-tree{,-origin}` key during the Ubuntu Core
15.04 development. It is not used since but got cargo culted
in our tests. This commit removes them now.
> gadget: remove `device-tree{,-origin}` from gadget tests

- cmd/snap-seccomp/syscalls/syscalls.go
The snap-seccomp helper maintains a list of all know syscalls supported by
libseccomp. We catch when the internal list diverges from upstream
libseccomp in a tests/main/snap-seccomp-syscalls spread test.
Upstream libseccomp has been updated with close_range syscall [1],
update the internal list.
[1] https://github.com/seccomp/libseccomp/commit/c305ef351bc9b254f3f65359ca2e6435bb920752
> snap-seccomp: add new `close_range` syscall

- daemon/api_validate.go
- daemon/api_validate_test.go
- daemon/export_api_validate_test.go
- overlord/assertstate/assertstate.go
- overlord/assertstate/assertstate_test.go
- overlord/assertstate/bulk.go
- overlord/assertstate/validation_set_tracking.go
- tests/main/snap-validate-basic/task.yaml
Handle `snap validate --monitor ...`. This isn't full monitor mode implementation yet, e.g. refreshing of assertions via pool is missing and will be done separately.
Disable snap-validate-basic spread test for now as it was only usable with early (dummy) implementation, it will need to be fleshed out and enabled once all the branches land and the feature is usable.
> api: validation sets monitor mode

- daemon/api_validate.go
- daemon/api_validate_test.go
Followup to #9922 suggested by @pedronis: fallback for `snap validate account/name=seq` if the assertion is not in the store, but was ack'ed locally.
> api: local assertion fallback when it's not in the store

- tests/main/uc20-create-partitions-encrypt/task.yaml
- tests/main/uc20-create-partitions-reinstall/task.yaml
- tests/main/uc20-create-partitions/task.yaml
Fix the cleanup after a bunch of uc20-create-partitions tests. Make sure that
mountpoints are unmounted before trying to remove the loopback device. Verify
that loopback device is gone.
Ideally we should write a test invariant that verifies that no new mounts or loopback devices are present.
> tests/main/uc20-create-partitions: fix tests cleanup

- interfaces/apparmor/template.go
Allow reading how much entropy is available in the kernel. This is a
miscellaneous access that some applications, eg. those that generate random data
may need. Note that the AppArmor base abstraction already allows reading from
/dev/{u,}random, and our base template allows writing to it. Thus, even without
knowing how much entropy is available, it is possible to drain it.
See [1] for more details.
1. https://forum.snapcraft.io/t/allow-access-to-proc-sys-kernel-random-entropy-avail/23275
> interfaces/apparmor: allow reading /proc/sys/kernel/random/entropy_avail

- interfaces/builtin/docker_support.go
- interfaces/builtin/kubernetes_support.go
- interfaces/builtin/kubernetes_support_test.go
This will enable new versions of docker to use the new version of go-systemd
which communicates with journald via an automatic/empty address specification on
a SOCK_DGRAM socket.
This access already exists in the kubernetes-support interface as the
autobind-unix flavor, so update that comment to reflect that we should only use
the new syntax when AppArmor userspace is vendored into snapd.
See also https://github.com/coreos/go-systemd/issues/331
> interfaces/docker-support: add autobind unix rules to docker-support

- tests/lib/prepare-restore.sh
- tests/lib/reset.sh
The idea of this change is to validate all the tests restore the environment during the restore phase.
So each test should start in a clean environment, then prepare, execute and restore the test, and then clean up the environment and check the invariants, so the next test can run in a clean environment as well.
> tests: run the reset.sh helper and check test invariants while the test is restored

- interfaces/builtin/allegro_vcu_test.go
- interfaces/builtin/media_control_test.go
Fix running the interfaces unit tests on a distro that uses /usr/libexec/snapd.
Instead of mocking it in test set up, fix it in the tests, so we know that the
tests use proper paths.
> interfaces/builtin: update unit tests to use proper distro's libexecdir

- asserts/batch.go
- asserts/batch_test.go
- seed/helpers.go
- seed/seed.go
- seed/seed16.go
- seed/seed20.go
- seed/seed20_test.go
- seed/seedtest/seedtest.go
ReadSystemEssentialAndBetterEarliestTime retrieves in one go
information about the model and essential snaps of the given types
for the Core 20 recovery system seed specified by seedDir and label
(which cannot be empty).
It can operate even if current system time is unreliable by taking
a earliestTime lower bound for current time.
It returns as well an improved lower bound by considering appropriate
assertions in the seed.
> seed: ReadSystemEssentialAndBetterEarliestTime

- overlord/snapstate/handlers.go
We got some reports that snapd during download consumes a lot of
CPU. It turns out this was introduced with PR#6356 when we add
re-refresh on epoch bumps. This commit mitigates the effect.
Fixing this for good will require some work in the taskrunner.
But with this change I see on my machine that download only
takes ~14% compared to the 56% it took before.
> snapstate: reduce reRefreshRetryTimeout to 1/2 second

- overlord/configstate/configcore/picfg.go
Required for supporting custom resolutions/working with certain devices.
See https://www.raspberrypi.org/documentation/configuration/config-txt/video.md
Yes, I did sign it before.
> o/configstate/configcore: add hdmi_timings to pi-config

- boot/systems_test.go
Extend the try recovery system helper unit tests to demonstrate that run key is
resealed for current-recovery-systems, while the recovery keys are only resealed
for the good ones.
> boot: extend set try recovery system unit tests

- cmd/snap/cmd_pack.go
We now fully support using compression lzo and not just xz, so there's no
reason to continue to hide the compression option here.
> cmd/snap/pack: unhide the compression option

- overlord/devicestate/devicemgr.go
- overlord/devicestate/devicestate_test.go
- overlord/devicestate/fde/fde.go
- overlord/hookstate/ctlcmd/fde_setup_test.go
- tests/lib/fde-setup-hook/fde-setup.go
The spec states that the encryption key in the fde-setup-request JSON structure
that is passed to the hook via `snapctl` should be a string encoded as base64.
We missed the fact that this code was not doing that, since it was refactored
rather late in the cycle, and the existing test (and also the real world hook)
are both written in Go, and thus take advantage of Go's advanced JSON decoding
which handles both the case of
```json
{
...
"key": [96, 34, 56, 54, ... ],
...
}
```
```json
{
...
"key": "ABCDE==",
...
}
```
the same when decoding. Actually because of this fact, we can in fact change the
request we send to conform to the spec without breaking the existing client and
test.
Also expand the existing spread test to check that the JSON sent to the hook via snapctl is indeed decodable …
> o/{device,hook}state: encode fde-setup-request key as base64 string 

- daemon/api_users_test.go
Occasionally in the Github test runs we observe this problem:
```
PANIC: api_users_test.go:1074: userSuite.TestPostCreateUserFromAssertionNoModel
... Panic: cannot add test assertions: model assertion timestamp "2021-03-23 22:31:21 +0000 UTC" outside of signing key validity (key valid since "2021-03-23 22:31:22 +0000 UTC") (PC=0x439C58)
/snap/go/7221/src/runtime/panic.go:965
in gopanic
/home/runner/work/snapd/snapd/src/github.com/snapcore/snapd/overlord/assertstate/assertstatetest/add_many.go:38
in AddMany
api_users_test.go:1088
in userSuite.TestPostCreateUserFromAssertionNoModel
/snap/go/7221/src/reflect/value.go:337
in Value.Call
/snap/go/7221/src/runtime/asm_amd64.s:1371
in goexit
OOPS: 444 passed, 1 PANICKED
--- …
```
> daemon: fix signing key validity timestamp in unit tests

- client/client_test.go
- cmd/snap/cmd_services_test.go
- cmd/snap/cmd_snap_op_test.go
The client timeouts in unit tests are too aggressive. Specifically when running
on OBS, I often see a bunch of failures due to client timeouts being exceeded.
> cmd/snap: use less aggressive client timeouts in unit tests

- tests/main/cgroup-tracking/task.yaml
The test needs to retry a bit to make sure the process is removed.
Sometimes it takes just a bit and if we check the number of cgroup
processes right after the process is killed then it fails.
The error is easy to reproduce on centos8.
The tests sequence which makes the test fail is the following:
https://paste.ubuntu.com/p/r7CxTVYb5B/
> tests: fix cgroup-tracking test

- tests/lib/fde-setup-hook/fde-setup.go
The key data should be decodable both as a []byte in Go directly (using the
standard library's automatic conversion of base64 encoded strings into []byte),
as well as manually by reading the base64 string and decoding out of band from
the Go standard library.
We added code to do this for the fde-setup-request, but we should also do this
check for the fde-reveal-key structure too just to be extra safe around this
area.
> tests/lib/fde-setup-hook: also verify that fde-reveal-key key data is base64

- tests/core/fsck-on-boot/task.yaml
If the snapd snap was mounted in the initrd because this is the first boot with
of a UC20 system, then /run/mnt/snapd will be mounted either from the
`/run/mnt/ubuntu-seed/snaps/snapd_*.snap` or possibly from
`/run/mnt/ubuntu-seed/systems/<sys>/snaps/snapd_*.snap` depending on how the
system was constructed. To handle this ambiguity, just unmount the mountpoint
directly and avoid issues like:
```
Error: 2021-03-18 16:42:18 Error executing google:ubuntu-core-20-64:tests/core/fsck-on-boot (mar181546-879259) :
-----
+ os.query is-core16
+ os.query is-core18
+ os.query is-core20
+ LABEL=ubuntu-seed
+ case "$SPREAD_REBOOT" in
+ echo 'We can corrupt the boot partition'
We can corrupt the boot partition
+ unmount_vfat
+ os.query is-core16
+ os.query is-core18
+ os.query is-core20
+ mountpoint …
```
> tests/core/fsck-on-boot: unmount /run/mnt/snapd directly on uc20

- overlord/snapstate/handlers.go
- overlord/snapstate/handlers_link_test.go
- overlord/snapstate/snapstate_test.go
When snap is refreshed, the current symlink would briefly go away between
unlink-current-snap and link-snap tasks. If the system gets rebooted at this
time, during startup all services from snaps will fail to start. This is caused
by the fact that /usr/bin/snap, which on Core is linked to
/snap/snapd/current/usr/bin/snap will be dangling, as /snap/snapd/current was
removed.
Address the problem by not removing current of the snapd snap, unless unlinking
is called during removal for the first install of the snapd snap on core or a
general snapd snap removal. In the snapd on core scenario, the /usr/bin/snap
will be invoked from the core snap anyway.
Supersedes #10066
> overlord/snapstate: make sure that snapd current symlink is not removed during refresh

- tests/lib/prepare-restore.sh
- tests/lib/reset.sh
After the reset.sh use was moved to the restore of each test, then it is
not needed anymore to run it restoring the test suite.
Also the --store parameter won't be used and it can be removed.
> tests: simplify the reset.sh logic by removing not needed command

- interfaces/builtin/udisks2.go
A uc20 project needs udisks2 to mount usb to obtain files. It needs to set a lock on /run/mount/utab but is currently denied. 
Since this interface already provides write access, adding lock would seem OK.
> interfaces/udisks2: allow locking /run/mount/utab for udisks 2.8.4

- overlord/configstate/configcore/refresh.go
- overlord/configstate/configcore/refresh_test.go
- tests/main/interfaces-snapd-control-with-manage/task.yaml
Deal with no longer valid refresh.timer=managed / refresh.schedule=managed in the state when validating refresh config option of core. This option may become invalid if the snap managing refreshes is not signed anymore (i.e. devicestate.CanManageRefreshes returns false). The idea is to detect whether the value came in the transaction changes or became invalid in the existing config; if it's the latter, then it's ignored and doesn't interrupt the processing of remaining options. refreshScheduleManaged() handles this correctly and if "managed" cannot be supported anymore, we log it.
This isn't ideal. Ideally config infra would handle this for all options (but this probably needs discussion and is a larger piece of work). If this fix seems acceptable, then I'll try to work on a spread test. …
> o/configstate: deal with no longer valid refresh.timer=managed

- tests/main/snap-advise-command/task.yaml
When we refactored to use retry-tool we accidently broke the
checks for 429 from the names endpoint. This commit fixes it.
> tests: fix snap-advise-command check for 429

- tests/lib/prepare-restore.sh
This is important to make sure the first test for each suite will run
with the clean environment and with the snapd state restored.
This prevents errors that happen in the first tests of the second test suite executed.
> tests: reset the system while preparing the test suite

- cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
- cmd/snap-bootstrap/export_test.go
- cmd/snap-bootstrap/initramfs_mounts_state.go
- tests/lib/nested.sh
- tests/lib/prepare.sh
- tests/nested/manual/core20-initramfs-time-moves-forward/task.yaml
This uses ReadSystemEssentialAndBetterEarliestTime in order to get a trusted
time that the system can be moved forward to, providing as input the current
time from the system, which should be trusted, as it is either from a RTC, or
from systemd moving the time forward to when the initrd was built.
Also add tests for the various different relative times that can exist during
the initramfs for each mode.
Also add a nested spread test simulating this sort of device. If folks want I could break out the spread test to a followup.
> cmd/snap-bootstrap/initramfs-mounts: move time forward using assertion times

- interfaces/apparmor/backend.go
- interfaces/apparmor/backend_test.go
- interfaces/backend.go
- overlord/snapstate/handlers.go
- overlord/snapstate/handlers_discard_test.go
- overlord/snapstate/snapstate.go
- overlord/snapstate/snapstate_remove_test.go
- overlord/snapstate/snapstate_test.go
When a snapd snap is refreshed on an Ubuntu Core device, the setup-security-profiles task *replaced* the AppArmor profile of snap-confine from the old revision of snapd, with one for the new revision. Then an unexpected reboot occurs after the task has run, but before the 'current' symlink of the snapd snap has been replaced, any attempts to start the snap applications going through /usr/bin/snap end up invoking `/snap/snapd/<old-revision>/usr/lib/snapd/snap-confine`. However, at the time it happens, the AppArmor profile for snap-confine is already gone and replaced with one for the new revision. Thus s-c would ends up running as an `unconfined` process, and we intentionally exit with an error such this happen.
The branch attempts to not remove the snap-confine apparmor profiles when …
> interfaces, interfaces/apparmor, overlord/snapstate: late removal of snap-confine apparmor profiles

- cmd/snap-seccomp/main_test.go
The "socket" syscall on ppc64el needs to be de-multiplexed with
recent versions of libseccomp. This is similar to what we need
to do on i386 and s390x.
This fixes the build failure on hirsute:
https://launchpad.net/ubuntu/+source/snapd/2.49+21.04ubuntu1/+build/21197477
I tested this on ppc64el inside juju on hirsute and bionic and this PR works in both envs.
> snap-seccomp: fix seccomp test on ppc64el

- interfaces/ifacetest/backend.go
- overlord/ifacestate/helpers.go
- overlord/ifacestate/helpers_test.go
- overlord/ifacestate/ifacemgr.go
- overlord/snapstate/export_test.go
- overlord/snapstate/handlers.go
- overlord/snapstate/handlers_discard_test.go
- overlord/snapstate/handlers_prepare_test.go
- overlord/snapstate/snapstate_test.go
Followup to #10081. The branch moves the security profile removal to ifacestate.
> overlord/snapstate, overlord/ifacestate: move late security profile removal to ifacestate

- overlord/snapstate/catalogrefresh.go
- overlord/snapstate/catalogrefresh_test.go
- tests/main/apt-hooks/task.yaml
- tests/main/snap-advise-command/task.yaml
The branch implements the idea from @anonymouse64 about enabling catalog refresh selectively in specific tests that exercise the functionality, but leave it disabled for the others so that we do not hit the store ratelimiting.
Hopefully, we should see fewer failures in tests/main/apt-hooks and tests/main/snap-advise.
> overlord/snapstate: skip catalog refresh when snappy testing is enabled

- overlord/configstate/configcore/picfg.go
This is used in conjunctino with hdmi_mode, hdmi_group, and hdmi_drive in order
to use a custom specified HDMI mode. See
https://www.raspberrypi.org/documentation/configuration/config-txt/video.md
for full documentation.
See also https://forum.snapcraft.io/t/system-boot-config-txt-from-rpi-3-on-ubuntu-core-18-gets-overwritten/23620
where this was first requested.
> o/configstate/configcore/picfg.go: add hdmi_cvt support

- overlord/configstate/configcore/corecfg_test.go
- overlord/configstate/configcore/handlers.go
- overlord/configstate/configcore/runwithstate.go
- overlord/configstate/configcore/utils.go
See individual commit messages for full details, but these changes are broken out from https://github.com/snapcore/snapd/pull/9965, specifically to make it easier to review the refactors present in that PR.
> o/configstate/configcore: simple refactors in preparation for new function

- daemon/api_aliases_test.go
- daemon/api_apps_test.go
- daemon/api_asserts_test.go
- daemon/api_base_test.go
- daemon/api_buy_unsupp_test.go
- daemon/api_cohort_test.go
- daemon/api_console_conf_test.go
- daemon/api_debug_seeding_test.go
- daemon/api_debug_test.go
- daemon/api_download_test.go
- daemon/api_find_test.go
- daemon/api_general_test.go
- daemon/api_model_test.go
- daemon/api_sideload_n_try_test.go
- daemon/api_snapctl_test.go
- daemon/api_snaps_test.go
- daemon/api_snapshots_test.go
- daemon/api_system_recovery_keys_test.go
- daemon/api_systems_test.go
- daemon/api_themes_test.go
- daemon/api_users_test.go
- daemon/api_validate_test.go
these test a daemon request and check the expected response type
before returning the response for further specific checks
this simplifies away some checks in the tests but the bigger win is
avoiding the .(*daemon.Resp) casts everywhere, in particular
this will reduce the number of affected places if we change
somewhat the internal types used to produce responses
> daemon: introduce apiBaseSuite.(json|sync|async|error)Req  (and some apiBaseSuite cosmetics)

- .github/workflows/cla-check.yaml
One area where the new cla-check workflow differs from the old one is that it does not whitelist contributions from previous committers to the repository, so it ends up hitting Launchpad triggering more OOPS reports than we used to see.  This is most likely affecting core contributors who have not configured git to commit with an `@canonical.com` email address.
It does have an `accept-existing-contributors` input parameter, so this PR turns that on.
> ci: set the accept-existing-contributors parameter for the cla-check action

- tests/main/snap-validate-basic/task.yaml
- tests/main/snap-validate-with-store/task.yaml
- tests/main/snap-validate-with-store/testset1-seq1.yaml
- tests/main/snap-validate-with-store/testset1-seq2.yaml
Spread test for validation sets assertion fetched from the store. It's separate from existing snap-validate-basic test for clarity and also to check that prerequisite developer assertion is fetched automatically.
Assertions were uploaded to the store with snapcraft from a private channel, I've included instruction in the test comments in case we want/need to recreate it with another dev account.
> tests: add spread test for snap validate against store assertions

- spread.yaml
- tests/main/cgroup-devices/task.yaml
- tests/main/cgroup-freezer/task.yaml
- tests/main/security-device-cgroups-serial-port/task.yaml
- tests/main/security-device-cgroups/task.yaml
- tests/main/snap-device-helper-nvme/task.yaml
- tests/main/snapctl-is-connected/task.yaml
Tentative workaround for arch failures - use `pacman -Syu` as apparently there is a libc update and -Sy isn't enough to handle this (when this happens, even pacman doesn't work anymore because it depends on libcurl).
The failure is:
```
curl -sS -o - https://codeload.github.com/snapcore/snapd/tar.gz/2.49
curl: /usr/lib/libc.so.6: version `GLIBC_2.33' not found (required by curl)
curl: /usr/lib/libc.so.6: version `GLIBC_2.33' not found (required by /usr/lib/libcurl.so.4)
gzip: stdin: unexpected end of file
```
Also, arch now apparently uses cgroup v2, so this PR updates the affected tests.
> spread: tentative workaround for arch failure caused by libc upgrade and cgroups v2

- interfaces/builtin/gpio_test.go
This was never actually being tested, and in addition the IgnoresMissingSymlink
test was evaluating symlinks on the host, and so the test would have failed if
run on a Raspberry Pi for example with gpio pins available.
Discovered while debugging https://github.com/snapcore/snapd/pull/10061
> interfaces/builtin/gpio_test.go: actually test the generated gpio apparmor

- cmd/snap-preseed/main_test.go
- cmd/snapd-generator/main.c
- osutil/squashfs/fstype.go
- overlord/snapstate/backend/mountunit_test.go
- systemd/systemd_test.go
Use x-gvfs-hide mount option to hide squashfs loopback devices in Gnome gvfs
- x-gvfs-hide mount option should be used to hide block devices in
Gnome gvfs. This is documented in
https://gitlab.gnome.org/GNOME/gvfs/blob/master/monitor/udisks2/what-is-shown.txt
- gvfs-udisks2-volume-monitor uses a lot of CPU when there are a lot of
mount loopback devices unless the loopback devices are hidden from udisks2
with x-gvfs-hide or udev rule containing ENV{UDISKS_IGNORE}="1"
> many: add x-gvfs-hide option to mount units

- tests/main/snap-services/task.yaml
Add simple sanity check for systemctl show --property=UnitFileState output for non-existing service to catch any potential change in systemd behavior.
Related to #10083
> tests: add simple sanity check for systemctl show --property=UnitFileState for unknown service

- daemon/api_interfaces.go
- daemon/api_interfaces_test.go
- tests/main/snap-connect/task.yaml
Provide meaningful error message (snap "foo" is not installed) when referencing a non-installed snap via snap connect/disconnect. In the existing code we simply call ResolveConnect/ResolveDisconnect which unfortunately produce a misleading error message if snap is not installed. Note, repository only knows about plugs/slots (doesn't know about snaps that don't have plugs/slots), so the case needs to be handled outside of repo.
Fixes LP: #1921152
> api: provide meaningful error message on connect/disconnect for non-installed snap

- overlord/configstate/config/helpers.go
- overlord/configstate/config/transaction.go
- overlord/configstate/config/transaction_test.go
- overlord/hookstate/ctlcmd/unset_test.go
Fix panic with a sequence of config unset operations over same path in same transaction by creating an empty map if necessary. 
Also fix a very closely related problem (a variation of the first scenario) where setting a config path that was previously set to null in same transaction would have no result (config would remain at null).
Fixes LP #1920773
> o/configstate: fix panic with a sequence of config unset ops over same path

- spread.yaml
Small followup to my earlier PR #10108, thanks to @bboozzoo for suggestion.
> spread: ignore linux kernel upgrade in early stages for arch preparation

- spread.yaml
- tests/lib/prepare-restore.sh
This reverts commit e6a1f560b980615087f05ddd8e22b3b464286699.
For new systems, i.e. ubuntu 20.04 spread tests fail after latest refresh in case we set the var GO111MODULE: off in spread.yaml
It is failing in debian-sid, ubuntu-20.04, centos-8, arch-linux, etc
It works well in older systems like ubuntu-16.04, ubuntu-18.04
The error is the following:
+ best_golang=golang-1.10
+ quiet xargs -r eatmydata apt-get install -y
+ gdebi --quiet --apt-line ./debian/control
++ command -v go
+ '[' -z /usr/bin/go ']'
++ command -v govendor
+ '[' -z '' ']'
+ rm -rf /home/gopath/src/github.com/kardianos/govendor
+ go get -u github.com/kardianos/govendor
go: unknown environment setting GO111MODULE=false
> tests: update "spread: disable Go modules support in environment"

- systemd/systemd.go
- systemd/systemd_test.go
Rely on empty value of UnitFileState property to determine if the requested service is installed. This seems to work consistently across 16.04 - 18.04 - 20.04, e.g.
```
$ systemctl show --property=ActiveState,UnitFileState,Type,Id foo.service
Type=
Id=foo.service
ActiveState=inactive
UnitFileState=
```
(and exit status is 0 on all systems).
**Alternative** is to use `systemctl status ..` but this behaves differently on 16.04 vs newer systems -on 16.04:
```
$ systemctl status foo.service
● foo.service
Loaded: not-found (Reason: No such file or directory)
Active: inactive (dead)
vagrant@xenial:~$ echo $?
3
```
On 18.04 and 20.04:
```
$ systemctl status foo.service
Unit foo.service could not be found.
vagrant@bionic:~$ echo $?
4
```
The exit status = 4 seems to be conforming to …
> systemd: enrich UnitStatus returned by systemd.Status() with Installed flag

- interfaces/builtin/pwm.go
- interfaces/builtin/pwm_test.go
- interfaces/policy/basedeclaration_test.go
- run-checks
- tests/lib/snaps/test-snapd-policy-app-consumer/meta/snap.yaml
PWM interface is often used to control device's LED, fan or heater and
its sysfs can allow user space to expose PWM under /sys/class/pwm/pwmchipN
where N is the base of PWM chip and each chip may have multiple channels
used for application. The access path for the specific channel should be
specified at /sys/class/pwm/pwmchipN/pwm? and that channel needs to be
exported via /sys/class/pwm/pwmchipN/export, so its behavior is similar
to GPIO interface.
Reference:
https://www.kernel.org/doc/Documentation/pwm.txt
> interfaces/pwm: add PWM interface

- boot/debug.go
- cmd/snap/cmd_debug_bootvars_test.go
Include snapd_extra_cmdline_args in snap debug boot-vars output on UC20 systems.
> boot, cmd/snap: include extra cmdline args in debug boot-vars output

- gadget/layout.go
- gadget/layout_test.go
The `$kernel:ref/` resolving was a bit too restricted and would
not allow writing something like: `$kernel:ref/dir` unless the
"ref" and the "dir" are part of kernel.yaml.
This commit fixes this so that you can have a kernel.yaml that
contains only:
```
assets:
pidtbs:
update: true
content:
- dtbs/
```
And the gadget.yaml resolves deeper paths like:
```
volumes:
pi:
schema: mbr
bootloader: u-boot
structure:
- name: ubuntu-seed
role: system-seed
filesystem: vfat
type: 0C
size: 1200M
content:
- source: $kernel:pidtbs/dtbs/broadcom/
target: /
- source: $kernel:pidtbs/dtbs/overlays/
target: /overlays
- source: boot-assets/
target: /
```
This came up during the review of LP:1907056
> gadget: be more flexible with kernel content resolving

- boot/flags.go
- boot/flags_test.go
- boot/initramfs20dirs.go
- cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
- tests/core/basic20/task.yaml
/run/snapd/snap-bootstrap is a scratch directory and user space shouldn't care a lot about it
> boot,tests: move where we write boot-flags one level up

- boot/cmdline.go
- boot/cmdline_test.go
- boot/export_test.go
Introduce a helper that derives which boot variables must be set for gadget
provided kernel command line component
> boot: derive boot variables for kernel command lines

- daemon/api_snapctl.go
- daemon/api_snapctl_test.go
- daemon/daemon.go
- daemon/export_test.go
- daemon/ucrednet.go
- daemon/ucrednet_test.go
This PR extracts the ucrednet cleanup from PR #9043 into its own pull request.  It updates the `ucrednetGet` helper to return a `ucrednet` struct rather than return the three credentials separately.
> daemon: make ucrednetGet() return a *ucrednet structure

- tests/bin/os.paths
- tests/lib/tools/os.paths
- tests/main/os.paths/task.yaml
The idea of this tool is to replace the dirs.sh helper
Also should be nice to add here other paths which currently are being resolved in the scripts.
> tests: new os.paths tool

- boot/assets_test.go
- boot/boot_test.go
- boot/cmdline.go
- boot/cmdline_test.go
- boot/makebootable.go
- boot/makebootable_test.go
- boot/seal.go
- boot/seal_test.go
- boot/systems_test.go
Two patches that prepare the stage for the things to come. The first one adjusts the API of command line helpers to take a path to the gadget directory or snap. The next one loads the gadget from the recovery system seed.
Effectively nothing changes when the keys are (re-)sealed as the boot code does not load the command line from the snap yet.
> boot: pass gadget path to command line helpers, load gadget from seed

- boot/makebootable.go
- boot/makebootable_test.go
- tests/nested/manual/core20-custom-kernel-commandline/task.yaml
The branch sets up kernel command line arguments for the seed system, which makes them appear in install & recovery modes. The PR includes a simple spread test to verify that recovery mode has the right command line arguments.
Based on top of #10120.
>  boot: set extra kernel command line arguments when making a recovery system bootable

- boot/seal_test.go
Due to merging of 2 separate branches which introduced a mock gadget snap yaml
using the same const name, we now have a name clash.
> boot: drop gadget snap yaml which is already defined elsewhere in the tests

- tests/core/gadget-kernel-refs-update-pc/task.yaml
This test is failing on all the devices for beta validation
The error in all cases is:
+ snap install pc_x1.snap
error: cannot open: "pc_x1.snap"
> tests: fix gadget-kernel-refs-update-pc test on arm and when $TRUST_TEST_KEY is false

- tests/main/prepare-image-grub-core18/task.yaml
This change is to avoid some out of disk space errors that are happening
on arm devices.
This is the error that is happening on rpi2/3/4:
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           462M  4.0K  462M   1% /tmp
Filesystem      Size  Used Avail Use% Mounted on
/dev/mmcblk0p2   30G  752M   27G   3% /home
$TESTSLIB/assertions/ubuntu-core-18-amd64.model /tmp/root
Fetching snapd
Fetching pc-kernel
Fetching core18
Fetching pc
Fetching test-snapd-tools-core18
error: cannot extract "*" to "/tmp/root/kernel": failed: "Write on
output file failed because No space left on device", "writer: failed to
write data block 6", "Failed to write
/tmp/root/kernel/firmware/iwlwifi-8000C-13.ucode, skipping", "Write on
output file failed because No space left on device", and 18164 more
> tests: fix prepare-image-grub-core18 for arm devices

- daemon/access.go
- daemon/access_test.go
- daemon/daemon.go
- daemon/daemon_test.go
- daemon/export_access_test.go
This has been extracted from PR #9043, and builds on top of PR #10126.
This PR includes the four implementations of the new `accessChecker` interface, without the changes to actually plumb them into the REST server.  The four checkers are intended to represent the different levels of access used by the REST API:
1. `openAccess` allows unrestricted access on the main `/run/snapd.socket` socket.
2. `authenticatedAccess` allows access on `/run/snapd.socket` provided one of the following is true:
* The user has provided a macaroon login token.
* The user is root
* The user is granted access by polkitd
3. `rootAccess` allows access on `/run/snapd.socket` if the user is root.
4. `snapAccess` allows access on `/run/snapd-snap.socket` (for use by `/v2/snapctl`).
The branch also updates the …
> daemon: add new accessChecker implementations

- spread.yaml
Followup to https://github.com/snapcore/snapd/pull/10086, it missed 20.04 in spread.yaml.
> tests: add 20.04 to systems for nested/core

- boot/debug.go
- cmd/snap/cmd_debug_bootvars_test.go
Extend the output of `snap debug boot-vars` to include the full command line override.
> cmd/snap, boot: add snapd_full_cmdline_args to dumped boot vars

- boot/boot_test.go
- boot/bootstate20.go
- boot/cmdline.go
- overlord/devicestate/devicemgr.go
- overlord/devicestate/devicestate_bootconfig_test.go
- overlord/devicestate/devicestate_gadget_test.go
- overlord/devicestate/devicestate_test.go
- overlord/devicestate/firstboot_preseed_test.go
- overlord/devicestate/handlers_gadget.go
- overlord/managers_test.go
- overlord/snapstate/snapstate.go
- overlord/snapstate/snapstate_install_test.go
- overlord/snapstate/snapstate_update_test.go
- tests/nested/manual/core20-custom-kernel-commandline/task.yaml
~~Stacked on top of #10143.~~ The relevant commits are in the overlord package and subpackages, start with https://github.com/snapcore/snapd/commit/1351e70bab09b959c1003c1022df2e010a2762bc and then subsequent ones.
> overlord/devicestate, overlord/snapstate: add task for updating kernel command lines from gadget

- interfaces/builtin/dsp.go
- interfaces/builtin/dsp_test.go
- interfaces/policy/basedeclaration_test.go
- run-checks
- tests/lib/snaps/test-snapd-policy-app-consumer/meta/snap.yaml
This interface will be used by specific devices with plugs that have flavor
attributes identifying which will provide board specific access to digital
signal processor devices which are very specific to a particular BSP or board.
The initial accesses here are sufficient for the software that we have tested 
and have access to, we will likely need to expand this set after getting more
feedback from the customer, but in the meantime we have agreement to move
forward with merging just this for now and add things as followups.
cc @woodrow-shen
> interfaces/builtin: introduce dsp interface

- boot/cmdline.go
- gadget/gadget.go
- gadget/gadget_test.go
Since it was not very useful when done externally, the opening of a snap
container for the gadget snap was rolled back into the gadget helper.
> boot, gadget: move opening the snap container into the gadget helper

- tests/lib/tools/snaps-state
- tests/main/snaps-state/task.yaml
This is going to be used to replace the names.sh helper
> tests: add new command to snaps-state to get current core, kernel and gadget

- tests/core/iio/task.yaml
- tests/lib/prepare-restore.sh
- tests/lib/prepare.sh
- tests/lib/reset.sh
- tests/lib/state.sh
- tests/lib/tools/snapd.tool
- tests/nightly/install-snaps/task.yaml
- tests/regression/lp-1630479/task.yaml
- tests/regression/lp-1644439/task.yaml
- tests/regression/lp-1805838/task.yaml
- tests/regression/lp-1813963/task.yaml
- tests/smoke/remove/task.yaml
- tests/upgrade/basic/task.yaml
- tests/upgrade/selinux-relabel/task.yaml
The first part of the migration from dirs.sh helper to os.paths tool
> tests: use op.paths tools instead of dirs.sh helper - part 1

- overlord/servicestate/servicemgr.go
- overlord/servicestate/servicestate.go
- overlord/servicestate/servicestate_test.go
- overlord/snapstate/backend/link.go
- overlord/snapstate/backend_test.go
- overlord/snapstate/booted_test.go
- overlord/snapstate/handlers.go
- overlord/snapstate/handlers_link_test.go
- overlord/snapstate/snapstate_test.go
There should be exactly one place that knows how to compute the
correct SnapServiceOptions of a snap given current state.
configcore still needs to be separately fixed in this respect.
This is useful also for ongoing quota group work.
This is useful for #10164 as well.
> overlord: make servicestate responsible to compute SnapServiceOptions

- boot/cmdline_test.go
- boot/makebootable_test.go
- gadget/gadget.go
- gadget/gadget_test.go
- spread.yaml
- tests/nested/manual/core20-custom-kernel-commandline/task.yaml
Support a multiline format of the cmdline file shipped by the gadget. Now it is valid to have a content like this:
```
paramter parameter
panic=-1
```
> gadget: multi line support in gadget's cmdline file

- wrappers/services.go
- wrappers/services_gen_test.go
- wrappers/services_test.go
The callback is called on additions and changes and gets information
about the app, the unit type, name and old and new content
This also simplifies some of the code that was on master.
This drops the modified return value in favor or just exposing what changed if relevant via the callback. 
The problem is that to cover all the use cases correctly we would need a complicated data structures, 
and we don't know enough about them to pick a simplified return value that covers most of them yet.
> wrappers: support in EnsureSnapServices a callback to observe changes

- boot/makebootable.go
- boot/makebootable_test.go
- bootloader/lk.go
- bootloader/lk_test.go
Split out bits that make the recovery system bootable. Those will be used
independently when creating a recovery system and setting it up for boot.
> boot: split out a helper for making recovery system bootable

- tests/lib/nested.sh
Stop compressing the images as it seems to be a waste of time. Analyzing some
UC20 runs, the image built by ubuntu-image is 199MB (10GB apparent size, since
those are sparse files). Compressing that image with xz -0 takes ~2 minutes,
inflating it takes another ~30s. The compressed image is 195MB (vs 199MB
initially).
Instead of compression, use simple cp to keep track of the pristine versions of
the images and preserve the sparse file property.
> tests/lib/nested: do not compress images, return early when restored from pristine image

- bootloader/bootloadertest/bootloadertest.go
Split out interface implementations into reusable mixins. Provide a mock implementation of a bootloader implementing RecoveryAwareBootloader and TrustedAssetsBootloader.
> bootloader/bootloadertest: provide interface implementation as mixins, provide a mock for recovery-aware-trusted-asses bootloader

- overlord/hookstate/hooks.go
- overlord/snapstate/autorefresh_gating.go
- overlord/snapstate/autorefresh_gating_test.go
- overlord/snapstate/export_test.go
- overlord/snapstate/snapstate.go
Helper function for creating gate-auto-refresh hooks.
Base/restart flags are set on the hook context since they will be readily available when hooks get created.
Version/revision/channel values be obtained from "refresh-candidates" from state (TODO in followups).
Based on #10053
> o/snapstate: helper for creating gate-auto-refresh hooks

- overlord/snapstate/autorefresh.go
- overlord/snapstate/check_snap.go
- overlord/snapstate/export_test.go
- overlord/snapstate/refreshhints.go
- overlord/snapstate/refreshhints_test.go
- overlord/snapstate/snapstate.go
Store "refresh-candidates" in state during refresh-hints.
> o/snapstate: store refresh-candidates in the state

- testutil/filecontentchecker.go
- testutil/filecontentchecker_test.go
The FileEquals checker can verify that the file content is equal to strings,
byte slices or something that implements fmt.Stringer. Extend the functionality
to allow checking that file contents are the same as of a referenced file
with FileContentRef.
> testutil: support referencing files in FileEquals checker

- overlord/snapstate/backend/mountunit_test.go
- systemd/systemd.go
- systemd/systemd_test.go
Tentative fix for https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1922293
(this is still being discussed and needs checking with zfs-linux maintainer)
> systemd: wait for zfs mounts

- overlord/hookstate/ctlcmd/refresh.go
- overlord/hookstate/ctlcmd/refresh_test.go
Basic scaffolding for `snapctl refresh` command. The command is hidden until the feature gets implemented. There are some TODOs marked in the code:
- use refresh-candidates from state (after #10167)
- support --available flag.
- support for running outside of hooks
For running from hook, hook context will have base/restart flags set upfront when all gate-auto-refresh hooks get created.
For running outside of hooks the idea is to re-use  affectedByRefresh from #10053 and re-calculate this on demand.
> o/hookstate: add "refresh" command to snapctl (hidden, not complete yet)

- tests/core/create-user-2/task.yaml
- tests/core/create-user/task.yaml
This is to add extra info when the test fails during beta validation
Error executing external:ubuntu-core-20-64:tests/core/create-user
(external:ubuntu-core-20-64) :
+ '[' true = true ']'
+ snap create-user --sudoer mvo@ubuntu.com
created user "mvo"
+ echo 'Did not get expected error creating user in managed device'
Did not get expected error creating user in managed device
+ exit 1
> tests: adding debug info for create user tests

- overlord/managers_test.go
Add mocking that makes the host look like an Ubuntu Core system.
> overlord: properly mock usr-lib-snapd tests to mimic an Ubuntu Core system

- overlord/snapstate/check_snap.go
- overlord/snapstate/check_snap_test.go
This adds the "kernel-assets" string to the feature set of snapd.
With that snaps can use: `assumes: [kernel-assets]` and snapd will
ensure that the snaps that need this feature (like the new gadget
and kernel) will only be installed when there is an updated version
of snapd.
> snapstate: add "kernel-assets" to featureSet (2.50)

- overlord/servicestate/servicemgr.go
- overlord/servicestate/servicestate.go
- overlord/servicestate/servicestate_test.go
- overlord/snapstate/backend/link.go
- overlord/snapstate/backend_test.go
- overlord/snapstate/booted_test.go
- overlord/snapstate/handlers.go
- overlord/snapstate/handlers_link_test.go
- overlord/snapstate/snapstate_test.go
- wrappers/services.go
- wrappers/services_gen_test.go
- wrappers/services_test.go
Backport of https://github.com/snapcore/snapd/pull/10133 for 2.50 - with that we can cherry-pick PR #10164 (commit  406dbc0 from master).
As suggested this now also includes #10151 and  #10171
>  wrappers/services.go: introduce EnsureSnapServices() (2.50)

- daemon/api_apps_test.go
- daemon/api_base_test.go
- overlord/managers_test.go
- overlord/overlord.go
- overlord/overlord_test.go
- overlord/servicestate/servicemgr.go
- overlord/servicestate/servicemgr_test.go
- overlord/servicestate/servicestate.go
- overlord/servicestate/servicestate_test.go
- overlord/snapstate/backend/link.go
- overlord/snapstate/backend/link_test.go
- overlord/snapstate/backend_test.go
- overlord/snapstate/booted_test.go
- overlord/snapstate/handlers.go
- overlord/snapstate/handlers_link_test.go
- overlord/snapstate/snapstate_test.go
- systemd/emulation.go
- systemd/systemd.go
- systemd/systemd_test.go
- wrappers/core18.go
- wrappers/services.go
- wrappers/services_gen_test.go
- wrappers/services_test.go
This is https://github.com/snapcore/snapd/pull/10164 for 2.50 - it includes the pre-reqs from https://github.com/snapcore/snapd/pull/10183
> o/servicestate/servicemgr.go: add ensure loop for snap service units (2.50)

- boot/export_test.go
- boot/seal.go
- boot/seal_test.go
- kernel/fde/export_test.go
- kernel/fde/fde.go
- kernel/fde/fde_test.go
- kernel/fde/reavel_key.go
- overlord/hookstate/ctlcmd/fde_setup_test.go
- secboot/export_test.go
- secboot/secboot_dummy.go
- secboot/secboot_hooks.go
- secboot/secboot_sb.go
- secboot/secboot_sb_test.go
This is another preparatory PR for the changes for fde-hooks-v2.
The first two commits are small cleanups, while the latter commits move responsibilities down respectively for:
* run fde-reveal-key to kernel/fde from secboot
* sealing keys with fde-setup hook to secboot from boot
> many: move responsibilities down seboot -> kernel/fde and boot -> secboot

- spread.yaml
The compueengine project will be disable and the new project is snapd-spread under canonical organization.
> spread.yaml: update the gce project to start using snapd-spread

- tests/lib/nested.sh
- tests/nested/manual/snapd-refresh-from-old/task.yaml
There are new data buckets in the new project in gce
snapd-spread-tests (used to store tests data) and snapd-spread-images (used to store spread images)
> tests: new buckets for snapd-spread project on gce

- overlord/servicestate/quotas.go
- overlord/servicestate/quotas_test.go
- overlord/servicestate/servicemgr_test.go
* Add AllQuotas for getting all quotas from the state
* Add GetQuota for getting an individual quota group from the state by name
* Add UpdateQuotas for updating one or many quotas in the state in a single 
transaction
* Add some units for this, including refactoring to share some of the overlord
setup with the servicemgr_test.go tests via baseServiceMgrTestSuite
This is orthogonal to https://github.com/snapcore/snapd/pull/10198
> o/servicestate/quotas: add functions for getting and setting quotas in state

- overlord/servicestate/quotas_test.go
- snap/quota/quota.go
any of the two groups can end up being checked first and produce the error seen
maybe the underlying function should use a multi-error but as we maintain the state there it might be overkill
> o/servicestate: test has internal ordering issues, consider both cases

- client/quota.go
- client/quota_test.go
- cmd/snap/cmd_quota.go
- cmd/snap/cmd_quota_test.go
Introduce 'snap quota' command along with client methods with support for creating/updating and querying info for single quota group.
> cmd/snap: introduce 'snap quota' command

- snap/naming/validate.go
- snap/quota/export_test.go
- snap/quota/quota.go
- snap/quota/quota_test.go
Addresses comments from #10152.
> snap/quotas: followups from previous PR

- overlord/configstate/configcore/vitality_test.go
- overlord/servicestate/quota_control.go
- overlord/servicestate/quota_control_test.go
- overlord/servicestate/quotas.go
- overlord/servicestate/quotas_test.go
- overlord/servicestate/servicemgr_test.go
- overlord/servicestate/servicestate_test.go
- overlord/snapstate/backend/link_test.go
- snap/quota/export_test.go
- snap/quota/quota.go
- snap/quota/quota_test.go
- wrappers/services.go
- wrappers/services_test.go
cc @stolowski these methods (or something very close to them hopefully) are what the daemon backend will need to use
I still need to write tests for these methods, but wanted to get alignment on the set of functions here... Also was wondering if we should be creating tasks / changes for these operations to match i.e. `snap set` and `snap start`. Arguably we could, but also maybe we want to avoid that complexity.
Based on top of https://github.com/snapcore/snapd/pull/10153
> o/servicestate/quota_control.go: introduce basic group manipulation methods

- daemon/api_systems_test.go
- overlord/devicestate/devicectx.go
- overlord/devicestate/devicemgr.go
- overlord/devicestate/devicestate_serial_test.go
- overlord/devicestate/devicestate_systems_test.go
- overlord/devicestate/devicestate_test.go
- overlord/hookstate/ctlcmd/export_test.go
- overlord/hookstate/ctlcmd/system_mode.go
- overlord/hookstate/ctlcmd/system_mode_test.go
Have ways to get general details about the system mode the device is in from DeviceManager.
Use this to implement a first pass at `snapctl system-mode`.
> o/devicestate,o/hookstate/ctlcmd: introduce SystemModeInfo methods and snapctl system-mode

- client/quota.go
- cmd/snap/cmd_quota.go
- cmd/snap/cmd_quota_test.go
Implement `snap quotas` command.
As discussed on the standup and agreed with @pedronis , the initial implementation shows a limited amount information, i.e.
```
Quota  Parent  Max-Memory
xxx             9.9kB
zzz             5000B
aaa    zzz      1000B
...
```
(the output is sorted by hierarchy, then names).
All details are available with `snap quota <name>` (already landed).
> cmd/snap, client: snap quotas command

- cmd/snap/cmd_prepare_image.go
- cmd/snap/cmd_prepare_image_test.go
- image/image_linux.go
- image/image_test.go
- image/options.go
this moves special customization responsabilities from ubuntu-image to prepare-image
this would allow to support them on UC20 with grade dangerous if requested and reduces
the u-i work to support more of these if needed
this matches https://github.com/CanonicalLtd/ubuntu-image/pull/199/ (I tested the two combined to some extent)
> image,c/snap: implement prepare-image --customize

- boot/export_test.go
- boot/flags.go
- boot/flags_test.go
- boot/makebootable.go
- boot/makebootable_test.go
- image/image_linux.go
- image/image_test.go
- image/options.go
This will let us set the "factory" hint flag.
First commit is a follow-up to previous PR touching customization.
> boot,image: support image.Customizations.BootFlags

- snap/snaptest/snaptest.go
- snap/snaptest/snaptest_test.go
Introduce a helper that can mock a snap such that both the mount directory of
the snap and the squashfs file can be obtained.
> snap/snaptest: helper that mocks both the squashfs file and a snap directory

- cmd/snap-bootstrap/cmd_initramfs_mounts_test.go
> cmd/snap-bootstrap: Fix linter errors

- cmd/snap/cmd_debug_state.go
- cmd/snap/cmd_info.go
- cmd/snap/cmd_login.go
- cmd/snap/cmd_quota.go
- cmd/snap/cmd_quota_test.go
- cmd/snap/cmd_routine_console_conf.go
- cmd/snap/cmd_validate.go
- cmd/snap/cmd_validate_test.go
This fixes some of the errors reported for `cmd/snap`. The ones that are left are:
```
cmd/snap/cmd_run.go:114: File is not `gofmt`-ed with `-s` (gofmt)
"gdbserver": i18n.G("Run the command with gdbserver"),
cmd/snap/cmd_run_test.go:783: File is not `gofmt`-ed with `-s` (gofmt)
"99", // COMP_TYPE (no change)
"99", // COMP_KEY (no change)
"11", // COMP_POINT (+1 because "an-app" is one longer than "alias")
"2",  // COMP_CWORD (no change)
" ",  // COMP_WORDBREAKS (no change)
cmd/snap/cmd_debug_timings_test.go:29: File is not `goimports`-ed with -local github.com/snapcore/snapd (goimports)
"github.com/snapcore/snapd/cmd/snap"
cmd/snap/cmd_validate_test.go:29: File is not `goimports`-ed with -local github.com/snapcore/snapd (goimports)
"github.com/snapcore/snapd/cmd/snap" …
```
> cmd/snap: Fix errors reported by linter

- interfaces/connection_test.go
- interfaces/repo_test.go
Rework the test code to be in the interfaces_test package (thanks Ian
for the patch!) and remove some unused code.
> interfaces: fix linter errors

- .github/workflows/test.yaml
- spread.yaml
Fedora 34 was released on 24.04.2021, we should add to the test suite.
@sergiocazzolato we'll need an image of Fedora 34, can you look into add it?
> spread: add Fedora 34, leave a TODO about dropping Fedora 32

- tests/main/cgroup-devices/task.yaml
- tests/main/cgroup-freezer/task.yaml
- tests/main/snap-device-helper-nvme/task.yaml
- tests/main/snapctl-is-connected/task.yaml
OpenSUSE Tumbleweed has been updated to systemd 248 which defaults to cgroup v2
now. Account for that in the tests.
> tests: fix tests expecting cgroup v1/hybrid on openSUSE Tumbleweed

- cmd/snap/cmd_changes.go
- cmd/snap/cmd_changes_test.go
Fixes: https://bugs.launchpad.net/snapd/+bug/1823974
> cmd/snap: exit normally if "snap changes" has no changes

- interfaces/builtin/udisks2.go
References:
https://forum.snapcraft.io/t/udisks2-interface-extend-permissions/24073
> interfaces/udisks2: Allow access to the login manager via dbus

- HACKING.md
- tests/lib/nested.sh
The old aws url is not longer available, now the spread binary is stored in gce bucket
> tests: update spread url

- interfaces/apparmor/template.go
- interfaces/builtin/account_control.go
- interfaces/builtin/docker_support.go
- interfaces/builtin/greengrass_support.go
- interfaces/builtin/hardware_observe.go
- interfaces/builtin/kernel_module_control.go
- interfaces/builtin/kernel_module_observe.go
- interfaces/builtin/multipass_support.go
- interfaces/builtin/multipass_support_test.go
- interfaces/builtin/network_control.go
- interfaces/builtin/network_manager.go
- interfaces/builtin/ppp.go
- interfaces/builtin/time_control.go
- interfaces/builtin/udisks2.go
Core20 does not have populated `/bin` and `/sbin` directories, instead those are symbolic links to `/usr/bin` and `/usr/sbin` respectively.
Apparmor profiles need to reflect this, otherwise we have disparity what is allowed on pre uc20 and uc20 systems
> interfaces: builtin: update permitted paths to be compatible with UC20

- interfaces/builtin/dbus.go
- interfaces/builtin/dbus_test.go
This is to accommodate for Firefox claiming one name per running instance, where the suffix is the base64-encoded profile name (https://bugzilla.mozilla.org/1441894).
> interfaces/dbus: allow claiming 'well-known' D-Bus names with a wildcard suffix

- secboot/encrypt.go
- tests/main/uc20-create-partitions-encrypt/task.yaml
We are using an incorrect size for encryption key in secboot. @chrisccoulson 
mentioned this a while ago and this commit fixes it and moves to
a 32 byte key instead of the 64 byte key.
> secboot: switch encryption key size to 32 byte (thanks to Chris)

- boot/seal.go
- boot/seal_test.go
It is possible that only the recovery boot chain will be changed when we add a
tried recovery system to the set of tested recovery systems. In this case, the
reseal of fallback objects should still be carried out, even if the run boot
chain has not changed.
> boot: reseal given keys when the respective boot chain has changed

- overlord/managers_test.go
Set up a mock for logger so that one can inspect the logged task information.
> overlord: mock logger in managers unit tests

- interfaces/apparmor/backend_test.go
- interfaces/builtin/i2c_test.go
- interfaces/builtin/iio_test.go
- interfaces/builtin/serial_port_test.go
- interfaces/kmod/backend_test.go
- interfaces/kmod/kmod_test.go
- interfaces/policy/basedeclaration_test.go
- interfaces/seccomp/spec.go
- interfaces/udev/backend.go
Running the linter in the `interfaces/` directory tree.
> interfaces: fix linter issues

- tests/main/mount-ns/google.ubuntu-18.04-64/HOST.expected.txt
- tests/main/mount-ns/google.ubuntu-18.04-64/PER-SNAP-16.expected.txt
- tests/main/mount-ns/google.ubuntu-18.04-64/PER-SNAP-18.expected.txt
- tests/main/mount-ns/google.ubuntu-18.04-64/PER-SNAP-C7.expected.txt
- tests/main/mount-ns/google.ubuntu-18.04-64/PER-USER-16.expected.txt
- tests/main/mount-ns/google.ubuntu-18.04-64/PER-USER-18.expected.txt
- tests/main/mount-ns/google.ubuntu-18.04-64/PER-USER-C7.expected.txt
After the new ubuntu bionic is published, thenmount option on /boot/efi changed dmask= parameter in the distro
> tests: update mount-ns test to support changes in the distro

- tests/lib/nested.sh
- tests/nested/manual/core20-install-mode-shutdown-via-hook/install-device
- tests/nested/manual/core20-install-mode-shutdown-via-hook/task.yaml
This test exercises the install-device hook with the snapctl reboot command to
create a UC20 device which shuts itself down after install mode has finished,
such that we can then reboot it later on and it proceeds to run mode normally.
This needs a little bit of support in nested.sh and nested-state for VM's that shut
themselves down.
> tests/nested/manual: add test for install-device + snapctl reboot

- overlord/hookstate/ctlcmd/refresh.go
- overlord/hookstate/ctlcmd/refresh_test.go
- overlord/snapstate/autorefresh.go
- overlord/snapstate/refreshhints.go
- overlord/snapstate/refreshhints_test.go
Flesh out snapctl --pending: print version, revision and channel info. Enhanced refreshCandidate struct with version string.
Handles running from hook only at the moment.
> o/hookstate, o/snapstate: print revision, version, channel with snapctl --pending

- tests/core/fsck-on-boot/task.yaml
- tests/core/fsck-vfat/task.yaml
- tests/core/snap-repair/task.yaml
- tests/lib/prepare-restore.sh
- tests/lib/tools/suite/tests.cleanup/task.yaml
- tests/lib/tools/suite/tests.invariant/task.yaml
- tests/lib/tools/tests.cleanup
- tests/main/cgroup-tracking-failure/task.yaml
- tests/main/cgroup-tracking/task.yaml
- tests/main/exitcodes/task.yaml
- tests/main/interfaces-audio-playback-record/task.yaml
- tests/main/interfaces-desktop-document-portal/task.yaml
- tests/main/interfaces-pulseaudio/task.yaml
- tests/main/interfaces-timeserver-control/task.yaml
- tests/main/refresh/task.yaml
- tests/main/snapctl-is-connected-pid/task.yaml
- tests/regression/lp-1891371/task.yaml
- tests/regression/lp-1898038/task.yaml
- tests/regression/lp-1910456/task.yaml
The idea of this change is to avoid preparing and make automatic
restoration of the defered commands.
In case it is required the restore can be invoqued manually.
> tests: simplify the tests.cleanup tool

- cmd/snap/cmd_snap_op_test.go
- cmd/snap/error.go
This produces precise messages when a ErrorKindSystemRestart is for halt/poweroff.
follow-up to #10222
> c/snap: more precise message for ErrorKindSystemRestart op != reboot

- overlord/snapstate/autorefresh_gating_test.go
- overlord/snapstate/export_test.go
- overlord/snapstate/handlers.go
- overlord/snapstate/refreshhints.go
- overlord/snapstate/refreshhints_test.go
- overlord/snapstate/snapmgr.go
- overlord/snapstate/snapstate.go
Implement autorefresh method that initiates auto-refresh: updates refresh-candidates, creates hooks and a new gating task ("conditional-auto-refresh"). Phase 2 will be handled by doAutoRefreshGate.
> o/snapstate: autorefresh phase1 for refresh-control

- overlord/devicestate/systems.go
- overlord/devicestate/systems_test.go
Pass a callback so that the caller can observe, and thus track, writing snaps
when creating a recovery system.
> overlord/devicesate: observe snap writes when creating recovery systems

- overlord/hookstate/ctlcmd/ctlcmd.go
- overlord/hookstate/ctlcmd/system_mode_test.go
there is nothing particularly sensitive in its output or purpose.
reorg how we check whether a snapctl command is allowed for non-root,
as the list has grown a bit now.
> o/hookstate/ctlcmd: allow system-mode for non-root

- asserts/account_test.go
- asserts/database.go
- asserts/database_test.go
- asserts/headers.go
- asserts/ifacedecls.go
- asserts/ifacedecls_test.go
- asserts/membackstore.go
- asserts/repair_test.go
- asserts/snapasserts/validation_sets.go
- asserts/system_user_test.go
Besides some trivial fixes, this also adds the (previously unused) class
`isUnacceptedUpdateSuite` to the tests suite.
> asserts: fix errors reported by linter

- cmd/snap-update-ns/change.go
- cmd/snap-update-ns/change_test.go
This error has not been addressed:
```
cmd/snap-update-ns/sorting_test.go:20:9: package should be `main_test` instead of `main` (testpackage)
package main
^
```
The reason is that if I change the package name as advised, a few symbols are not getting resolved anymore:
```
cmd/snap-update-ns/sorting_test.go:42:12: undeclared name: `byOriginAndMagicDir` (typecheck)
sort.Sort(byOriginAndMagicDir(entries))
^
cmd/snap-update-ns/sorting_test.go:63:12: undeclared name: `byOriginAndMagicDir` (typecheck)
sort.Sort(byOriginAndMagicDir(entries))
^
cmd/snap-update-ns/sorting_test.go:89:12: undeclared name: `byOriginAndMagicDir` (typecheck)
sort.Sort(byOriginAndMagicDir(entries))
^
cmd/snap-update-ns/sorting_test.go:91:12: undeclared name: `byOriginAndMagicDir` (typecheck) …
```
> cmd/snap-update-ns: fix linter errors

- interfaces/builtin/raw_input.go
- interfaces/builtin/raw_input_test.go
- tests/lib/snaps/test-snapd-policy-app-consumer/meta/snap.yaml
- tests/main/interfaces-input/task.yaml
- tests/main/interfaces-input/test-snapd-sh/bin/sh
- tests/main/interfaces-input/test-snapd-sh/meta/snap.yaml
Context: https://forum.snapcraft.io/t/what-interface-provides-access-to-dev-input/22657/11
You can use [this libinput snap](https://gitlab.com/mardy/snaps/-/tree/master/libinput/snap) to manually test this interface. The snap runs correctly, but the following denials are found in the audit log:
```
[104642.241275] audit: type=1400 audit(1620727863.291:2670): apparmor="DENIED" operation="open" profile="snap.libinput-tool.libinput-debug-events" name="/run/udev/data/+usb:3-4.1:1.0" pid=475087 comm="libinput-debug-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[104642.241399] audit: type=1400 audit(1620727863.291:2671): apparmor="DENIED" operation="open" profile="snap.libinput-tool.libinput-debug-events" name="/run/udev/data/c189:265" pid=475087 comm="libinput-debug-" requested_mask="r" …
```
> interfaces/builtin: introduce raw-input interface

- interfaces/builtin/serial_port.go
- interfaces/builtin/serial_port_test.go
Add support for two Qualcomm serial port devices.
ttyMSMX: drivers/tty/serial/msm_serial.c
ttyHSX: drivers/tty/serial/qcom_geni_serial.c
> interfaces/serial-port: add Qualcomm serial port devices to allowed list

- cmd/snap/main.go
- cmd/snap/main_test.go
- i18n/i18n.go
This helps debug which translation is incorrect and needs to be adjusted when
users run into this and paste the output they see directly to i.e. the forum.
> cmd/snap: include locale when linting description being lower case

- packaging/debian-sid/patches/0007-i18n-use-dummy-localizations-to-avoid-dependencies.patch
Some i18n related changes landed recently in master. The Debian Sid packaging
carries a patch which needs to be updated to apply cleanly.
> packaging/debian-sid: update locale patch for the latest master

- release-tools/changelog.py
Use a more general regular expression with a capturing group to enable
modifying just the version number we need to change without needing the hackish
manual whitespace bits inserted as part of the version number to replace. This
also enables us to confirm that only one version modification was made to the
file whereas previously we could be accidentally modifying more than one line
without realizing it.
Also optimizing the reading and writing of files so we only read each file we
need once, modify it in a memory buffer, then write it back out once. This
should make the script faster and less likely to fail with half modified files
where only the version number was changed but not the changelog itself for
example with the Fedora spec file.
Thanks to Maciej for all the suggestions!
> release-tools/changelog.py: refactor regexp + file reading/writing

- tests/lib/reset.sh
We have observed nc to get stuck on Debian 10 when snapd socket is restart. The
problem can also reproduced locally at random. Try to apply the workaround we
have for Fedora 34 on Debian.
> tests/lib/reset: make nc exit after a while when connection is idle

- overlord/devicestate/devicemgr.go
- overlord/managers_test.go
When running managers tests, the device manager is created as part of the test
setup. The modeenv is only read once, when the manager is created, thus making
it problematic for tests that modify the modeenv to observe the desired changes.
Add a helper that allows for reloading the modeenv in tests.
> overlord, overlord/devicestate: allow for reloading modeenv in devicemgr when testing

- osutil/meminfo.go
- osutil/meminfo_test.go
Introduce a helper to determine the total amount of memory in the system by
inspecting the contents of /proc/meminfo.
So that we can extend the idea in #10295 and look at memory too.
> osutil: a helper to find out the total amount of memory in the system

- overlord/snapstate/autorefresh.go
- overlord/snapstate/export_test.go
- overlord/snapstate/handlers_prereq_test.go
- overlord/snapstate/refreshhints_test.go
- overlord/snapstate/snapstate.go
- overlord/snapstate/snapstate_install_test.go
- overlord/snapstate/snapstate_test.go
- overlord/snapstate/snapstate_update_test.go
- overlord/snapstate/storehelpers.go
- overlord/snapstate/storehelpers_test.go
Extracted from #10261 
Introduce minimalInstallInfo interface and manualUpdateInfo that implements it, plus update refreshCandidate to implement it. This allows for reusing some of the existing logic where previously we would be passing full snap.Info (such as installSize helper).
> o/snapstate: introduce minimalInstallInfo interface

- systemd/emulation.go
- systemd/systemd.go
- systemd/systemd_test.go
The unit can be a service or a slice. If the unit or slice doesn't exist or is
not active, then an error is returned.
This is needed for daemon to get the current memory usage for a quota
group.
> systemd: add CurrentMemoryUsage to get current memory usage for a unit

- overlord/servicestate/servicemgr_test.go
- snap/quota/quota.go
- snap/quota/quota_test.go
- systemd/emulation.go
- systemd/systemd.go
- systemd/systemd_test.go
Based on top of #10304. 
The function returns 0 for slices that don't currently exist.
> snap/quota: add CurrentMemoryUsage for current memory usage of a quota group

- overlord/devicestate/devicestate_systems_test.go
- overlord/devicestate/systems_test.go
- seed/seedtest/seedtest.go
- seed/seedwriter/writer_test.go
In preparation for managers level tests using the helper, move it around to the seedtest package.
> seed/seedtest, overlord/devicestate: move seed validation helper to seedtest

- daemon/api_quotas.go
- daemon/api_quotas_test.go
- daemon/export_api_quotas_test.go
This is needed in order to support quota group updates.
> daemon/api_quotas.go: support updating quotas with ensure action

- gadget/install/export_test.go
- gadget/install/partition.go
- gadget/install/partition_test.go
This commit allows creating the "Windows Basic Data Partition"
as part of the gadget.yaml. This is needed so that the ubuntu-boot
partition can be put on a gpt vfat partition. Note that we already
support this for non-gpt partition layouts.
> gadget: support creating vfat partitions during bootstrap

- overlord/managers_test.go
- overlord/snapstate/snapstate.go
The `update-gadget-assets` task used to have "gadget" hardcoded
in the human readable description.
This commit changes the description to read
```
Update assets from gadget "<gadget-snap>"
Update assets from kernel "<kernel-snap>"
```
depending on the type.
Note that the task kind does not change, I think that's okay
because even though the assets come from the kernel snap they
are defined in the gadget.
Build on top of   https://github.com/snapcore/snapd/pull/9981
> snapstate: adjust update-gadget-assets user visible message

- packaging/ubuntu-16.04/changelog
This is needed to prevent the edge builds of the core snap from moving backwards, the real 2.51 changelog will be landed to release/2.51 in a separate PR shortly.
> packaging/ubuntu-16.04/changelog: add 2.50 and 2.50.1 changelogs, placeholder for 2.51

- packaging/fedora/snapd.spec
This was generated incorrectly by release-tools/changelog.py, but is now fixed
in https://github.com/snapcore/snapd/pull/10315.
This is https://github.com/snapcore/snapd/pull/10319, but for release/2.51.
> packaging/fedora/snapd.spec: correct date format in changelog

- interfaces/apparmor/apparmor.go
- interfaces/apparmor/apparmor_test.go
When the system has a single CPU, snapd would not pass any jobs flags to
apparmor_parser. In such case, the defaults would be used, which allow for up to
8 jobs to be started in parallel. What means, that with the way we pass the
flags, in a system with a single CPU would run the same number of jobs as 10 CPU
one (as we use #CPU - 2 there). Since the system has just 1 CPU, set the number of jobs
to 1 (same also for 2 CPUs).
There is an apparmor 3.x feature [1] that makes -j0 mean use the main process and don't fork but is not backward compatible (-j0 in apparmor 2.x means auto).
1. https://gitlab.com/apparmor/apparmor/-/blob/7dcf013bcab9548582734db244ba74f09449f9c1/parser/parser_main.c
> interfaces/apparmor: limit the number of jobs when running with a single CPU

- overlord/snapstate/autorefresh.go
- overlord/snapstate/autorefresh_test.go
Bump max postponement for refreshes from 60 to 95 days, Loosely related to refresh control feature, proposed separately to slightly reduce the diff of other PR.
This aligns maximum holding to what can be done with cohorts which allow already for 90 days.
> o/snapstate: bump max postponement from 60 to 95 days

- release-tools/changelog.py
This just basically adds a basic templated header to the changelog entries and
makes the changelog entries align with proper markdown lists etc.
Eventually it would be super nice to be able to use the GitHub API to actually
create the release after it has been tagged and pushed, etc. with this included
automatically, but that will require an API key and also code, so it is left as
a future improvement.
See https://github.com/snapcore/snapd/releases/tag/2.51 for an example of what it looks like IRL
> release-tools/changelog.py: add function to generate github release template

- release-tools/changelog.py
Miscellaneous little fixes I needed to apply to actually use the script for the 2.51 release. 
* The LP SRU bug release needs to be different for major releases, eventually for minor releases we can probably(?) auto-detect the right bug number, but for new major releases it should always be a new LP bug
* The line length check was incorrect
* For some weird reason I see that on my machine I don't get a %z timezone format string specified, so use UTC if this ends up the case
* Fix the Fedora *.spec file date format generation, I had switched around the order of the name of the month and the day of the month.
> release-tool/changelog.py: misc fixes from real world usage

- cmd/snap/cmd_info_test.go
This test would always fail if run on a machine configured with a time
zone more to the east of UTC+2, because in those timezones the refresh
date returned by the mock server correspond to 2006-01-03, and not to
2006-01-02.
> cmd/snap/cmd_info_test.go: make test robust against TZ changes

- interfaces/builtin/dsp.go
- interfaces/builtin/dsp_test.go
The /dev/cavalry is required to enable vector processor featuers when
flavor is from Ambarella chip.
> interfaces/dsp: add /dev/cavalry into dsp interface

- tests/main/snap-quota-groups/task.yaml
- tests/main/snap-quota/task.yaml
- wrappers/services.go
- wrappers/services_test.go
Add a test that snap quota groups functionally work to limit memory usage and
that they thread together the various systemd implementation bits properly.
> tests/main/snap-quota-groups: add functional spread test for quota groups

- daemon/api_aliases.go
- daemon/api_apps.go
- daemon/api_apps_test.go
- daemon/api_asserts.go
- daemon/api_base_test.go
- daemon/api_debug.go
- daemon/api_download_test.go
- daemon/api_general_test.go
- daemon/api_interfaces.go
- daemon/api_model.go
- daemon/api_sideload_n_try.go
- daemon/api_sideload_n_try_test.go
- daemon/api_snap_conf.go
- daemon/api_snap_file_test.go
- daemon/api_snaps.go
- daemon/api_snaps_test.go
- daemon/api_snapshots.go
- daemon/api_themes.go
- daemon/api_users_test.go
- daemon/daemon.go
- daemon/errors.go
- daemon/errors_test.go
- daemon/export_test.go
- daemon/response.go
- daemon/response_test.go
This is the first branch in a series, the goal is to streamline how responses, also error responses in particular are built in daemon.
To achieve that this introduces a StructuredResponse interface and a apiError structure and then it starts changing/simplifying how response are built and the corresponding helpers.
> daemon: introduce StructuredResponse and apiError

- daemon/api_quotas.go
- daemon/api_quotas_test.go
- daemon/export_api_quotas_test.go
- tests/main/snap-quota-groups/task.yaml
- tests/main/snap-quota/task.yaml
Also disable the spread tests on Amazon Linux 2 and Centos 7, since those
systems will require work-arounds that we don't want to propose in this PR.
In a follow-up, we will either:
I have intentionally not linked this to any other PR to prevent confusion. Please re-review this on its own merits.
> daemon/api_quotas.go: include current memory usage information in results

- usersession/userd/privileged_desktop_launcher_test.go
The unit tests will fail right now on systems that do not have
systemd installed (like the trusty sbuild containers) because
`systemd --version` is called but not mocked.
This commit should fix this. I tested it in spread and manually removing systemd.
> userd: mock `systemd --version` in privilegedDesktopLauncherSuite

- systemd/systemd.go
- systemd/systemd_test.go
We recently had a build failure on trusty in a schroot environment.
It turned out that the issue was that no systemctl binary was installed
there. But the error was a bit misleading:
```
[--version] failed with exit status 0:
```
This commit improves the error reporting for non-exit code errors
and errors that do not have an associated exit status.
> systemd: improve systemctl error reporting

- overlord/devicestate/devicestate.go
- overlord/devicestate/devicestate_remodel_test.go
- overlord/managers_test.go
By agreement, we will require a serial assertion to be present before remodeling
can be started. The change adds relevant checks and updates the tests.
Remodel spread tests may fail at this point.
> o/devicestate: require serial assertion before remodeling can be started

- overlord/servicestate/quota_control_test.go
This puts the responsibility of escaping into the helpers and makes it a bit
easier to write tests for group names that need to be escaped.
Also modify one of the test cases to make sure that we have coverage of group
names with escaped characters in the name.
> o/servicestate/quota_control_test.go: change helper escaping

- interfaces/builtin/opengl.go
In some boards, the path to access Xilinx zocl DRM driver is
/sys/devices/platform/amba/amba:zyxclmm_drm/
, without the _pl* postfix. Change appamor path to make it accessible
from confined apps.
Details of the driver in
https://github.com/Xilinx/XRT/tree/master/src/runtime_src/core/edge/drm.
> interfaces: opengl: change path for Xilinx zocl driver

- client/quota.go
- client/quota_test.go
- cmd/snap/cmd_quota.go
- cmd/snap/cmd_quota_test.go
- daemon/api_quotas.go
- daemon/api_quotas_test.go
- daemon/export_api_quotas_test.go
- tests/main/snap-quota-groups/task.yaml
- tests/main/snap-quota/task.yaml
* Make quota command only responsible for showing/displaying quota group
information.
* Introduce new set-quota command which creates or updates quota groups
* Move the display of memory limit under a map section "constraints" which then
has a memory key to allow future resource types to live under this section.
* Display current memory usage for quota groups under a new section "current",
which like "constraints" can be expanded for future resource types too.
Also update the spread test to check that memory usage reported by snapd is 
approximately that of what the kernel reports. 
THE SPREAD TESTS ARE FINALLY HAPPY :tada: :t-rex: :tada: :taco: :shipit:
> cmd/snap/quota: refactor quota CLI as per new design 

- store/store_action.go
- store/store_action_test.go
Extend context and action objects of SnapAction with optional validation-sets arrays, they are going to be used with enforcing mode on refresh and install.
From validation-sets spec:
"The existing refresh context is an array of objects with mandatory: snap-id, revision, tracking-channel and instance-key fields. The context and action item fields will be extended to allow for passing the information about relevant validation sets governing the revision decision for the snap (multiple per snap are possible if they all specified the same revision):
- The context objects would gain an optional validation-sets field. This is relevant for snaps being refreshed.
The action object for an install action will accept an optional validation-sets field as well. 
In both cases the same format for the …
> store: extend context and action objects of SnapAction with validation-sets

- cmd/snap-mgmt/snap-mgmt.sh.in
- packaging/ubuntu-16.04/snapd.postrm
- tests/main/postrm-purge/task.yaml
- tests/main/snap-mgmt/task.yaml
- wrappers/services.go
- wrappers/services_test.go
Removing slice units when we purge snapd requires us to add `X-Snappy` to the slice units we generate.
> wrappers, packaging, snap-mgmt: handle removing slices on purge too

- daemon/api_asserts_test.go
- daemon/api_download_test.go
- daemon/api_general_test.go
- daemon/api_snaps_test.go
- daemon/export_test.go
- daemon/response.go
- daemon/response_test.go
The partly generic role of resp was taken over and extended by the StructuredResponse interface instead.
> daemon: drop resp completely in favor of using respJSON consistently

- overlord/snapstate/backend_test.go
- overlord/snapstate/handlers.go
- overlord/snapstate/snapstate_test.go
The mutex needs to be locked after backend.StartServices() returns, but before
returning from the function such that the state of the mutex matches was earlier
defers expect.
Observed in the wild:
```
fatal error: sync: unlock of unlocked mutex
goroutine 84 [running]:
runtime.throw(0x55faf19fed79, 0x1e)
/usr/lib/go-1.10/src/runtime/panic.go:616 +0x83 fp=0xc42068f9f0 sp=0xc42068f9d0 pc=0x55faf11713a3
sync.throw(0x55faf19fed79, 0x1e)
/usr/lib/go-1.10/src/runtime/panic.go:605 +0x37 fp=0xc42068fa10 sp=0xc42068f9f0 pc=0x55faf1171317
sync.(*Mutex).Unlock(0xc42039f3b0)
/usr/lib/go-1.10/src/sync/mutex.go:184 +0xc4 fp=0xc42068fa38 sp=0xc42068fa10 pc=0x55faf11b6264
github.com/snapcore/snapd/overlord/state.(*State).unlock(0xc42039f3b0)
/build/snapd/parts/snapd-deb/build/_build/src/github.com/snapcore …
```
> overlord/snapstate: lock the mutex before returning from stop snap services undo

- overlord/servicestate/quota_control.go
- overlord/servicestate/quota_handlers.go
This new file will be the home of the new handlers we execute as tasks for the
change based quota group modifications.
Also slightly refactor to use an options struct instead of defaulting to empty
things. 
The only real code change here is introducing the options struct and initializing
it, the rest of the function's implementation should be the same.
This is mainly to reduce the diff in other PR's since this function's more natural 
home I think is alongside the handlers rather than the top-level functions creating
the tasks for the handlers.
Broken out from #10347
> overlord/servicestate: mv ensureSnapServicesForGroup to new file

- snap/quota/quota.go
- snap/quota/quota_test.go
- systemd/emulation.go
- systemd/systemd.go
- systemd/systemd_test.go
- tests/main/snap-quota-groups/task.yaml
- tests/main/snap-quota/task.yaml
- wrappers/services.go
- wrappers/services_test.go
This PR implements what I think is a reasonable compromise around supporting these older systems by identifying the specific buggy situation and changing the memory usage from 16 exbibytes to 0 in that specific scenario only, using code that should be easy to read and reason about. 
It also re-enables the spread tests which demonstrate that the work-around works, specifically that on these buggy systems:
> many: fix quota groups for centos 7, amazon linux 2 w/ workaround for buggy systemd

- daemon/api_general.go
- overlord/devicestate/devicectx.go
- overlord/devicestate/devicemgr.go
- overlord/devicestate/devicestate_test.go
- overlord/devicestate/export_test.go
- overlord/devicestate/remodel.go
the expectations control whether to report "run" or "" on non-UC20
systems.
this is an idea discussed with @bboozzoo, it avoids having to resort to
use the cached value field directly sometimes which is confusing.
> daemon,o/devicestate: have DeviceManager.SystemMode take an expectation on the system

- overlord/servicestate/service_control.go
This is mainly for myself in the future when I inevitably get confused about
this field.
Asking for review from a few folks to make sure I got this all correct.
> o/servicestate/service_control.go: add comment about ExplicitServices

- daemon/api_aliases_test.go
- daemon/api_apps_test.go
- daemon/api_base_test.go
- daemon/api_cohort_test.go
- daemon/api_download_test.go
- daemon/api_find_test.go
- daemon/api_general_test.go
- daemon/api_model_test.go
- daemon/api_quotas_test.go
- daemon/api_sideload_n_try_test.go
- daemon/api_snapctl_test.go
- daemon/api_snaps_test.go
- daemon/api_snapshots_test.go
- daemon/api_systems_test.go
- daemon/api_users_test.go
- daemon/api_validate_test.go
- daemon/export_test.go
This is possible now that apiError is used everywhere to return errors.
This contains also some final cleanups, for example dropping now superfluous apiBaseSuite.apiErrorReq.
> daemon: have apiBaseSuite.errorReq return *apiError directly 

- boot/boot.go
- boot/boot_test.go
- boot/bootstate20.go
- boot/makebootable.go
- boot/makebootable_test.go
- boot/modeenv.go
- boot/modeenv_test.go
A preparatory PR for further remodel work. Improve tracking of current model in the modeenv by adding all properties that are measured by secboot (model, brand, sign-key-id, and implicit series which is fixed now). Add fields that will describe the candidate model.
> boot: track model's sign key ID, prepare infra for tracking candidate model

- overlord/assertstate/assertstate_test.go
- overlord/hookstate/context_test.go
- overlord/hookstate/ctlcmd/get_test.go
- overlord/hookstate/ctlcmd/is_connected_test.go
- overlord/hookstate/ctlcmd/refresh_test.go
- overlord/hookstate/ctlcmd/set_test.go
- overlord/hookstate/ctlcmd/system_mode.go
- overlord/hookstate/ctlcmd/system_mode_test.go
- overlord/hookstate/ctlcmd/unset_test.go
- overlord/hookstate/hooktest/handler_test.go
- overlord/ifacestate/hotplug_test.go
- overlord/ifacestate/implicit_test.go
- overlord/overlord.go
- overlord/servicestate/service_control.go
- overlord/snapstate/autorefresh_gating_test.go
- overlord/snapstate/backend/aliases_test.go
- overlord/snapstate/backend/backend_test.go
- overlord/snapstate/backend/copydata_test.go
- overlord/snapstate/backend/link_test.go
- overlord/snapstate/backend/snapdata_test.go
- overlord/snapstate/check_snap_test.go
- overlord/snapstate/snapstate_install_test.go
- overlord/snapstate/snapstate_test.go
- overlord/snapstate/snapstate_update_test.go
- overlord/state/change_test.go
- overlord/stateengine.go
assertstate_test.go was importing go-check both as check
and with . ??, this confused gci, I had to clean that up manually
> overlord: fix imports ordering (according to gci)

- HACKING.md
This is because without that dependency ./run-checks will fail
> tests: new note in HACKING file to clarify about yamlordereddictloader dependency

- overlord/servicestate/service_control_test.go
Tests were not undoing the last Lock() operation on the state. We now
issue a "defer Unlock()" right after the first Lock() invocation to
ensure that the mutex will get unlocked when the test function stops.
Special care must be taken with check assertions occurring after the
state has been explicitly Unlocked() again, because a test failure would
cause the test function to terminate and the deferred operation would
attempt to unlock an unlocked mutex. That's why we avoid assertions
while in unlocked state, and instead just capture the subject of our
checks into variables and do the assertion only when the state has been
locked again.
> overlord/servicestate: improve test robustness with locking

- boot/modeenv.go
- boot/modeenv_test.go
A small bug landed with #10377. The checks for try model data inside modeenv were not consistent with the existing checks for current model. 
Also added some unit tests to cover consistency checks as suggested in https://github.com/snapcore/snapd/pull/10377#pullrequestreview-681679483
> boot: fix model inconsistency check in modeenv, extend unit tests

- overlord/hookstate/ctlcmd/refresh.go
- overlord/hookstate/ctlcmd/refresh_test.go
- overlord/hookstate/hooks.go
- overlord/snapstate/autorefresh_gating.go
- overlord/snapstate/autorefresh_gating_test.go
- overlord/snapstate/snapstate.go
Handle snapctl refresh --proceed and --hold actions. In addition to updating holdState via respective helpers, the action is also cached on the hook context, so that hook handler can know if the hook did anything, and implement a default behavior if needed.
> o/hookstate: handle snapctl refresh --proceed and --hold

- overlord/snapstate/handlers.go
- overlord/snapstate/handlers_link_test.go
- overlord/snapstate/snapmgr.go
- overlord/snapstate/snapstate_test.go
- overlord/snapstate/snapstate_update_test.go
Update LastRefreshTime in doLinkSnap on install/update (not on revert). Also rename the JSON field to last-refresh-time for consistency with refresh-inhibited-time.
> o/snapstate: update LastRefreshTime in doLinkSnap handler

- daemon/api_themes.go
- daemon/api_themes_test.go
- overlord/snapstate/backend.go
- store/details_v2.go
- store/store.go
- store/store_test.go
- store/storetest/storetest.go
Try to minimize the amount of data requested from the store when just mostly checking for a snap existence.
> many: introduce Store.SnapExists and use it in /v2/accessories/themes

- tests/main/security-device-cgroups-serial-port/task.yaml
- tests/main/security-device-cgroups/task.yaml
This change includes:
. When the rule is added, then teh TAGS and CURRENT_TAGS are updated
. Remove the snap and check the udev CURRENT_TAGS is remove
. After rebooting the system the udev TAGS is removed as well
To reproduce the error run:
google:ubuntu-21.04-64:tests/main/security-device-cgroups:uinput
google:ubuntu-21.04-64:tests/main/security-device-cgroups:kmsg
The error:
+ echo 'And other devices are not shown as assigned to the snap'
And other devices are not shown as assigned to the snap
+ not MATCH 'E: TAGS=.*snap_test-snapd-sh_sh'
+ udevadm info /sys/devices/virtual/misc/uinput
Full log: https://paste.ubuntu.com/p/CCtdrNTXPC/
> tests: fix issue when checking the udev tag on test security-device-cgroups

- overlord/servicestate/export_test.go
- overlord/servicestate/quota_control_test.go
This is a test-only change.
These unit tests exercise the more complicated logic which now lives in the
handlers, so call the handlers directly.
Also add some basic happy path tests for the exported functions to be sure that
they are still working, but the exported functions will shortly be refactored
to return task sets and not perform the logic directly.
Also adjust the error message from the handler implementation to match the
original implementation.
> o/servicestate/quota_control_test.go: test the handlers directly

- asserts/crypto.go
- asserts/fetcher_test.go
- asserts/gpgkeypairmgr_test.go
- asserts/ifacedecls_test.go
- asserts/snap_asserts.go
- asserts/snapasserts/snapasserts_test.go
- asserts/store_asserts_test.go
- asserts/sysdb/sysdb_test.go
- interfaces/apparmor/spec_test.go
- interfaces/builtin/all_test.go
- interfaces/builtin/display_control_test.go
- interfaces/builtin/wayland.go
- interfaces/core_test.go
- interfaces/dbus/dbus_test.go
- interfaces/hotplug/udevadm_test.go
- interfaces/policy/helpers_test.go
- interfaces/systemd/backend_test.go
- snap/container_test.go
- snap/epoch_test.go
- snap/info_snap_yaml_test.go
- snap/naming/validate_test.go
- snap/pack/pack_test.go
- snap/revision_test.go
- snap/snapdir/snapdir_test.go
- snap/types_test.go
- snap/validate_test.go
interfaces/core_test.go had an extra "." import of interfaces that needed manual fixing.
> asserts,interfaces,snap: fix imports order (according to gci)

- tests/lib/cloud-init-seeds/attacker-user/user-data
- tests/lib/cloud-init-seeds/normal-user/user-data
- tests/lib/nested.sh
- tests/nested/manual/grade-signed-cloud-init-testkeys/task.yaml
This is easier to read and tell what the password is, and since these are all
for test user accounts on walled off VM's the obscurity is more annoying than
anything else.
Also fix a typo
> tests/many: change all cloud-init passwords for ubuntu to use plain_test_passwd

- tests/main/postrm-purge/task.yaml
The grep could not match any snap service due to them weres removed. So
the debug section will fail as in the following example:
2021-06-14 11:24:27 Error debugging
google:arch-linux-64:tests/main/postrm-purge (jun141057-913226) :
-----
+ grep -E 'snap\..*\.(service|timer|socket|slice)'
+ systemctl --no-legend --full
-----
If the debug fail for the test, then the debug each is not executed and
we can't see usefull information.
> tests: fix debug section for postrm-purge test

- interfaces/builtin/dsp.go
It seems we accidentally merged the dsp interface with a debug printf left intact. Let's remove it.
> interfaces: remove leftover debug print

- tests/lib/snaps/test-snapd-policy-app-consumer/meta/snap.yaml
This interface only existed temporarily during the lifetime of
snapcore/snapd#10110.
> tests/lib/snaps/test-snapd-policy-app-consumer: remove dsp-control interface

- cmd/snap-bootstrap/cmd_initramfs_mounts.go
- cmd/snap-bootstrap/initramfs_systemd_mount_test.go
- cmd/snap-exec/main_test.go
- cmd/snap-preseed/main_test.go
- cmd/snap-seccomp/main.go
- cmd/snap-seccomp/main_test.go
- cmd/snap-seccomp/versioninfo_test.go
- cmd/snap/cmd_buy.go
- cmd/snap/cmd_changes.go
- cmd/snap/cmd_confinement.go
- cmd/snap/cmd_connect.go
- cmd/snap/cmd_disconnect.go
- cmd/snap/cmd_interface.go
- cmd/snap/cmd_interfaces.go
- cmd/snap/cmd_keys.go
- cmd/snap/cmd_known_test.go
- cmd/snap/cmd_managed.go
- cmd/snap/cmd_pack.go
- cmd/snap/cmd_prefer.go
- cmd/snap/cmd_remove_user.go
- cmd/snap/cmd_sign_build.go
- cmd/snap/cmd_sign_test.go
- cmd/snap/cmd_unalias.go
- cmd/snap/cmd_whoami.go
- cmd/snap/cmd_whoami_test.go
- cmd/snap/color_test.go
- cmd/snap/main.go
- cmd/snap/main_test.go
- cmd/snapctl/main_test.go
- cmd/snapd/main_test.go
gci needed cmd/snap-seccomp/main.go import comment to made one long line otherwise it keeps only the last line :(
cmd/snap/color_test.go needed some manual cleanup of commented out imports
> cmd: fix imports order (according to gci)

- cmd/snap-bootstrap/initramfs_systemd_mount.go
- cmd/snap-bootstrap/initramfs_systemd_mount_test.go
Add new `Bind` option to systemdMountOptions struct.
> snap-bootstrap: add bind option with tests

- daemon/access.go
- daemon/access_test.go
- daemon/daemon.go
- daemon/daemon_test.go
We want to make the theme installation REST API available to selected snaps over the `snapd-snap.socket` socket.  At present, the idea is to control which snaps have access to these calls through a marker interface. That means the access checker will need to be able to check whether a given snap has a connected plug of the marker interface.  I've done this by passing the `Daemon` as an argument to the`CheckAccess` method.
There are some alternatives that could be used instead:
* We really want the `Overlord` to perform the interface connection check, so we could pass that instead. There may be other future use cases that need more than the Overlord though.
* `Command` would also be usable here, since it holds a pointer to the `Daemon`.  It's not clear what other information in that struct …
> daemon: add a Daemon argument to AccessChecker.CheckAccess

- cmd/snap-preseed/main_test.go
- cmd/snap-preseed/preseed_linux.go
Include actual mount command and error output if snap-preseed fails early when mounting core/snapd snaps.
At the moment the error is just:
```
+ /usr/lib/snapd/snap-preseed /tmp/tmp.1HOxEDtVav
error: cannot mount /var/lib/snapd/seed/snaps/snapd_11843.snap at /tmp/snapd-preseed in preseed mode: exit status 32 
```
> cmd/snap-preseed: provide more error info if snap-preseed fails early on mount

- README.md
Snapd developers have moved away from Freenode to Libera Chat.
Fixes: https://bugs.launchpad.net/snappy/+bug/1932129
> README.md: refer to new IRC server

- overlord/snapstate/handlers.go
Looking at that code wrt Maciek's fix in https://github.com/snapcore/snapd/pull/10357, I noticed undoStartSnapServices is not unlocking the state before calling the backend to stop services.
> o/snapstate: unlock the state before calling backend in undoStartSnapServices

- overlord/snapstate/autorefresh_gating.go
- overlord/snapstate/autorefresh_gating_test.go
Wire up HeldSnaps helper with snapsToRefresh and only refresh snaps that are not held in autoRefreshPhase2.
> o/snapstate: consider held snaps in autoRefreshPhase2

- boot/flags_test.go
- bootloader/lk.go
- client/asserts.go
- client/asserts_test.go
- client/cohort_test.go
- client/icons_test.go
- client/model_test.go
- client/snapctl_test.go
- daemon/daemon_test.go
- errtracker/errtracker_test.go
- image/image_linux.go
- sanity/squashfs.go
- store/details_v2_test.go
- store/export_test.go
- sysconfig/gadget_defaults_test.go
- systemd/systemd_test.go
- tests/lib/fakestore/store/store_test.go
- usersession/agent/rest_api_test.go
- usersession/userd/launcher_test.go
- usersession/userd/ui/zenity_test.go
- usersession/xdgopenproxy/xdgopenproxy_test.go
- wrappers/services_test.go
had to make the comment in wrappers/services_test.go a one-liner
otherwise half of it is lost
last set of files needing changing (as per current master)
> many: fix imports order (according to gci)

- packaging/debian-sid/patches/0001-cmd-snap-seccomp-use-upstream-seccomp-package.patch
Update the patches so that they can be applied on latest master.
> packaging/debian-sid: update snap-seccomp patches for latest master

- tests/lib/snaps/test-snapd-policy-app-consumer/meta/snap.yaml
- tests/lib/tools/os.query
- tests/main/interfaces-many-core-provided/task.yaml
- tests/main/interfaces-many-snap-provided/task.yaml
This change just impacts debian10
The test now selects randomly the 30% of the interfaces to connect and
disconnect.
It is because debian 10 has some performance issues disconnecting
interfaces.
Also os.query tool has been updated to include a new check for debian 10
> tests: connect 30% of the interfaces on test interfaces-many-core-provided 

- spread.yaml
- tests/main/lxd/task.yaml
On 2021.06.15 with LXD 4.15/candidate (rev 20717, latest/candidate at the time)
we've started observing failures related to starting nested LXD containers, with
the following errors:
```
create_inode: failed to create character device /var/snap/lxd/common/lxd/storage-pools/default/containers/my-inner-ubuntu/rootfs/dev/full, because Operation not permitted
create_inode: failed to create character device /var/snap/lxd/common/lxd/storage-pools/default/containers/my-inner-ubuntu/rootfs/dev/mapper/control, because Operation not permitted
create_inode: failed to create character device /var/snap/lxd/common/lxd/storage-pools/default/containers/my-inner-ubuntu/rootfs/dev/null, because Operation not permitted
create_inode: failed to create character device …
```
> spread, tests/main/lxd: no longer manual, switch to latest/stable

- spread.yaml
The LXD team has landed a fix in https://github.com/lxc/lxd/pull/8901. Switch
back to the candidate channel.
> spread: switch LXD back to latest/candidate channel

- overlord/hookstate/ctlcmd/refresh.go
- overlord/hookstate/ctlcmd/refresh_test.go
Do not call ProceedWithRefresh immediately from snapctl as this would allow snap to abuse it to reset its holdState and then follow it with --hold, bypassing existing hold start time (and hold duration limit). Instead, only cache proceed action on the context - the actual proceed logic will be executed by the hook handler.
> o/hookstate/ctlcmd: do not call ProceedWithRefresh immediately from snapctl

- overlord/servicestate/quota_control_test.go
- overlord/servicestate/quota_handlers.go
The variables produced by this bit of code are not used anymore.
Reference: https://github.com/snapcore/snapd/pull/10266#discussion_r653622039
> overlord/servicestate: avoid unnecessary computation of disabled services

- overlord/servicestate/internal/quotas.go
- overlord/servicestate/internal/quotas_test.go
- overlord/servicestate/quota_control.go
- overlord/servicestate/quota_handlers.go
- overlord/servicestate/quotas.go
- overlord/servicestate/quotas_test.go
- overlord/servicestate/servicestate_test.go
- overlord/servicestate/servicestatetest/quotas.go
this splits most of quotas.go into an internal package and
introduces a dedicated servicestatetest package exposing PatchQuotas
this should allow to  have in servicestattest a clean test-only
API to mock quotas in state
> o/servicestate: introduce internal and servicestatetest

- overlord/servicestate/quota_control.go
- overlord/servicestate/quota_control_test.go
- packaging/debian-sid/snapd.postrm
- packaging/ubuntu-14.04/snapd.postrm
- snap/quota/quota.go
- snap/quota/quota_test.go
- tests/lib/tools/os.query
- tests/main/os.query/task.yaml
- tests/main/postrm-purge/task.yaml
- tests/main/quota-groups-systemd-accounting/task.yaml
- tests/main/snap-mgmt/task.yaml
- tests/main/snap-quota-groups/task.yaml
- tests/main/snap-quota/task.yaml
* Add a spread test for a new way to reproduce the buggy behavior from systemd's accounting, which is even worse as it propagates incorrect values to quota groups which are supposed to have real usage
* Remove the workaround we added previously since we don't need it anymore
Also pour one out for poor xenial and UC16 which will be left in the dust.
This undoes most of the workaround in https://github.com/snapcore/snapd/pull/10354, but leaves in place the systemd methods we added, since those will be useful when we expand to tasks/processes controlling/reporting.
> o/servicestate, snap/quota: eliminate workaround for buggy systemds, add spread test

- boot/assets.go
- boot/boot_test.go
- boot/bootstate20.go
- boot/cmdline.go
- boot/seal.go
- boot/seal_test.go
- boot/systems.go
The last 2 patches addressing unnecessary use of model in reseal and bootstate code.
> boot: drop model from resealing and boostate

- overlord/snapstate/autorefresh_gating.go
- overlord/snapstate/handlers.go
- overlord/snapstate/snapstate.go
- overlord/snapstate/snapstate_update_test.go
Remove installed snap from "snaps-hold" state so it's no longer held.
> o/snapstate: remove refreshed snap from snaps-hold in snapstate.doInstall

- overlord/hookstate/ctlcmd/refresh.go
- overlord/hookstate/ctlcmd/refresh_test.go
`snapctl refresh --pending --proceed` is a verbose way of saying "proceed" and should be allowed per spec.
> o/hookstate/ctlcmd: allow snapctl refresh --pending --proceed syntax.

- overlord/servicestate/quota_control.go
- overlord/servicestate/quota_handlers.go
- overlord/servicestate/quota_handlers_test.go
We can get rid of the meter argument to most of the helpers if we delay
creating the meter until when we need it doing systemd operations. When we do
those operations however, we also need to be careful to use the right meter,
since some operations are done with the state lock and some are done without
the state lock.
> o/servicestate: refactor meter handling, eliminate some common parameters

- cmd/.clangd
- cmd/Makefile.am
- cmd/autogen.sh
An assorted bunch of tweaks and updates for our C code, which has not been well taken care of until recently.
The patches fix the use of `make hack` such that it builds the snap-update-ns in a correct way. autogen has been fixed to work on openSUSE Tumbleweed and use a proper libexecdir there. Lastly, I've added a config file for [clangd](https://clangd.llvm.org/) which should be valid for most systems.
> cmd: a bunch of tweaks and updates

- overlord/snapstate/autorefresh_gating.go
- overlord/snapstate/autorefresh_gating_test.go
- overlord/snapstate/export_test.go
- overlord/snapstate/handlers.go
- overlord/snapstate/snapstate_remove_test.go
Prune snaps-hold state (both held and holding snaps) and refresh-candidates when a snap gets removed.
This introduces a new `pruneSnapsHold` helper; while it would be possible to use existing helpers (with two separate calls), a dedicated helper feels more natural, and is also more optimal.
> o/snapstate: prune gating information and refresh-candidates on snap removal

- tests/main/classic-prepare-image-no-core/task.yaml
- tests/main/classic-prepare-image/task.yaml
Ruuning with su the command "snap prepare image" is making followins
tests fail when them try to access to
/run/user/0/snapd-session-agent.socket
This happens when the su -c command is used without the test user
To reproduce the isse run:
> spread-debug -order -debug -single-worker
google:ubuntu-20.04-64:tests/main/classic-prepare-image
google:ubuntu-20.04-64:tests/main/snap-user-service-start-on-install
Like this example
>2021-06-18 14:36:25 Error executing
google:ubuntu-20.04-64:tests/main/snap-user-service-start-on-install
(jun181711-404796) :
>echo 'Install the a snap with user services while a user session is
active'
>Install the a snap with user services while a user session is active
/home/gopath/src/github.com/snapcore/snapd/tests/lib/tools/snaps-state
>install-local …
> tests: fix classic-prepare-image test

- overlord/servicestate/export_test.go
- overlord/servicestate/quota_control.go
- overlord/servicestate/quota_handlers.go
- overlord/servicestate/quota_handlers_test.go
This is done by splitting ensureSnapServicesForGroup and separating out restartSnapServices.
The reason for this refactoring is that we need to swap out the SetStatus(DoneStatus) with some other state handling to track the work done and to do. The effect of the current code is that a change using this, is considered Done before the services are restarted which we don't want. We still need to track things such in the case of a restart (panic for example) or reboot we do the right thing, the actual fix for that will come in a separate PR.
> o/servicestate: move SetStatus to doQuotaControl

- tests/lib/reset.sh
- tests/main/security-dev-input-event-denied/task.yaml
Force group events are processed after uninstall the test-snapd-event snap
To check the test is fixed, run:
> spread -debug -repeat 20 google:ubuntu-core-18-64:tests/main/security-dev-input-event-denied
> tests: fix restore for security-dev-input-event-denied test

- HACKING.md
With go1.16 we need to disable go modules or our instructions
will fail at the "go get" stage because go will try to init
using go modules.
This can be dropped once we move to go 1.13 but right now
out instructions do not work for people on Ubuntu 21.04 or
similar new distro releases.
> HACKING.md: update instructions for go1.16+

- overlord/devicestate/devicemgr.go
- overlord/managers_test.go
Followup to https://github.com/snapcore/snapd/pull/10361 I promised to @pedronis
> overlord, o/devicestate: use a single test helper for resetting to a post boot state

- cmd/snap-update-ns/bootstrap.go
With newer go (1.16) and some refactoring tools such as gorename, a rename or
refactor in the whole source tree may be invoked from an external directory. In
this case, the include search path does not necessarily include the package
source directory. Make sure that the path is included.
> cmd/snap-update-ns: add SRCDIR to include search path

- overlord/configstate/hooks.go
- overlord/devicestate/devicemgr.go
- overlord/healthstate/healthstate.go
- overlord/hookstate/hookmgr.go
- overlord/hookstate/hooks.go
- overlord/hookstate/hookstate_test.go
- overlord/hookstate/hooktest/handler.go
- overlord/hookstate/hooktest/handler_test.go
- overlord/ifacestate/hooks.go
Return bool flag from Error() function of hook handler to indicate to the hook manager that hook task should not error out with 
the original hook error.
This is needed for gate-auto-refresh hook handler to handle errors and not fail the entire change.
> o/hookstate: return bool flag from Error function of hook handler to ignore hook errors

- overlord/snapstate/autorefresh_gating.go
- overlord/snapstate/autorefresh_gating_test.go
- overlord/snapstate/handlers.go
- overlord/snapstate/snapmgr.go
- overlord/snapstate/snapstate.go
Make conditional-auto-refresh task conflict with other tasks via affected snaps.
> o/snapstate: make conditional-auto-refresh conflict with other tasks via affected snaps

- cmd/libsnap-confine-private/cgroup-support.c
- cmd/snap-confine/mount-support.c
- cmd/snapd-generator/main.c
Sparse identified the following issues:
```
libsnap-confine-private/cgroup-support-test.c: note: in included file:
libsnap-confine-private/cgroup-support.c:82:22: warning: non-ANSI function declaration of function 'sc_cgroup_is_v2'
snap-confine/mount-support.c:163:68: warning: Using plain integer as NULL pointer
snap-confine/mount-support.c:761:47: warning: Using plain integer as NULL pointer
snap-confine/mount-support.c:807:73: warning: Using plain integer as NULL pointer
snap-confine/mount-support.c:830:57: warning: Using plain integer as NULL pointer
snap-confine/mount-support.c:835:57: warning: Using plain integer as NULL pointer
snapd-generator/main.c:46:5: warning: symbol 'ensure_root_fs_shared' was not declared. Should it be static?
snapd-generator/main.c:164:5: warning: symbol …
```
> cmd/snap-confine, cmd/snapd-generator: fix issues identified by sparse

- cmd/snap/cmd_snap_op_test.go
The TestInstallNoPATH unit test is currently failing when the SUDO_UID
environment is set. This happens e.g. in a pbuilder environment.
To reproduce:
```
$ SUDO_UID=100 go test -check.f TestInstallNoPATH
FAIL: cmd_snap_op_test.go:229: SnapOpSuite.TestInstallNoPATH
cmd_snap_op_test.go:252:
c.Check(s.Stderr(), testutil.MatchesWrapped, `Warning: \S+/bin was not found in your \$PATH.*`)
... wrapped string = ""
... expected string = "Warning: \\S+/bin was not found in your \\$PATH.*"
```
The fix is to ensure that SUDO_UID is unset in this test.
> snap: fix TestInstallNoPATH unit test failure when SUDO_UID is set

- cmd/Makefile.am
- cmd/libsnap-confine-private/cgroup-support-test.c
- cmd/libsnap-confine-private/cgroup-support.c
- cmd/libsnap-confine-private/cgroup-support.h
- cmd/snap-confine/ns-support.c
- cmd/snap-confine/snap-confine.apparmor.in
- cmd/snap-confine/snap-confine.c
- tests/main/stale-base-snap/task.yaml
Fix the mount namespace usage check to work with a cgroup v2 setup. Previously,
the snap processes would end up in a separate group under the freezer
controller, making the check simple and efficient.
With cgroups v2, there is are separate controllers. However, each snap process
is moved to a tracking group (systemd scope) created by snap run early in the
call chain. We can use that property to locate processes from a given snap. The
groups are managed externally by systemd, which takes care of the cleanup once
the last process exits. A slight detour is that snap-confine is no longer
responsible for placing the process inside the group, as the step has been done
early on by either the system or user systemd instance.
The patch refactors the code to be aware of the tracking group, and …
> cmd/snap-confine: make mount ns use check cgroup v2 compatible

- cmd/snaplock/runinhibit/inhibit.go
- overlord/hookstate/hooks.go
- overlord/hookstate/hooks_test.go
- overlord/snapstate/autorefresh_gating.go
Dedicated handler for gate-auto-refresh hook. The handler implements the default behavior if the hook doesn't call snapctl refresh --hold/--proceed as well as error handling if the hook errors out. It also manipulates runinhibit lock.
> o/hookstate: dedicated handler for gate-auto-refresh hook

- overlord/devicestate/devicemgr.go
since it can be used consistently its first usage happens much earlier
in the file now, being placed directly after modeenv helpers makes also
sense
> o/devicestate: move SystemMode method before first usage

- cmd/snap-update-ns/bootstrap.go
This reverts commit 08c2e6da1b72cb4d21436f1ba1f1c15f66a83187.
The launchpad builds are failing like so:
```
(cd _build/bin && GOPATH=$(pwd)/.. GO111MODULE=off GOCACHE=/tmp/go-build go build --ldflags '-extldflags "-static"'  github.com/snapcore/snapd/cmd/snap-update-ns)
can't load package: package github.com/snapcore/snapd/cmd/snap-update-ns: /<<BUILDDIR>>/snapd-2.51.1+git3058.84b3a3c8~ubuntu16.04.1/_build/src/github.com/snapcore/snapd/cmd/snap-update-ns/bootstrap.go: malformed #cgo argument: -I/<<BUILDDIR>>/snapd-2.51.1+git3058.84b3a3c8~ubuntu16.04.1/_build/src/github.com/snapcore/snapd/cmd/snap-update-ns
debian/rules:167: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 1
make[1]: Leaving directory …
```
> cmd/snap-update-ns: Revert "cmd/snap-update-ns: add SRCDIR to include search path"

- store/store_download.go
The log appears is visible in the user's terminal when running `snap download`
command.
Reported in the forum: https://forum.snapcraft.io/t/snap-download-slips-in-extra-logging-with-download-size/25151
> store: make the log with download size a debug one

- cmd/libsnap-confine-private/cgroup-support-test.c
- cmd/libsnap-confine-private/cgroup-support.c
Bump the maximum depth of cgorups hierarchy tree to 32.
As requested in https://github.com/snapcore/snapd/pull/10436#discussion_r658613399
> cmd/libsnap-confine-private: bump max depth of groups hierarchy to 32

- overlord/configstate/config/helpers.go
- overlord/configstate/configcore/corecfg.go
- overlord/configstate/configcore/handlers.go
- overlord/configstate/configcore/swap.go
- overlord/configstate/configcore/swap_test.go
- tests/core/swapfiles/task.yaml
This is https://github.com/snapcore/snapd/pull/9932 for 2.51 to allow a clean cherry pick of https://github.com/snapcore/snapd/pull/10446
> o/configstate/configcore: support snap set system swap.size=... (2.51)

- overlord/servicestate/export_test.go
- overlord/servicestate/quota_handlers.go
- overlord/servicestate/quota_handlers_test.go
instead remember that the non-idempotent updates were done and which
snaps need restarting, so to behave correctly if there is a reboot
or (more unlikely) just a snapd restart
see changed comments for more details
> o/servicestate: stop setting DoneStatus prematurely for quota-control

- testutil/jsonchecker.go
- testutil/jsonchecker_test.go
This is useful when comparing more complex structure from external packages,
when the structures may have unexported fields that would otherwise be picked up
by check.DeepEquals.
This becomes more useful when doing `c.Check(m, testutil.JsonEquals, &boot.Modeenv{ ... })`, which doesn't work with DeepEquals and moddenv that was read from the disk.
> testutil: introduce a checker which compares the type after having passed them through a JSON marshaller

- overlord/snapstate/autorefresh_gating_test.go
- overlord/snapstate/snapstate.go
The special case for populating affectedSnapInfo for the snap that gets refreshed and may want to control his own refresh (hold itself) wasn't correct and didn't fill affectingSnaps. As a result, the gate-auto-refresh hook of such snap didn't have affecting-snaps set correctly and --hold or --proceed wouldn't update hold state for itself.
> o/snapstate: fix populating of affectedSnapInfo.AffectingSnaps for marking self as affecting

- cmd/snap/cmd_debug_state.go
- cmd/snap/cmd_debug_state_test.go
Prevent slow convergence where the wait graphs might have an exponential number of paths (or very unlikely cycles).in waitChainSearch with snap debug state --change=... state.json command by avoiding visiting same halt task.
> cmd/snap: prevent cycles in waitChainSearch with snap debug state

- interfaces/builtin/ssh_keys.go
- tests/main/interfaces-ssh-keys/task.yaml
Since the 8.4p1 version of the openssh package, the vendor config files were
moved to /usr/etc/ssh.
> tests/main/interfaces-ssh-keys: tweak checks for openSUSE Tumbleweed

- overlord/assertstate/assertstate.go
- overlord/assertstate/assertstate_test.go
- overlord/devicestate/devicestate_systems_test.go
- overlord/devicestate/handlers_systems.go
- overlord/devicestate/systems_test.go
- overlord/managers_test.go
During a remodel, the model assertion isn't added to the DB until the very last stage of the process, however when a recovery system is being assembled, the seedwriter pulls the model assertion from the database. Because of this we need to use a temporary database that is stacked on top of the main one in this process.
> overlord/devicestate, overlord/assertstate: use a temporary DB when creating recovery systems

- tests/lib/store.sh
The make_snap_installable_with_id() was not actually copying the snap
binary into the fake store archive, because that's a step performed by
the new_snap_declaration() function, which was not invoked here.
By using that function we ensure that the snap binaries are made
available to the store. It also automatically acks the assertions.
For consistency, we also use new_snap_revision(), which apart from the
extra "ack" on the assertion is equivalent to the previous
implementation.
> tests/lib/store.sh: fix make_snap_installable_with_id()

- overlord/ifacestate/handlers.go
- overlord/ifacestate/handlers_test.go
Following #10461, avoid visiting same halt task in waitChainSearch helper in ifacestate to avoid slow convergence where the wait graphs might have an exponential number of paths (or very unlikely cycles).
> o/ifacestate: do not visit same halt tasks in waitChainSearch to avoid cycles

- client/quota.go
- client/quota_test.go
- cmd/snap/cmd_quota.go
- cmd/snap/cmd_quota_test.go
- daemon/api_quotas.go
- daemon/api_quotas_test.go
- daemon/export_api_quotas_test.go
- overlord/servicestate/quota_control.go
- overlord/servicestate/quota_control_test.go
- overlord/servicestate/quota_handlers_test.go
- overlord/servicestate/servicemgr.go
- tests/main/snap-quota-groups/task.yaml
The exported methods from the servicestate package all return tasksets now, 
which is expected to be put into changes that are executed by the overlord 
loop. This involves changes in many parts that use quotas, such as the tests,
where a new mock function to create a quota group in state without running any
servicectl commands as well as changes to the client side.
>  many: use changes + tasks for quota group operations

- overlord/snapstate/autorefresh_gating_test.go
- overlord/snapstate/snapstate.go
Fix check-rerefresh task summary as it was missing the list of snaps to re-refresh. Also fix verifyPhasedAutorefreshTasks test checks to ensure correct number of tasks is expected; if expected > actual tasks it wouldn't report excessive tasks, so due to copy-paste error for the test data one of the tests expected more tasks than it should.
> o/snapstate: fix check-rerefresh task summary when refresh control is used

- overlord/servicestate/export_test.go
- overlord/servicestate/quota_control.go
- overlord/servicestate/quota_control_test.go
- overlord/servicestate/quota_handlers.go
- overlord/servicestate/servicemgr.go
This is done for the involved snaps plugging into the snapstate mechanisms.
And for quota themselves introducing a new servicestate.CheckQuotaChangeConflictMany.
TODO: we need to surface the new error properly over the API.
> o/servicestate: detect conflicts for quota group operations

- boot/export_test.go
- boot/seal.go
- seed/seedtest/seedtest.go
Tweak test helpers to enable better testing. The seedtest change specifically allows creating seeds when the model has already been created and signed, as in the case of testing the remodel in managers suite.
> boot, seed/seedtest: tweak test helpers

- tests/lib/store.sh
This reverts commit 69fe30426bc737c46b2e995a84f0617cd135887c.
We don't want to ack the assertions when building the image simply because we
don't need to as we are only building an image at that point to put the
assertions into the image, and we actually use/ack the assertions at runtime
inside the VM.
See https://paste.ubuntu.com/p/Dcfqhy2vwK/ for an example failure that this
commit caused.
As mentioned in https://github.com/snapcore/snapd/pull/10470#issuecomment-874322823, we can refactor this
function if need be to make other tests easier by acking and perhaps make the 
nested tests that need to not ack the assertions use an option/flag to prevent
this function from ack'ing the assertions, but let's do that as a follow-up to unblock
other "run nested" PR's which are currently failing …
> tests/lib/store.sh: revert #10470

- boot/modeenv.go
- boot/systems.go
- boot/systems_test.go
- overlord/devicestate/devicestate_systems_test.go
When we create a try system, its model may not match the expected measurements done during boot and thus will prevent unsealing the data and the tried system will be marked as failed.
Based on #10477 with some helpers from #10469, the relevant commit is https://github.com/snapcore/snapd/commit/8d22ebeaf8b2f1c4740d7035088615b7917502c9
~~Marking as blocked at least until #10477 lands~~
> boot: properly handle tried system model

- tests/nested/manual/preseed/task.yaml
The core images may be shipping core20 only by now, but the
test-postgres-system-usernames snap that we use in the test requires core18
base. Make sure that the required base snap is present in the seed.
> tests/nested/manual/preseed: fix for cloud images that ship without core18

- tests/main/refresh-delta-from-core/task.yaml
- tests/main/refresh-delta/task.yaml
This will unblock our tests.
I will open a PR that re-enables the test so that we can monitor the progress of the store team.
> tests: disable delta download tests for now until the store is fixed

- cmd/libsnap-confine-private/cgroup-support-test.c
- cmd/libsnap-confine-private/cgroup-support.c
Similarly to #10485 be more resilient in case of ENOENT when traversing the group hierarchy tree.
Also, tweak the getline handling as indicated by @alexmurray in #10436.
> cmd/libsnap-confine-private: do not fail on ENOENT, better getline error handling

- asserts/extkeypairmgr.go
- asserts/extkeypairmgr_test.go
- asserts/gpgkeypairmgr.go
- asserts/gpgkeypairmgr_test.go
- cmd/snap/cmd_export_key.go
- cmd/snap/cmd_keys.go
- cmd/snap/cmd_sign.go
- cmd/snap/cmd_sign_build.go
- cmd/snap/complete.go
- cmd/snap/export_test.go
- cmd/snap/keymgr.go
- cmd/snap/keymgr_test.go
This is done by centralizing keypair manager creation and a common KeypairManager interface.
> c/snap,asserts: start supporting ExternalKeypairManager in the snap key-related commands

- .github/workflows/test.yaml
- spread.yaml
- tests/lib/pkgdb.sh
- tests/main/desktop-portal-filechooser/task.yaml
- tests/main/desktop-portal-open-file/task.yaml
- tests/main/desktop-portal-open-uri/task.yaml
- tests/main/desktop-portal-screenshot/task.yaml
- tests/main/preseed-lxd/task.yaml
Changes to support running spread tests in ubuntu-18.04-32 system
The idea is then to remove ubuntu-16.04-32 in a following PR
> tests: run spread tests in ubuntu bionic 32bits

- sandbox/cgroup/export_test.go
- sandbox/cgroup/freezer.go
- sandbox/cgroup/freezer_test.go
The groups that we walk through may be going away at any time. Try to be more
robust in such scenarios.
> sandbox/cgroup: do not be so eager to fail when paths do not exist

- spread.yaml
The idea of this pr is to reduce the amount of logs printed for the
nested tests:
1. The serial logs are being printed twice, so remove that from the
suite debug section
2. The journal-log for the nested service is almost the same the serial
log contains. So the idea is to just print the serial log.
> tests: print serial log just once for nested tests

- tests/core/gadget-kernel-refs-update-pc/task.yaml
- tests/core/gadget-update-pc/task.yaml
- tests/lib/nested.sh
- tests/lib/store.sh
Restore the default behaviour of acking the newly created assertions by
default, but add a --noack option to prevent this from happening. Use
this option in the nested tests.
> tests: ack assertions by default, add --noack option

- testutil/jsonchecker_test.go
Thanks to @anonymouse64 for spotting this
> testutil: fix typo in json checker unit tests

- interfaces/builtin/block_devices.go
Without this line:
cat /sys/block/mmcblk0/device/date
results in this denial:
/sys/devices/platform/soc/3f202000.mmc/mmc_host/mmc0/mmc0:aaaa/date
See: https://forum.snapcraft.io/t/interface-for-read-info-about-sd-card/25202
After adding the line in the commit to my snap apparmor file it works:
root@srly-r7d8mg4oj4eo0go:/home/pi# sudo apparmor_parser -r /var/lib/snapd/apparmor/profiles/snap.screenly-client.submit-report 
Warning from /var/lib/snapd/apparmor/profiles/snap.screenly-client.submit-report (/var/lib/snapd/apparmor/profiles/snap.screenly-client.submit-report line 1297): Character # was quoted unnecessarily, dropped preceding quote ('\') character
root@srly-r7d8mg4oj4eo0go:/home/pi# snap run --shell screenly-client.submit-report
root@srly-r7d8mg4oj4eo0go:/home/pi# cat …
> interface: allows reading sd cards internal info from `block-devices` interface

- tests/lib/snaps/store/test-snapd-refresh-control-provider.v3/build-aux/snap/snapcraft.yaml
- tests/lib/snaps/store/test-snapd-refresh-control-provider.v3/meta/snap.yaml
- tests/main/auto-refresh-gating/task.yaml
Test the case where gate-auto-refresh hook errors out, resulting in hold, and for case where the hook does nothing (resulting in normal refresh). It adds a 3rd version of the test snap to test new scenarios (the snap has been uploaded to the store).
> tests: test for gate-auto-refresh hook error resulting in hold

- client/errors.go
- client/quota.go
- client/quota_test.go
- daemon/api_quotas.go
- daemon/api_quotas_test.go
- daemon/errors.go
- tests/main/snap-quota/task.yaml
Use a more proper error kind for quota conflicts, supporting the error type
*servicestate.QuotaChangeConflictError inside errToResponse and indicating what
sort of change the conflict is being used for.
Also update the unit tests for the daemon error response to check for this.
> daemon/api_quotas.go: handle conflicts, returning conflict response

- overlord/snapstate/autorefresh.go
Remove unused refreshSchedule argument for isRefreshHeld helper.
> o/snapstate: remove unused refreshSchedule argument for isRefreshHeld helper

- tests/main/system-usernames-microk8s/task.yaml
This test fails on centos 7 thusly:
```
Error: 2021-07-07 14:10:59 Error executing google:centos-7-64:tests/main/system-usernames-microk8s (jul071354-110681) :
-----
+ echo 'Try to install a snap which is not entitled to use the microk8s user'
Try to install a snap which is not entitled to use the microk8s user
++ snap install test-microk8s-username
++ true
+ OUT='error: cannot perform the following tasks:
- Mount snap "test-microk8s-username" (1) (snap "test-microk8s-username" system usernames require a snapd built against libseccomp >= 2.4)'
+ MATCH 'snap "test-microk8s-username" is not allowed to use the system user "snap_microk8s"'
+ echo 'error: cannot perform the following tasks:
- Mount snap "test-microk8s-username" (1) (snap "test-microk8s-username" system usernames require a …
```
> tests/main/system-usernames-microk8s: disable on centos 7 too

- asserts/extkeypairmgr.go
- asserts/extkeypairmgr_test.go
- cmd/snap/cmd_create_key.go
- cmd/snap/cmd_delete_key.go
- cmd/snap/cmd_delete_key_test.go
- cmd/snap/export_test.go
- cmd/snap/keymgr.go
- cmd/snap/keymgr_test.go
at least initially we don't support using snap commands to create/delete
keys under an external keypair manager, organize things such that though
we can produce appropriate error messages and we can implement
supporting this later if required
> c/snap,asserts: create/delete-key external keypair manager interaction 

- tests/main/snap-user-service-socket-activation/task.yaml
The test is failing when we executed twice in a row:
> spread -repeat 2 -debug
google:ubuntu-20.04-64:tests/main/test-snapd-user-service-sockets
The idea is to remove the snap before the user session is restore so the
socket is properly clean.
> tests: fix test-snapd-user-service-sockets test removing snap

- httputil/client.go
- httputil/transport.go
- store/store_download_test.go
It appears that ResponseHeaderTimeout needs to be set explicitly, no headers response from the server doesn't seem to be covered by any other timeout. 
This should fix the download getting stuck issue.
For more context, see the stacktrace obtained from a system where download got stuck: https://pastebin.canonical.com/p/nZkRMTBbv3/
(the affected goroutine seems to be sitting inside for-select loop of  /usr/lib/go-1.10/src/net/http/transport.go:2033)
(to play with it comment out `ResponseHeaderTimeout: ...` from transport.go and modify test timeout from 5 * time.Second to a huge value and it should be stuck)
> store: set ResponseHeaderTimeout on the default transport

- tests/bin/any-python
- tests/lib/pkgdb.sh
- tests/lib/tools/README
- tests/lib/tools/memory-observe-do
- tests/lib/tools/mountinfo.query
- tests/lib/tools/retry
- tests/lib/tools/suite/tests.session/task.yaml
- tests/lib/tools/user-state
- tests/lib/tools/version-compare
Python 3 should be available everywhere at this point. Try dropping the wrapper.
> tests: drop any-python wrapper

- gadget/install/install.go
- gadget/install/install_dummy.go
- gadget/install/install_test.go
- overlord/devicestate/devicestate_install_mode_test.go
- overlord/devicestate/export_test.go
- overlord/devicestate/handlers_install.go
- tests/lib/uc20-create-partitions/main.go
This provides some nested measurements during the install task to see how long the individual steps take.
Probably only useful with https://github.com/snapcore/snapd/pull/10513
> install: add a bunch of nested timings

- asserts/pool.go
- asserts/pool_test.go
- overlord/assertstate/assertstate.go
- overlord/assertstate/assertstate_test.go
- overlord/assertstate/bulk.go
Refresh validation sets in enforcing mode and check for conflicts before committing them to asserts db.
> o/assertstate: check for conflicts when refreshing and commiting validation set asserts

- tests/core/snapd-refresh-vs-services-reboots/task.yaml
- tests/core/snapd-refresh-vs-services/task.yaml
- tests/lib/reset.sh
This workaround for the tests/core/refresh-vs-services tests should be done
globally for all tests, since other tests may have the same problem of reusing
multiple unasserted revisions of the same snap but with different content in
the second (or later) revisions of the snap.
> tests/lib/reset.sh: add workaround from refresh-vs-services tests for all tests

- tests/nested/manual/cloud-init-never-used-not-vuln/task.yaml
- tests/nested/manual/cloud-init-nocloud-not-vuln/task.yaml
- tests/nested/manual/core20-gadget-cloud-conf/task.yaml
- tests/nested/manual/grade-signed-cloud-init-testkeys/task.yaml
Use snapd 2.45 as the baseline snapd version in the image that we build for the
refresh case, since this test variant is about old devices that were built 
before the fix was merged. 
Additionally, fix the environment variables which were subtly wrong (missing 
the _SNAPD_), and also replace the nested_is_core_16_system with the equivalent
os.query call.
Finally, fix the cloud-init journal check to actually fail if we don't see the
message after 60 seconds, and check for the right message (which is lower-case)
This should be thought of as a pre-requisite for https://github.com/snapcore/snapd/pull/10409, since
it fixes the tests which were causing some issues in the review there so that they are
in the right shape on master before we merge that PR, and can better reason about the
changes …
> tests/nested/cloud-init-{never-used,nocloud}-not-vuln: fix tests, use 2.45

- store/download_test.go
- store/export_test.go
- store/store.go
- store/store_action.go
- store/store_download.go
- store/store_download_test.go
Prefer using xdelta3 from the system snap if it is available and we are able to
run the config subcommand successfully. This ensures that we try to use a known
good xdelta3 command which should always work with what the store sends down,
but does still offer the fallback of using xdelta3 from the host system if for
some reason the xdelta3 command from the system snap becomes broken at some
point. In that case, attempt using the xdelta3 command from the host system,
performing the same config check before assuming that it is usable.
This has the effect that on older systems like Centos 7 and Amazon Linux 2,
where for example xdelta3 from the distro does not support LZMA, when a delta
generated using LZMA is encountered, we will first try the system snap provided
xdelta3 which should …
> store/store_download.go: use system snap provided xdelta3 priority + fallback

- tests/lib/reset.sh
This was actually not even parsing correctly, since each word in every line is
what we would loop over, not each line. Shell scripts, much like boulders, are
hard.
This is needed to make the snapd-failover, snapd-refresh-vs-services and 
snapd-refresh-vs-services-reboots tests more robust.
> tests/lib/reset.sh: fix removing disabled snaps

- interfaces/builtin/gpio.go
- interfaces/builtin/gpio_test.go
- interfaces/builtin/pwm.go
- interfaces/builtin/pwm_test.go
- interfaces/naming.go
- interfaces/naming_test.go
- interfaces/systemd/backend.go
- interfaces/systemd/backend_test.go
- interfaces/systemd/spec.go
- interfaces/systemd/spec_test.go
this is somewhat simpler for the callers and more consistent because
the systemd backend needs to control the naming pattern to allow
update/removal anyway
also produce slightly more informative clashing def internal errors
> interfaces: make the service naming entirely internal to systemd BE

- overlord/assertstate/assertstate.go
- overlord/assertstate/validation_set_tracking.go
- overlord/assertstate/validation_set_tracking_test.go
- overlord/snapstate/storehelpers.go
Implement a helper for getting ValidationSets object for all currently tracked validation sets in Enforce mode.
> o/assertstate: Implement EnforcedValidationSets helper

- cmd/snap/cmd_model.go
- cmd/snap/cmd_model_test.go
The snaps header is only shown in verbose, while the storage-safety header is
shown in all modes when not empty.
To be honest, I'm not super satisfied with the modes header indention/formatting,
I tried a few different ways and I couldn't decide what looks best, so opinions 
welcome on this critical subject of how much whitespace to put in the output.
> cmd/snap/model: support storage-safety and snaps headers too

- interfaces/builtin/modem_manager.go
The mbim-proxy daemon is started by the ModemManager service.
The modem's app which wants to send MBIM messages will
connect to the mbim-proxy daemon via the unix socket.
The mbim-proxy daemon uses the the abstract socket path
"mbim-proxy". The modem-manager interface needs a
corresponding update. This provides that update.
References:
https://bugs.launchpad.net/austin/+bug/1936374
This is really just https://github.com/snapcore/snapd/pull/10543/files squashed and commited with `--author " Jerry Lee <jerry.lee@canonical.com>"` so that the CLA checker is happy.
> interface/modem-manager: add support for MBIM/QMI proxy clients

- tests/main/services-install-hook-can-run-svcs/task.yaml
- tests/main/services-install-hook-can-run-svcs/test-snapd-install-hook-runs-svc/meta/hooks/install.in
This test currently fails on master.
> tests/main/services-install-hook-can-run-svcs: add variant w/o --enable

- overlord/servicestate/service_control.go
- overlord/servicestate/service_control_test.go
- overlord/servicestate/servicestate.go
- wrappers/services.go
Use snap app names for ExplicitServices of ServiceAction. This keeps it consistent with existing Service field.
> o/servicestate: use snap app names for ExplicitServices of ServiceAction

- tests/lib/reset.sh
This is to prevent errors installing snaps with daemons for test users
like the following example.
/home/gopath/src/github.com/snapcore/snapd/tests/lib/tools/snaps-state
install-local test-snapd-user-service
error: cannot perform the following tasks:
- Make snap "test-snapd-user-service" (unset) available to the system
(Post http://0/v1/service-control: dial unix
/run/user/0/snapd-session-agent.socket: connect: connection refused)
This happens when snap the test does "set system
experimental.user-daemons=true"
To reproduce the error run:
google:ubuntu-20.04-64:tests/main/cgroup-tracking:root
google:ubuntu-20.04-64:tests/main/snap-services
> tests: force snapd-session-agent.socket to be re-generated

- tests/main/services-install-hook-can-run-svcs/task.yaml
Thanks to Samuele for pointing this out, it is much more clear in spread
output:
google: ubuntu-core-16-64:tests/main/services-install-hook-can-run-svcs:enableflag
google: ubuntu-core-16-64:tests/main/services-install-hook-can-run-svcs:noflag
> tests/main/services-install-hook-can-run-svcs: make variants more obvious

- tests/main/lxd-mount-units/task.yaml
- tests/main/lxd-no-fuse/task.yaml
- tests/main/lxd-postrm-purge/task.yaml
- tests/main/lxd-services-smoke/task.yaml
- tests/main/lxd-snapfuse/task.yaml
- tests/main/lxd-try/task.yaml
- tests/main/lxd/task.yaml
- tests/main/selinux-lxd/task.yaml
This is a temporal, at some point it should be automatically removed
when lxd is uninstalled.
The explanation about this service is:
"The snap.lxd.workaround.service unit is needed by lxd to avoid systemd
wiping the cgroups when snapd disables all the lxd units during refresh
Effectively an empty unit with Delegate=yes which snapd doesn't know
about and so won't be disabled during refresh"
This is to prevent the spread error on postrm-purge test
+ systemctl --no-legend --full
+ grep -E 'snap\..*\.(service|timer|socket)'
snap.lxd.workaround.service                                                                  loaded active exited    /bin/true                                                                    
+ echo 'found unexpected leftovers'
found unexpected leftovers
+ exit 1
-----
> tests/many: remove lxd systemd unit to prevent unexpected leftovers

- cmd/snap/cmd_login.go
We mention the "snap buy" feature in our "snap login" output. We
currently do not support "buy" so it's best to remove this from
our docs.
> snap: change `snap login --help` to not mention "buy"

- overlord/devicestate/devicestate_install_mode_test.go
- overlord/devicestate/handlers_install.go
- sysconfig/cloudinit.go
- sysconfig/cloudinit_test.go
- sysconfig/gadget_defaults_test.go
- sysconfig/sysconfig.go
Move more responsibility of handling cloud-init config permission handling to
sysconfig instead of devicestate since we now have access to the model in
ConfigureTargetSystem which we can use to get the model grade.
This also means we can refactor the functions which install cloud-init config
to be more straight forward and readable.
This is the first of a few PR's, it makes other PR's simpler and easier to review 
if I do this refactor first.
> o/devicestate, sysconfig: refactor cloud-init config permission handling

- .github/workflows/test.yaml
We should run gofmt for 1.13 unit test jobs.
> github: enable gofmt for Go 1.13 jobs

- cmd/libsnap-confine-private/test-utils.c
With https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1967 the
g_spawn_check_exit_status call is flagged as deprecated now. This also broke in
F35 mass rebuild in Rawhide:
```
make[1]: Leaving directory '/builddir/build/BUILD/snapd-2.51/cmd'
libsnap-confine-private/test-utils.c: In function 'rm_rf_tmp':
libsnap-confine-private/test-utils.c:63:9: error: 'g_spawn_check_exit_status' is deprecated: Use 'g_spawn_check_wait_status' instead [-Werror=deprecated-declarations]
63 |         g_assert_true(g_spawn_check_exit_status(exit_status, NULL));
|         ^~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/glib.h:81,
from libsnap-confine-private/test-utils.c:24:
/usr/include/glib-2.0/glib/gspawn.h:280:10: note: declared here
280 | gboolean g_spawn_check_exit_status (gint …
```
> cmd/libsnap-confine-private: g_spawn_check_exit_status is deprecated since glib 2.69

- tests/main/nfs-support/task.yaml
Using udp protocol on mount for ubuntu 20.04, 21.04 and 21.10 is not
supported anymore.
+ mount -t nfs localhost:/home /home -o nfsvers=3,proto=udp
mount.nfs: an incorrect mount option was specified
The test nfs-support is skipping those systems
> tests: skip udp protocol on latest ubuntus

- cmd/snap-confine/udev-support.c
Refactor the handling of device cgroup to facilitate adding v2 support.
The PR contains pieces of #10540, specifically the refactor of per assigned udev_device handling.
> cmd/snap-confine: refactor device cgroup handling to enable easier v2 integration

- asserts/snapasserts/validation_sets.go
- asserts/snapasserts/validation_sets_test.go
Implement CheckPresenceInvalid and CheckPresenceRequired methods for ValidationSets. They are going to be used in enforcing mode for install, refresh and remove.
> asserts/snapasserts: CheckPresenceInvalid and CheckPresenceRequired methods

- snap/squashfs/squashfs.go
- snap/squashfs/squashfs_test.go
Arch recently landed an update of squahfs-tools to 4.5 which broke our code. The
main difference is that the output of unsquahfs stdout does not contain the
header we expected. For instance:
```
google:ubuntu-20.04-64 .../mini/hello# unsquashfs -n -dest . -ll /root/foo.snap
Parallel unsquashfs: Using 1 processor
5 inodes (1 blocks) to write
drwx------ root/root                55 2021-07-27 11:31 .
-rw-r--r-- root/root                 0 2021-07-27 11:31 ./data.bin
drwxr-xr-x root/root                27 2021-07-27 11:31 ./food
drwxr-xr-x root/root                27 2021-07-27 11:31 ./food/bard
drwxr-xr-x root/root                 3 2021-07-27 11:31 ./food/bard/bazd
drwxr-xr-x root/root                45 2021-07-27 11:31 ./meta
drwxr-xr-x root/root                58 2021-07-27 11:31 …
```
> snap/squashfs: handle squashfs-tools 4.5+

- tests/main/snapd-snap/task.yaml
The snapd snap does not yet specify a base, so it is no longer buildable with
snapcraft 5.x, which drops support for baseless and base: core snaps.
Instead, use 4.x channel of snapcraft which does still support this scenario.
> tests/main/snapd-snap: install 4.x snapcraft to build the snapd snap

- interfaces/builtin/desktop.go
This is intended to help support colour scheme customisations for GTK apps on KDE desktops.
KDE tries to make GTK apps follow the user's chosen colour scheme by writing a `~/.config/gtk-3.0/colors.css` file that defines a number of symbolic colour names that are referenced by the Breeze-gtk theme (a theme they provide that matches their Qt theme). It also creates or updates `~/.config/gtk-3.0/gtk.css` to include the `colors.css` file. We want snapped applications to have read access for these CSS files.
In addition to this snapd change, the Snapcraft gnome-* extensions will require changes to symlink these CSS files into the snap's private `$HOME`. More details can be found here:
https://forum.snapcraft.io/t/very-ugly-cursor-for-spotify-and-kde-snaps/17118/31?u=jamesh
> interfaces/builtin: allow access to per-user GTK CSS overrides

- tests/lib/nested.sh
I see that sometimes the uc20 nested tests fail because of a disconnection
with the remote vm. The problem seems to be a race because the snpad
snap is installed while the tools are being prepared.
To fix that the idea is to prepare the tools after we check snap command
is ready.
error in test:
2021-07-30T02:21:20.4738952Z Warning: Permanently added
'[localhost]:8022' (ECDSA) to the list of known hosts.
2021-07-30T02:21:20.4740233Z
PATH=/writable/test-tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
2021-07-30T02:21:20.4741638Z Warning: Permanently added
'[localhost]:8022' (ECDSA) to the list of known hosts.
2021-07-30T02:21:20.4742645Z Connection to localhost closed by remote
host.
2021-07-30T02:21:20.4743582Z -----
vm journal log: …
> tests: update nested wait for snapd command

- overlord/snapstate/autorefresh_gating.go
- overlord/snapstate/autorefresh_gating_test.go
- overlord/snapstate/export_test.go
- overlord/snapstate/snapstate.go
Some changes to preapare affectedByRefresh for reusing when called from hookstate:
- Change affectedByRefresh implementation to consider the snap being updated as affecting itself instead of adding self-dependency explicitly (externally by the caller).
- Make affectedSnapInfo exported
- Pass current snap infos rather than upcoming updates infos to affectedByRefresh.
The hookstate will use another helper instead of calling affectedByRefresh directly, therefore it's not exported.
> o/snapstate: affectedByRefresh tweaks

- packaging/debian-sid/rules
- packaging/ubuntu-16.04/rules
For go-1.13 we need to ensure that we have a GOCACHE directory set.
If this is not set then the HOME directory is used. But in an sbuild
environment this is set to /sbuild-nonexistent so the build fails.
The reason we see this on 18.04 now is that we switched to the new
go-1.13 there but the dh-golang tooling is still assuming the 18.04
go-1.10.
This commit fixes this by setting one global GOCACHE.
See https://launchpad.net/~snappy-dev/+archive/ubuntu/edge/+packages?field.name_filter=&field.status_filter=published&field.series_filter=bionic for the build failures.
> packaging: fix build failure on bionic and simplify rules

- interfaces/builtin/tee.go
- interfaces/builtin/tee_test.go
Add support for /dev/qseecom device node, equivalent of /dev/tee on Qualcomm SoC
> interfaces/tee: add support for Qualcomm qseecom device node

- overlord/configstate/config/transaction.go
- overlord/configstate/configcore/timezone.go
- overlord/configstate/configcore/timezone_test.go
- tests/core/snap-set-core-config/task.yaml
This commit uses the new virtual configuration mechanism to make
the `snap get core system.timezone` output look at the system
setting instead of at what is stored in the state. It also adds
a test that ensures that writing the timezone will not store it
in the state.
> configcore: register virtual config for timezone reading

- overlord/snapstate/autorefresh_gating.go
- overlord/snapstate/autorefresh_gating_test.go
Add AffectedByRefreshCandidates helper for use from hookstate. Having the helper avoids exporting of snapstate.refreshCandidate (there is a simplified version of refreshCandidate in hookstate, for gating hook only).
> o/snapstate: add AffectedByRefreshCandidates helper

- spread.yaml
This is needed to make test snapd-snap:lxd pass in 21.10
The test is currently failing due to out of space after hte test was
moved to snapcraft v4
> tests: use bigger storage on ubuntu 21.10

- secboot/encrypt_sb.go
- secboot/encrypt_sb_test.go
- secboot/export_sb_test.go
- vendor/vendor.json
This commit moves our secboot code to the `snapshot-4c814e1` branch
that contains fixes around the KDF benchmarking. This will improve
the install performance.
> vendor: move to snapshot-4c814e1 branch and set fixed KDF options

- overlord/devicestate/firstboot.go
- overlord/devicestate/firstboot20_test.go
- overlord/snapstate/backend.go
- overlord/snapstate/backend/setup.go
- overlord/snapstate/backend/setup_test.go
- overlord/snapstate/backend_test.go
- overlord/snapstate/flags.go
- overlord/snapstate/handlers.go
When seeding the device we currently extract the kernel. This is
unneeded because the kernel is already in place (without it the
system would not have been booted). Either ubuntu-image or "install"
mode extracted the kernel into the right place already.
This commit changes the code to skip kernel extraction when seeding.
This is an alternative and kind of complementary way to #10594. We
probably want to make the low-level bits also a bit more robust but this
high level approach is hopefully simpler.
> {device,snap}state: skip kernel extraction in seeding

- packaging/arch/PKGBUILD
- packaging/debian-sid/changelog
- packaging/fedora/snapd.spec
- packaging/opensuse/snapd.changes
- packaging/opensuse/snapd.spec
- packaging/ubuntu-14.04/changelog
- packaging/ubuntu-16.04/changelog
So that edge core snap builds have the right version number.
> packaging: merge 2.51.4 changelog back to master

- .github/workflows/test.yaml
5.x doesn't support the snapd snap as currently supported, so we need to build
with 4.x for the time being.
> .github/workflows/test.yaml: use snapcraft 4.x to build the snapd snap

- overlord/configstate/configcore/backlight.go
- overlord/configstate/configcore/journal.go
- overlord/configstate/configcore/network.go
- overlord/configstate/configcore/timezone.go
It looks like there was some copy/paste in the error handling
of the coreCfg() calls and an incorrect error handling is
used in some of the handle* functions.
This commit fixes this.
> configcore: fix a bunch of incorrect error returns

- overlord/configstate/configcore/timezone.go
It looks like there was some copy/paste in the error handling
of the coreCfg() calls and an incorrect error handling is
used in some of the handle* functions.
This commit fixes this.
> configcore: fix early config timezone handling

- wrappers/services.go
The `startSnapServices()` measurements are currently missing a
good chunk of where the time is spend. Here is an example from
the `test-snapd-service` snap:
```
39545  Done         4125ms            -  Start snap "test-snapd-service" (2) services
^                     5ms            -    start service "snap.test-snapd-service.test-snapd-sigterm-all-service.service"
^                     5ms            -    start service "snap.test-snapd-service.test-snapd-service.service"
^                     6ms            -    start service "snap.test-snapd-service.test-snapd-service-refuses-to-stop.service"
^                     6ms            -    start service "snap.test-snapd-service.test-snapd-endure-service.service"
^                    18ms            -    start service …
```
> wrappers: measure time to enable services in StartServices()

- .gitignore
- cmd/snap/cmd_set.go
- cmd/snap/cmd_set_test.go
- overlord/hookstate/ctlcmd/set.go
- overlord/hookstate/ctlcmd/set_test.go
Adds two flags, `-s` and `-t`, to enable strict processing of the `snap/snapctl set` arguments as string and JSON, respectively. When using `-s`, the argument will be taken as is and when using `-t`, the argument will be parsed as JSON (and fail if it's invalid). The default behavior remains the same, snap/snapctl will try to parse the argument as JSON and, if that fails, fallback to handling it as a string. .
Note: the .gitignore commit is already in PR #10584 (I was waiting for that to be merged to open this, but I'll just rebase this PR once that merges)
> c/snap,o/hookstate/ctlcmd: add JSON/string strict processing flags to snap/snapctl

- sysconfig/cloudinit.go
- sysconfig/cloudinit_test.go
- sysconfig/export_test.go
In a future commit, we will use the result of measuring the datasource settings
for the cloud-init config from the gadget, but for now just introduce the
machinery to read it.
> sysconfig/cloudinit.go: measure (but don't use) gadget cloud-init datasource

- tests/nested/manual/core-early-config/task.yaml
The execute_remove is not used anymore, it was replaced by tests.nested
> tests: fix core-early-config test to use tests.nested tool

- .clang-format
Configure clang-format such that include blocks (groups of #include separated by
newlines) are preserved. This will prevent clang-format from reordering includes
in a silly way, for instance moving config.h to a place where it breaks the
build as _GNU_SOURCE is no longer defined early enough.
See https://clang.llvm.org/docs/ClangFormatStyleOptions.html for details on the
option used.
> clang-format: stop breaking my includes

- overlord/assertstate/assertstate.go
- overlord/assertstate/assertstate_test.go
Implement ValidationSetAssertionForEnforce helper for obtaining validation set when handling 'snap validate --enforce ...'.
ValidationSetAssertionForEnforce updates all currently tracked validation set assertions, obtains assertion for the requested validation set and then checks if the existing and new validation do not conflict and are valid for the installed snaps.
> o/assertstate: implement ValidationSetAssertionForEnforce helper

- overlord/devicestate/devicestate_install_mode_test.go
- overlord/devicestate/handlers_install.go
- tests/lib/nested.sh
- tests/lib/store.sh
- tests/nested/manual/core20-install-device-file-install-via-hook-hack/defaults.yaml
- tests/nested/manual/core20-install-device-file-install-via-hook-hack/install-device
- tests/nested/manual/core20-install-device-file-install-via-hook-hack/pc-snap-decl-extras.json
- tests/nested/manual/core20-install-device-file-install-via-hook-hack/prepare-device
- tests/nested/manual/core20-install-device-file-install-via-hook-hack/snap-yaml-extras.yaml
- tests/nested/manual/core20-install-device-file-install-via-hook-hack/task.yaml
For UC20 install mode, we have devices which need to install files into the run
mode system before rebooting into install mode. The temporary solution designed
for this was to use the install-device hook with system-files providing write
access to the /run/mnt/ubuntu-data/system-data/_writable_defaults/... directory
where ubuntu-data is mounted during install mode. That seemed to work fine in
devmode, but the issue in strict mode is that system-files only grants
permissions to create that specific file, it doesn't grant permission to create
any of the parent directories the file lives in.
So, temporarily for this device to be released and shipped, create those
directories at the end of the setup-run-system task, which runs before the
install-device hook, thus ensuring that the hook is …
>  o/devicestate/handlers_install.go: add workaround to create dirs for install

- cmd/libsnap-confine-private/cgroup-support-test.c
- cmd/libsnap-confine-private/cleanup-funcs-test.c
- cmd/libsnap-confine-private/feature-test.c
- cmd/libsnap-confine-private/mount-opt-test.c
The latest coverity scan has identified issues like this:
```
*** CID 1506495:  Error handling issues  (CHECKED_RETURN)
/libsnap-confine-private/feature-test.c: 73 in
...
>>>     CID 1506495:  Error handling issues  (CHECKED_RETURN)
>>>     Calling "g_file_set_contents(pname, "", -1L, NULL)" without checking return value. This library function may fail and return an error code.
73      g_file_set_contents(pname, "", -1, NULL);
```
which is a pattern we use commonly in the test code.
Also, the glib developer manual states that g_assert_true/g_assert_false should be over g_assert() in test code. See: https://docs.gtk.org/glib/func.assert_true.html
> cmd/libsnap-confine-private: fix coverity issues in tests, tweak uses of g_assert()

- overlord/snapstate/snapstate.go
In my PR that landed yesterday I accidentally left out some commented out code (it was moved around a few lines up/down, then I forgot to remove it).
> o/snapstate: remove commented out code

- interfaces/builtin/raw_usb.go
Commit ac28b0a437a7b251b107aac3549d40f71848e0c3 introduced a typo in the allowed
path, it should be /sys/devices/platform/scb instead of ../sbc, even though the
actual commit message references the correct path.
While at it, on raspberry Pi 3 the usb hub appears right under the soc platform
device, eg.: /sys/devices/platform/soc/3f980000.usb, while on Pi 4, there is a
PCIe controller under the SCB device, eg:
/sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.4/idVendor
See https://forum.snapcraft.io/t/openhab-3-0-no-access-to-z-wave-usb-stick/26044
for additional details.
> interfaces/builtin/raw_usb: fix platform typo, fix access to usb devices accessible through platform

- build-aux/snap/snapcraft.yaml
Broken out from #10559 thanks to Ian for spotting this.
> build-aux: build with go-1.13 in the snapcraft build too

- packaging/arch/PKGBUILD
- packaging/debian-sid/changelog
- packaging/fedora/snapd.spec
- packaging/opensuse/snapd.changes
- packaging/opensuse/snapd.spec
- packaging/ubuntu-14.04/changelog
- packaging/ubuntu-16.04/changelog
Changelog for 2.51.5 to prevent the edge core builds from rolling back in version number to 2.51.4.
> packaging: changelog for 2.51.5 to master

- client/apps.go
- cmd/snap/cmd_services.go
- cmd/snap/cmd_services_test.go
Sets the default timezone for the 'snap logs' command to the local timezone. Adds an --abs-time flag to display the timestamps in UTC.
https://bugs.launchpad.net/snapd/+bug/1934686
> cmd/snap: print logs in local timezone

- cmd/libsnap-confine-private/cgroup-freezer-support.c
- cmd/libsnap-confine-private/cgroup-support-test.c
- cmd/libsnap-confine-private/classic-test.c
- cmd/libsnap-confine-private/cleanup-funcs-test.c
Another batch of fixes, mostly trivial ones. Commit https://github.com/snapcore/snapd/commit/3d356a183241677c10ec11723150348012db0dcf is potentially interesting as we seem to have had a bug in handling of processes that go away when the cgroup v1 freezer was checked for being occupied by processes. The problem wasn't a big deal as it only executed if the base snap was changed while an application was already running. Since the processes can die at any time while we are listing the contents of cgroup.procs, we did a special check to verify that the process in question still exists. In this scenario, we would have incorrectly identified the base snap as being in use.
> cmd/libsnap-confine-private: fix issues identified by coverity

- overlord/hookstate/ctlcmd/export_test.go
- overlord/hookstate/ctlcmd/refresh.go
- overlord/hookstate/ctlcmd/refresh_test.go
Allow snapctl refresh --proceed outside of hooks.
> o/hookstate: allow snapctl refresh --proceed from snaps

- daemon/api_snaps.go
- daemon/api_snaps_test.go
- overlord/snapstate/handlers.go
- overlord/snapstate/snapstate.go
- overlord/snapstate/snapstate_install_test.go
- overlord/snapstate/storehelpers.go
Handle IgnoreValidation flag on snap install; followup to #10544.
TODO: installInfo function. Once wired up, snapstate test can be updated to verify the flag is passed with snap actions to the store.
> daemon, o/snapstate: handle IgnoreValidation flag on install (2/3)

- spread.yaml
It appears that /home/ubuntu/.ssh is owned by root:root. Apply a temporary fix
until the images are updated.
@sergiocazzolato is this something we can fix in our image build process?
> spread: temporarily fix the ownership of /home/ubuntu/.ssh on 21.10

- tests/core/create-user-2/task.yaml
- tests/core/create-user/task.yaml
In case the create-user-2 test fails and the user was not installed, then we need to
check the user was created before removing it, otherwise the restore phase fails and the machine is discarded. 
When this happens with external backend the whole execution is lost because of that error.
> tests: remove the test user just when it was installed on create-user-2 test

- secboot/encrypt_sb.go
- secboot/encrypt_sb_test.go
The main encryption key is high entropy 256bit already so there is
no need to use a strong KDF on top of this. There was a PR already
that switched this to 32MB but it turns out that 32KB is enough.
> secboot: switch main key KDF memory cost to 32KB

- packaging/arch/PKGBUILD
- packaging/debian-sid/changelog
- packaging/fedora/snapd.spec
- packaging/opensuse/snapd.changes
- packaging/opensuse/snapd.spec
- packaging/ubuntu-14.04/changelog
- packaging/ubuntu-16.04/changelog
Mainly for consistency in the view of the release versions for 2.52 when it comes time to cut this release.
> packaging: merge 2.51.6 changelog back to 2.52

- packaging/arch/PKGBUILD
- packaging/debian-sid/changelog
- packaging/fedora/snapd.spec
- packaging/opensuse/snapd.changes
- packaging/opensuse/snapd.spec
- packaging/ubuntu-14.04/changelog
- packaging/ubuntu-16.04/changelog
To prevent the core snap edge build versions from getting out of sync.
> packaging: merge 2.51.6 changelog back to master

- packaging/debian-sid/rules
- packaging/ubuntu-14.04/rules
- packaging/ubuntu-16.04/rules
In the (very) old days before spread we ran our testsuite in the
autopkgtest infrastructure. This had many problems and when spread
came along we used that and never looked back.
The code to run the tests in autopkgtest is still in place [1] and
this commit removes it now as it is unlikely we ever us this
again (and if so we can always revert this commit).
This is broken out from the code that moves to `go modules`.
[1] In debian/rules because autopkgtest really only can deal with
debian packages.
> packaging: remove TEST_GITHUB_AUTOPKGTEST support

- tests/main/interfaces-firewall-control/task.yaml
In case the service is not active, the restore fails to stop the service and the machine is discarded.
In case the restore fails when using the external backend, the whole run is lost.
> tests: stop the service when is active in test interfaces-firewall-control test

- secboot/secboot_tpm.go
Remove duplicate import, and use existing/long-standing snapcore
secboot import called sb.
Fixes: 37fc0edcdc866f05b5cd458c6dd056ec4e3ae57c
> secboot: remove duplicate import

- .github/workflows/test.yaml
This now works, so we should be able to start getting coverage again.
I enabled coverage for all variants of the unit tests, it's unclear to me if we want coverage to be reported for the withbootassets and the nosecboot tags or not, I seem to recall things were slow if we enabled that, but maybe it's worth the slowness?
> .github/workflows: add codedov again

- tests/main/security-dev-input-event-denied/task.yaml
The test is failing with the following error:
+ udevadm settle
+ echo 'Then the snap is still not able to access an evdev keyboard'
Then the snap is still not able to access an evdev keyboard
+ test-snapd-event -event-kbd
+ echo 'Expected permission error calling evtest with connected joystick
plug'
Expected permission error calling evtest with connected joystick plug
+ exit 1
The idea of the fix is to retry the check because sometimes it takes a
bit of time to start denying access.
> tests: fix timing issue on security-dev-input-event-denied test

- tests/main/services-refresh-mode/task.yaml
The change contains 2 fixes:
1. The timeout has been increased due to on some pi3 it is giving kill-timeout. Just the remove takes like 3 minutes.
2. The files checked are wrong, bot cat are giving "No such file or directory"
> tests: fix services-refresh-mode test

- interfaces/builtin/u2f_devices.go
- interfaces/builtin/u2f_devices_test.go
This adds the Nitrokey FIDO2 to the list of supported U2F devices.
See also this Launchpad bug: https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1940467
And this thread on the Snapcraft forum: https://forum.snapcraft.io/t/nitrokey-fido2-does-not-work-with-chromium-snap/26098
I am, however, not sure how to add the line `TAG=="snap_chromium_chromium", RUN+="/usr/lib/snapd/snap-device-helper $env{ACTION} snap_chromium_chromium $devpath $major:$minor"`, which is also required to make this key actually work.
> interfaces/u2f-devices: add Nitrokey FIDO2

- tests/main/services-install-hook-can-run-svcs/task.yaml
Shellcheck complains:
```
ERROR:root:tests/main/services-install-hook-can-run-svcs/task.yaml: section 'execute':
In - line 5:
sed ./test-snapd-install-hook-runs-svc/meta/hooks/install.in -e s/%%FLAGS%%/$FLAGS/ > ./test-snapd-install-hook-runs-svc/meta/hooks/install
^----^ SC2086: Double quote to prevent globbing and word splitting.
Did you mean:
sed ./test-snapd-install-hook-runs-svc/meta/hooks/install.in -e s/%%FLAGS%%/"$FLAGS"/ > ./test-snapd-install-hook-runs-svc/meta/hooks/install
For more information:
https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...
ERROR:root:validation failed for the following files:
- tests/main/services-install-hook-can-run-svcs/task.yaml
```
> tests/main/services-install-hook-can-run-svcs: shellcheck issue fix

- .github/workflows/test.yaml
When the test run was restored from cache, do not try to upload coverage
> github: do not try to upload coverage when working with cached run

- i18n/xgettext-go/main.go
- i18n/xgettext-go/main_test.go
The update-pot script was failing because escaped double quotes in raw strings were being escaped again resulting in \\" which would escape the slash and not the quote breaking the output. This changes the processing to keep escaped double quotes as they are and only escape standalone quotes.
> i18n/xgettext-go: preserve already escaped quotes

- .github/workflows/test.yaml
This should make coverage work for Pull requests, because we need to trigger the unit tests (but probably _just_ the unit tests) to run on pushes to master.
Alternatively, if this is considered too much work / time for running CI, we could switch to a schedule based run where we run the unit-tests job on a schedule like nightly or every 6 hours or something, but this seems deceptively easy.
Also I am deliberately not adding the "skip-spread" label here so we can see that spread jobs do still run for PRs, and then after this is merged we should confirm that the github actions workflow that is triggered _only_ runs the unit-tests job and not the snap-builds, spread or spread-nested jobs
> .github/workflows/test.yaml: test github.events key

- tests/main/services-refresh-mode/task.yaml
- tests/main/services-snapctl/task.yaml
- tests/main/services-stop-mode-sigkill/task.yaml
- tests/main/services-stop-mode/task.yaml
- tests/main/snap-service/task.yaml
- tests/main/snap-user-service-restart-on-upgrade/task.yaml
- tests/main/snap-user-service-socket-activation/task.yaml
- tests/main/snap-user-service-start-on-install/task.yaml
- tests/main/snap-user-service-upgrade-failure/task.yaml
- tests/main/snap-user-service/task.yaml
- tests/main/snap-wait/task.yaml
Some of these tests are failing on pi2 and pi3 in the lab with kill
timeout.
Some boards are getting slow and the idea is to move from 5m to 10m to
avoid those issues.
The affected tests are the ones that run on ubuntu core.
The test services-refresh-mode initially was in 5 minutes, then moved to 12 but when tested with 10m it works fine.
> tests: set to 10 minutes the kill timeout for tests failing on slow boards

- cmd/libsnap-confine-private/cgroup-support.c
- cmd/libsnap-confine-private/utils.c
- cmd/libsnap-confine-private/utils.h
Allow to hide the cgroup v2 warning by passing any value to `SNAPD_HIDE_CGROUPV2_WARNING`.
This warning to stderr makes systemd autopkgtests (and probably many others) fail and it would be handy if we could somehow disable it.
> cgroup-support: allow to hide cgroupv2 warning via ENV

- sysconfig/cloudinit.go
- sysconfig/cloudinit_test.go
- sysconfig/export_test.go
This will filter out the config we allow on ubuntu-seed to a subset of
cloud-init configuration.
Currently, this just allows configuration as required by MAAS to setup a device
with cloud-init, but this could be expanded in the future.
Next and final PR (hopefully) for cloud-init MAAS support is https://github.com/snapcore/snapd/pull/10573 to see the context of how this is put together.
> sysconfig/cloudinit.go: add functions for filtering cloud-init config

- store/details_v2.go
- store/details_v2_test.go
Our code did not deal with the `assumes:` field in the raw yaml
that we get from the store. This lead to the really nasty bug
that on a refresh the assumes is not checked correctly, see
https://bugs.launchpad.net/snapd/+bug/1940553
A bigger manager test is included in the followup for this.
> store: deal correctly with "assumes" from the store raw yaml

- overlord/hookstate/hooks_test.go
- overlord/snapstate/autorefresh_gating.go
- overlord/snapstate/autorefresh_gating_test.go
Don't hold some snaps if not all snaps can be held by the given gating snap.
> o/snapstate: don't hold some snaps if not all snaps can be held by the given gating snap

- .github/workflows/test.yaml
We want the spread tests to also run on pushes to release/** branches, so the
operator here should just be || otherwise these jobs will not run on pushes.
Thanks to Alberto for pointing this out to me.
Furthermore, we don't want to run the snap-builds job on anything other than
pull requests, since we already have Launchpad snap build recipes setup for the
release and master branches and this would just be duplicating that effort and
use up artifact storage space.
Also cleanup an unused setting that I had commented out as I wasn't sure if it 
would be necessary or not, but I can see now that it's not necessary.
Again, I'm deliberately not adding the skip spread label so we can see the actions 
run here just in case I have mucked things up again.
> .github/workflows/test.yaml: fix logic

- overlord/hookstate/ctlcmd/ctlcmd.go
- overlord/hookstate/ctlcmd/ctlcmd_test.go
- tests/main/snapctl/task.yaml
Fixes the error message returned by snapctl when running a command that requires root without root and with a flag (like `--disable`). When a command should be blocked from running due to not running as root, we were adding a ForbiddenCommand to the parser which would then just return an error when running. However, if called with a flag, the parser would fail because the ForbiddenCommand didn't have any flag fields. The fix changes this so that no command is added, instead we fail immediately  and deal with the "-h", "--help" case manually. 
https://bugs.launchpad.net/snapd/+bug/1893970
> o/hookstate/ctlcmd: correct err message if missing root

- overlord/snapstate/snapstate.go
- overlord/snapstate/snapstate_remove_test.go
Fails `snap remove` without removing any snap, if any of the specified snaps does not exist.
https://bugs.launchpad.net/snapd/+bug/1842203
> o/snapstate: fail remove with invalid snap names

- daemon/api_snaps.go
- daemon/api_snaps_test.go
- daemon/export_test.go
- overlord/assertstate/assertstate.go
- overlord/assertstate/assertstate_test.go
- overlord/assertstate/bulk.go
- overlord/managers_test.go
When making requests to the snap store, some refresh requests with the 'fetch assertion' action were missing the "Snap-Refresh-Reason: scheduled" header. This was due to an unset RefreshOption when the assertions were auto refreshed. This PR sets the RefreshOptions when calling the store to make the refresh request.
https://bugs.launchpad.net/snapd/+bug/1937309
> o/assertstate: fix missing 'scheduled' header when auto refreshing assertions

- daemon/api.go
- daemon/api_snaps.go
- daemon/api_snaps_test.go
- daemon/export_test.go
- overlord/assertstate/assertstate.go
- overlord/assertstate/assertstate_test.go
Refresh validation set assertions together with snap declarations (on snap update atm, will be expanded to install and remove in another PR) with new asserstate.RefreshAssertions helper.
> o/assertstate,daemon: refresh validation sets assertions with snap declarations

- tests/lib/snaps/store/test-snapd-refresh-control.v1/bin/pending
- tests/lib/snaps/store/test-snapd-refresh-control.v1/bin/proceed
- tests/lib/snaps/store/test-snapd-refresh-control.v1/build-aux/snap/snapcraft.yaml
- tests/lib/snaps/store/test-snapd-refresh-control.v2/bin/pending
- tests/lib/snaps/store/test-snapd-refresh-control.v2/bin/proceed
- tests/lib/snaps/store/test-snapd-refresh-control.v2/build-aux/snap/snapcraft.yaml
- tests/main/auto-refresh-gating-from-snap/task.yaml
Spread test for snapctl refresh --pending and --proceed from the snap
Based on #10528 and #10626.
> tests: spread test for snapctl refresh --pending/--proceed from the snap

- cmd/snap-bootstrap/initramfs_systemd_mount.go
- cmd/snap-bootstrap/initramfs_systemd_mount_test.go
- cmd/snap/cmd_run.go
- cmd/snap/cmd_run_test.go
- run-checks
- tests/lib/fakestore/store/store_test.go
gofmt was only running on paths ending with "snapd/[A-Za-z0-9_]+$".
This was done to avoid running gofmt on root dirs and again in their
subdirs (since gofmt already does that) but would also exclude paths
that don't have a package in the dir directly below snapd, like snap/cmd.
snapd/cmd/snap (has a pkg) would be excluded and snapd/cmd isn't listed
by 'go list' (doesn't have a pkg) so it wasn't gofmt'ed.
This fix is simply runs gofmt on all dirs since the performance
impact was negligible (in my local tests).
Edit: oh, I also removed the `-l` when invoking gofmt because, since we already
use `-d`, I didn't see the need for it but please correct me if I'm wrong.
> many: fix run-checks gofmt check 

- overlord/managers_test.go
Use host-scaled timeout to avoid riscv64 failure (as seen here for 2.51.1 - https://launchpadlibrarian.net/556133108/buildlog_ubuntu-focal-riscv64.snapd_2.51.1+20.04_BUILDING.txt.gz)
We use host-scaled timeout for other settle ops in this test suite and it gives 6 * 45 second timeout on riscv64, so this makes it consistent with the rest.
> tests: use host-scaled timeout to avoid riscv64 test failure

- wrappers/binaries_test.go
- wrappers/services_test.go
We have a bunch of duplicated key in our snap.yaml that we use in
tests. This is not allowed with the yaml spec but `yaml.v2` is
leaniant about it. It becomes a problem with `yaml.v3` because
that errors for duplicated keys. Hence this first commit to fix some
obvious duplication. There will be more :)
> wrappers: fix a bunch of duplicated service definitions in tests

- spread.yaml
Update qemu spread machines to have 21.10 and remove no longer
needed 20.10.
> spread: add 21.10 to qemu, remove 20.10 (EOL)

- spread.yaml
Sometimes a test fails due to lack of disk space:
2021-09-01T07:22:47.7421902Z Failed to create snap, snap command failed:
2021-09-01T07:22:47.7422575Z stdout:
2021-09-01T07:22:47.7422907Z
2021-09-01T07:22:47.7423352Z stderr:
2021-09-01T07:22:47.7424089Z error: cannot pack "/root/prime":
mksquashfs call failed:
2021-09-01T07:22:47.7425146Z -----
2021-09-01T07:22:47.7426088Z Write failed because No space left on
device
....
2021-09-01T07:22:49.8110021Z 2021-09-01 07:22:49 Debug output for
google:ubuntu-16.04-64:tests/main/snapd-snap:lxd (sep010658-426075) :
> tests: add more space on ubuntu xenial

- tests/lib/preseed.sh
Bump the number of retries when waiting for /deb/nbd0p1, for some reason it is much slower on 21.10 and preseed/preseed-reset tests tend to fail because of this.
> tests: bump the number of retries when waiting for /dev/nbd0p1

- tests/main/interfaces-libvirt/task.yaml
This test was moved to run on `20.04` but there are at least two
problems:
1. The `libvirtd` group got renamed to `libvirt`
2. The <kernel>test_ping_serve.virtio</kernel> errors when it
comes from a read-only medium like a snap
To unblock us short term this commit just reverts back to 16.04 to
unbreak master and then we can work on a proper fix.
> tests: move interfaces-libvirt test back to 16.04

- interfaces/builtin/snap_refresh_control.go
Small tweak suggested by Ian to the just landed snap-refresh-control interface.
> interfaces: no need for snapRefreshControlInterface struct

- overlord/hookstate/hookstate_test.go
This should help avoid another riscv64 build failure. I'm setting it to 15s (which is multiplied by 6 on riscv) instead of 45 as was in managers test, hopefully this will be enough.
> tests: use host-scaled settle timeout for hookstate tests

- interfaces/builtin/network_control.go
This should allow an access of the form:
AVC apparmor="DENIED" operation="open" profile="snap.name.app" name=/sys/devices/platform/soc@0/30800000.bus/30be0000.ethernet/net/eth0/address pid=18219 comm="vgc-bc" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> interfaces/network-control: additional ethernet rule

- overlord/snapshotstate/snapshotstate_test.go
- overlord/snapstate/handlers_download_test.go
- overlord/snapstate/handlers_prereq_test.go
- overlord/snapstate/snapstate.go
- overlord/snapstate/snapstate_remove_test.go
- overlord/snapstate/snapstate_test.go
Enforce validation sets in enforcing mode when removing snaps - do not allow removing snaps snaps that are required.
Open question about removing a snap at specific revision that I covered with a dedicated error handling, but I think this scenario won't be possible when we disallow disabling snaps if they are required (or switching to a different revision when a specific rev is required) - if we prevent those, then remove will bail out early as it rejects removal of active snap revision.
> o/snapstate: enforce validation sets assertions when removing snaps

- tests/nested/core/extra-snaps-assertions/task.yaml
Since switching to Bionic in cc6266051b6f98797fdce6ec04fc4b84ec7ee36c the test
was broken as it expected a different pattern.
> tests/nested/core/extra-snaps-assertions: fix the match pattern

- overlord/snapstate/backend/mountunit_test.go
- systemd/systemd.go
Add a helper to allow injecting a mock Systemd implementation.
The mount backend tests are rewritten to use this new feature, as an example.
The benefit is that we'll have fewer dependencies in the tests, and fewer things to adapt when we change the implementation of the systemd methods (systemctl calls in particular).
The previous attempt at something similar was in https://github.com/snapcore/snapd/pull/10704
> systemd: add mock systemd helper

- codecov.yml
Apply a mapping, as documented in [1], to allow codecov to resolve the
filenames into valid paths inside our git repository. This will allow us
to see the coverage data for individual source files.
[1]: https://codecov.freshdesk.com/support/solutions/articles/43000593943-files-not-showing-in-codecov-fixing-paths-
> codecov: fix files pathnames

- strutil/intersection.go
- strutil/intersection_test.go
This treats input slices as sets and computes the intersection of those sets.
We need this for cloud-init where we have to take a 3-way intersection of slice
lists.
Split out from https://github.com/snapcore/snapd/pull/10573
> strutil: add Intersection()

- tests/nested/manual/refresh-revert-fundamentals/task.yaml
Commit a7657b5b10e7bfc38991918d33467d659d05fe4b seems to have broken the test,
which went unnoticed until there happened to be leaking a set -u from one of the
sourced files which triggered this error:
```
+ echo 'Check the new version of the snaps is correct after the system reboot'
Check the new version of the snaps is correct after the system reboot
+ tests.nested exec 'snap list core20'
+ MATCH '^core20.*1113.*latest/edge.*'
Warning: Permanently added '[localhost]:8022' (ECDSA) to the list of known hosts.
+ echo 'Check the change is completed'
Check the change is completed
+ case "$SNAP" in
/bin/bash: line 121: REVERT_ID: unbound variable
-----
```
Signed-off-by: Maciej Borzecki <maciej.zenon.borzecki@canonical.com>
Have you signed the …
> tests/nested/manual/refresh-revert-fundamentals: fix variable use

- overlord/ifacestate/handlers.go
- overlord/ifacestate/ifacestate_test.go
When the setup of security profiles in InterfaceManager.doConnect()
fails the code needs to remove the already made `repository`
connection. Otherwise any subsequent attempt to connect an interface
will trigger snapd to try to connect failing connection again
until snapd is restarted.
This was discovered as part of PR#10580.
> ifacestate: undo repository connection if doConnect fails

- overlord/ifacestate/ifacestate_test.go
The #10728 PR landed after we merged unused arguments cleanups and caused some
conflicts with current master.
Fixes:
```
Running vet
vet: overlord/ifacestate/ifacestate_test.go:8842:15: cannot use c (variable of type *check.C) as interfaces.Interface value in argument to s.mockIfaces: missing method AutoConnect
```
> overlord/ifacestate: fix arguments in unit tests

- overlord/overlord_test.go
Temporary workaround to unblock riscv64 builds.
> tests: skip overlord tests on riscv64 due to timeouts.

- packaging/debian-sid/rules
- packaging/debian-sid/snapd.install
The `snapd.apparmor.service` was not needed in debian because
it used a version of apparmor that would do the snapd apparmor
profile loading for us. However this support was dropped with
apparmor 3 and when it entered unstable this broke snapd.
This commit ensures it is shipped on debian too.
> packaging: ship the `snapd.apparmor.service` unit in debian

- spread.yaml
- tests/nested/manual/core20-install-device-file-install-via-hook-hack/task.yaml
This is to avoid the error
systemd-run --collect --unit fakedevicesvc fakedevicesvc localhost:11029
Failed to start transient service unit: Unit fakedevicesvc.service
already exists.
The the following tests were executed in order:
google-nested:ubuntu-20.04-64:tests/nested/manual/core20-install-device-file-install-via-hook-hack
google-nested:ubuntu-20.04-64:tests/nested/manual/grade-signed-above-testkeys-boot:secured
> tests: fix fakedevicesvc service already exists

- build-aux/snap/snapcraft.yaml
Investigating LP: #1943077 revealed that libc has been loading
libgcc_s.so.1 from the host forever, which apparently we have been
getting away with but no longer works on impish.
> build-aux: stage libgcc1 library into snapd snap

- overlord/hookstate/ctlcmd/refresh.go
- overlord/hookstate/ctlcmd/refresh_test.go
- tests/lib/snaps/store/test-snapd-refresh-control.v1/build-aux/snap/snapcraft.yaml
- tests/lib/snaps/store/test-snapd-refresh-control.v2/build-aux/snap/snapcraft.yaml
- tests/main/auto-refresh-gating-from-snap/task.yaml
Require snap-refresh-control interface for `snapctl refresh --proceed` from snaps. The test snaps in the store have been updated with the new definitions including this interface.
> o/hookstate: require snap-refresh-control interface for snapctl refresh --proceed

- interfaces/builtin/block_devices.go
This enables the control for the path of block devices that can be removed or
recovered after setting the state of running, so it would be safer to
take block devices to be offline state instead of unplugging the
physical devices.
> interfaces/block-devices: support to access the state of block devices

- image/image_linux.go
- image/image_test.go
This is how it shows up in ubuntu-image today:
WARNING: proceeding to download snaps ignoring validations, this default will change in the future. For now use --validation=enforce for validations to be taken into account, pass instead --validation=ignore to preserve current behavior going forwardWARNING: "pc-kernel", "pc" installed from local snaps disconnected from a store cannot be refreshed subsequently!
Copying "snapd-upstream.snap" (snapd)
Copying "pc-kernel.snap" (pc-kernel)
Copying "core20-upstream.snap" (core20)
Copying "pc-gadget.snap" (pc)
There should be a newline so it appears like
WARNING: proceeding to download snaps ignoring validations, this default will change in the future. For now use --validation=enforce for validations to be taken into account, pass instead …
> image/image_linux.go: add newline

- tests/lib/nested.sh
This is needed for testing ubuntu-seed MAAS config on UC20 nested tests, where
we need to add multiple / many files to a UC20 image file before booting it.
Also don't check cloud-init if the VM is not using cloud-init.
Broken out from https://github.com/snapcore/snapd/pull/10573
See the spread test in https://github.com/snapcore/snapd/pull/10573 for an example of how this is used.
> tests/lib/nested.sh: split out additional helper for adding files to VM imgs

- tests/lib/prepare.sh
The idea of this change is to have cached the snaps in the system so
then it is faster to install new snaps which depends on either core18 or
core20
> tests: pre-cache snaps in classic and core systems

- overlord/hookstate/ctlcmd/services_test.go
- overlord/snapstate/snapstate_install_test.go
- overlord/snapstate/storehelpers.go
Enforce validation sets on snap install (single snap). This mostly means:
- checking that the requested snap doesn't have presence:invalid in any validation set
- requesting specific snap revision if the snap is required at the specific revision (open question: this may not be a viable real use case since it won't be possible to enable the validation set without having snap already installed?)
- passing respective validation set keys to store action.
Based on #10678
> o/snapstate: enforce validation sets on snap install

- go.mod
Required by github.com/snapcore/snapd/overlord/configstate/configcore; running go test over master updates it every time (was indirect before).
> go: update go.mod dependencies

- dirs/dirs.go
- overlord/managers_test.go
- overlord/snapstate/backend.go
- overlord/snapstate/backend/mountunit.go
- overlord/snapstate/backend/mountunit_test.go
- overlord/snapstate/backend_test.go
- overlord/snapstate/handlers.go
- overlord/snapstate/snapstate_remove_test.go
- overlord/snapstate/snapstate_test.go
- systemd/emulation.go
- systemd/systemd.go
- systemd/systemd_test.go
- systemd/systemdtest/systemdtest.go
This includes the changes in systemd, overlord and wrappers to create, list and remove mount unit files.
> mount-control: step 1

- tests/lib/prepare.sh
Also handle the case where BASE_CHANNEL != IMAGE_CHANNEL, since this will
confuse spread at runtime when the base snap is updated and the system is
rebooted.
This is a re-implementation of the code in #10708 without the hard-coding of beta
since that's not needed anymore.
> tests/lib/prepare.sh: download core20 for UC20 runs via BASE_CHANNEL

- overlord/snapstate/autorefresh_gating_test.go
- overlord/snapstate/handlers.go
Update the list of snaps stored on conditional-auto-refresh task when we know what snaps are going to be refreshed. This avoids unnecessary conflicts on snaps that are held and won't get refreshed (for more context see the end of autoRefreshPhase1() function where "snaps" map is originally stored on the task, and conditionalAutoRefreshAffectedSnaps() helper that affects conflict check based on "snaps").
> o/snapstate: optimize conflicts around snaps stored on conditional-auto-refresh task

- overlord/hookstate/ctlcmd/refresh.go
- overlord/hookstate/ctlcmd/refresh_test.go
Implement snapctl refresh --show-lock command for showing current value of refresh inhibit lock.
> o/hookstate/ctlcmd: Implement snapctl refresh --show-lock command

- daemon/api_quotas_test.go
- overlord/configstate/configcore/journal.go
- overlord/configstate/configcore/vitality_test.go
- overlord/managers_test.go
- overlord/servicestate/quota_control.go
- overlord/servicestate/quota_control_test.go
- overlord/servicestate/quota_handlers_test.go
- systemd/systemd.go
- systemd/systemd_test.go
- tests/main/snap-quota/task.yaml
- usersession/userd/privileged_desktop_launcher.go
Allow the systemd.Version() method to be mocked, and add a new AtLeast() method, as per the TODO.
> systemd: add AtLeast() method, add mocking in systemdtest

- bootloader/assets/generate.go
- go.mod
- go.sum
- mkversion.sh
- packaging/debian-sid/rules
- packaging/ubuntu-14.04/rules
- packaging/ubuntu-16.04/rules
- strutil/version.go
- tests/lib/prepare-restore.sh
- update-pot
Use a new network namespace without any interfaces and routing while building
the packages to ensure that we are not reaching out to remote services.
> packaging, tests/lib/prepare-restore: build packages without network access, fix building debs with go modules

- overlord/servicestate/export_test.go
- overlord/servicestate/servicestate.go
- overlord/servicestate/servicestate_test.go
If no services have been explicitly given, we are unable to tell what
services will be effectively restarted.
See also:
https://bugs.launchpad.net/snapd/+bug/1803212/comments/9
> o/servicestate: Update task summary for restart action

- interfaces/builtin/microstack_support_test.go
Some distros such as openSUSE or Fedora use /usr/libexec. Fix unit tests to
behave correctly if one runs them on such system.
> interfaces/builtin: fix microstack unit tests on distros using /usr/libexec

- tests/main/snapd-state/task.yaml
Weird things can happen at midnight:
https://pastebin.ubuntu.com/p/mmQskRXvhM/
The test could fail because it attempts to match the times by their date
component, without taking into account that if the two measurements
happen with the midnight in between, the date component will be
different.
Here we attempt to be a bit more robust, by comparing the given date not
only against the current date, but also against the date we had a few
minutes ago.
> tests: be more robust against a new day stepping in

- tests/main/quota-groups-systemd-accounting/task.yaml
The quota-groups-systemd-accounting test has been seen failing on Arch
with these logs:
https://paste.ubuntu.com/p/YB5xpM5FYR/
While it's not totally clear why the OOM was triggered (there don't
appear to be any processes inside the control group), the test does
indeed create a couple of control groups with a ridiculously low amount
of memory, and one theory about this failure is that the systemd process
itself got momentarily assigned to the group.
In any case, the test is not interested in checking whether an OOM
occurred or not, so we do not want to trigger a failure if it happened.
> tests: increase memory quota in quota-groups-systemd-accounting

- cmd/libsnap-confine-private/cgroup-support.c
- sandbox/forcedevmode.go
- sandbox/forcedevmode_test.go
- tests/main/document-portal-activation/task.yaml
- tests/main/snapctl-is-connected/task.yaml
- tests/smoke/install/task.yaml
Now that we have cgroup v2 support in master, we can drop the warnings and forced devmode.
> cmd/libsnap-confine-private, tests, sandbox: remove warnings about cgroup v2, drop forced devmode

- packaging/ubuntu-14.04/rules
- packaging/ubuntu-16.04/rules
We already invoke dh_auto_build with GO111MODULE support on, pass the flag to
test too.
Ideally we should make the sbuild test run on systems other than Debian Sid too.
> packaging/ubuntu: pass GO111MODULE to dh_auto_test

- cmd/Makefile.am
The gdb helper shims execute inside the snap mount namespace, but may come from
the snapd package on the host, or have otherwise been built on the host system.
In order to avoid dependency on a specific version of glibc on the host, build
both binaries statically.
> cmd: build gdb shims as static binaries

- store/export_test.go
- store/store.go
- store/store_action_test.go
Following previous revelation from #10518 I wanted to double-check that the Timeout we set in store's http client works, so added a test similar to that from #10518 (and yes it works 😅 )
> tests: add test for store.SnapAction() request timeout

- tests/lib/pkgdb.sh
- tests/main/snap-confine-drops-sys-admin/task.yaml
- tests/main/snap-confine-privs/task.yaml
- tests/regression/lp-1812973/Makefile
21.10 uses glibc 2.34 while all our base snaps use and older version, thus binaries built on 21.10 host will not work properly in the mount ns of snaps using those bases.
> tests: fix tests for 21.10

- store/store_action_test.go
PR #10785 was merged prematurely, there was a real unit test failure caused by small change in error message between the go version I've locally and the one we use, causing:
FAIL: store_action_test.go:3191: storeActionSuite.TestSnapActionTimeout
store_action_test.go:3225:
c.Assert(err, ErrorMatches, `Post http://127.0.0.1:.*/v2/snaps/refresh: net/http: request canceled \(Client.Timeout exceeded while awaiting headers\)`)
... error string = "Post \"http://127.0.0.1:38331/v2/snaps/refresh\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
... regex string = "Post http://127.0.0.1:.*/v2/snaps/refresh: net/http: request canceled \\(Client.Timeout exceeded while awaiting headers\\)"
This PR fixes that
> tests: fix regex of TestSnapActionTimeout test

- overlord/devicestate/devicestate.go
- overlord/devicestate/devicestate_remodel_test.go
- overlord/managers_test.go
- overlord/snapstate/autorefresh_gating_test.go
- overlord/snapstate/conflict.go
- overlord/snapstate/devicectx.go
- overlord/snapstate/devicectx_test.go
- overlord/snapstate/snapstate_test.go
- overlord/snapstate/snapstatetest/devicectx.go
This PR adds the change ID to the change conflict error so that an op conflicting with a duplicate op in the same change can just check that the conflict a kind of "self-conflict" and skip.
> o/snapstate: add ChangeID to conflict error

- overlord/devicestate/devicestate_remodel_test.go
There were two changes being created in the mocked Install so the change against which the remodel conflicted was non-deterministic. I changed it to only have one required snap since having multiple didn't seem crucial for the test and it prevents the issue.
> o/devicestate: fix flaky test remodel clash

- .github/workflows/test.yaml
Uploading coverage to codecov fails on occasion. It is not really useful to
block the whole test run because of this.
> github: do not fail when codecov upload fails

- store/store_action_test.go
Looks like there are more changes with go 1.17
> store: one more tweak for the test action timeout

- tests/main/prepare-image-gating/task.yaml
this resolves the TODO in the original PR
> tests: add a local snap variant to testing prepare-image gating support

- tests/nested/manual/core20-install-device-file-install-via-hook-hack/task.yaml
- tests/nested/manual/grade-signed-above-testkeys-boot/task.yaml
- tests/nested/manual/grade-signed-cloud-init-testkeys/task.yaml
There is a race here in waiting for snapd to finish this task, since the
nested tooling will wait for snapd to be seeded, but this task runs immediately
after seeding is done, so we may execute the code before the task is actually
done executing.
> tests/nested/manual: use loop for checking for initialize-system task done

- tests/main/preseed-lxd/task.yaml
- tests/main/preseed/task.yaml
The lxd snap now uses the core20 base snap, so we need to check for that
everywhere.
See the following output from a failing task:
```
Check that the tasks of preseeded snapd have expected statuses
+ MATCH 'Doing .+ mark-preseeded +Mark system pre-seeded'
+ MATCH 'Done .+ prerequisites +Ensure prerequisites for "snapd" are available'
+ MATCH 'Done .+ prepare-snap +Prepare snap "/var/lib/snapd/seed/snaps/snapd.snap'
+ MATCH 'Done .+ mount-snap +Mount snap "snapd" \(unset\)'
+ MATCH 'Done .+ copy-snap-data +Copy snap "snapd" data'
+ MATCH 'Done .+ setup-profiles +Setup snap "snapd" \(unset\) security profiles'
+ MATCH 'Done .+ link-snap +Make snap "snapd" \(unset\) available to the system'
+ MATCH 'Done .+ auto-connect +Automatically connect eligible plugs and slots of snap "snapd"'
+ MATCH …
```
> tests/main/preseed: update for new base snap of the lxd snap

- cmd/snap/main.go
- cmd/snap/main_test.go
- tests/main/i18n/task.yaml
There's been a few reports about a log warning breaking autocomplete and confusing users.  It looks something like: `description of <command>'s "<arg name>" is lowercase in locale "<locale>": "<the translation">`. This PR removes logs caused by  "incorrect" translation during normal operation but keeps the panic when testing/debugging. IMO the warning doesn't reach the intended audience, it's not actionable for the user and it reportedly breaks some functionality (autocomplete) so I think it's better to remove it.
https://bugs.launchpad.net/snapd/+bug/1773174
https://bugs.launchpad.net/snapd/+bug/1808213
https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1932579
> cmd/snap: only log translation warnings in debug/testing

- asserts/snapasserts/validation_sets.go
- asserts/snapasserts/validation_sets_test.go
- overlord/snapstate/snapstate_install_test.go
- overlord/snapstate/snapstate_remove_test.go
Return full validation set keys from CheckPresenceRequired and CheckPresenceInvalid. Full keys including series and sequence are expected by store api.
> asserts, snapstate: return full validation set keys from CheckPresenceRequired and CheckPresenceInvalid

- overlord/snapstate/snapstate_install_test.go
- overlord/snapstate/storehelpers.go
Enforce validation sets when install multiple snaps at once.
> o/snapstate: enforce validation sets/enforce on InstallMany

- .github/workflows/test.yaml
This is necessary to avoid the failure to refresh LXD - the images already have
LXD and so can build the snap, they just can't refresh LXD due to store
outages sometimes, so this new version helps with that when it happens and
keeps out CI moving along to the extent that it can.
> .github/workflows/test.yaml: bump action-build to 1.0.9

- cmd/libsnap-confine-private/device-cgroup-support.c
Tweak the device cgroup setup to use root only when necessary, that is when:
- creating the BPF map & pinning it to the path
- getting BPF map fd from a path
- loading BPF program
Once we obtain handle to the map/program, no further mediation is performed and operations can be carried out after dropping root privs.
> cmd/libsnap-confine-private: use root when necessary for BPF related operations

- overlord/ifacestate/handlers.go
- overlord/ifacestate/ifacestate_test.go
- overlord/state/state_test.go
Do not create stray "Setup snap ... security profiles for auto-connection" task in the state (with no associated change) in batchConnectTasks if there are no connections, just return early. Not sure it's really a bug, maybe a "mild bug" since I think we do have cases where we create tasks in state and error out elsewhere in processing, and never add them to changes which is fine, but it's best to avoid leaving garbage in happy cases where there are no connections to handle.
The task wouldn't be executed and has no impact on snapd ops AFAICT, but is useless/confusing when found in the state (this was noticed while investigating https://bugs.launchpad.net/snapd/+bug/1943686, but not a fix for that bug).
Also added a simple test for state for the behavior of .Tasks() and .TaskCount(), since …
> o/ifacestate: do not create stray task in batchConnectTasks if there are no connections

- overlord/devicestate/devicestate_remodel_test.go
- overlord/devicestate/devicestate_test.go
We occasionally see the TestUC20RemodelSetModelWithReboot fail when running the
test suite runs on Launchpad builder on armhf or s390, but not really on other
architectures. Use a longer timeout as the test seems to be working in general,
but it is suspected that the build host/vm is so slow that settle does not
converge in time.
> overlord/devicestate: make settle wait longer in remodel tests

- data/selinux/snappy.te
- packaging/fedora/snapd.spec
Update the SELinux policy. The bpffs is mounted at /sys/fs/bpf, so we need permissions to list/read /sys. On top of this, there's separate permissions to manipulate files in bpffs, and bpf related capabilities.
> data/selinux: update the policy to allow s-c to manipulate BPF map and programs

- .github/workflows/test.yaml
This reverts commit 5296059c305482ca19d7a26dfeca5d06c8bc7eef.
Now that the v1 tag has been updated to point to 1.0.9, we can go back to 
tracking v1 instead of tracking specifically v1.0.9, which will prevent us from
getting updates in the future if there is i.e. a 1.0.10 or something.
See also: https://github.com/snapcore/action-build/issues/25#issuecomment-922830224
> .github/workflows/test.yaml: revert #10809

- tests/main/snapd-state/task.yaml
Currently the last-refresh time depends on the time when the snapd suite
was prepared, as the state is backed up at that moment and then restored
on each test. So the idea of this change is to increate the time
tolerance to address that.
> tests: update the time tolerance to fix the snapd-state test

- cmd/libsnap-confine-private/device-cgroup-support.c
There's no need to call getpid() here, since we get the PID from the
caller.
> libsnap-confine: use the pid parameter

- daemon/api_validate.go
- overlord/assertstate/assertstate.go
- overlord/assertstate/assertstate_test.go
- overlord/assertstate/bulk.go
- overlord/assertstate/helpers.go
- overlord/snapstate/snapstate.go
- overlord/snapstate/snapstate_test.go
Check installed snaps when refreshing validation set assertions (not just if the assertions conflict), otherwise we may end up in a situation where installed snaps do not meet the requirements of updated assertions.
This also moves InstalledSnaps helper to snapstate.
> o/assertstate: check installed snaps when refreshing validation set assertions

- interfaces/builtin/opengl.go
This was added a long time ago to the NVIDIA mount support in snap-confine, so
we mount it there, but we never added it to the policy allowing it.
See https://forum.snapcraft.io/t/kdenlive-cannot-render-any-projects-stuck-in-waiting/26689/3
> interfaces/builtin/opengl.go: add libOpenGL.so* too

- usersession/client/client.go
Add a method to issue a request to a single usersession agent; besides
making the code more readable, this will come handy in those cases when
we already know the user ID we want to talk to.
Also add a note of warning about using the `doMany()` method carelessly.
> usersession/client: refactor doMany() method

- sysconfig/cloudinit_test.go
The cloud-init filtering writes a bunch of files into /tmp that
are not removed. So avoid cluttering /tmp on the hosts when
unit tests are run this commit sets TMPDIR to the unit test
tmpdir so that it's properly cleaned up.
This brings up a bit of a meta question (which may make the PR obsolete):
Should we write the filtered config into something like `/run/snapd/cloud-init`
to avoid having it in /tmp that may get cleared at random points?
(see `sysconfig/cloudinit.go:filterCloudCfgFile()` and ioutil.TempFile() there).
> sysconfig: set TMPDIR in tests to avoid cluttering the real /tmp

- spread.yaml
This shoudl be regather impossible, but we see mknod failing with EPERM in
prepare of certain tests. As far as I can tell, the kernel should not be
triggering this with devmtmpfs even if the device the node we are creating for
does not exist. Perhaps there is a device cgroup set up for the current session.
> spread: display information about current device cgroup in debug dump

- daemon/daemon_test.go
- overlord/ifacestate/helpers.go
- overlord/ifacestate/ifacestate_test.go
- overlord/snapstate/snapstate.go
- tests/regression/lp-1943853/task.yaml
Fix for https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1943853
Conns that refer to an unknown plug/slot (unknown = not in the repo = newer version of the snap doesn't have it OR we failed to load its info entirely) will not get pruned from the state if either plug or slot snap is in "broken" state.
> o/ifacestate: don't lose connections if snaps are broken

- kernel/fde/fde.go
- kernel/fde/fde_test.go
This method is used to determine if the fde-device-unlock helper is
available.
This is part of the inline-crypt-setup hook support.
If you feel it's too little to review I can push the (messy) WIP branch that implements this all where this is chopped off from.
> fde: add HasDeviceUnlock() helper
